### ISSUE TITLE
how to reply with HTML?

### ISSUE THREAD

**Issue by cho060303** [python-telegram-bot/python-telegram-bot#1000]
how to reply with html? I can't find reply with html in document.

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup). Or (if you can't reach our group) our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot)
