### ISSUE TITLE
Possible to talk to botfather?

### ISSUE THREAD

**Issue by hannpet** [python-telegram-bot/python-telegram-bot#1001]
I wonder if it is possible to talk to @Botfather from my Bot itself? Because the command-list seems not editable in the API but only by contacting "him" directly (as far as I figured)...

**Comment by Eldinnie** [comment]
You are correct. Bot's can not talk to other Bots, nor to @botfather.
Howvever, this is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup). Or (if you can't reach our group) our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot)
