### ISSUE TITLE
Bot API 3.6 features

### ISSUE THREAD

**Issue by Eldinnie** [python-telegram-bot/python-telegram-bot#1005]
Telegram released bot [API v3.6](https://core.telegram.org/bots/api#february-13-2018) 

Adjustments needed to the library:

- [x] Supported text formatting in media captions. (should work out of the box)
- [x] In supergroups, if the bot receives a message that is a reply, it will also receive the message to which that message is replying – even if the original message is inaccessible due to the bot's privacy settings. (should work out of the box)
- [x] Added the new field connected_website to Message. (bool)
- [x] Added the new parameter supports_streaming to the sendVideo method
- [x] Added a field supports_streaming to the inputMediaVideo object.
- [x] Change https://travis-ci.org/python-telegram-bot/python-telegram-bot/jobs/341799350#L1860 to expecting a `BadRequest: Media_caption_too_long` instead of just cutting

**Comment by MrMarble** [comment]
Maybe i'm missing something but when i send media with formatted caption i still see normal text...
Tried with markdown and html but nothing works

**Comment by Eldinnie** [comment]
@MrMarble We've not yet released these new features so unless you're using the master branch this is correct
