### ISSUE TITLE
[FeatureRequest] Bot API 3.6: caption_html and caption_markdown

### ISSUE THREAD

**Issue by blueset** [python-telegram-bot/python-telegram-bot#1010]
As Bot API 3.6 now supports formatting and URL in message captions, it would be useful to have `caption_html`, `caption_html_urled`, `caption_markdown` and `caption_markdown_urled` in `Message` objects that has comparable features to their [`text_` counterparts](https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html#telegram.Message.text_html).

**Comment by Eldinnie** [comment]
I'll start on this
