### ISSUE TITLE
LoadBalancingUpdater - Possibility to have multiple Bots using the same Dispatcher

### ISSUE THREAD

**Issue by JosXa** [python-telegram-bot/python-telegram-bot#1016]
With the Bot API rate limiting, it can be of great value to employ multiple bots in order to balance the user requests between them. The best example of this would be @MasterTagAlertBot, which uses 10 additional bots and redirects users to the other ones if the load on one is too high:

![image](https://user-images.githubusercontent.com/7313176/36512755-13510c54-176c-11e8-8307-dfce6d4db029.png)

It would be nice to have native support for this, as bots built with the library start to exceed the 10k MAU threshold and the flood criteria of Telegram are kind of odd.

Therefore, in a very simple 20-minute prototype hack, I managed to implement a `LoadBalancingUpdater` that takes a list of tokens or bots, and a `BotSelector` instance with an abstract method `select_best_candidate` (`random.choice(available_bots)` per default) which is passed to the job_queue and the dispatcher. Not many changes were required for this, and the added value is great from what I can tell by discussions with @TheGasta (MTABot developer).

Things to consider:
- Responding to updates from the "correct" bot, i.e. the one the user has actually interacted with.
- Border cases of polling and webhooks that I haven't considered so far

Naming for everything is WIP and suggestions are appreciated.

**Comment by wolfsyntax** [comment]
How to handle/get the response from a ForceReply? and can I possibly create a button without ManyBot?

**Comment by Poolitzer** [comment]
I like this idea, but I feel like you let it sound easier to implement then it is :)

**Comment by Bibo-Joshi** [comment]
TBH I'm not a fan of this feature. It's basically some tooling around PTB and needs a high level of customization. E.g. imagine you have a conversation that works in groups but accesses the `user_data` of the participants. So you'd basically have to ensure that all users that may at some point participate in the same conversation use the same bot or find a way to sync the `user_data` across bots (which mayb be doable at some point, but still …)

IMO this is out of scope of PTB.

**Comment by Poolitzer** [comment]
What about ptbcontrib?

**Comment by Bibo-Joshi** [comment]
sure, almost anything goes over there.

**Comment by Bibo-Joshi** [comment]
After internal discussion, we don't see this feature being implemented, at least not in the forseable future. If someone finds this comment and really wants this feature: Feel free to comment or open a new issue that references this one.
