### ISSUE TITLE
dp.add_handler(CallbackQueryHandler...

### ISSUE THREAD

**Issue by testservices** [python-telegram-bot/python-telegram-bot#1023]
I have a callbackquery button, when it clicked this button, I send a message to bot and I wanna to bot answer to this message, I tryed ❇️dp.add_handler(CallbackQueryHandler...❇️ but I didn't undrestand

please help me
thx

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup). Or (if you can't reach our group) our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot)

**Comment by testservices** [comment]
Hello
I want to do some work like this , but it gets errors :
states{....
MY_CALLBACK: [CallbackQueryHandler('call_btn',my_message),
                            ],

....}
Please Help Me ....
THX....

**Comment by tsnoam** [comment]
Repeating what @Eldinnie wrote:

This is not an issue with the library's code, but a usage question. Feel free to ask it in our telegram group. Or (if you can't reach our group) our IRC channel

I'm closing this issue now.
