### ISSUE TITLE
Bot does NOT have a means to check if URL preview is on

### ISSUE THREAD

**Issue by Pauldic** [python-telegram-bot/python-telegram-bot#1025]
When sending a message bot can decide if to enable/disable URL preview. However, when an update containing URL is received, there the library lacks inclusion the disable_web_preview status in the incoming message. 

### Steps to reproduce
1. Send URL message to bot without preview 

2. Repeat the above with preview 

3. Compare the 2 objects to observe they are same

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by tsnoam** [comment]
@Pauldic 
`disable_web_page_preview` is an attribute of sending messages, not when receiving them.
Check the Bot API: https://core.telegram.org/bots/api

If you'd like such support you should contact telegram bot support.
