### ISSUE TITLE
Handler callback revamp

### ISSUE THREAD

**Issue by tsnoam** [python-telegram-bot/python-telegram-bot#1026]
This issue is here to expose to the community a proposed design for the Handlers callback prototype.
We have recently closed/rejected PR #859 in this subject as we preferred to go in a different direction. Here we intend to discuss with the community what will be the chosen design.

**Current situation:**
Minimal callback prototype is `def callback(bot, update)`.
If users require more data/facilities they can initialize the Handler with extra `pass_` (bool) arguments  which mandates the callback to accept more arguments (like `groups`, `args` and others).

Problems:
 * The API is very cumbersome and confusing for new users.
 * Adding/pushing new context data into the callbacks requires code changes from the users.
Lets say that we want the RegexHandler to provide the match object to the callback. With the current design it will be impossible to add that information without changing the callback prototype and (most likely) impose a new `pass_` parameter during Handler initialization.

**Proposed API**
IMPORTANT: This change is non backward compatible. We might implement a backward compatibility layer for a certain period like we have done with other deprecated mechanisms in the past.
 * Deprecate `pass_` arguments when initializing Handlers.
 * Handler callbacks prototype will change to: `def callback(update, ctx)`.
 * The above `ctx` will be a context of all information/facilities that users may need. The context will be a Mixin of various context objects, depending on the Handler.
Examples of such information/facilities:
    * `bot`
    * `update_queue`
    * `job_queue` (something to think about: instead of updater_queue & job_queue, pass the `updater`)
    * `user_data`
    * `chat_data`
    * `match` (instead of `groups`, `groups_dict` and similar for).

**Comment by JosXa** [comment]
@tsnoam I'd love for the ctx argument to be optional somehow. This was one of the nice results of #859, enabling short callbacks like
https://github.com/python-telegram-bot/python-telegram-bot/blob/9c6efb8b6ba2b0d9c0da5ca59c48714e805d5cdc/examples/autowiring.py#L39

**Comment by tsnoam** [comment]
@JosXa 
I don't see a reason why to make the context argument optional. Users should have all the power they need. They can ignore (not use) the argument if they want, but they should still be able to easily use it.

**Comment by tsnoam** [comment]
To clarify what I'm thinking:
Passing a context argument to the callback is the standard approach. This is what every programmer is looking for when he tries to understand what he can do from within the callback.
So in order to make things simple, the callback prototype should be simple enough so every one can immediately see what he has at hands.

**Comment by Eldinnie** [comment]
I'm a fan. But two things. I would add the update to the context as well. This makes for:
`def callback(context):`
And regarding adding `job_queue` and `update_queue`. You mentioned passing updater. But I think the more logical thing would be passing `dispatcher`.
This could be a good solution overall, because users sometimes want to acces the `user_data` dict etc.

**Comment by JosXa** [comment]
@Eldinnie Dynamically adding handlers as an "immediate next step callback" would be nice that way, the pyTelegramBotAPI people go quite well with that.
Possibly with a lifetime attached, but that's gold plating.

**Comment by tsnoam** [comment]
@Eldinnie 
> And regarding adding job_queue and update_queue. You mentioned passing updater. But I think the more logical thing would be passing dispatcher.
That's why I raised it for discussion. The `Updater` contains references to all these objects. I want things to be simple, but OTOH I don't want things to be too much elaborate as it can become cluttered and confusing very quickly.

**Comment by tsnoam** [comment]
@JosXa 
I don't like comparing this library to others. I prefer doing what I find right and suitable for the "spirit" of the library. Please refrain from such comparisons in the future.
That said, if you have a suggested API in mind, you should provide a usage example.

**Comment by tsnoam** [comment]
@Eldinnie, about this (including the `Update` as part of the context):
> ` def callback(context):`

Personally, I find it too radical. To be honest, I wasn't sure if the `Bot` should be only part of the callback arguments, only part of the context or be part of both. What tipped the scale for me to have the `Bot` only in the context, is that these days, every `Update` object (or to be more precise `Message` object) contains reference to `Bot`, so you can easily call methods like `reply_audio()`.

What I'm trying to say, I want the callback prototype to be compact, but at the same time provide the most common and useful features accessible just at the tips of the fingers for the really simple usecases.

That said, I'm not convinced of anything...

**Comment by JosXa** [comment]
@tsnoam I like the idea of splitting the args up into "things you can do with the incoming message" (Update) and "data storage and convenience from the library" (Context). Which also separates namespaces 👍

I agree in the point that the access to bot is not as relevant anymore, since most things are bundled nicely in the update.

I was also a proponent of context.update before (I.e. only having context as the single argument), but I've grown to like the idea of two separate arguments more.

**Comment by JosXa** [comment]
By implementing #1080, we might possibly stick with the pass_* instructions.

**Comment by bomjacob** [comment]
Fixed by #1100 - closing.
