### ISSUE TITLE
Change all links to t.me

### ISSUE THREAD

**Issue by DanKatzuv** [python-telegram-bot/python-telegram-bot#1027]
You can change all links in the wiki (and probably in other places too) from telegram.me/[stuff] to t.me/[stuff]: https://telegram.org/blog?offset=10#t-me-links

**Comment by tsnoam** [comment]
This sounds like a nice idea.

We always welcome community contribution. Therefor, everyone with a GitHub account can modify the wiki. For the code base itself feel free to send PRs.

**Comment by JosXa** [comment]
@tsnoam https://github.com/python-telegram-bot/python-telegram-bot/wiki
