### ISSUE TITLE
ConversationHandler is not thread safe

### ISSUE THREAD

**Issue by tsnoam** [python-telegram-bot/python-telegram-bot#1029]
The following are initial findings, but it's a good place to start:

Members which need a mutex protecting them:
- [x] `conversations`
- [x] `timeout_jobs`

Members which should be removed. Instead `check_update()` should probably return a context to be passed to `handle_updates()`:
- [x]  `current_conversation`
- [x]  `current_handler`

- [x] All other members must be set internal (i.e. renamed to be prefixed with `__`) so they won't be modified after `__init__()`.

**Comment by jh0ker** [comment]
`current_conversation` and `current_handler` could also be in a `threading.local`

**Comment by bomjacob** [comment]
The issues with `current_conversation` and `current_handler`  have been fixed by implementing context based callbacks (#1100) (see `ConversationHandler.check_update`).
