### ISSUE TITLE
Updates containing pictures from channels get missed

### ISSUE THREAD

**Issue by phDooY** [python-telegram-bot/python-telegram-bot#1033]
### Steps to reproduce
1. Create a simple bot from templates, print(update) to console

2. Add bot to group

3. Forward a message from any channel (read-only sort of channel, like news group) that contains a picture into this group

### Expected behaviour
Updater should track message and print it to console

### Actual behaviour
Updater skips the message for some reason, and you can not see update json in console:
![image](https://user-images.githubusercontent.com/6223779/36973429-065d5522-2084-11e8-90db-7d01d21367c1.png)

### Configuration
**Operating System:**  Windows 10; Unubtu 16.04
**Python Version:** Python 3.6.4
**Dependencies:**
- python-telegram-bot 9.0.0
- certifi 2018.01.18
- future 0.16.0

**Comment by Eldinnie** [comment]
I'm assuming this solved your issue. Closing it.
