### ISSUE TITLE
Why the jobqueue with each server reload sends one more message to the user? 

### ISSUE THREAD

**Issue by VitaliyVinnychenko** [python-telegram-bot/python-telegram-bot#1034]
Why the jobqueue with each server reload sends one more message to the user? 
And how to close the previous jobqueue in past server runnings?

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup). Or (if you can't reach our group) our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot)
