### ISSUE TITLE
Removing bot from group!

### ISSUE THREAD

**Issue by aabdulwahed** [python-telegram-bot/python-telegram-bot#1035]
### Expected behaviour
We need to let admin bot to delete other scam bot from our channel.

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup). Or (if you can't reach our group) our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot)

**Comment by aabdulwahed** [comment]
Thanks! 

This is the function I looked for:
```
./bot.py:1388:    def kick_chat_member(self, chat_id, user_id, timeout=None, until_date=None, **kwargs):
```
