### ISSUE TITLE
Reply to group messages

### ISSUE THREAD

**Issue by blast1987** [python-telegram-bot/python-telegram-bot#1036]
#Hello,
i am using the simple example echobot and it is working good on a single chat!
but how to listen to group messages?

i want my bot to be in a group and reply for every user that post a message in that group, how to do that?

this works only in single chat:

> dp.add_handler(MessageHandler(Filters.text, echo))
def echo(bot, update):
    """Echo the user message."""
    update.message.reply_text(update.message.text)

Thanks

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup). Or (if you can't reach our group) our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot)
