### ISSUE TITLE
Object Oriented code

### ISSUE THREAD

**Issue by keldrom** [python-telegram-bot/python-telegram-bot#1037]
Hi everyone,
I've issues on implementing an O.O. program of the conversationbot2.py
I'd like to make different classes for the main and the functions.
When the bot start I'm able to recall the 'start' function but the return does't seems to be able to recall one of the states of the ConversationHandler.
It seems that for the correct usage of the bot the only way is to implement all in a single giant class.
Can you help me? 
Thanks a lot.

PS If there's someone that can explain me better the meaning of the line 32 of the conversationbot2.py I'll be grateful; I've understood that every STATE must be written in that list and the overall range() must be the sum of the states used but I don't know why.

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup). Or (if you can't reach our group) our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot)
