### ISSUE TITLE
filter for telescope handler 

### ISSUE THREAD

**Issue by mostafaasadi** [python-telegram-bot/python-telegram-bot#1038]
### Configuration
**Ubuntu 16.04**
**Version of Python, python-telegram-bot & dependencies:**
```python-telegram-bot 10.0.1
certifi 2018.01.18
future 0.16.0
Python 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
```

please add a filter to handle and detect **[telescope messag](https://telegram.org/blog/video-messages-and-telescope)**

thanks

**Comment by JosXa** [comment]
@mostafaasadi I'd say make your own 🤷‍♀

**Comment by bomjacob** [comment]
You mean [VideoNote](https://python-telegram-bot.readthedocs.io/en/latest/telegram.videonote.html#telegram.VideoNote)? ([official docs](https://core.telegram.org/bots/api#videonote))
If so you can use a simple [MessageHandler](https://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.messagehandler.html#telegram.ext.MessageHandler) with a custom video note filter until we implement one ourselves.
``` python
class _VideoNoteFilter(BaseFilter):
        name = 'custom filter for video_note'

        def filter(self, message):
            return bool(message.video_note)

video_note_filter = _VideoNoteFilter()
```
