### ISSUE TITLE
Keyboard not working!

### ISSUE THREAD

**Issue by mohamad29175** [python-telegram-bot/python-telegram-bot#1039]
### Expected behaviour
Keyboard must be shown to the user.

### Actual behaviour
neither inline keyboard nor standard keyboard, none of them appear when I use them in my code.

### Configuration
Windows 10 64-bit

**Version of Python, python-telegram-bot & dependencies:**

Anaconda3

### Logs
Insert logs here (if necessary)

**Comment by g1uk** [comment]
same problem, inline keyboard and custom keyboard (like contact and location request) doesn' show in chat. Even tried bot from examples, but same issue.

Python 3.5 on fedora 27 and kali linux.

**Comment by Eldinnie** [comment]
There seems to be some problems with this sometimes on telegram x. However it's not due to the library so I;m closing this issue

**Comment by g1uk** [comment]
I faced with this issue on classic telegram app, not telegram X

**Comment by Eldinnie** [comment]
@g1uk you can open a new issue following the issue template if you think it's a problem with the library.

If it is a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup). Or (if you can't reach our group) our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot)
