### ISSUE TITLE
sendDocument doesn't accept emojis or unicode chars in caption

### ISSUE THREAD

**Issue by DarthJahus** [python-telegram-bot/python-telegram-bot#1040]
Adding an emoji or a unicode character in `caption` parameter prevents the file from being sent.

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup). Or (if you can't reach our group) our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot)
