### ISSUE TITLE
Media caption is not formatted

### ISSUE THREAD

**Issue by bukvaeshka** [python-telegram-bot/python-telegram-bot#1044]
Hi. I updated my telegram to 10.0.1 - which I suppose should support media caption formatting as per:
February 13, 2018
Bot API 3.6.
Following is a simple code which is not working for me:

from telegram.ext import Updater

def start(bot, update):
  bot.send_photo(chat_id=update.message.chat_id, photo=open('/some-photo.jpg', 'rb'), caption = "<b>bold</b>", parse_mode = "HTML")

if __name__ == '__main__':$
  updater = Updater(config.token)$
  updater.dispatcher.add_handler(CommandHandler('start', start))$
  updater.start_polling()$
  updater.idle()

### Steps to reproduce
1. Write simple bot that sends photo on /start with ex: bold caption and HTML parse mode.

2. See that caption in the sent photo is not bold.

### Expected behaviour
Caption should have been bold.

### Actual behaviour
Caption is not bold.

### Configuration
Linux 4.8.13-100.fc23.x86_64

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

python-telegram-bot 10.0.1
certifi 2018.01.18
future 0.16.0
Python 3.4.3 (default, Aug  9 2016, 15:36:17)  [GCC 5.3.1 20160406 (Red Hat 5.3.1-6)]

### Logs
Insert logs here (if necessary)

**Comment by Eldinnie** [comment]
Hi, I edited your comment so the code actually shows up :D.

It's good to know that caption formatting does not yet show up in telegram desktop. Can you check on a mobile device that caption is not properly formatted?

**Comment by bukvaeshka** [comment]
Only thing I'm thinking is that update for API 3.6 is made in
February 13, 2018
Bot API 3.6.

But, my version shows:
python-telegram-bot 10.0.1
certifi 2018.01.18   => Jan 18th

I updated my telegram through pip. Does it mean that the API 3.6 is not available through pip?

**Comment by bukvaeshka** [comment]
Haa. You're right Eldinnie, mobile phone works fine.

**Comment by jh0ker** [comment]
@bukvaeshka It's just the certifi version that is a bot older but it's not relevant for this issue

**Comment by Eldinnie** [comment]
@bukvaeshka good to hear, now we just wait till telegram desktop finaly updates the client. I'm closing the issue.

**Comment by bukvaeshka** [comment]
Thank you for the fastest issue solving!
