### ISSUE TITLE
bot.send_message() raises TimedOut exception for some messages over quota, but still delivers them

### ISSUE THREAD

**Issue by corehack** [python-telegram-bot/python-telegram-bot#1045]
### Steps to reproduce

```python
import time
from telegram import Bot
from telegram.error import RetryAfter, TimedOut

def telegram_send(message):
    tries = 0
    max_tries = 10
    retry_delay = 10
    while tries < max_tries:
        try:
            _telegram_send(
                'Test message {}, Retries {}'.format(
                    message, tries
                )
            )
        except (RetryAfter, TimedOut) as e:
            print("Message {} got exception {}".format(message, e))
            time.sleep(retry_delay)
            tries += 1
        else:
            break


def _telegram_send(message):
    chat_id = "put your chat id here"
    bot = Bot(token="put your token here")
    bot.send_message(chat_id=chat_id, text=message)


for n in range(30):
    telegram_send(str(n))
```

### Expected behaviour
Each message delivered exactly once, or not delivered (if the exceptions listed are not enough to handle all cases)

### Actual behaviour
All messages delivered. Message 20 is delivered 3 times:
```
Bot [15.03.18 00:18]
Test message 20, Retries 0
Bot [15.03.18 00:18]
Test message 20, Retries 1
Bot [15.03.18 00:19]
Test message 20, Retries 2
```
The reason is obvious:
```
In [2]: for n in range(30):
   ...:     telegram_send(str(n))
   ...: 
Message 20 got exception Timed out
Message 20 got exception Timed out
```
So what we have is first 2 deliveries are "timedout" duplicates and the third delivery is the normal one.

### Configuration
**Operating System:**
Some old Ubuntu ("trusty")

**Version of Python, python-telegram-bot & dependencies:**

```
$ python -m telegram
python-telegram-bot 10.0.1
certifi 2018.01.18
future 0.16.0
Python 3.6.0 (default, Oct 19 2017, 13:41:42)  [GCC 4.8.4]
```

**Comment by bomjacob** [comment]
This seems to me like a Telegram issue, since it involves telegram raising too many TimedOut errors (we are just relaying what we receive from their servers).
@python-telegram-bot/developers would you all agree?

**Comment by tsnoam** [comment]
@bomjacob Actually, TimedOut and RetryAfter are very much different exceptions.
The prior is usually observed due to network errors while the latter is a specific error received from the telegram server, telling you how many seconds you have to wait before trying again.

**Comment by corehack** [comment]
I could not reproduce issue after I switched to using API directly with requests library - it either keeps trying to connect and succeeds, or in case of timeout the message is not delivered. With python-telegram-bot it looks like even after the timeout exception the connection is still alive and it succeeds eventually leading to duplicates.

**Comment by Eldinnie** [comment]
@tsnoam does urllib and our request have some retry mechanism? That would explain this

**Comment by tsnoam** [comment]
I think I wasn't clear enough with my previous comment 
The example code is wrong.
@corehack please separate between  TimedOut and RetryAfter exception catching because they're totally different things.
Also, please enable logging and attach the logs.

**Comment by corehack** [comment]
@tsnoam You can see from the console output I provided RetryAfter does not matter here, as it's not raised.
We already switched from the python-telegram-bot to requests-based solution already, as our needs are very basic atm. I hope the information I provided here is enough to reproduce.

**Comment by DimaDK24** [comment]
Got the same error with SendMessage:

`TimedOut
Timed out`

`ReadTimeoutError
HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)`

`timeout
The read operation timed out`
Does anyone know how to really solve it?

**Comment by DimaDK24** [comment]
It's strange, that request lasts 5 seconds as I can see in the logs...
![s80614-22372823 1](https://user-images.githubusercontent.com/25607790/41434330-091e948e-7024-11e8-9f73-45fe45380d89.jpg)

**Comment by DimaDK24** [comment]
Just for future people with such error:
I increased timeout to 15 second and made program restart request if TimedOut was raised and everything work like a charm

**Comment by corehack** [comment]
Huh ? Was this bug fixed ?

**Comment by sdelquin** [comment]
> It's strange, that request lasts 5 seconds as I can see in the logs...
> ![s80614-22372823 1](https://user-images.githubusercontent.com/25607790/41434330-091e948e-7024-11e8-9f73-45fe45380d89.jpg)

Sorry for the offtopic. What is this screencapture? Kind of profiler?

**Comment by sdelquin** [comment]
> Just for future people with such error:
> I increased timeout to 15 second and made program restart request if TimedOut was raised and everything work like a charm

@DimaDK24 How do you increase timeout in python-telegram-bot ??

**Comment by DimaDK24** [comment]
@sdelquin, it's amazing platform for watching errors of your app: sentry.io.

For increasing timeout search for "timeout" in the docs of the project. I suppose it's mentioned in send_message or something like this.

**Comment by sdelquin** [comment]
Thanks for your hints @DimaDK24. Here is the link to `send_message` documentation where you can increase the timeout: https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.send_message

**Comment by Nukesor** [comment]
Is there a way to set the timeout for send_message for the whole bot?
I'm using send_message in way too many places, it would be great to get a well documented solution on how to specify the timeout on a global level.
