### ISSUE TITLE
Consider making chat_id a positional argument in chat.send_message and similar to avoid error messages when not using kwargs

### ISSUE THREAD

**Issue by xates** [python-telegram-bot/python-telegram-bot#1048]
When doing `chat.send_message("Hello")`  the following error occurs: 
> TypeError: send_message() got multiple values for keyword argument 'chat_id'

This can be solved by providing each argument through its keyword (like that: `chat.send_message(text="Hello")`), however this is not very convenient.

By replacing keyword argument `chat_id=self.id` with positional argument `self.id` (it is the first argument in of the `bot.send_message` method) in the `Chat` class, you can avoid to be forced to always use kwargs when calling this method.

The same thing happens for the other shortcut methods (`send_photo`, `send_audio`, ...) and for the corresponding methods of the `User` class.
https://github.com/python-telegram-bot/python-telegram-bot/blob/1530ed20e51960296b0edb9bfa483047b59187e0/telegram/chat.py#L227

**Comment by jh0ker** [comment]
@xates Yeah I agree with that. Would you like to contribute a PR to change this behavior?

**Comment by xates** [comment]
Yeah sure!

**Comment by jh0ker** [comment]
@xates Thanks a lot! :)

Please read the contributing guide before you begin: https://github.com/python-telegram-bot/python-telegram-bot/blob/master/.github/CONTRIBUTING.rst
