### ISSUE TITLE
Delete inline message

### ISSUE THREAD

**Issue by bukvaeshka** [python-telegram-bot/python-telegram-bot#1051]
This might not be issue but question/request.
Can we delete inline message?
I know that we can edit reply markup for inline message - it would be great to have api to delete inline message also.

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup). Or (if you can't reach our group) our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot)
