### ISSUE TITLE
Telegram forgets users

### ISSUE THREAD

**Issue by ivanov-kir-m** [python-telegram-bot/python-telegram-bot#1052]
### Steps to reproduce
1. Start a chat via bot and any user. Save his chat_id. Notify him from time to time like each 1 hour by using method bot.sendMessage(we use job_queue for that). After a day or about that you'll get an error "error_code": 400, "description": "Bad Request: chat not found".

### Expected behaviour
Bot can send message to known user at any time. 

### Actual behaviour
I got an error "error_code": 400, "description": "Bad Request: chat not found". Looks like bot forget about the user. If you send from the user a message to the bot you'll be able to send messages again from bot to user. Bot restarting doesn't help without sending a message from user again.

### Configuration
**Operating System:**
Cent OS 7
**Version of Python, python-telegram-bot & dependencies:**
``$ python -m telegram``
python-telegram-bot 10.0.1
certifi 2018.01.18
future 0.16.0
Python 3.6.2 (default, Jul 18 2017, 22:59:34)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

**Comment by tsnoam** [comment]
@ivanov-kir-m 
This is not an issue with the library but rather an issue with Telegram itself. You should contact bot support about that.
One tip before doing so, you should make sure that the user hasn't blocked the Bot.

**Comment by Eldinnie** [comment]
Actually it seems more likely to me the users deleted the chat with your bot.
