### ISSUE TITLE
CallbackQueryHandler doesn't work

### ISSUE THREAD

**Issue by hangyas** [python-telegram-bot/python-telegram-bot#1053]
Hi,

I'm trying to use CallbackQueryHandler, but when I click the inline button nothing happens. The problem persists in [examples/inlinekeyboard.py](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/inlinekeyboard.py) too.

### Steps to reproduce
1. run examples/inlinekeyboard.py
2. /start
3. click an inline button

### Actual behaviour
there is no error message or any kind response

### Configuration
```
> python -m telegram
python-telegram-bot 10.0.1
certifi 2018.01.18
future 0.16.0
Python 3.6.4 (default, Jan  5 2018, 02:35:40)  [GCC 7.2.1 20171224]

> uname -a
Linux hangyas-arch 4.15.9-1-ARCH #1 SMP PREEMPT Sun Mar 11 17:54:33 UTC 2018 x86_64 GNU/Linux
```

**Comment by Eldinnie** [comment]
@hangyas Hi, We've recently been alerted that this might have to do with the age of the token you're using.
Can you please try yo revoke/renew your token with @botfather and try again?

**Comment by hangyas** [comment]
the new token has fixed it, thanks!

**Comment by ilov3** [comment]
Hi, 
Same issue
Renew of token didn't help
