### ISSUE TITLE
urllib3 HTTPError [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] 

### ISSUE THREAD

**Issue by Pauldic** [python-telegram-bot/python-telegram-bot#1054]
I have some codes in the update function but I noticed (though NOT for every updates) that every time I restart the process, sometimes (most often on the 2nd update) I get 

`urllib3 HTTPError [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1977)`

 which breaks my code and funny enough I could not catch the Exception but I will ONLY   SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC error on the log.

This has existed since version v9.x and priori to v10.x this type usually get propagated to `add_error_handler(error)` where I am able to fail safely but I noticed that after upgrading to v10 it does not propagate any longer.

In the sample below I will only see:

`Something 123
urllib3 HTTPError [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1977)`

`print("Something 123")
try:
    member = bot.getChatMember(update.message.chat.id, update.message.from_user.id)
except Exception as err:
    print("did I catch you? ")
print("Something 456")`

**Comment by tsnoam** [comment]
Closing the issue does not comply with issue template.
