### ISSUE TITLE
Feature request: ConversationHandler, acquaintance of its own in a conversation

### ISSUE THREAD

**Issue by blackhuman** [python-telegram-bot/python-telegram-bot#1056]
In some circumstances, in the handler method, having the acknowledgement of whether the method was invoked in a conversation would be a convenience. For instance, a handler which only handles the contact message would make no sense if there is no context at all (not in a conversation).

Is there any chance to add the optional third param for handler method which invoked in `ConversationHandler.handle_update`, like in line 305 of [conversationhandler.py](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/conversationhandler.py#L305)

**Comment by JosXa** [comment]
Hi there,

Would a lambda expression suit your needs?

```
...
State: [
    MessageHandler(..., lambda bot, update: callback(bot, update, invoked_via_chandler=True))
] ,...
```

**Comment by blackhuman** [comment]
Very clever, it works, thank you very much.
