### ISSUE TITLE
How i can find organization near me?

### ISSUE THREAD

**Issue by gukobrist** [python-telegram-bot/python-telegram-bot#1058]
Hello! Thx for this library. Im beginner. I wants ask you - maybe u now - how i can take my coordinate? Or how i can finde organization near me whith function 

`location_keyboard = KeyboardButton(text="Мое местонахождение", request_location=True)`

I create bot whith function "MyLocate" and when i click "Wher am i?" i take a screenshot map with marker and me. How i can take my coordinat or just search for a specific organization near me and print her address?

Please help me if u can)

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup). Or (if you can't reach our group) our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot)
