### ISSUE TITLE
How to receive supergroup messages?

### ISSUE THREAD

**Issue by savao** [python-telegram-bot/python-telegram-bot#1060]
Hello!
Try to use this package to create telegram bot, but faced with problem.
Bot don't take any messages from supergroup, only commands.
I try to use RegexHandler, MessageHandler... in the end I create own custom handler as the inheritor of class Handler. But this handler not receive messages in supergroup too.
At the same time in the private chat everything works well.
What can I do to solve this problem?

Example of my custom handler:

    def cb(bot, update):
        print('cb')

    class CustomHandler(Handler):

        def __init__(self, pattern, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.pattern = re.compile(pattern)

        def check_update(self, update):
            print('check:')
            print('em = ', update.effective_message.text)
            print('m = ', update.message.text)
            return bool(re.match(self.pattern, update.message.text))

        def handle_update(self, update, dispatcher):
            return self.callback(dispatcher.bot, update)

    handler = BotCommandHandler(pattern, cb)
    dispatcher.add_handler(handler)

**Comment by savao** [comment]
I found that when I'm add a bot to the list of group administrators, then it reads all messages. If he is not an administrator, then it can  read in the group only commands, i.e. messages starting with "/". Should it be?

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup). Or (if you can't reach our group) our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot)

**Comment by savao** [comment]
Thank you.
