### ISSUE TITLE
Login Widget

### ISSUE THREAD

**Issue by jimist** [python-telegram-bot/python-telegram-bot#1075]
As the telegram added **login widget for bots**  in the website said:

> Added the new field connected_website to Message. The bot will receive a message with this field in a private chat when a user logs in on the bot's connected website using the Login Widget and allows sending messages from your bot.

 so we should have an extra field for our messages but I cannot find it

Can anyone share a snippet for this usage?

**Comment by tsnoam** [comment]
@jimist 
When you open a new issue, please respect the issue template. I'm closing this issue now, please open a new issue with all details as requested.

Also, please join our users group https://telegram.me/pythontelegrambotgroup we have a vibrant community happy to assist with usage questions.
