### ISSUE TITLE
Some messages a not delivered to handler

### ISSUE THREAD

**Issue by ManuelSchneid3r** [python-telegram-bot/python-telegram-bot#1090]
### Expected behaviour
Handle all messages

### Actual behaviour
Some messages a not handled

### Configuration
ubuntu 16.04
Python 3.5.2
python-telegram-bot==10.0.2

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question (I think, you're not giving any information). Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup). Or (if you can't reach our group) our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot)
