### ISSUE TITLE
here telegram is filtered so i have to use proxy to test my bot

### ISSUE THREAD

**Issue by sizdah** [python-telegram-bot/python-telegram-bot#1101]
i want to use a proxy server to bypass filtering and connect to telegram API server 
i already installed this library

 pip install python-telegram-bot[socks] 

`
 def setup(webhook_url=None):
    REQUEST_KWARGS = {"proxy_url": "103.241.205.66:8080"}

    logging.basicConfig(level=logging.WARNING)
    if webhook_url:
        bot = Bot(TOKEN)
        update_queue = Queue()
        dp = Dispatcher(bot, update_queue)
    else:
        updater = Updater(TOKEN, request_kwargs=REQUEST_KWARGS)
        bot = updater.bot
        dp = updater.dispatcher
        dp.add_handler(CommandHandler("start", start))
        dp.add_handler(CommandHandler("help", start))

        # on noncommand i.e message - echo the message on Telegram
        dp.add_handler(MessageHandler(Filters.text, paper))

        # log all errors
        dp.add_error_handler(error)
    # Add your handlers here
    if webhook_url:
        bot.set_webhook(webhook_url=webhook_url)
        thread = Thread(target=dp.start, name='dispatcher')
        thread.start()
        return update_queue, bot
    else:
        bot.set_webhook()  # Delete webhook
        updater.start_polling()
        updater.idle()

if __name__ == '__main__':
    setup()`

but i get this error:

> Traceback (most recent call last):
  File "E:/shift/hec/app.py", line 118, in <module>
    setup()
  File "E:/shift/hec/app.py", line 93, in setup
    updater = Updater(TOKEN, request_kwargs=REQUEST_KWARGS)
  File "C:\Users\sina\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telegram\ext\updater.py", line 121, in __init__
    self._request = Request(**request_kwargs)
  File "C:\Users\sina\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telegram\utils\request.py", line 124, in __init__
    mgr = urllib3.proxy_from_url(proxy_url, **kwargs)
  File "C:\Users\sina\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\poolmanager.py", line 363, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "C:\Users\sina\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\poolmanager.py", line 314, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None

Process finished with exit code 1

what should i do ?

**Comment by tsnoam** [comment]
Hi,

You're missing the scheme from the URL
i.e. `https://103.241.205.66:8080`, `socks5://103.241.205.66:8080`, etc.

In general, you're invited to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
