### ISSUE TITLE
Tests missing for `User.mention_markdown` and `User.mention_html`

### ISSUE THREAD

**Issue by Eldinnie** [python-telegram-bot/python-telegram-bot#1108]
And while we're at it. Maybe `helpers.mention_markdown/html` too.

**Comment by JosXa** [comment]
Didn't we decide this wasn't needed as they're just wrappers?

**Comment by Eldinnie** [comment]
@JosXa Ehm, can't remember. IMO everything should be tested. The helpers module is missing a lot of tests but have a lower priority IMO.

**Comment by JosXa** [comment]
Oh nevermind, I thought we were talking about reply_* methods
