### ISSUE TITLE
Add __slots__ to library objects

### ISSUE THREAD

**Issue by JosXa** [python-telegram-bot/python-telegram-bot#1109]
We have many classes in the library. Bots use a lot of memory.
Let's add `__slots__` to the classes where they make sense.

More info on what `__slots__` are: https://stackoverflow.com/questions/472000/usage-of-slots?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

We have to consider **where it actually makes sense**:
- Let's find out candidates where users are likely to monkey patch their own attributes on library objects. These should not receive slots as it would break existing code bases.
- Which objects are so big that we would like to benefit from `__slot__` 's performance boosts nonetheless?

Please list candidates in the comments.

**Comment by Eldinnie** [comment]
One little point (taken from your link):
```
Add '__dict__' to __slots__ to get dynamic assignment:
class Foo(object):
    __slots__ = 'bar', 'baz', '__dict__'
and now:

>>> foo = Foo()
>>> foo.boink = 'boink'
So with '__dict__' in slots we lose some of the size benefits with the upside of having dynamic assignment and still having slots for the names we do expect.```
Nothing breaks like this.

**Comment by Bibo-Joshi** [comment]
I think we should go for this. The benefits are clear and the biggest caveat being multiple inheritance should only occour in some special cases in PTB (if at all). In fact I guess we cann add slots to *all* classes. Adding `__dict__` to them will keep backwards compatibility. Ofc this will be somewhat tedious work, but maybe it can probably automated with [`inspect.getmembers`](https://docs.python.org/3/library/inspect.html#inspect.getmembers) or something else from that lib … In fact we should have a unit test thet checks all existing classes in PTB and asserts that the slots don't contain anything that is *not* a member, which will probably work in a similar fashion.

In the long term we can drop `__dict__` from all API classes (adding custom attributes to them is bad practice i think).
regarding tg.ext:

* `CallbackContext` should keep `__dict__` as adding custom attributes to be accessed by handlers in a higher group is a valid use case.
* For all other classes in tg.ext: keeping `__dict__` is subclassing-friendly. OTOH, we can just document that we're using `__slots__` and if someone wants to subclass, they can add the slots they need …
