### ISSUE TITLE
Using Tor as socks proxy not working

### ISSUE THREAD

**Issue by sae13** [python-telegram-bot/python-telegram-bot#1130]
Hi there, I wanna user Tor socks as my proxy but it doesnt work, 
```
request=Request(proxy_url="socks5://127.0.0.1:9050",
                read_timeout=30, connect_timeout=20,
                con_pool_size=10)
bot = telegram.Bot("TOKEN",request=request)
chat_id= -1001218877913 #@nicicoShahrbabak
#chat_id= -1001397321509 #@MesShahrbabak
img = bot.send_photo(chat_id = chat_id, photo = open("greeting_card.png",'rb'),timeout=60)

```

and error is :
```
raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot591133322:AAE8oUf2bNBB4_c_cOhCPYpiPMNkE_BC0-Y/sendPhoto (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fe4acc2c9b0>: Failed to establish a new connection: 0x01: General SOCKS server failure',))
```

complete error code can be found here :
https://beepaste.io/paste/view/0OQUYN

My python version is : 
```
(venv)  saeb@PublicRelation  ~/PycharmProjects/NicicoPrice   master ●  python -m telegram
python-telegram-bot 10.1.0
certifi 2018.04.16
future 0.16.0
Python 3.6.5 (default, May 11 2018, 04:00:52)  [GCC 8.1.0]
(venv)  saeb@PublicRelation  ~/PycharmProjects/NicicoPrice   master ●  
```

TOR Log is : 
```
journalctl -u tor --since today
Rejecting SOCKS request for anonymous connection to private address [scrubbed]
```

**Comment by Eldinnie** [comment]
@sae13 revoke your token. It's visible here

**Comment by sae13** [comment]
@Eldinnie thanks , I tried to find that before sending but I coudnt find that. tnx

**Comment by tsnoam** [comment]
@sae13 Please add missing information from the new issue template.

Also, looking at the logs it seems that the error is on the server side. Please check the logs on your proxy server.

**Comment by sae13** [comment]
> @sae13 Please add missing information from the new issue template.
sorry I`m noob, where I can find template i`ll add them

> 
Also, looking at the logs it seems that the error is on the server side. Please check the logs on your proxy server.


I use tor in my local machine, I don't think that have problem berceuse I`m using tor proxy in my telegram desktop

**Comment by sae13** [comment]
@tsnoam  I added details

**Comment by tvorogme** [comment]
Same for me

**Comment by tvorogme** [comment]
I have solution for you 
https://github.com/python-telegram-bot/python-telegram-bot/issues/1137

**Comment by jsmnbom** [comment]
As @tvorogme said in #1137 changing your protocol from socks5 to socks5h should be sufficient.
Closing issue since it should be resolved.
If changing protocols does not fix, feel free to reopen :)
