### ISSUE TITLE
Bot does not run more than one MessageHandler

### ISSUE THREAD

**Issue by mike-johnson-jr** [python-telegram-bot/python-telegram-bot#1133]
def echo_message_sent_from_droplyuserbot(bot,update):
	    if update.message.chat_id == int(droply_userbot_id):
		split_message = update.message.text.split('@@')
		group_id = split_message[0]
		message = split_message[1]
		bot.send_message(chat_id=group_id, text=message)

    emsfd_handler = MessageHandler(Filters.text,echo_message_sent_from_droplyuserbot)
    dispatcher.add_handler(emsfd_handler)

    def send_message_on_login(bot,update):
        if update.message.connected_website:
            bot.send_message(chat_id=update.message.chat_id, text="Thank you for logging in with Telegram!")

    smol_handler = MessageHandler(Filters.all,send_message_on_login)
    dispatcher.add_handler(smol_handler)

    updater.start_polling()

`send_message_on_login` used to execute before I put `echo_message_sent_from_droplyuserbot` before it. Now only `echo_message_sent_from_droplyuserbot` executes. Before I put `echo_message_sent_from_droplyuserbot` before `send_message_on_login`, `echo_message_sent_from_droplyuserbot` didn't execute. It seems both can't operate together. How can I make them work together?

### Configuration
**Operating System:** Windows

**Version of Python, python-telegram-bot & dependencies:**

$ python -m telegram
python-telegram-bot 10.1.0
certifi 2018.04.16
future 0.16.0
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Inte
l)]

**Comment by iskhomutov** [comment]
Hi. You should add second handler into another group, e.g.
`dispatcher.add_handler(emsfd_handler)`
`dispatcher.add_handler(smol_handler, group=1)`
By default, the dispatcher add handlers into group 0 and then, search for the first match in each group.
[https://github.com/python-telegram-bot/python-telegram-bot/blob/d2059ed184cbcb01d92194b9fa299fe643e2ecef/telegram/ext/dispatcher.py#L303](https://github.com/python-telegram-bot/python-telegram-bot/blob/d2059ed184cbcb01d92194b9fa299fe643e2ecef/telegram/ext/dispatcher.py#L303)

**Comment by tsnoam** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
