### ISSUE TITLE
Extend parameter passing to callback functions

### ISSUE THREAD

**Issue by TimiH** [python-telegram-bot/python-telegram-bot#1134]
Is it possible to extend the Handlers to allow the passing of parameters to callback functions?

I implemented a number of a Conversations, which are inherently designed for user input. 
Take this code of a state for example. The allowed input '^(SO|BO)$'  is being passed through Buttons or often keyboard.
```
AMOUNT: [RegexHandler('^(SO|BO)$', amount,pass_user_data=True),
                  MessageHandler(Filters.text, error,pass_user_data=True)],
```

In order to give feedback on bad input it would be neat if we could call callback functions with parameters other than user_data etc.
```
AMOUNT: [RegexHandler('^(SO|BO)$', amount,pass_user_data=True), 
    MessageHandler(Filters.text, error,pass_callback="This is not the required input")],
```
```
def error(bot,update,text):
    bot.send_message(text=text,....)
```

The alternative is writing custom Error functions, which seems excessive and bloats the code unnecessary or consistently having to pass and store the state, whilst keeping a dict(state,errormessage).

**Comment by tsnoam** [comment]
Hן @TimiH 
v11 will include such support - the whole Handlers API had been refactored. You can look at `V11` branch for an heads up on what's coming. Just remember, if you choose to work with unreleased branch, we still reserve the right to make API changes... :-)

**Comment by tsnoam** [comment]
@TimiH 
Take a look at the `CallbackContext` object from `V11` branch. I believe that this is what you're looking for.

**Comment by JosXa** [comment]
@TimiH In my opinion what you're doing should be part of normal error handling in your callbacks as it can be expected that the user will make mistakes. 
If your goal is separation of concerns, I would suggest splitting up your callback functions into a reusable one for error handling, and the actual business logic.
