### ISSUE TITLE
Proxy not working and I fixed it.

### ISSUE THREAD

**Issue by tvorogme** [python-telegram-bot/python-telegram-bot#1137]
### Steps to reproduce
1. Define proxy like in [example](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Working-Behind-a-Proxy). My problem about my own socks5 proxy with username and password and tor proxy also. Maybe other types of proxy will work.

2. Run bot.

### Expected behaviour
Bot not working behind proxy

### Actual behaviour / solution
Ok. To understand what actually happens I go to the source code and:

when you run your bot  - actually you bypass your proxy to [Updater](https://github.com/python-telegram-bot/python-telegram-bot/blob/f8a17cddcbe374b95fbc834de5c6f3319a87592b/telegram/ext/updater.py#L121), than it goes to [Request](https://github.com/python-telegram-bot/python-telegram-bot/blob/b77b329dd64f0d114ec5ef02c922036d5d4f5726/telegram/utils/request.py#L122).  
If you print kwargs of ```__init__``` in request you will actually see your proxy:

 ```{'maxsize': 8, 'cert_reqs': 'CERT_REQUIRED', 'ca_certs': '/home/tvorogme/projects/voicegiftelegram/venv/lib/python3.6/site-packages/certifi/cacert.pem', 'socket_options': [(6, 1, 1), (1, 9, 1), (6, 4, 120), (6, 5, 30), (6, 6, 8)], 'timeout': <telegram.vendor.ptb_urllib3.urllib3.util.timeout.Timeout object at 0x7fb4cd3c9fd0>, 'username': 'YOUR_USERNAME', 'password': 'YOUR_PASSWORD'}```

 after that it initialize [SOCKSProxyManager](), same there proxy will be saved to properties of object: 

```{'socks_version': 2, 'proxy_host': 'tvorog.me', 'proxy_port': 6666, 'username': 'YOUR_USERNAME', 'password': 'YOUR_PASSWORD', 'rdns': False}```.

The SOCKSProxyManager based on PoolManager class and it based on RequestMethods of urllib3.

... after hours of source code ...

All problems about proxy -> ``` 'rdns': False```, you need set it to True. I don't know why it so, but after I set rdns to ```True``` - both of my proxies include tor are worked for me!

How I understand that rdns is problem?
I run small script ```print("lol", requests.get('https://api.telegram.org/', proxies=dict(http=check_proxy_url, https=check_proxy_url)))``` and put some debug to pysocks, so request work, but telegram-bot no. I just check difference between  params.

So to define rdns from telebot use ```socks5h://{}:{}@{}:{}``` url instead.

From urllib3 [issue](https://github.com/urllib3/urllib3/issues/1035) -> socks5h - resolve host name thrue proxy. In my country (Russia) telegram is blocked, so i need to receive ip by hostname thrue proxy.

Maybe we will add some information about it to the wiki page with proxy?

### Configuration
**Operating System:** Arch Linux

**Version of Python, python-telegram-bot & dependencies:**

``
python-telegram-bot 10.1.0
certifi 2018.04.16
future 0.16.0
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)  [GCC 7.2.0]
``

### Logs
```
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fb4cd3d86a0>: Failed to establish a new connection: 0x05: Connection refused',)': /bot/deleteWebhook
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fb4cd385438>: Failed to establish a new connection: 0x05: Connection refused',)': /bot/deleteWebhook
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fb4cd3850b8>: Failed to establish a new connection: 0x05: Connection refused',)': /bo/deleteWebhook
ERROR:telegram.ext.updater:Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fb4cd385278>: Failed to establish a new connection: 0x05: Connection refused',))
WARNING:telegram.ext.updater:Failed bootstrap phase; try=1 max_retries=-1
```

**Comment by jsmnbom** [comment]
So it seems the relavant piece of code is https://github.com/urllib3/urllib3/blob/master/urllib3/contrib/socks.py#L159, where it decides whether to resolve dns through the proxy or not.
@tvorogme if you wanna add that info (needing to use socks5h instead of just socks5) to the wiki article at https://github.com/python-telegram-bot/python-telegram-bot/wiki/Working-Behind-a-Proxy please go ahead. If you don't, we'll probably go it sometime in the future, when a contibutor has time.
I'm closing this issue for now, since it's not really an unresolved issue :)

**Comment by Asgoret** [comment]
@tvorogme hi! Can you plz put some code example how use another proxy than urlib3?) Thanks)
