### ISSUE TITLE
support colors in HTML parser 

### ISSUE THREAD

**Issue by mzfr** [python-telegram-bot/python-telegram-bot#1142]
currently the HTML parser doesn't support colors . It would be a good feature to have if we can have support for colors.
Example: If we can add red color for the errors and green for normal text we want.
or maybe just like we can add colors in HTML like `color=FF0000` or maybe with RGB values.

**Comment by JosXa** [comment]
Yea well ask Durov to give you colors :)

**Comment by JosXa** [comment]
For completeness, Telegram does not support any concept of colors. If you were talking about logs, that's a different story.
