### ISSUE TITLE
message decorator is never getting default values from wrapped functions

### ISSUE THREAD

**Issue by jonbesga** [python-telegram-bot/python-telegram-bot#1145]
I just realized of this after working with the [send_audio](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/bot.py#L396) function and see that the default timeout value, 20, is not getting used. The [message](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/bot.py#L68) decorator doesn't know anything about the parameters of the wrapped function and its default values. So the timeout argument and other default values are None unless is explicitly passed.

This is a problem, for example, with the [send_audio](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/bot.py#L396) because big files take more than 5 seconds, and without the `timeout` argument passed to the `self._request.post` function it raise a NetworkError exception.

I submitted #1146 with the fixes

**Comment by jsmnbom** [comment]
Per discussion in #1146, the best fix for this is probably gonna be to remove the `@message` decorator in favour of calling method that has the same functionality (except that it properly passes the default args of course).

**Comment by y2kbug-hk** [comment]
It seems I have found the same issue. Even though I have set a 300sec timeout, the request get timeout easily within a short time.

**Comment by jsmnbom** [comment]
Fixed in #1156 .
