### ISSUE TITLE
Handling of  'WARNING - Update {"...."} caused error "Timed out"'

### ISSUE THREAD

**Issue by sshkrv** [python-telegram-bot/python-telegram-bot#1149]
Hello! Got an issue with requests on my simple telegram - bot. The bot takes requests to search for items in mysql list, than it sorts them and give back one by one. But sometimes ReplyKeyboard doesn't appear when it supposed to and sometimes I can't get any response, so i have to tap once more to get response.
### Steps to reproduce
1. Basically, I am using updater, dispatcher and ConversationHandler to make responses to a client. I can add some code if needed.

2. 90% of time the bot works fine, but in 10% of requests bot stops responding and on server side I've got something like this from logger:
### Logs
`2018-06-22 20:40:28,218 - __main__ - WARNING - Update "{'_effective_message': {'delete_chat_photo': False, 'new_chat_photo': [], 'from': {'username': u'jamakassi', 'first_name': u'Yaroslav', 'is_bot': False, 'id': 198752497, 'language_code': u'ru'}, 'text': u'40', 'caption_entities': [], 'entities': [], 'channel_chat_created': False, 'new_chat_members': [], 'supergroup_chat_created': False, 'chat': {'username': u'jamakassi', 'first_name': u'Yaroslav', 'type': u'private', 'id': 198752497}, 'photo': [], 'date': 1529700022, 'group_chat_created': False, 'message_id': 409}, '_effective_chat': {'username': u'jamakassi', 'first_name': u'Yaroslav', 'type': u'private', 'id': 198752497}, 'message': {'delete_chat_photo': False, 'new_chat_photo': [], 'from': {'username': u'jamakassi', 'first_name': u'Yaroslav', 'is_bot': False, 'id': 198752497, 'language_code': u'ru'}, 'text': u'40', 'caption_entities': [], 'entities': [], 'channel_chat_created': False, 'new_chat_members': [], 'supergroup_chat_created': False, 'chat': {'username': u'jamakassi', 'first_name': u'Yaroslav', 'type': u'private', 'id': 198752497}, 'photo': [], 'date': 1529700022, 'group_chat_created': False, 'message_id': 409}, '_effective_user': {'username': u'jamakassi', 'first_name': u'Yaroslav', 'is_bot': False, 'id': 198752497, 'language_code': u'ru'}, 'update_id': 68604379}" caused error "Timed out"`

3. I've seen issues like this, but no solutions to this. I also have to say, that I'm using webhooks on a server, but replacing it with start_polling doesn't change anything.
### Configuration
Python         3.5.2
pyTelegramBotAPI              3.6.3                            
python-telegram-bot           10.1.0

**Comment by jsmnbom** [comment]
Have you tried taking a look at https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors ?

**Comment by sshkrv** [comment]
Sorry for delayed reply. That brochure helped me out! Sorry for not being not attentive -_-
