### ISSUE TITLE
Feature suggestion: Authentication

### ISSUE THREAD

**Issue by baruchiro** [python-telegram-bot/python-telegram-bot#1151]
I wrote an authentication function to my private bots, to control who can use the bot.
I thought to add it to this project, but there are 2 problems:

1. The bot should save a file, DB, to remember which user are authenticated.
2. The manager- the first user, should insert his id directly to code or DB.

**Comment by jsmnbom** [comment]
This is not currently in the scope of this project. We do provide our users with a simple way of doing this over on our wiki ([Code Snippets -> Restrict access to a handler (decorator)](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#restrict-access-to-a-handler-decorator)).

**Comment by jsmnbom** [comment]
Alright in that case.
I personally think it's okay to just have it on our wiki, but @python-telegram-bot/developers what do you guys think?

**Comment by JosXa** [comment]
I'm not sure a decorator is the right design pattern here. It feels like it should be something more integrated than that... Also, it might be hard to design a decorator in a way that it won't stop the execution of other handlers in the same group..?

**Comment by JosXa** [comment]
```
@roles(Role.Admin)
def callback(update, context): ...

dp.set_authorization(62056065, Role.Admin)
```
with the `@role` attribute picking and inserting itself into the dispatcher singleton?

**Comment by JosXa** [comment]
Design proposal:

- A `Role` can be any comparable object: `Enum`, custom class, ... It's just important that they implement the `__gt__`, `__lt__`, and `__eq__` methods.
- Dispatcher holds a mapping of `Dict[Role, List[UserID]` in `dispatcher.auth_roles`
- We'll provide a default `Enum` (or static class in 2.7) that defines `UserRole.Admin = 0`, `UserRole.Moderator = 10`, and `UserRole.None = 20` (dunno about the naming...)
- Set authorization for a group of users as follows: `dispatcher.auth_roles[UserRole.Admin] = [62056065, 1234567]`
- Default handler authorization wokrs by `*Handler(callback, ..., role=UserRole.Admin)`, where the default value is a very high number. All numbers lower than what the Handler defines will be applicable for the handler (so if you specify **UserRole.Moderator**, then Admins will also be able to access it).
- We'll also provide an `@auth` (or `@role`?) decorator that takes the dispatcher singleton and forces the dispatcher to do an additional check before executing the handler. Not quite sure how this should play together with the argument to *Handler, but in any case I think decorators would be good for code locality (i.e. "you immediately see whom a handler applies to).

Comments appreciated.

**Comment by icecom-dg** [comment]
A few suggestions:

- Higher roles should have higher `Enum` value: `UserRole.Banned = -10` can be used to ban abusive users if needed, `UserRole.Default = 0` (Using `None` might not be the best idea), `UserRole.Moderator = 10`, `UserRole.Admin = 20` and so on if there will be any higher roles.
- Allow a certain function to be executed every time before a permission check: can be used to update  `dispatcher.auth_roles` mapping according to a database for example.
- Maybe it will be easier to implement something like this using a `Filter`?

**Comment by JosXa** [comment]
I like those suggestions.

Filters for roles should be there, of course. I fail to understand the  custom function for role mappings so far, what stops you from simply adding it to the dispatcher?

**Comment by Eldinnie** [comment]
Is there anyone that is working on this, or any good reason to keep this open? Will close after 2 weeks without respons

**Comment by markusressel** [comment]
I needed this (and a couple other things) myself so i wrote a lib for that.
It's python 3.5+ only and uses the latest v12 beta of python-telegram-bot but if you are interested have a look:
https://github.com/markusressel/telegram-click

**Comment by Bibo-Joshi** [comment]
Because this was due to be closed 2 years ago and we recently decided to move #1789 to a contrib repo (see #1912), I'll go ahead and close this.
