### ISSUE TITLE
Thumbnail issue when sending video > 10MB

### ISSUE THREAD

**Issue by poustchi** [python-telegram-bot/python-telegram-bot#1155]
### Steps to reproduce

sent = bot.sendVideo(chat_id=CHANNEL_ID,  video=open(myvideofile.mp4, mode='rb'),  timeout=5000)

### Expected behaviour
Tell us what should happen

Video should upload with a thumbnail.

### Actual behaviour
Tell us what happens instead

Video uploads successfully but instead of thumbnail i will get a black square box. This problem happens when video file size > 10MB.
Videos withe less than 10MB shows the thumbnail correctly without any issue.

### Configuration
**Operating System:**
Windows 10 x64

**Version of Python, python-telegram-bot & dependencies:**

Python 3.6
PTB  10.1.0 - Latest version

**Comment by JosXa** [comment]
Hi @poustchi, could you send a failing video to @pythontelegrambotgroup and tag me (@JosXa)?

**Comment by jsmnbom** [comment]
Is there any chance that this has anything to do with the lib? It sounds a lot like a telegram issue to me?

**Comment by Eldinnie** [comment]
From chat we learned that video's with a file size larger then 10mb will not get a thumbnail. It's TG's choice, we can;t fix it with the wrapper.

**Comment by jsmnbom** [comment]
> Added support for attaching custom thumbnails to uploaded files. For animations, audios, videos and video notes, which are less than 10 MB in size, thumbnails are generated automatically.
This is now documented at https://core.telegram.org/bots/api#july-26-2018.
#1184 should allow setting custom thumbs for files < 10MB.
Closing issue as it's not a lib issue.
