### ISSUE TITLE
Cannot get updates for edited inline queries with '-' symbols

### ISSUE THREAD

**Issue by r0m4n-z** [python-telegram-bot/python-telegram-bot#1162]
Hi
I'm using 10.1.0 version for inline bot and have faced issues with updates for edited messages.

Here's steps to reproduce:
1. Run bot with handler InlineQueryHandler and some simple function just to catch updates.

2. Type a message to bot like "a -- b", but don't send it. Bot will receive update with inline_query and query text "a -- b".

3. Remove one of two "-" symbols to get "a - b". Bot will never receive second update while you will get both manually via POST\GET requests to .../getUpdates.

I've noticed such behavior only in case of "-". If you will try to replace one of "-" with any other symbol - bot will receive this update. If you replace it back to get "a -- b" - this update will not be received.

**Version of Python, python-telegram-bot & dependencies:**
$ python3 -m telegram
python-telegram-bot 10.1.0
certifi 2018.04.16
future 0.16.0
Python 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]

**Comment by jh0ker** [comment]
@r0m4n-z That's probably just a case of caching. By default, the inline query results for a particular query are cached for 5 minutes. You can change the cache_time parameter for answerInlineQuery to 0 to disable it.

**Comment by jh0ker** [comment]
@r0m4n-z It's possible that the caching is flawed, or that an old result was still cached. In any case, this is not an issue with this library and nothing we have any influence on.

**Comment by r0m4n-z** [comment]
Ok, thank you again
