### ISSUE TITLE
Useless else in ConversationHandler.update_state()

### ISSUE THREAD

**Issue by icecom-dg** [python-telegram-bot/python-telegram-bot#1163]
https://github.com/python-telegram-bot/python-telegram-bot/blob/d4b5bd40a5545a238ebd63f7ffcc1811691526b0/telegram/ext/conversationhandler.py#L320-L323

Should there be something?

**Comment by jsmnbom** [comment]
I think it might be to make 100% clear that it doesn't do anything if key isn't in self.conversations... A comment would probably be a better way to show that though...
@jh0ker, you got any idea?

**Comment by Eldinnie** [comment]
No Idea why it got added, but I think it can be safely removed...

**Comment by francamacdowell** [comment]
The issue isn't close, can I send a PR yet?
