### ISSUE TITLE
The error "The method you tried to invoke cannot be executed as a bot" when calling iter_messages

### ISSUE THREAD

**Issue by tracytaxa** [python-telegram-bot/python-telegram-bot#1164]
### Steps to reproduce
1.calling the method client.iter_messages(entity)
### Expected behaviour
the "iter_messages" function could be executed correctly

### Actual behaviour
error

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**
Python 3.7
the latest python-telegram-bot

### Logs
Insert logs here (if necessary)

**Comment by JosXa** [comment]
https://GitHub.com/lonamiwebs/telethon

**Comment by tsnoam** [comment]
@tracytaxa 
This is not python-telegram-bot API, you are welcome to go through our documentation http://python-telegram-bot.readthedocs.io/en/stable/ and install the library using `pip install python-telegram-bot`, but i'm closing this issue as it's not about this library.
