### ISSUE TITLE
ConversationHandler startpoint

### ISSUE THREAD

**Issue by szhyhalo** [python-telegram-bot/python-telegram-bot#1177]
### Steps to reproduce
1.` entry_points=[CommandHandler('start', start)]`

2. Call ReplyKeyboardMarkup in `start()` and handle it with RegexHandler

3. Use /start while working with bot.

### Expected behaviour
1. Function `start()` runs and returing CHOOSING to RegexHandler
2. RegexHundler should handle selected button

### Actual behaviour
After calling /start bot in not reacting at all.

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & 
`python-telegram-bot 10.1.0
certifi 2018.04.16
future 0.16.0
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)]`

**Comment by n5y** [comment]
Could you please provide a minimal working example of code required for steps 1 and 2?

**Comment by jsmnbom** [comment]
Hi!,

As @n5y stated, please provide some example code that shows the issue.

**Comment by Eldinnie** [comment]
3 weeks later I;m closing this issue for lack of respons from @szhyhalo
