### ISSUE TITLE
Using InlineKeyboardMarkup with one button without 2D list

### ISSUE THREAD

**Issue by BoberMod** [python-telegram-bot/python-telegram-bot#1186]
### Steps to reproduce
```
reply_markup = InlineKeyboardMarkup(InlineKeyboardButton(text="TEST_BUTTON", url="t.me/TEST"))
bot.send_message(chat_id=chat_id, text="TEST_MESSAGE", reply_markup=reply_markup)
```

### Expected behaviour
A message appears with the TEST_MESSAGE text and the TEST_BUTTON button
![image](https://user-images.githubusercontent.com/8740496/44001093-f87eaf7c-9e33-11e8-83b4-12e31357df8a.png)

### Actual behaviour
`KeyError: 0` because the markup needs a compulsory of a list within a list (even for one button).

### Configuration
**Operating System:** Win10 1803
**Version of Python, python-telegram-bot & dependencies:**
```
python-telegram-bot 10.1.0
certifi 2018.01.18
future 0.16.0
Python 3.6.2
```
### Logs
```
2018-08-12 12:42:19,317 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "E:\python362\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "E:\python362\lib\site-packages\telegram\ext\commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "E:\bobermod\bot.py", line 17, in start
    bot.send_message(chat_id=update.message.chat_id, text="TEST_MESSAGE", reply_markup=reply_markup)
  File "E:\python362\lib\site-packages\telegram\bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "E:\python362\lib\site-packages\telegram\bot.py", line 81, in decorator
    data['reply_markup'] = reply_markup.to_json()
  File "E:\python362\lib\site-packages\telegram\base.py", line 57, in to_json
    return json.dumps(self.to_dict())
  File "E:\python362\lib\site-packages\telegram\inline\inlinekeyboardmarkup.py", line 47, in to_dict
    for inline_keyboard in self.inline_keyboard:
  File "E:\python362\lib\site-packages\telegram\base.py", line 39, in __getitem__
    return self.__dict__[item]
KeyError: 0
```
### Improvement
It can be fixed by using list within a list:
`reply_markup = InlineKeyboardMarkup([[InlineKeyboardButton(text="TEST_BUTTON", url="t.me/TEST")]])`
**But it would be nice if it could be used with a single button without extra lists.**

**Comment by Eldinnie** [comment]
@python-telegram-bot/maintainers Do we want this?
It should support:
```
List[List[Button]]
List[Button]
Button
```
then. I personally think it;s not needed.

**Comment by tsnoam** [comment]
technically we don't mandate a list today, it can also be a generator if i recall correctly.
if i'm right - i vote to keep this functionality.
if i'm wrong - i like the 
```
List[List[Button]]
List[Button]
Button
```
suggestion

another approach would be:
```
InlineKeyboard.from_button(button)
InlineKeyboard.from_single_line(line: List[Button])
```
both will be class methods which will call `__init__()` with proper parameters.

**Comment by Lonami** [comment]
It's very convenient in my opinion, and I [personally would do](https://github.com/LonamiWebs/Telethon/blob/e5fc9d8674c36c4bb91451145e94e58fb676f85d/telethon/client/buttons.py#L28-L31) something like this:

```python
if not utils.is_list_like(buttons):
    buttons = [[buttons]]
elif not utils.is_list_like(buttons[0]):
    buttons = [buttons]
```
