### ISSUE TITLE
Is it possible to echo all types of messages?

### ISSUE THREAD

**Issue by alisherafat01** [python-telegram-bot/python-telegram-bot#1195]
I need to echo all types of received message (photo , text , sticker, voice ,...) in a simple way?
Is there a built in method?
`
dispatcher.add_handler(MessageHandler(Filters.all, echo))  

def echo(bot,update):
    # what to do here
`

**Comment by vasinkd** [comment]
You may try to use this method: https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html?highlight=bot#telegram.Bot.forward_message

Actually, there is a better place to ask questions about python-telegram-library: [Telegram chat](https://t.me/pythontelegrambotgroup) or [IRC Channel](https://webchat.freenode.net/?channels=##python-telegram-bot) if Telegram is unavailable for you.

**Comment by jsmnbom** [comment]
Other than forwarding as @vasinkd said, then not at the moment no.

**Comment by alisherafat01** [comment]
Thanks @vasinkd  that's good! but i want to forward messages without quoting the sender that i think is impossible so i should send all types of message manually :|
