### ISSUE TITLE
ssl module not found exception

### ISSUE THREAD

**Issue by nirsegev** [python-telegram-bot/python-telegram-bot#1196]
### Steps to reproduce
1. Use Python 2.7.9 which should be supported by the library

2. put this import line from telegram.ext import CommandHandler

### Expected behaviour
CommandHandler Import should work 

### Actual behaviour
as Updater.py imports ssl transitively we get ssl module not found as ssl library is not supporting Python 2.6+

### Configuration
**Operating System:**
linux

**Version of Python, python-telegram-bot & dependencies:**
Python 2.7.9

**Comment by Eldinnie** [comment]
@nirsegev I can not reproduce:
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from telegram.ext import dispatcher
>>>

**Comment by Eldinnie** [comment]
@nirsegev just to be sure. Python 2,7,9 is to old. in 2.7.11 changes to ssl were introducead

**Comment by nirsegev** [comment]
@Eldinnie thanks, I will check regarding the python versions. I also updated the issue it seems the CommandHandler is pointing to updater.py which requires ssl library. not dispatcher as I first mentioned

**Comment by nirsegev** [comment]
@Eldinnie issue is resolved. was a problem with app engine dependencies. thanks for the help.
