### ISSUE TITLE
Update wiki about Webhooks and host providers

### ISSUE THREAD

**Issue by pabluk** [python-telegram-bot/python-telegram-bot#1205]
I don't know if I need to open an issue in order to update the Wiki, but I didn't find anything about wiki pages on the contributing guidelines.

I just want to update this page https://github.com/python-telegram-bot/python-telegram-bot/wiki/Where-to-host-Telegram-Bots to add another option to decide where to host a Telegram bot.

Now it's easier to deploy a bot on any serverless provider using Webhooks so I've written an article about that and maybe it can be useful for someone else.

**Comment by pabluk** [comment]
Here's my change https://github.com/python-telegram-bot/python-telegram-bot/wiki/Where-to-host-Telegram-Bots/_compare/2117b8ede7f7d3a86ada94bc91a8223aa4405a1c feel free to edit or change it if it's not appropriate.

**Comment by jsmnbom** [comment]
Thank you a lot for that addition. Normally we simply allow people to update the wiki with relavant information so good call on doing that! :D
