### ISSUE TITLE
Typo in comment in conversationbot2.py

### ISSUE THREAD

**Issue by freelancervvp** [python-telegram-bot/python-telegram-bot#1210]
### Steps to reproduce
1. Not really a bug... wrong comment line in conversationbot2.py :)

### Expected behaviour
Should be: # Add conversation handler with the states CHOOSING, TYPING_CHOICE and TYPING_REPLY

### Actual behaviour
Actual comment in conversationbot2.py (leftover from conversationbot.py I guess :))
# Add conversation handler with the states GENDER, PHOTO, LOCATION and BIO

### Configuration
**Operating System:**
Windows

**Version of Python, python-telegram-bot & dependencies:**
3.6

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by marcelogdeandrade** [comment]
I will work on this just to start contributing to the project.

**Comment by jsmnbom** [comment]
Great! :D Nice to have you :)

Just write on the telegram group if you need help setting up the development environment :D

**Comment by marcelogdeandrade** [comment]
Hello, I fixed the requested comment and opened a PR but it seems that the CI test didn't pass, which is really strange because I just changed a simple comment on one file. Could you help me understand what went wrong on the test? Thanks!
