### ISSUE TITLE
Can python-telegram-bot use MTProxy?

### ISSUE THREAD

**Issue by kevin9010** [python-telegram-bot/python-telegram-bot#1219]
I can't find the introduction of MTProxy in the python-telegram-bot Doc., Can this lib use MTProxy while using Updater?

**Comment by Daniel-Shu** [comment]
> As far as we know MTProxy is only supported by Telegram clients and not for the Bot API.

3Q! Maybe for the safety?

**Comment by MohammadSalek** [comment]
Is it still not possible to use MTProxy? If not, may I create an issue for it as feature request?

**Comment by Poolitzer** [comment]
@MohammadSalek I am not sure about the definitions of a MTProxy. But what stops you from using just a normal SOCKS proxy

**Comment by MohammadSalek** [comment]
@Poolitzer  "MTProto" is what it was meant. I did a mistake copying the title of this issue . Which I think it is was also meant to be MTProto.

**Comment by Poolitzer** [comment]
Then its not even related to this and no, this is a bot api wrapper. This is not going to change :)
