### ISSUE TITLE
Cannot import bot from telegram anymore

### ISSUE THREAD

**Issue by MarcelBeining** [python-telegram-bot/python-telegram-bot#1223]
Hi, a few days ago I installed the google library for dealing with youtube. Since then I get an error when doing "from telegram import bot"
### Steps to reproduce
1. pip install --upgrade google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

2. Start python on Spyder. 

3. type `from telegram import bot`

### Expected behaviour
Just import the bot as normal (was working before).

### Actual behaviour
The following error occurs: 
   

>  from telegram import (ReplyKeyboardMarkup,InlineKeyboardMarkup,InlineKeyboardButton,bot)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\telegram\__init__.py", line 101, in <module>
>     from .bot import Bot
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\telegram\bot.py", line 42, in <module>
>     from telegram.utils.request import Request
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\telegram\utils\request.py", line 36, in <module>
>     import telegram.vendor.ptb_urllib3.urllib3.contrib.appengine as appengine
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\contrib\appengine.py", line 63, in <module>
>     from google.appengine.api import urlfetch
> 
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
> 
>   File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
> 
>   File "<frozen importlib._bootstrap>", line 890, in _find_spec
> 
>   File "<frozen importlib._bootstrap>", line 864, in _find_spec_legacy
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 253, in find_module
>     fp, pathname, (ext,mode,ty) = imp.find_module(fullname,package_path)
> 
>   File "C:\ProgramData\Anaconda3\lib\imp.py", line 271, in find_module
>     "not {}".format(type(path)))
> 
> RuntimeError: 'path' must be None or a list, not <class '_frozen_importlib_external._NamespacePath'>
> 

### Current solution
- Add class RunTimeError to the catched exceptions in site-packages\telegram\vendor\ptb_urllib3\urllib3\contrib\appengine.py

### Configuration
**Operating System:**
Windows 10 64 bit
Spyder

**Version of Python, python-telegram-bot & dependencies:**

python-telegram-bot 11.1.0
certifi 2018.04.16
future 0.16.0
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]

**Comment by MarcelBeining** [comment]
> ehm..
> 
> I'm not very used to this. But it seems that this line is giving you trouble:
> `from google.appengine.api import urlfetch`
> Can you try running that? It's weird that it does not give an importerror though

Yes, that line is what I am currently catching by catching RunTimeError.
When I simply run only this line I get:

> Traceback (most recent call last):
> 
>   File "<ipython-input-103-2d7b139e8a2d>", line 1, in <module>
>     from google.appengine.api import urlfetch
> 
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
> 
>   File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
> 
>   File "<frozen importlib._bootstrap>", line 890, in _find_spec
> 
>   File "<frozen importlib._bootstrap>", line 864, in _find_spec_legacy
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pyximport\pyximport.py", line 253, in find_module
>     fp, pathname, (ext,mode,ty) = imp.find_module(fullname,package_path)
> 
>   File "C:\ProgramData\Anaconda3\lib\imp.py", line 271, in find_module
>     "not {}".format(type(path)))
> 
> RuntimeError: 'path' must be None or a list, not <class '_frozen_importlib_external._NamespacePath'>

**Comment by Eldinnie** [comment]
It seems to me it's a problem of your env or anaconda's config. Canyou try it in a clean env?

**Comment by MarcelBeining** [comment]
Hm interesting, when I run it from command line (Windows) it says

> from google.appengine.api import urlfetch
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'google.appengine'

`import google` works but` import google.apiengine` not

**Comment by MarcelBeining** [comment]
Ok I found the problem, which is that Spyder calls pyximport.install(), in its file sitecustomize.py.
The current solution is to comment out line 189 in this file (`pyximport.install(setup_args=pyx_setup_args, reload_support=True)`) and restart Spyder
See these threads:
https://github.com/spyder-ide/spyder/issues/5299
https://stackoverflow.com/questions/46422488/get-rid-of-pyximport

Thanks for your answers and sorry for blaming python-telegram-bot :-)

**Comment by Eldinnie** [comment]
Good to know. Thanks!
