### ISSUE TITLE
Underlining text for chat messages no longer possible?

### ISSUE THREAD

**Issue by tr91** [python-telegram-bot/python-telegram-bot#1224]
Tried to use the `<u>text</u>` html formatting to no avail. I assume it's gone since html5 no longer has it built in unfortunately?

**Comment by nmlorg** [comment]
https://core.telegram.org/bots/api#formatting-options

**Comment by jsmnbom** [comment]
It's not possible to underline text in telegram, this has nothing to do with the library, and I'm therefore gonna close this issue ^^
