### ISSUE TITLE
test.py loaded and executed if it's in same directory without actual load/execute

### ISSUE THREAD

**Issue by bissei** [python-telegram-bot/python-telegram-bot#1225]
### Steps to reproduce
1. create _test.py_ file and insert there following code:
`#!/usr/bin/python3`
`print("HELLO FROM test.py FILE!")`

2. create another file in same directory, let's call it _tele.py_ and insert there following code:
`#!/usr/bin/python3`
`from telegram.ext import CommandHandler, MessageHandler, Filters, RegexHandler, Updater`

3. execute _tele.py_ and it will run also _test.py_ file. You can also do `chmod 000 test.py` and it will still run it.

### Expected behaviour
Nothing, as _tele.py_ does not do nothing

### Actual behaviour
_test.py_ file will be executed

### Configuration
**Operating System:**
Manjaro & Ubuntu 18.04

**Version of Python, python-telegram-bot & dependencies:**
Ubuntu: Python 3.6.6
Manjaro: Python 3.7.0
python-telegram-bot-10.1.0

### Notice
This happen only with Python 3, not with Python 2.

**Comment by jsmnbom** [comment]
This was previously submitted as #945, and subsequently dismissed.
The upstream issue is in `python-future`: https://github.com/PythonCharmers/python-future/issues/268

I think there might be a workaround we can do though. It seems we only use `future.backports` one place so we could probably replace that.
https://github.com/python-telegram-bot/python-telegram-bot/blob/09bdb8882273c6889633510e8bed99619c327c4e/telegram/files/file.py#L23

**Comment by tsnoam** [comment]
Honestly, I don't think we need to track this or fix it.
We can document it in the wiki, though.

**Comment by Eldinnie** [comment]
seeing as this is an issue with the future library I think we can close this issue
