### ISSUE TITLE
sendVideo tests fail in travis when using pypy

### ISSUE THREAD

**Issue by jsmnbom** [python-telegram-bot/python-telegram-bot#1229]
### Steps to reproduce
1. Use pypy in travis

2. Run the test_video tests

### Expected behaviour
Tests should pass

### Actual behaviour
Tests time out for some odd reason
`NetworkError: urllib3 HTTPError [SSL] PEM lib`

### Logs
https://travis-ci.org/python-telegram-bot/python-telegram-bot/jobs/435517879#L1998

(it has happened for a while now, opening a issue so as to track it better :))

**Comment by Bibo-Joshi** [comment]
Closing since we moved to Github Actions
