### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'chat'

### ISSUE THREAD

**Issue by MedourMehdi** [python-telegram-bot/python-telegram-bot#1244]
### Steps to reproduce

1. SaltStack calling python-telegram library (using beacons)
2. Send messages to bot account and edit it (maybe before it's received by the server).

### Expected behaviour

Receive data from Telegram

### Actual behaviour

Debug show this trace:

> 2018-10-05 17:07:28,740 [salt.minion      :2494][CRITICAL][17641] The beacon errored:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 2492, in handle_beacons
>     beacons = self.process_beacons(self.functions)
>   File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 444, in process_beacons
>     return self.beacons.process(b_conf, self.opts['grains'])  # pylint: disable=no-member
>   File "/usr/lib/python2.7/dist-packages/salt/beacons/__init__.py", line 112, in process
>     raw = self.beacons[fun_str](b_config[mod])
>   File "/usr/lib/python2.7/dist-packages/salt/beacons/telegram_bot_msg.py", line 98, in beacon
>     if message.chat.username in _config['accept_from']:
>   AttributeError: 'NoneType' object has no attribute 'chat'

 Because we receive 

> {'edited_message': {'delete_chat_photo': False, 'new_chat_photo': [], 'edit_date': 1
> 538748845, 'from': {'username': u'xxxxx', 'first_name': u'xxxx', 'last_name': u'xxxx', 'is_bot': False, 'language_code': u'en-US', 'id': xxxx}, 'text': u'test', 'caption_entities': [], 'entities': [{'length': 20, 'type': u'email', 'offset': 10}], 'channel_chat_created': False, 'new_chat_members': [], 'supergroup_chat_created': False
> , 'chat': {'username': u'mmedour', 'first_name': u'xxxx', 'last_name': u'xxxx', 'type': u'private', 'id': xxxxxx}, 'photo': [], 'date': 1538748758, 'group_chat_created': False, 'm
> essage_id': 14}, 'update_id': 658994597}

### Configuration
**Operating System:**

Ubuntu 16.04

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

```python-telegram-bot 11.1.0
certifi 2018.08.24
future 0.16.0
Python 2.7.12 (default, Dec  4 2017, 14:50:18)  [GCC 5.4.0 20160609]
```

My fix:

/usr/lib/python2.7/dist-packages/salt/beacons/telegram_bot_msg.py,  line 91:

```
    for update in updates:
        if update.message:
          message = update.message
        else:
          message = update.edited_message

        log.debug('DEBUG PERSO %s', update.message)

        if update.update_id > latest_update_id:
            latest_update_id = update.update_id

        if message.chat.username in _config['accept_from']:
            output['msgs'].append(message.to_dict())
```

**Comment by jsmnbom** [comment]
This isn't a bug with the library as far as I can see.
You get an AttributeError because `.message` is none, because you received a `.edited_message` instead. You're probably looking for `.effective_message` which will be either a message or edited_message.

**Comment by jsmnbom** [comment]
I see now that didn't actually write the code that errored. I urge you to report this issue upstream with the SaltStack team.

**Comment by MedourMehdi** [comment]
Ok i'll do,

Many thanks.

**Comment by purwowd** [comment]
> This isn't a bug with the library as far as I can see.
> You get an AttributeError because `.message` is none, because you received a `.edited_message` instead. You're probably looking for `.effective_message` which will be either a message or edited_message.

my fix: 
change .message to .effective_message.

Thanks @jsmnbom
