### ISSUE TITLE
teelegram proxy error

### ISSUE THREAD

**Issue by Und3rCover96** [python-telegram-bot/python-telegram-bot#1245]
i have this error when i try use sock5 proxy in my code :+1: 

   update = Updater(TOKEN,request_kwargs=proxyset)
  File "/home/undercover/.local/share/virtualenvs/All_in_One-NwKWv0l6/lib/python3.6/site-packages/telegram/ext/updater.py", line 127, in __init__
    self._request = Request(**request_kwargs)
TypeError: __init__() got an unexpected keyword argument 'username'

**Comment by Eldinnie** [comment]
Hi, please see here
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Working-Behind-a-Proxy
