### ISSUE TITLE
AttributeError: type object 'ConversationHandler' has no attribute 'conversations'

### ISSUE THREAD

**Issue by Aidaho12** [python-telegram-bot/python-telegram-bot#1253]
### Steps to reproduce
1. Add save state snippet as told in man: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#store-conversationhandler-states

2.  Add import:
```
from telegram.ext import ConversationHandler as conv_handler
```

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
 python3 -m telegram
python-telegram-bot 11.1.0
certifi 2018.08.24
future 0.16.0
Python 3.4.8 (default, Jul 25 2018, 22:08:49)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
### Logs
```
^C2018-10-12 22:04:38,701 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
Data file not found
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "./bot2.py", line 818, in saveData
    for k, v in conv_handler.conversations.items():
NameError: name 'conv_handler' is not defined
```

Code:
```
def main():
...
	updater.idle()
	
	def loadData():
		try:
			f = open('conversations', 'rb')
			conv_handler.conversations = pickle.load(f)
			f.close()
			f = open('userdata', 'rb')
			dp.user_data = pickle.load(f)
			f.close()
		except FileNotFoundError:
			print("Data file not found")         
		except:
			print(sys.exc_info()[0])         
 
	def saveData():
		while True:
			time.sleep(10)
			# Before pickling
			resolved = dict()
			for k, v in conv_handler.conversations.items():
				if isinstance(v, tuple) and len(v) is 2 and isinstance(v[1], Promise):
					try:
						new_state = v[1].result()  # Result of async function
					except:
						new_state = v[0]  # In case async function raised an error, fallback to old state
					resolved[k] = new_state
				else:
					resolved[k] = v
			try:
				f = open('conversations', 'wb+')
				pickle.dump(resolved, f)
				f.close()
				f = open('userdata', 'wb+')
				pickle.dump(dp.user_data, f)
				f.close()
			except:
				print(sys.exc_info()[0])
	loadData()
	threading.Thread(target=saveData).start()
	
	
if __name__ == '__main__':
	main()
```

Hi! What do I wrond? (

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
