### ISSUE TITLE
User.markdown_mention produces wrong markdown

### ISSUE THREAD

**Issue by Sil3ntStorm** [python-telegram-bot/python-telegram-bot#1254]
### Steps to reproduce
1. have your display name (first_name and / or last_name) include brackets like `[foo]`

2. Send a message containing to return value of `update.message.from_user.mention_markdown()` with markdown parsing

### Expected behavior
A link to the user with the user display name as the link text should be sent.

### Actual behavior
The link is broken. For example `Test [Bot]` turns into `[Test \[Bot]](tg://user?id=123456789)` which will be rendered as `Test \[Bot](tg://user?id=123456789)` instead of being rendered as `Test [Bot]` linked.

### Configuration
**Operating System:**
Docker based on python:latest on a Windows 10 host.

**Version of Python, python-telegram-bot & dependencies:**

current master

**Comment by Eldinnie** [comment]
the `mention_markdown` method works as expected. If you insist on using markdown it's on you to escape the `name` argument. We even added a helper for it in `utils.helpers.escape_markdown`

**Comment by Sil3ntStorm** [comment]
Except that the mention_markdown is already calling the escape_markdown utils function.
