### ISSUE TITLE
Timed out bootstrap del webhook

### ISSUE THREAD

**Issue by licht1stein** [python-telegram-bot/python-telegram-bot#1256]
Bot stopped working, please help. I've been working on this project for 6 months.

### Steps to reproduce
1. Bot stopped working without me changing anything in the source code. It stopped working both on server and locally, and switching bots doesn't help.

### Expected behaviour
Bot should start polling for updates.

### Actual behaviour
I receive repeated errors:

10-14 01:40:37 telegram.vendor.ptb_urllib3.urllib3.connectionpool DEBUG    Starting new HTTPS connection (5): api.telegram.org
10-14 01:40:43 telegram.ext.updater DEBUG    Timed out bootstrap del webhook: Timed out

### Configuration
Local: Windows 10
Remote: Ubuntu Server 18.04

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
python-telegram-bot 11.1.0
certifi 2018.08.24
future 0.16.0
Python 3.6.6 

### Logs
10-14 01:40:13 docker.utils.config DEBUG    Trying paths: ['C:\\Users\\MB\\.docker\\config.json', 'C:\\Users\\MB\\.dockercfg']
10-14 01:40:13 docker.utils.config DEBUG    Found file at path: C:\Users\MB\.docker\config.json
10-14 01:40:13 docker.auth  DEBUG    Found 'auths' section
10-14 01:40:13 docker.auth  DEBUG    Auth data for 968029870820.dkr.ecr.eu-central-1.amazonaws.com is absent. Client might be using a credentials store instead.
10-14 01:40:13 docker.auth  DEBUG    Found 'credsStore' section
10-14 01:40:14 root         WARNING  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
10-14 01:40:15 root         WARNING  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
10-14 01:40:15 root         WARNING  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
10-14 01:40:16 root         WARNING  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
10-14 01:40:16 root         WARNING  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
10-14 01:40:16 root         WARNING  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
10-14 01:40:16 telegram.ext.dispatcher DEBUG    Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x000002AEEBEAB0B8>
10-14 01:40:16 JobQueue     DEBUG    JobQueue thread started
10-14 01:40:16 telegram.ext.updater DEBUG    dispatcher - started
10-14 01:40:16 telegram.ext.updater DEBUG    updater - started
10-14 01:40:16 telegram.ext.updater DEBUG    Updater thread started (polling)
10-14 01:40:16 telegram.ext.updater DEBUG    Start network loop retry bootstrap del webhook
10-14 01:40:16 telegram.bot DEBUG    Entering: delete_webhook
10-14 01:40:16 telegram.vendor.ptb_urllib3.urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.telegram.org
10-14 01:40:16 telegram.ext.dispatcher DEBUG    Dispatcher started
10-14 01:40:16 app.py       INFO     UFY Bot v3.0: Started at 01:40:16 in development mode. Database: api_dev
10-14 01:40:22 telegram.ext.updater DEBUG    Timed out bootstrap del webhook: Timed out
10-14 01:40:22 telegram.bot DEBUG    Entering: delete_webhook
10-14 01:40:22 telegram.vendor.ptb_urllib3.urllib3.connectionpool DEBUG    Starting new HTTPS connection (2): api.telegram.org
10-14 01:40:27 telegram.ext.updater DEBUG    Timed out bootstrap del webhook: Timed out
10-14 01:40:27 telegram.bot DEBUG    Entering: delete_webhook

**Comment by jsmnbom** [comment]
Telegram servers are currently experiencing a bit of a hick up. Nothing we can do about this, sorry, you'll just have to wait :)

**Comment by licht1stein** [comment]
Thank you!
