### ISSUE TITLE
Make it easier to handle webhooks manually, by providing a convience setup method for dispatcher

### ISSUE THREAD

**Issue by jsmnbom** [python-telegram-bot/python-telegram-bot#1258]
Sometimes you need not just webhooks from telegram, but from other services too. It would be nice if we could integrate this nicely into the library, without forcing users to not use Updater (which means handling threading, jobqueue starting, and of cause webhooks themselves).

As this is still very much an advanced feature, I think a good way of doing this could be to allow passing a custom `WebhookAppClass` to `Updater._start_webhook` somehow.

https://github.com/python-telegram-bot/python-telegram-bot/blob/eca0ccf6b376699ffcc7816d4db7e91b205a4fdd/telegram/ext/updater.py#L357-L365

For example to also receive webhooks from github one could write a custom GithubWebhookHandler (instance of `tornado.web.RequestHandler` that perhaps turns incomming data into a `GithubUpdate` type that a `TypeHandler` can then handle) and then a [WebhookAppClass](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/utils/webhookhandler.py#L71-L79) like:
``` python
class WebhookAppClass(tornado.web.Application):
    def __init__(self, webhook_path, bot, update_queue):
        handlers = [
            (
                r'/github/?',
                GithubWebhookHandler,
                {'update_queue': update_queue}
            ),
            (
                r"{0}/?".format(webhook_path),
                telegram.utils.webhookhandler.WebhookHandler,
                {'bot': bot, 'update_queue': update_queue}
            )
        ]
        super().__init__(handlers)
```

The only way this is currently possible to do is something like
```
telegram.utils.webhookhandler.WebhookAppClass = WebhookAppClass
```
But as that line needs to come before any `telegram` imports, it makes it quite messy.

**Comment by jsmnbom** [comment]
So after discussing this a lot in our developer chat, we have decided to go about it differently.
Instead of the above, we are gonna provide a method that sets up and configures a Dispatcher, including setting up a JobQueue (if desired), an update queue, a Request instance, and of cause a Bot.
This makes it a lot easier to integrate with other webhook solutions (and therefore adding additional services), as configuring Dispatcher was the difficult job before.

**Comment by JosXa** [comment]
I take it it was meant more as a joke, but the factory/builder pattern might indeed come in handy for the purpose of creating all these instances with their specific settings and the option to start threads immediately or delayed.

**Comment by Curiouspaul1** [comment]
> So after discussing this a lot in our developer chat, we have decided to go about it differently.
> Instead of the above, we are gonna provide a method that sets up and configures a Dispatcher, including setting up a JobQueue (if desired), an update queue, a Request instance, and of cause a Bot.
> This makes it a lot easier to integrate with other webhook solutions (and therefore adding additional services), as configuring Dispatcher was the difficult job before.

So is this ready yet?.. If not what options are available at the moment

**Comment by Bibo-Joshi** [comment]
Catching up on this old issue, I had the following idea:

`tornade.web.Application` already has the `add_handlers` method, so we can leverage that. Sketch of my idea:

* Provide a `PTBRequestHandler` (or whatever naming) along the lines

```python
class PTBRequestHandler(tornado.web.RequestHandler):
     update_queue: CassVar[Queue] = None

     @classmethod
     def set_update_queue(cls, uq):
        cls.update_queue = uq
```

* make the `app` currently set here:

https://github.com/python-telegram-bot/python-telegram-bot/blob/9ddb361f761abd34b9cbc03a15251a84a9abdb11/telegram/ext/updater.py#L519

  a instance attribute
* add `Updater.add_webhook_handlers(handlers: List[PTBRequestHandler])` as wrapper around `self.app.add_handlers` that also takes care of calling `PTBRequestHandler.set_update_queue`.

That way users can implement their own handler and just call `self.update_queue.put(update)`. Alternatively one could skip the part with `PTBRequestHandler` and make the user manually pass `updater.update_queue` at the right spot in `Updater.add_webhook_handlers`

We can still provide a `Dispatcher.build()` (or whatever) class-method that provides all missing optional args of `__init__`. Can indeed be useful for customized webhook solutions, where `Updater` isn't used.

**Comment by Bibo-Joshi** [comment]
In v20 (pre-released was published recently), setting up a custom setup for fetching updates via webhooks has become way easier (with `ApplicationBuilder` basically addressing https://github.com/python-telegram-bot/python-telegram-bot/issues/1258#issuecomment-429764087), which also allows to handle updates from external services. #3059 linked above adds an example for such a setup that also showcases how handling of custom updates can be done. We are therefore not planning to integrate such a functionality directly into the library and recommend to leverage the improved flexibility of the `telegram.ext` framework instead :)
