### ISSUE TITLE
webhook config not set with proxy

### ISSUE THREAD

**Issue by alirezaimi** [python-telegram-bot/python-telegram-bot#1263]
### Steps to reproduce
I use this config for set webhook for my bot with custom cert behind nginx,

	updater = Updater(botToken, workers=15, request_kwargs={
								'proxy_url': 'socks5h://127.0.0.1:9050/'
							})  
	 
	updater.start_webhook(listen='127.0.0.1',
						  port=5664,
						  url_path=botToken)

	updater.bot.set_webhook(url='https://XXX.XXX.XXX.XXX:8443/' + botToken,
							certificate=open('./cert.pem', 'rb'),
							max_connections=100)
	updater.idle()

Since i live in iran and iranian gov blocked telegram in iran i must use proxy that i use tor for this matter, 
is set_webhook method use proxy config ?
with long-polling i have no problem with proxy but webhook not set at all .
######################

### Expected behaviour
Set webhook.

### Actual behaviour
When i check it with `https://api.telegram.org/botXX:XXXX/getWebhookInfo` the url field is empty .

### Configuration
`linux debian testing`

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

	python-telegram-bot 11.1.0
	certifi 2018.01.18
	future 0.16.0
	Python 3.6.4 (default, Jan  5 2018, 02:13:53)  [GCC 7.2.0]

### Logs
None.

**Comment by ratijas** [comment]
May I reopen this one?
