### ISSUE TITLE
telegram.Update.inline_query does not share location on IOS

### ISSUE THREAD

**Issue by lmediavilla** [python-telegram-bot/python-telegram-bot#1265]
### Steps to reproduce
1. Create an inline bot that has request location enabled

2. use an inlinequery handler

3. On IOS the update inline_query doesn't have the location added

### Expected behaviour
this is running an inline bot on android
update.inline_query -> {'id': '32029897195563526', 'query': 'bicis', 'offset': '', **'location': {'longitude': -1.927914, 'latitude': 36.616403}**, 'from': {'id': 7457549, 'first_name': user, 'is_bot': False, 'username': ufser, 'language_code': 'es'}}

### Actual behaviour
This is the operation in IOS 12
update.inline_query -> {'id': '32029896872472380', 'query': 'bicis', 'offset': '', 'from': {'id': 7457541, 'first_name': 'user', 'is_bot': False, 'username': 'user', 'language_code': 'es-ES'}}

### Configuration
**Operating System:**
IOS 12 everything allowed, the bot has inline location allowed

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 11.1.0
certifi 2018.08.24
future 0.16.0
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]

### Logs
Insert logs here (if necessary)

**Comment by jsmnbom** [comment]
This is unfortunately not a bot with our library. We know this since we don't interact with the mobile OS whatsoever, the library merely communicates with the bot API.
You will probably have more success reporting this bug with the telegram iOS developers.

**Comment by midianet** [comment]
I have the same project
