### ISSUE TITLE
TelegramError: HTTP Error 502: Bad Gateway

### ISSUE THREAD

**Issue by tukhfatov** [python-telegram-bot/python-telegram-bot#128]
Please see the attached screen file 
![713235274_972_7336077732516321034](https://cloud.githubusercontent.com/assets/2496303/11894829/a327ab02-a59b-11e5-8a7d-476a720df4a5.jpg)

**Comment by rahiel** [comment]
You have to catch that exception, look at the exception handling in [this example](https://github.com/python-telegram-bot/python-telegram-bot/blob/9e7314134e786eb8589b01d7218991e42acc8c03/examples/echobot.py#L48). I recommend to base your bot on that example.

**Comment by jh0ker** [comment]
@rahiel is right, that should take care of it.
