### ISSUE TITLE
Inlinequery example bot not working

### ISSUE THREAD

**Issue by hubwoop** [python-telegram-bot/python-telegram-bot#1286]
### Steps to reproduce
1. Copy inlinequery example to new project from https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/inlinebot.py

2. Start Bot

3. Try to use inline query via @name_of_bot 

### Expected behaviour
Suggestions which inline commands are available should be shown

### Actual behaviour
Nothing

### Configuration
**Operating System:**
System Version: macOS 10.13.2 (17C88)
Kernel Version: Darwin 17.3.0
      

**Version of Python, python-telegram-bot & dependencies:**
Python 3.6

Package             Version   
------------------- ----------
asn1crypto          0.24.0    
certifi             2018.10.15
cffi                1.11.5    
chardet             3.0.4     
cryptography        2.3.1     
future              0.17.1    
idna                2.7       
Pillow              5.2.0     
pip                 18.1      
pony                0.7.6     
pycparser           2.19      
python-telegram-bot 11.1.0    
requests            2.19.1    
setuptools          28.8.0    
six                 1.11.0    
urllib3             1.23      

``$ python -m telegram``
python-telegram-bot 11.1.0
certifi 2018.10.15
future 0.17.1
Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13)  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

### Logs
```
2018-11-04 10:05:09,872 - telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update
2018-11-04 10:05:09,872 - __main__ - WARNING - Update "{'update_id': 284154945, 'inline_query': {'id': '1234567890', 'query': '', 'offset': '', 'from': {'id': 1234567890, 'first_name': 'USER', 'is_bot': False, 'username': 'USERNAME', 'language_code': 'de'}}}" caused error "Input message content is not specified"
```

**Comment by tsnoam** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
