### ISSUE TITLE
Code snippet "Send a chat action" does not work with states in ConversationHandler

### ISSUE THREAD

**Issue by artemrys** [python-telegram-bot/python-telegram-bot#1288]
### Steps to reproduce
1. Create a ConversationHandler
2. Copy&paste code snippet [Send a chat action](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#send-a-chat-action)
3. Decorate some function from `states` with `send_typing_action` decorator.

### Expected behaviour
Telegram should show typing, then exectue state function code

### Actual behaviour
Nothing happens

### Configuration
**Operating System:**
MacOS 10.14

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
python-telegram-bot 11.1.0
certifi 2018.04.16
future 0.17.1
Python 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 11:07:29)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

### Code
Set environment variable `TELEGRAM_BOT_TOKEN`
```python
import os
import time
from functools import wraps

from telegram import ChatAction
from telegram.ext import Updater, CommandHandler, ConversationHandler


def send_typing_action(func):
    """Sends typing action while processing func command."""

    @wraps(func)
    def command_func(*args, **kwargs):
        bot, update = args
        bot.send_chat_action(chat_id=update.message.chat_id, action=ChatAction.TYPING)
        func(bot, update, **kwargs)

    return command_func


STATES = range(0)


@send_typing_action
def start(bot, update):
    time.sleep(1)
    update.message.reply_text("You have pressed /start. Go to /state")
    return STATES


@send_typing_action
def state(bot, update):
    time.sleep(1)
    update.message.reply_text("Ok")
    return ConversationHandler.END


@send_typing_action
def help(bot, update):
    time.sleep(1)
    update.message.reply_text("You have pressed /help")


conversation_handler = ConversationHandler(
    entry_points=[CommandHandler("start", start)],
    states={
        STATES: [CommandHandler("state", state)]
    },
    fallbacks=[],
)


def main():
    # Create the Updater and pass it your bot's token.
    TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")

    updater = Updater(TOKEN)

    updater.dispatcher.add_handler(conversation_handler)
    updater.dispatcher.add_handler(CommandHandler("help", help))

    # Start the Bot
    updater.start_polling()

    # Run the bot until the user presses Ctrl-C or the process receives SIGINT,
    # SIGTERM or SIGABRT
    updater.idle()


if __name__ == '__main__':
    main()
```

**Comment by jsmnbom** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
