### ISSUE TITLE
reply_to_message_id not available in bot.py functions eventhough described in docstring

### ISSUE THREAD

**Issue by TheCroak** [python-telegram-bot/python-telegram-bot#129]
Hey, I was wondering for a while, why isn't reply_to_message_id available as an argument for methods in bot.py eventhough it is described in the the docstring ? I had to fork and modify bot.py to add the reply_to_message_id to the arguments list

**Comment by leandrotoledo** [comment]
For which function? The @message decorator at top of send* functions parses the **kwargs, and includes handling reply_to_message_id, reply_markup and so on. So it should be working, we did like this to avoid repeated coded for all those functions, even though we kept docstring to list off the possible args even through **kwargs 

Usage: sendMessage(-0123, 'ABC', reply_to_message_id=12345)

**Comment by TheCroak** [comment]
Eh, weird, I swear remembering having troubles having it work. I just tested it and it is fine. I was probaly doing something wrong at the time

Nevermind

**Comment by leandrotoledo** [comment]
No worries at all.
Thanks for using this!
