### ISSUE TITLE
Update.inline_query bug

### ISSUE THREAD

**Issue by Golova1111** [python-telegram-bot/python-telegram-bot#1291]
Hello!
How can I check with `pattern` in InlineQueryHandler, that my query is empty?

In your code in `check_update` method I find next:

 ```
if isinstance(update, Update) and update.inline_query:
            if self.pattern:
                if update.inline_query.query:
                    match = re.match(self.pattern, update.inline_query.query)
                    return bool(match)
            else:
                return True
```

It's mean, that if string is empty (have a falsy value) you'll return None. Is it really predictable behaviour? Maybe, you should fix it.
Thanks!

**Comment by jsmnbom** [comment]
Just use a pattern like `^$`.
^ means start of line and $ means end.
