### ISSUE TITLE
Telegram API for getFile function

### ISSUE THREAD

**Issue by nournia** [python-telegram-bot/python-telegram-bot#130]
Hi,
I wanted to use `getFile` function for retrieving files from telegram server. In [API documentation page for this function](https://core.telegram.org/method/upload.getFile) it needs [InputFileLocation](https://core.telegram.org/type/InputFileLocation) object which consists of three values: `volume_id`, `local_id` and `secret`.

I have these three values for files that I want to download, but in `python-telegram-bot`, `getFile` function uses `file_id` that to me seems kind of hashed value of those three variables. Is it possible, to fetch url of one file using its `InputFileLocation` object?

**Comment by rahiel** [comment]
Those docs are of the Telegram API, this library is only a wrapper around the [bot API](https://core.telegram.org/bots/api#getfile) (see difference [here](https://core.telegram.org/api)). 

In this library: if a user sends a bot a file, the bot receives a `file_id` it can then use to download the file with the `bot.getFile` method.

**Comment by nournia** [comment]
Thanks.
