### ISSUE TITLE
Hi everybody! how can i create telegramm bot for sending photo by requests

### ISSUE THREAD

**Issue by avazdev** [python-telegram-bot/python-telegram-bot#1310]
### Steps to reproduce
1.

2.

3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by avazdev** [comment]
for example: if we send a message to bot by command "/car"  bot must send us a photo by link which we linked "car.jpg"
and how i can link a photo 
i have  just started to learn Python
could you give me a simple examples

**Comment by Bibo-Joshi** [comment]
Hey!
If you are new to Python, you might wanna start with an [introduction to the language](https://www.python.org/about/gettingstarted/) and head over to the [tutorial](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-Your-first-Bot) afterwards.
E.g. your specific questions ins answered [here](https://t.me/pythontelegrambotgroup).

For questions about the library, there is also a [Telegram group](https://t.me/pythontelegrambotgroup).
