### ISSUE TITLE
Enhancement: global memory

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#1318]
It would be lovely to have a global, persistable memory available. That is, add an attribute `global_data` or such to the `Dispatcher` class, that can be passed to handlers and is integrated in persistence.
This would make it easy to process stuff that can be changed by multiple different chats.

Putting this here, because I don't know when/if I will be able to open a PR. If someone is faster than me, please don't hesitate ;)

**Comment by jsmnbom** [comment]
I agree that we need some way to have arbitrary data (not accociated with a chat/user) be persisted via persistence.

**Comment by Bibo-Joshi** [comment]
Closed by #1325
