### ISSUE TITLE
relicense examples to CC0?

### ISSUE THREAD

**Issue by rahiel** [python-telegram-bot/python-telegram-bot#132]
It could make people more at ease for just taking the example code and using it to build their own bot. The LGPLv3 allows this, but then their bot must use the same license too if distributed. (That is not the case for programs that only import a LGPLv3  library.)

To do this everyone who contributed to the examples needs to agree (right?).

**Comment by jh0ker** [comment]
Relicensing can be done by the copyright owner(s). Anyone who contibuted _significantly_ to a piece of OSS owns part of the copyright, that's what I read. I'm fine with relicensing those that I added, and I don't think @leandrotoledo will have a problem with those he made. 
I just checked the git history for the examples, and I think you'd be the only other person who needs to agree.

**Comment by rahiel** [comment]
Of course I agree :smile:. Then we only need Leandro's ok for this.

**Comment by jh0ker** [comment]
@rahiel Great :) So, @leandrotoledo, what do you say?
