### ISSUE TITLE
give threads a name prefix

### ISSUE THREAD

**Issue by bmxp** [python-telegram-bot/python-telegram-bot#1332]
Just an idea if **_python-telegram-bot_** is part of a bigger program: 

It would be a nice thing to improve bug finding in bigger programms of which python-telegram-bot is a part of if one could name the thread. Instead of names like

```
dispatcher
updater
84a23bc3-ec23-4aeb-be53-f24e7af82544_0
84a23bc3-ec23-4aeb-be53-f24e7af82544_1
84a23bc3-ec23-4aeb-be53-f24e7af82544_2
84a23bc3-ec23-4aeb-be53-f24e7af82544_3
```

I would rather like to see
```
telegram_dispatcher
telegram_updater
telegram_worker_0
telegram_worker_1
telegram_worker_2
telegram_worker_3
```
Since any thread has an id anyway, this should not be too difficult.
So instead using uuid4 to name a worker, just give a custom param of ``name_prefix='telegram'`` and ``worker_name='worker'``

Thanks in advance!

**Comment by jsmnbom** [comment]
This looks like it should be doable, we'll look into it and get back to you.
(note that it might be a while as we're right now pretty focused on getting V12 out asap)

**Comment by bmxp** [comment]
Ok, thanks for letting me know, I am looking forward to this improvement.

**Comment by Eldinnie** [comment]
@bmxp good find. Would you be comfortable to PR this yourself?

**Comment by bmxp** [comment]
I would love to but my expertise is not good enough to provide a PR and I am not very good with API creating thus I'd rather step aside and let someone else make a superior solution.
To give som emore background: We have an Open Source Project SmartHomeNG and have a plugin which uses the library. To distinguish the threads it will help to have them named.
![image](https://user-images.githubusercontent.com/3002409/52851836-68933f00-3117-11e9-980d-11b49a4ab6b1.png)
