### ISSUE TITLE
`last` kwarg for `JobQueue.run_repeating` method

### ISSUE THREAD

**Issue by plammens** [python-telegram-bot/python-telegram-bot#1333]
Just as `JobQueue.run_repeating` takes a `first` optional keyword argument, that specifies the first time a job should be run (as a `datetime.datetime` object, for example), I believe it would be convenient to add a `last` optional keyword argument that specified, if relevant, the last time a job should be run.

## Use cases

I can think of a few use cases, but I'm sure there are more. For example, suppose the bot is part of a game, during which it has to send regular updates (by using a `Job`). Suppose the game lasts a fixed amount of time, which set prior to its start; say, 1 hour. Then, by specifying the `last` keyword argument, the bot programmer could set the "regular updates job" to end when the game ends.

## Current alternative

A workaround I have been using is to specify a separate `run_once` job that will run the `schedule_removal` method on the job at the desired time. A better way is to check inside the job's callback, and remove the job from there using `job.schedule_removal()`.

In either case, I find these solutions to be, if not cumbersome, inelegant, compared to having a much simpler-to-use and elegant dedicated feature.

------

A proposed implementation can be found in #1345.

**Comment by Eldinnie** [comment]
I think this would make an excellent addition. Would you care to go ahead and create a PR for this feature?

**Comment by plammens** [comment]
@Eldinnie Sure, I'll try :)

**Comment by Bibo-Joshi** [comment]
After internal discussion, we came to the conclusion that we don't want to continue implementing scheduling logic on our own and instead rely on a 3rd party library for that. Hence, I'll close this in favor of #1936.
