### ISSUE TITLE
Implement CRON style job scheduling

### ISSUE THREAD

**Issue by marekyggdrasil** [python-telegram-bot/python-telegram-bot#1337]
Hi all! I'd like to contribute to this project. I think it would be much easier to work with CRON style job scheduling. Below I describe the idea and list few examples. If this suggestion can be approved and merged I can come up with some integration plan.

# Implementation details

```python
def run_cron(self, callback, tab)
```

Where `tab` is a `string` object representing a standard CRON tab entry.

Function `run_cron` would throw appropriate exception if `tab` object is not a string matching CRON tab entry (use regex validation)

In order to easily integrate it into current scheduler we need to know how much time is required to pass until next execution, then we just add it into the queue with appropriate delay, which itself can be computed using [croniter](https://github.com/taichino/croniter).

Few examples below.

# Examples

Run callback_function everyday at 2:00 AM.

```python
job = j.run_cron(callback_function, '0 2 * * *')
```

Run callback_function twice per day, at 5:00 AM and at 5:00 PM

```python
job = j.run_cron(callback_function, '0 5,17 * * *')
```

Run callback_function every minute

```python
job = j.run_cron(callback_function, '* * * * *')
```

Run callback_function every Sunday at 5:00 PM ( note that Sunday is both `0` and `7` )

```python
job = j.run_cron(callback_function, '0 17 * * 0')
```

Run callback_function every 10 minutes

```python
job = j.run_cron(callback_function, '*/10 * * * *')
```

Run callback_function every minute but only in January, May and August

```python
job = j.run_cron(callback_function, '* * * 1,5,8 *')
```

Run callback_function every Friday and Sunday at 5:00 PM

```python
job = j.run_cron(callback_function, '0 17 * * 5,7')
```

**Comment by Eldinnie** [comment]
I guess it's a decent addition, but maybe this would be better placed as a helper method (in `telegram.utils.helpers`)?
@python-telegram-bot/maintainers ?

**Comment by marekyggdrasil** [comment]
There's not much feedback from @python-telegram-bot/maintainers, I guess I'll just prototype and PR. I'll keep you guys updated!

**Comment by llybin** [comment]
What a problem to use APScheduler or Celery?

**Comment by marekyggdrasil** [comment]
@llybin there is absolutely nothing wrong with APScheduler nor Celery. Those are very useful tools and could be used to solve the problems I mentioned while opening this issue. Let me explain my line of reasoning

1. I think most developers (if not nearly all of them) are familiar with CRON syntax, but not everyone used tools such as APScheduler
2. Croniter integrates nicely into current implementation - it is a library that given a crontab and current timestamp provides next timestamp job has to be executed and it works well with `threading.Event.wait(tmout)` which is the way `jobqueue` works at the moment

**Comment by Bibo-Joshi** [comment]
After internal discussion, we came to the conclusion that we don't want to continue implementing scheduling logic on our own and instead rely on a 3rd party library for that, in fact APScheduler. Hence, I'll close this in favor of #1936.
