### ISSUE TITLE
CallbackQueryHandler fires multiple times on IOS

### ISSUE THREAD

**Issue by DanielLavrushin** [python-telegram-bot/python-telegram-bot#1341]
### Steps to reproduce
Hi Team. I have an issue while using CallbackQueryHandler on IOS12.1.2 (iPhoneXR) python3.
1.
I have a simple script
```
from telegram import InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters,CallbackQueryHandler,InlineQueryHandler, ChosenInlineResultHandler
import datetime


keyboard = [[InlineKeyboardButton("1", callback_data="1"),
                 InlineKeyboardButton("2", callback_data="2")],
                [InlineKeyboardButton("3", callback_data="3")]]

reply_commands = InlineKeyboardMarkup(keyboard)
updater = Updater("token")
dp = updater.dispatcher

def command_main_menu(bot, update):
   print('{} - test here', datetime.datetime.now())

dp.add_handler(CallbackQueryHandler(command_main_menu))

updater.start_polling(timeout=60, read_latency=60)
updater.idle()
```
Press any button in the screen (after /start), quickly switch to iPhone desctop and return to the app. The command_main_menu will be fired more than one time.
This only happens in IOS, Android and Web versions work fine.

### Expected behaviour
The command_main_menu function should be fired one time when you press the inline buttons.

### Actual behaviour
In IOS (iPhone) the command_main_menu fires all the time you leave the telegram app and return back.

### Configuration
**Operating System:** IOS 12.1.2 iPhone XR

**Version of Python, python-telegram-bot & dependencies:**
``$ python -m telegram``
python-telegram-bot 11.1.0
certifi 2018.11.29
future 0.17.1
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)]

**Comment by jsmnbom** [comment]
Since this is a thing that only happens on one platform. This has got to be a telegram client issue, and therefore there's nothing that we can do about it.

**Comment by Eldinnie** [comment]
@jsmnbom To be precise it's IOS's way of telling you your bot should call `answer\_callback\_query`

**Comment by catbaron0** [comment]
Same issue here.
