### ISSUE TITLE
all exceptions should be TelegramError

### ISSUE THREAD

**Issue by tsnoam** [python-telegram-bot/python-telegram-bot#135]
this issue is here so the subject won't be forgotten.
fixes to this issue will be incremental, probably in their own issues/PRs.

**Comment by jh0ker** [comment]
Is this done with your latest PR or should we keep it?

**Comment by tsnoam** [comment]
I think we had a significant improvement. I am not 100% certain that we don't have stray exceptions, but I think that we can close this issue & whether we ever encounter such exception again, handle it specifically.
