### ISSUE TITLE
[request] allow to continue update propagation in the same group even when the update enters an handler

### ISSUE THREAD

**Issue by zeroone2numeral2** [python-telegram-bot/python-telegram-bot#1356]
The content of this issue doesn't really fit the template so I'm just going to freestyle here, if it's not a problem.

I'm going to make a short introduction just to make sure I fully unsrtand how the dispatching system currently works:

The current updates dispatching system allows to use different groups of handlers. Every update is dispatched sequentially to each handler of each group. If the update passes an handler's checks, the handler's callback is executed and the update is dispatched to the handlers of the following group.

I'm not completely sure what I'm going to request is a good design choice, but I've more than once found myself in this situation: because of some processing needs, I sometimes have to define many different handlers which run some logging/debugging/filtering/editing/flood control/db operations that need to be done on _every_ update received by the bot, and every update needs to enter these handlers regardless of what happened in the previous handlers.
Right now, I'm structuring my handlers in a way each of these "preprocess" handlers is registered in a different group, using the `group` parameter of `dispatcher.add_handler()`.

This structure, by the way, it's hard to mantain because each handler needs to be registered in a different group. Adding a new handler requires a lookup of the files containing the callbacks to figure out what's the highest/lowest group used until now.

So, after this premise, my request is: it would be nice to be able to raise an exception that signals the dispatcher to continue the propagation of the current update to the next handler of the current group, in a similar way to what we can already do with `DispatcherHandlerStop` to stop the propagation

I'm aware my proposal of raising an exception to _continue_ the propagation inside the current group doesn't really sound as a good design choice, but it would match the already established opposite behavior

**Comment by Ambro17** [comment]
You can branch from the lib and create that extra except yourself, it's not so hard.
just an except block with the new exception, some logging and a continue to allow the for to keep looking for handlers

**Comment by zeroone2numeral2** [comment]
@Ambro17 I already have my own fork that works that way, I was just wondering if it's a good idea to make this a standard feature in the library

**Comment by Eldinnie** [comment]
Hi @zeroone2numeral2 ,

Thanks for your proposal. At some point the thing you proposed has been in the codebase, and has since been reverted in #792 . In our opinion it actually complicates things more than it solves.
However I want to give you some advice. Groups are just integers, but nothing is stopping you from naming those:
`LOGGING, DB_CHECK, REPLY, TEARDOWN = -10, -5, 1, 10`
So you can use those in you handdler definitions:
```dp.add_handler(TypeHandler(Update, loggingcallback), group=LOGGING)```
This will make your code far better readable and saves you looking up handler group numbers.

I will close this issue for now because we're not intending to implement this request.

**Comment by zeroone2numeral2** [comment]
Hi @Eldinnie, thank you for the answer and thank you for the tip, your suggestion looks nice and I will surely adopt this approach and name my groups integers. I've never thought about that. Thank you
