### ISSUE TITLE
Use UTC dates

### ISSUE THREAD

**Issue by Lonami** [python-telegram-bot/python-telegram-bot#1362]
https://github.com/python-telegram-bot/python-telegram-bot/blob/439790375ed8ed493c43e464aa8e2b60a77939db/telegram/utils/helpers.py#L78-L90

Should probably be using `tz=timezone.utc`. Python's `datetime` isn't the best, and `fromtimestamp` by default sets no `tz` information, which uses the local time, which in turn is generally a bad idea.

**Comment by Eldinnie** [comment]
@Lonami I guess we all agree it should be UTC, but it is a breaking change. Maybe we can get it in before official v12 release?

**Comment by PaulSonOfLars** [comment]
I agree, since there's a breaking change spree for v12, might as well add this in
