### ISSUE TITLE
Automatic answerCallbackQuery

### ISSUE THREAD

**Issue by Lonami** [python-telegram-bot/python-telegram-bot#1364]
This would be, in my opinion, desirable behaviour. If the user uses any other method (e.g. edits the message) **and** they haven't answered the query themselves before, it's done automatically with no parameters (such as text or show alert).

Once it is answered, it cannot be answered again (I believe Telegram ignores it?).

I can think of two caveats:
* User answers the query as the last thing they do (in my opinion it should be the first thing anyway). This may make the change breaking.
* User answers the query through the bot object (so it's a lot harder to track if a callback was answered). This shouldn't be a big deal, since the last call is ignored.

**Comment by jh0ker** [comment]
@Lonami Why not do it after the handlers are done? That way, it would only be a fallback in case the user forgets it.

**Comment by Lonami** [comment]
That is a different option which I hadn't considered, and has one drawback less.

**Comment by Poolitzer** [comment]
After some internal discussion, we came to the conclusion that this is something which, to be actually helpful, would require knowing what the user does in their callback and be unnecessary complicated at that point to implement, so I am closing this.
