### ISSUE TITLE
Add a timeout callback in ConversationHandler

### ISSUE THREAD

**Issue by levnikmyskin** [python-telegram-bot/python-telegram-bot#1368]
Hi! Don't know if this could be useful to many people, but at the moment it seems that there's no way other than subclassing ConversationHandler to execute a callback function when the `conversation_timeout` is reached.  
If one is storing conversation-related information in a data structure or in a database, it could be useful to know when the conversation times out so that some cleanup may happen. For instance, I have this code now:  
```python
class MyConversationHandler(ConversationHandler):
    def __init__(self, timeout_callback, *args, **kwargs):
        self.timeout_callback = timeout_callback  
        super().__init__(*args, **kwargs)  
    def _trigger_timeout(self, bot, job):  
        super()._trigger_timeout(bot, job)  
        self.timeout_callback(bot, job, self.current_conversation)
```  
Even though subclassing and overriding a couple of methods is not particulary time consuming, I think it'd be nice if this was already built-in in the ConversationHandler. I could open a pull request to add such a thing if you wish!

**Comment by Eldinnie** [comment]
Hi @levnikmyskin ,

One of the things we added in the V12 release is this feature. See the PR in #1217 that we merged to add this behavior.

**Comment by levnikmyskin** [comment]
Ah right, didn't see that! Great job :D will look forward to the new release
