### ISSUE TITLE
Multiple message queues for a bot

### ISSUE THREAD

**Issue by alistvt** [python-telegram-bot/python-telegram-bot#1369]
I just read this source of the decorator [@messagequeue](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/messagequeue.py)
and I thought what if a bot needs multiple message queues?
because the limits in telegram are different for each type of requests.
for example the limit for editing message texts is too low!

what do you suggest to do?

Thanks.

**Comment by jsmnbom** [comment]
We currently don't have anything implemented that can do that kinda thing. We'd probably be open to suggestions/PRs with how such a thing should be done tho! :D

**Comment by Poolitzer** [comment]
On one hand, it might even be interesting to do this behind the scenes. So we add each request in a queue and try to be smart when we do what so we dont hit limits.

On the other hand, there is nothing we can do if a user sends 60 requests at once, and they should limit such a bulk request by themself in the code actually.

**Comment by Maga007** [comment]
от куда найты библотека телеграм боту

**Comment by Bibo-Joshi** [comment]
> от куда найты библотека телеграм боту

@Maga007 please stick to english on GitHub (or at least this repo) and also please don't randomly comment on open issues. Read the [README](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/README.rst) to find out where this libary can be found.

**Comment by jiyoungsin** [comment]
When we say message ques would this include an actual conversation? 
eg.
ME: /doThis
Response: Which bot would you like to do this with?
ME: bot1
Response: Executes.

**Comment by Bibo-Joshi** [comment]
As we won't tackle this issue individually but in the context of #2139, I will close this. #2139 links here, so it won't be forgotten :)
