### ISSUE TITLE
get username

### ISSUE THREAD

**Issue by soundaraj** [python-telegram-bot/python-telegram-bot#1370]
how to get username by user_id or chat_id

**Comment by loozhengyuan** [comment]
Not sure if its what you want but consider using `update.message.from_user.username`. Also, I suggest you refer to the [Wiki](
https://github.com/python-telegram-bot/python-telegram-bot/wiki) or [Docs](https://python-telegram-bot.readthedocs.io/en/stable/) for more detailed information.
