### ISSUE TITLE
Error for CallbackQueryHandler with PrefixHandler inside ConversationHandler

### ISSUE THREAD

**Issue by alisher-matkurbanov** [python-telegram-bot/python-telegram-bot#1374]
### Steps to reproduce
https://gist.github.com/alisher-matkurbanov/3898a6d192c5eb047c0b38fcbdb7cf15

1.  Create CallbackQueryHandler, PrefixHandler, ConversationHandler
2.  Add PrefixHandler in entry_points of ConversationHandler
3.  Add CallbackQueryHandler to states of ConversationHandler
4.  Push inline button
5.  Script fails with error: TypeError: 'str' object is not callable
### Expected behaviour
Expect inline button will be handled by the CallbackQueryHandler
### Actual behaviour
Tell us what happens instead
Script fails with error: TypeError: 'str' object is not callable
### Configuration
**Operating System:**
Windows 10 Pro
**Version of Python, python-telegram-bot & dependencies:**
``$ python -m telegram``
python-telegram-bot 12.0.0b1
certifi 2019.03.09
future 0.17.1
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)]

### Logs
Traceback (most recent call last):
  File "C:\Users\AMatkurbanov\Desktop\Test12ver\venv\lib\site-packages\telegram\ext\dispatcher.py", line 333, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\AMatkurbanov\Desktop\Test12ver\venv\lib\site-packages\telegram\ext\conversationhandler.py", line 326, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "C:\Users\AMatkurbanov\Desktop\Test12ver\venv\lib\site-packages\telegram\ext\handler.py", line 117, in handle_update
    return self.callback(update, context)
TypeError: 'str' object is not callable

**Comment by jsmnbom** [comment]
If you look at the docs for [callbackQueryHandler](https://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.callbackqueryhandler.html#telegram.ext.CallbackQueryHandler) you will see that the first argument should be the callback, and that you should pass the pattern you wanna check for as pattern=.

``` python
INLINE: [CallbackQueryHandler(inline_callback, pattern='[0-9]')]
```

(oh and also: callbacks from CallbackQueryHandler don't have a update.message)
