### ISSUE TITLE
[v12.0.0b1] InlineQueryHandler Only Firing on First Instance of a Unique String

### ISSUE THREAD

**Issue by Gambloide** [python-telegram-bot/python-telegram-bot#1377]
### Steps to reproduce
1. Copy the **inlinekeyboard.py** bot example (https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/inlinekeyboard.py)

2. Add **logger.info('Update: "%s"', query)** to **inlinequery** and your token to **Updater**.

3. Run **inlinekeyboard.py**

4. Use inline mode and slowly type **TEST**

5. Delete **TEST** and type it again

### Expected behaviour
The InlineQueryHandler should fire on every keypress. Example log output:
```
[...] - __main__ - INFO - Update: "T"
[...] - __main__ - INFO - Update: "TE"
[...] - __main__ - INFO - Update: "TES"
[...] - __main__ - INFO - Update: "TEST"
[...] - __main__ - INFO - Update: "TEST"
[...] - __main__ - INFO - Update: "TES"
[...] - __main__ - INFO - Update: "TE"
[...] - __main__ - INFO - Update: "T"
[...] - __main__ - INFO - Update: "TE"
[...] - __main__ - INFO - Update: "TES"
[...] - __main__ - INFO - Update: "TEST"
```

### Actual behaviour
The InlineQueryHandler only fires on the first instance of every provided input string. Example log output: 
```
[...] - __main__ - INFO - Update: "T"
[...] - __main__ - INFO - Update: "TE"
[...] - __main__ - INFO - Update: "TES"
[...] - __main__ - INFO - Update: "TEST"
```

### Configuration
**Operating System:**
```
edition Windows 10 Pro
version 1809
build 17763.379
```

**Version of Python, python-telegram-bot & dependencies:**

```
python-telegram-bot 12.0.0b1
certifi 2019.03.09
future 0.17.1
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
```

**Comment by jsmnbom** [comment]
This is not a bug. Please have a look at the docs for `bot.answer_inline_query`, specifically the `cache_time`, that should fix your "issue" :)

**Comment by Gambloide** [comment]
Thanks a lot! I was aware of `cache_time` and still had the tab with the docs for `bot.answer_inline_query` open, just didn't think it was what I needed, due to the client side not updating. I should take more breaks to clear my head. I am sorry for the unnecessary issue.
