### ISSUE TITLE
InlineQueryResultArticle thumb results in invalid url error

### ISSUE THREAD

**Issue by DailytheNoob** [python-telegram-bot/python-telegram-bot#1378]
### Steps to reproduce
1. Download thumbnail for InlineQueryResultArticle to return

2. Assign it in the parameters with thumb_url

3. receive `"Webdocument_invalid_url"` error from `telegram.ext.dispatcher`

### Expected behaviour
The article should show itself

### Actual behaviour
No article appears due to the error.

### Configuration
**Operating System:** CentOS 7

**Version of Python, python-telegram-bot & dependencies:**
Python: 3.6.3
PTB: 12.0.0b1
certifi 2018.11.29
future 0.17.1

### Logs
```
2019-04-01 10:23:01,314 - telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update
2019-04-01 10:23:01,314 - __main__ - WARNING -
Update "{'update_id': 655844385, 'inline_query': {'id': '751802571639684714', 'query': 'test', 'offset': '', 'from': {'id': 175042676, 'first_name': 'David', 'is_bot': False, 'username': 'DailytheNoob', 'language_code': 'en'}}, '_effective_user': {'id': 175042676, 'first_name': 'David', 'is_bot': False, 'username': 'DailytheNoob', 'language_code': 'en'}}" caused error "Webdocument_url_invalid"
```
I copied the full script to https://ahk.daviddaily.dev/mybot.py
(go to https://www.daviddaily.dev/ for some fun)

**Comment by jsmnbom** [comment]
A `url` in the telegram sense, has to use either `http` or `https` protocol. You cannot use local files.

**Comment by DailytheNoob** [comment]
changing it to https results in the same exact error. I got it to work once with a local file, but it hasn't worked again.

**Comment by jsmnbom** [comment]
Well if you've gotten it to work before then it's not a bug, please ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.

**Comment by DailytheNoob** [comment]
I did ask in the telegram group already, and if its not a bug then why does the unchanged code not work anymore?

**Comment by tsnoam** [comment]
@DailytheNoob Can you please provide a minimal code for recreating the problem?
