### ISSUE TITLE
Dispatcher.remove_handler when handlers is empty

### ISSUE THREAD

**Issue by serebryakov-av** [python-telegram-bot/python-telegram-bot#1379]
https://github.com/python-telegram-bot/python-telegram-bot/blob/b745645397e3659084c0be6a64d4354c47cdcea0/telegram/ext/dispatcher.py#L339

I think that there should be `len(self.handlers) and (handler in self.handlers[group])`. Someone may try to remove handler even if there are no handlers at all.

**Comment by Ambro17** [comment]
If it tries to remove a non-existing handler it will fail because `__contains__` will return `False`.
It is not pythonic to resort to len in order to ask for pertenence. But maybe there's some edge case you've found that i'm missing?

**Comment by serebryakov-av** [comment]
Then okay. I'm not so experienced with Python, so I agree :)

**Comment by serebryakov-av** [comment]
I thought that it is not ok when method fail when I'm trying to remove handler.

**Comment by Ambro17** [comment]
But what exception did it raise? `KeyError` on group key? or `TypeError` because of the handlers type? It will help if you gave more context on how you found this problem.

**Comment by serebryakov-av** [comment]
```from telegram.ext import Updater
token='1234567:1234567890abcdefG'
updater = Updater(token=token, use_context=True)
def myhandler(update, context):
    pass
updater.dispatcher.remove_handler(myhandler)
```

This example rises an Exception `KeyError: 0`:
```
KeyError                                  Traceback (most recent call last)
<ipython-input-1-4906b5281f56> in <module>
      4 def myhandler(update, context):
      5     pass
----> 6 updater.dispatcher.remove_handler(myhandler)

/anaconda3/lib/python3.7/site-packages/telegram/ext/dispatcher.py in remove_handler(self, handler, group)
    424 
    425         """
--> 426         if handler in self.handlers[group]:
    427             self.handlers[group].remove(handler)
    428             if not self.handlers[group]:
```

**Comment by serebryakov-av** [comment]
I am using `remove_handler` in a case when:
1. I need to remove an old handler implementation and
2. then create a new implementation which I'll add with `add_handler`.

And at the beginning it could be that there are no handlers in dispatcher. Then I have to use `try: ... except KeyError: ...`.

**Comment by Eldinnie** [comment]
I think raising an exception when trying to remove something from an empty list/dict is expected behavior and we should keep it at that.
If you expect the behavior to happen regardless you should indeed `try ... except` it.

**Comment by serebryakov-av** [comment]
Ok, I got it :) Thank you for your interest.
