### ISSUE TITLE
How to remove conversationhandler warning logs

### ISSUE THREAD

**Issue by Flowelcat** [python-telegram-bot/python-telegram-bot#1380]
### Steps to reproduce
1. Create at least one conversation handler

2. Add this conversation handler to dispatcher

3. Now you can watch logs like "If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message."

### Expected behaviour
I want be able to disable specific loggers

### Actual behaviour
With a lot of states library flooding with same log message

### Configuration
Ubuntu 18.04.2

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 11.1.0
certifi 2019.03.09
future 0.17.1
Python 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]

### Comment
If there is reason to add warning logs to logging library?
telegram/ext/conversationhandler.py:178-179
`                    logging.warning("If 'per_message=False', 'CallbackQueryHandler' will not be "
                                    "tracked for every message.")
`

Also if per_message==True i'll get this messages instead:
`If 'per_message=True', all entry points and state handlers"
                                    " must be 'CallbackQueryHandler', since no other handlers "
                                    "have a message context.`

I building not small bots and i can't get rid of this messages, i have at least 40 warning messages per bot run, so, yes, this is a problem for me.

**Comment by jsmnbom** [comment]
We've made sure to only have loggers like these in the `__init__` of the handler. This means that you should not see this message multiple times unless you are creating multiple conversation handlers.

Also you should probably take the advise in the loggers to heart as they are simply there to help, and you should not be getting warnings if using the handlers correctly.

Also https://stackoverflow.com/questions/11029717/how-do-i-disable-log-messages-from-the-requests-library is a thing.

I feel like I've given you enough solutions to be able to fix this, and therefore I'm gonna close this issue.

**Comment by Flowelcat** [comment]
Yes i am creating  multiple conversation handlers, and getting a lot of warning messages and i just want to disable them but i can't.

I can't disable this warnings using this advise: 
https://stackoverflow.com/questions/11029717/how-do-i-disable-log-messages-from-the-requests-library 
because this warning logs pushed through logging library (root logger) and not telegram.ext or 'conversationhandler' loggers.
