### ISSUE TITLE
Sommer/Winter time with Jobs

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#1381]
### Steps to reproduce
1. Live in Europe

2. Run a weekly job with something like

```
first = datetime(foo)
job_queue.run_repeating(job,
                        interval = timedelta(7),
                        first = first)
```

### Expected behaviour
Job runs once a week at the specified time

### Actual behaviour
The clock change from winter to sommer time is not handled correctly and the job runs an hour early/late.

### Proposal:
Since the problem occurs only twice a year and is easily fixed by restarting the bot **and** this nonsence of constantly changing clocks hopefully [ends by 2021](https://www.bbc.com/news/world-europe-47704345), I guess this can be "fixed" by documenting it in the docstring of ``JobQueue.run_daily()`` and ``JobQueue.run_repeating()``.
If I get a LGTM for this "solution", I'll open a PR for it :)

**Comment by tsnoam** [comment]
@Bibo-Joshi 
Thanks for the report. The documentation will be fixed.
