### ISSUE TITLE
MessageHandler doesn't handle a contact message

### ISSUE THREAD

**Issue by DilsMatchanov** [python-telegram-bot/python-telegram-bot#1385]
When I send a message with contact the callback is not called

```python
def callback(bot, update):
    print("Message")

contact_handler = MessageHandler(callback=something)
```

I share a contact with a bot and it doesn't print anything in the console

**Comment by muellerti** [comment]
So what was the reason?

**Comment by DilsMatchanov** [comment]
@muellerti Maybe lil bit late but, for everybody else who will face the same problem, the proper contact message handling looks like this
```py
contact_handler = MessageHandler(Filters.contact, callback)
```
