### ISSUE TITLE
Bot API 4.2

### ISSUE THREAD

**Issue by jsmnbom** [python-telegram-bot/python-telegram-bot#1386]
All in all doesn't look too bad :)

- [ ] Polls
  - [ ] bot methods: sendPoll, stopPoll
  - [ ] object: Poll
  - [ ] msg attribute: poll

- [ ] ChatMember attribute: is_member
- [ ] msg attribute: forward_sender_name

irelevant changes
- deleteMessage can be used in private chats
- pinned msg in basic groups
- new webhook subnets
- document thumbnail changes (might need changing of tests)

**Comment by sshnakamoto** [comment]
https://core.telegram.org/bots/api-changelog#april-14-2019

**Comment by erohmensing** [comment]
+1 for polls! Was going to be disappointed that this wasn't supported until I read that they're only 2 weeks old. Thanks for being on top of this!

**Comment by sshnakamoto** [comment]
> +1 for polls! Was going to be disappointed that this wasn't supported until I read that they're only 2 weeks old. Thanks for being on top of this!

@erohmensing  It's already on development. 
Check that branch: [api4.2-poll](https://github.com/python-telegram-bot/python-telegram-bot/commits/api4.2-poll)

**Comment by Nukesor** [comment]
Resolved with #1418
