### ISSUE TITLE
Send automatic messages

### ISSUE THREAD

**Issue by candidobugarin** [python-telegram-bot/python-telegram-bot#139]
Hello again. Sorry if my question is idiot but the api have a function that send a massage every hour or a time lapse defined by the user? 

Thanks

**Comment by jh0ker** [comment]
@candidobugarin Hi! Currently, that is not possible, but we're planning to add that feature soon :)

**Comment by jh0ker** [comment]
v3.2 contains the `JobQueue` which resolves this issue.

**Comment by mashaalah** [comment]
Hello how i can use jobQueue to send daily message in some times.(07:00)?
tanks

**Comment by Eldinnie** [comment]
This issue is closed for over a year. If you have an **issue** you;re welcome to open a new one. If you're looking for usage questions please ask in our telegram group.
