### ISSUE TITLE
don't download package

### ISSUE THREAD

**Issue by aminSharifi21** [python-telegram-bot/python-telegram-bot#1398]
what is this problem???
![Screenshot from 2019-04-28 11-20-11](https://user-images.githubusercontent.com/37484729/56866542-e56d4f80-69c9-11e9-99d3-8e145daaf0c5.png)

**Comment by Bibo-Joshi** [comment]
Closing due to lack of information and activity.
Also the issue doesn't seem to be with PTB as far as I can tell from the screenshot.
