### ISSUE TITLE
Message handler error: 'NoneType' object has no attribute 'chat_id'

### ISSUE THREAD

**Issue by jonbesga** [python-telegram-bot/python-telegram-bot#1403]
Hi,

I have this handler that I expect to manage messages that include text:

`dispatcher.add_handler(MessageHandler(Filters.text, handlers.my_function))`

The callback is the following:
```
def my_function(bot, update):
    print(update.message.chat_id)
```

And it's usually working fine. However, sometimes I'm getting:

```
AttributeError
'NoneType' object has no attribute 'chat_id'
```

I'm wondering in what cases an update managed by the MessageHandler does not contain a message property

**Comment by jonbesga** [comment]
I'll answer myself after taking a look deeper into the message handler code: Channels

**Comment by arbitrandomuser** [comment]
can you paste what was the issue over here ? you seem to have corrected it , people who google and arrive at this will ask again in the group
