### ISSUE TITLE
Call dispatcher.update_queue.task_done() after handler execution finished?

### ISSUE THREAD

**Issue by alesdokshanin** [python-telegram-bot/python-telegram-bot#1410]
I couldn't find any calls of `update_queue.task_done()` in the codebase.

You can use the following handler to demonstrate the problem - it returns incrementing numbers:
```python3
def echo(bot, update):
    reply_text = f"Unfinished tasks: {bot.dispatcher.update_queue.unfinished_tasks}"
    bot.send_message(chat_id=update.message.chat_id, text=reply_text)
```
I personally would really like to know whether my bot is resting and all jobs are completed. It could help me to properly exit from a serverless handler.

Is there any reason why `task_done()` is never called? If there isn't, what would be the best place to put that logic in? Thanks.

**Comment by Eldinnie** [comment]
Hi,

I don't know where you get the `unfinished_tasks` property from, because it does not seem to be documented on a `queue.Queue` object.
However, we don't call `task_done()` but you might be right we should.
I'm calling out @python-telegram-bot/maintainers to answer here too, but would you be interested in implementing this?

**Comment by jh0ker** [comment]
I didn't even know about `task_done`, very interesting. It seems like we should definitely call it.

https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/dispatcher.py#L276 would be the correct place to call it, I believe. Perhaps also above where the exit cases are handled, for completeness.

**Comment by jh0ker** [comment]
@alesdokshanin I'm not sure using the update queue is even a good idea in a serverless environment (I'm assuming AWS Lambda or equivalent). Take a look at https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks#alternative-no-threading It might be a little bit outdated, but in principle it should still work. It's at least worth a look and might make things a lot simpler.

**Comment by tsnoam** [comment]
@Eldinnie We should be calling task_done no question here. It&#x27;s a quick fix as well.

**Comment by alesdokshanin** [comment]
> @alesdokshanin I'm not sure using the update queue is even a good idea in a serverless environment (I'm assuming AWS Lambda or equivalent). Take a look at https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks#alternative-no-threading It might be a little bit outdated, but in principle it should still work. It's at least worth a look and might make things a lot simpler.

Yes, I have now rethought the way it should work and I don't think I need a separate thread with update queue, assuming that my handler will never receive any messages until it finished processing previous, so there's no need to care about having all the messages processed. 

But having an ability to wait until the bot is done with all updates could be great for implementing shutdown mechanisms for threaded use cases, for example.

**Comment by alesdokshanin** [comment]
> I'm calling out @python-telegram-bot/maintainers to answer here too, but would you be interested in implementing this?

I can implement it if it is just about adding one line and tests for it.

**Comment by tsnoam** [comment]
@alesdokshanin We should be adding the task_done() regardless.

**Comment by alesdokshanin** [comment]
Here's the PR https://github.com/python-telegram-bot/python-telegram-bot/pull/1428
