### ISSUE TITLE
wrong indentation in parse*entity methods

### ISSUE THREAD

**Issue by lorien** [python-telegram-bot/python-telegram-bot#1412]
Here: https://github.com/python-telegram-bot/python-telegram-bot/blob/5c45e469d5837b244f9cd589ec787036e5be9970/telegram/message.py#L869

Return line must be inside else branch

Both `parse_entity` and `parse_caption_entity` methods should be fixed.

**Comment by Eldinnie** [comment]
Hi,

Thanks for notifying us.
Although the end result and workings are the same, it would be more visually appropriate to fix this.

Whould you be interested in making a PR to `fix` the problem?
