### ISSUE TITLE
Progress callback for File.download

### ISSUE THREAD

**Issue by Lonami** [python-telegram-bot/python-telegram-bot#1421]
[There is at least some interest](https://t.me/pythontelegrambotgroup/230936), and it sounds like a very basic feature request.

**Comment by Eldinnie** [comment]
ehm...
What exactly is it you propose?

**Comment by Lonami** [comment]
[`File.download`](https://python-telegram-bot.readthedocs.io/en/latest/telegram.file.html#telegram.File.download) has, as far as I know, no way to print or otherwise use the download progress. There should be a way. Sure, you tell it to download, but you don't know how far the download is, and you can't keep the bot's users up-to-date with the progress (e.g. "Downloading file…"). This is specially important with not-so-fast connections.

**Comment by Eldinnie** [comment]
`File.download()` is blocking so when it returns, it's done.
making it a possiblity to check progress would first mean to make it async and then get some indicator or callback to know what state it's in.

I don't really see the point. afaics:
```
# reply to user start downlaoding
file.download()
# reply to user done
```
should be enough for the small file sizes.

@python-telegram-bot/maintainers any other opinions?

**Comment by Eldinnie** [comment]
@Eldinnie @jsmnbom @tsnoam @jh0ker inout please

**Comment by Lonami** [comment]
What need is there to make it "async"? The callback can get called whenever progress is made, while the call is still blocked. If the file is downloaded in chunks (…it should be), it should be easy.

**Comment by jh0ker** [comment]
Especially since bots can only download files up to 20mb, I tend to agree with @Eldinnie here. If it's really needed, it's always possible to build a custom download function that supports this. But adding this to the library seems like feature creep.

**Comment by Lonami** [comment]
20MB may not be much, but the bot may be under heavy load or they may be different reasons to make the download slow, where knowing the progress can be really useful for… whatever the user wants to. I also don't understand how a simple callback argument is a "feature creep".

**Comment by Lonami** [comment]
As an example implementation and usage…

```python
def download(file, progress):                     # <- progress added
    with requests.get(file, stream=True) as r:
        r.raise_for_status()
        total = int(r.headers['content-length'])  # <- ptb probably already knows "size"
        with open(local_filename, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192): 
                if chunk:
                    f.write(chunk)
                    progress(f.tell(), total)     # <- added callback

**Comment by jh0ker** [comment]
If it is that simple, then it would make sense to have it.

**Comment by Lonami** [comment]
I haven't checked how the mentioned `File.download` is implemented, but like I said, it should be chunked, and once it it's trivial.

**Comment by tsnoam** [comment]
@Lonami Afaik, requests.get is the blocking here.
It will return only when the entire download is completed 

In order to monitor the progress we need some kind of async approach here (multithread or even loop).
Maybe if and when we&#x27;ll dump py2.7 support and switch to native asyncio

**Comment by Lonami** [comment]
@tsnoam I just showcased a working example with `requests` in https://github.com/python-telegram-bot/python-telegram-bot/issues/1421#issuecomment-501676317…

**Comment by Eldinnie** [comment]
It's not such an easy fix, because the actual downloading of the file get's handed of to the connectionpool of the `request` instance for the bot.

**Comment by Lonami** [comment]
If the URL gets passed to that pool, the callback can be passed too.

**Comment by tsnoam** [comment]
@Lonami Right! I missed that part in your example.

However:
1. I&#x27;m not very fond of the idea of adding a dependency to the library like &quot;requests&quot; .
Maybe we can utilize urlllib3 for that. After all requests is built on top of it.
2. Multithreading issues should be taken into account here. Possibly only a documentation note bit we do need to consider them.
3. Regarding connection pool (re: @eldinnie ) - the connection doesn&#x27;t need to be part of the connectionpool of interaction with the bot-api-server.

**Comment by jh0ker** [comment]
if I understand correctly, the progress callback is called synchronously

**Comment by tsnoam** [comment]
@jh0ker What guarantee do we have that the callback will not be decorated with run_async (or equivalent)?

**Comment by Eldinnie** [comment]
To copy from the maintainers chat:

I think it's a very edgy usecase (one user, total, asked for this. No-one thumbed or supported the issue). With a lot of trouble to implement (modifying the request class to accept a parameter only used for this).
I'm against it not because it's a feature creep but because I don;t like implementing new stuff that (likely) no-one ever needs or uses.

**Comment by Poolitzer** [comment]
I personally dont think the hassle introducing this will be worth the result.

**Comment by Bibo-Joshi** [comment]
Since this has been inactive for a while and the response is not too positive, I'll be closing this.
