### ISSUE TITLE
de_json should be documented

### ISSUE THREAD

**Issue by igoose1** [python-telegram-bot/python-telegram-bot#1423]
### Problem

To be familiar with de_json functions programmer has to read the source. I found that it works with parsed data (like you should do json.loads(...) before) after reading the notice in the wiki of "Custom solution for Webhooks" by the chance.

There is no information in docs for Update and Message.

### Solution
Someone can write the simple notice like:
**de_json works with dictionaries not with strings!**

**Comment by Eldinnie** [comment]
Hi,

`de_json` is not documented because it is intended for internal use. Although some applications can be made we do not intend to document `de_json()`.
