### ISSUE TITLE
Android keyboard doesn't appear after inline keyboard used on mobile

### ISSUE THREAD

**Issue by cheesemarathon** [python-telegram-bot/python-telegram-bot#1425]
### Steps to reproduce
1. Use the latest version of the telegram app on android

2. Run the conversationbot.py example code

3. Start talking to the bot. After you select boy or girl it asks you for a photo. The built-in keyboard does not reappear after the boy/girl/other inline keyboard is used.

![Screenshot_20190612-141840](https://user-images.githubusercontent.com/16329132/59355532-093ce880-8d1f-11e9-897f-3fde83d3bde5.png)

### Expected behaviour
The android keyboard should appear for the user to type with

### Actual behaviour
A black space appears where the keyboard should be

### Configuration
Windows 10 running bot
Python 3.7
Python telegram bot version 12.0.0b1

Google pixel running android 9 with version 5.7.1 of telegram app (the latest version as of writing this). Using SwiftKey keyboard but the issue persists with Google keyboard

**Comment by cheesemarathon** [comment]
This only seems to occur after clearing message history and can be fixed by leaving the chat to the main menu and then re-entering the chat with the bot. The keyboard will then reappear. This makes it seem more like a bug with telegram than python-telegram-bot.

**Comment by Eldinnie** [comment]
Hi,

It sounds like a client bug. Unfortunately we can;t fix thos with the library so I'm closing this issue.
