### ISSUE TITLE
Fix doc for dispatcher.run_async

### ISSUE THREAD

**Issue by Eldinnie** [python-telegram-bot/python-telegram-bot#1433]
https://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.dispatcher.html#telegram.ext.Dispatcher.run_async

**Comment by Bibo-Joshi** [comment]
Fixed by #1348, although on ReadTheDocs (latest), it's still wrong. But I guess, the docs just haven't been build since then.
Closing, since no code changes are needed.
