### ISSUE TITLE
Add health endpoint - 405 Method not allowed

### ISSUE THREAD

**Issue by Alwinius** [python-telegram-bot/python-telegram-bot#1438]
Before upgrading to version 12, a basic HTTP GET request to the running bot would return 200 OK with an empty response body. Now, I get 405 Method Not Allowed. I used this for my monitoring to regularly check if the bot is responsive to requests. Ideally, there would be some kind of health endpoint, which only returns 200 OK if the bot is really ok to process incoming messages from Telegram servers, but an endpoint that returns OK all the time (maybe there is already one?) would help me fix my monitoring, too. 

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram
python-telegram-bot 12.0.0b1
certifi 2018.11.29
future 0.17.1
Python 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]``

**Comment by Poolitzer** [comment]
hey. what stops you from doing a simle ping to the bot, to which the bot replies with pong?

How did your request "to the bot" look like?

**Comment by Eldinnie** [comment]
I think this changed because we changed to Tornado.

@tsnoam Can you get some eyes on this please?

**Comment by Isopodus** [comment]
I was trying to ping my bot to keep heroku web process awake (it goes to sleep after 30 minutes on free plan).
```
# tried this
requests.get('https://myapp.herokuapp.com').status_code

# this
requests.get('https://myapp.herokuapp.com/' + bot_token).status_code

# and also this (tried ports 80 and 8443)
requests.get('https://myapp.herokuapp.com:8443').status_code
```
Anyway, I was getting 405 or 404 everytime.

**Comment by Poolitzer** [comment]
Okay, this is a fairly common used scenario.

It wont be enough if you bot sends a message every 30/29 minutes?

**Comment by tsnoam** [comment]
Simply doing HTTP GET means only that the HTTP service is responsive and means nothing regarding the proper functioning of a bot.
We can add another URL to check for the status just to restore previous behaviour, however we should consider adding some data inside + callback for the user to run his own checks inside.

**Comment by Alwinius** [comment]
> hey. what stops you from doing a simle ping to the bot, to which the bot replies with pong?
> 
> How did your request "to the bot" look like?

I'm using CheckMK monitoring with Nagios backend. I can define a HTTP request (GET, POST...), even with custom headers, and define rules based on the response content. What I cannot do (without custom checks) is to set HTTP Status Codes as OK and alert only on others. Since I can filter the response content, additional service health information would definitely be helpful. For now I would be satisfied with a 200 Status Code alone because it means the bot is not crashed entirely and probably responds to requests by Telegram servers as well.

**Comment by Poolitzer** [comment]
I think pending reply isn't fitting to this anymore, if i understand this correctly, our stance regarding this is:

> We can add another URL to check for the status just to restore previous behaviour, however we should consider adding some data inside + callback for the user to run his own checks inside.

So that's what we want to see in a PR. I will change the label to enhancement,

**Comment by reimarstier** [comment]
What about using https://pypi.org/project/py-healthcheck/ or doing something similar? The healthcheck already supports adding additional checks. Now it's just about where and how to expose this functionality to the user.

**Comment by Poolitzer** [comment]
our goal is btw to implement this using tornado. just in case someone else is insane enough to do that.

**Comment by dixneuf19** [comment]
Would be very interested in this feature, since I host my bot on Kubernetes. Having an health-check endpoint is quite important if you want auto healing... It could be available behind the `.well-know/` endpoint, such as `/.well-known/apollo/server-health` for some [graphql servers](https://www.apollographql.com/docs/apollo-server/monitoring/health-checks/).

Is there any example of a repo which has implemented a work around, using the existing tornado server ? Maybe something with `TypeHandler` ?

**Comment by reimarstier** [comment]
If you are using docker / kubernetes you may as well add a little script to your setup which does the check for you: 
```
#!/bin/sh

RESULT=$(curl https://api.telegram.org/bot${TELEGRAM_AUTH_TOKEN}/getWebhookInfo | jq '.ok')
if [ "$RESULT" = "true" ]; then
  exit 0
else
  exit 1
fi
```
Make sure the environment variable **TELEGRAM_AUTH_TOKEN** is set in your container and you are good to go. The script is using jq, you might add that or use something else to parse the response.

**Comment by zpavloudis** [comment]
I would like to take my chances with this as part of hacktoberfest.
I've also been going through comments in this thread as well as in [#1622](https://github.com/python-telegram-bot/python-telegram-bot/pull/1622) and my understanding is that the bot should serve a 200 OK response through an end-point over Tornado iff it is currently running. I could then look into the callback request.

Currently working in understanding the bot's code and am looking at `webhookhandler.py ` and `updater.py` as possible points to implement solution.

**Comment by Bibo-Joshi** [comment]
Hi. Sorry for missing this, but the hacktoberfest label is actually from two years ago and things have changed a bit since then …
Specifically, we're working towards a conversion to the `asyncio` module (see #2352) and it is unclear how webhooks will be handled after the conversation. We therefore want to wait with tackling this until after the conversion is done.
Still, I'm happy that you consider contributing - maybe one of the other hacktoberfest issues is of interest for you?

**Comment by zpavloudis** [comment]
Hi @Bibo-Joshi, thats understandable - I'm currently looking at #2505.

**Comment by Bibo-Joshi** [comment]
In v20 (pre-released was published recently), setting up a custom setup for fetching updates via webhooks has become way easier, which also allows to include custom endpoints. #3059 linked above adds an example for such a setup that also includes a health end point. We are therefore not planning to integrate such a functionality directly into the library and recommend to leverage the improved flexibility of the `telegram.ext` framework instead :)
