### ISSUE TITLE
new way to handle conversations

### ISSUE THREAD

**Issue by khode-mohsen** [python-telegram-bot/python-telegram-bot#1443]
in handlers we can write a method ,want to run next update with this function 

def usernameHandler (bot, update):
	//code
	bot.send_update_to(emailHandler)

**Comment by Bibo-Joshi** [comment]
Could you clarify your idea? Maybe you can give a full example as pseudo code.

**Comment by Eldinnie** [comment]
Closing.
it's a usage question and they're not responding. If you want to clarify please reply and we can re-open
