### ISSUE TITLE
BufferedReader is not JSON serializable while sending local saved video

### ISSUE THREAD

**Issue by lucadibello** [python-telegram-bot/python-telegram-bot#1446]
### Steps to reproduce
```python
self.update.message.reply_video(self.update.message.chat_id,
                                        open(video_path, 'rb'),
                                        supports_streaming=True,
                                        timeout=self.VIDEO_TIMEOUT
                                        )
```

### Expected behaviour
Send a local saved video

### Actual behaviour
Object of type BufferedReader is not JSON serializable

### Configuration
**Operating System:**
Microsoft Windows 10 Home
Version: 10.0.17763 build 17763

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 12.0.0b1
certifi 2019.03.09
future 0.17.1
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]

**Comment by shrub77** [comment]
I have this issue too with a locally saved photo

**Comment by hameda169** [comment]
@lucadibello @shrub77 
When you are using `Message().reply_video()` or `Message().reply_photo()`, it's not needed to pass chat_id again. Every message has it's chat_id itself. The first attribute of that functions must be `video[open(local_video, 'rb')]` and `photo[open(local_photo, 'rb')]`
