### ISSUE TITLE
loginurl full example with https://comments.app

### ISSUE THREAD

**Issue by alfilesnet** [python-telegram-bot/python-telegram-bot#1448]
Could you create a full example about how to use LoginUrl inline button to connect with https://comments.app ?

Thanks a lots in advance.

**Comment by Bibo-Joshi** [comment]
To connect to a site with a Telegram comments section, simply use

```
login_url = LoginUrl(url='<URL>')
reply_markup = InlineKeyboardMarkup([[InlineKeyboardButton('Text',login_url=login_url)]])
```

Note, that you have to set up your bots domain to the domain of `url` via BotFather or use the `bot_username` parameter of `LoginUrl` with a bot that has the correct domain setting.

To connect with a subpage of https://comments.app, set `url=comments.app/view/<ID>`. You may use `but_username='@discussbot`.

If you want to set up a comments section on your own domain, you will have to handle the authentication yourself (see [here](https://core.telegram.org/bots/api#loginurl)). That however is more of a web delevopement problem, IMHO.

**Comment by Nukesor** [comment]
Can this be issue marked as resolved?

**Comment by Eldinnie** [comment]
It has to be said that we did not yet implement the 4.4 version of the bot api yet, thus LoginUrl is not a valid type yet

**Comment by Poolitzer** [comment]
related to #1494. I am not sure if we need an example, but welp.
