### ISSUE TITLE
Implement inline bots

### ISSUE THREAD

**Issue by jh0ker** [python-telegram-bot/python-telegram-bot#146]
- `answerInlineQuery` as a new Method
- `InlineQuery` as a new type, which can be accessed in the new field `inline_query` in `Update`
- `InlineQueryResult[Article|Photo|Gif|Mpeg4Gif|Video]` as the reply types for answers

**Comment by jh0ker** [comment]
Implementation can now be found on branch inlinebots. Unstable and missing unit tests.

**Comment by carlosmuller** [comment]
Using InlineQueryResultPhoto Doesnt show properly all images, most of time only show blank results. All images I'm using are jpegs  less them 5mb

**Comment by jh0ker** [comment]
@carlosmuller Hmm... Could you show us some of the code?

On another note, the previously documented (and therefore implemented by me) `ChosenInlineResult` has been quietly removed from the API. Your problems may also be related to Telegrams problems with the API.

**Comment by carlosmuller** [comment]
http://pastebin.com/MNv2ReyB
def inlinequery (bot, update):
	if update.inline_query is not None and update.inline_query.query:
		api = "https://api.deckbrew.com/mtg/cards/typeahead?q=<NAME>"
		query = update.inline_query.query.split("//")[0].strip()
		logger.debug("Query is :{0}".format(query))
		cards = requests.get(api.replace("<NAME>",query.lower().replace(",","")).replace("'","")).json()
		images = list()
		i = 0
		if(cards == []):
			return
		if (len(cards) == 1):
			images.append(InlineQueryResultPhoto(id=hex(getrandbits(64))[2:],
												photo_url = cards[0]['editions'][0]['image_url'],
												thumb_url = cards[0]['editions'][0]['image_url']))
			logger.debug("Card {0} : {1}".format(cards[0]['name'],cards[0]['editions'][0]['image_url']))
			bot.answerInlineQuery(update.inline_query.id, results=images)
			return
		for card in cards:
			img =''
			if(card['editions'][0]['multiverse_id']==0):
				img = card['editions'][1]['image_url']
			else:
				img = card['editions'][0]['image_url']
			images.append(InlineQueryResultPhoto(id=i,caption=card['name'],
													title=card['name'],
													photo_url = img,
													thumb_url = img))
			logger.debug("Card {0} {1} : {2}".format(i,card['name'],img))
			i = i +1
		bot.answerInlineQuery(update.inline_query.id, results=images)

**Comment by jh0ker** [comment]
@carlosmuller Hmm. Are you seeing any errors in the log? Also, try to generate a real ID for the results, it should be a unique identifyer for that specific result (you're just using 0..n)

**Comment by carlosmuller** [comment]
No errors, any suggestions to the id ? or just some hex(getrandbits(64))[2:]?

**Comment by jh0ker** [comment]
@carlosmuller I recommend using the uuid module now. It will generate an id and is more clean than using random

**Comment by jgrondier** [comment]
Hey, I've been toying with inline bot yesterday, and I am a bit confused as the Telegram API isn't very precise about it.

I'm trying to get this one bot to send back URLs, but there doesn't seem to be a page preview:


    def inlinequery(bot, update):
        if update.inline_query is not None and update.inline_query.query:
            query = update.inline_query.query
    
            nyaa_list = nyaa.search(query, filter='a_plus')
    
            results = [InlineQueryResultArticle(id=hex(getrandbits(64))[2:], title=x.title, url=x.link,
                                                message_text=x.link, disable_web_page_preview=False,
                                                description=x.title)
                       for x in nyaa_list]
    
            bot.answerInlineQuery(update.inline_query.id, results=results)


Am I missing anything ?

**Comment by jh0ker** [comment]
@jgrondier Some URLs do not generate a preview. Have you tried sending `'http://google.com/'` to check?

**Comment by jgrondier** [comment]
Actually I was trying it as soon as I posted it, seems to be a problem with the website I'm using, thanks.

**Comment by jh0ker** [comment]
@jgrondier Good to hear that :)

**Comment by carlosmuller** [comment]
I tried with lib uuid and still no better, i will try with another host to see if works

**Comment by carlosmuller** [comment]
My problem is resolved, I have to put height and width.  Thanks for the support

**Comment by carlosmuller** [comment]
Anothe question how to use offset?

**Comment by jh0ker** [comment]
@carlosmuller Check the documentation about that in the telegram bot api documentation: https://core.telegram.org/bots/api#answerinlinequery
