### ISSUE TITLE
Open Browser, just a question

### ISSUE THREAD

**Issue by ah8ad3** [python-telegram-bot/python-telegram-bot#1467]
Hi,
Thanks for the sdk

i want to redirect user to specific website, but without click or type anything can i?
i can not found any document about that!

**Comment by Bibo-Joshi** [comment]
As far as I know, there is no way to open a website by a command. The simplest way would be to either put the link in a message (plain URL or as text link) or to add an `InlineKeyboardButton`.

**Comment by ah8ad3** [comment]
Ok thanks
