### ISSUE TITLE
Feature Request: coroutines support

### ISSUE THREAD

**Issue by USSX-Hares** [python-telegram-bot/python-telegram-bot#1469]
Hi!
Could you add option to register coroutine as a callback (i.e., for ability to use python async/await syntax), as well as asynchronous versions of `send_message()` and other similar methods?

Thank you

**Comment by Eldinnie** [comment]
Hi @USSX-Hares 

Yes ultimately that would be great, but for now that is not going to happen yet.
First of all we still support Python 2.7 until it's [end of life](https://pythonclock.org/). Secondly, rewriting the library to support asyncio would mean a massive overhaul. In the end we will propaply do it, but not in the near future.

**Comment by JokerQyou** [comment]
Well, Python 2.7 had already met its end of life, it'll be good to get start. 😃

**Comment by Ghostbird** [comment]
Yes please! I have little experience with Python's `asyncio` so I have no trouble, writing async-all-the-way code, or writing pure callback based code. However now I'm stuck trying to somehow get a call to a purely async library working from a `python-telegram-bot` callback, and I just can't get it working.

**Comment by Bibo-Joshi** [comment]
closing in favor of #2288
