### ISSUE TITLE
'Updater' object has no attribute 'job_queue'

### ISSUE THREAD

**Issue by mr-karan** [python-telegram-bot/python-telegram-bot#147]
I get the error 'Updater' object has no attribute 'job_queue' . I have Python 3.5.1 and installed python-telegram-bot using Pip in a virtual environment. Though I later fixed this issue by installing using the git link directly, I am curious to know why didn't Pip installed the latest version which should have job_queue method ?

**Comment by jh0ker** [comment]
We just pushed the new release a few minutes ago, you might just want to try again! ;)

**Comment by jh0ker** [comment]
If the issue persists after upgrading the pip package, feel free to re-open this issue :)
