### ISSUE TITLE
messages.addChatUser

### ISSUE THREAD

**Issue by mrb0098** [python-telegram-bot/python-telegram-bot#1471]
can i use [this api method](https://core.telegram.org/method/messages.addChatUser) with python-telegram-bot ?

**Comment by Bibo-Joshi** [comment]
The PTB library only provides the methods listed in the [Telegram Bots API](https://core.telegram.org/bots/api). Telegram Bots cannot add users to groups (but can [kick](https://core.telegram.org/bots/api#kickchatmember) them).
Maybe an invite link will work for you? (See [here](https://core.telegram.org/bots/api#exportchatinvitelink) and [here](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.export_chat_invite_link))

However, a quick google search lead me to this [SO question](https://stackoverflow.com/a/52385143/10606962) and the [MadelineProto](https://github.com/danog/MadelineProto) library (PHP). If I understand correctly, MadelineProto enables you to interact with Telegrams methods _as user_. Note that this is not, what PTB wants to do.

**Comment by Bibo-Joshi** [comment]
Closing this, since @mrb0098 seems to be satisfied with the answer (gave thumbs up)
