### ISSUE TITLE
Errors when setting music bot

### ISSUE THREAD

**Issue by Dummyjaii10852** [python-telegram-bot/python-telegram-bot#1498]
Starting...
Passed Git checks...
You have modified files that are tracked by Git (e.g the bot's source files).
Should we try resetting the repo? You will lose local modifications. (y/n): y
HEAD is now at 3976fe0 Set bot version string to git describe result
Checking if we need to update the bot...
Already up to date.
Attempting to update dependencies...
Collecting pynacl==1.2.1 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/28/44/577007ec0e7c05ebf667
9a1d8f98e53576b337c3e87af2619d9e249ff20b/PyNaCl-1.2.1-cp37-cp37m-win32.whl (158k
B)
Traceback (most recent call last):
  File "update.py", line 17, in update_deps
    subprocess.check_call('"{}" -m pip install --no-warn-script-location --user
-U -r requirements.txt'.format(sys.executable), shell=True)
  File "C:\Users\Dummy\AppData\Local\Programs\Python\Python37-32\lib\subprocess.
py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"C:\Users\Dummy\AppData\Local\Programs\P
ython\Python37-32\python.exe" -m pip install --no-warn-script-location --user -U
 -r requirements.txt' returned non-zero exit status 120.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update.py", line 76, in <module>
    main()
  File "update.py", line 72, in main
    update_deps()
  File "update.py", line 19, in update_deps
    raise OSError("Could not update dependencies. You will need to run '\"{0}\"
-m pip install -U -r requirements.txt' yourself.".format(sys.executable))
OSError: Could not update dependencies. You will need to run '"C:\Users\Dummy\Ap
pData\Local\Programs\Python\Python37-32\python.exe" -m pip install -U -r require
ments.txt' yourself.

C:\Users\Dummy\Desktop\Bot\MusicBot>

**Comment by tsnoam** [comment]
This has nothing with this project.
