### ISSUE TITLE
Google App Engine Compatibility

### ISSUE THREAD

**Issue by hbirler** [python-telegram-bot/python-telegram-bot#150]
Google App Engine is not compatible with the Updater Module.

**Comment by jh0ker** [comment]
Can you please give a bit more detail on that?

**Comment by hbirler** [comment]
1-) The webhook handler's reliance on BaseHTTPServer seems to make it incompatible with GAP from my initial tests. I will check again if this is the case but from what I know GAP doesn't support BaseHTTPServer.
2-) Polling doesn't seem to work either.
I am not really experienced with GAP so I can't confirm whether these issues are reproducable or an error on my side.
(I don't have a lot of free time these days. Sorry if I am unable to respond or can't find the time to implement a solution.)

**Comment by taemery** [comment]
Google App Engine does not support using the signal library (imported in the Updater class) causing a fatal error

**Comment by taemery** [comment]
#184 Can be merged

**Comment by leandrotoledo** [comment]
As stated by @taemery let's keep this discussion on #184
