### ISSUE TITLE
command handler with sqlalchemy is not working with job_queue.

### ISSUE THREAD

**Issue by realblack0** [python-telegram-bot/python-telegram-bot#1513]
Hello. I'm trying to make a bot checking new posts.
I hope the bot sends message using User.db.
Command handler didn't update DB when job_queue is running. (It updates DB well without job-queue)

```python

# sqlalchemy DB
class User(base):
    __tablename__ = "User"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer)
    subscribe = Column(Boolean)

def subscribe_command(update, context):
    context.bot.send_message(chat_id=update.message.chat_id,
                             text="processing...")

    user_id = update.message.chat.id
    subs = session.query(User.subscribe).filter(User.user_id == user_id)
    if subs.first()[0] == False:
        subs.update({User.subscribe:True})
        session.commit()
        context.bot.send_message(chat_id=user_id,
                                 text="Subscription starts.")

    else:
        context.bot.send_message(chat_id=user_id,
                                 text="Already applied.")


    context.bot.send_message(chat_id=user_id,
                             text="complete")

subscribe_command = CommandHandler("subscribe", subscribe_command)


def unsubscribe_command(update, context):
    context.bot.send_message(chat_id=update.message.chat.id,
                             text="processing...")

    user_id = update.message.chat.id
    subs = session.query(User.subscribe).filter(User.user_id == user_id)
    if subs.first()[0] == True:
        subs.update({User.subscribe:False})
        session.commit()
        context.bot.send_message(chat_id=user_id,
                                 text="Subscription ends.")
    else:
        context.bot.send_message(chat_id=user_id,
                                 text="Not applied yet.")

    context.bot.send_message(chat_id=user_id,
                             text="complete")

unsubscribe_command = CommandHandler("unsubscribe", unsubscribe_command)


updater.dispatcher.add_handler(subscribe_command)
updater.dispatcher.add_handler(unsubscribe_command)


# Crawler
def check_update(context):
    url = "https://test.com"
    previous = "test"

    resp = requests.request("get", url)
    dom = BeautifulSoup(resp.text, "lxml")
    current = dom.select_one(".board_title > a").text.strip()
    if not previous == current:
        for user_id in session.query(User.user_id).filter(User.subscribe==True):
            context.bot.send_message(chat_id=user_id[0],
                text="New posting on the Notice-board. \n{}\n{}".format(current, url))


j = updater.job_queue
j.run_repeating(check_update, interval=10, first=0)

updater.start_polling(timeout=3, clean=True)
updater.idle()
```

### Expected behaviour
Bot sends message to who are registered as subscriber in DB.
Check for new post on given URL periodically, and send a message to subscribers when a new posting appears.
I set interval as 10 seconds and previous title as "test" for test.

When "/subscribe" command is given, bot updates DB. Also "/unsubscribe" command works in opposite way.

### Actual behaviour
Sending new posting message is working well every 10 seconds. 
But when "/subscribe" command was given, subscribe_command didn't update DB.
Bot only replied "processing" message which is on first line in the function. The if statement and sending "complete" message were not executed. 

Also, I tested each function independently. It worked well. subscribe_command updated DB and sent "complete" message. The issue occurs when executing with job_queue.

I experienced same issue before. I tried to use threading library. At that time, I set crawler as daemon thread. As I know, updater.idle() uses thread internally, I'm guessing this issue related to thread...

### Configuration
**Operating System:**
windows10 pro

**Version of Python, python-telegram-bot & dependencies:**
Python 3.7
python-telegram-bot 12.0.0

**Comment by Poolitzer** [comment]
Hi,

We invite you to ask questions about the usage of this library in our Telegram group. In case you are unable to join our group due to Telegram restrictions, you can use our IRC channel to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.

P.S.: Adding logging will definitly help you troubleshooting :)
