### ISSUE TITLE
Bot dict return wrong value for first_name

### ISSUE THREAD

**Issue by ARSujonID** [python-telegram-bot/python-telegram-bot#1519]
### Steps to reproduce
1. ``from telegram import Bot``

2. ``bot: Bot = Bot(token='708626524:abc-token')``

3. ``print(bot.to_dict())``

### Expected behaviour
``{'id': 708626524, 'username': 'for_testx_bot', 'first_name': 'For Test'}``

### Actual behaviour
``{'id': 708626524, 'username': 'for_testx_bot', 'first_name': 'for_testx_bot'}``

### Configuration
Microsoft Windows [Version 10.0.16299.15]
(c) 2017 Microsoft Corporation. All rights reserved.

(venv) E:\Working\Running_Projects\abc>python -m telegram
python-telegram-bot 12.1.1
certifi 2019.09.11
future 0.17.1
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]

### More Info
![bot_issue](https://user-images.githubusercontent.com/55732633/65488023-f31bf800-dec9-11e9-8d7a-82befc3e14f9.PNG)

**Comment by clonex10100** [comment]
I would like to try to work on this for hacktoberfest.

**Comment by Poolitzer** [comment]
way to go :)

**Comment by Poolitzer** [comment]
Oh @clonex10100, you didnt submit a PR for that. #1528 beat you to it :( Im so sorry, since you did the work already...
