### ISSUE TITLE
doesn't raise exceptions in info level and raise them in debug level ! 

### ISSUE THREAD

**Issue by mmdaz** [python-telegram-bot/python-telegram-bot#1521]
### Expected behavior
Raise exceptions in the info level of logging (default level of it)
Becuase exception level is higher than the info level.
### Actual behaviour
Raise exceptions when I am setting the logging level to debug.

**Comment by Poolitzer** [comment]
Hey,
First of all, your title and the body of your issue are contradictory. I am going to assume that the title is what you actually want. Now that we have that out of the way, may I ask why exactly you need them in debug?

**Comment by mmdaz** [comment]
@Poolitzer 
My title is ok
I am saying that when I set the log level  to  debug, I see exceptions
But in the info level (default level of logging module in python) I don't see exceptions.
I except that see these exceptions in info level because exception level is higher than info level.

**Comment by tsnoam** [comment]
@mmdaz Hi,

We, the maintainers, find it somewhat difficult to understand what exactly is the problem. 

Can you please supply a minimalistic example code and specify what is the behaviour you&#x27;d expect and what is the behaviour in practice?

Thanks!

**Comment by mmdaz** [comment]
@tsnoam 
I'm sorry for the delay.
I'm mean when I set the level of logging to DEBUG I can see exceptions.
```  logging.basicConfig(level=logging.DEBUG) ```
But the expected result is that It should show exception logs without using the top line.

**Comment by jh0ker** [comment]
@mmdaz I don't think your problem has anything to do with log levels. You simply need this line to enable logging at all. Without it, no logs are visible, no matter of level.

It is your responsibility to enable logging if you want it.

**Comment by mmdaz** [comment]
@jh0ker 
Yes
I realized what you say and my problem was solved.
thanks :)
