### ISSUE TITLE
drop python2 support

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#1538]
That means to remove it from:

- [ ] README.rst
- [ ] CONTRIBUTING.rst
- [ ] .pre-commit-config.yaml
- [ ] .travis.yml
- [ ] appveyor.yml
- [ ] setup.py
- [ ] tox.ini
- [ ] all tests (hihi)

We can even think about dropping all the python2 workarounds we have in the library itself:

- [ ] remove `future` from requirements and all the imports
- [ ] `_UTC` in `telegram.utils.helpers`
- [ ] Workaround in `telegram.InputFile.__init__()`
- [ ] `from builtins import str` in `telegram.utilts.request`
- [ ] `test_send_on_server_emoji`
- [ ] imports in `test.updater`

(This list is not comprehensive)

**Comment by Poolitzer** [comment]
@jh0ker funny how you write the most work required part. But yes. We should.

**Comment by Bibo-Joshi** [comment]
Took the liberty to add some ToDos to the description ;) We can update that list, if we stumble across some workaround while coding something else …

**Comment by septatrix** [comment]
Hey, if possible I would like to work on this.
I already started a bit and would create a WIP merge request tomorrow...

**Comment by Bibo-Joshi** [comment]
Sure, please go ahead :)

**Comment by septatrix** [comment]
Pull request is now live #1715...

**Comment by Poolitzer** [comment]
#1731 removed 2.7 from the workflow to reduce testing time

**Comment by Bibo-Joshi** [comment]
Closed by #1715
