### ISSUE TITLE
Is payment also working for iOS?

### ISSUE THREAD

**Issue by MalteToenjes** [python-telegram-bot/python-telegram-bot#1539]
When the payment function was released by telegram I think it was restricted for iOS users. I'm curious if its allowed now, since I can't find any update about this when I google...

**Comment by Poolitzer** [comment]
I never knew it doesnt work for ios, but I bet it does now. Just get an iphone and test ;P or maybe ask in https://t.me/telegramiostalk

Anyway, not related to the library, closing
