### ISSUE TITLE
multipart/form-data

### ISSUE THREAD

**Issue by Carlovan** [python-telegram-bot/python-telegram-bot#154]
`multipart/formdata` upload method doesn't work to send files.

**Comment by jh0ker** [comment]
Hi! Would you please post the error message that you get and the code that causes it?

**Comment by Carlovan** [comment]
I don't get any error, it simply doesn't work. I tried passing a `file` object with open(), an `InputFile` and `InputFile.to_form()` to `bot.sendDocument`  but nothing happens. I managed to do it using directly the `requests` module.

**Comment by jh0ker** [comment]
This line should work fine:
    bot.sendDocument(chatid, document=open(filename, 'rb') 
Make sure you put 'rb' as the mode so it will read the file in binary mode. You should not be using InputFile for this task.

**Comment by Carlovan** [comment]
Yes it works. Thanks. I think you should add this example to the README

**Comment by jh0ker** [comment]
There is an example with sendVoice which works just the same way, but it might need some clarification :) 
Thanks for using the library! Feel free to also ask questions in our telegram group (the invitation  link can be found at the top of the Readme)

**Comment by hamidzr** [comment]
This fails in python3.5 whereas the exact same thing works on python2.7. ( it times out when uploading a big file, bigger than 2 mb  )

**Comment by Rostgnom** [comment]
@hamidzr I can confirm this, as it's only in the current master branch.
