### ISSUE TITLE
Dispatcher.processUpdate update with context

### ISSUE THREAD

**Issue by jlmadurga** [python-telegram-bot/python-telegram-bot#156]
Hi all,

It is great to use dispatcher to process commands but I think is not very flexible as it only accept Update data. 
I am using  `dispatcher.processUpdate` in a django view to handle the Update but I also need some of request context data to generate the response.

**Comment by jh0ker** [comment]
Hi! Have you considered using Dispatcher.addTypeHandler? It enables you to dispatch objects of any type.

**Comment by jlmadurga** [comment]
Its an option but encapsulateing Update plus extra data in a TypeHandler I will lose the possibility of using the other great commands handlers. 
I am using processUpdate for every POST. So I think the cleanest design would be:
```
 def processUpdate(self, update,**kwargs):
        # for every update
         ....
         self.dispatchStringCommand(update, **kwargs)
```
Using a TypeHandler will be an option but will need to preprocess update to generate different Command + extra data types.

**Comment by jh0ker** [comment]
@jlmadurga You might use a type handler and a command handler together. You can process the custom class first and re-insert the update itself back into the update_queue so it will be handled by the right command handler. Would that be an option?

**Comment by jh0ker** [comment]
Oh wait, you're not using the update queue, right? Hmm... You could just call processUpdate with the encapsulated Update though

**Comment by jlmadurga** [comment]
No I am not using the queue. 
In my opinion adding **kwargs to processUpdate and dispatchers will fit in the design. `dispatchTo` is already prepared to accept kwargs
 ```
    def dispatchTo(self, handlers, update, **kwargs):
        """
        Dispatches an update to a list of handlers.
        Args:
            handlers (list): A list of handler-functions.
            update (any): The update to be dispatched
        """

        for handler in handlers:
            self.call_handler(handler, update, **kwargs)

```

**Comment by jh0ker** [comment]
I agree. Do you have an idea about how this could be implemented so it will also benefit users that work with the update_queue?

**Comment by jlmadurga** [comment]
We should override standard `Queue` for `update_queue` trying to preserve the standard function signatures. Not everyone must deal with our customized Queue. So lets them keep think it is the standard one :)  

We can store it as a tuple
```
def put(self, item, block=True, timeout=None, context=None):
         ...
        if not context:
               self._put(item)
        else:
               self._put((item, context))
```
Just in case it is requested return tuple instead of only the Update item.
```
def get(self, block=True, timeout=None, context=False):
               ...
                 if not context:
                       return item[0]
                 else:
                       return item
```
I think this is a good way not to disturb standard users. Just if you want to use context you have to explicitly `put` and `get`  (in `get` method we can detect if context but I consider better to keep it explicitly)

Tell me your opinions and I cant work in the PR if you want

**Comment by jh0ker** [comment]
That approach seems good. For consistency, I'd always put a tuple into the queue (the second part being None in the default case). Feel free to submit a pull request, they're always welcome! Please take a look at CONTRIBUTING before you start :)
