### ISSUE TITLE
reading MASCONS

### ISSUE THREAD

**Issue by krisangh** [python-telegram-bot/python-telegram-bot#1561]
### Steps to reproduce
1.runfile('C:/Users/dell/Documents/WA_PKS/Sheet4_6_Subarn/grace_for_basin.py', wdir='C:/Users/dell/Documents/WA_PKS/Sheet4_6_Subarn')
C:/Users/dell/Documents/WA_PKS/Sheet4_6_Subarn/grace_for_basin.py:35: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_info = pd.read_csv(MASCON_INFO, sep=r"\s*", header=None, skiprows=11)
C:/Users/dell/Documents/WA_PKS/Sheet4_6_Subarn/grace_for_basin.py:38: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_dates = pd.read_csv(MASCON_DATES, sep=r"\s*", header=None, skiprows=10)
Traceback (most recent call last):

  File "<ipython-input-1-52ebb93f0de8>", line 1, in <module>
    runfile('C:/Users/dell/Documents/WA_PKS/Sheet4_6_Subarn/grace_for_basin.py', wdir='C:/Users/dell/Documents/WA_PKS/Sheet4_6_Subarn')

  File "C:\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/dell/Documents/WA_PKS/Sheet4_6_Subarn/grace_for_basin.py", line 51, in <module>
    w = shapefile.Writer(shapefile.POLYGON)

  File "C:\Anaconda2\lib\site-packages\shapefile.py", line 1057, in __init__
    self.shp = self.__getFileObj(os.path.splitext(target)[0] + '.shp')

  File "C:\Anaconda2\lib\ntpath.py", line 200, in splitext
    return genericpath._splitext(p, sep, altsep, extsep)

  File "C:\Anaconda2\lib\genericpath.py", line 99, in _splitext
    sepIndex = p.rfind(sep)

AttributeError: 'int' object has no attribute 'rfind'

2.

3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by Bibo-Joshi** [comment]
Hi,

We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.
