### ISSUE TITLE
[BUG] Change condition in Filters.user to avoid error with empty lists

### ISSUE THREAD

**Issue by xates** [python-telegram-bot/python-telegram-bot#1562]
Consider changing this condition
https://github.com/python-telegram-bot/python-telegram-bot/blob/88eccc6608d141004d231b38df76492e1c5f5b93/telegram/ext/filters.py#L796
 to something like
```python
if (user_id is None) == (username is None):
```
To avoid throwing the `ValueError` _"One and only one of user_id or username must be used"_ when an empty list of `user_id`s **or** `username`s is issued.

Similarly for `Filters.chat`.

PS This should also be 3 to 4 times faster.

**Comment by xates** [comment]
(I can make a PR if you wish)

**Comment by tsnoam** [comment]
@xates Hi,

Please help us to understand what is the problem. As we understand it:
1. <code>One and only one of user_id or username must be used</code>
2. Neither user_id nor username are legitimate as empty lists.

What is the usecase which you were trying to use?

**Comment by xates** [comment]
> Please help us to understand what is the problem. As we understand it:
> 
> 1. `One and only one of user_id or username must be used`
> 2. Neither user_id nor username are legitimate as empty lists.

The problem is that currently if an empty list of either user ids or usernames is used, it is still considered by the cited precondition as if no parameter was set, because` bool([]) = False`, where instead it is actually set.

> What is the usecase which you were trying to use?

A function of the bot that is restricted (or prohibited) to a certain group of users which may be empty at the first start of the bot or generally up to a certain moment.

**Comment by tsnoam** [comment]
@xates Thanks for clarifying.
This was not a use case we initially thought of, however it is a very reasonable one.
While fixing this bug we should take into account thread safety.

Also, if you&#x27;d like to write the fix, we&#x27;ll be happy to see the PR.
Just write down how you intend to tackle thread safety prior to implementation. So we&#x27;ll be in sync about that.

**Comment by xates** [comment]
I didn't think about thread safety, honestly. The solution I had thought of is the one in the opening post.
I can't imagine in which situation a problem could arise, though.
I am not very shrill on the subject either.
