### ISSUE TITLE
Keyboard buttons

### ISSUE THREAD

**Issue by escobarjj** [python-telegram-bot/python-telegram-bot#1575]
Hi!

I am worried about the fact that maybe this space is not the appropriate one to post this question but I am in a hurry... I have understood how the custom keyboard buttons work but what if I need a numeric keyboard in order to make the end-user type a valid number greater than a unit, e.g. 1000, etc. Not to send a single number once it is pressed. This can be done? Am I missing some additional arguments?

Thanks in advance!

PD: if it is not possible to do this in this way, what would you suggest?

**Comment by Poolitzer** [comment]
Hey. What are you using, reply or inline keyboard?

**Comment by escobarjj** [comment]
Sorry! I am using reply keyboard

**Comment by Poolitzer** [comment]
Okay. What stops you from doing a ReplyKeyboard("1000")?

**Comment by escobarjj** [comment]
I mean, it could be any integer

**Comment by Poolitzer** [comment]
Exactly. Just give it there as I showed you. I dont see the/your problem

**Comment by escobarjj** [comment]
Sorry, I haven't explained very well... A use case could be for example asking the end-user to type the percentage of accomplishment of the sales in the past week. In this case, I could get answers from 0 to 100... because of that, I would want to limit the user to type just numbers setting a numeric keyboard

**Comment by Poolitzer** [comment]
In my opinion, thats now how keyboards (neither reply nor inlines) are designed to work. If I were you, I would ask teh user to send me the number, then run a simple check like that:
```python
try:
    number = int(update.effective_message.text)
    if not 0 <= number <= 100:
        raise ValueError
except ValueError:
    update.effective_message.reply_text("I am sorry, you need to send me a number between 0-100, nothing else")
    return
whatever_you_want_now
```

**Comment by escobarjj** [comment]
I was about to do something like that... You were really helpful, thanks!

**Comment by Poolitzer** [comment]
no problem, glad I could help :)
