### ISSUE TITLE
Implement HTML parse mode

### ISSUE THREAD

**Issue by tapionx** [python-telegram-bot/python-telegram-bot#158]
I recieved this from Telegram BotNews channel:

```
We forgot to announce this, but you can use either 
HTML-style or markdown-style formatting in your bot's 
messages to get italic, bold or fixed-width text and inline links.

See this section for details:
https://core.telegram.org/bots/api#formatting-options
```

It seems that they added a new parsing method:
https://core.telegram.org/bots/api#html-style
https://core.telegram.org/bots/api#sendmessage

I would like to use this feature on the Bot

**Comment by jh0ker** [comment]
@tapionx Hi! 
For now, you can just pass `parse_mode='HTML'` in `sendMessage`, we'll add a corresponding constant in the next release.

**Comment by tapionx** [comment]
```
bot.sendMessage(parse_mode='HTML', chat_id=********, text='<b>test</b>')
```
It works! ;)
You can close this for me, maybe just add this in the documentation?

**Comment by jh0ker** [comment]
Great :) I will add it to the documentation :)

**Comment by 0ppp9** [comment]
not working for me!!!! text worked now when i try HTML or Markdown simply fails wih a 502 bad gateway error!

**Comment by fuuman** [comment]
@0ppp9 Jup, same error here. HTML Messages are just failing.

**Comment by evstratbg** [comment]
@0ppp9 @fuuman Have you checked html tags? Are they correct?

**Comment by fuuman** [comment]
Jup, my bad, sorry. I used unsupported tags.

@0ppp9: I guess that's your problem, too. Take a look at: https://core.telegram.org/bots/api#formatting-options

**Comment by peterremote1980** [comment]
supports color?

**Comment by JosXa** [comment]
Doesn't.
