### ISSUE TITLE
[QUESTION] get message type

### ISSUE THREAD

**Issue by moonlightam** [python-telegram-bot/python-telegram-bot#1580]
hello, i have a problem to get type of messages after it calledd back to a function
e.g.
```
MessageHandler(filters=Filters.all,callback=test)
def test(update,context):
   info= # here i want to get message type
```

**Comment by jh0ker** [comment]
@moonlightam What exactly do you mean by &quot;message type&quot;

**Comment by moonlightam** [comment]
for example 'text' , 'video' , ...

**Comment by jh0ker** [comment]
There is no built-in way to get the type directly. You'd have to test if `update.message.text`, `update.message.video` etc. are set or not.
See https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html for all `Message` attributes available.

**Comment by moonlightam** [comment]
tnx a lot
