### ISSUE TITLE
[QUESTION]entities

### ISSUE THREAD

**Issue by moonlightam** [python-telegram-bot/python-telegram-bot#1582]
i have a problem to detect url in message i see entities in telegram.message but i really confused how to use it i want to complete this if

> if(update.message.entities.URL!=None):
>     # codes
i'm sure that is wrong i see perse_entities but i don't know how to use
i see docs and i can't send message to telegram group so by searching i find nothing to help

**Comment by Poolitzer** [comment]
Hey there. I always recommend using Filters in this case. Since ou want to handle URL and text link probably, go with `(Filters.entity(URL) | Filters.entity(TEXT_LINK))`. 
If you later want to extract the actual link, do it like this:
```python
import MessageEntity
entities = update.message.parse_entities([MessageEntity.URL, MessageEntity.TEXT_LINK])
links = []
for entity in entities:
        if entity == MessageEntity.TEXT_LINK:
            links.append(entities[entity].url)
        elif entities[entity].type == MessageEntity.URL:
            links.append(entities[entity])
```

**Comment by Poolitzer** [comment]
closing since that seems to have resolved it
