### ISSUE TITLE
Spamming logs when no connection

### ISSUE THREAD

**Issue by electrofloat** [python-telegram-bot/python-telegram-bot#1584]
Every time my internet connection dies, the api starts to spam my logs with these 4 lines every couple of seconds:
https://pastebin.com/ZsCYpyFg
these continue until the connection comes back up.

Pretty annoying since I use logcheck which sends me system logs every 10 minutes, and I get hundreds of lines of logs from telegram while my connection is down.

### Steps to reproduce
1.
To easily reproduce the issue deny access to api.telegram.org
`iptables -I OUTPUT -p tcp --dport 443 -d api.telegram.org -j DROP`

### Expected behaviour
It should only log the connection error **once** until the connection comes back up again.
If for some reason this is _not_ the expected behavior for you, you can make this configurable, or point me to the right direction in the code where this happens, so that I can manually change it.

### Actual behaviour
It spams these 4 lines every couple of seconds:
https://pastebin.com/ZsCYpyFg

### Configuration
Linux

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
```
(homeassistant) homeassistant@tada:~/homeassistant$ python3 -m telegram
python-telegram-bot 11.1.0
certifi 2019.09.11
future 0.18.1
Python 3.6.8 (default, Oct  7 2019, 12:59:55)  [GCC 8.3.0]
```

### Logs
Insert logs here (if necessary)
https://pastebin.com/ZsCYpyFg

**Comment by electrofloat** [comment]
Ok, so I found where the ERROR is logged:
https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/updater.py#L345

but for the 3 warnings, they are coming from urllib3?
and the urrlib3's log level is set here:
https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/utils/request.py#L63

So I could probably come up with a solution to only log the error once, but I don't know how to handle the urllib3's warnings...

**Comment by jh0ker** [comment]
Well, it tells you in the log where the warning comes from: [`telegram.vendor.ptb_urllib3.urllib3.connectionpool`](https://github.com/python-telegram-bot/urllib3/blob/d2403a79fc38afbdd9aba8a05d274a83dc8bb412/urllib3/connectionpool.py#L689)

this is because we use the automatic retry feature of urllib3 and that apparently logs at the `warning` level. 
We have our own fork of urllib3 for unrelated reasons, in case you wonder.

**Comment by electrofloat** [comment]
> this is because we use the automatic retry feature of urllib3 and that apparently logs at the `warning` level.
> We have our own fork of urllib3 for unrelated reasons, in case you wonder.

Sounds great. That means the warnings spam can also be fixed.

**Comment by Bibo-Joshi** [comment]
I'm not sure if filtering the log by default is a good idea.  After all, the messages are there for a reason  … Introducing parameters somewhere for that seems over the top to me.
You could add a [logging filter](https://docs.python.org/3/library/logging.html#filter-objects) to make sure that you e.g. only get the updater-errors and at most once every 10min. I guess you can even achieve the "only 1 message until the connection comes back on" thingy with filters, as ptb logs successfull `get_updates` requests on debug level irrc.
On a side node: If you haven't done that already, you should revoke the bot token you posted in the pastebin ;)

**Comment by thisguyeseme** [comment]
Can you assist on how i can actually create a webhook for my bot to get
feedbacks from google?

**Comment by Bibo-Joshi** [comment]
> Can you assist on how i can actually create a webhook for my bot to get feedbacks from google?

Hi,

please don't randomly chime in on old issues. We invite you to ask questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
