### ISSUE TITLE
[BUG] DeprecationWarning in vendored urllib3

### ISSUE THREAD

**Issue by setop** [python-telegram-bot/python-telegram-bot#1586]
### Steps to reproduce

1. ` python -Wd -c "import telegram.ext"`

### Expected behaviour

no output

### Actual behaviour

```
.venv/lib/python3.7/site-packages/future/standard_library/__init__.py:65
  .venv/lib/python3.7/site-packages/future/standard_library/__init__.py:65: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

.venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/selectors.py:11
  .venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/selectors.py:11: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import namedtuple, Mapping

.venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/_collections.py:2
  .venv/lib/python3.7/site-packages/telegram/vendor/ptb_urllib3/urllib3/_collections.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Mapping, MutableMapping
```

### Configuration
**Operating System:**

Linux  4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

**Version of Python, python-telegram-bot & dependencies:**

python-telegram-bot 12.2.0
certifi 2019.09.11
future 0.18.1
Python 3.7.3 (default, Apr  3 2019, 05:39:12)  [GCC 8.3.0]

### Logs

none

### complement

`python -Wd -c "import urllib3"` outputs nothing.

**Comment by tsnoam** [comment]
we should make a unitest for this.

**Comment by tsnoam** [comment]
A unitest wasn't created, because `future` dependency has its own deprecation warning.
May reconsider when we stop py2.7 support and then we can drop `future`.
