### ISSUE TITLE
Wiki about writing unit tests is scarce

### ISSUE THREAD

**Issue by higton** [python-telegram-bot/python-telegram-bot#1592]
The current documentation in unit testing needs examples on how to make unit-tests with bot, the actual documentation just refers to some not maintained solutions.

My proposal is to document how to mock test the bot with some examples like [this wiki](https://github.com/rubenlagus/TelegramBots/wiki/Bot-Testing), mocking to perform unit testing with the bot was the only solution i could find to test the bot on the project i am currently working with.

**Comment by Bibo-Joshi** [comment]
Hi @higton. Additional documentation almost never hurts and we've been asked about the tests routines multiple times, indeed. I've you're willing to try and put together some basic information for our wiki, we'd be glad :)

**Comment by Bibo-Joshi** [comment]
Since there has been no feedback for a while and this is not an issue with the library strictly speaking, I'll be closing this. Still, anyone is welcome to contribute to the wiki :)
