### ISSUE TITLE
What do you use to create state diagrams?

### ISSUE THREAD

**Issue by jekeam** [python-telegram-bot/python-telegram-bot#1593]
With what do you create [these ](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/conversationbot2.png) state diagrams?

**Comment by jh0ker** [comment]
@jekeam We used [Umbrello](https://umbrello.kde.org/) with a modified color scheme. Go to `Diagram > New > State Diagram...` to create this type of diagram.

**Comment by jh0ker** [comment]
Closing this since you reacted with :+1:, feel free to re-open the issue if you have more questions.
