### ISSUE TITLE
Custom Filters: Wiki and code are in conflict

### ISSUE THREAD

**Issue by ema-pe** [python-telegram-bot/python-telegram-bot#1595]
About custom filters, the [Wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-Advanced-Filters#custom-filters) says that the `filter` method accepts a `Message` instance, but in the [source code it accepts](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/filters.py#L114) only an `Update` instance.

What is right? Should the Wiki be updated (and can I update the accused page)?

**Comment by jh0ker** [comment]
You are correct, good catch!
The wiki is wrong, this has been changed in https://github.com/python-telegram-bot/python-telegram-bot/pull/1221
Feel free to update the wiki page :slightly_smiling_face:

**Comment by ema-pe** [comment]
@jh0ker it is not easy, because in the [source code](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/filters.py#L73) `filter` can accepts also a `Message`. Why there are two equivalent options?

**Comment by Eldinnie** [comment]
@ema-pe Well. It&#x27;s not wrong are it is...
Because we long as you don&#x27;t set the class attribute <code>update</code> on your custom, only accepting a message is fine

**Comment by ema-pe** [comment]
> @ema-pe Well. It's not wrong are it is...
> Because we long as you don't set the class attribute `update` on your custom, only accepting a message is fine

You're right, I did not see the class attribute. But `filter`'s method documentation should be updated.

**Comment by Eldinnie** [comment]
@ema-pe I agree on that. Would you be comfortable creating a PR to fix it?

**Comment by ema-pe** [comment]
> @ema-pe I agree on that. Would you be comfortable creating a PR to fix it?

Yes, I'm creating a PR

**Comment by ema-pe** [comment]
Here is the PR: #1596

**Comment by Bibo-Joshi** [comment]
#2032 clarifies this. As it's already merged into the v13 branch, I'll go ahead and close this issue.
