### ISSUE TITLE
Exception Handling Wiki's page is deprecated

### ISSUE THREAD

**Issue by ema-pe** [python-telegram-bot/python-telegram-bot#1597]
Hi, I think that [Exception Handling on Wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Exception-Handling) describes old way to handle python-telegram-bot exceptions. The [API documentation](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.dispatcher.html#telegram.ext.Dispatcher.add_error_handler) is different. Should be the Wiki page updated?

**Comment by Poolitzer** [comment]
yes, it is indeed. Do you want to tackle the update?

**Comment by ema-pe** [comment]
Yes, I'll update the Wiki in the next days (or weeks, I'm a bit busy).

**Comment by ema-pe** [comment]
This is [my revision](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Exception-Handling/08347541025272e021c6199cb13773681589e4b7), I updated error handling with context based API.

**Comment by Poolitzer** [comment]
almost perfect, but since 12.1, every error in handlers gets fowarded to the error handler. I edited it slighty, thank you so much though for the main work!
