### ISSUE TITLE
Make tests more generic

### ISSUE THREAD

**Issue by leandrotoledo** [python-telegram-bot/python-telegram-bot#16]
The way it is right now it will fail if not ToledosPalaceBot, if more generic Travis could run all the tests when pull requesting, etc.

**Comment by Jzarecta** [comment]
I want to learn how the module handles the declared commands assigned by botfather and be able to route them to the desired action.

**Comment by leandrotoledo** [comment]
Hi @Jzarecta, it doesn't. Bot API doesn't provide methods to get declared commands, you have to create your own handlers parsing text messages when polling updates from their servers. Have a look at examples folder from this repository, hopefully it will be a good start.

Feel free to reach out me for any further questions.

**Comment by Jzarecta** [comment]
Actually the example folder didn't gave me much insight. Perhaps I didnt read it right, but I was able to declare updates on the api, but that was it, the rest was a lonely def that supposely was the command to use, but it didnt work as expected. I had the following code:
```python
def p(value):
    #Buscamos el API
    bitapeso=urllib2.urlopen("http://bitapeso.com/json/").read()
    jobject = json.loads(mxn, 'utf-8')
    val=jobject['mxn']
    if val == None:
        peso = float(val)
    else:
        peso = float(val) * value
    return peso.strip()
```

Maybe I miss something, or a lot.

**Comment by franciscod** [comment]
We could get the token from an env-var

**Comment by franciscod** [comment]
are these tests https://travis-ci.org/leandrotoledo/python-telegram-bot/jobs/87105084 from #87 failing due to a testing token issue?

**Comment by franciscod** [comment]
there are a lot of hardcoded things, right? message/file ids, message contents

**Comment by leandrotoledo** [comment]
The way it's writen atm I'm the only one who can see the bot interation (as it sends messages to chat_id corresponding my telegram user). @jh0ker has suggested a public channel so anyone planning to submit a feature can see the results for their thats. In order to accomplish that we would need to change some tests and avoid hardcoding as @franciscod mentioned. I'll spend some time on it this week.

**Comment by leandrotoledo** [comment]
Seems like the amount of efforts to have the same result does justify this rework right now.
The token and the chat_id are now shared on `tests/base.py` so anyone can run tests. Until we have a better (and easier way) to emulate client requests or generic tests I'd say to keep the way we have.
