### ISSUE TITLE
Add tests for optional parameters that should accept empty string as input

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#1601]

**Comment by tsnoam** [comment]
@Bibo-Joshi can you please provide some examples ?

**Comment by Bibo-Joshi** [comment]
Haven't had a thorough look thorugh the library yet, but this was triggered by `switch_inline_query`, see #1594 . Another example would be `(Inline)KeyboardButton.text`
