### ISSUE TITLE
[BUG] PrefixHandler does not support prefixes that ended with space " "

### ISSUE THREAD

**Issue by ldebortoli** [python-telegram-bot/python-telegram-bot#1602]
``prefixes = ["!", "$", ".", ">", bot_username + " ", bot_username[:-3] + " "]``
``handler = PrefixHandler(prefixes, "command", function, pass_args=True)``
``dispatcher.add_handler(handler)``

This is what I am trying to do in my bot code. What I want is that a command can be executed if it is called "username command parameters". But adding the "username" of my bot followed by a space as a prefix does not work, just as with any other prefix that ends in a space: the function is not executed when the corresponding message arrives.

**Comment by Eldinnie** [comment]
@ldebortoli that is kindof expected since we split the <code>message.text</code> by whitespace characters. So prefix+command cannot contain a space.

I suggest you use a messagehandler with <code>Filters.regex(r&#x27;^{} (.*)&#x27;.format(bot_username)</code> for this purpose

**Comment by ldebortoli** [comment]
Ok, I'm going to do that, thanks for the help.
