### ISSUE TITLE
[QUESTION] update.message.reply_photo() timeout

### ISSUE THREAD

**Issue by 01101100** [python-telegram-bot/python-telegram-bot#1633]
### Issue I am facing
I have used this library for a month to create bots to send photos, 
it works normally until today
The bot can't send pictures anymore and says "Timed out"
When set timeout = 60, bot encountered "Flood exceeded error".

reply_text and reply_document functions are still working normaly.

### Related part of your code
```python
def action(update, path):
    try:
        update.message.reply_photo(open(path, "rb"))
    except Exception as e:
        update.message.reply_text(str(e) + "Contact @ld."
```

**Comment by Poolitzer** [comment]
Hey, a flood error is a pretty specific error. You did something too often in a specific timeframe, so telegram limited you. You need to wait for how long the error states, and then you can do it again. In order to prevent this from happening again, restrict your requests and do them slower :)

**Comment by Poolitzer** [comment]
The appropriate doc link would be https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this
