### ISSUE TITLE
Maybe bug with send_media_group and timeout?

### ISSUE THREAD

**Issue by walkman99** [python-telegram-bot/python-telegram-bot#1637]
Using

>    files = bot.send_media_group('-' + tg_channel, media, timeout=100)

I got

> TypeError: send_media_group() got an unexpected keyword argument 'timeout'

I look in source and "timeout" really absent but https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.send_media_group has it.

**Comment by Bibo-Joshi** [comment]
The `timeout` kwarg is present in the source code (see [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/a5ba64becb366b4805fdfbf94e63995c18c39f4d/telegram/bot.py#L954)). Which version of PTB are you running?

**Comment by walkman99** [comment]
I so sorry! I wrote in wrong project!
