### ISSUE TITLE
[QUESTION] pure-API telegram.Bot connection through proxy

### ISSUE THREAD

**Issue by FloeHetling** [python-telegram-bot/python-telegram-bot#1649]
I am doing a simple pager script. It gets text from sys.argv and posts it to distinguished **chat_id**s
The problem I am facing now: 
It is not enough to just
```python
import telegram
pager = telegram.Bot(token=TOKEN)
```
as I must to be behind the proxy, so, here is where it stops.

Our core bot (based on Echobot2) is doing just fine while passing kwargs to Updater(), but it seems like telegram.Bot accepts no kwargs at all

**Comment by Eldinnie** [comment]
@FloeHetling the easiest solution would be to do:
<pre>updater = Updater(TOKEN, kwargs)
bot = updater.bot</pre>
Let updater do the work for you and leave it at that.
Alternatively you could create a <code>Request</code> object (<code>telegram.utils.Request</code>) to your likeing and pass that to <code>Bot</code>

**Comment by FloeHetling** [comment]
```python
from telegram.ext import Updater
TOKEN='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
# Connecting through TOR@localhost
REQUEST_KWARGS={
    'proxy_url': 'socks5://127.0.0.1:9050',
    }
updater = Updater(TOKEN, request_kwargs=REQUEST_KWARGS)
pager = updater.bot
pager.send_message(chat_id=sys.argv[1], text=sys.argv[2])
```
Updated your hint for the new API.
It totally works that way, thanks a lot!

**Comment by Eldinnie** [comment]
@FloeHetling 👍
