### ISSUE TITLE
Naive datetime should be treated as local timezone. UTC datetimes should be timezone aware.

### ISSUE THREAD

**Issue by n5y** [python-telegram-bot/python-telegram-bot#1658]
Caused by #1506(#1505) #1485(#1362)

I believe local timezone is the expected default for naive datetime objects. Breaking those expectations will lead to unnecessary surprises for the users. It will also lead to awkward conversions if another library that does follow this convention is used. 

Python's `datetime.fromtimestamp` and `datetime.astimezone` assume local timezone for naive objects. There are three warnings in [datetime docs](https://docs.python.org/3/library/datetime.html) that start with "Because naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC."

Using utc time is surely more sane than using local time, but the better way to do that is timezone aware datetimes, not naive-utc datetimes. For example Message.date should be timezone aware.

**Comment by Bibo-Joshi** [comment]
As of #1621 (released in v12.7), `helpers.from_timestamp` returns an aware object. Therefore I see this issue as resolved and will close.
If I'm missing the point and/or you disagree, feel free to comment.

**Comment by n5y** [comment]
I disagree, that pull request only addressees the second sentence from the issue title. Using aware datetimes removes the need to use "naive-utc", but at the moment naive datetimes are still treated as utc by the library.

On a side note: `update.message.date` changing from naive to aware is a breaking change and is not really explained in release notes.

**Comment by Bibo-Joshi** [comment]
Sorry, I don't really understand what you mean by "but at the moment naive datetimes are still treated as utc by the library." Or are you talking about JobQueue?

I'll update the changelog.

**Comment by n5y** [comment]
I'm talking about datetime objects being provided by a user. Looks like it's only relevant to job queue stuff at the moment, but it also affects any future methods that will accept a dtatetime/time from a user, since they will probably use the same helpers.

**Comment by Bibo-Joshi** [comment]
Mh okay. E.g. `send_poll`s `close_date` and `kick_chat_member`s `until_date` would also fall into that category. Didn't have that in mind. Fair enough, I'll reopen.

Just FYI: We're planning on adding `tzinfo` to the `Defaults` logic, which would allow to interpret all naive date/time objects in the library as a customized timezone. I know that's not exactly what you proposed, but it would make it easy to have everything interpreted as local timezone.

**Comment by Bibo-Joshi** [comment]
We discussed this again internally and decided to stick with the way it is now, i.e. tread naive datetimes as UTC by default.
