### ISSUE TITLE
[BUG] Typo in def of enocde_conversations_to_json

### ISSUE THREAD

**Issue by rizlas** [python-telegram-bot/python-telegram-bot#1660]
Hi,
i was using helpers.py yesterday and i found a typo in enocde_conversation_to_json [function definition](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/utils/helpers.py#L303)

If it wasn't wanted I would suggest to change it:

From:
`def enocde_conversations_to_json(conversations)`

To:
`def encode_conversations_to_json(conversations)`

### Traceback to the issue
[Github results](https://github.com/python-telegram-bot/python-telegram-bot/search?q=enocde_conversations_to_json&unscoped_q=enocde_conversations_to_json)

**Comment by Bibo-Joshi** [comment]
Uh yes, that's a typo for sure. Thanks for bringing this to our attention!
Would you maybe like to make a PR for this?

**Comment by rizlas** [comment]
Yeah, i will have a look into it.

Thanks!
