### ISSUE TITLE
[QUESTION] Flushed persistence gets overwritten when the bot stops.

### ISSUE THREAD

**Issue by cupcakearmy** [python-telegram-bot/python-telegram-bot#1662]
I have a `PicklePersistence` setup as follows:

```python
persistence = PicklePersistence(DB_FILE)
updater: Updater = Updater(config['token'], use_context=True, persistence=persistence)
```

I then have an async cron job that updates the persistence object directly. i also call `persistence.flush()` whenever I make changes outside of a bot handler. 

However, when I stop the bot, it gets flushed again, but with an old state :/
My guess i that the telegram bot has a copy of the storage inside the instance?

Any suggestions on how to change this? Right now I had to turn off the persistence form the `Updater` object and handle my persistence manually.

I can provide further code/details if the issue is not clear 🙂

**Comment by Eldinnie** [comment]
Ehm
Theres's a lot opf information missing. For starters you don't initialize updater with persistence...

**Comment by cupcakearmy** [comment]
@Eldinnie thanks for the fast response! It was a typo :) See the updated init code.

**Comment by Eldinnie** [comment]
@cupcakearmy Well, there's still a lot of information missing. When I'm testing persistence. It's working as expected and intended. So if you found anomalous behavior, then please provide context and code to showcase the problem. We can;t help you if you don't provide information.

**Comment by cupcakearmy** [comment]
Sure, I though maybe you already had an idea :)

I'll prepare a little bot to reproduce the exact behaviour as soon as I get home :)

**Comment by cupcakearmy** [comment]
While building a small bot to recreate the issue I stumbled apon `run_async` and the job queue which I did not know existed before (this library is amazing ❤️). I was doing a lot of async stuff and I'm sure I messed something up in the process. 

Thanks for taking the time!
