### ISSUE TITLE
[BUG] ParseMode.MARKDOWN Not Working With Below Code Snippet

### ISSUE THREAD

**Issue by maruashok** [python-telegram-bot/python-telegram-bot#1663]
### Steps to reproduce
1.bot.send_message(
                chat_id=ME,
                parse_mode=telegram.ParseMode.MARKDOWN,
                text='User ID : %s\nUsername : %s\n%s' % (
                    str(bot_update.message.chat_id), bot_update.message.from_user.name,
                    'txt_msg'))

### Expected behaviour
Message should be sent

### Actual behaviour
Receives error

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**
python 3.8 , 12.2.0
``$ python -m telegram``

### Logs
[b'{"ok":false,"error_code":400,"description":"Bad Request: can\'t parse entities: Can\'t find end of the entity starting at byte offset 37"}']

bot.send_message(chat_id=123456, text='User ID : %s\nUsername : %s\n%s' % (
                str(self.bot_update.message.chat_id), str(self.bot_update.message.from_user.name), txt_msg))

when i add {parse_mode=telegram.ParseMode.MARKDOWN} to above code it failed to send message

**Comment by Poolitzer** [comment]
hey there,

Telegram has only very limited markdown, check it out here: https://core.telegram.org/bots/api#markdown-style

**Comment by maruashok** [comment]
Ol solved it, from_user.name conatains '@'
