### ISSUE TITLE
[BUG] MessageHandler stopped working

### ISSUE THREAD

**Issue by psytron** [python-telegram-bot/python-telegram-bot#1665]
### Steps to reproduce
1. Run Example from https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/echobot2.py
2. Send command --> Notice it echos
3. Send regular message --> No response occurs

### Expected behaviour
Should echo text as described.

### Actual behaviour
Nothing occurred, but for /command messages everything works

### Configuration
**Operating System:**
Mac0S Mojave with Python 3.7

**Version of Python, python-telegram-bot & dependencies:**
Python 3.7 

``$ python -m telegram``
python-telegram-bot 12.2.0
certifi 2019.09.11
future 0.17.1
Python 3.7.4 (v3.7.4:e09359112e,

### Logs
Insert logs here (if necessary)

**Comment by Poolitzer** [comment]
@psytron are you testing this in a group?

**Comment by psytron** [comment]
Yes I am

**Comment by Poolitzer** [comment]
Then this article will provide some inside why its not echoing: https://core.telegram.org/bots/faq#what-messages-will-my-bot-get

In short, make the bot admin or disable privacy. You need to re-add the bot in the second case though

**Comment by psytron** [comment]
Wow Thanks @Poolitzer !!
