### ISSUE TITLE
[QUESTION] InlineKeyboardMarkup For send_photo & send_message

### ISSUE THREAD

**Issue by maruashok** [python-telegram-bot/python-telegram-bot#1668]
### Issue I am facing
InlineKeyboardMarkup gives json error if i use it with send_photo & send_message while the same is working for update.message.reply_text

### Traceback to the issue
```
https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/inlinekeyboard.py , how to use same reply_markup in send_photo & send_message methods ?
```

### Related part of your code
```as of now i need to use this to achieve my goal,

from telebot import types
key = types.InlineKeyboardMarkup()
key.add(types.InlineKeyboardButton("Yes", callback_data="Yes"), types.InlineKeyboardButton("No", callback_data="No"))
```

please give me equivalent code snippet for python-telegram-bot API

**Comment by Bibo-Joshi** [comment]
Hi. Please post the JSON error you are getting along with a minimal example of your code that produces said error.
Also, see [here](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.send_photo) and [here](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.send_message) for documentation of the methods.

**Comment by Eldinnie** [comment]
Let's close this because they're not using this library.
