### ISSUE TITLE
switching off "No updates found" log messages

### ISSUE THREAD

**Issue by eignatenkov** [python-telegram-bot/python-telegram-bot#167]
It would be nice to be able to switch off "No updates found" messages from log files

**Comment by leandrotoledo** [comment]
As suggested on group, we may should move this to DEBUG instead INFO.

**Comment by naveenvhegde** [comment]
For time being, this can be suppressed like this.

tglogger = logging.getLogger("telegram.bot")
tglogger.setLevel(logging.WARN)
