### ISSUE TITLE
[FEATURE] Add telegram.ext.filters.Filters.poll for native poll messages

### ISSUE THREAD

**Issue by blueset** [python-telegram-bot/python-telegram-bot#1672]
#### Is your feature request related to a problem? Please describe.
Since version 4.2, Bot API added poll message support, and PTB has also followed up with that in the API. However, as of PTB 12.2.0, ther is no support of poll messages in built in filters like other message types.

#### Describe the solution you'd like
Add a filter `telegram.ext.filters.Filters.poll`, namely:

```python
    class _Poll(BaseFilter):
        name = 'Filters.poll'

        def filter(self, message):
            return bool(message.poll)

    poll = _Poll()
    """Messages that contain :class:`telegram.Poll`."""
```

#### Describe alternatives you've considered
I’m having this filter in my own code so far.

#### Additional context
None

**Comment by Eldinnie** [comment]
@blueset This would make a great addition. Could you make a PR according to our contributers guide?

**Comment by blueset** [comment]
Just sent a PR #1673 on feature.
