### ISSUE TITLE
Telegram channel bot

### ISSUE THREAD

**Issue by zoeProger** [python-telegram-bot/python-telegram-bot#1674]
How to make the bot respond to messages in the telegram channel. Bot added by channel administrator.

```
def test(bot, update):
    bot.send_message(chat_id='@namechannal', text='this is a test')

def main():
    updater = Updater(
        token='1234567890:BBGWv6tk8dflo56-H67BDls-gWlFMwerfld',
    )
    dp = updater.dispatcher

    dp.add_handler(CommandHandler("test", test))

    updater.start_polling()
    updater.idle()


if __name__ == '__main__':
    main()

```
I can not get the bot to work with the telegram channel

**Comment by Poolitzer** [comment]
@zoeProger That is because commands in channels dont get the command entity, thus not being recognized by the commandhandler.

Use a messagehandler with regex filter for that. And also think about switching to context handlers if you are developing a new bot

**Comment by zoeProger** [comment]
@Poolitzer Thanks It works!
I get a warning in the console. 

> TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details

I probably use outdated solutions in my code ...

**Comment by Poolitzer** [comment]
@zoeProger This is the context handlers switch I talked about :)

**Comment by zoeProger** [comment]
@Poolitzer Ok!) 
```use_context=True```
And no more warning ))

**Comment by Eldinnie** [comment]
@zoeProger Revoke your token

**Comment by zoeProger** [comment]
@Poolitzer I myself came up with this token, it does not exist
I wonder why in my case it’s not working..
```def message_handler(bot, update):
    bot.send_message(chat_id='@namechannal', text=update.message.text)
```
namely, this part: ```text=update.message.text```

**Comment by Poolitzer** [comment]
@zoeProger Did you change your callback parameters from bot, update to update, context?

**Comment by zoeProger** [comment]
@Poolitzer I'm sorry, I'm just a beginner, and I don't quite understand your question. 
Thank you for your responses

**Comment by zoeProger** [comment]
Probably a problem in this part of the code:
```
dp.add_handler(MessageHandler(
        filters=Filters.all, callback=message_handler))
```

**Comment by Poolitzer** [comment]
@zoeProger That should help: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-12.0

**Comment by zoeProger** [comment]
I looked through all the changes in version 12. 
Here is my code (echo bot):
```
def message_handler(update: Update, context: CallbackContext):
    text = update.message.text
    context.bot.send_message(chat_id='@namechannal', text=text)

def main():
    updater = Updater(
        token='1234567890:BBGWv6tk8dflo56-H67BDls-gWlFMwerfld',
        use_context=True
    )

    dp = updater.dispatcher

    print('Start!')

    dp.add_handler(MessageHandler(
        filters=Filters.all, callback=message_handler))

    updater.start_polling()
    updater.idle()

    print('Stop')

if __name__ == '__main__':
    main()
```
But it does not work ((((

**Comment by Poolitzer** [comment]
@zoeProger Did you enable logging and get an error?

Im case you didnt, do it.

<code>import logging
logging.basicConfig()</code>

**Comment by zoeProger** [comment]
@Poolitzer 

> text = update.message.text
> AttributeError: 'NoneType' object has no attribute 'text'

Strange why there is no attribute text

**Comment by Poolitzer** [comment]
@zoeProger use <code>update.effective_message.text</code>. message can be none on a couple of updates

**Comment by zoeProger** [comment]
@Poolitzer Yes! It's work! Thanks!
A strange library for telegram bot, in one case everything works, in another case, you don’t know what is happening .... does it have to be so ....

**Comment by zoeProger** [comment]
@Poolitzer Tell me please how the message differs from the effective_message.

**Comment by zoeProger** [comment]
**effective_message** 

> The message included in this update, no matter what kind of update this is

**Comment by Poolitzer** [comment]
@zoeProger the different is that .message is the included message from the update, directly taken from telegram.

Effective_message is from the library, providing that field as soon as there is text. Its way more convenient.
