### ISSUE TITLE
Callbacks is not working

### ISSUE THREAD

**Issue by liceistdominator** [python-telegram-bot/python-telegram-bot#1675]
Hi. My situation is next: In private chat I want my bot to clear history with user in private chat. Instead of it I tried to use method `leave_chat()`. It caused an error. I restarted my bot (just turn it off by ^C and turn on in terminal as `python my_bot.py`) and after it callbacks stopped to appear in updates. My bot became insensitive to callbacks from inline keyboards. From any source code. Debug logger shows empty update while I am pressing inline buttons. My bot fail to respond to callbacks from different codes (independently is it my_bot.py or purchase_bot.py or question.py). But another bot (with another token from Bot_Father) work fine with callbacks, despite code is absolutely similar. Only difference is in <bot_token> at `updater=Updater(token=<bot_token>, use_context=True)`.
Do you have any ideas what caused such behavior and how to fix it in future?
Thank you in advance.

**Comment by Eldinnie** [comment]
Sorry but this is just too few information. Please share alle relevant information.

**Comment by liceistdominator** [comment]
> Sorry but this is just too few information. Please share alle relevant information.

Thank you for reply. I just created another bot and launched testing code with `leave_chat()` and Callbacks. And I find out it is not `leave_chat()` cause strange behaviour with callbacks. It seems like I am missing something. The problem is I have no idea what it can be. Thus I cannot share relevant information.
But thank you again.
