### ISSUE TITLE
[QUESTION] job execution datetime and forcing/postponing jobs

### ISSUE THREAD

**Issue by Andrej730** [python-telegram-bot/python-telegram-bot#1676]
1. I need to obtain the exact time when the job will be executed. To do so i'm currently accessing job_queue._queue.queue. Is there some other function for this purpose that i'm missing?

2. I need to be able to force job execution or postpone it. Is there any more simple way to do it?
To force job execution I do (To postpone execution I do similar thing but without step 1 of course):
- create a new job with job_queue.run_once that will run the callback right now
- disable the current job and set it's interval to (base_interval - (t - now)). (t is time when the job supposed to be executed according to it's original interval)
- create a job that will run in (t - now) seconds and will enable the forced job and set it's interval to base_interval (so the job would keep working with the original interval as it was before forcing it).

And the problem with my method is that some time after the job was postponed or forced I cannot access the time it will be executed with job_queue._queue.queue and I need to calculate it and store it somewhere else.

I think postponing, forcing the jobs and accessing the time job will be executed should be more straightforward and it should be handled by the library. Am I wrong?

**Comment by Eldinnie** [comment]
1. jobqueue.jobs

**Comment by Andrej730** [comment]
> 1. jobqueue.jobs

It returns list of current jobs but how do I get the time when they will be executed?

**Comment by Bibo-Joshi** [comment]
- To force execution, you can just run

    ```
    job.run(dispatcher)
    job.schedule_removal() #If you want to delete the job
    ```
    (see the [docs](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.job.html#telegram.ext.Job.run))

- If you want to postpone a `run_once` job to a given time `T`, just create a new `run_once` job with interval `T - now` and delete the original one.
- If you want to postpone *a single* execution of a `run_repeating` job `j` to a given time `T`, I suggest deactivating `j` and creating a `run_once` job with interval `T-now` that also reactivates `j`.
- If you want to postpone *every* execution of a `run_repeating` job, I'd also suggest to delete it after creating a new job with the appropriate interval.

> And the problem with my method is that some time after the job was postponed or forced I cannot access the time it will be executed with job_queue._queue.queue and I need to calculate it and store it somewhere else.

I don't really get, what you mean by that

> I think postponing, forcing the jobs and accessing the time job will be executed should be more straightforward and it should be handled by the library. Am I wrong?

Well, `JobQueue` is somewhat fragile and complex. Personally I wouldn't fancy adding a native `postpone` method. However, I think adding an attribute `next_t` to `Job`, that's set (and updated) by `JobQueue._put`

**Comment by Andrej730** [comment]
>To force execution, you can just run...

Thanks, that actually will work for me, I was overthinking this part..

> I don't really get, what you mean by that

My bot has a command that shows when the job will be executed next time. That's the method I'm using to get the time:

```python
for t, job in self.job_queue._queue.queue:
	if not job.removed and job.name == job_name:
		return datetime.fromtimestamp(t)
```

And then when I postpone the job (I disable the current job and create a `run_once`  job that will reactivate the original job at the right time) I cannot get the next execution time with my method anymore and I need to keep track of whether job was postponed or not. 

For example, `t` is the next execution time, `p` - postponed execution time. Before I postpone the job `t` is the next execution time and everything is fine. 

Then to postpone the job I set it's interval to `p-t` and disable it until `t`. After I postpone it the actual next execution time is not equals `t` and equals `p`. After the time `t` will come, `t` will be the same as `p` and I can use my method again but until that I need to keep track of the fact whether the job was postponed or not and return `p` instead of `t` with my method.

And one more thing - if job was postponed twice then I need to keep track of the job that supposed to reactivate the original job, find it, disable it, change interval for the original job according to it's previous postpone time `p` and schedule a new reactivation job. 

It seems like for postponing task I need to write some job manager on top of JobQueue.

>However, I think adding an attribute next_t to Job, that's set (and updated) by JobQueue._put

That would be really useful!

**Comment by Bibo-Joshi** [comment]
> > I don't really get, what you mean by that
> 
> My bot has a command that shows when the job will be executed next time. That's the method I'm using to get the time:
> ...
> It seems like for postponing task I need to write some job manager on top of JobQueue.

Whoof … Sounds like a lot of bookkeeping. But tbh I thinks that's also beyond the scope of PTB. More so, since it's rather a specific use case for jobs than a general framework (from my point of view)

> > However, I think adding an attribute next_t to Job, that's set (and updated) by JobQueue._put
> 
> That would be really useful!

You're welcome to PR, if you like :)

**Comment by Bibo-Joshi** [comment]
Since the actual question seems to be answered, I'll close this.
