### ISSUE TITLE
ParseMode HTML

### ISSUE THREAD

**Issue by Pantic14** [python-telegram-bot/python-telegram-bot#168]
I want to send a message with html code. But "ParseMode.HTML" don't exists.

>>> bot.sendMessage(chat_id=chat_id, text="<b>bold</b> <i>italic</i> <a href="http://google.com">link</a>.", parse_mode=telegram.ParseMode.HTML)

**Comment by jh0ker** [comment]
Hi :)

You are right, this feature is not yet available in the current published version. You can either use `parse_mode='HTML'` or install the current version from GitHub with `pip install -U https://github.com/python-telegram-bot/python-telegram-bot/archive/master.zip`

**Comment by Pantic14** [comment]
I can't install the current version from GitHub.
I try and receive a Exception (traceback)

**Comment by jh0ker** [comment]
Please try updating pip first with `pip install -U pip`

**Comment by jlmadurga** [comment]
```pip install -e git+https://github.com/python-telegram-bot/python-telegram-bot.git#egg=python-telegram-bot```
