### ISSUE TITLE
Problem with log.exception

### ISSUE THREAD

**Issue by KianaRajabi** [python-telegram-bot/python-telegram-bot#1683]
Hello everyone .
I have a problem in ```telegram/utils/promise.py``` file in line 60.
This line of code hits log.exception but It shouldn't . When this happens it gets sent to sentry and apps related to Error Tracking.
How can I disable this ?!
Thanks !

```
   def run(self):
        """Calls the :attr:`pooled_function` callable."""

        try:
            self._result = self.pooled_function(*self.args, **self.kwargs)

        except Exception as exc:
            logger.exception('An uncaught error was raised while running the promise')
            self._exception = exc

        finally:
            self.done.set()
```

**Comment by Bibo-Joshi** [comment]
The file history tells me that @tsnoam added the line in 0fb00c4c8b6f57fd79d9dd0afd717c5c5f5b983c .
But tbh I don't really see why you would want to disable logging here.

**Comment by tsnoam** [comment]
@Bibo-Joshi Yeah, I agree.
This log line is to identify that the user of the library has an exception raised at their code.

The alternative of silently ignoring an exception is worse.

If a user wants to ignore exceptions they can do that in their own code.
