### ISSUE TITLE
4.5 bot api update arrived

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#1689]
Aint much, but its honest work
- [x]  Two new messageEntities, strikethrough and underline
- [x] nested messageEntities, we have a PR for that somewhere
- [x] New parsemode, MardownV2
- [x] New file_unique_id for Animation, Audio, Document, PassportFile, PhotoSize, Sticker, Video, VideoNote, Voice, File
- [x] small_file_unique_id and big_file_unique_id to the object ChatPhoto.
- [x] custom_title for ChatMember
- [x] new method setChatAdministratorCustomTitle
- [x] new slow_mode_delay for Chat object

**Comment by Poolitzer** [comment]
@dmytrohoi get yourself in here :)

**Comment by Bibo-Joshi** [comment]
Already got started on the MessageEntities & MarkdownV2. Let's make #1508 the PR for API 4.5. I'll push my changes to the [`nested-entities` branch](https://github.com/python-telegram-bot/python-telegram-bot/tree/nested-entities) some time tomorrow.

@dmytrohoi could you rebase #1690 to `nested-entities`, so we can merge all the API changes to master in one go?
Please ping me here, if you want to get started on the unique file id stuff, so we don't do the work twice ;)

**Comment by dmytrohoi** [comment]
@Bibo-Joshi squashed all commits to one, added tests and checked using flake8. PR has been directed to the nested-entities branch.

I think, the nested-entities branch needs to pull latest commits from master branch, before you can merge  #1690 PR to it. (My patch-1 was forked from the master and have 44 more commits than nested-entities.)

All passed, ready to next instructions. ;)

[FYI: I'm not currently working on the "unique file identifier" part.]

**Comment by Poolitzer** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#message-formatting-bold-italic-code-
dont forget to update that page then

**Comment by Bibo-Joshi** [comment]
@dmytrohoi It took a bit longer but the MessageEntity and MarkdownV2 stuff is now pushed no `nested-entities`. When you're done with the file ID stuff, please pr to that branch :)
