### ISSUE TITLE
[ERROR] No module named 'telegram.ext'.

### ISSUE THREAD

**Issue by VitorCav** [python-telegram-bot/python-telegram-bot#1691]
Hi everyone, I was trying to test echobot2.py example and couldn't make it work. This same error every time:

Traceback (most recent call last):
  File "C:/Users/Vitor/PycharmProjects/untitled1/new.py", line 18, in <module>
    from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
ModuleNotFoundError: No module named 'telegram.ext'

Process finished with exit code 1

I tried all the things you guys suggested but didn't get it working. Some help?

**Comment by Bibo-Joshi** [comment]
Hi. Have you successfully installed python-telegram-bot via pip(3)? If yes, what's the output of ``$ python -m telegram``, i.e. which version are you running?

**Comment by VitorCav** [comment]
> Hi. Have you successfully installed python-telegram-bot via pip(3)? If yes, what's the output of `$ python -m telegram`, i.e. which version are you running?

There it is

C:\Users\Vitor>python -m pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-19.3.1

C:\Users\Vitor>python -m pip install --upgrade pip
Requirement already up-to-date: pip in c:\users\vitor\anaconda3\lib\site-packages (19.3.1)

C:\Users\Vitor>python -m telegram
C:\Users\Vitor\Anaconda3\python.exe: No module named telegram

C:\Users\Vitor>

**Comment by VitorCav** [comment]
![image](https://user-images.githubusercontent.com/59452228/71701015-c10e1200-2da5-11ea-92d4-491da226a8e4.png)

**Comment by Bibo-Joshi** [comment]
> ```
> C:\Users\Vitor>python -m pip install --upgrade pip
> ...
> Successfully installed pip-19.3.1
>```

This just installs pip, not python-telegram-bot

> ```
> C:\Users\Vitor>python -m telegram
> C:\Users\Vitor\Anaconda3\python.exe: No module named telegram
> ```

Hence this output.

But on your second image the command line stets that ptb is indeed installed. So did you run `pip(3) install python-telegram-bot`?

> `C:\Users\Vitor\Anaconda3\python.exe: No module named telegram`

Also I see that you're using Anaconda. I'm not actually familiar with that, but if I understand [this](https://github.com/sagemathinc/cocalc/issues/2403) correctly, it needs special tretment. Try

```
conda install python-telegram-bot
```
and see [here](https://docs.anaconda.com/anaconda/user-guide/tasks/install-packages/) for details.

**Comment by Eldinnie** [comment]
@Bibo-Joshi I think the problem is pycharm created an env for the project, and the library is installed globaly, not in the env for the project.

**Comment by VitorCav** [comment]
Thanks you all, i don't know what i did, but it is working now. I think it was something @Bibo-Joshi sad. I uninstall all and re install all.

**Comment by mohsnHERE** [comment]
hey! i have this problem too,

Traceback (most recent call last):
  File "C:/Users/Bartar/PycharmProjects/Training/venv/p1.py", line 1, in <module>
    from telegram.txt import Updater
ModuleNotFoundError: No module named 'telegram.txt'


(venv) C:\Users\Bartar\PycharmProjects\Training>python -m telegram
python-telegram-bot 12.8
certifi 2020.06.20
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)]


what can i do?

**Comment by Poolitzer** [comment]
How are you starting this script?

**Comment by mohsnHERE** [comment]
I wrote telegram.txt and now write with .ext
And its worke
Is it deprected? (telegram.ext)

**Comment by Poolitzer** [comment]
no its not you just made a typo I didnt see

**Comment by ericestoll** [comment]
I've been having problems with this since yesterday. 
I Finally fixed it by making sure to run the install using **pip3** instead of pip (as mentioned above by @Bibo-Joshi .

**pip3 install python-telegram-bot** 

All running smoothly now on Raspberry Pi 3 + Latest Raspbian (as of 2020/06/27)

Thanks to all

**Comment by AjocaJunior** [comment]
Thank you all.. I had the same problem and pip3 install python-telegram-bot solved my problem
