### ISSUE TITLE
[BUG] reply_ documentation always says photo in its description

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#1692]
example: https://github.com/python-telegram-bot/python-telegram-bot/blob/3d42df3366d7cff030c3ce06d6a95259b3bdf62e/telegram/message.py#L594-L600

There are two steps I have to do before PR a patch
- [x] check how many files are affected. Currently known is _message_, there will likely be more
- [x] change the part to the actual reply there is

**Comment by Poolitzer** [comment]
@Poolitzer great.

Now I am at a stage where I cant even program a bot in peace without seeing issues

**Comment by Bibo-Joshi** [comment]
Couldn't find any other files with the wrong docs. Fixed in #1642
