### ISSUE TITLE
[FEATURE] run_monthly method for job_queue

### ISSUE THREAD

**Issue by daviddl9** [python-telegram-bot/python-telegram-bot#1697]
#### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
I want to schedule a monthly recurring message at a particular time. A simple use case would be when I want the bot to remind me to pay my credit card bills on a particular date for every month. 

#### Describe the solution you'd like
It would be nice to have a function along the lines of:
`job_queue.run_monthly(callback, day_of_month, time, context=None, name=None)` that a developer can just call to run monthly jobs.

#### Describe alternatives you've considered
The alternative would be to write the code for it yourself, which makes your code more lengthy. It would be helpful if it came along with this wrapper

**Comment by daviddl9** [comment]
I'd like to work on it!

**Comment by Bibo-Joshi** [comment]
Sounds like a reasonable thing. Please, PR away :) You can orientate yourself on `run_daily` and please make sure to also add tests for the new method.

As a workaround you can schedule a job via `run_once` that in turn schedules the next job.

**Comment by daviddl9** [comment]
Sure! :)

**Comment by daviddl9** [comment]
Wanted to check with you guys - I encountered the following error when I ran the command `git commit -a -m 'message'`:

```
[INFO] Installing environment for git://github.com/pre-commit/mirrors-pylint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/davidlivingston/.cache/pre-commit/repoisChtT/py_env-python2.7/bin/python', u'/Users/davidlivingston/.cache/pre-commit/repoisChtT/py_env-python2.7/bin/pip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /Users/davidlivingston/.cache/pre-commit/repoisChtT
    
stderr:
    DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
    ERROR: Could not find a version that satisfies the requirement pylint==2.3.0 (from pre-commit-dummy-package==0.0.0) (from versions: 0.15.2, 0.16.0, 0.18.0, 0.18.1, 0.19.0, 0.20.0, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.25.1, 0.25.2, 0.26.0, 0.27.0, 0.28.0, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5)
    ERROR: No matching distribution found for pylint==2.3.0 (from pre-commit-dummy-package==0.0.0)
```
I ran the command `pip install -r requirements.txt` and it states that all the requirements are already satisfied. Please help!

**Comment by tsnoam** [comment]
@daviddl9 please note that next releases of this library won't support py2.7

**Comment by daviddl9** [comment]
Okay! I also have python 3 installed, is there  way I can run the following with python 3 instead? I'm on macOS catalina

**Comment by tsnoam** [comment]
@daviddl9 probably your default python is python2. (/usr/bin/python -&gt; python2)
make sure your default python is python3 (use venv if necessary) and reinstall pre-commit hook (follow the CONTRIBUTING guide)

**Comment by llybin** [comment]
If I will would like run_every_two three month ... Do you will add these function also? I believe don't that should be in telegram library, use task schedulers...
