### ISSUE TITLE
[BUG] duplicate assignment of job_queue in dispatcher class

### ISSUE THREAD

**Issue by mayurnewase** [python-telegram-bot/python-telegram-bot#1699]
Hi I was going through dispatcher.py, I found job_queue class object initialized twice at line 115 and 141,which seems not helping anywhere.
Should I remove it and raise PR?

Thanks

**Comment by Bibo-Joshi** [comment]
@mayurnewase Sure, go ahead and remove the second one. Thanks for the catch :)
