### ISSUE TITLE
Inline Query

### ISSUE THREAD

**Issue by jtmigowski** [python-telegram-bot/python-telegram-bot#170]
Hello everyone!
Is there any document on how to access methods to receive, process and respond to inline query?

**Comment by jh0ker** [comment]
Currently, there is only an example that you can find here: https://github.com/python-telegram-bot/python-telegram-bot/blob/inlinebots/examples/inlinebot.py

All new classes on the `inlinebots` branch are documented as well. Currently, no further documentation is available.

**Comment by jh0ker** [comment]
Please also check out PR #174 
If you have any further questions, please feel free to re-open!
