### ISSUE TITLE
[BUG] CI: check master after merge

### ISSUE THREAD

**Issue by tsnoam** [python-telegram-bot/python-telegram-bot#1700]
An unexpected regression of #1615 was that it only tests master at night.
We need master to:
1. Be tested after each commit to master (or merged PR for that matter).
2. Be tested every night.

**Comment by Poolitzer** [comment]
@tsnoam We need to fix the night tests first (which were failing, at least the last time I checked). But doing a test at every commit in master is a very easy change, will do that in a bit

**Comment by Bibo-Joshi** [comment]
Also, test-official should be allowed to fail. iirc, we had this set up before switching to github actions

**Comment by Poolitzer** [comment]
Okay, that should be possible, will do this today
