### ISSUE TITLE
Problems with run_repeating

### ISSUE THREAD

**Issue by Suhoy571** [python-telegram-bot/python-telegram-bot#1701]
Hi! 
After update to version 12.3, this code start to work wrong. The first command that sends is get_links_state, than, after one second, sends get_alarms_state. After rollback to version 12.2.0 all started to work normally. Code remains unchanged. 
Sorry for mistakes, English isn`t my mother tongue)
Code: 
```
    updater = Updater("TOKEN", use_context=True)
    queue_updater = updater.job_queue

    queue_updater.run_repeating(get_alarms_state, interval=60, first=0)
    queue_updater.run_repeating(get_links_state, interval=70, first=20)

```

**Comment by Poolitzer** [comment]
I am pretty sure you haven't updated to 13.0, given that this version isn't existing. And what exactly went wrong after the update?

**Comment by Suhoy571** [comment]
> I am pretty sure you haven't updated to 13.0, given that this version isn't existing. And what exactly went wrong after the update?

The first comand didn't started at 0, it started after 60 seconds

**Comment by Bibo-Joshi** [comment]
Hi @Suhoy571. I ran the example and can't reproduce the described behaviour. Can you set logging level to debug and post the full log (make sure to remove personal information such as the bot token)?

**Comment by Bibo-Joshi** [comment]
Mh, stupid me didn't run the example on v12.3 :man_facepalming: Can reproduce now, will have a look
