### ISSUE TITLE
[QUESTION] ImportError: cannot import name 'Update' from 'telegram.ext'

### ISSUE THREAD

**Issue by staticdev** [python-telegram-bot/python-telegram-bot#1704]
### Issue I am facing
I am migrating from version11 to 12 following https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-12.0 and created the new style handler as described: 
`def start(update: Update, context: CallbackContext):
`
But I get the error:
`ImportError: cannot import name 'Update' from 'telegram.ext'
`
It is nowhere in the migration guide where to import it. It is also not in the first bot tutorial:
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-Your-first-Bot (also this tutorial seems updated, it does not use the "new style").

**Comment by Poolitzer** [comment]
You would need to import Update from telegram. `from telegram import Update`.

Don't mix that up with Updater, which you import from telegrem.ext. one little letter :)

**Comment by staticdev** [comment]
@Poolitzer Thanks for the enlightment. It would be very nice to have that updated in the documentations mentioned.

**Comment by Poolitzer** [comment]
@staticdev Yeah, fair enough. It is a wiki, everyone can edit it. If you want to, give it a shot, otherwise I will do if later today or so
