### ISSUE TITLE
[BUG] InputMediaVideo dosen't upload thumb image

### ISSUE THREAD

**Issue by ehsanonline** [python-telegram-bot/python-telegram-bot#1709]
### Steps to reproduce
send a video with `send_media_group` including one `input_media_video` with a local video and local thumb image passed as `open('path','rb')`.
thumb image width is less than 320px and size is about 40kb.

### Expected behaviour
video sent with image as thumb.

### Actual behaviour
video sent with no thumb (white background).

note 1: the video sent properly with `send_video` function and the same thumb.
note 2: video size should be more than 10-11mb so telegram use the passed thumb image, instead of it's own generated thumb.
note 3: you can use `edit_message_media` instead of `send_media_group`. this problem is related to `input_media_video`, so any function which has this, is effected.

### Configuration
**Operating System:**
Ubuntu 18.04

**Version of Python, python-telegram-bot & dependencies:**
```
python-telegram-bot 12.3.0
certifi 2019.11.28
future 0.18.2
Python 3.6.8 (default, Jan 14 2019, 11:02:34)  [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

### Logs
no logs.

**Comment by Poolitzer** [comment]
Hey, btw: We discussed your case internally. Right now, we think its rather a telegram/telegram client issue then one with the library. We need to test this though, which is why no one has replied here yet.

**Comment by Poolitzer** [comment]
Hey, its me again. After taking way too long to recreate this using only requests, I can now safely say that this is an issue with our library, not with telegrams API. Thanks for bringing this bug to our attention, we uhm, shall start fixing it.
