### ISSUE TITLE
[FEATURE] RestApiPersistence implementation

### ISSUE THREAD

**Issue by alisher-matkurbanov** [python-telegram-bot/python-telegram-bot#1717]
I want to implement `RestApiPersistence` of `user_data`, `chat_data` and `conversations` to allow users divide client and server side of the application. I think that would be good to make client side fully stateless. As a part of this feature I want implement simple django (drf) app that will be handling requests from client and will be storing user \ chat data and conversations in database.

It would be nice if you share your thoughts on it and let me know any pitfalls that I don't see.
Also I have a question:
- Do users may store arbitrary Python objects in `user_data`, `chat_data` dict? May I restrict users to store only json-serializable objects using my persistence?

Thank you for attention!

**Comment by Poolitzer** [comment]
Hey, that sounds fun, go for it. The data is a simple dictionary, users can save anything in there. So json can fail if they for example put an object as value.

On the other side, PicklePersistence also fails with objects, so I guess you can just let user figure out their error.

Btw, for json itself, we have [DictPersistence](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.dictpersistence.html).

**Comment by alisher-matkurbanov** [comment]
Thanks for feedback, @Poolitzer ! 
Should I close this issue?

**Comment by Poolitzer** [comment]
Well, if I understood correctly, you want to implement within this library, no?

**Comment by alisher-matkurbanov** [comment]
Yes, I want to implement `BasePersistence` interface as a `RestApiPersistence`. Users will require to  create their own backend if they want to use it. `RestApiPersistence` will send some data to that backend. I'm gonna implement such backend on Django for my project.

**Comment by Poolitzer** [comment]
@alisher-matkurbanov Yes, that sounds great. Are you gonna make the REST api accessible as URL? That would be its definition if I understood wikipedia correctly.

**Comment by alisher-matkurbanov** [comment]
I think there will be user configured endpoints of this API such as 
GET `/user_data` to get user_data dict from database, 
PATCH `/user_data` to update user_data dict.
Also I need to provide similar methods to get \ set chat_data and conversations data.
This methods may be implemented by users with the tool what they prefer (there may be Flask, Django or even other programming language \ framework).

I'm gonna implement these HTTP methods with Django Rest Framework. I will open-source this app, so everyone may use it or improve it.

**Comment by Poolitzer** [comment]
Ah okay. We have the tornado library for that.

**Comment by alisher-matkurbanov** [comment]
I don't think this app should be the part of PTB, I just need to make the http requests from RestApiPersistence to some endpoints. If user will not provide backend, then persistence will not work (it may just raise ConnectionError). Or it may work as a DictPersistence, but I think that won't be nice idea (because user expect that data will be stored somewhere). If user want to use that persistence, he may use any library he want to implement backend - http methods handlers that will communicate with database. handlers will save the data they recieve from ptb and return if ptb will require user_data, chat_data or conversations. I hope I understand the client \ server scheme correctly - python-telegram-bot will call server methods for some data (or will be provide data to server).

**Comment by Poolitzer** [comment]
Now I get you. What I was confused by was client/server. So your persistence would act as a client. Fair enough. I would expect it to act as a server with that name for some reason, but your idea would definitely work, I dont see a downside to that. Maybe return something from the server so it can give your persistence an error message and you can raise an error.

But overall, good idea. I like it. You can develope it on your own ofc, but if you want to, you can make it part of the library as well :) your choice.

**Comment by alisher-matkurbanov** [comment]
Okay 🙂 Thanks for feedback, @Poolitzer !

**Comment by Poolitzer** [comment]
@alisher-matkurbanov You are welcome. I would close this issue though because its not directly related to our library. If you need help, feel free to comment here further, or come into our (offtopic) telegram group :)
