### ISSUE TITLE
Question on "old" versus "new"

### ISSUE THREAD

**Issue by zefoo** [python-telegram-bot/python-telegram-bot#172]
I'm noticing a change in the code from a bot class to using the Updater class. It seems that the bot method (eg. using webhook + bot class) are "old", while the Updater class with polling is newer. Why was this change made? Why would polling be better? I'm more familiar with the older method, and I thought that was best, and I'm curious what benefits there are to this "new way." I also want to make sure the "old" way won't be phased out. I may have missed something, but I can't seem to find anything in the docs or on telegram's API mentioning this. Thank you.

**Comment by jh0ker** [comment]
Hey :)

Don't worry, the 'old' method will not be removed (ever). Actually, the 'new' method builds on top of the `Bot` class. 

The `Updater` is responsible for calling `Bot.getUpdates()` periodically. That is what is happening when you call `Updater.start_polling()`. Alternatively, if you want to use a webhook, you can use `Updater.start_webhook()`, which starts up a `SimpleHTTPServer` and listens for updates on an ip/port you specify. It replaces Flask and other http frameworks.

The `Dispatcher` is used to create rules on which new updates will be checked and delivered to handler-functions that you specify. For example, it scans an update for commands or regex matches.

Check out this minimal echo-bot example (and our other examples) if you're not yet convinced:

    #!/usr/bin/env python

    from telegram import Updater

    def echo(bot, update):
        bot.sendMessage(update.message.chat_id, text=update.message.text)

    # Create the Updater and pass it your bot's token.
    updater = Updater("TOKEN")

    # Call the echo function on any message that contains text (ignore images, videos, stickers, etc)
    updater.dispatcher.addTelegramRegexHandler('.+', echo)

    # Start the Bot
    updater.start_polling()

    # Run the bot until the user presses Ctrl-C or the process receives SIGINT,
    # SIGTERM or SIGABRT
    updater.idle()

If you want to learn more, feel free to post a follow-up or join our telegram group!

**Comment by jh0ker** [comment]
Hey, I will close this issue now. If your question has not been answered, feel free to reopen the issue
