### ISSUE TITLE
Python supported versions need to be updated in docs

### ISSUE THREAD

**Issue by ffiori** [python-telegram-bot/python-telegram-bot#1720]
Not really a bug, but for example it still says Python 3.4 is supported in readme and setup explanations.

Copy-pasting from https://pypi.org/project/python-telegram-bot/ :

> This library provides a pure Python interface for the Telegram Bot API. It’s compatible with Python versions 2.7, 3.3+ and PyPy.

**Comment by Bibo-Joshi** [comment]
Jup. Please see #1538 and the corresponding PR ;)

**Comment by Poolitzer** [comment]
@Bibo-Joshi That issue is about python 3.5 and not 2.7. would only need to be dropped in setup, docs and readme.

**Comment by Bibo-Joshi** [comment]
Mh … Well, you like to update, it doesn't hurt. Just figured that the removal of 2.7 is the important one, which is covered by #1538

**Comment by Poolitzer** [comment]
We officially dropped support when python dropped support. We just need to reflect this. Currently, installation fails with 3.5.
