### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mboocannon** [python-telegram-bot/python-telegram-bot#1728]
### Steps to reproduce
1. I tried to return to my prior username and data stored for later use and was redirected to this website: https://xyz.is/  

2. The image had this text description: 403nginxxyz

3. I google searched the text and now I am trying to rebuild from scratch.

### Expected behaviour
Prior username to be authorized

### Actual behaviour
403 Alert for port 443

### Configuration
**Operating System:**
supposedly on my iPhone 7, but I believe my phone has been hacked by an android device.

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

**Comment by Bibo-Joshi** [comment]
@mboocannon Uhm, if I understand correctly, you are having a issue with chancing the username linked to your user account?
Please note that this repository is a Python library for the Telegram Bot API and has nothing to do with user accounts, so you&#x27;ll probably want to contact telegram support (on your phone go to settings -&gt; help)
If I your issue really is with this library and I just don&#x27;t understand it, please try to describe it more clearly.
