### ISSUE TITLE
[FEATURE] Send message without notification

### ISSUE THREAD

**Issue by borissimkin** [python-telegram-bot/python-telegram-bot#1729]
#### Is your feature request related to a problem? Please describe.
I would like to be able to send messages without notification. There is such an opportunity in Telegram, but I did not find a solution here.

#### Describe the solution you'd like
I think it would be nice to do this as a flag in send_message,
e.g. 
bot.send_message (chat_id = telegram_user_id,
text = text,
**silent = True**)

**Comment by Bibo-Joshi** [comment]
@borissimkin The keyword argument you are looking for is <code>disable_notification</code>. Please have a look at your <a href="https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.send_message">documentation</a> ;)

**Comment by borissimkin** [comment]
how could i miss this, thank you very much)
