### ISSUE TITLE
Missing error reports

### ISSUE THREAD

**Issue by Pixdigit** [python-telegram-bot/python-telegram-bot#173]
I have not gone through the code so what follows about internal stuff are just assumptions:

When beginning to learn the lib I stumbled around a problem where it would not send the message but would return no error message. After trying around I found out that errors in general in the functions that handle the messages and are given to functions like `addTelegramCommandHandler(bot, this_function)` are completely ignored. 
I am sometimes not a fan of PEP either but please at least [PEP-20](https://www.python.org/dev/peps/pep-0020/):
10.Errors should never pass silently.
11.Unless explicitly silenced.

And  in this case it makes no sense to silence them.

**Comment by Pixdigit** [comment]
Sorry for the rage but I just "wasted" what felt like hours (probably 10minutes) and it is really annoying when it is such a simple solution.
Either way, thank you for the awesome lib ;)

**Comment by jh0ker** [comment]
Hey :)
Have you checked `addErrorHandler()`? You can pass a handler that will receive all Errors that are Telegram-related (`TelegramError`). All other errors are logged, but the program will not exit.

**Comment by Pixdigit** [comment]
Logged where to?

**Comment by jh0ker** [comment]
To the `logging` module. You can set up basic logging like so:

     logging.basicConfig(level=logging.DEBUG,
                         format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                         filename='bot.log',
                         filemode='w')

or, if you want to log to stdout:

     logging.basicConfig(level=logging.DEBUG,
                         format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

**Comment by Pixdigit** [comment]
Ok thank you for the fast help. ^^

But please mention it somewhere in the "getting-started" section to avoid further confusion.

**Comment by jh0ker** [comment]
Will do! Thank you for using this lib :) Feel free to also join our Telegram Group if you have more questions (a link can be found at the top of the README)
