### ISSUE TITLE
Feature: get correct offset for entites in messages with emojis

### ISSUE THREAD

**Issue by SpcCw** [python-telegram-bot/python-telegram-bot#1732]
#### Problem:
If message contains emojis, values returned in `entity.offset` are wrong and do not match where entity applies to text. While `update.message.parse_entity` does return correct entity substring, sometimes correct offset is needed as well. See example below.

#### Describe the solution you'd like:
Some method or attribute returning correct offset for entities. `update.message.parse_entity` already calculates correct substring, it just has to return its offset and length (or start and end index) too.

#### Describe alternatives you've considered:
As it happens as a conflict between two UTF-16 and UTF-8 encodings it is possible to calculate it manually every time. It is cumbersome, especially for novices.

#### Example:
I need to replace Telegram text formatting with BBCode so it can be reshared to BBCode compatible system API. So I need to parse message and convert **some bold text**  into `[b]some bold text[/b]`. Knowing just correct entity substring isn't good enough for this as strings in the text can repeat. 

E.g.: 
"I do like cats because cats **do** what they want."

`update.message.parse_entity` returns substring "do" and it is impossible to know which one to process without correct offset.

**Comment by Bibo-Joshi** [comment]
Hi. A workaround would be to have a look an `Message._parse_html/_parse_markdown` and build your own method based on it. If you want it to work with nested entities, you should have a look an the `nested-entities` branch, since API 4.5 is not yet merged …

**Comment by software2Daniel** [comment]
I am giving you a list of 5 best paid engineering in our nation
Enter now


https://sites.google.com/aprendizajesignificativo.org/ingenierasmejorpagas/p%C3%A1gina-principal

**Comment by SpcCw** [comment]
@Bibo-Joshi thanks for the suggestion! I added new method _parse_bbcode similar to existing ones, it seems to work well. 

While I believe it shouldn't close this issue because people may need correct offsets for other reasons maybe we can include bbcode parsing with the bot?

**Comment by Bibo-Joshi** [comment]
Glad it helped :)
To be honest, maintaining the parse modes supported by Telegram already is not fun (implementing the API 4.5 update gave me headaches) and since there is no direct use case for BBCode with the API itself, I don't see that we would add it.
However, you are very welcome to add your code to the code snippets section of our wiki.

As for the actual feature: @Poolitzer, are you working on this (already or in the near future)?
If not: @SpcCw you are welcome to create a PR to add a method `parse_entity_position` (or a similar naming). Spontaneous thoughts on that:

* I guess the return value should be a tuple `(offset, length)` or `(start_index, end_index)`
* We will need test cases for the new method of course
* `parse_entity` and friends should leverage the new method wherever possible
* If you like, you can add yourself to the authors file

**Comment by Poolitzer** [comment]
No Im not working on it. I realized the way we deal with non UTF 16 environment is with encoding the string into a weird format and then decoding the cut out part back, which makes calculating the actual length of the entity in the string way harder then I thought.

**Comment by Bibo-Joshi** [comment]
haha, okay :D
So, @SpcCw if you feel like giving it a try, feel free to go ahead. If not, I suggest we close the issue.

**Comment by SpcCw** [comment]
I arrived to the same conclusion as Poolitzer earlier but blamed my very little Python experience :)

Right now I patched message.py and messageentity.py to add additional method but if there is no use for it in the main code, I'll work on making it code snippet instead.

**Comment by Poolitzer** [comment]
@SpcCw No worries, I also blame my insufficient experience.

**Comment by Bibo-Joshi** [comment]
> Right now I patched message.py and messageentity.py to add additional method but if there is no use for it in the main code, I'll work on making it code snippet instead.

Great, thanks :)

**Comment by SpcCw** [comment]
I added it to the wiki: [Telegram formatting to BBCode](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#telegram-formatting-to-bbcode)

Mentioning it here too in case someone comes looking :)

**Comment by Bibo-Joshi** [comment]
👍 Just added a note that nested entities are not supported by the snippet ;)
