### ISSUE TITLE
Add helpers for t.me/ links

### ISSUE THREAD

**Issue by JosXa** [python-telegram-bot/python-telegram-bot#1733]
In #854, I suggested to also add extract_url helpers for `t.me/..` links:

![image](https://user-images.githubusercontent.com/7313176/73142068-e16e7b00-408a-11ea-97c9-3e93875f5d6e.png)

https://github.com/python-telegram-bot/python-telegram-bot/pull/854#issuecomment-566120162

This represents that comment converted to an issue.

**Comment by Bibo-Joshi** [comment]
After internal discussion, we decided not to implement this. Also see [here](https://github.com/python-telegram-bot/python-telegram-bot/pull/854#issuecomment-581179809)
