### ISSUE TITLE
Get Name input from User

### ISSUE THREAD

**Issue by blaublaugelb** [python-telegram-bot/python-telegram-bot#1736]
Hi everyone .
I am trying to fetch names of two users in the telegram chat, so the chatbot can call them by their name directly.
My code didnt work so far:

…
names = []

def get_name(update, context):
    if not names:
        text = update.message.text

        names.append(text)
        return get_name

    else:
        names.append(update.message.text)
        return B

def b(update, context):

    update.message.reply_text("{}, how old are you?".format(names[0]))

    return C
…

Does anyone know, how this could work?
Thanks a lot

**Comment by Bibo-Joshi** [comment]
@blaublaugelb Hi. from what I can tell from your snippet, you may wanna have a look at <code>user_data</code> (see our <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Storing-user--and-chat-related-data">wiki page</a> and the documentation of <a href="https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.callbackcontext.html#telegram.ext.CallbackContext.user_data">CallbackContext</a>). You can store the users name as e.g. <code>user_data[&#x27;name&#x27;]</code> and access it in later callbacks.
