### ISSUE TITLE
[QUESTION] How do job queues communicate with the API when launched in a webhook configuration.

### ISSUE THREAD

**Issue by vulcan25** [python-telegram-bot/python-telegram-bot#1737]
I've been reading the Wiki article about [Job Queues](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-JobQueue) although I haven't yet had the chance to test this functionality.

I'm trying to work out how these communicate with the Telegram API.

```
u = Updater('TOKEN', use_context=True)
j = u.job_queue
def callback_minute(context: telegram.ext.CallbackContext):
    context.bot.send_message(chat_id='@examplechannel', 
                             text='One message every minute')

job_minute = j.run_repeating(callback_minute, interval=60, first=0)
```
This code would make sense when the `Updater` is launched with the polling method, as (if my understanding is correct) my Python code periodically polls the API, acting like a client, thus could theoretically send out the message at the interval specified above.

However, when the `Updater` is launched with the webhook method, Telegram's API is instructed to hit the speicified URL on my server, with every message the bot receives.  How can this code then send out the message at that interval, if it needs Telegram's API to invoke the callback.

Perhaps I'm misunderstanding part of this?  Could anyone clarify what's happening here?

**Comment by Bibo-Joshi** [comment]
Hi. Getting updates and sending "commands" to telegram are two different things. In particular, the latter is nothing more then making http requests (see [here](https://core.telegram.org/bots/api#making-requests)) and as such independent of the method used to get updates. So you can even send messages without even bothering about getting updates:

```
bot = Bot('TOKEN')
bot.send_message(chat_id, text)
```
I hope that this answers your question :)

**Comment by vulcan25** [comment]
Great answer, many thanks.

So it would be true to say that a webhook enabled bot, which also uses job queues (or sends messages with the method you mentioned here) would recieve both incoming HTTP requests for the former, and make outgoing HTTP requests for the latter?

**Comment by Bibo-Joshi** [comment]
Yes, the updates come as requests to the webhook and the bot sends messages as requests to the telegram api
