### ISSUE TITLE
[QUESTION] filter and call callback_funtion with '@mybotname' tag ?

### ISSUE THREAD

**Issue by tuansacer** [python-telegram-bot/python-telegram-bot#1742]
Hello.
How I can filter and call callback_funtion for my bot when someone using '@mybotname' tag ?
If you have any code sample, Please help me

**Comment by Bibo-Joshi** [comment]
@tuansacer Hi. It&#x27;s not very clear, what you&#x27;re trying to achive. Please fill out the issue template and describe your problem more precisely.

**Comment by tuansacer** [comment]
@Bibo-Joshi so sorry. My Emglish really is not good.
I trying make my bot only accept command code when someone using tag "@mybotname".
Example: Use "@mybotname /help"  instead of "/help" (CommandHandler)

What can I using for this case ?

**Comment by Bibo-Joshi** [comment]
@tuansacer Okay. Your best shot probably is a PrexifHandler, with prefix &quot;@mybotname /&quot; and <code>command</code> a list of all commands that should be accepted (e.g. <code>[&quot;help&quot;, &quot;start&quot;]</code>).
To make sure that only acutal bot commands are accepted, you could combine this with <code>filters.entity</code>.
Also note, that in group chats bots will only listen to commands like <code>/help@mybotname</code> by default. For more information, you should have a look at<a href="https://core.telegram.org/bots/faq#what-messages-will-my-bot-get"> privacy mode</a>.
Hope, this helps

**Comment by Bibo-Joshi** [comment]
@tuansacer Okay. Your best shot probably is a PrexifHandler, with prefix &quot;@mybotname /&quot; and <code>command</code> a list of all commands that should be accepted (e.g. <code>[&quot;help&quot;, &quot;start&quot;]</code>).
To make sure that only actual bot commands are accepted, you could combine this with <code>filters.entity</code>.
Also note, that in group chats bots will only listen to commands like <code>/help@mybotname</code> by default. For more information, you should have a look at<a href="https://core.telegram.org/bots/faq#what-messages-will-my-bot-get"> privacy mode</a>.
Hope, this helps

**Comment by tuansacer** [comment]
@Bibo-Joshi Thanks so much. I will try this way
