### ISSUE TITLE
[BUG] Improve Wiki pages regarding Python 2 and venv

### ISSUE THREAD

**Issue by septatrix** [python-telegram-bot/python-telegram-bot#1743]
### Expected behaviour
In accordance to #1538 (#1731 #1734 and #1715) we should default to Python 3 for wiki pages.
This would mean default to using `python3` and `pip3` as long as the respective versionless commands are not aliased to them in most major distributions.

### Actual behaviour
The wiki does not mentions Python 3 as the default case for usage

### Misc
We would need to look through all wiki pages manually.
When doing so I think would be a good time to switch to using Pythons `venv` in examples as I sometimes experienced a few problem installing this module globally...

**Comment by Bibo-Joshi** [comment]
Hi. Sorry for the late reply.
For the `python/pip3` part: Would be good yes. 
For the `venv`: I'd suggest to rather put a note somewhere that using `venv` might be beneficial. But since the acutal setup of a system is up to the user, I would not rewrite the wiki to use a `venv` by default.
Would you maybe like to do these changes?

**Comment by Bibo-Joshi** [comment]
Update: Please don't use `sudo` in the examples either (see #1558 ) ;)

**Comment by septatrix** [comment]
Oh okay

**Comment by septatrix** [comment]
Using `sudo` for `apt` though is necessary. The discussion you linked was about `pip` where it indeed should be avoided to use `sudo` and most of the time `--user` should be used.

**Comment by Bibo-Joshi** [comment]
oh yes, overlooked that. just saw sudo and remembered #1558 :D Thanks for being busy on the wiki! Feel free to close this one you're done :)

**Comment by septatrix** [comment]
Additionally i added a few ` ```python ` tags to doc strings and used `python3 -m pip` instead of `pip` as the former has a few advantages and is recommended. Maybe we should also add this issue to the 13.0 Milestone as there are a few places in the wiki where we include additional information for python 2 which we won't support in that release

**Comment by Bibo-Joshi** [comment]
Mh, I feel like that can be removed when someone stumbles upon it after 13.0 is released. I'll close this for now.
thanks again for the effort :)

**Comment by Bibo-Joshi** [comment]
Seems we rushed ahead a bit here. The consensus is the dev chat is that people should know what python version they use. I reverted the changes.
