### ISSUE TITLE
Add User in Group

### ISSUE THREAD

**Issue by anderson7play** [python-telegram-bot/python-telegram-bot#1745]
I made a bot that verify if user buy a course, it is works!

How can I put this user that buy my course in a group automatically?

**Comment by Poolitzer** [comment]
You cant.

What you can do is send the user an invitation link to your group, revoke the link after the user joined and kick users who join the group if they are not supposed to be there.

**Comment by anderson7play** [comment]
Thanks for previous reply! 

Can you say to me, How can I send a message to a unique user automatically?

**Comment by Poolitzer** [comment]
bot.send_message, where you put the user_id

**Comment by anderson7play** [comment]
Thank you very much!  thanks for listening
