### ISSUE TITLE
updater.py modification

### ISSUE THREAD

**Issue by lopanta** [python-telegram-bot/python-telegram-bot#175]
In order to have a nice shutdown, I suggest to modify updater.py putting self. to the two thread in  
with self.__lock: 
of 
def start_polling(self, poll_interval=0.0, timeout=10, network_delay=2): 

and to add
                self.dispatcher_thread.join()
                self.updater_thread.join()
before
self.logger.debug("Dispatcher stopped.")
in 
with self.__lock:
            if self.running:
of
def stop(self):

thanks

lorenzo

**Comment by tsnoam** [comment]
fixed on #177
