### ISSUE TITLE
Make `filters.command` work as expected

### ISSUE THREAD

**Issue by Eldinnie** [python-telegram-bot/python-telegram-bot#1755]
Now `filters.text` allows messages starting with a `/`, not excluding bot commands, we need a fast and simpler way to stop those entering `filters.text` if you want to exclude them.

I propose to change `filters.command` to the following behavior:
- invoking `filters.command` will filter any messages with `entity.type='bot_command`. Basically a mirror of `filters.entity(['bot_command']) which we can just invoke this way)
- invoking `filters.command(only_start=True) | filters.command(True)` (name is open for discussion) filters any messages that **start** with a bot command.

this will allow for easily using `filters.text & ~filters.command(true)` to not get any command updates with your text filter.

Optionally we could make `filters.command` a `data_filter` and add the found commands to CallbackContext` as the `context.commands` (list). Although maybe that is outside this scope and then should also be added for commandhandler to add.

**Comment by Bibo-Joshi** [comment]
See #1744. This makes filters.command only listen for MessageEntities, but lacks the `only_start` parameter

**Comment by Bibo-Joshi** [comment]
Personally I'd argue, that filtering for bot commands *not* at the beginning can be done by `filters.entity` easily enough. So after #1744 filtering for texts not starting with command could be done with `filters.text & ~filters.command` while `filters.text & ~filters.entity(ME.BOT_COMMAND)` will only allow messages that don't have a bot command anywhere.
Also, allowing `foo /command` for `filters.command` now would be breaking in terms of it would allow more updates than currently.

**Comment by Eldinnie** [comment]
@Bibo-Joshi Maybe, but then the filters name should be changed because <code>filters.command</code> does not imply only the start of the message. Would changing the default behavior to only at the start, and optionally everywhere in the message be better?
Mind you, we&#x27;re already having a breaking change with the change to <code>filters.text</code>. So once you start, you might aswell break more.

**Comment by Bibo-Joshi** [comment]
> Mind you, we're already having a breaking change with the change to `filters.text`. So once you start, you might aswell break more.

True
> Maybe, but then the filters name should be changed because `filters.command` does not imply only the start of the message. Would changing the default behavior to only at the start, and optionally everywhere in the message be better?

Good point. but with changing the default to only start I'd be comfortable (also without renaming `filters.command`). My reasoning: Commands are mainly used as "standalone" messages, i.e. when selecting a command in the app, it'll immediately send it rather then allowing you to append it to an existing message. So even `/cmd arg1 arg2` is less common than `/cmd`, not to speak of `arg1 arg2 /cmd`
