### ISSUE TITLE
Use tempfile module in tests

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#1765]
E.g. in test_persistence, but also check the other tests. Better than actually writing to disk.

**Comment by Bibo-Joshi** [comment]
Mh, with `tempfile` module there is no way to specify the exact file name of the created temporary files. But `PicklePersistence` will look for specific file names and I wouldn't fancy monkey patching the load methods of `PicklePersistence` in the tests …

**Comment by tsnoam** [comment]
@Bibo-Joshi What about using tempfile to create a temp directory?
