### ISSUE TITLE
Don't use builtin function names as variables

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#1766]
There is e.g. `all` in `PicklePersistence` and I think also `type` somewhere. Also `id`

**Comment by tsnoam** [comment]
@Bibo-Joshi &quot;type&quot; might be forced upon us because of it is derived from telegram API.

**Comment by Poolitzer** [comment]
@tsnoam Actually, I think most of our usage of built-in function names will be where we take the naming from the API, and I dont think its worth changing that. Nevertheless, I can have a look later and see if I find issues of that in other places
