### ISSUE TITLE
[BUG] Inconsistence Defaults

### ISSUE THREAD

**Issue by hexatester** [python-telegram-bot/python-telegram-bot#1772]
### Steps to reproduce
1. Create instance of telegram.Bot with token
2. Create instance of telegram.ext.Default with parse_mode=telegram.ParseMode for example
3. Then create Updater with the instance of telegram.Bot and telegram.ext.Default

### Expected behaviour
Default parse_mode should be telegram.ParseMode right?
Please confirm if it's intended behaviour, or not.

### Actual behaviour
Default parse_mode is None

### Configuration
**Operating System: WSL2 Ubuntu**

**Version of Python, python-telegram-bot & dependencies: python3.8, python-telegram-bot==12.4.2**

Thanks.

**Comment by Bibo-Joshi** [comment]
@hexatester Hi. If you pass a custom Bot instance to the Updater, you will need to set <i>all</i> the arguments by yourself. In this case you will need to pass the instance of telegram.ext.Defaults to the Bot as well as to the Updater.
If you just need a regular bot, that is you&#x27;re not e.g. subclassing, it&#x27;s recommended however, to just pass the token to the Updater. That way it will take care of creating a Bot instance <i>and</i> passing all suitable arguments.
I hope this helps :)

**Comment by hexatester** [comment]
Oh. I see now, thanks btw @Bibo-Joshi 
Please add additional info to Updater documentation, about Defaults and in conjunction with custom Bot.
