### ISSUE TITLE
Wrong phone number entity parsing when generating Message.text_html

### ISSUE THREAD

**Issue by Flowelcat** [python-telegram-bot/python-telegram-bot#1774]
### Steps to reproduce
1. Send message using bot.send_message(...) with HTML parse mode and text where phone number send as bold. For example 
`bot.send_message(chat_id=chat_id, text="<b>+7-111-1111111</b>", parse_mode="HTML")`

2. Print returned message.text_html

3. Get printed value `"+7-111-1111111<b>+7-111-1111111</b>"`

### Expected behaviour
For source sended text `"<b>+7-111-1111111</b>"` expected to print
`"<b>+7-111-1111111</b>"`

### Actual behaviour
For source sended text `"<b>+7-111-1111111</b>"` we get
`"'+7-111-1111111<b>+7-111-1111111</b>"`

### Configuration
**Operating System:** Ubuntu 18.04.4 LTS

**Version of Python, python-telegram-bot & dependencies:**

```
$ python -m telegram
python-telegram-bot 12.4.2
certifi 2019.11.28
future 0.18.2
Python 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
```

**Comment by Poolitzer** [comment]
Hey, thats a nested entity related bug I fuess. You would need to try it with that branch, but it should be fixed there. Will see by myself in a bit, that's likely the issue.

**Comment by Bibo-Joshi** [comment]
Can confirm that it's a nested entity thingy and it works as expected on the `nested-entities` branch. I'll close this since it's just not supported currently but will be, when API 4.5 is merged. Sorry for putting you off …

**Comment by Poolitzer** [comment]
Btw, if you want 4.5 support right now, check this message out: https://t.me/pythontelegrambotgroup/291272
