### ISSUE TITLE
[QUESTION] How to cron

### ISSUE THREAD

**Issue by pristis** [python-telegram-bot/python-telegram-bot#1776]
Hello!

I have a problem. When I start the bot manually, from the console, there is no problem and works perfect.

When I put the py file on crontab with code: `@reboot python /home/user/bot_dir/bot.py` the bot doesn't start and there is the log of cronjiob https://pastebin.com/u5te1kpB. But manually works.

Can someone to help me to start the bot on boot?

Thanks!

**Comment by tsnoam** [comment]
@pristis Network is probably still down when cron service spawns your bot.

You might want to try using systemd to start your bot service and make it dependent on network.
