### ISSUE TITLE
[BUG] NetworkError urllib3: Failed to establish a new connection

### ISSUE THREAD

**Issue by fjnieto15** [python-telegram-bot/python-telegram-bot#1777]
# Steps to reproduce
1. Create a simple bot which sends a message every 5 minutes

### Expected behaviour
The message should arrive every 5 minutes

### Actual behaviour
The chat starts  receiving messages from the bot and the stops

### Configuration
**Operating System:** Raspbian Buster Lite

**Version of Python, python-telegram-bot & dependencies:** 
``$ python -m telegram``
python-telegram-bot 12.3.0
certifi 2018.08.24
future 0.18.2
Python 3.7.3 (default, Apr  3 2019, 05:39:12)  [GCC 8.2.0]

### Logs
File "/usr/local/lib/python3.7/dist-packages/telegram/utils/request.py", line 224, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot$TOKEN$/getMe (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0xb58d3430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by Poolitzer** [comment]
Hey, this is an issue with your network, not with us.

**Comment by fjnieto15** [comment]
> Hey, this is an issue with your network, not with us. The log tells you exactly what fails :)

Well, maybe I opened the bug because what the log says it fails, does not fail.

I continuously ping to api.telegram.org and receive 45ms response, while the bot is telling me that it is unreachable... The board (Raspberry Pi Zero W) is placed 5 meters away of the router, so wifi signal is never lost... I don't think is my connection, and if it was, I don't know how to debug the issue, so please, help me out.

**Comment by jh0ker** [comment]
The error message indicates a problem with the DNS servers. Perhaps your ping only resolves the domain once, while urllib3 does it more often to make sure it's always up to date.
Perhaps you could try setting up a different DNS provider like 1.1.1.1 (Cloudflare) or 8.8.8.8 (Google) in your OS or Router to prevent this issue.

**Comment by fjnieto15** [comment]
I have set static DNS in my Raspberry to use Cloudfare's servers: `1.1.1.1` and  `1.0.0.1`.But the same error stills happenning... Is there a way to test if the DNS are being used as they should?

**Comment by jh0ker** [comment]
I'm not sure how to do that with urllib3. On a system level you can probably confirm with `nslookup` or `dig`.
If the problem persists with different DNS servers, that probably means there is a bigger network problem. Perhaps instead of using a ping, try setting up a small shell script that runs something like `curl https://api.telegram.org/botYOURTOKENHERE/getMe
` every 5 seconds to figure out if it's urllib3-specific or if other http clients are affected.

**Comment by fjnieto15** [comment]
Well, I think I found the issue here. The bot was set to automatically start when the RPi did, and it seems the bot started too early and did not have connection or could not resolve the IP... I don't know.

Introducing a delay before launching the bot seems to have solved the issue.

**Comment by jh0ker** [comment]
@fjnieto15 Glad you were able to figure out the problem, and thank you for reporting back here!
