### ISSUE TITLE
Link to the group in `README.md` is invalid.

### ISSUE THREAD

**Issue by blueset** [python-telegram-bot/python-telegram-bot#178]
Link to the group in `README.md` is invalid.

By the way, is it possible to integrate it with Django or Flask?

**Comment by naveenvhegde** [comment]
Yes, the group link is invalid. Telegram group is chnaged to invite only group. Contact @jh0ker.

you can integrate with Flask, but you won't be able to use Updaterr, you can still use Dispatcher to demux events.

**Comment by jh0ker** [comment]
Sorry, the group link expires or breaks every other day now. And no, @naveenvhegde, the group is not invite-only ;)
About integrating with Flask, also check #160
