### ISSUE TITLE
[BUG] fallback not working

### ISSUE THREAD

**Issue by rspadim** [python-telegram-bot/python-telegram-bot#1782]
Hi!
I'm not receiving fallback updates (when no other entrypoint was used) 
i checked the source code at https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/dispatcher.py#L383 and didn't found what happen when no update was select, any help here?

**Comment by Bibo-Joshi** [comment]
What do you mean by "receiving fallback updates"? Please fill out the entire issue template.

**Comment by rspadim** [comment]
if it's not the defined behaviour

could we include a global fallback method?

**Comment by rspadim** [comment]
hi Bibo

i'm using a ConversationHandler() and when no state was selected to handle the update, the fallback should be used

but i'm a bit confused if the state isn't being used (i'm not in a conversation handler) or if fallback isn't being triggered

considering the conversation handler:

```
ConversationHandler(
			entry_points=[CommandHandler('start', start, pass_args=True)],
states={0:[ MessageHandler(Filters.all, state_0)],
1:[ MessageHandler(Filters.all, state_1)],
2:[ MessageHandler(Filters.all, state_2)]},
fallbacks=[MessageHandler(Filters.all, fallback)]
)
```

i never hit the fallback function

**Comment by rspadim** [comment]
could be possible a global fallback method? for example...
consider that /start wasn't used by user (i restarted the bot and not using persistence) should a global fallback method handle any update and tell user that he must /start again?

**Comment by Bibo-Joshi** [comment]
For the global fallback: We don't like adding default functionality to the library. You can easily add a global fallback yourself by `dp.add_handler(TypeHandler(Telegram.Update, callback), group=<some very high number>)` or something similar.

As for you specific problem: The fallback of the ConversationHandler will only be called, if the conversation is active. So if the user didn't send `/start` in your case, there is no way for `fallback` to be triggered.

Hope this helps

**Comment by rspadim** [comment]
yes, this helps a lot, since i restarted the server, the /start isn't handled (i'm without persistent)

thanks bibo!
