### ISSUE TITLE
telegram.bot logging

### ISSUE THREAD

**Issue by dev-dsp** [python-telegram-bot/python-telegram-bot#179]
Sorry for such a stupid question, but how can i disable logging this:
> 2016-02-12 07:07:03,499 - telegram.bot - INFO - No new updates found.
? It is very annoying for me.
I appreciate your help.

**Comment by naveenvhegde** [comment]
time being, this can be suppressed like this.

tglogger = logging.getLogger("telegram.bot")
tglogger.setLevel(logging.WARN)

**Comment by jh0ker** [comment]
This has been already fixed for #167
