### ISSUE TITLE
[Feature] update hut count

### ISSUE THREAD

**Issue by rspadim** [python-telegram-bot/python-telegram-bot#1790]
hello

Could be possible if the current update message (any kind of message) include how many handlers (considering all groups) handled the message?

It’s usefull when a message was not handled by any other handler sucessfully and the current handler is a “final handler” to tell user what options should he/she answer

Maybe a counter inside context variable could do this job, a handlers_hit and a handlers_hit_with_error

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for the suggestion. However, the use case seems quite specific. Moreover, using `bot_data`, `chat_data` and `user_data` you can already keep track on the information you need. Simply store it in the callback and in the "final handler" callback if you find no stored data you will know that the update hasn't been handled so far. We also have a [wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Storing-bot%2C-user-and-chat-related-data) on storing data that you might wanna read.

**Comment by rspadim** [comment]
Nice i think it will fit perfectly, thanks!
