### ISSUE TITLE
[BUG] HTML formatting does not replace &lt; &gt; &amp; symbols

### ISSUE THREAD

**Issue by e-caste** [python-telegram-bot/python-telegram-bot#1793]
### Steps to reproduce
1. Setup a test bot to send a message containing the "<" character and use `parse_mode=HTML` in the `send_message` method. You will see a traceback saying that it can't parse an empty HTML tag, as expected.

2. Now, per [Telegram bot documentation](https://core.telegram.org/bots/api#html-style), if you replace the "<" character with `&lt;` it should interpret it correctly, that is as a "less than" sign, and not the beginning of an HTML tag. Even when setting `parse_mode=HTML`, the message received will contain literally `&lt;`, and not "<", which means the message is not entirely parsed as HTML (it works for the bold, italic and some other tags).

3. Here's the strange part: if you use the following code, it will work correctly.
```
update.message.reply_text(text="<"
                                  .replace("<", "&lt;").replace(">", "&gt;").replace("&", "&amp;")  # WRAP in html formatting
                                  .replace("&lt;", "<").replace("&gt;", ">").replace("&amp;", "&"),  # UNWRAP html formatting
                                  parse_mode=HTML)
```

### Expected behaviour
The strings `&lt;`, `&gt;`, `&amp;` are converted to the strings "<", ">", "&" respectively if using `parse_mode=HTML`.

### Actual behaviour
To work correctly, we need to use a double `.replace()` call, first to convert "<", ">", "&" to `&lt;`, `&gt;`, `&amp;`, and then back, as shown at point 3.

### Configuration
**Operating System:** macOS 10.15.3, Ubuntu Server 18.04.

**Version of Python, python-telegram-bot & dependencies:** Python 3.7.
Result of `pip freeze`:
```
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
cryptography==2.8
decorator==4.4.1
future==0.18.2
idna==2.9
pycparser==2.19
python-telegram-bot==12.4.2
requests==2.23.0
six==1.14.0
tornado==6.0.3
urllib3==1.25.8
```

``$ python -m telegram``
```
python-telegram-bot 12.4.2
certifi 2019.11.28
future 0.18.2
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24)  [Clang 6.0 (clang-600.0.57)]
```

### Logs
No necessary logs.

**Comment by Bibo-Joshi** [comment]
Hi. When sending messages with parse mode, you will have to do the escaping yourself, as there is no way to come up with a general rule on when to escape a character and when not to.
You can easily escape using [html.escape](https://docs.python.org/3/library/html.html#html.escape).
so your example would become

```python

update.message.reply_text(text=escape("<"), parse_mode="HTML")
```

hope, this helps :)
