### ISSUE TITLE
Continue conversation afret restart

### ISSUE THREAD

**Issue by panitrooper** [python-telegram-bot/python-telegram-bot#1794]
Is it possible to continue conversation without use an enter_point after restart bot?

**Comment by Bibo-Joshi** [comment]
Yes, if your conversations are persistent, it's current state will be safed and after a restart the conversation can be continued. Please also have a look at the docs about [conversations](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.conversationhandler.html#telegram.ext.ConversationHandler.persistent) and [persistence](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Making-your-bot-persistent#what-do-i-need-to-change).

**Comment by panitrooper** [comment]
What I should do if I need to continue conversatoin, which contains handlers with @run_async decorator? Pickle don't working.

**Comment by Bibo-Joshi** [comment]
@panitrooper For persisting conversations, only the current <i>state</i> of the conversation is safed, so I don&#x27;t think that you will have a problem with that.

**Comment by panitrooper** [comment]
But I have this error if I using handlers with @run_async decorator in conversation:

`Can't pickle <function UserHandlers.__get_timetable at 0x0000023D4516CEE8>: attribute lookup UserHandlers.__get_timetable on handlers failed`

And after that I can't restart bot? because piclefile is incorrect.

**Comment by Bibo-Joshi** [comment]
@panitrooper I don&#x27;t really understand your setup. Can you provide a minimal working example or you code?

**Comment by Bibo-Joshi** [comment]
@Eldinnie pointed out, that with `@run_async`, the new state of the conversation will be a promise, which isn't pickable. So currently, it's not easily possible to have a asyncronous handler in a conversation.
