### ISSUE TITLE
Embed a photo in message

### ISSUE THREAD

**Issue by Keramatfar** [python-telegram-bot/python-telegram-bot#1795]
Dear developer,
is there any way using this package to send an image embedded message?

**Comment by Bibo-Joshi** [comment]
@Keramatfar <b>Bot.send_photo</b>
<i>python-telegram-bot</i> documentation for this method:
<a href="https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.send_photo">telegram.Bot.send_photo</a>

The official documentation has more info about <a href="https://core.telegram.org/bots/api#sendphoto">sendPhoto</a>.
