### ISSUE TITLE
[BUG] Error handler omits important information

### ISSUE THREAD

**Issue by pflink** [python-telegram-bot/python-telegram-bot#1796]
### Steps to reproduce
1. Run PTB and wait for an error to happen

2. Repeat step 1

3. Repeat step 2

### Expected behaviour
Tell us what should happen
Error handler should report what module caused error and on what line. The builtin error handler does this.
### Actual behaviour
Error handler reports like this:

: WARNING Update "{'update_id': .... is_bot': False, 'language_code': 'fi'}}}" caused error "Expecting value: line 1 column 1 (char 0)"

Which is almost useless. It's much better to just comment out the error handler, which gives you the erroring module and line of code, but then halts the code execution.

### Configuration
**Operating System:**
Applies to all

**Version of Python, python-telegram-bot & dependencies:**
Latest version of python and PTB. 
``$ python -m telegram``

### Logs
Not necessary.

**Comment by Bibo-Joshi** [comment]
Hi. The error handlers in the examples are *examples* and you are in fact encouraged to handle errors in a way that suits your needs. You may want to have a look at [this snippet](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#an-good-error-handler) and the [docs](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.dispatcher.html#telegram.ext.Dispatcher.add_error_handler). I hope this helps.

**Comment by pflink** [comment]
Thanks. Didn't know the error handler was just a function like that.
