### ISSUE TITLE
[FEATURE] Extensions of Defaults

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#1797]
Possible candidates to add to the Defaults concept:

## tzinfo
We should use Defauts.tzinfo as default instead of UTC … That would mean:

* When a job is created without setting tzinfo explicitly, use Defaults.tzinfo
* When calling JobQueue._put() with a naive `when`, use `when.replace(tzinfo=defaults.tzinfo)`
  This would basically not change the current set up, but just put it under the hood
* Probably `Message.date` and all the friends should also use `defaults.tzinfo`, so basically every `datetime` instance occuring in the lib.

## Arguments of Filters

* Filters.command: allow commands *anywhere* in the text or not
* Filters.{user, chat}: *allow_empty* (only relevant after #1757)

How to make it work: We would need to override those attributes on `dispatcher.add_handler` somehow. that's pretty much the only time, the filters and the dispatcher can see each other …

## Dice.emoji

* Only relevant after #1917. Also discussable, if this really is a good idea, as the emoji attribute of `Dice` is positional and not optional

## ReplyKeyboardMarkup

* `resize_keyboard`
* `one_time_keyboard`

# Redesign of `default_quote`

Right now, `default_quote` get's passed from getting updates through all objects, whose attributes have a `Message` attribute and is set as attribute in `Message`. But as the `Message.reply_*` methods only work with a bot anyway, we could just access `Message.bot.defaults.default_quote`.

See #1965

**Comment by Bibo-Joshi** [comment]
On second thought, we should use `Defauts.tzinfo` as default instead of `UTC` then, so it's probaby worth it already …

**Comment by Bibo-Joshi** [comment]
closed by #2042 and #1965

(We decided that additional things should probably only be added to defaults only, when users actually request it  …)

**Comment by JosXa** [comment]
> Filters.command: allow commands anywhere in the text or not

what the heck? ^^

**Comment by Bibo-Joshi** [comment]
> > Filters.command: allow commands anywhere in the text or not
> 
> what the heck? ^^

Read as: Add default setting for making `Filters.command` only filter for commands at the start of the message or anywhere in the message. The filter has a parameter for that since … 12.4?
But as stated above, the consensus in dev chat was to not add more defaults too quickly. See [here](https://t.me/c/1494805131/5336) and above
