### ISSUE TITLE
Custom keyboard with the updater class

### ISSUE THREAD

**Issue by giacomocerquone** [python-telegram-bot/python-telegram-bot#180]
Hi, I need some help here. This is my first python project (never worked with it before) and due to a lack of examples I can't figure how (if it's possible) I can create custom keyboards using the new updater class. If I had known python enough I would have understood it by myself looking the sources.
I appreciate every kind of support, thanks.

**Comment by jh0ker** [comment]
@giacomocerquone Hi :) 
The custom Keyboard example in the Readme still applies if you're using the updater.

**Comment by giacomocerquone** [comment]
Thank you very much, I needed just to be sure that it was possible. I figured out by myself.
The problem I encountered was that I didn't think I had to import anyway telegram if I was using the new updater class (maybe because I saw the examples and in all of them the whole telegram library isn't imported).

Here the code (it's useless but not harmful)
```python
def custom_keyboard(bot, update):
    keyboard = [[ "btn1", "btn2" ]]
    reply_markup = telegram.ReplyKeyboardMarkup(keyboard)
    bot.sendMessage(update.message.chat_id, text="You enabled the custom keyboard", reply_markup=reply_markup)
```

**Comment by jh0ker** [comment]
Oh I see. You could also so something like `from telegram import Updater, ReplyKeyboardMarkup` so you can use the keyboard directly without to prepend `telegram`.
