### ISSUE TITLE
one time keyboard

### ISSUE THREAD

**Issue by HadiMhh** [python-telegram-bot/python-telegram-bot#1801]
Hi,
I used this method:
```python
classtelegram.ReplyKeyboardMarkup(
    keyboard,
    resize_keyboard=False,
    one_time_keyboard=False,
    selective=False,
    **kwargs
)
```
and I set the ```one_time_keyboard``` True so the buttons disappear when the user clicks on one of them. But after that the user phone keyboard is opened automatically. I want to prevent the keyboard being opened automatically because I have lots of panels that user moves between them and opening of the typing keyboard is not necessary and sometimes bad experience.
How can I prevent that?

Thank you

**Comment by Poolitzer** [comment]
@HadiMhh Hey, you would need to delete the Keyboard with the next message the bot sends in orddr fo prevent this. It still exists on the user side because the clients are only asked to hide it in their UI, not tobdelete it

**Comment by Poolitzer** [comment]
@HadiMhh Hey, you would need to delete the Keyboard with the next message the bot sends in orddr fo prevent this. It still exists on the user side because the clients are only asked to hide it in their UI, not to delete it

**Comment by Poolitzer** [comment]
@HadiMhh In case you are referring to the phone keyboard being opened, no way to do this, sorry. You would need to contact <a href="https://t.me/botsupport">@botsupport</a> and ask if they can think of a way to implement this, but since its very client specific and only a minor inconvenience, I personally don&#x27;t see it happening.

**Comment by HadiMhh** [comment]
@Poolitzer 
Thank you for your fast response
Yes, I mean the keyboard that opens when the user clicks on the input field. 
But I want to stop it's opening when the one-time keyboard button is clicked.
So you say there is no proper way to stop the opening of the keyboard after the user clicks on one of the bot's buttons?
Thanks

**Comment by Poolitzer** [comment]
Yes, I am saying there isnt, sorry.

**Comment by Poolitzer** [comment]
closing cause discussion is over, as said, contact botsupport
