### ISSUE TITLE
answerCallbackQuery accept by user

### ISSUE THREAD

**Issue by Keramatfar** [python-telegram-bot/python-telegram-bot#1802]
Thanks for your great package,
I used this method to show a box to user, but i wonder is it possible to use this or other method to get accept from the user for his click on an inline button? for example "are you sure ?", and after acceptance the program continue?

**Comment by Poolitzer** [comment]
@Keramatfar Hey, what I do is send it with an alert the first time and ask the user to press again the same button if they are really surr

**Comment by Poolitzer** [comment]
@Keramatfar Hey, what I do is send it with an alert the first time and ask the user to press again the same button if they are really sure

**Comment by Keramatfar** [comment]
Not so user-friendly. Any other option?

**Comment by Poolitzer** [comment]
Well, its friendly imo. You can also edit the message to include your question and a yes no button markup.

**Comment by Keramatfar** [comment]
OK, but how get a signal of that, which directs the continue of code? In my case, the code continues while the user has not approved the message yet.

**Comment by Poolitzer** [comment]
Well put the code in the new handler obviously

**Comment by Keramatfar** [comment]
can you make your answer more clear?

**Comment by Poolitzer** [comment]
Uhm. What part dont you understand? If its a specific word I said, have a look at the docs+wiki first, they might explain it way better then I ever could.
