### ISSUE TITLE
[QUESTION] Multiple servers

### ISSUE THREAD

**Issue by rspadim** [python-telegram-bot/python-telegram-bot#1806]
hello, could be possible run one bot in multiple servers to loadbalance?
something like :

telegram server -> loadbalancer -> my server pool [from 0 to 10 servers running the bot]

or anything like it to spread the load?

**Comment by Poolitzer** [comment]
Yes its quite easy, you need to add one server in front of your server pool though, which receives the updates and then distributes it into your pool. From there, they can make requests without additional limitations.

**Comment by rspadim** [comment]
Uhm, how set webhook and start webhook should be set? There’s a example with two bots at nginx and webhook at documentation, but i didn’t found one with load balance, any help?

**Comment by Poolitzer** [comment]
I dont know of full fledged ptb bots with a load balancer server pool in the background, sorry. Sounds rather specific to me.

**Comment by rspadim** [comment]
i will try with nginx or haproxy, if it works i will post here =)

thanks @Poolitzer !
