### ISSUE TITLE
[QUESTION] Deploying to pythonanywhere

### ISSUE THREAD

**Issue by aldwnesx** [python-telegram-bot/python-telegram-bot#1807]
Hi, how do I deploy to pythonanywhere? What is this based on?

> 
> » Django
> » web2py
> » Flask
> » Bottle

**Comment by Bibo-Joshi** [comment]
Hi. I don't really get, what you mean. Installing is as easy as running `pip install python-telegram-bot` .
The dependencies can be found [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/requirements.txt).

**Comment by aldwnesx** [comment]
> Hi. I don't really get, what you mean. Installing is as easy as running `pip install python-telegram-bot` .
> The dependencies can be found [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/requirements.txt).

Need to set up configuration of the project when deploying on PythonAnywhere. What should I select? Thanks for replyn

**Comment by Bibo-Joshi** [comment]
I'm not familiar with PythonAnywhere. Can you post a screenshot/listing of the available options? to be clear: We're not talking about hosting a website, are we?
