### ISSUE TITLE
Using src as running code

### ISSUE THREAD

**Issue by Pixdigit** [python-telegram-bot/python-telegram-bot#181]
In the process of development I decided to use the source code itself so my users do not have to install python-telegram-bot. But when executing the code it seems like it is referencing itself as lib in python. So when using the code itself it does not know "import telegram". 

I would recommend importing the modules themselves rather than as part of the library.

**Comment by tsnoam** [comment]
@Pixdigit if i understand properly you're suggesting a different directory structure of the code.
Can you be so kind and also provide an example of how you suggest to change the structure?

**Comment by Pixdigit** [comment]
@tsnoam No. I mean that if I want to deliver my application to my customers they should not need to install it. But there is a problem if I import the code. It relies on that python-telegram-bot is installed so it can simply `import telegram` instead of `from . import __init__ as telegram`

**Comment by taemery** [comment]
This code is meant to be used as a package. If you want to use it as intended then just import it. Python's design is to be modular, you're trying to go against that grain.

**Comment by tsnoam** [comment]
Hi @Pixdigit,
Sorry for the latency in response. Had it very busy lately, I hope to be more responsive now.
1. Unless I failed to understand your intentions, I think that @taemery  comment is very accurate (and I probably couldn't put it any better).
2. If indeed I've failed in understanding your requirement, I think the best way would be to send a PR.

So, what do you say?

**Comment by jh0ker** [comment]
Please also make sure that whatever you are trying to do, you adhere to the LGPL 3 license

**Comment by Pixdigit** [comment]
@tsnoam  @taemery I do not know if you mean what I mean.(Btw what is a PR? Am I right if I guess Pull Request?). My goal is to deliver a software which runs as it. So no need to install anything (except python). However this API is designed only to be usable when referenced as installed library. So when I download and import the source code it will raise an ImportError because there is no such library as "telegram" because it is referencing itself.
I do not get how this interferes with modularity. And if so why is this library designed to only be usable as package? Is not that against modularity too?
@jh0ker Always.

**Comment by tsnoam** [comment]
@Pixdigit
 
1. The "normal" way of using a python package is by installing it into your `site-packages` dir (there is one for the system & one for the user). You can usually use `pip` for that. (or in Linux, many python packages can already be acquired using the distro's packaging system)
2. You can also install into the `site-packages` from the sources, using `setup.py`.
3. If both of the above are not suitable for your needs, and you just want to work with the sources directly from git, then just dump them in some directory and set your `PYTHON_PATH` environment variable to include the sources directory, (or similary, from inside the python code, modify `sys.path`)

Does this answer your question?

**Comment by Pixdigit** [comment]
@tsnoam Yes it does. But I still wonder what the use of that is (in terms of "Zen of Python").
