### ISSUE TITLE
[BUG] TypeError: Object of type ellipsis is not JSON serializable

### ISSUE THREAD

**Issue by manel00** [python-telegram-bot/python-telegram-bot#1810]
Reproducing the tutorial part of https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#build-a-menu-with-buttons it gives the error. I'm using Python 3.8 and i've tried to make a list and also using list comprehension and doesnt work at all.

Thank you so much

**Comment by jh0ker** [comment]
Please fill out the issue template.
