### ISSUE TITLE
Return message ID from channel

### ISSUE THREAD

**Issue by bigildar** [python-telegram-bot/python-telegram-bot#1812]
Telegram bot sends a message to the channel.
How can I return the message ID from the channel?
Or how to return the ID of the last message in the channel?

**Comment by Eldinnie** [comment]
all send methods return the sent message.

**Comment by bigildar** [comment]
I do not write well in English, maybe I did not speak correctly at the beginning. I will try more specifically.
I need to send a message to the channel and immediately record in the database the data about this message and its ID. So far, I can only get the message ID of the internal chat with the bot

**Comment by bigildar** [comment]
> all send methods return the sent message.

I do not write well in English, maybe I did not speak correctly at the beginning. I will try more specifically.
I need to send a message to the channel and immediately record in the database the data about this message and its ID. So far, I can only get the message ID of the internal chat with the bot

**Comment by jh0ker** [comment]
@bigildar Code example:

```python
message_information = bot.send_message(...)
# or
message_information = update.message.reply_text(...)
```

This works for most API calls.

**Comment by bigildar** [comment]
I very 

> @bigildar Code example:
> 
> ```python
> message_information = bot.send_message(...)
> # or
> message_information = update.message.reply_text(...)
> ```
> 
> This works for most API calls.


Thanks. I'm probably very stupid. I did not see the obvious.
