### ISSUE TITLE
Need help with some basic understanding of how to use the Handler

### ISSUE THREAD

**Issue by m0neytree** [python-telegram-bot/python-telegram-bot#1815]
Hi,

I tried to follow the example to create my own Chatbot. However I not quite understand how things works.

After issuing /start, I would like to give the user few options. However, it looks like the commandhandler isnt working perfectly.

My code:
HELP: [MessageHandler(Filters.text, help), CommandHandler('help', help)]

My guess is that MessageHandler is filtering out the keyword "help", and then bring it over to CommandHandler to issue "/help". However in my option I created "Help", I tried replacing the text in the reply_keyboard as "help" instead yet it still doesnt get into the Help section? Can anyone explain how the line works?

**Comment by Bibo-Joshi** [comment]
Hi. Your problem description unfortunately is not very precise.

Im guessing that you're trying to use a `ConversationHandler` where the entry point is a `CommandHandler('start', some_callback)`? How is the user supposed to select the option "help" after that? With a `ReplyKeyboardMarkup`? If you would provide a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example), it would be a lot easier to help you.

Also, `MessageHandler` doesn't pass anything over to anyone. If you haven't fully understood how handlers work, please read our [wiki ](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-–-Your-first-Bot) and the [docs](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.messagehandler.html).
