### ISSUE TITLE
[QUESTION] No module named 'telegram' in a heroku worker

### ISSUE THREAD

**Issue by Javain** [python-telegram-bot/python-telegram-bot#1819]
### Issue I am facing
I'm trying to make my own bot work in a heroku app but I face a `No module named 'telegram'` error when executing in a heroku worker. I had no such problem in my local before.

### Traceback to the issue
```
20:03:26 worker.1   |  Traceback (most recent call last):
20:03:26 worker.1   |    File "main.py", line 1, in <module>
20:03:26 worker.1   |      from bot import TelegramBot
20:03:26 worker.1   |    File "***\bot.py", line 1, in <module>
20:03:26 worker.1   |      from telegram.ext import CommandHandler, Updater, MessageHandler, Filters
20:03:26 worker.1   |  ModuleNotFoundError: No module named 'telegram'
[DONE] Killing all processes with signal  SIGINT
20:03:26 worker.1   Exited with exit code null
```

### Related part of your code
```python
from telegram.ext import CommandHandler, Updater, MessageHandler, Filters
```
Dependency line from requirements.txt:
> python-telegram-bot==12.4.2

**Comment by Bibo-Joshi** [comment]
Did you install ptb, e.g. via `pip install python-telegram-bot` or `pip install -r requirements.txt`? If yes, please provide a minimal working example.

**Comment by Javain** [comment]
requirements.txt:
`python-telegram-bot==12.4.2`

main.py:
`from telegram.ext import CommandHandler, Updater, MessageHandler, Filters`

Finally, the commands used:
`pip install -r requirements.txt`
`python main.py`

Installation appears to work fine since heroku console gives:
`Requirement already satisfied: python-telegram-bot==12.4.2 in ./.heroku/python/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (12.4.2)`

**Comment by tsnoam** [comment]
@Javain Do you happen to have a file called <code>telegram.py</code> or a directory called <code>telegram</code> in your project?

If not, you should check your runtime python path.
Try to print <code>sys.path</code> when you get the error.

**Comment by tsnoam** [comment]
@Javain To be clear, a file or directory under these names may cause import errors because of the name collisions.

**Comment by Javain** [comment]
@tsnoam no such file or directory exists in the project. I'll try to provide `sys.path` as soon as I can.

**Comment by Eldinnie** [comment]
@Javain can you please show the build log from Heroku&gt;

**Comment by Javain** [comment]
It appears the problem has been resolved on its own and that part of code is passing now. Don't know why, but it's working, so I'm closing the issue. If it shall happen again, I'll provide everything you're asking me from the start.
