### ISSUE TITLE
telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

### ISSUE THREAD

**Issue by manel00** [python-telegram-bot/python-telegram-bot#1821]
`2020-03-09 09:26:20,694 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2020-03-09 09:26:20,695 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"`

Hi, i'd like to know how to stop a function in telegram without breaking it, because after doing a updater.stop() or updater.idle(), also when i want to stop a function because i don't want to finish a "conversationHandler" with the code i mentioned, it doesnt work and i have to restart the telegram bot, there is some way to deal with it? Just i want to get out from a function and keep it working without getting the error from above

**Comment by Bibo-Joshi** [comment]
@manel00 Hi. Please fill out the entire issue template.

What do you mean by &quot;function&quot;? A callback function of a handler? If you want to end a conversation, you may wanna have a look at the &quot;fallbacks&quot; argument of ConversationHandler (see our docs at read-the-docs).

**Comment by manel00** [comment]
What would be the best practice? To put on fallbacks or to put as a CommandHandler inside one state? cannot understand it?

**Comment by Bibo-Joshi** [comment]
If we're just talking about how to properly end a conversation: Using a fallback handler or using a CommandHandler for e.g. `/cancel`, is a decision regarding the user experience and purely up to you.

Still, I don't see, why you would have to restart the bot or what the posted error message has to do with your question. Regarding the error message: just do as it says: "make sure that only one bot instance is running"

**Comment by AmiraliKhatib2000** [comment]
ERROR:telegram.ext.updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

what should I do?

**Comment by AmiraliKhatib2000** [comment]
from telegram.ext import Updater

updater = Updater(token='token', use_context=True)
dispatcher = updater.dispatcher

from telegram.ext import CommandHandler

def caps(update, context):
    text_caps = ' '.join(context.args).upper()
    context.bot.send_message(chat_id=update.effective_chat.id, text=text_caps)

caps_handler = CommandHandler('caps', caps)
dispatcher.add_handler(caps_handler)

updater.start_polling()
**********************************************************************************************
ERROR:telegram.ext.updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

what should I do?
