### ISSUE TITLE
[BUG] context.user_data saved in a conversation is lost upon timeout.

### ISSUE THREAD

**Issue by bsashidh** [python-telegram-bot/python-telegram-bot#1823]
### Steps to reproduce
1. In the entry function of a conversation save some data in context.user_data

2. Set the conversation_timeout of the conversation to some value other than 0. I used it as 10

3. In the "ConversationHandler.TIMEOUT" state define a callback handler and in that try reading the user_data from context.

### Expected behaviour
Should be able to fetch the saved data using context.user_data.get method.

### Actual behaviour
I get the following error: AttributeError: 'NoneType' object has no attribute 'get'. In all other states I am able to read the user_data except in the TIMEOUT state.

### Configuration
**Operating System:**
Windows 10

**Version of Python, python-telegram-bot & dependencies:**
Version of Python 3.7.5
Version of python-telegram-bot 12.4.2

**Comment by Bibo-Joshi** [comment]
Hi thanks for the catch! Haven't tested it myself, but looking at the code, your description makes sense. I think, we just need to call `CallbackContext.from_update()` in this `__init__` function over [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/28ded6718ecaf2541b2dd25a14bad0a7c3068c7b/telegram/ext/conversationhandler.py#L32).

As a workaround: If I see correctly, the `context` you are getting in the timeout handler should have the attributes `update` and `dispatcher`. You can then use 
```python
context.dispatcher.chat_data[context.update.chat.id]
context.dispatcher.user_data[context.update.from_user.id]
```
to access the data (if the update has a chat/from_user, that is)

**Comment by bsashidh** [comment]
Your work around solves my problem for now. Thank you very much.
