### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by vovean** [python-telegram-bot/python-telegram-bot#1828]
#### Is your feature request related to a problem? Please describe.
I believe that testing is essential for any development and for bots in particular. However, I haven't found anything about it in the docs. The code that is in the `tests` folder suggests to use a separate bot specifically for testing which seems an overkill to me.
So, I think that creating a built-in testing environment is a great feature to implement

#### Describe the solution you'd like
Ok, I'm not very good at creating such big components as testing environments, but I think I can make some points:

- I must be able to mock Telegram server, so I can return my own custom responses

- I must be able to mock Updater and Dispatcher, so I can test Handlers without actually setting up a Telegram server.

Obviously, there are a lot more features can be added to the list, but these I think are the basics

#### Describe alternatives you've considered
Well, I don't think there is any alternative for a built-in testing environment

#### Additional context
There already is a library for testing: https://github.com/Eldinnie/ptbtest , however, it looks abandoned, so it isn't really an option to use. Nevertheless, it can be used to create a built-in testing environment on its base.

**Comment by Bibo-Joshi** [comment]
Hi. After some internal discussion, the consensus is not to pursue this for several reasons:

1. We just don't have the capacity
2. PTB itself is tested to properly work with the Telegram API (which oftentimes is quite combersome)
3. You can test your own code by using monkeypatch to mock the send methods of the bot class

That said, nobody will stop you from forking ptbtest :wink:

**Comment by Poolitzer** [comment]
@Bibo-Joshi And I will also chime in and say ptbtest has a PR bringing it up to V11 apparently, so you might not have to do that much to get it up to date :)
