### ISSUE TITLE
Tests failure: pytest.mark.coverage

### ISSUE THREAD

**Issue by stkw0** [python-telegram-bot/python-telegram-bot#1830]
Hi. I was trying to run the tests but seems it can not find the pytest.mark.nocoverage thing. And I was not capable of finding where is it defined or which library provides that functionality. Is this a bug?

```
tests/test_meta.py:29: in <module>
    @pytest.mark.nocoverage
/usr/lib64/python3.6/site-packages/_pytest/mark/structures.py:327: in __getattr__
    PytestUnknownMarkWarning,
E   pytest.PytestUnknownMarkWarning: Unknown pytest.mark.nocoverage - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
```

**Comment by Poolitzer** [comment]
@stkw0 Hey. We don&#x27;t face this issue on our end. Could you please tell us you python and pytest version, and verify that you installed requirements-dev.txt?

**Comment by stkw0** [comment]
Following the setting-up procedure of the wiki seems that the problem disappeared. Seems I was using the pytest version 5.3.5 (from the system) instead of the version 4.2.0 from the requirements-dev.txt. But I'm still getting another error when executing "make test"
```ImportError while loading conftest '/python-telegram-bot/tests/conftest.py'.
tests/conftest.py:30: in <module>
    from telegram import (Bot, Message, User, Chat, MessageEntity, Update,
telegram/__init__.py:104: in <module>
    from .bot import Bot
telegram/bot.py:45: in <module>
    from telegram.utils.request import Request
telegram/utils/request.py:42: in <module>
    import urllib3
E   ModuleNotFoundError: No module named 'urllib3'
```

once I install it manually I get another error.

```
ImportError while importing test module '/python-telegram-bot/tests/test_official.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_official.py:25: in <module>
    from telegram.vendor.ptb_urllib3 import urllib3
E   ImportError: cannot import name 'urllib3' from 'telegram.vendor.ptb_urllib3' (unknown location)
```

**Comment by tsnoam** [comment]
@stkw0 You need to clone the git submodules. It&#x27;s all there in the readme.

**Comment by stkw0** [comment]
True, my mistake. Sorry :p
