### ISSUE TITLE
Issue sending email with variable + hyperlink

### ISSUE THREAD

**Issue by miclopez3** [python-telegram-bot/python-telegram-bot#1831]
Hi all!

I have a little code in api telegram bot to send me messages like this:
`def redirector(update, context)
     update.message.reply_text('Hi {}. '.format(update.message.from_user.username) + 'Go [here] 
     (google.com)", parse_mode="MARKDOWN") `

The problem is:

- If I remove the hyperlink, all works fine
- Il I remove the variable (format(update....)), all works fine.
-If I try to send the message with both items (variable + hyperlink), no error from python but my bot doesn't answer the message

What I am doing wrong?

**Comment by Bibo-Joshi** [comment]
Hi. I notice that you are using two different quotes in the link part (' and "). Also I'm not sure, if Markdown can handle the whitespace between `[here]` and `(google.com)`. If you have further questions, please fill out the entire issue template, especially providing the traceback of your error. The template is there for a reason ;)

**Comment by miclopez3** [comment]
Hi,
Sorry for ' and " and the space into the hyperlink. (only typing error :))
My code is
`def redirector(update, context) update.message.reply_text('Hi {}. '.format(update.message.from_user.username) + 'Go [here](google.com)', parse_mode="MARKDOWN")`

I didn't put any error because Python didn't give any error. I can execute correctly the file. The problem is that the bot receives de commandhandler but he doesn't answer with both items (variable + link) on the same message and I don't understand why :(

**Comment by Bibo-Joshi** [comment]
Okay. Have you

* tried building the string before passing it to `update.message.reply_text`
* enabled logging and added an error handler?

**Comment by miclopez3** [comment]
Yes, I tried to build the string before, but same issue.
For logging, I think that I put it correctly and I found and Exception, but I don't know what it refers to.

raise BadRequest(message)
BadRequest: Can't parse entities: can't find end of the entity starting at byte offset 7.

What does this message mean?

**Comment by Bibo-Joshi** [comment]
It means that Telegram has a problem parsing the markdown entities. Are you testing with a username containing an underscore? That would lead to Telegram trying to find an italics entity. You should probably use `telegram.utils.helpers.escape_markdown` on the username.

**Comment by miclopez3** [comment]
Yes! The username has a markdown.
Looking this issue, I tried changing the markdown format to HTML format. And it works fine!
Thanks!
Today I learned to use Logging (I tried after your reply :D) and to use markdown + HTML format.
Profitable day!

**Comment by Poolitzer** [comment]
@miclopez3 That is only a temporary fix, until someone incorporates html tags in their username (may not possible yet, but just wait for the future). I would highly suggest always escape users input if you use markdown. Our utils helper for telegrams own Markdown, and html.escape for the html one.

**Comment by miclopez3** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/issues/1831#issuecomment-598238726
You are probably right... I will think about at to avoid possible issues in the future.
Thanks!
