### ISSUE TITLE
Hebrew not working as keyboard button text

### ISSUE THREAD

**Issue by ddm4313** [python-telegram-bot/python-telegram-bot#1838]
![Capture](https://user-images.githubusercontent.com/53798547/77147754-4e503100-6a8e-11ea-94de-2f961e3018aa.PNG)
Now, in caption it works, but as keyboard button text, no, it does not.
Anyway to fix?

`
            keyboard = [[InlineKeyboardButton("בדיקה", callback_data="", ),
                         InlineKeyboardButton(buttons['BUTTON_2']['TEXT'], callback_data=buttons['BUTTON_2']['CALLBACK_DATA'])],
                        [InlineKeyboardButton(buttons['BUTTON_3']['TEXT'], callback_data=buttons['BUTTON_1']['CALLBACK_DATA'])]]
            menu_markup = InlineKeyboardMarkup(keyboard)
`

**Comment by Bibo-Joshi** [comment]
Hi. I can't reproduce the problem in Win10, py3.8, PTB master. Please fill out the entire issue template (it's there for a reason!) and make sure that the issue really is with PTB.
