### ISSUE TITLE
get AttributeError: 'Update' object has no attribute 'sendPhoto' when i try to send photo with bot

### ISSUE THREAD

**Issue by Sn0wl3r0ker** [python-telegram-bot/python-telegram-bot#1839]
i get AttributeError: 'Update' object has no attribute 'sendPhoto' when i try to send photo with bot
Here's my code:
`def ptt_beauty(bot, update):
    bot.sendPhoto(chat_id=update.message.chat_id, photo="https://i.imgur.com/AD3MbBi.jpg")`
And got these error here:
`  File "/Users/sn0wl3r0ker/Documents/python-telegram-bot/telegram/ext/dispatcher.py", line 390, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/sn0wl3r0ker/Documents/python-telegram-bot/telegram/ext/handler.py", line 117, in handle_update
    return self.callback(update, context)
  File "/Users/sn0wl3r0ker/Documents/python-telegram-bot/bot.py", line 36, in ptt_beauty
    bot.sendPhoto(chat_id=update.message.chat_id, photo="https://i.imgur.com/AD3MbBi.jpg")
AttributeError: 'Update' object has no attribute 'sendPhoto'`
really need some helps on this :(

**Comment by Poolitzer** [comment]
@Sn0wl3r0ker Hey, you are using V12 code with an older version of the library or without setting context to true in the updater

**Comment by Sn0wl3r0ker** [comment]
> @Sn0wl3r0ker Hey, you are using V12 code with an older version of the library or without setting context to true in the updater

But i use git clone on the newest github version, and i did set use_context=True in the updater = Updater('TOKEN', use_context=True)
so...what do u suggest me to do? Sorry i'm still a rookie...

**Comment by tsnoam** [comment]
@Sn0wl3r0ker 1. Update object has no send* methods.
2. ptb doesn&#x27;t use camelCase naming conventions, so you&#x27;re probably looking for a method named send_photo.
3. Bot object has a method named send_photo.

**Comment by tsnoam** [comment]
@Sn0wl3r0ker Here&#x27;s a link to the Bot documentation:
https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot

**Comment by Sn0wl3r0ker** [comment]
> @Sn0wl3r0ker Here's a link to the Bot documentation:
> https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot
Hey dude... i change True into False and it start working...it really confuse me...what's the different between use_context's True and False.
but if False:
`def hello(update, context):
    update.message.reply_text(
        'hello, {}'.format(update.message.from_user.first_name))`
This will not work...it has to change like:
`def hello(bot, update):` or
`def hello(context, update):`
it's so weird... or am i on the right version?...

**Comment by Bibo-Joshi** [comment]
@Sn0wl3r0ker You should have gotten some warnings on starting the Bot after switching use_context to False. They are there for a reason 😉. Read them. They include a link. Click it. (Spoiler: it leads you <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-12.0#context-based-callbacks">here</a>)

**Comment by Sn0wl3r0ker** [comment]
> @Sn0wl3r0ker You should have gotten some warnings on starting the Bot after switching use_context to False. They are there for a reason 😉. Read them. They include a link. Click it. (Spoiler: it leads you [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-12.0#context-based-callbacks))

alright! thanks mate!
