### ISSUE TITLE
[FEATURE] Poll quiz mode support

### ISSUE THREAD

**Issue by ruslankrivoshein** [python-telegram-bot/python-telegram-bot#1842]
There is here now not support of quiz mode of poll.
I suppose, it needs to add additional params to [#L3492](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/bot.py#L3492) and cover with tests, of course. I.e.:

```
data = {
    'chat_id': chat_id,
    'question': question,
    'options': options,
    'type': kwargs.get('type', 'regular'),
    'correct_option_id': kwargs.get('correct_option_id', 0),
}
```

**Comment by Poolitzer** [comment]
@ruslankrivoshein Hey. That is a 4.6 feature and is already implemented in the 4.6 branch.

You can install it with pip: <code>pip install -U https://github.com/python-telegram-bot/python-telegram-bot/archive/4.6-update.zip</code>

Check out the poll example in said branch to see how the new polls work.
