### ISSUE TITLE
[BUG] ConversationHandler mixes callbacks (under heavy load?)

### ISSUE THREAD

**Issue by toobaz** [python-telegram-bot/python-telegram-bot#1843]
### Steps to reproduce

My bot has several steps defined of this kind

``` python3
def step(number):
    def callback(update, context):
        query = update.callback_query
        value = query.data
        logger.info("%s - %s", number, value)
        bot = context.bot
        keyboard = [
            [InlineKeyboardButton(str(i), callback_data=f'q{number}a{i}')
             for i in range(1, 8)]
        ]
        reply_markup = InlineKeyboardMarkup(keyboard)
        bot.edit_message_text(
            chat_id=query.message.chat_id,
            message_id=query.message.message_id,
            text="Some text",
            reply_markup=reply_markup
        )
    return number + 1
```

I then build the ``states`` argument to the ``ConversationHandler`` as

``` python3
    dp = updater.dispatcher

    states = {}
    
    for q in s_questions:
        states[q] = [CallbackQueryHandler(step(q), pattern='.*')]
    conv_handler = ConversationHandler(
        entry_points=[CommandHandler('start', start)],
        states=states,
        fallbacks=[CommandHandler('start', start)]
    )

    dp.add_handler(conv_handler)
    dp.add_error_handler(error)

    updater.start_polling()
    updater.idle()

```

Notice that the ``callback_data`` identifies the step (because it has the step number in it). So in my logs I should always observe messages like ``4 - q3a4``, ``2 - q1a4``... with the first number which is one more than the second. And indeed, this is what I observe when I test my bot. But then, under heavy load (I had some hundreds of users interacting at the same time), I started to observe a lot of stuff like ``3 - q1a5``, which shouldn't have happened.

I'm unable to reproduce reliably with few users unfortunately.

### Expected behaviour

Each state should always receive a callback from the previous state.

### Actual behaviour

States callbacks are mixed.

### Configuration
**Operating System:** debian Linux, buster

**Version of Python, python-telegram-bot & dependencies:** 
```
python-telegram-bot 12.4.2 (v12.4.2-4-g8d6970a)
certifi 2019.11.28
future 0.16.0
Python 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
```

**Comment by MattRighetti** [comment]
Had this kind of problem too yesterday

**Comment by Bibo-Joshi** [comment]
Hi. I just see that we never got back to you. Does the problem still persist?

**Comment by Bibo-Joshi** [comment]
Closing due to lack of feedback from OP. If you encounter this problem again, feel free to comment/open a new issue :)

**Comment by toobaz** [comment]
> Hi. I just see that we never got back to you. Does the problem still persist?

Oops... me neither. Unfortunately I'm not using that bot anymore.
