### ISSUE TITLE
Handle End of Conversation

### ISSUE THREAD

**Issue by Mifulapirus** [python-telegram-bot/python-telegram-bot#1846]
### Issue I am facing
Is there a way to catch the end of a conversation so I can inform the user that it has ended right before finishing it?

For example, when using a `ConversationHandler` and setting `conversation_timeout = 30.0`, I'd like to send a message back informing of the end of such conversation.

Thanks!

**Comment by Bibo-Joshi** [comment]
Hi. For the timeout, use the [`TIMEOUT` state](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.conversationhandler.html#telegram.ext.ConversationHandler.TIMEOUT), see the last paragraph of the handler description for details. In any other case, just send a message before you callback returns [`END`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.conversationhandler.html#telegram.ext.ConversationHandler.END). That should do the trick.

**Comment by Mifulapirus** [comment]
Hey @Bibo-Joshi thanks for the hint. Unfortunately I can't figure out how to use the information on that last paragraph and I can't find any examples about it.
Do you know of any resource with s bit more explicit information?

Thank you for your help anyway!

**Comment by Bibo-Joshi** [comment]
well, in the setup of a ConversationHandle, you need to define handlers for each state. Borrowing from our example [conversationhandler.py](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/conversationbot.py), this e.g. looks like this:

```python
states={
            GENDER: [MessageHandler(Filters.regex('^(Boy|Girl|Other)$'), gender)],

            PHOTO: [MessageHandler(Filters.photo, photo),
                    CommandHandler('skip', skip_photo)],

            LOCATION: [MessageHandler(Filters.location, location),
                       CommandHandler('skip', skip_location)],

            BIO: [MessageHandler(Filters.text, bio)]
        },
```

Now, if you want to define handlers to be called in the timeout state, you just append them like this:

```python
states={
            ...
            BIO: [MessageHandler(Filters.text, bio)],
            ConversationHandler.TIMEOUT: [MessageHandler(Filters.all, timeout_callback)],
        },
```

Note, that the update passed to those handlers  in the timeout state will be the last received update, as stated in the docs for the [`conversation_timeout`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.conversationhandler.html#telegram.ext.ConversationHandler.conversation_timeout) parameter. Also, the callback context passed to the timeout handlers currently doesn't contain the `user/chat_data` set in the last valid callback, see #1823 and #1826 for  more details.

**Comment by Mifulapirus** [comment]
Thank you so much, @Bibo-Joshi!
I did not realize it was that obvious :/
Thanks for your help and time!!!
