### ISSUE TITLE
[QUESTION] Callstack on error

### ISSUE THREAD

**Issue by rspadim** [python-telegram-bot/python-telegram-bot#1852]
how could i get the line number and file name of an error?

for example:

```python
def bot_handler(update, context):
   raise Exception("error")

def bot_error(update,context):
   print("here i want know from where the error exception come, line and file name")

...
dp.add_handler(CommandHandler("handler", bot_handler))
dp.add_error_handler(bot_error)
...
```

**Comment by Poolitzer** [comment]
You would need to get the latest traceback.

Check out this [error handler snippet](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#an-good-error-handler) an amazing coder (me) put in the wiki for an example :)
