### ISSUE TITLE
[QUESTION] How to "escape" markdown text

### ISSUE THREAD

**Issue by rspadim** [python-telegram-bot/python-telegram-bot#1857]
hi, i'm with a database that my bot query
one field in this database have a value like "_hello_"
i'm using markdown at reply_text and the "_" convert to italic

there's something that "escape" markdown text? like html escapes?

**Comment by Poolitzer** [comment]
@rspadim <b>utils.helpers.escape_markdown</b>
<i>python-telegram-bot</i> documentation for this function:
<a href="https://python-telegram-bot.readthedocs.io/en/stable/telegram.utils.helpers.html#telegram.utils.helpers.escape_markdown">telegram.utils.helpers.escape_markdown</a>

**Comment by rspadim** [comment]
Thanks @Poolitzer !!!!
