### ISSUE TITLE
[FEATURE] Infere bot commands from CommandHandler and set them automatically

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#1859]
#### Is your feature request related to a problem? Please describe.
Even with API 4.7s new `Bot.set_my_commands`, setting commands will be tiresome

#### Describe the solution you'd like
* Add `description` attribute to `CommandHandler`
* Add `Disptacher.set_commands(update=False, delete=False, add=True)` that
  * gets the bots command from the registered `CommandHandlers`
  * Checks that they are valid for `BotCommand` and `set_my_commands`
  * gets current commands
  * sets new commands with options:
    * `update`: If `False` don't change a command if already set
    * `delete`: If `True`, delete commands that were set but currently don't have a corresponding handler
    * `add`: If `False` and currently commands are set, doesn't add new ones

#### Describe alternatives you've considered
Tiresome handwork

#### Additional context
`Bot.set_my_commands` is very new, so maybe wait till the next API update to make sure Telegram doesn't change the methods directly

**Comment by n5y** [comment]
I imagine situation where user doesn't want some of the commands to appear in command autocompletion list is quite common.

**Comment by Bibo-Joshi** [comment]
I'd try to add as few new parameters to `CommandHandler` as possible. Another solution would be to skip commands without description in `Disptacher.set_commands` (or add a parameter for that).

**Comment by Bibo-Joshi** [comment]
Closing for the reasons mentioned in #1911
