### ISSUE TITLE
Adding internal information module

### ISSUE THREAD

**Issue by Pixdigit** [python-telegram-bot/python-telegram-bot#186]
I had the problem that users installed a wrong a library since this module's name is only telegram.
To be able to distinguish different programs and/or versions a module with information about version and complete name can be introduced.

Greetings Pixdigit.

(Priority: Low)

**Comment by jh0ker** [comment]
There is some information you can access like this:

    >>> import telegram
    >>> print(telegram.__author__)
    devs@python-telegram-bot.org
    >>> print(telegram.__version__)
    3.2.0

**Comment by Pixdigit** [comment]
Did not see that in the documentation, that is why I asked.

**Comment by taemery** [comment]
With readthedocs is there a way to document global variables such as telegram.__author__ ?

**Comment by tsnoam** [comment]
`__version__` & `__author__` are well known python conventions. There is no need to explicitly document them.

**Comment by Pixdigit** [comment]
@tsnoam In my experience (To be fair its only three years) I never stumbled upon a library that uses this convention. Even python itself does not have these. It may however be that some libraries use these convention alongside other possibilities. After s short test json was the only library that has this out of [sys, tkinter, json, pygame, ConfigParser, PIL] and I could probably go on.
But I agree that that should be best practice to do, but essentially nearly nobody does this.

**Comment by tsnoam** [comment]
@Pixdigit 
It is true that these are not official python conventions. However, they are widely spread.
Furthermore, `__version__` is mentioned by PEP-008.
In any case, after discussing the issue with the other maintainers, we all believe that this convention is good enough for us and there is no reason to do anything special about it.
