### ISSUE TITLE
[BUG] Quiz poll doesn't work

### ISSUE THREAD

**Issue by AyraHikari** [python-telegram-bot/python-telegram-bot#1860]
### Steps to reproduce
message = update.effective_message
context.bot.send_poll(message.chat.id, question="test poll", options=["1", "2"], type="quiz", correct_option_id=1)

### Expected behaviour
It should send as Vote Poll instead of Quiz Poll
This API is work and send as Quiz Poll
`requests.post("https://api.telegram.org/bot"+TOKEN+"/sendPoll", json={"chat_id": chat_id, "question": "Test", "options": ["True","False"], "type": "quiz", "correct_option_id": 1}).json()`

### Actual behaviour
It send as Vote Poll instead of Quiz Poll

### Configuration
**Operating System:**
Linux Ubuntu 16.04

**Version of Python, python-telegram-bot & dependencies:**
- python 3.8
- python-telegram-bot 12.5.1

### Logs
No logs are needed

**Comment by Bibo-Joshi** [comment]
Can't reproduce. Can you try using `type=Poll.QUIZ` and maybe post logs on debug level?

Also, you can shorten your code by using `Message.reply_poll`

**Comment by AyraHikari** [comment]
Yeah, here is debug code
```
2020-03-31 05:41:31,855 - telegram.ext.dispatcher - DEBUG - Processing Update: {'update_id': 90229178, 'message': {'message_id': 1645097, 'date
': 1585608091, 'chat': {'id': 388576209, 'type': 'private', 'first_name': 'Ayra', 'last_name': 'Hikari'}, 'text': '/emil message = update.effec
tive_message\ncontext.bot.send_poll(message.chat.id, question="test poll", options=["1", "2"], type="quiz", correct_option_id=1)', 'entities':
[{'type': 'bot_command', 'offset': 0, 'length': 5}, {'type': 'url', 'offset': 63, 'length': 15}], 'caption_entities': [], 'photo': [], 'new_cha
t_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_
created': False, 'from': {'id': 388576209, 'first_name': 'Ayra', 'is_bot': False, 'last_name': 'Hikari', 'language_code': 'en'}}}
2020-03-31 05:41:31,856 - telegram.bot - DEBUG - Entering: send_poll
020-03-31 05:41:32,150 - telegram.bot - DEBUG - {'message_id': 1645098, 'date': 1585608091, 'chat': {'id': 388576209, 'type': 'private', 'first_name': 'Ayra', 'last_name': 'Hikari'}, 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'poll': {'id': '6057850405193252882', 'question': 'test poll', 'options': [{'text': '1', 'voter_count': 0}, {'text': '2', 'voter_count': 0}], 'is_closed': False}, 'from': {'id': 692882995, 'first_name': 'Emilia', 'is_bot': True, 'username': 'EmiliaHikariBot'}}
2020-03-31 05:41:32,150 - telegram.bot - DEBUG - Exiting: send_poll
```

**Comment by AyraHikari** [comment]
Oh wait, i just solved it.
I was in 12.4.1 (idk pip -U says already up to date), then installing 12.5.1 by typing `python3.8 -m pip install -U python-telegram-bot` is solved my issue.
Sorry
