### ISSUE TITLE
How to break any conversation when a new valid command is entered?

### ISSUE THREAD

**Issue by floatingpurr** [python-telegram-bot/python-telegram-bot#1862]
I'm using `python-telegram-bot==12.4.2`. What I want to achieve is implementing a couple of conversations along with a group of classic  `CommandHandler` (i.e., stateless commands) in the same bot. 

In particular, if a user is involved in an active conversation and she enters another valid command, the active conversation should be ended and the new command must take the control of the conversation, whether it is a stateless command, a new conversation or the same conversation restarted from the beginning.

This is my simple experiment:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import logging

from telegram import (ReplyKeyboardMarkup, ReplyKeyboardRemove)
from telegram.ext import (Updater, CommandHandler, MessageHandler, Filters,
                          ConversationHandler)

# Enable logging
logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    level=logging.INFO)

logger = logging.getLogger(__name__)


# Conversation 1
FOO = 0

# Conversation 2
BAR = 0

def start(update, context):
    """ Just to start """
    update.message.reply_text('Hi! This is an example')

def classic(update, context):
    """ I'm classic stuff """
    update.message.reply_text('Take me out from any conversation and print this!')

def start_conv_1(update, context):
    """ Start conversation #1 """
    update.message.reply_text('Conversation 1 has just started')
    return FOO

def start_conv_2(update, context):
    """ Start conversation #2 """
    update.message.reply_text('Conversation 2 has just started, type /bar to continue')
    return BAR

def handle_1(update, context):
    """ Handle conversation #1 """
    update.message.reply_text(f'User entered {update.message.text}')
    return ConversationHandler.END

def handle_2(update, context):
    """ Handle conversation #2 """
    update.message.reply_text('Thank you!')
    return ConversationHandler.END

def cancel(update, context):
    """ Cancel current conversation """
    update.message.reply_text('Conversation ended')
    return ConversationHandler.END


def main():
    updater = Updater("TOKEN", use_context=True)

    # Get the dispatcher to register handlers
    dp = updater.dispatcher

    # conversation 1
    conv_1_handler = ConversationHandler(
        entry_points=[CommandHandler('start_conv_1', start_conv_1)],

        states={
            # echo user input
            FOO: [MessageHandler(Filters.text, handle_1)],
        },

        fallbacks=[MessageHandler(Filters.command, cancel)]
    )

    dp.add_handler(conv_1_handler)

    # conversation 2
    conv_2_handler = ConversationHandler(
        entry_points=[CommandHandler('start_conv_2', start_conv_2)],

        states={
            BAR: [CommandHandler('bar', handle_2)],
        },

        fallbacks=[MessageHandler(Filters.command, cancel)]
    )

    dp.add_handler(conv_2_handler)

    # classic commands
    dp.add_handler(CommandHandler('start', start))
    dp.add_handler(CommandHandler('classic', classic))


    # Start the Bot
    updater.start_polling()
    updater.idle()


if __name__ == '__main__':
    main()
```

I have 3 problems with that approach.

1. During conversation 1 (the one that echoes user input) any entered command is echoed as well and the fallback is never triggered for example:

> u: /start_conv_1
> b: Conversation 1 has just started
> u: /classic
> b: User entered /classic

_The last line shouldn't be displayed. The bot should display 'Conversation ended' and then 'Take me out from any conversation and print this!' instead_

2. During conversation 2, the fallback ends the conversation but then the new command (i.e., `/classic` is not triggered

> u: /start_conv_2
> b:Conversation 2 has just started, type /bar to continue
> u: /classic
> b: Conversation ended

_Here the bot simply does not display 'Take me out from any conversation and print this!'_

3. If the user restarts a conversation while she is in the middle of it (e.g., typing `/start_conv_2` and `/start_conv_2` again), then the conversation ends without restarting.

I tried to switch the calls to `add_handler`(i.e., adding classic commands before the conversations) without any success. In this case, problem 1 is the same, problem 2 changes a little bit:

> u: /start_conv_2
> b:Conversation 2 has just started, type /bar to continue
> u: /classic
> b: Take me out from any conversation and print this!

but then if I type `/bar`, I get `Thank you!`, therefore I guess that with this configuration the fallback is not called at all also in this case and the conversation remains active.

I believe that problem 1 is simply related to the `Filters.text` that is too broad. Problems 2 and 3 could be related to the way handlers work.

How can I fix? Thanks!

**Comment by Bibo-Joshi** [comment]
Hi. I didn't read all the details, but my guess it, that putting the command handlers in different groups should help, as only one handler per group will be executed. Please also have a look at #1640 and #1447. If that doesn't help, please ping me here.

**Comment by floatingpurr** [comment]
Hey @Bibo-Joshi, thanks for those pointers.

I've almost fixed this just adding handlers in different groups (one for classic commands and one per each conversation).

I cannot yet restart the same conversation with the same entry point command (e.g., typing `/start_conv_2` and `/start_conv_2` again). Am I using filters in a wrong way? 

Here there are my handlers now:

```python
dp = updater.dispatcher


conv_1_handler = ConversationHandler(
    entry_points=[CommandHandler('start_conv_1', start_conv_1)],

    states={
        FOO: [MessageHandler(Filters.text & (~ Filters.command), handle_1)],
    },

    fallbacks=[MessageHandler(Filters.command, cancel)]
)

conv_2_handler = ConversationHandler(
    entry_points=[CommandHandler('start_conv_2', start_conv_2)],

    states={
        BAR: [CommandHandler('bar', handle_2)],
    },

    fallbacks=[MessageHandler(Filters.command, cancel)]
)

# Group 1
dp.add_handler(CommandHandler('start', start),1)
dp.add_handler(CommandHandler('classic', classic),1)
# Group 2
dp.add_handler(conv_1_handler,2)
# Group 3
dp.add_handler(conv_2_handler,3)

```

**Comment by Bibo-Joshi** [comment]
I think you just need to set[ `allow_reentry=True` ](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.conversationhandler.html#telegram.ext.ConversationHandler.allow_reentry)

**Comment by floatingpurr** [comment]
Great. it works! Thanks for your kind help!

**Comment by floatingpurr** [comment]
Just a very little follow-up question. What if I need to add an unknown command handler to catch all the unknown commands. Something like:

```python
# added as the last handler
dp.add_handler(MessageHandler(Filters.command, unknown))
```

I mean, to which group should this handler belong to? If that belongs to the same group of the _classic_ commands, it will be triggered each time conversations start.

**Comment by Poolitzer** [comment]
Isn't that basically the fallback part? If the current handlers in an active conversation dont handle the update, handlers in the fallback are checked.

**Comment by floatingpurr** [comment]
A kind of. This should be the "default fallback" triggered when you are not in a conversation. For example, when you are not conversing, only those 2 commands are available

```python
# classic commands
dp.add_handler(CommandHandler('start', start))
dp.add_handler(CommandHandler('classic', classic))
```

if the user types `/foo`, such a "default fallback" should be triggered.

Feel free to correct me if I'm creating an anti-pattern.

**Comment by Poolitzer** [comment]
No, hmm. The issue is you cant directly check if a different conversationhandler already handled it in another group.

What about adding it to the last group after the command handler and exclude all entry point commands or whatever you have there? Would that be enough?

**Comment by floatingpurr** [comment]
Do you mean something like this? (not tested yet)

```python
# Group 1
dp.add_handler(CommandHandler('start', start),1)
dp.add_handler(CommandHandler('classic', classic),1)
# default fallback: filter out all commands that are used in the bot and in conversations 
dp.add_handler(MessageHandler(Filters.command & (~ Filters.regex('^(\/start|\/classic|\/start_conv_1 |\/start_conv_2)$')), unknown), 1)

# Group 2 (conversation)
dp.add_handler(conv_1_handler,2)

# Group 3 (conversation)
dp.add_handler(conv_2_handler,3)
```

**Comment by Bibo-Joshi** [comment]
Should work

**Comment by floatingpurr** [comment]
Ok thanks.

Just my 2 cents: having a global fallback could be a good resource in the `python-telegram-bot` toolkit :)
