### ISSUE TITLE
[QUESTION] Can non inline-mode support Table in Markdown or HTML ?

### ISSUE THREAD

**Issue by nguyenl95** [python-telegram-bot/python-telegram-bot#1865]
### Issue I am facing
As title, I try to use MD and HTML to build a message with Table

Here is what I tried

The result of MD parser below is raw text
```python
query = '| localtime | task |\n| --- | --- |\n| 2020-04-02 23:48:18 | task 01 |\n'
context.bot.send_message(job.context, text='{}'.format(escape_markdown(query)), parse_mode=ParseMode.MARKDOWN)
```

About HTML parser, it seems that they don't support \<table\> tag

**Comment by Poolitzer** [comment]
Yep, telegram doesnt support tables, sorry.

**Comment by nguyenl95** [comment]
Are there anything pretty that could construct data like table that you could think of?

**Comment by tsnoam** [comment]
Hi, 
This issue tracking is for questions/bugs specific to ptb.
This question is off topic here, but much more appropriate in our users group, feel free to join and ask there!
https://t.me/pythontelegrambotgroup
