### ISSUE TITLE
[QUESTION] - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: api.telegram.org

### ISSUE THREAD

**Issue by zyzzando** [python-telegram-bot/python-telegram-bot#1868]
Hi,
I have a problem with my bot and I do not understand why this happens...
I also searched a lot in your doc but I did not found the problem neither the solution:

This is my error and it happens so many times during the excution (also if the bot is used by only ONE user):

```telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: api.telegram.org```

This is my bot implementation (I do not report the implementation of the single functions):

```
bot = telegram.Bot(token=TOKEN)
MAIN_MENU, PROFILE_AMZ, EMAIL, GET_NUMORD, VALIDATE, UPD_PROFILE, UPD_EMAIL, REVIEW = range(8)

updater = Updater(TOKEN, use_context=True)
dp = updater.dispatcher
conv_handler = ConversationHandler(
entry_points=[MessageHandler(Filters.text, start, pass_user_data=True), CommandHandler('start', start), CallbackQueryHandler(start, pattern = 'new_order'), CallbackQueryHandler(start, pattern = 'ask_profile'), CallbackQueryHandler(start, pattern = 'ask_email'), CallbackQueryHandler(start, pattern = 'selReview'), CallbackQueryHandler(start, pattern = 'insReview'), CallbackQueryHandler(start, pattern = 'mainMenu')],
		states={MAIN_MENU: [MessageHandler(Filters.text, start, pass_user_data=True), CallbackQueryHandler(email, pattern = 'new_order'), CallbackQueryHandler(ask_profile, pattern = 'ask_profile'), CallbackQueryHandler(ask_email, pattern = 'ask_email'), CallbackQueryHandler(selReview, pattern = 'selReview'), CallbackQueryHandler(insReview, pattern = 'insReview'), CallbackQueryHandler(mainMenu, pattern = 'mainMenu')],
		PROFILE: [MessageHandler(Filters.text, profile, pass_user_data=True)],
		EMAIL: [MessageHandler(Filters.text, email, pass_user_data=True), CallbackQueryHandler(mainMenu, pattern = 'mainMenu')],
		GET_NUMORD: [MessageHandler(Filters.text, get_numord, pass_user_data=True), CallbackQueryHandler(mainMenu, pattern = 'mainMenu')],
		VALIDATE: [MessageHandler(Filters.text, validate, pass_user_data=True), MessageHandler(Filters.photo, validate, pass_user_data=True), CallbackQueryHandler(mainMenu, pattern = 'mainMenu')],
		UPD_PROFILE: [MessageHandler(Filters.text, upd_profile, pass_user_data=True), CallbackQueryHandler(mainMenu, pattern = 'mainMenu')],
		UPD_EMAIL: [MessageHandler(Filters.text, upd_email, pass_user_data=True), CallbackQueryHandler(mainMenu, pattern = 'mainMenu')],
		REVIEW: [MessageHandler(Filters.text, review, pass_user_data=True), CallbackQueryHandler(mainMenu, pattern = 'mainMenu'), CallbackQueryHandler(selReview, pattern = 'selReview')]},
		fallbacks=[CommandHandler('cancel', cancel)]
		)
dp.add_handler(conv_handler)
dp.add_error_handler(error_callback)
updater.start_polling()
updater.idle()
```

### **Expected behaviour**
NO WARNING

### **Actual behaviour**
WARNING

### **Configuration**
Operating System: Windows 10

### **Version of Python, python-telegram-bot & dependencies:**

python-telegram-bot 12.4.2 (v12.4.2-4-g8d6970a)
Python 3.8.2

**Comment by zyzzando** [comment]
**NOTE:** I tried `request.CON_POOL_SIZE = 10`
in my code but warning still apears

**Comment by tsnoam** [comment]
@zyzzando 1. Please add the missing information according to the issue template. We need it in order to help.

2. You do not need to create a Bot object yourself, but rather use the one passed via the context object to the callbacks.

3. This sounds like an improper ratio between number of async threads to the size of the connection pool. Which can also be related to the fact you&#x27;re using a Bot object which wasn&#x27;t created during Updater initialization.

**Comment by zyzzando** [comment]
> @zyzzando 1. Please add the missing information according to the issue template. We need it in order to help.
> 
> 1. You do not need to create a Bot object yourself, but rather use the one passed via the context object to the callbacks.
> 2. This sounds like an improper ratio between number of async threads to the size of the connection pool. Which can also be related to the fact you're using a Bot object which wasn't created during Updater initialization.

I understad and this could be an hint
but in this case how to delete a specific message without calling 

`bot.deleteMessage(update.effective_chat.id,  msg_id)`

**Comment by tsnoam** [comment]
@zyzzando ext.Updater.bot<b>ext.Updater.bot</b>
<i>python-telegram-bot</i> documentation for this attribute:
<a href="https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.updater.html#telegram.ext.Updater.bot">telegram.ext.Updater.bot</a>

**Comment by tsnoam** [comment]
@zyzzando Sorry wrong link

**Comment by tsnoam** [comment]
@zyzzando You&#x27;ve got the Bot instance on the update object

**Comment by Poolitzer** [comment]
@tsnoam <b>Update</b>
<i>python-telegram-bot</i> documentation for this class:
<a href="https://python-telegram-bot.readthedocs.io/en/stable/telegram.update.html#telegram.Update">telegram.Update</a>

The official documentation has more info about <a href="https://core.telegram.org/bots/api#update">Update</a>.

**Comment by tsnoam** [comment]
@zyzzando 

I'm sorry for the confusion, I wasn't very focused. I've deleted the previous misleading comments.

1. To delete a message you can call the `delete()` method on it: https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html#telegram.Message.delete
2. If you need the Bot instance from a callback, the recommended way is to use a context enabled Handler (it's an optional flag during the Handler initialization which will become enabled by default in the future).
3. The message object contains a reference to the bot object: `Message.bot`.

Hope that it helps.

**Comment by zyzzando** [comment]
> @zyzzando
> 
> I'm sorry for the confusion, I wasn't very focused. I've deleted the previous misleading comments.
> 
> 1. To delete a message you can call the `delete()` method on it: https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html#telegram.Message.delete
> 2. If you need the Bot instance from a callback, the recommended way is to use a context enabled Handler (it's an optional flag during the Handler initialization which will become enabled by default in the future).
> 3. The message object contains a reference to the bot object: `Message.bot`.
> 
> Hope that it helps.

Hi tsnoam, first of all thanks a lot for your help.
If I unserstand well both this function:

`update.callback_query.message.delete()`

and

`update.message.delete()`

remove only the current message inside of my context
but I need to remove programmatically a specific message not the last one, i am asking you how to do that.

Thanks another time for your patience and support :)

**Comment by Bibo-Joshi** [comment]
> 2. If you need the Bot instance from a callback, the recommended way is to use a context enabled Handler (it's an optional flag during the Handler initialization which will become enabled by default in the future).

This is the important part. If you set up your `Updater` as `Updater('TOKEN', use_context=True')`, your callbacks will look like this:

```python
def my_callback(update: Update, context: CallbackContext):
    bot = context.bot
    # stuff
    bot.delete_message(chat_id, msg_id)
```
Here, `context.bot` is the `Bot` instance set up by the `Updater`. So you don't need to instantiate a bot yourself. For more information on context based callbacks, see [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-12.0#context-based-callbacks).

**Comment by zyzzando** [comment]
I just implemened this solution in my bot, now i am testing it whit my uers.
You are help is very useful, I want to thank you sincerely.

In the mittle I want to ask you another thing, why with this conversationhandler implementation i have the following warning?

`warnings.warn("If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.")`

how to fix it?

**Comment by Bibo-Joshi** [comment]
Please see #1781

**Comment by zyzzando** [comment]
yeah but my conversationhandler does not consist only in callbackqueryhandler as you can see in the first post

**Comment by Bibo-Joshi** [comment]
This is why "It's not an error, it's a warning ;)". Warnings can be ignored.

**Comment by zyzzando** [comment]
yeah but if this situation does not concern me and my implementation why the warning appers ? It will be useful if concern something that I did 

i ask just to understand better

**Comment by Bibo-Joshi** [comment]
The warning is triggered, when one of the handlers in a `ConversationHandler` is a `CallbackQueryHandler`, which is the case in your example.

**Comment by zyzzando** [comment]
so regardless of the implementation, whether correct or incorrect?
