### ISSUE TITLE
[QUESTION] Is it possible to use generator functions as callbacks?

### ISSUE THREAD

**Issue by Javain** [python-telegram-bot/python-telegram-bot#1870]
### Issue I am facing
To perform some tests, I intend to call the callback directly without using the bot. It works fine. 

Problem comes when I execute the bot and expect the callback to be called after an update is sent: callback stops working if I include yield statement in some line.

### Traceback to the issue
None

### Related part of your code
```python
def run(self, update, context):
    { SOME CODE }
    yield {some variable}
    { SOME CODE }
```

**Comment by Bibo-Joshi** [comment]
Mh, when handling an update, the dispatcher will call `run(update, context)`, which will be a generator object in your case. But (as far as I understand) a generators code will only be executed when iterating over it. This part won't happen in the normal setup and I don't really see what you would expect PTB to do.

What would be your use case?

**Comment by Javain** [comment]
As far as I know, the returns from callbacks are ignored. I expected PTB to behave as it would without the yield statements.

The code would be something like this:
```
class Start(Command):
   def run(self, update, context):
       { SOME CODE }
       yield {some variable}
       { SOME CODE }

    {MORE METHODS}

class StartTest(Start, Test):
    def test(self):
        # I generate update and context from a simulated message text
        update, context = self._generate_variables("/start")
        assert list(self.run(update, context)) == [{some variables}]


if __name__ == '__main__':
    start = StartTest()
    start.test()
    # if code goes on from here, callback works fine

    updater = Updater(token=bot_token, use_context=True)
    start = Start()
    start_handler = CommandHandler("start", start.run)
    updater.dispatcher.add_handler(start_handler)
    updater.start_polling()
    updater.idle()
```

**Comment by Bibo-Joshi** [comment]
It's not surprising that 

```python
assert list(self.run(update, context)) == [{some variables}]
```
works, as the `list()` directive will _execute_ the generator provided by `run()`. The line is equivalent to
```python
assert [x for x in self.run(update, context] == [{some variables}]
```
But such a thing won't happen on processing an update with `Handler(.., Start().run)`. `Handler.handle_update` will just call `Start().run`, which just does, as is to expected by a generator. You would need to do something like

```python
for x in Handler.handle_update(update):
    # do stuff with x
```
for the code in `python Start.run` to be executed. But as I said, I don't see why one would expect PTB to do likewise. Can you describe you use case? Maybe there is another solution.

**Comment by Javain** [comment]
If I understood correctly, you're saying that, as far as PTB is concerned, these two functions do the same thing:
```python
   def run(self, update, context):
       x = context.args[0]
       x += 1
       context.bot.send_message(chat_id=update.effective_chat.id, text=x, reply_to_message_id=update.message.message_id)

   def run_with_yield(self, update, context):
       x = context.args[0]
       x += 1
       yield x
       context.bot.send_message(chat_id=update.effective_chat.id, text=x, reply_to_message_id=update.message.message_id)
```
Am I right?

**Comment by Bibo-Joshi** [comment]
@Javain No. I was saying the the latter can&#x27;t be expected to work as callback argument of a handler and that I don&#x27;t see why you would expect it to work. Again, knowing what exactly you&#x27;re trying to achieve is crucial for helping you.

**Comment by Javain** [comment]
@Bibo-Joshi Ok, just making sure if what I understood was true. Since you said the handler would just call `Start().run` and _not execute the generator_, which is precisely what I'd want.

I'll try to answer you in a more detailed way as soon as I can.
