### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Javain** [python-telegram-bot/python-telegram-bot#1872]
### Issue I am facing
To perform some tests, I intend to call the callback directly without using the bot. It works fine. Problem comes when I execute the bot and expect the callback to be called after an update is sent, callback stops working if I include yield statement in some line.

### Traceback to the issue
None

### Related part of your code
```
def run(self, update, context):
    { SOME CODE }
    yield {some variable}
    { SOME CODE }
```

**Comment by Bibo-Joshi** [comment]
Please elaborate in #1870 instead of opening a new issue

**Comment by Javain** [comment]
@Bibo-Joshi sorry, I created this issue unintentionally.
