### ISSUE TITLE
How to make different list for each user?

### ISSUE THREAD

**Issue by SaidtheBoss** [python-telegram-bot/python-telegram-bot#1876]
I was programming a bot that would take user message and add it to the list so when user wanted the reminder it would ask for it.

### Issue I am facing
there is no separate list for each user everyone is using the same list
### Traceback to the issue
I tested two phones for the bot and when i asked for list in both of them it was mixed
put it here

### Related part of your code
List[]

MessageHandler(update , context):
       if message !='send list':
           List.append(message)
      else:
          send list

the problem is that its treating List as one so when one user adds a reminder  it also adds to other user's list

**Comment by Bibo-Joshi** [comment]
Please have a look at our [wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Storing-bot,-user-and-chat-related-data).

**Comment by SaidtheBoss** [comment]
> Please have a look at our [wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Storing-bot,-user-and-chat-related-data).
I tried sorry i am new to this 
i did not understand it

**Comment by SaidtheBoss** [comment]
how would i make lists for different chat id ?

**Comment by SaidtheBoss** [comment]
there are also other vars to such as time and day so how do that?

**Comment by Bibo-Joshi** [comment]
> how would i make lists for different chat id ?

Using `context.chat_data` or `context.user_data` as described in the wiki. If you have a hard time understanding the terminology in the wiki article, I suggest you read up on some python tutorials. Roolsbot has [some links](https://t.me/pythontelegrambotgroup/304764) for you.

Also, please don't write issue comments like you write messages on instant messengers. Some people will get mail notifications every time you comment ;)
