### ISSUE TITLE
[QUESTION] How to get channel admin

### ISSUE THREAD

**Issue by Amiiwr1** [python-telegram-bot/python-telegram-bot#1878]
I wanted to get channel info such as admin user 
so that I can set some features for admins.

**Comment by Bibo-Joshi** [comment]
Hi. You'll wanne have a look at [get_chat_member ](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.get_chat_member) and [get_chat_administrators](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.get_chat_administrators).

For the future, please stick to the issue templates. It makes it way easier to help you ;)

**Comment by Amiiwr1** [comment]
@Bibo-Joshi thanks for your help.
I found it out.
