### ISSUE TITLE
[QUESTION] - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

### ISSUE THREAD

**Issue by zyzzando** [python-telegram-bot/python-telegram-bot#1879]
Hi,
I have a problem with my bot, randomly few times in a day I have the following error:

`telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running`

But I have only one istance of bot in my code, now I use context to send and delete message.
This is my bot implementation (I do not report the implementation of the single functions):

Can you help me?

```MAIN_MENU, PROFILE_AMZ, EMAIL, GET_NUMORD, VALIDATE, UPD_PROFILE, UPD_EMAIL, REVIEW = range(8)

updater = Updater(TOKEN, use_context=True)
dp = updater.dispatcher
conv_handler = ConversationHandler(
entry_points=[MessageHandler(Filters.text, start, pass_user_data=True), CommandHandler('start', start), CallbackQueryHandler(start, pattern = 'new_order'), CallbackQueryHandler(start, pattern = 'ask_profile'), CallbackQueryHandler(start, pattern = 'ask_email'), CallbackQueryHandler(start, pattern = 'selReview'), CallbackQueryHandler(start, pattern = 'insReview'), CallbackQueryHandler(start, pattern = 'mainMenu')],
		states={MAIN_MENU: [MessageHandler(Filters.text, start, pass_user_data=True), CallbackQueryHandler(email, pattern = 'new_order'), CallbackQueryHandler(ask_profile, pattern = 'ask_profile'), CallbackQueryHandler(ask_email, pattern = 'ask_email'), CallbackQueryHandler(selReview, pattern = 'selReview'), CallbackQueryHandler(insReview, pattern = 'insReview'), CallbackQueryHandler(mainMenu, pattern = 'mainMenu')],
		PROFILE: [MessageHandler(Filters.text, profile, pass_user_data=True)],
		EMAIL: [MessageHandler(Filters.text, email, pass_user_data=True), CallbackQueryHandler(mainMenu, pattern = 'mainMenu')],
		GET_NUMORD: [MessageHandler(Filters.text, get_numord, pass_user_data=True), CallbackQueryHandler(mainMenu, pattern = 'mainMenu')],
		VALIDATE: [MessageHandler(Filters.text, validate, pass_user_data=True), MessageHandler(Filters.photo, validate, pass_user_data=True), CallbackQueryHandler(mainMenu, pattern = 'mainMenu')],
		UPD_PROFILE: [MessageHandler(Filters.text, upd_profile, pass_user_data=True), CallbackQueryHandler(mainMenu, pattern = 'mainMenu')],
		UPD_EMAIL: [MessageHandler(Filters.text, upd_email, pass_user_data=True), CallbackQueryHandler(mainMenu, pattern = 'mainMenu')],
		REVIEW: [MessageHandler(Filters.text, review, pass_user_data=True), CallbackQueryHandler(mainMenu, pattern = 'mainMenu'), CallbackQueryHandler(selReview, pattern = 'selReview')]},
		fallbacks=[CommandHandler('cancel', cancel)]
		)
dp.add_handler(conv_handler)
dp.add_error_handler(error_callback)
updater.start_polling()
updater.idle()
```
### **Expected behaviour**
NO ERROR

### **Actual behaviour**
ERROR

### **Configuration**
Operating System: Windows 10

### **Version of Python, python-telegram-bot & dependencies:**

python-telegram-bot 12.4.2 (v12.4.2-4-g8d6970a)
Python 3.8.2

**Comment by Bibo-Joshi** [comment]
Hi. Are you sure that you have only one process running that uses that bot token? Could that token have been exposed somewhere, so that someone else is using it? Try revoking the token with BotFather.

**Comment by obito2502** [comment]
Hi. Make sure that you are ran a bot from one place and check that the bot stopped his action. I had the same issue, when I started bot from terminal and after stopping the bot, terminal did not stopped it correctly. I should kill the process separately

**Comment by zyzzando** [comment]
I revoked the token but the issue still happening in randomly way...
How to check if I have other istance running ? checking by my task manager I see only the current powershell active...

**Comment by obito2502** [comment]
On Ubuntu 18.04 I typed in terminal command:
sudo ps -U username 

and found process called "python" and killed it

**Comment by zyzzando** [comment]
while in Windows?
