### ISSUE TITLE
Missing unit test for answerInlineQuery and InlineQuery*

### ISSUE THREAD

**Issue by jh0ker** [python-telegram-bot/python-telegram-bot#188]
We are currently missing a unit test for `answerInlineQuery` because of the dynamic nature of that API method.

**Comment by leandrotoledo** [comment]
Pending:
- [ ] InlineKeyboardButton
- [ ] InlineKeyboardMarkup
- [ ] InputMessageContent
- [ ] InputContactMessageContent
- [ ] InputLocationMessageContent
- [ ] InputTextMessageContent
- [ ] InputVenueMessageContent
- [ ] MessageEntity
- [ ] Venue

**Comment by leandrotoledo** [comment]
PR #261 has been submitted for this.
