### ISSUE TITLE
Importing telegram prints binary data [BUG]

### ISSUE THREAD

**Issue by prajwaldr9** [python-telegram-bot/python-telegram-bot#1883]
### Steps to reproduce
1. Install the latest version of python-telegram-bot 12.5.1   

I have installed python-telegram-bot latest version.
In Pycharm when I try to import it like
import telegram I'm getting this output

b'\x10'
b'\x00\x00\x00\x10'
b'\x10\x00\x00\x00'
b'\xfa\xfb\xfd\xfc'
240
0b10110

### Configuration
**Operating System:**
Mac High Sierra and Pycharm

**Version of Python, python-telegram-bot & dependencies:**
Python 3.7 
python-telegram-bot 12.5.1   
<img width="543" alt="Screenshot 2020-04-08 at 11 19 13 PM" src="https://user-images.githubusercontent.com/36110432/78816531-7d075a80-79ef-11ea-979a-134ebae65e70.png">

**Comment by Bibo-Joshi** [comment]
Hi. Do you maybe have a script `telegram.py` or a package named `telegram` in the same directory?

**Comment by prajwaldr9** [comment]
> Hi. Do you maybe have a script `telegram.py` or a package named `telegram` in the same directory

I am not sure how import telegram statement was executing test.py file. Thanks for letting me know. 


Please close the issue.
