### ISSUE TITLE
Bot is in sleep mode after 15 minutes

### ISSUE THREAD

**Issue by Quegga** [python-telegram-bot/python-telegram-bot#1885]
Hello,
I have a problem that if my bot does not receive an update through chat messages for 15 minutes it goes into a "sleep mode". The next message will then raise a `ConnectionResetError`, after which it works as expected until no update is received again for 15 minutes.
This is happening now since about  week, but I do not know exactly when it started. My bot is now running (not continuously) for about 1 year without any issues. I did not modify any of the components that interfer with the `updater`, `dispatcher`, etc. recently.

**My bot is using this updater:**

    def __init__(self, bot_id):
        updater = Updater(bot_id, use_context=True, request_kwargs={'read_timeout': 120, 'connect_timeout': 120})
        dispatcher = updater.dispatcher
        dispatcher.add_handler(CommandHandler("initialize", game.set_group_id))
        ...

        dispatcher.add_handler(CallbackQueryHandler(game.join, pattern="player_join"))
        ...

        dispatcher.add_handler(MessageHandler(filters=Filters.text, callback=game.private_message))
        ...

        dispatcher.add_error_handler(self.error)
        updater.start_polling()
        updater.idle()

**The error I receive** is `urllib3 HTTPError ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))`
It takes about 10 seconds after the first message for this error to appear. Afterwards it works without delay just as normal until no message is received again for 15 minutes. If another message is sent during that 10 seconds of "waking up", it gets processed immeadiatly after the error. I tried this on two different machines, same result.

I do not know exactly what `updater.idle()` does, I tried removing it, but the issue is still there.

Since this only started about 1 week ago I am clueless what could cause it. I did update my python-telegram-bot via pip today, same issue. Can I somehow manually produce an update every 10 minutes without putting an instance of my bot in some debug group chat that spams a message every 10 minutes? Or is there some kind of "stay awake" setting?

Thanks you!

**Comment by Bibo-Joshi** [comment]
Hi. Please have a look at #1773 and the issue linked therein.
As for manually generating updates: You can use `JobQueue.run_repeating`, with a job callback that enqueues an update via `context.update_queue`.

**Comment by Quegga** [comment]
Thank you, I was searching a lot but could not find that topic. Is this a correct call for what you are describing? it should produce an update every 10 seconds.
`telegram.ext.JobQueue.run_repeating(telegram.ext.JobQueue(), bot, 10)`

**Comment by Bibo-Joshi** [comment]
Our [wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-–-JobQueue) and the [timerbot ](https://github.com/python-telegram-bot/python-telegram-bot/tree/master/examples#timerbotpy)example should help you get startet :)

**Comment by tsnoam** [comment]
@Quegga If you haven&#x27;t done so already, you better read this as well:
Wiki of python-telegram-bot
Networking ➜ Handling network errors

**Comment by Quegga** [comment]
Thanks @Bibo-Joshi and @tsnoam , I managed to solve it by starting a repeating timer as soon as my bot is started with 10 minutes duration. Its callback sends a message to a non-existing telegram ID, which is not a very elegant solution, but it keeps the bot awake.
