### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by simo3o** [python-telegram-bot/python-telegram-bot#1891]
### Issue I am facing
I'm trying to check if a user is in a group with Bot.get_chat_member(chat_id, user_id) and I'm getting an error saying 
```
TypeError: get_chat_member() missing 1 required positional argument: 'user_id'
```
And if I add Bot.get_chat_member(context,chat_id,user_id) I get 
```
AttributeError: 'CallbackContext' object has no attribute 'base_url'
```
Do I need to pass context or is something wrong with my call with user_id?

### Related part of your code
```python
 member_of_group = Bot.get_chat_member(GROUP_ID, update.message.from_user.id)
```

**Comment by Bibo-Joshi** [comment]
You need to instantiate a bot by `bot = Bot('Token')` and then call `bot.get_chat_member(chat_id, user_id)`.

If you're new to python and/or object oriented programming, I suggest you read up on some tutorials. [Rulesbot](https://t.me/pythontelegrambotgroup/304764) has some links for you. To get started with PTB, the tutorial "Your first Bot" in our wiki is a good starting point.

**Comment by jh0ker** [comment]
Also if you already have a context, you use the existing bot instance like this `context.bot.get_chat_member(GROUP_ID, update.message.from_user.id)`

**Comment by simo3o** [comment]
> 
> 
> You need to instantiate a bot by `bot = Bot('Token')` and then call `bot.get_chat_member(chat_id, user_id)`.
> 
> If you're new to python and/or object oriented programming, I suggest you read up on some tutorials. [Rulesbot](https://t.me/pythontelegrambotgroup/304764) has some links for you. To get started with PTB, the tutorial "Your first Bot" in our wiki is a good starting point.

Thanks, I did try that, I'm not new on python or oop, thanks for the input. I finally made it work with jh0ker input, I don't know how I lost it this afternoon.
Thanks anyway.
