### ISSUE TITLE
[QUESTION] - Is it possible add a MessageHandler indipendent from the status of the ConversationHandler?

### ISSUE THREAD

**Issue by zyzzando** [python-telegram-bot/python-telegram-bot#1893]
If yes how?
and my second question is this : "If I have a function that send one message to my user everyday and in the rest of the script i use context.bot to send message, how can send message in this function in which i do not have context?"

**Comment by Bibo-Joshi** [comment]
Hi.

* Please fill out the entire issue template. It's there for a reason.
* Adding a `MessageHandler` is as easy as `disptacher.add_handler(MessageHandler(Filters.all, callback))`, as shown in our [examples](https://github.com/python-telegram-bot/python-telegram-bot/blob/314f87ec44845c602d484eeeb2de20297f32ebec/examples/echobot2.py#L66), in our [wiki ](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-–-Your-first-Bot)and as described in the [documentation](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.dispatcher.html#telegram.ext.Dispatcher.add_handler). If you want to have the `MessageHandler` _in_ a conversation, but make available in in every state, either just add it to every state, or consider using it as a [fallback](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.conversationhandler.html#telegram.ext.ConversationHandler.fallbacks).
* Assuming you're sending the timed message using the `JobQueue` and you're using context based callbacks, your job callback gets a `CallbackContext` object as argument, as shown in our [examples](https://github.com/python-telegram-bot/python-telegram-bot/blob/314f87ec44845c602d484eeeb2de20297f32ebec/examples/timerbot.py#L38), in our [wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-–-JobQueue) and as described in the [documentation](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.jobqueue.html#telegram.ext.JobQueue.run_daily).
* Please read the documentation resources carefully. They're there for a reason.
