### ISSUE TITLE
[FEATURE] Open handler for other services at telegram bot

### ISSUE THREAD

**Issue by jmwielandt** [python-telegram-bot/python-telegram-bot#1895]
#### Is your feature request related to a problem? Please describe.
I want to handle events from github (webhook) and send some info about it to a telegram chat but there is no way to do it.

#### Describe the solution you'd like
An OpenHandler handler, that pass a dictionary (from a json) as the update argument to `callback` func, `check_update` func and their friends.
Better way to implement it could be making `Update.de_json` func detects that a request isn't from telegram and then pass it as a dict to the OpenHandler.

<hr/>

Other solution would be:
- add a `add_nested_updater` method to `telegram.ext.Updater`, with it's own `url_path`.
- add an OpenHandler wich pass a json to `callback`, `check_update`, etc.
- having OpenUpdaters for this behaviour, instead of common Updaters.

On that way, if my root Updater's `url_path` is TOKEN and my nested `url_path` is `github`, then I use `https://my_app.com/TOKEN/github` to send info to my bot from github's webhook.

#### Describe alternatives you've considered
Create a second tornado app to exclusive listen to github requests and then uses the bot (from global variable "updater") to send the message to the chat.
The hugest problem for me is that, on that way, we loose the fantastic way to add new features to our bots, being forced to have a masive "if-else" block to manage different kind of interactions.
I didn't tried it with tornado, but with flask doesn't works.

#### Additional context
With the OpenHandler or similar the integration with many other services would be much more easy, not only github.

**Comment by Bibo-Joshi** [comment]
Hi. I think what you're looking for is the `TypeHandler`. Using `TypeHandler(MyUpdate, callback)`, the handler will process any update of type `MyUpdate`, which doesn't need to have to do anything at all with `telegram.Update`. In fact https://github.com/jsmnbom/githubbotrevised is using such a setup for sending news about your GitHub repos to telegram.

**Comment by Bibo-Joshi** [comment]
I'll close this. Feel free to comment, if I missed your point.
