### ISSUE TITLE
No Markup with send_photo [QUESTION]

### ISSUE THREAD

**Issue by rgaldieri** [python-telegram-bot/python-telegram-bot#1901]
Hey guys!

I've been playing with telegram API lately, and I was trying to send a bold caption with an image. I've tried both combinations below, and text always comes clean with markup removed, as if it was parsed but with no change. Am I doing something wrong?

`context.bot.sendPhoto(chat_id=update.effective_chat.id, photo = parser.imageURL, caption="*bold*", parse_mode="Markdown")`
`update.message.reply_photo(parser.imageURL, "*text*", parse_mode = 'Markdown')
`

I also tried with double ** instead, but the result is still the same. Any help would be appreciated!

**Comment by Bibo-Joshi** [comment]
Hi. I can't reproduce the issue. If you're only sending `'*bold*'`, it may not look too bold at first glance. Maybe try sending `'*bold*, normal` for comparison or `_italics_` to make sure that it's parsed correctly. On another note, you should switch to MarkdownV2 (use `parse_mode=ParseMode.MARKDOWN_V2`)
