### ISSUE TITLE
[BUG] RequestsDependencyWarning: urllib3 (1.25.9) or chardet (3.0.4) doesn't match a supported version!  

### ISSUE THREAD

**Issue by abdelhakel** [python-telegram-bot/python-telegram-bot#1906]
### Steps to reproduce
1.` python3 mybot`

2. 
```
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.9) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```

3.
The bot should run. But it is not

### Configuration
**Operating System:**
Ubuntu 18.04

**Version of Python, python-telegram-bot & dependencies:**
```
python-telegram-bot 12.6.1
certifi 2020.04.05.1
future 0.18.2
Python 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
```

**Comment by Poolitzer** [comment]
@abdelhakel Hey.

As I told you in the group, you installed requests on your own, this has nothing to do with our library. Just update urrlib3 and you are good to go.
