### ISSUE TITLE
[QUESTION]Help how i can send message for all bot users 

### ISSUE THREAD

**Issue by Nicolashide** [python-telegram-bot/python-telegram-bot#1909]
```
def answer(bot, update):
    global mail, city, cit, rayon,lol, tovari, lol1, tovar
    message = update.message
    if (message.chat.id in constants.admins) and message.text == 'Рассылка':
        mail = True
        bot.send_message(message.chat.id, 'Напишите сообщение!')
    elif mail == True:
        mail = False
        text = base_work.all_id()
        bot.send_message(message.chat.id, 'В течении 3 секунд, отправиться всем пользователям!')
        for i in text:
            try:
                bot.forward_message(i, message.chat.id, disable_notification=True, message_id=message.message_id)
            except:
                pass
```
Help, I need to send a message to all users that I will send to the bot.

**Comment by Bibo-Joshi** [comment]
Please see #1836.

**Comment by Nicolashide** [comment]
I can’t understand what should I do?
help I'm just a beginner

**Comment by Bibo-Joshi** [comment]
If you have a hard time understanding ptbs functionality, I suggest to go through the wiki, probably starting [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-–-Your-first-Bot). To understand #1836, [this](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Storing-bot,-user-and-chat-related-data) and [this](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Making-your-bot-persistent) page are helpfull. Moreover, the actual [documentation](https://python-telegram-bot.readthedocs.io/en/stable/) has answers for many questions regarding PTB.
