### ISSUE TITLE
[FEATURE] Contrib repository

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#1912]
This is kind of  a meta issue, but I felt like it's more appropriate and convenient to discuss it here than in the dev chat.

# Disclaimer
I know, that this is quite a wall of text. Still, I'd appreciate any feedback, both from the maintainers/developers and the users/potential contributers perspective. I'm sure that I haven't covered everything and that there are other, more elegant solutions to the problems I list, which I simply don't see.

# The Problem
We have sometimes have feature requests/PRs that are reasonable for some applications but kind of too specific for a general purpose library.

Examples (from my point of view) are #854 (`extract_url` helper) #1861 (forward messages by "copying" them), #1702 (handler for inline menus based on CH. There are also older approaches to that), maybe #1911 as well (read descriptions from CommandHandlers and use them with `Bot.set_my_commands`)

Right now, we have mostly have to reject those, because we simply don't have the resources to maintain those contributions.

Parts of the code snippets section in the wiki also fall into this category.

# Proposal: Contribution Repository
The idea of a contribution repository has been discussed in the dev chat before. The general idea is to add a repository `python-telegram-bot-contrib/plugins` or whatever, where such "reasonable but out of scope" features can be collected.

Personally, I find the idea appealing. That way we can give users a way of exchanging pieces of code that may be usefull for others and also have some "experimental" features that we don't want to have to maintain.

## Alternatives:
* We already have a `/contrib` directory in the main repo. However opening this to the contributions described above will probably hard to tell "important" prs/issues from contribution-ones. Also the git-log will likely become messy and we might be pressured into releasing quicker than we want to.

* A low-effort alternative would be to add a wiki page to just gather links to such things. Everyone could maintain their own plugin and add a link it there. While this means nearly no maintainance work, this also means that the listed resources most likely will come with a lower code standard and will probably not have a uniform integration interface (see below)

## Problems
*If* we decide that a contrib repo is a good thing to have, there are some issues to think about

### Shipping
How do we install the contrib repo?
* Ship it as regular package to be installed by `pip`. But how often? Contributers will likely expect a contrib package to be released much more frequently than ptb. Do we release after every commit? Once a month?
* Make people install master. `pip` can do that, so that's not really an issue. This seem unsatisfactory at first glance. On the other hand, people installing from a contrib repo should (*should*!) know their way around PTB and Python in general. Also it takes away a lot of maintainance work. The Changelog could be a separete one for every contribution and be updated on the fly.

### Architecture
The contrib repo should be designed such that all features are separated from each other. So if one feature is buggy, the others will still work. My suggestion would be to have every contribution in a single file/module, so we could do stuff like

```python
from telegram-contrib import feature-a
# from telegram-contrib import feature-b # skip this one, this is buggy
from telegram-contrib import feature-c
```

### Integration with PTB
This one is a real problem in my eyes. We'll want to make it simple to use the contrib repo with PTB, while making little to no changes with PTB itself. Let's assume we have installed the contrib repo as `telegram-contrib` package. There are different situations:

* Additional functions, handlers, ect. We can just import them like
  ```python
   from telegram-contrib import MyHandler
  ```
  and be done with it
* Additions to existing classes, e.g. #854 and #1861 would make sense as class methods of `Message`. This is a bit trickier, since `Message.de_json` is called on receiving updates. One could go for `Updater(..., use_contrib_message=True)` or something. However that poses two difficulties:
  * We have to make changes to ptb. Meh.
  * #854 and #1861 will likely (see above) be implemented independently from each other, so we'd have decide, *which* contrib `Message` to use. Using both would become a hassle.

  Another approach could be to do
  ```python
  from telegram import Message
  
  fun = Message.forward

  def forward(*args, **kwargs):
      fun(*args, **kwargs)
      # some stuff

  Message.forward = foward
  ```
  and then
  ```python
  from telegram import Message
  from telegram-contrib import patch-forward

  ...
  ```
    Kind of hacky, but it could do the trick.

    *Edit:* Past v13 this will play poorly with type hinting …
* Then there is stuff, that not like a "standalone" thing, but only really makes sense when integrated in the whole architecture of ptb, like #1789. This could surely be done as described as above, but that could become ugly quickly…

### Maintainance
Who will be maintainer and developer in this repo? Contributions should be reviewed (even if not as thoroughly as with PTB), so I guess merging would be the job of the PTB maintainers.

However, answering to issues related to their own contributions could be understood as the responsibility of the contributers themself, so one could argue that every contributer should be promoted to developer.

In any way, it would be a good idea to have someone as developer, who is not actively involved in the main repo, imho.

### Where to draw the line?
Pretty much linked with the maintainance question. Who decides, what is goes intro contribution and what goes into PTB? What is general purpose, what isn't?

### Documentation
I'd suggest to host documentation for the contrib repo on rtd independently from PTB. Using just the wiki is also a vailable way, but using only the wiki we don't really have a way to enforce contributers to document their features. The docs don't have to be as polished as the ones for PTB, but they should state what a feature can and cannot do and what known issues are. 

A Changelog could be kept for every feature separately, which would be especially usefull in the "install from master" option described above.

**Comment by JosXa** [comment]
@Bibo-Joshi Move fast and break things ¯\_(ツ)_/¯ Let the community figure it out. We&#x27;re just here for moderation, I&#x27;m pretty sure we&#x27;re going to find lots and lots of people who are gonna take care of such a repo that lives from the community contributions.

**Comment by JosXa** [comment]
Maybe the `contrib` folder should be renamed to `builtin` if we go ahead with this.

**Comment by JosXa** [comment]
There is a way to install additional dependencies with `[extra]` syntax, so something like `pip install python-telegram-bot[contrib]` should be possible.

**Comment by Bibo-Joshi** [comment]
> There is a way to install additional dependencies with `[extra]` syntax, so something like `pip install python-telegram-bot[contrib]` should be possible.

That sounds reasonable. We could still have `ptb[contrib]` install from contribs master, though.

**Comment by Eldinnie** [comment]
@Bibo-Joshi I&#x27;m just against anything that would mean the maintainers and contributers would have extra work trying to maintain contrib stuff.
We have seen in the past that things got implemented at some point by someone, but doesn&#x27;t get maintained. If that happens who is going to maintain it then? Or are you just going to remove it from the contrib package?
In my opinion, PTB is for the general public. Anything that is very specific or limited usecase should be up to the user. No-one is stopping them from releasing a package that hooks into PTB and I think we would gladly share them in our wiki. But I think integrating them into PTB in any way or form that it might seem to be part of PTB is a bad move.
I don&#x27;t know what is currently in the <code>contrib</code> folder. It used to be emojize (removed) and botan (removed), so maybe we can just remove the folder alltogether?

**Comment by Bibo-Joshi** [comment]
@Eldinnie Well, the idea of the contrib package <i>is</i> to have a place for code that comes with a label &quot;might not be maintained, use at your own risk&quot;. That&#x27;s why in my suggested a modular architeture, i.e. each contribution can be used, while others can be buggy as hell.

as to the current state of the contrib folder: currently it only contains stuff for packaging ptb as debian package

**Comment by Bibo-Joshi** [comment]
Just a spontanuous idea: a midway between a full blown contrib repo and "just link in the wiki".

1. Build a plugin template-repo containing
    * pro-commit hooks
    * if possible, configurations for Codecov and Codacy
    * a license
    * a readme-template with space for documentation and some "fill in the blank" installation instructions
    * some sort of template for the actual contribution
    * some default-tests:
        * maybe a meta tests that checks if any files where touched that should not be touched
        * meta tests for pre-commit
        * config.py & stuff from our tests, so that they don't need to manually try and set up an updater and such. We can even think about provide some bot tokens or just monkeypatch the bot methods by default
2. Instead of simple wiki page, we add a "curated list" of contributions, similar to this one: https://github.com/YOURLS/awesome-yourls . People need to PR for their contribution to be added and it will only be added if they use our tepmlate-repo and seem to meet our code standards at least to some degree.

Of course we can't control if people complete change their contrib-stuff after being added to the list, but this would probably be enough of a hurdle for this not to happen … We can still go over the list e.g. once a year and kick out stuff that seems have been reworked in a way that doesn't agree with our code standards.

**Comment by tsnoam** [comment]
@Bibo-Joshi 
I'm sorry it took me so long. But I finally got to it.
I tried to refer to all what you've mentioned. Anyway, the bottom line of my comment is "lets have a contrib repo".

1. **Repo name:** `contrib`.
    1. Not `plugins`, because `plugins` suggests a consistent API for all of the repo.
    2. Even though there's a `contrib/` directory in the main repo I don't find it as a conflict. They are just different kind of contributions...
2. **Shipping:** We can go for the in-between:
Supply `setup.py` but never release into pypi.
This will still allow users to pip install from a git url (including branch name or revision number).
3. **Package name:** `ptb-contrib` (i.e. `from ptb-contrib import XXX`).
4. **Architecture:** Totally agree. Allows importing only what you need, while not importing what you don't need.
5. **Integration with ptb:**
    1. We should not complicate ptb's code just to support the integration (that said, if a change is proposed and makes sense we can consider it).
    So any contrib code should take care of the integration. I can think of two ways of doing that:
        1. monkey patching (as you've already suggested in your second option).
        2. inheritence - contrib packages can inherit from `Updater` (for example) and re-implement one of its functions, possibly calling `super()`.
    2. Type hinting - this might work better using inheritance. But with all due respect, the contrib repo does not have to adhere to the same level of standards the main repo does: users will just have to make do.
6. **Maintenance:** We need someone to volunteer for that. Maybe the good people from ptb-church? This is something we want to do for the community, but we can't do everything. At the worst case we can offer someone who sends a PR: you want it in? Please maintain this git.
7. **Where to draw the line:**
First of all, we decide what is too specific to go into the main repo.
Once we've decided something is not worthy of the main repo, we may recommend it to the contrib repo.
Once suggested to the contrib repo, its maintainer will have the provocative to accept or decline.
I guess that whatever not going into the contrib may find its way into the wiki as a code snippet.
8. **Documentation:** I think that docstrings are sufficient enough and RTD is not necessary.
9. **Changelog:** Not mandatory IMHO. If someone wants to know what changed, their invited to use `git log`.
10. **License:** Also you didn't write originally, but all contributions must be licensed the same as ptb. Dual license of GPLv3 or Lesser GPLv3.

---

I like your idea to [start making a template already](https://github.com/python-telegram-bot/python-telegram-bot/issues/1912#issuecomment-708953786). Just restrict it to the bare minimum (I took your list and shorten it):
1. Pre-commit hook for code-style (i.e. black).
2. License
3. A first plugin which is an example. People would be able to copy-paste it and start coding (that's what you intended?).
4. `config.py`.

NO TESTS. NO CODE COVERAGE

**Comment by JosXa** [comment]
Replying to your points below, but first I would like to suggest that the concept of a **monorepo** could also be nice for this use case.

> 1. **Repo name:** `contrib`.
>    
>    1. Not `plugins`, because `plugins` suggests a consistent API for all of the repo.
>    2. Even though there's a `contrib/` directory in the main repo I don't find it as a conflict. They are just different kind of contributions...

[How about renaming the existing `contrib` to `builtin`?](https://github.com/python-telegram-bot/python-telegram-bot/issues/1912#issuecomment-616806729)

> 3. **Package name:** `ptb-contrib` (i.e. `from ptb-contrib import XXX`).

You mean `ptb_contrib` - dashes won't work. Package name can still be `ptb-contrib` of course, though I'll just throw `ptbcontrib` and `ptb_contrib` in the room aswell.

> 4. **Architecture:** Totally agree. Allows importing only what you need, while not importing what you don't need.

I'm wondering if every sub-project could also have a dedicated `extras` definition for pip install. What if a contrib subproject has an external dependency which would break your code when it's imported? In any case, I imagine these contrib packages to occasinally rely on third-party packages, and you don't want to get all of them when all you need is a small part.

Examples:
- ptb_contrib.nlu.IntentHandler (with dependency to Dialogflow, Wit.ai, etc.)
- ptb_contrib.persistence.RedisPersistence (with dependency to redis)
_- (I can think of a ton more where external packages make sense)_

> 5. **Integration with ptb:**
>       So any contrib code should take care of the integration. I can think of two ways of doing that: [...]

3. _Middleware_ would be a third. But obviously the most demanding of them. 

>    2. Type hinting - this might work better using inheritance. But with all due respect, the contrib repo does not have to adhere to the same level of standards the main repo does: users will just have to make do.

Automated linting, style, and type checks are a way to keep idiots out and the quality high. Might be a good idea to only allow contributions that pass rigorous automated checks...

> 6. **Maintenance:** We need someone to volunteer for that. Maybe the good people from ptb-church? 

✋ 
This stuff gets me excited, I'm in.

> NO TESTS. NO CODE COVERAGE

No tests? That sounds crazy. No coverage alright, that's fine.

**Comment by tsnoam** [comment]
@JosXa 
> How about renaming the existing contrib to builtin?

I wouldn't rename `contrib/` dir to `builtin/` or any other name:
1. It's customary having distribution packaging conf/build-system under a directory called `contrib/`.
2. I don't want to suggest in any way that we see it as anything else than just `contrib`. 

> You mean ptb_contrib - dashes won't work

Good catch. Lets use underscore.

> I'm wondering if every sub-project could also have a dedicated extras definition for pip install. 
* I don't want to add an extras directive to the main project.
* I did think of skipping automatic dependency installation.
* But we may consider if we can add extras to the `ptb_contrib` package which will bring the dependencies of the real wanted module.
    * Anyway, we don't have to decide on that now. We can check it up later.

> Middleware would be a third

Whatever. Every contribution can be done differently, according to the need. 

> Automated linting, style, and type checks are a way to keep idiots out and the quality high. Might be a good idea to only allow contributions that pass rigorous automated checks...

I see your point, but I don't want to waste time on that. At least not at the start, I want to get this contrib repo going already.

>  This stuff gets me excited, I'm in.

I have no objection.

> No tests? That sounds crazy. No coverage alright, that's fine.

You're probably right. Meaning each module would have to come with its own tests.

**Comment by Bibo-Joshi** [comment]
Some minor comments:

**Package name:** `ptbcontrib` would be fine by me as underscores are discouraged by [PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names)
**Integration:**
* @JosXa What exactly do you mean by middleware? People keep showing me stuff from aiogram and I keep telling them that they can achieve that by adding a `TypeHandler(telegram.Update, callback)` to a low group, but I've never really understood what that term is supposed to mean exactly
* annotations are only a problem, when users mock stuff, as explained in my first post. I'd simply not encourage that. `message.new_method(…)` can be achieved with minimal less comfort as `new_method(message, …)`

**Modularity:** If we go for "one repo, multiple files", we might end up with situations like this:

| Commit | Status Contrib A | Status Contrib B |
|------|-----------------|------------------|
| 1      | Working          | Buggy               |
| 2      | Buggy             | unchanged        |
| 3      | unchanged     | Working             |

Now there is no commit I can checkout to have both A and B in a working status. This would not be the case, when everyone would host their on contrib, as proposed [here](https://github.com/python-telegram-bot/python-telegram-bot/issues/1912#issuecomment-708953786). Ofc having everything in one place has many upsides and I'm willing to accept this downside. Just felt like it should point it out …

**Comment by Bibo-Joshi** [comment]
Closing, as [ptbcontrib](https://github.com/python-telegram-bot/ptbcontrib) is now online and we can pick up any discussion there.
