### ISSUE TITLE
[BUG] missing required positional argument when using classes handlers

### ISSUE THREAD

**Issue by en0mia** [python-telegram-bot/python-telegram-bot#1915]
### Steps to reproduce
1. create a class, for example:
 ```python
class Commands():
    def __init__(self):
        pass

    def start(self, update, context):
        context.bot.send_message(chat_id=update.effective_chat.id, text='hello bro')
 ```
2. register a handler
```python
commandHandlers = Commands
handler = CommandHandler('start', commandHandlers.start)
dispatcher.add_handler(handler)
```
3. run the bot:
```python
updater.start_polling()
```

### Expected behaviour
I expect a message from the bot: 

> hello bro

### Actual behaviour
TypeError: start() missing 1 required positional argument: 'context'

### Configuration
**Operating System:** Debian 9

**Version of Python, python-telegram-bot & dependencies:** python 3.5.3, python-telegram-bot v 12.6.1

``$ python -m telegram``

### Logs
```
Traceback (most recent call last):
  File "[...]/python3.5/site-packages/telegram/ext/dispatcher.py", line 343, in process_update
    handler.handle_update(update, self, check, context)
  File "[...]/python3.5/site-packages/telegram/ext/handler.py", line 117, in handle_update
    return self.callback(update, context)
TypeError: start() missing 1 required positional argument: 'context'
```

**Comment by Poolitzer** [comment]
@en0mia you forgot to call the class in the register part. <code>commandHandlers = Commands()</code>

**Comment by en0mia** [comment]
> @en0mia you forgot to call the class in the register part. `commandHandlers = Commands()`

Thank you for the quick reply, that "fixed" it, is there a label "I'm a stupid donkey"? :rofl:

**Comment by Poolitzer** [comment]
@en0mia I would create one but then all the other maintainers are going to be mad. We will just silently close this and now one notices ;P

**Comment by en0mia** [comment]
> @en0mia I would create one but then all the other maintainers are going to be mad. We will just silently close this and now one notices ;P

Can I use the excuse of fatigue? It's 1 AM (Italy) and I've been working all the day :D.
Thanks for all, and... see you for the next issue :P
