### ISSUE TITLE
[FEATURE] API 4.8

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#1916]
#### Is your feature request related to a problem? Please describe.
API 4.8 support

#### Pure API changes
- [x] `Bot.send_poll`: `explanation`, `explanation_parse_mode`, 
- [x] `Poll.{explanation, explanation_entities, open_period, close_date}`
- [x] `Bot.send_dice`: `emoji` (for whatever reason, sending a 'darts' is considered a die now …
- [x] `Dice.emoji`

#### Convenience stuff
- [x] `Poll.parse_explanation_entity/ies`
- [x] `Filters.dice.dice` and `Filters.dice.darts` for filtering only the corresponding emojis. Allow the `Filters.dice.*([1, 2])` syntax for both

**Comment by Poolitzer** [comment]
@Bibo-Joshi Official docs don&#x27;t mention it, but a bullseye is a 6.

Maybe we should?

**Comment by Bibo-Joshi** [comment]
Closed by #1917
