### ISSUE TITLE
[BUG] Behaviour of kwargs in bot methods

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#1918]
### Steps to reproduce
Pass undocumented kwargs to a bot method

### Expected behaviour
The kwargs should either be passed along to the API or an error should be thrown

### Actual behaviour
The kwargs are just ignored

### Offline discussion (with @Poolitzer @tsnoam @n5y):
* just ignoring kwargs is not good
* we're not really comfortable with passing method kwargs to the API
* we still need class kwargs (being ignored), so api changes dont immediately break the code

Note that this goes again older decisions, see #733.

Before we go for an implementation, let's hear, what @Eldinnie thinks.

**Comment by Eldinnie** [comment]
I vouched before to just pass added kwargs to data to send (I believe there's at least some methods that do so).

**Comment by Poolitzer** [comment]
@Eldinnie okay, but it comes with the huge downside of swallowing misspelled parameters. why are you vouching for it? Not to mention that at least some other methods dont pass kwargs, so those ones are useless anyway

**Comment by Eldinnie** [comment]
@Poolitzer Everything should accept and pass kwargs. Misspelling is a user error that would not be different to now. If a user misspells an argument now it doesn;t error or work either

**Comment by Eldinnie** [comment]
@Poolitzer Oh, and the reason to vouch for it is that passing kwargs might make the library work with new api arguments whil we did not implement them yet.

**Comment by Poolitzer** [comment]
@Eldinnie if we dont accept them anymore, python would throw an error, that is the point of this idea if I understood it correctly

**Comment by Bibo-Joshi** [comment]
Possible compromise: Pass kwargs, but warn about them:

```
if kwargs:
  warnings.warn(f"{url.split("/")[-1]} got unexpected kwargs {", ".join(kwargs.keys())})
  data.update(kwargs)
```

**Comment by n5y** [comment]
@Eldinnie It might make the library work with new api occasionally, but not always. But it always silently swallows misspelled args, which is undesirable. 

There's an option to release a new version to add the new arguments. Perhaps a fast beta release without thoughtful testing. There's no way for a user to disable **kwargs hiding errors. 
I guess a warning would help somewhat. I'd say if there's actually a need to allow user to pass extra kwargs to the api, make it an explicit argument which expects a dict.

**Comment by Bibo-Joshi** [comment]
Update: Turns out the `**kwargs` are only ignored on the methods that call `Bot._message` and and most (all ?) other methods, there is in fact an `data.update(kwargs)`. So @tsnoam and @Eldinnie recalled correctly and I just didn't think of methods that don't call `Bot._message` …

But still, the `kwargs` behaviour of `Bot._message` needs fixing and I think it would be good to have the `data.update(kwargs)` at a single location in the code.

**Comment by Bibo-Joshi** [comment]
#1924 has been merged into v13, so I'll close this
