### ISSUE TITLE
ImportError: cannot import name Updater

### ISSUE THREAD

**Issue by ThomasMW** [python-telegram-bot/python-telegram-bot#192]
Just did a clean install of the telegram-bot.

When I'm trying to run my script I get the error:
ImportError: cannot import name Updater

I already found an issue here from December and it was stated it was fixed, but it seems it is not?

I installed v3.3 and am running python 2.7.

Anyone?

**Comment by tsnoam** [comment]
@ThomasMW 1. can you please send the full stack trace?
2. do you happent to be running from GAE?

**Comment by ThomasMW** [comment]
1. I tried to run the standard echobot2 from the examples. This is what I get.

````
Traceback (most recent call last):                                                                                                                  
  File "telegram.py", line 18, in <module>                                                                                                          
    import telegram                                                                                                                                 
  File "/home/TreeofPython/telegram/telegram.py", line 19, in <module>                                                                              
    from telegram import Updater                                                                                                                    
ImportError: cannot import name Updater 
````
2. I'm running from PythonAnywhere.

**Comment by jh0ker** [comment]
You don't happen to have a file called `telegram.py` or a directory called `telegram` in the same directory of the bot? That would make python import those instead of the installed library.

**Comment by ThomasMW** [comment]
Woops, totally overlooked.

Rookie mistake, I'll show myself out now..

**Comment by jh0ker** [comment]
No problem! :D

**Comment by Legend-of-Success** [comment]
hi... I'm getting something similar to this error but I can't find out the reason. I have installed the latest version of python-telegram-bot (v7.0.1) and this is my error:

Traceback (most recent call last):
  File "inline_query_test.py", line 21, in <module>
    from telegram import Updater, Update, InlineQueryResultArticle, ParseMode
ImportError: cannot import name Updater

**Comment by bomjacob** [comment]
Please don't resurrect old issues, please make a new one and make sure to fill out the template, thanks :)

**Comment by AntonyBrazzers** [comment]
from telegram.ext import Updater
