### ISSUE TITLE
[FEATURE] Add Attribute chat_id to InlineQuery

### ISSUE THREAD

**Issue by GnohChengYi** [python-telegram-bot/python-telegram-bot#1922]
I want to return results to inline queries specific to the effective chat and user, but there is no way to get the effective chat in the function used to handle the inline query.

I think it would be nice if you add the attribute 'chat_id' to the inline query.

I looked into everything inside Update and CallbackContext in the function used to handle the inline query, but it didn't work because everything related to chat is None. 
One approach that might work but I abandoned due to potential performance issues is: store the data in the dispatcher (with `context.dispatcher.chat_data['queue'].append(chat_id)`) as a list and handle them one by one.
Note that using `context.chat_data['chat_id'] = chat_id` stores the data in `dispatcher.chat_data` in the form of `{chat_id: {'chat_id': chat_id}}` which is not useful as I need to know the `chat_id` to access the information.

Thanks in advance for the feature! 
By the way, here is the bot the I am developing: https://t.me/MYSGBridgeBot

**Comment by Bibo-Joshi** [comment]
Hi. As per both the [official](https://core.telegram.org/bots/api#inlinequery) and [ptbs](https://python-telegram-bot.readthedocs.io/en/stable/telegram.update.html#telegram.Update.effective_chat) docs, an inline query simply has no originating chat.

**Comment by alrevuelta** [comment]
Understand that with the current design an inline query doesn't belong to any chat, but just ran into this issue. Would be a nice feature, just saying.

**Comment by Poolitzer** [comment]
You want this library to magically know something telegrams servers dont provide?

**Comment by alrevuelta** [comment]
As a user of the API I don't know what is under the hood, so no need to be sarcastic.

**Comment by Bibo-Joshi** [comment]
The API has no hood ;) It's all documented at https://core.telegram.org/bots/api . All PTB can do is build a python wrapper around that.

**Comment by Poolitzer** [comment]
Bibo also linked to both API and our docs, which both could have explained why that is just not possible. Thats why I assumed you would have read it and geniualy wanted to know if that is what you wanted :)
