### ISSUE TITLE
[BUG] I am unable to deploy telegram bot in Heroku

### ISSUE THREAD

**Issue by abdullahsaeed98** [python-telegram-bot/python-telegram-bot#1926]
### Issue I am facing
I am unable to deploy telegram bot in Heroku

### Traceback to the issue
```
 "at=error code=H10 desc="App crashed" method=POST path="/TOKEN" host=whispering-bayou-97861.herokuapp.com request_id=a32791d3-1e10-4e8c-9809-8cc1505cd9e6 fwd="91.108.6.90" dyno= connect= service= status=503 bytes= protocol=https"
```

### Related part of your code

``` python
import logging,os

from telegram.ext import Updater, CommandHandler, MessageHandler, Filters


logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    level=logging.INFO)

logger = logging.getLogger(__name__)



def start(update, context):

    update.message.reply_text('Hi!')


def help(update, context):

    update.message.reply_text('Help!')


def echo(update, context):

    update.message.reply_text(update.message.text)


def error(update, context):

    logger.warning('Update "%s" caused error "%s"', update, context.error)


def main()
    TOKEN=" "
    updater = Updater(TOKEN, use_context=True)
    PORT = int(os.environ.get('PORT', '8443'))
    updater.start_webhook(listen="0.0.0.0",
                      port=PORT,
                      url_path=TOKEN)
    updater.bot.set_webhook("https://xyz.herokuapp.com/" + TOKEN)


    dp = updater.dispatcher

 
    dp.add_handler(CommandHandler("start", start))
    dp.add_handler(CommandHandler("help", help))


    dp.add_handler(MessageHandler(Filters.text, echo))

    # log all errors
    dp.add_error_handler(error)


    updater.start_polling()


    updater.idle()


if __name__ == '__main__':
    main()
```

**Comment by Eldinnie** [comment]
please show the output for 
`heroku logs -d web.1 --app <yourappname>`

**Comment by abdullahsaeed98** [comment]
> please show the output for
> `heroku logs -d web.1 --app <yourappname>`

2020-04-27T18:27:59.955549+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/MY TOKEN" host=whispering-bayou-97861.herokuapp.com request_id=eb9d48eb-6c2f-41be-afc1-48b27af40ea9 fwd="91.108.6.90" dyno= connect= service= status=503 bytes= protocol=https

**Comment by Eldinnie** [comment]
that does not seem right for the output for the command I requested. This is a `router` message, not `web.1`

**Comment by abdullahsaeed98** [comment]
> that does not seem right for the output for the command I requested. This is a `router` message, not `web.1`

it is returning me nothing.
![image](https://user-images.githubusercontent.com/56201080/80407852-b3921000-88df-11ea-8c67-07d377fb340a.png)

**Comment by JosXa** [comment]
I see a `start_polling` here which is unnecessary (since you're using webhooks).

**Comment by Eldinnie** [comment]
right. That's a problem for sure :D
