### ISSUE TITLE
Change debug level of telegram.bot

### ISSUE THREAD

**Issue by Scinawa** [python-telegram-bot/python-telegram-bot#193]
Hi,
Why the level of the message "No new updates found" is set do INFO and not to DEBUG?

I think it could be more appropriate, since half of my log are what I would consider as "DEBUG" messages. 

Am I wrong?

**Comment by jh0ker** [comment]
@Scinawa It should actually be in DEBUG since v3.3, have you tried updating?

**Comment by taemery** [comment]
Issue #167 changes this message to debug in this commit [Here](https://github.com/python-telegram-bot/python-telegram-bot/commit/6d2e159d75492444c9343d0793c46c843b5182db)

**Comment by Scinawa** [comment]
Well maybe also "Running job xxxx" can do the same?

**Comment by leandrotoledo** [comment]
> Well maybe also "Running job xxxx" can do the same?

Agree.

**Comment by leandrotoledo** [comment]
In fact we may want to change all .info() to .debug()

It's worth the read:
http://pythonsweetness.tumblr.com/post/67394619015/use-of-logging-package-from-within-a-library

**Comment by leandrotoledo** [comment]
PR #204 has been pushed for this change. Pending code review.

**Comment by leandrotoledo** [comment]
#204 has been merged, closing this one.
