### ISSUE TITLE
[BUG] Markdown parse mode no longer works

### ISSUE THREAD

**Issue by hildebro** [python-telegram-bot/python-telegram-bot#1930]
### Steps to reproduce
```
MESSAGE = 'some string with *bold* text '

def handle_start_command(update, context):
    update.message.reply_text(MESSAGE, parse_mode='Markdown')
```

### Expected behaviour
When the handler is called, the word bold should be styled as bold.

### Actual behaviour
The word is not bold.

### Configuration
**Operating System:**
Arch Linux
**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 12.6.1
certifi 2020.04.05.1
future 0.18.2
Python 3.8.2 (default, Apr  8 2020, 14:31:25)  [GCC 9.3.0]

### Info
This happens for both Markdown as well as MarkdownV2. Putting unescaped characters into a MarkdownV2 string will cause an exception as expected. Providing the valid example `MESSAGE` you can see above, will not cause an exception, but the bold text is not applied regardless.

**Comment by Bibo-Joshi** [comment]
Hi. I can't reproduce the issue (same configuration, except on Windows). Have you tried with monowidth or italics? See #1901

**Comment by hildebro** [comment]
seems like my font doesn't distinguish between normal and bold too well...
