### ISSUE TITLE
How to reply to messages forwarded from users who disallow adding a link to their account in forwarded messages?

### ISSUE THREAD

**Issue by sarvarolimjon** [python-telegram-bot/python-telegram-bot#1934]
#1933 Issue I am facing

My bot forwards messages it has got from other users to me. I reply to them. When I try to reply to messages forwarded from users who disallow adding a link to their account in forwarded messages, I get error. 

### Traceback to the issue
```
NoneType' object has no attribute 'id'
```

### Related part of your code
```
def reply_and_confirm(update, context):
    chat_id = update.message.chat_id
    sender_id = update.message.reply_to_message.forward_from.id
    if chat_id == request_id:
        reply = update.message.reply_to_message
        if reply:
            logger.info('reply')
            context.bot.send_message(
                chat_id = sender_id,
                text = 'Ответ оператора:\n\n' + update.message.text,
                reply_markup = accept_button()),
        else:
            logger.info('nothing')
        pass
    else:
        pass

```

**Comment by Eldinnie** [comment]
The bot will have to stay aware of which message came from which user (since the bot warwarded it, it should know from which user it came.) You will need a data storage. For example use `chat_data`

**Comment by Bibo-Joshi** [comment]
Probably `bot_data` will be more approriate, as you will have to

* save the info about the sender in a callback, where the `effective_chat` is the sender
* access that info in a callback, where the `effective_chat` is you

**Comment by Eldinnie** [comment]
@Bibo-Joshi I would suggest linking the message I&#x27;d from the forwarded message to the user id it came from. Bot_data send best indeed.

**Comment by sarvarolimjon** [comment]
> Probably `bot_data` will be more approriate, as you will have to
> 
> * save the info about the sender in a callback, where the `effective_chat` is the sender
> * access that info in a callback, where the `effective_chat` is you

Thank you! It worked. I have been trying this with user_data, which didn't work

**Comment by sarvarolimjon** [comment]
> @Bibo-Joshi I would suggest linking the message I'd from the forwarded message to the user id it came from. Bot_data send best indeed.

How it's done? Without linking bot replies only to the last user texted to the bot:(

**Comment by Bibo-Joshi** [comment]
On forwarding a message to yourself from chat_id just do

```python
message = bot.forward_message(...) #dont know the exact function name right now
context.bot_data[message.message_id] = chat_data.
```

That way, when you reply to a forwarded message you get the original user by looking up the message id in the bot_data
