### ISSUE TITLE
Refactor JobQueue

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#1936]
#### Is your feature request related to a problem? Please describe.
Maintaining `JobQueue` is not easy and sometimes error prone, see e.g. #1338 

#### Describe the solution you'd like
We could refactor `JobQueue` to use a third party library for the scheduling, keeping the `run_*` methods as wrappers. We should probably also add a `run_cron` as suggested in #1337 as convenience wrapper for all the other cases we can't all cover (like run a job every time mars and saturn align …)

#### Describe alternatives you've considered
Just implement `run_cron` would be a first step.

**Comment by Bibo-Joshi** [comment]
I did a bit looking around and to me it seems that we basically have 3 options here:

* **Pythons `sched`**
  Advantages: standard lib, so well maintained and reliable
  Disadvantages: Only has very basic functionality, e.g. no recurring events. So we'd still have to do much of the work ourselfes
* **Third party [`schedule`](https://schedule.readthedocs.io/en/stable/index.html)**
  Advantages:
  * Easy to use internally, and externally, i.e. if a user wants a very specific job pattern they could do e.g. `job_queue.every().wednesday.at("13:15").do(job)`
  * Lightweight
  * around since 2013

  Disatvantages:
  * Tested only with py 2.7, 3.5, 3.6
  * Not veriy actively maintained (current version is 0.6.0, last commit 08/2019)
* **Third party [`APScheduler`](https://apscheduler.readthedocs.io/en/stable/index.html)**
  Advantages:
  * extensive functionality (comes with a cron interface, several persistence options (with databases), has a Asyncio scheduler, …)
  * tested with py 3.4-3.7 (we're only missing 3.8)
  * around since 2009

  Disatvantages:
  * THB I don't see any


If we're okay with adding a third party lib for the scheduling, i'd vote for APS, from my first impression.

**Comment by KellyHwong** [comment]
> I did a bit looking around and to me it seems that we basically have 3 options here:
> 
> * **Pythons `sched`**
>   Advantages: standard lib, so well maintained and reliable
>   Disadvantages: Only has very basic functionality, e.g. no recurring events. So we'd still have to do much of the work ourselfes
> * **Third party [`schedule`](https://schedule.readthedocs.io/en/stable/index.html)**
>   Advantages:
>   
>   * Easy to use internally, and externally, i.e. if a user wants a very specific job pattern they could do e.g. `job_queue.every().wednesday.at("13:15").do(job)`
>   * Lightweight
>   * around since 2013
>   
>   Disatvantages:
>   
>   * Tested only with py 2.7, 3.5, 3.6
>   * Not veriy actively maintained (current version is 0.6.0, last commit 08/2019)
>   * No native support for different timezones
> * **Third party [`APScheduler`](https://apscheduler.readthedocs.io/en/stable/index.html)**
>   Advantages:
>   
>   * extensive functionality (comes with a cron interface, several persistence options (in memory/with databases), has a Asyncio scheduler, …)
>   * can handle timezones
>   * tested with py 3.4-3.7 (but supports 3.6-3.8?!)
>   * around since 2009
>   
>   Disatvantages:
>   
>   * THB I don't see any
> 
> If we're okay with adding a third party lib for the scheduling, i'd vote for APS, from my first impression.

I bet APScheduler. As a Python programmer, I prefer a functional library, clearly APScheduler's API is more readable.

**Comment by Bibo-Joshi** [comment]
#1981 has been merged into v13, so I'll close this
