### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by imnotadeveloper** [python-telegram-bot/python-telegram-bot#1945]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
![Untitled](https://user-images.githubusercontent.com/39151564/81058211-9e684300-8ed6-11ea-983c-dffd5f37b61d.png)

![Untitled](https://user-images.githubusercontent.com/39151564/81066815-5b15d080-8ee6-11ea-9185-5b3a2d2df441.png)

2. What OS are you using?
Windows 10

3. What version of python are you using?
![Untitled](https://user-images.githubusercontent.com/39151564/81058523-45e57580-8ed7-11ea-8e8e-6f62799807fe.png)

```
Traceback (most recent call last):
  File "c:/Users/USER/Desktop/instonline/instonline/main.py", line 8, in <module>
    from telebot import apihelper
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\apihelper.py", line 20, in <module>
    logger = telebot.logger
AttributeError: module 'telebot' has no attribute 'logger'
```

I try this:

> pip uninstall telebot
> pip install pyTelegramBotAPI

But it doesnt help

Also i delete and install Python again - doesnt help

**UPD:** Maybe this cause, because telebot have 0.0.3. version and requests have 2.23.0 vesion, BUT telebot require requests 2.7.0 version

**UPD 2:** I have used "apihelper" one time, BUT this line of code is commented and not used

**UPD 3:** Intslling this package "pip install python-telegram-bot --upgrade" also doenst help. From here: https://github.com/python-telegram-bot/python-telegram-bot 

UPD 4: While installing this package "pip install logging" it gives me big red code lines error

**Comment by Bibo-Joshi** [comment]
This is the issue tracker for python-telegram-bot, not for [pyTelegramBotAPI](https://github.com/eternnoir/pyTelegramBotAPI). These are two different python packages.
