### ISSUE TITLE
How can I access context in custom filter?

### ISSUE THREAD

**Issue by pirey** [python-telegram-bot/python-telegram-bot#1946]
I want to add message handler without filter for "starting" the bot, I call it the "start_handler".
For example, user can send whatever text in the begining, and bot will call start_handler.

But I also have some other conversation handler, e.g for registration, edit profile, etc.
Right now the handler is conflicted, that is when I'm inside a conversation handler, the start_handler is called instead of convo handler.

I have an idea to work around this by setting chat_data to tell the bot that user is in a conversation handler, so the start_handler can be skipped.

So I want to create custom filter, but is there a way i can access the context.chat_data from inside the custom filter?

**Comment by Eldinnie** [comment]
Hi,
No there is no way for that.
The way you could achieve this is put the start_handler and the ConversationHandler in [different groups](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.dispatcher.html#telegram.ext.Dispatcher.add_handler). and raise [DispatcherHandlerStop](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.dispatcherhandlerstop.html#telegram.ext.DispatcherHandlerStop) in the starthandler if you don;t want the conversationhandler to pick it up aswell.
