### ISSUE TITLE
How can I know how many messages has been sent to my bot in one time?

### ISSUE THREAD

**Issue by YHporkar** [python-telegram-bot/python-telegram-bot#1948]
I wanna get count of messages has been forwarded to my bot.
As I know if I send several message to the bot in one time, the bot processes them sequentially. 
any solution?

**Comment by Bibo-Joshi** [comment]
Hi. You'll need to keep track of the messages yourself, e.g. for each message store the sending date in `bot_data`, something along the lines of

```python
msg = update.message
context.bot_data['{} {}'.format(msg.chat.id, msg.message_id)] = msg.date
```
Then, when you want to know, how many messages have been sent in a given time interval, just check for all stored messages, if the stored date is in that interval.

**Comment by YHporkar** [comment]
it's OK. actually I have a bot. user is gonna forward to it several messages in one time. some processes will apply on messages and after all processes done, I want to send the user a message like 'every thing done'. 
So I have to know the count of messages first of all... HOW?

**Comment by Bibo-Joshi** [comment]
No clean way to do that without telling the bot to wait for forwarded messages beforhand. How else should he know that you're actually done? You can use the ConversationHandler to do something like
1. `/forward_messages` -> Bot waits for forwarded messages
2. forward the messages, bot processes them
3. `/done` -> tells the Bot that no more forwarded messages will be incoming, Bot can do some calculations and respond

You could try and set up a job that runs at `forwarded messgase received + 1s`, but I don't know how the receiving times behave, if you forward a large number of messages at once.
