### ISSUE TITLE
[BUG] inline keyboard always disappear after click on button

### ISSUE THREAD

**Issue by ivanDonadello** [python-telegram-bot/python-telegram-bot#1949]
### Steps to reproduce
I just  want to run this [example](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/inlinekeyboard.py)
1. Download the example
2. put a token
3. run it

### Expected behaviour
The inline keyboard shouldn't disappear.

### Actual behaviour
The inline keyboard disappear even with if I set ``one_time_keyboard=False``.

### Configuration
**System: OSX 10.9.5 **

**Version of Python, python-telegram-bot & dependencies:**

``python-telegram-bot 12.7``
``certifi 2020.04.05.1``
``future 0.18.2``
``Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]``

Thanks for the attention

**Comment by Bibo-Joshi** [comment]
That's actually, what the example is supposed to do. For an advanced example on inline keyboards, used to build menus, see [inlinekeyboard2.py](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/inlinekeyboard2.py).

Two more notes:
* `one_time_keyboard` is only for `ReplyKeyboardMarkups`, not `InlineKeyboardMarkups`
* If you edit a message and want the inline keyboard to stay, you'll need to pass it again as `reply_markup` to the `edited_message_*` method

**Comment by ivanDonadello** [comment]
Thank you very much @Bibo-Joshi
