### ISSUE TITLE
[QUESTION] Is it possible to run a webhook on top of reverse proxy with plain IP and nonstandard port?

### ISSUE THREAD

**Issue by moonbaseDelta** [python-telegram-bot/python-telegram-bot#1950]
Hello guys, I've found that if I do like this 
```
...
updater.start_webhook(listen='0.0.0.0', port=7865, url_path=TOKEN)
updater.bot.set_webhook(url=f'https://<server_ip>:7865/{TOKEN}', 
                                       certificate=open('cert.pem', 'rb'))
...
``` 
then PTB tells me that only ports 8443, 433, 88, 80 are allowed. 

Is that a limitation of the library, or I just don't get the meaning of start_\set_webhook functions?

The goal was to set up nginx server on a port, say 7865, on plain IP (so that FQDN is like just 192.192.192.192) and then redirect the traffic to tokens-paths.

**Comment by Bibo-Joshi** [comment]
Hi. I'm not an expert on that, but have you seen our [wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks#reverse-proxy--integrated-webhook-server)?

**Comment by moonbaseDelta** [comment]
Yes, I've read it. There's no examples with plain IP, only domains.
 
With that setup (modified from the wiki with ip+port instead of domain)
```
updater.start_webhook(listen='127.0.0.1', port=5000, url_path='TOKEN1')
updater.bot.set_webhook(webhook_url='https://<server_ip>:1234/TOKEN1',
                        certificate=open('cert.pem', 'rb')
```
I got error about ports.

While this works fine:
```
 updater.start_webhook(listen='0.0.0.0',
                            port=443,
                            url_path=TOKEN,
                            key='private.key',
                            cert='cert.pem',
                            webhook_url=f'https://<server_ip>:443/{TOKEN}')
```

**Comment by jh0ker** [comment]
Available ports are a telegram limitation, see https://core.telegram.org/bots/api#setwebhook

You can of course set up the webhook server to use a different port if you reverse proxy through nginx, as long as nginx listens on one of those ports. Then you set the webhook to target nginx and you should be good to go. 

Let me know if you have further questions.

**Comment by moonbaseDelta** [comment]
Thanks, now all working! (also it turns out that `url_path` is required for at least nginx case) 

```
updater.start_webhook(listen='127.0.0.1', port=WEBHOOK_PORT, url_path=TOKEN)
updater.bot.set_webhook(url=f'https://<server IP>:<port 80, 88, 443 or 8443>/{TOKEN}',
                certificate=open('cert.pem', 'rb'))
```

So with that and nginx config simular to wiki's one (but without `server_name` specified) a bot works supposed.
