### ISSUE TITLE
[QUESTION]How to stop ConversationHandler with a button...

### ISSUE THREAD

**Issue by Beppe1988** [python-telegram-bot/python-telegram-bot#1952]
### Issue I am facing
Hi to all. I have a trouble with a ConversationHandler with some state. For every state there are a MessageHandler with Filter.text. I want to add for every state a CallbackQueryHandler that close the conversation when I click on the "cancel" button of relative InlineKeyboard. 

I Tried this solution:
```python
  self.STATE1: [MessageHandler(callback=self.state1, filters=Filters.text),
                              CallbackQueryHandler(self.cancel)]
```
but the program wait only the message update and ignore the button.

Why?

I'm using python-telegram-bot v 12.7

Thanks.

**Comment by Bibo-Joshi** [comment]
Hi. Please provide sufficient information, i.e. a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example). At this point, my best guess is that the `CallbackQuery` is handled by another `CallbackQueryHandler`.

As a side note: Using GitHubs Markdown capability to format code makes things more readible. I went ahead and edited your snippet.
