### ISSUE TITLE
[QUESTION ]Is it possible to know and store the users who are online?

### ISSUE THREAD

**Issue by willgf84** [python-telegram-bot/python-telegram-bot#1953]
Hi!!

I would like to know if it is possible to know the users who are online in a group at a specific time. Or if it's possible to know the last seen of all the user of a group (ordered)

Thanks!

**Comment by Bibo-Joshi** [comment]
Hi. PTB can only wrap, what the [API](https://core.telegram.org/bots/api) provides. As the API doesn't provide a method to get the online status of users, the answer is no.

**Comment by willgf84** [comment]
Thank!

And could you get a list of the latest active users?

**Comment by Bibo-Joshi** [comment]
> PTB can only wrap, what the [API](https://core.telegram.org/bots/api) provides.

Please read the official docs before asking here ;)
