### ISSUE TITLE
forwarding message from a channel

### ISSUE THREAD

**Issue by YHporkar** [python-telegram-bot/python-telegram-bot#1956]
`update.message.bot.forward_message(chat_id=update.message.chat.id, from_chat_id='@' + channel_username, message_id=message_id)`

message_id is forward_from_message_id of the message. but it doesn't work.
message exists in the channel
ERROR:
> telegram.error.BadRequest: Message to forward not found

**Comment by Bibo-Joshi** [comment]
1. Please fill out the entire issue template. it's there for a reason
2. either the `chat_id` or the `message_id` is wrong. without minimal working example, there is no way to tell, why. You'll need to figure out that yourself
3. You can use [`Message.forward()`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html#telegram.Message.forward) as shortcut

**Comment by YHporkar** [comment]
I want to forward a message from a channel, and Message.forward() is for forwarding a message that user sends to another chat. 
I don't know what happens. even when I give static values to args of forward_message I have the same error.

**Comment by Bibo-Joshi** [comment]
> I want to forward a message from a channel, and Message.forward() is for forwarding a message that user sends to another chat.

Channel posts are just `Message` objects. If your bot recieves them as update, you should be able to forward them with the shortcut.

> I don't know what happens. even when I give static values to args of forward_message I have the same error.

"without minimal working example, there is no way to tell, why."

**Comment by YHporkar** [comment]
what do you mean by minimal working example

**Comment by Bibo-Joshi** [comment]
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by YHporkar** [comment]
assume that when the user started the bot, I just want to forward a single message from a specified channel to him. this is all I want.

my start function is something like this:
`def start(update, context):
    update.message.bot.forward_message(chat_id=update.message.chat.id,
                                       from_chat_id='@MemesMasters', message_id=6203)`

**Comment by Bibo-Joshi** [comment]
I see. Bots can only forward messages from chats they are in. As bots can join channels only as admin, your bot would need to an admin in that chat. If you want to forward always the exact same message, I'd suggest to just copy the text or for media messages, get the `file_id` of the file for your bot and send it by that.

Apart from that, the `bot` instance is available as `context.bot`, so you don't have to do the lengthy `update.message.bot`
