### ISSUE TITLE
handle forwarding album message

### ISSUE THREAD

**Issue by YHporkar** [python-telegram-bot/python-telegram-bot#1958]
when I forward a message containing album, looks like I forwarded multiple messages and my bot try to process every single elements of album. and I saw there is a specific url for every element of album.

is there anyway to tell my bot it's a single message?

**Comment by Bibo-Joshi** [comment]
As far as I know, album messages are in fact multiple messages, that are just displayed a bit nicer. That.'s why `send_media_group` returns a list of messages and not a single one. However, each of those messages will have a `media_group_id` (see [here](https://core.telegram.org/bots/api#message)), so you could try and make your bot treat messages with the same `media_group_id` as "single message". [`chat/bot_user_data`](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Storing-bot,-user-and-chat-related-data) will be helpfull.
