### ISSUE TITLE
Job Queue - Storing Backup Jobs

### ISSUE THREAD

**Issue by geffeh** [python-telegram-bot/python-telegram-bot#1959]
In the timerbot.py example. There is this block of code that I adapted to handle deleting backup jobs if the earlier job is fulfilled. However, this conflicts with persistence of chat_data as it cannot save job information.
```# Add job to queue and stop current one if there is a timer already
        if 'job' in context.chat_data:
            old_job = context.chat_data['job']
            old_job.schedule_removal()
        new_job = context.job_queue.run_once(alarm, due, context=chat_id)
        context.chat_data['job'] = new_job
```
What can you suggest I do to handle storing of job information (so that I can edit or delete later on) and not conflict with persistence?

**Comment by Bibo-Joshi** [comment]
Please see [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#save-and-load-jobs-using-pickle).

**Comment by geffeh** [comment]
For this execution, how would you be able to identify and delete a specific (backup) job?

**Comment by Bibo-Joshi** [comment]
I don't really get, what you mean. But identifying jobs is best done with the jobs name, which you can use to [get the job](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.jobqueue.html#telegram.ext.JobQueue.get_jobs_by_name) from the JobQueue.
