### ISSUE TITLE
Trying to send photos, can't manage

### ISSUE THREAD

**Issue by GabrieleAnsaldo** [python-telegram-bot/python-telegram-bot#1960]
### Issue I am facing
I am trying to adapt the example echobot.2 to my needs. Here is the example code (https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/echobot2.py). So basically I want to add a new command that would send a photo I have saved on my computer. I was trying to add this but it doesn't works:

### Related part of your code
```python
def photo_to_send(update, context):
    """Send photo when command /photo is issued."""
    pic = '/Users/me/Desktop/photo.png'
    update.message.send_photo(open(pic, 'rb'))
```

In main I then add this:

```python
dp.add_handler(CommandHandler("photo", photo_to_send))
```

Anyone that could help me?

Thanks so much

**Comment by Bibo-Joshi** [comment]
We have an exapmle on how to send files/photos in the code snippets section of the GitHub Wiki. Please have a look there.

**Comment by GabrieleAnsaldo** [comment]
Thanks for the hint @Bibo-Joshi, I am new to python and telegram bot, and I actually tried to add that line to my code but it didn't work for me. 
I copy pasted this

```python
bot.send_photo(chat_id=chat_id, photo=open('tests/test.png', 'rb'))
```
 but it gives an error. What am I missing?

**Comment by Bibo-Joshi** [comment]
If you're new to python in general, you might wanna read up on some tutorials. You can find a list in our Telegram help group (see the readme if this repo).

If you get an error, you'll need to provide at least the full error traceback for someone to help you, as "an error" is not very specific ;) of course, you'll need to replace the file path with the file path of your photo.
