### ISSUE TITLE
Human-friendly Conversation Persistence

### ISSUE THREAD

**Issue by paulthemagno** [python-telegram-bot/python-telegram-bot#1964]
I'm using a [ConversationHandler](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/conversationhandler.py) and I would like to **store all the conversations in a different file depending on the day**. I found a possible solution [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Making-your-bot-persistent) using [PicklePersistence](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/picklepersistence.py).
I obtained a pickle file I cannot understand: I'd like to have uhman-readable file with a format like this "_user id XXXX pressed button YYY_" or something similar. How can I read this pickle file or how can I obtain this kind of result?

**Comment by Bibo-Joshi** [comment]
Persisting conversations only stores the current state of a conversation (for each user/chat/...), so when the bot restarts, the conversation may be continued at that state. If you want to have detailed information about the progress of a conversation, you'll need to keep track of that yourself, e.g. with `user/chat/bot_data`.
