### ISSUE TITLE
 Can't parse entities: can't find end of the entity starting at byte offset 6643

### ISSUE THREAD

**Issue by YHporkar** [python-telegram-bot/python-telegram-bot#1967]
I want to send a post caption like below url to the user but I had the above error.
https://t.me/I_D_Network/4710?embed=1
my code:
`update.message.reply_text(caption, parse_mode=ParseMode.MARKDOWN)

why this error occured?

**Comment by YHporkar** [comment]
I know it's because of ParsMode but why and what is solution?

**Comment by Bibo-Joshi** [comment]
The error message says that you caption text is no valid markdown. Could be that you need to escape something (use `helpers.util.escape_markdown`) for that.
On a side note, you should use MarkdownV2, as Markdown is legacy mode now.
Also, please fill out the __entire__ issue template next time.
