### ISSUE TITLE
Are there code examples of using base persistence to store data into a database like MySQL?[QUESTION]

### ISSUE THREAD

**Issue by helpme1** [python-telegram-bot/python-telegram-bot#1970]
I would like to use a database like MySQL to collect user information. Base persistence seems to be the way to go. 
https://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.basepersistence.html

However, I am not able to find any example for using base persistence in this way. Are there source code examples of using base persistence to store data into a database like MySQL?

Thank you,

**Comment by Bibo-Joshi** [comment]
PTB doesn't provide an example of persistence with databases, as this beyond the scope of this project. You'd have to subclass `BasePersistence` yourself for that. However, you are welcome to ask in the users group (see readme of this repo), if some has experience with that.

**Comment by tsnoam** [comment]
@helpme1 Whether you accomplish the task, we invite you to add references in our wiki. It will be highly appreciated.

**Comment by helpme1** [comment]
> @helpme1 Whether you accomplish the task, we invite you to add references in our wiki. It will be highly appreciated.

If I managed to, I'll be happy to contribute to open-source.
One question to the experts here. I compared pickle persistence with base persistence. The methods are the same for both classes. Would it be a good start if I look at how picklepersistence implements persistence as a guide to implementing base persistence with MySQL? I'm at a loss how to start. I'm not familiar with python classes and have never coded stuff with them before. 
https://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.picklepersistence.html
https://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.basepersistence.html

**Comment by Bibo-Joshi** [comment]
>  The methods are the same for both classes. Would it be a good start if I look at how picklepersistence implements persistence as a guide to implementing base persistence with MySQL?

Sorry for the late repy. The methods are the same, because `BasePersistence` is an abstract base class, which `PickelePersistence` implements. I.e. Every class that implements all methods of `BasePersistence` can be used as persistence in PTB. Whether looking at PP helps for MySQL, I can not tell …
