### ISSUE TITLE
How to connect bot with database

### ISSUE THREAD

**Issue by Rune28** [python-telegram-bot/python-telegram-bot#1971]
I am trying to build a bot that is getting user input.

Is there any simple example how to connect bot with database? 
Could I use CommandHandler with comand for parsing input and write it to database?

**Comment by Bibo-Joshi** [comment]
Please see [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Making-your-bot-persistent), [[here](https://github.com/python-telegram-bot/python-telegram-bot/tree/master/examples)] and #1970
