### ISSUE TITLE
[FEATURE] support class callback

### ISSUE THREAD

**Issue by amrhgh** [python-telegram-bot/python-telegram-bot#1975]
#### Describe the solution you'd like
I'd like to contribute to this project. some times a callback can be complicated and I think it would much better to support class base callback to keep code clean by using power of classes. 
I have used this feature in my personal project and it was effective.

**Comment by Bibo-Joshi** [comment]
Hi. Can you elaborate the problem and give a minimal code example of what you're suggesting? Your description is not really clear (to me).

**Comment by tsnoam** [comment]
@amrhgh I don&#x27;t see how a class base callback should be different than a normal function.
Just add <code>__call__</code> method which has self and the other required parameters like a normal callback function.

**Comment by amrhgh** [comment]
in my project, I have two problem:

1- usually, what callbacks do is similar, get message, process data and send message, but for different type have to behave differently for example for text use message.text to get data and using bot.send_message to send text message and for voice using message.voice, thus should define multi handler for almost same work. function callbacks can increase duplication

2- sometimes the logic of the project is very complicated and should divided to smaller function and
it's hard to decide which parameters should be passed, with class base callbacks can keep this data as object attributes.

**Comment by tsnoam** [comment]
@amrhgh 
As mentioned above, just implement `__call__()` and then a class instance can be callable.

**Comment by tsnoam** [comment]
https://docs.python.org/3/reference/datamodel.html#object.__call__

**Comment by amrhgh** [comment]
thought about it more and realize maybe this scenario might not so common to add as feature.
thanks for your time.
