### ISSUE TITLE
[QUESTION] Daily job queue

### ISSUE THREAD

**Issue by its-K** [python-telegram-bot/python-telegram-bot#1976]
i am making a bot that sends message at particular time daily . After reading the docs i cant make it. So somebody could help me with a code that sends mesage at 12 pm daily in python

**Comment by Poolitzer** [comment]
@its-K Wiki of <i>python-telegram-bot</i>
<a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-JobQueue">Extensions ➜ Job Queue</a>

**Comment by Poolitzer** [comment]
@Poolitzer Did you read this article?

**Comment by its-K** [comment]
I read it. But i am a newbie and couldnt make it . A simple code woulld be helpful
