### ISSUE TITLE
Send message without admin priviledges

### ISSUE THREAD

**Issue by Gennttii** [python-telegram-bot/python-telegram-bot#1979]
Hi guys, I searched all day but couldn't find this.

I need to send messages with as a bot or as a member in groups that I don't have admin priviledges, is this possible..?

Thanks in advance for any help..

**Comment by Bibo-Joshi** [comment]
If you can't add your bot to the group, you can't send messages by the bot directly, no.
You can however use the inline mode to send messages _via_ the bot
