### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by basavaraj1995** [python-telegram-bot/python-telegram-bot#1984]
### Issue I am facing
How to call a callback without a user update?

```
def call_back1(update, context):
          .
          .
          .
           return CALL_BACK2

def call_back2(update, context):
         .
         .
         .
         .
         return CALL_BACK3

```

**Comment by Bibo-Joshi** [comment]
Two options depending on what you want to do:

1. Schedule a job with `JobQueue` (see [wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-–-JobQueue))
2. If what you want to do is not really realated to getting updates (e.g. you have a simple script that just sends a message), you don't have to use the updater logic at all. Just do `bot = Bot('token')` and the `bot.send_message(...)` or whatever.

For a more specific answer, you'd need to be more specific about your problem.

**Comment by basavaraj1995** [comment]
Thanks for the quick reply,

From the above example how to call the second function (call_back2) without getting a reply from the user for the first function (call_back1)?

**Comment by Bibo-Joshi** [comment]
If you just want to call `address` after `name`, you can you do

```python
def name(update, context):
    user = update.message.from_user

    address(update, context)

    return ADRESS
```

But this looks like you're actually looking for [`ConversationHandler`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.conversationhandler.html), see also the examples section.

**Comment by basavaraj1995** [comment]
if the function is CallbackQueryHandler then we cannot do it, right?

```
def button(update, context):
    chat_id = update.callback_query.message.chat_id
    query = update.callback_query
    query.answer()
    context.bot.send_message(chat_id, text="Selected option: {}".format(query.data))

    address(update, context)
    # return ADDRESS
```

For this kind of situation what to do?

**Comment by Bibo-Joshi** [comment]
`Update.effective_message` will help.

If you have more questions, please join us in the [users group](https://telegram.me/pythontelegrambotgroup), as this bug tracker is not intended for complete walk-troughs ;)

**Comment by basavaraj1995** [comment]
Thank you 👍
