### ISSUE TITLE
Update a CallbackQuery with photo

### ISSUE THREAD

**Issue by paulthemagno** [python-telegram-bot/python-telegram-bot#1985]
I'm developing a ConversationBot in which the user has to press buttons of an [InlineKeyboardMarkup ](https://python-telegram-bot.readthedocs.io/en/stable/telegram.inlinekeyboardmarkup.html)to make choices.
So I catch every user's answer with a [CallbackQueryHandler](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.callbackqueryhandler.html?) and every time I want to send a message from bot, I update the previous one with the method [edit_message_text](https://python-telegram-bot.readthedocs.io/en/stable/telegram.callbackquery.html#telegram.CallbackQuery.edit_message_text) of [CallbackQuery ](https://python-telegram-bot.readthedocs.io/en/stable/telegram.callbackquery.html):
```python
update.callback_query.edit_message_text(message, reply_markup=reply_markup, parse_mode=ParseMode.HTML)
```
The problem I'm facing is to **insert a photo, updating the previous message which has no photo**, but only text.

I found on the web this pull request: #1392. Anyway I found out [CallbackQuery ](https://python-telegram-bot.readthedocs.io/en/stable/telegram.callbackquery.html) isn't integrated yet with the method `edit_message_media`, beacuse it's a method of [Bot  ](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html). So I replicated the code of this issue using Bot method inspired by the issue #653 (to insert a photo) and I tried to do in this way:
```python
def method(update,context):
    image = open('/path/to/image.jpg', 'rb')
    bot.edit_message_media(chat_id=update.callback_query.message.chat_id,
                                message_id=update.callback_query.message.message_id, media=InputMediaPhoto(media=image))
...
```

But I got this error:
```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/ext/dispatcher.py", line 390, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/ext/conversationhandler.py", line 462, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/ext/handler.py", line 117, in handle_update
    return self.callback(update, context)
  File "conversation.py", line 311, in method
    message_id=update.callback_query.message.message_id, media=InputMediaPhoto(media=image))
  File "<decorator-gen-29>", line 2, in edit_message_media
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/bot.py", line 1979, in edit_message_media
    return self._message(url, data, timeout=timeout, reply_markup=reply_markup, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/bot.py", line 172, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 329, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 245, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: There is no media in the message to edit
```

It seems as I cannot use this method to update a CallbackQuery with an image if the CallbackQuery is not already embedded with a media.
Any suggestion?

**Comment by Bibo-Joshi** [comment]
You can call `edit_message_media` only for messages, which already contain media. For details, please see the docs.
If you want to show a picture, just send a new message with `bot.send_photo`
