### ISSUE TITLE
[QUESTION] MessageHandler behaviour when bot receives message while being in a group

### ISSUE THREAD

**Issue by Tarasovych** [python-telegram-bot/python-telegram-bot#1990]
### Issue I am facing
`MessageHandler` behaves different when bot receives message while being in a group and in private conversation.

### Traceback to the issue
Private conversation chat log:
```
me > hello
bot > hello
me > /hello
bot > /hello
```
Group chat log:
```
me > hello
// no reply from bot
me > /hello
bot > /hello
me > ///two slashes
bot > ///two slashes
me > ///
bot > ///
```

### Related part of your code
```python
def echo(update, context):
    update.message.reply_text(update.message.text)

def main():
    updater = Updater('TOKEN', use_context=True)

    dp = updater.dispatcher

    dp.add_handler(MessageHandler(Filters.text, echo))

    dp.add_error_handler(error)

    updater.start_polling()

    updater.idle()
```

Thanks in advance!

**Comment by RobertVCampbell** [comment]
Was this resolved or is it intentional? I just started making my first bot and ran into this issue when going through the "Your first bot" portion in the wiki. It worked perfectly fine in my direct chat with the bot, but did not work at all once I added it to a group.

**Comment by RobertVCampbell** [comment]
It was answered in another thread, in short it is a privacy/permissions issue:

https://github.com/python-telegram-bot/python-telegram-bot/issues/1665#issuecomment-567734100
