### ISSUE TITLE
Sending message using telegram.Message

### ISSUE THREAD

**Issue by Exist2Resist** [python-telegram-bot/python-telegram-bot#1993]
### Issue I am facing
Unable to send a message to Group Chat using Telegram.Message
I suspect it has something to do with the chat value. 

### Related part of your code
```
import telegram, datetime

bot = telegram.Bot(token='1111111111:AAHoDrlLD2pnpasdfasdfasdn5wAP2ZbyYo')

last_message=bot.get_updates()[len(bot.get_updates())-1].message.message_id
print(last_message)

message = telegram.Message(chat=-420000000, message_id=last_message+1, from_user='My_Alerts_bot' ,date=datetime.datetime.now(), text="Test message using API." )
print(message)
```

**Comment by Bibo-Joshi** [comment]
`telegram.Message` is a class representing message objects. To actually send messages, use `Bot.send_message`. Have a look at our [tutorial](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-–-Your-first-Bot).

**Comment by Exist2Resist** [comment]
Thanks my bad, I thought the `Bot.send_message` only applied to Telegram.ext, which I used to create my responses in the bot.
