### ISSUE TITLE
[QUESTION] Another handler is ending the conversation

### ISSUE THREAD

**Issue by danielWagnerr** [python-telegram-bot/python-telegram-bot#1996]
### Issue I am facing
I have some conversation handlers which are activated through a command and within it some states are activated by any text message.

In addition, I have a message handler that is activated whenever a message other than a command is sent by the user.

My problem is: when I start a conversation and then send a message, the other handler that is not present in the conversation is activated.

So, when I send the command /register the following conversation starts:

```python
ConversationHandler(
        entry_points=[CommandHandler('register', register)],
        states={
            NAME: [MessageHandler(Filters.text, name)],
            SURNAME: [MessageHandler(Filters.text, surname)]
        },
        fallbacks=[MessageHandler(Filters.command, fallback)],
        allow_reentry=False
    )
```
But when the user sends his name, the following handler is activated:

```python
dispatcher.add_handler(MessageHandler(filters=~ Filters.command, callback=any_message))
```
The above handler ends my conversation and do what the callback has to do, but what I want is to activate it only when there is no active conversation.

Any suggestion?

**Comment by Poolitzer** [comment]
Put the addition of the message handler literally lower in the code. At least after the add_conv calls, I normally put those handlers at the end and some kind of comment above them

**Comment by danielWagnerr** [comment]
Thanks @Poolitzer, I don't know how, but it solved my problem. Can you explain what happened?

Now I'm stucked with another problem:

I have a lot of ConversationHandlers, with fallbacks like this:

```python
fallbacks=[MessageHandler(Filters.command | (~Filters.text), fallback)]
```
And the conversations are added like this:
```python
    dispatcher.add_handler(register_conversation())
    dispatcher.add_handler(configure_conversation())
    dispatcher.add_handler(sign_conversation())
    dispatcher.add_handler(remove_jobs_conversation())
```
Obs.: All functions return a ConversationHandler

My problem is: When I type /config (that activates configure_conversation) and then /sign (that activates sign_conversation) the fallback works perfectly, but when I do the opposite, the fallback does not work and the configure_conversation starts.

Do you know of any solution for this?

**Comment by Bibo-Joshi** [comment]
Hi. Please read the documentation of `add_handler` carefully (hint: "groups"). Also, there are several issues related to "interrupting conversations". Please have a look at them and the issues linked therein.
I'm closing this one.
