### ISSUE TITLE
Dispatсher process command with no-break space like unknow command.

### ISSUE THREAD

**Issue by shelomentsevd** [python-telegram-bot/python-telegram-bot#200]
Occurs only if message sent from web version of telegram.

**How to reproduce**
1. In web version of telegram write a command to bot: '/command  '(two or more spaces) or press 'TAB' for auto-complete(will add no-break space to the end of message).
2. Bot will recognize command like 'command\xc2\xa0'('\xc2\xa0' is no-break space)

**Comment by leandrotoledo** [comment]
Woah! Nice catch.

**Comment by leandrotoledo** [comment]
#201 has been merged. Thanks!
