### ISSUE TITLE
[QUESTION] Channel participants?

### ISSUE THREAD

**Issue by iperov** [python-telegram-bot/python-telegram-bot#2001]
how to get?

https://core.telegram.org/method/channels.getParticipants

Bots can use this method

**Comment by Bibo-Joshi** [comment]
That's a method of MTProto. This library is for the Bot API, with the corresponding documentation at https://core.telegram.org/bots/api.
See [here](http://telegra.ph/How-a-Userbot-superacharges-your-Telegram-Bot-07-09) for an explanation on the difference between the Bot API and MTProto.

**Comment by iperov** [comment]
@Bibo-Joshi 

so, 
is there any way to massively delete "Deleted Account" (300+) users from the group using only bot api?

I don't like to establish developer api via key/hash.

**Comment by Bibo-Joshi** [comment]
Yes, you can use `kick_chat_member`, as documented [here](https://core.telegram.org/bots/api) and [here](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html?highlight=kickchatmember#telegram.Bot.kick_chat_member).
If you are new to the Bot API in general or PTB, please read our [wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Introduction-to-the-API).
For more question, please join our user [group](https://telegram.me/pythontelegrambotgroup), as this issue tracker is mainly intended for bugs of the library.

**Comment by iperov** [comment]
the problem is 
`kick_chat_member(chat_id, user_id,` requires user_id.
But I cannot get user_id without get all participants with their names from the group.

**Comment by Bibo-Joshi** [comment]
You'll need to keep track of users joining your group. getting all chat members is just not possible with the Bot API and there's nothing PTB can do about it.

> For more question, please join our user [group](https://telegram.me/pythontelegrambotgroup), as this issue tracker is mainly intended for bugs of the library.

**Comment by iperov** [comment]
> You'll need to keep track of users joining your group. getting all chat members is just not possible with the Bot API and there's nothing PTB can do about it.

But it requires bot on-line all time since group born. 
It is not a solution :(

ok thanks anyway for answers
