### ISSUE TITLE
Has anyone succeeded to use webhooks with this library?

### ISSUE THREAD

**Issue by cryptoqube777** [python-telegram-bot/python-telegram-bot#2003]
Hi.
I tried many times to make bot work using built-in webhook mechanism, but i failed both with self-signed and purchased SSL certificate. **set_webhook** command works fine, but **start_webhook** command returns two error messages:
**Flood control exceeded. Retry in 1 seconds**
and
**Bad webhook. Failed to set custom certificate file.**

I use the code from python-telegram-bot wiki page as follows:
`updater.bot.set_webhook(url='https://topmail.net.ua:8443')`
`updater.start_webhook(`
`        listen='0.0.0.0',`
`        port=8443,`
`        url_path='',`
`        key='private.key',`
`        cert='cert.pem',`
`        webhook_url='https://topmail.net.ua:8443'`
`    )`
`    updater.idle()`

Are there any chances to get this work or should i move to some other libraries?

**Comment by Poolitzer** [comment]
can you change to debug level logging and paste the output?

**Comment by ehsanonline** [comment]
You should pass your `cert.pem` file to `set_webhook`  as `certificate` arg:
`updater.bot.set_webhook(url='https://topmail.net.ua:8443',certificate='cert.pem')`

and about the flooding error, make sure your bot does not send more than 30 messages/second in total and 20 messages/minute in groups or channels.

**Comment by cryptoqube777** [comment]
@ehsanonline 
I tried adding cert as you advised, and now I'm getting an error 
`Bad webhook, Failed to set custom certificate file.`

**Comment by ehsanonline** [comment]
Ok, I think you don't need to run `set_webhook` at all, because it's in the `start_webhook` . so just run the `start_webhook` and make sure you made a cert with right `FQDN` as explained [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks#a-ssl-certificate).

then based on the [this example](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks#the-integrated-webhook-server) add token as well just for testing: 
```python
updater.start_webhook(listen='0.0.0.0',
                      port=8443,
                      url_path='TOKEN',
                      key='private.key',
                      cert='cert.pem',
                      webhook_url='https://topmail.net.ua:8443/TOKEN')
```

**Comment by Bibo-Joshi** [comment]
Please make sure to read our [wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks) on webhooks.

**Comment by Niteshkpatel** [comment]
I tried to implement the same after reading the webhook wiki page. After implementing `updater.start_webhook()` with proper arguments, I am getting the following message when I go to the url `https://api.telegram.org/bot{API}/getWebhookInfo`
`{"ok":true,"result":{"url":"{IP}:8443/{API}","has_custom_certificate":true,"pending_update_count":4,"max_connections":40}}`.

But the console raises an **NotImplementedError** error message.

**Comment by ehsanonline** [comment]
give us the **full error message** and your **code** please.

**Comment by Niteshkpatel** [comment]
I created a self signed certificate with OPENSSL with the FQDN having the smae address that was obtained from the ngrok. Then I ran the following code. 

`
import requests
import telegram
from telegram.ext import Updater, InlineQueryHandler, CommandHandler, CallbackQueryHandler,  MessageHandler, Filters, ConversationHandler
import os

my_token = ""


def start(update,context):
    update.message.reply_text("Hello world")


PORT = int(os.environ.get('PORT', '443'))

def main():
    updater = Updater(my_token, use_context=True)
    dp = updater.dispatcher

    # on different commands - answer in Telegram
    dp.add_handler(CommandHandler("start", start))

    #Setting Webhook
    try:
        updater.start_webhook(listen='0.0.0.0',
                        port=PORT,
                        url_path=my_token,
                        key='private.key',
                        cert='cert.pem',
                        webhook_url='https://51a0c2069cdb.ngrok.io:443/{my_token}')
    except Exception as e:
        print(e)
    updater.idle()


if __name__ == '__main__':
    main()

Then I got the following error in the console :
`
Exception in thread Bot:1169146915:updater:
Traceback (most recent call last):
  File "C:\Program Files\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\lib\site-packages\telegram\ext\updater.py", line 216, in _thread_wrapper
    target(*args, **kwargs)
  File "C:\Program Files\lib\site-packages\telegram\ext\updater.py", line 452, in _start_webhook
    self.httpd.serve_forever()
  File "C:\Program Files\lib\site-packages\telegram\utils\webhookhandler.py", line 52, in serve_forever
    self.http_server.listen(self.port, address=self.listen)
  File "C:\Program Files\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Program Files\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Program Files\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Program Files\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Program Files\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
`
 When I visited the link `https://api.telegram.org/bot{my_token}/getWebhookInfo`, I got the following response
{"ok":true,"result":{"url":"https://51a0c2069cdb.ngrok.io:443/{my_token}","has_custom_certificate":true,"pending_update_count":0,"last_error_date":1593801253,"last_error_message":"SSL error {error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed}","max_connections":40}}

**Comment by ehsanonline** [comment]
first of all, add an `f` before `webhook_url` value to currect it :
```python
webhook_url=f'https://51a0c2069cdb.ngrok.io:443/{my_token}'
```
run your code now, if you got `NotImplementedError` again, it seems like it's due to `asyncio` , not the `webhook`. make sure you are using python 3.5+. if so, try run the main with `asyncio` : 
```python
import asyncio
if __name__ == '__main__':
  loop = asyncio.get_event_loop()
  loop.run_until_complete(main())
  loop.close()
```
not sure if it works or not, i'm not an asyncio expert.
