### ISSUE TITLE
[BUG] Errors in Job callbacks are not passed to error handler

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2004]
### Steps to reproduce
1. Register an errory_handler
2. Set up a job

3. Make that job fail on execution

### Expected behaviour
Error should be handled by the error handler

### Actual behaviour
It's not, as the JobQueue doesn't handle that correctly (see [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/15268acb2729411ab8a64ef6127933b1d100c27d/telegram/ext/jobqueue.py#L571), this should call `dispatcher.dispatch_error`)

### Logs
https://pastebin.com/LhFTBb6S

**Comment by Bibo-Joshi** [comment]
Puttung the errors through `dispatcher.dispatch_error`, we'll have to pass `update = None`, which is kind of breaking, as

* it's not documented that `update` may be `None` in the error handlers
* e.g. the current example on error handler can't handle it

As `JobQueue` is getting refactored anyway, I'd propose to just include this into #1981 . What do you think @Poolitzer ?

**Comment by Poolitzer** [comment]
No we can have errors with Update None, fairly sure. I am back home in an hour let me check.

Since we are refactoring anyway it shouldnt matter though, Update None is fine.

**Comment by Bibo-Joshi** [comment]
Yes, passing `None` is no problem for `dispatcher.dispatch_error()`,  but in `errorhandlerbot.py` [this line](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/errorhandlerbot.py#L48) will fail and the [docs](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.dispatcher.html#telegram.ext.Dispatcher.add_error_handler) say nothing about `None` being allowed for `update`.

**Comment by Bibo-Joshi** [comment]
#1981 has been merged into v13, so I'll close this
