### ISSUE TITLE
[FEATURE] via_bot filter

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#2007]
This should be the same logic as the from user one. A list of str or ids, or one instance of each, for filtering after username or id.

**Comment by Poolitzer** [comment]
@Poolitzer <b>ext.filters.Filters.user</b>
<i>python-telegram-bot</i> documentation for this class:
<a href="https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.filters.html#telegram.ext.filters.Filters.user">telegram.ext.filters.Filters.user</a>

The official documentation has more info about <a href="https://core.telegram.org/bots/api#user">User</a>.

**Comment by Bibo-Joshi** [comment]
Closed via #2009
