### ISSUE TITLE
[QUESTION] How to use proxies in your library?

### ISSUE THREAD

**Issue by khmelev77** [python-telegram-bot/python-telegram-bot#2010]
Hello,
I have a proxy url (socks5), where can I specify it? Usually in other libraries, this is done like this:
Bot (token = '', proxy_url = 'my proxy url')
I need some kind of example, I did not find anything in the documentation

**Comment by Bibo-Joshi** [comment]
Hi. Please see [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Working-Behind-a-Proxy) and [here](https://github.com/python-telegram-bot/python-telegram-bot/issues/525).
