### ISSUE TITLE
[QUESTION] How to send a message with some pictures？

### ISSUE THREAD

**Issue by YulinChan** [python-telegram-bot/python-telegram-bot#2011]
### Issue I am facing
I want to make my bot to send a message with some pictures to my channel.
Just like this:
```
film title: film name
actor: xxx
downloadLink: magnet:?xt=urn:btih:xxxxxx
pictures_preview:
<a href="url of pic1">&#289;</a>
<a href="url of pic2">&#289;</a>
<a href="url of pic3">&#289;</a>
```
But it only show one pic in preview, the rest of pic are not show. I want all the pic can be saw, so how I can achieve it? 

### Related part of your code
```python
import telegram

bot = telegram.Bot('token of my bot')

msg = "film title: film name \n actor: xxx \n downloadLink: magnet:?xt=urn:btih:xxxxxx \n pictures_preview: \n <a href='url of pic1'>&#289;</a> <a href='url of pic2'>&#289;</a> <a href='url of pic3'>&#289;</a>"

bot.sendMessage('channel id', parse_mode=telegram.ParseMode.HTML, text=msg)
```

**Comment by Bibo-Joshi** [comment]
Hi.
What your code does is send *links* to the pictures. By default, telegram will try to show a preview of the first link in the message (which can be disabled with `disable_web_page_preview=True`). If you acutally want to send the pictures and not just the links to them, use `send_media_group`. You can combine the two approaches by adding the links as caption to the media group, so you'll have a "preview" of all pictures and the links.

**Comment by YulinChan** [comment]
I got it. Thank you very much!
