### ISSUE TITLE
Small misspelling in docs

### ISSUE THREAD

**Issue by DemianS** [python-telegram-bot/python-telegram-bot#2013]
https://github.com/python-telegram-bot/python-telegram-bot/blob/960c7a0c702d2fc2f0a7098645d69e3a23ab7e18/telegram/ext/defaults.py#L29
https://github.com/python-telegram-bot/python-telegram-bot/blob/960c7a0c702d2fc2f0a7098645d69e3a23ab7e18/telegram/ext/defaults.py#L43
it needs to be **text** instead of **toxt**

**Comment by Bibo-Joshi** [comment]
Hey. Thanks for reporting! :)
Will be fixed in #2008. I'll go ahead and close this one already, though.
