### ISSUE TITLE
Get user_id with Username

### ISSUE THREAD

**Issue by alimoradi2020** [python-telegram-bot/python-telegram-bot#2014]
Hi, how can i get user_id with username?
for Example i have an username (@username) and i print user_id (from_id)...

**Comment by Bibo-Joshi** [comment]
@alimoradi2020 <b>Bot.get_chat</b>
<i>python-telegram-bot</i> documentation for this method:
<a href="https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.get_chat">telegram.Bot.get_chat</a>

The official documentation has more info about <a href="https://core.telegram.org/bots/api#getchat">getChat</a>.

**Comment by Poolitzer** [comment]
@Bibo-Joshi Since that is the only method, as you can see, you need the id to get a user. If you have to rely on usernames, you need to make a database where you map the username to the id. Keep in mind usernames can change though :)

**Comment by alimoradi2020** [comment]
@Bibo-Joshi Thank you
