### ISSUE TITLE
[BUG] Defaults not working with MessageQueue

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2015]
### Steps to reproduce
1. Set up a bot with a MessageQueue as described in the wiki

2. pass a `Defaults` object to the bot

### Expected behaviour
Defaults should be used

### Actual behaviour
They're not. Instead `ValueError("Function has keyword-only parameters or annotations"` is raised

### Why this happens & how to overcome
1. `getargspec` is deprecated in favor of `getfullargspec`. This can easily be resolved
2. This doesn't suffice yet, as the methods of `MQBot` override the bots methods and are decorated. `getfullargspec` can't see through the decorator. using `inspect.getfullargspec(inspect.unwrap(method))` can resolve that
3. This still only works, if we explicitly list the methods args & kwargs while overriden in `MQBot`

After #2012 this is one more reason to tackle MQ in v13.X/v14. Just adding `inspect.getfullargspec(inspect.unwrap(method))` as a more or less quick fix doesn't really seem right to me …

**Comment by hexatester** [comment]
So tl;dr;

Source : https://github.com/python-telegram-bot/python-telegram-bot/issues/2012#issuecomment-655052184

```python
import functools
import inspect
from telegram import Bot
from telegram.ext import MessageQueue, Updater
from telegram.ext.messagequeue import queuedmessage
from telegram.utils.helpers import DEFAULT_NONE


class QueuedBot(Bot):
    def __new__(cls, *args, **kwargs):
        # Get default values from kwargs
        defaults = kwargs.get('defaults')

        # Make an instance of the class
        instance = super().__new__(cls)

        if not defaults:
            return instance

        # For each method ...
        for method_name, method in inspect.getmembers(instance, predicate=inspect.ismethod):
            # ... get kwargs
            argspec = inspect.getfullargspec(inspect.unwrap(method))
            kwarg_names = argspec.args[-len(argspec.defaults or []):]
            # ... check if Defaults has a attribute that matches the kwarg name
            needs_default = [
                kwarg_name for kwarg_name in kwarg_names if hasattr(defaults, kwarg_name)
            ]
            # ... make a dict of kwarg name and the default value
            default_kwargs = {
                kwarg_name: getattr(defaults, kwarg_name) for kwarg_name in needs_default if (
                    getattr(defaults, kwarg_name) is not DEFAULT_NONE
                )
            }
            # ... apply the defaults using a partial
            if default_kwargs:
                setattr(instance, method_name, functools.partial(method, **default_kwargs))

        return instance

    def __init__(self, *args, **kwargs):
        super(QueuedBot, self).__init__(*args, **kwargs)
        self._is_messages_queued_default = True
        self._msg_queue = MessageQueue()

    def stop(self):
        try:
            self._msg_queue.stop()
        except Exception:
            pass

    @queuedmessage
    def send_message(self, *args, **kwargs):
        '''Wrapped method would accept new `queued` and `isgroup` OPTIONAL arguments'''
        return super(QueuedBot, self).send_message(*args, **kwargs)


class QueuedUpdater(Updater):
    def __init__(self, bot: QueuedBot, *args, **kwargs):
        super(QueuedUpdater, self).__init__(bot=bot, *args, **kwargs)

    def signal_handler(self, signum, frame):
        super().signal_handler(signum, frame)
        self.bot.stop()

```

**Comment by Bibo-Joshi** [comment]
To provide some context for people stumbling upon this: the code provided by @hexatester is a semi-workaround for both the issue reported in #2012 and the issue reported here. Semi-workaround, because it overlooks 

> 3. This still only works, if we explicitly list the methods args & kwargs while overriden in MQBot

**Comment by hexatester** [comment]
Um.  I see, thanks.

> 
> 
> To provide some context for people stumbling upon this: the code provided by @hexatester is a semi-workaround for both the issue reported in #2012 and the issue reported here. Semi-workaround, because it overlooks
> 
> > 1. This still only works, if we explicitly list the methods args & kwargs while overriden in MQBot

**Comment by Bibo-Joshi** [comment]
As we won't tackle this issue individually but in the context of #2139, I will close this. #2139 links here, so it won't be forgotten :)
