### ISSUE TITLE
Pickle Persistence Not Saving Bot_data[BUG]

### ISSUE THREAD

**Issue by jingkatrader** [python-telegram-bot/python-telegram-bot#2016]
### Steps to reproduce
1.
In line 282 of picklepersistence.py:
[BUG]   if self.user_data or self.chat_data or self.conversations:
[FIX]  if self.user_data or self.chat_data or self.conversations or self.bot_data:

2.
Add self.bot_data in the if-check
3.

### Expected behaviour
When you register the pickle persistence with (store_user_data=False, store_chat_data=False), the bot should save bot_data to pickle file every time it calls flush().

### Actual behaviour
In the current version, the bot only checks user_data/chat_data/conversation to be non-empty to save the pickle file, which when the case (store_user_data=False, store_chat_data=False), the bot never checks bot_data in order to save the pickle file. In my case, user_data/chat_data are always empty, so bot doesn't save to pickle file

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by Bibo-Joshi** [comment]
Thanks for reporting the bug! Fixed it.
