### ISSUE TITLE
[QUESTION] whe i cant ignore ssl? ignore certs?

### ISSUE THREAD

**Issue by Pompeu** [python-telegram-bot/python-telegram-bot#2019]
### mybe
Add suport ?

on file https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/utils/request.py
has hardcoed for use certificate why ?
dont has suport fo config?
### Related part of your code
```python
cert_reqs='CERT_REQUIRED',
            ca_certs=certifi.where(),
```

**Comment by Poolitzer** [comment]
Hey, telegrams API only supports HTTPS, there is no sense in not enforcing it on that level :)
