### ISSUE TITLE
[QUESTION] how to pass an argument to e.g. the start method?

### ISSUE THREAD

**Issue by FruechteBini** [python-telegram-bot/python-telegram-bot#2020]
Is it possible to pass an additional argument to a method hello(). it usually takes args (update, context) and i want to add a String for example.
i tried it like this:

```
def hello(update, context, custom_string):
    custom_string = custom_string + "_edited"
    update.message.reply_text(custom_string))
```

and then call it like this in the handler:

```
updater = Updater('YOUR TOKEN HERE', use_context=True)
updater.dispatcher.add_handler(CommandHandler('hello', hello("thisismycustomstring"))
updater.start_polling()
updater.idle()
```

I want to do this not only with Strings but also with objects. Is this possible?

**Comment by Bibo-Joshi** [comment]
Hi. You can achive something like this using [`functools.partial`](https://docs.python.org/3.8/library/functools.html#functools.partial) , in your case
```python
updater.dispatcher.add_handler(CommandHandler('hello', functools.partial(hello, custom_string = 'thisismycustomstring'))
```
I'll go ahead and close the issue as it's not really ptb related ;)
