### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by yaserrahimi** [python-telegram-bot/python-telegram-bot#2021]
hi
i want sent massage to your support group but you restrictet me pls solved this
my telegram id : @iranyaser
tanks

**Comment by Bibo-Joshi** [comment]
Hi. If you're from a country, where access to Telegram is restricted, we can't do anything about it. Please use our [IRC bridge](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group in that case.

**Comment by yaserrahimi** [comment]
big tanks to freedom
