### ISSUE TITLE
How can I make the bot send a picture from my local disk?

### ISSUE THREAD

**Issue by CoulsonZhang** [python-telegram-bot/python-telegram-bot#2023]
### Issue I am facing
I am new to this telegram bot. I want my bot to send a picture from my local disk which is just generated by another python function. 
I can't find a photo related class or module in update or others.
Can someone help me out>
Thanks in advance

**Comment by Poolitzer** [comment]
@CoulsonZhang #snippets

**Comment by Poolitzer** [comment]
@CoulsonZhang <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets">Here</a> you can find many useful code snippets for the work with python-telegram-bot
