### ISSUE TITLE
[BUG] [docs] User.mention_markdown should mention legacy status

### ISSUE THREAD

**Issue by half-duplex** [python-telegram-bot/python-telegram-bot#2029]
The [Telegram formatting documentation](https://core.telegram.org/bots/api#formatting-options) says that "[Markdown v1] is a legacy mode, retained for backward compatibility."

In many cases this is fine, but in some, especially mention_markdown, v1 is never appropriate. There is no use I'm aware of that doesn't either require excessive and text-changing boilerplate (stripping special characters) or break the resulting message. This can't be worked around, since as the Telegram documentation says: "Escaping inside entities is not allowed" in markdown v1.

I would suggest deprecating `User.mention_markdown` and `utils.helpers.mention_markdown` with `version=1`. At a minimum, they should have a note added to [the](https://python-telegram-bot.readthedocs.io/en/stable/telegram.utils.helpers.html#telegram.utils.helpers.mention_markdown) [documentation](https://python-telegram-bot.readthedocs.io/en/stable/telegram.user.html#telegram.User.mention_markdown) to make clear that it's a bad choice and nudge users towards v2:
> Due to Telegram's Mardown v1 parsing, this will produce invalid links for users with certain characters in their display name like `[`. Use `mention_html` or `mention_markdown_v2` to avoid this problem.

People seem to [regularly](https://t.me/pythontelegrambotgroup/245932) [use](https://t.me/pythontelegrambotgroup/298172) [and](https://t.me/pythontelegrambotgroup/266450) [suggest](https://t.me/pythontelegrambotgroup/222660) [this](https://t.me/pythontelegrambotgroup/136632) [despite](https://t.me/pythontelegrambotgroup/120481) [it](https://github.com/AyraHikari/EmiliaHikari/blob/9e513d2db1c7e69ef7980104425d7fcc274b088a/emilia/modules/blacklist.py#L304-L327) [being](https://github.com/mjgui/sg_bridge_bot/blob/297d57f08202dd3c66a5ca870ad3962091c176c6/bot.py#L327-L330) [legacy](https://github.com/AnantaSrikar/TelegramBot/blob/b14d52776236e7a370707d7bf6efdf85148d9f8b/StartMyTelegramBot.py#L125) [and](https://github.com/covindia/CovIndia-CrowdsourcingPower/blob/5fb94592dbe0132d6ccc1b3d430751ad83cec96b/startSauron.py#L36) [broken](https://github.com/mud9/mud9adminbot/blob/ba635f1c6e111b45455916e0a4494c2b85be12c0/commands/group_management_commands.py#L49-L53) ([...](https://github.com/search?q=%22telegram%22+%22mention_markdown%22&type=Code)), and many bots will end up [having](https://github.com/python-telegram-bot/python-telegram-bot/issues/1254) [issues](https://t.me/pythontelegrambotgroup/200169) because of it (I just fixed my 4).

It may be good to eventually have a "This is legacy, use v2" note like Telegram's on anything that generates or consumes markdown v1.

### Steps to reproduce
1. Have a need to mention a user who may not have a username
2. Discover and use `User.mention_markdown()`, which appears to be simple and do what you need
3. Attempt to use the function on someone with a left square bracket (`[`) in their display name, and send the result in a `ParseMode.MARKDOWN` message

### Expected behaviour
Documentation makes clear that a normal user mention cannot be reliably sent using markdown v1 and points the user towards `mention_markdown_v2`/`ParseMode.MARKDOWN_V2` or `mention_html`/`ParseMode.HTML`.
Otherwise, based on the documentation, users would expect a valid mention in the resulting message: [\[Robert\]](https://github.com)

### Actual behaviour
The documentation does not warn about this footgun, leaving users to implement markdown v1 and have their bots break mysteriously on some names months later, displaying things like \\\[Robert]([tg://user?id=123)](https://github.com) [sic] in the resulting message.

### Configuration
**Operating System:**
Debian 10.4

**Version of Python, python-telegram-bot & dependencies:**
```
python-telegram-bot 12.8
certifi 2020.06.20
Python 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
```

**Comment by Poolitzer** [comment]
Warning the user might be hard to implement specifically for mention(), unless you want to generally warn users whenever they use markdown V1, which is fine with me, but other maintainers often argue that we/this library are/is not there to fix all of peoples problems by itself.

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for the extensive report.

Deprecating Markdown v1 alltogether as long as Telegram still supports it (even if only for backward compatibility) would certainly not be a good idea.
Also, issuing a warning in the code on use of Markdown v1 would be a bit over the top imo. PTB currently only does such for PTB-only related stuff (like non-context callbacks).

I agree however that adding a

```rst
Warning:
    ``ParseMode.MARKDOWN`` is is a legacy mode, retained by Telegram for backward compatibility. You should use :meth:`mention_markdown_v2` instead.
```
would be helpful. Such a note would be needed for

* `ParseMode.MARKDOWN`
* `User.mention_markdown`
* `Message.text/caption/reply_markdown`

@half-duplex would you maybe like to PR for that yourself?

**Comment by Bibo-Joshi** [comment]
Added notes to the docs in #2008. Closing.
