### ISSUE TITLE
jobQueue isn't able to send messages to every user

### ISSUE THREAD

**Issue by giacomocerquone** [python-telegram-bot/python-telegram-bot#203]
Hi, I've just built a bot with this API and now I have one huge problem to solve. This is the repo: https://github.com/UnivaqTelegramBot/UnivaqInformaticaBot and with this code: 

```python
def newson_command(bot, update):
    """Defining the command to enable notifications for news"""

    def notify_news(bat):
        """Defining method that will be repeated over and over"""
        unread_news = news.check_news()

        if len(unread_news) > 0:
            data = news.pull_news(10)
            utils.write_json(data, "json/news.json")
            new_news_string = ""
            for item in unread_news:
                truncated_descr = item['description'][:75] + '...' if len(item['description']) > 75\
                                  else item['description']
                new_news_string += "- [" + item['title'] + "](" + item['link'] + ")\n" \
                                  + truncated_descr + "\n"

            bat.sendMessage(update.message.chat_id, parse_mode='Markdown', text=new_news_string)

    JOB_QUEUE.put(notify_news, 10, repeat=True)
    bot.sendMessage(update.message.chat_id, text='Notifiche abilitate')
```
When a user send the newson command, I'm putting a job with jobQueue to fetch some data every 60 seconds and then send it back. It works very good... but just for me!! Maybe only the first who send that command get the news??
I feel like I'm missing something very stupid... I truly accept any kind of help here!
Thank you very much, hoping in a response.

**Comment by jh0ker** [comment]
Hello @giacomocerquone 
Have you checked the log if the jobs are executed at all?

**Comment by giacomocerquone** [comment]
Yes the jobs are absolutely executed, in fact as I said the news come back only to me... actually I think the implementation's idea is wrong. I think I should follow something like this https://github.com/makiftasova/telegram-twitter-bot/blob/master/bot.py

But I'd really appreciate if someone could explain the reasons behind my problems (I'm really a newbie in python)

**Comment by jh0ker** [comment]
I'm not an expert on function specifics like this one, but I think the problem is related to the fact that you define a function inside a function, but you're using a variable from the outer function in the inner one.

Try to change your code like this:

    def notify_news(bot, chat_id):
        """Defining method that will be repeated over and over"""
        unread_news = news.check_news()

        if len(unread_news) > 0:
            data = news.pull_news(10)
            utils.write_json(data, "json/news.json")
            new_news_string = ""
            for item in unread_news:
                truncated_descr = item['description'][:75] + '...' if len(item['description']) > 75\
                                  else item['description']
                new_news_string += "- [" + item['title'] + "](" + item['link'] + ")\n" \
                                  + truncated_descr + "\n"

            bot.sendMessage(chat_id, parse_mode='Markdown', text=new_news_string)

    def newson_command(bot, update):
        """Defining the command to enable notifications for news"""

        job = (lambda bot: notify_news(bot, update.message.chat_id))
        JOB_QUEUE.put(job, 10, repeat=True)
        bot.sendMessage(update.message.chat_id, text='Notifiche abilitate')

This way, the inner and outer functions will be seperated

**Comment by giacomocerquone** [comment]
Tried and doesn't work. There is a fundamental error, I think it's because I'm sending always to the same chat_id... For example the link above use a json list for the subscribers with their chat_id

**Comment by giacomocerquone** [comment]
Solved everything introducing a list and saving every chat_id! I love you guys, I love everyone!
