### ISSUE TITLE
[FEATURE] Is there any way to save Persistence not in file or RAM, but really persistent storage?

### ISSUE THREAD

**Issue by wowkin2** [python-telegram-bot/python-telegram-bot#2030]
#### Is your feature request related to a problem? Please describe.
I want to deploy my conversational bot to Heroku. And storing states and other data for persistence in file or RAM is not the case for me. Because Heroku don't allow writing to file (or erase it after redeploy).

#### Describe the solution you'd like
Is there any ready solutions to save it to really persistent storage (Postgresql, Redis or MongoDB)

#### Describe alternatives you've considered
Is there are any (library, code snippet, existing issue or PR)?

#### Additional context
None

**Comment by Bibo-Joshi** [comment]
Hi.
If you'd like to have the data persisted to a database, you can subclass `BasePersistence` and buid e.g. `MongoPersisence` to integrate MondoDB with PTB. PTB doesn't provide examples of persistence with databases, as this beyond the scope of this project. (See also  #1970 and #1717)
There probably alre corresponding classes out there already. You might wanna ask in the [telegram group](https://t.me/pythontelegrambotgroup).
I'll go ahead and close this feature request, as it's unlikely that more advanced persistence classes will be included directly in the future.
