### ISSUE TITLE
[BUG] Custom filter inherited from BaseFilter is not accepted in MessageHandler

### ISSUE THREAD

**Issue by MarcelBeining** [python-telegram-bot/python-telegram-bot#2033]
### Steps to reproduce
1. Use this custom filter as a filter for MessageHandler
```
from telegram.ext.filters import BaseFilter
from telegram.ext import MessageHandler

class DateFilter(BaseFilter):
    """
    Filters updates by checking if message can be parsed into a date.

    """

    name = 'Filters.date'

    def filter(self, message):
        try:
            parsed = dateparse(message.text)
        except:
            return False
        if parsed is None:
            return False
        return True

MessageHandler(DateFilter, SOMEFUNCTION)
```

### Expected behaviour
The DateFilter should be accepted as it is inherited from BaseFilter

### Actual behaviour
The code quits with this error:
>   File "C:\ProgramData\Anaconda3\lib\site-packages\telegram\ext\messagehandler.py", line 131, in __init__
>     self.filters &= Filters.update
> TypeError: unsupported operand type(s) for &=: 'ABCMeta' and '_UpdateType'

### Configuration
**Operating System:**
Windows 10 64bit

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 12.8
certifi 2020.06.20
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]

**Comment by Bibo-Joshi** [comment]
Hi. Citing the [docs](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.filters.html#telegram.ext.filters.BaseFilter):
> Note that the filters work only as class instances, not actual class objects (so remember to initialize your filter classes).

I.e. you'll need to do

```python
MessageHandler(DateFilter(), SOMEFUNCTION)
```

**Comment by MarcelBeining** [comment]
Ah thanks!
