### ISSUE TITLE
[BUG] Context manager not working with MessageQueue

### ISSUE THREAD

**Issue by DemianS** [python-telegram-bot/python-telegram-bot#2035]
### Steps to reproduce
1. Set up a bot with a MessageQueue as described in the wiki

2. Override methods send_document, send_photo with @messagequeue.queuedmessage decorator

3. Open file with `context manager` and try to send it

### Expected behaviour
Files must be sent to chat as usual, like they do without MessageQueue

### Actual behaviour
Files are not sent. As I found, file is closed at the moment it should have sent.
And we have: `ValueError: read of closed file` of course.

### Why this happens and how to overcome that _(steal that topic)_
Files are closed before actual send, because send_document returns Promise object instead of message, you know, because it's messagequeue. So that Promise results after context manager close this file.
**HotFix:** You should wait for promise.result() if you want to close file properly.
Or InputFile should close file after it is done with it, and you don't have to worry about it.

_Hope I fill everything right._

**Comment by Bibo-Joshi** [comment]
A solution specifically for `InputFile` would be to have `Promise` already construct the `InputFile`, something along the lines

```python


        new_args = []
        for arg in self.args:
            if InputFile.is_file(arg):
                new_args.append(InputFile(arg))
            else:
                new_args.append(arg)
        self.args = tuple(new_args)
        for key, value in self.kwargs.items():
            if InputFile.is_file(value):
                self.kwargs[key] = InputFile(value)
```

We would need to check, if we would need to handle more things like this, but at least atm I can't think of anything else …

**Comment by Bibo-Joshi** [comment]
As we won't tackle this issue individually but in the context of #2139, I will close this. #2139 links here, so it won't be forgotten :)
