### ISSUE TITLE
How can I send self destructing photos with python telegram bot?

### ISSUE THREAD

**Issue by kmahsi** [python-telegram-bot/python-telegram-bot#2037]
#1900 # Issue I am facing

**Comment by Bibo-Joshi** [comment]
Use [`JobQueue.run_once`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.jobqueue.html#telegram.ext.JobQueue.run_once) to delete the message after x seconds. Have a look at the [wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-–-JobQueue) and this [example](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/timerbot.py).

**Comment by kmahsi** [comment]
> Use [`JobQueue.run_once`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.jobqueue.html#telegram.ext.JobQueue.run_once) to delete the message after x seconds. Have a look at the [wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-JobQueue) and this [example](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/timerbot.py).

Thanks. And is there a way to prevent user from saving the image? I want to delete image after x seconds and I want to be sure that user can't take screen shot from the display or neither save image in the gallery. Is this possible?

**Comment by Bibo-Joshi** [comment]
I guess not, but that would be out of scope of PTB anyway
