### ISSUE TITLE
Flood limits violation

### ISSUE THREAD

**Issue by freeearth** [python-telegram-bot/python-telegram-bot#2038]
### Issue I am facing
Hello.
While implementing own bot, I using your wiki suggestions
to avoid hitting spam limits.

So, the first, I implemented new class, like MQBot
[here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-flood-limits)

Then, create an instance of MQBot - mq_bot, with, for example,
all_burst_limit=3, all_time_limit_ms=3000 parameters (the same with your wiki Example)
 
The third, create an Updater and Dispatcher with bot=mq_bot, previously instanced,
add callbacks.

And the fourth, inside one of callback functions, create a loop to send non group messages.

But, if It (callback function) sends, for example, 1000 messages, then leads
to TelegramError exception (flood limit ).

### Traceback to the issue
```

```

### Python code
```python
#inside the callback function
for i in range (1:1000):
    context.bot.send_message(chat_id=update.message.chat_id, text="message_text", disable_web_page_preview = False, isgroup=False, parse_mode = "html")
```

**Comment by Bibo-Joshi** [comment]
Hi. Using `MessageQueue` is no guarantee that no flood limits are hit, as those limits are not static. Sending 1000 messages to the same chat is very likely to trigger floot limits fast, especially, if you do that repeatedly during testing. `MessageQueue` simply helps you spreading a reasonable amount of requests over a reasonable amount of time.
With your settings, you can send 1 message per second. Sending 1 message per second for 1000 seconds ~= 17 minutes does not seam reasonable ;)

**Comment by freeearth** [comment]
Thank you, **Bibo-Joshi **.
And what do you think about their maximum amount messages threshold 
for the same chat?

**Comment by Bibo-Joshi** [comment]
I guess, if you have large amounts of messages, you'll need to figure it out yourself. However, I'd recommend to reduce the number of messages, wherever possible. As a user of a bot, I usually expect only one message as reply, maybe 2-3, if the text is *really* long and can't fit into a single message …

**Comment by freeearth** [comment]
I projecting it as history option.
It will work in the following way - user can request an arbitrary time interval, then
bot will send needed.
