### ISSUE TITLE
[QUESTION] Send msg in other thread

### ISSUE THREAD

**Issue by voxcdr** [python-telegram-bot/python-telegram-bot#2044]
I am using sending message from Flask route. Sending a message via telegram takes 100-250 ms.
Is it possible to send a message in a separate thread without waiting for the result?

**Comment by badjano** [comment]
I have a similar question, sometimes I send a message which takes time for the bot to process, and then when I send another one he waits for the last question to finish to answer the next one, and this in a multi-user situation is impractical.
I could make my own threaded solution using threading or multiprocess, buy I was wondering if there´s something already built in for this, and if not, why?
