### ISSUE TITLE
Why Updates are not updated for next person in InlineQuery??

### ISSUE THREAD

**Issue by alimoradi2020** [python-telegram-bot/python-telegram-bot#2046]
Why Updates are not updated for next person in InlineQuery??
and the Update for the previous person (first_name, user_id, query and ...)
i mean Updates for the next person in InlineQuery will not be updated and show updates and previous user information...

```
def inlinequery(update, context):
    print(update)

dp.add_handler(InlineQueryHandler(inlinequery))
```

**Comment by Bibo-Joshi** [comment]
Hey. I thing I just answered you in the user group: https://t.me/pythontelegrambotgroup/357120
