### ISSUE TITLE
[QUESTION] get chat by callback_query.chat_instance

### ISSUE THREAD

**Issue by mujad** [python-telegram-bot/python-telegram-bot#2055]
### Issue I am facing
I need to detect which chat update is coming from when somebody click on InlineKeyboard
instead.

I have chat_instance but how can i get that channel or group ?! 
I also try get_chat, Char, InputPeer, ... but didn't successful

### Related part of your code
```python
{'update_id': 919458969, 'callback_query': {'id': '3840023343991832218', 'chat_instance': '4639674142813626973', 'data': 'vote_8_15', 'inline_message_id': 'BAAAACAAAAB9J6um0irmoyJeMuk', 'from': {'id': 894075106, 'first_name': 'حامی', 'is_bot': False, 'last_name': 'ادمود', 'username': 'admood_ads', 'language_code': 'en'}}, '_effective_user': {'id': 894075106, 'first_name': 'حامی', 'is_bot': False, 'last_name': 'ادمود', 'username': 'admood_ads', 'language_code': 'en'}}

```

**Comment by Bibo-Joshi** [comment]
Hi. [Update.effective_chat](https://python-telegram-bot.readthedocs.io/en/stable/telegram.update.html#telegram.Update.effective_chat) is your friend in most cases. However, for callbackqueries, `update.effective_chat` will be `None`, if `update.callback_query.message` is `None`.
I don't know if there is a way to resolve `chat_instance` to the `chat_id`, but if there is, it's undocumented. IIRC there is a method in Telethon, tough to resovel `inline_message_id` to the `chat_id`, though …
Without using telethon, your best shot probably is to get a callbackquery originating from a message from said chat and store it's `chat_instance`, so you can map `chat_instance` -> `chat_id` later on.

Also note that this library is concerned with the Bot API, i.e. not userbots. Hence, `InputPeer` is no class in PTB.

**Comment by mujad** [comment]
@Bibo-Joshi thank you so so so much telethon resolve_inline_message_id do what i need.
