### ISSUE TITLE
[BUG] Not raising any exception when editing a deleted message

### ISSUE THREAD

**Issue by mowhammadrezaa** [python-telegram-bot/python-telegram-bot#2058]
### Steps to reproduce
1. Send a message with the bot and store its message_id.

2. User deletes the message sent by the bot in the previous step.

3. Bot tries to edit the message which is deleted already, using this line of code: 
`bot.edit_message_text(chat_id=chat_id,
  message_id= message_id,
  text=text)`

### Expected behaviour
An exception must get raised.

### Actual behaviour
Nothing happens either side. No exception raising, no message editing.

### Configuration
**Operating System:**
Mac OS

**Version of Python, python-telegram-bot & dependencies:**
The latest
``$ python -m telegram``
python-telegram-bot 12.8
certifi 2020.06.20
Python 3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
### Logs
Insert logs here (if necessary)

**Comment by Bibo-Joshi** [comment]
Hi. Unfortunately, PTB can't do anything about that. PTB is just a wrapper for the Telegram API and hence can't know if a message exists or not. You may want to report this to the bot support (@BotSupport on TG).
