### ISSUE TITLE
[QUESTION] webhook consistent 5 seconds delay, is it normal?

### ISSUE THREAD

**Issue by santalucial** [python-telegram-bot/python-telegram-bot#2065]
### Issue I am facing
Consistent 5 seconds delay using webhooks, no noticeable delay using pooling method. The webhook was set up following the wiki without issues. What could be causing this delay?

### Traceback to the issue
```
2020-08-24 10:43:00,825 - telegram.utils.webhookhandler - DEBUG - Webhook triggered
2020-08-24 10:43:05,328 - telegram.utils.webhookhandler - DEBUG - y.y.y.y - - "POST /xxxx HTTP/1.1" 200 -
2020-08-24 10:43:05,328 - telegram.utils.webhookhandler - DEBUG - Webhook received data:
```

**Comment by Bibo-Joshi** [comment]
Hi. I can't reproduce the issue on my local machine.
In fact the debug prints `Webhook triggered` and `Webhook received data` are just 5 lines apart of each other in [`WebhookHandler.post()`](https://github.com/python-telegram-bot/python-telegram-bot/blob/faa93fbf75c23528bee5e6f91482f761aa052e05/telegram/utils/webhookhandler.py#L129)
Maybe if you can find out where your second line comes from, one can see where the delay comes from …

**Comment by santalucial** [comment]
It seems uninstalling and reinstalling the library solved the issue, that was odd
