### ISSUE TITLE
Issue with telegram webhook + changing DNS 

### ISSUE THREAD

**Issue by zefoo** [python-telegram-bot/python-telegram-bot#207]
I use python-telegram-bot on https://mydomain.com, and I recently changed the A record on mydomain.com. The code, and the URL for webhook is all the same. I've confirmed code works via CLI, and I've confirmed HTTP works properly. However, when I message my bot on telegram, I don't see it posting to the webhook on the old server or the new server (in access or error logs). The only thing that's changed is DNS. I've transferred over my SSL cert which works fine as well.

What's strange is I would have expected to at least see a POST request to the old or new server, whereas now I'm seeing it on neither. I don't think there could be issues with my SSL cert remaining the same while the underlying IP changes? I'm going to wait it out, but I wanted to post this in the meantime in case someone had any two cents or even further troubleshooting tips. Thank you. :)

**Comment by taemery** [comment]
Please post on telegram community, this is for specifically the python telegram wrapper

**Comment by zefoo** [comment]
Ah, thank you. I didn't realize there was a telegram community somewhere? I looked at the FAQ options here: https://telegram.org/faq - is there an official (or unofficial) telegram community on github somewhere? Thank you.

**Comment by zefoo** [comment]
Actually, it appears to be a routing issue, and it's an issue outside of my data center. Considering it may be difficult to reach telegram, I may be better served to run the polling or Updater class. Glad I have the option, I never thought I'd justify it that way!
