### ISSUE TITLE
[FEATURE] VoIP calls support

### ISSUE THREAD

**Issue by Nisutec** [python-telegram-bot/python-telegram-bot#2070]
#### Is your feature request related to a problem? Please describe.
I want to create a bot that can start a VoIP call with another user. If the call will be accepted an audio stream will be returned to communicate with the other user.

#### Describe the solution you'd like
I think it would be nice if you implement the VoIP calls requests from telegram into API functions to work with it in bots.

**Comment by Bibo-Joshi** [comment]
Hi. Please understand that PTB a wrapper for the Bot API and as such can't implement features that are not available through the Bot API. For a full list of methods available through the Bot API see core.telegram.org/bots/api.
