### ISSUE TITLE
[FEATURE] Auto-pagination for inline results

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2071]
#### Is your feature request related to a problem? Please describe.
TG requires pagination for inline results using the `next_offset` parameter. Currently this has to be implemented manually, but the logic is always the same, so it's basically copy paste.

I think it would fit well into PTBs "more than just a wrapper" credo to provide a convenience method for that.

#### Describe the solution you'd like

Add a parameters `pagination` and `current_offset` to `answer_inline_query` to make PTB take care of that automically. it should be along the lines

``` python
offset = current_offset
max_length = 50
next_offset = None

if not offset:
    if len(results) > max_length :
        next_offset = len(results) - max_length 
        next_offset = next_offset or None
        results = results[:max_length]
elif len(results) > offset:
    results = results[offset:offset + max_length]
    if len(results) > offset + max_length:
        next_offset = offset + max_length
else:
    next_offset = ''
```

#### Describe alternatives you've considered
If we don't want to integrate this directly into `answer_inline_query`, we could at least add a function to `utils.helpers` , along the lines
```python
def paginate_inline_results(reslts: List[InlineQueryResult], current_offset: int) -> {'results': …, 'next_offset': …}
```
so one could call it like

```python
answer_inline_query(**paginate_inline_results(results, offset), …)
```

**Comment by JosXa** [comment]
Consider that expensive result generators might slow the overall execution down and be wasteful overall. I love the idea, and maybe an inbetween step should be a result generator that is passed the current `page` index, so that the developer can avoid overfetching but doesn't have to bother with the offset parameter. 

```
ResultFetcher = Callable[[int], Iterable[InlineResult]]
```

**Comment by Bibo-Joshi** [comment]
> Consider that expensive result generators might slow the execution down and be wasteful overall.

You mean "don't truncate a list of results, but just build the required results in the first place"? Makes sense for advanced use cases, for sure.

My concern with adding parameters to `answer_ilq` is that we're currently not fiddling with the official methods too much (everything has timeout, `Message` classmethods have `quote` and some some parameters we are more genereous, like `open()` instead of `InputFile` and ['button'] instead of an ReplyButton) and I wouldn't wanna go in a direction where just add a bunch of parameters everywhere. That's why I wanted this to be discussed before PRing :D

Adding to `answer_ilq`, we could go with adding `current_offset` and allowing for `results` to be a callback as @JosXa suggested. Then passing `current_offset` would mean that auto-pagination is to be used and only then would a callback be acceptable for `results`. This would me relatively minimal invasive.
In the `utils.helpers` scenario, we could basically do the same, or make `results` and `results_generator` two mutually exclusive parameters

**Comment by Bibo-Joshi** [comment]
> Adding to answer_ilq, we could go with adding current_offset and allowing for results to be a callback as @JosXa suggested. Then passing current_offset would mean that auto-pagination is to be used and only then would a callback be acceptable for results. 

For the `InlineQuery.answer()` shortcut we would have to replace the `current_offset` parameter by an `auto_pagination` boolean flag (or similar naming), as we'd use `current_offset=self.next_offset` for `self.bot.answer_inline_query` automatically.
