### ISSUE TITLE
ConnectionRefusedError: [WinError 10061]

### ISSUE THREAD

**Issue by AliRafieePour** [python-telegram-bot/python-telegram-bot#2075]
Hi everyone,

I am receiving this error when running every single instance of the examples provided in the Examples repository. Back in time, I never received such an error and this is becoming so boring given that there aren't much useful results searching in StackOverFlow.
The full error is:

```Traceback (most recent call last):
  File "c:/Users/A/Desktop/New folder (3)/Sandoq/bot.py", line 18, in <module>
    from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
  File "D:\ProgramData\Anaconda3\lib\site-packages\telegram\__init__.py", line 47, in <module>
    from .files.file import File
  File "D:\ProgramData\Anaconda3\lib\site-packages\telegram\files\file.py", line 24, in <module>
    from future.backports.urllib import parse as urllib_parse
  File "D:\ProgramData\Anaconda3\lib\site-packages\future\backports\__init__.py", line 14, in <module>
    import_top_level_modules()
  File "D:\ProgramData\Anaconda3\lib\site-packages\future\standard_library\__init__.py", line 810, in import_top_level_modules
    with exclude_local_folder_imports(*TOP_LEVEL_MODULES):
  File "D:\ProgramData\Anaconda3\lib\site-packages\future\standard_library\__init__.py", line 781, in __enter__
    module = __import__(m, level=0)
  File "c:\Users\A\Desktop\New folder (3)\Sandoq\test.py", line 9, in <module>
    s.connect((HOST, PORT))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it```

**Comment by Poolitzer** [comment]
Hey, that sounds like telegram servers are, for some reason, actively refusing to connect to your server. Try pinging api.telegram.org from there or maybe call `https://api.telegram.org/bot123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11/getMe`

(With your token obviously)

**Comment by AliRafieePour** [comment]
> https://api.telegram.org/bot123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11/getMe

Hey, 
Thanks for taking the time to review my question.
Pinging `api.telegram.org` seems Ok to me and I checked it multiple times.

**Comment by Poolitzer** [comment]
What about calling said URL? Does that work?

**Comment by AliRafieePour** [comment]
This is the result after replacing the token section of the url with my bot's token: `{"ok":false,"error_code":404,"description":"Not Found"}`

**Comment by Poolitzer** [comment]
Did you delete the bot part?

**Comment by AliRafieePour** [comment]
> Did you delete the bot part?

Yes I did. `https://api.telegram.org/1224580138:AAEESi6v(the rest of the token)/getMe`

**Comment by AliRafieePour** [comment]
> @AliRafieePour Yeah dont, it belongs there

Here is the result: `{"ok":true,"result":{"id":1224580138,"is_bot":true,"first_name":"CopyAltSignalsBot","username":"C`

**Comment by AliRafieePour** [comment]
> @AliRafieePour And you are doing this from your server?

Yes, I'm currently running these on my Desktop. In the past, I never had such an issue running bots on my Desktop.

**Comment by Andrei-Dolgolev** [comment]
Not sure what it the same but right now not connection ot telegram from digigtal ocean servers wich based in SF bay area.

**Comment by AliRafieePour** [comment]
> Not sure what it the same but right now not connection ot telegram from digigtal ocean servers wich based in SF bay area.

Well, It's almost a week I'm facing this. I've also checked various proxies so as to check whether my network has an issue!

**Comment by tsnoam** [comment]
Can you please provide the output of:

``$ python -m telegram``

**Comment by AliRafieePour** [comment]
> Can you please provide the output of:
> 
> `$ python -m telegram`

Hi,

Here is the result:
```
python-telegram-bot 12.4.2
certifi 2020.04.05.1
future 0.18.2
python 3.7.3 <default, Apr 24 2019, 15:29:51> 
```
