### ISSUE TITLE
[BUG]bot not receiving poll answer update

### ISSUE THREAD

**Issue by Mirage8-1** [python-telegram-bot/python-telegram-bot#2077]
### Steps to reproduce
1. send a non anonymous quiz mode poll 

2. set a handler with filter poll

3. answer the quiz

4. the bot should receive poll answer update but it does not trigger the handler

### Expected behaviour
4. the bot should receive poll answer update but it does not trigger the handler

### Actual behaviour
nothing happens
### Configuration
**Operating System:**
python:latest docker image

**Version of Python, python-telegram-bot & dependencies:**
python 3.8.5
python-telegram-bot 12.8
``$ python -m telegram``

### code
```
from telegram import Update
from telegram.ext import CallbackContext, Handler
from telegram.ext.filters import Filters
from app.handlers.tghandler import TGHandler
from telegram.ext.messagehandler import MessageHandler


class PollHandler(TGHandler):
    @classmethod
    def get_handler(cls) -> Handler:
        return MessageHandler(filters=Filters.poll, callback=cls.callback)

    @classmethod
    def callback(cls, update: Update, context: CallbackContext) -> None:
        print(update.effective_message)
        print(update.poll)
        print(update.poll_answer)

```

**Comment by Bibo-Joshi** [comment]
Hi. In order to receive `PollAnwser` updates, you'll need to use `PollAnswerHandler`. `MessageHandler(Filters.poll, …)` will only be called on updates where `update.effective_message` and `update.effective_message.poll` are present. For `PollAnswer` updates, only `update.poll_answer` is set.
