### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Mehrbod2002** [python-telegram-bot/python-telegram-bot#2080]
Hello 
I use inline keyboard button but when I order it to return a past function and my past function is start and It uses to get update.message informations and as inline button call back changes  result how can I use it ?
My bot first use to order Client to join a channel and I use api for this part to check Client joined or no with inline keyboard button 
And I order it to return and to complete process of Client joining , it changes results of update 
How should I use ?

**Comment by Mehrbod2002** [comment]
> @Mehrbod2002 Gonna close this cause answered in the group [(here)](https://t.me/pythontelegrambotgroup/369378)

I didn't get response from there 
so I will open new issue like this

**Comment by Bibo-Joshi** [comment]
> so I will open new issue like this

Please first try to get an answer in the group. And please try to be more precise about your problem, then.
