### ISSUE TITLE
[QUESTION] send_document reusable file_id not working?

### ISSUE THREAD

**Issue by GRyabkin** [python-telegram-bot/python-telegram-bot#2082]
My bot receives a photo and I want to post this photo in the same chat, according to the documentation this should work but it doesn't:
`update.message.reply_document(update.message.chat_id, update.message.photo[-1].file_unique_id)`

what I am doing wrong?

**Comment by GRyabkin** [comment]
> telegram.PhotoSize.file_unique_id

I have tried it as well
I see this:
"caused error "Wrong remote file identifier specified: wrong string length"

and documentation you have linked states that file_unique_id "Can’t be used to download or reuse the file."

**Comment by Bibo-Joshi** [comment]
> and documentation you have linked states that file_unique_id "Can’t be used to download or reuse the file."

exactly. use `file_id` instead ;)

**Comment by GRyabkin** [comment]
@Bibo-Joshi it doesn't matter what to use `file_id` or `file_unique_id`, I see the same error message:
"caused error "Wrong remote file identifier specified: wrong string length"

**Comment by GRyabkin** [comment]
![Screen Shot 2020-09-11 at 21 29 20](https://user-images.githubusercontent.com/2230377/92960222-ef380b80-f475-11ea-8a9e-0c09978831ff.png)

**Comment by GRyabkin** [comment]
If I use 
`context.bot.send_document(message.chat_id, document=message.photo[-1].file_id)`
then I see this:

> "Type of file mismatch"

**Comment by Bibo-Joshi** [comment]
I guess your problem is that you pass `chat_id` to `reply_photo`. the shortcut already takes care of passing the `chat_id`, as the documentation states.
Also you can't send a photo by `send_document`.

**Comment by GRyabkin** [comment]
@Bibo-Joshi I think the problem is that the framework expects `File` or `PhotoSize` for `reply_photo` `send_photo` and `Document` or `File` for `send_document`

**Comment by GRyabkin** [comment]
![Screen Shot 2020-09-11 at 21 40 00](https://user-images.githubusercontent.com/2230377/92961086-5a361200-f477-11ea-83e3-dd782f97556c.png)

**Comment by GRyabkin** [comment]
I have removed `chat_id` and I see in the debugger that it skips `file_id` as a string
![Screen Shot 2020-09-11 at 21 44 45](https://user-images.githubusercontent.com/2230377/92961505-04ae3500-f478-11ea-91e2-c10c7f83136a.png)

**Comment by GRyabkin** [comment]
@Bibo-Joshi ok, I was wrong it works now. I missed that it assigns my photo (file_id) just as a string. Ok, thanks for the help

**Comment by GRyabkin** [comment]
I actually don't understand how should I figure out that there's no need to pass `chat_id`
Here's what I see in the official documentation:
![Screen Shot 2020-09-11 at 21 48 28](https://user-images.githubusercontent.com/2230377/92961923-c5341880-f478-11ea-9998-a55729302a81.png)

**Comment by Bibo-Joshi** [comment]
It sais it right there: `message.reply_photo(*args, **kwargs) == bot.send_photo(message.chat_id, *args, **kwargs)`
