### ISSUE TITLE
[QUESTION] Can't remove image with caption

### ISSUE THREAD

**Issue by GRyabkin** [python-telegram-bot/python-telegram-bot#2083]
I want to remove an image with a caption
I used `edit_message_text` to remove messages with only text and it works fine but in case if a message is an image then it doesn't work anymore and the message not deleted.

Is there some specific way to do this?

**Comment by GRyabkin** [comment]
@Bibo-Joshi  `edit_message_caption` edits caption but doesn't remove an image

**Comment by Bibo-Joshi** [comment]
If you want to complete delete as message just use `message.delete()`

**Comment by GRyabkin** [comment]
Thanks a lot. This is what I was looking for. Your replies are so quick, amazing
