### ISSUE TITLE
How to answer a request a second time

### ISSUE THREAD

**Issue by Fr33vvay** [python-telegram-bot/python-telegram-bot#2084]
1. User writes a request. Bot uses a map-API and writes name and address of the object.
2. Then user uses a command /more_info and bot sends other information (website, opening hours...)
I use telegram.ext Updater, but when I click /more_info my bot perceives it like a new request. How to remember last keyboard query?
Another way. How to remember all information from responce and send first part(name/address) then second part, when user clicks /more_info?

```python
def address_data(address, data=None):
"""properties is a dictionary with indo about object"""
    params ={
        'text': address,
        'type': 'biz',
        'results': 1,
        'lang': 'ru',
        'apikey': MAP_TOKEN
    }
    response = requests.get(url=URL, params=params)
    json = response.json()
    features = json['features'][0]
    properties = features['properties']['CompanyMetaData']
    if data is 'name':
         resp = f'{properties.get("name")}, {properties.get("address")}'
    elif data is 'info':
        resp = f'...'
    return resp

def name_address(update, context):
    update.message.reply_text(address_data(update.message.text, 'name'))

def other_info(update, context):
    update.message.reply_text(address_data(update.message.text, 'info'))

def main():
    updater = Updater(BOT_TOKEN, use_context=True)
    dp = updater.dispatcher

    dp.add_handler(CommandHandler("more_info", other_info))

    dp.add_handler(MessageHandler(Filters.text & ~Filters.command, name_address))

    updater.start_polling()
    updater.idle()
 ```

**Comment by Bibo-Joshi** [comment]
I'm not entirely sure that I understand you correctly, but I think you're are looking for `ConversationHandler`. Have a look at the [examples](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/conversationbot.py).

**Comment by Fr33vvay** [comment]
I use echobot.
Simply put, I need the bot to respond to an incoming message. And then, if the user clicks the button "more info", the bot replied to the same message again. Now when the user clicks the button, the bot returns a message "more info".

**Comment by Bibo-Joshi** [comment]
Sorry, I still don't understand. There are no keyboard buttons in your example. So which button do you expect your user to press?
Please have a look at this [article](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Ask-Right) and try to formulate your question again more precisely.

**Comment by Fr33vvay** [comment]
Sorry for that and thanks for the help. I will try to explain better. I looked at the conversationbot as you advised and this is my code:
`def address_data(address, data=None):
    """This function return information about object"""

def start(update, context):
    update.message.reply_text('What are you looking for?')
    return INFO

def name_address(update, context):
    """Name and address of object"""
    reply_keyboard = [['More_info']]
    update.message.reply_text(address_data(update.message.text),
                              reply_markup=ReplyKeyboardMarkup(reply_keyboard, one_time_keyboard=True))
    return MORE_INFO

def url(update, context):
    '''URL of object'''
    update.message.reply_text(address_data(update.message.text, 'url'), reply_markup=ReplyKeyboardRemove())
    return ConversationHandler.END

def cancel(update, context):
    user = update.message.from_user
    logger.info("User %s canceled the conversation.", user.first_name)
    update.message.reply_text('Bye! I hope we can talk again some day.',
                              reply_markup=ReplyKeyboardRemove())
    return ConversationHandler.END

def main():
    updater = Updater(BOT_TOKEN, use_context=True)
    dp = updater.dispatcher

    conv_handler = ConversationHandler(
        entry_points=[CommandHandler('start', start)],

        states={
            INFO: [MessageHandler(Filters.text & ~Filters.command, name_address)],
            MORE_INFO: [MessageHandler(Filters.regex('^(More_info)$'), url)]
        },
        fallbacks=[CommandHandler('cancel', cancel)]
    )

    dp.add_handler(conv_handler)

    updater.start_polling()
    updater.idle()`

What I need:
1. User click /start.
2. User writes request (example: Bar, London, Carnaby Street). Bot responds "Dehesa, GB, London, Carnaby Street"
3. User click button More_info to find out the bar url. But the bot responds url of the object "More_info" (something similar in name). How to fix it?

**Comment by Bibo-Joshi** [comment]
uh okay, so in the state `MORE_INFO`  you want to retrieve more info on `Bar, London, Carnaby Street`, but in your `url` callback it is `update.message.text == 'More_info'`.

You need to store, which bar your user requested. PTB provides `context.user/chat/bot_data` for that. You'll probably wanna go with `user_data` here. Please have a look at the wiki page on [storing data](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Storing-bot,-user-and-chat-related-data).

I'll go ahead and close as the problem seems resolved by this. If you have follow up questions, please join us in the [user-group](https://t.me/pythontelegrambotgroup) on TG :)
