### ISSUE TITLE
[QUESTION] Bot restart with polling. Webhooks and context.

### ISSUE THREAD

**Issue by GRyabkin** [python-telegram-bot/python-telegram-bot#2086]
### Issue I am facing
Hi there. I have made a bot using `polling` and it works fine but hangs after deploying new updates and needs restart.

### Question 1
Could you please suggest how to make the experience flawless from a user perspective without him/her restarting the bot using for e.g. `/start `command or button `restart` in the bot's profile? Is it possible at all with polling?

### Question 2
Does `webhook` keep `context` similar to `polling`?
Does `webhook` help to resolve the issue with new bot versions deployment without triggering restart from the bots users side?

**Comment by GauthamramRavichandran** [comment]
Restart from user is required only when there's any change in the menu, you can retrieve the menu everytime instead of keeping the same menu (refer `one_time_keyboard` parameter)

`context` is similar for both `polling` and `webhook`

If you want context/states to remain between restarts, implement any of these [methods](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Making-your-bot-persistent)

**Comment by Bibo-Joshi** [comment]
@GRyabkin I guess by "deploying new updates" you mean that you update the bots code? In that case of course you need to restart your script. That's just how python works (unless you do black magic using `eval()` …). Therefore you should just restart your bot yourself after updating the code and not let the user do that. This is independent of whether you use polling or webhook.

**Comment by GRyabkin** [comment]
@Bibo-Joshi I use pm2 to run the bot on AWS EC-2 instance and restart it using `pm2 restart` command which creates a new process. 
Will [the persistence](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#save-and-load-jobs-using-pickle) help to resolve the problem of the lost state by `ConversationHandler` after bot restart?

**Comment by Bibo-Joshi** [comment]
I don't know the details of AWS thingies and googling pm2 it seem related to javascript and node.js but not python. But discussing the specifics of different hosts is out of scope of this issue tracker. You can join our [off-topic usergroup](https://t.me/pythontelegrambottalk) at TG. maybe someone can help you in there.
The snippet you link is about persisting *jobs*. For persisting conversations, have a look at the wiki page @GauthamramRavichandran linked.

**Comment by GRyabkin** [comment]
> I don't know the details of AWS thingies and googling pm2 it seems related to javascript and node.js but not python. But discussing the specifics of different hosts is out of scope of this issue tracker. You can join our [off-topic usergroup](https://t.me/pythontelegrambottalk) at TG. maybe someone can help you in there.
> The snippet you link is about persisting _jobs_. For persisting conversations, have a look at the wiki page @GauthamramRavichandran linked.

![Screen Shot 2020-09-16 at 16 18 34](https://user-images.githubusercontent.com/2230377/93342671-46542c80-f838-11ea-8234-b91dc69c456e.png)
pm2 allows running my bot written in python in the background

@Bibo-Joshi @GauthamramRavichandran  yes, I think persistence is what I was looking for. I just wanted to confirm it. Thanks
