### ISSUE TITLE
InlineKeyboardButton

### ISSUE THREAD

**Issue by saman-pasha** [python-telegram-bot/python-telegram-bot#2087]
all things work but when i set a string value to switch_inline_query gives me BadRequest
`
InlineKeyboardMarkup([
        [ InlineKeyboardButton(text='📆 ' + str(question_post.date), callback_data='*:*') ],
        [ InlineKeyboardButton(text='✉ ️Send', switch_inline_query='A2') ],
        [ InlineKeyboardButton(text='❌ Delete', callback_data='remove:' + str(question_id)) ]
    ]
`

**Comment by Bibo-Joshi** [comment]
What's the exact error message? Can you provide a [minimal working example](https://telegra.ph/Minimal-Working-Example-for-PTB-07-18)?

**Comment by saman-pasha** [comment]
2020-09-16 08:10:22 <class 'telegram.error.BadRequest'> BadRequest() [<FrameSummary file /var/www/soyguiri_bot/soyguiri_bot.py, line 42 in telegram_webhook>, <FrameSummary file /var/www/soyguiri_bot/channel.py, line 60 in process_channel_post>, <FrameSummary file /usr/local/lib/python3.6/dist-packages/telegram/bot.py, line 66 in decorator>, <FrameSummary file /usr/local/lib/python3.6/dist-packages/telegram/bot.py, line 1918 in edit_message_reply_markup>, <FrameSummary file /usr/local/lib/python3.6/dist-packages/telegram/bot.py, line 123 in _message>, <FrameSummary file /usr/local/lib/python3.6/dist-packages/telegram/utils/request.py, line 327 in post>, <FrameSummary file /usr/local/lib/python3.6/dist-packages/telegram/utils/request.py, line 238 in _request_wrapper>]

**Comment by saman-pasha** [comment]
```python
question_pattern = re.compile("^!(.*)$\n^\?(.*)$\n((^[+-].*$\n)*)^\*(.*)$\n^#(.*)$", re.M)

def question_keyboard(question_post, question_id):
    return InlineKeyboardMarkup([
        [ InlineKeyboardButton(text='📆 ' + str(question_post.date), callback_data='*:*') ],
        [ InlineKeyboardButton(text='✉ ️Send', switch_inline_query='A2') ],
        [ InlineKeyboardButton(text='❌ Delete', callback_data='remove:' + str(question_id)) ]
    ]);


def process_channel_post(bot, channel_post):
    if channel_post.chat.id == ROOT_CHAT_ID:
        match = question_pattern.search(utils.extract_text(channel_post))
        if match != None:
            question = match.group(2).strip()
            answers  = match.group(3).split('\n')[:-1]
            notice   = match.group(5).strip()
            link     = match.group(6).strip()
            level    = match.group(1).strip()
            id = add_question(question, answers, notice, link, level)
            if id > 0:
                bot.edit_message_reply_markup(chat_id=channel_post.chat.id, message_id=channel_post.message_id,
                                              reply_markup=question_keyboard(channel_post, id))
    else:
        bot.send_message(chat_id=channel_post.chat.id, text='You are not the admin of SoyGuiri')
        bot.leave_chat(channel_post.chat.id)
    return
```

**Comment by Bibo-Joshi** [comment]
Okay, as far as I understand, the problem is that you try to send a button with `switch_inline_query` to a *channel*. When I try that, I get an error

```python
telegram.error.BadRequest: Can't use switch_inline_query in a channel chat, because a user will not be able to use the button without knowing bot's username
```

which already explains everything. Hence, I'll close.

**Comment by saman-pasha** [comment]
But i give this message
```python
{'message': "Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard"}
```

**Comment by Bibo-Joshi** [comment]
Then please provide a *full* MWE as described by the article linked above

**Comment by saman-pasha** [comment]
Thank you, It was as you said, `switch_inline_query` only works on messages which created by bot on direct chat
