### ISSUE TITLE
InlineQueryResultCachedPhoto

### ISSUE THREAD

**Issue by saman-pasha** [python-telegram-bot/python-telegram-bot#2088]
why client does not show the title and desription of InlineQueryResultCachedPhoto? just shows the photo.

**Comment by Bibo-Joshi** [comment]
This is what @BotSupport replied to my questions:

> Title and description for photos would be shown only in situations when preview of the image can't be generated.

**Comment by Bibo-Joshi** [comment]
Small update for anyone stumbling on this: As of 2021-05-18, the official Android client will display title and description are displayed e.g. when the results also contain `InlineQueryResultArticles`. See https://gist.github.com/Bibo-Joshi/ff3deb015e027c89e10b2f261d1b5146 for an example.
