### ISSUE TITLE
I encountered a bug when using markdown

### ISSUE THREAD

**Issue by Sesprie** [python-telegram-bot/python-telegram-bot#2095]
### Issue I am facing
The result of markdown preview is not as expected

**Expected result**
[[Hello]World](https://www.google.com)

**The result i got**
`\[HelloWorld](https://www.google.com)`

### Traceback to the issue
```
no traceback
```

### Related part of your code
```python
text = telegram.utils.helpers.escape_markdown('[Hello]World')
url = 'https://www.google.com'
update.message.reply_text('[{}]({})'.format(text, url), parse_mode="Markdown")
```

**Comment by Bibo-Joshi** [comment]
Hi. AFAIK Markdown V1 just can't handle `[]` in the text part of text links. Unfortunately that's not documented …
Anyway, as Markdown v1 is deprecated, I advise you to either use Markdown v2, which can handle that or use HTML formatting which in my experience is more robust.

**Comment by Sesprie** [comment]
thank you very much
