### ISSUE TITLE
[DOCUMENTATION] Disclaim our dependencies properly

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#2099]
We should list them clearly, mention their licenses, link to said licenses; check if something varies on a per system basis.

**Comment by abelacu95** [comment]
I can work on this :)

**Comment by rexdivakar** [comment]
Assign it to me i will add in @Poolitzer

**Comment by Bibo-Joshi** [comment]
@rexdivakar I issigned you. Please base your PR on the v13 branch.

**Comment by rexdivakar** [comment]
Hey @Bibo-Joshi  the exisiting license u own is  ""GNU LESSER GENERAL PUBLIC LICENSE Version 3, 29 June 2007"" do u want me to check its options and its conditions matching ur application needs ?

**Comment by Bibo-Joshi** [comment]
@rexdivakar sorry, I'm not sure that I understand what you mean. What do you want to check?

**Comment by Bibo-Joshi** [comment]
Closing as, we have no pressing need for this. We can reopen in october 😄
