### ISSUE TITLE
Bot hangs when calling `username` on update

### ISSUE THREAD

**Issue by v0dro** [python-telegram-bot/python-telegram-bot#210]
I have an `accept_message` method which is a callback for `addTelegramMessageHandler`.

The method looks like this:
``` python
def accept_message(bot, update):
    d = {
        'chat_id': update.message.chat_id,
        'text': update.message.text,
        'username' : update.message.username,
        'bot': bot
    }
```

Strangely, the bot just freezes when `'username'` is called.

I tried adding a `print update.message.to_dict()` at the beginning of `accept_messages` and it still gives the same behavior. Basically anything called on `update.message` except `.chat_id` or `text` causes the program to hang on that line.

**Comment by v0dro** [comment]
**EDIT:**

Ok so calling `update.message.from_user.username` solves the problem, but I still think the program hanging on that method is a problem which should be fixed.

**Comment by jh0ker** [comment]
Hi
What do you mean by "freeze"? Does the bot stop to work completely?

What's likely happening here is that an `AttributeError` is raised because you tried to access `update.message.username` which does not exist. The error is caught and delivered to all handlers that are registered with `Dispatcher.addErrorHandler`. That is normal and expected behaviour. 

If something else is happening, I will need more information, like logs.

**Comment by v0dro** [comment]
By 'freeze' I mean that the program stops execution at that line and does not print any output (or stack trace). I'll add an error handler and see if I can get a stack trace.

I didn't know about `addErrorHandler`. Don't you think it's more intuitive to print the stack trace like any other error message rather than sending it to a handler?

**Comment by jh0ker** [comment]
Ah right, I mixed up something, sorry. The error should indeed be caught, only Errors of type `TelegramError` will be delivered to error handlers. All other errors are caught and logged. Turn on the logging module with 

    import logging

    # Enable logging
    logging.basicConfig(
            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            level=logging.DEBUG)

at the beginning of your script

**Comment by v0dro** [comment]
Ah. Will it possible to add this and other relevant details to the README?. It might make it much easier for others to fix bugs that way. I spent a lot of time trying to figure this out!

**Comment by rahiel** [comment]
> Ah. Will it possible to add this and other relevant details to the README?. It might make it much easier for others to fix bugs that way. I spent a lot of time trying to figure this out!

How to setup logging is mentioned in the README, at the beginning of the [Getting started](https://github.com/python-telegram-bot/python-telegram-bot#getting-started) part. The documentation could have some more clarity, we'll work on it!

**Comment by a7son** [comment]
It's always hang when user didn't have username... like someone who register with only phone number.. any solution for this?

**Comment by tsnoam** [comment]
@a7son Please don't resurrect ancient issues.
For help with usage, please see our users group on telegram http://t.me/pythontelegrambotgroup
For issues with the library please open a new one and follow the issue template.
