### ISSUE TITLE
Question: How to "start" the bot after "shutdown"?

### ISSUE THREAD

**Issue by Karatel11** [python-telegram-bot/python-telegram-bot#2103]
When I shutdown the bot with updater.stop(), it stops forever. But I want it to work after "/start". 

For example: It's Echo bot
When I texted "/start", it returned my messages. And when I stopped it with "/stop", it didn't return my messages. But when I texted "/start" again, it didn't work. It froze forever and the only way to continue the work is to press the  "Run" button in PyCharm. 

Could you please explain how to fix it?

**Comment by JosXa** [comment]
Hi, thanks for your question. Usually we will answer these in the support groups, but I will be kind and reply to you here.

What's your actual use case for this?
updater.stop() is meant for graceful shutdown of the system when it actually ends. If you want a restart command, check the snippets as there are some examples on how to restart the whole python process.
