### ISSUE TITLE
Overhaul & extension of constants

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2104]
We have constants in different locations, e.g.

* `telegram.constants`
* class attributes of `telegram.ParseMode`
* class attributes of `telegram.Dice`

That should be unified, i.e.:

- [x] Gather all constants in `telegram.constants` (I guess a regex-search for `SCREAMING_SNAIL_CASE` should do the trick …)
- [x] Repace the class attributes by links to the constant from `telegram.constant`, (e.g. `ParseMode.HTML = constants.PARSE_MODE_HTML`)
- [x] Add additional links, where suitable (e.g. `Message.MAX_LENGTH = constants.MAX_MESSAGE_LENGTH`)

Moreover, in light of the recent TG update, we should add

- [ ] constants for user ID `777000` and `1087968824`, which act as senders for forwarded channel posts and messages from anonymous admins (see [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#exclude-messages-from-anonymous-admins))
- [ ] Add properties `is_anonymous_admin` and `is_service_chat` (or similar namings) to `User` and `Chat` that compare the user/chat_id to the IDs menotioned above

*Edit:* there should be notes on the constants, if they are not documented. And going through the docs to see if there are constants not covered already probably won't hurt …

**Comment by Poolitzer** [comment]
maybe mention the ids are just from our experience and not officially mentioned?

**Comment by NikitaPirate** [comment]
I would like to do this. Did I understand correctly that I need to transfer the attributes of all classes to constants? Or should it be done selectively? I made a test commit, please tell me, am I moving in the right way? https://github.com/NikitaPirate/python-telegram-bot/commit/d599259dfda0622b87894d88303ad802630fefa9

**Comment by NikitaPirate** [comment]
Maybe it will be better if I only move constants to constants.py and make the class attributes link to it and leave everything else unchanged? Or is it better to change `Class.ATTR` to `constants.CONSTANT` in all code?

**Comment by NikitaPirate** [comment]
I did my experiments and got the same IDs. I think `channel_forwarder_service` is good name for 777000.

**Comment by Poolitzer** [comment]
I think its good, jup. Just make sure to note with a warning in the docs that this is undocumented behavior wherever you link this
