### ISSUE TITLE
[BUG] DictPersistence not working

### ISSUE THREAD

**Issue by nikolockenvitz** [python-telegram-bot/python-telegram-bot#2109]
### Steps to reproduce

The following bot should save data for a chat. It works to set data and use this when a second message arrives. But when I restart the bot, no data is found and the dict is empty.

```python
import os
from telegram.ext import Updater, CommandHandler, DictPersistence

class TelegramBot:
    def __init__(self):
        self.updater = Updater(
            token=os.getenv("TELEGRAM_BOT_TOKEN"), # set it via env or paste your token as a string here
            persistence=DictPersistence(store_user_data=False, store_chat_data=True, store_bot_data=False),
            use_context=True
        )
        self.dispatcher = self.updater.dispatcher

        self.dispatcher.add_handler(CommandHandler('help', self.help))

        self.updater.start_polling()
        self.updater.idle()
    
    def help(self, update, context):
        print(context.chat_data)
        context.chat_data["asked_for_help"] = True
        context.bot.send_message(chat_id=update.effective_chat.id, text="Help is on the way!")

t = TelegramBot()
```

### Expected behaviour
After doing all necessary steps described [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Making-your-bot-persistent#what-do-i-need-to-change) I expect that the bot is able to load data into the dictionary after restarts.

### Actual behaviour
No data is saved, no data can be loaded when the bot restarts.

### Configuration
**Operating System:** Win10

**Version of Python, python-telegram-bot & dependencies:**

```bash
$ python -m telegram
python-telegram-bot 12.8
certifi 2020.06.20
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:43:08) [MSC v.1926 32 bit (Intel)]
```

### Additional Notes

When using PicklePersistence it works to load data after a restart. I suspect that in DictPersistence no data is written at all to any file. For PicklePersistence it might be only working because it implements the `flush` method.

Why isn't there a way to specify the filename for the json?

**Comment by nikolockenvitz** [comment]
I don't have time to post a PR for this repo but you can find the necessary implementation steps (for saving dicts to and reading them from json file) [here](https://github.com/rcjberlin/rcj-notification-bot/blob/3f9dfc8f284b8d440a851b8d7574cc59492ef329/bots/telegram/chat_persistence.py). In my case I only implemented the parts for `chat_data` but it's pretty obvious what needs to be done for the others.

**Comment by Bibo-Joshi** [comment]
Hi. `DictPersistence` is in fact only in-memory and is mainly intended as starting point for custom persistence classes that need to json-dump the data. We'll elaborate that in the docs & wiki :)

**Comment by nikolockenvitz** [comment]
It should not be named persistence then. But great if you can update the docs accordingly so that it's clear 👍
