### ISSUE TITLE
guide us to on how to change type of menu used to ReplyKeyboardMarkup

### ISSUE THREAD

**Issue by FatimaAlmashi** [python-telegram-bot/python-telegram-bot#2111]
### Issue I am facing
Please describe the issue here in as much detail as possible

### Traceback to the issue
```
put it here
```

### Related part of your code
```python
put it here
```

**Comment by FatimaAlmashi** [comment]
hhhhhhhh im sorry can we contact on telegram plzzzzz

**Comment by Bibo-Joshi** [comment]
You are welcome to ask in the user group linked in the README but also there you are expected to ask good questions ;) So please read the article linked above. I'll go ahead and close this issue.
