### ISSUE TITLE
[QUESTION] Read the last/latest message/s from a public channel

### ISSUE THREAD

**Issue by NicoCaldo** [python-telegram-bot/python-telegram-bot#2112]
I'm building a script that checks if a certain message has been already sent on the channel. To do that I need to read a certain number of previous messages.

I've already built my bot and set it to send messages on the channel (it works) as below
```
bot = telegram.Bot(token='mytoken')
bot.sendMessage(chat_id='@mychatid', text=entry.link)
```
I was looking to a class named something like bot.getLastMessage() or bot.getMessagefromID(id_number) that returns the message or messages into a string or a list containing strings but I haven't found something.

I'm missing it or there's no implementation of such functions?

**Comment by Poolitzer** [comment]
Hi, you are correct, there is no implementation of such functions, since they don_t exists. There is basically no solution to your problem. You can only wait for updates from said channels, that's it.

**Comment by JosXa** [comment]
This sounds very doable as there's no requirement about making this work for **old** messages aswell (i.e. channel posts that have been sent BEFORE the bot has been added). Therefore, just write all channel posts to a database and compare with that.

**Comment by NicoCaldo** [comment]
> This sounds very doable as there's no requirement about making this work for **old** messages aswell (i.e. channel posts that have been sent BEFORE the bot has been added). Therefore, just write all channel posts to a database and compare with that.

As soon as the messages sent into the channel are sent only by the bot, yes, that was my plan B if no solution was found
