### ISSUE TITLE
[BUG] InlineQueryResultPhoto: Title and Description of the result are not displayed.

### ISSUE THREAD

**Issue by Dubzer** [python-telegram-bot/python-telegram-bot#2115]
I've coded this InlineQuery handler:

```
def inlinequery(update, context):
    update.inline_query.answer([
        InlineQueryResultPhoto(
            id=uuid4(),
            photo_url="https://upload.wikimedia.org/wikipedia/commons/c/c9/Moon.jpg",
            thumb_url="https://upload.wikimedia.org/wikipedia/commons/c/c9/Moon.jpg",
            title="It is the moon.",
            description="wow...")])
```

In theory, it should show title and description of the result, like InlineQueryResultArticle do. In fact, it displays only photo in Telegram for Android, Telegram X, Telegram Desktop and Unigram

![Picture](https://user-images.githubusercontent.com/18244287/95224606-8ab56580-0803-11eb-9444-1e2d5bbb3a17.png)
Am I doing something wrong, or is it bug on Telegram side?
I used python_telegram_bot-12.8

**Comment by Bibo-Joshi** [comment]
See #2088
