### ISSUE TITLE
[QUESTION] How can I exclude users from results when they stop sharing their live location?

### ISSUE THREAD

**Issue by Valaia** [python-telegram-bot/python-telegram-bot#2117]
Hello. I'm trying to create a bot that stores users' location in a dictionary. The bot is supposed to assist with a barebones food delivery service and track the couriers' locations so it can assign new orders per their proximity to the restaurant. Works like this: couriers share their live location with the bot for a period of time(8 hours) and the bot constantly updates the dictionary with username : location

### Issue I am facing

I want the user to be excluded from the dictionary's next update when they stop sharing their location(when they get off work). That does not happen and the bot keeps adding their last broadcasted location. How can I fix this? Thank you! 

### Related part of your code
```
def location(update, context):
        message = update.effective_message
        location = message.location.latitude, message.location.longitude
        location = str(location)
        location = location.replace("'", "").replace("(", "").replace(")", "")
        dict[message.from_user.first_name]=str(location)
        print(dict)
```

**Comment by Bibo-Joshi** [comment]
Afaik bots can't know if location update is a live location or not. For live locations they will just receive a location update every time the locations is updated and will no longer receive location updates, when the live location is ended.
So maybe your best shot is dropping the user if the last location update is older than x seconds.

**Comment by Valaia** [comment]
I was actually trying a similar improvisation now, only assigning the variable to the dictionary if it's different from the previous one. But your idea seems more elegant. Do you know how I can check the age of the last message/last location update? Thanks!

**Comment by Bibo-Joshi** [comment]
You can save the location messages date along with the location (`update.message.date`)
