### ISSUE TITLE
How to create interaction longer than one message?

### ISSUE THREAD

**Issue by Scinawa** [python-telegram-bot/python-telegram-bot#212]
Hi,
I would like to know if there are some code example or something. What If I want to write function (say /addText) and then, the next message the user send, receive the text and process the text according to the command. 

Now I could write  a function that if I send "/addText bla bla bla bla" manage to process the text "bla bla bla" because is in the same update of the command. 

But what if I want the text to process on multiple lines, until I reach a specific string (like "End") or something?

So, my idea is to develop a Finite State Automata: each time a new message arrives I interpret it according to the "state" the user is.

Thanks for help

**Comment by zefoo** [comment]
I think you would need to know when to start this "waiting" state. eg. /begin Hey this is Me. Add more text, add more text (meanwhile, this is all being captured in a database). Then when the end is received (command or certain word), you could process from start to finish by pulling items from database.

**Comment by jh0ker** [comment]
Hey, I've uploaded an example of a bot that uses a simple finite state machine here: https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/state_machine_bot.py

**Comment by jh0ker** [comment]
If you don't feel like your question has been answered, please re-open this issue.
