### ISSUE TITLE
[IMPROVEMENT] change our format to f-strings

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#2124]
Since we dropped 3.5 support, we can now introduce f-strings. This will be a great first issue for someone new who wants to do manual work, or a great regex kind of task for someone who wants to go crazy.

**Comment by Bibo-Joshi** [comment]
F strings shouldn't be used for logging, though, as that actually doesn't like `format`

**Comment by NishantPuri99** [comment]
Hi @Poolitzer I'd like to take this up

**Comment by Bibo-Joshi** [comment]
@NishantPuri99 I assigned you :)

**Comment by NishantPuri99** [comment]
Thank you so much :)

**Comment by NishantPuri99** [comment]
Hi @Bibo-Joshi and @Poolitzer , I've made the required changes. I hope they are correct and valid, and that the code still works fine.
Thanks and regards
