### ISSUE TITLE
[FEATURE] Filter for chat types

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2126]
We currently have 

* `Filters.private` for private chats
* `Filters.updates.channel_post` for channel posts
* `Filters.group` for normal *and* supergroups

We're missing a standalone supergroup filter. Different ideas listed below. Personally, I'd go for 3.

# Proposal 1: Minimal invasive

* Add `Filters.supergroup`
* Document that `Filters.group` allows both

# Proposal 2: Adding flags

* Add a flag to `Filters.group` to specify, whether supergroups should be allowed or not

# Proposal 3: The full way

* Add `Filters.chat_type` that basically acts like `Filters.chat/user/via_bot`, just with `update.effective_message.chat.type`. We don't need to have `Filters.chat_type` updatetable, though IMHO. I really don't see a usecase for that.
* Add shortcuts for `private, channel, (super)group` as attributes to `Filters.chat_type` (similar to the `Filters.dice`)
* Make `Filters.private, group` shortcuts that work with `Filters.chat_type` and deprecate them (adding `TelegramDeprecationWarning` and documenting it)

By this, we would have two checks for `channel` (`Filters.chat_type.channel` and `Filters.update.channel_post(s)`), but especially is the latter allows to differentiate between original and edited channel post, I thinks both have their value.

**Comment by GauthamramRavichandran** [comment]
I'll do the standalone supergroup filter, **Proposal 1**

**Comment by GauthamramRavichandran** [comment]
#2128

**Comment by Poolitzer** [comment]
Theoretically, suggestion 1 would be enough, yes. But I would go with three. `update.effective_chat.type` should be more straightforward though.

How well is the difference between the two channel post filters documented? Might be even worth an example in the filters main page.

**Comment by Bibo-Joshi** [comment]
> Theoretically, suggestion 1 would be enough, yes. But I would go with three.

Cool, then we're on the same page

> `update.effective_chat.type` should be more straightforward though.

Yes, that's good

> How well is the difference between the two channel post filters documented? Might be even worth an example in the filters main page.

```
channel_post - Updates with telegram.Update.channel_post

edited_channel_post - Updates with telegram.Update.edited_channel_post

channel_posts - Updates with either telegram.Update.channel_post or telegram.Update.edited_channel_post
```

I'd say that's documented well enough and we don't need an example
