### ISSUE TITLE
[QUESTION] from telegram import Bot ImportError: cannot import name 'Bot' from 'telegram'

### ISSUE THREAD

**Issue by L64** [python-telegram-bot/python-telegram-bot#2133]
Hi, I don't know if this is a bug, but, my bot is having this problem constantly, the bot stops and this message apears:
```
File "bot.py", line 2, in <module>
    from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\ext\__init__.py", line 21, in <module>
    from .basepersistence import BasePersistence
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\ext\basepersistence.py", line 25, in <module>
    from telegram import Bot
ImportError: cannot import name 'Bot' from 'telegram' (C:\Users\[username]\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\__init__.py)
```
I tested it from Repl.it and the error stills

### Info

- Python 3.7.3

- python-telegram-bot 1.30

**Comment by Poolitzer** [comment]
Hi, that normally means you have a file named telegram.py in your base directory. Rename that and you should be good to go.

**Comment by L64** [comment]
> Hi, that normally means you have a file named telegram.py in your base directory. Rename that and you should be good to go.

I don't have any telegram.py file in the base directory

**Comment by L64** [comment]
> @L64 Can you run `pip show telegram`?

Yes

**Comment by L64** [comment]
> @L64 Great. Can you paste the result here?

```
Name: telegram
Version: 0.0.1
Summary: Telegram APIs
Home-page: https://github.com/liluo/telegram
Author: liluo
Author-email: i@liluo.org
License: MIT
Location: c:\users\[username]\appdata\local\programs\python\python37\lib\site-packages
Requires:
Required-by:

```

**Comment by L64** [comment]
> @L64 Okay, so that is the issue. Run `pip uninstall telegram`

Completed, now I reinstall it?

**Comment by L64** [comment]
> @L64 No, now you can run your scripts :)

It didn't worked in my computer (it don't matters for me) but it worked in Repl.it :-) Thanks!!!!!!
