### ISSUE TITLE
Deprecated using in v3.4

### ISSUE THREAD

**Issue by clearsense** [python-telegram-bot/python-telegram-bot#214]
I'm upgrade code module form v3.3 to new v3.4 and get this:

``C:\Python34\lib\site-packages\telegram\__init__.py:59: UserWarning: telegram.Updater is being deprecated, please use telegram.ext.Updater from now on.
  warnings.warn("telegram.Updater is being deprecated, please use "``

**Comment by jh0ker** [comment]
We moved `Updater`, `Dispatcher` and `JobQueue` to `telegram.ext`. Instead of `from telegram import Updater`, please use `from telegram.ext import Updater` from now.
