### ISSUE TITLE
[FEATURE] introduce a file ending filter

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#2140]
Users might want to filter incoming updates based on the file endings on top of/instead of the mime type. Both attributes of documents are not safe, but that didn't stop us from introducing a mime type want and shouldn't stop us from a file ending one either. Both are a great way of initially filtering incoming files. We should just mention in the docs, as we do with mime types, that telegram doesnt offer any validation.

This filter can either be a subset of Filters.document or its own imo.

**Comment by Bibo-Joshi** [comment]
+1 for `Filters.document.extension`. As documents are the only valid use case, I thinks thats more natural than `Filters.extension`

**Comment by mlemosf** [comment]
Can i give this issue a shot?

**Comment by Poolitzer** [comment]
Sure!
