### ISSUE TITLE
[FEATURE] Specify what to do when the number of instances in the job_queue reaches the limit

### ISSUE THREAD

**Issue by Konano** [python-telegram-bot/python-telegram-bot#2141]
Sometime I will see the warning: 
`Execution of job "xxxxx (trigger: interval[0:01:00], next run at: 2020-xx-xx xx:xx:xx UTC)" skipped: maximum number of running instances reached(1)` 
But I want to kill the old instance, then run the new instance, so can we add a parameter to specify what to do when the number of instances reaches the limit.

For example: `updater.job_queue.run_repeating(sendMessage, skip=False)` means it will kill the old instance when we reach the limit, not skip.

**Comment by Bibo-Joshi** [comment]
Hi!
As of v13 we're using the 3rd party lib APScheduler for the `JobQueue`. So what happens in such cases is not really a concern of PTB anymore. A quick workaround would be to increase the `max_instances`, (see [this](https://github.com/python-telegram-bot/python-telegram-bot/issues/1338#issuecomment-656622278) comment). For other solutions, please have a look at the APS-docs :)

**Comment by Konano** [comment]
> Hi!
> As of v13 we're using the 3rd party lib APScheduler for the `JobQueue`. So what happens in such cases is not really a concern of PTB anymore. A quick workaround would be to increase the `max_instances`, (see [this](https://github.com/python-telegram-bot/python-telegram-bot/issues/1338#issuecomment-656622278) comment). For other solutions, please have a look at the APS-docs :)

Thanks!
I look at the APS-docs but I can't find a better solution. Anyone can help?

**Comment by Bibo-Joshi** [comment]
I'm gonna go ahead and close for the above mentioned reasons ;)
