### ISSUE TITLE
[BUG] Update timerbot example

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2144]
https://github.com/python-telegram-bot/python-telegram-bot/blob/3b4559dd95d14a4c9a9ca54237b5fe547386b666/examples/timerbot.py#L56-L58

If the job has already run, those lines give an error after v13.0, as APS remvos the job after it has run. But as jobs can't be persisted natively, I think we should just restructure the example to give the jobs the `chat_id` as name and use `get_jobs_by_name` to remove them if necessary

Edit: And we should definetely remove the `pass_*` kwargs, those are deprecated since v12 …

**Comment by timqsh** [comment]
Hi! I would like to help with this one.

**Comment by Bibo-Joshi** [comment]
Great :) I'll assign you
