### ISSUE TITLE
[BUG] Infinite loops with insert/replace_bot

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2145]
You fiddle with persistence, you introduce bugs … #1994 not introducing bugs would have been too easy :D

```python

class A:
     b = None

class B:
    a = None

a = A()
b = B()
a.b = b
b.a = a

replace/insert_bot(a)  # this exceeds max recursion limit
```

Luckily that can easily resolved by passing a `memo` dict just as `deepcopy` does and while tracking down the bug I already made the required changes to `insert_bot`. I'll try to adjust `repace_bot` accordingly and write some tests in the next days.

**Comment by tsnoam** [comment]
Honestly,
double referencing should not be used. Shows a design flaw in the program.
