### ISSUE TITLE
Using of start_webhook

### ISSUE THREAD

**Issue by clearsense** [python-telegram-bot/python-telegram-bot#215]
I was using updater.start_polling() method and all was working fine, but polling do nothing most of time and spend traffic.
So, now i want use updater.start_webhook() and get new updates only when its come:
``self.updater.start_webhook(listen='127.0.0.1',
                                   port=443,
                                   url_path=BOT_TOKEN)``
I run it localy and it sometimes work (sometimes i had Error 400) and then i get:
``2016-03-23 06:54:21,042 - telegram.utils.webhookhandler - DEBUG - Webhook Server started.``
but my bot don't react on commands.

So, question is how to do it right? 
Maybe i need to rewrite some other code or use setWebhook+flask instead. 
But what start_webhook() is used for then?

**Comment by jh0ker** [comment]
Two things:

1. You put `127.0.0.1` as your listen address. That means the library will only listen for incoming connections _from your own machine_. You have to put the public IP address of your server there, instead.

2. You also have to use HTTPS encryption to receive telegram updates, so you need an SSL certificate. Either you already have one that works for a domain name, then you have to provide a custom `webhook_url` in `start_webhook()`, or you have to generate a self-signed one.

**Comment by clearsense** [comment]
Sorry, but I don't clear with using of start_webhook anyway.
Give yet some explanations, please.

https://www.pythonanywhere.com/forums/topic/2674/
``your webhook URL will be using our SSL cert for *.pythonanywhere.com, which is not self-signed, so that's not the problem. It will work on port 80 (the http port) and port 443 (the https port)``

So it will be smth like this?
``self.updater.start_webhook(listen='mybot.pythonanywhere.com',
		                            port=443,
		                            url_path=BOT_TOKEN)``
Or ``listen=https://api.telegram.org`` and i also need smth like ``webhook_url=mybot.pythonanywhere.com:443/BOT_TOKEN``?

And i have cert and key files in mybot dir, should i use them or, following the link, i din't need this?

For clear: my goal is to get receive updates from Telegram only, when they created.
Thanks, for you help)

**Comment by jh0ker** [comment]
The correct line would probably be 

    self.updater.start_webhook(listen='0.0.0.0', port=443, url_path=BOT_TOKEN, 
                               cert='path/to/cert.pem', key='path/to/key.key', 
                               webhook_url='https://mybot.pythonanywhere.com/%s' % BOT_TOKEN)

This should start the server to listen from updates from the internet and set the correct webhook url

**Comment by clearsense** [comment]
Thanks for help, but it doesn't work for me too. 
One programmer said me that if i use Flask option of ``pythonanywhere.com``, i must use Flask for webhook purpose. In any case, i rewrite code for flask and it's work.

**Comment by sshkrv** [comment]
I use exactly the same code and I've got the same trouble. No response from bot
`updater.start_webhook(listen='0.0.0.0',
                          port=8443,
                          url_path='TOKEN,
                          key='private.key',
                          cert='cert.pem',
                          webhook_url='https://178.128.170.36:8443/TOKEN')`

**Comment by clearsense** [comment]
You can get more info about whats is wrong using this https://core.telegram.org/bots/api#getwebhookinfo
Maybe it helps
