### ISSUE TITLE
Max timeout for start_polling is 50 sec

### ISSUE THREAD

**Issue by clearsense** [python-telegram-bot/python-telegram-bot#216]
Maybe i do smth wrong, but i try to do that

``start_polling(timeout=100)``

but in fact, timeout is 50 sec.

P.S. start_polling - does simple short polling right?
If it is long why (for default case) do we get empty updates every 10 sec?

**Comment by tsnoam** [comment]
The `timeout` as explained in the documentation is passed to the telegram servers as part of the `getUpdates` call. (you can also check the API documentation:  https://core.telegram.org/bots/api#getupdates )
It is up to the telegram servers to honour this timeout for their own discretion.
