### ISSUE TITLE
[BUG] Error codes

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2162]
https://github.com/python-telegram-bot/python-telegram-bot/blob/ff3fd34f081c66affdaa601c52b39b285b6603e0/telegram/utils/request.py#L268-L280

We currently raise `InvalidToken` for 404, though 404 [seems to be raised](https://core.telegram.org/api/errors) when requesting non-existing methods.
`Unauthorized` (=401) is the acutal `InvalidToken` and 403 gives `Forbidden`. So

* 401 -> `Unauthorized`
* 403 -> `Forbidden`
* drop `InvalidToken`/only use it in `Bot._validate_token`

I do think we should update that. However those are pretty much breaking changes, so probably only in the next major release …

**Comment by stdz56** [comment]
I think that the current behavior is the right behavior.

To raise InvalidToken you have to: 
- pass an empty string as token 
- pass a token without digits
- pass a token without letters

If you actually pass a token Digits:Letters, it doesn’t raise InvalidToken as it’s a correct token from this view. 

Unauthorized is indeed the more appropriate for that case: https://api.telegram.org/bot1234567:ABCDEFGHI/getUpdates as the token is not invalid but you can’t use it anyway.

Even thought, users are more used to see Unauthorized related to trying to send messages to users that haven’t started the bot and it could indeed mislead.

**Comment by Bibo-Joshi** [comment]
I'm not sure if I fully understand what you'r saying. I'll try to summarize the behavior:

* correctly formatted token, but a non-existend method → "404 not found"
* correctly formatted token that is invalid → "401 Unauthorized"
* valid token but not enough rights → "403 Forbidden"
* malformed token → "404 not found"

We can rule out calling of non-existend methods, because we don't expose manual api calls to the user. That leaves is with 404 only happening for malformed tokens.

So we could

* raise `InvalidToken` for 404 and 401 (imho that's a more descriptive name than "Unauthorized")
* make 403 raise `Forbidden`
* keep `Unauthorized` as synonym for `Forbidden` for backwards compatibility with 403. It's unlikely that someone keeps a process running with correctly formatted but invalid token, so *not* keeping backwards compatibility with `Unauthorized` being raised for 401 is justifiable IMHO, especially if we do this in a major release

**Comment by SanthoshS20** [comment]
@Bibo-Joshi Can i contribute to this issue?

**Comment by Poolitzer** [comment]
it is in a later stage right now. I think this is because handling the API calls will drastically change once we implement this via async, so it doesn't make sense to change it for the threaded way we have right now. Since we arent at the stage yet where we switch to asyncio, it will also take a while since this issue is tackable.
