### ISSUE TITLE
[BUG] telegram.ext.dispatcher ERROR 

### ISSUE THREAD

**Issue by springjools** [python-telegram-bot/python-telegram-bot#2177]
### Steps to reproduce
1. Have PTB sit idle for maybe 2 days

2. Error is possibly related to temporary client network outage

3.

### Expected behaviour
Tell us what should happen
No  Error or handled error
### Actual behaviour
Tell us what happens instead
Error or not handled error
### Configuration
**Operating System:**
Linux jovian 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
pi@jovian:~ $ python -m telegram
python-telegram-bot 12.4.2
certifi 2019.11.28
future 0.18.2
Python 3.7.7 (default, Apr  1 2020, 10:55:29)  [GCC 9.3.0]
### Logs
Insert logs here (if necessary)
https://pastebin.com/vfuZ3bmp

**Comment by springjools** [comment]
pi@jovian:~ $ python3 -m telegram
python-telegram-bot 12.5.1
certifi 2019.11.28
future 0.18.2
Python 3.8.2 (default, Apr  1 2020, 10:59:39)  [GCC 9.3.0]

**Comment by Bibo-Joshi** [comment]
> Error is possibly related to temporary client network outage

that's what I'd bet. PTB can't really do anything about network failing. Maybe have a look at the wiki page on handling [network errors](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors).

I'll go ahead and close ;)

**Comment by springjools** [comment]
PTB could handle it better . Notice that there's a secondary error in PTB that is triggered by the network problem:

http.client.RemoteDisconnected: Remote end closed connection without response
 
During handling of the above exception, another exception occurred:

**Comment by springjools** [comment]
> 
> 
> > Error is possibly related to temporary client network outage
> 
> that's what I'd bet. PTB can't really do anything about network failing. Maybe have a look at the wiki page on handling [network errors](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors).
> 
> I'll go ahead and close ;)

Please do not close until error is resolved.

**Comment by Poolitzer** [comment]
> PTB could handle it better

How would you like PTB to handle that error?

**Comment by Bibo-Joshi** [comment]
> ### Expected behaviour
> Tell us what should happen
>No Error or handled error

The `uncaught error was raised while handling the error` is clearly due to your code, btw:

```
File "/home/pi/bot/bot.py", line 592, in error
    raise context.error
```

**Comment by springjools** [comment]
Well, I understand that network outage can trigger errors, but I would like to catch **client network** problems and how have the server (PTB) crash because of these. Additionally, the network error causes another error in the add_handler function, somewhere here: https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/dispatcher.py#L588

**Comment by Bibo-Joshi** [comment]
"and how have the server (PTB) crash because of these" = "and **not** have the server (PTB) crash because of these"?

PTB doesn't crash when an error handler raises an exception. the exception is logged (as in your case) and the process keeps running.

Also I can assure you that `Dispatcher.add_error_handler` does not raise network errors. the method is only used to register error handlers, which handle exceptions at runtime.

**Comment by springjools** [comment]
Yes, I use an error handling function in my bot that raises the error so the logger module can catch it:

---
# we raise the error again, so the logger module catches it. If you don't use the logger module, use it.
    raise context.error
---
This module was provided by PTB as some kind of example code. But I can't find it now.


So the uncaught error is me raising the error again?

11-03 15:37 telegram.ext.dispatcher ERROR    An uncaught error was raised while handling the error
Traceback (most recent call last):

**Comment by Poolitzer** [comment]
> So the uncaught error is me raising the error again?

Yes, otherwise it would not be logged. The example you copied from assumed you want all errors to be logged, just also want to do something else with them

**Comment by springjools** [comment]
Ok, thanks for the response. Sorry for my brusque tone earlier, it was because my post was tagged with a monkey :)

**Comment by Poolitzer** [comment]
thats alright, the monkey is for our tags, so we know its not a bug inside the library, rather "something else"
