### ISSUE TITLE
[BUG] Type Hinting of reply_markups

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#2191]
* `stop_poll` allows ReplyKeyboard, but only Inline is accepted. Same for a bunch of other methods
* ~`disable_web_page_preview` is falsely typed as `str`~ that already was fixed …
* `edit_message_reply_markup` should accept `None` for `reply_markup`

**Comment by revolter** [comment]
> Expected type 'MessageEntity', got 'Optional[Message]' instead

when calling `telegram.utils.helpers.effective_message_type(update.effective_message)`.

**Comment by Poolitzer** [comment]
why did you remove this from the milestone?

**Comment by Bibo-Joshi** [comment]
b/c I added #2204 to the milestone, which closes this

**Comment by Poolitzer** [comment]
ah I see

**Comment by revolter** [comment]
But it doesn't look like it would fix my issue. Should I repost it on that PR? Or maybe as a separate issue?

**Comment by Poolitzer** [comment]
As #2204 states, we will gather more fixes there before releasing. If you want to contribute which we always encourage, feel free to make a commit basing on https://github.com/python-telegram-bot/python-telegram-bot/tree/type-hinting and then make a PR against it :)

**Comment by Bibo-Joshi** [comment]
@revolter I just pushed a fix to #2204 ;)

**Comment by mdtouhidur** [comment]
Hello

**Comment by Poolitzer** [comment]
Hi?
