### ISSUE TITLE
Dispatcher.run_async break compatibility?

### ISSUE THREAD

**Issue by 91DarioDev** [python-telegram-bot/python-telegram-bot#2194]
Hello,
To run every update in a different thread I have been using for years these 2 lines of code in the main function 

#define the dispatcher
dp = updater.dispatcher

#this will run async the process_update
dp.process_update = run_async(dp.process_update)

After upgrading to ptb v.13 I tried to replace run_async with Dispatcher.run_async as the documentation states.

But I get the error: 

run_async() missing 1 required positional argument: 'self'

I don't know how to reproduce the same behavior I always had.

**Comment by Bibo-Joshi** [comment]
`Dispatcher.run_async` is not a class method, so you need `dp.run_async` ;)

**Comment by 91DarioDev** [comment]
Then I get this error 

process_update takes 1 position argument but 2 were given

I wrote dp.process_update = dp.run_async(dp.process_update)

**Comment by Bibo-Joshi** [comment]
Oh, I just had a closer look at what you're actually trying to do: Overwriting `process_update` to aways run asynchronously. That seems like a very dirty hack to me. All the handlers have a `run_async` parameter in v13, please use that as it's intended to be. if you're determined to override `Dispatcher.process_update`, you need to override it with a proper function. `dp.run_async(dp.process_update)` tries to run `dp.process_update` immediately. Again, I strongly advise not to do that.

**Comment by 91DarioDev** [comment]
Ok  thank you.
Anyways I used this hack for 3 years, because I think it’s more safe to be sure than you don’t miss any handler and any update is async. 
Another point: adding the run_async to all the handlers isn’t anyways not that performance because you are running async only the callback of the handler, but the dispatcher is still synchronous. Can be the different performance noticeable?

So there is no way to keep using the hack the same way I did for years ? This is why I opened it as a bug thread

**Comment by Bibo-Joshi** [comment]
I don't think that the overhead by `process_update` should be an performance bottle neck. Also, if you run he whole `process_update` function asynchronously, you'll get less precise error handling (unnecessary lines in the traceback and the `update` variable will not be set in the error handler).

> So there is no way to keep using the hack the same way I did for years ?

yes, override it with a proper function, should do the trick, i.e. something along the lines

```python
orig_process_update = dp.process_update

def async_process_update(self, *ars, **kwargs):
    return self.run_async(orig_procss_updare, *args, **kwargs)

dp.process_update = async_process_update
```

for the record and people stumbling upon this: Again, I strongly advise not to do that.

If you want to make sure that all your handlers use `run_async`, you can subclass the handlers that you use and your subclasses set `run_async` to `True` by default.

**Comment by 91DarioDev** [comment]
Ok thank you very much for the detailed comment :)
