### ISSUE TITLE
[FEATURE] Add documentation to ConversationHandler about how it interacts with the dispatcher

### ISSUE THREAD

**Issue by fjfnaranjo** [python-telegram-bot/python-telegram-bot#2200]
#### Is your feature request related to a problem? Please describe.
When inspecting the library code directly, I find difficult to understand how to use the `DispacherHandlerStop` exception to both return a new state and stop the dispatcher. My first naive approach was to just return the new state and I imagined that `ConversationHandler` would raise the exception by itself. After careful observation, I found the note in the exception docs but not around the handler code, when I was looking at first.

#### Describe the solution you'd like
I think a short sentence can be added to the `ConversationHandler` docs to help other library users with same problem. This handler documentation is also exported to the docs in the site and I think this will be a nice place to have it. It will be close to where the other `ConversationHandler` peculiarities are documented.

```To stop the dispatcher when changing the state, raise :class:`telegram.ext.DispatcherHandlerStop` setting a new state in the exception constructor.```

Or another alternative avoiding a semantic dependency:

```Check the :class:`telegram.ext.DispatcherHandlerStop` documentation about how to both set a new state and stop the dispatcher.```

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for reaching out. I added a note in #2201. We'll gather doc fixes in that PR and merge before the next release :)
