### ISSUE TITLE
[QUESTION] Typehinting in Markup should also allow None

### ISSUE THREAD

**Issue by GauthamramRavichandran** [python-telegram-bot/python-telegram-bot#2203]
**Issue I am facing**
In the IDE, it's showing as an error, 
`Expected 'InlineKeyboardMarkup', instead got 'None'`

**Traceback**:
[Screenshot](https://imgur.com/a/PYP17tZ) of the issue

#### Example code
```update.callback_query.edit_message_reply_markup(reply_markup = None)```

**Comment by Poolitzer** [comment]
agreed.

**Comment by Poolitzer** [comment]
see also #2191, they could be done in one PR

**Comment by Bibo-Joshi** [comment]
closing in favor of #2191
