### ISSUE TITLE
[BUG] AttributeError in Job

### ISSUE THREAD

**Issue by GauthamramRavichandran** [python-telegram-bot/python-telegram-bot#2206]
### Steps to reproduce
1.`pip install python-telegram-bot==13.0`
2. Copy this [MWE](https://del.dog/qocrinikil.txt)
3. Place your `BOTTOKEN` and run

### Expected behaviour
Prints the name of the job and its next run time

### Actual behaviour
Throws `AttributeError: 'Job' object has no attribute 'next_t'`

### Configuration
**Operating System:** Ubuntu 18.04

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
```
python-telegram-bot 13.0
certifi 2020.11.08
Python 3.6.9 (default, Oct  8 2020, 12:12:24)  [GCC 8.4.0]
```
**Related**:
Accessing `next_run_time` from APS Job object (`job.job.next_run_time`) also throws an `AttributeError`

**Comment by Bibo-Joshi** [comment]
OP found out that the issue was that `JobQueue` wasn't yet started and the job therefore not yet scheduled. (discussion starts here:  https://t.me/pythontelegrambotgroup/397661)

PTB can't really do anything about that and it's not really unexpected on a closer look.
