### ISSUE TITLE
[BUG] RuntimeError when using run_daily

### ISSUE THREAD

**Issue by nicos68** [python-telegram-bot/python-telegram-bot#2207]
### Steps to reproduce
1. Schedule a job using `run_daily`

### Expected behaviour
The job is executed at the time set.

### Actual behaviour
At the time of execution a `RuntimeError` is raised.

### Configuration
**Operating System: Kubuntu 20.04**

**Version of Python, python-telegram-bot & dependencies: python3.9, python-telegram-bot 13.0**

### Additional Info
The bug does not occur when using python-telegram-bot version 12.8.

I made a minimal project to demonstrate the bug. You can find it [here](https://github.com/nicos68/telegram-scheduling). On the `master` branch the version of python-telegram-bot is 13.0 and the bug _can_ be reproduced. On the branch named `12.8` the version of python-telegram-bot is 12.8 and the bug _cannot_ be reproduced.

### Logs
```logs
2020-11-11 23:48:00,001 - apscheduler.scheduler - ERROR - Error submitting job "daily (trigger: cron[day_of_week='0,1,2,3,4,5,6', hour='22', minute='48', second='0'], next run at: 2020-11-11 22:48:00 UTC)" to executor "default"
Traceback (most recent call last):
  File "/home/nicolas/.cache/pypoetry/virtualenvs/telegram-scheduling-Buskmnwy-py3.9/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 974, in _process_jobs
    executor.submit_job(job, run_times)
  File "/home/nicolas/.cache/pypoetry/virtualenvs/telegram-scheduling-Buskmnwy-py3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/home/nicolas/.cache/pypoetry/virtualenvs/telegram-scheduling-Buskmnwy-py3.9/lib/python3.9/site-packages/apscheduler/executors/pool.py", line 22, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
  File "/home/nicolas/.pyenv/versions/3.9.0/lib/python3.9/concurrent/futures/thread.py", line 163, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```

**Comment by Bibo-Joshi** [comment]
Hi. I can't reproduce the issue with your MWE on the master branch. The error message sounds like you're calling `job_queue.stop()` somewhere in your code. That stops the job queue, so it's not unexpected that you can't schedule jobs afterwards. If you want to stop a _job_, use `job.schedule_removal()`

Please note that since V13, PTB uses the APScheduler library for the JobQueue (see the V13 transition guide in the wiki).

**Comment by nicos68** [comment]
Hi. I pushed a Dockerfile to my repo. I also pushed an image on docker hub:
https://hub.docker.com/r/nicolasslr/telegram-scheduling
If you run it you'll be able to reproduce the issue. Below is an example command to run the image.
`[sudo] docker run -e TG_TOKEN=<your bot token> -w /opt/telegram-scheduling/telegram_scheduling -d telegram-scheduling python main.py`
Just to be sure : 
 * I set my bot to the Paris timezone, so either modify it or set the schedule time accordingly
 * you have to wait for the scheduled time to see the crash.

**Comment by Bibo-Joshi** [comment]
Hey. I see you're putting some effort into this :D
But if the issue is really with PTB, it should be reproducable simply by installing as `pip install python-telegram-bot==13.0` and then running a single file mwe. Can you try to produce something like that? Maybe start with the below snippet and try to find out what you need to modify o see your error:

```python
import logging
import datetime as dtm

import pytz
from telegram.ext import Updater, Defaults

logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


def daily(context):
    chat_id = context.job.context
    context.bot.send_message(
        chat_id=chat_id,
        text="It works !")


def main():
    logger.info("Starting up Bot")

    timezone = pytz.timezone('Europe/Paris')
    defaults = Defaults(tzinfo=timezone)
    updater = Updater('TOKEN', defaults=defaults)

    time = (dtm.datetime.now() + dtm.timedelta(seconds=2)).time()
    updater.job_queue.run_daily(daily, time, context='YOUR_CHAT_ID')

    updater.start_polling()
    updater.idle()
    logger.info('Bot started.')


if __name__ == '__main__':
    main()
```

**Comment by nicos68** [comment]
OK I was missing the `updater.idle()` instruction. I added it and everything's working now. Weird that you couldn't reproduce with my MWE.

Thanks a lot anyway !
