### ISSUE TITLE
[FEATURE] adding run_async in telegram.ext.Defaults

### ISSUE THREAD

**Issue by starry69** [python-telegram-bot/python-telegram-bot#2208]
Since most (if not all) people using PTB use asynchronous callbacks anyway, adding `run_async` parameter in `telegram.ext.Defaults` will be lot helpful for users, it'll also save them lot of time for adding `run_async=True` in each handlers, and ofcourse they can override the default `run_async` value for specific handler if they want to.. so it seems a win win in end!

**Comment by Bibo-Joshi** [comment]
Hey. After short internal discussion, we think this is a great feature.

A note about the implementation: the `Dispatcher` gets a `Bot` as argument anyway, so we can just extract the default setting is `self.bot.defaults.run_async`. Maybe add a (private) property as shortcut that checks if the bot has defaults, or something like that.

@starry69, ofc you're welcome to PR yourself :) If you want to, please leave a note, so we don't do the work twice.

**Comment by starry69** [comment]
Thanks for taking this into consideration! I'll PR soon..

**Comment by starry69** [comment]
Ig i should close this now
