### ISSUE TITLE
"run tests" procedure described in "python-telegram-bot#getting-the-code" does not work

### ISSUE THREAD

**Issue by bluehood** [python-telegram-bot/python-telegram-bot#221]
Just executing 
```
$ git clone https://github.com/python-telegram-bot/python-telegram-bot
$ cd python-telegram-bot
$ pip install -r requirements.txt
$ make test
```
produces several errors. I think they are due to the environment variable TOKEN not being set, but even when it is, it looks like the tests rely on specific chat_id's and assert a specific id for the bot.

What did I not understand?

**Comment by leandrotoledo** [comment]
This commit should have fixed it, please pull last changes and try again.

You also need to install development requirements:

``$ pip install -r requirements-dev.txt``

Thanks.
