### ISSUE TITLE
[BUG] Error with import telegram.ext

### ISSUE THREAD

**Issue by hagemouse** [python-telegram-bot/python-telegram-bot#2213]
I am using python3.8 and pipenv and PyCharm  in ubuntu 20.10. 

When I import telegram.ext and run the program,it shows error:
ModuleNotFoundError: No module named 'telegram.ext'

I tried to install an uninstall python-telegram-bot many times, using:
pip install  python-telegram-bot 
pip3 install  python-telegram-bot 
pipenv  install python-telegram-bot 

Even reinstalled pip, but they all didn't work.

Module telegram works well.

Anybody can help?
Thanks.

**Comment by Bibo-Joshi** [comment]
Sorry, but helping with installation problems is always a bit tricky without knowing your exact setup. Maybe ask in the off-topic group https://t.me/pythontelegrambottalk if someone is willing to help you, but I'll close this as helping with installation problems is a bit out of scope of this bugtracker.
