### ISSUE TITLE
Python-telegram-bot abilities.

### ISSUE THREAD

**Issue by hack3rcon** [python-telegram-bot/python-telegram-bot#2214]
Hello,
I have a question about the abilities of Python-telegram-bot. I have a Telegram group and a list of phone numbers and I want to join all of these numbers to my group. Can I use Python-telegram-bot for this goal?

Thank you.

**Comment by Bibo-Joshi** [comment]
No, bots can't add members to groups in general. Please also see this [FAQ answer](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#can-you-add-feature-to-ptb-can-i-do-thing-with-my-bot).
