### ISSUE TITLE
[FEATURE] Filter by bot_data

### ISSUE THREAD

**Issue by LeggoMahEggo** [python-telegram-bot/python-telegram-bot#2215]
I have a bot that I'm writing that has a 'maintenance mode'; basically, any commands/messages sent while in this mode, other than start and help, return 'server is in maintenance, please try later'. To make this work, I have added code that checks the mode stored in bot_data, for _each_ handler currently present. It would make things much simpler and maintainable if I could use a filter that checks a bot_data entry for a specific value.

**Comment by Bibo-Joshi** [comment]
Hi. What you're basically asking for is to make handlers "state" aware, where "state" here means a *global* condition of your bot. From how I see it, that's not really how handlers are designed to work. But that doesn't mean that you can't do something to make it work for you:

* add the handlers for `/start` and `/help` to group, say -2
* to group -1 add a `TypeHandler(telegram.Update, check_maintenance )`, where `check_maintenance` check `bot_data` for your flag and if your bot is in maitnenance mode, replies with a warning and raises `DispatcherHandlerStop()`
* add all other handlers to groups >=0

That way no handlers other that `/start` and `/help` will be executed when your bot is in maintnance mode *plus* you only have to make that decision once and not for every handler.

**Comment by LeggoMahEggo** [comment]
Whoa, didn't even consider groups! Thanks for the help!  (your wiki and docs are awesome btw)
