### ISSUE TITLE
[QUESTION] 'Job' object has no attribute 'interval'

### ISSUE THREAD

**Issue by AhmadrezaHadi** [python-telegram-bot/python-telegram-bot#2221]
### Issue
I'm using latest version of the module (13.0) and I was trying **callback_increasing** function described in [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-JobQueue) on my editor and I got error below.

you should change **bot token** and **@exampleID** to your own bot token and chat ID in code.

Thanks
### Error
```
AttributeError: 'Job' object has no attribute 'interval'
```

### My code
```python

from telegram.ext import Updater, CallbackContext

updater = Updater(token='bot token', use_context=True)
jobQueue = updater.job_queue

def callback_increasing(context: CallbackContext):
    job = context.job
    context.bot.send_message(chat_id='@exampleID',
                             text='Sending messages with increasing delay up to 10s, then stops.')
    job.interval += 1.0
    if job.interval > 10.0:
        job.schedule_removal()

jobQueue.run_repeating(callback_increasing, 1)

updater.start_polling()
```

**Comment by Bibo-Joshi** [comment]
Hi. As of v13, PTB uses the APScheduler library as backend for the JobQueue and `Job.interval` was removed. You can use `job.job.modify` to change the jobs schedule. See the docs of [APS](https://apscheduler.readthedocs.io/en/stable/modules/job.html#apscheduler.job.Job.modify) for details.
I'll update the wiki soon.

**Comment by AhmadrezaHadi** [comment]
thank you
