### ISSUE TITLE
export_chat_invite_link generates invalid link

### ISSUE THREAD

**Issue by jon4hz** [python-telegram-bot/python-telegram-bot#2224]
Sometimes the bot.export_chat_invite_link method generates "expired or invalid" links while the old link stays valid. According to the documentation this method should revoke every other link.

**Comment by Bibo-Joshi** [comment]
Hi. PTB can only pass the request Telegram. The library can not actually influence what Telegram makes of it. If you have problems with revoking chat invite links, please contact @BotSupport on TG.
