### ISSUE TITLE
Please add proper setup instructions

### ISSUE THREAD

**Issue by ManuelSchneid3r** [python-telegram-bot/python-telegram-bot#2226]
#1963 and #1212 are still an issue.

**Comment by Poolitzer** [comment]
Hey, that is correct, both are issues. Which one are you experiencing? Mind you though that both mentioned issues are actually issues of libraries we depend on, not ones this library creates :)

**Comment by ManuelSchneid3r** [comment]
Oh okayy. Which one? I'll post an issue there

**Comment by Poolitzer** [comment]
I dont know. What issue do you have?

**Comment by ManuelSchneid3r** [comment]
installing cryptography manually using the package manager helped
