### ISSUE TITLE
[QUESTION] How to assign a callback value to ReplyKeyboardMarkup 's buttons, instead of using its text as a callback ?

### ISSUE THREAD

**Issue by vic131** [python-telegram-bot/python-telegram-bot#2234]
The inlinekeyboard 's buttons has a text for the button and a separated calback value :

`InlineKeyboardButton(text='Add family member', callback_data=str(ADDING_MEMBER))`

But for the Replykeyboardmarkup , the text of the button is he callback value :

```
reply_keyboard = [
    ['Age', 'Favourite colour'],
    ['Number of siblings', 'Something else...'],
    ['Done'],
]
markup = ReplyKeyboardMarkup(reply_keyboard, one_time_keyboard=True)

```
I would like, for example, to have the button 'Age', and refers to it as the callback value 'A1'. Is it possible to do it now ? I didnt find anything on the documentation, or elsewhere.

**Comment by Bibo-Joshi** [comment]
Hi. That's not possible with `ReplyKeyboardMarkups`, they are just shortcuts for sending text messages.
