### ISSUE TITLE
Which integer corresponds to which day?

### ISSUE THREAD

**Issue by KappaOnGit** [python-telegram-bot/python-telegram-bot#2236]
I am trying to use `run_daily` to run a task in a particular day of the week and i need to pass a tuple of integers to indicate the days of the week, but how can i know which integer corresponds to which day?

**Comment by Poolitzer** [comment]
[As I said in the group already](https://t.me/pythontelegrambotgroup/407254), days are defined as `MON, TUE, WED, THU, FRI, SAT, SUN = range(7)`, which means Monday is 0 and Sunday 6. We do however need to document this in the run_daily docstring

**Comment by Bibo-Joshi** [comment]
Added to #2225.
