### ISSUE TITLE
[ENHANCEMENT] filename parameter of send_* functions

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#2237]
T[he send_document function has a filename parameter](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.send_document), which sets the file_name for the document to send when the actual document input is a file_like object. Since this is a feature of our library (and sadly not an undocumented one of telegrams API), we can evaluate  which other file sending function would benefit from exposing this parameter.

**Comment by jveer634** [comment]
Can you brief it a bit...

**Comment by Poolitzer** [comment]
Hey, what do you mean with brief?

**Comment by jveer634** [comment]
Like you said could benefit from.. means how do you say we work it on..

**Comment by Bibo-Joshi** [comment]
by adding a `filename` parameter to `send_*` methods that can use it and passing that argument to `parse_file_input` internally

**Comment by Poolitzer** [comment]
this means we need to evaluate which functions end up showing the filename in the end/if telegrams servers store it. Latter could be achieved by checking what other bots receive as a filename for each type of media. First would be to take as many clients as possible and see what they do with the media: Do they or do they not show the filename? E.g. a pictures filename is not shown, an audio ones is.

**Comment by Bibo-Joshi** [comment]
`InputMedia*` should be considered, too.
