### ISSUE TITLE
[ENHANCEMENT] Improve callback signature of shortcuts

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#2238]
We just pass kwargs and args to the underlying function call currently for maintenance easiness. This however means that type hinting/suggestions from IDEs don't live up to their full potential. One of ptb greatest feature are our shortcuts, sparing the developers a lot of time writing out user or chat ids etc. We should spend some time improving this part of our library in my opinion.

If we want to implement this feature, at least testing for it would be a requirement, so whenever we change the underlying functions or add new shortcuts, the test tells us that we have to change the type hints/docs/etc.

**Comment by Bibo-Joshi** [comment]
iirc, `inspect.getfullargspec` also gives type annotation info, that should also be compared.
Also I vote for not documenting the parameters at the shortcuts, as that is probably hard to test, easy to forget and really has no added benifit. We can just link to the corresponding bot methods documentation, if we want to be helpful.
