### ISSUE TITLE
no type hints for Filters.chat_type.private [BUG]

### ISSUE THREAD

**Issue by letmejustputthishere** [python-telegram-bot/python-telegram-bot#2239]
### Steps to reproduce
1. Use the Filter.chat_type.private filter

2. Run mypy on your code

3. Receive `error: "Type[Filters]" has no attribute "chat_type"`

### Expected behaviour
Type hints should be available for this filter.

### Actual behaviour
There is a warning from mypy.

### Configuration
**Operating System:**
macOS 10.13.6

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
python-telegram-bot 13.0
certifi 2020.06.20
Python 3.8.0 (default, Dec 10 2019, 14:57:04)  [Clang 10.0.0 (clang-1000.10.44.4)]
### Logs
Insert logs here (if necessary)

**Comment by Bibo-Joshi** [comment]
`Filters.chat_type` is new in v13.1. Apparently you're using v13.0. So upgrade ;)

**Comment by letmejustputthishere** [comment]
Easier than expected, thanks!
