### ISSUE TITLE
[BUG] Incorrect type hinting for Handlers

### ISSUE THREAD

**Issue by revolter** [python-telegram-bot/python-telegram-bot#2242]
### Steps to reproduce

This line:

https://github.com/python-telegram-bot/python-telegram-bot/blob/73b0e29a308da7ebb35328e5731bee8db0c423be/telegram/ext/commandhandler.py#L94

contradicts with this line:

https://github.com/python-telegram-bot/python-telegram-bot/blob/73b0e29a308da7ebb35328e5731bee8db0c423be/telegram/utils/types.py#L36

And I think that the `update` parameter can actually never be `str`, right?

### Expected behaviour

No mypy issue for

```py
dispatcher.add_handler(telegram.ext.CommandHandler('start', start_command_handler))
```

and

```py
def start_command_handler(update: telegram.Update, context: telegram.ext.CallbackContext) -> None:
```

### Actual behaviour

```
Argument 2 to "CommandHandler" has incompatible type "Callable[[Update, CallbackContext], None]"; expected "Callable[[Union[str, Update], CallbackContext], None]" 
```

### Configuration

**Operating System:**

macOS 10.15.7 (19H15)

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

python-telegram-bot 13.1
certifi 2020.11.08
Python 3.9.0 (default, Nov 21 2020, 14:01:50)  [Clang 12.0.0 (clang-1200.0.32.27)]

### Logs
Insert logs here (if necessary)

**Comment by Bibo-Joshi** [comment]
Hi, thanks for the report.
It's actually a bit tricky: While most handlers will certainly only ever accept `telegram.Update`, `StringCommand/RegexHandler` only except strings and `TypeHandler` accepts everything. So we should probably either change the annotation to `Any` or `Update`. In both cases, people have to silence type checkers at certain lines. with `Update` this will probably be happening less.
@Poolitzer do you have an opinion on this?

**Comment by revolter** [comment]
Well, can't `MessageHandler`, for example, declare a different type than `TypeHandler`?

**Comment by Bibo-Joshi** [comment]
Righ … It can, but we would at least need to silence mypy internall when checking that `Message/TypeHandlers` init signature matches the one of `telegram.Handler`. And dropping `typing.HandlerArg` in favor of `Any` would probably be favorable to handle stuff like `TypeHandler`. I'll try look into it.

**Comment by revolter** [comment]
I think that `Any` wouldn't be better. Because then, we would need to use `isinstance(update, telegram.Update)` in every handler function.

**Comment by Bibo-Joshi** [comment]
No I mean in the handlers annotate the callback function as what acutally is expected (i.e. `tg.Update` for `MessageHandler` and `str` for `StringCommandHandler`), but e.g. in `Dispatcher.process_update` annotate the `update` as `Any` instead of `HandlerArg`, b/c in fact anything can be put in the `update_queue`

**Comment by revolter** [comment]
I see. Then yes, it sounds like the best idea.
