### ISSUE TITLE
[QUESTION] Inline Buttons with native comments

### ISSUE THREAD

**Issue by Sirozha1337** [python-telegram-bot/python-telegram-bot#2248]
I'm using this library to add "like/dislike" buttons to my posts and I want to add the new native comments functionality to my channel. Currently posts with buttons don't have the native comment button.

My question or rather questions are:
1.  Is there a way for them to work together? Maybe some option that I'm missing?
2.  Can I replicate the native comment button functionality with another inline button? If so, please give me a hint on how to do that?

**Comment by Bibo-Joshi** [comment]
Hi.

> 1. Is there a way for them to work together? Maybe some option that I'm missing?

Not that I know of, but that's rather a question for TG support/@BotSupport. Mind you, Bot API currently offers no convenience methods for these comments at all.

> 2. Can I replicate the native comment button functionality with another inline button? If so, please give me a hint on how to do that?

What comes closest to those comments is replying to the forwarded channel post in the discussion group. Then you can still view all those replies in the "replies" view of the post. But I don't think there is a way to switch to the discussion group via an inline button __and__ force a reply to a specific message.

What you could try is direct the user to the bot via deep-linking and put the message_id of the channel post as deep-linking parameter. Have the user send their comment to the bot and have the bot post it as reply to the channel post in the discussion group. That's a bit tiresome for the user, though, and it has the downside that the user is not acutally the author of the reply in the discussion group.

**Comment by Sirozha1337** [comment]
@Bibo-Joshi thank you for a quick response. 

I've asked botsupport about it, but they weren't much help. So, I guess it's either don't use buttons or make a workaround that works differently from their comment button.

Interesting solution, I'll think about doing it this way. Thanks for the idea!

**Comment by Poolitzer** [comment]
> or make a workaround that works differently from their comment button

Hm, another solution I can think of is adding an URL inline button which has the text "comment" and then link to the specific message in the discussion group, it being the post of the channel. If a user is in the discussion group or the discussion group is public, that link will always work for them. They are not forced to reply to the message (hence generating a comment), but its pretty close to it and I think a lot of users will do that.
