### ISSUE TITLE
List Args first in docs

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2251]
I often find it somewhat unintuitive that I need to scroll quite long before finding the parameter list.
Ofc for the TG-Objects, parameters are a bit less important than attributes b/c you usually don't instantiate them manually, but the parameters are rendered more compactly than the attributes and attributes & parameters mostly coincide anyway, so for a quick glance it doesn't make a big difference.

I suggest to go over the different classes and rearrange the docstring as

1. General description
2. Notes, Examples & Warnings (if applicable)
3. Args
4. Attributes

**Comment by Poolitzer** [comment]
can you give an example of a specific class where this is really bad and rearranging would improve this?

**Comment by Poolitzer** [comment]
okay, what about doing an even crazier change, and do

1. Args
2. General description
3. Notes, Examples & Warnings (if applicable)
4. Attributes

<p float="left">
  <img src="https://user-images.githubusercontent.com/25934244/102488850-f66e4700-406c-11eb-90ac-c2b083a158a1.PNG" width="400" />
  <img src="https://user-images.githubusercontent.com/25934244/102488857-f8d0a100-406c-11eb-8113-5b4479c9316b.png" width="400" /> 
</p>

left is your suggestion, right is mine

**Comment by Bibo-Joshi** [comment]
Mh, tbh I'd vote for left. Having the description before the detailed list of arguments seems more sane to me. BTW, that's also how the python docs do it, (e.g. [here](https://docs.python.org/3/library/datetime.html#date-objects))

**Comment by Poolitzer** [comment]
and you would leave the notes between the description and the args?

**Comment by Bibo-Joshi** [comment]
Yes, as I see them as emphasized parts of the description. like TG puts the "you must provide exactly one of the optionals" above the arg list.

**Comment by Poolitzer** [comment]
alright
