### ISSUE TITLE
 Is it possible to send schedule messages?

### ISSUE THREAD

**Issue by orlovich** [python-telegram-bot/python-telegram-bot#2255]
Hello! Please tell me if this API has an implementation of this parameter http://prntscr.com/w58sgh in the sendMessage Telegram API method? And if so, where can the value of this parameter be written?

**Comment by Bibo-Joshi** [comment]
That screenshot is of the MTProto docs. This library is concerned with the Bot API ;)

**Comment by Poolitzer** [comment]
That being said, if you want to schedule a message, I would suggest checking out our job module: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-JobQueue

**Comment by orlovich** [comment]
Thank's!
