### ISSUE TITLE
[FEATURE] APScheduler should be optional dependency

### ISSUE THREAD

**Issue by mik-laj** [python-telegram-bot/python-telegram-bot#2257]
#### Is your feature request related to a problem? Please describe.
I want to do this library without apscheduler installation, but there is no way to do it.*

#### Describe the solution you'd like
I think it would be nice if you would move APScheduler to a new extra so it will allow us to install this library without installing APScheduler
More information:
https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html?highlight=extras_require#optional-dependencies
Example: 
https://github.com/googleapis/python-bigquery/blob/master/setup.py

#### Describe alternatives you've considered
N/A

#### Additional context
I am the commissioner of the Apache Airflow project and started to review the libraries that are required by this project.
https://github.com/apache/airflow/issues/12120
 I noticed a dependence there that I did not expect - APScheduler.  Apache Airflow has a similar use case, so this library is not expected to be installed when installing Airflow.
After looking at the code, it seems to me that we never use this library, so we don't need to install it.
https://github.com/apache/airflow/tree/master/airflow/providers/telegram

**Comment by Poolitzer** [comment]
Hey. We use APScheduler as a library to provide our job queue, which tightly integrates with the rest of our library and provides users an easy way to schedule tasks within their bots context.

If we were to make APScheduler optional, we would need to provide a seperate installation of our library, as well as rewrite every entry point and internal structures to not start when that installation happens and then display a clear error message to users why they cant access the job queue.

I do not think any current maintainer is willing to provide this effort to apply to your rather specific use case. If you want to though, we could discuss if we are willing to allow this fracture.

**Comment by mik-laj** [comment]
I have looked at this library and it seems it makes more sense to write one function on our side to send messages and drop this library altogether. 
https://github.com/apache/airflow/blob/49f104b894a11be764172afa932076bb0f85408c/airflow/providers/telegram/hooks/telegram.py#L151
```python
        response = self.connection.send_message(**kwargs)
```
It seems like a better solution because this way we will delete a few additional libraries at the cost of writing one function.

**Comment by mik-laj** [comment]
This would be ideal as I could still use the Telegram API without installing unnecessary libraries. 

Should I reopen this ticket?
