### ISSUE TITLE
Use of Caps for import statements in the replykeyboardmarkup line 23 causes app hosted on Heroku to crash

### ISSUE THREAD

**Issue by Mgregchi** [python-telegram-bot/python-telegram-bot#2261]
Hello, Good morning from here.

I would really appreciate help here. I attached log file from Heroku for better view.

Here's a copy of Heroku log file 🔢 
[p1-wormbot-console-1608604717079.txt](https://github.com/python-telegram-bot/python-telegram-bot/files/5729197/p1-wormbot-console-1608604717079.txt)

`Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/app/.heroku/python/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/app.py", line 4, in <module>
    from telegram.replykeyboardmarkup import ReplyKeyboardMarkup
  File "/app/.heroku/python/lib/python3.6/site-packages/telegram/replykeyboardmarkup.py", line 23, in <module>
    from telegram import KeyboardButton, ReplyMarkup
ImportError: cannot import name 'KeyboardButton'
`

App works well on local machine using NGROK for connection.
But crashes when hosted on Heroku.

I opened the "replykeyboardmarkup" file in 23 You can see the use of Caps for import statements, whereas, the
"keyboardbutton and replymarkup" are named with lower case respectively.
Yes, it works on local machine but it seems Heroku is case sensitive. 

I believe it is a typo from the Telegram Dev side.
Obviously machines are case sensitive.

The above is my observations. Meanwhile I would appreciate a work-around or a clearifications if I am getting it all wrong.

Thanks for Your help.

**Comment by Bibo-Joshi** [comment]
Hi. I'm sure that's not an issue of PTB. If it was, the tests would fail. More precisely, the line

https://github.com/python-telegram-bot/python-telegram-bot/blob/80b34811ab7cfb633d703f88d2a06df6e71d3551/telegram/replykeyboardmarkup.py#L23

works fine because in `telegram/__init__.py`, both `KeyboardButton` and `ReplyMarkup` are imported before `ReplyKeyboardMarkup`:

https://github.com/python-telegram-bot/python-telegram-bot/blob/80b34811ab7cfb633d703f88d2a06df6e71d3551/telegram/__init__.py#L43-L47

Please double check that PTB is installed correctly on Heroku.

**Comment by Mgregchi** [comment]
Thanks for quick response

I checked installation and build logs, even deleted the Heroku app and started all over again.

I Decided to include all the build logs from start to finish

Crashed:
`heroku logs --tail`

`2020-12-22T11:01:50.036925+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/replykeyboardmarkup.py", line 23, in <module>
2020-12-22T11:01:50.036926+00:00 app[web.1]:     from telegram import KeyboardButton, ReplyMarkup
2020-12-22T11:01:50.036926+00:00 app[web.1]: ImportError: cannot import name 'KeyboardButton' from 'telegram' (/app/.heroku/python/lib/python3.7/site-packages/telegram/__init__.py)`

From console when run manually:
`python -m app.py`

`Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/app/.heroku/python/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/app.py", line 4, in <module>
    from telegram.replykeyboardmarkup import ReplyKeyboardMarkup
  File "/app/.heroku/python/lib/python3.7/site-packages/telegram/replykeyboardmarkup.py", line 23, in <module>
    from telegram import KeyboardButton, ReplyMarkup
ImportError: cannot import name 'KeyboardButton' from 'telegram' (/app/.heroku/python/lib/python3.7/site-packages/telegram/__init__.py)
`

BUILD LOG:
Using heroku CLI commands

`-----> Installing python-3.7.6
-----> Installing pip 20.1.1, setuptools 47.1.1 and wheel 0.34.2
-----> Installing SQLite3
-----> Installing requirements with pip
       Collecting APScheduler==3.6.3
         Downloading APScheduler-3.6.3-py2.py3-none-any.whl (58 kB)
       Collecting certifi==2020.12.5
         Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
       Collecting cffi==1.14.4
         Downloading cffi-1.14.4-cp37-cp37m-manylinux1_x86_64.whl (402 kB)
       Collecting chardet==3.0.4
         Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
       Collecting click==7.1.2
         Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
       Collecting cryptography==3.3.1
         Downloading cryptography-3.3.1-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)
       Collecting decorator==4.4.2
         Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
       Collecting Flask==1.1.2
         Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
       Collecting gunicorn==20.0.4
         Downloading gunicorn-20.0.4-py2.py3-none-any.whl (77 kB)
       Collecting idna==2.10
         Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
       Collecting itsdangerous==1.1.0
         Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
       Collecting Jinja2==2.11.2
         Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
       Collecting MarkupSafe==1.1.1
         Downloading MarkupSafe-1.1.1-cp37-cp37m-manylinux1_x86_64.whl (27 kB)
       Collecting pycparser==2.20
         Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
       Collecting python-telegram-bot==13.1
         Downloading python_telegram_bot-13.1-py3-none-any.whl (422 kB)
       Collecting pytz==2020.4
         Downloading pytz-2020.4-py2.py3-none-any.whl (509 kB)
       Collecting pywildcard==1.0.10
         Downloading pywildcard-1.0.10.tar.gz (3.6 kB)
       Collecting requests==2.24.0
         Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
       Collecting six==1.15.0
         Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
       Collecting telegram==0.0.1
         Downloading telegram-0.0.1.tar.gz (879 bytes)
       Collecting tornado==6.1
         Downloading tornado-6.1-cp37-cp37m-manylinux2010_x86_64.whl (428 kB)
       Collecting tzlocal==2.1
         Downloading tzlocal-2.1-py2.py3-none-any.whl (16 kB)
       Collecting urllib3==1.25.11
         Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
       Collecting Werkzeug==1.0.1
         Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
       Building wheels for collected packages: pywildcard, telegram
         Building wheel for pywildcard (setup.py): started
         Building wheel for pywildcard (setup.py): finished with status 'done'
         Created wheel for pywildcard: filename=pywildcard-1.0.10-py3-none-any.whl size=3300 sha256=7719fbb9d25971acf95e29460c21a164767a3a053ce24a80cf73b82b744ced53
         Stored in directory: /tmp/pip-ephem-wheel-cache-3wzfdfi2/wheels/ba/67/ea/e2579bfbbe84b523728485c49676d7bd4fccee08a90e44ca8d
         Building wheel for telegram (setup.py): started
         Building wheel for telegram (setup.py): finished with status 'done'
         Created wheel for telegram: filename=telegram-0.0.1-py3-none-any.whl size=1306 sha256=a525e10af3abaf8225b16b0d386283ab93da3d64f3c69899ce5dd13a071f42d2
         Stored in directory: /tmp/pip-ephem-wheel-cache-3wzfdfi2/wheels/d9/9a/18/0fb06b374524281ac7c9f380a8405c361ace966c1e6a556ca6
       Successfully built pywildcard telegram
       Installing collected packages: six, pytz, tzlocal, APScheduler, certifi, pycparser, cffi, chardet, click, cryptography, decorator, MarkupSafe, Jinja2, Werkzeug, itsdangerous, Flask, gunicorn, idna, tornado, python-telegram-bot, pywildcard, urllib3, requests, telegram
       Successfully installed APScheduler-3.6.3 Flask-1.1.2 Jinja2-2.11.2 MarkupSafe-1.1.1 Werkzeug-1.0.1 certifi-2020.12.5 cffi-1.14.4 chardet-3.0.4 click-7.1.2 cryptography-3.3.1 decorator-4.4.2 gunicorn-20.0.4 idna-2.10 itsdangerous-1.1.0 pycparser-2.20 python-telegram-bot-13.1 pytz-2020.4 pywildcard-1.0.10 requests-2.24.0 six-1.15.0 telegram-0.0.1 tornado-6.1 tzlocal-2.1 urllib3-1.25.11
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 69.1M
-----> Launching...
       Released v6
       https://tele-avatar-bot.herokuapp.com/ deployed to Heroku`

**Comment by Bibo-Joshi** [comment]
In the logs I see

```
Successfully installed ... telegram-0.0.1 ...
```

Conflicting name spaces are likely the problem. Try uninstalling `telegram`

**Comment by Mgregchi** [comment]
Yeah me again
Thanks so much for your help, I really do appreciate @Bibo-Joshi 

I have solved the issue. Just copied the telegram folder to project root and deleted the dist-info folder. Also removed it from requirements.txt file.
That prevented Heroku from installing additional telegram package. I guess it uses the one i copied as top-level module(?)

HERES THE APP  https://tele-avatar-bot.herokuapp.com/
THE BOT CAN BE FOUND HERE : https://t.me/Worm_mark1_bot

THANKS SO MUCH
