### ISSUE TITLE
[BUG] Files which got from local api server have weird `file_path`

### ISSUE THREAD

**Issue by DahaWong** [python-telegram-bot/python-telegram-bot#2263]
I'm using a local bot api running with `--local`, the server runs and hosts the files successfully, but I cannot download it by its `file_path`, as is said [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Local-Bot-API-Server#working-with-files).

### Steps to reproduce
1. Use self-host bot api, with `--local`.

2. Get any file via `telegram.Bot.get_file(file_id)` from telegram server. (Sent by user in my case.)

3. Check the file's `file_path`

### Expected behaviour
`file_path` value should look like `/home/<server-username>/<bot-token>/documents/<file_name>`, and the file can be 'downloaded' by it.

### Actual behaviour
... but got `https://api.telegram.org/file/bot<bot-token>//home/<server-username>/<bot-token>/documents/<file_name>`, which causes `File.download()` fail with an error `InvalidToken()`.(maybe)

### Configuration
**Operating System:**
macOS version 11.0.1

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 13.1
certifi 2020.12.05
Python 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23)  [Clang 6.0 (clang-600.0.57)]

### Logs
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
    handler.handle_update(update, self, check, context)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telegram/ext/handler.py", line 156, in handle_update
    return self.callback(update, context)
  File "/Users/<username>/Documents/Development/<botname>/callbacks/message.py", line 160, in parse_doc
    doc_file.download()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telegram/files/file.py", line 161, in download
    buf = self.bot.request.retrieve(url, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telegram/utils/request.py", line 373, in retrieve
    return self._request_wrapper('GET', url, **urlopen_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telegram/utils/request.py", line 274, in _request_wrapper
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token
```

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for the report.

Apparently, on macOS, the guessing, if the file is local or not, seems to fail in `Bot.get_file`. Can you please define a function `get_file` as follows:

```python
    from telegram.utils.helpers import is_local_file

    def get_file(bot, file_id, timeout = Non, api_kwargs = None):
        try:
            file_id = file_id.file_id
        except AttributeError:
            pass

        data = {'file_id': file_id}

        result = bot._post('getFile', data, timeout=timeout, api_kwargs=api_kwargs)

        # Here we check the file path returned by TG
        print(result.get('file_path'))
        # Here we check if PTB correctly guesses if the file path is a local file
        print(is_local_file(result.get('file_path')))

        if result.get('file_path') and not is_local_file(
            result['file_path']
        ):
            result['file_path'] = '{}/{}'.format(
                bot.base_file_url, result['file_path']
            )

        return File.de_json(result, self)
```

Then call `get_file(bot, file_id)` report what's being printed? And if the first print shows the correct file local file path, but the second print gives `False`, please also check what

```python
pathlib.Path(<the correct local file path>).is_local()
```

gives.

**Comment by DahaWong** [comment]
Sorry, I might misunderstood the concept of `--local` label, I ran my bot on local macOS, but the api server is on a VPS.
