### ISSUE TITLE
document exception handling

### ISSUE THREAD

**Issue by rahiel** [python-telegram-bot/python-telegram-bot#227]
We should explain which `TelegramError`'s there are and how to handle them.

**Comment by leandrotoledo** [comment]
These pops up when I search for TelegramError:

- [ ] Unauthorized(TelegramError) on `error.py`
- [ ] InvalidToken(TelegramError) on `error.py`
- [ ] NetworkError(TelegramError) on `error.py`
- [ ] TelegramError('Could not parse file content') on `inputfile.py`
- [ ] TelegramError(msg) on `ext/dispatcher.py`
- [ ] TelegramError(str(error)) on `ext/updater.py`
- [ ] TelegramError('SSL Certificate invalid') on `ext/updater.py`
- [ ] TelegramError('Invalid server response') on `utils/request.py`

**Comment by jh0ker** [comment]
I put up a wiki page, feel free to improve :)
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Exception-Handling

**Comment by leandrotoledo** [comment]
- [ ] BadRequest(NetworkError) on 1e398821a013d89e9b1bd1afec41dae7c7dc9d96 and e70625772c49e93ed187372f57f224f6bf798c96

It inherits NetworkError to keep backwards compatibility, should handle errors like:
```
>>> bot.leaveChat(<invalid chat>)
...
telegram.error.BadRequest: Chat not found

>>> bot.answerCallbackQuery(<invalid query idt>)
...
telegram.error.BadRequest: Query_id_invalid

>>> bot.getFile(<invalid file id>)
...
telegram.error.BadRequest: Invalid file id

etc

**Comment by jh0ker** [comment]
@leandrotoledo I updated the wiki page (see above) with `BadRequest` and added some more details on how error handlers work. The wiki page is pretty complete now, if it isn't linked in the README already, I'd like to have it there now.

**Comment by leandrotoledo** [comment]
@jh0ker nice work!

**Comment by rahiel** [comment]
This has been solved by @jh0ker at the [wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Exception-Handling).
