### ISSUE TITLE
[FEATURE] PyCharm keep reporting telegram's __init__.py

### ISSUE THREAD

**Issue by lonyphus** [python-telegram-bot/python-telegram-bot#2270]
So I did it.

```
from .base import Base
from .bot import Bot
from .botcommand import Botcommand
from .callbackquery import Callbackquery
from .chat import Chat
from .chataction import Chataction
from .chatlocation import Chatlocation
from .chatmember import Chatmember
from .chatpermissions import Chatpermissions
from .choseninlineresult import Choseninlineresult
from .constants import Constants
from .dice import Dice
from .error import Error
from .forcereply import Forcereply
from .keyboardbutton import Keyboardbutton
from .keyboardbuttonpolltype import Keyboardbuttonpolltype
from .loginurl import Loginurl
from .message import Message
from .messageentity import Messageentity
from .messageid import Messageid
from .parsemode import Parsemode
from .poll import Poll
from .proximityalerttriggered import Proximityalerttriggered
from .replykeyboardmarkup import Replykeyboardmarkup
from .replykeyboardremove import Replykeyboardremove
from .replymarkup import Replymarkup
from .update import Update
from .user import User
from .userprofilephotos import Userprofilephotos
from .version import Version
from .webhookinfo import Webhookinfo
```

**Comment by Poolitzer** [comment]
hello, thanks for your report. You didn't really tell us though what PyCharm is reporting and what the fix for that would be?

**Comment by lonyphus** [comment]
Hi, thank you so much for responding me.

```python
import telegram
bot = telegram.Bot(token="token")
```

PyCharm keeps telling me ***Cannot find reference 'Bot' in '__init__.py'***

**Comment by Poolitzer** [comment]
can you go to File, settings, then project: on your left side and check in the python interpreter section if telegram is there, probably with version 0.0.1? if yes uninstall it and probably reinstall this library.

alternatively, do you have a folder or file named telegram in your project?

**Comment by lonyphus** [comment]
Yes it's 0.0.1 version. I did uninstall and reinstall, and it is still 0.0.1 version.
I try update it but it's still in vain.
I use pipenv for this project, and I make sure there's no other named telegram's thing.

**Comment by Poolitzer** [comment]
Ha, no, you need to remove the telegram package, and instead install python-telegram-bot :)
