### ISSUE TITLE
How to start a conversation With InlineKeyboardButton?

### ISSUE THREAD

**Issue by akhodagholi** [python-telegram-bot/python-telegram-bot#2275]
I have a InlineKeyboardButton and I want when user click on the one of the buttons, bot start a conversation and ask a question and then user answer with message.

**for example:**
1. user click on the InlineKeyboardButton
2. bot send message "what is your name?"
3. bot wait for answer a question
4. user send "Alex"
5. finally bot end conversation
6. 
I know how to create a InlineKeyboardButton and ConversationHandler my question is how to create InlineKeyboardButton and Conversation togther and interact with each other?

**Comment by Bibo-Joshi** [comment]
Use a CallbackQueryHandler as entry point. Iirc in the `nestedconversationbot.py` uses something like that.
