### ISSUE TITLE
[ENHANCEMENT] Inconsistencies in docstrings for deprecated attributes

### ISSUE THREAD

**Issue by zakaryan2004** [python-telegram-bot/python-telegram-bot#2305]
### Expected behaviour
The docstrings should tell if something is deprecated in all places.

### Actual behaviour
In some parts of the docstrings, the deprecation status isn't properly mentioned.

### Examples
1. https://github.com/python-telegram-bot/python-telegram-bot/blob/ffd675daecc40e49280e274e1f8548955beee0ef/telegram/ext/messagehandler.py#L117
2. https://github.com/python-telegram-bot/python-telegram-bot/blob/ffd675daecc40e49280e274e1f8548955beee0ef/telegram/ext/commandhandler.py#L119

**Comment by Bibo-Joshi** [comment]
Hi. I guess the confusion is between __arguments__ and __attributes__. In both of the cases you mention, the corresponding __arguments__ state that they are depricated. The arg-docstrings are always a bit more elaborate b/c they are the reference for what to pass in which case. the attribute docstrings simply list, which attributes are available.

**Comment by Poolitzer** [comment]
I do think that mentioning that the argument is depreciated in the argument docstring makes sense.

**Comment by Bibo-Joshi** [comment]
True. Though I'd like to point out that most of that will be dropped in the next major release anyway, so putting effort in documenting it might be futile :D

**Comment by Bibo-Joshi** [comment]
Clarification @zakaryan2004: I cerntainly don't want to stop from from PRing, if you'd like to! Just wanted to be honest about how long-lasting that PR would probably be ;)

BTW, if you want to PR, I think it would be good to adopt the `.. deprecated:: 12.x` [directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-deprecated), we recently started to use :)

**Comment by Bibo-Joshi** [comment]
Closing, as there is no urgent todo item here. Still, a PR (based on the `doc-fixes` branch) will of course be appreciated.
