### ISSUE TITLE
Contact user by id

### ISSUE THREAD

**Issue by paulthemagno** [python-telegram-bot/python-telegram-bot#2306]
My Telegram Bot logs into a channel the actions of each user. I have added a link to contact them **even if they don't have a username**. I have found this solution:
```python
from telegram import ParseMode
from telegram.utils.helpers import escape_markdown
...
message=f"• *Name*: [{escape_markdown(self.first_name)} {escape_markdown(self.last_name)}](tg://user?id={self.id})"
bot.send_message(chat_id=self.log_channel_chat_id, text=message, parse_mode=ParseMode.MARKDOWN)
```

With all the users with username the link `tg://user?id={self.id}` works. With a user without username not.
I tried also to remove my personal username and with my user it works properly. Why with some users without usernames, doesn't it work? It could be for privacy settings?

I'm asking this also because that link has to work precisely with users without username, otherwise I could use username directly (t.me/...)

**Comment by Poolitzer** [comment]
> It could be for privacy settings?

That is true. It is based on Forwarded messages privacy. If its enabled for the bot, this mention will not work outside of the users PM and groups with said users.

**Comment by paulthemagno** [comment]
@Poolitzer so is it something I can change on my bot settings? Or it depends on the settings of each user?

**Comment by Poolitzer** [comment]
No, each user.

**Comment by Poolitzer** [comment]
I'm gonna close this as answered
