### ISSUE TITLE
[QUESTION] Send VideoNote

### ISSUE THREAD

**Issue by soerenetler** [python-telegram-bot/python-telegram-bot#2309]
I want to send a VideoNote similar to reply_message or reply_contact.

From the telegram bot documentation this should be possible. I couldn't find anything in the documentation of the python telegram bot. Did I miss anything?

https://telegrambots.github.io/book/2/send-msg/video-video_note-msg.html#video-note

I would be happy to support implementing this feature.

Thank you in advance,
Sören

**Comment by Bibo-Joshi** [comment]
PTBs `Message` class does have an instance method [`Message.reply_video_note`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html?highlight=reply_video_note#telegram.Message.reply_video_note). So `update.(effective_)message.reply_video_note(…)` will do. But I don't quite understand, what that .NET API wrapper you linked has to do with PTB :D

**Comment by soerenetler** [comment]
Ohh, thanks. That was exactly what I needed.
I just linked the .Net API wrapper to show that it should be possible to send Video Notes.
Thanks a lot for your help :)

**Comment by Bibo-Joshi** [comment]
Haha, all right. The official [TG API docs](https://core.telegram.org/bots/api#sendvideonote) might have been less confusing ;P
