### ISSUE TITLE
[QUESTION] How to rate limit?

### ISSUE THREAD

**Issue by skhaz** [python-telegram-bot/python-telegram-bot#2317]
Is there an easy way to rate limit the usage of some specific command to avoid flood?

**Comment by skhaz** [comment]
@Bibo-Joshi and what about this? https://github.com/python-telegram-bot/rules-bot/blob/25f35c0344/util.py#L74

**Comment by Bibo-Joshi** [comment]
Sure, that also works. The approach I linked is probably more appropriate, if you want to rate limit users independently of which update they sent.

**Comment by skhaz** [comment]
Ok. Thank you @Bibo-Joshi!
