### ISSUE TITLE
[FEATURE] Shortcuts for Message

### ISSUE THREAD

**Issue by zeshuaro** [python-telegram-bot/python-telegram-bot#2322]
#### Is your feature request related to a problem? Please describe.
My most wanted shortcut is `Message.reply_chat_action`, but going through the list, think we can also add `Message.reply_{game, invoice}`. 

#### Describe the solution you'd like
Update `Message` with the new shortcuts.

#### Describe alternatives you've considered
N/A

#### Additional context
N/A

Happy to make a PR if you think this is suitable.

**Comment by Poolitzer** [comment]
> Happy to make a PR if you think this is suitable.

we absolutely do, feel free to give it a shot
