### ISSUE TITLE
[QUESTION] Unit tests support?

### ISSUE THREAD

**Issue by ingroxd** [python-telegram-bot/python-telegram-bot#2327]
### Issue I am facing
Hi everyone [:
I am not sure how I should test (with a proper test unit) a bot function that uses internet.
Does PTB provide some kind of mock utilities?
If not, is it something that is worth to include?

**TL;DR**
I am trying to create a test case for one of my functions using `unittest`.

I will try to make this issue code-agnostic.
Take this scenario: you send a command (say `/help` for example) and the bot reply to you with an help message.

I already managed to create an offline pair of `update` and `context` data that simulate a command sent by a user (in particular, myself), but I am not sure on what kind of assert I should do in this case.

I was wondering if PTB offers some piece of code I can use to have a copy of data received or sent by the bot and/or if there is some function I could use to mock data (in and/or out).

Thank you for your time [:

### Traceback to the issue
```
N/A
```

### Related part of your code
In the `function.help` module we have the following code:
```python
from telegram import Update
from telegram.ext import CallbackContext

def function(update: Update, context: CallbackContext):
    user = update.effective_user
    text = "help_message"
    context.bot.send_message(user.id, text=text)
```

For interested readers, this is the actual piece of code that create the simplest test case calling the function.
I omitted actual data that goes in costructors.
```python
import unittest

from telegram import Message
from telegram import Update
from telegram import User
from telegram.ext import CallbackContext
from telegram.ext import Updater

from function import help

update_id_sample = 123456789
user_sample = User()
message_sample = Message()
update_sample = Update(
    update_id=update_id_sample,
    message=message_sample
)
updater_sample = Updater()
context_sample = CallbackContext(updater_sample.dispatcher)


class TestFunctionHelp(unittest.TestCase):
    def test_function_help(self):
        help.function(update=update_sample, context=context_sample)
        # I am not sure of the assert I should use, or if PTB as some utility I can use.
```

**Comment by starry69** [comment]
Well PTB itself don't provide mock utilities, but all `Bot` methods are mockable. You can also check out https://github.com/python-telegram-bot/python-telegram-bot/wiki/Writing-Tests

**Comment by ingroxd** [comment]
Yes, I actually saw that page right after this issue.
I also read [this page](https://telegrambots.github.io/book/3/tests.html) that is still valid if you take those advice like code-agnostic.

By now, I already changed the test unit for my function, but I still have to build a userbot to automate the process.
In my test case (which is still a draft) is missing the automation through a userbot and a forcing-failure system.

It is not very clear, nor good looking, but it's something.
If I think that these are my first test units I consider myself satisfied.

Hoping this can help someone, I leave a piece of code that reseamble the draft I have now:
```python
# -*- coding: utf-8 -*-
import time
import unittest

from telegram import Message
from telegram import Update
from telegram import User
from telegram.ext import CallbackContext
from telegram.ext import Filters
from telegram.ext import MessageHandler

from src.mybot import setup_mybot_updater
import function

tester_id = 1234566789
tester_language_code = "en"

done = False


def reply_watchdog(update: Update, context: CallbackContext):
    global done
    if update.message.text.lower() == "true":
        done = True


class TestFunctionsSimple(unittest.TestCase):
    @classmethod
    def setUpClass(self):
        # If it quacks it's a duck
        self.update = Update(
            update_id=123456789,
            message=Message(
                message_id=1234,
                date=0,
                chat=None,
                text="test",
                from_user=User(
                    id=tester_id,
                    first_name="Tester",
                    is_bot=False,
                    username="Tester",
                    language_code=tester_language_code
                )
            )
        )
        self.updater = setup_mybot_updater()
        self.context = CallbackContext(self.updater.dispatcher)
        function.setup(self.updater)
        self.updater.dispatcher.add_handler(
            MessageHandler(Filters.text, reply_watchdog)
        )
        self.timeout = 0
        self.timer_shard = 10
        self.timer = 0
        self.updater.start_polling()

    def timer_set(self, seconds: int):
        self.timeout = seconds
        self.timer = self.timeout * self.timer_shard

    def timer_tick(self):
        time.sleep(1 / self.timer_shard)
        self.timer -= 1

    def send_question(self):
        self.updater.bot.send_message(
            chat_id=tester_id,
            text="Please confirm if test works sending 'true' or 'false'"
        )

    def setUp(self):
        global done
        done = False

    def test_function_help(self):
        self.timer_set(15)
        self.send_question()
        # needs manual confirmation
        self.update.message.text = "/help"
        function.help.function(update=self.update, context=self.context)
        while self.timer > 0 and not done:
            self.timer_tick()
        self.assertTrue(done)

    @classmethod
    def tearDownClass(self):
        self.updater.stop()


if __name__ == "__main__":
    unittest.main()
```
