### ISSUE TITLE
[QUESTION]How to perform read processing for an update_id?

### ISSUE THREAD

**Issue by njch1985** [python-telegram-bot/python-telegram-bot#2334]
How to perform read processing for an update_id? When one update is reached, the update_id will not appear again
Thank you very muc!!!

**Comment by starry69** [comment]
What do you mean by `read processing` of an `update_id` can you elaborate?

**Comment by njch1985** [comment]
How can the message update_id obtained by get_updates() not be displayed after the next get_updates()?

**Comment by njch1985** [comment]
Use get_updates() to get the new message update_id
How to no longer display the last obtained message in the next get_updates()

**Comment by njch1985** [comment]
thank you
