### ISSUE TITLE
Problems with sending media group

### ISSUE THREAD

**Issue by GushchinaVarya** [python-telegram-bot/python-telegram-bot#2337]
Is it possible to send local photos as a media group? For example I have 2 photos 'photo1.png', 'photo2.png' which are located in the bot working directory. I need to send it together. I tried 

```python
bot.send_media_group(
     chat_id=chat_id,
     media=[InputMediaPhoto('attach://Users/myuser/Documents/mybot/photo1.png'),
                   InputMediaPhoto('attach://Users/myuser/Documents/mybot/photo2.png')]
        )
```

but it didn't help

**Comment by Poolitzer** [comment]
hey, that's not the correct way to send local files.

```python
bot.send_media_group(
     chat_id=chat_id,
     media=[InputMediaPhoto(open('Users/myuser/Documents/mybot/photo1.png', 'rb')),
                   InputMediaPhoto(open('Users/myuser/Documents/mybot/photo2.png', 'rb'))]
        )
```

see https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#post-an-image-file-from-disk :)
