### ISSUE TITLE
Deprecation: v15

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2347]
Things we should drop in v15. The list is probably not complete. This includes everything deprecated in v13.x.

- [ ] The `@run_async` decorator
- [ ] `Filters.{private, group}`
- [ ] `utils.{promise, webhookhandler}`
- [ ] `clean` argument of `Updater.start_{polling, webhook}`
- [ ] Think about removing `Defaults` from `tg.Bot` completey and moving them to `tg.ext.ExtBot`. We may have to think about how to handle signatures with `DefaultVaule`, then, i.e. if `_insert_defaults` should stay in `tg.Bot` or should be moved to `tg.ext.ExtBot`.

**Comment by Poolitzer** [comment]
Why did you add this to the V14 stage?

**Comment by Bibo-Joshi** [comment]
because we decided to rip the band aid off … We also add the items to #2346 and delete this one, I was just too lazy for that

**Comment by Bibo-Joshi** [comment]
Closing in favor of #2346
