### ISSUE TITLE
Error while new installation on debian?

### ISSUE THREAD

**Issue by ChristianFeldmannHamm** [python-telegram-bot/python-telegram-bot#2356]
I started a new installation on debian 9.

```
pip3 install python-telegram-bot --upgrade
pip3 install -r requirements.txt
```

Then I created the echobot.py from the examples via nano.

Error message:
```
root@v2116:~# python3 echobot.py
Traceback (most recent call last):
  File "echobot.py", line 21, in <module>
    from telegram import Update
ImportError: cannot import name 'Update'
root@v2116:~#
```

Is there a simple explanation or solution to fix this problem?

Best regards Christian

**Comment by Bibo-Joshi** [comment]
Please double check that you have no other package installed that provides a `telegram` module. Also double check if you installed PTB to a virtual environment that you need to activate before running echobot.
