### ISSUE TITLE
[QUESTION] update_queue=None Warning

### ISSUE THREAD

**Issue by cocxtrash** [python-telegram-bot/python-telegram-bot#2360]
### Steps to reproduce
1. dispatcher: Dispatcher = Dispatcher(bot=bot, update_queue=None, workers=0, use_context=True)

### Expected behaviour
No Warning

### Actual behaviour
Warning: Expected type 'Queue', got 'None' instead

### Configuration
**Operating System:**
Microsoft Windows [Version 10.0.19042.572]

**Version of Python, python-telegram-bot & dependencies:**
``python-telegram-bot 13.2``
``certifi 2020.12.05``
``Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:37:30) [MSC v.1927 32 bit (Intel)]``

### Logs
---

**Comment by Bibo-Joshi** [comment]
Warning != Exception ;) If you don't want to see the warning, pass a `Queue()` to `update_queue` instead of `None`.
