### ISSUE TITLE
[BUG] Wrong signature of API objects/methods

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2367]
in `Bot.edit_message_mediag`, for some reason `media` is a optional kwarg, which is clearly wrong. Changing that is breaking, so putting on the v14 milestone.

We could think about expanding `test_official` to parse the offical docs in order to check such things.

**Comment by Bibo-Joshi** [comment]
We have a similar issue with the `ChatMember*` classes: For the subclasses currently all arguments are optional (except `user` and `status`), while most of them actually aren't. B/C users should never have to manually instantiate a `ChatMember*` manually, that's currently only a documentation/type hinting problem, but it should be fixed at some point.

We should really improve `test_official` for that …

**Comment by Poolitzer** [comment]
I like adding that to the test.
