### ISSUE TITLE
[BUG] Escaping markdown doesn't always work correctly

### ISSUE THREAD

**Issue by Endogen** [python-telegram-bot/python-telegram-bot#2371]
### Steps to reproduce
1. Execute this code:
```python
from telegram.utils.helpers import escape_markdown
test = "This is a test .. Let's see what happens"

update.message.reply_text(
    text=escape_markdown(test),
    parse_mode=ParseMode.MARKDOWN_V2
)
```
2. Result is:
```
‼️ Telegram ERROR: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
```

### Expected behaviour
Markdown should be escaped properly, no error should happen and the resulting message should be `This is a test .. Let's see what happens`

### Actual behaviour
Telegram replies with error:
`‼️ Telegram ERROR: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'`

### Configuration
**Operating System:**
macOS 11.1

**Version of Python, python-telegram-bot & dependencies:**
```
python-telegram-bot 13.2
certifi 2020.12.05
Python 3.9.1 (default, Dec 24 2020, 16:53:18)  [Clang 12.0.0 (clang-1200.0.32.28)]
```

**Comment by starry69** [comment]
Hi you need to pass optional `version` parameter as you're using markdown v2
```python
from telegram.utils.helpers import escape_markdown
test = "This is a test .. Let's see what happens"

update.message.reply_text(
    text=escape_markdown(test, version=2),
    parse_mode=ParseMode.MARKDOWN_V2
)```

**Comment by Endogen** [comment]
Oh! Didn't know, thanks! :+1:
