### ISSUE TITLE
[QUESTION] unable to install

### ISSUE THREAD

**Issue by flochocinco** [python-telegram-bot/python-telegram-bot#2376]
-->
### Steps to reproduce
Followed guide in main page.
1. ran python setup.py install in cloned folder (or python3 setup install)

### Expected behaviour
install successfully

### Actual behaviour
with python2:
  File "setup.py", line 52
    readme = f'README{"_RAW" if raw else ""}.rst'
                                                ^
SyntaxError: invalid syntax

with python3:
$ python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'

### Configuration
**Operating System:**
Ubuntu 18.04

**Version of Python, python-telegram-bot & dependencies:**

python 2.1.17 and python 3.6.9

cloned repo on february 9th

### Logs
Insert logs here (if necessary)

**Comment by Poolitzer** [comment]
hey, we dont provide support for python 2. setuptools is part of pip which is kinda part of python, I am not sure how you ended up with a version without one, but if you install pip, you should be good to go.

**Comment by flochocinco** [comment]
Hi,

I also tried with python3 using (from git clone folder):
python3 setup install

and I got:
Traceback (most recent call last):
File "setup.py", line 9, in
from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'

Did I miss something ?

**Comment by Bibo-Joshi** [comment]
Please install setuptools, then, i.e. `pip install setuptools`. The necessity for that has been subject of long discussions and lead to the PEP517 & PEP518 (iirc the numbers correctly), which to explain in detail is out of scope of this issue tracker ;)

**Comment by flochocinco** [comment]
Thanks for quick answer.
I think install is ok, eager to test now :)

actions:
$ sudo apt install python3-pip
$ pip3 install setuptools
$ sudo python3 setup.py install (Note: "python3 setup.pu install failed with message: error: can't create or remove files in install directory
)
