### ISSUE TITLE
Input of Make Test

### ISSUE THREAD

**Issue by KilluaKira** [python-telegram-bot/python-telegram-bot#238]
Hi, i have this error if i put make test

root@:~/python-telegram-bot# make test
nosetests -v
make: nosetests: Command not found
Makefile:28: recipe for target 'test' failed
make: *** [test] Error 127

**Comment by leandrotoledo** [comment]
@KilluaKira Hey, run to install the dependencies for development:

$ pip install -r requirements-dev.txt

**Comment by KilluaKira** [comment]
Sorry @leandrotoledo  i have this error
` ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/exec_used_py3.py", line 4
    exec('a = 1', globals={}) # [exec-used]
                         ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/invalid_star_assignment_target.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/invalid_star_assignment_target.py", line 3
    *FIRST = [1, 2, 3] # [invalid-star-assignment-target]
    ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/iterable_context_py3.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/iterable_context_py3.py", line 11
    class SomeClass(metaclass=Meta):
                             ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/mapping_context_py3.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/mapping_context_py3.py", line 15
    class SomeClass(metaclass=Meta):
                             ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/membership_protocol_py3.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/membership_protocol_py3.py", line 20
    class IterableClass(metaclass=MetaOldIterable):
                                 ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/misplaced_future.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/misplaced_future.py", line 3
    from __future__ import print_function # [misplaced-future]
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/nonlocal_and_global.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/nonlocal_and_global.py", line 5
    nonlocal missing
                   ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/nonlocal_without_binding.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/nonlocal_without_binding.py", line 9
    nonlocal a
             ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/not_async_context_manager.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/not_async_context_manager.py", line 50
    async def bad_coro():
            ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/not_in_loop.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/not_in_loop.py", line 7
    continue # [not-in-loop]
SyntaxError: 'continue' not properly in loop

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/raising_non_exception_py3.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/raising_non_exception_py3.py", line 13
    raise Exc from missing # [raising-non-exception]
                 ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/return_outside_function.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/return_outside_function.py", line 2
    return # [return-outside-function]
SyntaxError: 'return' outside function

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/star_needs_assignment_target.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/star_needs_assignment_target.py", line 3
    FIRST = *[1, 2]  # [star-needs-assignment-target]
            ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/star_needs_assignment_target_py35.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/star_needs_assignment_target_py35.py", line 8
    UNPACK_TUPLE = (*range(4), 4)
                    ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/syntax_error.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/syntax_error.py", line 1
    def toto # [syntax-error]
                            ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/syntax_error_jython.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/syntax_error_jython.py", line 1
    def toto # [syntax-error]
                            ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/too_many_star_expressions.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/too_many_star_expressions.py", line 3
    *FIRST, *SECOND = [1, 2, 3] # [too-many-star-expressions]
    ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/unbalanced_tuple_unpacking_py30.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/unbalanced_tuple_unpacking_py30.py", line 9
    first, second, *last = (1, 2, 3, 4)
                   ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/undefined_variable_py30.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/undefined_variable_py30.py", line 8
    def test(self)->Undefined: # [undefined-variable]
                  ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/unpacking_generalizations.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/unpacking_generalizations.py", line 16
    func_variadic_args(*(2, 3), *(3, 4), *(4, 5))
                                ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/used_before_assignment_nonlocal.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/used_before_assignment_nonlocal.py", line 10
    nonlocal cnt
               ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/yield_from_iterable_py33.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/yield_from_iterable_py33.py", line 7
    yield from 10  # [not-an-iterable]
             ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/yield_from_outside_func.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/yield_from_outside_func.py", line 2
    yield from [1, 2]  # [yield-outside-function]
             ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/yield_inside_async_function.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/yield_inside_async_function.py", line 4
    async def good_coro():
            ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/functional/yield_outside_func.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/functional/yield_outside_func.py", line 2
    yield 1  # [yield-outside-function]
SyntaxError: 'yield' outside function

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/input/func_kwoa_py30.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/input/func_kwoa_py30.py", line 3
    def function(*, foo):
                  ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/input/func_return_yield_mix_py_33.py ...
SyntaxError: 'return' with argument inside generator (func_return_yield_mix_py_33.py, line 8)

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/input/func_unused_import_py30.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/input/func_unused_import_py30.py", line 10
    class Meta(metaclass=abc.ABCMeta):
                        ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/input/func_w0705.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/input/func_w0705.py", line 28
    __revision__ += 1
SyntaxError: default 'except:' must be last

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/input/syntax_error.py ...
Sorry: IndentationError: expected an indented block (syntax_error.py, line 2)
Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/regrtest_data/bad_package/__init__.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/regrtest_data/bad_package/__init__.py", line 2
    raise missing.Missing..
                          ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/pylint/pylint/test/regrtest_data/syntax_error.py ...
  File "/tmp/pip-build-ShqHD7/pylint/pylint/test/regrtest_data/syntax_error.py", line 1
    class A extends B {}
                  ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-ShqHD7/astroid/astroid/tests/testdata/python3/data/module2.py ...
  File "/tmp/pip-build-ShqHD7/astroid/astroid/tests/testdata/python3/data/module2.py", line 100
    print('bonjour', file=stream)
                         ^
SyntaxError: invalid syntax

  Running setup.py install for wrapt
    building 'wrapt._wrappers' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/wrapt/_wrappers.c -o build/temp.linux-x86_64-2.7/src/wrapt/_wrappers.o
    src/wrapt/_wrappers.c:3:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    ***************************************************************************

    WARNING: The C extension component for wrapt could not be compiled.

    INFO: Trying to build without extensions.

    ***************************************************************************

    ***************************************************************************

    WARNING: The C extension component for wrapt could not be compiled.

    INFO: Only pure Python version of package installed.

    ***************************************************************************
  Running setup.py install for lazy-object-proxy

    warning: no directories found matching 'examples'
    warning: no files found matching '.isort.cfg'
    warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.dylib' found anywhere in distribution
    building 'lazy_object_proxy.cext' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc/lazy_object_proxy -I/usr/include/python2.7 -c src/lazy_object_proxy/cext.c -o build/temp.linux-x86_64-2.7/src/lazy_object_proxy/cext.o
    src/lazy_object_proxy/cext.c:3:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    ********************************************************************************
    WARNING:

        An optional code optimization (C extension) could not be compiled.

        Optimizations for this package will not be available!

    CAUSE:

        CompileError(DistutilsExecError("command 'x86_64-linux-gnu-gcc' failed with exit status 1",),)
    ********************************************************************************
Compiling /tmp/pip-build-ShqHD7/linecache2/linecache2/tests/inspect_fodder2.py ...
  File "/tmp/pip-build-ShqHD7/linecache2/linecache2/tests/inspect_fodder2.py", line 102
    def keyworded(*arg1, arg2=1):
                            ^
SyntaxError: invalid syntax

Successfully installed flake8 nose pep257 pylint unittest2 flaky pyflakes pep8 mccabe astroid traceback2 wrapt lazy-object-proxy linecache2
Cleaning up...`

**Comment by KilluaKira** [comment]
With this errors make test works lol

**Comment by leandrotoledo** [comment]
@KilluaKira haha, good!

**Comment by KilluaKira** [comment]
@leandrotoledo Sorry, you have a video tutorial to help me to create my first Bot? (to understand lol )Thanks in advance

**Comment by jh0ker** [comment]
@KilluaKira We don't have a video tutorial, **but** we have:
- complete [documentation](http://pythonhosted.org/python-telegram-bot/py-modindex.html)
- a step-by-step guide to your [first bot](https://github.com/python-telegram-bot/python-telegram-bot#extensions)
- lots of [code snippets](https://github.com/python-telegram-bot/python-telegram-bot#api)
- several [example bots](https://github.com/python-telegram-bot/python-telegram-bot/tree/master/examples) (suggest you start with `echobot2.py`)
