### ISSUE TITLE
[QUESTION] "Timed out" message

### ISSUE THREAD

**Issue by syyoo94** [python-telegram-bot/python-telegram-bot#2391]
### Steps to reproduce
1. An error occurs when downloading a file larger than 7MB

2.

3.

### Expected behaviour
try:
        bot.getFile(file_id_short).download(file_url_tmp,timeout=300)
except Exception as e:
        print e
        update.message.reply_text("Timed out! Please retry to upload!")

### Actual behaviour
Print "Timed out" Message

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by Bibo-Joshi** [comment]
Sorry, what's the issue here? I don't understand your description.

**Comment by starry69** [comment]
This is due to your network connection.. you connection gets times out before finishing the download. You can increase the timeout by passing `timeout` parameter like `File.download(timeout=120)`

**Comment by syyoo94** [comment]
An error occurs when downloading a file larger than 7MB

**Comment by Bibo-Joshi** [comment]
All right. If increasing the timeout doesn't help, there's nothing much PTB can do, though. Make sure that you have a stable internet connection and check this [wiki page.](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors)

**Comment by syyoo94** [comment]
When I try to download a file larger than 7MB using the telegram.File.download function, I get a "Timed out" error.
Is there any workaround other than modifying the timeout?
