### ISSUE TITLE
[QUESTION] ValueError: ConversationHandler my_conversation can not be persistent if dispatcher has no persistence

### ISSUE THREAD

**Issue by kenorb** [python-telegram-bot/python-telegram-bot#2395]
### Issue I am facing

I've the error when running `examples/persistentconversationbot.py`.

### Traceback to the issue
```
% ./persistentconversationbot.py
Traceback (most recent call last):
  File "./persistentconversationbot.py", line 181, in <module>
    main()
  File "./persistentconversationbot.py", line 166, in main
    dp.add_handler(conv_handler)
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 506, in add_handler
    raise ValueError(
ValueError: ConversationHandler my_conversation can not be persistent if dispatcher has no persistence
```

### Related part of your code

- `examples/persistentconversationbot.py`
- `python-telegram-bot==13.2`

**Comment by Poolitzer** [comment]
I can not reproduce. What system are you running the code on, and what python version?

**Comment by Bibo-Joshi** [comment]
in the example, persistence is used:

https://github.com/python-telegram-bot/python-telegram-bot/blob/a34f0b9beece9f503d0c02dd9ac04477438fa68a/examples/persistentconversationbot.py#L133

Your error means that you changed that.

**Comment by kenorb** [comment]
> In the example, persistence is used.

My fault, I've replaced token without having `persistence=pp` part. Thanks!
