### ISSUE TITLE
[FEATURE] Change ConversationHandler._get_key to return namedtuple instead of tuple

### ISSUE THREAD

**Issue by hexatester** [python-telegram-bot/python-telegram-bot#2413]
#### Is your feature request related to a problem? Please describe.
I want to create database backed persistence for conversations but there is no easy way to do it, because the key returned from ConversationHandler._get_key were unpredictable (very hard to distinguish between chatid, userid, and or messageid).

#### Describe the solution you'd like
I think it would be nice if you would add `ConversationKey` class or `collections.namedtuple` as the key so it will make it easier to develop custom coversation persistence.

```python
ConversationKey = namedtuple('ConversationKey', ['name', 'chat_id', 'user_id', 'message_id'])

# or

class ConversationKey:
    def __init__(self, name: str, chat_id: int, user_id: Optional[int] = None, message_id: Optional[int] = None):
        self.name = name
        self.chat_id = chat_id
        self.user_id = user_id
        self.message_id = message_id
```

#### Describe alternatives you've considered
I considered passing all ConversationHandler to persistence (to get .per_\* value), but that didn't work because its too had :P.

#### Additional context
Here's my [custom persistence](https://github.com/UnivTerbuka/UnivTerbukaBot/tree/main/univterbukabot/telegram/persistence) for the reference.

**Comment by Bibo-Joshi** [comment]
Hi. I don't really see why you would need to know which entry of the key tuple represents which information in order to make it persistend. You just need to store a mapping tuple -> state, which wouldn't really change if we used namedtuples/custom classes for the keys.

**Comment by hexatester** [comment]
> 
> 
> Hi. I don't really see why you would need to know which entry of the key tuple represents which information in order to make it persistend. You just need to store a mapping tuple -> state, which wouldn't really change if we used namedtuples/custom classes for the keys.

I intend to use the entry of the key for fetcing / storing the state in database.

**Comment by Bibo-Joshi** [comment]
> I intend to use the entry of the key for fetcing / storing the state in database.

So? If you database can't handle tuples as key, just convert it to a string or something. My point is that knowing the structure of the key is of no additional value when trying to serialize it as long as you *can* serialize it.
