### ISSUE TITLE
Can't instantiate abstract class FilterAwesome with abstract methods __call__ [BUG]

### ISSUE THREAD

**Issue by wub1990** [python-telegram-bot/python-telegram-bot#2418]
### Steps to reproduce
```
# Custom filter
class FilterAwesome(BaseFilter):
    def filter(self, message):
        if message.text is not None:
            return "echo" == message.text.lower().split(" ")[0]
```

### Expected behaviour
At this time noting, I am trying to start the bot and it crashes

### Actual behavior
It crashes with this error: `TypeError: Can't instantiate abstract class FilterAwesome with abstract methods __call__`

### Configuration
Ubuntu 20.04

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

python-telegram-bot 13.3
certifi 2020.12.05
Python 3.6.9 (default, Jan 26 2021, 15:33:00)  [GCC 8.4.0]

### Logs
Insert logs here (if necessary)

**Comment by wub1990** [comment]
It had worked previously. the complete code is:

create_filters .py
# Custom filter
class FilterAwesome(BaseFilter):
    def filter(self, message):
        if message.text is not None:
            return "echo" == message.text.lower().split(" ")[0]

filter_awesome = FilterAwesome()

bot.py
from create_filters import filter_awesome

echo_handler = MessageHandler(filter_awesome, filters.echo)
    dispatcher.add_handler(echo_handler)

filters.py
def echo(update, context):
    run("echo")
    message = " ".join(update.effective_message.text.split(" ")[1:])
    context.bot.send_message(chat_id=update.effective_message.chat_id, text=message)

**Comment by starry69** [comment]
If you're on v13 or above you need to inherit your custom filter from `MessageFilter` instead of `BaseFilter`
So your filter should look like:
```python
class FilterAwesome(MessageFilter):
    def filter(self, message):
        if message.text is not None:
            return "echo" == message.text.lower().split(" ")[0]

filter_awesome = FilterAwesome()
```

**Comment by wub1990** [comment]
> ```python
> MessageFilter
> ```

Thanks that fixed it. Sorry for mistagging
