### ISSUE TITLE
erro in replykeyboardmarkup.py

### ISSUE THREAD

**Issue by jegue** [python-telegram-bot/python-telegram-bot#242]
Hi i set the
 custom_keyboard = [[ telegram.Emoji.THUMBS_UP_SIGN, telegram.Emoji.THUMBS_DOWN_SIGN ]]
reply_markup = telegram.ReplyKeyboardMarkup(custom_keyboard) 
and getting this erro
 File "/usr/local/lib/python2.7/dist-packages/telegram/base.py", line 58, in to_json
    return json.dumps(self.to_dict())
  File "/usr/local/lib/python2.7/dist-packages/telegram/replykeyboardmarkup.py", line 77, in to_dict
    data['keyboard'].append([x.to_dict() for x in keyboard])
AttributeError: 'str' object has no attribute 'to_dict'

I am using the bot-api-2.0 branch

thanks a lot

**Comment by jh0ker** [comment]
@jegue You have to use keyboard buttons, check the state machine example on the dispatcher-rework branch.

**Comment by jegue** [comment]
thank you I wll check!

**Comment by jegue** [comment]
@jh0ker I start the bot and after enter any valeu in the Please enter your settings value or send /cancel to abort
I get this erro
 File "/usr/local/lib/python2.7/dist-packages/telegram/replykeyboardmarkup.py", line 77, in to_dict
    data['keyboard'].append([x.to_dict() for x in keyboard])
AttributeError: 'unicode' object has no attribute 'to_dict'

**Comment by jh0ker** [comment]
If the keyboard entries are of unicode type, you are probably doing something wrong. They should be of type KeyboardButton

**Comment by jegue** [comment]
@jh0ker 
yeap using the dispatcher-rework branch. solve the problem!
thanks a lot for you help! :)
