### ISSUE TITLE
[QUESTION] job queue is not passed to callback when use_context is True 

### ISSUE THREAD

**Issue by OriYitzhaki** [python-telegram-bot/python-telegram-bot#2421]
### Steps to reproduce
1. Set that code:

```from telegram.ext import Updater, CommandHandler

    def callback_alarm(bot, job):
        bot.send_message(chat_id=job.context, text='Wait for another 10 Seconds')

    def callback_timer(bot, update, job_queue):
        bot.send_message(chat_id=update.message.chat_id,
                         text='Wait for 10 seconds')
        job_queue.run_repeating(callback_alarm, 10, context=update.message.chat_id)

    def Stop_timer(bot, update, job_queue):
        bot.send_message(chat_id=update.message.chat_id,
                         text='Stopped!')
        job_queue.stop()

    updater = Updater("Token")
    updater.dispatcher.add_handler(CommandHandler('start', callback_timer, pass_job_queue=True))
    updater.dispatcher.add_handler(CommandHandler('stop', Stop_timer, pass_job_queue=True))

    updater.start_polling()
```

2. and send start.

### Expected behaviour
Well... that just should and send messages.

### Actual behaviour
TypeError: callback_timer() missing 1 required positional argument: 'job_queue'
the last arg is not passed.

### Configuration
**Operating System:** Windows 10.

**Version of Python, python-telegram-bot & dependencies:**
python 3.8, python-telegram-bot  Latest
``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by starry69** [comment]
You're using old handler signature, 
It should look like
```python
def job_callback(context: CallbackContext):
    ...
```
Since from v12 onwards, only `CallbackContext` gets passed into job callbacks, job is available as `context.job`
