### ISSUE TITLE
"object has no attribute 'text'" when bot is in Channel (works fine in groups)

### ISSUE THREAD

**Issue by PeterStavrou** [python-telegram-bot/python-telegram-bot#2422]
My bot works perfectly in groups and when I message it, however, when I add it to a Channel and give it all admin permissions it does not work. The echo message function gives an error of **caused error 'NoneType' object has no attribute 'text'**.

```
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
from telegram import MessageEntity, InlineQueryResultArticle, InputTextMessageContent

def echo(update, context): # this is from the documentation
    context.bot.send_message(chat_id=update.effective_chat.id, text=update.message.text)

def error(update, context):
    print(f'Error {update} caused error {context.error}')

def main():
    updater = Updater(API)
    dp = updater.dispatcher
    
    #Echo message
    echo_handler = MessageHandler(Filters.text & (~Filters.command), echo)
    dp.add_handler(echo_handler)

    #Handle errors
    dp.add_error_handler(error)

    updater.start_polling()
    updater.idle()

main()
```

**Comment by Bibo-Joshi** [comment]
That's because for channel posts it's `update.channel_post`. Use `update.effective_message` if you don't want to differentiate between channel posts, messages and edited messages/channel posts.

**Comment by PeterStavrou** [comment]
> That's because for channel posts it's `update.channel_post`. Use `update.effective_message` if you don't want to differentiate between channel posts, messages and edited messages/channel posts.

Perfect! Thank you so much!
