### ISSUE TITLE
[BUG] SSL error regarding hardcoded path of certificate in certifi.where() - Running serverless on aws lambda

### ISSUE THREAD

**Issue by herzog0** [python-telegram-bot/python-telegram-bot#2426]
### Steps to reproduce
1. Configure any bot (like echobot.py) to run on aws lambda

2. Configure it as a trigger to api gateway requests

3. Make a request to api gateway expecting the bot to run

(if requested I can provide the actual code to make it work "serverlessly", but the problem is not about the code)

### Expected behavior
The bot should run normally and echo the message back to me.

### Actual behavior
I get an SSL error which you can check [here](https://pastebin.com/CS0bmNGS) 

### Configuration
**Operating System:** Amazon Linux 2 (the instance in which an aws lambda runs with python3.8) 

**Version of Python, python-telegram-bot & dependencies:** 
I have the following dependencies for my project
```
boto3==1.17.25
googlemaps==4.4.2
python-dotenv==0.15.0
python_dateutil==2.8.1
python-telegram-bot==13.3
```
``$ python -m telegram``
python-telegram-bot 13.3
certifi 2019.11.28
Python 3.8.5 (default, Jan 27 2021, 15:41:15)  [GCC 9.3.0]

### Logs
 [Pastebin link](https://pastebin.com/CS0bmNGS)
 
 
 
 I've actually found a solution to the problem and managed to fix it, so I'm posting here and proposing a solution.    
 When deploying the code in this kind of server not always the standard paths are going to be preserved. In this case, for example, the hardcoded path `'/etc/ssl/certs/ca-certificates.crt'` in `venv/lib/python3.8/site-packages/certifi/core.py:15` was not the correct location for the certificate file.   
 In order to deploy my code to an aws lambda I have to generate a .zip package with all python packages in the root path, alongside the code. The zip is automatically extract to `/var/task/` by aws, and that hardcoded path by certifi actually doesn't exist.   
 To fix it, I've simply overwritten the hardcoded path with my own hardcoded path in the file mentioned above, that was `'/var/task/certifi/cacert.pem'`.   
 Now everything worked fine.  
 
 My proposed solution was to provide an optional environment variable that would override the result of `certifi.where()`. This way I wouldn't have to manually edit the core.py file and, probably, others won't have to search a lot to solve this problem. I was stuck with this for the past 2 days and only achieved the correct solution by joining several small pieces of solutions found on the internet.

**Comment by Bibo-Joshi** [comment]
Hi. TBH at first glance this seems to be a problem with certifi rather than actually with PTB. Please first try upgrading certifi to the latest version. Note that [`certify/core.py`](https://github.com/certifi/python-certifi/blob/2020.12.05/certifi/core.py) has changed considerably since v2019.11.28.

**Comment by herzog0** [comment]
Yep, bumping the version to the latest "certifi==2020.12.5" worked perfectly.  Could this be put in consideration? To give a minimum version clause to certifi in PTB's requirements?

**Comment by Bibo-Joshi** [comment]
Mh, I'm not sure that I see a big need for that. AFAIK this is the first time someone had this problem and it seems to be very platform specific. Additionally, any fresh setup won't have the problem.

**Comment by herzog0** [comment]
Oh, ok then. If someone else eventually stumbles into the same problem they will see the issue at least.  
I believe that I already had certifi installed globally and, since PTB doesn't lock certifi's version, the virtualenv was hard linking the old version already contained in my system.  Though my specific problem is indeed an OS specific problem, this old version of certifi doesn't point to the correct location of its certificate:  
```
~ >>> python3.8 -m certifi     # version 2019.11.28                                                                                                          /etc/ssl/certs/ca-certificates.crt
``` 
^- Hardcoded wrong path of the bundled certificate
```
~ >>> python3.8 -m certifi    # version 2020.12.5                                                                                                               
/home/mypc/.local/lib/python3.8/site-packages/certifi/cacert.pem
``` 
^- The actual correct location of certifi's bundled certificate.
