### ISSUE TITLE
Problem with decorated message handler functions

### ISSUE THREAD

**Issue by michaelimfeld** [python-telegram-bot/python-telegram-bot#243]
Hi,
I'm trying to write some decorators for message handler functions. It seems that the addition of the args parameter does not work in this case.
```
def mydecorator(decorator_arg):
    def decorate(func):
        def call(*args):
            print args 
            result = func(*args)
            return result
        return call
    return decorate

@mydecorator("helloworld")
def caps(bot, update, args):
    text_caps = ' '.join(args).upper()
    bot.sendMessage(chat_id=update.message.chat_id, text=text_caps)

dispatcher.addTelegramCommandHandler('caps', caps)
```

In my decorator which takes every argument (*args), I only get an update and a bot object as arguments. I assume that the telegram module does some kind of amount of required arguments discovery on my handler function which seems to be made impossible with my decorator?

**Comment by jh0ker** [comment]
@michaelimfeld Yes, this issue was already identified and is now fixed in the beta branch called dispatcher-rework. It introduces a few other changes, and also implements bot-api 2.0. Please note that it's not backwards compatible, and might contain bugs. It seems to be stable though.

**Comment by michaelimfeld** [comment]
Alright, thanks for the fast reply!

**Comment by jh0ker** [comment]
@michaelimfeld No problem - I also recommend you join our Telegram group, where you can get help with the transistion
