### ISSUE TITLE
[QUESTION] Close bot instance safely

### ISSUE THREAD

**Issue by RiccardoBarbieri** [python-telegram-bot/python-telegram-bot#2430]
Until now I've always closed it by typing Ctrl + C on the terminal but I got some errors regarding multiple instances open at the same time.
Is there any way to close a running bot instance safely?

**Comment by RiccardoBarbieri** [comment]
> @RiccardoBarbieri Ctrl + c will not leave a process running, it will terminate it. I am not sure I understand your question correctly, can you define safely?

I found this thread and a user says that with ctrl+c the session might not be terminated properly
https://github.com/yagop/node-telegram-bot-api/issues/550

**Comment by Bibo-Joshi** [comment]
That thread is from a node.js library. That's completely unrelated to PTB.

**Comment by RiccardoBarbieri** [comment]
Yes but the error is the same, any way is there a way to terminate a bot sessione properly and completely or is ctrl+c enough?

**Comment by Bibo-Joshi** [comment]
It's enough. If you still get that error, just revoke your bot token. That will make any other process that tries to get updates fail.

**Comment by RiccardoBarbieri** [comment]
Ok thank you
