### ISSUE TITLE
Failing to initialice a WebHook on version 13.4.1 on Mac OS

### ISSUE THREAD

**Issue by AnderUstarroz** [python-telegram-bot/python-telegram-bot#2434]
I am using Mac OS **10.15.7** (Catalina) with Python **v3.7.9** and **python-telegram-bot==v13.4.1**. I cannot initialize the webhook  on this new version because fails listening on the usually valid ips: `'127.0.0.1'`,`'localhost'`,  `'0.0.0.0'`. But it definitely works on **python-telegram-bot==v13.3** !

### Steps to reproduce
```
TELEGRAM_BOT = {
    'WEBHOOK_SITE': 'https://my-public-address',
    'BOTS': [
        {
            'TOKEN': 'my-bot-token',
        },
    ],
}
TELEGRAM_SERVER = {
    'CONFIG': {
        'listen': '127.0.0.1',
        'port': 5000,
        'url_path': TELEGRAM_BOT['BOTS'][0]['TOKEN']
    },
    'HTTPS': {
        'url': os.path.join(TELEGRAM_BOT['WEBHOOK_SITE'], TELEGRAM_BOT['BOTS'][0]['TOKEN']),
    }
}

def main():
    updater = Updater(settings.TELEGRAM_BOT['BOTS'][0]['TOKEN'])
    updater.start_webhook(**settings.TELEGRAM_SERVER['CONFIG'])
    updater.bot.set_webhook(**settings.TELEGRAM_SERVER['HTTPS'])
    updater.idle() 
    
main()
```
### Expected behaviour
Run server normally, just like the good old times (when using python-telegram-bot==**13.3**)

### Actual behaviour
Throws an error when using any  `'127.0.0.1'`,`'localhost'`,  `'0.0.0.0'`.

### Configuration
**Operating System:** Mac OS **10.15.7** (Catalina)
**Python:** 3.7.9
**python-telegram-bot:** 13.4.1

### Logs
```
telegram.error.BadRequest: Bad webhook: ip address 127.0.0.1 is reserved
```

**Comment by Bibo-Joshi** [comment]
Hi. Seems like we've overlooked something in #2419. Can you please try

```python
updater.start_webhook(**settings.TELEGRAM_SERVER['CONFIG'], webhook_url = settings.TELEGRAM_SERVER['HTTPS']['url'])
```
instead, i.e. pass the webhook url to `start_webhook` and skip the `set_webhook` call?

**Comment by AnderUstarroz** [comment]
Indeed, worked! Thanks @Bibo-Joshi
