### ISSUE TITLE
[BUG] Broken button '4' in inlinekeyboard2.py example

### ISSUE THREAD

**Issue by harshil21** [python-telegram-bot/python-telegram-bot#2440]
When the inline button '4' in the inlinekeyboard2.py example is clicked, it sends the same button as an option in the keyboard menu. Thus, when the user clicks it again, Telegram raises an error saying new message content and reply markup is same. This can confuse a user.

### Steps to reproduce
1. Run inlinekeyboard2.py, click `/start`.

2. Click button '1'.

3. Click button '4'.

4.  Click button '4' again.
5.  Error raised from Telegram.

Potential fix:
Change which button is offered in the keyboard menu.

**Comment by Poolitzer** [comment]
just change 4 to 2 or so

**Comment by hugoncosta** [comment]
Personally I also do not particularly enjoy this being considered an error. Editing a message and making it the same should be evaluated including the buttons and not just the message text. Personally, I change it based on the change actioned on the button (my use case has the user choosing who to follow and I edit the message to say "x is now followed" "x is not followed anymore").
