### ISSUE TITLE
[BUG] Markdown v2 inline links seem to be broken

### ISSUE THREAD

**Issue by l0drex** [python-telegram-bot/python-telegram-bot#2447]
### Steps to reproduce
1. Create a bot.

2. Send a message in markdown v2 formatting containing an inline link like this:
    ```markdown
    [Link](example.com) (test)
    ```

### Expected behaviour
A text like this:
[Link](example.com) (test)

### Actual behaviour
I receive no message from the bot. Same for only `(` or only `)` after the link.

### Configuration
**Operating System:**
Manjaro Linux

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

python-telegram-bot 13.4.1
Bot API 5.1
certifi 2020.12.05
Python 3.9.2 (default, Feb 20 2021, 18:40:11)  [GCC 10.2.0]

### Logs
Insert logs here (if necessary)

There is no error message in the command line.

**Comment by l0drex** [comment]
I also get no response when writing a url after the inline link like this:

```markdown
[Link](example.com) example.com
```

**Comment by Bibo-Joshi** [comment]
Hi. Please show how exactly you call `bot.send_method`, i.e. with all parameters that you pass. Also please try `http://example.com` instead of just `example.com`.

**Comment by l0drex** [comment]
I'm answering a command using the following code:

```python
# ...
def setup():
    # ...
    dispatcher.add_handler(CommandHandler('test', command_test)

def command_test(update, _):
    update.message.reply_markdown_v2('[test](https://example.com) (test)')
```

In the actual code I'm using a real link, so that `https://` shouldn't make a difference.

**Comment by Bibo-Joshi** [comment]
All right, the problem is that the braces around the second `test` need to be escaped: `\(test\)`. But you should get an error telling you that:

```python
telegram.error.BadRequest: Can't parse entities: character '(' is reserved and must be escaped with the preceding '\'
```
