### ISSUE TITLE
Drop Python 2.6

### ISSUE THREAD

**Issue by rahiel** [python-telegram-bot/python-telegram-bot#245]
We have some specific code for python 2.6 but we don't have to support it because it is already [EOL](https://docs.python.org/devguide/#status-of-python-branches) since 2013. 

We don't have to drop it immediately, we can drop it:
* when a dev is frustrated with py 2.6
* when a dev needs a [py 2.7 feature](https://docs.python.org/2.7/whatsnew/2.7.html)
* on April fool's

Reference: [Stop Supporting Python 2.6 (For Free)](http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html)

**Comment by leandrotoledo** [comment]
- [ ] Replace str % formatting to .format (not really because 2.6 but it's a good excuse)
- [ ] Replace {0} in favor of {}
- [ ] Native unittest2
- [ ] More asserts for unittest

**Comment by jh0ker** [comment]
Maybe we could run a small poll in the group to see if people are still running on 2.6

**Comment by leandrotoledo** [comment]
- Added to milestone: v5.0

**Comment by leandrotoledo** [comment]
Poll results:
www.strawpoll.me/10227996/r

**Comment by rahiel** [comment]
- [ ] replace `nullhandler.py` with [`logging.NullHandler`](https://docs.python.org/2/library/logging.handlers.html#logging.NullHandler)

**Comment by rahiel** [comment]
From the poll, 6% (12 votes) want to keep py 2.6. 

We released 4.1 on 16 May with the deprecation warning for py26, I propose to drop it from Travis somewhere around 16 August, then users have 3 months to upgrade. From then on support for 2.6 will be unofficial: it may accidentally work. Until we release 5.0 when we remove the last traces of the old snake.

Users of 2.6 could look at using [Miniconda](http://conda.pydata.org/miniconda.html).

**Comment by denismakogon** [comment]
This discussion should have wider context because Py 2.7 was already dropped of from Linux distribution in latest Debian and Ubuntu LTS releases. Available version of python is 3.5.1+

So, it is worth considering to drop off 2.6 and 2.7 at the same time.

**Comment by rahiel** [comment]
> So, it is worth considering to drop off 2.6 and 2.7 at the same time.

I disagree, 2.7 is still supported and will be supported even after 2020 in the pypy implementation. And Pypi statistics show that 2.7 is still used more than 3: [here](https://caremad.io/2015/04/a-year-of-pypi-downloads/) and more recently, [here](https://s.caremad.io/Xqm0DRUmF9/).
