### ISSUE TITLE
Error in inlinekeyboard_example.py

### ISSUE THREAD

**Issue by candidobugarin** [python-telegram-bot/python-telegram-bot#246]
Hello
I am studying program updates and have an error in the script when inlinekeyboard_example.py matter telegram package in the ninth line. I tried to install the telegram again but the error remains . The error in question is :
File " telegram_proj / telegram001_t.py " , line 8 , in < module>
    from telegram import Emoji , ForceReply , ReplyKeyboardMarkup , KeyboardButton
ImportError : can not import name Emoji

If I can help in any way , tell me .

Thank you and good night.

**Comment by leandrotoledo** [comment]
@candidobugarin By any chance do you have a file named telegram.py in your working dir?

**Comment by ronaldpatino** [comment]
Hi I am getting the same error (Python 2.7.10): 

(venv) orlock@comp:~/pythonsrc$ python ard2.py 
Traceback (most recent call last):
  File "ard2.py", line 9, in <module>
    from telegram import Emoji, ForceReply, InlineKeyboardButton, \
ImportError: cannot import name InlineKeyboardButton

**Comment by leandrotoledo** [comment]
@ronaldpatino make sure you are using the Release Candidate version of this library:

```
$ pip install python-telegram-bot==4.0rc1
```

**Comment by candidobugarin** [comment]
Hello When I updated by Pip , I found the error cited above. But using pip
install python- telegram -bot == 4.0rc1 , the funcinou program without
problems. I do not understand much about the pip , but I believe the
problem should be there. Grateful Candido Bugarin

2016-04-22 22:39 GMT-03:00 Leandro Toledo <notifications@github.com>:

**Comment by leandrotoledo** [comment]
@candidobugarin This is a RC version, so whenever you run `pip install python-telegram-bot` it will install the latest stable version, right now it is, `3.4`. Although, `4.0` has the Bot 2.0 features and we wanted to release to the community as soon as possible while we still work on get documentation and more tests.

Cheers.

**Comment by candidobugarin** [comment]
Ah yes. Updates that they made really were quite interesting . This new bot
I'm doing I intend to use my university to help students protect themselves
on campus because we have many problems with violence. Even I plan to use
some of the new features in it.

2016-04-22 23:09 GMT-03:00 Leandro Toledo <notifications@github.com>:

**Comment by ronaldpatino** [comment]
@leandrotoledo Thanks a lot! that did the trick. I appreciate a lot your help.

**Comment by candidobugarin** [comment]
The keyboard button to send location is already available?

2016-04-22 23:19 GMT-03:00 Ronald Patino <notifications@github.com>:

**Comment by leandrotoledo** [comment]
@candidobugarin it is, along with all the new features of Bot API 2.0 specified on http://core.telegram.org/bots/api. Happy hacking!

**Comment by candidobugarin** [comment]
@leandrotoledo 

Hello.
Testing request_location , I could not get the latitude and longitude after the user sends the location. I tried the update.message , update.message.location and he does not return anything .
This isthe code I used to create the keyboard: reply_markup ReplyKeyboardMarkup = ( [ [ KeyboardButton ( "test" , request_location = True ) ] ] , one_time_keyboard = True )
Even in the old version , I used the update.message.location to collect location .
You know if something changed in the form of collection ?

Thank you very much

**Comment by leandrotoledo** [comment]
@candidobugarin checking

**Comment by leandrotoledo** [comment]
@candidobugarin here is a snippet for that

https://gist.github.com/leandrotoledo/f84617ca088fe8fe0877d7222e057f7e

You should handle the user location as a new update to be parsed from the user.
