### ISSUE TITLE
[BUG] Can't handle editing message published via bot with getUpdates/webhook

### ISSUE THREAD

**Issue by vashchukmaksim** [python-telegram-bot/python-telegram-bot#2461]
### Steps to reproduce
1. Create simple bot
2. Create command handler (just for simplicity) to send any message to a channel
3. Create handler to catch chanel's post editing (or just `Filters.all`)
4. Add bot to channel's admins
5. Send a message using created command handler
6. Edit post via Telegram client
7. No reaction from bot

### Expected behaviour
Bot should handle editing message action for messages that is sends to a channel the same way it handles editing messages that are sent to a channel via Telegram client.

### Actual behaviour
No reaction from bot

### Configuration
**Operating System:**
Docker with python:3.6 image

**Version of Python, python-telegram-bot & dependencies:**
python 3.6
python-telegram-bot==13.4.1

### Logs
That's the problem - no logs

I have other handlers that work as expected including message editing but only for messages that are sent directly via Telegram client but not from bot (the same bot that tries to handle editing action). I tried to remove all the handlers and use the only one ith just `Filters.all` still no effect.

I'm not sure if it is a library bug or API limitation but I couldn't find any information about that. If it is expected could you please share a link to docs or source code where it is mentioned? Feel free to close this issue if it is not related to the library itself.

**Comment by Poolitzer** [comment]
Hi, I am confused. You say

 > Bot should handle editing message action for messages that is sends to a channel the same way it handles editing messages that are sent to a channel via Telegram client.
 
So I assume from this that you are confused why a handler, which should catch edit message updates, doesn't trigger when a post gets edited in the channel by the **bot itself**.

But then you said:

> 6. Edit post via Telegram client
> 7. No reaction from bot

which would mean that the handler should trigger when the post gets edited by **someone else**, which is a different situation.

So which one is it? :D

**Comment by vashchukmaksim** [comment]
Will try again briefly :D What the task and options are:

**Option 1 (works fine):**
1. Send a message manually via Telegram client
2. Edit this message via Telegram client
3. Catch edited message with bot (boom, it works, we see logs)

**Option 2 (doesn't work):**
1. Send a message to the same channel using bot
2. Edit this message via Telegram client
3. Catch edited message with bot (doesn't work, no reaction at all)

As you can see the only difference is who sent a message human via Telegram client vs bot.

**Comment by Poolitzer** [comment]
ah, hm. I think thats because the internal ownership of this message changes. Messages in channels behave really weird this way. E.g., send a message with a bot, edit it with a different one, then try to edit with the first, it will fail.

I am very sure that this is not an issue with the library, rather telegram not generating an update because... reasons, let me quickly check though

**Comment by Poolitzer** [comment]
Yes, verified, this is a (potential) issue with the telegram bot API. You can create an issue over at their [official repo](https://github.com/tdlib/telegram-bot-api), the maintainer their was very responsive so far.

**Comment by vashchukmaksim** [comment]
Thanks! Created an issue there. Btw, about ownership of a message, this scenario also works fine. But that's for multiple users/admins, not sure about different bots.

**Option 3 (also works fine):**

1. Send a message to a channel manually via Telegram client
2. Edit this message via Telegram client with the same user
3. Catch edited message with bot (boom, it works, we see logs)
4. Edit the same message with another user via Telegram client
5. Works again
