### ISSUE TITLE
[QUESTION] unclear usage of run_async 

### ISSUE THREAD

**Issue by xmatthias** [python-telegram-bot/python-telegram-bot#2462]
### Issue I am facing
It's unclear to me from both the docs and samples what the `run_async` parameter does in the command handler.
By passing `run_async` to a handler, i'd expect the callback provided to be treated as a coroutine - but that doesn't seem to be happening.

I also couldn't find any example using run_async - so the command naming suggests it'll support async requests, but it really doesn't call them (or await them).

### Related part of your code

```python
from telegram.ext import CallbackContext, CommandHandler, Updater

async def some_message(update: Update, context: CallbackContext) -> None:
    pass

def some_message_sync(update: Update, context: CallbackContext) -> None:
    pass


handlers = [
CommandHandler('somemessage',  some_message, run_async=True),
CommandHandler('somemessage2',  some_message_sync),
]

_updater = Updater(token=self._config['telegram']['token'], workers=0,
                                use_context=True)
for handle in handles:
     _updater.dispatcher.add_handler(handle)
_updater.start_polling()
...

```

**Comment by Bibo-Joshi** [comment]
Hi. `run_async` uses threads and currently has nothing to do with `asyncio` (which will change at some point in the futere, see [here](https://t.me/pythontelegrambotgroup/430620)). For a detailed introduction for `run_async` see [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Performance-Optimizations).

**Comment by xmatthias** [comment]
thanks - in that case the name is kinda missleading (run_threads might be better ...).

Anyway, i hope the asyncio version lands soon!
