### ISSUE TITLE
[BUG] JobQueue produces orphan processes

### ISSUE THREAD

**Issue by ismailbayram** [python-telegram-bot/python-telegram-bot#2463]
### Steps to reproduce
1. my workers parameter is set to 4. there are 3 jobs in the job queue which runs every 5 minutes.
2. After they worked, their processes weren't be killed. They still occupy the memory.
3. So I've tried a library which is used in PTB whose name is APScheduler==3.6.3. I've tried the similir scenario:

```python
from datetime import datetime
import time
import os

from apscheduler.schedulers.background import BackgroundScheduler


def tick():
    print('Tick! The time is: %s' % datetime.now())

if __name__ == '__main__':
    scheduler = BackgroundScheduler()
    scheduler.add_job(tick, 'interval', seconds=3)
    scheduler.start()
    print('Press Ctrl+{0} to exit'.format('Break' if os.name == 'nt' else 'C'))

    try:
        # This is here to simulate application activity (which keeps the main thread alive).
        while True:
            time.sleep(2)
    except (KeyboardInterrupt, SystemExit):
        # Not strictly necessary if daemonic mode is enabled but should be done if possible
        scheduler.shutdown()
```
4. there is no orphan processes.
### Expected behaviour
There should not be more than 4-5 processes.

### Actual behaviour
[orphan processes in my htop](https://ibb.co/4T2LRp0)

PTB orphan processes code example
```python
def init_alarms(job_queue, bot):
    now = datetime.utcnow()
    for alarm in Alarms:
        job_queue.run_repeating(alarms.alarm_func, settings.INTERVALS[interval],
                                        # FIXME: settings.INTERVALS[interval]
                                        name=...,
                                        first=first_time,  # FIXME: first_time
                                        context={...})


def main():
    updater = Updater(settings.TELEGRAM_TOKENS.get(os.getenv("ENV", "dev")), use_context=True, workers=4)

    # Get the dispatcher to register handlers
    dp = updater.dispatcher
    init_alarms(updater.job_queue, updater.bot)

    # log all errors
    dp.add_error_handler(error)

    # Start the Bot
    if os.getenv("ENV", "dev") == "prod":
        prod_token = settings.TELEGRAM_TOKENS["prod"]
        updater.start_webhook(....)
    else:
        updater.start_polling()

    # Run the bot until you press Ctrl-C or the process receives SIGINT,
    # SIGTERM or SIGABRT. This should be used most of the time, since
    # start_polling() is non-blocking and will stop the bot gracefully.
    updater.idle()
```

### Configuration
**Operating System:**
ubuntu 20.04

**Version of Python, python-telegram-bot & dependencies:**
python 3.8.6

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by Bibo-Joshi** [comment]
Hey. Thanks for the issue. Please also provide a [minimal example with PTB](https://telegra.ph/Minimal-Working-Example-for-PTB-07-18) that produces the orphan processes ;)

**Comment by ismailbayram** [comment]
@Bibo-Joshi I've added :)

**Comment by Bibo-Joshi** [comment]
Hey. I tried to reproduce and at least have a partial explanation. It mainly consists of me not being familiar with htop :D So the point is that PTB runs several threads:

* one main thread
* one for `Updater`
* one for `Dispatcher`
* one for `JobQueue`
* one for each `run_async` worker thread

and htop apparently shows them all separately. This is exactly what I see when I run the PTB example above and the number of processes stays constant.

Admittedly in your screenshot there's 16 processes IISC, which is ~double of what I expected. My first question would be if yor input for `workers` was higher for that particular example.

**Comment by ismailbayram** [comment]
I've decreased workers parameter to 0. The bot have been running for 6 hours and there are 14 processes shown in htop. @Bibo-Joshi

**Comment by Bibo-Joshi** [comment]
Stupid question, but did you restart the bot after changing the worker number to 0? The "6 hours" is irritating me, because I relplied only ~2hs ago :D 

btw, if you set `workers=0`, handlers with `run_async=True` won't work. Don't know if that's relevant for you, just don't want your bot to hang ;)

**Comment by ismailbayram** [comment]
@Bibo-Joshi Ofcourse I did :). And I have no handler whose run_async parameter is set as True. My problem is that my machine runs the bot has only 1GB memory :). The OS shuts it down every 10 hours. maybe I should increase my machine capacity.

**Comment by Bibo-Joshi** [comment]
Mh. That's strange. You shouldn't need 1GB memory to run a simple bot. Can you please check again and confirm that this minimal snippet (compressed from yours above, i.e. no other things related to your bot are involed) gives you 16 threads in htop and eats up the whole of your 1GB memory?

```python
from telegram.ext import Updater


updater = Updater('token')
updater.job_queue.run_repeating(lambda c: print('this is the job'), 2)
updater.start_polling()
updater.idle()
```

**Comment by ismailbayram** [comment]
Actually, the bot processes pandas dataframes whose sizes are almost 50MB, and there are 10 datasets.

**Comment by Bibo-Joshi** [comment]
Aha! Then please check

* if you're getting some many orphan processes with above minimalistic example
* if for your usual bot the number of processes is hight directly from the start or starts increasing with time when jobs are excuted
* if you're using pandas within the jobs, check how long the jobs take to finish, i.e. how many jobs are running in parallel
* if pandas opens any threads on its own

**Comment by ismailbayram** [comment]
Thank you very much. I'll check!

**Comment by ismailbayram** [comment]
Thank you for your reply.
