### ISSUE TITLE
Overhaul of warnings

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2467]
While reviewing #2464 I noticed that we're not very consistend on whether we use `logger.warning` or `warnings.warn` to issue warnings to users and I think we should try to overhaul that in v14. Here are a few things that came to my mind and that I'd like to discuss & tackle:

* We should add a subclass of `UserWarning` named `TelegramUserWarning` or similar. That way users can filter for those explicitly, if they want to.
* `TelegramDeprecationWarning` should then become a subclass of that new class
* Both should be properly included in the documentation. They exist so that users can use them in filtering, so users should be above to find them in the docs. To this end, they should probably also be easier importable, i.e. via `telegram.utils.TGWarning` or `telegram.deprecation.TGWarning`, maybe even `telegram.TGWarning` (see also #2468)
* Regarding when to use what: Citing the [python docs on logging](https://docs.python.org/3/howto/logging.html#when-to-use-logging):

  > **Issue a warning regarding a particular runtime event:**
  > warnings.warn() in library code if the issue is avoidable and the client application should be modified to eliminate the warning
  >
  > logging.warning() if there is nothing the client application can do about the situation, but the event should still be noted

  The way I understand this, this would mean in particular that we should use `warnings.warn()` whenever

  * the user passes some non-reasonable value on initialization on classes that are usually set up manually (e.g. `Updater` and `Handlers`, in contrast to the TG types)
  * the way the users tries to use stuff does not correspond to how they set up the bot (thinking of e.g. [~this~](https://github.com/python-telegram-bot/python-telegram-bot/blob/conv-timeout/telegram/ext/conversationhandler.py#L625) [this](https://github.com/python-telegram-bot/python-telegram-bot/blob/bcec6f03cb1797d31039926f0c8c0f2306dcdf5a/telegram/ext/conversationhandler.py#L648-L651))
  * the users misuses something, the example that I have in mind is equality comparison for objects that have no `_id_attrs`

* We should make a wiki page on logging and warnings. We can then delete the logging section from the readme. the wiki page should also contain some basic info about how to catch warnings in the logger and how to filter warnings/logging entries made by PTB.
* **edit:** for warnings, it would be good to double check that the `stacklevel` is set appropriately 

As changing warnings <-> logs is somewhat breaking at least for people who filter those things, I'm putting this on the v14 milestone.

**Comment by Poolitzer** [comment]
> We should make a wiki page on logging and warnings. We can then delete the logging section from the readme. the wiki page should also contain some basic info about how to catch warnings in the logger and how to filter warnings/logging entries made by PTB.

Very much agree on this,

**Comment by Poolitzer** [comment]
Tthe this link in the second bullet point doesn't work, and if I look at the code line you probably mean, Im not sure I get the relation:

```try:
            new_state = handler.handle_update(update, dispatcher, check_result, context)
        except DispatcherHandlerStop as exception:
            new_state = exception.state
            raise_dp_handler_stop = True```

**Comment by Bibo-Joshi** [comment]
Ah sorry. No, I meant this:

https://github.com/python-telegram-bot/python-telegram-bot/blob/bcec6f03cb1797d31039926f0c8c0f2306dcdf5a/telegram/ext/conversationhandler.py#L648-L651

i.e. the user tries to use the `JobQueue`, but didn't set one up.

**Comment by Poolitzer** [comment]
#2615 is probably a duplicate/extension of this, I am going to leave it open though until someone else decides that.
