### ISSUE TITLE
[INVALID] File to short when installing it in docker container

### ISSUE THREAD

**Issue by BlackTurtle123** [python-telegram-bot/python-telegram-bot#2469]
### Steps to reproduce
1. Build docker container `FROM python:3
RUN pip install python-telegram-bot`

2. Run the python application

3. During startup it crashes

### Expected behaviour
Application should run fine 

### Actual behaviour
```
Traceback (most recent call last):
  File "/height.py", line 2, in <module>
    from telegram.ext import Updater, CommandHandler
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/__init__.py", line 27, in <module>
    from .jobqueue import JobQueue, Job
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 26, in <module>
    from apscheduler.events import EVENT_JOB_ERROR, EVENT_JOB_EXECUTED, JobEvent
  File "/usr/local/lib/python3.7/site-packages/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 32, in <module>
    import plistlib
  File "/usr/local/lib/python3.7/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "/usr/local/lib/python3.7/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: /lib/x86_64-linux-gnu/libexpat.so.1: file too short
```

### Configuration
FROM python:3
But also tried fixed versions from 3.8, 3.8,...

**Version of Python, python-telegram-bot & dependencies:**
Latest since container is freshly build

**Comment by Bibo-Joshi** [comment]
This error does not seem to stem from PTB. Typing in `ImportError file too short` in your favorite search engine yields multiple results from idfferent contexts. TBH I haven't fully understood what it's exactly about but it seems to be a problem with shared libraries on your setup.

> Version of Python, python-telegram-bot & dependencies:
> Latest since container is freshly build

Apparently not, your traceback says `python3.7`, latest would be `3.9` :P

**Comment by BlackTurtle123** [comment]
Like I told, I tried with all the python container versions.
It all gives the same error. Where they before would work.
So because the 3.9 didn't worked I tried my way down the 3.x line...

Op di 13 apr. 2021 22:24 schreef Bibo-Joshi ***@***.***>:

**Comment by Bibo-Joshi** [comment]
I only saw 3.8 and 3.7, that's why I pointed it out, but I know that it shouldn't make a difference. Anyway, I'll close this, because we can't do anything about it.

**Comment by BlackTurtle123** [comment]
So how do you explain that older docker containers stop work for the newer
telegram python? All docker containers there dependecy's are updated in the
official repos ?

Op di 13 apr. 2021 22:32 schreef Bibo-Joshi ***@***.***>:

**Comment by Bibo-Joshi** [comment]
Well, you didn't even mention that, so how do you expect me to comment on that? 😉 
Please tell, then, on which PTB version the docker container worked and what else changed since then.
