### ISSUE TITLE
How to do internationalization?

### ISSUE THREAD

**Issue by zhitnik-hiteklab** [python-telegram-bot/python-telegram-bot#2471]
We're making simple bot with `python-telegram-bot`. It have to answer in dirrerent languages concerning client locale. How can we organize this? `gettext`? How bot will know client language?

**Comment by Bibo-Joshi** [comment]
Hi. There is `User.language_code` that you can use to determine the users locale. Note that this attribute is optional (and TBH I haven't yet tried out when it's `None` and when not), so you should set a fallback language. Another option is to provide a settings menu where the user can choose a language - this could be also done in addition to guessing the language from `User.language_code`.

How exactly you handle the translation is up to you. There is ofc `gettext` but also there are packages dedicated to internationalization. I also know bots that use simple dict-like structures to store predefined texts.

**Comment by zhitnik-hiteklab** [comment]
Ok, thanks!
