### ISSUE TITLE
[QUESTION] CallbackQueryHandler missing 1 required positional

### ISSUE THREAD

**Issue by Kmiokande** [python-telegram-bot/python-telegram-bot#2473]
### Issue I am facing
I have several callbacks in my bot, and I'm having trouble passing an argument to one of them. I followed the documentation and even then the error persists.

### Traceback to the issue
```
error crypto_callback_handler() missing 1 required positional argument: 'chat_data'
```

### Related part of your code
```python
def crypto_callback_handler(update, context, chat_data):
    My code ...

crypto_callback = CallbackQueryHandler(crypto_callback_handler, pass_chat_data=True)
```

**Comment by starry69** [comment]
After v12 `pass_something=True` arguments of handlers arevdeprecated, `chat_data` can now be acessed as [context.chat_data](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.callbackcontext.html#telegram.ext.CallbackContext.chat_data). Change your handler signature to
```python
def crypto_callback_handler(update, context):
    chat_data = context.chat_data
    My code ...
```
Also take a look at v12 [translation guide](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-12.0) for more information.

**Comment by Kmiokande** [comment]
Thanks :)
