### ISSUE TITLE
[QUESTION] How can I execute both callback and url parameters?

### ISSUE THREAD

**Issue by LightCannon** [python-telegram-bot/python-telegram-bot#2481]
Hello. 
I noticed that InlineKeyboardButton only executes opening url or the callback. 
How can I make it execute both? I want to make the button to open a url in telegram in addition to catch the callback from this button. How to do this?

**Comment by Poolitzer** [comment]
You can not.

You could, however, let the url point to your own public webserver and track access that way, or you could use a data button first, and upon pressing, edit it into an URL one.
