### ISSUE TITLE
invalid syntax update.message.from.language_code

### ISSUE THREAD

**Issue by WebParanoid** [python-telegram-bot/python-telegram-bot#2482]
Hi. I use the example echobot.py. When I try to get update.message.from.language_code I have an error  SyntaxError: invalid syntax

**Comment by Bibo-Joshi** [comment]
`from` is a reserved word in Python, hence PTB uses `from_user` instead, as noted in the [docs](https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html) 😉

**Comment by WebParanoid** [comment]
> `from` is a reserved word in Python, hence PTB uses `from_user` instead, as noted in the [docs](https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html) 😉

Thank you!
