### ISSUE TITLE
Why not every photo can be sent?? using send_photo

### ISSUE THREAD

**Issue by samyarkd** [python-telegram-bot/python-telegram-bot#2487]
hi !

I have a problem that has eaten my nerves

pls help me

problem: 
i want to send photo by URL using "send_photo" 

I have a list of links that I want to send but not all links are sent and I do not know what to do

Were there any restrictions on sending photos?

EX:
```python

urls = ['https://www.quizazem.com/wp-content/uploads/2020/05/Levi-Ackerman-7.jpg', 'https://wallpaperboat.com/wp-content/uploads/2020/10/20/57360/levi-ackerman-11.jpg', 'https://pm1.narvii.com/7569/bb01b6be7f0cab4e25e4512859bd8a55ce944451r1-870-1011v2_hq.jpg', 'https://static.zerochan.net/Levi.Ackerman.full.2574308.png', 'https://comicvine1.cbsistatic.com/uploads/original/11119/111193741/4236626-2778572452-levi-.jpg', 'https://d.wattpad.com/story_parts/626306859/images/15509e0b21efe7a8149802357564.gif', 'https://www.bing.com/th/id/OGC.2a9355b4fe1871b4c0448bf2df5cf5ea?pid=1.7&amp;rurl=https%3a%2f%2fd.wattpad.com%2fstory_parts%2f626306859%2fimages%2f15509e0b21efe7a8149802357564.gif&amp;ehk=IM6fvrYF8PAe%2fgFzTs4eJX2%2bESIbhUckug8w2Culas4%3d', 'https://images.wallpapersden.com/image/download/levi-ackerman-attack-on-titan_a2poZWWUmZqaraWkpJRnZWltrWZmamc.jpg', 'https://yt3.ggpht.com/a/AGF-l79VdGJiPItRn3lszUx5sHGLBQtkCJFXSZ5w-A=s900-c-k-c0xffffffff-no-rj-mo', 'https://fsa.zobj.net/crop.php?r=CxMdr3P5rmLMLvc3HVN_kkjY5jEY2HwixIJJ1oRH1yFUAtt87mEdgXwM-D0KVFLKDAev-hZpIqMJ6pO2Gw-ZkFP-CnZ2nWIgu6Kj5PD9o_uo4QLkfqP4jHHrPxxD5KiXbJrlHf8WjtS6BhS0']


for url  in urls:
    context.bot.send_photo(update.effective_chat.id, url)

```
this my code and not all links are sent 

🗡️

**Comment by Bibo-Joshi** [comment]
Hi. Do you get any specific error message? If yes, please show the traceback.
In general, Telegram is sometimes a bit picky about URLs. In my experience links ending on a file ending work more reliable than links that don't.

**Comment by samyarkd** [comment]
> Hi. Do you get any specific error message? If yes, please show the traceback.
> In general, Telegram is sometimes a bit picky about URLs. In my experience links ending on a file ending work more reliable than links that don't.

no , nothing

i think it's just about telegram :(
