### ISSUE TITLE
Can't import InlineQueryHandler and other stuff

### ISSUE THREAD

**Issue by savandriy** [python-telegram-bot/python-telegram-bot#249]
I can't import these things:

```python
from telegram import InputTextMessageContent
from telegram.ext import InlineQueryHandler, CommandHandler
```
Running Python 2.7.9, latest PyCharm (2016.1.2), Ubuntu 15.04. Installed python-telegram-bot using pip. Tried to run the inlinebot for testing, and got errors on imports.

**Comment by jh0ker** [comment]
You have to use the most up-to-date version: `pip install python-telegram-bot==4.0rc1 --upgrade`
pip doesn't install release candidates by default, that's why you have to specify the version here.

**Comment by savandriy** [comment]
Thanks! Now it works perfectly!
