### ISSUE TITLE
update_id attribute reference for class 'Message'

### ISSUE THREAD

**Issue by KirillTim** [python-telegram-bot/python-telegram-bot#250]
My pycharm noticed, that there is no attribute `update_id` in class `Message`(indeed) but it is referenced in many places: [updater.py#L251](https://github.com/python-telegram-bot/python-telegram-bot/blob/7c8a0e00c0308b3357d5cefbe12b454da19d4f4b/telegram/ext/updater.py#L251), [updater.py#L343](https://github.com/python-telegram-bot/python-telegram-bot/blob/7c8a0e00c0308b3357d5cefbe12b454da19d4f4b/telegram/ext/updater.py#L343). 
I've looked for changes if Message class and haven't find any resent `update_id` related changes.
Is it a bug oh what have i misunderstood?

**Comment by jh0ker** [comment]
Those are references to `Update.update_id`
