### ISSUE TITLE
[QUESTION] Save file to /tmp

### ISSUE THREAD

**Issue by enboig** [python-telegram-bot/python-telegram-bot#2508]
I am trying to save a file to temp folder, my code is:
```
filePath= newFile.download(custom_path=tempfile.gettempdir())
```
But it returns me
```
  File "/home/bot/newbot.py", line 436, in import_ods
    filePath= newFile.download(custom_path=tempfile.gettempdir())
  File "/home/bot/.local/lib/python3.8/site-packages/telegram/files/file.py", line 164, in download
    with open(filename, 'wb') as fobj:
IsADirectoryError: [Errno 21] Is a directory: '/tmp'
```
How could I achieve this?

**Comment by Poolitzer** [comment]
Well you need to save the file to a file, not a folder. Assuming the function for custom_path returns a string, all you need to do is add a `+ "/filename"`. Now, depending on your setup, you might want unique name there, but you will have to find your own logic for this. You could for example use the file ID.

**Comment by enboig** [comment]
Sorry to continue a closed issue, I will use complete file path if requested. After reading https://github.com/python-telegram-bot/python-telegram-bot/issues/1041  I thought just a folder path should be given.

**Comment by Bibo-Joshi** [comment]
If you're talking about `download(custom_path="/some/path")`: `"/some/path"` should be a file path in that case, e.g. `/path` is not a directory
