### ISSUE TITLE
Killing signal, SIGTERM SIGINT 

### ISSUE THREAD

**Issue by Justxd22** [python-telegram-bot/python-telegram-bot#2509]
How can i handle the kill signals, instead of exiting I want to do some work i can't find proper documentation about the signal_handler() function

**Comment by Bibo-Joshi** [comment]
See the `user_sig_handler` parameter of [Updater](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.updater.html). I'd like to point out that the signal handler is mainly intended for stuff like closing threads. If you want to run code on exit you can also just put it after the `updater.idle()` call. It will then get executed on exit. see also #2153
