### ISSUE TITLE
[FEATURE] messages.getAllChats method not found in Bot class

### ISSUE THREAD

**Issue by goedzo** [python-telegram-bot/python-telegram-bot#2512]
I want to get all the chats my bot is in, and the messages.getAllChats from the API should give these:
https://core.telegram.org/method/messages.getAllChats

However I am unable to find this method in the Bot class. 

 getChat(chat_id, timeout=None, api_kwargs=None) is implemented in Bot class, so to me it seems logically that getAllChats can also be added to the same object.

**Comment by goedzo** [comment]
@Bibo-Joshi thanks for the quick reply, but now I am a little confused here. What is the difference between Mtproto and the API? 
Under the API/Methods, the getAllChats function is listed: https://core.telegram.org/methods
To me this looked like an api method, but from your reply it seems that this is not? 

Nevertheless my goal is to get the chatID from all the groups my bot is in. Is this even possible?

**Comment by Bibo-Joshi** [comment]
See https://github.com/tdlib/telegram-bot-api/issues/1#issuecomment-721873231
If you want to know all chats your bot is a member in, you'll have to keep track. See the chatmemberbot.py example in the examples directory.
