### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by dqanshi** [python-telegram-bot/python-telegram-bot#2514]
### Issue I am facing
Please describe the issue here in as much detail as possible

### Traceback to the issue
```
```thats not sending photo   why

### Related part of your code
```python
```
update.effective_message.send_photo(
        img,PM_START_TEXT, 
        reply_markup=InlineKeyboardMarkup(buttons),
        parse_mode=ParseMode.MARKDOWN,
        timeout=60,
        disable_web_page_preview=False,

**Comment by Poolitzer** [comment]
if img is a file, you need to open it with open(img, "rb"), and please fill out the actual issue form and provide an error.

**Comment by dqanshi** [comment]
Thanks
