### ISSUE TITLE
cannot import name "Update" [BUG]

### ISSUE THREAD

**Issue by Staga-det** [python-telegram-bot/python-telegram-bot#2515]
I have never experienced this error before. I receive the following warning message: 
`ImportError: cannot import name 'Update' from 'telegram' (C:\Users\loren\anaconda3\lib\site-packages\telegram\__init__.py)
`
I have even tried to uninstall and reinstall the library (through `pip uninstall telegram`), but it doesn't seem to solve anything.

### Steps to reproduce
1. `pip install --upgrade python-telegram-bot` 

2. `from telegram import Update` or `from telegram.ext import Updater, CommandHandler, MessageHandler, Filters` (both result in a very similar error)

3. The following error appears:
```
ImportError                               Traceback (most recent call last)
<ipython-input-4-66bd7a92968d> in <module>
      1 import telegram
----> 2 from telegram import Update
      3 from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
      4 import logging
      5 import feedparser

ImportError: cannot import name 'Update' from 'telegram' (C:\Users\loren\anaconda3\lib\site-packages\telegram\__init__.py)
```

### Configuration
**Operating System:** Windows 10

**Version of Python, python-telegram-bot & dependencies:**
I'm using Python 3 via Jupyter Notebook

**Comment by Poolitzer** [comment]
Sounds like you have telegram installed from pip. Run `pip uninstall telegram` and then maybe reinstall PTB and you should be fine.

**Comment by Staga-det** [comment]
> Sounds like you have telegram installed from pip. 
Yes, I do

> Run `pip uninstall telegram` and then maybe reinstall PTB and you should be fine.
I have already tried uninstalling and reinstalling it with this procedure, but it does not solve the issue

**Comment by Staga-det** [comment]
> @Staga-det Do you have a file called telegram.py in your PYTHONPATH or current directory?

That does not seem to be the case

> What happens when you do:
 ```
import telegram
 print(telegram.__file__)
 ```

I receive the following:
```AttributeError                            Traceback (most recent call last)
<ipython-input-3-71c31dd959d9> in <module>
      1 import telegram
----> 2 print(telegram.file)

AttributeError: module 'telegram' has no attribute 'file'```

**Comment by Staga-det** [comment]
> @Staga-det Are you missing two underscores on each side?

I am so sorry, I had just noticed the typo. The output is:
```C:\Users\loren\anaconda3\lib\site-packages\telegram\__init__.py```

**Comment by Staga-det** [comment]
@tsnoam thank you so much for your time! That worked
