### ISSUE TITLE
[FEATURE] Add a pattern for result_id of ChosenInlineResultHandler

### ISSUE THREAD

**Issue by Flowiee** [python-telegram-bot/python-telegram-bot#2516]
In this way you can separate the results of your inline queries and redirect them to specific function as it happens for callback queries.

**Comment by Poolitzer** [comment]
I like this, good QoL change

**Comment by stdz56** [comment]
> In this way you can separate the results of your inline queries and redirect them to specific function as it happens for callback queries.

This logic works for all types of handler

**Comment by Poolitzer** [comment]
huh, I do not get that? There are quite some Handlers which handle without any filtering because it wouldn't make sense, e.g. the Poll handlers
