### ISSUE TITLE
[BUG]T unexpected keyword argument 'map_to_parent'

### ISSUE THREAD

**Issue by sergio-ns** [python-telegram-bot/python-telegram-bot#2518]
### Steps to reproduce
1.

2.

3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by Poolitzer** [comment]
Hey, please fill out the issue form, otherwise we are not able to help you.
