### ISSUE TITLE
[QUESTION] Unexpected keyword argument 'map_to_parent' in nestedconversationbot.py

### ISSUE THREAD

**Issue by sergio-ns** [python-telegram-bot/python-telegram-bot#2519]
### Issue I am facing
When launching the example file **nestedconversationbot.py** I'm getting an error message:
Unexpected keyword argument 'map_to_parent'

### Traceback to the issue
```
Traceback (most recent call last):
  File "nestedconversationbot.py", line 392, in <module>
    main()
  File "nestedconversationbot.py", line 331, in main
    STOPPING: STOPPING,
TypeError: __init__() got an unexpected keyword argument 'map_to_parent'
```

### Related part of your code
```python
        map_to_parent={
            # Return to second level menu
            END: SELECTING_LEVEL,
            # End conversation altogether
            STOPPING: STOPPING,
        },
```

**Comment by Poolitzer** [comment]
If you didnt change anything in the example, it sounds like you aren't on a version which supports the nested ConversationHandlers. Which one are you on? 

https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#how-can-i-check-the-version-of-ptb-i-am-using

**Comment by sergio-ns** [comment]
Understood, I'm on 12.1.1, I guess support for nested conv handlers was introduced later.
I will upgrade
Thanks

**Comment by sergio-ns** [comment]
Upgraded to latest and error went away, closing the issue.
Thanks for the prompt support
