### ISSUE TITLE
ftrack - autodesk maya - telegram bot problem 

### ISSUE THREAD

**Issue by hovertone** [python-telegram-bot/python-telegram-bot#2521]
We use ftrack data management system, 3D software Autodesk Maya and Telegram bot for notification. When I just use a Telegram bot in Autodesk Maya, everything works. But if I us Ftrack python for Autodesk Maya and Telegram bot, I get the error:

```
telegram.bot : Entering: send_video
telegram.vendor.ptb_urllib3.urllib3.connectionpool : Starting new HTTPS connection (1): api.telegram.org
Error: NetworkError: file X:/app/win/Pipeline/modules/bot/telegram/utils/request.py line 228: urllib3 HTTPError [Errno 2] No such file or directory # 
```

**Comment by Bibo-Joshi** [comment]
Please see this [wiki section](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#working-with-files-and-media) how sending files work.
