### ISSUE TITLE
[FEATURE/DISCUSSION]: Allow fine tuning of persistence setup

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2524]
There are two places in the current persistence setup where I think we can offer more customization for advanced users. All of this are just first ideas and up for discussion. If the dev team doesn't like the (use case value)/(maintenance workload) ratio, I'd be fine with not doing this.

1. Edit: We're dropping `insert/replace_data` see #2882 . 

    Original comment: 
We currently pass all data that goes through the persistence setup through `replace/insert_bot`. While this is the safest way to make sure no `Bot` instance gets serialized, it can also introduce some overhead which could get noticable when you have large, nested data structures in your `chat/bot/user_data` or are handling many updates. Adanced users will know where in their data they have bot instances that should get replaced. So we could offer settings like `replace_bots_in_chat/bot/user_data` (defaulting to True) and only call `replace/insert_data` when necessary.

     One should note that we'd have to re-indroduce deepcopy into the built-in persistence classes (depending on the `replace_bots_in_*` settings, that is). See https://github.com/python-telegram-bot/python-telegram-bot/pull/2262#discussion_r632762276

2. #2285 already made an effort to reduce the calls of `Dispatcher.update_persistence`. Still, updating after every update (or even handler call in case you're using `run_async`) might be unecessary, especially when you're getting updates frequently. Similarly to `PicklePersistence.on_flush` which allows users to control how often `PP` writes to file, we would add a flag telling `Dispatcher` to never automatically call `Dispatcher.update_persistence` at runtime (only on shutdown). Then users can call `Dispatcher.update_persistence` manually to their liking.

**Comment by Poolitzer** [comment]
I like both of these suggestions. Since we redesign a lot for 14 anyway, and the resulting maintenance after doing it once shouldn't be too bad,

**Comment by Paddy613** [comment]
****

**Comment by Bibo-Joshi** [comment]
Got started on the first part of this in the https://github.com/python-telegram-bot/python-telegram-bot/tree/customize-replace-insert-bot branch. But we're currently re-evaluating if we want to proceed this.

second part may be independent.

**Comment by Bibo-Joshi** [comment]
closed by #2893
