### ISSUE TITLE
[BUG] Message editing not working currently

### ISSUE THREAD

**Issue by beeb** [python-telegram-bot/python-telegram-bot#2525]
Hi! Something weird is happening with editing messages today. Same code was working fine earlier. Problem also happens when using a callback query and trying to edit the message through the query. Is anything wrong on the Telegram server side maybe?
Can anyone reproduce?

### Steps to reproduce
1. Create a message by either replying to user message or sending message directly through the bot

2. Save the message ID of that message

3. Try to edit message with `context.bot.edit_message_text` using the message ID

### Expected behaviour
The message should update with new content

### Actual behaviour
The message remains unedited

### Configuration
**Operating System:**
Linux + macOS

**Version of Python, python-telegram-bot & dependencies:**
Python 3.7.10
python-telegram-bot 13.5

``$ python -m telegram``

```
python-telegram-bot 13.5
Bot API 5.2
certifi 2020.12.05
Python 3.7.10 (default, May  3 2021, 02:44:43)  [GCC 9.3.0]
```

### Logs
Nothing in particular. The result of the edit command shows the edited message object.

**Comment by Poolitzer** [comment]
You don't get an error? It returns the edited message but you don't see it on your end?

**Comment by beeb** [comment]
> You don't get an error? It returns the edited message but you don't see it on your end?

Correct, no error, message is returned but I don't see the updated content in the chat. Tested on two different bots with two different codebases.

**Comment by beeb** [comment]
@Poolitzer just tried now and it's the same on the web-app. Almost like if the server did not send the updates to the clients and fails silently..?

**Comment by beeb** [comment]
@Poolitzer Thanks, I would love some confirmation to see if I'm going crazy or there's a backend problem ^^

**Comment by Poolitzer** [comment]
I used `bot.edit_message_text(params**)`, worked for me

**Comment by beeb** [comment]
Damn, I even tried reverting to one of my old commits where I'm 100% sure it was working, and still I don't get updates in the live bot, the test bot running the same code, and another totally different bot...
That's on clients for web, Android, Windows and macOS.
I could try to create a new bot maybe?

**Comment by beeb** [comment]
Deleting messages works so I think the message ID is correct...

**Comment by beeb** [comment]
Yep thanks, just wanted to make sure. I'll try to create a fresh bot also.

**Comment by Poolitzer** [comment]
Hope you figure it out!
