### ISSUE TITLE
[BUG] send_invoice: send_phone_number_to_provider is set from send_email_to_provider

### ISSUE THREAD

**Issue by nkrivenko** [python-telegram-bot/python-telegram-bot#2526]
### Steps to reproduce
1. Create bot with connected payment provider YooKassa

2. Call `bot.send_invoice(..., send_phone_number_to_provider=True, need_phone_number=True)`

### Expected behaviour
`sendInvoice` POST request to Telegram API with `send_phone_number_to_provider: true` in body

### Actual behaviour
`sendInvoice` POST request to Telegram API without `send_phone_number_to_provider: true` in body. This behaviour produces an error "Customer e-mail and phone number are not specified" when trying to pay with YooKassa.

### Configuration
**Operating System:**
Linux Mint 20.1 Ulyssa

**Version of Python, python-telegram-bot & dependencies:**

```
python-telegram-bot 13.5
Bot API 5.2
certifi 2020.12.05
Python 3.9.0+ (default, Oct 20 2020, 08:43:38)  [GCC 9.3.0]
```

**Comment by harshil21** [comment]
You're right. Sorry for this. Will be fixed
