### ISSUE TITLE
[FEATURE] skip scheduled job interval

### ISSUE THREAD

**Issue by MoonshineSG** [python-telegram-bot/python-telegram-bot#2538]
#### Is your feature request related to a problem? Please describe.
An enhanced "run_repeating" job scheduler where you can specify "skip between...". 

#### Describe the solution you'd like
Useful for  example to skip jobs at night. 

#### Describe alternatives you've considered
This can be achieved by doing a check inside the scheduled method/job. 

#### Additional context
n/a

**Comment by Poolitzer** [comment]
I think this is a fair enough feature request, though pretty advanced. You can use [APScheduler's](https://apscheduler.readthedocs.io/en/stable/index.html) scheduler instance directly via `context.job_queue.scheduler` (we use BackgroundScheduler). This way you can define your own [trigger](https://apscheduler.readthedocs.io/en/stable/userguide.html#choosing-the-right-scheduler-job-store-s-executor-s-and-trigger-s) which allows you to [combine triggers](https://apscheduler.readthedocs.io/en/stable/modules/triggers/combining.html#module-apscheduler.triggers.combining). However, you dont have the context parameter you expect. You'd have to pass args like the library does, just [look in the code](https://github.com/python-telegram-bot/python-telegram-bot/blob/cc43aef64bc3501c08cc9e1641777ecd87b98e74/telegram/ext/jobqueue.py#L275-L295) if you want to copy it.


I would agree that this is a valid feature request, and all we need to do to allow you to pass your own triggers would add this as parameters to the function, so I will be fine with this change. The other maintainers will need to voice their opinion on that however.

**Comment by Bibo-Joshi** [comment]
We already have `JobQueue.run_custom` in place that allows you to use your own triggers, so IMHO I don't see a need for additional functionality somewhere 🤔

**Comment by Poolitzer** [comment]
Oh yeah, I totally overlooked that one. Lets leave it open to see if OP wants more but I am sure this should suffice.

**Comment by MoonshineSG** [comment]
I'll have a look at custom jobs. Hopefully not too complicated to implement. 
I can always peak at "run_repeating" and get inspired. 

Let's say this will do. Thanks for a quick reply.

**Comment by MoonshineSG** [comment]
having a "run_cron" would be probably helpful...

**Comment by Bibo-Joshi** [comment]
APScheduler has a Cron trigger that you can use with run_custom

**Comment by MoonshineSG** [comment]
Thanks. Need to figure that one out then. Cron should be able to handle "repeat every X min between A and B" `*/5 7-22 * * *`

**Comment by MoonshineSG** [comment]
I admit defeated. "Cron trigger that you can use with run_custom" sounds simple, but can get my head around it...

**Comment by MoonshineSG** [comment]
`updater.job_queue.run_custom(check_payment_job, job_kwargs = {'trigger': CronTrigger.from_crontab("*/1 7-22 * * *")})`

seams to do the trick... Thanks!
