### ISSUE TITLE
How to upload large file (>1GB) 

### ISSUE THREAD

**Issue by rushi3691** [python-telegram-bot/python-telegram-bot#2540]
i want to upload a large file on telegram servers and check progress. how to implement this? Please help me
i've seen some bots that can upload large files on telegram.

**Comment by harshil21** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Local-Bot-API-Server

**Comment by rushi3691** [comment]
Thanks for reply. Can you please explain or is there any brief docs on this to understand it.

**Comment by Poolitzer** [comment]
you were literally linked to brief docs. what do you not understand?
