### ISSUE TITLE
Forcing to TLS 1.2?

### ISSUE THREAD

**Issue by gilfalko** [python-telegram-bot/python-telegram-bot#2545]
Hi,

As Telegram Supports TLS versions 1.2 and over,
I was wondering how do I setup this library to actually use it?

I'm getting the following error:

2021-06-05 16:33:31,969 - tornado.general - WARNING - SSL Error on 10 ('91.108.x.x', 35212): [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:852)

Thanks
Gil

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for reaching out. Can you please give us the details about

* Your operating system
* Your python version
* your version of PTB (``$ python -m telegram``)
* your version of tornado (``$ pip show tornado``)

?

**Comment by gilfalko** [comment]
Well, it turns out uploading the public cert to Telegram fixed it...
I have no idea how that's related if the error message was regarding TLS 1.0 but Webhook is working perfctly now.
Cheers!
Gil
