### ISSUE TITLE
[FEATURE] Add a shortcut for update.message.reply_to_message

### ISSUE THREAD

**Issue by Flowiee** [python-telegram-bot/python-telegram-bot#2546]
Accessing replied messages is kinda long, imagine having to look at the name of the user that replied to a message, it would be something like: `update.message.reply_to_message.from_user.first_name`, having a shortcut for that would be surely better, something like other `update.effective_` shortcuts.

**Comment by Bibo-Joshi** [comment]
Hi. If this is a serious feature request, please fill out the intire issue template so that we know what you're looking for.

**Comment by Bibo-Joshi** [comment]
Thanks for the update. So you'd suggest something like `update.effective_reply` as shortcut for `update.effective_message.reply_to_message`? TBH, at first glance this seems somewhat overly specific to me, but maybe the other devs have a different opinion.

Note that the `update.effective_*` shortcuts are just for cases where there is common behavior across different update types and we don't offer e.g. `update.callback_data` as shortcut for `update.callback_query.data` either.

**Comment by harshil21** [comment]
I don't really like the idea of it either, very specific and can be confusing to some.
