### ISSUE TITLE
PEP8 issue: Methods should be snake case

### ISSUE THREAD

**Issue by Nekmo** [python-telegram-bot/python-telegram-bot#255]
All methods violate the PEP8. I propose to implement both methods and add a DeprecationWarning.

Thanks!

**Comment by leandrotoledo** [comment]
Hi @Nekmo, thanks for opening this issue.
This is indeed true, most of Bot class methods violate PEP8 guidelines, but we decided to do it in this way to make it easier for those using Telegram Core API documentation, I hope this makes sense.
That said, I'd rather keep this way for now, IMO.

**Comment by Nekmo** [comment]
Ok, I'll use another Telegram library to my project, thanks.


Un cordial saludo:
-- Nekmo.

Sitio web: http://nekmo.com
Dirección de contacto: contacto@nekmo.com
XMPP/Jabber: contacto@nekmo.com
Google+: Nekmo Com

2016-04-25 12:42 GMT+02:00 Leandro Toledo <notifications@github.com>:

**Comment by rahiel** [comment]
Dear @Nekmo, we've recently released version 4.1 of the library, and on your advice we've implemented snake_case equivalents for all `Bot` class methods, so `telegram.Bot.sendMessage` is the same as `telegram.Bot.send_message`. All other methods are now also snake_case.

Give our library another try if you like :smile:

**Comment by Nekmo** [comment]
Thanks, I'll give it another try at your library. :)
