### ISSUE TITLE
[QUESTION] payment api doesn't work with Apple Pay (Stripe)

### ISSUE THREAD

**Issue by lukasresch** [python-telegram-bot/python-telegram-bot#2554]
### Issue I am facing
Hi
I use the telegram payments api with stripe and it works fine when entering the card manually,
but I get an 'Apple Pay is not available in "Telegram"' error with Apple Pay. I asked a couple of people and
they all have the same error. It occurs with both test and live token. I and all people I asked are located in Austria
if that makes any difference.

Same thing happens with https://t.me/ShopBot

### Traceback to the issue
- get stripe toke with botfather + stripe bot
- payment implementation as in examples
- pay and choose Apple Pay as payment method
- error

![error](https://user-images.githubusercontent.com/11249796/121036613-24784c80-c7af-11eb-8427-b900703b5d95.jpg)

**Comment by lukasresch** [comment]
Ok, thank you!

How do you know what I'm selling ? 😂😂

**Comment by Poolitzer** [comment]
I do not, that's why I wrote maybe. It is just way easier to sell digital goods (no refunds, no shipping), so that is why I included that note.

**Comment by lukasresch** [comment]
Ahh.. nah, that's the example bot from telegram.

But I indeed would like to sell digital goods, isn't there a workaround ?

**Comment by Poolitzer** [comment]
> isn't there a workaround ?

To what? To using apple pay? This is a client/telegram issue, you have to contact botsupport, they will forward it internally. Then they have to fix their app or the servers, whatever is the issue, and then this will work again,

To not being allowed to sell digital goods to iOS users? There is no workaround, that is a simple rule. You are expected to ask your user that they are definitely not on an iOS device when buying your good. Like you have to be a certain age (and have to tick that box or enter your age or whatever) to... play certain games or watch certain...... movies.
