### ISSUE TITLE
Get chat_id by username method

### ISSUE THREAD

**Issue by Nekmo** [python-telegram-bot/python-telegram-bot#256]
I think it's important to implement a method for get the chat_id by name.

Indeed, I think it should already be with the methods sendMessage, sendPhoto...

I know that there is no easy method for it. The only solution is to look at getUpdates. But if a new version of Telegram allows to get the chat_id, you only have to replace the function.

**Comment by leandrotoledo** [comment]
Hi @Nekmo, like you stated, Telegram doesn't provide such method yet. Currently you can only pass '@channelnames' as `chat_id`. I hope one day it gets available for all existing chat types. 

If it helps, you can send/forward a message to @userinfobot to get the `chat_id`.

Cheers.

**Comment by jh0ker** [comment]
You can also just pass a user ID as chat id to send a message to the private chat with the user. 

@leandrotoledo I think you can only get the user ID from userinfobot, not chat id

**Comment by leandrotoledo** [comment]
Ops, thanks @jh0ker.

**Comment by IrCodeXe** [comment]
how to find a person with chat id ??
@jh0ker

**Comment by jh0ker** [comment]
Try the `getChat` method. If you have further question, please ask in the Telegram group
