### ISSUE TITLE
[QUESTION] How to get all pinned messages?

### ISSUE THREAD

**Issue by d33tah** [python-telegram-bot/python-telegram-bot#2569]
### Issue I am facing

I'd like to query for all pinned messages in a given chat. I only know how to retrieve the latest one, is there a way to get all of them?

### Traceback to the issue

n/a

### Related part of your code

n/a

**Comment by d33tah** [comment]
@Poolitzer Thanks for the quick response! Is it because there's no support from the API perspective, or because it's currently not implemented?

**Comment by Poolitzer** [comment]
No the issue is with the API. We have fully included the latest update.
