### ISSUE TITLE
How can I keep the bot working after internet disconnections?

### ISSUE THREAD

**Issue by OzanKurt** [python-telegram-bot/python-telegram-bot#2584]
My internet is not stable, sometimes my pc gets disconnected from internet and telegram errors out.

Is there a way for me to restart it after re-connection or keep the bot working somehow?

My code is extremely simple;

I have an child object of `threading.Thread`, in the `__init__` method I simply run `init_telegram`

```python
    def init_telegram(self):
        self.updater = Updater(config['TELEGRAM_TOKEN'])
        self.dispatcher = self.updater.dispatcher

        self.dispatcher.add_handler(MessageHandler(Filters.text & ~Filters.command, self.captcha_message_handler))

        self.dispatcher.add_handler(CommandHandler("start", self.start_command_handler))
        self.dispatcher.add_handler(CommandHandler("stop", self.stop_command_handler))
        self.dispatcher.add_handler(CommandHandler("reload", self.reload_command_handler))
        self.dispatcher.add_handler(CommandHandler("command", self.custom_command_handler))

        self.updater.start_polling(drop_pending_updates=True)
```

**Comment by Poolitzer** [comment]
hey, that would be possible with a lot of ways. one would be to define a separate function for the start_polling call and let it call itself with a try except block :D
