### ISSUE TITLE
[Question] bot.send_message got error

### ISSUE THREAD

**Issue by Phuong39** [python-telegram-bot/python-telegram-bot#2585]
### Steps to reproduce
1.
bot.send_message(chat_id=user_id, text="xxxxxxxxxx")
if user_id have formart 455xxxxxx it working perfect!
but if have format 1780xxxxxx it error
```python
  File "..\lib\site-packages\telegram\bot.py", line 332, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "..\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "..\lib\site-packages\telegram\utils\request.py", line 356, in post
    result = self._request_wrapper(
  File "..\lib\site-packages\telegram\utils\request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Chat not found

```
2.

3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by Bibo-Joshi** [comment]
You left out the most important part of the traceback😉Please tell us, which error message the `BadRequest` error shows.
