### ISSUE TITLE
PEP8 and YAPF autoformatter

### ISSUE THREAD

**Issue by leandrotoledo** [python-telegram-bot/python-telegram-bot#259]
- [x] Rename all methods in codebase but the ones from Telegram Bot API to snake_case.
- [x] Comply with [YAPF](https://github.com/google/yapf) formatter.

- Added to milestone: v5.0

**Comment by leandrotoledo** [comment]
One issue found with YAPF was reported on google/yapf#252

**Comment by leandrotoledo** [comment]
@rahiel maybe we should rename function names and create aliases for the 'current' functions names instead, would be easier to get rid of it later on.

**Comment by rahiel** [comment]
> @rahiel maybe we should rename function names and create aliases for the 'current' functions names instead, would be easier to get rid of it later on.

It's already like that, the normal function names are PEP8 and the aliases are the old CamelCase. They are in blocks that can be easily removed, see [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/56b1d4f5cefe08eb829aa258d796c6c021a195ca/telegram/ext/dispatcher.py#L291).

If you mean the aliases in `bot.py`, I thought we were keeping both snake_case and CamelCase for the API?

**Comment by leandrotoledo** [comment]
@rahiel ah, ok, no, you're right
