### ISSUE TITLE
[QUESTION] Passing paramenter to job_queue.run_custom method

### ISSUE THREAD

**Issue by buinguyenhoangtho** [python-telegram-bot/python-telegram-bot#2605]
Hi. I got an simple code, but cannot find a way to pass args :cry: . Simple, i want to print `id=4` every minutes
Same with [this question](https://stackoverflow.com/questions/12412708/passing-parameters-to-apscheduler-handler-function) but in this cases, i want to pass in job_queue.run_custom method
```python
def jobID(id):
    print("Job_ID = ",id)
```
```python
    job_queue.run_custom(jobID,job_kwargs={"trigger" : CronTrigger.from_crontab ( '* * * * *',timezone='Asia/Ho_Chi_Minh')},name="Job ID ",context=None) 
```

**Comment by Bibo-Joshi** [comment]
Please have a look at the tutorial on [`JobQueue`](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-–-JobQueue) as well as the [`timerbot.py`](https://github.com/python-telegram-bot/python-telegram-bot/tree/master/examples#timerbotpy) example. They explain how a job callback should look like and how you can use the `context` parameter of `run_*`.
