### ISSUE TITLE
[BUG] Message.photo is set to an empty list when not provided

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#2606]
### Steps to reproduce
1. Generate a Message object without photo set.

2. Check the photo parameter

### Expected behaviour
.photo should be None

### Actual behaviour
.photo is an empty list

Wrong line: https://github.com/python-telegram-bot/python-telegram-bot/blob/1fdaaac8094c9d76c34c8c8e8c9add16080e75e7/telegram/message.py#L515

**Comment by Poolitzer** [comment]
Technically breaking (I guess?) and we want to do V14 changes now anyway, so on that list it goes

**Comment by nivramam** [comment]
Hi, is this issue still active?

**Comment by Bibo-Joshi** [comment]
Hi @nivramam . IIRC we haven't made a final decision on this, which is why I didn't tag it for hacktoberfest.

The reason why this was implemented in #788 was that e.g. `for photo_size in message.photo` will just always work if `message.photo` is an empty list and `if message.photo` works just as well. But I do see that it doesn't comply with the rest of the implementation.

Personally, I'd vote +0.5 on this, i.e. I'd be in on changing this but also wouldn't complain if it isn't changed.
@Poolitzer you're probablby +1 since you opened the issue? @harshil21 @starry69, what's your opinion?

**Comment by Poolitzer** [comment]
I actually personally really like the argument that `for photo_size in message.photo` works, because it could lessen code complexity. But I dont think many devs will use that. So I will vote a 0.5 as well: Dont care if implemented or not, but am fine if someone wants to taggle it

**Comment by nivramam** [comment]
@Bibo-Joshi Sure, would do. I've just started with contributing and learning on PRs, so a bit scratchy. Would definitely approach if I get stuck in between. As for now,we need to work changes on v14 right?

**Comment by Poolitzer** [comment]
Yes, switch to the v14 branch on your repo, and then base your working branch off of that one

**Comment by nivramam** [comment]
Yeah, I have edited the `telegram/message.py` file

**Comment by nivramam** [comment]
So while I was just reviewing for other changes required on similar lines to the above, in `_replykeyboardmarkup.py` file, I understand we try to append the button rows (provided as parameter) into our class's data - `self.keyboard`. Hence we init it with empty list. But after the appending process is done via the for loop, I wondered if we needed a check to ensure the data has actually been appended and the `self.keyboard` is not equal to [] after the appending. 

This is the snippet I am referring to.. 
![image](https://user-images.githubusercontent.com/36819505/141690840-053a21f7-7a56-4780-a44e-be0a6f60c4fa.png)
Please do give in your inputs, would be helpful for me to understand better.. Thanks a lot

**Comment by Bibo-Joshi** [comment]
Closing for the reasons mentioned in https://github.com/python-telegram-bot/python-telegram-bot/pull/2741#issuecomment-1001740609 and instead putting this on the todo list of #2633
