### ISSUE TITLE
[FEATURE] Add custom pytest mark to conv file

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#2613]
#### Is your feature request related to a problem? Please describe.
I would like to mark new tests I develope with a custom mark, so I can select them with the pytest command. This results in the following error however: `pytest.PytestUnknownMarkWarning: Unknown pytest.mark.XXX- is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html`

#### Describe the solution you'd like
I would like to have a custom mark added to the conf file so I can use it.

#### Describe alternatives you've considered
I can alternatively use -k to select the tests I want but that is more cumbersome in my opinion.

**Comment by Bibo-Joshi** [comment]
I always just use Pycharm IDE-magic for that. When working in a test file, you see those little green arrows left to methods & classes  - click them and it will run the corresponding test.
If you don't want to rely on IDE features, you can also use `pytest -k <pattern>` to run only tests that match the pattern.
I'm not sure if I see a benifit in adding a marker that would have to be removed before merging anyway …

**Comment by Poolitzer** [comment]
> I always use Pycharm Magic

Well, not everyone uses Pycharm. Good to know though :D

> I'm not sure if I see a benifit in adding a marker that would have to be removed before merging anyway

I use it to run the new tests I developed. That is the benefit for me. I remove the marker before committing.
And the whole point of having one custom marker in the config is that I can just use it without having to modify two files (the conf file and the test file).

And I know that k exists, but having a custom marker is less work.

**Comment by Bibo-Joshi** [comment]
mh, okay. well, if it makes developing easier for you, let's do it :)
