### ISSUE TITLE
[QUESTION] Register handler with decorator

### ISSUE THREAD

**Issue by gruvw** [python-telegram-bot/python-telegram-bot#2618]
### Registering handlers
I find the registering of handlers a bit weird and I wanted a _Flaskiest_ way to do it.  
I wrote a simple decorator that registers a function as a command handler:
```python
def commandHandler(func):
    """Registers a function as a command handler."""
    handler = CommandHandler(func.__name__, func)
    dispatcher.add_handler(handler)
    return func
```
It's used like this:
```python
@commandHandler
def start(update, context):
    context.bot.send_message(update.effective_chat.id, "hi")
```
We could also introduce a parameter for the command instead of taking the function name (I always name the function after the command).  
We could also create different decorators for other type of handlers.

What do you think about it and what about including it in the [Code Snippets](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets)

**Comment by Poolitzer** [comment]
I personally don't like it. We removed the async decorator for a reason, they can make it harder to know what actually happens inside the decorator and make it seem more like dark magic.

I am not against including it in the wiki though, however, I would make it use the context arg for the Dispatcher and definitely give it an optional argument to pass the group in.

**Comment by Bibo-Joshi** [comment]
Please see the discussion in #899 for why PTB doesn't offer this option.
If you want to add something to the wiki, I wont stop you, tough ;) I'll go ahead and close.

---

> I would make it use the context arg for the Dispatcher

that can't work since the `context` argument is not available at the time the decorator is executed.
