### ISSUE TITLE
replace Bot's @message decorators with explicit context creation/modification

### ISSUE THREAD

**Issue by tsnoam** [python-telegram-bot/python-telegram-bot#262]
this is following to a conversation in the dev group.
in a nutshell:

replace:

```
@message
def restMethod():
    ...
```

with:

```
def restMethod():
    ctx = pre_stuff()
    ....
```

advantages:
- more visible to users
- easier to debug (nicer looking stack traces)

**Comment by leandrotoledo** [comment]
I've added it to Milestone v5.0, but we can probably release it earlier.

**Comment by tsnoam** [comment]
We decided to keep the decorators.
