### ISSUE TITLE
[How to reply only keyboard makeup without text?]

### ISSUE THREAD

**Issue by gehaoyu-cn** [python-telegram-bot/python-telegram-bot#2626]
### Issue I am facing
I want to reply keyboard makeup only but I cant find that reply function

**Comment by Poolitzer** [comment]
Hey, that's not possible.

**Comment by gehaoyu-cn** [comment]
> Hey, that's not possible.

Thank you for your answer. Or is there any solution that makes my text invisible? I want to transform information only with keyboard, like a loading processing button.

**Comment by Bibo-Joshi** [comment]
no. If you want to send a `ReplyKeyboardMarkup`, you'll have to send it along with a message. The closest you could get is delete the message right after sending it.
