### ISSUE TITLE
[BUG + REFACTOR] Change behavior of `JobQueue.run_monthly`

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2627]
### Steps to reproduce
1. `job_queue.run_monthly(day=30, day_is_strict=False)`

### Expected behaviour
Runs on 30th day of each month excluding Feb + on Feb 28th/29th

### Actual behaviour
Runs on 30th *and* 31st day of each month excluding Feb + on Feb 28th/29th

This happens because I didn't pay enough attention when writing this:

https://github.com/python-telegram-bot/python-telegram-bot/blob/0c5085022ceaa854baf267b9dd82e0010ec7e4c8/telegram/ext/jobqueue.py#L364-L384

However, the use case of `day_is_strict` is mainly "run on the last day of the month". I therefore suggest to just drop the parameter and instead allow to pass `day='last'` or `day=-1` (I like this one better) to indicate that you want to run the job on the last day of the month.
The use case described above can still be achieved with `run_custom`.

**Comment by iota-008** [comment]
@Bibo-Joshi can i work on this  issue?

**Comment by iota-008** [comment]
> Hi, sure, you're welcome to! just make sure to base your branch on the v14 branch (and the PR should also go to there), as we're working towards a majorly breaking release :)

I have done the changes how can I test it?

**Comment by Bibo-Joshi** [comment]
We use `pytest` for our unit tests. Please have a look at the [contribution guide](https://github.com/python-telegram-bot/python-telegram-bot/blob/v14/.github/CONTRIBUTING.rst) for details. Admittedly, unit tests are not always easy, so feel free to ping me if you get stuck - probably open a PR with your changes first though ;)

**Comment by iota-008** [comment]
(on branch v14) i forked -> cloned -> changes -> pytest -> pre-commit ->  added files -> commit -> pushed ( and it says every thing is upto date)
how to solve this?

**Comment by Poolitzer** [comment]
It doesn't look like the commit actually commited. Maybe run `git log -1`?

**Comment by iota-008** [comment]
> It doesn't look like the commit actually commited. Maybe run `git log -1`?

yes, it's showing your commit but is that

**Comment by Bibo-Joshi** [comment]
If it doesn't show your commit, then you haven't commited ;) maye double check the contribution guide and carefully read what's printed in the console on each of the steps you make. e.g. when you tried to commit, you may have overlooked a error message that git showed you. running `git status` can also be useful.

**Comment by iota-008** [comment]
I am getting 3 assertion error's on pytest in test_schedule_removal, test_in_updater,  in which I haven't changed anything.

**Comment by Poolitzer** [comment]
Thats alright, job queue tests are very time sensitive. As long as they run on the CI, nothing to worry about. Pytest isn't part of the pre-commit hooks though and shouldn't stop your commit from going through

**Comment by iota-008** [comment]
getting these errors now :(
telegram\passport\credentials.py:192: error: Item "Ed25519PrivateKey" of "Union[Ed25519PrivateKey, Ed448PrivateKey, RSAPrivateKey, DSAPrivateKey, EllipticCurvePrivateKey]" has no attribute "decrypt"  [union-attr]
telegram\passport\credentials.py:192: error: Item "Ed448PrivateKey" of "Union[Ed25519PrivateKey, Ed448PrivateKey, RSAPrivateKey, DSAPrivateKey, EllipticCurvePrivateKey]" has no attribute "decrypt"  [union-attr]
telegram\passport\credentials.py:192: error: Item "DSAPrivateKey" of "Union[Ed25519PrivateKey, Ed448PrivateKey, RSAPrivateKey, DSAPrivateKey, EllipticCurvePrivateKey]" has no attribute "decrypt"  [union-attr]
telegram\passport\credentials.py:192: error: Item "EllipticCurvePrivateKey" of "Union[Ed25519PrivateKey, Ed448PrivateKey, RSAPrivateKey, DSAPrivateKey, EllipticCurvePrivateKey]" has 
no attribute "decrypt"  [union-attr]
telegram\passport\credentials.py:192: error: Incompatible types in assignment (expression has type "Union[Any, bytes]", variable has type "None")  [assignment]
Found 5 errors in 1 file (checked 147 source files)

**Comment by Bibo-Joshi** [comment]
for new you can commit with `get commit ... --no-verify`. this skips the pre-commit checks. they run again in the CI anyway, so we'll see if there are any issues

**Comment by iota-008** [comment]
i have made a pull request.

**Comment by iota-008** [comment]
i have made a pull request

**Comment by Bibo-Joshi** [comment]
I saw and I will review it when I have time for it 😉

**Comment by harshil21** [comment]
GitHub's closing from PR comment feature is broken, so closing manually
