### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HFKunz** [python-telegram-bot/python-telegram-bot#2630]
Hi

I've created a bot with this requirements:

APScheduler==3.6.3
cachetools==4.2.2
certifi==2021.5.30
charset-normalizer==2.0.3
cycler==0.10.0
Cython==0.29.24
decorator==4.4.2
emoji==1.2.0
flatbuffers==2.0
future==0.18.2
glpi==0.4.0
googlemaps==4.5.3
idna==3.2
imageio==2.9.0
kiwisolver==1.3.1
matplotlib==3.4.2
networkx==2.5.1
NudeNet==2.0.9
numpy==1.21.0
onnxruntime==1.8.1
opencv-python==4.5.3.56
opencv-python-headless==4.5.3.56
Pillow==8.3.1
progressbar2==3.53.1
protobuf==3.17.3
psycopg2==2.9.1
pydload==1.0.9
pyparsing==2.4.7
python-dateutil==2.8.2
python-dotenv==0.18.0
python-telegram-bot==13.7
python-utils==2.5.6
pytz==2021.1
PyWavelets==1.1.1
pyzbar==0.1.8
requests==2.26.0
scikit-image==0.18.2
scipy==1.7.0
six==1.16.0
tifffile==2021.7.2
tornado==6.1
tzlocal==2.1
urllib3==1.26.6

Linux Ubuntu 21.04. ( only for this , nothing more installed on it)
Python 3.9.5

It start OK, but, when execute a "button", the exception occur:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/dados/telegram_bot/gt_escritorio_bot/src/core.py", line 1018, in executeaacaomenu
    query.answer()
  File "/usr/local/lib/python3.9/dist-packages/telegram/callbackquery.py", line 166, in answer
    return self.bot.answer_callback_query(
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 2514, in answer_callback_query
    result = self._post('answerCallbackQuery', data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 356, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 265, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError [SSL: SHUTDOWN_WHILE_IN_INIT] shutdown while in init (_ssl.c:2633)

Same code running on Win10, same version of Python, does not occurr the error.

I appreciate any help.

Tks

**Comment by Bibo-Joshi** [comment]
@Poolitzer urllib3 being installed doesn't necessarily mean that it's uaed by PTB, right?

Anyway, it's and SSL related exception. To me This sound more like there is something wrong with the network configuration.

**Comment by Bibo-Joshi** [comment]
no, we do something like

```
try:
    from telegram.vendor.ptb_urllib3 …
except ImportError:
     from urllib3 import …
```

Anyway @HFKunz please provide the thoutput of `python -m telegram` like the template asked you to

**Comment by HFKunz** [comment]
Tks for your replies.

python -m telegram:

python-telegram-bot 13.7
Bot API 5.3
certifi 2021.05.30
Python 3.9.5 (default, May 11 2021, 08:20:37)  [GCC 10.3.0]


I don't import "urllib3", and anyone of "util*" make it too.


Main import:

import telegram
import logging
import random
import psycopg2
import urllib.parse
import re
import cv2
import os
import datetime
import json
import base64
import glob
import sys
import util.glpi_api
import util.util

from util.glpi_api import GLPI
from nudenet import NudeClassifier, NudeDetector
from pyzbar.pyzbar import decode
from typing import Union, List
from telegram import InlineKeyboardButton
from telegram.ext import CommandHandler, Filters, MessageHandler, Updater ,CallbackQueryHandler
from datetime import datetime, timedelta


Util imports:

from nudenet import NudeClassifier, NudeDetector
from pyzbar.pyzbar import decode
from pyzbar.pyzbar import ZBarSymbol
from typing import Union, List
from PIL import Image
import logging
import random
import urllib.parse
import re
import cv2
import os
import datetime
import json
import psycopg2
from psycopg2.extras import DictCursor 



Anyway, i created a new main file with the same imports of original, but only basic "def start", and it worked fine. Well, i'll continue putting pieces of code in the new file to see where the error begin...programmer life!!!

Tks again for your attentions.

**Comment by Poolitzer** [comment]
If you already fixed this in a different snippet and are on the hunt on your own now, great. I will close the issue then. If you found the code giving you trouble, feel free to comment on this one or open a new one with that part and we will try and help you further :)
