### ISSUE TITLE
Update Class - Can only get 256 characters from an Inline query

### ISSUE THREAD

**Issue by Jertlok** [python-telegram-bot/python-telegram-bot#264]
Hello there, update.inline_query.query gives me only 256 characters instead the 4096 that can be found at https://core.telegram.org/bots/api#inputtextmessagecontent

What is happened?

**Comment by leandrotoledo** [comment]
Hi @Jertlok! Can you confirm if this happen with all message_text you receive or just some of them, randomly?

Thanks.

**Comment by Jertlok** [comment]
@leandrotoledo I tested it with many entries, it always cuts at 256 characters.
I even tried with @bold and happens the same, is it a Telegram issue? Or just our client issues?

A normal message is still normally handled. Thanks for your reply.

**Comment by jh0ker** [comment]
You are looking at `InputTextMessageContent`, which is something different than an `InlineQuery`. `InputTextMessageContent` is something you can add to an inline result and will be sent as a text message when the user chooses that result.

**Comment by Jertlok** [comment]
My mistake, thanks for your reply. There's nothing we can do then.

Have a nice day.
