### ISSUE TITLE
[How to run two different bots at the same time?]

### ISSUE THREAD

**Issue by gehaoyu-cn** [python-telegram-bot/python-telegram-bot#2645]
I have two bots and they have different apikey, I tried to run them at the same time but I met conflict error:telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

I ran them in two panel of one tmux session, How can I fix that?

**Comment by Bibo-Joshi** [comment]
This means that there are two processes that try to fetch updates with the same bot token. Double check that your two scripts use different tokens. If you can't find the confliciting processes, try to restart your machine and if that doesn't help, revoke the bot token with botfather. This will make the processes (that run with the current token) fail.
