### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by itJunky** [python-telegram-bot/python-telegram-bot#2654]
### Issue I am facing
Please describe the issue here in as much detail as possible. Can't set permissons to user.

### Traceback to the issue
```
    bot.promote_chat_member(msg.chat.id, msg.from_user.id, [is_anonymous==True])
NameError: name 'is_anonymous' is not defined

```

### Related part of your code
```python
bot.promote_chat_member(msg.chat.id, msg.from_user.id, [is_anonymous==True])
```

How can i set right permissions to user?

**Comment by Bibo-Joshi** [comment]
Hi. Please have a look at the docs of [`Bot.promote_chat_member`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.promote_chat_member). `is_anynomous` is an ordinary optional parameter of that method, you you can pass it as keyword argument as usual ;)

**Comment by itJunky** [comment]
Yes, thanks. Firstly i try it right. But at old version of library =( And it shows me error and confuse me. After update lib i have no error in this part, but have another error:

TeleBot: "A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: RIGHT_FORBIDDEN"

**Comment by Bibo-Joshi** [comment]
Please note that this is the repository of the `python-telegram-bot` library and not of `pyTelegramBotAPI`, which is over at https://github.com/eternnoir/pyTelegramBotAPI.

Anyway, the error just tells you that your bot doesn't have enough permissions to promote the member.

**Comment by itJunky** [comment]
Wow... sorry =( its same names =(
