### ISSUE TITLE
Reduce some spam?

### ISSUE THREAD

**Issue by springjools** [python-telegram-bot/python-telegram-bot#266]
Is it possible to reduce some of the spamming in the log? Basically my log is filled up with lines like:
04-26 10:10 telegram.ext.jobqueue DEBUG    Next task isn't due yet. Finished!
04-26 10:10 telegram.ext.jobqueue DEBUG    Ticking jobs with t=1461654610.501873
04-26 10:10 telegram.ext.jobqueue DEBUG    Peeked at regularUpdate with t=1461654617.534923

Are these really necessary? Can't these debugging lines be removed from the production version once it is found that the product is working?

PS: Tried to add some filters to the logging handler in python but it's not very reliable...

**Comment by leandrotoledo** [comment]
Hi @springjools, we could certainly improve that, any suggestions on what you'd consider relevant DEBUG information for this library?

Thanks!

**Comment by leandrotoledo** [comment]
@springjools Friendly ping! :smile:

**Comment by springjools** [comment]
Sorry for the delay. I can only tell you my opinion, but I'm no professional Python programmer, and I have noticed that many Python packages like to use a lot of debug prints (for example the requests library does this).

Do you want a pull request? I could make the changes I think are sensible, and let you decide right with the code.

But otherwise I think maybe it's enough to just remove the debug prints from entering and leaving each process.

**Comment by leandrotoledo** [comment]
@springjools sure, if you got the cycles for a PR the @python-telegram-bot/developers can review if the changes can be merged into the codebase.

**Comment by leandrotoledo** [comment]
PR #299 has been submitted for review.

**Comment by leandrotoledo** [comment]
Marking as obsolete.
