### ISSUE TITLE
Use pathlib weherever possible

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2665]
[Object based file handling](https://docs.python.org/3/library/pathlib.html) makes a lot of stuff easier and we have alread started integrating it into PTB by accepting `pathlib.Path` objects as file input in case of local bot api servers.

We should try to use it wherever possible throughout the examples & lib, arguably even tests. This includes, but is not limited to, every `open(...)`  .

edit: we should probably also check the wiki

**Comment by eldbud** [comment]
hey! i'm tackling this issue at the moment, and was wondering - should File.download() (file.py) return a Path object instead of str, in cases where the path is returned from this method?

**Comment by Bibo-Joshi** [comment]
Hi - happy to hear that you want to tackle this :) `File.download` returning a `pathlib.Path` object sounds like a good idea! We should also accept both `str` and `pathlib.Path` for the `custom_path` argument, then.
Please be sure to base a PR on the v14 branch, as the change to `File.download` would be breaking.

BTW, regarding the hacktoberfest label: AFAIK only PRs opened in octobar are eligible for hacktoberfest, so if you're interesetd in that you should probably wait until next Friday with opening a PR :)

**Comment by eldbud** [comment]
Happy to try and help :)
Regarding the PR base - i followed the "contribute" instructions detailed in this repo, does that mean i am in-line with the v14 branch?
Also, i want to make sure - will returning ```Path``` object instead of ```str``` from ```File.download() ``` be backward compatible with callers of this method?

**Comment by Bibo-Joshi** [comment]
> Regarding the PR base - i followed the "contribute" instructions detailed in this repo, does that mean i am in-line with the v14 branch?

Not 100% … as we're currently working towards a major release, which will also break backward compatibility big time, we're doing that on a branch separate from `master`. So in [this step](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/.github/CONTRIBUTING.rst#instructions-for-making-a-code-change) you'll have to replac

```shell
$ git fetch upstream
$ git checkout master
$ git merge upstream/master
$ git checkout -b your-branch-name
```
 with

```shell
$ git fetch upstream
$ git checkout v14
$ git merge upstream/v14
$ git checkout -b your-branch-name
```
If you already have created a branch, you can do 

```shell
$ git fetch upstream
$ git checkout v14
$ git merge upstream/v14
$ git checkout your-branch-name
$ git merge v14
```

to merge the `v14` branch into yours.

> Also, i want to make sure - will returning `Path` object instead of `str` from `File.download()` be backward compatible with callers of this method?

No, but that's fine because. We have decided to just make everything breaking for v14 🙆‍♂️

**Comment by Bibo-Joshi** [comment]
I just fiddled with `test_slots.py` for another PR before realising that I actually don't need to. Anyway, a pathlib replacement for

https://github.com/python-telegram-bot/python-telegram-bot/blob/c3e3bb77e507f1997c1eb66f81265da4da12b68b/tests/test_slots.py#L41-L49

could be

```python
    tg_root = pathlib.Path(__file__).parent.parent.resolve()
    tg_vendor = tg_root / 'vendor'
    tg_paths = [p for p in tg_root.rglob('telegram/*.py') if p != tg_vendor and p.is_file()]

    for path in tg_paths:
        split_path = path.parts
```

Maybe this saves you a few minutes :D

**Comment by eldbud** [comment]
i think the merge from v14 didn't go very well, i am getting this in base.py:

>   from telegram.utils.deprecate import set_new_attribute_deprecated
E   ModuleNotFoundError: No module named 'telegram.utils.deprecate'


how can i resolve this? i didn't leave any files that were deleted in v14 when merging from it, so i don't know how this occurred, can you maybe help?

**Comment by eldbud** [comment]
> I just fiddled with `test_slots.py` for another PR before realising that I actually don't need to. Anyway, a pathlib replacement for
> 
> https://github.com/python-telegram-bot/python-telegram-bot/blob/c3e3bb77e507f1997c1eb66f81265da4da12b68b/tests/test_slots.py#L41-L49
> 
> could be
> 
> ```python
>     tg_root = pathlib.Path(__file__).parent.parent.resolve()
>     tg_vendor = tg_root / 'vendor'
>     tg_paths = [p for p in tg_root.rglob('telegram/*.py') if p != tg_vendor and p.is_file()]
> 
>     for path in tg_paths:
>         split_path = path.parts
> ```
> 
> Maybe this saves you a few minutes :D

so i used your code and it indroduced this error:
```
from telegram.utils.types import JSONDict
>   from telegram.utils.deprecate import set_new_attribute_deprecated
E   ModuleNotFoundError: No module named 'telegram.utils.deprecate'
```

But you see, the thing is, i don't think the problem is your code. i think the problem is existing code.
from what i've seen, it seems that only the first line of this test is actually being ran, and that is because that line returns an empty lists, which means the rest of the test is never executed.

```python
tg_paths = [p for p in iglob("telegram/**/*.py", recursive=True) if 'vendor' not in p]
```
returns an empty list.

So the test fails for me. please advise on how to handle this.

**Comment by Bibo-Joshi** [comment]
Hi. `set_new_attribute_deprecated` has been removed on the v14 branch already and the module `telegram.utils.deprecate` has basically been renamed to `telegram.utils.warnings`.
Please double check that you merged v14 correctly. You can e.g. view the diff between your branch and v14 (either directly via git in the command line or push you branch to github and draft a PR - you'll see the diff before submitting the PR) and check for any changes that you didn't actually make. Those are likely to be merging errors.

**Comment by eldbud** [comment]
but those imports are inside the telegram external library - it is no code i can even change....
What i am saying is that from what i checked (printed ```tg_paths``` to see the values) the the original code of the slots test yields an empty list - so of course there are no import problems. am i wrong about that?

**Comment by eldbud** [comment]
ok so i have managed to pass that hurdle.

Now i am encountering something strange - when running ```pytest tests``` i get 3 failures, screenshots attached. 
When i run these tests by themselves not via pytest cli, but via the IDE's "play" button, they all pass.

In addition, i don't think those tests relate to anything i touched in the code base.
Any idea how to resolve this?
![2021-09-26_22h37_43](https://user-images.githubusercontent.com/76731410/134821834-0a7ba68c-7499-4a7a-83cb-68d45ec6df2d.png)
![2021-09-26_22h38_23](https://user-images.githubusercontent.com/76731410/134821837-2ceb20d0-86ff-4384-b301-81957717d715.png)
![2021-09-26_22h38_53](https://user-images.githubusercontent.com/76731410/134821838-44046465-b79b-4d3c-b12b-1db0ad088e46.png)

**Comment by Bibo-Joshi** [comment]
`JobQueue` tests are sometimes flaky, because timing things are not always perfect on a computer. You can try to sychronize your machines timezone before running the tests, but otherwise you can just ignore those. We'll run tests in the CI when you PR, anyway ;)

The ConversationHandler test tells me that you still have code in your branch that has been removed in v14 already: [this](https://github.com/python-telegram-bot/python-telegram-bot/blob/v14/tests/test_conversationhandler.py#L97-L101) is the test on the v14-branch.
If you're having troubles with mergin v14 into your branch, maybe it's easier to make a new branch from v14 and apply your changes to that branch. You e.g. [cherry-pick](https://git-scm.com/docs/git-cherry-pick) your commits from your corrent branch - pycharm also let's you cherry pick commits by right-clicking them in the git log.

**Comment by eldbud** [comment]
if only i had known i should base my branch on the v14 branch... i think i now spent more time with merge issues than actual work.

So i did everything as instructed, all possibilities. last one was the cherry pick which seemed to go fine.
Then i discovered that for some reason in my branch there is a urllib3 package which does not exist in the v14 branch, even though this was the base branch, go figure, but ok. So i deleted the urllib3 package, and when i tried to run tests, it failed because the urllib3 package is missing.... so i undeleted the package, and now when i try to commit it regards all those files in there as new files being comitted, and there's TONS of commit errors. in the hundreds, maybe even more.

What do i do now? what is this urllib3 phantom package? is it part of the repo? how do i commit now, with the hundreds of commit errors that exist in this package? please advise.

**Comment by Bibo-Joshi** [comment]
Please see the last bullet point of point 5 (Address review comments until …) on [this section] of the contribution guide. We vendor the urllib3 library because we applied a patch that wasn't accepted by the maintainers of the urllib3 library. and it for sure does exist in the [v14 branch](https://github.com/python-telegram-bot/python-telegram-bot/tree/v14/telegram/vendor) 😉 

Yes, git can be tricky. If your branch looks okayish to you, you can just PR. In a PR we'll see if it contains any changes that should not be there and can correct that ;)

**Comment by eldbud** [comment]
i think all is ok now :)
i'll use your suggestion and wait to hacktoberfest for submitting the PR, if it is ok by you

**Comment by eldbud** [comment]
is there another task at hand i could maybe try and do?

**Comment by Bibo-Joshi** [comment]
See [here](https://github.com/search?q=org%3Apython-telegram-bot+label%3Ahacktoberfest+is%3Aissue+is%3Aopen). but let's keep this thread about the pathlib changes ;)

**Comment by ThisIsMatin** [comment]
Hi @Bibo-Joshi , Can I work for the `tests` folder to use pathlib, please? (If no one else is working on this section)

**Comment by Poolitzer** [comment]
Hey, they are already covered in the linked PR.

**Comment by ThisIsMatin** [comment]
Well @Poolitzer , what about the `telegram/ext/picklepersistence.py`? Can I work on this?

**Comment by Poolitzer** [comment]
If you check out the linked PR, you can see that they also already covered this. In fact, if you do find a file which has use for Pathlib but isn't covered by the PR, I would encourage you to comment in the PR and tell the author about it rather then splitting up tackling this issue into several PRs.

If you want to make your own changes to the code, there are other issues you can have a look at.
