### ISSUE TITLE
Convert issue & PR templates to forms (already taken)

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2666]
See [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms). Examples can be found e.g. [here](https://github.com/pypa/pypi-support/issues/new/choose).

A PR should basically convert the existing templates into the form layout.

**Comment by abxhr** [comment]
I would love to work on this! 🚀

**Comment by Bibo-Joshi** [comment]
Sure, you're welcome to :) harshil already assigned you to this issue.

**Comment by abxhr** [comment]
This PR includes the forms for all the three Issue templates. 

I'm not sure if the forms work along with Pull Request Templates as well. Let me know if it is possible, so that I could add a commit to the PR. :zap:

**Comment by fenilgandhi** [comment]
For anyone, who wanders here after me, looking for issues to work on, this one is already resolved.

**Comment by Poolitzer** [comment]
sorry, I will close it so it doesn't appear in search

**Comment by Bibo-Joshi** [comment]
Reopening because #2669 was not merged due to hacktoberfest-thingies. @abxhr could you open a new PR including the changes requested in #2669?

**Comment by abxhr** [comment]
@Bibo-Joshi I have created a new PR for the same 🚀
