### ISSUE TITLE
invalid filter

### ISSUE THREAD

**Issue by Gurzo** [python-telegram-bot/python-telegram-bot#267]
update from 4.0rc1 to 4.0.1 causes this error:

`dp.addHandler(MessageHandler([filters.TEXT], echo))`

>   File "/usr/local/lib/python2.7/dist-packages/telegram/ext/dispatcher.py", line 179, in processUpdate
>     if handler.checkUpdate(update):
>   File "/usr/local/lib/python2.7/dist-packages/telegram/ext/messagehandler.py", line 122, in checkUpdate
>     res = any(func(update) for func in self.filters)
>   File "/usr/local/lib/python2.7/dist-packages/telegram/ext/messagehandler.py", line 122, in <genexpr>
>     res = any(func(update) for func in self.filters)
> TypeError: 'int' object is not callable

in Transition guide to Version 4.0 add something like:

> replace filters.TEXT with Filters.text

**Comment by tsnoam** [comment]
@Gurzo Hi, we had a small change in the syntax when switching from rc to release regarding filters.
please check the transition guide again.
however, TL;DR :

from telegram.ext import Filters

Filters.Text

is the name of the filter

**Comment by Gurzo** [comment]
just updated my issue and just seen your reply, thanks

**Comment by tsnoam** [comment]
@Gurzo have you managed to work it out? can we close the issue?

**Comment by Gurzo** [comment]
yeah, but it's 

> Filters.text

not

> Filters.Text

**Comment by tsnoam** [comment]
@Gurzo he he.  should have read the transition guide (I wrote) again.
thanks for your patience 🙂

**Comment by Gurzo** [comment]
@tsnoam hehe, i have read http://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.messagehandler.html?highlight=filters#telegram.ext.messagehandler.Filters

PS: if you use Pocket (read it later service), give a try at my bot @grzbot (more info @Gurzo)
