### ISSUE TITLE
[QUESTION] Best practice to get the matched regex pattern in multiple ORed filters?

### ISSUE THREAD

**Issue by runapp** [python-telegram-bot/python-telegram-bot#2670]
Hi, recently I found that in `MergedFilter`, ORed data filters' results are only kept once even if only the last filter in the OR sequence matches. e.g. if I write something like this:

```python
dispatcher.add_handler(MessageHandler(
    Filters.regex(r'say (\S+)') |
    Filters.regex(r'speaker (\S+)') |
    Filters.audio & Filters.caption_regex(r'(\S+)') |
    Filters.photo & Filters.caption_regex(r'(\S+)'),
    call_speech_related_apis
))
```

However, when I received a message, I have no idea which regex is actually matched. In each of the three conditions, `msg.matches` is always of length 1. Of course I can always do some (kind of redundant) checks in `call_speech_related_apis`, but I'd prefer avoiding that. Before checking the implementation, I was thinking of `MergedFilter` leaving a `None` in `context.matches` for non-short-circuited filters, and then I can check it by using `len` or indices.

I know that the first two patterns can be merged, and that's why the 4th photo filter exists. In another word, I believe there's always a chance that choosing separated regex filters would bring better code structure or something.

**Comment by Bibo-Joshi** [comment]
Hi. I'd first like to point out that `or` and `and` are not even supported for filters. You must use `|` and `&` instead. See this [wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-–-Advanced-Filters). Also the [docs](http://localhost:63342/python-telegram-bot/docs/build/html/telegram.ext.filters.html#telegram.ext.filters.BaseFilter) explicitly have a note about the short circuiting logic 😉

Personally I'd say that if it's important to you which filter was activated, then you might as well split handler up into multiple handlers … the parts of the callback that don't depend on the regex can still be extracted to an external function that you can call.

**Comment by runapp** [comment]
@Bibo-Joshi Sorry the code was not checked. When I return to my real code I instantly found that I should use `|` and `&`.

For short-circuiting logic, I mean when only the 4th line matches (`Filters.photo & Filters.caption_regex(r'(\S+)')`), what's the best practice to get the number 4. I know that if any of the first 3 filter matches, `Filters.photo` and `Filters.caption_regex(r'(\S+)')` won't even be executed.

Also I have thought of splitting that into multiple handlers. But meanwhile it will bring tons of extra codes if I still want to share some common logic among them (such as api calling or network stuff). To me, it's still not the ultimate satisfying practice.

**Comment by Bibo-Joshi** [comment]
> For short-circuiting logic, I mean when only the 4th line matches (`Filters.photo & Filters.caption_regex(r'(\S+)')`), what's the best practice to get the number 4. I know that if any of the first 3 filter matches, `Filters.photo` and `Filters.caption_regex(r'(\S+)')` won't even be executed.

You know that the last regex can only be executed, if `update.message.photo` is present. BTW I strongly suggest to use braces to make the merging more readible. Also you can shorten the expression to

```python
(Filters.regex(r'say (\S+)') | Filters.regex(r'speaker (\S+)')) |  ((Filters.audio | Filters.photo) & Filters.caption_regex(r'(\S+)'))
```

> Also I have thought of splitting that into multiple handlers. But meanwhile it will bring tons of extra codes if I still want to share some common logic among them (such as api calling or network stuff). To me, it's still not the ultimate satisfying practice.

Put everything that is "common logic" in a separate function and call that function from wherever you need it

**Comment by runapp** [comment]
Ok, now I think I've considered all possible paradigms. Seems that I have to choose one among them. Thank you for replying.
