### ISSUE TITLE
Is paymentbot.py connecting to Stripe directly or should I implement the connetion?

### ISSUE THREAD

**Issue by PabloRuizCuevas** [python-telegram-bot/python-telegram-bot#2674]
### Issue I am facing

Hi, I’m just trying the **paymentbot.py example**. So far, I followed the guide at official telegram page and the API documentation about payments 2.0, connected with the @botfather and the @teststripe bot and run the bot. The python code seems to work fine with no issues and i got the message that says that **the transfer was successful**.

The test credit card passes the form etc. **_But_**... I’m using stripe as payment provider and I don’t see my test transactions at the stripe portal,  when other test transactions (outside telegram) seems to work and are registered as test payments.  The transaction is said as "successfully" in telegram, but the request **just never reaches Stripe**, in the log of stripe is written:

-your account authorised the telegram application

But not any payment is logged, received or displayed. In addition, if I make a payment through other channels (no telegram) it succeed and log.

-The payment of xxxxxx for x euros has succeeded

Do I need to add an API, a http request, or something else to the example in order to make it work? if so it may be nice to write it as a comment on the bot.

Thanks in advance.

### Question on Stackoverflow

https://stackoverflow.com/questions/69259789/python-telegram-bot-payment-issue-example-paymentbot-py-with-stride-sevicer

**Comment by Bibo-Joshi** [comment]
For completeness: This was also briefly discussed in the user group https://t.me/pythontelegrambotgroup/523628.

But as long as [this handler](https://github.com/python-telegram-bot/python-telegram-bot/blob/c3e3bb77e507f1997c1eb66f81265da4da12b68b/examples/paymentbot.py#L152) triggers, I'd say that everything went okay from the bots side. If other test payments actually show up with your provider, then maybe it's worth to ask @botsupport about this … or maybe try an actualy payment with a small amount.

**Comment by Bibo-Joshi** [comment]
> Ok, thanks, i tried a real transaction and did actually work, I'm sorry I didn't try it before, but i didn't want to burn my own real money. So in "live mode" stripe got the payment and everything worked nice,

Nice 👍 And no worries, would have done the same, I guess …

> It looks like in "test mode" the telegram bot does not make any request to the stripe page, I think that is a "missing feature" as any other test application will make a test request, but at least is not a big issue. Any case it would be nice to document it, so people don't get as confused as i got. I don't mind to write about this somewhere. (I notified also the bot support)

IMO this is indeeds TGs job to handle and/or document, as the bot API doesn't even do the actual payment on it's own.
