### ISSUE TITLE
How can I pass arguments to a job?

### ISSUE THREAD

**Issue by darthjuanan** [python-telegram-bot/python-telegram-bot#2676]
Hi everybody!

I'm using the run_once method to launch a new callback function, but how can I send parameters to the callback function? Is it possible?

I'm trying to use the job_kwargs, but I don't know how use it correctly. Can anybody help me?

```python
def callback_prueba(context :CallbackContext):
      job_me = context.job
      self.logger.info("Estoy en callback_prueba y el job vale <<{}>>".format(job_me.name))
      self.logger.info("kwargs")
      self.logger.info(kwargs)
      self.logger.info("job_kwargs")
      self.logger.info(job_kwargs)
j = context.job_queue
j.run_once(callback_prueba, when=0, name="prueba", job_kwargs={"numero": 1})
```

It returns:
```python
Update 'None' caused error '__init__() got an unexpected key word argument 'numero''
```

**Comment by Bibo-Joshi** [comment]
Yes, you can use the `context` parameter and access it in the callback as `contex.job.context`. `job_kwargs` are used to fine tune the scheduling of the job via APScheduler library that is used for the `JobQueue`.
the [`timerbot.py`](https://github.com/python-telegram-bot/python-telegram-bot/tree/master/examples#timerbotpy) example showcases fo `context` can be used and it's also explained on the [wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-–-JobQueue) 😉

**Comment by darthjuanan** [comment]
Ok, thanks.

But when I use the dict of job_kwargs as {"numero": 1}, the error is:
Update 'None' caused error '__init__() **got an unexpected key word argument 'numero'**'

So, how can I send parameters (not only the add_job function parameters) to the job?

Thanks!!

**Comment by Bibo-Joshi** [comment]
> Yes, you can use the `context` parameter and access it in the callback as `contex.job.context`.
> the [`timerbot.py`](https://github.com/python-telegram-bot/python-telegram-bot/tree/master/examples#timerbotpy) example showcases ~fo~ how `context` can be used and it's also explained on the [wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-JobQueue) 😉
