### ISSUE TITLE
@log obscured wrapped function's signature in VS Code

### ISSUE THREAD

**Issue by ushuz** [python-telegram-bot/python-telegram-bot#2677]
### Steps to reproduce
<img src=https://user-images.githubusercontent.com/1430856/122634030-b37b4380-d090-11eb-8f64-25b4c666a844.png height=400>

### Expected behaviour
Hover on referenced function, its actual signature pops up

### Actual behaviour
Instead, decorator's signature was prompted, as in screenshot above

### Configuration
**Operating System:** macOS 11.4
**Version of Python, python-telegram-bot & dependencies:** Python 3.6.9 (pyenv), PTB 13.6

---

I first reported this to pylance (https://github.com/microsoft/pylance-release/issues/1470), and was pointed out that `@log()`'s annotation is to blame (https://github.com/microsoft/pylance-release/issues/1470#issuecomment-865288128):

`...` in `func: Callable[..., RT]` throws away parameter definition, and should use `ParamSpec` instead.

https://github.com/python-telegram-bot/python-telegram-bot/blob/105f1ccdb5283f19c97c76a8234f8e61df88ce60/telegram/bot.py#L121-L123

However, `ParamSpec` is pretty new (landed in Python 3.10) thus requires `typing_extension` package with older Python.

**Comment by harshil21** [comment]
Hi, thanks for the issue. As you can see, we've implemented a workaround for this without using `Paramspec` in #2686. If you can test out the changes locally and confirm it's fixed that would be great.

**Comment by ushuz** [comment]
@harshil21 Thank you for the fix. I can confirm #2686 is working for me.
