### ISSUE TITLE
Further clear up imports policy: Private modules

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2680]
#### Is your feature request related to a problem? Please describe.
Currently all the modules like `telegram.{message, chat, user, …}` look like they are public. However, we don't consider them to be part of the public API and they should not be treated as such by the user. The only thing that we guarantee to work is `from telegram import Message, Chat, User, …` and *not* `from telegram.message import Message`.

#### Describe the solution you'd like
Rename all the private modules with a leading underscore, i.e. all files that contain classes that are imported in the `__init__`.
This is in accordance with [PEP8](https://www.python.org/dev/peps/pep-0008/#public-and-internal-interfaces): 

> Even with `__all__` set appropriately, internal interfaces (packages, modules, classes, functions, attributes or other names) should still be prefixed with a single leading underscore.

this should also be done for the `telegram.ext` package except for the module `telegram.ext.filters`. The packages `telegram(.ext).utils` should also be renamed to `telegram(.ext)._utils` and dropped from the documentation - unless this leads to pre-commit complaining about importing private packages. If it does, we'll have to re-evaluate.

#### Additional context
* This can be seen as extension of #2468 
* A PR for #2573 will likely introduce a new module. Depending on which issue get's resolved by a PR first, the other one will have to adapt to the changes.

**Comment by kennethcheo** [comment]
Hi, I would like to work on this!

**Comment by Bibo-Joshi** [comment]
Nice :) I assigned you.

**Comment by kennethcheo** [comment]
mypy's type checking fails when some modules are made private with a leading underscore. 

The modules affected are: `chat, message, user, callbackquery, inline.inlinequery, passport.credentials, passport.passportdata, passport.passportfile, payment.precheckoutquery, payment.shippingquery`. All other modules pass all unit and pre-commit tests.

For example, in a branch where only `message.py` is renamed to `_message.py` (limited to first 10 errors):

![image](https://user-images.githubusercontent.com/42935499/135608745-86d94978-c636-4955-8154-051543284e1a.png)

I have not identified the common cause yet as its my first time working with mypy. 

Hope someone can point me in the right direction, thanks! :)

**Comment by Bibo-Joshi** [comment]
Hi. This is in deed a bit tricky, so no worries :D `{Message, Chat, …}.bot` are usually `None` if you manually instantiate those classes, but because that's seldomly the case, we told mypy to just ignore those errors. That's this part of `setup.cfg`:

https://github.com/python-telegram-bot/python-telegram-bot/blob/c3e3bb77e507f1997c1eb66f81265da4da12b68b/setup.cfg#L61-L64

If you change the names to leading underscores here, too, it should work. If there are any mypy errors left that you can't resolve, you can just PR and we'll have a look together :)

BTW: We indeed aim to resolve this mypy-workaround with #2505

**Comment by kennethcheo** [comment]
Thanks that was indeed the issue. Its fixed now and I just opened a PR :)
