### ISSUE TITLE
[FEATURE/DISCUSSION] Make file paths in tests agnostic to execution source path

### ISSUE THREAD

**Issue by eldbud** [python-telegram-bot/python-telegram-bot#2701]
Tests which include file paths fail when executed not via the pytest cli from the project's root.
This happens because the path strings are relative and not absolute.

I think the test suite will be much friendlier if the provided paths will be absolute, so that these tests can be run from any directory within the project, as well as via the ide's play button.

i will be happy to take this task upon myself.

**Comment by eldbud** [comment]
@Bibo-Joshi what do you think about this?

**Comment by harshil21** [comment]
> as well as via the ide's play button.

fwiw, you can change the default test location directory, but you shouldn't have to. I like the idea!

**Comment by eldbud** [comment]
i'm on it then.
Can you please assign me? and also add the hacktoberfest tag if possible?
thanks!

**Comment by Bibo-Joshi** [comment]
IISC the point is that the creation of the absolute path depends on the current cwd. Anyway, you can cook up something and then we'll have a look :)

haha okay :D

**Comment by eldbud** [comment]
thanks for the elaboration!
look at the value of ```animation```.
When i run the test, using the play button, via working directory _C:\Users\eldad\PycharmProjects\python-telegram-bot_, the value of ```animation``` is ```'file:///C:/Users/eldad/PycharmProjects/python-telegram-bot/tests/data/telegram.jpg'```
But when i run the test via working directory _C:\Users\eldad\PycharmProjects\python-telegram-bot\tests_, the value of ```animation``` is only the relative path of ```'tests/data/telegram.jpg'```

Any idea on why this value changes from a uri to just a relative path, upon changing working dir?

**Comment by eldbud** [comment]
okay, i just thought this could be nice after seeing there's the ```thumb_file``` fixture, which is also just a function that returns something - the path to the thumb file. Fixtures are just functions that (sometimes) return something, only they're within the pytest realm. so i thought to do something similar, but i understand the preference for being explicit in filenames.

What i did so far is that there's a ```data_file``` fixture, to which the filename is provided.

**Comment by Bibo-Joshi** [comment]
The difference that I see is that a `data_file` fixture would return a constant function, i.e. every time the fixture is used, the same object (a function) is returned. In constrast to that, `thumb_file` returns a new object every time it's used. If one were to instead define a constant `THUMB_FILE = Path('tests/data/thumb.jpg').open()`, then one would have to call `THUMB_FILE .seek(0)` every time that constant was used. So the fixture is more handy.
For `data_file` I don't see an argument like this being relevant and hence would prefer a simple import over injecting the function into the test via a fixture.
If I'm missing/not understanding a point, please tell me :)
