### ISSUE TITLE
[QUESTION] db persistance

### ISSUE THREAD

**Issue by v-lavrushko** [python-telegram-bot/python-telegram-bot#2702]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

ok, so all cache, user data, chat data, and bot data are saved in our ram. Maybe there is a possibility to hold it all in the database? But work with it the same way

### Describe the solution you'd like

something like db_persistance, that will hold all our data in the database

**Comment by Bibo-Joshi** [comment]
Hi. PTB has your back: It comes with a built-in interface for persistence, see this [wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Making-your-bot-persistent). Note next to the built-in `PicklePersistence`, a PostreSQL persistence is available via [ptbcontrib](https://github.com/python-telegram-bot/ptbcontrib/tree/main/ptbcontrib/postgres_persistence). There may also be 3rd party persistence classes that we are not aware of.
