### ISSUE TITLE
[FEATURE] Filters.update.edited

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2703]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Currently, we have

* `Filters.update.messages` for handling either messages or edited messages
* `Filters.update.channel_posts` for handling either channel posts or edited channel posts

* but we don't have a filter that allows you to filter for [non-edited messages or non-edited channel post] or [edited messages or edited channel posts]

### Describe the solution you'd like

Add a `Filters.update.edited` that filters for for edited messages or edited channel posts

**Comment by PhilippFr** [comment]
Gonna tackle this issue
