### ISSUE TITLE
Inline query location

### ISSUE THREAD

**Issue by EvertKors** [python-telegram-bot/python-telegram-bot#272]
Hello,

when turning on inline location via botfather the location is not inside of the received inlineQuery.

**Comment by jh0ker** [comment]
Did you request the user to share his location with a KeyboardButton that has request_location set to True?

**Comment by EvertKors** [comment]
Yes, the location is also visible on https://api.telegram.org/botXXXXXXXXXXXXXX/getUpdates, but not inside the inlinequery update

**Comment by jh0ker** [comment]
This is indeed missing from the library. Thank you for reporting!

**Comment by jh0ker** [comment]
#273 has been merged to fix this issue. It will be included in the next release, but you can use it immediately by doing
```
pip uninstall python-telegram-bot
pip install https://github.com/python-telegram-bot/python-telegram-bot/archive/master.zip
```
