### ISSUE TITLE
[QUESTION] Does persistance saves callback_data?

### ISSUE THREAD

**Issue by v-lavrushko** [python-telegram-bot/python-telegram-bot#2729]
### Issue I am facing

I'm using Inline Keyboard and would like to use my custom objects as callback data. Does this callback data is saved in persistence?

### Operating System

Windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.7
Bot API 5.3
certifi 2021.05.30
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
```

**Comment by Poolitzer** [comment]
Hi, not by default if you use pickle persistence, but it definitely does. Also refer to this [wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Arbitrary-callback_data).
