### ISSUE TITLE
[QUESTION] Errorhandlerbot.py crashes if you send the command /bad_command via telegram-bot.

### ISSUE THREAD

**Issue by ChrSchultz** [python-telegram-bot/python-telegram-bot#2737]
### Steps to Reproduce

1. open telegram and navigate to the bot insertet to the program.
2. start errorhandlerbot.py  and wait for instructions in telegram.
3. send via the designed bot `/bad_command`
4. now the errohandlerbot.py crashes with the following messages:
```
Traceback (most recent call last):
  File "C:\Users\ic-sc\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\ic-sc\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "D:\Benutzer\ic-sc\Dokumente\telgram.py", line 60, in bad_command
    context.bot.wrong_method_name()  # type: ignore[attr-defined]
AttributeError: 'ExtBot' object has no attribute 'wrong_method_name'
```

### Expected behaviour

instead of crashin there should be send a message with the Error on telegram via the bot.

### Actual behaviour

program crash .

### Operating System

Windows 10 64 bit, 

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.7
Bot API 5.3
certifi 2020.12.05
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
```

**Comment by harshil21** [comment]
Hi, this is the intended behavior. See [line 31](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/errorhandlerbot.py#L31). Printing the error to console is intentional. 

However, the error should also be sent your chat. Have you added your chat id in the `DEVELOPER_CHAT_ID` variable?
