### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by jetvolkov2** [python-telegram-bot/python-telegram-bot#2743]
### Issue I am facing

Hello! Faced an exception handling problem. I launch my bot and it works well, but then I turn off the internet and the bot starts throwing telegram.error.NetworkError exceptions. I can't catch this exception. Did I understand correctly that this is due to the fact that the bot uses several threads to work and an exception is thrown in one of these threads? What am I doing wrong?

### Operating System

Arch linux

### Version of Python, python-telegram-bot & dependencies

```shell
* python 3.9
* python-telegram-bot 13.7
```

**Comment by Poolitzer** [comment]
can you post the full traceback? Im pretty sure doing a try except around your `.idle()` call should work, if you use that.
