### ISSUE TITLE
[FEATURE] Get invite link count of referrals

### ISSUE THREAD

**Issue by units-labs** [python-telegram-bot/python-telegram-bot#2760]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

I want to retrieve the members count that joined via a specific invite link

### Describe the solution you'd like

get_member_count_referred_by_invite_link(url)

**Comment by Poolitzer** [comment]
hi, this feature is rather out of scope of the main library I am afraid. There is ptbcontrib one could develop this for though.
