### ISSUE TITLE
[QUESTION] Time zone is always LMT on job_queue.run_once 

### ISSUE THREAD

**Issue by akbarabdul80** [python-telegram-bot/python-telegram-bot#2761]
### Steps to Reproduce

1. `time = datetime.time(hour=9, minute=49, tzinfo=pytz.timezone('asia/jakarta'))`
    `context.job_queue.run_daily(notify_assignees, time, context=update.message.chat_id)`
2. [LOG] WARNING - Run time of job "1 (trigger: date[2021-10-30 16:50:00 LMT], next run at: 2021-10-30 16:50:00 LMT)" was missed by 2 days, 15:36:34.468150

### Expected behaviour

Date time in trigger should have timezone WIB 

### Actual behaviour

The date that appears in the log has an LMT timezone 
`apscheduler.executors.default - WARNING - Run time of job "1 (trigger: date[2021-10-30 16:50:00 LMT], next run at: 2021-10-30 16:50:00 LMT)" was missed by 2 days, 15:36:34.468150`

### Operating System

Ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.0, python-telegram-bot 13.7
```

**Comment by Bibo-Joshi** [comment]
Hi. As mentioned in the [docs of `pytz`](https://pythonhosted.org/pytz/), 

> Unfortunately using the tzinfo argument of the standard datetime constructors ‘’does not work’’ with pytz for many timezones.

IIRC building a properly timezone aware `time` object with `pytz` work e.g. like

```python
dtm = datetime.datetime(year=1900, month=1, day=1, hour=9, minute=49)
tzinfo = pytz.timezone('asia/jakarta')
aware_time = tzinfo.localize(dtm).timetz()
```

If you want to use the same timezone everywhere, it might be useful to set it as the default timezone for the bot, see [this wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Adding-defaults-to-your-bot).

**Comment by akbarabdul80** [comment]
Ok thanks a lot, that solved my problem and i'm sorry for tagging the bug on this issue

**Comment by Bibo-Joshi** [comment]
No worries :)
