### ISSUE TITLE
[BUG]ptb v13 hardpins dependencies, causing installation to fail

### ISSUE THREAD

**Issue by xmatthias** [python-telegram-bot/python-telegram-bot#2765]
### Steps to Reproduce

I disagree with tagging of V14 for #2758

Duplicate of #2758 - but in this issue, i'm explicitly requesting this to be fixed for v13, requesting a fix for the current release cycle.

only opening this as new issue since as comments have been locked (probably intentionally, as you knew i asked for having this on v14 as well), and i disagree with the tagging 

### Expected behaviour

Installation works

### Actual behaviour

Installation broken

### Operating System

does not matter

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot==13.7
cachetools==4.2.4
```

### Relevant log output

```python
pip install cachetools==4.2.4 -U
Collecting cachetools==4.2.4
  Using cached cachetools-4.2.4-py3-none-any.whl (10 kB)
Installing collected packages: cachetools
  Attempting uninstall: cachetools
    Found existing installation: cachetools 4.2.2
    Uninstalling cachetools-4.2.2:
      Successfully uninstalled cachetools-4.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
python-telegram-bot 13.7 requires cachetools==4.2.2, but you have cachetools 4.2.4 which is incompatible.
```

**Comment by Bibo-Joshi** [comment]
you've already voiced your opinion rather clearly in #2757. Please refrain from opening more threads about this.

**Comment by xmatthias** [comment]
Closing (and locking) issues to prevent complaints about that without even trying to understand the problem is not good behavior - and clearly does not correspond to yoru own [code of conduct](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/CODE_OF_CONDUCT.md) - which states (and i'd like to point out here again):

> Showing empathy towards other community members

You're clearly NOT corresponding to your own code of conduct - so please treat this as **official complaint** about this same matter. 
Please note:
I expect a response from **another team member** about this complaint about your behaviour - as i think your focus on v14 (and disrespect for users and their problems withthe current stable version) is unacceptable.

**Comment by xmatthias** [comment]
@Bibo-Joshi Yes, and as you know i disagree, you've locked the issue i opened.

I've now filed an official complaint about your behaviour, as you're not sticking to your CoC.
I expect that issue to be worked on by someone other than yourself - thanks.
