### ISSUE TITLE
UserWarning: Asynchronous callbacks can not be processed without at least one worker thread

### ISSUE THREAD

**Issue by skhaz** [python-telegram-bot/python-telegram-bot#2768]
### Issue I am facing

On the logs I see

```bash
UserWarning: Asynchronous callbacks can not be processed without at least one worker thread.
```

What I need to do to dismiss this warning?

I am using with flask and gunicorn

### Traceback to the issue

```python
/usr/local/lib/python3.8/site-packages/telegram/ext/dispatcher.py:250: UserWarning: Asynchronous callbacks can not be processed without at least one worker thread.
```

### Related part of your code

I am starting the bot with gunicorn, with 1 worker and 8 threads because I am using Docker

```Dockerfile
FROM python:3.8-slim
ENV PYTHONUNBUFFERED True
WORKDIR /app
COPY *.txt .
RUN pip install --no-cache-dir --upgrade pip -r requirements.txt
COPY . ./

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 main:app
```

```python
@app.post("/")
def index() -> Response:
    dispatcher.process_update(Update.de_json(request.get_json(force=True), bot))

    return "", http.HTTPStatus.NO_CONTENT
```

### Operating System

Google Cloud Run (Docker)

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.8

flask==2.0.2
gunicorn==20.1.0
jinja2==3.0.2
python-telegram-bot==13.7
requests==2.26.0
```

**Comment by Poolitzer** [comment]
The issue stems from the initiation of [Dispatcher](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.dispatcher.html). You are setting the workers there to something below 1, which is why the error appears.

**Comment by skhaz** [comment]
I see... I forgot to mention this piece of code

```python
dispatcher = Dispatcher(bot=bot, update_queue=None, workers=0)
dispatcher.add_handler(MessageHandler(Filters.command, on_command))
```

It's ok to use the default number of workers with my current configuration of gunicorn running on cloud run (docker)?

**Comment by Poolitzer** [comment]
I have absolutely no idea, but if I were you, I would have just let the param be the default and monitored the result.

**Comment by skhaz** [comment]
Ok. Thank you @Poolitzer

**Comment by Poolitzer** [comment]
@skhaz Glad I was able to help

**Comment by skhaz** [comment]
Changed[1] to on one of my bots, let's see how it behaves

1 -
```python
dispatcher = Dispatcher(bot=bot, update_queue=None)
```

**Comment by alexeyshulzhenko** [comment]
@skhaz  and what are the results?

**Comment by skhaz** [comment]
@alexeyshulzhenko it seems to work correctly on Cloud Run, I am running the default number of workers and everything is fine

**Comment by alexeyshulzhenko** [comment]
@skhaz  got you, thanks!
