### ISSUE TITLE
[QUESTION] How to send a gif without resize?

### ISSUE THREAD

**Issue by munkito** [python-telegram-bot/python-telegram-bot#2772]
### Issue I am facing

Hello!

I'm trying to send an autogenerated gif file but everytime the gif is resized to very low quality.

I've tried with sendAnimation method and the gif is resized. With sendVideo method the gif is sent without resize but when try to play it in full screen mode the smartphone it throws an error to play it.

Does anyone some idea,?

Thanks!

### Operating System

Android

### Version of Python, python-telegram-bot & dependencies

```shell
3.8
```

**Comment by Bibo-Joshi** [comment]
Hi. How/If Telegram compresses the sent gif when sending it as animation/video, can not be controlled by the Bot API.
What kind of error do you see when trying to play it as video? Can you show a screenshot?
