### ISSUE TITLE
[FEATURE]  a conversation class to include all dialogues of a conversation + its handler

### ISSUE THREAD

**Issue by evakdev** [python-telegram-bot/python-telegram-bot#2781]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

I believe conversation handlers can become a mess very quickly, especially if they are nested. There is a need for some structure where you can gather the handler, functions, and keys of each conversation all in one place, separate from the others.

### Describe the solution you'd like

For my own use I've created a simple class where I have a handler attribute, keys for the states, and obviously all the related functions. This helps a lot in separating conversations, having loose coupling, and generally being less confused. 

I think it would be a good idea to have something similar in PTB itself. It could also include a class for managing keys to states.

**Comment by Bibo-Joshi** [comment]
Hi, thanks for reaching out.

TBH I don't quite understand what you're asking for. Are you looking for [`ConversationHandler`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.conversationhandler.html)? Are you suggesting an improvement of that handler? Can you show an example of your custom class to explain what you like to see in PTB?

**Comment by Bibo-Joshi** [comment]
I'll go ahead and close this due to inactivity.

**Comment by Bibo-Joshi** [comment]
superseded by #2827
