### ISSUE TITLE
unable to access job_queue list

### ISSUE THREAD

**Issue by shouya** [python-telegram-bot/python-telegram-bot#280]
For some reason I wish I could access to the job_queue list to remove added job. For now I can only modify `job_queue.queue` manually. Would there be public interfaces for removing/updating/listing jobs in a job queue?

**Comment by jh0ker** [comment]
The `JobQueue` uses a `PriorityQueue` that is not iterable and has no random access. I had two ideas on how to solve that:

1. `get` all jobs and then `put` all except the one to remove
2. If a job function returns `False`, it will not be re-enqueued

I like the second solution more.

**Comment by Gurzo** [comment]
number 1 it's the correct solution IMHO, but requires a lot of code and it's not very efficent.
the simplest way to update a job is to remove and readd a modified version

to remove a job, number 2 it's simple and works, i tested:
current:
```
try:
    j.run(self.bot)
except:
    self.logger.exception('An uncaught error was raised while executing job %s' % j.name)
    if j.repeat:
        self.put(j.run, j.interval)
```
my:
```
try:
    result = j.run(self.bot)
except:
    self.logger.exception('An uncaught error was raised while executing job %s' % j.name)
    if j.repeat and result:
        self.put(j.run, j.interval)
```
to stop a job, simply return False from the method. but, this way you lose the option to return a useful value. not a big problem, job don't return anything in noraml condition, but if you really need to return, you can do something like : 

`return {'result':'your return value', 'stop_job':True or False} `

and
```
if j.repeat and result['stop_job']:
        self.put(j.run, j.interval)
```

**Other way (TESTED), number 3:**
in jobqueue.py

```
class JobQueue(object):
    def __init__(self, bot, tick_interval=1.0):
        self.tick_interval = tick_interval
        self.queue = PriorityQueue()
        self.bot = bot
        self.logger = logging.getLogger(__name__)
        self.__lock = Lock()
        self.running = False
        self.to_kill = []        #<----new parameter, a list of job name to kill
```
a new method:
```
def kill(self, job_name):
        self.to_kill.append(job_name)
```

a new check before readd the job to the queue
```
try:
    j.run(self.bot)
except:
    self.logger.exception('An uncaught error was raised while executing job %s' % j.name)
if j.name in self.to_kill:
    self.to_kill.remove(j.name)
    allow = False
else:
    allow = True
if j.repeat and allow:
    self.put(j.run, j.interval)
```
to kill a job like that:

```
j = updater.job_queue
j.put(check_database, 100)
```

simply call:

`j.kill('check_database')`

in case we can use j.name + str(j.interval) to distinguish different istance of the same process

**Comment by Gurzo** [comment]
@jh0ker @shouya
instead, the simplest way to get a list of current active jobs, is to mantain a list

```
class JobQueue(object):
    def __init__(self, bot, tick_interval=1.0):
        self.tick_interval = tick_interval
        self.queue = PriorityQueue()
        self.bot = bot
        self.logger = logging.getLogger(__name__)
        self.__lock = Lock()
        self.running = False
        self.list_jobs = []        #<----new parameter, a list of active jobs
```

update the list

```
if j.repeat:
    self.put(j.run, j.interval)
    if not j.name in self.list_jobs:
        self.list_jobs.append(j.name)
else:
    self.list_jobs.remove(j.name)
```

a new method:

```
def get_jobs(self):
        return self.list_jobs
```

**Comment by leandrotoledo** [comment]
PR #307 has been submitted for review.

**Comment by jh0ker** [comment]
#307 has been merged, closing
