### ISSUE TITLE
[BUG] @run_async Not working and throws error

### ISSUE THREAD

**Issue by Rohith-sreedharan** [python-telegram-bot/python-telegram-bot#2803]
### Steps to Reproduce

1.  @run_async
2. ERROR - A promise with deactivated error handling raised an error
3./app/.heroku/python/lib/python3.9/site-packages/telegram/ext/handler.py:145: TelegramDeprecationWarning: The @run_async decorator is deprecated. Use the `run_async` parameter of`Dispatcher.add_handler` or `Dispatcher.run_async` instead.

### Expected behaviour

The bot should work

### Actual behaviour

/app/.heroku/python/lib/python3.9/site-packages/telegram/ext/handler.py:145: TelegramDeprecationWarning: The @run_async decorator is deprecated. Use the `run_async` parameter of`Dispatcher.add_handler` or `Dispatcher.run_async` instead.

2021-12-02T05:16:33.720156+00:00 app[worker.1]:   return self.callback(update, context)

2021-12-02T05:16:33.720435+00:00 app[worker.1]: 2021-12-02 05:16:33,720 - telegram.ext.dispatcher - ERROR - A promise with deactivated error handling raised an error.

### Operating System

Heroku

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.0
certifi 2020.06.20
Python 3.9.9 (main, Nov 16 2021, 09:53:35)  [GCC 9.3.0]
```

### Relevant log output

```python
/app/.heroku/python/lib/python3.9/site-packages/telegram/ext/handler.py:145: TelegramDeprecationWarning: The @run_async decorator is deprecated. Use the `run_async` parameter of`Dispatcher.add_handler` or `Dispatcher.run_async` instead.

2021-12-02T05:16:33.720156+00:00 app[worker.1]:   return self.callback(update, context)

2021-12-02T05:16:33.720435+00:00 app[worker.1]: 2021-12-02 05:16:33,720 - telegram.ext.dispatcher - ERROR - A promise with deactivated error handling raised an error.
```

**Comment by Bibo-Joshi** [comment]
Hi. As the warning tells you, the `@run_async` decorator is depercated. Please have a look at [this wiki page](../wiki/Performance-Optimizations) for instructions on how `run_async` works by now. The new mechanic will also properly log the exception that happend in your callback.
