### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Kaikiz17** [python-telegram-bot/python-telegram-bot#2806]
### Issue I am facing

Please where do I go to start up the installation for python bot
I only it keeps bon telling me something like this
$ python -m telegram
Where do I go to start it up

### Operating System

Android

### Version of Python, python-telegram-bot & dependencies

```shell
4.0
```

**Comment by Bibo-Joshi** [comment]
Hi. If you're new to python and don.t know yet how you can install packages, I recommend to read some tutorials. See e.g. [here](https://t.me/pythontelegrambotgroup/545421).

**Comment by aditya-yadav-27** [comment]
he/she didn't replied from 10 days I think this issue should be closed now
