### ISSUE TITLE
[QUESTION] How to get the id of Answer Inline Query input_message_content ?

### ISSUE THREAD

**Issue by raskyer** [python-telegram-bot/python-telegram-bot#2807]
### Issue I am facing

I would like to know how to get the id of the message posted after a choice made by the user when displaying 'answer_inline_query' results.

What I want :
Be able to stored the telegram id of the message sent in inline mode.

For example :
- a user type in a channel or group : @my_bot smth
- my bot answer multiples InlineQueryResultArticle with input_message_content = InputTextMessageContent
- a user tap on a choice
- the input_message_content is sent to the channel or group

How to get the id of the message sent in the last step ?

### Related part of your code

```python
context.bot.answer_inline_query(update.inline_query.id, results) # How to get the id ?
```

### Operating System

Windows

### Version of Python, python-telegram-bot & dependencies

```shell
13.8.1
```

**Comment by Bibo-Joshi** [comment]
Hi. You can only get info about the resulting message, if your bot is a member in the chat where the message is sent. I.e., inline mode allows users to send messages generated by your bot in chats that your bot is not a member of (e.g. private chats) and you can't expect to get info about those messages.

Anyway, in the chats where your bot is a member, it will get the resulting message as an update and [`Message.via_bot`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html#telegram.Message.via_bot) will be set. The filters module has [`Filters.via_bot`](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.filters.html?highlight=Message.via_bot#telegram.ext.filters.Filters.via_bot) built in, which you can use to filter for messages sent via your bot (or any bot).

**Comment by raskyer** [comment]
Thanks !

I think I manage to receive the choice by activating inline feedback :)
