### ISSUE TITLE
[API] Api 5.5

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#2808]
Api 5.5 is here. Rejoice.

- [x] Doc note: Bots are now allowed to contact users who sent a join request to a chat where the bot is an administrator with the can_invite_users administrator right – even if the user never interacted with the bot before.

 - [x] Doc note/potential shortcut: Added support for mentioning users by their ID in inline keyboards. This will only work in Telegram versions released after December 7, 2021. Older clients will display unsupported message.
- [x] New methods, nedds shortcuts at : Added the methods banChatSenderChat and unbanChatSenderChat for banning and unbanning channel chats in supergroups and channels.
- [x] `Chat` addition: Added the field has_private_forwards to the class Chat for private chats, which can be used to check the possibility of mentioning the user by their ID.
- [x] `Chat`/`Message` addition: Added the field has_protected_content to the classes Chat and Message.
- [x] `Message` addition:  Added the field is_automatic_forward to the class Message.

- [x] Evaluate if worth adding to channel post/forward method docs: Note: After this update it will become impossible to forward messages from some chats. Use the fields has_protected_content in the classes Message and Chat to check this.

- [ ] Evaluate if worth adding to channel post: Note: After this update users are able to send messages on behalf of channels they own. Bots are expected to use the field sender_chat in the class Message to correctly support such messages. Edit: Decided to not add it.

**Comment by Poolitzer** [comment]
I already added the first doc note to the JoinRequestClass, is it worth adding to handler/Update class? Or not worth at all? a20e95c

**Comment by jk6521** [comment]
Eagerly waiting for this feature in  PTB.
