### ISSUE TITLE
data field in a job

### ISSUE THREAD

**Issue by shouya** [python-telegram-bot/python-telegram-bot#281]
Many job queue implementations have a field to specify custom data when setting up a job. This piece of data come as a field in the job object and is accessible when the job is invoked. I think this functionality will be helpful for many uses.

**Comment by jh0ker** [comment]
I like the idea, but I don't think we can add it without breaking existing code, so it would be something for 5.0
Right now, you can use a lambda function for that.

**Comment by jh0ker** [comment]
With the rework of `JobQueue` in #307 I added this possibility as seen in the referenced commit above. What do you think?

**Comment by shouya** [comment]
Thank you. #307 looks good to me 👍

**Comment by jh0ker** [comment]
#307 has been merged, closing
