### ISSUE TITLE
[QUESTION] Process action before & after every update ?

### ISSUE THREAD

**Issue by raskyer** [python-telegram-bot/python-telegram-bot#2811]
### Issue I am facing

Hello,

I have a bot that do some database work during the commands. For example, checking the user, fetching data, updating etc ..
But let's say I have an error during the process (lost of connexion etc ...). I would like to handle connection/re-connection to this database.

My first thought was to connect when I receive an update and disconnect after handlers process it.

I would like to know if there's a easy was to do that ?
Of course I could add :
`try_to_connect()` and `try_to_disconnect()` in each of my handlers (Commands, Messages, Conversations, Callbacks etc ...)
But that's not very beautiful.

What I would like is a sort of "middleware" that is being called right before handlers and right after.

Another way to do so is to create groups in `dispatcher.add_handler` but here again, there's no "AllHandler" object, so I have to create at least 2 separate handlers (let's say one for message and one for callbacks) to put on group 0 and group 2 (because group 1 are the actual handlers).

Is there any better way to do that ? Some sort of callback function that triggers before and after processing an update ?
Thanks !

### Operating System

Windows

### Version of Python, python-telegram-bot & dependencies

```shell
bot : 13.8.1
python : 3.9.7
```

**Comment by Poolitzer** [comment]
Hi. Thanks for the very well formulated question.

> Another way to do so is to create groups in dispatcher.add_handler but here again, there's no "AllHandler" object

You are saying there is no AllHandler but there is, the [Type Handler](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.typehandler.html), when you pass the type `telegram.Update`. This (TypeHandler in group -1 and 1) is what I would recommend to you as well.

**Comment by raskyer** [comment]
Perfect! Thanks alot.
Have a good day.
