### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by codePerfectPlus** [python-telegram-bot/python-telegram-bot#2824]
### Issue I am facing

Hi Everyone.

I am new to telegram bot development. So I have few question.

1. Why we should user python-telegram-bot instead of pytelegrambotapi?
2. Is Python-telegram-bot support async functions?

Thanks

### Traceback to the issue

```python
None
```

### Related part of your code

```python
None
```

### Operating System

windows

### Version of Python, python-telegram-bot & dependencies

```shell
None
```

**Comment by Bibo-Joshi** [comment]
Hi. PTB currently does not yet support `asyncio` natively, but we're currently working on that - see the pinned issue #2352.
Regarding comparison with other bot API wrappers: Choosing a library to use usually depends on the set of features that you're looking for and ofc also on personal preferences. I suggest to check out the documentation & examples of the different libraries to get a feeling for how they work. You're also welcome to join our [off-topic usergroup](https://t.me/pythontelegrambottalk) and ask other members of our community for their experience with other libraries.
