### ISSUE TITLE
[FEATURE] A function to automatically decide if update.message.reply_text or update.callback_query.edit_message_text will be used.

### ISSUE THREAD

**Issue by evakdev** [python-telegram-bot/python-telegram-bot#2826]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

In some situations, it may not be possible to know if you should use update.message.reply_text or update.callback_query.edit_message_text. This could happen if user can start a conversation from different stages of a conversation (where sometimes they are using an inline keyboard and sometimes sending text.) IF it happens, you'll face an exception.

### Describe the solution you'd like

I think it would be useful to have a function in update, that decides automatically if it should use  update.message.reply_text or update.callback_query.edit_message_text. This could even be a simple try except block such as this:

```
def send_message(update, text, reply_markup=None, parse_mode=None):
    """
    Sends a message to the user.
    This will use callback_query.edit_message_text as priority. if it doesn't work, will use message.reply_text instead.
    To be used when we're not sure which one will be needed.
    """
    try:
        return update.callback_query.edit_message_text(
            text, reply_markup=reply_markup, parse_mode=parse_mode
        )
    except:
        return update.message.reply_text(
            text, reply_markup=reply_markup, parse_mode=parse_mode
        )
```

### Additional context

This may also an issue for accessing `from_user`, but I haven't checked the docs to see if there is a solution for that or not.

**Comment by Poolitzer** [comment]
Hi. I would vote to say this is the responsibility of the end user. Easy enough to do in code:

```python
callback(update, context):
    text = "This is the text to get to the user"
    if update.effective_message:
        update.effective_message.reply_text(text)
    else:
        update.callback_query.edit_message_text(text)

```
Or even more if statements if you have more potentially callbacks. Thats easy to know because you register them with specific handlers, normally.

**Comment by evakdev** [comment]
Sure, its easy enough to do. Just thought it can be a common issue, as I've had it several times :)

**Comment by Poolitzer** [comment]
It might be, though I personally define one callback per handler type.

Anyway, I don't think the library should just switch methods for the user. This is not the responsibility of it.

**Comment by evakdev** [comment]
Alright, should I close the issue then?

**Comment by Poolitzer** [comment]
You can leave it up if you are still convinced its a good idea and see what the other maintainers think.

**Comment by Bibo-Joshi** [comment]
Hi. The `update.effective_message` already covers `update.callback_query.message`, i.e. one doesn't need the if clauses in Pools example. IMO this already covers the requested use case.

Note that there is also `update.effective_{user, chat},` which in particular covers the `from_user` case.

**Comment by evakdev** [comment]
Ohh, I wasn't aware that covers them all! That makes things much easier. Thanks :)
Then perhaps maybe we could make the docs a bit clearer on what effective_{} do? it does say "no matter what kind of update this is", but maybe it could mention all the various things it checks? e.g `whether it be message, edited message, callback_query, etc.`

If you think that's a helpful addition, I could make that change. Otherwise I'll just close the ticket :)

**Comment by Poolitzer** [comment]
We list the updates which set it [here](https://python-telegram-bot.readthedocs.io/en/stable/telegram.update.html#telegram.Update.effective_message), where is your string from?

**Comment by evakdev** [comment]
Yes, that's where I got it from. It says it will be none for this and that. It doesn't say that it will return whichever of message, edited_message, callback_query, channel_post, edited_channel_post  that is present.

**Comment by Poolitzer** [comment]
@evakdev Ohh you mean instead of saying when it is None, you would say when it is the message?

**Comment by evakdev** [comment]
yes, exactly! it could say both too, actually

**Comment by Bibo-Joshi** [comment]
If you like to, you're very welcome to open a PR against the `doc-fixes` branch to elaborate the docs :)

**Comment by Bibo-Joshi** [comment]
I added the doc-enhancement to #2633 and will close this thread in favor of #2633 :)

**Comment by Bibo-Joshi** [comment]
FYI: I added a commit to #2822 that addresses the documentation. For `effective_{user, chat}`, I didn't list every possibility, but included exapmles that should get the idea across better :)
