### ISSUE TITLE
How to retrieve data from python telegram bot inline keyboard? [QUESTION]

### ISSUE THREAD

**Issue by sbatrow** [python-telegram-bot/python-telegram-bot#2829]
### Issue I am facing

[Video](https://i.stack.imgur.com/0RcsS.gif)

I want to get this kind of data from the python telegram bot 

**password enter keypad**

### Operating System

linax

### Version of Python, python-telegram-bot & dependencies

```shell
python3, python-telegram-bot last Version
```

**Comment by Poolitzer** [comment]
@sbatrow hi, maybe this example can help you figure it out on your own: <a href="https://github.com/python-telegram-bot/python-telegram-bot/tree/master/examples/#inlinekeyboardpy">inlinekeyboard.py</a>

**Comment by sbatrow** [comment]
@Poolitzer  ok sir I will analyze it

**Comment by sbatrow** [comment]
@Poolitzer  But it does capture all callback_query and it causes problems when running other callback_query, watch video  [video](https://i.imgur.com/T1bXSqj.mp4)

**Comment by Poolitzer** [comment]
@sbatrow This is what the pattern argument of the <a href="https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.callbackqueryhandler.html#telegram.ext.CallbackQueryHandler">telegram.ext.CallbackQueryHandler</a> helps with, if you insert a unique callback data in the button. Or you implement some different backend logic like mapping the message id of the message response to the proper trigger.
