### ISSUE TITLE
[FEATURE] Add shortcut to PM Users from the ChatJoinRequest Updates

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#2830]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

I think having a shortcut in the Update Class to send the user behind the Update a message is helpful. This was advertised in the [blog post by telegram](https://telegram.org/blog/protected-content-delete-by-date-and-more#responses-to-join-requests) as the new way to handle join requests, so I think that is an expected and very common workflow as a response to the Update.

### Describe the solution you'd like

I would like to have a class function implemented in the [ChatJoinRequest class](https://python-telegram-bot.readthedocs.io/en/stable/telegram.chatjoinrequest.html#telegram.ChatJoinRequest), maybe named `reply`, which acts a shortcut to `bot.send_message(chat_id=update.effective_user.id, *args, **kwargs)`. One can argue that having a reply for each kind of `send_` function is to be expected, similar to how we deal with this in the [Message](https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html#telegram.Message.reply_text) class.

### Describe alternatives you've considered

It is trivial to do this function call without the shortcut, so that is the alternative.

**Comment by Bibo-Joshi** [comment]
What advantage do you see in `update.chat_join_request.reply_text` over `update.effective_user.send_message`?
Note that the main advantage of `Message.reply_*` is that it takes care of the `reply_to_message_id`. If this parameter didn't exist, one might just as well use `update.effective_chat.send_*`. This is why I'm not sure if I see any benefit of an additional shortcut here …

**Comment by Poolitzer** [comment]
hmmm, now that you point out this obvious shortcut, I guess you are correct.
