### ISSUE TITLE
[QUESTION] set_my_commands() issue

### ISSUE THREAD

**Issue by Happy-Ferret** [python-telegram-bot/python-telegram-bot#2831]
### Issue I am facing

I'm trying to set commands from within a dictionary.
This fails with a string index out of range error and I cannot quite understand how.
Simply printing it returns the commands.

### Traceback to the issue

```python
Traceback (most recent call last):
  File "main.py", line 207, in <module>
    main()
  File "main.py", line 163, in main
    bot.set_my_commands(command.name, command.description)
  File "/home/user/.local/lib/python3.6/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/telegram/bot.py", line 5328, in set_my_commands
    cmds = [c if isinstance(c, BotCommand) else BotCommand(c[0], c[1]) for c in commands]
  File "/home/user/.local/lib/python3.6/site-packages/telegram/bot.py", line 5328, in <listcomp>
    cmds = [c if isinstance(c, BotCommand) else BotCommand(c[0], c[1]) for c in commands]
IndexError: string index out of range
```

### Related part of your code

```python
from telegram import Update, ForceReply, ChatPermissions, Bot, BotCommand

class Command(object):
    def __init__(self, name, description):
        self.name = name
        self.description = description

Commands = {
    1: Command("start", "start command"),
    2: Command("stop", "stop command")
}

def main() -> None:
    
    updater = Updater(config.TOKEN)
    bot = Bot(config.TOKEN)

    for command in Commands.values():
        bot.set_my_commands(command.name, command.description)
```

### Operating System

Windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.9
Bot API 5.5
certifi 2021.10.08
Python 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
```

**Comment by harshil21** [comment]
Hi,

You should pass those as a tuple in the method, like this:
``` python
    for command in Commands.values():
        bot.set_my_commands((command.name, command.description))
```
[See the docs](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.set_my_commands) for this method

**Comment by Happy-Ferret** [comment]
> Hi,
> 
> You should pass those as a tuple in the method, like this:
> 
> ```python
>     for command in Commands.values():
>         bot.set_my_commands((command.name, command.description))
> ```
> 
> [See the docs](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.set_my_commands) for this method

Thanks. Now it returns something.
Alas, only the first letter of the first command ("s").

**Comment by harshil21** [comment]
Oh, I just noticed you're not using our library's `BotCommand` class? Is there a reason why?

All you have to do is just change from using `Command` to `BotCommand` in the dictionary and then do:
``` python
bot.set_my_commands(list(Commands.values())
```

**Comment by Happy-Ferret** [comment]
> Oh, I just noticed you're not using our library's `BotCommand` class? Is there a reason why?
> 
> All you have to do is just change from using `Command` to `BotCommand` in the dictionary and then do:
> 
> ```python
> bot.set_my_commands(list(Commands.values())
> ```

Your code is missing a parentheses in the end. Other than that, awesome! It works. Thanks so much 😻
