### ISSUE TITLE
Hello How do I set up a separate permission for animations, games, stickers and inline bots in the supergroup?

### ISSUE THREAD

**Issue by ali-sajed** [python-telegram-bot/python-telegram-bot#2857]
### Issue I am facing

How do I set up a separate permission for animations, games, stickers and inline bots in the supergroup?(Is only the parameter can_send_other_messages?)

### Traceback to the issue

```python
bot.set_chat_permissions(chat_id,
    permissions=ChatPermissions(
        can_send_messages=True,
        can_send_media_messages=True,
        can_send_polls=True,
        can_send_other_messages=False,
        can_add_web_page_previews=True,
        can_change_info=True,
        can_invite_users=True,
        can_pin_messages=True
    )
)
```

### Operating System

centos 7

### Version of Python, python-telegram-bot & dependencies

```shell
last
```

**Comment by Bibo-Joshi** [comment]
As you've already noticed, there's no parameter for that. So the answer is "you can't" .
