### ISSUE TITLE
[QUESTION] Python 3.X and telegram-bot 5.6 message forwarding is not working

### ISSUE THREAD

**Issue by alireza-saberi** [python-telegram-bot/python-telegram-bot#2858]
### Issue I am facing

Scenario: I am writing a bot to transfer couple of selected messages from a private channel to the person(which I have his/her I) or to another group that I have its id

Status:

Bot: Admin of my private channel.(from part or source): (id=-15XXXXXX)

Bot: Privacy mode is off

Bot: normal member of forwarding to group (to part or sink) (I have the id as well)

me: Admin of private channel

me: normal member

user: I have his/her telegram id (I have the id as well)

All other commands are working.

I get following error in Pycharm console

`telegram.error.BadRequest: Chat not found`

I searched everywhere, It must work but it doesn't. WHY?

### Traceback to the issue

```python
2022-01-11 19:24:05,822 - apscheduler.scheduler - INFO - Scheduler started
2022-01-11 19:52:32,661 - telegram.ext.dispatcher - ERROR - No error handlers are 
registered, logging exception.
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site- 
packages\telegram\ext\dispatcher.py", line 555, in process_update
handler.handle_update(update, self, check, context)
File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site- 
packages\telegram\ext\handler.py", line 198, in handle_update
return self.callback(update, context)
File "C:\Users\a\PycharmProjects\telegramBot\commands\bot_commands.py", line 70, in 
forwardMsg
context.bot.forwardMessage(chat_id=update.effective_chat.id, from_chat_id=-154*****, 
message_id=4463)
File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\telegram\bot.py", 
line 130, in decorator
result = func(*args, **kwargs)
File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\telegram\bot.py", 
line 641, in forward_message
protect_content=protect_content,
File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site- 
packages\telegram\ext\extbot.py", line 209, in _message
protect_content=protect_content,
File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\telegram\bot.py", 
line 336, in _message
result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\telegram\bot.py", 
line 296, in _post
f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site- 
packages\telegram\utils\request.py", line 366, in post
**urlopen_kwargs,
File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site- 
packages\telegram\utils\request.py", line 279, in _request_wrapper
raise BadRequest(message)

telegram.error.BadRequest: Chat not found
```

### Related part of your code

```python
def forwardMsg(self, update: Update, context: CallbackContext):
    context.bot.forwardMessage(chat_id=update.effective_chat.id, 
    from_chat_id=-15XXXXXX, message_id=4463)



forwardMsg_handler = CommandHandler('forwardMsg', forwardMsg)
dispatcher.add_handler(forwardMsg_handler)
```

### Operating System

Window 11

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.7
python-telegram-bot: 
telegram-bot 5.6
```

**Comment by Bibo-Joshi** [comment]
The chat ID of the channel is likely wrong. Channel IDs and supergroup ids start with a -100. you can get the chat id of the channel by accessing `update.effective_chat.id` on updates that the bot receives from the channel.

**Comment by alireza-saberi** [comment]
Hi @Bibo-Joshi 

I have the update.effective_chat.id without problem. I want to forward from my private channel where its variable sits in `from_chat_id` and you are mentioning it should starts with -100.  However, ....

Bellow is invite link to this channel
![image](https://user-images.githubusercontent.com/4853299/149181207-aceaa54f-22a8-41e8-bbc6-f300b0891228.png)

Bellow is how I get number of chanel
![image](https://user-images.githubusercontent.com/4853299/149181480-6a7142db-f08d-4ea4-afdb-8e6253556b65.png)

which gives me
![image](https://user-images.githubusercontent.com/4853299/149181590-99ac6912-7fd2-4c97-a622-e5c65c7efa05.png)

**Comment by Poolitzer** [comment]
The ID for users and for bots are different, as of now with the aforementioned `-100` prepended to the ID.

**Comment by alireza-saberi** [comment]
@Poolitzer : yup, just got result by adding -100 as prefix to the 
![image](https://user-images.githubusercontent.com/4853299/149186541-d47eaeae-2f60-4111-9127-03944e9c6376.png)
