### ISSUE TITLE
[Question] How to get group chat id?

### ISSUE THREAD

**Issue by carlobolla** [python-telegram-bot/python-telegram-bot#286]
What's the object name for a group chat id? update.message.chat.id doesn't seem to work...

**Comment by jh0ker** [comment]
It should work like that. Would you mind sharing some code, maybe you're missing something else? Also you might not know that non-command messages in groups are not sent to bots by default. Only, if you disable privacy mode with BotFather.

**Comment by carlobolla** [comment]
I took a look at my code more attentively and discovered i was confusing the sender's chat id with the group chat id over and over... Totally my bad, sorry for wasting your time -_-"
Thanks a lot!!!
