### ISSUE TITLE
Replace git.io links

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2861]
GitHub is [deprecating git.io](https://github.blog/changelog/2022-01-11-git-io-no-longer-accepts-new-urls/). To be on the safe side and guarantee that we don't have any dead links, we should replace any git.io links that we have in the code base and wiki with the full links. Ofc, we can use [text links](https://github.com/python-telegram-bot/python-telegram-bot/issues/2861) wherever feasible.

A PR for this should be based on the v14 branch.
Wiki changes don't need a PR, since anyone can edit the wiki.

**Comment by murugu-21** [comment]
I was working on this issue and PEP8 throws a error for long links, what can i do as breaking url would reduce readability, shall i use a service like bit.ly?
