### ISSUE TITLE
[QUESTION] Bot is completely unresposive when trying to deploy it on heroku using webhooks

### ISSUE THREAD

**Issue by lucaguarro** [python-telegram-bot/python-telegram-bot#2862]
### Issue I am facing

I have developed a simple bot and tested that it works locally when polling from messages. Now I am trying to deploy it on heroku using webhooks and the bot is unresponsive. It also doesn't work when I run it locally with `heroku local`.

I don't get any errors from `heroku local` and just see:

> [OKAY] Loaded ENV .env File as KEY=VALUE Format

From the logging, I can verify that the API key is correctly set and the port is 8443.

### Related part of your code

```python
import os
from telegram.ext import Updater, CommandHandler, CallbackQueryHandler, Defaults
import commands as c
import logging

API_KEY = os.environ.get('API_KEY')
PORT = int(os.getenv('PORT', default=8443))
logging.getLogger().setLevel(logging.INFO)

def error(update, context):
    print(f"Update {update} caused error {context.error}")

def main():
    defaults = Defaults(parse_mode='MarkdownV2')
    print(API_KEY)
    updater = Updater(API_KEY, use_context=True, defaults=defaults)
    dp = updater.dispatcher

    dp.add_handler(CommandHandler("start", c.start_command))
    dp.add_handler(CallbackQueryHandler(c.button))
    dp.add_handler(CommandHandler("guess", c.guess_command))
    dp.add_handler(CommandHandler("status", c.status_command))
    dp.add_handler(CommandHandler("help", c.help_command))

    dp.add_error_handler(error)
    logging.info(PORT)
    logging.info(API_KEY)
    updater.start_webhook(listen="0.0.0.0",
                          port=int(PORT),
                          url_path=API_KEY,
                          webhook_url='https://wordle-telegram-bot.herokuapp.com/' + API_KEY)

    logging.info("I'm Running")

    updater.idle()

if __name__ == '__main__':
    main()
```

### Operating System

Windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
Python: 3.8.12

Output of "pip freeze":
APScheduler==3.6.3
backports.zoneinfo==0.2.1
beautifulsoup4==4.10.0
boto==2.49.0
cachetools==4.2.2
certifi==2021.10.8
click==8.0.3
colorama==0.4.4
Flask==2.0.2
itsdangerous==2.0.1
Jinja2==3.0.3
MarkupSafe==2.0.1
pyenchant==3.2.2
python-dotenv==0.19.2
python-telegram-bot==13.10
pytz==2021.3
pytz-deprecation-shim==0.1.0.post0
six==1.16.0
soupsieve==2.3.1
tornado==6.1
tzdata==2021.5
tzlocal==4.1
Werkzeug==2.0.2
wincertstore==0.2
```

**Comment by aditya-yadav-27** [comment]
Are you getting any error? check the heroku logs..

**Comment by aditya-yadav-27** [comment]
try changing the port to 5000..?

**Comment by lucaguarro** [comment]
Okay I think it is because of an error. Heroku doesn't have a lower-level C library that my app depends on. I, perhaps naively, thought that `heroku local` would be able to run the telegram bot since I do have that dependency. But anyways, it's weird because heroku local lets me know about other errors immediately.

By replacing my commands with dummy commands, it works so if I can navigate around this dependency I have, I think my issue will be solved
