### ISSUE TITLE
[QUESTION] how to forward message to a user without having chat with him/her before

### ISSUE THREAD

**Issue by alireza-saberi** [python-telegram-bot/python-telegram-bot#2866]
### Issue I am facing

Hi;

I like to forward a message from my private channel with my bot by just having an id from that user following style

`/forward msg# receiverID`

example 
`/forward 12 93349335`
or
`/forward 12 telgramUserName`

### Operating System

Window 11

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.7
python-telegram-bot: 
telegram-bot 5.6
```

**Comment by harshil21** [comment]
Hi,
It is impossible to do what you are asking for. This is stated in the [Bot API docs](https://core.telegram.org/bots#4-how-are-bots-different-from-humans).
