### ISSUE TITLE
[BUG] Non-english commands raise ValueError in CommandHandler

### ISSUE THREAD

**Issue by mishamsk** [python-telegram-bot/python-telegram-bot#2867]
### Steps to Reproduce

1. Try creating an instance of CommandHandler("привет", handler_func)

### Expected behaviour

A class instance is created

### Actual behaviour

ValueError('Command is not a valid bot command')

### Operating System

Mac OS

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.10 (v1.0.0-2-ga694230)
Bot API 5.6
certifi 2021.10.08
Python 3.10.1 (main, Dec  6 2021, 22:25:40) [Clang 13.0.0 (clang-1300.0.29.3)]
```

### Additional Context

lines 161-163 of CommandHandler.__init__ use an outdated regex...

```python
for comm in self.command:
    if not re.match(r'^[\da-z_]{1,32}$', comm):
         raise ValueError('Command is not a valid bot command')
```

**Comment by Poolitzer** [comment]
Hi, what makes you say the regex is outdated? The bot command can only contain English letters, underscores, and numbers.

**Comment by Bibo-Joshi** [comment]
See [the official API docs](https://core.telegram.org/bots/api#botcommand).

**Comment by mishamsk** [comment]
@Bibo-Joshi you are right. sorry. I was put off by this in the official [announcement](https://core.telegram.org/bots/api#june-25-2021) ![CleanShot 2022-01-17 at 10 02 54@2x](https://user-images.githubusercontent.com/5206955/149793407-ae228309-1e57-4889-a390-15887078e98f.png)

my bad. they could have spelled it better
