### ISSUE TITLE
API Policy: `ReplyMarkup`

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2868]
I just noticed that ptbs `telegram.ReplyMarkup` is in fact an invention of PTB, i.e. it's not defined by the official API docs. We should consider removing that class or at least making it private.

IISC it's currently only used for

* type hinting - that could easily be replaced by a type alias
* the static method `_check_keyboard_type` that's used in the inits of or `{Reply, Inline}KeyboardMarkup` - that could moved e.g. to `tg._utils`

Personally, I'd be in favor of just removing the class. @harshil21 IIRC you added the `_check_keyboard_type` method - what do you think?

**Comment by harshil21** [comment]
@Bibo-Joshi Yeah I&#x27;m good with just removing the class 👍

**Comment by harshil21** [comment]
what do you want to do with the references of this class in the bot methods? It's convenient to just click and see which one to use

**Comment by Bibo-Joshi** [comment]
> @Bibo-Joshi Yeah I'm good with just removing the class 👍

all right :) I see you already self-assigned 👌 

> what do you want to do with the references of this class in the bot methods? It's convenient to just click and see which one to use

IISC apart from the "base class:" references, there are only references in the type documentations of the `reply_markup` parameter. Here I would comply with the official bot API and just list `InlineKeyboardMarkup | ReplyKeyboardMarkup | ReplyKeyboardRemove | ForceReply`. for the type hint, we can ofc add `ReplyMarkup = Union[those 4]` to `tg._utils.types`
