### ISSUE TITLE
ChatAction TYPING

### ISSUE THREAD

**Issue by joaomsimoes** [python-telegram-bot/python-telegram-bot#2869]
### Issue I am facing

Hi!

I'm trying to implement the typing feature but it is not working... I even tried to follow the [documentation](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#send-a-chat-action)

Is this feature still working?

```python
def open_question_handler(update: Update, context: CallbackContext) -> None:
    """Semantic search"""
    context.bot.send_chat_action(chat_id=update.effective_message.chat_id, action=telegram.ChatAction.TYPING)
    answer = semantic_api(update.message.text)
    if answer[0]:
        update.message.reply_text(answer[0])
        update.message.reply_text(answer[1])
    else:
        update.message.reply_text("Sorry I did not understand what you want to say")
```

### Operating System

Windows 11

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.10
Bot API 5.6
Python 3.8.8
```

**Comment by Poolitzer** [comment]
Hi, yes it is. You should see a typing status for ~ 5 seconds above your bot. Do you not see it, is that your question?

**Comment by joaomsimoes** [comment]
My bad, it only shows in the mobile app, it doesn't show on the desktop. Sorry! But yes it is working!

Thanks!

**Comment by Poolitzer** [comment]
On a very much offtopic note, the desktop app displays the chat action just fine for me. You might want to report this as a bug with your setup to Telegram somewhere.
