### ISSUE TITLE
callback decorator

### ISSUE THREAD

**Issue by HK-Mattew** [python-telegram-bot/python-telegram-bot#2877]
### Issue I am facing

Hello

I would like to know how I can add a decorator to all callback functions at once. That is, without having to decorate function by function.

### Traceback to the issue

```python
a
```

### Related part of your code

```python
b
```

### Operating System

Kal1

### Version of Python, python-telegram-bot & dependencies

```shell
c
```

**Comment by Bibo-Joshi** [comment]
@HK-Mattew Hi. this doesn&#x27;t sound like something that PTB can help you with. Though searching &quot;python apply decorator dynamically&quot; yields some results that might help. Alternatively, please also have a look at <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#how-to-handle-updates-in-several-handlers">How to handle updates in several handlers</a> - maybe that already helps

**Comment by HK-Mattew** [comment]
Thanks, I'll see what I can do.
