### ISSUE TITLE
[QUESTION] How can I catch "reactions" updates in group chat?

### ISSUE THREAD

**Issue by PilgrimViis** [python-telegram-bot/python-telegram-bot#2879]
### Issue I am facing

Hi. Telegram recently introduced new "reactions" functionality. https://telegram.org/blog/reactions-spoilers-translations  People in group chat can post emojies (like, dislike, fire, etc) under a certain message. How can I catch events when people added a new reaction to a message in a group chat.

I've looked into MessageHandler, but I could not find any Filters that match "Reactions".

Thank you.

### Operating System

Any

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.10
Bot API 5.6
certifi 2021.10.08
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
```

**Comment by Poolitzer** [comment]
Hi. This library is a wrapper for the telegram bot API. As you can see in its documentation (https://core.telegram.org/bots/api#december-30-2021), they decided not to introduce reactions to bots in the December update. So there is no way to either do reactions or catch reactions.
