### ISSUE TITLE
[Question] Is there any way to handle requests in multiple threads?

### ISSUE THREAD

**Issue by SnShine** [python-telegram-bot/python-telegram-bot#288]
Hey,

I have built a bot which replies with images when passed a command. Currently, it is running on AWS, so internet speeds (~300Mb/s) aren't a problem. When simultaneously messaged from three devices, it took a lot of time to reply as dispatcher is handling requests in single thread.

So, is there anything I am missing, or any alternatives to do the job or any pointers to Telegram Bot API regarding this topic would be really appreciated.

**Comment by jh0ker** [comment]
Hi,

Yes, there is a decorator called `run_async` which you can use to mark functions to run in a seperate thread. Example:

```python
from telegram.ext.dispatcher import run_async

@run_async
def echo(bot, update):
  bot.sendMessage(update.message.chat_id, text=update.message.text)
```

The amount of concurrent threads is limited to 4 by default, but you can change it by passing `workers` when creating the `Updater` object.

**Comment by SnShine** [comment]
Thank you. I will see how this works.
