### ISSUE TITLE
Rename CommandHandler.command to CH.commands (plural) …

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2885]
… since it's always a list independent on whether the input was a single string or a list of strings. We might also think about making the attribute a set instead of a last, as checking `string in commands_set` is [significantly faster](https://stackoverflow.com/questions/2831212/python-sets-vs-lists) than `string in commands_list` and at least currently that's the only thing we use that attribute for

**Comment by Poolitzer** [comment]
Taken from your link, sets can only contain unique items. I am not saying it should break setups, but it can definitely break setups, we need to have this on our mind for the transition guide/breaking change list.
