### ISSUE TITLE
[Question] Build Your First Bot docs InlineQuery example doesn't work (again)

### ISSUE THREAD

**Issue by ZackPlauche** [python-telegram-bot/python-telegram-bot#2892]
### Steps to Reproduce

This is not off topic, please don't flag like the last one.

I copied verbatim from the "Your first bot" docs, and the inline query doesn't do anything.

How do we get it to work?

1. Copy the code that deals with the InlineQuery
2. Run it.
3. Try to use the Inline Query in chat with your bot
4. Nothing happens.

Also, maybe include a link or something to a description in how to trigger inline commands in the first place (_/-_-)_/

### Expected behaviour

I think literally anything should happen.

### Actual behaviour

Nothing happens in the chat.

### Operating System

windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
> This is not off topic, please don't flag like the last one.

I don't know which thread you're referring to

> How do we get it to work?

you'll have to enable inline mode with botfather

> Also, maybe include a link or something to a description in how to trigger inline commands in the first place (/--)_/

like the description [here](https://github.com/python-telegram-bot/python-telegram-bot/tree/master/examples#inlinebotpy)? 😉

**Comment by Bibo-Joshi** [comment]
I see. Well, it works fine for me. Please try restarting your client and also make sure that you actually type something - the example doesn't answer the inline query if it's empty.
If that still doesn't help, please set the logging level to debug so that you can see if the inline query actually reaches your bot.

**Comment by ZackPlauche** [comment]
Actually it does work, I was just tired and missed InputTextMessageContent instead of InputMessageContent lol
