### ISSUE TITLE
[QUESTION] Sending A array when all photo messages are received

### ISSUE THREAD

**Issue by alisaqi** [python-telegram-bot/python-telegram-bot#2894]
### Issue I am facing

Suppose I send 4 photos in one **message group** and each of the pictures has **its own message.id**. But **media_group_id** is obviously the same for these 4 pictures.

How can I write a loop to store these message.ids and **at the end of the loop**, send me a message? For example:

`print("all photos are received")`

### Operating System

Windows

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.9
```

**Comment by Poolitzer** [comment]
Hey, we get a question for this quite often. This is the reason why I decided to write it in our wiki for design patterns, check it out [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#how-do-i-deal-with-a-media-group). If that leaves open questions, please ask them here and I can respond/update the wiki.

**Comment by alisaqi** [comment]
> Hey, we get a question for this quite often. This is the reason why I decided to write it in our wiki for design patterns, check it out [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#how-do-i-deal-with-a-media-group). If that leaves open questions, please ask them here and I can respond/update the wiki.

Thanks for your idea. 

Could you please tell me how I can implement this pattern in my code? I read that page but I couldn't find how I can use that pattern in my code
