### ISSUE TITLE
Make Updater compatible with GAE

### ISSUE THREAD

**Issue by jh0ker** [python-telegram-bot/python-telegram-bot#290]
It seems that Google App Engine is still a good option to host python bots for free, but the `Updater` does not support it because the `signal` module is not supported. It should be easy to implement a fallback for that, if that's really all. The `idle` method would be unavailable then, but that should not be a problem.

To support webhooks as well, it might be an option to implement a webhook server that uses GAEs HTTP API.

**Comment by SalamiArmy** [comment]
Is python-telegram-bot really compatible with GAE? I get an error from Google:
> appcfg.py: error: Error parsing app.yaml: the library "python-telegram-bot" is not supported

**Comment by leandrotoledo** [comment]
@SalamiArmy it is. Try:

```
$ mkdir lib

$ pip install -t lib python-telegram-bot

$ vi appengine_config.py
from google.appengine.ext import vendor
vendor.add('lib')
```

**Comment by SalamiArmy** [comment]
Google accepts my code! But then I get unrecognized module errors, so I do your trick over and voer until I have all the modules:

> $ mkdir lib

> $ pip install -t lib future

> $ vi appengine_config.py
> from google.appengine.ext import vendor
> vendor.add('lib')

> $ mkdir lib

> $ pip install -t lib moves

> $ vi appengine_config.py
> from google.appengine.ext import vendor
> vendor.add('lib')

> $ mkdir lib

> $ pip install -t lib requests

> $ vi appengine_config.py
> from google.appengine.ext import vendor
> vendor.add('lib')

Etc. I'm still doing this, but it feels like I'm gonna end up with every python module in existence checked into my project directory by the time I get it running!

**Comment by leandrotoledo** [comment]
@SalamiArmy For this library you only need future module as dependency, if it is failing because of requests or moves or anything else it's probably because you are importing something else.

Check this example:
https://github.com/leandrotoledo/gae-devops-reaction-telegram-bot

**Comment by jh0ker** [comment]
closing because old
