### ISSUE TITLE
Handling of defaults for bot methods

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2900]
Currently we have a few places, where the default value in the signature specifies the default value specified by Telegram. This is both the case for bot methods and Telegram classes. E.g. in `send_poll`:

https://github.com/python-telegram-bot/python-telegram-bot/blob/92cb6f3ae8d5c3e49b9019a9348d4408135ffc95/telegram/bot.py#L5141-L5147

and in `ReplyKeyboardMarkup`:

https://github.com/python-telegram-bot/python-telegram-bot/blob/92cb6f3ae8d5c3e49b9019a9348d4408135ffc95/telegram/replykeyboardmarkup.py#L87-L92

More importantly, we pass those values to TG. This isn't really necessary, since we'd get the same behavior when not passing those parameters. This has two effects:

1. More params are getting passed -> more traffic than strictly necessary. admittedly, probably barely noticable, but still.
2. In case TG changes some defaults, the change will not be reflected in PTB until we change the signature.

While the first one is clearly a downside, one *might* argue that the second one does have some advantages in terms of stability. Personally, I'd rather comply with the current state of the bot API, but I'm open to discussing this.

In any case, I think we should do this uniformly, i.e. either reflect the default value in the signature everywhere or nowhere & try to unit test this in `test_official`. E.g. Currently e.g. the `emoji` parameter of `send_dice` has `None` as default value instead of `'🎲'`:

https://github.com/python-telegram-bot/python-telegram-bot/blob/92cb6f3ae8d5c3e49b9019a9348d4408135ffc95/telegram/bot.py#L5315-L5326

In case we go for removing the default values, some bot methods internals may be simplified.
Either change would be non-breaking since the current defaults in the signatures are up to date with the defaults documented in the API.

**Comment by Poolitzer** [comment]
> Personally, I'd rather comply with the current state of the bot API, but I'm open to discussing this.

That would be my stance as well
