### ISSUE TITLE
Is there any way to run a command while another command is already running in python-telegram-bot?

### ISSUE THREAD

**Issue by AdityaDas5501** [python-telegram-bot/python-telegram-bot#2915]
### Issue I am facing

Let's say there's an infinity loop inside the start function. while it's running... I need another command to run in the background. another function. (a stop command for an example). I tried multithreading and other methods but this commandHandler function is so stubborn, it only executes if there is no current process going on or the bot is idle. Please tell me how to run two commands simultaneously!!

### Operating System

Windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2020.12.05
Python 3.9.5 (default, May 27 2021, 19:45:35)  [GCC 9.3.0]
```

**Comment by Bibo-Joshi** [comment]
Hi. PTB comes with built-in functionality to run the callbacks of handlers in a thread of a thread pool. See [this wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Performance-Optimizations) for detailed information.

Note however that running infinite loops via that functionality still has downsides - more precisely it will block of thread of the pool and if you have multiple of such callbacks running, you might end up blocking all threads of the pool, effectively blocking your whole bot.

Depending on your use case, I'd recommend to either

* manually spawn a custom thread 
* use the [`JobQueue`](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-JobQueue) for recurring tasks

**Comment by Bibo-Joshi** [comment]
Hi. PTB comes with built-in functionality to run the callbacks of handlers in a thread of a thread pool. See [this wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Performance-Optimizations) for detailed information.

Note however that running infinite loops via that functionality still has downsides - more precisely it will block of thread of the pool and if you have multiple of such callbacks running, you might end up blocking all threads of the pool, effectively blocking your whole bot.

Depending on your use case, I'd recommend to either

* manually spawn a custom thread 
* use the [`JobQueue`](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-JobQueue) for recurring tasks

**Comment by AdityaDas5501** [comment]
> Hi. PTB comes with built-in functionality to run the callbacks of handlers in a thread of a thread pool. See [this wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Performance-Optimizations) for detailed information.
> 
> Note however that running infinite loops via that functionality still has downsides - more precisely it will block of thread of the pool and if you have multiple of such callbacks running, you might end up blocking all threads of the pool, effectively blocking your whole bot.
> 
> Depending on your use case, I'd recommend to either
> 
> * manually spawn a custom thread
> * use the [`JobQueue`](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-JobQueue) for recurring tasks

Hey Bibo-Joshwala, thank you/u for your reply
I am a noob in this telegram python thingy so I will hardly be able to understand something from a documentation 😔, so if you would take some pain to write a full code on sending two commands concurrently, I would e very happy 😄

Cheers
Adi, (ur mom)!

**Comment by Bibo-Joshi** [comment]
I won't write code for you, no. If you're new to PTB or Python in general, I recommend to start with the more basic usages and then slowly make your way to the more complicated setup.
