### ISSUE TITLE
[BUG] Wrong file identifier/http url specified

### ISSUE THREAD

**Issue by lucamaia9** [python-telegram-bot/python-telegram-bot#2917]
### Steps to Reproduce

For some reason, if I try to send the url image below it returns an error "Wrong file identifier/http url specified". The most weird thing is that it works for all images, except for this specific one.

url_that_works =               'https://media.rightmove.co.uk/55k/54616/120532730/54616_DAN191020_L_IMG_08_0000.jpeg'
url_that_gives_an_error = 'https://media.rightmove.co.uk/55k/54616/120532730/54616_DAN191020_L_IMG_07_0000.jpeg'
chat_id = CHAT_ID

updater.bot.send_photo(chat_id=5201841440, photo=url_that_gives_an_error , caption="Testing")

### Expected behaviour

The message should be sent without any problems, as url_that_works variable works fine.

### Actual behaviour

  File "E:\Anaconda3\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "E:\Anaconda3\lib\site-packages\telegram\bot.py", line 729, in send_photo
    return self._message(  # type: ignore[return-value]
  File "E:\Anaconda3\lib\site-packages\telegram\ext\extbot.py", line 200, in _message
    result = super()._message(
  File "E:\Anaconda3\lib\site-packages\telegram\bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "E:\Anaconda3\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "E:\Anaconda3\lib\site-packages\telegram\utils\request.py", line 367, in post
    result = self._request_wrapper(
  File "E:\Anaconda3\lib\site-packages\telegram\utils\request.py", line 285, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: **Wrong file identifier/http url specified**

### Operating System

Windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
```

**Comment by aditya-yadav-27** [comment]
This is not a bug tho, IMO its something wrong in the image I am not sure what, but yes

**Comment by Bibo-Joshi** [comment]
Hi. I agree with @aditya-yadav-27. The error message you see is not issued by `python-telegram-bot` but directly by Telegram. To verify that the issue is not with `python-telegram-bot`, you can make the request manually via your browser/postman/curl/... .

In fact this error message is rather frequently reported by users who try to send a file via URL. Telegram seems to be picky about which URLs it accepts. One thing that they explicitly mention [in the docs](https://core.telegram.org/bots/api#sending-files) is that Telegram must be able to guess the mime type from the URL - though I can't judge whether or not that is the problem here

**Comment by lucamaia9** [comment]
I see, I changed my code to manually requests all the images and pass them as raw images (without altering any property of the image) instead and it worked flawlessly.

Even though it is a telegram problem, I will try to find out will telegram triggers this error. One possible smarter solution is to request the image file from the url manually using a request if a given image url returns this error.
