### ISSUE TITLE
What type of things can I put in the queue returned by start_polling?

### ISSUE THREAD

**Issue by boatcoder** [python-telegram-bot/python-telegram-bot#2919]
### Issue I am facing

This is what the docs (in the code say)
```
        Returns:
            :obj:`Queue`: The update queue that can be filled from the main thread.
```

All I have to work with from readthedocs is

> [](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.updater.html#telegram.ext.Updater.update_queue)update_queue
Queue for the updates.
>
>Type
>Queue

What I'm having trouble discovering is WHAT kind of objects I can put into that queue.  Is there a page that explains this somewhere?  googling for the [`update_queue`](https://www.google.com/search?q=update_queue+site%3Acore.telegram.org&rlz=1C5CHFA_enMX982MX982&oq=update_queue+site%3Acore.telegram.org&aqs=chrome..69i57.3406j0j4&sourceid=chrome&ie=UTF-8) in the telegram docs doesn't find anything.

I'm assuming I don't put jobs into this queue since there is a `job_queue`

So, where is the interface doc for that the update_queue?

### Operating System

MacOS

### Version of Python, python-telegram-bot & dependencies

```shell
python3.10
python-telegram-bot==13.11
```

**Comment by Poolitzer** [comment]
Hi, you can put literally any class into it, and if you register a TypeHandler for the class, it will be triggered by the dispatcher. My understanding at least.
