### ISSUE TITLE
[BUG] APScheduler version is too restrictive

### ISSUE THREAD

**Issue by lbenc135** [python-telegram-bot/python-telegram-bot#2929]
### Steps to Reproduce

1. pip install -U python-telegram-bot apscheduler==3.9.1

### Expected behaviour

Should successfully install.

### Actual behaviour

`python-telegram-bot 13.11 requires APScheduler==3.6.3, but you have apscheduler 3.9.1 which is incompatible.`

### Operating System

Ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.9.7 (default, Sep 10 2021, 14:59:43)  [GCC 11.2.0]
```

**Comment by Bibo-Joshi** [comment]
Updating our policy for dependencies is on the todo list for v14. For discussion, see #2758 and the threads linked in that issue. Closing as duplicate.
