### ISSUE TITLE
[BUG] python-telegram-bot 13.11 does not provide the extra 'ujson'

### ISSUE THREAD

**Issue by setop** [python-telegram-bot/python-telegram-bot#2930]
### Steps to Reproduce

1. `pip install python-telegram-bot[ujson]`

### Expected behaviour

last version of python-telegram-bot, 13.11, with ujson extra dep, is installed, as suggested by the readme.

### Actual behaviour

get `WARNING: python-telegram-bot 13.11 does not provide the extra 'ujson'` and extra dep is not installed.

### Operating System

linux

### Version of Python, python-telegram-bot & dependencies

```shell
* python-telegram-bot 13.11
* Bot API 5.7
* certifi 2021.10.08
* Python 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
```

**Comment by Bibo-Joshi** [comment]
Hi. That's a typo in the readme. please use `pip install python-telegram-bot[json]`.
