### ISSUE TITLE
No error handlers are registered, logging exception.

### ISSUE THREAD

**Issue by NPS-Dive** [python-telegram-bot/python-telegram-bot#2931]
### Issue I am facing

Hi, There

I've got confused. could you please help and let me know what is the problem?

### Traceback to the issue

```python
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Program Files\Python310\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "C:\Telegram\04_bot.py", line 7, in start_handler
    chat_id = update.message.chat_id
AttributeError: 'CallbackContext' object has no attribute 'message'
```

### Related part of your code

```python
from telegram.ext import Updater, CommandHandler

token = "*****"


def start_handler(bot, update):
    chat_id = update.message.chat_id
    first_name = update.message.chat.first_name
    last_name = update.message.chat.last_name
    bot.sendMessage(chat_id, "Hi Dear {0} {1}".format(first_name, last_name))


updater = Updater(token)

start_command = CommandHandler("start", start_handler)

updater.dispatcher.add_handler(start_command)

updater.start_polling()

updater.idle()
```

### Operating System

Win-10 X64

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
```

**Comment by NPS-Dive** [comment]
> Hi. This is a perfect example why you should always take 3rd party tutorials for _anything_ with a grain of salt. The authors of those often don't update them when there is an update to the library they cover. If you look [at any](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-Your-first-Bot#your-first-bot-step-by-step) of [the examples](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/echobot.py#L33) we [provide](https://python-telegram-bot.org/), you would not have ended up with `def start_handler(bot, update):`, which is depreciated since 2 1/2 years now. Replace it with `def start_handler(update, context):` and you are good to go.

Dear Poolitzer;
tnx a million, I have done as you guided.
but another issue arose as follows:
raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5098406595:AAHnKw-W-_SqlrYIXcKtreesCyiI8yrIrnM/getMe (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000028040FD1BD0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))

I have not got the idea what would it mean. I have flushed my DNS, changed it to a lower time DNS and even used a vpn. But I get the "connection time-out" message...
would you kindly please let me know what shall I do then?

**Comment by Poolitzer** [comment]
First of all, you need to revoke your bot token because you just posted it here.

There is not much one can help you with network issues though. You can try pinging api.telegram.org from the server and if that works, check if a python request outside of the library goes through. I am quite certain one of these will fail, and you can debug from there. Not an issue of this library though.

**Comment by NPS-Dive** [comment]
> pinging api.telegram.org from the server

done it from my CMD and seems to be away:

Pinging api.telegram.org [10.10.34.35] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Once again, thank you very much of your kind supports
