### ISSUE TITLE
How do I send a picture?

### ISSUE THREAD

**Issue by tanzerlana** [python-telegram-bot/python-telegram-bot#2939]
### Issue I am facing

Hello!

I've not been able to find it in the samples, and what I found online refers to the old version of this library. I would like to have the bot send images over taken with a webcam. The images are in numpy.ndarray but I can convert them to other formats.

What I would like to do is to send these images over in chat as answer to the command /sendpic

could ou please help me out on this? 

Thank you!

### Operating System

windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
@tanzerlana please have a look at the docs of <a href="https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.send_photo">telegram.Bot.send_photo</a> <a href="https://core.telegram.org/bots/api#sendphoto">ᵀᴱᴸᴱᴳᴿᴬᴹ</a> and <a href="https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html#telegram.Message.reply_photo">telegram.Message.reply_photo</a> <a href="https://core.telegram.org/bots/api#message">ᵀᴱᴸᴱᴳᴿᴬᴹ</a> as well as the wiki section on <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#working-with-files-and-media">Working with files and media</a>

**Comment by tanzerlana** [comment]
@Bibo-Joshi I think I am missing one link in my understanding of the library.. Those comands refer to a "bot". The example I checked (echo bot) refers to a "updater". how do these two relate?

**Comment by Bibo-Joshi** [comment]
the `telegram` package contains a pure wrapper for the Bot API and the class `telegram.Bot` exposes the methods of the API. the `telegram.ext` package contains classes that go beyond the pure API and are intended to make it easy to write chat bots. Of course for that you still need the `telegram` package, in particular a `Bot`. In the context of `telegram.ext.`, the latter is usually available as `updater/dispatcher.context.bot`.

Please have a look at the [introduction to the api](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Introduction-to-the-API) as well as the [tutorial your first bot](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-–-Your-first-Bot) for a more detailed introduction.
