### ISSUE TITLE
Send numpy array as image

### ISSUE THREAD

**Issue by tanzerlana** [python-telegram-bot/python-telegram-bot#2941]
### Issue I am facing

Hello

I've been able to send a image that is saved on the disk, but I would need to send a image that is not on the disk. I have it in memory as a numpy.ndarray. 

Is there a way to send this image or do i have to save it to disk first?

Thank you

Best regards

### Operating System

windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
It would suffice to convert it to an image in memory as `send_message` accepts bytes as input. But you don't necessarily have to write those bytes to file.

**Comment by tanzerlana** [comment]
Thank you, 

I tried like this:

    def sendImage(self, score, im0):
        PIL_image = Image.fromarray(numpy.uint8(im0)).convert('RGB')
        self.bot.send_photo(-123456789, PIL_image, f'{score:0.2f}')

but get the message: 

TypeError: Object of type Image is not JSON serializable

**Comment by Bibo-Joshi** [comment]
`PIL_image` is an instance of pillows `Image` class and not of type `bytes`. try [`PIL_images.tobytes()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.tobytes).

**Comment by tanzerlana** [comment]
thank you very much.. now i get the message telegram.error.BadRequest: Image_process_failed

I assume that now the problem is in the conversion. thank you very much for your help!

**Comment by tanzerlana** [comment]
I just tried to save the image with:

PIL_image.save("c:/yolov5/test.png")

and the image is correct... any idea of what might be the cause then?

**Comment by Bibo-Joshi** [comment]
Apparently `tobytes()` doesn't return a format that TG likes. I dug up how I did this a while ago: https://gitlab.com/HirschHeissIch/twitter-status-bot/-/blob/master/bot/utils.py#L19-38 (`build_sticker` returns a pillow `Image`), which is then used [here](https://gitlab.com/HirschHeissIch/twitter-status-bot/-/blob/master/bot/commands.py#L32-33).

**Comment by tanzerlana** [comment]
this worked like a charm! thank you very much!!!
