### ISSUE TITLE
How to write on multiple lines?

### ISSUE THREAD

**Issue by tanzerlana** [python-telegram-bot/python-telegram-bot#2942]
### Issue I am facing

Hello! I would like to write a message over multiple lines, but \n does not work. 

How can I write a message on multiple rows?

text = depot + '\\n\\nScore: ' + f'{score:0.2f}' + '\\nNr. crate: ' + classname

outputs:

halle\n\nScore: 0.86\nNr. crate: 136

thank you!

### Operating System

windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
please show a code snippet of how you send the text to the user.

**Comment by tanzerlana** [comment]
text = depot + '\\n\\nScore: ' + f'{score:0.2f}' + '\\nRec. crate: ' + classname
        self.bot.send_photo(-720329337, image_stream, text)

I am appending it to the photo..

**Comment by Bibo-Joshi** [comment]
> ```
>     text = depot + '\\n\\nScore: ' + f'{score:0.2f}' + '\\nRec. crate: ' + classname
>     self.bot.send_photo(-720329337, image_stream, text)
> ```

in this snippet you're escaping the line breaks, which is not what you showed above. use `\n` instead of `\\n`.

**Comment by tanzerlana** [comment]
thank you. the text in the first message has been edited automatically somehow, as I copied and pasted it. didnt notcie it. 

thank you for your help!
