### ISSUE TITLE
How to post an image or video?

### ISSUE THREAD

**Issue by magnusso** [python-telegram-bot/python-telegram-bot#2953]
### Issue I am facing

Could someone please provide a minimal example of how to post an image or video. I've tried to modify the echo example, but I'm stuck with creating a working handler.  

### Operating System

Linux

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2018.08.24
Python 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
```

**Comment by Poolitzer** [comment]
Hi, you dont even need to create a new working handler. You can replace line 49 with or append to it something like
```python
update.message.reply_photo("https://raw.githubusercontent.com/python-telegram-bot/python-telegram-bot/master/tests/data/telegram.png", caption=update.message.text)

update.message.reply_video(open("path/to/file.video", "rb"), caption=update.message.text)
```

**Comment by Alfro** [comment]
Can confirm Poolitzer code applied on the echobot.py example works as intended.

@magnusso could you give it a look and maybe close the issue if it works for you?

If you have trouble locating exactly where the ``reply_photo / reply_video`` should go, you just have to modify the echo function.

Like so:
```python
def echo(update: Update, context: CallbackContext) -> None:
    update.message.reply_photo("https://raw.githubusercontent.com/python-telegram-bot/python-telegram-bot/master/tests/data/telegram.png", caption=update.message.text)
    update.message.reply_video(open("path/to/file.video", "rb"), caption=update.message.text)
```
