### ISSUE TITLE
[QUESTION] New tg feature, js web apss

### ISSUE THREAD

**Issue by rokv1l** [python-telegram-bot/python-telegram-bot#2955]
### Issue I am facing

Hello. As we know, tg add a new feature to bots. Now devs can use js to making apps directly in the bot. Will this feature implemented in python telegram bot? Or may be this is implemented already. I tried to search info about that, but found nothing : (

Example of new feature u can see here - https://t.me/durgerkingbot

Im so sorry if this question already answered

### Operating System

-

### Version of Python, python-telegram-bot & dependencies

```shell
-
```

**Comment by harshil21** [comment]
See #2954
