### ISSUE TITLE
After update python-telegram-bot api doesnt work handlers

### ISSUE THREAD

**Issue by q121212** [python-telegram-bot/python-telegram-bot#296]
$ ./bot.py 
Traceback (most recent call last):
  File "./bot.py", line 330, in <module>
    main()
  File "./bot.py", line 296, in main
    dp.addHandler(CommandHandler("start", start))
NameError: name 'CommandHandler' is not defined

in my code line 296:
dp.addHandler(CommandHandler("start", start))

--------
if i check:
print(dir(dp))

$ ./bot.py 
['_Dispatcher__exception_event', '_Dispatcher__stop_event', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'addErrorHandler', 'addHandler', 'add_error_handler', 'add_handler', 'bot', 'dispatchError', 'error_handlers', 'groups', 'handlers', 'logger', 'm', 'processUpdate', 'removeErrorHandler', 'removeHandler', 'remove_error_handler', 'remove_handler', 'running', 'start', 'stop', 'update_queue']

-------------
if I check:
print(dp.add_handler.__code__.co_varnames) 

$ ./bot.py 
('self', 'handler', 'group')
---------------------------

I think something happens after update api of python-telegram-bot, but in exaples at github in all of files we can see the code like this:
    dp.add_handler(CommandHandler("start", start))

I tried write code in the same manner, but the same trouble happend

**Comment by leandrotoledo** [comment]
@q121212 Have you tried to import CommandHandler?
from telegram.ext import CommandHandler

**Comment by q121212** [comment]
Oh, thank you! that's a good idea, and with this import everything is working!
