### ISSUE TITLE
[FEATURE] Set SocketOpts

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#2965]
To improve the networking backend, we would like to set socketopts if possible. Before the `asyncio` switch, we did something like

https://github.com/python-telegram-bot/python-telegram-bot/blob/ad5a1fb1f6a01f5f662e9e610ddb77fb57558e44/telegram/request/_httpxrequest.py#L164-L168

It would be nice if we could do that for httpx as well at some point.

**Comment by Delhibabu1** [comment]
import httpx
import socket

# create a socket stream
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
stream = httpx.SocketStream(sock)

# set TCP keepalive options for Linux and macOS
if platform.system() == 'Linux':
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPIDLE, 120)
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPINTVL, 30)
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPCNT, 8)
elif platform.system() == 'Darwin': # macOS
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPALIVE, 1)
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPINTVL, 10)
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPCNT, 3)

# create an httpx client with the socket stream
client = httpx.Client(transport=httpx.Transports(sockets=[stream]))

This code sets the TCP keepalive options on a socket object and creates an 'httpx' client with a SocketStream transport using the socket. You can replace the TCP options and the httpx client parameters with your own values as needed.
I think this code will be useful for httpx

**Comment by Delhibabu1** [comment]
Sure, the httpx version '0.18.1' and above include the 'SocketStream' class and the 'Transport' class

**Comment by Bibo-Joshi** [comment]
Unfortunately I can confirm that neither for [v0.18.1](https://github.com/encode/httpx/blob/0.18.1/httpx/__init__.py) nor for the current [v0.24.0](https://github.com/encode/httpx/blob/0.24.0/httpx/__init__.py).

**Comment by Delhibabu1** [comment]
It works for v0.18.1 and greater version

**Comment by clot27** [comment]
> It works for v0.18.1 and greater version

It doesnt atleast for me, gives following error:
```
Traceback (most recent call last):
  File "/home/abc/main.py", line 5, in <module>
    stream = httpx.SocketStream(sock)
AttributeError: module 'httpx' has no attribute 'SocketStream'
```

**Comment by Delhibabu1** [comment]
import httpx
import ssl
import socket

# create an SSL context with the TCP keepalive options set
context = ssl.create_default_context()
context.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)
context.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPIDLE, 120)
context.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPINTVL, 30)
context.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPCNT, 8)

# create an httpx client with the SSL context
client = httpx.Client(http2=True, verify=False, ssl=context)

# make requests using the client...

can you try this code .This code creates an 'SSL' context with the TCP keepalive options set, and passes it to the httpx.Client constructor as the ssl parameter.

**Comment by Bibo-Joshi** [comment]
httpx v0.25.0 added support for `socket_options` in encode/httpx#2716. The underlying change is encode/httpcore#668 and some documentation can be found [here](https://www.encode.io/httpcore/async/#httpcore.AsyncConnectionPool.__init__) and [here](https://github.com/encode/httpx/issues/2715#issue-1721830338).
This might give us a handle to add support for socket options as well. CC @tsnoam
