### ISSUE TITLE
[sphinx build] Adding linkcheck test

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#2974]
In my asyncio "review", I saw that somebody inserted a 404 link into the docstring. Apart from daring to do that to our docs (shame on them), existing links can break as well. SO I researched a bit and found the `linkcheck` build option of sphinx. We can run this like once a week. I am quite sure we have to parse the output since it doesn't break when it finds a non working link, but that shouldn't be too much work _TM_. From me messing around with it, we should definitely exclude our changelist file since it has too many github links and it doesn't matter too much if those break IMO.

Buildname linkcheck: https://www.sphinx-doc.org/en/master/man/sphinx-build.html

Config: https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-the-linkcheck-builder

After a short internal discussion, we want to different test triggers:
 - [ ] once/twice per month, on the whole docs
 - [ ] on a PR/push, only on the changed files.

**Comment by Bibo-Joshi** [comment]
nice idea 👍 

We run sphinx in nitpicky mode already, so warnings should probably already be converted to errors 🤔 In addition to running on schedule (once a month may be enough?), we can integrate this into the existing doc-building test. via `docs/source/conf.py` it should be possible to enable the link checking only when in the GitHub CI, such that it doesn't slow down local builds.

**Comment by Poolitzer** [comment]
> We run sphinx in nitpicky mode already, so warnings should probably already be converted to errors thinking

Didn't test this, sure, might be

> once a month may be enough?

Yeah probably

> via docs/source/conf.py it should be possible to enable the link checking only when in the GitHub CI

This is a different builder, I dont think you have to make the effort. It's not in the pre-commit hooks or part of pytest, right? So unless someone explicitly calls it, its not included in local builds.

**Comment by Bibo-Joshi** [comment]
> This is a different builder, I dont think you have to make the effort. It's not in the pre-commit hooks or part of pytest, right? So unless someone explicitly calls it, its not included in local builds.

Ah, now I get it! Still, one could add it as another command to run in [this workflow](https://github.com/python-telegram-bot/python-telegram-bot/blob/v14/.github/workflows/docs.yml).

**Comment by Poolitzer** [comment]
@Bibo-Joshi that one runs on PR/pushes, since we both agree only once per X weeks is required, I guess a new workflow file will be more appropriate.
