### ISSUE TITLE
Runtime check of any value in Filters

### ISSUE THREAD

**Issue by Kemsekov** [python-telegram-bot/python-telegram-bot#2976]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

I missing something like this
```py
dispatcher.add_handler(MessageHandler(Filters.where(db.get(chat_id) is not None), handler)
```
So at any given request it will check if chat_id of request is in database and invoke handler only if it is satisfies condition.

### Describe the solution you'd like

Add new functionality to `Filters` so it will be more flexible

### Describe alternatives you've considered

I am facing hard times finding alternatives. Pattern `chain of responsability` will do the trick, or making your own single
`MessageHandler` that will accept all messages and redirect them, but I fear to write a lot of code because it need to be tested, which is a lot of effort for me

**Comment by Poolitzer** [comment]
Hi, maybe I am missing the point, but have you thought about defining your own filter? https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-Advanced-Filters#custom-filters. They are invoked at runtime, so if I don't misunderstand your setup, that should work...

**Comment by Kemsekov** [comment]
@Poolitzer it will help. Thanks
