### ISSUE TITLE
pinned_message() returns None

### ISSUE THREAD

**Issue by tanzerlana** [python-telegram-bot/python-telegram-bot#2979]
### Steps to Reproduce

1. Create a supergroup
2. add your bot with privacy settings disabled and/or set the bot to administrator
3. pin a message
4. try to get the pinned message using bot.get_chat(-xxxxxxxxxxx).pinned_message

### Expected behaviour

should return the message that has been pinned last

### Actual behaviour

returns "none"

### Operating System

windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:00) [MSC v.1929 64 bit (AMD64)]
```

**Comment by Poolitzer** [comment]
Hey, I did the exact step by step guide, worked just fine for me.

**Comment by tanzerlana** [comment]
@Poolitzer thank you, then probably there is something else I am doing wrong..

I am actually using only 2 lines of code to try this:


        bot = telegram.Bot(token='5104489088:AxxxxxxxxxxxxxxxxxxxxxxxxxxZw54pi-s')
        print(bot.get_chat(-720311111).pinned_message)

am I missing something?

![image](https://user-images.githubusercontent.com/67956327/165692110-09441bce-5e68-4e8c-a2bd-877570084953.png)

![image](https://user-images.githubusercontent.com/67956327/165692159-adac4a43-5273-46ae-b1ea-2da2055194b7.png)

![image](https://user-images.githubusercontent.com/67956327/165692347-cb127d71-447f-481d-a97f-3f8312ccdf50.png)

**Comment by Poolitzer** [comment]
That is not a supergroup, thats a normal group. Let me test that, if it doesn't work then its a not documented limitation of the api.

**Comment by Poolitzer** [comment]
My bot with default admin rights get the pinned message after its promotion, it didn't get it without.

**Comment by tanzerlana** [comment]
how can you determine that it is a normal group? according to plus messenger it is a supergroup, and also i can select if it is private or public. that feature is not available in normal groups afaik...

![image](https://user-images.githubusercontent.com/67956327/165693311-4ec555d2-0edd-4325-9b2a-12ef79afbd03.png)

----

my bot is admin and also with privacy disabled.. but I still cant read the message.

**Comment by Poolitzer** [comment]
> how can you determine that it is a normal group?

Its ID doesn't start with 100. If you don't believe me, do `get_chat().type`, it will be group and not supergroup.

**Comment by tanzerlana** [comment]
BINGO!!!! that was the problem. The ID is the old one.. Thank you very much!
