### ISSUE TITLE
telegram.error.BadRequest: Can't parse entities: unsupported start tag

### ISSUE THREAD

**Issue by gitpull2** [python-telegram-bot/python-telegram-bot#2981]
### Steps to Reproduce

```
from telegram.bot import Bot
my_bot=Bot(token="<bot token>")
my_bot.send_message(chat_id=1234,parse_mode="HTML",text="<<b>1234</b>")
```

### Expected behaviour

Sends message to `chat_id `: <**1234**

### Actual behaviour

`telegram.error.BadRequest: Can't parse entities: unsupported start tag "<b" at byte offset 0
`

### Operating System

Windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.05.30
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 16:30:00) [MSC v.1900 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
You have `<` too much in the `text`

**Comment by gitpull2** [comment]
I want to send the `<` . See the `Expected behaviour` section

**Comment by Poolitzer** [comment]
The library can not possibly know which part of your string is an intended character and which you want to escape. If you want to do this, just split up your strings and use html.escape() on the parts in between your tags.

**Comment by hammersharkfish** [comment]
> The library can not possibly know which part of your string is an intended character and which you want to escape.  

We could have a method which escapes any non-formatting HTML entities  . The amount of people who would want to send `<b>Some Text</b>`  as the text would be miniscule . More often then not they would want to make` Some Text` `bold `.  So text like this  `For a <b>Triangle</b> : Side1+side2>side3`  gets transformed into ` For a <b>Triangle</b> : Side1+side2&gt;side3` using the new method . 
 
> If you want to do this, just split up your strings and use html.escape() on the parts in between your tags.

Splitting -> manually escaping-> Putting it back  is still some task.

**Comment by gitpull2** [comment]
> The library can not possibly know which part of your string is an intended character and which you want to escape.

We could have a method which escapes any non-formatting HTML entities . The amount of people who would want to send `<b>Some Text</b>` as the text would be miniscule . More often then not they would want to make `Some Text ``bold `. So text like this `<b>Triangle</b> : Side1+side2>side3 `gets transformed into ` <b>Triangle</b> : Side1+side2&gt;side3` using the new method .

>If you want to do this, just split up your strings and use html.escape() on the parts in between your tags.

Splitting -> manually escaping-> Putting it back is still some task.

**Comment by Bibo-Joshi** [comment]
This is still not easy.

> `In TGs HTML markup, you have to write <code>&lt;</code> instead of the "lesser than" sign.`

Do you want the `&` to be escaped or not? It's clear to a human, but how should a parser function know?

Such a functionality can only ever cover a subset of all use cases and cause confusion with users whose use case is not covered. IMO it is not a good fit for a general purpose library like PTB.
That said, it may be a good fit for ptbcontrib. If you like to, you can PR over there.
