### ISSUE TITLE
How can my bot download a file?

### ISSUE THREAD

**Issue by tanzerlana** [python-telegram-bot/python-telegram-bot#2982]
### Issue I am facing

Hello!

I have a message that contains a file. i would liek to download this file to a specific path. 

So the first thing i need to do is to check if this message even has a file. I would do this by checking if the file_id exists. Does this make any sense or is there a better way to do this?

then once i know that there is a file attached to the message I would like to download it, but following code returns a file size error. 

        bot.get_chat(-100111111111).pinned_message.document.get_file()

telegram.error.BadRequest: File is too big

After googeling a bit I found out that the file size is limited to 20 MB via the http bot api, and my file is 27 mb in size.

Is there a way around this limitation? 

Also, how can I specify the download path/filename?

Thank you very much!

### Operating System

windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:00) [MSC v.1929 64 bit (AMD64)]
```

**Comment by Poolitzer** [comment]
> Does this make any sense or is there a better way to do this?

You can also use https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html#telegram.Message.effective_attachment, but if you know its always a document and not something else, `if message.document `will be fine

> Is there a way around this limitation?

You can run a local bot api service or use the MTproto api. Or you make the document smaller by putting it in an archive with high compression.

> Also, how can I specify the download path/filename?

First argument of the download call, see https://python-telegram-bot.readthedocs.io/en/stable/telegram.file.html#telegram.File.download

**Comment by tanzerlana** [comment]
> if message.document will be fine
great thank you

> You can run a local bot api service or use the MTproto api. Or you make the document smaller by putting it in an archive with high compression.
compression only gets it down to 23 mega so i have to try the other way with mtproto api. will google what it is and how to do it.

>First argument of the download call, see https://python-telegram-bot.readthedocs.io/en/stable/telegram.file.html#telegram.File.download

now I am a little confused. if download is used to download hte files, what is get_file() then? 

thank you for all your precious help! its very appreciated

**Comment by Poolitzer** [comment]
@tanzerlana ´get_file makes the file ready to download on telegrams side, and then download actually requests the file from your bot side

**Comment by tanzerlana** [comment]
@Poolitzer so I first call the get_file and then the download?

as for the MTproto api, is it supported by python-telegram-bot?

**Comment by Poolitzer** [comment]
> so I first call the get_file and then the download?

yes, so `bot.get_chat(-100111111111).pinned_message.document.get_file().download("path/to"file.file")` would be the full call to get the file on your system

> is it supported by python-telegram-bot?
nope, thats a different API from telegram
