### ISSUE TITLE
run bot on different thread gives error

### ISSUE THREAD

**Issue by tanzerlana** [python-telegram-bot/python-telegram-bot#2985]
### Issue I am facing

Hi all!

For my needs, I have to run the bot on a QThread. The idea is to start a new, clean thread, instantiate a bot, do some stuff, and when its done kill the thread. it works and does everything I expect it to do, but when the thread is done it gives this error:

sys:1: ResourceWarning: unclosed <socket.socket fd=552, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 65293), raddr=('127.0.0.1', 65291)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback

to reproduce it, simply run following code on a QThread:

```
  def sendTextMessage(self):
        bot = telegram.Bot(token='mytoken...')
        bot.sendMessage(-100111111111, text)
```

how can this be solved?

thank you!

### Operating System

windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:00) [MSC v.1929 64 bit (AMD64)]
```

**Comment by harshil21** [comment]
Hi, thanks for this issue.

It is hard to discern where this warning is originating from. IIRC, we had this issue in our test suite too. My guess is that its coming from `tornado`. Since there's not much we can do, I would just ignore this warning.

**Comment by Poolitzer** [comment]
Probably also important to state that we will release the asyncio rewrite soonish and wont do much support for the threaded version...
