### ISSUE TITLE
[QUESTION] ImportError: Cannot import Update from telegram

### ISSUE THREAD

**Issue by rideordieGTi** [python-telegram-bot/python-telegram-bot#2988]
### Issue I am facing

Hey team, 

Getting error in Pycharm with this package, see logs

### Traceback to the issue

```python
from telegram import Update
ImportError: cannot import name 'Update' from 'telegram' (unknown location)
```

### Related part of your code

```python
import logging
from telegram import Update
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters, CallbackContext

updater = Updater(token=mytoken, use_context=True)
dispatcher = updater.dispatcher

logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    level=logging.DEBUG)


def start(update: Update, context: CallbackContext):
    context.bot.send_message(chat_id=update.effective_chat.id,
                             text="Send commands, I'll obey")


start_handler = CommandHandler('start', start)
dispatcher.add_handler(start_handler)

updater.start_polling()
```

### Operating System

Ubuntu 20.04

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot v 13.11
Python 3.8.10

PyCharm 2021.2.3 (Community Edition)
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Current Desktop: Budgie:GNOME
```

**Comment by aditya-yadav-27** [comment]
Make sure you installed python-telegram-bot in correct environment (venv)

**Comment by rideordieGTi** [comment]
Its installed with the interpreter in pycharm in /venv

**Comment by harshil21** [comment]
@rideordieGTi Wiki of <i>python-telegram-bot</i> - Category <i>FAQ</i>
<a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#why-am-i-getting-importerror-cannot-import-name-xy-from-telegram">Why am I getting ImportError: cannot import name &#x27;XY&#x27; from &#x27;telegram&#x27;?</a>
