### ISSUE TITLE
Does telegram.ext.Updater prevent re-entrancy when polling ?

### ISSUE THREAD

**Issue by gitpull2** [python-telegram-bot/python-telegram-bot#2993]
### Issue I am facing

Do we have to handle re-entrancy manually by storing the `update_id ` or does this library handle that .  

### Operating System

windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
```

**Comment by Bibo-Joshi** [comment]
`Updater.start_polling` passes the `offset` parameter to `get_updates`, which marks the received updates as seen. So there is no need to store anything.

**Comment by gitpull2** [comment]
So in case the same message is re-sent by telegram (which will carry the same update_id) it will be ignored ?

**Comment by Bibo-Joshi** [comment]
once an update is marked as "received" (through the `offset` parameter), Telegram discards it and you can't retrieve it again.

**Comment by gitpull2** [comment]
> once an update is marked as "received" (through the `offset` parameter), Telegram discards it and you can't retrieve it again.
Thanks
