### ISSUE TITLE
[QUESTION] Unable to import ParseMode

### ISSUE THREAD

**Issue by super22n** [python-telegram-bot/python-telegram-bot#3005]
### Issue I am facing

I noticed some articles were updated recently, so I just downloaded python-telegram-bot again and now when I try to run my code, I get an error saying that I cannot import ParseMode. I am using ParseMode to send a message to Telegram. 

### Traceback to the issue

```python
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    from telegram import Update, ParseMode
ImportError: cannot import name 'ParseMode' from 'telegram' (/usr/local/lib/python3.7/dist-packages/python_telegram_bot-20.0a0-py3.7.egg/telegram/__init__.py)
```

### Related part of your code

```python
from telegram import Update, ParseMode
async def start(update, context):
    await context.bot.send_message(chat_id=update.message.chat_id, text="My text", parse_mode=ParseMode.MARKDOWN)
```

### Operating System

Debian 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a0
Bot API 6.0
Python 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
```

**Comment by harshil21** [comment]
@super22n as per <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-20.0">Version 20</a> you need to use from telegram.constants import ParseMode

**Comment by super22n** [comment]
Ah I see. Ok it works now thanks.
