### ISSUE TITLE
[Type Hinting] Pylance can't infer type of `CallbackContext.DEFAULT_TYPE`

### ISSUE THREAD

**Issue by harshil21** [python-telegram-bot/python-telegram-bot#3008]
### Steps to Reproduce

1. Start typing `context.bot.` in vscode with pylance
2. No type hints/autocomplete is available since pylance cannot infer the type of `CallbackContext.DEFAULT_TYPE`

The same applies for rest: `UD`, `CD`, `BD` (user/chat/bot_data)

### Expected behaviour

Pylance could maybe infer the type and give autocomplete suggestions? But I wouldn't expect it to.

### Actual behaviour

It doesn't infer the type correctly.

Possible solution: Remove `CallbackContext.DEFAULT_TYPE` and add a `CallbackContextType`  (or similar naming) where that would be simply `CallbackContext[ExtBot, Dict, Dict, Dict]`. We could keep this in the same file too.

### Operating System

Linux, Ubuntu 22.04

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a0
Bot API 6.0
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
```

### Relevant log output

```python
-
```

### Additional Context

Originally reported here: https://t.me/pythontelegrambottalk/218000

**Comment by Bibo-Joshi** [comment]
Is this related to https://github.com/microsoft/pylance-release/issues/1983 & the `--verifytypes` option? In PyCharm I get proper auto completion.

Also checked with mypy: it recognizes the correct type of `context.bot`, but apparently only sees it as inferred, which is a bit strange, since the property is explicitly annotated and the type of `context` itself is apparently not inferred

**Comment by Bibo-Joshi** [comment]
The changes to `CCT.__init__` that I mentioned yesterday don't quite solve the problem. Instead I made another attempt on the [`cct-init`](https://github.com/python-telegram-bot/python-telegram-bot/tree/cct-init) branch. Doesn't pass CI yet, but maybe @harshil21 can still check if that improves it beavior for pylance? It does remove the "too few type arguments provided" errors that I mentioned yesterday …
