### ISSUE TITLE
__init__() got an unexpected keyword argument 'user'

### ISSUE THREAD

**Issue by 39bit** [python-telegram-bot/python-telegram-bot#301]
Cannot do getUpdates.

Python environment:

`Python 3.4.3 (default, Oct 14 2015, 20:33:09)
[GCC 4.8.4] on linux`

Full traceback:

http://pastebin.com/1kYLrcQS

Maybe this is because of Bot API v2.1?

**Comment by jh0ker** [comment]
Oh shit
I'll push a quick fix release. Thank you for the notice!

**Comment by jh0ker** [comment]
I pushed a new release v4.1.2
https://telegram.me/pythontelegrambotchannel/27

Again, thank you for bringing this to our attention!
