### ISSUE TITLE
Introduce keyword-only arguments for auxiliary arguments of Bot methods

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#3016]
# Current situation

All bot methods have arguments `{read, write, connect, pool}_timeout` and `api_kwargs`, which are added by PTB and do not correspond to arguments defined by the Bot API.
When a bot API update introduces new arguments to a method, we currently have to add them *after* the arguments mentioned above to ensure backwards compatibility for people that pass the arguments as positional arguments. This leads to constructs like

https://github.com/python-telegram-bot/python-telegram-bot/blob/d917404de1b6f6fd7e11ed2301bb89d68904d6cf/telegram/_bot.py#L557-L574

which is not very nice and may lead to people passing values to the wrong parameters if they rely on the order defined by the bot API.

# Proposed solution

Make the arguments `{read, write, connect, pool}_timeout` and `api_kwargs` [keyword-only arguments](https://peps.python.org/pep-3102/).

# ToDo

A PR for this issue should include:

* Update the definitions of all methods of the `Bot` class that have these argumemts
* The docstrings should be updated to reflect the order of the signature
* all corresponding methods of the `ExtBot` class should be updated as well
* as should all shortcut methods like `Message.reply_text`, `Chat.send_message` etc
* It should be checked if the rendered HTML documentation includes the `*` in the displayed signature. If it does not, the docstrings should include some other indicator that these arguments are keyward-only arguments. How this should look may be discussed at a later stage
* The unit tests must be updated accordingly. Running the test suit to see which tests fail after the changes should be a good start. Additionally, we should make sure that the auxiliary functions that currently test the signature definition of shortcut methods are still working as expected. This is a bit more intricate, so the development team can help with that.

# Additional Info

We have a [contribution guide](https://python-telegram-bot.readthedocs.io/en/v20.0a0/contributing.html)

**Comment by harshil21** [comment]
> should include some other indicator that these arguments are keyward-only arguments.

One could use ["Keyword Args:"](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/#docstring-sections) in the docstring to make it more clear. Will need to be done for every bot method.

**Comment by tal66** [comment]
hi, i'd like to do this

**Comment by harshil21** [comment]
> hi, i'd like to do this

Great! Hope you've read the contribution guide linked above. Assigning you
