### ISSUE TITLE
Deprecation: `imghdr` module is being deprecated in Python 3.11

### ISSUE THREAD

**Issue by harshil21** [python-telegram-bot/python-telegram-bot#3020]
The `imghdr` module is being deprected in `3.11` and will be removed in `3.13`. See [PEP 594](https://peps.python.org/pep-0594/#imghdr) for details. 

We currently use it only in one area: https://github.com/python-telegram-bot/python-telegram-bot/blob/be8f4f7aad9c3ded333950d00ecde57dbdda59c2/telegram/_files/inputfile.py#L108

Alternatives would be:
1. Just use the `mimetype` module? We were using only the `mimetype` module until [@b83a659](https://github.com/python-telegram-bot/python-telegram-bot/commit/b83a659) where we used a 'hack' to detect the type from the byte stream. This was then [replaced](https://github.com/python-telegram-bot/python-telegram-bot/commit/5dc1e4cac19cdd34d7cad4688afa0277a0c8a436) by the `imghdr` module which did the same thing better.
2. Use a library called [filetype](https://github.com/h2non/filetype.py) to detect images. This was [recommended](https://peps.python.org/pep-0594/#deprecated-modules) by the PEP.
3. Just copy the python [source](https://github.com/python/cpython/blob/3.11/Lib/imghdr.py) of the `imghdr` module into ours?

**Comment by tsnoam** [comment]
@harshil21 Interesting topic.

I remember the image detection being a wanted feature. How many users are really using it I can&#x27;t tell. Otoh, deleting this feature will reduce code complexity and it&#x27;s always nice.

If we do decide to keep the feature, the pep suggests (I wouldn&#x27;t say recommend at all, just suggests) several libraries, not only &quot;filetype&quot;. There&#x27;s also the library &quot;puremagic&quot; which should be considered. Personally I prefer libraries without compiled code dependencies.

In any case, I wouldn&#x27;t want to copy the original imghdr to our codebase, as it will force us to support it, and it&#x27;s really not what ptb is about.

**Comment by Bibo-Joshi** [comment]
> I remember the image detection being a wanted feature.

Interesting to know 👍 I noticed that at the time this was added, the `filename` parameter didn't exist yet - that was introduced only in #1168.
