### ISSUE TITLE
[QUESTION] Why is and ImportError showing up for only one of the imports (Application)

### ISSUE THREAD

**Issue by pabgamgar** [python-telegram-bot/python-telegram-bot#3041]
### Issue I am facing

I get the following error: ImportError: cannot import name 'Application' from 'telegram.ext'.

I've tried to uninstall and reinstall it again many times, even cloning the repository and installing it manually but after this it doesn't work still. I've looked up in the files of telegram/ext and there is no file called application.py, it's not even in the __init_.py 

Is Application not usable anymore, is there a way to replace it then?

### Traceback to the issue

```python
Traceback (most recent call last):
  File "botexample.py", line 6, in <module>
    from telegram.ext import (
ImportError: cannot import name 'Application' from 'telegram.ext' (/env/lib/python3.9/site-packages/telegram/ext/__init__.py)
```

### Related part of your code

```python
import logging
from telegram import ReplyKeyboardMarkup, ReplyKeyboardRemove, Update
from telegram.ext import (
    Application,
    ConversationHandler,
    Filters,
    MessageHandler,
    CommandHandler,
    filters,
    CallbackContext,
)
```

### Operating System

MacOS 12.4 (M1 Pro Macbook)

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.9.12 (main, Mar 26 2022, 15:44:31)  [Clang 13.1.6 (clang-1316.0.21.2)]
```

**Comment by harshil21** [comment]
See https://github.com/python-telegram-bot/python-telegram-bot/issues/3040#issuecomment-1128440437

**Comment by BlabliGam** [comment]
Thanks!
