### ISSUE TITLE
[QUESTION] Stuck conversation

### ISSUE THREAD

**Issue by DrMartiner** [python-telegram-bot/python-telegram-bot#3051]
### Issue I am facing

Hello,

If a user interrupts a conversation in a state, he will not be able to continue the one. The conversation will be stuck at the first step. How can I fix it?

Below I posted the conversation-handler code: 
```python
handler = ConversationHandler(
    entry_points=[
        MessageHandler(
            (Filters.text & Filters.regex(f"^{config_global.button_new_ad}$"))
            | (Filters.command & Filters.regex("^/new$")),
            start_new,
        ),
        CallbackQueryHandler(start_new, pattern=r"^ad_edit_(\d+)$"),
    ],
    states={
        NEW_AD_INFO: [
            CallbackQueryHandler(choice_category, pattern=r"^new_choice_city_(\d+)$"),
            CallbackQueryHandler(choice_action, pattern=r"^new_choice_category_(\d+)$"),
        ],
        NEW_AD_DESCRIPTION: [
            CallbackQueryHandler(type_title, pattern=r"^new_choice_action_(\d+)$"),
            MessageHandler(Filters.text, type_description),
        ],
        NEW_AD_PRICE: [
            MessageHandler(Filters.text, choice_currency),
            CallbackQueryHandler(type_price, pattern=r"^new_choice_currency_(\d+)$"),
        ],
        NEW_AD_PRICE_AGAIN: [
            MessageHandler(Filters.text, save_price),
        ],
        NEW_AD_PHOTO: [
            MessageHandler(Filters.photo, photo),
            CallbackQueryHandler(skip_photo, pattern=r"^skip$"),
        ],
        NEW_AD_CONFIRMATION: [
            CallbackQueryHandler(confirm_ad, pattern=r"^confirmed$"),
            CallbackQueryHandler(edit_ad, pattern=r"^edit$"),
        ],
    },
    fallbacks=[CommandHandler("start", process_start)],
)

updater = Updater(TELEGRAM_TOKEN)
updater.dispatcher.add_handler(new_ad_handler)
# Added etc handlers 
updater.start_polling()
updater.idle()
```

### Operating System

Ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot = "^13.11"
```

**Comment by DrMartiner** [comment]
> sorry, What do you mean by "user interrupts"? in what context?

Execute another command (e.g. `/start`)

**Comment by aditya-yadav-27** [comment]
Oh so you meant that if a conversation is going on and the user used another command the conversation will stop and the user have to start over right? Well to solve that add the conversation handler first before any other handlers, or put your conversation handler in different group if u wanna answer the issued command and want to keep the conversation alive

**Comment by Bibo-Joshi** [comment]
Note that `Filters.text` catches __any__ text including commands. If you don't want that, please use `Filters.text & ~Filters.command`. That way, your fallback handler would tigger in more cases. For a more detailed discussion on interruptions of conversations, please also see #1640 and the threads linked therein.

**Comment by DrMartiner** [comment]
> Oh so you meant that if a conversation is going on and the user used another command the conversation will stop and the user has to start over right? Well to solve that add the conversation handler first before any other handlers, or put your conversation handler in different group if u wanna answer the issued command and want to keep the conversation alive

I meant that if a user calls another command in a going conversation, he can't start the conversation again. As I understood the lib keeps state. How can I "reset" the conversation's state

**Comment by aditya-yadav-27** [comment]
> > Oh so you meant that if a conversation is going on and the user used another command the conversation will stop and the user has to start over right? Well to solve that add the conversation handler first before any other handlers, or put your conversation handler in different group if u wanna answer the issued command and want to keep the conversation alive
> 
> I meant that if a user calls another command in a going conversation, he can't start the conversation again. As I understood the lib keeps state. How can I "reset" the conversation's state

apparently, the closest thing related to "reset" state of conv is allow_reentry param (Set it to true)
