### ISSUE TITLE
Background non-blocking task[QUESTION]

### ISSUE THREAD

**Issue by ryouthere** [python-telegram-bot/python-telegram-bot#3062]
### Issue I am facing

As i understood, v2.0 has moved from multithreading to async. 

I used to have a functionality which enabled the user to upload a csv file, trigger a background job and when it was done the user would be notified. All this time the user could continue using the bot, the job was non-blocking. 

```
async def netflix_csv(update: Update, context: CallbackContext) -> int:
    """Sends CSV file in order to be processed"""

    csv_context = {
        'user': update.effective_user.id,
        'file': update.message.document.file_id,
        'send_notifications': context.user_data['send_notifications'],
    }
    await update.message.reply_text("Thanks!We started the upload process, we'll let you know "
                                    "when it's done or if there's any trouble.")
    context.job_queue.run_once(
        callback=csv_upload_handler,
        context=csv_context,
        when=0
    )
    return await reset(update, context)
```

And the job:

```
async def csv_upload_handler(context: CallbackContext):
    file_id = context.job.context['file']
    tgram_user = context.job.context['user']
    send_notifications = context.job.context['send_notifications']
    file = await context.bot.getFile(file_id)
    # Create an in-memory file
    f = io.BytesIO()
    await file.download(out=f)
    # Pointer is at the end of the file so reset it to 0.
    f.seek(0)
    # To pd.df
    df = pd.read_csv(f)
   "------- other logic here ------"
    await context.bot.send_message(text=f"CSV update successful!\n"
                                        f"Out of {len(df)} entries in your CSV file, "
                                        f"{len(identified_movies)} were movies while "
                                        f"{soap_or_unidentified} were either soap episodes, "
                                        f"series or likewise. The rest were already in your database "
                                        f"({len(df) - len(identified_movies) - soap_or_unidentified})",
                                   chat_id=tgram_user)
```

Right now it still works but the bot is stuck until the job is done. How can i achieve the same functionality that i used to have? The code is mostly the same like it was in the previous version, just had to add the asyncs and awaits so that it would not break in v.2.0

### Operating System

Linux, Windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a0
Bot API 6.0                                                                                        
Python 3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC v.1916 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
Hi. Any I/O bound logic that happens in your job should not hinder the bot from processing updates while the job is running. Only CPU-bound logic does. E.g. if `df = pd.read_csv(f)` takes a lot of CPU time, that will be "blocking". note that this is likely the same in `threading`, as multithreading in (C)Python does not really work on multiple CPUs - keyword: Global interpreter lock.
my suggestion would be to first try and narrow down which part of the code takes long to complete and only afterwards try to find a way to improve that :)

**Comment by ryouthere** [comment]
Hi, thanks for the response! Keep up the good work, it's a great framework.
