### ISSUE TITLE
[QUESTION] Is WebAppInitData avalaible?

### ISSUE THREAD

**Issue by Scolymus** [python-telegram-bot/python-telegram-bot#3071]
### Issue I am facing

Can we use [WebAppInitData](https://core.telegram.org/bots/webapps#webappinitdata) ? If so, how? Basically, I'm asking about sending information to the WebApp when opening the webapp as in the [webapp example](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/webappbot.py) 

I would be really nice to be able to do a POST. I guess that if WebAppInitData is not avalaible, the only way around is to call the webpage adding ?variable=&variable2&... at the end of the web url...

### Operating System

Running on ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
last pre, 20.0a0
```

**Comment by Poolitzer** [comment]
Yes you can use it in your web app, as long as it is launched via inline keyboard button, as the docs state. No, you can not set its content to your liking. And no, there is no post call you can get Telegram to do, just a get one to the URL you set. So URL queries are the way to go here. Or just an unique URL/use the user id in the backend to get the unique user experience you probably want.
