### ISSUE TITLE
[FEATURE] Add convenience property `id` to `Message`

### ISSUE THREAD

**Issue by harshil21** [python-telegram-bot/python-telegram-bot#3075]
## Current situation

Telegram currently offers attribute `message_id` to `Message`. But this is inconsistent with the rest of their API, e.g. `Chat.id`, `User.id`, `InlineQuery.id`, etc. We can offer a convenience property `Message.id` which will make it more consistent and make it less prone to errors, e.g. when someone forgets it's `message_id` and not `id`. 

## Proposed change

Add the property `id` to `Message` which just returns `self.message_id`. A similar example can be found [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/_message.py#L570-L573).

## A PR for this issue should

- Add a docstring along with a `.. versionadded:: 20.0` directive to the function.
- Add an unit test to `test_message.py` that ensures that this works as expected and is the same as `Message.message_id`.

## Additional Info

We have a [contribution guide](https://python-telegram-bot.readthedocs.io/en/v20.0a0/contributing.html)

**Comment by dglitxh** [comment]
@harshil21 can i take this?

**Comment by harshil21** [comment]
Sure, assigning you.

**Comment by dglitxh** [comment]
@harshil21 apparently 'id' is not a valid name. It gets blocked by the pre-commit scripts although it passes the unit test

**Comment by dglitxh** [comment]
#3076
