### ISSUE TITLE
[QUESTION] Is there anyway to avoid collapse when showing a WebApp?

### ISSUE THREAD

**Issue by Scolymus** [python-telegram-bot/python-telegram-bot#3091]
### Issue I am facing

I'm showing a php file that has an image slider. When the app is loaded, Telegram maximizes the screen for the WebApp (There's a Telegram.WebApp.expand(); at the end of the web file). However, I'm facing a problem with the dragging depending on where the user clicks on the screen to drag.

If the user clicks for dragging on position (X,Y), 2 behaviours can happen:
   - If Y>height/2, being y=0 the bottom of the screen, the webapp reduces its size so you can see the conversation too.
   - If Y<height/2, being y=0 the bottom of the screen, the webapp maximizes its size so you cannot see the conversation.

I want to avoid the reduction of the avalaible area, so in both cases it happens as in Y<height/2. Is there any way to force telegram to expand until the user press the button to send the data back to telegram? I added this js:

window.addEventListener('resize', reportResize);
function reportResize() {
  Telegram.WebApp.expand();
}

but is doing anything. Is there anyway to log it?

### Operating System

Android

### Version of Python, python-telegram-bot & dependencies

```shell
3.9, v20.0a0
```

**Comment by Poolitzer** [comment]
Currently, there is no good way to debug your web app. I can try to have a look though if you send the url/source file.

**Comment by Scolymus** [comment]
Here you have!

https://easyupload.io/sfhj6g

**Comment by Bibo-Joshi** [comment]
I'll go ahead and close this as issues with the JS-components of WebApps are nothing that this library can control :)
