### ISSUE TITLE
post_shutdown method in addition to post_init

### ISSUE THREAD

**Issue by 91DarioDev** [python-telegram-bot/python-telegram-bot#3105]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

i would like to be able to await coroutines before of shutting down the bot after application.run_polling().

it could be done implementing a post_shutdown method in addition to the already existing post_init method

### Describe the solution you'd like

It is especially useful for closing a db connection in aiosqlite ( await db.close() )

**Comment by Poolitzer** [comment]
This feels natural to me. Normally you can write your code after the long_polling/webhook call, but I bet there are cases where this comes in handy anyway.

**Comment by Bibo-Joshi** [comment]
Jup. A contribution in this direction would be very welcome! A PR for this could probably closely follow the changes in #3078.

**Comment by harshil21** [comment]
@ExalFabu yep, we can guide better after we see what&#x27;s happening :)
