### ISSUE TITLE
Constant improvement

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#3107]
We currently have quite some limits still hard coded into the docstrings, for example [vcard,](https://docs.python-telegram-bot.org/en/v20.0a1/telegram.bot.html#telegram.Bot.send_contact.params.vcard) [telegram.Bot.send_poll#explanation](https://docs.python-telegram-bot.org/en/v20.0a1/telegram.bot.html#telegram.Bot.send_poll.params.explanation) or [#open_period](https://docs.python-telegram-bot.org/en/v20.0a1/telegram.bot.html#telegram.Bot.send_poll.params.open_period). We also could think about including [switch_pm_parameter](https://docs.python-telegram-bot.org/en/v20.0a1/telegram.bot.html#telegram.Bot.answer_inline_query.params.switch_pm_parameter) somehow. I would like to collect the thoughts of the maintainers here and maybe motivate someone from the community to contribute this since it is quite an "easy" addition to the project.

**Comment by harshlancer** [comment]
Hey, I'm new to open source and want to learn how to contribute, and I can't quite get what needs to be done here. Can you guide me on which doc is required in order to be updated or changed?

**Comment by Poolitzer** [comment]
Hey, nice to hear.

So I already linked to a few examples in my original message. Have a look at the source doc string of [send_poll](https://github.com/python-telegram-bot/python-telegram-bot/blob/v20.0a1/telegram/_bot.py#L6727-L6872). As you can see in `question`, it links the 1-_number_ to _:tg-const:\`telegram.Poll.MAX_QUESTION_LENGTH\`_  instead of writing out the number in the doc string itself (this happens five arguments later in `explanation`, where it says 0-200 characters without the link).

If you have a look at that linking, you can see that it references MAX_QUESTION_LENGTH in the Poll file. In the [source of Poll](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/_poll.py#L294-L306), you can see that you have been bamboozled and the actual source for these variables lies in the constants.py file, MAX_QUESTION_LENGTH is just a link to `constants.PollLimit.QUESTION_LENGTH`.

In the [source of constants](https://github.com/python-telegram-bot/python-telegram-bot/blob/v20.0a1/telegram/constants.py#L741-L757), you can finally see how it is implemented: An IntEnum Class which has the values mapped to their respective key.

----

The issue is that we only did this sparingly thus far, whenever we thought of it. I would like to replace every limit currently written out in the docstrings with links to constants files. We as maintainer still have decide on a couple things. 

Now there is the question of what you can do in the meantime. What would be an amazing help if you can go through the whole documentation (maybe scroll through telegrams one, its easier to read one after another since its just one page). Any missed limitation (last point in the list below) would be hugely appreciated pointed out, since that would require a decision from us before one can implement it.

Otherwise you could go ahead and convert some obvious limitations already.

On a side-note, I will push an example improvements of the `invoice` object limitations in the near future, I will ping this issue to it, so one can see a clear example of before>after.

**Comment by Poolitzer** [comment]
> I don't really understand this. Do you want to enforce this at runtime? I thought we decided against that in https://github.com/python-telegram-bot/python-telegram-bot/issues/2901?

No nothing here is enforcing at runtime, its a question of how we interpret entries to our constant files. On one side we have the usual API constants, on the others we have the max/min limits of specific calls/objects, so people can do `if length(input) > Poll.MaxTitle: do_error`. The other two are continuations of it. With the second they can do `if not constants.SwitchPMValidation(input): do_error`, with the third `if not two/three_letter_ISO(input): do_error`.

>I think they can change over time
They have never. But thats the same for any other entry to constants.

**Comment by harshil21** [comment]
Ah okay. I guess having those validation functions for "constants" is not very fitting, since it's meant to be hardcoded values and nothing else? Maybe having them in a separate `validators.py` file as functions is better? Are there other places where we can validate input?

**Comment by Bibo-Joshi** [comment]
> What would be an amazing help if you can go through the whole documentation

Or just regex-search for integers 🙂 

> > * [ ]   Include Min **and** Max limits of a given constraint in the constants?
> 
> I would say yes for the Min only if it's non zero

+1
> > * [ ]   Include type restrictions (e.g. only latin characters for deep links). If yes, how?
> 
> I guess having those validation functions for "constants" is not very fitting, since it's meant to be hardcoded values and nothing else? Maybe having them in a separate validators.py file as functions is better? Are there other places where we can validate input?

I agree with harshil here. constants is for constants, not validators. Personally I see the main advantage of the constants module in not having to hard code values/define those constants on your own. How a user uses them is another question.
Validators *could* go into `helpers`, though personally I don't see a big need to do that. If we get feature requests for that - sure. ptbcontrib is another possibility.

> > * [ ]   Include two/three-letter ISO code restriction

Punshline the same as above, with the addition that a maintained list of ISO-language codes *very* likely already exists somewhere and I don't see a need to duplicate that in PTB.

**Comment by Poolitzer** [comment]
Alright, lets drop validation stuff for now and let these limits in the doc strings, we can stick to the other hardcoded values. One example on how this is implemented is visual in #3112:

The doc strings of [InputInvoiceMessageContent](https://github.com/python-telegram-bot/python-telegram-bot/pull/3112/files#diff-a880792d5d6dd376cf0b019508a6ab9c21bed9055ef0795454d1caa7842eaff8) and [bot.send_invoice](https://github.com/python-telegram-bot/python-telegram-bot/pull/3112/files#diff-2aef7cabe736b556967d73b7f946c32a67142d6bccb4c90a355d375374ebd8eaR4607-R4614) changed, the constants were linked in [Invoice](https://github.com/python-telegram-bot/python-telegram-bot/pull/3112/files#diff-32b9a43fa30c12649a20368d7b8440223fb2a0a819e17ae3a71665a14306a07d) and finally implemented in [InvoiceLimits enum](https://github.com/python-telegram-bot/python-telegram-bot/pull/3112/files#diff-9dd9ba2fa5677486ab0a281e94af2aa08bc99c769fec8231e9787ab1b34e149cR816-R836) in the constants file.

Hope this makes clear how we expect this issue to be implemented.

**Comment by lemontree210** [comment]
I kind of like getting rid of magical numbers so I could dive into this unless you'd like me to focus on something more pressing

**Comment by clot27** [comment]
@lemontree210 .

**Comment by lemontree210** [comment]
How about default values? My guess is that we do **not** put them into the enumerations because default values (if we are talking about Telegram API, not additional kwargs) are not passed to Telegram: `None` is passed and then Telegram applies the default value, as opposed to PTB passing the default value.

That would mean that, for example, for parameter `max_connections` of `Bot.set_webhook()` I will add constants for min (`1`) and max (`100`), but **not** for default value (`40`), which will remain just a number `40` (without a hyperlink) in the docstring.

Even if I added a constant for that too, that wouldn't mean a change in the signature of `set_webhook()`: `max_connections` would still default to `None`.

The example for `Bot.send_invoice()` had no such cases (non-zero defaults), so I just wanted to check that understanding.

**Comment by harshil21** [comment]
@lemontree210 yes, that understanding is correct. No need to make constants for default values.

**Comment by lemontree210** [comment]
> One example on how this is implemented is visual in #3112:
> 
> The doc strings of [InputInvoiceMessageContent](https://github.com/python-telegram-bot/python-telegram-bot/pull/3112/files#diff-a880792d5d6dd376cf0b019508a6ab9c21bed9055ef0795454d1caa7842eaff8) and [bot.send_invoice](https://github.com/python-telegram-bot/python-telegram-bot/pull/3112/files#diff-2aef7cabe736b556967d73b7f946c32a67142d6bccb4c90a355d375374ebd8eaR4607-R4614) changed, the constants were linked in [Invoice](https://github.com/python-telegram-bot/python-telegram-bot/pull/3112/files#diff-32b9a43fa30c12649a20368d7b8440223fb2a0a819e17ae3a71665a14306a07d) and finally implemented in [InvoiceLimits enum](https://github.com/python-telegram-bot/python-telegram-bot/pull/3112/files#diff-9dd9ba2fa5677486ab0a281e94af2aa08bc99c769fec8231e9787ab1b34e149cR816-R836) in the constants file.

The files actually demonstrate two approaches: class [Invoice](https://github.com/python-telegram-bot/python-telegram-bot/pull/3112/files#diff-32b9a43fa30c12649a20368d7b8440223fb2a0a819e17ae3a71665a14306a07d) contains class constants that are linked to [InvoiceLimits enum](https://github.com/python-telegram-bot/python-telegram-bot/pull/3112/files#diff-9dd9ba2fa5677486ab0a281e94af2aa08bc99c769fec8231e9787ab1b34e149cR816-R836), but class [Bot](https://github.com/python-telegram-bot/python-telegram-bot/pull/3112/files#diff-2aef7cabe736b556967d73b7f946c32a67142d6bccb4c90a355d375374ebd8eaR3843-R3850) shows a different approach to `WebhookLimit`. `Bot`'s docstring contains direct references to [WebhookLimit](https://github.com/python-telegram-bot/python-telegram-bot/pull/3112/files#diff-9dd9ba2fa5677486ab0a281e94af2aa08bc99c769fec8231e9787ab1b34e149cR839) in constants.py, no class constants were declared in `Bot` itself.

Which approach should I follow? I assume the former (like in `Invoice`), but I wanted to double check. Also, if the approach for `InvoiceLimit` is the best, then maybe I should also add `WebhookLimit`'s constants to `Bot`.

**Comment by harshil21** [comment]
> Which approach should I follow? I assume the former (like in `Invoice`), but I wanted to double check.

I don't think we should add class constants for `Bot`, since `Bot` contains many methods and most of them link to different constants.
