### ISSUE TITLE
[What is the reason for the following error? "RuntimeError: Cannot close a running event loop" ]

### ISSUE THREAD

**Issue by ghghorbanzade** [python-telegram-bot/python-telegram-bot#3108]
### Issue I am facing

I faced the following error by running each of the examples of this GitHub page: 

### Traceback to the issue

```python
RuntimeError  Traceback (most recent call last)
[/usr/lib/python3.7/asyncio/selector_events.py](https://localhost:8080/#) in close(self)
     86     def close(self):
     87         if self.is_running():
---> 88             raise RuntimeError("Cannot close a running event loop")
     89         if self.is_closed():
     90             return

RuntimeError: Cannot close a running event loop
```

### Operating System

running on Colab

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot == 20.0a1
```

**Comment by Bibo-Joshi** [comment]
Hi. Is thit really the full traceback? can you reproduce when running the exmaples locally? I'm not familiar with google colab, but I can imagine that it's doing some tricky background work that doesn't play well with asyncio.
