### ISSUE TITLE
[Documentation]  Add valuable information to attribute docstrings of telegram classes

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#3109]
The docs of Telegram classes are currently written such that the docstring of the arguments are more informative than the docstring of the respective attributes. E.g. for `Chat.has_private_forwards`, "Returned only in `get_chat()`" is only present in the [argument docstrings](https://docs.python-telegram-bot.org/en/v20.0a1/telegram.chat.html#telegram.Chat.params.has_private_forwards), not in the [attribute docstring](https://docs.python-telegram-bot.org/en/v20.0a1/telegram.chat.html#telegram.Chat.has_private_forwards). For `Message.text`, the length limitation is only documented for the argument, not the attribute.

This logic makes sense for classes that are to be instantiated by the user (like `BotCommand` or `InputMedia*`), but for classes that are rarely instantiated by the user like `Chat` and `Message` this makes it sometimes hard to find valuable information.

I suggest to revisit the documentation of the Telegram classes and either unify the docstrings of args & attributes or at least check which information would be worth adding to the attributes as well.

Contributions in this direction are very welcome! They also don't have to cover all Telegram classes at once - instead this can be done step by step. If you want to cover (parts of) this, please leave a comment below, so that we can avoid duplicate work.

PRs for this should be made against the `doc-fixes` branch. Please also check out the [contribution guide](https://docs.python-telegram-bot.org/en/v20.0a1/contributing.html), especially the part on how to [build the documentation locally](https://docs.python-telegram-bot.org/en/v20.0a1/contributing.html#documenting).

Classes are listed [below](https://github.com/python-telegram-bot/python-telegram-bot/issues/3109#issuecomment-1333572895) for convenience.

**Comment by Bibo-Joshi** [comment]
You're very welcome to contribute! please leave a short comment about which classes you want to cover in a pull request :)

**Comment by simonfongnt** [comment]
is this still available for a beginner?

**Comment by Bibo-Joshi** [comment]
You're very welcome to contribute! There haven't been any PRs regarding this so far. please leave a short comment about which classes you want to cover in a pull request :)

**Comment by simonfongnt** [comment]
i shall go for the `Message` class and unify the docstrings of args & attributes in the PR.

**Comment by penguinpee** [comment]
Collision avoidance: I'll start at the bottom and take care of the _web family of classes.

Happy Hacktober! :beers:

**Comment by Bibo-Joshi** [comment]
Thanks for the notice @penguinpee . But can you clarify which classes exactly you mean? There are no classes in the `telegram` package whose name ends on `_web` or `Web` 😄

**Comment by penguinpee** [comment]
I was referring to the classes in `telegram/_web*.py`. The corresponding classes are called `Web*`.

**Comment by HatimZ** [comment]
I did the Chat class and unified the docstrings of args & attributes in the PR.

**Comment by RobiMez** [comment]
Tackling the poll class for a start.

**Comment by RobiMez** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/pull/3312

**Comment by RobiMez** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/pull/3314

**Comment by lemontree210** [comment]
List of classes:

- [ ] Telegram package
  - [ ] Available Types
    - [ ] telegram.Animation
    - [ ] telegram.Audio
    - [ ] telegram.BotCommand
    - [ ] telegram.BotCommandScope
    - [ ] telegram.BotCommandScopeAllChatAdministrators
    - [ ] telegram.BotCommandScopeAllGroupChats
    - [ ] telegram.BotCommandScopeAllPrivateChats
    - [ ] telegram.BotCommandScopeChat
    - [ ] telegram.BotCommandScopeChatAdministrators
    - [ ] telegram.BotCommandScopeChatMember
    - [ ] telegram.BotCommandScopeDefault
    - [ ] telegram.CallbackQuery
    - [ ] telegram.Chat
    - [ ] telegram.ChatAdministratorRights
    - [ ] telegram.ChatInviteLink
    - [ ] telegram.ChatJoinRequest
    - [ ] telegram.ChatLocation
    - [ ] telegram.ChatMember
    - [ ] telegram.ChatMemberAdministrator
    - [ ] telegram.ChatMemberBanned
    - [ ] telegram.ChatMemberLeft
    - [ ] telegram.ChatMemberMember
    - [ ] telegram.ChatMemberOwner
    - [ ] telegram.ChatMemberRestricted
    - [ ] telegram.ChatMemberUpdated
    - [ ] telegram.ChatPermissions
    - [ ] telegram.ChatPhoto
    - [ ] telegram.Contact
    - [ ] telegram.Dice
    - [ ] telegram.Document
    - [ ] telegram.File
    - [ ] telegram.ForceReply
    - [ ] telegram.ForumTopic
    - [ ] telegram.ForumTopicClosed
    - [ ] telegram.ForumTopicCreated
    - [ ] telegram.ForumTopicReopened
    - [ ] telegram.InlineKeyboardButton
    - [ ] telegram.InlineKeyboardMarkup
    - [ ] telegram.InputFile
    - [ ] telegram.InputMedia
    - [ ] telegram.InputMediaAnimation
    - [ ] telegram.InputMediaAudio
    - [ ] telegram.InputMediaDocument
    - [ ] telegram.InputMediaPhoto
    - [ ] telegram.InputMediaVideo
    - [ ] telegram.KeyboardButton
    - [ ] telegram.KeyboardButtonPollType
    - [ ] telegram.Location
    - [ ] telegram.LoginUrl
    - [ ] telegram.MenuButton
    - [ ] telegram.MenuButtonCommands
    - [ ] telegram.MenuButtonDefault
    - [ ] telegram.MenuButtonWebApp
    - [ ] telegram.Message
    - [ ] telegram.MessageAutoDeleteTimerChanged
    - [ ] telegram.MessageEntity
    - [ ] telegram.MessageId
    - [ ] telegram.PhotoSize
    - [ ] telegram.Poll
    - [ ] telegram.PollAnswer
    - [ ] telegram.PollOption
    - [ ] telegram.ProximityAlertTriggered
    - [ ] telegram.ReplyKeyboardMarkup
    - [ ] telegram.ReplyKeyboardRemove
    - [ ] telegram.SentWebAppMessage
    - [ ] telegram.TelegramObject
    - [ ] telegram.Update
    - [ ] telegram.User
    - [ ] telegram.UserProfilePhotos
    - [ ] telegram.Venue
    - [ ] telegram.Video
    - [ ] telegram.VideoChatEnded
    - [ ] telegram.VideoChatParticipantsInvited
    - [ ] telegram.VideoChatScheduled
    - [ ] telegram.VideoChatStarted
    - [ ] telegram.VideoNote
    - [ ] telegram.Voice
    - [ ] telegram.WebAppData
    - [ ] telegram.WebAppInfo
    - [ ] telegram.WebhookInfo
  - [ ] Stickers
    - [ ] telegram.MaskPosition
    - [ ] telegram.Sticker
    - [ ] telegram.StickerSet
  - [ ] Inline Mode
    - [ ] telegram.ChosenInlineResult
    - [ ] telegram.InlineQuery
    - [ ] telegram.InlineQueryResult
    - [ ] telegram.InlineQueryResultArticle
    - [ ] telegram.InlineQueryResultAudio
    - [ ] telegram.InlineQueryResultCachedAudio
    - [ ] telegram.InlineQueryResultCachedDocument
    - [ ] telegram.InlineQueryResultCachedGif
    - [ ] telegram.InlineQueryResultCachedMpeg4Gif
    - [ ] telegram.InlineQueryResultCachedPhoto
    - [ ] telegram.InlineQueryResultCachedSticker
    - [ ] telegram.InlineQueryResultCachedVideo
    - [ ] telegram.InlineQueryResultCachedVoice
    - [ ] telegram.InlineQueryResultContact
    - [ ] telegram.InlineQueryResultDocument
    - [ ] telegram.InlineQueryResultGame
    - [ ] telegram.InlineQueryResultGif
    - [ ] telegram.InlineQueryResultLocation
    - [ ] telegram.InlineQueryResultMpeg4Gif
    - [ ] telegram.InlineQueryResultPhoto
    - [ ] telegram.InlineQueryResultVenue
    - [ ] telegram.InlineQueryResultVideo
    - [ ] telegram.InlineQueryResultVoice
    - [ ] telegram.InputMessageContent
    - [ ] telegram.InputTextMessageContent
    - [ ] telegram.InputLocationMessageContent
    - [ ] telegram.InputVenueMessageContent
    - [ ] telegram.InputContactMessageContent
    - [ ] telegram.InputInvoiceMessageContent
  - [ ] Payments
    - [ ] telegram.Invoice
    - [ ] telegram.LabeledPrice
    - [ ] telegram.OrderInfo
    - [ ] telegram.PreCheckoutQuery
    - [ ] telegram.ShippingAddress
    - [ ] telegram.ShippingOption
    - [ ] telegram.ShippingQuery
    - [ ] telegram.SuccessfulPayment
  - [ ] Games
    - [ ] telegram.Callbackgame
    - [ ] telegram.Game
    - [ ] telegram.GameHighScore
  - [ ] Passport
    - [ ] telegram.Credentials
    - [ ] telegram.DataCredentials
    - [ ] telegram.EncryptedCredentials
    - [ ] telegram.EncryptedPassportElement
    - [ ] telegram.FileCredentials
    - [ ] telegram.IdDocumentData
    - [ ] telegram.PassportData
    - [ ] telegram.PassportElementError
    - [ ] telegram.PassportElementErrorDataField
    - [ ] telegram.PassportElementErrorFile
    - [ ] telegram.PassportElementErrorFiles
    - [ ] telegram.PassportElementErrorFrontSide
    - [ ] telegram.PassportElementErrorReverseSide
    - [ ] telegram.PassportElementErrorSelfie
    - [ ] telegram.PassportElementErrorTranslationFile
    - [ ] telegram.PassportElementErrorTranslationFiles
    - [ ] telegram.PassportElementErrorUnspecified
    - [ ] telegram.PassportFile
    - [ ] telegram.PersonalDetails
    - [ ] telegram.ResidentialAddress
    - [ ] telegram.SecureData
    - [ ] telegram.SecureValue
