### ISSUE TITLE
Getting chat_id from old, anwsered messages

### ISSUE THREAD

**Issue by FutureSharks** [python-telegram-bot/python-telegram-bot#311]
Quick question...

There is Telegram user who is in a conversation with my bot but there is no new messages from the user:
```
bot=telegram.Bot(token=token)
>>> bot.getUpdates()
[]
```

At this point I want to send a message to the user. Is it possible to get the chat_id? Or must the bot wait for a message, get the chat_id and then reply?

**Comment by rahiel** [comment]
You need to save the `chat_id` your bot got from a previous message. You can then reuse it.
