### ISSUE TITLE
[Documentation] Add more cross-references

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#3110]
It would be nice to add more cross-references to the documentation. This should help users to better understand "where is this used?"/"what is this relevant for?".

For this, we can use the sphinx directive `.. seealso::` like done e.g. [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/67e7468366098f79cd2aa4f88b40e6e47d93ae5a/telegram/ext/_applicationbuilder.py#L332).

Notable things that can be cross-referenced better include:

* point to shortcuts from the bot methods. e.g. point to `Message.reply_text` from `Bot.send_message`, point to `CallbackQuery.answer` from `Bot.answer_callback_query` and so on.
* point to examples & wiki: All classes/arguments that are show cased in an example or explained in a wiki page should point to those. e.g. `JobQueue` should point to `timerbot` and the wiki page on `JobQueue`. `Bot.arbitrary_callback_data` should point to the wiki page on arbitrary callback data and to the `arbitrarycallbackbot` example.
* for classes in tg.ext (and for `tg.Bot`) point to attributes of that type: e.g. `JobQueue` should point to `{Application, CallbackContext}.job_queue`, `Bot` should point to `{Application, Updater, CallbackContext}.bot`, `CallbackDataCache` should point to `ExtBot.callback_data_cache`

Contributions in this direction are very welcome! They also don't have to cover everything classes at once - instead this can be done step by step. If you want to cover (parts of) this, please leave a comment below, so that we can avoid duplicate work.

PRs for this should be made against the `doc-fixes` branch. Please also check out the [contribution guide](https://docs.python-telegram-bot.org/en/v20.0a1/contributing.html), especially the part on how to [build the documentation locally](https://docs.python-telegram-bot.org/en/v20.0a1/contributing.html#documenting).

**Comment by aditya-yadav-27** [comment]
Can I work on this?

**Comment by Bibo-Joshi** [comment]
Yes, please :) if you can leave a short comment on which places you want to cover, that would be great (you can also edit that comment in case you extend your work)

**Comment by aditya-yadav-27** [comment]
All `bot.send_*` methods, all updating message methods e.g. `answer_inline_query`, all chat moderation and information methods e.g. `ban_chat_member`. Point to examples as you have mentioned. Point classes to attributes as you have mentioned

**Comment by lemontree210** [comment]
> Point to examples & wiki: All classes/arguments that are show cased in an example or explained in a wiki page should point to those

I would like to work on this if possible :)

**Comment by Bibo-Joshi** [comment]
Sure, you are very welcome to 👍

**Comment by lemontree210** [comment]
> point to shortcuts from the bot methods

Do we want to point from a shortcut method in `Chat` to another shortcut method in `Message`? I'm guessing not but it's worth double-checking.

**Comment by Bibo-Joshi** [comment]
Closing this issue for now. There are probably still more places out there that might benefit from additional cross references, but finding *all* of them is a non-completeable task anyway …
