### ISSUE TITLE
[Documentation] Add note on editing with reply markups

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#3111]
We should add note to all `Bot.edit_*` methods that states the limitation about editing messages from the official docs:

> Please note, that it is currently only possible to edit messages without `reply_markup` or with inline keyboards.

This should be done via the `Note:` role of sphinx as done e.g. [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/11007c17154e874716cdb99f6fdcd04c1724c8df/telegram/_message.py#L84)

A contribution in this direction is very welcome! A PR for this should be made against the `doc-fixes` branch. Please also check out the [contribution guide](https://docs.python-telegram-bot.org/en/v20.0a1/contributing.html), especially the part on how to [build the documentation locally](https://docs.python-telegram-bot.org/en/v20.0a1/contributing.html#documenting).

**Comment by abhinav1912** [comment]
As a first contribution, this seems like a manageable task. Should I pick this?

**Comment by Bibo-Joshi** [comment]
Hi, thanks for your interest! Someone already PRed for this issue - see #3121. But #3110 and #3109 are possible alternatives :)

**Comment by Bibo-Joshi** [comment]
closed by #3121
