### ISSUE TITLE
Suppressing exceptions .

### ISSUE THREAD

**Issue by gitpull2** [python-telegram-bot/python-telegram-bot#3113]
### Issue I am facing

Is there any way to suppress all exceptions coming from the library ? It is vital for my clients app to keep running , it is ok if a few unimportant messages are missed while sending, editing , pinning  but I don't want the program to stop. Using `try` , `except` block after every `send_message` , pinning, editting etc makes the program bulky and less readable . 

`bot.send_message(chat_id="1234",text="<",parse_mode="HTML")` '

### Traceback to the issue

```python
telegram.error.BadRequest: Can't parse entities: unclosed start tag at byte offset 0
```

### Operating System

windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
```

**Comment by Bibo-Joshi** [comment]
PTB is designed such that exceptions in callback don't shut down the bot. see also the [wiki page on that](../wiki/Exceptions%2C-Warnings-and-Logging). However, if an exception happens in a callback, the rest of the callback will indeed not be executed. if you really want every call to certain bot methods to be wrapped in try-except you can consider writing a custom helper function for that or even subclassing `telegram.Bot`/`telegram.ext.ExtBot`.

**Comment by gitpull2** [comment]
Thanks, I would be doing that . What are your thoughts on having this as a new feature ? 
`bot.send_message(chat_id = "1234" ,text = "<",  parse_mode = "HTML" ,supress_exceptions = True)`

**Comment by Bibo-Joshi** [comment]
I don't see anything like this being added to the library at any point. for one, I consider it very bad practice to silently mute exceptions. Moreover, functions raising exceptions is a general python concept and not specific to this library.
