### ISSUE TITLE
[QUESTION] Send a photo with text

### ISSUE THREAD

**Issue by Adlemex** [python-telegram-bot/python-telegram-bot#3116]
### Issue I am facing

Tell me how to send a photo with text that looks like this: https://imgur.com/a/uQunezo

### Operating System

Windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.12
Bot API 6.0
certifi 2022.06.15
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
```

**Comment by harshil21** [comment]
@Adlemex Parameter <a href="https://docs.python-telegram-bot.org/telegram.bot.html#telegram.Bot.send_photo.params.caption">caption</a> of <a href="https://docs.python-telegram-bot.org/telegram.bot.html#telegram.Bot.send_photo">telegram.Bot.send_photo</a>
