### ISSUE TITLE
Add tag to forward_message class[FEATURE]

### ISSUE THREAD

**Issue by kinshusharma0412** [python-telegram-bot/python-telegram-bot#3123]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Add either Message_ids to forward_message class Or reply_to_message_id

### Describe the solution you'd like

Since your code not forward multiple message.
So tag message lose tag itself

### Describe alternatives you've considered

![IMG_20220626_115142](https://user-images.githubusercontent.com/73776157/175804314-31103fc6-9321-4f11-aad3-677f6ac8a652.jpg)

Original message👆👆

![IMG_20220626_115210](https://user-images.githubusercontent.com/73776157/175804259-33649fc0-6c2a-416e-818f-f4952e1e9c45.jpg)

when bot forward messages👆👆

![IMG_20220626_115225](https://user-images.githubusercontent.com/73776157/175804326-5ac2c8d3-c48d-4206-a9cc-44e4d7088e89.jpg)

when user forward multiple message👆👆

Third photo what I want by bot

**Comment by Bibo-Joshi** [comment]
@kinshusharma0412 Wiki of <i>python-telegram-bot</i> - Category <i>FAQ</i>
<a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#can-you-add-feature-to-ptb-can-i-do-thing-with-my-bot">Can you add [feature] to PTB? Can I do [thing] with my bot?</a>
