### ISSUE TITLE
__main__ - WARNING - Update "None" caused error "Conflict: terminated by other long poll or webhook (409)

### ISSUE THREAD

**Issue by celisflen-bers** [python-telegram-bot/python-telegram-bot#313]
### Steps to reproduce
1.Run
2.Update messages, print errors in loops
3.

### Expected behaviour
No problem

### Actual behaviour
2016-05-28 17:36:59,553 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other long poll or webhook (409)
2016-05-28 17:36:59,578 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other long poll or webhook (409)".....loop

### Configuration
**Operating System:**
**pythonanywhere.com**
3.13.0-85-generic x86_64 x86_64 GNU/Linux

**Version of Python:**
``$ python -V``
Python 2.7.6

**Version of python-telegram-bot:**
``$ python -c 'import telegram; print(telegram.__version__)'``
Version: 4.1.2

### Logs
Insert logs here (if necessary)

**Comment by jh0ker** [comment]
You probably have a second instance of your bot running somewhere

**Comment by celisflen-bers** [comment]
Yes, thanks. Running in bg :confused:

**Comment by jh0ker** [comment]
No problem :+1:
