### ISSUE TITLE
Como iniciar echobot

### ISSUE THREAD

**Issue by Witputinfo7** [python-telegram-bot/python-telegram-bot#3133]
### Issue I am facing

hello, I'm a beginner, I wanted to start echobot, but this appears in the terminal, I'm using Ubuntu and I don't know what it is, I didn't find the tutorial on how to start a bot, can anyone help me? Yours sincerely!
![IMG-20220702-WA0053](https://user-images.githubusercontent.com/108410970/177010628-a52db24a-a387-4f6f-9e22-282137662b16.jpg)

### Traceback to the issue

```python
it's in print mosyrabd
```

### Related part of your code

```python
f"This example is not compatible with your current PTB version {TG_VER}. To view the "
        f"{TG_VER} version of this example, "
        f"visit https://docs.python-telegram-bot.org/en/v{TG_VER}/examples.html"
```

### Operating System

Ubuntu 20.4

### Version of Python, python-telegram-bot & dependencies

```shell
/usr/bin/python: No module named telegram
```

**Comment by Poolitzer** [comment]
what python version are you on?

**Comment by Witputinfo7** [comment]
> em qual versão do python você está?

Python 2.7.18

**Comment by Poolitzer** [comment]
this library supports 3.7+.
