### ISSUE TITLE
[QUESTION] Can't convert to an executable

### ISSUE THREAD

**Issue by roystonlmq** [python-telegram-bot/python-telegram-bot#3137]
### Issue I am facing

I tried to create an executable for my main.py. It didn't work because of the following traceback.

### Traceback to the issue

```python
1462 WARNING: Failed to collect submodules for 'gevent.testing' because importing 'gevent.testing' raised: RuntimeError: This example is not compatible with your current PTB version 13.13. To view the 13.13 version of this example, visit https://docs.python-telegram-bot.org/en/v13.13/examples.html
```

### Related part of your code

```python
NA
```

### Operating System

Windows 11

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a2
Bot API 6.1
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
```

**Comment by Poolitzer** [comment]
The error explicitly says the versions of our library is 13.13 and not 20.0.a2. Make sure you don't mess up the venvs :)
