### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by foad-heidari** [python-telegram-bot/python-telegram-bot#3138]
### Issue I am facing

Hello.
I want to validate the user by one of this options 
- the date which user joined telegram
- the date of user profile picture upload

So I want to know if user is a real user. And they do not pretend to be someone else by fake data from someone else.

if there is any option i can check please let me know. I already checked a lot 

### Operating System

Ubuntu 

### Version of Python, python-telegram-bot & dependencies

```shell
Last version
```

**Comment by Poolitzer** [comment]
Both are not returned by the bot api.

**Comment by foad-heidari** [comment]
> Both are not returned by the bot api.

@Poolitzer any suggestion how i can validate the existing user in the group?

**Comment by Poolitzer** [comment]
The second point is obtainable with the mtproto api, the first one not at all. Bots also can't get every member in a group and user api only returns 10k. So validate all might not be possible at all for you.

If you want to create a humans only group, make a new chat, only let people in with a join request, and chat personally with every one to make sure they are real people. Watch out for good text AI though :)
