### ISSUE TITLE
[BUG] Invalid MarkdownV1 parsing

### ISSUE THREAD

**Issue by why-not-try-calmer** [python-telegram-bot/python-telegram-bot#3142]
### Steps to Reproduce

1. Call the `mention_markdown(123, "Keeping_the_underscores", version=1)` function from `telegram.helpers`

### Expected behaviour

`[Keeping_the_underscores](tg://user?id=123)`, that is valid MarkdownV1 and consistent with https://core.telegram.org/bots/api#markdown-style.

### Actual behaviour

`[Keeping\\_the\\_underscores](tg://user?id=123)`. However this will fail to parse into well-formed MarkdownV1 -- in fact Telegram will respond with an error if it occurs in a message with `parse_mode = Markdown`.

### Operating System

Linux

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot==20.0a2
```

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for the catch. I can reproduce that the additional escaping produces the wrong result. What I can't reproduce is that TG raises an error. Can you provide a minimal reproducable example for that?

**Comment by why-not-try-calmer** [comment]
Hello, sorry took a couple of days off, indeed I could not reproduce the error part of this Issue from within this framework. 

To recap: 
- `[Keeping\\_the\\_underscore](URL)` (what this framework I think was trying to do) is the correct escaping but not needed in that specific context
-  `[Keeping\_the\_underscore](URL)` (what it is actually doing) is not a correct escaping

Thanks!

**Comment by Bibo-Joshi** [comment]
There's a pull request open for this at #3155. @why-not-try-calmer could you double check if that fixes your use case?
You can install the patched version via `pip install git+https://https://github.com/python-telegram-bot/python-telegram-bot.git@fix_escape_mk1`
