### ISSUE TITLE
[FEATURE] `TelegramObject.to_dict(recursion=value)`

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#3146]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Have a dict representation of `TelegramObject` without having the attributes also converted to dicts

### Describe the solution you'd like

Make `TO.to_dict` accept a parameter `recursion` that specifies up to which level attributes should be converted to dict. Logic:

* `recursion=None` (default) recurs infinitely
* `0` gives a dict representation but doesn't convert attributes to dicts
* `1` converts attributes, but not attributes of attributes
* etc

### Describe alternatives you've considered

Alternatively, a simple `recursion=True/False` could be a step in the same direction with, having the same effect as `None`/`0` described above

### Additional context

Would e.g. allow to do `ptbcontrib.send_by_kwargs(bot, chat_id=chat_id, **message.to_dict(recursion=0)`. See also https://github.com/python-telegram-bot/ptbcontrib/issues/39 which was implemented only partly

Just a wild idea so far and of no major importance to me :)

**Comment by harshil21** [comment]
what about `TGObject._get_attrs(recursive=False/True)`, which does what you said. Maybe we could make it public?

**Comment by Bibo-Joshi** [comment]
Yes, I noticed that we have these internals :D exposing the argument through `to_dict` should be rather straightforward (with some adaptions in the classes that override `to_dict`.
