### ISSUE TITLE
how to set  commands menu with this library ?

### ISSUE THREAD

**Issue by lidd77** [python-telegram-bot/python-telegram-bot#3156]
### Issue I am facing

hey,  
    I want to set  commands list menu with using this library,   I know @Botfather can also do this, 
but as a programmer,  we prefer to use  this library codes to finish this function. 
  but until now,  i still do not find any example to set commands list menu, have checked "tests" and "examples" directory.
but nothing found.  
 Any help is Welcome !

### Operating System

Linux

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a1
Bot API 6.0
Python 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0]
```

**Comment by Bibo-Joshi** [comment]
`Bot.set_my_commands`
python-telegram-bot documentation for this method:
[`telegram.Bot.set_my_commands`](https://docs.python-telegram-bot.org/telegram.bot.html#telegram.Bot.set_my_commands)

Telegram's official Bot API documentation has more info about [`setMyCommands`](https://core.telegram.org/bots/api#setmycommands).

**Comment by lidd77** [comment]
> `Bot.set_my_commands` python-telegram-bot documentation for this method: [`telegram.Bot.set_my_commands`](https://docs.python-telegram-bot.org/telegram.bot.html#telegram.Bot.set_my_commands)
> 
> Telegram's official Bot API documentation has more info about [`setMyCommands`](https://core.telegram.org/bots/api#setmycommands).

hey, thanks, the next is my code , but for ``` application ``` , there is no  "set_my_commands" property .  
where can find  a detailed  example for   [`setMyCommands`](https://core.telegram.org/bots/api#setmycommands) ?
thank you ,bro .

````
application = Application.builder().token("xxx").build()
````
