### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by andylvua** [python-telegram-bot/python-telegram-bot#3159]
### I found a kind of issue on the 13.x [wiki page](https://github.com/python-telegram-bot/v13.x-wiki/wiki) at [examples](https://github.com/python-telegram-bot/v13.x-wiki/wiki#examples-explained) section. 

The link to the bot examples page there is just a permalink to the latest examples folder at master, however, all examples in that folder have been moved to asyncio since https://github.com/python-telegram-bot/python-telegram-bot/commit/42eaa67fd51c7800c4378cc5cf3aa2b6ffa75f5c. 

### Describe the solution you'd like

<img width="767" alt="image" src="https://user-images.githubusercontent.com/93153950/179871420-edace8d3-b844-48a5-9df1-aded1b97b909.png">

I suggest **changing the examples folder link** [here](https://github.com/python-telegram-bot/v13.x-wiki/wiki#examples-explained) so it links to examples on the [point of history](https://github.com/python-telegram-bot/python-telegram-bot/tree/778eadbe7c4fd0bc79dbb7f536e3956adca0d86b/examples) before https://github.com/python-telegram-bot/python-telegram-bot/commit/42eaa67fd51c7800c4378cc5cf3aa2b6ffa75f5c commit, or better to the [examples forder](https://github.com/python-telegram-bot/python-telegram-bot/tree/v13.x/examples) on your 13.x branch. 

<img width="644" alt="image" src="https://user-images.githubusercontent.com/93153950/179871713-9192eb95-a6f7-477c-b969-796ce8cc3738.png">

**Also, link on [this section](https://github.com/python-telegram-bot/v13.x-wiki/wiki/Extensions-%E2%80%93-Your-first-Bot#what-to-read-next) has to be changed as well.**

**Comment by Bibo-Joshi** [comment]
Hi. thanks for reaching out! keeping all links up to date is sometimes not easy :D You should indeed be able to edit the pages yourself - would you like to do that?
