### ISSUE TITLE
CallbackQuery to_dict

### ISSUE THREAD

**Issue by jlmadurga** [python-telegram-bot/python-telegram-bot#316]
I am using `to_json` methods to generate telegram `Updates` for testing. I have found `CallbackQuery` do not have `to_dict` overriden just to generate field `from_user` to API key `from`.

**Comment by leandrotoledo** [comment]
@jlmadurga Good catch!

**Comment by leandrotoledo** [comment]
Released under v4.2.1

Please upgrade your version:
``$ pip install -U python-telegram-bot``
