### ISSUE TITLE
Is the setting correct it still informs KeyError: 'KEYS'

### ISSUE THREAD

**Issue by 08star** [python-telegram-bot/python-telegram-bot#3161]
### Issue I am facing

Is the setting correct it still informs KeyError: 'KEYS'

bot.ini set up

[KEYS]
bot_api = 2079XXXXX:AAF1GZp6D53OXXXXXVTnOI-nE6PEJtQcw
github_auth = 2079XXXXX

### Operating System

w10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a2
Bot API 6.1
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
```

**Comment by 08star** [comment]
async def post_shutdown(application: Application) -> None:
    await cast(Search, application.bot_data["search"]).shutdown()


def main() -> None:
    config = configparser.ConfigParser()
    config.read("bot.ini")

    defaults = Defaults(parse_mode=ParseMode.HTML, disable_web_page_preview=True)
    application = (
        ApplicationBuilder()
        .token(config["KEYS"]["bot_api"])
        .defaults(defaults)
        .post_init(post_init)
        .job_queue(RulesJobQueue())
        .build()
    )

    application.bot_data["search"] = Search(github_auth=config["KEYS"]["github_auth"])

**Comment by Poolitzer** [comment]
Hey, this is apparently a question about using python configparser. Have a look [at their docs](https://docs.python.org/3/library/configparser.html) or ask the question in [our telegram offtopic group](https://t.me/pythontelegrambottalk), but this bug tracker is dedicated to the library it belongs to (as is the case with most bug trackers), so please refrain from using it to ask unrelated questions :)
