### ISSUE TITLE
[QUESTION] Is there a way to check username if it exists?

### ISSUE THREAD

**Issue by 121me** [python-telegram-bot/python-telegram-bot#3165]
### Issue I am facing

I want to check any username if it exists as described here: https://core.telegram.org/method/account.checkUsername
Is there a way to do that? I find that some other telegram libraries are capable of doing it.

### Operating System

Fedora Linux 36

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.13
Bot API 6.1
certifi2022.05.18.1
Python 3.10.5 (main, Jun  9 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
```

**Comment by Poolitzer** [comment]
As I wrote to you in the group, bot accounts can not use that call. Also read in general what this library can or can not do: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#can-you-add-feature-to-ptb-can-i-do-thing-with-my-bot
