### ISSUE TITLE
[QUESTION] How can I access `messages.getMessageReactionsList`?

### ISSUE THREAD

**Issue by sadrasabouri** [python-telegram-bot/python-telegram-bot#3171]
### Issue I am facing

I wanted to put a handler on the user's reaction to my bot's messages. While searching for it I find [this](https://core.telegram.org/method/messages.getMessageReactionsList) on the telegram's website. But unfortunately, I couldn't find it here in **python-telegram-bot**.

### Operating System

Ubuntu 20.04

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a2
Bot API 6.1
Python 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0]
```

**Comment by Poolitzer** [comment]
As your search result says, this api method is not available for bots. In general: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#can-you-add-feature-to-ptb-can-i-do-thing-with-my-bot
