### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sstef93** [python-telegram-bot/python-telegram-bot#3179]
### Steps to Reproduce

await application.bot.set_my_commands([BotCommand("cmd1", "description")])

### Expected behaviour

Expect to set the commands

### Actual behaviour

TypeError('Object of type type is not JSON serializable')

### Operating System

Ubuntu 22

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.10.4
python-telegram-bot prerelease 20.0a2
```

### Relevant log output

```python
in set_commands
    await context.bot.set_my_commands(bot_group_commands, scope = BotCommandScopeAllGroupChats)
  File "/home/latest-env/lib/python3.10/site-packages/telegram/_bot.py", line 236, in decorator
    result = await func(*args, **kwargs)
  File "/home/latest-env/lib/python3.10/site-packages/telegram/_bot.py", line 7335, in set_my_commands
    result = await self._post(
  File "/home/latest-env/lib/python3.10/site-packages/telegram/_bot.py", line 309, in _post
    return await request.post(
  File "/home/latest-env/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 162, in post
    result = await self._request_wrapper(
  File "/home/latest-env/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 287, in _request_wrapper
    raise NetworkError(f"Unknown error in HTTP implementation: {repr(exc)}") from exc
telegram.error.NetworkError: Unknown error in HTTP implementation: TypeError('Object of type type is not JSON serializable')
```

**Comment by Poolitzer** [comment]
If you use
`await application.bot.set_my_commands([BotCommand("cmd1", "description")])`
as you wrote down in steps to reproduce, it works. bot_group_commands will not be a list of BotCommand instances.

**Comment by sstef93** [comment]
> If you use `await application.bot.set_my_commands([BotCommand("cmd1", "description")])` as you wrote down in steps to reproduce, it works. bot_group_commands will not be a list of BotCommand instances.

I had to edit _bot.py to get it to work, otherwise it is trying to json serialize the BotCommand instances objects and it throws this error.

i added the following on the set_my_commands function on _bot.py to make it work:

        cmds_ = []
        for item in cmds:
            cmds_.append({"command": item.command, "description": item.description})
        data: JSONDict = {"commands": cmds_}

        if scope:
            data["scope"] = {"type": scope}

also i've set the scope to str and pass it raw

**Comment by Bibo-Joshi** [comment]
I guess the problem is `scope = BotCommandScopeAllGroupChats`, which should instead be `scope = BotCommandScopeAllGroupChats()` (mind the `()`!).

The following MWe works fine on master:

```python
import asyncio

from telegram import BotCommand, BotCommandScopeAllGroupChats
from telegram.ext import ApplicationBuilder

application = ApplicationBuilder().token("TOKEN").build()


async def main():
    async with application:
        await application.bot.set_my_commands(
            [BotCommand("cmd1", "description")], scope=BotCommandScopeAllGroupChats()
        )


asyncio.run(main())
```

**Comment by sstef93** [comment]
> I guess the problem is `scope = BotCommandScopeAllGroupChats`, which should instead be `scope = BotCommandScopeAllGroupChats()` (mind the `()`!).
> 
> The following MWe works fine on master:
> 
> ```python
> import asyncio
> 
> from telegram import BotCommand, BotCommandScopeAllGroupChats
> from telegram.ext import ApplicationBuilder
> 
> application = ApplicationBuilder().token("TOKEN").build()
> 
> 
> async def main():
>     async with application:
>         await application.bot.set_my_commands(
>             [BotCommand("cmd1", "description")], scope=BotCommandScopeAllGroupChats()
>         )
> 
> 
> asyncio.run(main())
> ```

Thanks that worked. Is that now a bug or just a rookie mistake of mine?

**Comment by Bibo-Joshi** [comment]
rookie mistake 😉
