### ISSUE TITLE
sendPhoto

### ISSUE THREAD

**Issue by aryanbaghi** [python-telegram-bot/python-telegram-bot#318]
In python 2.7 when I use sendPhoto with image url I got this error:

> lib/python2.7/site-packages/telegram/inputfile.py", line 167, in _parse
>     return '\r\n'.join(form)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

And this is my code:

```
 bot.sendPhoto(
                     chat_id=payment.payer.chat_id,
                     photo='http://127.0.0.1:8000/%s'%project.completion_photo,
                 )

```
by the way how I could use local file?

**Comment by leandrotoledo** [comment]
> bot.sendPhoto(chat_id=chat_id, photo=open('tests/test.png', 'rb'))

More examples: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets

Make sure project.completion_photo doesn't have any unconverted unicode chars.

**Comment by aryanbaghi** [comment]
Error is in _parse method, after getting data from my local simple server. And also completion_photo is only ascii.

**Comment by leandrotoledo** [comment]
Can you post this image somewhere, so I can try to reproduce?

**Comment by leandrotoledo** [comment]
And, could you print('http://127.0.0.1:8000/%s'%project.completion_photo'), we want to reproduce the same situation.

**Comment by aryanbaghi** [comment]
http://127.0.0.1/images/573c5fd63eb8673812ca3cd0.png

and also I test `open('images/573c5fd63eb8673812ca3cd0.png', 'rb')`
got this error:

```

/lib/python2.7/site-packages/telegram/inputfile.py", line 167, in _parse
    return '\r\n'.join(form)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 0: ordinal not in range(128)
```

**Comment by leandrotoledo** [comment]
Cool, can you upload the image? Or send me in pvt via telegram

**Comment by aryanbaghi** [comment]
![573c5fd63eb8673812ca3cd0](https://cloud.githubusercontent.com/assets/4646461/15683863/b7e2631a-2779-11e6-9112-97597bab45e0.png)

**Comment by aryanbaghi** [comment]
May be because exif info? @leandrotoledo

**Comment by leandrotoledo** [comment]
Uhm, not sure if EXIF info got lost when you uploaded this image:

```
$ identify -verbose b7e2631a-2779-11e6-9112-97597bab45e0.png | grep -i "exif"
<empty>
```

Also, I was able to send the image

```
>>> bot.sendPhoto(chat_id, open('b7e2631a-2779-11e6-9112-97597bab45e0.png', 'rb'))
<telegram.message.Message object at 0x7f3bec4161d0>
```

**Comment by aryanbaghi** [comment]
Interesting  after I download it, it works!
I think I should mail it to you to check it.

**Comment by leandrotoledo** [comment]
Zip it and send to devs@python-telegram-bot.org

**Comment by leandrotoledo** [comment]
Same thing

```
>>> bot.sendPhoto(12173560, open('b7e2631a-2779-11e6-9112-97597bab45e0.png', 'rb'))
<telegram.message.Message object at 0x7faaaf342f10>
```

In fact, both photos are equal.
```
$ md5sum *.png
6887f8c1ac25924d9005c794f77e7f2f  573c5fd63eb8673812ca3cd0.png
6887f8c1ac25924d9005c794f77e7f2f  b7e2631a-2779-11e6-9112-97597bab45e0.png
```

**Comment by aryanbaghi** [comment]
I find problem.
Mongo string field is unicode I should convert it manually!
Thanks

**Comment by leandrotoledo** [comment]
Cool! But could you expand how did you find it a little bit? I'd like to understand that better.

**Comment by aryanbaghi** [comment]
When I set:
```
bot.sendPhoto(
                    chat_id=payment.payer.chat_id,
                    photo=open(str(project.completion_photo), 'rb'),
                )
```
it work
but this not worked in this way:
```
bot.sendPhoto(
                    chat_id=payment.payer.chat_id,
                    photo=open(project.completion_photo, 'rb'),
                )
```
