### ISSUE TITLE
User is unable to join the group via invite link after using unban_chat_member

### ISSUE THREAD

**Issue by Friday8229** [python-telegram-bot/python-telegram-bot#3183]
### Issue I am facing

Hi, I am using the bot in a private group where it has admin rights. Everything works flawlessly. So, here is the problem in my group users can only enter through an invite link generated by the bot. When I have to kick some user out of the group I use `bot.ban_chat_member(user_id=userid, chat_id=c.channel_id)` which works as expected. Now if I want to unban the user I use `bot.unban_chat_member(chat_id=channelid, user_id=u.userid) `  which still works but when I send the user a new invite link generated by the Bot it says the user has to wait for admin approval (this is unexpected behavior).  Is there anything that I am missing? or there is a better way to achieve the same?

### Traceback to the issue

```python
# There are no errors, It's a functionality issue.
```

### Related part of your code

```python
# Used Imports

from telegram.ext import *
from telegram import *
import telebot

# Bot Settings

bot = telebot.TeleBot(Api)

# Creating the invite link

req = bot.create_chat_invite_link(chat_id=channelid, 
                                        member_limit=1, 
                                        expire_date=my_date)


# Ban the chat member

bot.ban_chat_member(user_id=userid, chat_id=c.channel_id)

# Unban Chat member

bot.unban_chat_member(chat_id=channelid, user_id=u.userid)
```

### Operating System

Windows 10 64 bit

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.13
Bot API 6.1
certifi2022.06.15
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
> There are no errors, It's a functionality issue.

That sounds like there's little that we can do here. PTB is just a wrapper for the Bot API, it can't influence what the bot API actually does. See [this faq enty](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#can-you-add-feature-to-ptb-can-i-do-thing-with-my-bot)

> ```python
> from telegram.ext import *
> from telegram import *
> import telebot
> ```

I highly recommend to pick *one* python library that provides an interface for the Bot API and then stick to it.

**Comment by Bibo-Joshi** [comment]
As this has already been discussed at https://t.me/pythontelegrambotgroup/615530, I'll close this.
