### ISSUE TITLE
[FEATURE] Add `caption` parameter to functions that consume a media group

### ISSUE THREAD

**Issue by obviyus** [python-telegram-bot/python-telegram-bot#3185]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

For displaying a caption on a media group, one needs to set the `caption` parameter on the first element of the  list. 

### Describe the solution you'd like

I'd like to propose a _shortcut_ parameter for the methods that consume a media group; e.g. `reply_media_group` which will take a `caption` parameter and apply it on the first element of the list.

- What happens if the first item already has a caption present? Do we overwrite it?
- If `caption` is being passed, then `parse_mode` will need to be as well 

Let me know if this feature is desirable and I'll get started on making a PR.

### Additional context

<details>
  <summary>Example of a media group with a caption</summary>
  
<img width="449" alt="image" src="https://user-images.githubusercontent.com/22031114/183087820-8d21b878-b192-4060-b4ef-bf1546f6393f.png">
  
Only the first item in the list needs to have a caption for the whole media group to display it.
</details>

**Comment by Poolitzer** [comment]
I like it I have to say, it's a good shortcut. I would make it override. And by keyword only, to separate it from api keys.

+1 from me.

**Comment by harshil21** [comment]
I really like it too, and we already provide some convenience parameters like [`location`](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/_bot.py#L1953) so why not also add this. But we will also need to have `caption_entities` which can be specified instead of `parse_mode`, so 3 new params in total.

**Comment by Bibo-Joshi** [comment]
Okay, if both Pool & harshil vote to add this, I won't veto. However, I strongly vote to only accept the 3 new parameters of *none* of the InputMedia has these set, i.e. make them mutually exclusive. kwargs only is a must anyway.

**Comment by harshil21** [comment]
@obviyus would you still like to do this?

**Comment by obviyus** [comment]
@harshil21 I'd like to but I don't think I have the time to for a while. Please feel free to mark this issue as un-assigned.

**Comment by lemontree210** [comment]
Let me double-check my understanding. This behaviour (caption for the 1st item becomes a caption for the whole group) is not a quirk of PTB (as for example discussed <a href="https://stackoverflow.com/a/58895281" target="_blank">here</a>) but normal behaviour of Telegram Bot API itself (as per [issue](https://github.com/TelegramBot/Api/issues/188) for Bot API) that PTB just (so far) does not modify.

I can see how this can be similar to `location`, but it's a bit different in that we will have to handle the case not only of the _first_ item having a caption, but of _any_ item having a caption. So the user should get an exception thrown if they pass group caption and if at the same time _any_ of the items has a caption. I think this way the behaviour will be most predictable.

I'm not saying I can get this issue assigned to me already, I'm still in process of reading and understanding. But I'm focused on this.
