### ISSUE TITLE
[QUESTION] 13.13 version missmatch with documentation

### ISSUE THREAD

**Issue by Astatroth** [python-telegram-bot/python-telegram-bot#3186]
### Issue I am facing

Hi, i was looking at the error handling example and noticed that it uses Application instead of Updater. Then I noticed that in the documentation Application is also used. So the documentation is updated, but there's no such class in v13.13. It's in v20, which i suppose is not released yet. So how do you assume people to use the documentation wich is few steps ahead of the actual code?

### Operating System

Ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
Python3.9
PTB 13.13
```

**Comment by Bibo-Joshi** [comment]
The v13 examples are available [here](https://github.com/python-telegram-bot/python-telegram-bot/tree/v13.x/examples/)
