### ISSUE TITLE
[QUESTION] How to use docker restart the telegram-bot

### ISSUE THREAD

**Issue by hotchilipowder** [python-telegram-bot/python-telegram-bot#3187]
### Issue I am facing

Hello, I am using the version ```python-telegram-bot==20.0a2```.
But my internet connection is not stable enough. When my network is broken, my bot loses its connection. I need to reboot it manually, which is very annoying. I have tried to add ```read_timeout``` in [this issue](https://github.com/python-telegram-bot/python-telegram-bot/issues/3141), but it did not work.
So I switch to another solution in docker, using docker restarting.
However, I found that, unlike a normal kill, I could not use the restart mechanism provided by docker to restart my bot.
If I use ```raise SystemExit``` or ```sys.exit(-1)```, it will get stuck.
If i use ```os.kill(os.getpid(), signal.SIGINT)``` in [this issue](https://github.com/python-telegram-bot/python-telegram-bot/issues/801), my docker service will stop and never restart.

Can you give me some suggestions on how to use docker restart to restart my bot when raising some errors?
Thank you

### Traceback to the issue

```python
tg_bot_1  | =========================== logs ===========================
tg_bot_1  | navigating to "1", waiting until "load"
tg_bot_1  | ============================================================
tg_bot_1  | 2022-08-07 14:24:50,037 INFO [my_bot.py:125] rebooting
```

### Related part of your code

```python
async def kill_process_handler(update, error):
    logger.exception(error)
    logger.info('rebooting')
    os.kill(os.getpid(), signal.SIGINT)
    # sys.exit(-1) 
    # raise SystemExit 


def main():
    application = ApplicationBuilder().token(TOKEN).build()
    
    start_handler = CommandHandler('start', start)
    echo_handler = MessageHandler(filters.TEXT & (~filters.COMMAND), xxx_handler)
    
    application.add_handler(start_handler)
    application.add_handler(echo_handler)
    
    application.add_error_handler(kill_process_handler)
    application.run_polling()

if __name__ == "__main__":
    main()
```

### Operating System

Ubuntu22.04

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a2
Bot API 6.1
Python 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
```

**Comment by hotchilipowder** [comment]
The docker-compose.yml is simple as
```
services:
  tg_bot:
    image: tg_bot_app
    build: .
    command: python3 my_bot.py
    restart: always
    ports:
      - 31000:8000
```

**Comment by Bibo-Joshi** [comment]
> When my network is broken, my bot loses its connection. I need to reboot it manually

How does restarting your bot affect the network connection? I would be surprised if it did at all. If it doesn't, I don't see what the benefit of restarting the bot would be.

**Comment by hotchilipowder** [comment]
> > When my network is broken, my bot loses its connection. I need to reboot it manually
> 
> How does restarting your bot affect the network connection? I would be surprised if it did at all. If it doesn't, I don't see what the benefit of restarting the bot would be.

Hello, Thank you for your reply.
In my case,  the bot will not respond to me when network errors happened. I restart it, everything works again.
So, I hope to kill the process when encountering errors and the docker restarts it for me.

**Comment by hotchilipowder** [comment]
I am sorry, I find that ```os.kill(os.getpid(), signal.SIGINT)``` works as expected when I run ```docker-compose up -d``` instead of ```docker-compose up```.
So I closed this issue.
