### ISSUE TITLE
Hi everyone, I need your help, I  want to make a python telegram bot (v20.0a2) who reply to two differents specifics words with a one word.

### ISSUE THREAD

**Issue by shythe20** [python-telegram-bot/python-telegram-bot#3189]
### Issue I am facing

I  want to make a python telegram bot (v20.0a2) who reply to two differents specifics words with a one word.

### Operating System

Pycharm, Python v 3.10.5

### Version of Python, python-telegram-bot & dependencies

```shell
Python v 3.10.5
Python telegram bot v20.0a2
```

**Comment by harshil21** [comment]
You can add a [`filters.Regex`](https://docs.python-telegram-bot.org/en/latest/telegram.ext.filters.html#telegram.ext.filters.Regex) in your `MessageHandler` to catch two words, and then in the callback just reply with the same word. See [line 158 of conversationbot](https://docs.python-telegram-bot.org/en/latest/examples.conversationbot.html)

**Comment by shythe20** [comment]
Thank you, it's so kind

**Comment by shythe20** [comment]
`﻿from telegram import Update
from telegram.ext import filters, MessageHandler, ApplicationBuilder, CommandHandler, ContextTypes

...
async def echo(update: Update, context: ContextTypes.DEFAULT_TYPE):
     `if` 'hello' or 'hi' in update.message.text:
         await context.bot.send_message(chat_id=update.effective_chat.id, text= 'hello nice to meet you')
     if  'how are you?'  or ''how. it's going?' in update.message.text:
          await context.bot.send_message(chat_id=update.effective_chat.id, text= 'pretty good')

    
if __name__ == '__main__':
    ...
    echo_handler = MessageHandler(filters.TEXT & (~filters.COMMAND), echo)
    
    application.add_handler(start_handler)
    application.add_handler(echo_handler)

    application.run_polling()'

I want it like this, but if ran this code, it reply both of the responses in the same time.

How to fix this?`

**Comment by shythe20** [comment]
@harshil21 

``#I want it like this:

﻿from telegram import Update
from telegram.ext import filters, MessageHandler, ApplicationBuilder, CommandHandler, ContextTypes

...
async def echo(update: Update, context: ContextTypes.DEFAULT_TYPE):
   if 'hello' or 'hi' in update.message.text:
         await context.bot.send_message(chat_id=update.effective_chat.id, text= 'hello nice to meet you')
     if  'how are you?'  or ''how. it's going?' in update.message.text:
          await context.bot.send_message(chat_id=update.effective_chat.id, text= 'pretty good')

    
if __name__ == '__main__':
    ...
    echo_handler = MessageHandler(filters.TEXT & (~filters.COMMAND), echo)
    
    application.add_handler(start_handler)
    application.add_handler(echo_handler)

    application.run_polling()

#But if ran this code, it reply both of the responses in the same time.

#How to fix this?``

**Comment by harshil21** [comment]
your text probably contains both "hello" and "how are you?" and some combination of those. You can just add a `return` statement in the `if` condition, or just make the rest of the `if`'s as `elif`s

**Comment by shythe20** [comment]
@harshil21 
thank you for taking your time to reply my questions and giving helps, i realy appreciate
