### ISSUE TITLE
How to allow only the users who have joined my telegram channel to chat in my bot, and send to those who have not yet joined a message, so that they can join the channel and access to my bot 

### ISSUE THREAD

**Issue by shythe20** [python-telegram-bot/python-telegram-bot#3192]
### Issue I am facing

Hello guys!
How to allow only the users who have joined my telegram channel to chat in my bot, and send to those who have not yet joined a message, so that they can join the channel and access to my bot .
please, I realy need your helps.

### Operating System

pyhon-telegram-bot v20.0a.2, python v 3.10.5

### Version of Python, python-telegram-bot & dependencies

```shell
python v3.10.5
pyhon-telegram-bot v20.0a.2
```

**Comment by harshil21** [comment]
Wiki of python-telegram-bot - Category Design Pattern
[How do I enforce users joining a specific channel before using my bot?](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#how-do-i-enforce-users-joining-a-specific-channel-before-using-my-bot)

Also consider asking this in the [user group](https://t.me/pythontelegrambotgroup) or open a discussion instead.

**Comment by shythe20** [comment]
@harshil21 
thank you very much
I have already joined the [user group](https://t.me/pythontelegrambotgroupl)
I'm a beginner in coding, and my english is not better.
can you help me and show me where i put my channel username and the other settings of this topic or give an exemple
if i'm not mistaken this is the code;

`    @_log
    async def get_chat_member(
        self,
        chat_id: Union[str, int],
        user_id: Union[str, int],
        *,
        read_timeout: ODVInput[float] = DEFAULT_NONE,
        write_timeout: ODVInput[float] = DEFAULT_NONE,
        connect_timeout: ODVInput[float] = DEFAULT_NONE,
        pool_timeout: ODVInput[float] = DEFAULT_NONE,
        api_kwargs: JSONDict = None,
    ) -> ChatMember:

        data: JSONDict = {"chat_id": chat_id, "user_id": user_id}
        result = await self._post(
            "getChatMember",
            data,
            read_timeout=read_timeout,
            write_timeout=write_timeout,
            connect_timeout=connect_timeout,
            pool_timeout=pool_timeout,
            api_kwargs=api_kwargs,
        )
        return ChatMember.de_json(result, self)  # type: ignore[return-value, arg-type]`
