### ISSUE TITLE
AttributeError: __aenter__ when trying to use "with" on telegram.Bot

### ISSUE THREAD

**Issue by zPhoeniqz** [python-telegram-bot/python-telegram-bot#3193]
### Steps to Reproduce

1. copy the code from the quickstart guide: 
```
import telegram
import asyncio

async def main():
    bot = telegram.Bot("TOKEN")

    async with bot:
        print(await bot.get_me())

if __name__ == "__main__":
    asyncio.run(main())```
```

2. Add your bot token to the code
3. Run it

### Expected behaviour

A response of the telegram API which contains information about the bot.

### Actual behaviour

The code errors with an AttributeError:
```
Traceback (most recent call last):
  File "/home/paul/Programming/python/TelegramBot_Movies/bot.py", line 11, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/paul/Programming/python/TelegramBot_Movies/bot.py", line 7, in main
    async with bot:
AttributeError: __aenter__
```

### Operating System

RebornOS (based on Arch Linux)

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.13
Bot API 6.1
certifi2022.06.15
Python 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.
```

**Comment by harshil21** [comment]
You're on PTB v13, while the code you're trying to run is for v20. 
Either upgrade using `pip install python-telegram-bot --pre -U` or refer to the [v13 wiki](https://github.com/python-telegram-bot/v13.x-wiki)

**Comment by zPhoeniqz** [comment]
Ok, thanks. Thought `pip install python-telegram-bot --pre` would do it.
