### ISSUE TITLE
How to trigger persistence sync using a bot scheduled job? [QUESTION]

### ISSUE THREAD

**Issue by marekyggdrasil** [python-telegram-bot/python-telegram-bot#3196]
### Issue I am facing

My server has unexpectedly shutdown while the bot process was still exiting. This resulted in a corrupted pickle persistence file that could no longer be used to restore the context. I managed to manually recreate this data, it is not the object of this issue, just to give you guys some context.

I would like the bot to regularly update the pickled persistence and have my own script copy and rename those files to keep last N backups or maybe bot could create a new persistence file regularly using a scheduled job? In the section below I provide some example code with a hole to fill... Is it even possible? 

### Related part of your code

```python
from telegram.ext import Updater, PicklePersistence
from datetime import datetime

# a job that is meant to be run every 10 minutes and sync the
# bot persistence file with current context
def persistenceSyncJob(context):
    # TODO if possible, it would be good to be able to pick a filename
    _format_file = 'bot-persistence-backup-%Y-%m-%d--%H-%M-%S.pickle'
    now = datetime.now()
    filename = now.strftime(_format_file)
    # TODO if not possible to create a new persistence file
    # maybe at least I could update please-dont-get-corrupted.pickle
    # and use my own CRON job in the background to iterate and copy
    # the last N such files?
    pass

# persistence
my_persistence = PicklePersistence(filename='please-dont-get-corrupted.pickle')

# initiate the bot
updater = Updater('<your API key here>', use_context=True, persistence=my_persistence)

# initiate the job queue and register the clean-up job
ten_minutes = 10*60
job_queue = updater.job_queue
job_queue.run_repeating(persistenceSyncJob, interval=ten_minutes, first=ten_minutes)

# start polling and idle
updater.start_polling()
updater.idle()
```

### Operating System

MacOS Catalina 10.15.7

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.13
Bot API 6.1
certifi2020.12.05
Python 3.7.4 (default, Mar  4 2021, 15:06:24)  [Clang 12.0.0 (clang-1200.0.32.27)]
```

**Comment by harshil21** [comment]
It's possible for your pickle file to get corrupted at times, sorry to hear that. It's better to migrate away from pickle files (if your file is getting corrupted often) than make multiple backups. Anyway, if you still want to create more backups you should:

- get access to current saved data: (`data = context.dispatcher.user/chat/bot_data`)
- call [`data = context.dispatcher.persistence.replace_bot`](https://github.com/python-telegram-bot/python-telegram-bot/blob/v13.x/telegram/ext/basepersistence.py#L209)`(data)` to be safe.
- Simply pickle your file by opening a file and dumping it (e.g. [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/v13.x/telegram/ext/picklepersistence.py#L215))

Note that this method is untested and probably still won't save your files from corruption, and probably has some other drawbacks.

If you don't want to use this, I guess you can simply [copy](https://docs.python.org/3/library/shutil.html#shutil.copy) your pickle file as you mentioned.
