### ISSUE TITLE
[BUG] Sidebar not sorted alphabetically

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#3197]
This issue stems from the sidebar being defined in the same blocks as the api docs in telegram.rst. We should discuss if we want it (then I would vote to also include the blocks themselves in the sidebar, so make it three levels deep, or if not, then we should make it alphabetically

**Comment by 9gl** [comment]
Hey @Poolitzer  ,
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started.

**Comment by Poolitzer** [comment]
Hey, sure, what part specifically do you not understand?

**Comment by Bibo-Joshi** [comment]
I vote for nested sidebars

**Comment by Poolitzer** [comment]
I gave it a thought, yes, I think I prefer that.

**Comment by Poolitzer** [comment]
Yes, okay, now its alphabetical, but I still have to scroll down a lot of classes before I see the top level headers.

What do you think of putting everything now in three more headers: File related stuff, chat stuff, and (Generic) Objects
And have the Bot class as the first item in the list, all the other entries are categories for sub menus.

That would make finding what you are looking for easier imo.

**Comment by Bibo-Joshi** [comment]
Fine with me

**Comment by Poolitzer** [comment]
Great!
