### ISSUE TITLE
[QUESTION] Having a bot in a group show sent commands only to the user who sent it

### ISSUE THREAD

**Issue by blastbeng** [python-telegram-bot/python-telegram-bot#3204]
### Issue I am facing

Hello,
i haven't found anything in the docs about this. I want to have my bot command sent by users in a group visible only from the user who sent it. Similar to "ephermeal" responses in discord.js

In discord.js you send a command, nobody can see it and you can have the answer visible only from the user who sent it. I want to know if this can also be achieved using python-telegram-bot.

[https://discordjs.guide/interactions/slash-commands.html#ephemeral-responses](https://discordjs.guide/interactions/slash-commands.html#ephemeral-responses)

In case this isn't possibile, I want to have my bot to be silent, i don't want it to send notifications in my group, but this is actually not working in a group:

`update.message.reply_text('blablablabla', disable_notification=True, reply_to_message_id=update.message.message_id, protect_content=True)`

Any help?

Thanks

### Related part of your code

```python
update.message.reply_text('blablablabla', disable_notification=True, reply_to_message_id=update.message.message_id, protect_content=True)
```

### Operating System

Docker image: python:3.8-slim-bullseye

### Version of Python, python-telegram-bot & dependencies

```shell
python:3.8

requirements.txt:

python-telegram-bot
python-dotenv
requests
pytz
```

**Comment by Bibo-Joshi** [comment]
> In discord.js you send a command, nobody can see it and you can have the answer visible only from the user who sent it. I want to know if this can also be achieved using python-telegram-bot.

This is not possible. Please read this [faq entry](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#can-you-add-feature-to-ptb-can-i-do-thing-with-my-bot).

> In case this isn't possibile, I want to have my bot to be silent, i don't want it to send notifications in my group, but this is actually not working in a group:

`disable_notification` does not completely suppress notifications, it just makes sure that your phone doesn't make a sound when receiving the message.

---

BTW, `message.reply_text` already sets the correct value for `reply_to_message_id`, so you don't have to do that.

**Comment by blastbeng** [comment]
Thanks for the clarifications.
Closing the issue since what I asked isn't possible right now.

**Comment by blastbeng** [comment]
Sorry for reopening this, but I have an idea

As a workaround I could just delete the slash command sent, but this is working only in a private chat with the bot, not in a group. Am i wrong? Is this possible?

**Comment by Bibo-Joshi** [comment]
Please see the docs of [`delete_message`](https://docs.python-telegram-bot.org/en/v20.0a2/telegram.bot.html#telegram.Bot.delete_message) for the limitations on deleting messages. Note that deleting the message will also make it invisible to the sender. Sending a message in a group that's only visible to a selected user is not possible in any case.

**Comment by blastbeng** [comment]
Thanks again.
