### ISSUE TITLE
[QUESTION] inline_message_id is none in ChosenInlineResultHandler

### ISSUE THREAD

**Issue by ali19991377** [python-telegram-bot/python-telegram-bot#3205]
### Issue I am facing

im trying to edit a message after user chose it and send it in InlineQueryHandler .
i search a lot and all methods said that there should be something named **inline_message_id** in response of **ChosenInlineResultHandler** , but there is not anything . i want to use edit_message_text to edit the text but i dont know what id i should set for message_id or inline_message_id. both result_id and update_id tested and didnt work

### Related part of your code

```python
def inliner(update, context):
    bot = context.bot
    result = update.chosen_inline_result.result_id
    message = update.chosen_inline_result.inline_message_id
    query = update.chosen_inline_result.query
    user = update.chosen_inline_result.from_user


dp.add_handler(ChosenInlineResultHandler(inliner))
```

### Operating System

linux

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.13
Bot API 6.1
certifi2022.06.15
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
Hi. Keep in mind that `inline_message_id` is available only if the inline results contains an inline keyboard.

**Comment by ali19991377** [comment]
thank you very much . i solve my problem by adding reply_markup and i now have inline_message_id in my responses .
