### ISSUE TITLE
[QUESTION] Unable to initialize bot data while making data persistence

### ISSUE THREAD

**Issue by tech-fever** [python-telegram-bot/python-telegram-bot#3212]
### Steps to Reproduce

1. apt install python3-pip && pip install python-telegram-bot==20.0a4
2. vim main.py
3. python3 main.py

Following is my MWE (everything works fine if I remove Persistence Setup `persistence(persistence=my_persistence)` ) :
```python3
import logging
from telegram.ext import PicklePersistence, ApplicationBuilder, CommandHandler


logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)


async def say_hello(update, context):
    await update.message.reply_text(context.bot_data["hello"])


if __name__ == '__main__':
    """Persistence Setup"""
    my_persistence = PicklePersistence(filepath='my_file', update_interval=1)
    application = ApplicationBuilder().token(TOKEN).persistence(persistence=my_persistence).build()
    application.bot_data["hello"] = "Hello World!"
    application.add_handler(CommandHandler("start", say_hello))
    """Start the bot"""
    application.run_polling()
```

### Expected behaviour

I add "Hello World!" to `bot_data["hello"]`. When I send /start to bot, bot will reply `Hello World!`

### Actual behaviour

I can not add "Hello World!" to `bot_data["hello"]`

output log is as below:
```log
    await update.message.reply_text(context.bot_data["hello"])
KeyError: 'hello'
```

### Operating System

Windows 10 Enterprise / Ubuntu 20.04

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a4
Bot API 6.2
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
```

### Relevant log output

```python
(telebot) root@debian:~/telebot/scammerChannel# python main.py
2022-07-30 13:02:53,327 - apscheduler.scheduler - INFO - Scheduler started
2022-07-30 13:02:53,328 - telegram.ext._application - INFO - Application started
2022-07-30 13:02:59,766 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/miniconda3/envs/telebot/lib/python3.10/site-packages/telegram/ext/_application.py", line 983, in process_update
    await coroutine
  File "/root/miniconda3/envs/telebot/lib/python3.10/site-packages/telegram/ext/_handler.py", line 137, in handle_update
    return await self.callback(update, context)
  File "/root/telebot/scammerChannel/main.py", line 59, in say_hello
    await update.message.reply_text(context.bot_data["hello"])
KeyError: 'hello'
```

### Additional Context

Using `post_init` will be a good solution. But I still think it may be a bug (not urgent):
```python3
import logging
from telegram.ext import PicklePersistence, ApplicationBuilder, CommandHandler


logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)


async def post_init(application: Application):
    """
    Initial data refresh
    """
    application.bot_data["hello"] = "Hello World!"


async def say_hello(update, context):
    await update.message.reply_text(context.bot_data["hello"])


if __name__ == '__main__':
    """Persistence Setup"""
    my_persistence = PicklePersistence(filepath='my_file', update_interval=1)
    application = ApplicationBuilder().token(TOKEN).persistence(persistence=my_persistence).post_init(post_init).build()
    application.bot_data["hello"] = "Hello World!"
    application.add_handler(CommandHandler("start", say_hello))
    """Start the bot"""
    application.run_polling()
```

**Comment by Bibo-Joshi** [comment]
Hi. IMO this is not a bug, but expected behavior (even though I admin that it's obvious on very first glance):

`Application.run_polling` calls `Application.initialize`, which in turn loads the stored data from the persistence. This will override anything that you have set to `Application.{bot, chat, user}_data` before calling `run_polling`. Hence, if `bot_data["hello"]` was not already in the stored data, you'll get the exception.

Using `post_init` is the solution that I'd propose as well. We can also surely look into updating the documentation to emphasize this behavior more. Maybe you have a suggestion where in the documentation you would have expected this info?

**Comment by tech-fever** [comment]
Thanks for your explanation. Sorry it works with v13.x. Hence I thought it would work with v20.x too. SO it is not a bug. If I read documentation better may be I will notice that. [Here](https://docs.python-telegram-bot.org/en/v20.0a4/telegram.ext.application.html#telegram.ext.Application.initialize) has tell us `initialize()` will initialize the Application by initializing bot, updater and **persistence**.

As for documentation, I do not have a good suggestion because I used **wiki** to learn how to get start instead of documentation. Maybe here we can add this info to wiki your first bot chapter?
Like:
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-Your-first-Bot
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Making-your-bot-persistent

**Comment by Bibo-Joshi** [comment]
I added a note to the "what do I need to change" § of "Making your bot persistent". As the "Tutorial your first bot" doesn't deal with persistence yet, adding a note there would feel a bit weird to me …

**Comment by tech-fever** [comment]
😂 Thanks. If it is weird, maybe you just do not add a note. Thanks again. You may close this issue now.

**Comment by Poolitzer** [comment]
You can actually do it yourself :D
