### ISSUE TITLE
[Suggestion] Add chat(s) parameter to ChatJoinRequestHandler

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#3215]
This param should allow to filter out chats which will be handled by the ChatJoinRequestHandler, much like the pattern argument of the CallbackQueryHandler. It should allow "username" strings as well as ids and if set, the handler should check if the incoming update is from that chat.

For first time contributors, check how CallbackQueryHandler implements the pattern argument in check_update: https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/_callbackqueryhandler.py#L123

**Comment by Bibo-Joshi** [comment]
@Poolitzer CQH.pattern is rather different though, right? I&#x27;d rather compare with <a href="https://docs.python-telegram-bot.org/telegram.ext.filters.html#telegram.ext.filters.Chat">telegram.ext.filters.Chat</a> <a href="https://core.telegram.org/bots/api#chat">ᵀᴱᴸᴱᴳᴿᴬᴹ</a>

**Comment by simonfongnt** [comment]
is this still available for a newbie like me?

**Comment by Poolitzer** [comment]
Yes it is!

**Comment by simonfongnt** [comment]
i shall add the username and id (if available) before its return. is `pytest -v` sufficient to test it?
or i need to update the test_chatjoinrequesthandler as well?

**Comment by Poolitzer** [comment]
Hey @simonfongnt, while I did state that this issue is still available for you, miles already implemented this issue by now, as you probably saw already. It was my fault that I didn't double check your name and OP from the linked PR, I assumed it was you who opened it. This is my fault, I am sorry.
