### ISSUE TITLE
[Suggestion] Add mention_XXX to Chat class

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#3216]
XXX means .html and .markdown(_v2). It is supposed to mention the Chat in the picked markup. Use title or first_name + space + Lastname as the text if the input parameter name is not set (otherwise use that), and the inline mention of the chat.id.

The logic will be close to the User one, have a look at it here: https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/_user.py#L222

Also check out our [contrib](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/.github/CONTRIBUTING.rst) document to get started with this project, and don't forget to unit test your changes!

**Comment by Bibo-Joshi** [comment]
@Poolitzer @Poolitzer if you can elaborate what exactly you would like to see in #3216 and #3215, we can push them to the &quot;dev chat&quot; :) for &quot;good first issues&quot; we should IMO make a bit of an effort to guide contributors in regards of what we expect them to do (see e.g. #3075 or  #3038)

**Comment by zeehio** [comment]
> Hi, i want contribute in this project. Please assign this project to me @Poolitzer @lorien @iley @zeehio @wjt.

Hi, my contribution to this project has been just one word, fixing a typo. Please do not tag random contributors, it is distracting to us, it is inconsiderate towards our time and we are powerless to help you.

You can check the contributor insights page to find major contributors to a project

https://github.com/python-telegram-bot/python-telegram-bot/graphs/contributors

Have a nice day

**Comment by Bibo-Joshi** [comment]
@DhwanishShah glad that you like to contribute. I'm assigning this issue to you.
And please indeed don't tag people without good reason ;)

**Comment by DhwanishShah** [comment]
Hi  i am new to this  community And i want to work on this suggestion. Can you please explain this suggestoin in brief @Poolitzer .

**Comment by DhwanishShah** [comment]
Hi  I am new to this community. Can you please explain in brief about this suggestion @Poolitzer ?

**Comment by Poolitzer** [comment]
Hey, sure. Please read the description and if you have a specific technical question while implementing the mentioned changes to the Chat class, ask them, and I will explain :D

**Comment by Bibo-Joshi** [comment]
Sicne @DhwanishShah hasn't PRed so far, I'll re-assign to @Srijan-bot . @DhwanishShah if you are in fact preparing a PR, please leave a short comment here.

**Comment by DhwanishShah** [comment]
> Sicne @DhwanishShah hasn't PRed so far, I'll re-assign to @Srijan-bot . @DhwanishShah if you are in fact preparing a PR, please leave a short comment here.

Yes I am preparing PR

**Comment by Bibo-Joshi** [comment]
All right. Can you give an estimate on when you'll be PRin @DhwanishShah? It has been two weeks since your last comment 😉 

@Srijan-bot @Paari1263 please for now have a look at the other [hacktoberfest issues](https://github.com/search?q=org%3Apython-telegram-bot+label%3Ahacktoberfest+is%3Aissue+is%3Aopen) instead.

**Comment by Bibo-Joshi** [comment]
@DhwanishShah since I've not seen a reply from you since 10 days, I'll unassign you again. @Srijan-bot @Paari1263 (or anyone else) if you're still interested, please leave a short comment.

**Comment by miles170** [comment]
`tg://user?id={user_id}` is for mentioning a user.
I cannot find how to mention chat on the Telegram doc.

**Comment by MRZHD1** [comment]
Hello! I'd like to contribute if that's okay. I'm new to this repo and new to contributing, but I have worked with python quite a bit.

**Comment by MRZHD1** [comment]
> Hey, sure. Please read the description and if you have a specific technical question while implementing the mentioned changes to the Chat class, ask them, and I will explain :D
@Poolitzer

I don't get the 'mention the Chat in the picked markup'. As mentioned by miles, I can't seem to find anywhere in the API to mention chats, only mentioning users. Could you elaborate on this?

**Comment by Poolitzer** [comment]
Hi, sorry for my late response. You both are right, there is no documented way of dealing with Chats without usernames, i forgot this when writing the issue.

There is however the link to specific messages in chats with no username, https://t.me/c/chat_id/message_id. This only works if you are part of the chat ofc, and it is only really implemented for super groups/channels. But it can be used to link to a chat without a username.

I need the opinion of the maintainers of this repository before "I" can tell you if/how to implement this. There are three ways to try to abuse this link I can think of, either with adding nothing, with adding -1 or with adding a very large number (this is problematic because some groups might reach this number of messages and then the "chat link" turns into a "message link"). I have collected the behaviour on all official telegram apps:

Local group links only work in the Android App and the Web apps.

| App | Adding Nothing | Adding -1 | Adding 10000000 |
| :-: | :-: | :-: | :-: |
| Telegram Android | ❌| ✔️ | ✔️|
| Telegram X for Android | ❌| ❌<br />(opens the browser)| ✔️<br />(error message that message doesn't exist, stays in the last position in the chat)|
| Telegram iOS| ❌| ✔️ | ✔️|
| Telegram Web K| ✔️| ✔️<br />(jumps to the beginning, not to the end)| ✔️|
| Telegram Web X| ✔️<br />(Right now chats don't load their content, so I couldn't verify if they open at the bottom or not)| ✔️| ✔️|
| Telegram Desktop | ❌| ❌<br />(opens the browser)| ✔️|
| Unigram | ❌| ❌| ✔️<br />(stays in the last position in the chat)|

Until we reached a consent if and if yes, how to implement this, you could implement mentioning by chat username. This works with https://t.me/username, in the respective markup. @miles170 commented earlier, so if they want to implement this, I would give them a day to say that.

**Comment by MRZHD1** [comment]
Alright, no problem! I'll check in on this tomorrow.

**Comment by Poolitzer** [comment]
@Poolitzer https://bugs.telegram.org/c/21352 got created. Ideally we get a proper documented way to mention chats without usernames at some point.

**Comment by Bibo-Joshi** [comment]
Tbh I had thought that the main use case here would be private chats, where mentioning the chat boils down to mentioning the user. IMO it would be perfectly fine to just `return None` (or raise an exception) if the chat is not private until we have a documented way of mentioning chats.

In any case, `Chat.mention_*` should coincide with `User.mention_*` for private chats IMO.

**Comment by Poolitzer** [comment]
I would prefer the method returns the t.me link for public chats instead of None.

**Comment by harshil21** [comment]
Agree with poolitzer for public chats. For private chats we can just use `tg://user?id=` syntax

**Comment by Bibo-Joshi** [comment]
> I would prefer the method returns the t.me link for public chats instead of None.

For public chats, sure. For private group-chats, I'm leaning towards returning `None` rather than relying on not-really-supported links 🤔 

> For private chats we can just use `tg://user?id=` syntax

That's exactly what `User.mention_*` does, yes :)

**Comment by Poolitzer** [comment]
We have reached a decision. Please implement the return function the following way: 
If the chat type is PRIVATE, make the function return the usual inline text link.

If not and the chat has a username, make the text link to https://t.me/username.

If the chat does not have a username, raise a ValueError with the text set to something like "Can not create a link to a private group chat".

If you want to implement this @MRZHD1 I will assign you, everyone else had enough time to speak up :D

**Comment by miles170** [comment]
I can work on this if no one wants to take over.

**Comment by Poolitzer** [comment]
Looks like it's yours.

**Comment by miles170** [comment]
I have one question left to implement this. Should I change 
```python
def mention_html(user_id: Union[int, str], name: str) -> str
```
to
```python
def mention_html(user_id: Union[int, str], name: str, tg_link_prefix: str = "tg://user?id=") -> str
```

Since mention_XXX in chat might use it like `mention_html(id, name, tg_link_prefix="https://t.me/")`

**Comment by Poolitzer** [comment]
Currently the .link attributes of chat and user do not allow to change the prefix, I wouldn't add it in this PR.

If you think it's a good thing to have that, you can make a new issue, and we can add it everywhere at once.
