### ISSUE TITLE
[/] Button with list of commands is empty

### ISSUE THREAD

**Issue by RedLann** [python-telegram-bot/python-telegram-bot#322]
Hello, i was wondering if there is a way to show the commands i register with `	dispatcher.add_handler(CommandHandler('users', users, pass_args=True))
`
for example, in the list of commands of the bot. I noticed that some bots show you a list when you type "/" or when you tap the [/] button (near the stickers/emoji icon).

**Comment by RedLann** [comment]
Sorry just noticed it has to be done from botfather. Closing...

**Comment by hannpet** [comment]
Is it somehow possible to talk to botfather from the Bot itself? Because I wonder how I would get a chatid required to send a message to botfather...

**Comment by filipre** [comment]
Maybe it would make sense to write this down somewhere in the documentation (maybe the FAQ?). It took me a while to find out about this "command suggestion list" feature.

**Comment by zevarela** [comment]
Here's the steps I've followed to get the command list to work: 
1. Open a chat to BotFather
2. Select your bot
3. Select Edit Bot
4. Select Edit Commands
5. Paste a previously prepared list of commands like:
```
help - see list of supported commands
version - show bot version and details
```

**Comment by Bibo-Joshi** [comment]
[Setting commands via the API](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html?highlight=set_my_commands#telegram.Bot.set_my_commands) was added in [API 4.7](https://core.telegram.org/bots/api#march-30-2020), which is available since PTB [v12.6](https://python-telegram-bot.readthedocs.io/en/stable/changelog.html#version-12-6). See also #1911

**Comment by zevarela** [comment]
Many thanks @Bibo-Joshi for the quick reply, that was really helpfull!

**Comment by jayasankarj93** [comment]
Can u pls help me ? 
I m going to make a internet surfing bot . Pls give me commands in for that, i want to show searching website contents  . I am a bigginer programmer . Pls give me code for that
