### ISSUE TITLE
[QUESTION] Asynchronous Programming

### ISSUE THREAD

**Issue by windshadow233** [python-telegram-bot/python-telegram-bot#3220]
### Issue I am facing

Hello developers~

Maybe I did't read the document carefully enough, but I am just confused about asynchronous programming in python-telegram-bot.

Now I'm faced with such situation:

```python
import asyncio
from telegram import Update
from telegram.ext import (
    Application,
    CommandHandler,
    ContextTypes
)


async def long_term_task():
    await asyncio.sleep(100)
    return 0


async def command1(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.effective_message.reply_text("I am going to sleep...")
    print(await long_term_task())
    await update.effective_message.reply_text("hello~this is command 1")


async def command2(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.effective_message.reply_text("hello~this is command 2")


application = (
    Application.builder()
    .token("TOKEN")
    .build()
)

cmd1_handler = CommandHandler('command1', command1)
cmd2_handler = CommandHandler('command2', command2)
application.add_handlers([
    cmd1_handler,
    cmd2_handler
])

application.run_polling()
```

The bot is bound to two command handlers, and one of the command (for example: command1) will take a very long time. In this situation, when I send /command1, the task will be blocked so that other commands (for example: command2) will not response until command1 finishes.

Just like that:
<img width="524" alt="Xnip2022-09-05_17-36-18" src="https://user-images.githubusercontent.com/50669888/188420431-2f234d4f-87ce-43e4-8a14-908ebf3fbf38.png">

I have searched with google and issues of this repo, and find a name "Job queue", but as I tried this, I find it awkward when programming.

I tried another framework named "pyTelegramBotAPI", and found it easily to solve my problem. However I prefer to use python-telegram-bot, so make this issue to learn if their is something useful ignored by me.

### Operating System

Ubuntu 20.04

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a4
Bot API 6.2
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:05:16)  [Clang 12.0.1 ]
```

**Comment by Bibo-Joshi** [comment]
@windshadow233 Hi. Please have a look at the wiki page on <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Concurrency">Concurrency in PTB</a>.

**Comment by windshadow233** [comment]
> @windshadow233 Hi. Please have a look at the wiki page on [Concurrency in PTB](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Concurrency).

thank you~ I will carefully read it

**Comment by windshadow233** [comment]
> @windshadow233 Hi. Please have a look at the wiki page on [Concurrency in PTB](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Concurrency).

It's useful! Thanks a lot!
