### ISSUE TITLE
[QUESTION] Detect if a bot has been promoted to admin

### ISSUE THREAD

**Issue by shravandoda** [python-telegram-bot/python-telegram-bot#3222]
### Issue I am facing

After manually adding a bot to a group, the owner may or may not promote the bot to admin rights. Is there a way to detect if the bot has been promoted to admin?

### Operating System

Mac OS

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2020.12.05
Python 3.8.12 (default, Feb  1 2022, 12:35:13)  [Clang 13.0.0 (clang-1300.0.29.30)]
```

**Comment by Bibo-Joshi** [comment]
@shravandoda You can either keep track of permission change events via <a href="https://docs.python-telegram-bot.org/telegram.update.html#telegram.Update.my_chat_member">telegram.Update.my_chat_member</a> <a href="https://core.telegram.org/bots/api#update">ᵀᴱᴸᴱᴳᴿᴬᴹ</a> (see also the <a href="https://docs.python-telegram-bot.org/examples.html#examples-chatmemberbot">chatmemberbot.py</a> example) and/or get the info via <a href="https://docs.python-telegram-bot.org/telegram.bot.html#telegram.Bot.get_chat_member">telegram.Bot.get_chat_member</a> <a href="https://core.telegram.org/bots/api#getchatmember">ᵀᴱᴸᴱᴳᴿᴬᴹ</a>.

**Comment by shravandoda** [comment]
Gotcha. Thanks very much @Bibo-Joshi
