### ISSUE TITLE
Copy message from other channel

### ISSUE THREAD

**Issue by ashkufaraz** [python-telegram-bot/python-telegram-bot#323]
Hi
Sorry,I have a question about your project(telegram).
Can I get the message channels that I'm not their admin?
I want write a script that read message from other chanel and write to
my chanel.
I can do it?
best regards
thanks

**Comment by jh0ker** [comment]
Hi @ashkufaraz 
The Telegram Bot API has no way for a bot to receive messages in a channel. 
The reason for that: To prevent infinite feedback message loops, bots can not receive any messages sent by other bots. In a channel, the source of a message is unknown - it could always be a bot.
