### ISSUE TITLE
[QUESTION] Async env

### ISSUE THREAD

**Issue by searayeah** [python-telegram-bot/python-telegram-bot#3230]
### Issue I am facing

This thing starts async bot in a sync environment.
```python
def main() -> None:
    application = Application.builder().token("TOKEN").build()
    application.run_polling()

if __name__ == "__main__":
    main()
```
But is there a way to start async bot in async environment?
Something like that??
```python
async def main() -> None:
    application = Application.builder().token("TOKEN").build()
    await application.run_polling()

if __name__ == "__main__":
    asyncio.run(main())
```

### Operating System

Linux

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a4
Bot API 6.2
Python 3.7.6 (default, May  7 2022, 13:31:42)  [GCC 11.2.0]
```

**Comment by Bibo-Joshi** [comment]
[`Application.run_polling`](https://docs.python-telegram-bot.org/en/v20.0a4/telegram.ext.application.html?highlight=run_polling#telegram.ext.Application.run_polling) basically does something like 

```python
await application.initialize()
await application.start()
await application.updater.start_polling()
# run until it receives a stop signal
await application.updater.stop()
await application.stop()
await application.shutdown()
```

You can ofc also do that manually. See also the [`customwebhookbot`](https://docs.python-telegram-bot.org/en/v20.0a4/examples.customwebhookbot.html) example, where this is showcased in the context of using a custom webserver.

**Comment by searayeah** [comment]
Thanks a lot! That solved my issue.
