### ISSUE TITLE
[QUESTION] How to check which date user set their profile pictures

### ISSUE THREAD

**Issue by Foadsf** [python-telegram-bot/python-telegram-bot#3238]
### Issue I am facing

I am very new to the whole Telegram bot development. I have followed some initial tutorials, though to be sure that I am moving in the right direction, I am posting this question here.
My end goal is to develop a bot for my group and detect some potentially malicious users. I want the bot to check every new user and send the date-time of the user's first profile picture, to another group. 
I was wondering if this is possible or not. and if it is possible please point me to the right direction and some sample/relevant examples. 

### Operating System

macOS, Windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a4
Bot API 6.2
Python 3.10.6 (main, Aug 30 2022, 05:12:36) [Clang 13.1.6 (clang-1316.0.21.2.5)]
```

**Comment by Poolitzer** [comment]
@Foadsf No, you can&#x27;t get the date time when a user set a profile picture.

**Comment by Foadsf** [comment]
@Poolitzer what info I can get from a user?

**Comment by Poolitzer** [comment]
@Foadsf Check <a href="https://docs.python-telegram-bot.org/telegram.user.html#telegram.User">telegram.User</a> <a href="https://core.telegram.org/bots/api#user">ᵀᴱᴸᴱᴳᴿᴬᴹ</a> :)
