### ISSUE TITLE
bot.sendPhoto doesn't work anymore

### ISSUE THREAD

**Issue by ar3ac** [python-telegram-bot/python-telegram-bot#324]
I can't send photo anymore....

 bot.sendPhoto(chat_id=id_number, photo="http://url_of_img" )

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/telegram/bot.py", line 121, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/telegram/bot.py", line 147, in decorator
    result = request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/lib/python2.7/site-packages/telegram/utils/request.py", line 71, in decorator
    message = _parse(error.read())
  File "/usr/lib/python2.7/site-packages/telegram/utils/request.py", line 49, in _parse
    raise TelegramError('Invalid server response')
telegram.error.TelegramError: Invalid server response

Operating System: archlinux on raspberry pi

Version of Python: Python 2.7.11

Version of python-telegram-bot : 4.2.1

**Comment by leandrotoledo** [comment]
@ar3ac are you sure the URL is still valid? ``telegram.error.TelegramError: Invalid server response`` tells me something. If so, please send the URL of img so I can try to reproduce your issue.

Thanks.

**Comment by ar3ac** [comment]
This morning always that error message,
Now it works...
thanks anyway for your attention.

**Comment by ar3ac** [comment]
Ok this morning again,
the url of the image is this : 

http://s33.postimg.org/plci93h4v/image.png

same error , invalid server response

**Comment by ar3ac** [comment]
I have a script in the crontab that send me a photo once a day,
and make a check every 10 minutes.
Now that image arrived.
Very strange.

**Comment by leandrotoledo** [comment]
@ar3ac seems like you need to handle these exceptions and implement some retry/timeout logic, as ``Invalid server response`` indicates server unavailable at the moment of request.

```
try:
   bot.sendPhoto(chat_id=id_number, photo="http://url_of_img" )
except telegram.error.TelegramError:
   retry_logic()
```

**Comment by ar3ac** [comment]
did you try to send you the image url ?
just to know it's only my problem,

thanks anyway

**Comment by leandrotoledo** [comment]
@ar3ac 

```
>>> bot.sendPhoto(chat_id=chat_id, photo='http://s33.postimg.org/plci93h4v/image.png')
<telegram.message.Message object at 0x7f719cf02f50>
```

**Comment by ar3ac** [comment]
i just try to send the message from an ubuntu machine, 
same error,
maybe i need to upgrade some modules ? is it possibile ?

**Comment by leandrotoledo** [comment]
@ar3ac could you paste the output of ``curl -I http://s33.postimg.org/plci93h4v/image.png``?

**Comment by ar3ac** [comment]
sure,

HTTP/1.1 200 OK
Date: Mon, 13 Jun 2016 13:51:45 GMT
Content-Type: image/png
Content-Length: 271679
Connection: keep-alive
Set-Cookie: __cfduid=d6f28141d1c3780e436f3ed9879d4582c1465825905; expires=Tue, 13-Jun-17 13:51:45 GMT; path=/; domain=.postimg.org; HttpOnly
Last-Modified: Mon, 13 Jun 2016 00:39:42 GMT
ETag: "575e00ce-4253f"
CF-Cache-Status: HIT
Expires: Tue, 13 Jun 2017 13:51:45 GMT
Cache-Control: public, max-age=31536000
Accept-Ranges: bytes
Server: cloudflare-nginx
CF-RAY: 2b2604e2da900e4e-MXP

**Comment by ar3ac** [comment]
on ubuntu the error change :  

>>> bot.sendPhoto(chat_id=16371820, photo=img)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 128, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 145, in decorator
    return Bot._post_message(url, data, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 175, in _post_message
    network_delay=network_delay)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 85, in decorator
    raise Unauthorized()
telegram.error.Unauthorized: Unauthorized

**Comment by leandrotoledo** [comment]
@ar3ac Unauthorized, per https://github.com/python-telegram-bot/python-telegram-bot/wiki/Exception-Handling

```
Example: You're trying to send a message, but the user blocked the bot. An Unauthorized exception, a subclass of TelegramError, will be raised and delivered to your error handler, so you can delete it from your conversation list, if you keep one.
```

Try a different chat_id.

**Comment by ar3ac** [comment]
but on that id ( that is me on my phone ) i can send simple messages with senbMessage anytime i want

**Comment by ar3ac** [comment]
i just try with another image and there is no error, just that url!

**Comment by henesy557616** [comment]
The problem is in the old version of api. I changed my npm library and it worked. I leave a link to the repository https://www.npmjs.com/package/telegram-bot-api
