### ISSUE TITLE
[QUESTION] How to install

### ISSUE THREAD

**Issue by Faizan711** [python-telegram-bot/python-telegram-bot#3241]
### Issue I am facing

I can't understand the installation process in windows. Can someone explain that is is necessary to have The Telegram Desktop to install the bot in the windows???

### Operating System

Windows 

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.
```

**Comment by harshil21** [comment]
This is a library used to make Telegram Bots in Python. Telegram Desktop is an application to use Telegram easily on desktop. Both are not related. The installation process for this library is very clear.
