### ISSUE TITLE
[QUESTION] location from telegram in exponent format

### ISSUE THREAD

**Issue by jekeam** [python-telegram-bot/python-telegram-bot#3248]
### Issue I am facing

I got strange coordinates from telegram itself, in exponent format, how to work with this, it looks like this is a telegram bug? So far there has been only one error and usually the coordinates come correctly in the format 00.123456 and now 3e-06, but I have few users, can anyone come across this? Received coordinates:

` "location": {
      "longitude": 3e-06,
      "latitude": 1e-05
    },`

### Operating System

Unix

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a2
Bot API 6.1
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
```

**Comment by harshil21** [comment]
I suppose the only way this can happen is if a user has spoofed their location to 0.000, 0.000 ([Null Island](https://en.wikipedia.org/wiki/Null_Island)). 

You can work with this easily since it still a `float`. Access it with `update.effective_message.location`
