### ISSUE TITLE
UnicodeDecodeError in bot.sendPhoto

### ISSUE THREAD

**Issue by ishalyminov** [python-telegram-bot/python-telegram-bot#326]
### Steps to reproduce
1. photo_file = open('tests/data/telegram.jpg')

2. bot.sendPhoto(chat_id, photo_file)

### Expected behaviour

Photo would be sent successfully

### Actual behaviour

telegram/inputfile.py:154
*** UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

### Configuration
**Operating System:**
OSX El Capitan

**Version of Python:**

``$ python -V``
Python 2.7.11

**Version of python-telegram-bot:**

``$ python -c 'import telegram; print(telegram.__version__)'``
4.2.1

### Logs
Insert logs here (if necessary)

**Comment by ishalyminov** [comment]
UPD: works under python3, only reproduced under python2

**Comment by jh0ker** [comment]
Hello! The problem might be that you're reading the file in ASCII mode. Try this instead:

`open('tests/data/telegram.jpg')`

**Comment by jh0ker** [comment]
Sorry :D `open('tests/data/telegram.jpg', 'rb')`

**Comment by ishalyminov** [comment]
Tried that as well, even tried passing the url to file - no luck

**Comment by leandrotoledo** [comment]
@ishalyminov please take a look at #318, maybe you are doing something similar to that?

**Comment by ishalyminov** [comment]
```
bot.sendPhoto(
                    chat_id=payment.payer.chat_id,
                    photo=open(str(project.completion_photo), 'rb'),
                )
```

`str()` - Good idea, will try (although the path to the file is ASCII-only, and the photo itself is from your unit-tests which work ok and don't use str() :)).

**Comment by ishalyminov** [comment]
Yes, str() did the thing.

**Comment by jh0ker** [comment]
@tsnoam suggested you might be using `from __future__ import unicode_literals` in your code, effectively "converting" all regular strings in your code to unicode strings. Could you check if that is the case?

**Comment by ishalyminov** [comment]
No, no such import in my code.

**Comment by jh0ker** [comment]
Ok, thank you for checking

**Comment by dontsovcmc** [comment]
This is a problem in Python 2.7!
sendPhoto works only if image opens with str "path", not Unicode "path"!

requests.py: 
result = _request_wrapper('POST', url, body=data.to_form(), headers=data.headers) # data.to_form() failed

**Comment by dontsovcmc** [comment]
jh0ker, argument caption in sendPhoto also doesn't works with Unicode string (Python 2.7)

**Comment by leandrotoledo** [comment]
@dontsovcmc  We don't cast encode strings, so if you have Unicode chars in your path/caption it is expected to encode them manually IMO. Before we got rid of all .(en|de)code in our codebase it was hard to maintain this transition of unpredictable input strings to Unicode and then send to Telegram in UTF-8. 

Original bug #239 

We look forward for suggestions on how to improve that but without going to much on encode behalf the user.

Thanks.
