### ISSUE TITLE
[BUG] telegram.Bot class doesn't have a '__aenter__' attribute

### ISSUE THREAD

**Issue by amirHosseinAsghari** [python-telegram-bot/python-telegram-bot#3260]
### Steps to Reproduce

`import asyncio
import telegram

async def main():
    bot = telegram.Bot("TOKEN")
    async with bot:
        print(await bot.get_me())

if __name__ == '__main__':
    asyncio.run(main())`

### Expected behaviour

the bot object should be compatible with async 

### Actual behaviour

But the bot obj created from telegram.Bot can work with asyncio 

### Operating System

Ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.14
Bot API 6.2
certifi2022.09.24
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
```

**Comment by harshil21** [comment]
@amirHosseinAsghari See https://github.com/python-telegram-bot/python-telegram-bot/issues/3040#issuecomment-1128440437
