### ISSUE TITLE
[QUESTION] Joining specific telegram channel

### ISSUE THREAD

**Issue by EnkhAmar** [python-telegram-bot/python-telegram-bot#3262]
### Issue I am facing

Hello,
Is this library supports joining other telegram channel as a bot? If not how can i join the other channel as my bot. I want channel listener bot.

### Operating System

MacOS

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a4
Bot API 6.2
Python 3.10.6 (main, Aug 11 2022, 13:36:31) [Clang 13.1.6 (clang-1316.0.21.2.5)]
```

**Comment by Bibo-Joshi** [comment]
bots can't join chats on their own, no. That's not a limitation of this library though, but of the bot API itself. See also [this faq entry](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#can-you-add-feature-to-ptb-can-i-do-thing-with-my-bot).
