### ISSUE TITLE
How to use argument messageautodeletetimerchanged?

### ISSUE THREAD

**Issue by nuranov04** [python-telegram-bot/python-telegram-bot#3264]
### Issue I am facing

I try user argument message_auto_delete_timer_changed in message instance but python interpeteter raise exeption AttributeError. I checked documentation but there isn't noting info
about argument message_auto_delete_timer_changed and how can use this method. There is, but it's wrong.
Can you help me please?

P.s. Sorry for my English. I'm just beginner learning English :)

### Traceback to the issue

```python
File "/home/artur/Desktop/vscode/python/telegram_bot/bot.py", line 15, in commands_processing
    msg.message_auto_delete_timer_changed(10)
AttributeError: 'Message' object has no attribute 'message_auto_delete_timer_changed'
```

### Related part of your code

```python
@bot.message_handler(commands=['start', 'stop', 'info'])
def commands_processing(message):
    print(message.text)
    if message.text == '/start':
        msg = bot.send_message(chat_id=message.chat.id, text='Hello world', timeout=20)
        msg.message_auto_delete_timer_changed(10)
```

### Operating System

linux ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.10.6
pyTelegramBotAPI==4.7.0
```

**Comment by Bibo-Joshi** [comment]
Hi. This is the issue tracker for the `python-telegram-bot` library. Your code does not look like you're using that library.
