### ISSUE TITLE
[QUESTION] How do u get the phone number of the user using the bot ?

### ISSUE THREAD

**Issue by kaikiat** [python-telegram-bot/python-telegram-bot#3265]
### Issue I am facing

How do u get the phone number of the user using the bot ?

### Traceback to the issue

```python
-
```

### Related part of your code

```python
-
```

### Operating System

macOs

### Version of Python, python-telegram-bot & dependencies

```shell
-
```

**Comment by Bibo-Joshi** [comment]
@kaikiat Wiki of <i>python-telegram-bot</i> - Category <i>Code Snippets</i>
<a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#requesting-location-and-contact-from-user">Requesting location and contact from user</a>
