### ISSUE TITLE
Refactor InputFile to use urllib3

### ISSUE THREAD

**Issue by leandrotoledo** [python-telegram-bot/python-telegram-bot#328]
Per @jh0ker on developers group:

```
urllib3 supports multipart-encoding out of the box
can we use that instead of InputFile.to_form?
```

http://urllib3.readthedocs.io/en/latest/helpers.html#urllib3.filepost.encode_multipart_formdata

**Comment by tsnoam** [comment]
I suggest also changing botan.py to use urllib3 in the process. (i.e. eliminate all traces of urllib/urllib2)

**Comment by tsnoam** [comment]
closing. better stay with what we have. we don't know that will always use urllib3 and won't switch to something else.
