### ISSUE TITLE
Address DeepSource issues

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#3285]
For a while, DeepSource has been reporting issues in a number of PRs which

* mostly are not really related to the changes in those PRs
* partly are false positives
* we probably just want to ignore.

It would be nice if we somehow could review at least most of these issues and address them. I haven't yet found an overview where one can see all the failures at once, but via https://deepsource.io/gh/python-telegram-bot/python-telegram-bot/history/runs one can at least rather quickly access all PR runs of DS.

In this context, I have already openend a feature-request-thread over at DS: https://discuss.deepsource.io/t/improve-granular-setting-possibility-to-pin-a-deepsource-version/472.

**Comment by techrajdeep** [comment]
Hey @Bibo-Joshi , I am looking for an issue for my first contribution . Can you help me here.

**Comment by Bibo-Joshi** [comment]
Hi. Glad that you're interested in contributing!
TBH I don't see this issue as a good fit for a first contribution, as it requires some familarity with the code base and probably also access to PTBs DeepSource account. Please instead have a look at the issues that we marked for first contributions & the hacktoberfest: https://t.me/pythontelegrambotchannel/124
