### ISSUE TITLE
I ran into a problem when using send_photo

### ISSUE THREAD

**Issue by chenjieup** [python-telegram-bot/python-telegram-bot#3293]
### Issue I am facing

for i in photo_list:
    photo_url = SOURCE[source]+ i
    photo = requests.get(photo_url).content
    context.bot.send_photo(chat_id=update.effective_chat.id, photo=photo, read_timeout=50)
========================================
  File "D:/telgrambot/bot.py", line 242, in get_one_ziyuan
    context.bot.send_photo(chat_id=update.effective_chat.id, photo=photo, read_timeout=50)
  File "C:\Users\chenjie\Anaconda3\envs\web\lib\site-packages\telegram\bot.py", line 127, in decorator
    result = func(*args, **kwargs)
TypeError: send_photo() got an unexpected keyword argument 'read_timeout'

### Traceback to the issue

```python
File "D:/telgrambot/bot.py", line 242, in get_one_ziyuan
    context.bot.send_photo(chat_id=update.effective_chat.id, photo=photo, read_timeout=50)
  File "C:\Users\chenjie\Anaconda3\envs\web\lib\site-packages\telegram\bot.py", line 127, in decorator
    result = func(*args, **kwargs)
TypeError: send_photo() got an unexpected keyword argument 'read_timeout'
```

### Related part of your code

```python
for i in photo_list:
    photo_url = SOURCE[source]+ i
    photo = requests.get(photo_url).content
    context.bot.send_photo(chat_id=update.effective_chat.id, photo=photo, read_timeout=50)
```

### Operating System

win 7

### Version of Python, python-telegram-bot & dependencies

```shell
python==3.6
python-telegram-bot==13.5
```

**Comment by chenjieup** [comment]
please help me!

**Comment by Poolitzer** [comment]
@chenjieup read_timeout isn&#x27;t a parameter for send_photo, timeout is if you want to change that, see also the docs at <a href="https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.send_photo">telegram.Bot.send_photo</a> <a href="https://core.telegram.org/bots/api#sendphoto">ᵀᴱᴸᴱᴳᴿᴬᴹ</a>
