### ISSUE TITLE
[QUESTION] Is there way to view the file transmission progress on ptb?

### ISSUE THREAD

**Issue by akash-user** [python-telegram-bot/python-telegram-bot#3301]
### Issue I am facing

Example: on send_video or document 

I am using Local Bot API Server + HTTP URL for the webhook

### Operating System

ubuntu Budgie 22.04

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.14
Bot API 6.2
certifi2022.09.24
Python 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
```

**Comment by Poolitzer** [comment]
This is not a question for PTB but for the bot AP, see tdlib/telegram-bot-api#37
