### ISSUE TITLE
[BUG] Runtime errors when running tests due to missing libraries

### ISSUE THREAD

**Issue by lemontree210** [python-telegram-bot/python-telegram-bot#3329]
### Steps to Reproduce

1. Follow the installation steps listed in [contributing guidelines](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/.github/CONTRIBUTING.rst)
2. Run all unit tests.

### Expected behaviour

Tests get loaded and run

### Actual behaviour

Error messages pop up, such as:
```
RuntimeError: To use Telegram Passports, PTB must be installed via `pip install python-telegram-bot[passport]`.
```
So in order to have the tests run smoothly, I had to run two additional commands (from my virtual environment, obviously):

```bash
pip install python-telegram-bot[passport]
pip install python-telegram-bot[rate-limiter]
```

I also have the following command I ran prior to those, but unfortunately I don't remember what the error message was that made me run it.

```bash
pip install python-telegram-bot -U --pre
```

### Operating System

Ubuntu 20.04

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a4 (v20.0a4-65-g03cec0b8)
Bot API 6.2
Python 3.9.15 (main, Oct 12 2022, 19:14:24)  [GCC 9.4.0]
```

**Comment by Bibo-Joshi** [comment]
Hi.

The contribution guide was recently updated. Step 4 in "Setting things up" now reads `pip install -r requirements-all.txt`. That will install all optional dependencies.
Installing PTB into your development environment via pip does not seem like a good idea to me, as it could lead to confusion between the PTB version that you're currently working on (`path/to/your/git/repo/python-telegram-bot/telegram`) and the PTB version that pip installed to to `path/to/your/python/version/site-packages/telegram`.

**Comment by lemontree210** [comment]
OK thank you, closing this issue.
