### ISSUE TITLE
set/change size of InlineKeyboardMarkup buttons like ReplyKeyboardMarkup

### ISSUE THREAD

**Issue by alirezaimi** [python-telegram-bot/python-telegram-bot#333]
I have 4 keys in my telegram bot api with InlineKeyboardMarkup, but when i send it for android client size of buttons is too small that user can see.In web client of telegram these icons is ok and have very well size !
http://i.stack.imgur.com/xo2Th.png
Is there any way to set buttons size in InlineKeyboardMarkup like ReplyKeyboardMarkup and resize_keyboard parameter? or customize these buttons size and ... ?

```
class Ctmp: pass
ctobj = Ctmp()
ii = 0
a = []
for k, v in ddd.items() :
    if ( len(k) > 0 and len(v) > 0 ) :
        print(k, v)
        setattr(ctobj, 'repkey'+ str(i),  InlineKeyboardButton(text= str(v), callback_data=str(k), resize_keyboard=True))
        a.append( getattr(ctobj, 'repkey' + str(i)) )
        ++ii

repl = InlineKeyboardMarkup([a])
bot.sendMessage(chat_id= dd.get("chatid", None), text="/", reply_markup=repl)
```
http://stackoverflow.com/questions/38159182/set-change-size-of-inlinekeyboardmarkup-buttons-like-replykeyboardmarkup

**Comment by anviloro** [comment]
I'm experiencing the same problem, break line didn't work.

**Comment by jh0ker** [comment]
Sorry, there is nothing we can do here. It's an issue of these particular Telegram client implementations, not the Bot API.

**Comment by rhaspody** [comment]
i have a noob question. how do i customise button function on inlinekeyboardbutton. im new to python
