### ISSUE TITLE
how to connect user and client through a bot chat initiated by client?

### ISSUE THREAD

**Issue by SergejGorev** [python-telegram-bot/python-telegram-bot#3330]
### Issue I am facing

I am trying to implement a possibility for a manager to step in, and take over the conversation using the same chat initiated by user/bot interaction. So, for example, user starts the bot ... clicks on connect to manager. Manager (real person) takes over the conversation, while bot is on sleep for the time, an they talk in the same chat. Important, so the user dont need to click around additional times.

Is it possible?

### Operating System

ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a4
Bot API 6.2
Python 3.10.6 (main, Oct  7 2022, 20:19:58) [GCC 11.2.0]
```

**Comment by clot27** [comment]
You can use [Conversations](conversationbot.py (https://docs.python-telegram-bot.org/examples.html#examples-conversationbot)) for this task, try to make your question more clear so we can help you better :)

**Comment by lemontree210** [comment]
I guess [this](https://docs.python-telegram-bot.org/examples.html#examples-conversationbot) was the intended link to the examples :)
