### ISSUE TITLE
[FEATURE] NamedHandler and/or handlers with name argument

### ISSUE THREAD

**Issue by clot27** [python-telegram-bot/python-telegram-bot#3338]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Hi, as referenced originally in PTB group [here](https://t.me/pythontelegrambotgroup/635972) the ability to add/remove handlers by name is more convinient. I can think of two approaches for this:

### **1. Add a NamedHandler**
Add another handler called NamedHandler which wraps existing handlers. This handler can be used add a handler with name argument. e.g.
```
start_handler = CommandHandler("start", callback)
name_handler = NamedHandler(start_handler, name="start")
```

### **2.  Add a name paramtere to all type of handlers**
Add optional name parametre to all handlers, e.g.
```
start_handler = CommandHandler("start", callback, name="start")
```
If multiple handlers have the same name only the first one which is registered is removed by application.remove_handler().
IMO first one is more convinient 🤓

**Comment by harshil21** [comment]
tbh, I don't see a good use case for this. Do you have one in mind?

I think you would need access to handlers only if you are doing some hacky stuff I think. Also access to handlers is already available via `application.handlers`, from which one can delete handlers too

**Comment by Bibo-Joshi** [comment]
I tend to agree with harshil here, at least at first glance. IISC, the OP in the group didn't give an explanation of what they would use this for, but in my experience that particular OP has a tendency to over-engineer things a bit … If one wants a unique identifier for a given handler, once could always do something like `MY_SPECIAL_HANDLER: int = id(some_handler`.

**Comment by clot27** [comment]
The alternative suggested by hinrich is pretty nice, closing this as no good arguments in favour...
