### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by DarkSkull91** [python-telegram-bot/python-telegram-bot#3339]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Because updating some libraries with Pip I got these errors:
`python-telegram-bot 13.14 requires APScheduler==3.6.3, but you have apscheduler 3.9.1 which is incompatible.
python-telegram-bot 13.14 requires cachetools==4.2.2, but you have cachetools 5.2.0 which is incompatible.
python-telegram-bot 13.14 requires tornado==6.1, but you have tornado 6.2 which is incompatible.`

### Describe the solution you'd like

I think it woul be nice to update the code to support these versions

**Comment by harshil21** [comment]
Have a look at #3259. Also note that in v13 is in "API compatibility" mode and won't get any additional improvements. This has been fixed in v20.

**Comment by DarkSkull91** [comment]
Where is hte v20 version? Is it possible to install it with pip? Is a stable version?

**Comment by clot27** [comment]
whats "hte"?

**Comment by clot27** [comment]
> Where is hte v20 version? Is it possible to install it with pip? Is a stable version?

I feel like you meant the, yes you can install v20 by `pip install python-telegram-bot --pre`, no its not stable but you can use it for small projects very well.

**Comment by DarkSkull91** [comment]
One last question, if I install the v20 version, it automatically delete the v13 or I have to uninstall it manually?

**Comment by clot27** [comment]
@DarkSkull91 it will automatically delete the v13

**Comment by DarkSkull91** [comment]
Thank you very much for you answers! It's a very great project!
