### ISSUE TITLE
[Feature] Bot API 6.3 update

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#3340]
This issue exists to keep track of the implementation of the 6.3 Update.

- [x] Topics (in groups):
  - [x] can_manage_topics in classes ChatAdministratorRights, ChatMemberAdministrator, ChatPermissions, ChatMemberRestricted 
  - [x] also in Bot function promoteChatMember
- [x] Message class
  - [x] new empty classes ForumTopicReopened, ForumTopicClosed 
  - [x] new class ForumTopicCreated
  - [x] add to all shortcuts thread_message_id, and add new shortcuts if needed (doubtful, but I did not check)
- [x] changed docstring: setChatTitle title attribute and deleteMessage
- [x] new param message_thread_id to too many methods to list
- [x] Chat
  - [x] needs shortcuts to all new methods except getForumTopicIconStickers
- [x] implement new methods
  - [x] new class ForumTopic

**Comment by lemontree210** [comment]
I think I should be able to handle adding param `message_thread_id` to those numerous methods. Any pitfalls a newcomer wouldn't spot there?

**Comment by Poolitzer** [comment]
@lemontree210 Doubt it. Think about adding it before the * in the param list, the docstring, the tests (if no fitting one exists create them, there should always be one mocking telegrams response and check all params), and you are good.

**Comment by clot27** [comment]
Should I do the Topics (in groups) part?

**Comment by Poolitzer** [comment]
@clot27 If you want to, sure :)

**Comment by Poolitzer** [comment]
I will do the docstring changes now and then a couple new methods
