### ISSUE TITLE
[BUG] Broken links for examples directory

### ISSUE THREAD

**Issue by GauthamramRavichandran** [python-telegram-bot/python-telegram-bot#3349]
### Steps to Reproduce

1. All the examples would lead to 404 page if version < v20a. Talking about [this part](https://github.com/python-telegram-bot/python-telegram-bot/blob/53c3a130ab2d46624a74adcd4bf2fc1063a9ce8f/examples/conversationbot2.py#L31). Since read-the-docs didn't had an examples page prior to v20a.
2. Examples mentioned in some wiki links are also [broken](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#get-the-new-members-message). Check out the example mentioned in that block

### Expected behaviour

Working link

### Actual behaviour

Broken link

### Operating System

Mac OS

### Version of Python, python-telegram-bot & dependencies

```shell
ptb < v20
```

**Comment by clot27** [comment]
Hi, the links you mentioned are fine for m, also how those links relate with the ptb version?

**Comment by Bibo-Joshi** [comment]
Closing since we've just released v20.0 and hence no longer support 13.x. As a side effect of this release, the links should actually work again :D
