### ISSUE TITLE
Use `Sequence` instead of `Union[List[…], Tuple[…]]`

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#3350]
Currently we accept only `List` for arguments that Telegram documents as "array". This limitation is rather unnecessary. Passing a tuple will in fact also work out of the box since the `json` module automatically converts tuples to json arrays. 

IMO it's sane to expect every object that is iterable, with finite length and fixed order of elements to work - which brings us to [`Sequence`](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes). Once could argue that we don't strictly need fixed order and instead go for `Collection`, but for most objects, the order of elements does change the behavior of Telegram and using `Sequence` avoids one possible source of confusion for users. The only example I can think of where order doesn't matter are the `(caption_)entities` arguments …

This is also in symmetry with #3249, which accepts `Sequence` for class arguments and converts them to tuple.

The only downside of this approach is that we need one additional check somewhere in `RequestParameter` along the lines

```
if not isinstance(object, (tuple, list)):
    object = list(object)
```

as otherwise `json.dumps` would fail.

Edit: More precisely, the edit would be required here:

https://github.com/python-telegram-bot/python-telegram-bot/blob/5c3b06f015c7ae5e02f23a2a9a2afea37c551dee/telegram/request/_requestparameter.py#L141-L146

**Comment by Bibo-Joshi** [comment]
I just realize that we indeed already use `Union[List[…], Tuple[…]]` in most of these places. Still, I.d like to replace that with `Sequence` wherever possible (there are also a few places besides bot methods)

**Comment by harshil21** [comment]
so apparently `isinstance("Hi", Sequence)` returns `True`. So I don't think we can use this, unless..?

**Comment by Bibo-Joshi** [comment]
Good point, we must exclude strings from that. But IISC bot method parameters only accept strings, numbers or arrays, so `if not isinstance(obj, str) and isinstance(obj, Sequence)` should do the trick, I guess. In terms of type annotations, `Sequence[SomethingOtherThanStr]` already excludes `str` …

**Comment by Bibo-Joshi** [comment]
Oh, `bytes` is also a Sequence …

**Comment by Bibo-Joshi** [comment]
Return values of bot methods should probably also be canged from `List` to `tuple`, since they represent the current state that TG reports. We can refacter `TO.de_list` to `TO.de_tuple`. Maybe it's worth doing this within #3249 …
