### ISSUE TITLE
[FEATURE] Typings: switch to explicit optional types

### ISSUE THREAD

**Issue by Viicos** [python-telegram-bot/python-telegram-bot#3367]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Since [mypy 0.990](https://mypy-lang.blogspot.com/2022/11/mypy-0990-released.html), implicit optional types are disabled by default. Maybe it is a good time to switch to explicit optional types, if so I can work on this.

Future reference: https://github.com/hauntsaninja/no_implicit_optional

### Describe the solution you'd like

Switch to explicit optional types (e.g. `def foo(s: str | None = None)`)

**Comment by Bibo-Joshi** [comment]
Thanks for reaching out. Are there any advantages of switching to explicit optional types other than complying with PEP 484?

**Comment by harshil21** [comment]
> Thanks for reaching out. Are there any advantages of switching to explicit optional types other than complying with PEP 484?

It would work slightly better with pylance/pyright for one...

**Comment by Bibo-Joshi** [comment]
I checked with harshil again and it seems that changing this in our library does not make a difference when __using__ PTB with pylance. I doubt that there will be any changes for users using other type checkers.
While the "explicit is better than implicit" argument is ofc somewhat right, I don't see a compelling benefit of this change. We can just re-enable the implicit optional mode once needed.

I vote -1 on this.

**Comment by Viicos** [comment]
Alright that's understandable, you might want to update the pre-commit config to use `no_implicit_optional = False`, as iirc the default value have changed (not an issue for now as mypy is still on 0.982).

**Comment by Bibo-Joshi** [comment]
our pre-commit-ci integration will inform us about that once the dependency is updated :)

I'll close this issue. Still, thanks again for taking the time and making the suggestion, @Viicos !
