### ISSUE TITLE
Add `caption`, `caption_entities` as parameters to `Bot._send_message`

### ISSUE THREAD

**Issue by harshil21** [python-telegram-bot/python-telegram-bot#3372]
This should do 2 things: 
- Add `caption_entities` to `_send_message`, so we can reduce repetition even further.
- Comment in `_send_message` that we do this to reduce repetition (DRY).

Ref https://github.com/python-telegram-bot/python-telegram-bot/pull/3346#discussion_r1026897846

**Comment by lemontree210** [comment]
I have 2 questions if you don't mind:

1. Did you really mean `caption_entities`, not `entities`? If so, why not also `caption`?
2. What avoidance of repetition are we talking about? The if-clauses? (`if data["caption_entities"]`)?

**Comment by harshil21** [comment]
> 1. If you mean `caption_entities`, not `entities`, then why not also `caption`? It gets repeated just as often as `caption_entities`.

yeah looks like that could be added as well.

> 2. What avoidance of repetition are we talking about? The if-clauses? (`if data["caption_entities"]`)?

Yep

**Comment by harshil21** [comment]
Noticed another inconsistency: 

We always pass `parse_mode` in `data` in the bot method, but we don't do this for the other `DefaultValue` params. See e.g.
https://github.com/python-telegram-bot/python-telegram-bot/blob/3042f187ed5d3cf456d9ab9bcce61a781c4b6a47/telegram/_bot.py#L937-L940
and
https://github.com/python-telegram-bot/python-telegram-bot/blob/3042f187ed5d3cf456d9ab9bcce61a781c4b6a47/telegram/_bot.py#L457-L459

I think this inconsistency should be corrected as well. i.e. add `parse_mode` to `_send_message`.
