### ISSUE TITLE
[QUESTION] How to filter echo when inside an ConversationHandler

### ISSUE THREAD

**Issue by Yusseiin** [python-telegram-bot/python-telegram-bot#3374]
### Issue I am facing

Hi all (sorry for bad eng),
i would like to add a simple echo function to my bot like the one in the example
but this is getting trigger with any message coming, i would like to filter the message coming from ConversationHandler so they won't trigger the echo function.
Is it possible? 
I have watched the "filters" but i am not able to find one that suits me.
Has anyone already done this?
Thanks for the answer.

### Related part of your code

async def echo(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.message.from_user
    logger.info("User: %s is writing: %s", user.first_name, update.message.text)
    await context.bot.send_message(chat_id=update.effective_chat.id, text=update.message.text)
echo_handler = MessageHandler(filters.TEXT & (~filters.COMMAND), echo)
application.add_handler(echo_handler)
### Operating System

Windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0.alpha.4
python 3.10.8
```

**Comment by Poolitzer** [comment]
Hey, I think all you need to do is call add_handler of the conversation handler before the echo_handler.

**Comment by Yusseiin** [comment]
> Hey, I think all you need to do is call add_handler of the conversation handler before the echo_handler.

That is not working.
I am calling the handler like this
```
application.add_handler(start_handler) "Command /start won't trigger echo
application.add_handler(singup_handler, 1) "ConversationHandler this will trigger the echo
application.add_handler(echo_handler, 2)
```
Where, as i understand correctly, higher the number less the priority but echo is still gettin trigger

**Comment by Poolitzer** [comment]
No the number puts them in different groups, every group gets the update

/start should still trigger echo in this setup, probably the echo handler has some filtering preventing it.

**Comment by Yusseiin** [comment]
> No the number puts them in different groups, every group gets the update
> 
> /start should still trigger echo in this setup, probably the echo handler has some filtering preventing it.

Yes echo has a filter for command, but no filter for message in conversation handler and that is my problem.

Putting them all in the same group will not trigger the echo if there are other handler declared before him?

`application.add_handler(start_handler,1) "Command /start won't trigger echo
application.add_handler(singup_handler, 1) "ConversationHandler this will trigger the echo
application.add_handler(echo_handler, 1)`

like in this setup echo will be still trigger? or it will be trigger like
start first then Conversation Handler and echo at the end?

**Comment by Poolitzer** [comment]
> Putting them all in the same group will not trigger the echo if there are other handler declared before him?

This is correct. In one group, an update is only handled by the first (in terms of first being added) handler. So in your showcase, `signup_handler` will trigger, but not `echo_handler`, for the troublesome updates.

**Comment by Yusseiin** [comment]
> > Putting them all in the same group will not trigger the echo if there are other handler declared before him?
> 
> This is correct. In one group, an update is only handled by the first (in terms of first being added) handler. So in your showcase, `signup_handler` will trigger, but not `echo_handler`, for the troublesome updates.

Thanks tomorrow i will try to update my code and see if it is working.
Have a nice day :)
