### ISSUE TITLE
Python 3.10+ support

### ISSUE THREAD

**Issue by frankhuurman** [python-telegram-bot/python-telegram-bot#3378]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

I'm on PopOS! 22.04 which has support for Python3.10 and 3.11. Already tried it but running PTB in a 3.10 venv didn't work :(

Even though Python 3.9 is in the apt repository, the python3.9-venv package is missing so I still can't use PTB properly.

Is there support planned for newer Python versions? (Especially 3.11 which should see some speed improvements)

Thanks!

### Describe the solution you'd like

To be able to make a venv in python 3.10 or python 3.11 and install + use a fully functional PTB.

### Describe alternatives you've considered

I wanted to use python 3.9 since that's supported by PTB but I can´t make a 3.9 venv due to a missing package.
An other alternative is to use python 3.9 + PTB inside a container but that makes the development process a bit more cumbersome each time I want to try something.

**Comment by Poolitzer** [comment]
Hi, can you define not working.

**Comment by frankhuurman** [comment]
```
from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes
ImportError: cannot import name 'ApplicationBuilder' from 'telegram.ext' (/home/myuser/Documents/telegrambot/venv/lib/python3.10/site-packages/telegram/ext/__init__.py)
```

On second thought, I might have assumed it's a Py 3.10 issue out of the box.

I just tried running the example on the main website:
https://python-telegram-bot.org/

If it's a Py 3.10 issue I'll use the deadsnakes PPA to get around it, thanks!

**Comment by Poolitzer** [comment]
It is not a python issue, the import error stems from you not installing the pre version but using code for it.

Since you start out with a new project apparently, I'd suggest you use it. Run `pip install -U --pre python-telegram-bot` in the venv

**Comment by frankhuurman** [comment]
Thanks a lot for the quick responses!
Really appreciated.

I noticed it installed `python-telegram-bot==13.14` before, now I've got 20.0a5.

At least it's not throwing exceptions anymore but bot doesn't seem to be responding even with the correct API key. Running the script just seems to block the terminal output but nothing ever happens when I chat hello to the bot(also remade the venv and everything, doesn't seem to be working so far).

But that's something else for me to figure out!

Thanks a lot for the help :smile:

**Comment by Poolitzer** [comment]
> Running the script just seems to block the terminal output

That is expected

> when I chat hello to the bot

CommandHandler means the callback is called when you chat "/hello", not only "hello"

> But that's something else for me to figure out!

If you want direct help from the community without making issues, feel free to [join our telegram group](https://t.me/pythontelegrambotgroup).

> Thanks a lot for the help smile

Alright, will close.
