### ISSUE TITLE
Documentation doesn't build.

### ISSUE THREAD

**Issue by Faalentijn** [python-telegram-bot/python-telegram-bot#338]
### Steps to reproduce
1. Go to Docs/
2. make info
### Expected behaviour

The outputted file contains the documentation for python-telegram-bot in info format.
### Actual behaviour

The outputted file is empty. The exception for this is when you are building the html files.
### Configuration

**Operating System:**
GNU/Linux

**Version of Python:**
Python 3.4.4

**Version of python-telegram-bot:**
Fresh clone.

**Version of Sphinx**
1.3.5

The fix seems to be to either add modules.srt or telegram.srt to the index.srt file. 

I've also noticed that there is some inconsistent naming in the documentation. For example you've telegram.ext.handler.rst and telegram.inlinequeryresultcachedmpeg4gif.rst. I'm not sure whether this is a bug or intended behaviour.

**Comment by jh0ker** [comment]
Hi! Thank you for your contribution :) 

> I've also noticed that there is some inconsistent naming in the documentation. For example you've telegram.ext.handler.rst and telegram.inlinequeryresultcachedmpeg4gif.rst. I'm not sure whether this is a bug or intended behaviour.

If you're referring to the `.ext.` part, that is because the handler file is located in the `telegram.ext` submodule. If that is the wrong way to document submodules (or there is a more common way to do it), please let me know. This is my doing ^^

**Comment by Faalentijn** [comment]
> If you're referring to the .ext. part, that is because the handler file is located in the telegram.ext submodule. If that is the wrong way to document submodules (or there is a more common way to do it), please let me know. This is my doing ^^

I'm not sure what the common way of doing it is (I can't seem to find a standard and I'm quite green) but they way it is done right now seems kind of silly.

The documentation in its current state is more of a reference but the way it is laid out makes it kind of difficult. Mainly the lack of grouping like you're doing with `.ext` (the .ext defines a subdomain). Without grouping you can easily get a difficult to find things.

So for instance rather than having the following layout:
`telegram.audio module
telegram.base module
<snip>
telegram.ext package (a group of modules)
<snip>
telegram.inlinequeryresult module
telegram.inlinequeryresultarticle module
telegram.inlinequeryresultaudio module
telegram.inlinequeryresultcachedaudio module
telegram.inlinequeryresultcacheddocument module
`
Why don't you do something like this:
`
Audio / telegram.audio module
Base / telegram.base.module
<snip>
Ext. module / telegram.ext package
<snip>
Inline query package (with the inline query modules inside)
`

This would make it a lot easier to find the documentation you want/need.

**Comment by Faalentijn** [comment]
It seems that the way the documentation is generated in sphinx-autodoc causes this slightly odd layout. It generates a .srt file for each file and creates a new group for each directory (as we saw earlier with `.ext`. This means that the only way to change this using auto-generation is to change the layout of the code.

**Comment by tsnoam** [comment]
@Faalentijn 
regarding the one problem left - failure to build documentation, can you please attach the output of `make info` as a text file?

**Comment by Faalentijn** [comment]
[output_make_info.txt](https://github.com/python-telegram-bot/python-telegram-bot/files/354895/output_make_info.txt) and here is the outcome converted to a pdf: 
[PythonTelegramBot.pdf](https://github.com/python-telegram-bot/python-telegram-bot/files/354905/PythonTelegramBot.pdf)

**Comment by tsnoam** [comment]
I see now.
Please see my comments on PR #337

**Comment by leandrotoledo** [comment]
That's true, we are building docs using sphinx (normally using ```$ python setup.py build_sphinx```), sphinx-autodoc was our first option because otherwise it would demand some work customizing the .rst every time adding new classes or modules.

But I agree, this is good for reference only but kinda confusing, everything is grouped by modules, and mostly it is either root level or .ext. I'll try to get it somehow better, but if you want to contribute in that way ping me on Telegram and we can work together on this. Maybe also adding the good articles @jh0ker has written on Wiki to documentation too.

**Comment by Faalentijn** [comment]
- [ ] Use code blocks rather than literals to denote code in documentation.
- [ ] Add wiki pages to the documentation
- [ ] Group modules with similar functionality together to make searching it easier
- [ ] Include documentation for how to build and install it the documentation on your system (ex. man or info)
- [ ] Include important external files like AUTHORS and CONTRIBUTING.
- [ ] Give them more sensible titles. (ex.  Inlinequery_result ->  Cached -> Video module instead of telegram.inlinequeryresultcachedvideo)

**Comment by jh0ker** [comment]
Addressing two issues here, the rest seem very good to me:

> Use code blocks rather than literals to denote code in documentation.
We had discussed this before, deciding between single- and double-backticks (if that's what you mean by that), and decided for double-backticks.

> Give them more sensible titles. (ex. Inlinequery_result -> Cached -> Video module instead of telegram.inlinequeryresultcachedvideo)
These titles are mirroring the names of the code files, so changing would mean a code change, no?

**Comment by Faalentijn** [comment]
> We had discussed this before, deciding between single- and double-backticks (if that's what you mean by that), and decided for double-backticks.

I'm talking about [rest code blocks](http://www.sphinx-doc.org/en/stable/markup/code.html#directive-code-block). See the screenshots for difference between the two methods.
![pretty](https://cloud.githubusercontent.com/assets/8453949/16714224/adbe0c56-46bc-11e6-81f2-43bbba53356a.png) 
![big.](https://cloud.githubusercontent.com/assets/8453949/16714234/dc9ecb64-46bc-11e6-86f6-b233733f67db.png)

> These titles are mirroring the names of the code files, so changing would mean a code change, no?

Yes and no. The titles of the files do not dictate from which place in the code is should generate documentation from.

````
Inlinequery Result package  <-- name/title
=================================

Submodules <-- subtitle
----------------
.. toctree:: <-- Links to other files
   article
   audio
   cached/main
   contact
   document
   gif
   location
   mpeg4gif
   photo
   venue
   video
   voice

Module contents
----------------
.. automodule:: telegram.inlinequeryresult <- from which file it should generate the docs from.
    :members:
    :undoc-members:
    :show-inheritance:
```
In fact the only thing in the file you can't touch is the ```automodule``` line.

**Comment by leandrotoledo** [comment]
I'd add to the task list:

- [ ] suppress/fix warning messages (most of them should be easy to fix)

```
/home/leandrotoledo/workspace/python-telegram-bot/telegram/ext/__init__.py:docstring of telegram.ext.Dispatcher.add_handler:None: WARNING: more than one target found for cross-reference u'Handler': telegram.ext.Handler, telegram.ext.handler.Handler
/home/leandrotoledo/workspace/python-telegram-bot/telegram/ext/__init__.py:docstring of telegram.ext.Dispatcher.remove_handler:None: WARNING: more than one target found for cross-reference u'Handler': telegram.ext.Handler, telegram.ext.handler.Handler
/home/leandrotoledo/workspace/python-telegram-bot/telegram/ext/__init__.py:docstring of telegram.ext.JobQueue:None: WARNING: more than one target found for cross-reference u'Bot': telegram.Bot, telegram.bot.Bot
/home/leandrotoledo/workspace/python-telegram-bot/telegram/ext/__init__.py:docstring of telegram.ext.JobQueue.put:None: WARNING: more than one target found for cross-reference u'Job': telegram.ext.jobqueue.Job, telegram.ext.Job
/home/leandrotoledo/workspace/python-telegram-bot/telegram/ext/__init__.py:docstring of telegram.ext.Handler.collect_optional_args:None: WARNING: more than one target found for cross-reference u'Dispatcher': telegram.ext.Dispatcher, telegram.ext.dispatcher.Dispatcher
/home/leandrotoledo/workspace/python-telegram-bot/telegram/ext/__init__.py:docstring of telegram.ext.TypeHandler:None: WARNING: more than one target found for cross-reference u'type': telegram.chat.Chat.type, telegram.Chat.type, telegram.user.User.type, telegram.User.type, telegram.InlineQueryResult.type, telegram.inlinequeryresult.InlineQueryResult.type
/home/leandrotoledo/workspace/python-telegram-bot/telegram/ext/handler.py:docstring of telegram.ext.handler.Handler.collect_optional_args:None: WARNING: more than one target found for cross-reference u'Dispatcher': telegram.ext.Dispatcher, telegram.ext.dispatcher.Dispatcher
/home/leandrotoledo/workspace/python-telegram-bot/telegram/ext/dispatcher.py:docstring of telegram.ext.dispatcher.Dispatcher.add_handler:None: WARNING: more than one target found for cross-reference u'Handler': telegram.ext.Handler, telegram.ext.handler.Handler
/home/leandrotoledo/workspace/python-telegram-bot/telegram/ext/dispatcher.py:docstring of telegram.ext.dispatcher.Dispatcher.remove_handler:None: WARNING: more than one target found for cross-reference u'Handler': telegram.ext.Handler, telegram.ext.handler.Handler
/home/leandrotoledo/workspace/python-telegram-bot/telegram/ext/handler.py:docstring of telegram.ext.handler.Handler.collect_optional_args:None: WARNING: more than one target found for cross-reference u'Dispatcher': telegram.ext.Dispatcher, telegram.ext.dispatcher.Dispatcher
/home/leandrotoledo/workspace/python-telegram-bot/telegram/ext/jobqueue.py:docstring of telegram.ext.jobqueue.JobQueue:None: WARNING: more than one target found for cross-reference u'Bot': telegram.Bot, telegram.bot.Bot
/home/leandrotoledo/workspace/python-telegram-bot/telegram/ext/jobqueue.py:docstring of telegram.ext.jobqueue.JobQueue.put:None: WARNING: more than one target found for cross-reference u'Job': telegram.ext.jobqueue.Job, telegram.ext.Job
/home/leandrotoledo/workspace/python-telegram-bot/telegram/ext/typehandler.py:docstring of telegram.ext.typehandler.TypeHandler:None: WARNING: more than one target found for cross-reference u'type': telegram.chat.Chat.type, telegram.Chat.type, telegram.user.User.type, telegram.User.type, telegram.InlineQueryResult.type, telegram.inlinequeryresult.InlineQueryResult.type
```

**Comment by celisflen-bers** [comment]
I do not download photo with [snippet](https://core.telegram.org/bots/api#getfile) please check example

```
    file_info = message.photo[-1]
    photo = bot.get_file(file_info.file_id)
    photo.download()
```

Error:
```
photo.download()
AttributeError: File instance has no attribute 'download'
```

**Comment by rahiel** [comment]
With the recent effort by @Eldinnie, this bug is fixed. `make info` now properly builds the documentation in info format. However there are still some good suggestions in this comment: https://github.com/python-telegram-bot/python-telegram-bot/issues/338#issuecomment-231561665.
