### ISSUE TITLE
[QUESTION] Poll parameters

### ISSUE THREAD

**Issue by NeoDashboard** [python-telegram-bot/python-telegram-bot#3387]
### Issue I am facing

I'm seeing on Telegram API documentation *public_voters* is available to choose to show or not users answers but can't find this on Python wrapper. Am I missing something?
Doc link: https://core.telegram.org/api/poll

### Operating System

Ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot==20.0a6
```

**Comment by Bibo-Joshi** [comment]
@NeoDashboard Wiki of <i>python-telegram-bot</i> - Category <i>FAQ</i>
<a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#can-you-add-feature-to-ptb-can-i-do-thing-with-my-bot">Can you add [feature] to PTB? Can I do [thing] with my bot?</a>
