### ISSUE TITLE
sending audio file missing punctuations like "【】"[QUESTION]

### ISSUE THREAD

**Issue by RibosomeK** [python-telegram-bot/python-telegram-bot#3405]
### Issue I am facing

I have a audio file name: ```【言和原创】TH讠NK【踏云社】.m4a```, and using ```send_audio()``` to send it out. When I received the audio, the titile changed to ``` 言和原创 TH讠NK 踏云社 ```. It seems that all the bold brackets (U+3030 and U+3031) are replaced by space, although I don't see any error messages in the log.

I pass a file object with ```open(file_name, mode="rb")``` to the parameter ```audio```, and I also used parameter ```filename``` to customize the name and yet it does't work for me.

The updater and handler seems does not affect the result when I simply create a bot with ```bot = telegram.Bot(token)``` and send audio. But in that case the updater and handler I'm using is ```telegram.Updater``` and ```telegram.ext.MessageHandler```. In my code is like ```echo_handler = MessageHandler(Filters.text & (~Filters.command), echo)```

I haven't try other send functions like ```send_documents()``` to see wheather it's universal or not.

### Related part of your code

```python
def echo(update: Update, context: CallbackContext):
    if update.effective_chat is not None:
        text = update.message.text
        id, platform = detect_url(text)
        if id and platform:
            context.bot.send_message(
                chat_id=update.effective_chat.id, text=f"It contains a link from {platform.value}."
            )
            context.bot.send_message(
                chat_id=update.effective_chat.id, text="Let me try to download the audio for you."
            )
            try:
                file_name = download_audio(id, platform)
            except Exception as e:
                file_name = ""
                print(e)
            if os.path.exists(file_name):
                with open(file_name, mode="rb") as audio:
                    context.bot.send_audio(
                        chat_id=update.effective_chat.id, audio=audio, filename=file_name
                    )
                    print(f"{file_name=}")
                    context.bot.send_message(
                        chat_id=update.effective_chat.id, text="Download complete!"
                    )
                os.remove(file_name)
            else:
                print(f"file_name: {file_name}")
                context.bot.send_message(
                    chat_id=update.effective_chat.id, text="I'm sorry the download failed <(_ _)>"
                )

        else:
            text = update.message.text
            user_name = update.message.chat.full_name
            print(f"{user_name}: {text}")
            context.bot.send_message(
                chat_id=update.effective_chat.id, text=f"What is this? I'm gonna repeat it：{text}"
            )
```

### Operating System

Ubuntu 20.04.5 LTS on Windows 10 x86_64

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.14
Bot API 6.2
certifi2022.09.24
Python 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0]
```

**Comment by Bibo-Joshi** [comment]
Hi. 

I can reproduce the behavior. But I can also reproduce by directly using the `httpx` library (that `python-telegarm-bot` uses for the networking stuff) and also using the `requests` library - a different library for making http requests, not used by `python-telegram-bot`. MWE (written with ptb v20.0a6 and using `send_document` instead):

```python
import asyncio

import httpx
import requests

from telegram import Bot

TOKEN = "token"
CHAT_ID = 123456


async def main():
    async with Bot(TOKEN) as bot:
        await bot.send_document(CHAT_ID, "【言和原创】TH讠NK【踏云社】.jpg")

    httpx.post(
        f"https://api.telegram.org/bot{TOKEN}/sendDocument",
        data={"chat_id": CHAT_ID},
        files={"document": open("【言和原创】TH讠NK【踏云社】.jpg", "rb")},
    )

    requests.post(
        f"https://api.telegram.org/bot{TOKEN}/sendDocument",
        data={"chat_id": CHAT_ID},
        files={"document": open("【言和原创】TH讠NK【踏云社】.jpg", "rb")},
    )


if __name__ == "__main__":
    asyncio.run(main())
```

Hence this does not seem to be an issue of `python-telegram-bot`. It might be an issue that python-specific and that affects both `httpx` and `requests`, but I rather guess that Telegram is the one renaming the file. To double check this, one could try to make a manual request with curl/wget/postman or similar …

**Comment by RibosomeK** [comment]
> 

Thank you for your answer. Sorry to bother you again, before I use PTB I used little Internet related moduels or command, Can you be more specific on how to request manually? I'm sorry if it bother you again.

**Comment by Poolitzer** [comment]
I did a curl, same result. I would say it is telegram changing that, if both python libraries and curl did this.

```bash
curl \
     -F chat_id=208589966\
     -F audio=@"【言和原创】TH讠NK【踏云社】.m4a"\
     https://api.telegram.org/botTOKEN/sendAudio 

```

**Comment by Bibo-Joshi** [comment]
Thanks for checking, Pool. I'll close the issue, then.
