### ISSUE TITLE
[QUESTION] 'File' object has no attribute 'download_to_drive'

### ISSUE THREAD

**Issue by RomanoZumbe** [python-telegram-bot/python-telegram-bot#3408]
### Issue I am facing

I try to download a file that is send to the bot. But when the file is received I get the error message that 'File' object has no attribute 'download_to_drive'. Up until the get_file() mthod everything works fine, I just can't download the file

### Traceback to the issue

```python
Update {'update_id': ######, 'message': {'supergroup_chat_created': False, 'forward_from': {'username': '######', 'is_bot': False, 'last_name': '#####', 'id': ######, 'language_code': 'de', 'first_name': '######'}, 'caption_entities': [], 'entities': [], 'delete_chat_photo': False, 'new_chat_photo': [], 'message_id': 693, 'photo': [], 'new_chat_members': [], 'channel_chat_created': False, 'forward_date': 1670272370, 'chat': {'username': '#####', 'last_name': '#####', 'type': 'private', 'first_name': '#####', 'id': #######}, 'document': {'mime_type': 'application/x-ms-dos-executable', 'file_unique_id': 'AgADbScAAgZTcEg', 'file_size': 2130864, 'file_id': 'BQACAgIAAxkBAAICtWOOYB53eoJQCj22uYoYQXa2y9WqAAJtJwACBlNwSJdhOHBGdvSsKwQ', 'file_name': 'vs_BuildTools.exe'}, 'group_chat_created': False, 'date': 1670275102, 'from': {'username': '######', 'is_bot': False, 'last_name': '#####', 'id': ########, 'language_code': 'de', 'first_name': '#####'}}} caused error 'File' object has no attribute 'download_to_drive'
```

### Related part of your code

```python
import const as keys
from telegram.ext import *

print("Bot started...")

def handle_documents(update, context):
    msg = update.message
    print(f"Download of {msg.document.file_name} started")
    msg.document.get_file().download_to_drive()
    
def error(update, context):
    print(f"Update {update} caused error {context.error}")

def main():
    updater = Updater(keys.API_KEY, use_context=True)
    dp = updater.dispatcher
    dp.add_handler(MessageHandler(Filters.document, handle_documents))
    dp.add_error_handler(error)
    updater.start_polling()
    updater.idle()

main()
```

### Operating System

Debian 11

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.14
Bot API 6.2
certifi2020.06.20
Python 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
```

**Comment by harshil21** [comment]
@RomanoZumbe hey there, you&#x27;re using the old version of the library which does not support `download_to_drive`. The equivalent method for that is <a href="https://python-telegram-bot.readthedocs.io/en/stable/telegram.file.html#telegram.File.download">telegram.File.download</a> <a href="https://core.telegram.org/bots/api#file">ᵀᴱᴸᴱᴳᴿᴬᴹ</a>

**Comment by RomanoZumbe** [comment]
Ah, that was it! I thought 13.14 was the newest version. Thats what pip installs, I even tried updating it. But now that the error is solved I get a time out error for larger files (I'm running a local api server). Anyway, big thanks for your help!

**Comment by harshil21** [comment]
@RomanoZumbe no problem! To upgrade to the latest version, run `pip install python-telegram-bot --pre -U`. But before upgrading, make sure to read the Transition guide: <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-20.0">Version 20</a>
