### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by VarunBanka** [python-telegram-bot/python-telegram-bot#3418]
### Issue I am facing

Storing user input in a variable and replying the data of a variable 

### Operating System

Windows (also tried on arch )

### Version of Python, python-telegram-bot & dependencies

```shell
3.10
```

**Comment by Bibo-Joshi** [comment]
@VarunBanka Hey. In order for someone to be able to help you, you must ask a <b>good technical question</b>. Please read <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Ask-Right">this short article</a> and try again ;)

**Comment by VarunBanka** [comment]
> @VarunBanka Hey. In order for someone to be able to help you, you must ask a good technical question. Please read [this short article](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Ask-Right) and try again ;)

Alright, thanks
