### ISSUE TITLE
[DOCS] add references to Code Resources Wiki section?

### ISSUE THREAD

**Issue by lemontree210** [python-telegram-bot/python-telegram-bot#3421]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

in #3398 I added `seealso` references to Wiki pages to close #3110. I think I could add more references - from docs to section with code resources. 

For example, from `ReplyKeyboardMarkup` to "Keyboard Menus" section of [Code Snippets](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets).

### Describe the solution you'd like

If you are in favor of this, what do you think should be the link text? In other Wiki references the link text is the name of Wiki page, but here we might want to choose something different. The target of the link should in any case be not the page but a heading within it.

- "Code Snippets"
- "Code Snippets in Wiki"
- "Code Snippets: Keyboard Menus"
- "Keyboard Menus"

### Additional context

I think that as a beginning bot developer, I would like to have links to these snippets from docs.

**Comment by Bibo-Joshi** [comment]
@lemontree210 Tbh I&#x27;m not very convinced by this. The code snipped page is far from being well organized (meaning that links can easily become outdated) and most of the things on the page are in my impression either direct translations of the docs into code or so specific that don&#x27;t fit into the docs.

The only thing in there that could IMO be worth linking to from the docs is the &quot;working with files an media&quot; section and for that I&#x27;d rather convert that section to a standalone wiki page.

**Comment by lemontree210** [comment]
Sounds good. Yes, I thought too that the code snippets may not be that organized. 
Do you see this standalone wiki page in "Code resources" or in "Notable features"?

**Comment by Bibo-Joshi** [comment]
@lemontree210 I&#x27;d say &quot;concepts &amp; import elements&quot;. The section should also be updated to reflect that you can now always pass file paths as arguments
