### ISSUE TITLE
No connect behind a proxy with authentication

### ISSUE THREAD

**Issue by kalety** [python-telegram-bot/python-telegram-bot#343]
### Steps to reproduce
1.Connection errors 

2. the user and pass is given in that format:

https_proxy=user:pass@proxydir:port

http_proxy=user:pass@proxydir:port
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
Debian "stretch"

**Version of Python:**

``$ python -V``ver 3.5

**Version of python-telegram-bot:**
4.3.3
``$ python -c 'import telegram; print(telegram.__version__)'``

### Logs
Insert logs here (if necessary)

**Comment by kalety** [comment]
Something like this?

```
Example using proxy authentication:
>>> headers = urllib3.make_headers(proxy_basic_auth=’myusername:mypassword’)
>>> proxy = urllib3.ProxyManager(’http://localhost:3128’, proxy_headers=headers)
>>> r = proxy.request(’GET’, ’http://example.com/’)
>>> r.status
```

**Comment by tsnoam** [comment]
@kalety thank you for the information.
if you'd like you can assist us with fixing the issue.
you can take a look at the file telegram/utils/request.py there you can see the code which retrieves the https_proxy env. var. 
according to your example it appears that an extra parsing to the user name and password is required and obviously some extra handing to pass it as headers.

**Comment by kalety** [comment]
I'm trying it...

;))

**Comment by tsnoam** [comment]
the problem still exist... repoening

**Comment by tsnoam** [comment]
there's `urllib3.proxy_from_url()` so no parsing is required.
i'm testing a solution at the moment

**Comment by kalety** [comment]
Ok!, tomorrow I'll try again. Thanks!. 

Enviado desde mi iPhone

**Comment by kalety** [comment]
Hi!, I´ve tested two ways:

1.- ` urllib3.proxy_from_url(url, proxy_headers=headers)`

2.- ` urllib3.ProxyManager(url, proxy_headers=headers).`

The behavior is identical (I think is the same thing...), and both work perfectly.

The headers must parsed in this form:

`headers=urllib3.make_headers(proxy_basic_auth='user:passwd')`

Using **from_env (request.py)** we get all the parameters.

We could get the data for `proxy_basic_auth`:

`auth=(from_env.split('//'))[1].split('@')[0]`

and url:

`url=(from_env.split('//'))[0]+'//'+(from_env.split('//'))[1].split('@')[1]`

Now I will try to work inside **request.py**... but this is more difficult to me, since is not my program and I have to "decodify" it.

Thanks in advance, and I hope this is worth for something.

Bye! ;))

**Comment by kalety** [comment]
Ooops.....

**Comment by kalety** [comment]
Sorry, I don´t read your proposed solution.... :((, but.... it works flawesly!!!!. Your python-telegram-bot acquires a "proffessional flavour". I can´t help you with other proxies types since I couldn´t test it.

If I help you in any way say me.

Thanks a lot!
