### ISSUE TITLE
[BUG] typo in wiki

### ISSUE THREAD

**Issue by Vlad-Vargan** [python-telegram-bot/python-telegram-bot#3437]
### Steps to Reproduce

ON wiki page
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-flood-limits
Mentioned usage of rate_limit_args as `rate_limit_args={'priority': -1}` which leads to an error
`unsupported operand type(s) for +: 'dict' and 'int'`

Because by docs that's an optional int, not a dict
https://docs.python-telegram-bot.org/en/latest/telegram.ext.aioratelimiter.html#telegram.ext.AIORateLimiter

### Expected behaviour

Usage of priority in rate limiting without error, and correct documentation

### Actual behaviour

 error
`unsupported operand type(s) for +: 'dict' and 'int'`

### Operating System

MacOS Ventura 13.0.1

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.8.12, python-telegram-bot["ext"]^20.0b0
```

**Comment by Bibo-Joshi** [comment]
@Vlad-Vargan Hi. Note that <code>rate_limit_args={&#x27;priority&#x27;: -1}</code> is not used in combination with <code>AIORateLimiter</code> but only with <code>MyLimiter </code>which is a hypothetical custom implementation of <code>BaseRateLimiter.</code> The point is to showcase that depending on the implementation the parameter <code>rate_limit_args</code> can accept arbitrary objects.

**Comment by Vlad-Vargan** [comment]
Ok, i got it, thanks
