### ISSUE TITLE
[QUESTION] How can I manage conversation state from async callback?

### ISSUE THREAD

**Issue by Ledorub** [python-telegram-bot/python-telegram-bot#3440]
Hi!
I am currently developing the bot that relies on a `ConversationHandler` to implement a dialogue with a user. Upon user's request the bot have to retrieve some data from one or more microservices and present it to user. To obtain the data from microservices it uses message broker (Kafka). The bot processes received update and sends a message to Kafka topic, then consumer awaits for reply to invoke the callback that will send response data to user and set next conversation state.

My current solution is to generate a unique message ID, and use it as a key to an update object. When reply with the same ID arrives, update object is fetched from storage and recreated with `Update.de_json()`, context is recreated with `CallbackContext.from_update()` and both are passed to callback, along with received response message. After processing the response, I have to somehow change the state. So I have another hack up my sleeve to achieve it:

```python
key = conv_handler._get_key(update)
conv_handler._update_state(state, key)
```

Resulting solution is too hacky and doesn't look reliable in the long run.
This [SO answer](https://stackoverflow.com/a/55759244/6928691) also advices against changing state directly.

Could someone recommend a better approach?

### Operating System

Windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0a6
Bot API 6.3
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
The `_get_key` and `_update_state` methods are marked as protected for a reason. They are not intended to be manually called by you as user.

I see no reason why replying to the user and changing the conversations state would have to be done outside the handler callback. With asyncios cooperative concurrency handling and PTBs ways of supporting that in handling updates (see the "Concurrency in PTB" page in the wiki), you could just `await` the information from the Microservice.

**Comment by Ledorub** [comment]
I read through the wiki page you mentioned, but I think it doesn't help to solve my problem.
> you could just await the information from the Microservice

It's not possible to await the response. It is pushed to the topic, that is read by a consumer. Consumer then invokes a callback according to the message type. The order of responses is not guaranteed. As for now, it's implemented like this:
```python
while True:
    # Can't await this from ConversationHandler, because msg can be a resp. to another req.
    msg = await self._consumer.getone()
    await self.run_handlers(msg)
    await asyncio.sleep(0)
```

**Comment by Ledorub** [comment]
After some exploration, I came up with idea to create a future when messege is sent to topic. The future is stored somewhere from where it can be retrieved by message / correlation ID. ConversationHandler's callback awaits for the future with `await asyncio.wait_for(f, timeout)`. Kafka consumer, when response arrives, gets the same future by ID and calls `set_result(res)` on it, if it isn't cancelled by timeout.
How to make this persistent is still a question.
