### ISSUE TITLE
Drop Python 2.7 

### ISSUE THREAD

**Issue by dontsovcmc** [python-telegram-bot/python-telegram-bot#345]
Can't install package in Mac OS X. 
Python 2.7.5.

```
Install packages failed: Error occurred when installing package python-telegram-bot. 

The following command was executed:

packaging_tool.py install --build-dir /private/var/folders/6d/w28yfrld7b7c_v7ss8cngjb40000gn/T/pycharm-packaging5213068996327577591.tmp --user python-telegram-bot

The error output of the command:


Downloading/unpacking python-telegram-bot
  Running setup.py egg_info for package python-telegram-bot
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/private/var/folders/6d/w28yfrld7b7c_v7ss8cngjb40000gn/T/pycharm-packaging5213068996327577591.tmp/python-telegram-bot/setup.py", line 5, in <module>
        import telegram
      File "telegram/__init__.py", line 44, in <module>
        from .inputfile import InputFile
      File "telegram/inputfile.py", line 34, in <module>
        from future.moves.urllib.request import urlopen
    ImportError: No module named future.moves.urllib.request
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/private/var/folders/6d/w28yfrld7b7c_v7ss8cngjb40000gn/T/pycharm-packaging5213068996327577591.tmp/python-telegram-bot/setup.py", line 5, in <module>

    import telegram

  File "telegram/__init__.py", line 44, in <module>

    from .inputfile import InputFile

  File "telegram/inputfile.py", line 34, in <module>

    from future.moves.urllib.request import urlopen

ImportError: No module named future.moves.urllib.request

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /private/var/folders/6d/w28yfrld7b7c_v7ss8cngjb40000gn/T/pycharm-packaging5213068996327577591.tmp/python-telegram-bot
Storing complete log in /Users/dontsov/Library/Logs/pip.log
```

**Comment by leandrotoledo** [comment]
@dontsovcmc could you paste the output of ``pip freeze`` (from the same directory you are trying to install the library)?

Thanks.

**Comment by dontsovcmc** [comment]
CherryPy==3.8.0
Django==1.7.3
Jinja2==2.7.3
MarkupSafe==0.23
MinimalModbus==0.6
PyExifTool==0.1
alglib==0.0.0
argparse==1.2.1
beautifulsoup4==4.4.1
cffi==0.8.6
configobj==5.0.5
cryptography==0.7.1
decorator==4.0.9
dict==0.0.5
enum34==1.0.4
get==0.0.7
google-api-python-client==1.3.1
httplib2==0.9
ino==0.3.6
matplotlib==1.4.3
mock==1.0.1
ndg-httpsclient==0.4.1
nose==1.3.6
numpy==1.9.2
oauth2client==1.4.5
ordereddict==1.1
pbr==0.10.7
protobuf==2.5.0
public==0.0.0
py==1.4.26
pyOpenSSL==0.14
pyasn1==0.1.7
pyasn1-modules==0.0.5
pycparser==2.10
pycrypto==2.6.1
pycurl==7.19.5
pyparsing==2.0.3
pyserial==2.7
pytest==2.6.4
python-dateutil==2.4.2
pytz==2015.2
query-string==0.0.5
requests==2.10.0
rsa==3.1.4
self==0.0.5
simplejson==3.6.5
six==1.7.2
stevedore==1.2.0
tox==1.8.1
uritemplate==0.6
virtualenv==12.0.5
virtualenv-clone==0.2.5
virtualenvwrapper==4.3.2
wsgiref==0.1.2

**Comment by tsnoam** [comment]
Hi @dontsovcmc ,
It looks like you're trying to install from sources.
Please make sure that you've installed all required dependencies (and the respective versions) as specified in `requirements.txt`.

Installing from pip takes care of it usually.

**Comment by dontsovcmc** [comment]
I try to install it from PyCharm.
I got error messages:

1:04:06 Some skeletons failed to generate: 1 module failed in 1 interpreter. Details...
1:04:20 Install packages failed: Error occurred when installing packages. Details...
1:04:26 Some skeletons failed to generate: 1 module failed in 1 interpreter. Details...

1. 
Failed modules
Python 2.7.12 virtualenv at ~/Documents/CODE/GisMeteoBot/win32_env 
Nav
Generation of skeletons for the modules above will be tried again when the modules are updated or a new version of generator is available.

2.
Error occurred when installing packages.

The following command was executed:

packaging_tool.py install --build-dir /private/var/folders/6d/w28yfrld7b7c_v7ss8cngjb40000gn/T/pycharm-packaging3628242130164364209.tmp python-telegram-bot

The error output of the command:


Downloading/unpacking python-telegram-bot
  Running setup.py egg_info for package python-telegram-bot
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/private/var/folders/6d/w28yfrld7b7c_v7ss8cngjb40000gn/T/pycharm-packaging3628242130164364209.tmp/python-telegram-bot/setup.py", line 5, in <module>
        import telegram
      File "telegram/__init__.py", line 44, in <module>
        from .inputfile import InputFile
      File "telegram/inputfile.py", line 34, in <module>
        from future.moves.urllib.request import urlopen
    ImportError: No module named future.moves.urllib.request
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/private/var/folders/6d/w28yfrld7b7c_v7ss8cngjb40000gn/T/pycharm-packaging3628242130164364209.tmp/python-telegram-bot/setup.py", line 5, in <module>

    import telegram

  File "telegram/__init__.py", line 44, in <module>

    from .inputfile import InputFile

  File "telegram/inputfile.py", line 34, in <module>

    from future.moves.urllib.request import urlopen

ImportError: No module named future.moves.urllib.request

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /private/var/folders/6d/w28yfrld7b7c_v7ss8cngjb40000gn/T/pycharm-packaging3628242130164364209.tmp/python-telegram-bot
Storing complete log in /Users/dontsov/.pip/pip.log

3. same as 1.

**Comment by dontsovcmc** [comment]
I install  dependencies manually and python-telegram-bot installed successfully! Thanks!
(future, urllib3, certifi)
