### ISSUE TITLE
[BUG]callback not working

### ISSUE THREAD

**Issue by wolf-joe** [python-telegram-bot/python-telegram-bot#3463]
### Steps to Reproduce

1. download callback bot example: [arbitrarycallbackdatabot.py](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/arbitrarycallbackdatabot.py)
2. replace token in `arbitrarycallbackdatabot.py` and enable debug log
3. run `arbitrarycallbackdatabot.py`
4. type `/start` in bot and click button

### Expected behaviour

something happens

### Actual behaviour

nothing happens besides clock icon
![image](https://user-images.githubusercontent.com/58905296/210208600-38db3be4-b4d2-4fe6-bcfe-5c3c5884f5ec.png)

### Operating System

Ubuntu 20.04.3 LTS

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0
Bot API 6.4
Python 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
```

**Comment by Bibo-Joshi** [comment]
Thanks for reaching out.
We are not aware of any bug in the example as it [works fine for us](https://t.me/pythontelegrambotgroup/648559?thread=648554). Please try changing `application.run_polling()` to `application.run_polling(allowed_updates=Update.ALL_TYPES)` to ensure that your bot can actually receive all kinds of updates.

**Comment by wolf-joe** [comment]
> Thanks for reaching out. We are not aware of any bug in the example as it [works fine for us](https://t.me/pythontelegrambotgroup/648559?thread=648554). Please try changing `application.run_polling()` to `application.run_polling(allowed_updates=Update.ALL_TYPES)` to ensure that your bot can actually receive all kinds of updates.

works well after set `allowed_updates=Update.ALL_TYPES`

**Comment by wolf-joe** [comment]
Telegram `getUpdates` API does not return `CallbackQuery` message in my case. Considering that my bot with callback handler works well later early, maybe this is a server-side issue.

**Comment by Bibo-Joshi** [comment]
> maybe this is a server-side issue.

Since `allowed_updates=Update.ALL_TYPES` solved the issue for you, I rather think that it was a config problem on your end.
