### ISSUE TITLE
Can we provide a more descriptive error message? 🤔

### ISSUE THREAD

**Issue by UpToDate2010** [python-telegram-bot/python-telegram-bot#3465]
Can we provide a more descriptive error message? 🤔

_Originally posted by @Bibo-Joshi in https://github.com/python-telegram-bot/python-telegram-bot/pull/3322#discussion_r1010658146_

**Comment by clot27** [comment]
@UpToDate2010 what

**Comment by harshil21** [comment]
This has been addressed in the PR, it is indeed possible to provide a more descriptive error message. Perhaps you were not viewing an _up to date_ version of the PR?
