### ISSUE TITLE
[QUESTION] Can't import telegram.ext.updater

### ISSUE THREAD

**Issue by unknownleakersource** [python-telegram-bot/python-telegram-bot#3476]
### Steps to Reproduce

1. ModuleNotFoundError: No module named 'telegram.ext.updater'

i was installed pip ready 

py -m telegram
python-telegram-bot 20.0
Bot API 6.4

yesterday its ok and right now problem 

### Expected behaviour

Traceback (most recent call last):
  File "E:\Project 2023\Builder Stub on TelegramBot\builder.py", line 1, in <module>
    from telegram.ext.updater import Updater
ModuleNotFoundError: No module named 'telegram.ext.updater'

### Actual behaviour

Traceback (most recent call last):
  File "E:\Project 2023\Builder Stub on TelegramBot\builder.py", line 1, in <module>
    from telegram.ext.updater import Updater
ModuleNotFoundError: No module named 'telegram.ext.updater'

### Operating System

WINDOWS 10

### Version of Python, python-telegram-bot & dependencies

```shell
py -m telegram
python-telegram-bot 20.0
Bot API 6.4
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
```

### Relevant log output

```python
Traceback (most recent call last):
  File "E:\Project 2023\Builder Stub on TelegramBot\builder.py", line 1, in <module>
    from telegram.ext.updater import Updater
ModuleNotFoundError: No module named 'telegram.ext.updater'
```

### Additional Context

Traceback (most recent call last):
  File "E:\Project 2023\Builder Stub on TelegramBot\builder.py", line 1, in <module>
    from telegram.ext.updater import Updater
ModuleNotFoundError: No module named 'telegram.ext.updater'

**Comment by Poolitzer** [comment]
@unknownleakersource Don&#x27;t install <code>telegram</code>, that is a completely different package. Uninstall <code>telegram</code> and <code>python-telegram-bot</code>, reinstall <code>python-telegram-bot</code>, and you are good to go.

.updater does not exists anymore in V20, read the wiki on how to do this now.

**Comment by unknownleakersource** [comment]
thank boss

**Comment by unknownleakersource** [comment]
> @unknownleakersource Don't install `telegram`, that is a completely different package. Uninstall `telegram` and `python-telegram-bot`, reinstall `python-telegram-bot`, and you are good to go.
> 
> .updater does not exists anymore in V20, read the wiki on how to do this now.

how can i make limit users id for requests to my telegram api any refferent

**Comment by unknownleakersource** [comment]
> @unknownleakersource Don't install `telegram`, that is a completely different package. Uninstall `telegram` and `python-telegram-bot`, reinstall `python-telegram-bot`, and you are good to go.
> 
> .updater does not exists anymore in V20, read the wiki on how to do this now.

i need use telegram InlineKeyboardButton, InlineKeyboardMarkup, ParseMode

**Comment by clot27** [comment]
@unknownleakersource Wiki of <i>python-telegram-bot</i> - Category <i>Design Pattern</i>
<a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#how-do-i-rate-limit-users-of-my-bot">How do I rate limit users of my bot?</a>
