### ISSUE TITLE
[QUESTION] limit users from using bot

### ISSUE THREAD

**Issue by unknownleakersource** [python-telegram-bot/python-telegram-bot#3477]
### Issue I am facing

i want try python telegram bot with limit per users example :
1 guy can get requests 3 times per key 

### Operating System

WINDOWS 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0
Bot API 6.4
```

**Comment by Poolitzer** [comment]
@unknownleakersource you can find an example design on how to restrict access in the wiki, here: <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#restrict-access-to-a-handler-decorator">Restrict access to a handler (decorator)</a>

We will not code something for you however.
