### ISSUE TITLE
[FEATURE] Time Picker Menu 

### ISSUE THREAD

**Issue by perevale** [python-telegram-bot/python-telegram-bot#3482]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Hi, it would be awesome if PTB is able to provide a menu for picking time (or date and time). 

### Describe the solution you'd like

There is already a scheduler menu in Telegram itself which can be triggered by scheduling a message or setting a reminder in the Scheduled messages. 
![image](https://user-images.githubusercontent.com/28216258/210794638-4982597b-1dc8-4127-96df-775f13017236.png)
![image](https://user-images.githubusercontent.com/28216258/210794865-0cc681b1-0062-468a-9df0-d66bf45894c0.png)

Maybe this can be triggered by some system calls, but I am not sure.

### Describe alternatives you've considered

By a little googling, I have found a lot of awkward  workarounds (e.g. inline keyboards), but none of them are really attractive from both UX and integrating into code point of view. 

### Additional context

Thank you in advance!

**Comment by Bibo-Joshi** [comment]
Hi thanks for reaching out.

The native date(time) picker of Telegram clients [can not be accessed via the Bot API](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#can-you-add-feature-to-ptb-can-i-do-thing-with-my-bot).

A common approach is to use inline keyboards to provide date(time) pickers (there even is a [library](https://pypi.org/project/python-telegram-bot-calendar/) for that, but I'm not sure if it's compatible with PTB v20) or to just parse textmessage (the [`dateutil`](https://pypi.org/project/python-dateutil/) library may be useful for that).

PTB is a *general purpose* library for building telegram bots. A UX for a date picker is a rather specific use case IMO and I don't see something like this getting integrated into the library. [`ptbcontrib`](https://github.com/python-telegram-bot/ptbcontrib) however would be a suitable place.

**Comment by harshil21** [comment]
Also note that with webapps you can implement this exact UI into your application, but again a place like ptbcontrib is a better place to implement this
