### ISSUE TITLE
[QUESTION] Export GPG key to a key-server

### ISSUE THREAD

**Issue by Felixoid** [python-telegram-bot/python-telegram-bot#3494]
### Issue I am facing

When I try to install an Arch Linux package from AUR, I need to do a manual step to [get the key](https://aur.archlinux.org/packages/python-telegram-bot#comment-861131) from github content.

A standard way to share the keys with the community is key servers. So the key owner should do something like:

```
gpg --send-keys 4CBA518847044E289548BD9FA2B984A9073022B2 --keyserver https://pgp.mit.edu
gpg --send-keys 4CBA518847044E289548BD9FA2B984A9073022B2 --keyserver hkps://keyserver.ubuntu.com
```

### Operating System

Arch Linux

### Version of Python, python-telegram-bot & dependencies

```shell
not relative
```

**Comment by Bibo-Joshi** [comment]
I've published the key to keyserver.ubuntu.com.
