### ISSUE TITLE
Flask and webhoos

### ISSUE THREAD

**Issue by gaiar** [python-telegram-bot/python-telegram-bot#351]
Hi!

I'm was trying to setup webhook with Flask/uwsgi/Nginx.

I was trying to use example from https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks

```
bot = Bot(tokens.TELEGRAM_TOKEN)
update_queue = Queue()
dp = Dispatcher(bot, update_queue)

def main():

    dp.add_handler(CommandHandler('start', start, pass_args=True))
    dp.add_handler(CommandHandler("help", help))
    dp.add_handler(MessageHandler([Filters.text], messages))
    dp.add_error_handler(error)

    thread = Thread(target=dp.start, name='dp')
    thread.start()

main()


@app.route('/hook/'+tokens.TELEGRAM_TOKEN, methods=['GET', 'POST'])
def webhook():
    if request.method == "POST":
        # retrieve the message in JSON and then transform it to Telegram object
        update = Update.de_json(request.get_json(force=True))

        logger.info("Update received! "+ update.message.text)
        update_queue.put(update)
        return "OK"
    else:
        return redirect("https://telegram.me/links_forward_bot", code=302)

```

But seems, such construction is not working. Should I manually go through Queue and pop updates to dispatch events?

I got code working after your comment which I found in other closed issue:

```
@app.route('/hook/'+tokens.TELEGRAM_TOKEN, methods=['GET', 'POST'])
def webhook():
    if request.method == "POST":
        # retrieve the message in JSON and then transform it to Telegram object
        update = Update.de_json(request.get_json(force=True))

        logger.info("Update received! "+ update.message.text)
        dp.process_update(update)
        update_queue.put(update)
        return "OK"
    else:
        return redirect("https://telegram.me/links_forward_bot", code=302)
```

This line made handlers receive events
`dp.process_update(update)`

Could please say if I'm doing something wrong with dispatcher and Queue?

**Comment by jh0ker** [comment]
Could you try setting the logging module to DEBUG level?

**Comment by gaiar** [comment]
Yes, sure. What should I look for?
If you need the whole project code - it is here https://github.com/gaiar/pocket-telegram-bot

**Comment by jh0ker** [comment]
Any log entries related to `telegram/ext/dispatcher.py` could be interesting

**Comment by jh0ker** [comment]
Friendly ping

**Comment by gaiar** [comment]
Sorry for delay. There is not so much information, unfortunately:

`cat ~/projects/forwardbot/forwardbot.log | grep dispatcher
2016-07-16 05:34:06,952 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2016-07-16 05:37:52,499 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2016-07-16 05:55:07,689 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
  File "/home/gaiar/projects/forwardbot/forwardbotenv/local/lib/python2.7/site-packages/telegram/ext/dispatcher.py", line 203, in process_update
    return self.callback(dispatcher.bot, update, **optional_args)
2016-07-16 05:58:05,118 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2016-07-16 07:29:49,816 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2016-07-17 07:43:34,256 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2016-07-19 07:01:36,387 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
  File "/home/gaiar/projects/forwardbot/forwardbotenv/local/lib/python2.7/site-packages/telegram/ext/dispatcher.py", line 203, in process_update
    return self.callback(dispatcher.bot, update, **optional_args)
`

**Comment by jh0ker** [comment]
I think this is the key:
` An uncaught error was raised while processing the update`

That usually means that your handler callback function raised an exception (you cut off the actual exception though)

**Comment by gaiar** [comment]
yes, it was related to my incorrect way of calling process_update. It doesn't happen anymore.
