### ISSUE TITLE
[Question] Importing Error

### ISSUE THREAD

**Issue by pruthivithejan** [python-telegram-bot/python-telegram-bot#3517]
### Steps to Reproduce

`import telegram.ext`

Import "telegram.ext" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)

### Expected behaviour

My bot suppose to work

### Actual behaviour

Traceback (most recent call last):
  File "c:\Users\Pruthivi\Desktop\Telegram Bots\ReminderBot\main.py", line 5, in <module>
    import telegram.ext
ModuleNotFoundError: No module named 'telegram'

### Operating System

Windows 11 Pro

### Version of Python, python-telegram-bot & dependencies

```shell
Python : 3.11
python-telegram-bot: 20.0
```

### Relevant log output

```python
Traceback (most recent call last):
  File "c:\Users\Pruthivi\Desktop\Telegram Bots\ReminderBot\main.py", line 5, in <module>
    import telegram.ext
ModuleNotFoundError: No module named 'telegram'
```

**Comment by harshil21** [comment]
@pruthivithejan Wiki of <i>python-telegram-bot</i> - Category <i>FAQ</i>
<a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#why-am-i-getting-importerror-cannot-import-name-xy-from-telegram">Why am I getting ImportError: cannot import name &#x27;XY&#x27; from &#x27;telegram&#x27;?</a>

**Comment by pruthivithejan** [comment]
> @pruthivithejan Wiki of python-telegram-bot - Category FAQ [Why am I getting ImportError: cannot import name 'XY' from 'telegram'?](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#why-am-i-getting-importerror-cannot-import-name-xy-from-telegram)

That didn't worked either. I haven't installed `telegram`. Installed `python-telegram-bot`

**Comment by Bibo-Joshi** [comment]
I see a capital T (Telegram) where there should be a lower case t (telegram).

**Comment by pruthivithejan** [comment]
> I see a capital T (Telegram) where there should be a lower case t (telegram).

Nah. I tried that afterwards. It didn't worked in the first place.

**Comment by Poolitzer** [comment]
how do you run main.py?

**Comment by pruthivithejan** [comment]
> how do you run main.py?

In VS Code. Do I have to use a framework?

**Comment by Bibo-Joshi** [comment]
you'll have to make sure that you run the script with the same python executable that's linked to the installation of ptb. having multiple python versions and/or virtual environments on one machine can mean that you installed PTB to one python version but use a different one to run the script. This is a general issue with installing python packages though and not specific to PTB.

**Comment by pruthivithejan** [comment]
> you'll have to make sure that you run the script with the same python executable that's linked to the installation of ptb. having multiple python versions and/or virtual environments on one machine can mean that you installed PTB to one python version but use a different one to run the script. This is a general issue with installing python packages though and not specific to PTB.

Thanks! It Worked. I had multiple versions installed.
