### ISSUE TITLE
Update messages with a photo

### ISSUE THREAD

**Issue by maglighter** [python-telegram-bot/python-telegram-bot#352]
Is it possible to update message with a photo? There is a method to update a message text: editMessageText, but how to change photo?

**Comment by rahiel** [comment]
No, the only methods available are those documented in the Telegram API: https://core.telegram.org/bots/api.

**Comment by gil9red** [comment]
Now, you can update the photo through the method Telegram API [editMessageMedia](https://core.telegram.org/bots/api#editmessagemedia)

Here is the method [Message.edit_media](https://github.com/python-telegram-bot/python-telegram-bot/blob/fc5844c13da3b3fb20bb2d0bfcdf1efb1a826ba6/telegram/message.py#L898), example ([my example](https://github.com/gil9red/SimplePyScripts/blob/12cf34f5a649e660489a7e2e441426547cb3eeb4/telegram_bot_examples/pagination/example_as_images.py#L72)):
```
from telegram import InputMediaPhoto

...

message.edit_media(
    media=InputMediaPhoto(
        media=open('image.jpg', 'rb'),
        caption='Title'
    )
)
```
