### ISSUE TITLE
New style of _application.process_update method (increase performance).

### ISSUE THREAD

**Issue by david-shiko** [python-telegram-bot/python-telegram-bot#3521]
I just read about design patterns and wondered why not to delegate choosing an appropriate handler up to Python and therefore increase the performance? 
We can use the publisher-subscriber pattern.

https://github.com/python-telegram-bot/python-telegram-bot/blob/359232e6c743d811c7f553e1d1ca096a02f01c98/telegram/ext/_application.py#L1049

### Describe the solution you'd like

```
# This dict created on app init.
app.update_types = {
'Photo': ['handler_1', 'handler_2', 'handler_n', ..., ],  # list of subscribed handlers
'Message': ['handler_1', 'handler_11', 'handler_n', ..., ],  # list of subscribed handlers
...
}

async def process_update(self, update: object) -> None:
    ...
    handlers = update_types[udate.type]
    if handlers:
        handler = handlers[0]  # IIRC, PTB passes update only to the first appropriate handler.
        handler.handle_update(update, self, check, context)
```

Instead of checking every handler for the update, we can just to use `dict` (hashmap) to check only the required subset.

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for reaching out.
TBH I don't see a benefit of your proposed solution and rather several drawbacks:

* Checking which attribute of the `update` is not `None` already requires looping over the attributes, so I doubt that this approach really speeds things up
* If you want more fine-grained control, e.g. only handling messages with a photo, you'd have to use nested dicts: `handlers = {'message': {'photo': […], 'sticker': […], ...}}` and loop also over the attributes of `message`
* This approach only allows to handle updates based on the presence of attributes. More elaborate checks as
    * checking the content of the message text
    * making one handler handle both edited messages and new messages is not possible.
    * checking the sender of the update
* Getting a grouping setup (see the `group` parameter of `Application.add_handler` working with your approach would require to either define multiple such dictionaries or introduce further nesting making the code less readable

**Comment by david-shiko** [comment]
I think you don't understand my point. Sorry for the obscurity. 
By using a new style, we can detect the type of update (such as 'message', 'command', 'callback', etc.) and use it as a key in a dictionary with handlers (subscribers). 
Even if a handler uses advanced filters (such as 'text' or 'regexp'), the filter is still a subset of some payload type ('Message' in this case) . 
So the order is:"

```
subscribers: dict[list] = {}  # defaultdict, add `*UpdateType` key if not exists yet

def my_cmd_handler(...):
    ...
```

APP INIT STAGE
```
dispatcher.add_handler(my_cmd_handler) causes -> 
subscrber_key = my_cmd_handler.expected_update_payload_type
subscribers[subscrber_key].append(my_cmd_handler)
```
 
WHEN UPDATE COMES:
```
async def process_update(self, update: object) -> None:
    ...
    subscribers_key = update.extract_update_payload_type()  # ComamndType for example
    handlers = update_types[subscribers_key]  # List of command handlers
    for cmd_handler in cmd_handlers:
        if cmd_handler.check_update(update):  # If handler uses advanced filters
            cmd_handler.handle_update(update, self, check, context)
            break
```

**Comment by Bibo-Joshi** [comment]
I see, so this would only narrow down, on which handlers we need to call `check_update`.
Still, I don't understand what you mean by 

> By using a new style, we can detect the type of update
> `update.extract_update_payload_type()  # ComamndType for example`

How do you expect this mechanism to look like? `CommandType` implies that you want this "type" to contain more information than which attributes are set: to know that a message contains a command, it's not sufficient to check of `message.text` and/or `message.entities` are there -  you have to check the contents of the entities.

Plus, my last point about grouping of handlers still remains …

**Comment by david-shiko** [comment]
Yes, it's only the way to "narrow down, on which handlers we need to call `check_update`".
TBH I don't know how PTB can detect "type" of incoming update. You have mentioned "checking contents of the entities", -it's looks sensible.

**Comment by Bibo-Joshi** [comment]
> TBH I don't know how PTB can detect "type" of incoming update.

There is no specific functionality for that and one would currently have to loop over all attributes to check if they are None.
One could think of a mechanism that sets the "type" of the update while that Update instance is built. But that becomes more involved with classes that have multiple attributes that can be present at the same time and also doesn't cover more complex filtering like inspecting message entities.

> You have mentioned "checking contents of the entities", -it's looks sensible.

This would require an interface like `is_update_type(update, update_type)` or similar and this would have to be called for potentially every update_type key in the dictionary.
This will only shift the computation time from `Handler.check_update` to `is_update_time`, but not really make it go away.

Keep in mind that
* We're talking about performance optimization in Python here - Python is not really the fastest language anyway ...
* `check_update` don't usually do computationally intensive operations. Only simple `is None` checks, Internet comparisons etc. Those aren't the things that slow your bot down - networking operations do

**Comment by david-shiko** [comment]
Okay. My key point is that we are applying Handler.check_update to every handler, 
but potentially we may only accomplish it on a predefined set of handlers, depending on the update type. 
But anyway, I believe you know what you're doing :)
