### ISSUE TITLE
[FEATURE] Persist timeouts of ConversationHandler

### ISSUE THREAD

**Issue by rejedai** [python-telegram-bot/python-telegram-bot#3522]
### Steps to Reproduce

1. Write ConversationHandler with **conversation_timeout**

### Expected behaviour

The time of the last message should be stored in persistence, because after restarting, the job disappears.

### Actual behaviour

After restarting the bot, the conversation does not end.

### Operating System

Linux

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0
Bot API 6.4
Python 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
```

**Comment by clot27** [comment]
hey, what persistence setup are you using?

**Comment by clot27** [comment]
is this similar to https://github.com/python-telegram-bot/ptbcontrib/issues/35#issue-1051441783 ?

**Comment by Bibo-Joshi** [comment]
Closing in favor of #2770
