### ISSUE TITLE
Inline queries not working in example. [BUG]

### ISSUE THREAD

**Issue by phentrophil100** [python-telegram-bot/python-telegram-bot#3524]
### Steps to Reproduce

1. Run bot with valid bot token.
2. Add bot to the group.
3. Write a message containing the name of the bot and the query, like this : "@bot_username query"

### Expected behaviour

Bot read&handle the message.
Bot echo the message.

### Actual behaviour

Bot do nothing

### Operating System

Debian

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0
Bot API 6.4
Python 3.11.0 (main, Nov 29 2022, 01:16:13) [GCC 10.2.1 20210110]
```

### Relevant log output

```python
2023-01-31 13:03:40,514 - apscheduler.scheduler - INFO - Scheduler started
2023-01-31 13:03:40,514 - telegram.ext._application - INFO - Application started
```

### Additional Context

Reproduce this with https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/inlinebot.py

**Comment by Bibo-Joshi** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/inlinebot.py#L6

**Comment by phentrophil100** [comment]
> https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/inlinebot.py#L6

Im blind idiot, sorry)
