### ISSUE TITLE
[QUESTION] Application instantiation without async function

### ISSUE THREAD

**Issue by searayeah** [python-telegram-bot/python-telegram-bot#3526]
### Issue I am facing

I've read tutorial [Running PTB alongside other asyncio frameworks](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#running-ptb-alongside-other-asyncio-frameworks) in the Wiki and using it's code built a simple echo bot.
```python
import asyncio
from telegram.ext import (
    ApplicationBuilder,
    MessageHandler,
    filters,
)
from os import environ

async def echo(update, context):
    await update.message.reply_text(update.message.text)

TG_TOKEN = environ["TG_TOKEN"]
application = ApplicationBuilder().token(TG_TOKEN).build()
application.add_handler(MessageHandler(filters.TEXT, echo))

async def main():
    async with application:
        await application.start()
        await application.updater.start_polling()
        await asyncio.sleep(100) # sleep for testing purpose
        await application.updater.stop()
        await application.stop()

asyncio.run(main())
```
It launches without an errors, updaters polling sees my input messages and ```MessageHandler``` is present in ```application.handlers```. However, I do not receive any messages back from the bot, as if the Handler does not trigger at all.
I found out that if I move Application instantiation inside async main function bot starts working fine and echoes my messages.
```python
import asyncio
from telegram.ext import (
    ApplicationBuilder,
    MessageHandler,
    filters,
)
from os import environ

async def echo(update, context):
    await update.message.reply_text(update.message.text)

TG_TOKEN = environ["TG_TOKEN"]

async def main():
    application = ApplicationBuilder().token(TG_TOKEN).build()
    application.add_handler(MessageHandler(filters.TEXT, echo))
    async with application:
        await application.start()
        await application.updater.start_polling()
        await asyncio.sleep(100) # sleep for testing purpose
        await application.updater.stop()
        await application.stop()

asyncio.run(main())
```
And moving the line ```application = ApplicationBuilder().token(TG_TOKEN).build()``` is what makes a difference. I do not understand this behaviour and it bothers me because I need the Application class be available globally for importing from other project files. 

### Operating System

Manjaro Linux 22

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0
Bot API 6.4
Python 3.9.16 (main, Jan  2 2023, 17:20:16)  [GCC 12.2.0]
```

**Comment by Bibo-Joshi** [comment]
Hi. I ran the example locally and it seems like tha `updater` does put the updates into the queue but for some reason the `application` is not able to fetch them. It does work however if I switch to Python 3.10/3.11. So my first guess is that the internals of `asyncio.run` changed somehow.
I haven't looked deeper into it yet. Maybe PTB can do something to support this on py3.7-3.9. Maybe it can't …
If using a newer python version is feasible for you, that would be a quick fix.

**Comment by searayeah** [comment]
Yeah, changing Python verison fixed the issue. Thanks
