### ISSUE TITLE
[BUG] Callback data larger than MAX_CALLBACK_DATA makes request and throws exception

### ISSUE THREAD

**Issue by pniaps** [python-telegram-bot/python-telegram-bot#3528]
### Steps to Reproduce

Try to send button with callback_data more than MAX_CALLBACK_DATA bytes long

```
keyboard = InlineKeyboardMarkup(
    [
        [
            InlineKeyboardButton(
                text='Button text',
                callback_data='------this------callback------data------is------more------than------64------bytes------long------'
            )
        ],
    ]
)
await update.effective_message.reply_text(
    text='message text',
    reply_markup=keyboard
)

```

### Expected behaviour

Throw an exception instead of making a request to Telegram API

### Actual behaviour

It makes a request to Telegram API that returns a bad request response and throws an exception

### Operating System

Ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0
Bot API 6.4
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
```

### Relevant log output

```python
File "/opt/virtualenv/lib/python3.10/site-packages/telegram/_message.py", line 1006, in reply_text
    return await self.get_bot().send_message(
  File "/opt/virtualenv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 2596, in send_message
    return await super().send_message(
  File "/opt/virtualenv/lib/python3.10/site-packages/telegram/_bot.py", line 334, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
  File "/opt/virtualenv/lib/python3.10/site-packages/telegram/_bot.py", line 767, in send_message
    return await self._send_message(
  File "/opt/virtualenv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 488, in _send_message
    result = await super()._send_message(
  File "/opt/virtualenv/lib/python3.10/site-packages/telegram/_bot.py", line 515, in _send_message
    result = await self._post(
  File "/opt/virtualenv/lib/python3.10/site-packages/telegram/_bot.py", line 422, in _post
    return await self._do_post(
  File "/opt/virtualenv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 306, in _do_post
    return await super()._do_post(
  File "/opt/virtualenv/lib/python3.10/site-packages/telegram/_bot.py", line 453, in _do_post
    return await request.post(
  File "/opt/virtualenv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
  File "/opt/virtualenv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 328, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Button_data_invalid
```

**Comment by pniaps** [comment]
At first, the 'Button_data_invalid' error does not give me useful information and I have to debug the code, but the code is correct.

If this data is validated before making the request (in the constructor of the class) it will be easier to debug the code.

**Comment by harshil21** [comment]
@pniaps Hi, PTB doesn&#x27;t do any client side length check on your callback data. If you want to send callback data more than 64 bytes, have a look at <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Arbitrary-callback_data">Arbitrary callback_data</a>

**Comment by Poolitzer** [comment]
I would like to expand on that that the reason behind this decision to drop most validation in the library is that they would be very limiting if telegram ever changes them. E.g. if they would suddenly allow 128 bytes in callback data, but PTB doesn't easily allow you to set them in older versions, you force people to upgrade needlessly.

**Comment by pniaps** [comment]
> If you want to send callback data more than 64 bytes, have a look at [Arbitrary callback_data](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Arbitrary-callback_data)

Thanks, i will think about implementing this.

> I would like to expand on that that the reason behind this decision to drop most validation in the library is that they would be very limiting if telegram ever changes them. E.g. if they would suddenly allow 128 bytes in callback data, but PTB doesn't easily allow you to set them in older versions, you force people to upgrade needlessly.

I agree with that.

In my case, i'm concatenating a string. It's normally short, but there are corner cases that produces a very long string. I'm checking the length of the string and if necessary I remove a part of the string
