### ISSUE TITLE
[BUG] Incorrect type hinting for Application.create_task

### ISSUE THREAD

**Issue by sam-mosleh** [python-telegram-bot/python-telegram-bot#3540]
### Steps to Reproduce

In the wiki you have provided an example for [Avoiding flood limits](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-flood-limits) :

```python
async def broadcast(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(text="Starting the broadcast...")
    context.application.create_task(
        asyncio.gather(
            *(
                context.bot.send_message(
                    chat_id=user_id, text="Hello World!", rate_limit_args={'priority': -1}
                )
                for user_id in user_ids
            )
        )
    )

```
which has a typing issue because `asyncio.gather` returns a `asyncio.Future` and `Application.create_task` expects an `asyncio.Coroutine`

### Expected behaviour

`Application.create_task` should also expect a `Future` besides `Coroutine`.

### Actual behaviour

```python
def create_task(self, coroutine: Coroutine, update: object = None) -> asyncio.Task:
```

### Operating System

Manjaro Linux 22.0.0

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.0
Bot API 6.4
Python 3.10.6 (main, Aug 23 2022, 08:36:38) [GCC 10.2.1 20210110]
```

**Comment by sam-mosleh** [comment]
I would be glad to try to open a PR for this, Thanks.

**Comment by Bibo-Joshi** [comment]
Thanks for reaching out. A PR would be welcome indeed!
Please apply the same type hints as the std library does:

https://github.com/python/typeshed/blob/cf6ff75952c21e4b5de72b2d0d3d0f0cbb14a563/stdlib/asyncio/tasks.pyi#L323

**Comment by sam-mosleh** [comment]
Since we are only awaiting on the object, utilizing `Awaitable` is more suitable, considering both `asyncio.Future` and `typing.Coroutine` are sub-classes of it.
