### ISSUE TITLE
documentation improvement

### ISSUE THREAD

**Issue by songproducer** [python-telegram-bot/python-telegram-bot#3545]
Documentation on https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-JobQueue
heading: **Usage**

Should be pip install python-telegram-bot[job**-**queue]
not 
pip install python-telegram-bot[job**_**queue]

1. pip install python-telegram-bot[job_queue]
2. WARNING: python-telegram-bot 20.0 does not provide the extra 'job_queue'

**Comment by harshil21** [comment]
sorry, there's a typo, it's actually `pip install python-telegram-bot [job-queue]` which has been fixed

**Comment by clot27** [comment]
Fixed in v20.1
