### ISSUE TITLE
[FEATURE] Use local Bot API server in Github Actions

### ISSUE THREAD

**Issue by harshil21** [python-telegram-bot/python-telegram-bot#3558]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

We can use a local bot API server in our test workflow, so we can catch bugs like #3556 early. With cached GH builds, we only need to build once per API update/OS upgrade of the runner

### Describe the solution you'd like

- Create a new job in `test.yml` which builds the instance
- New bot should be used, and that bot should always log out of cloud Bot API server before any other tests are run

We can then also test additional things using an environment variable flag:
- the `AppBuilder.local_mode` setting for file handing

### Additional context

Things to check before attempting an implementation:

- [ ] Can recompiling be automatically be done when detecting changes on https://github.com/tdlib/telegram-bot-api?
- [ ] Can we run several CI runs the same time with the same bot token for tests on local api server?
    - [ ] Does starting the API on a new server (i.e. each time a new ci runner is selected) count as new instance? Or is that tied to api-id/hash?
    - [ ] Can a bot make requests to more than one local api server at a time? 
    - [ ] Were in the test suite do we use `get_updates`/`run_polling`/`set/delete_webhook`/`run_webhook` and how does affect the question at hand?

**Comment by Bibo-Joshi** [comment]
> that bot should always log out of cloud Bot API server before any other tests are run

It must also `close` after each run of the CI, no matter if the test suite succeeded.

> we only need to build once per API update/OS upgrade of the runner

It would be great if that could be automated as well, e.g. by recompiling if updates are detected on https://github.com/tdlib/telegram-bot-api

**Comment by Poolitzer** [comment]
Maybe I don't see it, is there a downside to always use a local api instance?

**Comment by Bibo-Joshi** [comment]
> Maybe I don't see it, is there a downside to always use a local api instance?

* not testing against the cloud instance 
* having to rebuild for all OSes on very API update
* depending on how well tha `close` thingy works, possibly increased flakyness …

**Comment by Poolitzer** [comment]
@Bibo-Joshi Well one OS with the instance would be enough no?
Close is just needed if you move instances though... We could also host one ourselves (on our website/rools server) and limit that to our own tokens so the abuse potential is not there, and we don&#x27;t have to deal with potential janky close behavior.

I might overcomplicate things though

**Comment by Bibo-Joshi** [comment]
@Poolitzer One OS: Welp, I understood &quot;always use local API&quot; as run all tests on local API 😉

Close: from my understanding, starting the API on a new server (i.e. each time a new ci runner is selected) would be a new instance, right? Or is that tied to api-id/hash?

Host on our own: that way we couldn&#x27;t test the local mode though. Unless we set up a custom githuh runner. THB that sounds like overkill to me :D

**Comment by Poolitzer** [comment]
> one OS

Yeah that's what I meant, thought that might make implementing the local API easier.

> tied to new instance or is that tied to api-id/hash

I don't know

> Host on our own: that way we couldn't test the local mode though.

Sure we could, just because you run the API server in local mode doesn't mean the connections to it do have to be local

**Comment by Bibo-Joshi** [comment]
> > tied to new instance or is that tied to api-id/hash
> 
> I don't know
>

So that would need checking :)

> > Host on our own: that way we couldn't test the local mode though.
> 
> Sure we could, just because you run the API server in local mode doesn't mean the connections to it do have to be local

Huh? If the API server is on a remote machine, then how is uploading a file by passing the file path supposed to work?

**Comment by Poolitzer** [comment]
@Bibo-Joshi Hardcode the file path.

**Comment by Bibo-Joshi** [comment]
As there is no profound interest in this feature in the dev team at the moment and the technical realization is still rather unclear, I'm closing this issue as won't-do for now. If interest spikes in the future, we can revisit.
