### ISSUE TITLE
problem with ext submodule

### ISSUE THREAD

**Issue by asurari** [python-telegram-bot/python-telegram-bot#356]
### Steps to reproduce
1.import telegram.ext produces error

2.

3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating System:**
windows 7

**Version of Python:**
2.7.9
``$ python -V``

**Version of python-telegram-bot:**
5.0.0
``$ python -c 'import telegram; print(telegram.__version__)'``

### Logs
Insert logs here (if necessary)

**Comment by rahiel** [comment]
You should include the error, how else can we know what went wrong?

Also read [How to Report Bugs Effectively](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html)

**Comment by jh0ker** [comment]
Closing, please reopen if you have info to reproduce
