### ISSUE TITLE
[QUESTION]new_chat_members can't be obtained in a group of 48,000 people

### ISSUE THREAD

**Issue by xiaomi2077** [python-telegram-bot/python-telegram-bot#3560]
### Issue I am facing

I want the robot to say hello to everyone who has just entered the group, and it works fine in a group of less than 10,000 people, but it does not respond in a group of 48,000 people.
My code like this:
``` python
dispatcher.add_handler(MessageHandler(Filters.status_update.new_chat_members & Filters.chat(chat_id=manage_groups),
                                            say_hi),
                            group=1)
```
When someone joins the group, `update.message.new_chat_members` value is an empty list, and the normal situation should be the `user` object of the person who just joined the group

I found a similar issue, and you guys have a solution -> https://github.com/python-telegram-bot/python-telegram-bot/issues/2314#issuecomment-759923754
I noticed this sentence in code snippets -> `Note that service messages about non-bot users joining the chat are removed from large groups.` Is that the cause of the problem?

And I found code for similar functionality in the example code.
https://github.com/python-telegram-bot/python-telegram-bot/blob/680cca8262ab3e8dc00916ec523b9e015db5bc22/examples/chatmemberbot.py#L144
But it doesn't work for me. When someone joins the group, the function`greet_chat_members` is not triggered at all.

### Related part of your code

```python
1. dispatcher.add_handler(MessageHandler(Filters.status_update.new_chat_members & Filters.chat(chat_id=manage_groups),
                                            say_hi),
                            group=1)

  2.  dispatcher.add_handler(ChatMemberHandler(say_hi, ChatMemberHandler.ANY_CHAT_MEMBER)
                            ,group=1)

# I tried 2 ways to write and none worked
```

### Operating System

mac air m1

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.15
Bot API 6.3
certifi2022.09.24
Python 3.10.6 (main, Oct 24 2022, 11:04:07) [Clang 12.0.0 ]
```

**Comment by Poolitzer** [comment]
> . When someone joins the group, the function `greet_chat_members` is not triggered at all.

https://docs.python-telegram-bot.org/en/stable/telegram.update.html#telegram.Update.chat_member
