### ISSUE TITLE
Sequential processing for single user, but async processing for different

### ISSUE THREAD

**Issue by karfly** [python-telegram-bot/python-telegram-bot#3575]
### Issue I am facing

I set `.concurrent_updates(True)` in my bot to make it fully asynchronous.
Is it possible to process updates for a single user sequentially one-by-one, but keep bot asynchronous for other users?

I'm asking this question, because I'm afraid of race conditions while accessing DB for a single user. Sequential processing would fully solve my problem.

### Operating System

Ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
20.1
```

**Comment by Poolitzer** [comment]
#3509
