### ISSUE TITLE
[QUESTION] unable to take multiple inputs within a single feature

### ISSUE THREAD

**Issue by KavyaSethia** [python-telegram-bot/python-telegram-bot#3578]
### Issue I am facing

we are making a telgram bot for assignment reminder using python telegram bot librarry.But the problem is whenever i take input from user it cant recognize it

### Operating System

Windows

### Version of Python, python-telegram-bot & dependencies

```shell
python3.9
 python-telegram-bot 12.0.0
```

**Comment by Bibo-Joshi** [comment]
@KavyaSethia Hey. In order for someone to be able to help you, you must ask a <b>good technical question</b>. Please read <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Ask-Right">this short article</a> and try again ;), Hey. You seem to be using a version &lt;=13.15 of <code>python-telegram-bot</code>. Please note that we only provide support for the latest stable version and that the library has undergone significant changes in v20. Please consider upgrading to v20 by reading the release notes and the transition guide linked below.
