### ISSUE TITLE
[QUESTION] customwebhookbot.py do not react to commands

### ISSUE THREAD

**Issue by Acidherr** [python-telegram-bot/python-telegram-bot#3579]
### Steps to Reproduce

1.  clone customwebhookbot.py
2.  set bot token, url, admin chat_id and port at the start of the `main` function.
3.  run 

### Expected behaviour

- When sending the command '/start' in the bot's chat, the bot should reply with instructions on how to use the bot
- When sending a webhook the bot reacts

### Actual behaviour

- When sending the command '/start' in the bot's chat, the bot do not reply
- When sending a webhook the bot reacts

### Operating System

windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.1
Bot API 6.5
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
Please check the output of the `getWebhookInfo` API endpoint to see if there are any issues with your webhook configuration

**Comment by Acidherr** [comment]
> Please check the output of the `getWebhookInfo` API endpoint to see if there are any issues with your webhook configuration

I am not sure what you mean. 

- checked URL:PORT/healthcheck and it outputs "The bot is still running fine :)"
- checked URL:PORT/getWebhookInfo and it says "Not Found", which I understand, because such route is never defined.

To be clear, the webhooks work just fine, the problem is that the bot do not react to my commands in the chat (/start).

**Comment by Poolitzer** [comment]
@Acidherr That&#x27;s a telegram api call, if you do it, it will show you if telegram is able to send its updates to your server

**Comment by Bibo-Joshi** [comment]
@Acidherr <code>Bot.get_webhook_info</code>
<i>python-telegram-bot</i> documentation for this method:
<a href="https://docs.python-telegram-bot.org/telegram.bot.html#telegram.Bot.get_webhook_info">telegram.Bot.get_webhook_info</a>

Telegram&#x27;s official Bot API documentation has more info about <a href="https://core.telegram.org/bots/api#getwebhookinfo">getWebhookInfo</a>.

**Comment by Acidherr** [comment]
> @Acidherr `Bot.get_webhook_info` python-telegram-bot documentation for this method: [telegram.Bot.get_webhook_info](https://docs.python-telegram-bot.org/telegram.bot.html#telegram.Bot.get_webhook_info)
> 
> Telegram's official Bot API documentation has more info about [getWebhookInfo](https://core.telegram.org/bots/api#getwebhookinfo).

thanks, turns out my proxy was doing crazy stuff.
