### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'pass_job_queue'

### ISSUE THREAD

**Issue by AmirGhazaei** [python-telegram-bot/python-telegram-bot#358]
### Steps to reproduce
1. run timerbot example

### Expected behaviour
error: TypeError: __init__() got an unexpected keyword argument 'pass_job_queue'

### Actual behaviour
run without error! 

### Configuration
Windows 10

**Version of Python:**

3.5.2

**Version of python-telegram-bot:**

5.0.0

### Logs
```
Traceback (most recent call last):
** IDLE Internal Exception: 
  File "C:\Program Files (x86)\Python35-32\lib\idlelib\run.py", line 351, in runcode
    exec(code, self.locals)
  File "D:\OK\Bots\Python\Tests\jobqueue.py", line 104, in <module>
    main()
  File "D:\OK\Bots\Python\Tests\jobqueue.py", line 88, in main
    dp.add_handler(CommandHandler("set", set, pass_args=True, pass_job_queue=True))
TypeError: __init__() got an unexpected keyword argument 'pass_job_queue'
```

**Comment by jh0ker** [comment]
Hello! Would you please include the output of `python -m telegram`

**Comment by AmirGhazaei** [comment]
Hello!
With clean install python 3.5.2 and python-telegram-bot 5.0.0 the problem is solved.
Thanks you.
