### ISSUE TITLE
[QUESTION] Unable to parse escape

### ISSUE THREAD

**Issue by xyhcode** [python-telegram-bot/python-telegram-bot#3585]
### Issue I am facing

I did a `Markdown` conversion of the results returned by the `OpenAI`, but I still get an error after the conversion.

### Traceback to the issue

```python
2023-03-10 21:04:57,372 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telegram/ext/_conversationhandler.py", line 826, in handle_update
    new_state: object = await handler.handle_update(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/Users/xianxian/Documents/python/study/ChatGPT-Telegram.py", line 83, in reply
    sent_message = await context.bot.send_message(chat_id=update.effective_chat.id,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 2598, in send_message
    return await super().send_message(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telegram/_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telegram/_bot.py", line 760, in send_message
    return await self._send_message(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 488, in _send_message
    result = await super()._send_message(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telegram/_bot.py", line 512, in _send_message
    result = await self._post(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telegram/_bot.py", line 419, in _post
    return await self._do_post(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 306, in _do_post
    return await super()._do_post(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telegram/_bot.py", line 450, in _do_post
    return await request.post(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 328, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
```

### Related part of your code

```python
# Returns the Open AI result and converts it
def retrunres(issue):
    completion = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": issue}]
    )
    recontent = telegram.helpers.escape_markdown(completion.choices[0].message.content, 2)
    return recontent

# Send to the user：This is just the main code sent 
    await context.bot.edit_message_text(chat_id=sent_message.chat_id,
                                        message_id=sent_message.message_id,
                                        text=f"{user_name}：{update.message.text}\n\n{Replycontent}",
                                        parse_mode=ParseMode.MARKDOWN_V2)
```

### Operating System

macOS Ventura 13.2.1

### Version of Python, python-telegram-bot & dependencies

```shell
xianxian@xianxiandeMacBook-Pro study % python3 -m telegram
python-telegram-bot 20.1
Bot API 6.5
Python 3.10.10 (v3.10.10:aad5f6a891, Feb  7 2023, 08:47:40) [Clang 13.0.0 (clang-1300.0.29.30)]
```

**Comment by xyhcode** [comment]
> 嗨，你既没有逃避`user_name `也没有`update.message.text`，你确定问题不存在吗？

If these two weren't, I don't think it should be this mistake

**Comment by Poolitzer** [comment]
Then post the string please which breaks our `escape_markdown` so I can try to reproduce

**Comment by xyhcode** [comment]
> Then post the string please which breaks our `escape_markdown` so I can try to reproduce

This content is returned by `openai`, the problem is to write a multiplication phrase in Java, of course, if I am not practical with the returned content `escape_markdown` it will also report an error

```java
public class MultiplicationTable {
    public static void main(String[] args) {
        // Produce multiplication table from 1 to 9
        for (int i = 1; i <= 9; i++) {
            for (int j = 1; j <= i; j++) {
                System.out.print(j + " x " + i + " = " + i * j + "   ");
            }
            System.out.println();
        }
    }
}
```

输出结果为：

```text
1 x 1 = 1   
1 x 2 = 2   2 x 2 = 4   
1 x 3 = 3   2 x 3 = 6   3 x 3 = 9   
1 x 4 = 4   2 x 4 = 8   3 x 4 = 12   4 x 4 = 16  
1 x 5 = 5   2 x 5 = 10  3 x 5 = 15  4 x 5 = 20  5 x 5 = 25  
1 x 6 = 6   2 x 6 = 12  3 x 6 = 18  4 x 6 = 24  5 x 6 = 30  6 x 6 = 36  
1 x 7 = 7   2 x 7 = 14  3 x 7 = 21  4 x 7 = 28  5 x 7 = 35  6 x 7 = 42  7 x 7 = 49  
1 x 8 = 8   2 x 8 = 16  3 x 8 = 24  4 x 8 = 32  5 x 8 = 40  6 x 8 = 48  7 x 8 = 56  8 x 8 = 64  
1 x 9 = 9   2 x 9 = 18  3 x 9 = 27  4 x 9 = 36  5 x 9 = 45  6 x 9 = 54  7 x 9 = 63  8 x 9 = 72  9 x 9 = 81  
```

**Comment by Poolitzer** [comment]
I am not sure you understood me correctly, I need the string which errors out for you. Your string works just fine if you replace the newlines with \n.

![image](https://user-images.githubusercontent.com/25934244/224367908-5ae3d994-accf-4305-ba2d-e5af2d4e0aa8.png)

```python
import asyncio
import telegram


async def main():
    bot = telegram.Bot("1234455:TOKEN")
    async with bot:
        print(await bot.send_message(208589966, telegram.helpers.escape_markdown("1 x 1 = 1   \n1 x 2 = 2   2 x 2 = 4   \n1 x 3 = 3   2 x 3 = 6   3 x 3 = 9   \n1 x 4 = 4   2 x 4 = 8   3 x 4 = 12   4 x 4 = 16  \n1 x 5 = 5   2 x 5 = 10  3 x 5 = 15  4 x 5 = 20  5 x 5 = 25  \n1 x 6 = 6   2 x 6 = 12  3 x 6 = 18  4 x 6 = 24  5 x 6 = 30  6 x 6 = 36  \n1 x 7 = 7   2 x 7 = 14  3 x 7 = 21  4 x 7 = 28  5 x 7 = 35  6 x 7 = 42  7 x 7 = 49  \n1 x 8 = 8   2 x 8 = 16  3 x 8 = 24  4 x 8 = 32  5 x 8 = 40  6 x 8 = 48  7 x 8 = 56  8 x 8 = 64  \n1 x 9 = 9   2 x 9 = 18  3 x 9 = 27  4 x 9 = 36  5 x 9 = 45  6 x 9 = 54  7 x 9 = 63  8 x 9 = 72  9 x 9 = 81  ", 2)))


if __name__ == '__main__':
    asyncio.run(main())

```

**Comment by xyhcode** [comment]
> I am not sure you understood me correctly, I need the string which errors out for you. Your string works just fine if you replace the newlines with \n.
> 
> ![image](https://user-images.githubusercontent.com/25934244/224367908-5ae3d994-accf-4305-ba2d-e5af2d4e0aa8.png)
> 
> ```python
> import asyncio
> import telegram
> 
> 
> async def main():
>     bot = telegram.Bot("1234455:TOKEN")
>     async with bot:
>         print(await bot.send_message(208589966, telegram.helpers.escape_markdown("1 x 1 = 1   \n1 x 2 = 2   2 x 2 = 4   \n1 x 3 = 3   2 x 3 = 6   3 x 3 = 9   \n1 x 4 = 4   2 x 4 = 8   3 x 4 = 12   4 x 4 = 16  \n1 x 5 = 5   2 x 5 = 10  3 x 5 = 15  4 x 5 = 20  5 x 5 = 25  \n1 x 6 = 6   2 x 6 = 12  3 x 6 = 18  4 x 6 = 24  5 x 6 = 30  6 x 6 = 36  \n1 x 7 = 7   2 x 7 = 14  3 x 7 = 21  4 x 7 = 28  5 x 7 = 35  6 x 7 = 42  7 x 7 = 49  \n1 x 8 = 8   2 x 8 = 16  3 x 8 = 24  4 x 8 = 32  5 x 8 = 40  6 x 8 = 48  7 x 8 = 56  8 x 8 = 64  \n1 x 9 = 9   2 x 9 = 18  3 x 9 = 27  4 x 9 = 36  5 x 9 = 45  6 x 9 = 54  7 x 9 = 63  8 x 9 = 72  9 x 9 = 81  ", 2)))
> 
> 
> if __name__ == '__main__':
>     asyncio.run(main())
> ```

Sorry, maybe you haven't understood what I mean, you tried adding this code earlier, you are missing a piece of Java code, if it is a simple multiplication mantra for sure.  Please use the contents of the file to try the string.
[test.txt](https://github.com/python-telegram-bot/python-telegram-bot/files/10944060/test.txt)

**Comment by xyhcode** [comment]
> I am sorry, I don't want to run java code. Please just give me the string which breaks the `escape_markdown`.

No, I'm not asking you to run Java, you just need to test the contents of the file as strings

**Comment by xyhcode** [comment]
> Ohhh now I get you. Sure. Works. ![image](https://user-images.githubusercontent.com/25934244/224374260-30c79cb4-ac83-4280-8b1b-e17a8943eba8.png)
> 
> ```
> print(await bot.send_message(208589966, telegram.helpers.escape_markdown('```java\npublic class MultiplicationTable {\n    public static void main(String[] args) {\n        // Produce multiplication table from 1 to 9\n        for (int i = 1; i <= 9; i++) {\n            for (int j = 1; j <= i; j++) {\n                System.out.print(j + " x " + i + " = " + i * j + "   ");\n            }\n            System.out.println();\n        }\n    }\n}\n```\n\n输出结果为：\n\n```text\n1 x 1 = 1   \n1 x 2 = 2   2 x 2 = 4   \n1 x 3 = 3   2 x 3 = 6   3 x 3 = 9   \n1 x 4 = 4   2 x 4 = 8   3 x 4 = 12   4 x 4 = 16  \n1 x 5 = 5   2 x 5 = 10  3 x 5 = 15  4 x 5 = 20  5 x 5 = 25  \n1 x 6 = 6   2 x 6 = 12  3 x 6 = 18  4 x 6 = 24  5 x 6 = 30  6 x 6 = 36  \n1 x 7 = 7   2 x 7 = 14  3 x 7 = 21  4 x 7 = 28  5 x 7 = 35  6 x 7 = 42  7 x 7 = 49  \n1 x 8 = 8   2 x 8 = 16  3 x 8 = 24  4 x 8 = 32  5 x 8 = 40  6 x 8 = 48  7 x 8 = 56  8 x 8 = 64  \n1 x 9 = 9   2 x 9 = 18  3 x 9 = 27  4 x 9 = 36  5 x 9 = 45  6 x 9 = 54  7 x 9 = 63  8 x 9 = 72  9 x 9 = 81  \n```', 2)))
> ```
Thank you very much for your patience to answer for me, below is my code, I hope you can help me check it out when you have time

```python
def retrunres(issue):
    completion = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": issue}]
    )
    print(completion.choices[0].message.content)
    recontent = telegram.helpers.escape_markdown(completion.choices[0].message.content, 2)
    return recontent

async def reply(update: Update, context: CallbackContext) -> int:
    user_name = update.effective_user.full_name
    message_text = update.message.text
    reply_to_message = update.message.reply_to_message
    if reply_to_message and reply_to_message.text:
        previous_message_text = reply_to_message.text
        await context.bot.send_chat_action(chat_id=update.effective_chat.id, action="typing")
        Replycontent = await retrunres(previous_message_text + " " + message_text)
    else:
        await context.bot.send_chat_action(chat_id=update.effective_chat.id, action="typing")
        Replycontent = retrunres(message_text)
    await context.bot.send_message(chat_id=update.effective_chat.id, text=Replycontent, parse_mode=ParseMode.MARKDOWN_V2)
    return REPLY
```

**Comment by xyhcode** [comment]
> Ohhh now I get you. Sure. Works. ![image](https://user-images.githubusercontent.com/25934244/224374260-30c79cb4-ac83-4280-8b1b-e17a8943eba8.png)
> 
> ```
> print(await bot.send_message(208589966, telegram.helpers.escape_markdown('```java\npublic class MultiplicationTable {\n    public static void main(String[] args) {\n        // Produce multiplication table from 1 to 9\n        for (int i = 1; i <= 9; i++) {\n            for (int j = 1; j <= i; j++) {\n                System.out.print(j + " x " + i + " = " + i * j + "   ");\n            }\n            System.out.println();\n        }\n    }\n}\n```\n\n输出结果为：\n\n```text\n1 x 1 = 1   \n1 x 2 = 2   2 x 2 = 4   \n1 x 3 = 3   2 x 3 = 6   3 x 3 = 9   \n1 x 4 = 4   2 x 4 = 8   3 x 4 = 12   4 x 4 = 16  \n1 x 5 = 5   2 x 5 = 10  3 x 5 = 15  4 x 5 = 20  5 x 5 = 25  \n1 x 6 = 6   2 x 6 = 12  3 x 6 = 18  4 x 6 = 24  5 x 6 = 30  6 x 6 = 36  \n1 x 7 = 7   2 x 7 = 14  3 x 7 = 21  4 x 7 = 28  5 x 7 = 35  6 x 7 = 42  7 x 7 = 49  \n1 x 8 = 8   2 x 8 = 16  3 x 8 = 24  4 x 8 = 32  5 x 8 = 40  6 x 8 = 48  7 x 8 = 56  8 x 8 = 64  \n1 x 9 = 9   2 x 9 = 18  3 x 9 = 27  4 x 9 = 36  5 x 9 = 45  6 x 9 = 54  7 x 9 = 63  8 x 9 = 72  9 x 9 = 81  \n```', 2)))
> ```
I don't know why, I can't do this anymore
<img width="599" alt="image" src="https://user-images.githubusercontent.com/64968400/224453420-98d59015-2b60-441d-aba8-c9d28d9c50c6.png">

**Comment by Poolitzer** [comment]
You need to make sure to not accidentally escape markdown you actually want applied.

![image](https://user-images.githubusercontent.com/25934244/224482076-b99c8e12-76e4-46d3-9570-a6e75d932f22.png)
```
print(await bot.send_message(208589966, "```" + telegram.helpers.escape_markdown('java\npublic class MultiplicationTable {\n    public static void main(String[] args) {\n        // Produce multiplication table from 1 to 9\n        for (int i = 1; i <= 9; i++) {\n            for (int j = 1; j <= i; j++) {\n                System.out.print(j + " x " + i + " = " + i * j + "   ");\n            }\n            System.out.println();\n        }\n    }\n}\n', 2) + "```\n\n输出结果为：\n\n```" + telegram.helpers.escape_markdown('text\n1 x 1 = 1   \n1 x 2 = 2   2 x 2 = 4   \n1 x 3 = 3   2 x 3 = 6   3 x 3 = 9   \n1 x 4 = 4   2 x 4 = 8   3 x 4 = 12   4 x 4 = 16  \n1 x 5 = 5   2 x 5 = 10  3 x 5 = 15  4 x 5 = 20  5 x 5 = 25  \n1 x 6 = 6   2 x 6 = 12  3 x 6 = 18  4 x 6 = 24  5 x 6 = 30  6 x 6 = 36  \n1 x 7 = 7   2 x 7 = 14  3 x 7 = 21  4 x 7 = 28  5 x 7 = 35  6 x 7 = 42  7 x 7 = 49  \n1 x 8 = 8   2 x 8 = 16  3 x 8 = 24  4 x 8 = 32  5 x 8 = 40  6 x 8 = 48  7 x 8 = 56  8 x 8 = 64  \n1 x 9 = 9   2 x 9 = 18  3 x 9 = 27  4 x 9 = 36  5 x 9 = 45  6 x 9 = 54  7 x 9 = 63  8 x 9 = 72  9 x 9 = 81  \n', 2) + "```", parse_mode=telegram.constants.ParseMode.MARKDOWN_V2))
```
