### ISSUE TITLE
[QUESTION] How to add usernames dynamically to `filters.User()`?

### ISSUE THREAD

**Issue by clemsau** [python-telegram-bot/python-telegram-bot#3589]
### Issue I am facing

Is it possible to add `username` to a `User` instance, the same way we can add `chat_id` with the method `add_user_ids` (see `telegram.ext.filters.User`)

I think I have seen some past issues mentioning this and solving this, but why don't I have any method to do it ?

### Related part of your code

```python
user_filter = filters.User()

# cannot do
user_filter.add_username("me")
```

### Operating System

Ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
python 3.10
python-telegram-bot 20.1
```

**Comment by Poolitzer** [comment]
The function is named with an s: https://docs.python-telegram-bot.org/en/stable/telegram.ext.filters.html#telegram.ext.filters.User.add_usernames
