### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by crypton0** [python-telegram-bot/python-telegram-bot#3592]
### Issue I am facing

faced with a problem when assembling a bot - who will be able to assemble it ?

### Operating System

Xz 

### Version of Python, python-telegram-bot & dependencies

```shell
Buy - sell - Crypto - Market 
Open - Settings - Settings
```

**Comment by Poolitzer** [comment]
Hello there. You are writing your job offer in our issues, which is against rules/common behavior. To find a bot developer, please look at agencies dedicated towards freelancers. An example of those would be https://fiverr.com, which we are not associated with.

**Comment by crypton0** [comment]
👍
