### ISSUE TITLE
[QUESTION] TypeError: __init__() got an unexpected keyword argument 'bot_token'

### ISSUE THREAD

**Issue by Lhassa1912** [python-telegram-bot/python-telegram-bot#3596]
### Issue I am facing

As creating a Telegram bot, I face this issue and I can't find solutions on internet. I tried to fix this with ChatGPT but it couldn't help. I tried with "token" instead of "bot_token" but the error's the same. Thank you for your time and your help :)

### Traceback to the issue

```python
TypeError: __init__() got an unexpected keyword argument 'bot_token'
```

### Related part of your code

```python
updater = Updater(bot_token='MY_TOKEN', use_context=True)
```

### Operating System

Windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.1
Bot API 6.5
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
```

**Comment by harshil21** [comment]
@Lhassa1912 /compat@roolsbot

**Comment by Lhassa1912** [comment]
Sorry, it's the first time I ask something here, I didn't mean to close the question. Thank you for your answer and your ressources. Though after having checked both links, I really can't find how to update the problematic line of code. By CTRL+F "token" I can't find anything related. Could you know how to help me ?
