### ISSUE TITLE
AttributeError: 'ApplicationBuilder' object has no attribute 'dispatcher'[QUESTION]

### ISSUE THREAD

**Issue by Lhassa1912** [python-telegram-bot/python-telegram-bot#3599]
### Issue I am facing

Hi, I think I know my mistake but can't figure how to fix it. I try to code this telegram bot and the said issue keeps coming. I code in python >v20 and I thinl my code is made for previous versions. After checking the transition guide, I still can't find how to update these lines to the modern version of python...

hank you for your time if you can help me !

### Traceback to the issue

```python
AttributeError: 'ApplicationBuilder' object has no attribute 'dispatcher'
```

### Related part of your code

```python
updater.dispatcher.add_handler(CommandHandler('start', start))
updater.dispatcher.add_handler(MessageHandler(~CommandHandler('start'), translate_message))
```

### Operating System

Windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.1
Bot API 6.5
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
@Lhassa1912 Hey. You seem to be using a version &gt;=20.0 of <code>python-telegram-bot</code>  but your code is written for version &lt;=13.15. Please either upgrade your code to  v20 by reading the release notes and the transition guide linked below or install a version of PTB that is compatible with your code base.
Please note that we only provide support for the latest stable version and that the library has undergone significant changes in v20.

**Comment by Lhassa1912** [comment]
Yes that's what I wrote in my message but even with the transition guide (that helped me for a few lines) I can't find the solution to this specific problem, I can't figure out what is the v20 translation

**Comment by Bibo-Joshi** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-20.0#overall-architecture

That part explains that there is no longer a Dispatcher
