### ISSUE TITLE
Better documentation of best practices for error handling

### ISSUE THREAD

**Issue by waltonjones** [python-telegram-bot/python-telegram-bot#36]
It would be useful to add a section to the documentation dealing with error handling. There are certain issues that can lead to errors that may not be immediately obvious.

Example: What happens when a user deletes a chat before the bot has responded? I think it produces a Telegram server error, but what is the best way to deal with this situation safely without crashing the bot.

**Comment by leandrotoledo** [comment]
Thank you for reminding of that!

**Comment by franciscod** [comment]
Yeah, same thing with bot being removed from a group. It might be useful to have an additional higher level bot with error handling, queueing, command handlers...

**Comment by jh0ker** [comment]
@franciscod We are actually working on something like that. Check out the example bot on branch boteventhandler. It's still work in progress though ;)

**Comment by leandrotoledo** [comment]
Related to #135
