### ISSUE TITLE
Installation error with buildout

### ISSUE THREAD

**Issue by spacetekk** [python-telegram-bot/python-telegram-bot#360]
### Steps to reproduce
1. Install python-telegram-bot using buildout

### Expected behaviour
setup.py file must not have implicit dependencies from requirements.txt

### Actual behaviour
As I see, the **setup.py** file contains telegram package import on line 5:

    import telegram

Correct me if I wrong, but it means that all requirements for this package must be already installed. This import is only used to get correct version on line 21:

    version=telegram.__version__,

and when i clone whole repository into src subfolder, remove this import by hardcoding version into setup.py file, everything works like a charm and package installs as develop package without any errors.

### Configuration
Arch Linux

**Version of Python, python-telegram-bot & dependencies:**

python 2.7.12
buildout 2.5.2
python-telegram-bot 5.0.0

### Logs
    ...
    File "/tmp/easy_install-XUjpMi/python-telegram-bot-5.0.0/setup.py", line 5, in <module>
    File "/tmp/easy_install-XUjpMi/python-telegram-bot-5.0.0/telegram/__init__.py", line 44, in <module>
    File "/tmp/easy_install-XUjpMi/python-telegram-bot-5.0.0/telegram/inputfile.py", line 34, in <module>
    ImportError: No module named future.moves.urllib.request
    An error occurred when trying to install python-telegram-bot 5.0.0. Look above this message for any errors that were output by easy_install.
    While:
    Installing python-telegram-bot.
    Getting distribution for 'python-telegram-bot'.
    Error: Couldn't install: python-telegram-bot 5.0.0
    make: *** [config/make/admin.mk:36: /home/stas/nightsearch/.make.buildout] Error 1

**Comment by jh0ker** [comment]
Hello! Thank you for pointing out this issue.

The way I see it, this issue could be solved by placing the version in a separate file called `version.py` with no additional imports, which we could then safely import from both places.

**Comment by spacetekk** [comment]
Hi. Totally agree with you. It is good solution, and it makes possible to use this package with something different than pip+virtualenv.

**Comment by spacetekk** [comment]
Just be aware that you cannot directly import version.py in the setup.py file, cause of \_\_init\_\_.py evaluation. In setup.py it must be imported with some 'indirect' approach. Found a good question on stackoverflow with couple of examples: [http://stackoverflow.com/questions/2058802/how-can-i-get-the-version-defined-in-setup-py-setuptools-in-my-package](http://stackoverflow.com/questions/2058802/how-can-i-get-the-version-defined-in-setup-py-setuptools-in-my-package)

**Comment by jh0ker** [comment]
:)

@tsnoam realized this as well, and @leandrotoledo pointed out this page: https://packaging.python.org/single_source_version/

We decided to go for option 4.

**Comment by jh0ker** [comment]
We (probably) changed our mind and went with the `execfile` solution

**Comment by jh0ker** [comment]
Closing because PR was merged
