### ISSUE TITLE
Error with "add_handler"

### ISSUE THREAD

**Issue by Lhassa1912** [python-telegram-bot/python-telegram-bot#3602]
### Issue I am facing

The mistake might be a version mistake (v13~v20) but I can't find what do I gotta do to fix it. Note that once it will be fixed, I will probably have the same problem with the following line:

**updater.add_handler(translate_message_handler)**

Thank you for your attention and time !

### Traceback to the issue

```python
AttributeError: 'ApplicationBuilder' object has no attribute 'add_handler'
```

### Related part of your code

```python
updater.add_handler(start_handler)
```

### Operating System

Windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.1
Bot API 6.5
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
```

**Comment by Poolitzer** [comment]
Hey, you set updater to `ApplicationBuilder` for some reason, please actually read through the full guide we already linked you to and follow it and/or check out our examples on how to use V20. You probably need to call `.build()`
