### ISSUE TITLE
[BUG] Hard coded upload file size or ?

### ISSUE THREAD

**Issue by TopperBG** [python-telegram-bot/python-telegram-bot#3604]
### Steps to Reproduce

1. Local container with Telegram Bot API
2. PTB 13.9
3. Try to upload to bot file larger than 20Mb (90Mb in fact)

### Expected behaviour

When useing local Telegram bot API running with --local option as described at https://github.com/tdlib/telegram-bot-api
`To enable Bot API features not available at https://api.telegram.org, specify the option --local. In the local mode the Bot API server allows to:`
we should have next abilities:

> Download files without a size limit.
> Upload files up to 2000 MB.

Bot is running sucessfuly connected to http://localhost:8081/bot'bot_token_here'

### Actual behaviour

The error message: File is too big

### Operating System

Linux Ubuntu 20.04 LTS and docker containers

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.9
Bot API 5.5
certifi 2020.06.20
Python 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
```

### Relevant log output

```python
file = context.bot.get_file(file_id)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 2315, in get_file
    result = self._post('getFile', data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: File is too big
```
```


### Additional Context

_No response_

**Comment by Poolitzer** [comment]
Hi, we don't provide support for V13 anymore, we certainly did not hardcode a file limit however.

You need to change the `base_file_url` and serve the files yourself.

**Comment by TopperBG** [comment]
> Hi, we don't provide support for V13 anymore, we certainly did not hardcode a file limit however.
> 
> You need to change the `base_file_url` and serve the files yourself.

I'm sorry for request of PTB 13.
Thanks for the advice, will test it.

**Comment by TopperBG** [comment]
So after litle digging I found hard coded file limite decpite your assurance 
https://github.com/python-telegram-bot/python-telegram-bot/blob/800598ced461189d03868267d628291a9f514a5a/telegram/_bot.py#LL2878C20-L2878C70

>  Use this method to get basic info about a file and prepare it for downloading. For the
>         moment, bots can download files of up to
>         :tg-const:`telegram.constants.FileSizeLimit.FILESIZE_DOWNLOAD` in size. The file can then
>         be e.g. downloaded with :meth:`telegram.File.download_to_drive`. It is guaranteed that
>         the link will be valid for at least 1 hour. When the link expires, a new one can be
>         requested by calling get_file again.

**Comment by TopperBG** [comment]
Understood, so Telegram API should detect local TB API and avoid that checks ...

**Comment by Poolitzer** [comment]
Telegram api doesn't detect, your local bot api instance, if run with the local flag, will download the file and return the file path, the bot api instance (either yours without the local flag or the one(s) telegram provides via api.telegram.org) check the file size and return the file too big error.
