### ISSUE TITLE
[QUESTION] no matches found: python-telegram-bot[job_queue] 

### ISSUE THREAD

**Issue by disonwei** [python-telegram-bot/python-telegram-bot#3614]
### Issue I am facing

 poetry update python-telegram-bot[job_queue]
pip install  python-telegram-bot[job_queue]

no matches found: python-telegram-bot[job_queue] 

### Operating System

mac m2 13.2.1

### Version of Python, python-telegram-bot & dependencies

```shell
python 3.11.1
python-telegram-bot 20.1
```

**Comment by Poolitzer** [comment]
@disonwei Hey, it&#x27;s <code>pip install
Python-telegram-bot [job-queue]</code>, typo on our party, sorry about that.

**Comment by Poolitzer** [comment]
@disonwei Hey, it&#x27;s <code>pip install
Python-telegram-bot[job-queue]</code>, typo on our party, sorry about that.
