### ISSUE TITLE
[BUG] v13.10 Bot.send_message works v20.1 not

### ISSUE THREAD

**Issue by Ciangi** [python-telegram-bot/python-telegram-bot#3615]
### Steps to Reproduce

```
from telegram import Bot

channel_id='-100somechannelid'
bot = Bot('SOMETOKEN')
def try_send_message(channel_id, message, num_tries=5):
    i = 0
    while i < num_tries:
        try:
            bot.send_message(channel_id, message)
        except:
            i += 1
            continue
try_send_message(channel_id, f'''test2''')
```

### Expected behaviour

Bot should send meesage on both library versions

### Actual behaviour

on v13.10 works without problems.
on v20.1 not working

could someone tell me why?

### Operating System

Debian

### Version of Python, python-telegram-bot & dependencies

```shell
v13.10
v20.1
```

**Comment by Bibo-Joshi** [comment]
@Ciangi Hey. You seem to be using a version &gt;=20.0 of <code>python-telegram-bot</code>  but your code is written for version &lt;=13.15. Please either upgrade your code to  v20 by reading the release notes and the transition guide linked below or install a version of PTB that is compatible with your code base.
Please note that we only provide support for the latest stable version and that the library has undergone significant changes in v20.

Hey. In order for someone to be able to help you, you must ask a <b>good technical question</b>. Please read <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Ask-Right">this short article</a> and try again ;)
