### ISSUE TITLE
[BUG] 'int' object is not callable on concurrent_updates

### ISSUE THREAD

**Issue by Eugene-Lam** [python-telegram-bot/python-telegram-bot#3617]
### Issue I am facing

When attempting to call the method "concurrent_updates()" with a parameter of "True" on an instance of the "application" object, a TypeError is raised with the message "'int' object is not callable".

### Traceback to the issue

```python
Traceback (most recent call last):
    File "/usr/src/app/./main.py", line 590, in <module>
        application.concurrent_updates(True)
TypeError: 'int' object is not callable
```

### Related part of your code

```python
application = Application.builder().token(TOKEN).build()
application.concurrent_updates(True)
application.add_handler(xxx)

...


application.run_polling()
```

### Operating System

MacOS via Python Docker image

### Version of Python, python-telegram-bot & dependencies

```shell
FROM python:3.10

python-telegram-bot==20.1
```

**Comment by clot27** [comment]
You have to set concurrent updates before building the Application. like this:
`application = ApplicationBuilder().concurrent_updates(True).token(TOKEN).build()`
