### ISSUE TITLE
Use pytests `--lf` feature to stabalize CI

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#3626]
It rather frequently happens that a handful of tests fail in the CI due to flakyness (even though Harshil always puts admirable effort in trying to stabalize that away :D). Rerunning the failing jobs usually fixes that, but it requires manual work.

Pytest comes with the [`--lf`](https://docs.pytest.org/en/7.2.x/how-to/cache.html) feature, i.e. it allows to re-run only the failing tests. I suggest to make use of featurer in our workflow definition by running `pytest --lf` one (or maybe even twice). For tests failing due to flakyness, this hopefully reduces the number of failing jobs. For tests that fail due to systematic problems, this will not affect the outcome.

**Comment by Ayazcan3333** [comment]
T
