### ISSUE TITLE
Allow to add a certificate on the setwebhook

### ISSUE THREAD

**Issue by Xevib** [python-telegram-bot/python-telegram-bot#363]
The module don't allow to set a webhook with a certificate acording to https://core.telegram.org/bots/api#setwebhook

**Comment by jh0ker** [comment]
It does allow you to that, like this: 
```python
bot.setWebhook('example.com', certificate=open('certificate.pem', 'rb'))
```

**Comment by Xevib** [comment]
@jh0ker Thank you, this should be updated on the documentation https://pythonhosted.org/python-telegram-bot/telegram.bot.html?highlight=setwebhook#telegram.bot.Bot.setWebhook
