### ISSUE TITLE
[QUESTION]    TypeError: __init__() got an unexpected keyword argument 'token'

### ISSUE THREAD

**Issue by raelschiffler** [python-telegram-bot/python-telegram-bot#3641]
### Issue I am facing

Code I'm running:
`    updater = Updater(token=BOT_TOKEN, use_context=True)`
BOT_TOKEN was previously set already.

Due to errors I commented the above line that read:
`#    bot = telegram.Bot(token=BOT_TOKEN)`

Couldn't find this exact error in web search.

### Traceback to the issue

```python
Traceback (most recent call last):
  File "bot.py", line 125, in <module>
    main()
  File "bot.py", line 114, in main
    updater = Updater(token=BOT_TOKEN, use_context=True)
TypeError: __init__() got an unexpected keyword argument 'token'
```

### Related part of your code

```python
BOT_TOKEN = 'PRIVATE'
#    bot = telegram.Bot(token=BOT_TOKEN)
    updater = Updater(token=BOT_TOKEN, use_context=True)
```

### Operating System

Ubuntu 20.04

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.2
Bot API 6.6
Python 3.9.13 (main, Aug 25 2022, 23:26:10)  [GCC 11.2.0]
```

**Comment by clot27** [comment]
@raelschiffler Hey. You seem to be using a version &gt;=20.0 of <code>python-telegram-bot</code>  but your code is written for version &lt;=13.15. Please either upgrade your code to  v20 by reading the release notes and the transition guide linked below or install a version of PTB that is compatible with your code base.
Please note that we only provide support for the latest stable version and that the library has undergone significant changes in v20.

**Comment by raelschiffler** [comment]
Thanks for pointing out the code's version incompatibility.
