### ISSUE TITLE
Am trying to make a telegram bot while executing this error occurred. 

### ISSUE THREAD

**Issue by Nurain313** [python-telegram-bot/python-telegram-bot#3645]
### Issue I am facing

.../0/Telegram-bot $ python /storage/emulated/0/Telegram-bot/nureinbot.py
Traceback (most recent call last):
  File "/storage/emulated/0/Telegram-bot/nureinbot.py", line 28, in <module>
    updater = telegram.ext.Updater(token=os.environ["TELEGRAM_BOT_TOKEN"], use_context=True)
              ^^^^^^^^^^^^
AttributeError: module 'telegram' has no attribute 'ext'
.../0/Telegram-bot $

### Traceback to the issue

```python
Traceback (most recent call last): File "/storage/emulated/0/Telegram-bot/nureinbot.py", line 28, in <module> updater = telegram.ext.Updater(token=os.environ["TELEGRAM_BOT_TOKEN"], use_context=True) ^^^^^^^^^^^^ AttributeError: module 'telegram' has no attribute 'ext'
```

### Related part of your code

```python
def respond(update, context):
    prompt = update.message.text
    response = generate_response(prompt)
    context.bot.send_message(chat_id=update.effective_chat.id, text=response)

if __name__ == '__main__':
    updater = telegram.ext.Updater(token=os.environ["TELEGRAM_BOT_TOKEN"], use_context=True)
    dispatcher = updater.dispatcher
    dispatcher.add_handler(telegram.ext.CommandHandler('start', start))
    dispatcher.add_handler(telegram.ext.MessageHandler(telegram.ext.Filters.text & ~telegram.ext.Filters.command, respond))
    updater.start_polling()
    updater.idle()
```

### Operating System

Android 

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.11.2, 20.2
```

**Comment by Nurain313** [comment]
Am using termux to run the executes

**Comment by Poolitzer** [comment]
Hi, for your issue, have a look at [this FAQ entry](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#why-am-i-getting-importerror-cannot-import-name-xy-from-telegram).

Do also note that you run V13 code on V20, which you will need to [Transition](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-20.0).

**Comment by 1tushr** [comment]
To fix this issue, you can try reinstalling the 'python-telegram-bot' library using the following command:
pip install python-telegram-bot --upgrade


If the issue persists after reinstalling the library, you may need to check that the 'telegram.ext' module is present in the installed version of the library. You can do this by running the following code in the Python interpreter:

import telegram.ext
