### ISSUE TITLE
MessageEntity: text_mention

### ISSUE THREAD

**Issue by niklasdoerfler** [python-telegram-bot/python-telegram-bot#365]
Hey,

I'm trying to implement mentioning users which haven't set up a username. I found the MessageEntity and its property text_mention (-> [https://core.telegram.org/bots/api#messageentity](https://core.telegram.org/bots/api#messageentity)) But it looks like I can't use it with the sendMessage() function. 

I tried it like this:
```
bot.sendMessage(update.message.chat_id, 
				text="Hello Testuser!", 
				entities=[{'length': 8, 'offset': 6, 'type': 'text_mention', 'user': update.message.from_user}])
```

Is this feature going to be implemented soon?

Thanks in advance!
Niklas

**Comment by jh0ker** [comment]
Hello Niklas,
It's not our decision to make, since we only provide a Python wrapper for the official HTTP Bot API.
You'll have to ask the Telegram folks on if/when they're going to implement them.
