### ISSUE TITLE
[QUESTION] iOS does not receive voice in ogg file format, but wav needed

### ISSUE THREAD

**Issue by decayassault** [python-telegram-bot/python-telegram-bot#3651]
### Steps to Reproduce

1. run telegram bot
2. use send_voice with open("filename.ogg", "rb")
3. no message received on IPhone

### Expected behaviour

Automatically provided correct format

### Actual behaviour

No errors

### Operating System

Ubuntu 20

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.2
Bot API 6.6
Python 3.8.10 (default, Mar 13 2023, 10:26:41)  [GCC 9.4.0]
```

**Comment by Poolitzer** [comment]
@decayassault Handling how clients deal with audios is not possible to change with this library. You would need to complain to the iOS developers.

However a successful send call will always result in a message, you can&#x27;t have a situation where a message is only visible on android and not iOS, though your issue title makes it sound like there is :) It just might not appear as a voice note and instead as a document.
