### ISSUE TITLE
[FEATURE] Add methods to ForumTopic

### ISSUE THREAD

**Issue by Trifase** [python-telegram-bot/python-telegram-bot#3653]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

At the moment, `ForumTopic` is just a list of property and it's returned only when using `Bot.create_forum_topic`. Could be useful to add some methods or shortcuts, even if they are only partial because only `message_thread_id` is present.

### Describe the solution you'd like

Some useful methods would be some sort of topic management (close, rename, delete, etc) and the whole `reply_*` suite of shortcuts.

Considering that a `ForumTopic` is only returned when creating a new topic, this has moderate/low usefulness.
I can just think of the use case of posting the "first" message of a forum topic, or maybe editing it.

I also don't know if this has been discussed before.

**Comment by Bibo-Joshi** [comment]
@Trifase Hi. Thanks for the feature request. I vaguely recall having a similar discussion within the dev team when API 6.3 got released 😄

The problem that I see it&#x27;s that the ForumTopic object doesn&#x27;t have a chat_id attribute. All the send_* methods as well as the forum topic methods require a chat_id though. Adding shortcuts is hence not possible without adding additional PTB specific logic to the class. I&#x27;m not a fan of that tbh ...

**Comment by Poolitzer** [comment]
Yes I do remember talking about this.

1. I don't see it as a problem, we have lots of shortcuts where a couple arguments are required to use it, e.g. `chat.copy_message()`. Why not here?

2. TBH, additional PTB specific logic didn't sound too bad to me when thinking about it. We make an extForumTopic, return it when using the ext bot, and all it does is have a chat_id argument which enables the shortcuts to be easier. 99% of users (I assume at least) use ext bot anyway, are none the wiser, and happier that we enable easy shortcuts for them.

**Comment by Bibo-Joshi** [comment]
1. For `Chat.copy_message` we don't have a 1-to-1 mapping of a chat_id to the message_id that should be forwarded. For `ForumTopic` we do. Putting it differently: If `chat_id` is a positional argument of e.g. `ForumTopic.close`, then it would be possible to do something like

    ```python
    forum_topic = bot.create_forum_topic(chat_id=123, name="topic")
    forum_topic.close(chat_id=456)
    ```
    That would be very weird IMO

2. I'm very strongly against duplicating Bot API classes in `tg.ext`. We discussed the overhead of that already in the context of `tg.ext.Defaults` and decided against it.
    The best that I could imagine is something like `ForumTopic.(_){set, get}_chat_id` (analogous to `set/get_bot`).  The downsides of that are IMO

    * additional manual work making sure that all places that return a `ForumTopic` set that attribute (in case more are added in the future)
    * it increases code complexity & mantenance work for a feature that OP themself pointed out has "low usefulness"

**Comment by Bibo-Joshi** [comment]
@harshil21 Can your thumbs up reaction to my comment be understood as "-1 vote" on this feature request?

**Comment by harshil21** [comment]
Yes, I'm against it

**Comment by Bibo-Joshi** [comment]
Okay. I'll close, then … Sorry pool
