### ISSUE TITLE
[BUG] Permission Denied when using download_to_drive() with custom_path

### ISSUE THREAD

**Issue by jasonborn0** [python-telegram-bot/python-telegram-bot#3658]
### Steps to Reproduce

1. custom_path = Path("windows/string/path")
2. photo = await photo_file.download_to_drive(custom_path=custom_path)
3. PermissionError: [Errno 13] Permission denied: 'windows/string/path'

### Expected behaviour

No permission error and download file to provided path

### Actual behaviour

3. PermissionError: [Errno 13] Permission denied: 'windows/string/path'

### Operating System

Windows 11

### Version of Python, python-telegram-bot & dependencies

```shell
python 3.10.10
```

**Comment by Bibo-Joshi** [comment]
Hi. This means that your python processes dies not have the permissions to create/write to that file. This is an issue of giving your python processes the proper access rights and/or removing write restrictions from the target path. PTB has no influence in that.

**Comment by jasonborn0** [comment]
> Hi. This means that your python processes dies not have the permissions to create/write to that file. This is an issue of giving your python processes the proper access rights and/or removing write restrictions from the target path. PTB has no influence in that.

Yes I am aware, however when custom_path is not provided, the process can write to current directory with no issue at all.

**Comment by jasonborn0** [comment]
Nevermind, I was being an idiot. The path I provided was to a folder, not a file name
