### ISSUE TITLE
RegexHandler: error with unicode strings (2.7)

### ISSUE THREAD

**Issue by dontsovcmc** [python-telegram-bot/python-telegram-bot#366]
### Steps to reproduce
1. use RegexHandler:
RegexHandler('^(Обновить)$', refresh_handler)
2. send message with cyrillic characters
3. profit!

### Configuration
Python 2.7

### Logs
Insert logs here (if necessary)

### Soving:
regexhandler.py:
Add .encode('utf-8') if text is unicode instance for match functions
```
if isinstance(update.message.text, unicode):
    match = re.match(self.pattern, update.message.text.encode('utf-8'))
else:
    match = re.match(self.pattern, update.message.text)
```

**Comment by jh0ker** [comment]
Have you tried using a unicode string, like ` RegexHandler(u'^(Обновить)$', refresh_handler)`

**Comment by dontsovcmc** [comment]
Thanks! It's works. 
My previous check failed... Sorry )
