### ISSUE TITLE
Sub-Optiomal type hints in `ConversationHandler`

### ISSUE THREAD

**Issue by klim-neumann** [python-telegram-bot/python-telegram-bot#3665]
### Steps to Reproduce

1. Сreate an instance of the CallbackQueryHandler class
2. Create an instance of the ConversationHandler class with entry_points that contains the instance from the first step

### Expected behaviour

Type checking should pass without errors

### Actual behaviour

Type checking throws an error:

`Argument of type "list[CallbackQueryHandler[DEFAULT_TYPE]]" cannot be assigned to parameter "entry_points" of type "List[BaseHandler[Update, CCT@ConversationHandler]]"`

### Operating System

MacOS 12.6.5

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.2
Bot API 6.6
Python 3.11.2 (main, Apr 15 2023, 18:09:35) [Clang 14.0.0 (clang-1400.0.29.202)]
```

### Additional Context

ConversationHandler entry_points should be `Sequence[BaseHandler[Update, CCT]]` instead of `List[BaseHandler[Update, CCT]]`?

**Comment by Bibo-Joshi** [comment]
Hi. To clarify: This is not about runtime behavior but about sub-optimal type hints, right?

**Comment by klim-neumann** [comment]
yes, that's right.

**Comment by Bibo-Joshi** [comment]
Okay. Thanks for pointing it out. Overhauling CH is a big item on the roadmap.
I'm adding it to the (long) list in #2770 and will close this issue in favor of #2770 :)
