### ISSUE TITLE
Add a method to edit the media and caption at the same time

### ISSUE THREAD

**Issue by AumJavalgikar** [python-telegram-bot/python-telegram-bot#3666]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

When I want to edit the media as well as caption in a message, I have to first use update.effective_message.edit_media() to change the image then update.effective_message.edit_caption() to change the text underneath the image which causes a delay between the image popping up with no text and then a second later the text coming up underneath, please add a caption parameter to edit_media() method so the image and text change at the exact same time.

### Describe the solution you'd like

something like

await update.effective_message.edit_media(media=media, caption=text, reply_markup=reply_markup)

**Comment by Bibo-Joshi** [comment]
The [Bot API](https://core.telegram.org/bots/api) does not offer such functionality. Adding a `caption` parameter to `edit_message_media` on PTBs side could only work if we'd call `edit_message_caption` internally. This neither solves your delay problem, nor is it transparent to the user.

I vote -1.
