### ISSUE TITLE
The bot does not response to some of the creation ways

### ISSUE THREAD

**Issue by tetelevm** [python-telegram-bot/python-telegram-bot#3669]
### Issue I am facing

Hello! I found a strange thing for me. (code below)

I usually run the bot the way `app_2` runs (sorry if that's clumsy :) ). But I decided to put the non-asynchronous things in a separate function like in `app_1`, and the bot stopped responding. In the example below, I moved the building of the bot to a special function, and the bot stopped working.

I found out that the problem happens in `Application._update_fetcher` in the line `update = await self.update_queue.get()`. The problem is that `update` is always successfully queued but never read.

However, the first time it is read normally as long as the queue is not empty (for example, if you timeout before the loop and have time to fill the queue). But when `update_queue.qsize() == 0`, `await` just freezes and is no longer executed, even if the queue fills again.

Since I found the bug and fixed it locally, I don't need any help with that, I'm just interested in why this might be happening? Maybe it has something to do with the asynchronous event loop or something like that?

### Related part of your code

```python
import asyncio
from telegram.ext.filters import ChatType
from telegram.ext import Application, MessageHandler

# vvv

def create_app_1(token: str):
    return Application.builder().token(token).build()

async def run_app_1(app_1: Application):
    app_1.add_handler(MessageHandler(ChatType.PRIVATE, send, block=False))
    await app_1.initialize()
    await app_1.updater.start_polling()
    await app_1.start()
    print("Bot 1 is running!")

async def run_app_2(token: str):
    app_2 = Application.builder().token(token).build()
    app_2.add_handler(MessageHandler(ChatType.PRIVATE, send, block=False))
    await app_2.initialize()
    await app_2.updater.start_polling()
    await app_2.start()
    print("Bot 2 is running!")

# ^^^

async def send(update, context):
    await update.effective_chat.send_message("TEXT")

async def pulling(*coros):
    await asyncio.gather(*coros)
    while True:
        await asyncio.sleep(1)

TOKEN_1 = "123:TOKEN_1"
TOKEN_2 = "321:TOKEN_2"

app_1 = create_app_1(TOKEN_1)
run_coro_1 = run_app_1(app_1)

run_coro_2 = run_app_2(TOKEN_2)

asyncio.run(pulling(run_coro_1, run_coro_2))
```

### Operating System

Ubuntu 20.04

### Version of Python, python-telegram-bot & dependencies

```shell
python3.8
python-telegram-bot==20.2

nothing else :)
```

**Comment by Bibo-Joshi** [comment]
Hi. I tested your example locally and it actually works prefectly fine for me. Both bots are repesonding as expected. However you meantioned "non-asynchronous things" in your description, which I don't really see in the example, so I'm wondering if your actual use case is different. Please double check that you show us an [mwe](../wiki/MWE) that actually includes the problem :)

**Comment by tetelevm** [comment]
Hmm, that's strange. I checked again on a whole new project, and everything works just as I described. I did:
```shell
mkdir test
cd test
python3.8 -m venv env
. ./env/bin/activate
pip3 install python-telegram-bot==20.2
> bot.py
nano bot.py
# here I pasted code from the question and replaced the tokens
python3 bot.py
```
And the bot with token `TOKEN_1` still did not answer me, but with token `TOKEN_2` answered.

**Comment by Bibo-Joshi** [comment]
If it everything works fine in a fresh venv, then tbh it sounds like something is just going wrong in your existing venv …

**Comment by tetelevm** [comment]
But no, on the contrary, the new venv still does not work correctly.

Although, to be honest, given that the problem with the queue work, most likely the problem lies deeper, somewhere in the work of `asyncio`.

I thought that such a problem has already occurred to someone, but if not - that's okay, I was just curious to know why it is so :)

**Comment by Bibo-Joshi** [comment]
Mh, okay. Would you mind testing on python 3.10 or 3.11 again? That's what I have been using …

**Comment by tetelevm** [comment]
Yes, I was going to do that myself, but I've been busy.
I tested on versions `Python3.8-12`, and it doesn't work on versions `3.8` and `3.9`, but it works fine on `3.10`, `3.11` and `3.12`.

**Comment by Bibo-Joshi** [comment]
I double checked as well. The hint can be seen when stopping the script with CLTR+C: on py 3.9- you'll see a line saying "…  got Future <Future pending> attached to a different loop".

TBH I'm not entirely sure on all the details, but from what I understand, the problem is the following: `run_app_2` creates *and* runs the app_2, but the creation happens only once you actually `await` the coroutine. That happens inside `pulling`, i.e. inside `asyncio.run` such that `app_2` is created only once the event loop used by `asyncio.run` is already in place.
On the other hand, `app_1` is created *outside* of `asyncio.run_polling`, where the event loop used by `asyncio.run` is not yet set.

This behavior [has been improved in python 3.10](https://stackoverflow.com/questions/55918048/asyncio-semaphore-runtimeerror-task-got-future-attached-to-a-different-loop/55918049#55918049) and hence your code works in py 3.10+.
Unfortunately, I don't think that PTB can reasonably improve this for the user …

**Comment by tetelevm** [comment]
Thank you so much, got it!
