### ISSUE TITLE
[QUESTION] Import error

### ISSUE THREAD

**Issue by lupo35214** [python-telegram-bot/python-telegram-bot#3677]
### Issue I am facing

I can't import telegram.ext to my python program after installing python-telegram-bot.

### Operating System

Mac OS Big Sur

### Version of Python, python-telegram-bot & dependencies

```shell
python 3.11
python-telegram-bot 20.2
pip 3
```

**Comment by clot27** [comment]
Wdym by "can't import"? what error you are facing?
