### ISSUE TITLE
[QUESTION] The problem of locking the bot until a concurrent function is performed

### ISSUE THREAD

**Issue by masoudnick** [python-telegram-bot/python-telegram-bot#3689]
### Issue I am facing

Hi, My bot has a section to send messages to all users. When the message sending process starts, the bot is locked until all messages are sent (It takes about 20 minutes). While I use `Application.create_task` function and concurrency technique to send messages.
What should I do to solve this problem?

### Related part of your code

`
context.application.create_task(
        asyncio.gather(
            *(
                context.bot.send_message(
                    chat_id=user_id, text="Hello World!", rate_limit_args={'priority': -1}
                )
                for user_id in user_ids
            )
        )
    )
`

### Operating System

ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
python v3.10
python-telegram-bot v20.2
aiolimiter v1.0.0
```

**Comment by masoudnick** [comment]
@Bibo-Joshi 
Thanks for your quick reply :)
This is the piece of code that I use to send messages to users. [https://hastebin.com/share/gutilezela.rust](url)
And unfortunately, I have to send the message to each user :(

**Comment by Bibo-Joshi** [comment]
Unfortunately this is not an MWE. I'm afraid that I can't really help you without seeing one. Please re-read the wiki page that I linked above. 

> And unfortunately, I have to send the message to each user :(

What I meant was that *for demonstration purposes* the MWE doesn't have to send messages to a lot of different users.

**Comment by masoudnick** [comment]
@Bibo-Joshi 
Hi again, 
Here you are, My [MWE](https://hastebin.com/share/zosujiyulo.rust)
When sending messages, if you press the `/start` command (or other commands), the bot will not respond until all messages are sent.
I hope you can help me by seeing this MWE.

**Comment by masoudnick** [comment]
> @Bibo-Joshi Hi again, Here you are, My [MWE](https://hastebin.com/share/zosujiyulo.rust) When sending messages, if you press the `/start` command (or other commands), the bot will not respond until all messages are sent. I hope you can help me by seeing this MWE.

For example, as per the screenshot below, I have sent an image as a message at 7:11 PM. While sending the message, I also sent two commands, /start and help, but the bot responded one minute later (after sending the message to all users).
![Capture](https://user-images.githubusercontent.com/20556982/236276378-97ac10ff-6f1e-4d5a-9f45-0d29c0222f86.jpg)

**Comment by masoudnick** [comment]
@Bibo-Joshi 
Thank you very much for your help
So you suggest I use another rate limiter instead of `AIORateLimiter` that has the ability to create multiple queues? 
If you know a good one, introduce me?
If someone has already solved this problem, please tell me the solution of that person.

**Comment by Bibo-Joshi** [comment]
My main intention was to explain why the use of `create_task` and/or `AIRateLimiter` does not solve your problem.
A more sophisticated `BaseRateLimiter` implementation would be one solution, yes. However, I'm not aware of any other implementation apart from `AIORateLimiter` so far. Note that this rate limiting mechanism of PTB is available only since v20.0a3.
Another option would be to put manualy delays between the broadcasting messages, e.g. using PTBs `JobQueue`.

**Comment by masoudnick** [comment]
Ok, thanks for your help, good luck :)
