### ISSUE TITLE
[QUESTION] concurrent_updates set to true, but no concurrency

### ISSUE THREAD

**Issue by GeiserX** [python-telegram-bot/python-telegram-bot#3696]
### Issue I am facing

After following the docs, I decided to add concurrency globally to my bot:

```python
...
def main() -> None:
    application = Application.builder().token(os.environ["TOKEN"]).concurrent_updates(True).build()
    application.add_handler(CommandHandler("sleep", sleep)) # sleep 1min
    application.add_handler(CommandHandler("echo", echo)) # echo the message
...
```

However, while one user executes the `sleep` command, another user cannot see the `echo`, not until the first `sleep` trigger is completed. I understood it creates a task to be handled in the background, but after some checks I don't see any concurrency here. Am I doing something wrong?

PS. This also happened in PTB 20.2, as I upgraded just to see if the error faded away.

### Operating System

Debian

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.3
Bot API 6.7
Python 3.11.3 (main, May  3 2023, 08:39:36) [GCC 8.3.0]
```

**Comment by Bibo-Joshi** [comment]
@GeiserX Hey. Please provide a minimal working example (MWE). Have a look at <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/MWE">Minimal Working Example (MWE)</a> if you need help.

**Comment by harshil21** [comment]
You should use block=False in the handler and also make sure to use `asyncio.sleep` instead of `time.sleep`

**Comment by GeiserX** [comment]
Hi @harshil21 , thanks for the tips.
I'm trying it this way now:
```python
    ...
    application.add_handler(CommandHandler("url_select", select_url, block = False))
    ...
```
However, if I try to execute the same command from another phone, it's waiting for the first task to finish to begin the second one.
Should I consider anything else?

**Comment by harshil21** [comment]
It depends on the task. If the task itself is blocking, then PTB can't really help you. You can use asyncio.to_thread to run blocking tasks in another thread
