### ISSUE TITLE
telegram.error.BadRequest: u'Bad Request: chat not found'

### ISSUE THREAD

**Issue by cyphre672** [python-telegram-bot/python-telegram-bot#370]
pi@raspberrypi:~ $ sudo python2.7 homesecurity.py
GPIO pin 4 is HIGH
Detected Activity
--- Opening /dev/video0...
Trying source module v4l2...
/dev/video0 opened.
No input was specified, using the first.
Adjusting resolution from 384x288 to 352x288.
--- Capturing frame...
Captured frame in 0.00 seconds.
--- Processing captured image...
Writing JPEG image to 'image.jpg'.
Traceback (most recent call last):
  File "homesecurity.py", line 34, in <module>
    bot.sendMessage(chat_id=chat_id, text="Some activity detected for the past 5 seconds!")
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 121, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 147, in decorator
    result = request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 235, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 180, in _request_wrapper
    raise BadRequest(repr(message))
telegram.error.BadRequest: u'Bad Request: chat not found'

### Steps to reproduce
1. 

2.

3.

### Expected behaviour
I connected a PIR to GPIO 4. When activated it should use fswebcam to take a picture.
This picture then should be send to my mobile device by the use of telegram bot

### Actual behaviour
The picture is succesfully made on but the sending is not happening

### Configuration
RPI3 on jessie (latest upgrade)
Linux raspberrypi 4.4.13-v7+ 

**Version of Python, python-telegram-bot & dependencies:**

python-telegram-bot 5.0.0
urllib3 1.16
certifi 2016.08.02
future 0.15.2
Python 2.7.9 (default, Mar  8 2015, 00:52:26)  [GCC 4.9.2]

I will paste the source hereunder in the hope anyone can take a look and can push me a bit in the right direction:

########################
# Shazin Sadakath      #
#######################

import RPi.GPIO as GPIO
import time
import telegram
from subprocess import call

sensor = 4

GPIO.setmode(GPIO.BCM)
GPIO.setup(sensor, GPIO.IN, GPIO.PUD_DOWN)

previous_state = False
current_state = False

chat_id = -1 
token = "MYTOKENISFILLEDINHERE"

bot = telegram.Bot(token=token)

while True:
	time.sleep(5)
	previous_state = current_state
	current_state = GPIO.input(sensor)
	#print("Current State : %s" % current_state)
	if current_state != previous_state:
		new_state = "HIGH" if current_state else "LOW"
		print("GPIO pin %s is %s" % (sensor, new_state))
		if new_state == "HIGH":
			print("Detected Activity")
			call(["fswebcam", "image.jpg"])
			bot.sendMessage(chat_id=chat_id, text="Some activity detected for the past 5 seconds!")
bot.sendPhoto(chat_id=chat_id, photo=open("/home/pi/image.jpg"))

**Comment by jh0ker** [comment]
Hi!
Two things here: 

1. You have the wrong `chat_id` (`chat_id = -1 `) You can use [userinfobot](https://telegram.me/userinfobot) to find out your user ID and then use that as the chat ID
2. To send a photo from a file, use `open("/home/pi/image.jpg", "rb")` so it will **r**ead in **b**inary mode

**Comment by cyphre672** [comment]
Hey ! thanks a lot for your respons, very exited to make this work. WIll try it tomorrow after work :). Thanks again

**Comment by jh0ker** [comment]
Great :) If you have further questions, I recommend you join our Telegram group: https://telegram.me/pythontelegrambotgroup

**Comment by cyphre672** [comment]
Hi, i am now succesfully receiving the notification initiated by the gpio 4 pin. Also the pic is been maded by fswebcam. Its just not sending it still, i did add the rb at the end like you suggested.

last 2 lines are now:

bot.sendMessage(chat_id=chat_id, text="Some activity detected for the past 5 seconds!")
bot.sendPhoto(chat_id=chat_id, photo=open("/home/pi/image.jpg", "rb"))

In the pythontelegrambotgroup channel i get no respons, people are talking a lot and i think my message has not been seen. Thought id ask here again :)

Greetings,

**Comment by jh0ker** [comment]
So you get the test message "Some activity detected for the past 5 seconds!", but not the photo afterwards?

**Comment by cyphre672** [comment]
correct. i did get some help in the channel yesterday and in respond i upped some debug info. i think it didnt show anything usefull.

I wil try again in an hour or so and was reading about changing the open() to file() someone talked about the string not being formatted to utf8, guess i try an alternative...

Do you have some further ideas maybe ? 

Regards

**Comment by jh0ker** [comment]
What error message do you get with the current code? Please provide the full error stack.

**Comment by cyphre672** [comment]
http://hastebin.com/ujuhogemit.py

**Comment by cyphre672** [comment]
It looks like its ignoring the whole bottom line, when i adjust the line from: 

bot.sendPhoto(chat_id=chat_id, photo=open("/home/pi/image.jpg", "rb")) to
 -> bot.sendPhoto(chat_id, image.jpg) , the result is exactly the same

**Comment by cyphre672** [comment]
changed the unicode to UTF-8 but this changed nothing.

used different folders but no difference also

**Comment by leandrotoledo** [comment]
@cyphre672 sorry, what you changed to UTF-8 and how? Would you paste the code and upload the image somewhere?

**Comment by cyphre672** [comment]
The complete sourcefile, in the interpreter i have it this option, its called: JetBrains PyCharm Community Edition 2016.2 .. well the source is here (i obscured the token)

http://hastebin.com/fusamutawa.hs

Hope you can see something :)

**Comment by leandrotoledo** [comment]
@cyphre672 what's the output of 
```
$ file /home/pi/image.jpg
```

**Comment by jh0ker** [comment]
Uhh in the file you posted, it looks like the `sendPhoto` line is outside the whole `while` loop

**Comment by cyphre672** [comment]
@leandrotoledo : i dont exactly know what you mean but there is no respns on this last line, its like its ignored.

@jh0ker: I will look into how to place this last line into the while loop :) its not clear to me now but ill find out, thanks for now :)

**Comment by cyphre672** [comment]
@leandrotoledo I think you mean this:

/home/pi/image.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 96x96, segment length 16, comment: "CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), quality = 255", baseline, precision 8, 352x288, frames 3

**Comment by leandrotoledo** [comment]
@cyphre672 Please run this minimal code

```
import telegram

chat_id = 253935990
token = "TOKEN"

bot = telegram.Bot(token=token)
bot.sendPhoto(chat_id=chat_id, photo=open("/home/pi/image.jpg", "rb"))
```

**Comment by cyphre672** [comment]
This IS working, indeed :)

**Comment by leandrotoledo** [comment]
@cyphre672 cool, so as @jh0ker pointed out, your ```bot.sendPhoto()``` is outside the loop, that's the reason it never got to be sent. I'll resolve this issue but feel free to reopen if further assistance is needed.
