### ISSUE TITLE
[QUESTION] How to push something to bot

### ISSUE THREAD

**Issue by springjools** [python-telegram-bot/python-telegram-bot#371]
I read the wiki and the manuals, but I didn't find this exactly covered.

I know you can set up handlers that make the telegram bot respond afetr the user does something with it. But how to push information to the bot? Specifically, how to get access to the "bot" object? It's always included in the handlers, such as "def start(bot, update):"

I know that bots cannot initiate messages to users, but I already have the chat_id:s saved in a database (of people that want updates)

Hope this is relevant and also benefits other people...

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
python-telegram-bot 5.0.0
urllib3 1.9.1
certifi 2016.08.08
future 0.15.2
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
### Logs
Insert logs here (if necessary)

**Comment by jh0ker** [comment]
Hello.
You could either use the `JobQueue` that the `Updater` creates for you, like::

```python
u = Updater(token)
j = u.job_queue
j.put(some_job)
```
(wiki link here: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-JobQueue)

Alternatively, you can simply make a `telegram.Bot` instance on its own, and use it withouth the `telegram.ext` framework.

**Comment by springjools** [comment]
Thanks. I simply ended up doing:
bot = telegram.bot.Bot("TOKEN"), so then it was easy to send messages to it. Didn't know it that simple.

**Comment by jh0ker** [comment]
Sweet
