### ISSUE TITLE
A new way to restart the bot under v20

### ISSUE THREAD

**Issue by harshil21** [python-telegram-bot/python-telegram-bot#3718]
In v13, we had a simple code snippet we could use to restart the bot (https://github.com/python-telegram-bot/v13.x-wiki/wiki/Code-snippets#simple-way-of-restarting-the-bot), which restarted the whole script passing in any arguments. However simply adapting that to v20 this doesn't work since:

1. threading and asyncio don't play well together
2. the application methods (`stop`, `shutdown`, `app.updater.shutdown`) all need to be awaited instead of simply called
3. something more I didn't see at first glance

If anyone has figured out a simple way to restart the whole script (e.g. by sending a command to a bot), feel free to propose your solution below!

**Comment by Trifase** [comment]
The solution I'm implementing in my v20 bot is fairly primitive but it works well.
It uses another python scripts that launches the main.py file, and if for some reasons this process closes, the script restart it again.
This is the launching script, `launch_bot.py` that uses `subprocess.call` to start `main.py`.
```
# launch_bot.py
import subprocess
import time
 
while True:
    subprocess.call(["python", "main.py"])
    time.sleep(0.1)
```

and this is the bot itself, `main.py`. When I need to restart it, I raise `SystemExit()`, it gracefully exits and `launch_bot.py` restarts it again.

```
# main.py
from telegram import Update
from telegram.ext import ApplicationBuilder, CallbackContext, CommandHandler, ContextTypes
 
BOT_TOKEN = 'my_token'
 
async def restart(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text('See you soon!')
    raise SystemExit()
 
def main():
    builder = ApplicationBuilder()
    builder.token(BOT_TOKEN)
    app = builder.build()
    app.add_handler(CommandHandler('restart', restart))
    app.run_polling()
 
if __name__ == "__main__":
    main()
 ```

**Comment by lemontree210** [comment]
My solution would be to just recommend running the bot as a systemd service in production. It can be set up so as to restart the service every time it fails. I kind of see it as a general problem and a general solution, unrelated to the specifics of PTB, and the solution by @Trifase would also work with any script, not just our bot.

**Comment by Bibo-Joshi** [comment]
@lemontree210 auto-restarting the bot if it fails is one thing. Restarting it from within the code is more complictade though …

@Trifase can you paste the output of running `python -m telegram` on the setup that works for you? It.s not working for me.

In fact, I also know *why* it's not working: Raising `SystemExit` currently prevents `application.update_queue.task_done()` from being called. Now, `application.stop()` waits for `await application.update_queue.join()`, which never happens because the interrupted update processing makes the queue never be empty. A rather simple `try-finally` does help a bit, but doesn't quite cut it, because the exception also makes the background task crash that fetches the updates. This is a problem, becaues `application.stop` also inserts a special stop signal into the `update_queue` that usually tells the background task to shut down. This ofc doesn't happen, which again prevents `await application.update_queue.join()` from finishing.

I guess some research is in order on how `(Base)Exceptions` are propagated from within `asyncio.Tasks` to the main loop.
Apart from raising a `BaseException`, there may also be other ways of providing the user with a nice way of shutting the application down. The main issue is this kind of recursion, i.e. `application.stop()` waiting for the callbacks to finish, while we want to stop the application from within the callbacks.

**Comment by lemontree210** [comment]
> @lemontree210 auto-restarting the bot if it fails is one thing. Restarting it from within the code is more complictade though …

How about using something like [psystemd](https://github.com/systemd/pystemd) to restart the application that is running as a systemd service?

**Comment by Bibo-Joshi** [comment]
Does that allow you to trigger a graceful shutdown from within a callback and then restart the program?

**Comment by lemontree210** [comment]
> Does that allow you to trigger a graceful shutdown from within a callback and then restart the program?

`pystemd` docs say that the library allows executing commands equivalent to `sudo systemctl restart <service>`, which I'm pretty sure handles things correctly as it's used to restart things like nginx and gunicorn. But of course, this has to be tested to be sure. Maybe I have to create a simple example and then, say, try to `logger.info()` some message in a method that is supposed to be called at application shutdown?

**Comment by DDF95** [comment]
I use this:

```
async def restart_bot(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("Restarting...")
    args = sys.argv[:]
    args.insert(0, sys.executable)
    os.chdir(os.getcwd())
    os.execv(sys.executable, args)
```

**Comment by Bibo-Joshi** [comment]
Finally got around to have a closer look at my findings from https://github.com/python-telegram-bot/python-telegram-bot/issues/3718#issuecomment-1575624571. By having a look at the source of `run_*`

https://github.com/python-telegram-bot/python-telegram-bot/blob/59105b240fdca81b881539dd55f37097a1ccc0a5/telegram/ext/_application.py#L935-L940

and then cross-checking with the [python docs](https://docs.python.org/3/library/asyncio-eventloop.html?highlight=run_forever#asyncio.loop.run_forever)

> loop.run_forever()
> Run the event loop until [stop()](https://docs.python.org/3/library/asyncio-eventloop.html?highlight=run_forever#asyncio.loop.stop) is called.
> 
> If [stop()](https://docs.python.org/3/library/asyncio-eventloop.html?highlight=run_forever#asyncio.loop.stop) is called before [run_forever()](https://docs.python.org/3/library/asyncio-eventloop.html?highlight=run_forever#asyncio.loop.run_forever) is called, the loop will poll the I/O selector once with a timeout of zero, run all callbacks scheduled in response to I/O events (and those that were already scheduled), and then exit.
> 
> If [stop()](https://docs.python.org/3/library/asyncio-eventloop.html?highlight=run_forever#asyncio.loop.stop) is called while [run_forever()](https://docs.python.org/3/library/asyncio-eventloop.html?highlight=run_forever#asyncio.loop.run_forever) is running, the loop will run the current batch of callbacks and then exit. Note that new callbacks scheduled by callbacks will not run in this case; instead, they will run the next time [run_forever()](https://docs.python.org/3/library/asyncio-eventloop.html?highlight=run_forever#asyncio.loop.run_forever) or [run_until_complete()](https://docs.python.org/3/library/asyncio-eventloop.html?highlight=run_forever#asyncio.loop.run_until_complete) is called.

this becomes a bit of a case of RTFM 😄 . I proposed a method of stopping the application from within callbacks in #3804. Once that is possible, restarting the script after it has finished can be done by generic (i.e. non-ptb-specific) means like systemd or `os.execv`.

**Comment by Trifase** [comment]
I still don't get why it works for me.

**Comment by Bibo-Joshi** [comment]
v20.5 introduced [`Application.stop_running`](https://docs.python-telegram-bot.org/en/stable/telegram.ext.application.html#telegram.ext.Application.stop_running) and I just added a [code snippet based on that](../wiki/Code-snippets#simple-way-of-restarting-the-bot). Closing.
