### ISSUE TITLE
[QUESTION] Is it possible to get the chat id in the main func and pass it to the job queue context

### ISSUE THREAD

**Issue by aromanchev** [python-telegram-bot/python-telegram-bot#3720]
### Issue I am facing

I want my scheduled tasks to work without sending any commands, it starts working as soon as it starts, is there any way to get the chat id in the main func

### Related part of your code

```python
async def scheduled_func(context: ContextTypes.DEFAULT_TYPE) -> None:
    job = context.job
    await context.bot.send_message(chat_id=job.chat_id, text=f'scheduled msg')

def main() -> None:
    application.add_error_handler(error_handler)
    application.add_handler(CommandHandler(["start"], start))
    application.job_queue.run_repeating(scheduled_func, interval=300, chat_id=chat_id)?
    application.run_polling()
```

### Operating System

MacOS

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot=20.3
python=3.9.9
```

**Comment by clot27** [comment]
Passing `chat_id` param to `job_queue.run_*` gives you access to `chat_data` in corresponding callback, you have to have `chat_id` somehow in the main function already in order to pass it ofc.

**Comment by aromanchev** [comment]
@clot27 any suggestions on how this could be done?

**Comment by clot27** [comment]
@aromanchev explain &quot;this&quot;

**Comment by aromanchev** [comment]
@clot27 how i can get the chat_id, i don't understand, can you send please example of code snippet

**Comment by clot27** [comment]
@aromanchev you are not recieving any update in `main` to get `chat_id` from. So you have to have it either hardcoded or stored in some db. You can get chat id via [telegram.Chat.id ](https://docs.python-telegram-bot.org/telegram.chat.html#telegram.Chat.id).

**Comment by aromanchev** [comment]
@clot27 got it thanks
