### ISSUE TITLE
Explicitly set `allowed_updates` in examples

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#3726]
Every now and then we get questions on why our examples (or custom user code) isn't receiving any updates and in many of these cases it turns of that the `allowed_updates` were not configured correctly. To avoid these problems at least with our examples, we should explicitly pass `allowed_updates=Update.ALL_TYPES` to `run_polling`, `get_updates`, `run_webhook` and `set_webhook` in our [examples](https://github.com/python-telegram-bot/python-telegram-bot/tree/master/examples).

A PR that addresses this would be very welcome. It should cover all examples.

**Comment by Trifase** [comment]
I can do it. 

Do I need to do it in every example or only in those who uses non-default updates, like `chatmemberbot.py`?

**Comment by Poolitzer** [comment]
@Trifase Please in every, since people can by accident set a different type previously and if we don&#x27;t override it, the examples don&#x27;t work

**Comment by Trifase** [comment]
@Poolitzer No problem, will make a PR probably tomorrow

**Comment by harshil21** [comment]
Closed by #3741
