### ISSUE TITLE
[QUESTION] Unable to receive and process chat_join_request event

### ISSUE THREAD

**Issue by DaLian369** [python-telegram-bot/python-telegram-bot#3727]
### Issue I am facing

I encountered a problem when developing a Telegram bot using the Telegram Bot API. The bot cannot receive the `join_chat_request` event, so it cannot detect new member join group requests.
I use `application.add_handler(MessageHandler(filters.ALL, echo))` to see that there is no `chat_join_request` field in the update structure.

Although I have specified the join_chat_request event in allowed_updates and added the corresponding event handler using ChatJoinRequestHandler, the bot still cannot receive new member join group request events. There is also no relevant debug information in the logs. 
It is likely that I have made some mistakes in the code or configuration. If there are any confirmed solutions to this issue, please point out the relevant errors to help me solve this problem. 
Thank you very much for taking the time to read my issue, and I look forward to your reply!

### Related part of your code

```python
import logging
from telegram import Update
from telegram.ext import ApplicationBuilder, ChatJoinRequestHandler, MessageHandler, ContextTypes, filters
import telegram

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)

async def echo(update: Update, context: ContextTypes.DEFAULT_TYPE):
    print(update.chat_member)
    print(update.my_chat_member)
    print(update.chat_join_request)
    logging.info("echo update: %s\n ", update)

async def join(update: Update, context: ContextTypes.DEFAULT_TYPE):
    print("join", update)

TOKEN = ''

if __name__ == '__main__':
    default_bot = telegram.Bot(TOKEN)
    application = ApplicationBuilder().bot(default_bot).build()
    # application.add_handler(MessageHandler(filters.ALL, echo))
    application.add_handler(ChatJoinRequestHandler(join))
    application.run_polling(allowed_updates=Update.ALL_TYPES)
```

### Operating System

macOS 12.2 (21D49)

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.3
Bot API 6.7
Python 3.8.9 (default, Jul 19 2021, 09:37:32)  [Clang 13.0.0 (clang-1300.0.27.3)]
```

**Comment by Bibo-Joshi** [comment]
> The bot must have the `can_invite_users` administrator right in the chat to receive these updates.

Please double check if this is the case.

**Comment by DaLian369** [comment]
> > The bot must have the `can_invite_users` administrator right in the chat to receive these updates.
> 
> Please double check if this is the case.

the bot has this permission.

**Comment by Bibo-Joshi** [comment]
@DaLian369 Invite links don&#x27;t trigger join requests.

**Comment by DaLian369** [comment]
> @DaLian369邀请链接不会触发加入请求。

how should i test

**Comment by DaLian369** [comment]
<img width="835" alt="image" src="https://github.com/python-telegram-bot/python-telegram-bot/assets/46351234/28b0781f-19c5-4d74-bb7c-fc4c78a3d530">

**Comment by Bibo-Joshi** [comment]
Ah, my bad. For invite links, this only works if you configured that the invite link requires join requests as described [here](https://telegram.org/blog/shared-media-scrolling-calendar-join-requests-and-more?ln=r#join-requests-for-groups-and-channels). IISC that only works for private groups. In this setting your example still works fine for me.
