### ISSUE TITLE
Adopt Py3.8+ features: Logging Stacklevel

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#3729]
Python 3.8 adds a `stacklevel` argument to the methods of the [`Logger`](https://docs.python.org/3/library/logging.html#logging.Logger) class. This allows to be more precise about where the resulting log line should point to in order to be helpful for the user.
We should

* review all usages of `Logger.{debug, info, warning, exception, …}` in our code base and check if we can use the new parameter to our/the users advantage
* improve the test suite, i.e. every test that uses the `caplog` fixture, to assert that the log entry is issued at the stacklevel that we expect it to

A PR in this direction is very welcome. As long as #3728 is open, it should be based on the `drop-py-37` branch. A PR can probably take a lot of inspiration from #3674 which did similar things for the `warnings`. If you would like to send a PR, please be sure to read our [contribution guide](https://docs.python-telegram-bot.org/en/stable/contributing.html) and leave a short comment so that we can assign you.

**Comment by thefunkycat** [comment]
I would like to work on this. I glanced over #3674 and I have some questions, so some guidance/background would be appreciated. Is there a discord server for the bot development that I could join btw? 

- How exactly are we assigning stacklevel? Is this arbitrary or are we getting the stack level from the stack trace? I saw a method for incrementing the stack level too (by one and by two (?)), which leads me to believe it's arbitrary, but not sure. 
- Also which level indicates what (related to the previous question)
- Just a general explanation of the approach would be helpful :)

**Comment by Poolitzer** [comment]
@thefunkycat Not in a position to answer your other questions right now, but we do have a Telegram group for development on PTB: https://t.me/pythontelegrambotdev

**Comment by lemontree210** [comment]
Hey @thefunkycat ! My answer may not be 100% exhaustive, but at least I hope it isn't wrong :) It'll check my own understanding of stack level one more time.

`stacklevel` indicates how "deep" we are in the calling stack. It lets the user know where exactly the warning is coming from. Each call of a function or method increases `stacklevel` by `1`. When we create warnings for `Bot` methods, we know how "deep" in the stack these methods are and put exact `stacklevel` values. 

Then, when we're using an auxiliary function in `warnings.py` to issue the warning itself, we have to increment `stacklevel` once again.

When some warning is triggered in `ExtBot`, which is built "on top of" `Bot` and hence calls `Bot` methods, we need to increment `stacklevel` further by another `1`.

**Comment by lemontree210** [comment]
As far as the introduction of `stacklevel` for loggers is concerned, I'm not sure `stacklevel` is required here, or if it is, maybe in few places. Maybe the idea is to change the class being logged e.g. for a `_LOGGER.exception` in `AIORateLimiter.process_request()` from `AIORateLimiter` to `ExtBot`?

**Comment by Bibo-Joshi** [comment]
TBH I don't have a clear idea about where that will be beneficial and I haven't tried that feature out so far. The description of this issue is really meant to be open into he result. If it turns out that there is no benefit of using the stack level, I'm fine with that.

**Comment by lemontree210** [comment]
I looked at it again, and I think that `telegram._utils.logging.get_logger()` function already makes the `stacklevel` unnecessary because it shows the user the prettified name of the class from which the message originates. And my impression is that `logger....` statements are put exactly in those classes whose names we want the user to see.

Unless we want our logging to become more specific and return method names as well. Then another look into this will be warranted.

**Comment by lemontree210** [comment]
On second (third?) thought, maybe `stacklevel` could be useful for debug calls like this one...
```py
        if result:
            self._LOGGER.debug("Getting updates: %s", [u["update_id"] for u in result])
        else:
            self._LOGGER.debug("No new updates found.")
```
...if it is important to know, in this case, who exactly called `Bot.get_updates()`

However, for this to be useful, I think that either this customized logger should be tweaked, or a standard `logging.getLogger()` should be used for debugging calls.

**Comment by Bibo-Joshi** [comment]
The `get_updates` use case sounds very good to me! Would you like to investigate the possibilities here? Otherwise, I guess I agree with your previous message :)

**Comment by lemontree210** [comment]
> The `get_updates` use case sounds very good to me! Would you like to investigate the possibilities here? Otherwise, I guess I agree with your previous message :)

I have found only one place with `Bot.get_updates()` where stacklevel could be useful, and I have doubts even about that only place too.

```py
        async def polling_action_cb() -> bool:
            try:
                updates = await self.bot.get_updates(
                    offset=self._last_update_id,
                    timeout=timeout,
                    read_timeout=read_timeout,
                    connect_timeout=connect_timeout,
                    write_timeout=write_timeout,
                    pool_timeout=pool_timeout,
                    allowed_updates=allowed_updates,
                )
```

It gives following output in the log (note the last line):

```2023-06-28 01:39:08,179 - telegram.ext._updater - DEBUG - Bootstrap done
2023-06-28 01:39:08,179 - telegram.ext._updater - DEBUG - Waiting for polling to start
2023-06-28 01:39:08,179 - telegram.ext._updater - DEBUG - Polling updates from Telegram started
2023-06-28 01:39:08,179 - telegram.ext._updater - DEBUG - Start network loop retry getting Updates
2023-06-28 01:39:08,179 - telegram._bot - DEBUG - Entering: get_updates
```
I'm not sure whether it's worth the hassle to introduce `stacklevel` only for this line to say `._updater` instead of `._bot`.

**Comment by Bibo-Joshi** [comment]
Given that there is even a log line from the updater stating that it's fetching updates again, you are probably right. Let's close this as won't do, then :). Thnaks for taking the time for the investiation!
