### ISSUE TITLE
dispatcher threads not terminated

### ISSUE THREAD

**Issue by macrojames** [python-telegram-bot/python-telegram-bot#374]
My Flask application with python-telegram-bot does not terminate after CTRL-C.
Maybe I am doing something wrong, but i think the telegram.ext.dispatcher does not work how it should.

### Steps to reproduce
Short:
```python
    updater = Updater(TOKEN)
    updater.dispatcher.add_handler(CommandHandler('start', tg_start))
    updater.dispatcher.add_handler(CommandHandler('toggle', tg_toggle, pass_args=True))
    app.run(threaded=True, use_reloader=False, debug=DEBUG, host='0.0.0.0')
    log.debug("Stopping...")
    updater.dispatcher.stop()
```
Full (requires Flask)

[bug.py.txt](https://github.com/python-telegram-bot/python-telegram-bot/files/411030/bug.py.txt)

I left out the message and command handling as that was not neccesary to reproduce the bug.
I am doing that in a webhook handler:
``` python 
        update = telegram.Update.de_json(request.get_json(force=True))
        try:
            updater.dispatcher.process_update(update)
        except Exception as e:
            log.error(e)
```
And command processing works so far.

### Expected behaviour
After CTRL+C Flask is stopping, and the dispatcher stops all threads and programm terminates.

### Actual behaviour
dispatcher threads keep alive, exit pending forever

### Configuration
Ubuntu 15.10, Python 2.7.10

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
    python-telegram-bot 5.0.0
    urllib3 1.11
    certifi 2016.08.08
    future 0.15.2
    Python 2.7.10 (default, Oct 14 2015, 16:09:02)  [GCC 5.2.1 20151010]

### Logs
[log.txt](https://github.com/python-telegram-bot/python-telegram-bot/files/411037/log.txt)

contains references like 
```
  File "/usr/local/lib/python2.7/dist-packages/telegram/ext/dispatcher.py", line 49, in _pooled
    promise = ASYNC_QUEUE.get()
  File "/usr/lib/python2.7/Queue.py", line 168, in get
    self.not_empty.wait()
  File "/usr/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
```

**Comment by jh0ker** [comment]
I think the problem is that you `stop` the dispatcher without starting it in the first place ^^

**Comment by macrojames** [comment]
If I start it before the flask thread, it was blocking and flask never runs. 
I don't want polling or integrated webhook threads, just the command handler. 
Am 10.08.2016 9:23 nachm. schrieb Jannes Höke <notifications@github.com>:I think the problem is that you stop the dispatcher without starting it in the first place ^^

**Comment by jh0ker** [comment]
I edited my comment

**Comment by macrojames** [comment]
Removed any calls after the flask.run(), removed any Updater.
Initialized now with:
```python
bot = telegram.Bot(TOKEN)
dispatcher = Dispatcher(bot, Queue(), workers=1)
dispatcher.add_handler(CommandHandler('start', tg_start))
app.run(threaded=False, use_reloader=False, debug=DEBUG, host='0.0.0.0')
```
Same result :(

**Comment by jh0ker** [comment]
Oh, try using `workers=0`

**Comment by macrojames** [comment]
Ok, tried that.
That let's me terminate the program, but disables the CommandHandling.

**Comment by macrojames** [comment]
Nevermind my last comment, it works as it should since removing the Updater and setting workers=0.
