### ISSUE TITLE
send_file reports that the file is too large? My files are all at least 200mb, what should I do?[QUESTION]

### ISSUE THREAD

**Issue by jianchao123** [python-telegram-bot/python-telegram-bot#3744]
### Issue I am facing

I have a lot of compressed files, but most of them are over 50mb, calling send_file will report "file too large error". Is there any way I can solve large file uploads?

### Operating System

ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot-20.0
```

**Comment by clot27** [comment]
@jianchao123 You have to use a local api server, see <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Local-Bot-API-Server">Local API Server</a>
