### ISSUE TITLE
Filter support for invoice_payload in PreCheckoutQueryHandler and successful_payment message

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#3752]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

There is currently no solution to filter for `invoice_payload` in the previously mentioned updates.

### Describe the solution you'd like

I would like to change the SuccessfulPayment message filter to the same type of filter we have with the [text one](https://docs.python-telegram-bot.org/telegram.ext.filters.html#telegram.ext.filters.Text). And I would like to have a pattern argument in the PreCheckoutQueryHandler, similar to the [callbackqueryhandler](https://docs.python-telegram-bot.org/en/stable/telegram.ext.callbackqueryhandler.html).

### Describe alternatives you've considered

Filtering has to happen in the callback. That works, but is not our design philosophy.

**Comment by harshil21** [comment]
Okay 👍🏽  assigning you

**Comment by thefunkycat** [comment]
@Poolitzer can I have some additional context here please?
When you say we should change the `SuccessfulPayment` filter to the same type of filter as the  `telegram.ext.filters.Text`  one in order to filter based on `invoice_payload`, does this mean you're looking to have the `telegram.ext.filters.SUCCESSFUL_PAYMENT` filter return all non empty `invoice_payload` `successful_payment` messages or do I want to pass a list of` invoice_payloads` and filter based on `successful_payment` messages that have that particular `invoice_payload`.

**Comment by Poolitzer** [comment]
SUCCESSFUL_PAYMENT, as with TEXT, should be a shortcut to an instance of the new class `SuccessfulPayment`. And that should then return all `successful_payment` messages. Which will always have invoice_payload be set to smth.
But one can then create their own instance of  `SuccessfulPayment` and pass there a list of strings to filter against, again like with the text filter.

**Comment by thefunkycat** [comment]
@Poolitzer made a pr, let me know if any changes should be made or if I misunderstood something, thanks!

**Comment by erickisos** [comment]
I can take it if it's still pending!

**Comment by harshil21** [comment]
@erickisos yes, you may work on it, assigning you

**Comment by namesarnav** [comment]
Hey, could you assign this issue to me if it's still open. I'd love to contribute. Thanks!

**Comment by Bibo-Joshi** [comment]
#3899 was closed due to inactivity. Anyone interested in having another go at this issue may ofc use https://github.com/python-telegram-bot/python-telegram-bot/pull/3773 or #3899 has starting point

**Comment by nietxan** [comment]
Hello, I'd like to try

**Comment by Poolitzer** [comment]
Sure, give it a shot :)

**Comment by aelkheir** [comment]
I gave it a try, #4005. Please review :).
