### ISSUE TITLE
 Retrieve old picture message data

### ISSUE THREAD

**Issue by ozicmoi** [python-telegram-bot/python-telegram-bot#3755]
### Issue I am facing

I am trying to take a picture according to the text by filtering text in telegram. My aim is to take the picture of the message if the date I took from the database and the text field of the message have the same date.

![image](https://github.com/python-telegram-bot/python-telegram-bot/assets/52746269/58907193-3a5c-4c57-b8a5-68a06bdee980)

İ want to check filtered text and  image

Can u help. Thanks

### Related part of your code

```python
import telegram
def get_filtered_messages(bot_token, chat_id, keyword):
    bot = telegram.Bot(token=bot_token)
    messages = bot.get_chat(chat_id)
    print(messages)
    
    filtered_messages = []
    
    for message in messages:
        text = message.get('2023', '')
        if keyword in text:
            filtered_messages.append(message)
    
    return filtered_messages

def main():
    # Bot tokenini ve chat ID'sini buraya girin
    bot_token = 'my_token'
    chat_id = 'my_chatid'
    keyword = '2023-06-13 16:04:57'
    print(telegram.ext.filters.ALL)

    
    filtered_messages = get_filtered_messages(bot_token, chat_id, keyword)
    
    for message in filtered_messages:
        text = message.get('text', '')
        date = message.get('date')
        print('Mesaj:', text)
        print('Tarih:', date)
        print('---')
```

### Operating System

Windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python 3.8
```

**Comment by Bibo-Joshi** [comment]
- please don't randomly mention people
- please not that we no longer provide support for versions older than v20. There is a transition guide in our GitHub wiki
- the bot API does not offer functionality to retrieve a list of messages in a chat. Your bot would instead have to listen to all incoming messages and keep track of them

**Comment by ozicmoi** [comment]
I've been searching your documents for days but I couldn't.
 I felt the need to write to the issues area. I just asked for support on this. You don't have to be so rude.
