### ISSUE TITLE
[QUESTION] IndexError: tuple index out of range for get images 

### ISSUE THREAD

**Issue by tofuurem** [python-telegram-bot/python-telegram-bot#3757]
### Steps to Reproduce

1. pip install python-telgram-bot==20.3
2. create simple bot with message handler for video and photo `MessageHandler(filters.PHOTO | filters.VIDEO, callback=callback_message_media)`
3. create callback handler like this
```python
async def callback_message_media(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    photo_files: tuple[PhotoSize, ...] | None = update.message.photo
    video: Video | None = update.message.video
    if photo_files is not None:
        print(len(photo_files), type(photo_files), photo_files[-1])
```
4. send photo with video like media group
<img width="316" alt="image" src="https://github.com/python-telegram-bot/python-telegram-bot/assets/51081709/175ee9d3-5b1f-4b88-bb96-3757e826d20c">

### Expected behaviour

1. get the last image without errors as if I had sent only the image

### Actual behaviour

1. traceback with an error
```python
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/rabbit/Desktop/pet_projects/telegram_notify_bot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1124, in process_update
    await coroutine
  File "/Users/rabbit/Desktop/pet_projects/telegram_notify_bot/venv/lib/python3.11/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rabbit/Desktop/pet_projects/telegram_notify_bot/src/bot/admin/callbacks/callback_media.py", line 36, in callback_message_media
    print(len(photo_files), type(photo_files), photo_files[-1])
                                               ~~~~~~~~~~~^^^^
IndexError: tuple index out of range
```

2. after the `print` output 
 ```python
4 <class 'tuple'> PhotoSize(file_id='AgACAgIAAxkBAAICpWSKMoKd3VWTcnMd3OTS1d3b0nvJAALdzTEbOs9BSOcdmqcYVNmnAQADAgADeQADLwQ', file_size=180153, file_unique_id='AQAD3c0xGzrPQUh-', height=854, width=1280)

```

### Operating System

Mac OS 13.4

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.3 (v0.11.1-7-ga2a559c)
Bot API 6.7
Python 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
```

### Relevant log output

```python
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/rabbit/Desktop/pet_projects/telegram_notify_bot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1124, in process_update
    await coroutine
  File "/Users/rabbit/Desktop/pet_projects/telegram_notify_bot/venv/lib/python3.11/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rabbit/Desktop/pet_projects/telegram_notify_bot/src/bot/admin/callbacks/callback_media.py", line 36, in callback_message_media
    print(len(photo_files), type(photo_files), photo_files[-1])
                                               ~~~~~~~~~~~^^^^
IndexError: tuple index out of range
4 <class 'tuple'> PhotoSize(file_id='AgACAgIAAxkBAAICoGSKMNdahEeMCRjA3D-5Ohmx_YijAALdzTEbOs9BSOcdmqcYVNmnAQADAgADeQADLwQ', file_size=180153, file_unique_id='AQAD3c0xGzrPQUh-', height=854, width=1280)
```

**Comment by Bibo-Joshi** [comment]
@tofuurem Hi. Please have a careful look at the docs of <a href="https://docs.python-telegram-bot.org/telegram.message.html#telegram.Message.photo">telegram.Message.photo</a> <a href="https://core.telegram.org/bots/api#message">ᵀᴱᴸᴱᴳᴿᴬᴹ</a>. I&#x27;m sure that you will notice something:)

**Comment by tofuurem** [comment]
@Bibo-Joshi Hi, I apologize if this is not a bug after all.
I looked through the documentation before writing the issue.
The issue is that there are 4 objects in the tuple, I can see it, but for some reason I get IndexError when I try to access even one. 

I would understand if it was an empty tuple or None

**Comment by tofuurem** [comment]
@Bibo-Joshi 
I withdraw my question, I realized that when it receives a group of media, it sees them as two separate objects and first processes one then the other.

I thought it processes them as 1 object and sends the whole message at once, but it sends first the first file and after the second, even if quickly this behavior is different from what I expected:)
Thanks for your reply!

**Comment by Poolitzer** [comment]
@tofuurem We have a design entry for media groups: <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#how-do-i-deal-with-a-media-group">How do I deal with a media group?</a>

**Comment by tofuurem** [comment]
@Poolitzer This is for sending messages as media, and I'm talking about the bot receiving a media group as 1 message, but either I did it wrong, or each media object is sent separately, as a separate message

**Comment by tofuurem** [comment]
@Poolitzer Oh, thank you so much! I'm sorry I must have missed it :3
