### ISSUE TITLE
Execfile does not exist in py3k

### ISSUE THREAD

**Issue by bomjacob** [python-telegram-bot/python-telegram-bot#376]
### Steps to reproduce
1. Use python 3

2. Try to install from git:
`$ pip install -e git+https://github.com/python-telegram-bot/python-telegram-bot.git@555e36ee8036a179f157f60dcb0c3fcf958146f4#egg=telegram`

### Expected behaviour
The library should be installed.

### Actual behaviour
NameError due to `execfile` not being a thing in python 3.
See here for alternatives: https://stackoverflow.com/a/437857
I would fix it myself, but I am unable to actually find the execfile call anywhere .-.

### Configuration
**Operating System:**
Windows 10 Education

**Version of Python, python-telegram-bot & dependencies:**
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul 5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]

### Logs
```
$ pip install -e git+https://github.com/python-telegram-bot/python-telegram-bot.git@555e36ee8036a179f157f60dcb0c3fcf958146f4#egg=telegram
Obtaining telegram from git+https://github.com/python-telegram-bot/python-telegram-bot.git@555e36ee8036a179f157f60dcb0c3fcf958146f4#egg=telegram
  Skipping because already up-to-date.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Development\telegram\VocaBot2\src\telegram\setup.py", line 20, in <module>
        execfile(os.path.join('telegram', 'version.py'))
    NameError: name 'execfile' is not defined
Command "python setup.py egg_info" failed with error code 1```

**Comment by bomjacob** [comment]
Actually nevermind, turns out I was looking for the execfile on a very old version of the library... I'll go make a pull-request.

**Comment by bomjacob** [comment]
Fixed by #377.

**Comment by bomjacob** [comment]
@jh0ker It would seem that my #377 doesn't always work (it worked when I first tested it, but not any more...)... So idk :/
Is there a particular reason we can't just `from .telegram.version import __version__`? (or something like that, not sure about the exact number of dots and such) That seems a lot nicer IMO.
Bottom line is: the setup.py is currently broken (both on py2 and py3) and my pull-request should probably be reverted or something for now.

**Comment by jh0ker** [comment]
@bomjacob Yes, the reason is that we import some of our requirements (implicitly) when we go the usual import way

**Comment by bomjacob** [comment]
Ah okay... Well I'm sure there's a way to do it with the code I've
committed (since its like the official way to do execfile now)... Honestly
I'm not even entirely why it doesn't work... I'll have a look at it
tomorrow.
