### ISSUE TITLE
[QUESTION] Bot freezes for all users when trying to edit same message repeatedly using `AIORateLimiter`

### ISSUE THREAD

**Issue by bigbabybubble** [python-telegram-bot/python-telegram-bot#3765]
### Issue I am facing

I noticed that when trying to edit the same message more than 3 times in seconds, the bot freezes for all users
I can solve this problem with a task, but are there any other methods?
context.bot.edit_message_text(text, chat_id=chat_id, message_id=message.message_id, parse_mode=parse_mode

TASK:
try:
                        task_to_edit = asyncio.create_task(context.bot.edit_message_text(text, chat_id=chat_id, message_id=message.message_id, parse_mode=parse_mode))
                        await asyncio.wait_for(task_to_edit, timeout=1)
                    except asyncio.TimeoutError:
                        task_to_edit.cancel()

Settings:
    application = (
        ApplicationBuilder()
        .token(config.telegram_token)
        .concurrent_updates(True)
        .rate_limiter(AIORateLimiter(max_retries=5))
        .post_init(post_init)
        .build()
    )

### Traceback to the issue

```python
try:
                        task_to_edit = asyncio.create_task(context.bot.edit_message_text(text, chat_id=chat_id, message_id=message.message_id, parse_mode=parse_mode))
                        await asyncio.wait_for(task_to_edit, timeout=2)
                    except asyncio.TimeoutError:
                        task_to_edit.cancel()
```

### Operating System

linux

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot[rate-limiter]==20.2
```

**Comment by bigbabybubble** [comment]
If i cancel the task, editing is possible again. I suspect this is a bug in the async function. Also, I don't see any flood errors.

**Comment by Bibo-Joshi** [comment]
@bigbabybubble Please carefully read the docs if <a href="https://docs.python-telegram-bot.org/telegram.ext.aioratelimiter.html#telegram.ext.AIORateLimiter">telegram.ext.AIORateLimiter</a>. I&#x27;m rather sure that this will answer your question.

**Comment by bigbabybubble** [comment]
Maybe you can explain in more detail why the bot is freezes to all users if, for example, the bot was unable to edit a message for only one user? How is it possible to fix this?

**Comment by Bibo-Joshi** [comment]
@bigbabybubble &gt; A RetryAfter exception will halt all requests for retry_after + 0.1 seconds. This may be stricter than necessary in some cases, e.g. the bot may hit a rate limit in one group but might still be allowed to send messages in another group.

**Comment by bigbabybubble** [comment]
> 

Bot does not receive error 429 from telegram. The bot is blocked by freezes for all users. Above I gave an example with a task. When a task is forcibly canceled, the bot is again available to both a specific user and all users. This error is not related to error telegram 429

**Comment by Bibo-Joshi** [comment]
One of the points of using AIORatelimiter is that it automatically handles RetryAfter exceptions automatically for you. As long as you stay within the 5 retries, you won't see any raised exceptions about rate limits. AIORatelimiter does log the catched exceptions though. You can see that if you set your logging level to Info.

**Comment by bigbabybubble** [comment]
> 

It helped me
Thank you
