### ISSUE TITLE
[BUG] AIORateLimiter's algorithm isn't suitable for stopping flood errors

### ISSUE THREAD

**Issue by bigbabybubble** [python-telegram-bot/python-telegram-bot#3772]
### Steps to Reproduce

Hello! The algorithm you are using in AIORATELIMITER is called bucket leak, but it is not compatible with telegram limits. We can't afford leaks under tight restrictions

This algorithm allowed sending more than 20 in 60 sec messages to a group

```python
import asyncio
from aiolimiter import AsyncLimiter
from datetime import datetime

group_limiter = AsyncLimiter(20, 60)
base_limiter = AsyncLimiter(30, 1)

async def print_operation(iteration):
    async with group_limiter:
        async with base_limiter:
            current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            print(f"Iteration: {iteration}, Current Time: {current_time}")

async def main():
    for iteration in range(1, 61):
        await print_operation(iteration)
        await asyncio.sleep(1) 

asyncio.run(main())
```

### Operating System

Linux

### Version of Python, python-telegram-bot & dependencies

```shell
20.3
```

### Relevant log output

```python
root@ams:~# python3 testrate.py
Iteration: 1, Current Time: 2023-06-23 19:46:51
Iteration: 2, Current Time: 2023-06-23 19:46:52
Iteration: 3, Current Time: 2023-06-23 19:46:53
Iteration: 4, Current Time: 2023-06-23 19:46:54
Iteration: 5, Current Time: 2023-06-23 19:46:55
Iteration: 6, Current Time: 2023-06-23 19:46:56
Iteration: 7, Current Time: 2023-06-23 19:46:57
Iteration: 8, Current Time: 2023-06-23 19:46:58
Iteration: 9, Current Time: 2023-06-23 19:46:59
Iteration: 10, Current Time: 2023-06-23 19:47:00
Iteration: 11, Current Time: 2023-06-23 19:47:01
Iteration: 12, Current Time: 2023-06-23 19:47:02
Iteration: 13, Current Time: 2023-06-23 19:47:03
Iteration: 14, Current Time: 2023-06-23 19:47:04
Iteration: 15, Current Time: 2023-06-23 19:47:05
Iteration: 16, Current Time: 2023-06-23 19:47:06
Iteration: 17, Current Time: 2023-06-23 19:47:07
Iteration: 18, Current Time: 2023-06-23 19:47:08
Iteration: 19, Current Time: 2023-06-23 19:47:09
Iteration: 20, Current Time: 2023-06-23 19:47:10
Iteration: 21, Current Time: 2023-06-23 19:47:11
Iteration: 22, Current Time: 2023-06-23 19:47:12
Iteration: 23, Current Time: 2023-06-23 19:47:13
Iteration: 24, Current Time: 2023-06-23 19:47:14
Iteration: 25, Current Time: 2023-06-23 19:47:15
Iteration: 26, Current Time: 2023-06-23 19:47:16
Iteration: 27, Current Time: 2023-06-23 19:47:17
Iteration: 28, Current Time: 2023-06-23 19:47:18
^CTraceback
```

**Comment by Bibo-Joshi** [comment]
Hi. This behavior is explained by the [bursting](https://aiolimiter.readthedocs.io/en/latest/#bursting) of aiolimiter, i.e. at the very start of the script no messages have been sent yet and hence you are free to send 20 messages immediately. The rate limiting then kicks in only later. This is more obvious if you remove the `asyncio.sleep(1)`:

<details><summary>MWE & OUtput</summary>

```python
import asyncio
import time

from aiolimiter import AsyncLimiter

group_limiter = AsyncLimiter(20, 60)
base_limiter = AsyncLimiter(30, 1)

ref = time.time()
last_call = ref


async def print_operation(iteration):
    global last_call
    async with group_limiter:
        async with base_limiter:
            print(
                f"Iteration: {iteration},\t Delay since start: {time.time() - ref:>5.2f},\t "
                f"Delay since last iteration: {time.time() - last_call:>5.2f}"
            )
            last_call = time.time()


async def main():
    for iteration in range(1, 61):
        await print_operation(iteration)
        # await asyncio.sleep(1)


asyncio.run(main())
```

```python
Iteration: 1,    Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 2,    Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 3,    Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 4,    Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 5,    Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 6,    Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 7,    Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 8,    Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 9,    Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 10,   Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 11,   Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 12,   Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 13,   Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 14,   Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 15,   Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 16,   Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 17,   Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 18,   Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 19,   Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 20,   Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 21,   Delay since start:  3.02,       Delay since last iteration:  3.01
Iteration: 22,   Delay since start:  6.03,       Delay since last iteration:  3.01
Iteration: 23,   Delay since start:  9.03,       Delay since last iteration:  3.00
Iteration: 24,   Delay since start: 12.04,       Delay since last iteration:  3.01
Iteration: 25,   Delay since start: 15.05,       Delay since last iteration:  3.01
Iteration: 26,   Delay since start: 18.06,       Delay since last iteration:  3.01
Iteration: 27,   Delay since start: 21.07,       Delay since last iteration:  3.01
Iteration: 28,   Delay since start: 24.08,       Delay since last iteration:  3.01
Iteration: 29,   Delay since start: 27.09,       Delay since last iteration:  3.01
Iteration: 30,   Delay since start: 30.11,       Delay since last iteration:  3.02
Iteration: 31,   Delay since start: 33.12,       Delay since last iteration:  3.01
Iteration: 32,   Delay since start: 36.12,       Delay since last iteration:  3.00
Iteration: 33,   Delay since start: 39.13,       Delay since last iteration:  3.01
Iteration: 34,   Delay since start: 42.14,       Delay since last iteration:  3.00
Iteration: 35,   Delay since start: 45.15,       Delay since last iteration:  3.02
Iteration: 36,   Delay since start: 48.16,       Delay since last iteration:  3.01
Iteration: 37,   Delay since start: 51.17,       Delay since last iteration:  3.01
Iteration: 38,   Delay since start: 54.18,       Delay since last iteration:  3.01
Iteration: 39,   Delay since start: 57.19,       Delay since last iteration:  3.01
Iteration: 40,   Delay since start: 60.18,       Delay since last iteration:  2.99
Iteration: 41,   Delay since start: 63.18,       Delay since last iteration:  3.01
Iteration: 42,   Delay since start: 66.20,       Delay since last iteration:  3.01
Iteration: 43,   Delay since start: 69.20,       Delay since last iteration:  3.01
Iteration: 44,   Delay since start: 72.21,       Delay since last iteration:  3.01
Iteration: 45,   Delay since start: 75.21,       Delay since last iteration:  3.00
Iteration: 46,   Delay since start: 78.23,       Delay since last iteration:  3.01
Iteration: 47,   Delay since start: 81.24,       Delay since last iteration:  3.01
Iteration: 48,   Delay since start: 84.25,       Delay since last iteration:  3.01
Iteration: 49,   Delay since start: 87.26,       Delay since last iteration:  3.01
Iteration: 50,   Delay since start: 90.26,       Delay since last iteration:  3.00
Iteration: 51,   Delay since start: 93.27,       Delay since last iteration:  3.00
Iteration: 52,   Delay since start: 96.28,       Delay since last iteration:  3.01
Iteration: 53,   Delay since start: 99.28,       Delay since last iteration:  3.00
Iteration: 54,   Delay since start: 102.29,      Delay since last iteration:  3.01
Iteration: 55,   Delay since start: 105.30,      Delay since last iteration:  3.01
Iteration: 56,   Delay since start: 108.31,      Delay since last iteration:  3.01
Iteration: 57,   Delay since start: 111.32,      Delay since last iteration:  3.01
Iteration: 58,   Delay since start: 114.32,      Delay since last iteration:  3.01
Iteration: 59,   Delay since start: 117.33,      Delay since last iteration:  3.01
Iteration: 60,   Delay since start: 120.35,      Delay since last iteration:  3.01

```

</details>

Now, the `asyncio.sleep(1)` prevents the bursting but  aiolimiter still allows you to send more messages in the beginning because the capacity is still not full. The limiting still kicks in later on:

<details><summary>MWE & OUtput</summary>

```python
import asyncio
import time

from aiolimiter import AsyncLimiter

group_limiter = AsyncLimiter(20, 60)
base_limiter = AsyncLimiter(30, 1)

ref = time.time()
last_call = ref


async def print_operation(iteration):
    global last_call
    async with group_limiter:
        async with base_limiter:
            print(
                f"Iteration: {iteration},\t Delay since start: {time.time() - ref:>5.2f},\t "
                f"Delay since last iteration: {time.time() - last_call:>5.2f}"
            )
            last_call = time.time()


async def main():
    for iteration in range(1, 61):
        await print_operation(iteration)
        await asyncio.sleep(1)


asyncio.run(main())
```

```python
Iteration: 1,    Delay since start:  0.00,       Delay since last iteration:  0.00
Iteration: 2,    Delay since start:  1.01,       Delay since last iteration:  1.01
Iteration: 3,    Delay since start:  2.02,       Delay since last iteration:  1.01
Iteration: 4,    Delay since start:  3.03,       Delay since last iteration:  1.01
Iteration: 5,    Delay since start:  4.04,       Delay since last iteration:  1.01
Iteration: 6,    Delay since start:  5.06,       Delay since last iteration:  1.01
Iteration: 7,    Delay since start:  6.06,       Delay since last iteration:  1.01
Iteration: 8,    Delay since start:  7.07,       Delay since last iteration:  1.01
Iteration: 9,    Delay since start:  8.08,       Delay since last iteration:  1.00
Iteration: 10,   Delay since start:  9.09,       Delay since last iteration:  1.01
Iteration: 11,   Delay since start: 10.10,       Delay since last iteration:  1.01
Iteration: 12,   Delay since start: 11.11,       Delay since last iteration:  1.01
Iteration: 13,   Delay since start: 12.13,       Delay since last iteration:  1.01
Iteration: 14,   Delay since start: 13.13,       Delay since last iteration:  1.01
Iteration: 15,   Delay since start: 14.14,       Delay since last iteration:  1.01
Iteration: 16,   Delay since start: 15.16,       Delay since last iteration:  1.01
Iteration: 17,   Delay since start: 16.17,       Delay since last iteration:  1.01
Iteration: 18,   Delay since start: 17.18,       Delay since last iteration:  1.01
Iteration: 19,   Delay since start: 18.19,       Delay since last iteration:  1.01
Iteration: 20,   Delay since start: 19.20,       Delay since last iteration:  1.01
Iteration: 21,   Delay since start: 20.20,       Delay since last iteration:  1.00
Iteration: 22,   Delay since start: 21.21,       Delay since last iteration:  1.01
Iteration: 23,   Delay since start: 22.21,       Delay since last iteration:  1.01
Iteration: 24,   Delay since start: 23.23,       Delay since last iteration:  1.01
Iteration: 25,   Delay since start: 24.23,       Delay since last iteration:  1.01
Iteration: 26,   Delay since start: 25.25,       Delay since last iteration:  1.01
Iteration: 27,   Delay since start: 26.25,       Delay since last iteration:  1.01
Iteration: 28,   Delay since start: 27.27,       Delay since last iteration:  1.01
Iteration: 29,   Delay since start: 28.28,       Delay since last iteration:  1.01
Iteration: 30,   Delay since start: 32.31,       Delay since last iteration:  4.03
Iteration: 31,   Delay since start: 33.32,       Delay since last iteration:  1.01
Iteration: 32,   Delay since start: 37.34,       Delay since last iteration:  4.03
Iteration: 33,   Delay since start: 41.36,       Delay since last iteration:  4.02
Iteration: 34,   Delay since start: 42.38,       Delay since last iteration:  1.01
Iteration: 35,   Delay since start: 46.38,       Delay since last iteration:  4.01
Iteration: 36,   Delay since start: 50.40,       Delay since last iteration:  4.02
Iteration: 37,   Delay since start: 51.40,       Delay since last iteration:  1.00
Iteration: 38,   Delay since start: 55.42,       Delay since last iteration:  4.02
Iteration: 39,   Delay since start: 59.44,       Delay since last iteration:  4.02
Iteration: 40,   Delay since start: 60.45,       Delay since last iteration:  1.00
Iteration: 41,   Delay since start: 64.45,       Delay since last iteration:  4.01
Iteration: 42,   Delay since start: 68.47,       Delay since last iteration:  4.01
Iteration: 43,   Delay since start: 69.47,       Delay since last iteration:  1.00
Iteration: 44,   Delay since start: 73.47,       Delay since last iteration:  4.00
Iteration: 45,   Delay since start: 77.49,       Delay since last iteration:  4.02
Iteration: 46,   Delay since start: 78.50,       Delay since last iteration:  1.01
Iteration: 47,   Delay since start: 82.51,       Delay since last iteration:  4.01
Iteration: 48,   Delay since start: 86.53,       Delay since last iteration:  4.02
Iteration: 49,   Delay since start: 87.55,       Delay since last iteration:  1.02
Iteration: 50,   Delay since start: 91.55,       Delay since last iteration:  4.00
Iteration: 51,   Delay since start: 95.57,       Delay since last iteration:  4.02
Iteration: 52,   Delay since start: 96.57,       Delay since last iteration:  1.00
Iteration: 53,   Delay since start: 100.59,      Delay since last iteration:  4.02
Iteration: 54,   Delay since start: 104.61,      Delay since last iteration:  4.02
Iteration: 55,   Delay since start: 105.62,      Delay since last iteration:  1.01
Iteration: 56,   Delay since start: 109.62,      Delay since last iteration:  4.01
Iteration: 57,   Delay since start: 113.64,      Delay since last iteration:  4.01
Iteration: 58,   Delay since start: 114.65,      Delay since last iteration:  1.02
Iteration: 59,   Delay since start: 118.66,      Delay since last iteration:  4.01
Iteration: 60,   Delay since start: 122.69,      Delay since last iteration:  4.03
```

</details>

The issue with Telegrams flood limiting is that they are not documented and are not constant. So we don't *really* know what limiting exactly we should apply. The `AIORatelimiter` is a minimal effort reference implementation. You can make it more strict my adjusting the limits (e.g. `AsyncLimiter(1, 3)` enforces to send messages only once every 3 seconds) or you can implement your own version of `BaseRateLimiter`.
From my POV this is not a bug in `AIORatelimiter` but rather a design choice - the choice being to rely on aiolimiters rate limiting logic rather than implementing a custom one.

**Comment by bigbabybubble** [comment]
Telegram: “ Also note that your bot will not be able to send more than 20 messages per minute to the same group.”
We can rely on this limitation to be clearly and understandably described. Then, having this information, we can conclude that it is not minimal effort reference implementation. Because we can't use this implementation because it obviously violates the telegram limits: Also note that your bot will not be able to send more than 20 messages per minute to the same group

In this case, your answer suggests that “we have implemented the constraint, but whether you get an error or not, we do not know”. In my understanding “ minimal effort reference implementation” is “play and play” solution. But users using this solution do not even assume that they can immediately violate telegram limits “ Also note that your bot will not be able to send more than 20 messages per minute to the same group”. They will make this setting and will think that everything is fine and you can sleep peacefully until they start getting flood errors at night.

**Comment by Bibo-Joshi** [comment]
> We can rely on this limitation to be clearly and understandably described.

This is where I disagree. The phrasing "20 messages per minute" does not define how that is measure. Do they use a sliding windows logic, a fixed window logic, a leaky bucket logic, a mix of them, or something different entirely? Without knowing exactly how Telegram calculates the flood limits, we can not design an algorithm that exactly avoids them. We can only use heuristicts (and I'm fairly sure that this is exactly why TG doesn't tell us).

So far, I have not seen reports about using AIORateLimiter leading to significant occurences of flooding exceptions and I must hence assume that either it was used very scarsely so far or that the logic is working well enough. Note that AIORateLimiter also has a built-in retry mechanism, which can make the heuristic approach even more resiliant :)

If you would like the docs of AIORateLimiter to stress that it can not guarantee to avoid flood limits all together, you are welcome to suggest some wording for that.

**Comment by bigbabybubble** [comment]
> > We can rely on this limitation to be clearly and understandably described.
> 
> This is where I disagree. The phrasing "20 messages per minute" does not define how that is measure. Do they use a sliding windows logic, a fixed window logic, a leaky bucket logic, a mix of them, or something different entirely? Without knowing exactly how Telegram calculates the flood limits, we can not design an algorithm that exactly avoids them. We can only use heuristicts (and I'm fairly sure that this is exactly why TG doesn't tell us).
> 
> So far, I have not seen reports about using AIORateLimiter leading to significant occurences of flooding exceptions and I must hence assume that either it was used very scarsely so far or that the logic is working well enough. Note that AIORateLimiter also has a built-in retry mechanism, which can make the heuristic approach even more resiliant :)
> 
> If you would like the docs of AIORateLimiter to stress that it can not guarantee to avoid flood limits all together, you are welcome to suggest some wording for that.

Hello! I understand your approach and thanks for the reply. I had to disassemble in the algorithm to understand how this algorithm works.
https://docs.python-telegram-bot.org/en/stable/telegram.ext.aioratelimiter.html
[group_max_rate](https://docs.python-telegram-bot.org/en/stable/telegram.ext.aioratelimiter.html#telegram.ext.AIORateLimiter.params.group_max_rate) ([float](https://docs.python.org/3/library/functions.html#float)) – The maximum number of requests allowed for requests related to groups and channels per [group_time_period](https://docs.python-telegram-bot.org/en/stable/telegram.ext.aioratelimiter.html#telegram.ext.AIORateLimiter.params.group_time_period). When set to 0, no rate limiting will be applied. Defaults to 20.
[group_time_period](https://docs.python-telegram-bot.org/en/stable/telegram.ext.aioratelimiter.html#telegram.ext.AIORateLimiter.params.group_time_period) ([float](https://docs.python.org/3/library/functions.html#float)) – The time period (in seconds) during which the [group_max_rate](https://docs.python-telegram-bot.org/en/stable/telegram.ext.aioratelimiter.html#telegram.ext.AIORateLimiter.params.group_max_rate) is enforced. When set to 0, no rate limiting will be applied. Defaults to 60.
This documentation describes clear and explicit limitations. 

https://github.com/python-telegram-bot/python-telegram-bot/issues/3765 My question was related to this algorithm, although I did not receive an answer in the official telegram chat why I do not limit the number of messages edited by this algorithm. Now I understand why this is happening. But I don’t understand why a solution is being developed in a productive way, which is based on conjectures and assumptions? :) Is this the correct approach when you call is "minimal effort reference implementation"? I guess not, since I have proven that this restriction does not work when editing messages.

But then let's consider another problem of your own solution AIORateLimiter. If you allow the assumption that the restrictions are not explicit, then why does your solution completely block the bot when you receive a flood error (async def process_request()). After all, Telegram itself states that if a bot cannot send messages to one user, this does not mean that it cannot send it to another user. In this: https://github.com/python-telegram-bot/python-telegram-bot/issues/3765 I describe that the solution blocks the bot for everyone. Is this the correct approach? I think no. 

I wrote this class and now I am based on a real constraint that I can imagine and I understand that it works as it can be predicted
```
class AsyncRateLimiter:
    def __init__(self, max_operations, period):
        self.max_operations = max_operations
        self.period = period
        self.operations = 0
        self.last_reset = None

    async def __aenter__(self):
        if self.last_reset is None or (asyncio.get_event_loop().time() - self.last_reset) > self.period:
            self.operations = 0
            self.last_reset = asyncio.get_event_loop().time()

        if self.operations >= self.max_operations:
            time_to_wait = self.period - (asyncio.get_event_loop().time() - self.last_reset)
            logger.error("most operation to edit")
            await asyncio.sleep(time_to_wait)

        self.operations += 1

    async def __aexit__(self, exc_type, exc, tb):
        pass

```

But the main problem is precisely why the solution in the production is not explicitly described and documented and placed with the wording "minimal effort reference implementation"?

**Comment by Bibo-Joshi** [comment]
> But the main problem is precisely why the solution in the productive is not explicitly described and documented and placed with the wording "minimal effort reference implementation"?

From my POV the logic implemented within `AIORateLimiter` is documented well enough by a) pointing explicitly to the used `aiolimiter` library and b) several notes and explanations about what this logic does and does not include

What the wording "minimal effort reference implementation" here means is that `AIORateLimiter` is a rather basic example implementation of the `BaseRateLimiter` interface class. It showcases how the interface methods can be used to delay awaiting the coroutine, to retry on flood errors and to use the `rate_limit_args` args. It does not aim to handle all special cases in a sophisticated way.
If you disagree with the wording for this, you are welcome to suggest a different one.

> But I don’t understand why a solution is being developed in a productive way, which is based on conjectures and assumptions?

As explained in https://github.com/python-telegram-bot/python-telegram-bot/issues/3772#issuecomment-1607999936, one *has* to make assumptions when trying to avoid TGs flood limits. This is also stressed in the [wiki page on flood limiting](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-flood-limits).

**Comment by bigbabybubble** [comment]
> > But the main problem is precisely why the solution in the productive is not explicitly described and documented and placed with the wording "minimal effort reference implementation"?
> 
> From my POV the logic implemented within `AIORateLimiter` is documented well enough by a) pointing explicitly to the used `aiolimiter` library and b) several notes and explanations about what this logic does and does not include
> 
> What the wording "minimal effort reference implementation" here means is that `AIORateLimiter` is a rather basic example implementation of the `BaseRateLimiter` interface class. It showcases how the interface methods can be used to delay awaiting the coroutine, to retry on flood errors and to use the `rate_limit_args` args. It does not aim to handle all special cases in a sophisticated way. If you disagree with the wording for this, you are welcome to suggest a different one.
> 
> > But I don’t understand why a solution is being developed in a productive way, which is based on conjectures and assumptions?
> 
> As explained in [#3772 (comment)](https://github.com/python-telegram-bot/python-telegram-bot/issues/3772#issuecomment-1607999936), one _has_ to make assumptions when trying to avoid TGs flood limits. This is also stressed in the [wiki page on flood limiting](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-flood-limits).

OK, thank you. I understood the logic of this limiter. This means that we must observe and adjust our bot ourselves based on real experiments. I did not know that the specifics of working with telegram bots are exactly like this.
