### ISSUE TITLE
[QUESTION] Bot and groups information on bot startup

### ISSUE THREAD

**Issue by haserwolf** [python-telegram-bot/python-telegram-bot#3782]
### Issue I am facing

Previously in my bots (based on 13.x PTB) on bot startup simple part of the code print bot name and group titles. This behavior helps with a situation I have logs from various instances of the same bot code running. Unfortunately, I can't reproduce this in the new version I'm working on (based on 20.x PTB). Change to asyncio caused fields in the app.bot exists but not contain the correct information, instead of this all fields contain error message "ExtBot is not properly initialized. Call ExtBot.initialize before accessing this property." (based on testing in Python Console module in Pycharm). Is there a possibility to reproduce this functionality in 20.x-based bots?

### Traceback to the issue

```python
Traceback (most recent call last):
  File "/home/haserwolf/repo/xbot/main.py", line 30, in <module>
    print('Bot name: ' + str(app.bot.name))
  File "/home/haserwolf/repo/xbot/venv/lib/python3.9/site-packages/telegram/_bot.py", line 704, in name
    return f"@{self.username}"
  File "/home/patka/haserwolf/xbot/venv/lib/python3.9/site-packages/telegram/_bot.py", line 673, in username
    return self.bot.username  # type: ignore
  File "/home/patka/haserwolf/xbot/venv/lib/python3.9/site-packages/telegram/_bot.py", line 641, in bot
    raise RuntimeError(
RuntimeError: ExtBot is not properly initialized. Call ExtBot.initialize before accessing this property.
```

### Related part of your code

```python
# Working version (with 13.x PTB)
bot = Bot(TOKEN)
updater = Updater(TOKEN, use_context=True)
disp = updater.dispatcher

print('Bot name: ' + str(bot.name))
print('Control group: ' + str(bot.get_chat(CONTROL).title))
print('Main group: ' + str(bot.get_chat(MAIN).title))

# First try (with 20.x PTB)
app = ApplicationBuilder().token(TOKEN).build()

print('Bot name: ' + str(app.bot.name))
print('Control group: ' + str(app.bot.get_chat(CONTROL).title))
print('Main group: ' + str(app.bot.get_chat(MAIN).title))
```

### Operating System

GNU/Linux NixOS 22.11.4613.03091c9ffd7 (Raccoon) x86_64

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.2
Bot API 6.6
Python 3.9.16 (main, Dec  6 2022, 18:36:13)  [GCC 11.3.0]
(venv)
```

**Comment by Bibo-Joshi** [comment]
@haserwolf Hi. We have <a href="https://docs.python-telegram-bot.org/telegram.ext.applicationbuilder.html#telegram.ext.ApplicationBuilder.post_init">telegram.ext.ApplicationBuilder.post_init</a> in place which allows to run code on startup, but after the initialization.

**Comment by haserwolf** [comment]
Hi @Bibo-Joshi, thank you for your fast reply. The post_init function is what I was missing, but continued I have problems with use print and str functions with async code.

**Comment by Bibo-Joshi** [comment]
> The post_init function is what I was missing

👍

> but continued I have problems with use print and str functions with async code.

That sounds like a general problem of how to work with asyncio code. I recommend to read up in some asyncio tutorials, as that's beyond the scope of this issue tracker.
