### ISSUE TITLE
[QUESTION] Using arbitrary callback data with custom webhook

### ISSUE THREAD

**Issue by ikhomutov** [python-telegram-bot/python-telegram-bot#3790]
### Issue I am facing

Greetings,
I'm trying to integrate a telegram bot to my starlette-based application. I setup handling updates from telegram using custom webhook example. Everything worked perfectly until I tried to add an arbitrary callback data functionality. It seems that the actual callback data is not provided with `update.callback_query.data`. Instead, it returns a 62 character string which, I assume, is a callback cache key.
My question is, do I need to make additional setup to make this works?

I combined code from examples from the docs to make the reproduction of this behaviour easier.
https://gist.github.com/ikhomutov/7fd41decb07a0df1cc3341adf74e1a19

### Operating System

Windows 11

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.2
Bot API 6.6
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
```

**Comment by Poolitzer** [comment]
Hi. Did you install the optional dependency via `pip install python-telegram-bot[callback-data]`

**Comment by ikhomutov** [comment]
Ah nevermind. After submitting an issue, I decided to check the wiki  again, and only now noticed the "Manually handling updates" part. After adding the `bot.insert_callback_data(update)` line everything start to work properly.
