### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by GodFatherClover** [python-telegram-bot/python-telegram-bot#3796]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Robot A receives a message and reprocesses it before sending it to Robot B. Can you provide this example?

### Describe the solution you'd like

I have a requirement，In the example of echobot.py, the echo function, I want to send this message to robot B

**Comment by GodFatherClover** [comment]
![image](https://github.com/python-telegram-bot/python-telegram-bot/assets/129489866/b8ec4c69-3b8c-4521-90b7-0cd82989fc64)

**Comment by Bibo-Joshi** [comment]
@GodFatherClover Please have a look at these wiki sections: 

* <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#what-about-messages-from-other-bots">What about messages from other Bots?</a>
* <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#can-you-add-feature-to-ptb-can-i-do-thing-with-my-bot">Can you add [feature] to PTB? Can I do [thing] with my bot?</a>

**Comment by GodFatherClover** [comment]
custom webhook ，Does it mean I need to build my own service ？But I don't want to build my own server

**Comment by GodFatherClover** [comment]
> 


custom webhook ，Does it mean I need to build my own service ？But I don't want to build my own server

**Comment by GodFatherClover** [comment]
Does custom webhook mean that I need to build my own service but I don't want to build my own server? Is there any other way?

**Comment by Bibo-Joshi** [comment]
I don't understand your question. Neither of the solutions requires you to physically build your own server. Ofc you anyways need to server(/machine) to run your bot(s) on. If you run both bots on the same machine or even in the same (python) process, then using a form of shared memory/shared database should work fine. In fact even webhooks can be used in this setting, meaning that you'd make http requests between webservers on the same machine, but that may a bit over the top.

**Comment by GodFatherClover** [comment]
Thank you for your answer. I think I understand what you mean

Bibo-Joshi ***@***.***> 于2023年7月12日周三 18:56写道：
