### ISSUE TITLE
[FEATURE] Add bot mentioned filter

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#3799]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

There is currently no filter defined by us which simply checks if message contains a bot mention, so `@botusername message`.

### Describe the solution you'd like

Make a new filter which checks if a message contains the mention of a bot. So first check if the message has the [`telegram.constants.MessageEntityType.MENTION`](https://docs.python-telegram-bot.org/en/stable/telegram.constants.html#telegram.constants.MessageEntityType.MENTION), and then check if the username is the one of the bot

### Describe alternatives you've considered

One can do this filter by themselves, but providing one would be nice

### Additional context

Maybe having the only_start parameter here would be nice, same as with the command filter.

## Assignees:

~Current assignee: @ElmurodovJavohir - #3857. If they don't commit/reply by Oct 7th, the next in line to tackle this issue is:~

~- @Prathmesh-rajurkar~
~- @AbhigyanBaruah~

Issue is being tackled by dev team due to the continued inactivity from the contributors.

**Comment by shivamsn97** [comment]
I would love to work on this. Please assign me if you would like me to do this.

**Comment by harshil21** [comment]
@shivamsn97 Assigned you 👍

**Comment by Bibo-Joshi** [comment]
Before work goes into a PR for this, I would like to clarify at least the naming of the filter. Also I have two more thoughts:

- I think it would be good to make the filter generic in the way that only the bot but any specified user/chat can be mentioned
- it might even be beneficial to filter for any specified MessageEntity object, optionally with ignoring the offset and length. e.g. You could filter for messages that contain a specific underlined word

**Comment by harshil21** [comment]
> it might even be beneficial to filter for any specified MessageEntity object

We already have [filters.Entity](https://docs.python-telegram-bot.org/en/doc-fixes/telegram.ext.filters.html#telegram.ext.filters.Entity) for this?

**Comment by shivamsn97** [comment]
Got them. Let me know what you think about the naming of the filter.

**Comment by Bibo-Joshi** [comment]
@harshil21 This filters only for the type, not a specific instance. I.e. you can filter for messages that contain any bold word, but not for a specific one

**Comment by Bibo-Joshi** [comment]
Okay, my rambling was nonsense, as `MessageEntity` objects don't contain the text that is formatted. One *could* pass a `MessageEntity` object along with the expected text, but I see that this clumsy to use and the use case is surely minimal.
I would like to see a generic "mention" filter though instead of a specifc "bot mention" filter. I guess it should accept as input a

* a username
* a user id (as string or int)
* a `User` object

and then use a combination of `MessageEntity.user` and `Message.parse_entities` to check if any of the `MENTION` *or* `TEXT_MENTION` entities mentions that user.
Accepting a sequence as input also sounds reasonable, allowing several users to be mentioned.

I guess `filters.Mention` would make sense as name.

@Poolitzer @harshil21 what do you think?

**Comment by aelkheir** [comment]
Hi @shivamsn97, are you still interested in this? I'd love to take it if you found yourself busy, no pressure tho

**Comment by Bibo-Joshi** [comment]
@aelkheir if shivam doesn't reply fover the weekend, I guess you can go ahead and pr :)

**Comment by shivamsn97** [comment]
@Bibo-Joshi the name wasn't finalized yet right? That's what I was waiting for. There was no update from harshil and poolitzer.
Anyways, @aelkheir you can take it if you want, no issues.

**Comment by Bibo-Joshi** [comment]
Ah, right, my bad. let me ping them offline

**Comment by aelkheir** [comment]
> @Bibo-Joshi the name wasn't finalized yet right? That's what I was waiting for. There was no update from harshil and poolitzer. Anyways, @aelkheir you can take it if you want, no issues.

Oh sorry for the confusion. I was just a little excited for my first contribution :). @shivamsn97 you can wait for their input and I'll take the next issue 😄.

**Comment by harshil21** [comment]
> I guess `filters.Mention` would make sense as name.
> 
> @Poolitzer @harshil21 what do you think?

Yes that name and the implementation seems fine with me

**Comment by Bibo-Joshi** [comment]
Poolitzer is currently unavailable, but with harshils approval I'd say we're good to go @shivamsn97  :)

**Comment by shivamsn97** [comment]
Thanks. I'll let you know about any update or questions.

**Comment by aelkheir** [comment]
I see no sign of another good first issue. So consider me standby for this one 👍

**Comment by harshil21** [comment]
@aelkheir #3825 is also a good first issue, if you'd like to do that

**Comment by aelkheir** [comment]
Yes, totally. Replied on the issue.

**Comment by Bibo-Joshi** [comment]
@ElmurodovJavohir Please open a pull request so that we can do a proper review:)

**Comment by ElmurodovJavohir** [comment]
> Accepting a sequence as input also sounds reasonable, allowing several users to be mentioned.

Could you a bit explain about user id and user object, if it possible with example

**Comment by Bibo-Joshi** [comment]
Sorry, I don't understand what exactly you want explained. Please join us at https://t.me/pythontelegrambotchannel/125 for a easier communication.

**Comment by Prathmesh-rajurkar** [comment]
I would love to work on this. Please assign me if you would like me to do this.

**Comment by harshil21** [comment]
> I would love to work on this. Please assign me if you would like me to do this.

There is already an open PR for it (#3857). If @ElmurodovJavohir doesn't commit/reply in a week, we'll close that PR and assign it to you.

**Comment by AbhigyanBaruah** [comment]
Is this issue still open? I'd like to try working on this issue.

**Comment by harshil21** [comment]
> Is this issue still open? I'd like to try working on this issue.

This issue is hot, there is a queue of contributors waiting to finish this, I will edit OP to show status
