### ISSUE TITLE
 'str' object has no attribute 'to_dict' error when calling send_invoice method in python-telegram-bot library.

### ISSUE THREAD

**Issue by jamesvm696** [python-telegram-bot/python-telegram-bot#3805]
### Issue I am facing

I'm attempting to use the send_invoice function in the python-telegram-bot library in my bot to request a payment from a user. However, when calling this function, I encounter an AttributeError: 'str' object has no attribute 'to_dict' exception.

Despite thorough debugging and type-checking all arguments passed to the function, I could not resolve the issue. All types seem to be correct and conform to the documentation, with prices being a list of LabeledPrice objects, which do have a to_dict method.

### Traceback to the issue

```python
Traceback (most recent call last):
  File "C:\Users\James\PycharmProjects\LegitimateChatbotIceAI\IceAI.py", line 85, in send_invoice
    context.bot.send_invoice(
  File "C:\Users\James\PycharmProjects\LegitimateChatbotIceAI\venv\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "C:\Users\James\PycharmProjects\LegitimateChatbotIceAI\venv\lib\site-packages\telegram\bot.py", line 3525, in send_invoice
    'prices': [p.to_dict() for p in prices],
  File "C:\Users\James\PycharmProjects\LegitimateChatbotIceAI\venv\lib\site-packages\telegram\bot.py", line 3525, in <listcomp>
    'prices': [p.to_dict() for p in prices],
AttributeError: 'str' object has no attribute 'to_dict'
```

### Related part of your code

```python
def send_invoice(update: Update, context: CallbackContext) -> None:
    print("send_invoice called")
    chat_id = update.effective_chat.id

    title = "Payment Invoice"
    description = "Test Payment"
    payload = "Custom payload"
    start_parameter = "test-payment"
    currency = "USD"

    price = LabeledPrice("Test", 1000)  # amount is in the smallest units of the currency (cents for USD)
    prices = [price]
    
    try:
        context.bot.send_invoice(
            chat_id, title, description, payload,
            provider_token, start_parameter, currency, prices
        )
    except Exception as e:
        print(f"Error sending invoice: {e}")
```

### Operating System

Microsoft Windows 10, Version 22H2.

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.4
Bot API 6.7
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
```

**Comment by jamesvm696** [comment]
Any help would be incredibly appreciated.

**Comment by Bibo-Joshi** [comment]
Hi. I can not reproduce this problem locally with v20.4. The parsing of the price works just fine.
For more in-depth debugging you could go to the source code of `Bot` and have a look at the value of `prices` (either via printing/logging it, or via a brakepoint).

Also I noticed that you are missing `async` and `wait` in your code snippet and the traceback points to the file `bot.py`, both of which indicates that this code is running on PTB <=v13.15. But you report that you are using v20.4. This doesn't match.

**Comment by jamesvm696** [comment]
Hi Bibo,

interesting, I will look into these now and get back to you with what I find. I Appreciate the swift reply!

**Comment by jamesvm696** [comment]
I believe I may have fixed the issue, thanks to your help. Something I missed was the global environment packages. Thank you for your help Bibo :)
