### ISSUE TITLE
Issue with Payments Through Telegram Bot (Stripe Payment Provider)

### ISSUE THREAD

**Issue by jamesvm696** [python-telegram-bot/python-telegram-bot#3807]
### Issue I am facing

I am currently developing a Telegram bot using the python-telegram-bot library and Stripe as the payment provider. I think i might have an issue with the send_invoice function. When the user selects a service, an invoice is created and sent. However, the transaction does not seem to go through and Stripe does not register any incoming transaction requests. I am going to send the 3 functions that handle the payment. I have attempted to contact telegram but no reply. My issue doesn't give me Traceback, as it happens through the Built in telegram payments system. 

### Related part of your code

```python
def send_invoice(update: Update, context: CallbackContext):
    print("send_invoice called")
    chat_id = update.effective_chat.id
    payload = "Custom payload"
    start_parameter = "time-package"
    currency = "USD"

    # Extract the selected option from the command
    option = update.message.text.split("_")[1]

    # Define the available options and their corresponding descriptions and prices
    options = {
        "5": {"description": "5 Minutes chat time", "price": 500},
        "10": {"description": "10 Minutes chat time", "price": 1000},
        "20": {"description": "20 Minutes chat time", "price": 2000},
        "50": {"description": "50 Minutes chat time", "price": 5000},
        "lifetime": {"description": "Lifetime pass for unlimited chat time", "price": 50000}
    }

    if option in options:
        description = options[option]["description"]
        price = options[option]["price"]
        title = f"Purchase - {description}"
        prices = [LabeledPrice(description, price)]

        try:
            context.bot.send_invoice(chat_id=chat_id, title=title, description=description, payload=payload,
                                     provider_token=provider_token, start_parameter=start_parameter, currency=currency,
                                     prices=prices)
            print(f"Invoice sent for {description}")
        except Exception as e:
            print(f"Error sending invoice for {description}: {e}")
    else:
        print("Invalid option")

def handle_precheckout_query(update, context):
    query = update.pre_checkout_query
    if query.invoice_payload != 'Custom payload':
        context.bot.answer_pre_checkout_query(pre_checkout_query_id=query.id, ok=False,
                                              error_message="Something went wrong...")
    else:
        context.bot.answer_pre_checkout_query(pre_checkout_query_id=query.id, ok=True)

def handle_successful_payment(update, context):
    user_chat_id = update.effective_chat.id
    total_amount = update.effective_message.successful_payment.total_amount / 100  # total_amount is in cents
    seconds_paid = total_amount * 60  # $1 for 60 seconds

    _, _, time_paid, time_left = get_conversation_history(user_chat_id)
    time_paid += total_amount
    time_left += seconds_paid
    store_conversation_history(user_chat_id, 'bot', 'Payment received', 1, time_paid, time_left)

    context.bot.send_message(chat_id=user_chat_id, text=f'Thank you for your payment. You have paid for {seconds_paid} seconds of voice message time.')
```

### Operating System

Microsoft Windows 10, Version 22H2.

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.5
Bot API 5.2
certifi 2023.05.07
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
```

**Comment by jamesvm696** [comment]
2023-07-20 12:39:00,144 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: api.telegram.org
2023-07-20 12:41:33,339 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000002885E196100>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot5896995660:AAFUzrYvwYo83zoO2SfNifbu7wy0uIghRCs/getUpdates

i receive these in my logs when i go to make a purchase but i am unsure if they are relevant.

**Comment by Bibo-Joshi** [comment]
@jamesvm696 Hi. You should revoke the bot takon that you posted as part of the traceback. Apart from that: You seem to be using a version &lt;=13.15 of <code>python-telegram-bot</code>. Please note that we only provide support for the latest stable version and that the library has undergone significant changes in v20. Please consider upgrading to v20 by reading the release notes and the transition guide linked below.

**Comment by jamesvm696** [comment]
awesome thank you mate, i updated to latest version, took a while to change everything to be compatible with v20.4 but its all functioning now. thank you for your help. as a quick sidenote. Could you point me in the right direction of how i would be able to create a UI in telegram that has multiple options. Similar to the way Botfather shows you options for your bot. i will attach an image for reference.
![UI Payments Options](https://github.com/python-telegram-bot/python-telegram-bot/assets/139785263/778adbf1-ac80-497f-94c9-d63124e0673b)

**Comment by Bibo-Joshi** [comment]
@jamesvm696 Have a look at <a href="https://docs.python-telegram-bot.org/examples.html#examples-inlinekeyboard2">inlinekeyboard2.py</a>

**Comment by jamesvm696** [comment]
Thank you for your help once again :)
