### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by david-shiko** [python-telegram-bot/python-telegram-bot#3808]
### Steps to Reproduce

I probably detected a bug, I use ptb v13.11 so I not elaborated a lot on it, but feel free to ask me for details.
The bug:
clicking on button (cbk_handler) that belongs to CH after restarting app just quietly killing app with
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`
Probably this functionality was reworked in latest ptb versions and it's not actual, I described it just in case.

### Expected behaviour

Success cbk handling

### Actual behaviour

`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

### Operating System

GNU/Linux

### Version of Python, python-telegram-bot & dependencies

```shell
pip list | grep -i telegram
python-telegram-bot   13.11
$ python -V
Python 3.10.6
```
```


### Relevant log output

_No response_

### Additional Context

_No response_

**Comment by clot27** [comment]
We dont support version < 20.0 anymore.
