### ISSUE TITLE
Is there a way to use ChosenInlineResult in conversation?

### ISSUE THREAD

**Issue by mohsenjfar** [python-telegram-bot/python-telegram-bot#3810]
### Issue I am facing

I'm wondering is there a way to use **ChosenInlineResult** in **conversations**, I have searched on the internet and haven't found a solution for that.

here is the scenario:
1. I have a bot that manages tasks in a database.
2. a user wants to delete a task
3. they select the task using inline query (results are filtered base on the query)
4. as the task is selected the conversation goes on and confirm for deletion and eventually delete it.

The problem is that the results generated by inline query are handled through just one callback and I couldn't manage to handle them in conversation states.

May be I'm not doing this in a right way, so any suggestions would be very appreciated.
thanks in advance.

P.S: it would also be very useful to know which chat the results come from.

### Related part of your code

```python
task_conv = ConversationHandler(
        entry_points=[
            CallbackQueryHandler(remove_task, pattern=f"^{DELETE}$")
        ],
        states={

            ...

            DELETE : [
                ChosenInlineResultHandler(remove_task_query) #Here is what i want to do
            ],

           ...

        },
        fallbacks=[
            CallbackQueryHandler(select_cancel, pattern=f"^{CANCEL}$")
        ]
    )
```

### Operating System

linux (debian 11)

### Version of Python, python-telegram-bot & dependencies

```shell
3.9
```

**Comment by Bibo-Joshi** [comment]
@mohsenjfar Hi. Please have a look at <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#what-do-the-per_-settings-in-conversationhandler-do">What do the per_* settings in ConversationHandler do?</a>. <code>ConversationHandler</code> even issues a warning about this if a <code>ChosenInlineResultHandler</code> is used, you should se ethat in your terminal 😉

**Comment by mohsenjfar** [comment]
Dear @Bibo-Joshi , thank you so much for you reply and time. I hope this doesn't sound silly, but I changed per_chat to false and again the handler is not triggered. 

When I put the handler outside conversation, it works just fine.

Thank you
