### ISSUE TITLE
[BUG]: `telegram.ext.Application.builder().proxy_url(...)` doesn't work for all requests

### ISSUE THREAD

**Issue by trim21** [python-telegram-bot/python-telegram-bot#3815]
### Steps to Reproduce

I'm in a network environment which doesn't have direct access to telegram, so I'll have to use proxy for all my http requests to telegram http API.

But, when I set proxy with `telegram.ext.Application.builder().proxy_url('...')`, I can only receive partial message, and can't handle message correctly.

I add a debug print here:

https://github.com/python-telegram-bot/python-telegram-bot/blob/7226aaea04d2e652a566164472a8b1d8d9fa8749/telegram/request/_httpxrequest.py#L158-L159

I can see that this method is called twice, once with `'proxies': ...` and once it's `'proxies': None`.

So some requests are broken.

I add some lines to get the full stack trace:

```diff
    def _build_client(self) -> httpx.AsyncClient:
+        print(self._client_kwargs)
+        if self._client_kwargs['proxies'] is None:
+            raise  Exception("proxies not working")
        return httpx.AsyncClient(**self._client_kwargs)  # type: ignore[arg-type]
```

and the stack trace is 

```text
Traceback (most recent call last):
  File "...\telegram-bot\main.py", line 98, in <module>
    main()
  File "...\telegram-bot\main.py", line 80, in main
    application = application.build()
  File "...\telegram-bot\.venv\lib\site-packages\telegram\ext\_applicationbuilder.py", line 289, in build
    bot: Bot = self._build_ext_bot()  # build a bot
  File "...\telegram-bot\.venv\lib\site-packages\telegram\ext\_applicationbuilder.py", line 260, in _build_ext_bot
    get_updates_request=self._build_request(get_updates=True),
  File "...\telegram-bot\.venv\lib\site-packages\telegram\ext\_applicationbuilder.py", line 240, in _build_request
    return HTTPXRequest(
  File "...\telegram-bot\.venv\lib\site-packages\telegram\request\_httpxrequest.py", line 134, in __init__
    self._client = self._build_client()
  File "...\telegram-bot\.venv\lib\site-packages\telegram\request\_httpxrequest.py", line 161, in _build_client
    raise  Exception("proxies not working")
```

### Expected behaviour

all requests send by application should use proxy

### Actual behaviour

some request are not using requests

### Operating System

windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.4
Bot API 6.7
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
```

### Additional Context

my startup code：

```python
    application = tg.ext.Application.builder().token(config.TELEGRAM_BOT_TOKEN)

    if sys.platform == "win32":
        application = application.proxy_url("...")

    application = application.build()
```

**Comment by harshil21** [comment]
@trim21 have you also tried using <a href="https://docs.python-telegram-bot.org/telegram.ext.applicationbuilder.html#telegram.ext.ApplicationBuilder.get_updates_proxy_url">telegram.ext.ApplicationBuilder.get_updates_proxy_url</a>? Also that exception is happening because you added that exception?

**Comment by trim21** [comment]
> that exception is happening because you added that exception?

this exception is happening because you added this exception to show the stace trace, code raise exception is not part of the library itself.

**Comment by trim21** [comment]
Ok, I see, some http request's proxy need to be set with `get_updates_proxy_url`.

**Comment by harshil21** [comment]
> Ok, I see, some http request's proxy need to be set with `get_updates_proxy_url`.

yes

Though I don't know how you got `'procies': ...` in the `self._client_kwargs`. That shouldn't happen

**Comment by trim21** [comment]
> > Ok, I see, some http request's proxy need to be set with `get_updates_proxy_url`.
> 
> yes
> 
> Though I don't know how you got `'procies': ...` in the `self._client_kwargs`. That shouldn't happen

that's a typo, is't `proxies`

**Comment by trim21** [comment]
Then I think the document need to be updated...
