### ISSUE TITLE
504 gateway error nginx

### ISSUE THREAD

**Issue by d3c0b81f** [python-telegram-bot/python-telegram-bot#382]
### Expected behaviour
504 NGINX Gateway error on set webhook
How to check webhook state? Bot doesn't send any message.

Sorry for my english :(

### Configuration
**Operating System:**
Debian GNU/Linux 8.5 (jessie)

**Python Code**
```
 start_handler = CommandHandler('start', start)
 echo_handler = MessageHandler([Filters.text], message_listener)
 updater.dispatcher.add_handler(CallbackQueryHandler(callback_query_handler))
 updater.dispatcher.add_handler(start_handler)
 updater.dispatcher.add_handler(echo_handler)
 token = settings.TELEGRAM_BOT_TOKEN

 updater.start_webhook(listen='127.0.0.1', port=5000, url_path=token)
 updater.bot.setWebhook(url='https://myurl/%s' % token,
                        certificate=open('/path/to/key/cert.pem', 'rb'))
```

**Nginx Configuration**
![aptekabot](https://cloud.githubusercontent.com/assets/19824363/17694208/321be600-63bc-11e6-9802-d49697c46f81.png)

**Netstat response**
![aptekabot](https://cloud.githubusercontent.com/assets/19824363/17694637/3550a07a-63be-11e6-9cb7-a02fa7d9526e.png)

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
python-telegram-bot 5.0.0
certifi 2016.08.08
urllib3 1.16
future 0.15.2

**Comment by jh0ker** [comment]
Hi!
Could you try removing the `url_path=token` from `setWebhook`?

**Comment by jh0ker** [comment]
Sorry, I mean `start_webhook`
