### ISSUE TITLE
[FEATURE] Story / stories support

### ISSUE THREAD

**Issue by Geczy** [python-telegram-bot/python-telegram-bot#3833]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Add stories via python to your profile

### Describe the solution you'd like

VIa code

**Comment by Bibo-Joshi** [comment]
@Geczy Wiki of <i>python-telegram-bot</i> - Category <i>FAQ</i>
<a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#can-you-add-feature-to-ptb-can-i-do-thing-with-my-bot">Can you add [feature] to PTB? Can I do [thing] with my bot?</a>
