### ISSUE TITLE
[FEATURE] warn if `ConversationHandler.states` has a key -1

### ISSUE THREAD

**Issue by DonutByte** [python-telegram-bot/python-telegram-bot#3834]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

I have now experienced the most frustrating side effect caused by `ConversationHandler.END` being set to -1.
I had a `CH` state key which was set to -1 and my entry point returned that state.
it caused the `CH` to exit (-1 is also `END`) right after my entry point which confused me.

here is an MWE which explains it better than I can with words:
https://pastebin.com/bk8MhwiX

to reproduce:
/start
pick any button - expected to continue the conversation, but instead the bot doesn't respond

### Describe the solution you'd like

I thought maybe PTB can warn if -1 is set in `ConversationHandler.states` so nobody else has to experience it too :)
AFAIK there's no harm doing so because setting a state key to -1 is useless, it'll never get triggered

**Comment by Bibo-Joshi** [comment]
I suggest to add this to #2770

**Comment by Bibo-Joshi** [comment]
Added to #2770. Closing this in favor of tracking everything in #2770
