### ISSUE TITLE
[QUESTION] Test Stripe payment error 

### ISSUE THREAD

**Issue by navin-hariharan** [python-telegram-bot/python-telegram-bot#3836]
### Steps to Reproduce

1.  Get the BOT_TOKEN and PAYMENT_PROVIDER_TOKEN [test]
2. run my code
3. My test stripe is not working with the test cards 4242 4242 4242 4242

### Expected behaviour

Successful payment

### Actual behaviour

I am getting the bot could not process your payment 

### Operating System

windows

### Version of Python, python-telegram-bot & dependencies

```shell
import logging
from telegram import LabeledPrice, Update
from telegram.ext import (ContextTypes, Application, CommandHandler, PreCheckoutQueryHandler, MessageHandler, filters)

# Enable logging
logging.basicConfig(format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO)
logging.getLogger("httpx").setLevel(logging.WARNING)
logger = logging.getLogger(__name__)

PAYMENT_PROVIDER_TOKEN = "PAYMENT_PROVIDER_TOKEN "

async def start_callback(update: Update, context) -> None:
    msg = ("/noshipping for an invoice without shipping.")
    await update.message.reply_text(msg)

async def buy_laksha_credits_callback(update: Update, context) -> None:
    chat_id = update.message.chat_id
    title = "LAKSHNA AI - LAKSHA CREDITS"
    description = "LAKSHA CREDITS 100 🪙"
    payload = "Custom-Payload"
    currency = "INR"
    prices = [LabeledPrice("Subtotal", 100 * 100), LabeledPrice("Handling", 3 * 100)]
    await context.bot.send_invoice(
        chat_id,
        title,
        description,
        payload,
        PAYMENT_PROVIDER_TOKEN,
        currency,
        prices,
        need_email=True,
        photo_url='https://play-lh.googleusercontent.com/A2IZkHB9QKlLbhuVSOvU3lt2_g_R2O48pXqePmqmCqjcXkDSbbJfbO_RV2Ai1omGcg=w240-h480-rw'
    )

async def precheckout_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    query = update.pre_checkout_query
    if query.invoice_payload != "Custom-Payload":
        await query.answer(ok=False, error_message="Something went wrong...")
    else:
        await query.answer(ok=True)

async def successful_payment_callback(update: Update, context) -> None:
    await update.message.reply_text("Thank you for your payment!")

def main() -> None:
    application = Application.builder().token("BOT_TOKEN").build()

    application.add_handler(CommandHandler("start", start_callback))
    application.add_handler(CommandHandler("buy", buy_laksha_credits_callback))
    application.add_handler(PreCheckoutQueryHandler(precheckout_callback))
    application.add_handler(MessageHandler(filters.SUCCESSFUL_PAYMENT, successful_payment_callback))

    application.run_polling(allowed_updates=Update.ALL_TYPES)

if __name__ == "__main__":
    main()
```

### Relevant log output

```python
No error in console
```

**Comment by Bibo-Joshi** [comment]
> I am getting the bot could not process your payment

Where do you see this? Is this an exception that you see in the console? Is it a promt that you see in the Telegram app (if so: please attached a screenshot)?

**Comment by navin-hariharan** [comment]
![Screenshot 2023-08-11 031139](https://github.com/python-telegram-bot/python-telegram-bot/assets/42506955/2d664dec-a8c1-44c2-b028-af3eda173cec)
![Screenshot 2023-08-11 031200](https://github.com/python-telegram-bot/python-telegram-bot/assets/42506955/ed99c447-13e4-4225-bab8-e785043b80bc)



It's a promt that I see in the Telegram app

**Comment by navin-hariharan** [comment]
> > I am getting the bot could not process your payment
> 
> Where do you see this? Is this an exception that you see in the console? Is it a prompt that you see in the Telegram app (if so: please attached a screenshot)?

Find anything that could fix this?

**Comment by Bibo-Joshi** [comment]
Hi. Sorry, I thought I had replied. The step where the problem happens is invisible to the Bot API, so PTB can't do anything about it. I suggest to try different test credit cards or to reach out to the payment provider or/and TG.
