### ISSUE TITLE
Running inside an event loop

### ISSUE THREAD

**Issue by Corfucinas** [python-telegram-bot/python-telegram-bot#3842]
### Issue I am facing

How do I start the bot inside an asyncio coroutine?

I'm currently running an event loop for handling a message queue, while the telegram bot is being started with a `Process`, but I think this is not the way to go, just to spin a thread for handling the bot.

Is there's a way to initialize the application in a `asyncio.gather`?

### Operating System

Ubuntu-latest

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.2 (0.6.1-78-g6340a92)
Bot API 6.6
Python 3.11.2 (main, Mar 18 2023, 12:39:58) [GCC 12.2.0]
```

**Comment by Bibo-Joshi** [comment]
@Corfucinas I&#x27;m not sure if I understand your setup. <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#running-ptb-alongside-other-asyncio-frameworks">Running PTB alongside other asyncio frameworks</a> *may* be of help for you though.
