### ISSUE TITLE
[FEATURE] Make the `BaseHandler.callback` Attribute Private

### ISSUE THREAD

**Issue by Samylov-Mikhail** [python-telegram-bot/python-telegram-bot#3848]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

The `BaseHandler` class has the public documented `callback` attribute. The `ConversationHandler`, being a subtype of the `BaseHandler`, does not have it, which violates the [Liskov substitution principle (LSP)](https://en.wikipedia.org/wiki/Liskov_substitution_principle).
The `callback` attribute is not tested directly.
Also it does not make sense (see Additional context).

### Describe the solution you'd like

Make the `BaseHandler.callback` attribute private.

### Additional context

The `BaseHandler.callback` attribute is only used in one place in the PTB:
https://github.com/python-telegram-bot/python-telegram-bot/blob/5128748092da3b6f7d827e01019327d9baf63fa5/telegram/ext/_conversationhandler.py#L896-L901
And it is not used in examples at all.

**Comment by Samylov-Mikhail** [comment]
Please assign this issue to me.

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for reaching out.
We're aware that the current implementation of ConversationHandler violates best practice of class inheritance. Refactoring that handler is a long standing topic on the roadmap: #2770.
For all other handlers, the current handling of the `callback` argument/attribute is well define though and it is an essential part of `BaseHandler.handle_update`. I therefore see no reason to change anything about this in `BaseHandler.`
