### ISSUE TITLE
Can Celery and gevent work with ptb? 

### ISSUE THREAD

**Issue by tima2000** [python-telegram-bot/python-telegram-bot#3856]
### Steps to Reproduce

1. Create file called celery-telegram.py and paste below sample code from celery website and just import into that code telegram module.

```
import telegram
from celery import Celery
app = Celery('tasks', broker='redis://:qwerty@localhost:6379/0')

@app.task
def add(x, y):
    return x + y
```
4. then run celery 
`celery -A celery-telegram worker --loglevel=INFO --concurrency=10 -P gevent
`

### Expected behaviour

celery should run with no problem

```
 -------------- celery@kub01 v5.3.1 (emerald-rush)
--- ***** -----
-- ******* ---- Linux-5.15.0-78-generic-x86_64-with-glibc2.35 2023-08-22 10:51:46
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x7f8bc96037f0
- ** ---------- .> transport:   redis://:**@localhost:6379/0
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 16 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery


[tasks]
  . celery-telegram.add
```

### Actual behaviour

```
Usage: celery [OPTIONS] COMMAND [ARGS]...
Try 'celery --help' for help.

Error: Invalid value for '-A' / '--app':
Unable to load celery application.
Module 'select' has no attribute 'epoll'


```

### Operating System

Ubuntu 22.04.2 LTS

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.4
Bot API 6.7
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
```

### Additional Context

You can run provide code with no problem when import telegram is commented.

**Comment by tsnoam** [comment]
Looking at the snippet and the error message it seems that the combined usage the epoll asyncio (by ptb) with gevent of a celery worker is causing the fatal error. 

Also, afaik, Celery is not asyncio compatible (though my knowledge might be out of date on that).

I think that this is all out of scope for ptb. @Bibo-Joshi any thoughts?

**Comment by tsnoam** [comment]
Event though out of scope in my opinion, some things to try:
* import telegram after importing celery
* don't use gevent with celery
* Try this package: https://pypi.org/project/asyncio-gevent/ (fair disclosure: I have no experience with it, I just found it online)
