### ISSUE TITLE
Flag emoji

### ISSUE THREAD

**Issue by d3c0b81f** [python-telegram-bot/python-telegram-bot#387]
Emoji class doensn't have flag emoji's?

**Comment by rahiel** [comment]
> Emoji class doensn't have flag emoji's?

Yes, the Emoji class is incomplete and not recommended.

You can search the [emoji list](http://www.unicode.org/emoji/charts/full-emoji-list.html) for the (country flag) emoji you want and use it as described on the  [new wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Emoji).
