### ISSUE TITLE
[Feature Request] Support InternLM

### ISSUE THREAD

**Issue by vansinhu** [python-telegram-bot/python-telegram-bot#3875]
Dear python-telegram-bot developer,

Greetings! I am vansinhu, a community developer and volunteer at InternLM. Your work has been immensely beneficial to me, and I believe it can be effectively utilized in InternLM as well. Welcome to add Discord https://discord.gg/gF9ezcmtM3 . I hope to get in touch with you.

Best regards,
vansinhu

**Comment by Poolitzer** [comment]
Hello there. Nice to hear that our work has been beneficial to you.

We do not believe in having closed off conversations in a non public space like discord. We prefer having those right here on GitHub, so everyone can chime in.

If you want to use our library in your project, you don't have to ask us for permission, just be sure to follow our license.
