### ISSUE TITLE
[QUESTION] Persistence breaks

### ISSUE THREAD

**Issue by bauermarkus** [python-telegram-bot/python-telegram-bot#3877]
### Steps to Reproduce

This is a follow up to #3835

I created a repository with a MVE: https://github.com/bauermarkus/PTB_persistence

The problem is
`TypeError: cannot pickle 'pyodbc.Cursor' object`

### Expected behaviour

Output every second `Update bot data`

### Actual behaviour

No output

### Operating System

Windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.4
Bot API 6.7
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
```

### Relevant log output
```
.venv\lib\site-packages\telegram\ext\_application.py", line 1538, in __update_persistence
    coroutines.add(self.persistence.update_bot_data(deepcopy(self.bot_data)))
  File "C:\Program Files\Python39\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Python39\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Program Files\Python39\lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'pyodbc.Cursor' object
```

**Comment by Bibo-Joshi** [comment]
@bauermarkus Hi. The <a href="https://docs.python.org/3/library/pickle.html#module-pickle">pickle</a> module that PicklePersistence is build on has its limitations. This is well documented in the Python docs and not a limitation on PicklePersistence itself.

**Comment by bauermarkus** [comment]
@Bibo-Joshi 

But my persistence is derived from `BasePersistence`

I updated the original post

**Comment by bauermarkus** [comment]
Here is the code directly

```
from typing import Any, Dict, Optional
from telegram.ext import BasePersistence, PersistenceInput
from telegram.ext._utils.types import CDCData, ConversationDict, ConversationKey

import logging

class Persistence(BasePersistence):
    def __init__(self, users: list, cursor):

        self._store_data = PersistenceInput(
            True, # bot_data
            False, # chat_data
            False, # user_data
            False,  # callback_data
        )

        super().__init__(store_data=self._store_data, update_interval=1)
        self._users = users
        self._cursor = cursor

    async def get_bot_data(self):
        return {'users': self._users, 'cursor': self._cursor}
    async def update_bot_data(self, data) -> None:
        print("Update bot data")
        logging.getLogger().info("Update bot data")
    async def refresh_bot_data(self, bot_data) -> None:
        print("Refresh:",bot_data)
        

    async def get_chat_data(self) -> Dict[int, Any]:
        pass
    async def update_chat_data(self, chat_id: int, data: Any) -> None:
        pass
    async def refresh_chat_data(self, chat_id: int, chat_data: Any) -> None:
        pass
    async def drop_chat_data(self, chat_id: int) -> None:
        pass

    async def get_user_data(self) -> Dict[int, Any]:
        pass
    async def update_user_data(self, user_id: int, data: Any) -> None:
        pass
    async def refresh_user_data(self, user_id: int, user_data: Any) -> None:
        pass
    async def drop_user_data(self, user_id: int) -> None:
        pass

    async def get_callback_data(self) -> CDCData or None:
        pass
    async def update_callback_data(self, data: CDCData) -> None:
        pass

    async def get_conversations(self, name: str) -> ConversationDict:
        pass
    async def update_conversation(self, name: str, key: ConversationKey, new_state: object or None) -> None:
        pass

    async def flush(self) -> None:
        pass
```

**Comment by Bibo-Joshi** [comment]
I see. The problem the is that all data is being deep-copied while passing through [update_perstistemce](https://docs.python-telegram-bot.org/en/v20.5/telegram.ext.application.html#telegram.ext.Application.update_persistence). deepcopy and pickle use a common interface. So the error message is a bit confusing, but not wrong :)

**Comment by bauermarkus** [comment]
@Bibo-Joshi Thanks
Can you please change the issue to a "question" and tell me, how to save such a object properly?

**Comment by Bibo-Joshi** [comment]
I do not know how such an object can be copied or even serialized. That's also beyond the scope of PTB. Not that if you simply want to have global access to your cursor object, it might be enough to define it as global constant or make it available via the context object via CustomContextTypes (see also the corresponding example in the examples section in the docs).

**Comment by bauermarkus** [comment]
I guess that's what I need

>  make it available via the context object via CustomContextTypes (see also the corresponding example in the examples section in the docs).
I'll have a look

**Comment by bauermarkus** [comment]
Ok I tried to work with the context and failed and while I was searching why I was failing, it seems like I failed already in the persistence

```
2023-09-11 22:31:11,523 - telegram.ext.Application - INFO - Application started
2023-09-11 22:31:34,807 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "c:\Projekte\i40\PTB_persistence\.venv\lib\site-packages\telegram\ext\_application.py", line 1173, in process_update
    await coroutine
  File "c:\Projekte\i40\PTB_persistence\.venv\lib\site-packages\telegram\ext\_basehandler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "C:\Projekte\i40\PTB_persistence\bot.py", line 15, in inner
    return await func(update, context, *args, **kwargs)
  File "C:\Projekte\i40\PTB_persistence\bot.py", line 35, in save
    context.bot_data['save'] += msg
KeyError: 'save'
```

I tried to update like this in a `MessageHandler`:
```
@userHandler
async def save(update: Update, context: ContextTypes.DEFAULT_TYPE):
    msg = update.message.text.strip()
    context.bot_data['save'] += msg
    await context.bot.send_message(chat_id=update.effective_chat.id, text=context.context.bot_data['save'])
```
Full bot is still on [Github](https://github.com/bauermarkus/PTB_persistence)

**Comment by Bibo-Joshi** [comment]
This is now a general question on dictionaries in python - i.e. you will have to make sure that the entry in bot_data exists before trying to increment the value

**Comment by bauermarkus** [comment]
F.... Thanks a lot!

The customContext also does it's job as far as I can tell now

Thanks a lot for your help and patience
