### ISSUE TITLE
using in pydroid

### ISSUE THREAD

**Issue by tsalehm** [python-telegram-bot/python-telegram-bot#3885]
### Issue I am facing

can't run in pydroid

ModuleNotFoundError: no module named 'telegram'
but python-telegram-bot 20.5 is installed

### Operating System

android

### Version of Python, python-telegram-bot & dependencies

```shell
20.5
```

**Comment by Bibo-Joshi** [comment]
@tsalehm Please make sure that you have installed PTB for the same Python version or virtual environment that your are using. However this is a rather general question on python package management in pydroid and this is out of scope for this issue tracker
