### ISSUE TITLE
[Documentation]: Context manager dunder Methods

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#3886]
The dunder methods `__aenter__` and `__aexit__` that are implemented in several classes in `tg.(ext)` (Updater, Application, Bot, BaseRequest, BaseUpdateProcessor) should get docstrings that explain how these methods behave.

* Since the behavior is very similar in most cases, usage of sphinx insertions may be beneficial
* The notes that we currently have in the class docstring regarding context manager behavior can possibly be (party) replaced by references to these methods
* Sphinx needs to be configured to show these docstrings

**Comment by Anshika91** [comment]
add _repr_ methods
