### ISSUE TITLE
[QUESTION] Callback Query from different users in Conversation Handler

### ISSUE THREAD

**Issue by lucasmolinari** [python-telegram-bot/python-telegram-bot#3897]
### Callback Query from different users

``I'm working in a bot where a user can make a request to another user in a group, the bot is only a intermediary between both. For e.g,  user 1 sends a command replying to a user 2 message, then the bot sends a inline keyboard in the group where user 2 can choose to accept or refuse user 1 request.

The issue is that the inline keyboard queryback only accepts input from user 1 (that called the command) and never accepts user 2 input. 
Also, I'm using a conversation handler, maybe that's the issue? The conversation handler is necessary since the bot can't respond to another commands while the trade is being made.

### Related part of your code

```python
if message_type == 'group':
        # Get requester and replier information
        requester_id = update.effective_user.id
        replier_id = update.message.reply_to_message.from_user.id
         
        keyboard = [[
            InlineKeyboardButton('Accept', callback_data=1),
            InlineKeyboardButton('Reject', callback_data=0),
        ]
        ]
        
        await context.bot.send_message(chat_id=group_id, text=text, reply_markup=reply_markup, parse_mode='Markdown')

async def trade_callback(update: Update, Context: ContextTypes.DEFAULT_TYPE) -> None:
   # Here the bot only receives 'user 1' query, I need 'user 2'
    query = update.callback_query
    await query.answer()
    if query.data:
        await query.edit_message_text('Trade accepted')
    else:
        await query.edit_message_text('Trade rejected')

    return ConversationHandler.END
```

### Operating System

Windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.4
Bot API 6.7
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
PS C:\projects\RollCardBot>
```

**Comment by Bibo-Joshi** [comment]
@lucasmolinari Hi. Please have a look at this wiki entry: <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#what-do-the-per_-settings-in-conversationhandler-do">What do the per_* settings in ConversationHandler do?</a>

**Comment by lucasmolinari** [comment]
@Bibo-Joshi Thanks, that should fix my issue.
