### ISSUE TITLE
[documentation]: User input command is not clear in the "Extensions Your first Bot" file for the CAPS function.

### ISSUE THREAD

**Issue by Billa05** [python-telegram-bot/python-telegram-bot#3904]
### Steps to Reproduce

1. Go to README.rst
2. Then go to [Tutorial: Your first Bot](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions---Your-first-Bot)
3. see the CAPS function tutorial 

### Expected behaviour

The code is okay but for a newbie doing the tutorial the command he is giving to the telegram bot should be clear

like for me, this was the issue:
![Screenshot 2023-09-27 234346](https://github.com/python-telegram-bot/python-telegram-bot/assets/90760974/8a531371-216c-4fad-a855-6a643f1647d3)

here I thought after giving the "/caps" command I had to give a word to capitalise but it should have been with the command only like in the picture

### Actual behaviour

a new commer would think that after giving a command, we have to give input, so it gives the same input as an output as we have another function (echo) that returns the same input if it is not a command.

![Screenshot 2023-09-28 002133](https://github.com/python-telegram-bot/python-telegram-bot/assets/90760974/ab5f3a61-5658-4c1b-9b8d-2c1e4132a091)

### Operating System

windows 11

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.5
Bot API 6.8
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
Thanks for reaching out. I added a short inline example :)
