### ISSUE TITLE
Send image from URL

### ISSUE THREAD

**Issue by bvanrijn** [python-telegram-bot/python-telegram-bot#391]
### Steps to reproduce
N/A

### Expected behaviour
I'd like to see a way to send a photo from a given URL, either through sendPhoto or a new function

### Actual behaviour
Right now, you can't (easily), ~~resulting in [weird errors](https://github.com/bvanrijn/archillect/issues/1)~~

### Configuration
**Operating System:**
Ubuntu 14.04 and 16.04

**Version of Python, python-telegram-bot & dependencies:**
2.7, 4.2.1 (but this is a version-independent feature request)

    $ python -m telegram
    /usr/bin/python: No module named telegram.__main__; 'telegram' is a package and cannot be directly executed

### Logs
N/A

**Comment by bomjacob** [comment]
_If_ we _do_ add this, we should definitely do it for all the `send_*` methods, not just photo.

**Comment by jh0ker** [comment]
From the [Wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#general-code-snippets):

> To post a file from an URL, this library offers a shortcut. You can pass the URL of the file, instead of downloading the file first. If you do that, the file will be downloaded and directly streamed into the response to Telegram.
> ```python
> >>> bot.sendPhoto(chat_id=chat_id, photo='https://telegram.org/img/t_logo.png')
> ```

Is this maybe what you want?

**Comment by bomjacob** [comment]
@jh0ker Oh .-.
On another note, should the wiki be updated to use snake_case names instead of camelCase?

**Comment by bvanrijn** [comment]
@bomjacob Please open a new issue, as I'm going to close this one. Thanks.
