### ISSUE TITLE
[QUESTION] Chat action not displaying in chat

### ISSUE THREAD

**Issue by Fonti49** [python-telegram-bot/python-telegram-bot#3923]
### Steps to Reproduce

Use the send_chat_action method in a "MessageHandler" callback for exemple.

`test = await update.effective_chat.send_chat_action(action="upload_document")
`
Here is the callback function.
```
async def brainstorm_subject_response(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
	# Create a new keyboard.
	user = update.message.from_user
	logger.info("Brainstorm of %s: %s", user.first_name, update.message.text)	
	# Send typing action
	test = await update.effective_chat.send_chat_action(action="upload_document")
	# define user_prompt and system_prompt
	user_prompt, system_prompt = get_brainstorm_prompt(update.message.text)
	gpt_response = await call_simple_chat_completion(user_prompt, system_prompt)
	response_txt = f"Voici mon brainstorm !\n\n" \
	f"{gpt_response.choices[0].message.content}"
```

Tried with several calls : 
`await context.bot.send_chat_action(chat_id=update.message.chat_id, action="typing")
`

### Expected behaviour

Typing should appear on screen.

### Actual behaviour

Nothing happens.

### Operating System

Windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.5
Bot API 6.8
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
```

**Comment by Poolitzer** [comment]
It gets reset when another action happens in the chat. So if your gpt response is too quick, you might not see it

**Comment by Fonti49** [comment]
@Poolitzer  thanks for your answer but I'm calling openAI so it takes some time.
+ I tried with a timer, still no result.

**Comment by Poolitzer** [comment]
Okay, I am not sure what you are doing wrongly, it works for me.

```python
async def msg_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
        test = await update.effective_chat.send_chat_action(action="upload_document")
        await asyncio.sleep(5)
        await update.effective_chat.send_message("hiiii")

def main() -> None:
    application = Application.builder().token("TOKEN").build()
    application.add_handler(CommandHandler("test", msg_handler))
    application.run_polling(allowed_updates=Update.ALL_TYPES)


```

**Comment by harshil21** [comment]
This is usually a client dependent thing. Can you see the action on Tdesktop / official android client? IIRC, Telegram X had issues showing the typing status from bots.
