### ISSUE TITLE
[QUESTION] Not receiving ChatMemberUpdated.invite_link upon using invite link to join Private Group

### ISSUE THREAD

**Issue by v8ive** [python-telegram-bot/python-telegram-bot#3927]
### Issue I am facing

Hey there! So I've been piecing together a quite simple bot. My main goal is to track invite uses and reward users for inviting members. While I was digging, I came across the **ChatMemberUpdated** class. I used `update.chat_member.invite_link` to access the invite link that was used to join the group. This worked fined for a few tries, but all of a sudden I am getting nothing for the invite_link.

It may be worth noting that I am joining/leaving the group in order to catch the updates in the console to test the functionality. Maybe when a member rejoins a group, an invite link isnt passed?

Any help would be greatly appreciated!

### Traceback to the issue

```python
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/telegram/ext/_application.py", line 1195, in process_update
    await coroutine
  File "/home/container/.local/lib/python3.10/site-packages/telegram/ext/_basehandler.py", line 153, in handle_update
    return await self.callback(update, context)
  File "/home/container/bot.py", line 110, in greet_chat_members
    invite_link = update.chat_member.invite_link.invite_link
AttributeError: 'NoneType' object has no attribute 'invite_link
```

### Related part of your code

```python
async def greet_chat_members(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Greets new users in chats and announces when someone leaves"""
    result = extract_status_change(update.chat_member)
    if result is None:
        return
    was_member, is_member = result
    from_user = update.chat_member.from_user
    new_member = update.chat_member.new_chat_member.user

    if not was_member and is_member:
        # Member Joined
        invite_link = update.chat_member.invite_link.invite_link
            
```
and lower in the handlers...

```python

def startup() -> None:
    """Start the bot."""
    # Create the Application and pass it your bot's token.
    bot_token = os.getenv("BOT_TOKEN")
    application = ApplicationBuilder().token(bot_token).build()

    application.add_handler(ChatMemberHandler(greet_chat_members, 0))

    application.add_handler(CommandHandler("start", start))

    application.run_polling(allowed_updates=Update.ALL_TYPES)


if __name__ == "__main__":
    startup()

```

### Operating System

Windows 11
*though I am hosting the bot on Sparked Host, which has nothing to do with the error as I had success before*

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.5
Bot API 6.8
Python 3.10
```

**Comment by Bibo-Joshi** [comment]
Hi. Is your group public or private?

**Comment by v8ive** [comment]
> Hi. Is your group public or private?
> Edit: sorry, the title already says private. I asked because this made me think of https://github.com/tdlib/telegram-bot-api/issues/428, but that is only relevant for public groups 

Yea no worries. I thought maybe it had something to do with the fact it was a private group. Whats weird though is I have it in two groups. When I create an invite link in one group, the invite link shows up in the "Invite Links" as created by the bot. However, in the other group it shows no new links upon creating one....I'm really not sure what the expected outcome should be, but it's been so iffy...
