### ISSUE TITLE
[BUG] Incorrect sticker emoji API

### ISSUE THREAD

**Issue by maksloboda** [python-telegram-bot/python-telegram-bot#3928]
### Steps to Reproduce

1. Make bot create a sticker 
2. Set associated emoji to 👨‍👧‍👦

### Expected behaviour

Sticker is created and associated emoji is 👨‍👧‍👦

### Actual behaviour

You get an error "Can't parse sticker: expected a unicode emoji"

### Operating System

Pop os (Ubuntu) and Android

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.6
Bot API 6.9
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
```

### Relevant log output

```python
2023-10-11 00:19:18,603 - httpx - INFO - HTTP Request: POST https://api.telegram.org/[REDACTED]/getUpdates "HTTP/1.1 200 OK"
2023-10-11 00:19:18,871 - httpx - INFO - HTTP Request: POST https://api.telegram.org/[REDACTED]/sendMessage "HTTP/1.1 200 OK"
2023-10-11 00:19:24,977 - httpx - INFO - HTTP Request: POST https://api.telegram.org/[REDACTED]/getUpdates "HTTP/1.1 200 OK"
2023-10-11 00:19:25,117 - httpx - INFO - HTTP Request: POST https://api.telegram.org/[REDACTED]/getFile "HTTP/1.1 200 OK"
2023-10-11 00:19:25,210 - httpx - INFO - HTTP Request: GET https://api.telegram.org/file/[REDACTED]/stickers/file_2.webp "HTTP/1.1 200 OK"
2023-10-11 00:19:25,213 - __main__ - INFO - 👨‍👧‍👦
2023-10-11 00:19:25,441 - httpx - INFO - HTTP Request: POST https://api.telegram.org/[REDACTED]/addStickerToSet "HTTP/1.1 400 Bad Request"
2023-10-11 00:19:25,443 - __main__ - ERROR - Can't parse sticker: expected a unicode emoji
```

### Additional Context

This is not a singular emoji but rather multiple emojis joined with special characters.
Instead of putting this groupped emoji into the array it is split into parts, and since special characters are not emojis we get an error.

This line contains incorrect behaviour
https://github.com/python-telegram-bot/python-telegram-bot/blob/af130ef5e72d00695b4bbf5e9ddf17e76bcab674/telegram/_files/inputsticker.py#L93

Perhaps we should usethe analyze method with emoji groupping from the package  [emoji](https://github.com/carpedm20/emoji) package or allow to pass a raw array.

**Comment by maksloboda** [comment]
Also there are stickers like this one
![image](https://github.com/python-telegram-bot/python-telegram-bot/assets/26490401/3e7ea5df-0772-4821-9ad1-c19a7caed57a)
from pack: https://t.me/addstickers/urr_vk
It has one emoji that is made of 2 symbols, first is the emoji and the second one is an invisible symbol

**Comment by Bibo-Joshi** [comment]
Thanks for reaching out! At first glance it looks like `parse_sequence_arg` should just return the input unchanged if it is a string. Unfortunately I probably won't be able to test this in the next few days.

**Comment by maksloboda** [comment]
> Thanks for reaching out! At first glance it looks like `parse_sequence_arg` should just return the input unchanged if it is a string. Unfortunately I probably won't be able to test this in the next few days.

It will return a tuple containing 3 emojis and multiple special invisible symbols in the first case as it is not a string of size 1.
In the second case it will return tuple of size 2.

**Comment by Bibo-Joshi** [comment]
@maksloboda Yes, that&#x27;s what&#x27;s currently happening. What I mean is that the function should be adapted to return strings unchanged

**Comment by maksloboda** [comment]
I dug a bit deeper, it turns out that wrapper does everything correctly, as it expects a list. Its the telegram that returns a string instead of the list for the sticker emojis.
![image](https://github.com/python-telegram-bot/python-telegram-bot/assets/26490401/2c036e00-23a7-4420-b02a-1c2a1b91a080)
So i guess its up to the user to parse emojis into the array.

**Comment by Bibo-Joshi** [comment]
Ah, right. Yes, only the primary emoji is returned. Glad that you could resist the issue :)
