### ISSUE TITLE
Bug on received Array Data Telegram

### ISSUE THREAD

**Issue by carlosfelipe29** [python-telegram-bot/python-telegram-bot#393]
Hi everyone,
These modules and codes really works perfect, but:
I have found something awkward like a bug when I using the telegram codes to receive messages.

### Steps to reproduce
When I use the following line to wait for a message, I can't get the sender info.

1.    for update in bot.getUpdates(offset=update_id, timeout=10):
2.            print("UPDATE : \n ", update)        #ok
3.            chat_id = update.message.chat_id    #ok
4.            MsgTelegram2 = update.message.text   #ok
5.            who_send = update.from.username    #(from is reserve word, sintax error )

### Expected behaviour

5th line.  save the username of the person who sends the message on a local variable.

### Actual behaviour

2nd line, print all the features of the message, group, id, message (line 3) and so on. (OK)  example:
Update:
 {'update_id': XXXXXXX, 'message': {'channel_chat_created': False, 'entities': [], 'new_chat_title': '', 'migrate_to_chat_id': 0, 'caption': '', 'delete_chat_photo': False, 'migrate_from_chat_id': X, 'chat': {'type': 'group', 'username': '', 'last_name': '', 'first_name': '', 'id': -XXXXXXXX, 'title': 'name_group3'}, 'photo': [], 'group_chat_created': False, 'from': {'type': '', 'username': 'Name_Last', 'id': XXXXXXX, 'first_name': 'Name', 'last_name': 'last'}, 'message_id': XXX, 'date': XXXXXXX, 'supergroup_chat_created': False, 'new_chat_photo': [], 'text': 'MESSAGE'}}

3th line, receive the message of the array: MESSAGE.  (OK)

4th line,  works fine!!!

5th line:  (with this line the program does not executed.)
if I want to get  username, id, etc of the user who sends the message throught 'from' attribute 
   EXAMPLE:  sender = update.from.username

THERE IS A BUG because of "from" is a reserve word and it is not allow to use it as a variable or object on Python. In this sense, it is not possible to access to update.from.id,  last_name, first_name. (Console error indicates Sintax error, and not allowed)

### Configuration
debian - rasberry Pi 3

**Version of Python, python-telegram-bot & dependencies:**
python3.4,  last version

``$ python -m telegram``

### Logs
using "from"  is a reserve word, not allow to used as a variable,   sintax error

File "bot_adminTel.py", line 174
    print("who sends msg: \t ", update.from.username)
                                            ^
SyntaxError: invalid syntax

I appreciate your help.

Is there another way to get the sender info (id, username, first_name, etc.)?
Is it possible to change the "from" by "from_" or a different word?

thanks a lot.

**Comment by jh0ker** [comment]
@carlosfelipe29 Yea, we use from_user instead

**Comment by carlosfelipe29** [comment]
Hi,  @jh0ker,

did you meant to use  update.from_user.username, in order to get the username of the sender?

thanks a lot.

**Comment by jh0ker** [comment]
`update.message.from_user.username` to be specific. I'll close this issue then!

**Comment by balthild** [comment]
I'm interested in why the `to_dict()` method renames `from_user` to `from`.

**Comment by bomjacob** [comment]
Cause that's how telegram does it.
And and please never resurrect more than a year old issues for any reason :)
