### ISSUE TITLE
[QUESTION] How to automaticaly launch start_command when I reboot main.py?

### ISSUE THREAD

**Issue by ElioErrico** [python-telegram-bot/python-telegram-bot#3930]
### Issue I am facing

Hello everybody,
this is my first Telegram bot so thank you in advance for you support and sorry if is a basic question.

I would like to have the start_command to run always for all the users connected to the bot when i reboot the main.py,
Now every time i run the file, if the chat_id already exist, each user need to type \start to make it run correctly.

below you can find the code cleaned from useless strings.

Thank you for tout help.

### Related part of your code

```python
TOKEN: Final ="6495................aL5ucI"
BOT_USERNAME: Final = "@Test...._bot"

def function_1(update,context):
    ...
    return

async def start_command(update:Update, context:ContextTypes.DEFAULT_TYPE):    
    function_1(update,context)
    await update.message.reply_text("bot started")

async def handle_message(update:Update, context:ContextTypes.DEFAULT_TYPE):
    text: str = update.message.text
    user=update.message.chat.id
    response: str=handle_response(user,text)
    print("Bot", response)
    await update.message.reply_text("always the same answer")


def main():
    print("starting bot")
    app = Application.builder().token(TOKEN).build()
    app.add_handler(CommandHandler("start",start_command))
    app.add_handler(MessageHandler(filters.TEXT, handle_message))
    print("Polling...")
    app.run_polling(allowed_updates=Update.ALL_TYPES)  

if __name__=="__main__":
    main()
```

### Operating System

windows 11

### Version of Python, python-telegram-bot & dependencies

```shell
version of python 3.11

python-telegram-bot==20.6
python-telegram-bot[job-queue]==20.6
```

**Comment by Bibo-Joshi** [comment]
@ElioErrico Please have a look at <a href="https://docs.python-telegram-bot.org/telegram.ext.applicationbuilder.html#telegram.ext.ApplicationBuilder.post_init">telegram.ext.ApplicationBuilder.post_init</a>
