### ISSUE TITLE
thnak :smile:

### ISSUE THREAD

**Issue by mostafa-vn** [python-telegram-bot/python-telegram-bot#3932]
Hi.

Which keys are duplicated? Ordinary dictionaries can't have duplicate keys in python, so I can't really imagine what the issue is here. Please provide an example output of

```
# data has duplicate keys
        print(data)
```

Let me also point out that `PicklePersistence` is not intended to be subclassed and uses quite some pickle related logic internally. We provide the `DictPersistence` class specifically as base class for persistence classes that work with JSON serialization. Please check if you can subclass from that class instead.

_Originally posted by @Bibo-Joshi in https://github.com/python-telegram-bot/python-telegram-bot/issues/3564#issuecomment-1442868871_
            

tank you :smile:

**Comment by harshil21** [comment]
Hi, Please use Issues only if you have a genuine question/bug/feature suggestion.
