### ISSUE TITLE
[QUESTION]Unable to import Update

### ISSUE THREAD

**Issue by ylsh001** [python-telegram-bot/python-telegram-bot#3933]
### Issue I am facing

Unable to import Update

### Traceback to the issue

```python
Traceback (most recent call last):
  File "G:\pythonProject\tgbot\main.py", line 1, in <module>
    from telegram import Update
ImportError: cannot import name 'Update' from 'telegram' (unknown location)
```

### Operating System

win10

### Version of Python, python-telegram-bot & dependencies

```shell
python_telegram_bot-20.6
Python 3.9.7
```

**Comment by lemontree210** [comment]
Hey! Please look at [this FAQ entry](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#why-am-i-getting-importerror-cannot-import-name-xy-from-telegram)

**Comment by ylsh001** [comment]
> 嘿！请查看[此常见问题解答条目](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#why-am-i-getting-importerror-cannot-import-name-xy-from-telegram)
I have already looked at it, but I have not installed the Telegram library. The answer here cannot solve the problem

**Comment by lemontree210** [comment]
Do you have your own file called telegram.py?

If not, please post an MWE
