### ISSUE TITLE
TypeError: ulropen() got multiple values for keyboard argument 'body'

### ISSUE THREAD

**Issue by eugenio412** [python-telegram-bot/python-telegram-bot#394]
### Steps to reproduce
1.  python3.4 echobot.py

### Expected behaviour
It should work, it's just echobot on my brand new VPS, I should have installed everything properly, but I guess the problem is that I only have a root user
### Actual behaviour
TypeError: ulropen() got multiple values for keyboard argument 'body'
![error](https://cloud.githubusercontent.com/assets/13478476/17927979/ae92ef3e-69f8-11e6-951e-2e859a8bf695.PNG)
'

### Configuration
**Operating System:**

Debian jessie with only root user

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

python-telegram-bot 5.0.0
urllib3 1.16
certifi 2016.08.08
future 0.15.2
python2.7.9

for python3:

python-telegram-bot 5.0.0
urllib3 1.9.1
certifi 2016.08.08
future 0.15.2
python3.4.2

**Comment by jh0ker** [comment]
I know this error. You should have a version of `urllib3` of at least `1.10` (as stated in [requirements.txt](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/requirements.txt)), but you probably have version 1.9.1 installed via `apt` and Python doesn't override it.

Try using a virtualenv, that should work.

**Comment by eugenio412** [comment]
thank you
