### ISSUE TITLE
[QUESTION] Incorrect character encryption during sending

### ISSUE THREAD

**Issue by Komo4ekoI** [python-telegram-bot/python-telegram-bot#3945]
### Issue I am facing

In my code I need to send characters like "ì" and "è", but in telegram they come in this form "Г¬", how do I solve this?

### Operating System

windows 11

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.6
Bot API 6.9
Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
Python 3.11
```

**Comment by Bibo-Joshi** [comment]
Please provide the MWE that I [already requested](https://t.me/pythontelegrambotgroup/705648). Moreover, please don't ask the same question in multiple places at once without at least providing a link to the other locations ;)

**Comment by Bibo-Joshi** [comment]
Closing in favor of the discussion in the user group
