### ISSUE TITLE
ImportError: cannot import name TelegramError

### ISSUE THREAD

**Issue by thonixx** [python-telegram-bot/python-telegram-bot#395]
### Update
(EDIT: It also happens when just firing up the python CLI and executing `from telegram.ext import Updater` Maybe it is something concerning multiple Python projects using this library and not only the one I mentioned at the point "Steps to reproduce")

### Steps to reproduce
1. pip install python-telegram-bot
2. pip install telegram
3. pip install requirements
4. git clone https://github.com/Jiaconda/SBB_Telegram_bot.git
5. cd SBB_Telegram_bot && python sbb_bot.py 

### Expected behaviour
Can not say

### Actual behaviour
Error message as follows from the Telegram bot library:
`Traceback (most recent call last):
  File "sbb_bot.py", line 4, in <module>
    from telegram.ext import Updater, CommandHandler, MessageHandler
  File "/usr/local/lib/python2.7/site-packages/telegram/ext/__init__.py", line 21, in <module>
    from .dispatcher import Dispatcher
  File "/usr/local/lib/python2.7/site-packages/telegram/ext/dispatcher.py", line 29, in <module>
    from telegram import (TelegramError, NullHandler)
ImportError: cannot import name TelegramError`

### Configuration
**Operating System:**
OSX 10.11

**Version of Python, python-telegram-bot & dependencies:**
Python 2.7.11
and:
``$ python -m telegram``
Gives me following error:
`Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/telegram/__main__.py", line 7, in <module>
    from . import __version__ as telegram_ver
ImportError: cannot import name __version__`

### Logs
no logs available

### Remarks
I am not very experienced with developing with Python and I wanted to use an existing small Python Telegram bot. So maybe I am doing something wrong. So I would be glad if something can point me to the correct steps necessary.

**Comment by jh0ker** [comment]
`pip install telegram` looks suspicious... our library also uses the `telegram` namespace, so that might be the reason. Do you need the `telegram` library too?

**Comment by thonixx** [comment]
I'll give it a try tomorrow w/o telegram library. Keep you updated.

**Comment by thonixx** [comment]
Ok. I removed telegram library and it works. Sorry for the trouble. I don't even know why I have installed it in the first place.

**Comment by jh0ker** [comment]
Sweet, have a nice day!

**Comment by gideonadegbesan** [comment]
Hi there, i am having the same challenge saying:

> "from telegram import Emoji, ParseMode, TelegramError, Update"
> "cannot import Emoji, ParseMode, TelegramError, Update"

Please how do i fix that and also how do i remove the telegram library, i also happened to have installed it. It's urgent.
Thanks

**Comment by gideonadegbesan** [comment]
I already removed the telegram library,
what's left is to fix the main error message above.
Please how do i fix that?
