### ISSUE TITLE
[QUESTION] Flood control exceeded

### ISSUE THREAD

**Issue by Abduvakilov** [python-telegram-bot/python-telegram-bot#3950]
### Shortly what I want
Send many files to their owners in short time with minimum floods and wait times

At the beginning everything seems ok. Flood error appears once in ~5 minutes. But after 45 minutes I get many flood and 100s of timeout errors. In addition When Flood limit is reached or near the bot stops all messages which increases wait time.

### Traceback to the issue

```python
telegram.error.RetryAfter: Flood control exceeded. Retry in 3 seconds
telegram.ext.AIORateLimiter - ERROR - Rate limit hit after maximum of 0 retries
ERROR - Timed out: Pool timeout: All connections in the connection pool are occupied. Request was *not* sent to Telegram. Consider adjusting the connection pool size or the pool timeout.
```

### Related part of your code

```python
extbot = ExtBot(TELEGRAM_TOKEN,
          rate_limiter=AIORateLimiter())

def main():
  #...
  asyncio.run(send_files())

async def send_files():
  #...
  tasks = [handle_file(file) for file in files]
  await asyncio.gather(*tasks)

async def handle_file(file):
  #...
  timeout = 180
  timeout_args = {'write_timeout': timeout,
            'read_timeout': timeout,
            'connect_timeout': timeout,
            'pool_timeout': timeout}
  await bot.send_document(chat_id, file_path, **timeout_args)
```

### Operating System

oracle linux 8

### Version of Python, python-telegram-bot & dependencies

```shell
python 3.8
python-telegram-bot v20.6
```

### Questions
Is It normal to have these errors? Should’t the `AIORateLimiter` avoid it? Or Have I done anything wrong?
How to decrease the wait time sending to other chats when one has exceeded message count?

**Comment by Bibo-Joshi** [comment]
I'm not sure what kind of answer you're expeciting on the flood limits. The flood limits are controlled by Telegram, not by PTB. I can only recommend to set stricter limits for your `AIORateLimiter` instance.
Regarding the pool timeouts: Since you manually instantiate an `ExtBot` object, the default pool size is 1. I recommend to pass a custom instance of `HTTPXRequest` to [`ExtBot`](https://docs.python-telegram-bot.org/en/stable/telegram.bot.html#telegram.Bot.params.request) and adjust the [pool size](https://docs.python-telegram-bot.org/en/stable/telegram.request.httpxrequest.html#telegram.request.HTTPXRequest.params.connection_pool_size).

**Comment by Abduvakilov** [comment]
@Bibo-Joshi, Thanks for the reply. I have added to the issue:
### Questions
Is It normal to have these errors? Should’t the `AIORateLimiter` avoid it? Or Have I done anything wrong?
How to decrease the wait time sending to other chats when one has exceeded message count?

So I will try to increase pool size. Or is it better to build with `Application.builder`

**Comment by Bibo-Joshi** [comment]
> ### Questions
> Is It normal to have these errors? Should’t the `AIORateLimiter` avoid it? Or Have I done anything wrong? How to decrease the wait time sending to other chats when one has exceeded message count?

Using `AIORateLimiter` (or in fact any custom implementation of `BaseRateLimiter`) is not a guarante never to run into `RetryAfter` exceptions for the simple reason that Telegram does not document the flood limits exactly. Moreover, as stated in the docs of `AIORateLimiter`

> This class is to be understood as minimal effort reference implementation. If you would like to handle rate limiting in a more sophisticated, fine-tuned way, we welcome you to implement your own subclass of [BaseRateLimiter](https://docs.python-telegram-bot.org/en/stable/telegram.ext.baseratelimiter.html#telegram.ext.BaseRateLimiter)

Specifying arguments for `AIORateLimiter` that enforce slower sending of messages will help to some extend. If you observe some specific pattern in the flood exceptions that you get, I recommend implementing a custom subclass for the rate limiting that takes this pattern into account.

> So I will try to increase pool size. Or is it better to build with `Application.builder`

The `Application` class is meant mainly as starting point for chat-flow based bots, ie. if you want to use PTBs handler setup. If you simply want to call methods of the `Bot` class, then there is not really a need to use the `Application` class.
