### ISSUE TITLE
[QUESTION] Bot sending messages two times

### ISSUE THREAD

**Issue by Grufoony** [python-telegram-bot/python-telegram-bot#3966]
### Issue I am facing

Is've created a [bot](https://github.com/RiccardoBarbieri/the_unibot) to autosend timetable of university courses daily.
Recently, the main group in which I use the bot has migrated to a supergroup, thus I have migrated the chat id using the `ChatMigrated` raised error.
It seems to work fine but after the first day in which it sends the correct messages then it starts to send them twice.
In the log I have only noticed some `NetworkError`s and nothing more, even in debug mode.
I've had this problem since September, any idea on how to solve it?

### Operating System

Ubuntu22.04

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.6
Bot API 6.9
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
```

**Comment by harshil21** [comment]
Hi, 

We cannot dive deep into that codebase and find the error for you, if you can point out a tiny code snippet or better yet, a MWE (Minimal working example), then we'll be able to assist you. Maybe you have a job running twice in one go?

**Comment by Grufoony** [comment]
Hi, thank you for the response.
Obviously I was not expecting you to read all my repo, I was just waiting for some questions in order to attach a useful part of the code.

I've checked the running jobs and it seems like there are no double jobs... could the problem be the handling of `ChatMigrated`?

```Python
async def __callback_loop(self, context: CallbackContext) -> None:
        """
        This method is used for the callback of a scheduled job.

        Parameters
        ----------
        context : telegram.ext.CallbackContext
            Contains the context object.

        Returns
        -------
        None
        """
        try:
            await self.__orario_autosend(context)
        except ChatMigrated as e:
            # add a new line to the database with same data but new chat_id
            self.db.insert(
                "data",
                chat_id=e.new_chat_id,
                user_id=context.job.user_id,
                course=self.db.query_by_ids(context.job.chat_id)[0]["course"],
                year=self.db.query_by_ids(context.job.chat_id)[0]["year"],
                detail=self.db.query_by_ids(context.job.chat_id)[0]["detail"],
                curricula=self.db.query_by_ids(context.job.chat_id)[0]["curricula"],
                autosend=self.db.query_by_ids(context.job.chat_id)[0]["autosend"],
                autosend_time=self.db.query_by_ids(context.job.chat_id)[0][
                    "autosend_time"
                ],
                filter=self.db.query_by_ids(context.job.chat_id)[0]["filter"],
                language=self.db.query_by_ids(context.job.chat_id)[0]["language"],
            )
            # set old entry to default values
            self.db.update(
                "data",
                key_chat_id=context.job.chat_id,
                course="0",
                year=1,
                detail=2,
                curricula="default",
                autosend=0,
                autosend_time="00:00",
                filter="",
                language="en",
            )
            # remove old job
            self.jobs[str(context.job.chat_id)].schedule_removal()
            # add new job
            self.jobs[str(e.new_chat_id)] = self.job_queue.run_daily(
                self.__callback_loop,
                time=Utils.parse_time(
                    self.db.query_by_ids(e.new_chat_id)[0]["autosend_time"]
                ),
                days=(0, 1, 2, 3, 4, 5, 6),
                chat_id=e.new_chat_id,
                user_id=context.job.user_id,
                data=context.job.data,
            )
            self.jobs[str(e.new_chat_id)].enabled = True
            logging.warning(
                f"Chat migrated from {context.job.chat_id} to {e.new_chat_id}"
            )
```

Here the function `__callback_loop` is the one I call in every job. During the handling of `ChatMigrated` I remove the current job from schedul introducing a new one for the new chat_id, However, every time double messages are sent I get a warning from the logger, so `ChatMigrated` is raised every time the job runs.
Am I missing something?

**Comment by Grufoony** [comment]
Could changing the previous code with
```Python
# remove old job
self.jobs[str(context.job.chat_id)].schedule_removal()
self.jobs[str(context.job.chat_id)].enabled = False
```
solve the problem?
