### ISSUE TITLE
[QUESTION] inside message handler function 

### ISSUE THREAD

**Issue by developermano** [python-telegram-bot/python-telegram-bot#3968]
### Issue I am facing

 inside message handler function , i could not call async function . how to use it 

### Traceback to the issue

```python
There is no current event loop in thread 'Bot:6102100720:dispatcher'.
```

### Operating System

windows

### Version of Python, python-telegram-bot & dependencies

```shell
1
```

**Comment by Poolitzer** [comment]
@developermano Please fill out the template appropriately. And don&#x27;t mix threading and asyncio if you don&#x27;t know what you are doing. This error comes from you spawning a thread and then not run an event loop in it.
