### ISSUE TITLE
No warnings/exceptions in command handler

### ISSUE THREAD

**Issue by johannes87** [python-telegram-bot/python-telegram-bot#397]
### Steps to reproduce

```
from telegram.ext import Updater, CommandHandler

def start(bot, update):
    non_existent_function()
    bot.sendMessage(update.message.chat_id, text='Hello World!')

updater = Updater('TOKEN')

updater.dispatcher.add_handler(CommandHandler('start', start))

updater.start_polling()
updater.idle()
```

### Expected behaviour
An exception/a warning is shown on the terminal when the "/start" command is processed, informing the developer that the function `non_existent_function` does not exist.

### Actual behaviour
Nothing is shown, the execution seems to stop at the point where the (non-visible) exception is thrown. The user is not informed that something went wrong.

### Configuration
**Operating System:**
Debian Jessy
Python 3.4.2
Current python-telegram-bot (git ref: `ca81a75f297ae77c17ed67fe2d292446ca31f432`)

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
python-telegram-bot 5.0.0
urllib3 1.16
certifi 2016.08.08
future 0.15.2
Python 3.4.2 (default, Oct  8 2014, 10:45:20)  [GCC 4.9.1]

**Comment by jh0ker** [comment]
Hallo Johannes, our library uses the `logging` module to log exceptions, , you can read more about it on [this Wiki article](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Exception-Handling) in the **Other exceptions** section (but the rest of the page is interesting, too).
