### ISSUE TITLE
UnboundLocalError when submitting smth else then an Update to the webhook

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#3979]
https://github.com/python-telegram-bot/python-telegram-bot/blob/dd9af64a5c99c2518ef86027e008cdb8659dd1f5/telegram/ext/_utils/webhookhandler.py#L141-L148

I realized that when putting a not decodable "Update", the appropriate log is shown, but since the code continues to run, the other party receives a non descriptive 500 Internal Server Error and in the traceback an UnboundLocalError appears.

This could be easily fixed with adding `update = None` to line 149, but this means the sending party receives 200 OK while it is certainly not OK.

However, if I add a descriptive error here, bad actors could realize that they hit a telegram bot webhook and try to abuse it/spam it.  Do we want that?

If people want to protect their webhooks, they should add the secret anyway. There we however raise if the wrong/none token has been supplied, already exposing that a PTB webhook is located behind the URL...

<details>
 <summary>Traceback if you want to look at it</summary>

```
DEBUG:telegram.ext.Updater:0.0.0.0 - Exception in TelegramHandler
Traceback (most recent call last):
  File "/home/poolitzer/python-telegram-bot/venv/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/home/poolitzer/python-telegram-bot/telegram/ext/_utils/webhookhandler.py", line 159, in post
    if update:
       ^^^^^^
UnboundLocalError: cannot access local variable 'update' where it is not associated with a value
```

</details>

**Comment by Bibo-Joshi** [comment]
I agree that we can handle this more gracefully and I also agree that we should not return 200 to the sender in case the update can not be parsed. I'm okay with a descriptive error message. Something generic like "Update could not be processed" is probably unlikely to be very interpretable unless you know that you're working with a webhook of a telegram bot.

Maybe something like

```python
try:
    update = Update.de_json(…)
except:
    # log
    update = None

if update:
    # process
else:
    # reply to sender with 400 "Update could not be processed"
```

?

**Comment by Poolitzer** [comment]
@Bibo-Joshi Sure, good idea.
