### ISSUE TITLE
[BUG] An unknown user filter bypass security vulnerability alert

### ISSUE THREAD

**Issue by rikonaka** [python-telegram-bot/python-telegram-bot#3988]
### Steps to Reproduce

1. I am not the discoverer of this vulnerability, but when I was using PTB I found that someone could bypass the user filter function that comes with PTB.

### Expected behaviour

```
application.add_handler(CommandHandler(
        'test', commands.test, filters=filters.User(username=ADMINS_USERNAME)))
```

I used this code to restrict who can use the command, but recently I found that hackers could bypass this restriction and access this command. I have ruled out any other possibilities, and I added a `log` function to this command and can clearly see that the command is accessed by other users.

But I don’t know the specific bypass principle of this vulnerability.

### Actual behaviour

Do filters jobs.

### Operating System

Debian 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.6
Bot API 6.9
Python 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
```

**Comment by Bibo-Joshi** [comment]
@rikonaka Hi. Thanks for your report. I double checked the <a href="https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/filters.py#L752-L761">source code</a> of <a href="https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/filters.py#L2408-L2409">that filter</a> and I can&#x27;t see a bug in it. Well ofc also have unit tests in place for the filter.
Could you provide a minimal example that shows the observed behavior?

**Comment by rikonaka** [comment]
I can provide a copy of the code for the main function, but this code requires other files to run 🥲

```python
#!/usr/bin/env python3

import logging
import argparse
# import sys
from datetime import time

from telegram.ext import filters
from telegram.ext import Application
from telegram.ext import MessageHandler
from telegram.ext import CommandHandler
from telegram.ext import InlineQueryHandler
from telegram.ext import CallbackQueryHandler

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO)
logger = logging.getLogger(__name__)


def error(update, context):
    logger.warning('update <%s> caused error %s', update, context.error)


aps_logger = logging.getLogger('apscheduler')
aps_logger.setLevel(logging.WARNING)

parser = argparse.ArgumentParser(description='Telegram bot')
parser.add_argument('--backup', action='store_true', help='Run backup server')

args = parser.parse_args()


def main():

    current_version = version.version()
    database_version = db_version()
    logging.info('channelsbot: v%s' % current_version)
    logging.info('%s' % database_version)

    application = Application.builder().token(config.BOT_TOKEN).build()

    job = application.job_queue
    job.run_repeating(
        commands.jobs, interval=6000, first=1)

    application.add_handler(MessageHandler(
        custom_filters.inline_messsage, inline.inline_message_process))
    # message handle
    application.add_handler(MessageHandler(
        (filters.TEXT | filters.FORWARDED) & (~filters.COMMAND), messages.message_process))

    application.add_handler(CommandHandler(
        'start', commands.command_start))

    # hiden function for normal user
    application.add_handler(CommandHandler(
        'traffic', commands.command_traffic, filters=filters.User(username=config.ADMINS_USERNAME)))

    # invalid command
    application.add_handler(MessageHandler(
        filters.COMMAND, utils.invalid_command))

    '''Add inline query handle.'''
    application.add_handler(InlineQueryHandler(
        commands.command_inline_process))

    '''Add inline keyboard callback function'''
    application.add_handler(CallbackQueryHandler(
        commands.inline_keyboard_process))

    # handle errors
    application.add_error_handler(error)
    logging.info('running...')

    application.run_polling()


if __name__ == '__main__':
    main()
```

In order to deal with bypass, I now use double identity check, one user filter from PTB and one user filter written by myself.

```python
def only_admin(func):
    @wraps(func)
    def wrapped(update, context, *args, **kwargs):
        uid = get_uid(update)
        if uid in config.ADMINS_USERID:
            return func(update, context, *args, **kwargs)
    return wrapped
```

I just checked the filter code and found that I have been using username list instead of user id list in filters, which the code say `will be discarded`. I don't know if it's because of this.

**Comment by Bibo-Joshi** [comment]
@rikonaka Unfortunately this doesn&#x27;t help much, as the code is not runnable so that we can&#x27;t try to reproduce the issue. Please have a look at <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/MWE">this wiki page</a>.

**Comment by Bibo-Joshi** [comment]
@rikonaka if the issue still persists on your side, please provide a reproducable example. Otherwise I'll have to close this issue b/c we can't reproduce it.
