### ISSUE TITLE
Edited Filter

### ISSUE THREAD

**Issue by bomjacob** [python-telegram-bot/python-telegram-bot#399]
It would be awesome to have a `Filters.edited` inside `messagehandler.py` that would allow only updates with edited messages. I would write it myself, but since currently the `check_update` method of `MessageHandler` only passes either `update.message` _or_ `update.edited_message` along to the filters (with no indication of which one it was) it is not possible.
Unfortunately all the ways of solving this that I can see involve changing the arguments of every single filter - which seems a bit extreme.

**Comment by jh0ker** [comment]
There is a parameter for the constructor `allow_edited`, we decided to go for a parameter because it is then consistent with the CommandHandler.

**Comment by bomjacob** [comment]
Yeah, I saw that one. What I'm asking for is the ability to exclusively get edited messages.
The reason I can't just have it in the callback btw, is that the handler would then "eat" messages it's not supposed to.

**Comment by jh0ker** [comment]
@bomjacob Can't you just put the regular message handlers first, so only the edited updates are left at that point? Or, place it in a different group so it doesn't consume updates in the default group?

**Comment by bomjacob** [comment]
Hmm, yes I guess that could work actually. I hadn't thought of that since one of them was in a conversationhandler :)
Thanks for the help :)
