### ISSUE TITLE
Handling of MessageEntity length and offset

### ISSUE THREAD

**Issue by bomjacob** [python-telegram-bot/python-telegram-bot#400]
### Steps to reproduce
1. Send a message like "👩‍👩‍👧‍👧http://google.com" (that is, a family emoji (or really any complicated unicode codepoint) followed by a link)

2. The link should appear in a MessageEntity in `update.message.entities` with the type 'url'.

3. Try to use the `length` or `offset` attribute for basically any purpose... Fx. 
```python
entity = update.message.entities[0]
link = update.message.text[entity.offset:entity.offset + entity.length]
```

### Expected behaviour
In the example above you'd expect to have "http://google.com" in the `link` variable.

### Actual behaviour
`link` contains "://google.com".

### Why
This happens because telegram servers calculate lengths in 'UTF-16' codepoints, while python clearly doesn't (and really that's good since utf-16 is bad...). This means that python sees the family emoji as 8 characters while telegram sees it as 12 characters...

### Solution
Either:

1. Patch the length and offset inside MessageEntity's such that it matches what python thinks...
2. Add some sort of util function to convert to and from utf-8 and utf-16
3. Add some sort of custom slicing util function that does the conversion internally

### Configuration
**Operating System:**
Windows 10 Education

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 5.0.0
urllib3 1.16
certifi 2016.08.08
future 0.15.2
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]

**Note**
The behaviour of wide strings (weird unicode stuff) apparently changed as of python 3.3 (it now has a certain behaviour always where before it was a build-flag or something like that), so to support all python versions, we'd probably have to do some sort of wizardry... (See discussion at https://stackoverflow.com/questions/30775689/python-length-of-unicode-string-confusion for more info (kinda))

**Comment by bomjacob** [comment]
We basically have to replicate this function https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/jni/breakpad/common/convert_UTF.c#L233 in python... and make it compatible across versions...

**Comment by bomjacob** [comment]
I've gotten some help from [stackoverflow](https://stackoverflow.com/questions/39280183/utf-16-codepoint-counting-in-python)... I'll start working on a pull-request tomorrow :)

**Comment by bomjacob** [comment]
It seems like we have two ways to fix this:
## 1
Change the `text` attribute of `Message` to be a class similar to the one below. Doing that would make slicing using the `offset` and `length`.
```python
class TelegramString(str):
    def __init__(self, string):
        super().__init__(string)
        self.utf16string = string.encode('utf-16-le')

    def __getitem__(self, key):
        if sys.maxunicode == 0xffff:
            return super().__getitem__(key)
        else:
            if isinstance(key, slice):
                return self.utf16string[key.start * 2:key.stop * 2:key.step].decode('utf-16-le')
            else:
                return self.utf16string[key]
```
(Note that I didn't text the above code with the library)
## 2
We could also iterate over each `MessageEntity` in `entities` and add a `text` attribute (and perhaps then remove `offset` and `length`). Doing this would make the library deviate from the official documentation though.
```python
utf16string = self.text.encode('utf-16-le')
for entity in self.entities:
    # We'd need to add a text attribute in MessageEntity
    entity.text = utf16string[entity.offset * 2: (entity.offset + entity.length) * 2].decode('utf-16-le')
```

I'm not sure what people would prefer though... Thoughts?

**Comment by jh0ker** [comment]
I would like to hear @tsnoam s opinion on this, but I think I'm in favour of the first solution

**Comment by rahiel** [comment]
How about instead of changing the semantics of the Telegram API , we add a `get_entity` method to the `Message` object that takes as arguments the utf-16 offset and length, and returns the entity text. Then we're not hiding what's going on from the user and don't deviate from the API.

**Comment by bomjacob** [comment]
@rahiel That could definitely work. Maybe it could take a MessageEntity instead of the offset and length though? It seems annoying to have to use `message.get_entity(entity.length, entity.offset)` instead of just `message.get_entity(entity)`.

**Comment by tsnoam** [comment]
@rahiel @bomjacob 
I like the last suggestion: `message.get_entity(entity.length, entity.offset)`
It's clean, doesn't break/change Telegram semantics and still leaves us with the power to change the internal implementation.
