### ISSUE TITLE
Any way just block function not eventloop when ratelimiter？

### ISSUE THREAD

**Issue by jnxyatmjx** [python-telegram-bot/python-telegram-bot#4003]
### Issue I am facing

when i see the class **telegram.ext.AIORateLimiter** , it block all eventloop when issue flood limits.
Is there any method just block function(e.g. the send request functions) but not the eventloop?

### Related part of your code

```python
for i in range(max_retries + 1):
            try:
                return await self._run_request(
                    chat=chat, group=group, callback=callback, args=args, kwargs=kwargs
                )
            except RetryAfter as exc:
                if i == max_retries:
                    _LOGGER.exception(
                        "Rate limit hit after maximum of %d retries", max_retries, exc_info=exc
                    )
                    raise exc

                sleep = exc.retry_after + 0.1
                _LOGGER.info("Rate limit hit. Retrying after %f seconds", sleep)
                # Make sure we don't allow other requests to be processed
                self._retry_after_event.clear()
                await asyncio.sleep(sleep)
            finally:
                # Allow other requests to be processed
                self._retry_after_event.set()
```

### Operating System

Debain 11 64bit

### Version of Python, python-telegram-bot & dependencies

```shell
PTB 20.7
```

**Comment by Bibo-Joshi** [comment]
Hi. Let me first clarify that `await asyncio.sleep(…)` does not block the entire event loop. It's still cooperative concurrency. What it *does* block is *all* requests going out to the Bot API. This is a known and documented limitation of [`AIORatelimiter`](https://docs.python-telegram-bot.org/en/stable/telegram.ext.aioratelimiter.html):

> A [RetryAfter](https://docs.python-telegram-bot.org/en/stable/telegram.error.html#telegram.error.RetryAfter) exception will halt all requests for [retry_after](https://docs.python-telegram-bot.org/en/stable/telegram.error.html#telegram.error.RetryAfter.retry_after) + 0.1 seconds. This may be stricter than necessary in some cases, e.g. the bot may hit a rate limit in one group but might still be allowed to send messages in another group.

Changing this is currently considered out-of-scope for the built-in `AIORateLimiter`. If this is too limiting for you, I recommend to implement a custom version of [`BaseRateLimiter`](https://docs.python-telegram-bot.org/en/stable/telegram.ext.baseratelimiter.html#telegram.ext.BaseRateLimiter).

I hope that this answers your question.

**Comment by jnxyatmjx** [comment]
> t's still cooperative concurrency.

i mean the statement **self._retry_after_event.clear()**. does it block the entire event Loop?

**Comment by jnxyatmjx** [comment]
If i have a long time task doing (e.g. get_file for large file). and trigger the limiter at this point.
after call **self._retry_after_event.clear()** the get_file function will return with None immediatelly.
I thank may be have a better way just put task to _queue_ but not really process until after **self._retry_after_event.set()**

**Comment by Bibo-Joshi** [comment]
> i mean the statement **self._retry_after_event.clear()**. does it block the entire event Loop?

No. The usage og the `_retry_after_evevnt` is asyncio friendly as well:

https://github.com/python-telegram-bot/python-telegram-bot/blob/a8f1164b0cb9bb1e26920a03ae5c88b167bd3041/telegram/ext/_aioratelimiter.py#L199-L203

> use Dict with special function name?

Using different events for different kinds of requests to the Bot API would be one idea, yes.

> after call self._retry_after_event.clear() the get_file (or any other) function will return with None immediatelly

I doubt that this happens. [this line](https://github.com/python-telegram-bot/python-telegram-bot/blob/a8f1164b0cb9bb1e26920a03ae5c88b167bd3041/telegram/ext/_aioratelimiter.py#L263) will never actually run (and this  shows in our [test coverage](https://app.codecov.io/gh/python-telegram-bot/python-telegram-bot/blob/master/telegram%2Fext%2F_aioratelimiter.py#L263)). If you experience problems with `get_file` in combination with `AIORateLimiter`, please provide an [MWE](../wiki/MWE) so that we can try to reproduce this.

> I thank may be have a better way just put task to queue but not really process until after self._retry_after_event.set().

This is basically what's happening in the code lines cited above.

**Comment by jnxyatmjx** [comment]
> > i mean the statement **self._retry_after_event.clear()**. does it block the entire event Loop?
> 
> No. The usage og the `_retry_after_evevnt` is asyncio friendly as well:
> 
> https://github.com/python-telegram-bot/python-telegram-bot/blob/a8f1164b0cb9bb1e26920a03ae5c88b167bd3041/telegram/ext/_aioratelimiter.py#L199-L203
> 
> > use Dict with special function name?
> 
> Using different events for different kinds of requests to the Bot API would be one idea, yes.
> 
> > after call self._retry_after_event.clear() the get_file (or any other) function will return with None immediatelly
> 
> I doubt that this happens. [this line](https://github.com/python-telegram-bot/python-telegram-bot/blob/a8f1164b0cb9bb1e26920a03ae5c88b167bd3041/telegram/ext/_aioratelimiter.py#L263) will never actually run (and this shows in our [test coverage](https://app.codecov.io/gh/python-telegram-bot/python-telegram-bot/blob/master/telegram%2Fext%2F_aioratelimiter.py#L263)). If you experience problems with `get_file` in combination with `AIORateLimiter`, please provide an [MWE](../wiki/MWE) so that we can try to reproduce this.
> 
> > I thank may be have a better way just put task to queue but not really process until after self._retry_after_event.set().
> 
> This is basically what's happening in the code lines cited above.

got it. thanks very much
