### ISSUE TITLE
[FEATURE REQUEST] Please lower httpx to allow >=0.24

### ISSUE THREAD

**Issue by ericxl** [python-telegram-bot/python-telegram-bot#4004]
### Steps to Reproduce

in poetry, add both `supabase` and `python-telegram-bot`

### Expected behaviour

N/A

### Actual behaviour

N/A

### Operating System

N/A

### Version of Python, python-telegram-bot & dependencies

```shell
N/A
```

**Comment by Bibo-Joshi** [comment]
Hi. PTB makes explicit use of features introduced in httpx 0.25.0:

* #3939
* #3935

Allowing httpx 0.24.* would require to make runtime checks for these features, which would require additional coding & testing effort. TBH I don.t see this going on any roadmap, though I would mabye be willing to accept a contribution for this.
However I see that you have already requested supabase to update their httpx requirement https://github.com/supabase-community/supabase-py/issues/639, so I would like to first see how that goes.
IISC they do have dependabot set up (https://github.com/supabase-community/supabase-py/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+httpx+), so I expect there is a high chance that they will update httpx anyways :)

**Comment by Bibo-Joshi** [comment]
https://github.com/supabase-community/supabase-py/issues/639 has been closed, so closing this one as well
