### ISSUE TITLE
[QUESTION]track button click event for web_app

### ISSUE THREAD

**Issue by coolsnake** [python-telegram-bot/python-telegram-bot#4006]
### Issue I am facing

I use the following code,but I don't know how to track the "open_website" button click for web_app. Any one can help me? Thanks.

```python
keyboard = [
    [
        InlineKeyboardButton(lang[LANGUAGE]["settings"], callback_data="language"),
        InlineKeyboardButton(lang[LANGUAGE]["open_website"],
        web_app=WebAppInfo(url=f"{MINI_APP_URL}/{LANGUAGE}"))
    ],
]
```

### Operating System

linux

### Version of Python, python-telegram-bot & dependencies

```shell
NA
```

**Comment by Poolitzer** [comment]
Wdym with track, the url will just be called.

**Comment by coolsnake** [comment]
> Wdym with track, the url will just be called.

Thank you!  I don't know Wdym, can you explain more?

**Comment by coolsnake** [comment]
> Please also see [this faq entry](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#can-an-inlinekeyboardbutton-have-both-a-url-and-callback-data)

Thank you very much.

**Comment by Poolitzer** [comment]
> > Wdym with track, the url will just be called.
> 
> Thank you! I don't know Wdym, can you explain more?

Wdym is short for what do you mean, this feels like a duplicate of #4009 and I still don't get your issue. Your webserver with the web app receives a request with every click. So. use that.
