### ISSUE TITLE
[QUESTION]Track click event for Menubutton on the left side of the text input area

### ISSUE THREAD

**Issue by coolsnake** [python-telegram-bot/python-telegram-bot#4009]
### Issue I am facing

I have set up Menubutton on the left  side of the text input area and after click the Menubutton, it will open mini-app. 
How to track the click event before it opens the mini-app?

### Traceback to the issue

```python
NA
```

### Related part of your code

```python
NA
```

### Operating System

linux

### Version of Python, python-telegram-bot & dependencies

```shell
NA
```

**Comment by Bibo-Joshi** [comment]
@coolsnake Telegram does not emit an event for that. See also <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#can-you-add-feature-to-ptb-can-i-do-thing-with-my-bot">Can you add [feature] to PTB? Can I do [thing] with my bot?</a>?
