### ISSUE TITLE
raise RuntimeError('Connection Pool already initialized') after restarting update instances

### ISSUE THREAD

**Issue by optixx** [python-telegram-bot/python-telegram-bot#401]
### Steps to reproduce
1.  Using multiple telegram bot update instance in gevent based server 
2. Start them with updater.start_polling()
2. Stop all updater.stop()
3. Restart them with  updater.start_polling()
 
### Expected behaviour
Make possible to run mutliple updater instance with either shared urlib3 pools or seperate pools
 
### Actual behaviour
Failed to allocate new dispatcher workers due global constraint in urllib3 connection pool

### Configuration
Linux

**Version of Python, python-telegram-bot & dependencies:**

```
urllib3 1.10 has no metadata
python-telegram-bot 5.0.0 has no metadata
```

### Logs
```
  File "/opt/devcores/env/local/lib/python2.7/site-packages/telegram/ext/updater.py", line 85, in __init__
    exception_event=self.__exception_event)
  File "/opt/devcores/env/local/lib/python2.7/site-packages/telegram/ext/dispatcher.py", line 124, in __init__
    raise RuntimeError('Connection Pool already initialized')
```

**Comment by tsnoam** [comment]
@optixx Thank you for reporting the issue.
When we designed/implemented urllib3 feature, we were aware of this limitation and chose not to support this configuration simply because we were not aware of users who require it.
Now that we are aware of such need, we'll put it in our work plans.
Of course, if you desire, we would welcome a PR to handle such scenario.

**Comment by optixx** [comment]
@tsnoam Thanks for the feedback. Any ideas for a feasible workaround for me? 

- Monkey patch Dispatcher to re-setup worker threads despite request.is_con_pool_initialized() being true
- Possible to disable the pool at all?
- Go back to an older version of python-telegram-bot like 4.2.1 where didn't have this kind of problems

**Comment by tsnoam** [comment]
@optixx for now you can use the latest version without urllib3 (probably 4.2.1 i don't recall as I live on the master)
