### ISSUE TITLE
[Type Hinting] _log function is not properly annotated

### ISSUE THREAD

**Issue by DavidEGx** [python-telegram-bot/python-telegram-bot#4010]
### Steps to Reproduce

1. Create a `test.py` like:
```
import asyncio
import telegram

bot = telegram.Bot(token="some-token")
async def send_msg():
    await bot.send_message(chat_id="channel-id", text="Hello World")  # Argument missing for parameter "self"

asyncio.run(send_msg())
```
2. Run
```
pyright test.py
```

You'll see:
```
test.py:6:11 - error: Argument missing for parameter "self" (reportGeneralTypeIssues)
```

Fix is described in pyright discussion, see https://github.com/microsoft/pyright/discussions/6669#discussioncomment-7781395

### Expected behaviour

Code is properly annotated so pyright doesn't throw any error.

### Actual behaviour

Pyright complains _Argument missing for parameter "self"_

### Operating System

Ubuntu 23.10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.7
Bot API 6.9
Python 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0]
```

**Comment by Bibo-Joshi** [comment]
Thanks for reaching out. This is in fact not the first time we had issues with the typing for this decorator, as it came up in #2677 before, which was adressed in #2686. I strongly suggest that we manually check compatability of a new fix with VSCode and PyCharm before merging.
It would also be good to use this chance to fix & improve our [type completeness check](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/.github/workflows/type_completeness.yml) as we discovered through this issue that it [apparently fails silently](https://github.com/python-telegram-bot/python-telegram-bot/actions/runs/7200052287/job/19613114285). It would be good to see if this check can automatically detect this shortcoming with a newer version of pyright. If it does not, we should reach out to pyright and ask for clarification.
