### ISSUE TITLE
How to set up multiple bots in only one python script?[QUESTION]

### ISSUE THREAD

**Issue by jnxyatmjx** [python-telegram-bot/python-telegram-bot#4017]
### Issue I am facing

Can we run multiple bots in only one python script? 
should you show me the code example if it can?

### Operating System

Linux 5.15.133.1 WSL2  x86_64 GNU/Linux

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.7 (warp-56-g1204c88)
Bot API 6.9
Python 3.8.10 (default, Nov 22 2023, 10:22:35)  [GCC 9.4.0]
```

**Comment by Bibo-Joshi** [comment]
@jnxyatmjx Hi. Please have a look at <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#running-ptb-alongside-other-asyncio-frameworks">Running PTB alongside other asyncio frameworks</a>.
