### ISSUE TITLE
Can bot handle user typing event ?

### ISSUE THREAD

**Issue by alexey2baranov** [python-telegram-bot/python-telegram-bot#4021]
### Issue I am facing

I need to delay some very expensive operation until user finish writing his question. It might be from 1 to n questions depends on sutuation. So one approach is to set crazy large timeout after first message before run expensive operation. But I prefere the idea of combining middle-size timeout plus handling user type event. Having user typing event handling I be able to debounce my expensive operation. 

### Traceback to the issue

```python
N/A
```

### Related part of your code

```python
N/A
```

### Operating System

Ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
3.10
```

**Comment by Poolitzer** [comment]
@alexey2baranov No bots don&#x27;t get a typing event

**Comment by alexey2baranov** [comment]
@Poolitzer thanks for quick replay. Can you suggest another workaround for my situation?
