### ISSUE TITLE
How can I get pictures from Bot users ? 

### ISSUE THREAD

**Issue by scsdev-cyber** [python-telegram-bot/python-telegram-bot#4025]
### Issue I am facing

How can I get pictures from Bot users ? 

When sending photo to the bot, nothing happened. 

### Operating System

any

### Version of Python, python-telegram-bot & dependencies

```shell
python3
```

**Comment by Poolitzer** [comment]
@scsdev-cyber Wiki of <i>python-telegram-bot</i> - Category <i>Code Snippets</i>
<a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#fetch-images-sent-to-your-bot">Fetch images sent to your Bot</a>
