### ISSUE TITLE
How to delete a file (using file_id) completely from telegram?

### ISSUE THREAD

**Issue by adithyaamara** [python-telegram-bot/python-telegram-bot#4027]
### Issue I am facing

I know that delete_message can be used to delete a message that vanishes the files from chat as well. But I can still use the `get_file` method to download a file using file_id for many number of days. How to delete a file completely from telegram?
I am using 13.2 version of this library, ready to use latest if it provides the said functionality.

### Operating System

Windows

### Version of Python, python-telegram-bot & dependencies

```shell
Python: 3.10.5, python-telegram-bot: 13.2
```

**Comment by Poolitzer** [comment]
Hi, there isn't a different API call. You would need to contact Telegram about this.

**Comment by adithyaamara** [comment]
@Poolitzer Do you know of a way at-least by which we can overwrite the existing file with some dummy data using `file_id`?

**Comment by Poolitzer** [comment]
@adithyaamara I mean you can edit media, e.g. <a href="https://docs.python-telegram-bot.org/telegram.bot.html#telegram.Bot.edit_message_media">telegram.Bot.edit_message_media</a> <a href="https://core.telegram.org/bots/api#editmessagemedia">ᵀᴱᴸᴱᴳᴿᴬᴹ</a>
