### ISSUE TITLE
How to use bot.editMessageText to edit a message sent through an inline query

### ISSUE THREAD

**Issue by mpschr** [python-telegram-bot/python-telegram-bot#403]
Hi there 

So this is more of a support issue than a bug.

Background: I am successfully adding buttons to a message which then, by clicking are edited via the function `bot.editMessageText` - it works like a charm

But now, if I would like to do the same if the message has been sent as an inlineQuery answer/result, then there is no `message_id`, but a `inline_message_id`. So far so good, but if I send it with `message_id == None` and `inline_message_id = update.callback_query.message.message_id` an error of the following sort will be displayed in my console:

`WARNING:root:Update "{'callback_query': {'id': '51107415403141447', ....redacted..., 'inline_message_id': 'BAAAAO8RBQDskbUAmPbrZPeyYm4'}, 'update_id': 549038251}" caused error "'Bad Request: message not found'"
`

Does anybody have an idea how this has to be done?

**Comment by mpschr** [comment]
Oh wow, I just figured it out! I have to set the `chat_id` to `None` if `inline_message_id` is specified. Well then - I hope this helps somebody

**Comment by rezaysh** [comment]
tnx body, your guide helps me so much.

**Comment by bakytn** [comment]
hey mpschr you saved me a lot of hours for sure. Thanks!
