### ISSUE TITLE
Update Copyright

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#4041]
We should update the copyright on all the PTB/ptbcontrib
Important: not all files have the 2015-2021 header, some have 20XX-2021 or even just 20XX, consider this in the regex

Let's do that after #4034 is merged, as that PR is creating several new files

**Comment by CodeYard01** [comment]
@Bibo-Joshi you can assign it to me. I will do

**Comment by Bibo-Joshi** [comment]
Assigning you 👍 Please subscribe to notifications on #4034 so that you'll know when to get started :)

**Comment by CodeYard01** [comment]
Subscribed !

**Comment by Bibo-Joshi** [comment]
We wait until the PR is finished and merged

**Comment by Bibo-Joshi** [comment]
#4034 is merged, so this can now be addressed :)

**Comment by aelkheir** [comment]
@Poolitzer, I could do it if you haven't started  yet
