### ISSUE TITLE
Cannot use a ConversationHandler as part of another ConversationHandler

### ISSUE THREAD

**Issue by liiight** [python-telegram-bot/python-telegram-bot#405]
### Steps to reproduce
1. Define a ConversationHandler where one if its states corresponds to another ConversationHandler
2. Trigger the nested ConversationHandler
3. End the nested ConversationHandler using the `Conversation.END` state.
### Expected behaviour

There should be an option to manipulate the "external" conversation state, as possible with other Handlers.
### Actual behaviour

Since the last return value of the nested conversation is END, there is no option to alter the external conversation state, and it's "stuck" in that state.

Linked to #385

**Comment by jh0ker** [comment]
I think this (with #385 in mind) requires a small but backwards-compability breaking adjustment to the Handler subsystem , so I'll put this up for milestone 6.0

IMO we should get #373 resolved, release 5.1 and then start working on this.

**Comment by jh0ker** [comment]
Thoughts:

When you want to exit the current `ConversationHandler` and also pass on a new state for the parent handler, return a `list`: 

- `return [ConversationHandler.END, FOO]` 
- or to exit two stages: `return [ConversationHandler.END, ConversationHandler.END]` 

In [`ConversationHandler.handle_update`](https://github.com/python-telegram-bot/python-telegram-bot/blob/a91fe5f8f6058abdb12eb8ebaf47ad860313bd17/telegram/ext/conversationhandler.py#L208), we could then test if the return type is `list`, and if the first item in that list is `END`. If so, slice the first element off and return the remainder of the list, which will then be interpreted by the parent `ConversationHandler`. If only one item is left in the list, return that.

Another idea: `ConversationHandler.END` is defined as `-1`. We define another exit condition. If the return value is a `tuple` (named `t`) with `len(t) == 2` and the first element is a negative number, the `ConversationHandler` ends the conversation and does 

```python
if t[0] < -1:
    return (t[0] + 1, t[1])
else:
    return t[1]
```

That way, we don't have to build big lists that could be messed up.

Let me know what you think!

**Comment by jh0ker** [comment]
Alright this issue is pretty old, and we have decided to close it because 

1. Any solution to allow for nested conversation handlers is incredibly convoluted
2. From a computer science perspective, nested state machines are the same as state machines
