### ISSUE TITLE
I need some explains about python-telegram-bot

### ISSUE THREAD

**Issue by Mohammad-Taha-Jedi** [python-telegram-bot/python-telegram-bot#4055]
### Issue I am facing

When I read the [document](https://docs.python-telegram-bot.org/en/v20.7/) I can't understand what is the different between Bot and Update and...
Can somebody explain to me that for example when I wanna get the user first name how I can find the related part in document and how I can use it in my bot?

### Operating System

Windows 11

### Version of Python, python-telegram-bot & dependencies

```shell
Thr version of library is 20.7 which don't use dispatcher more
```

**Comment by Poolitzer** [comment]
You should read the wiki, start [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Introduction-to-the-API), read through the next 5 pages, and you are good to go.
