### ISSUE TITLE
[FEATURE] Add unit tests support

### ISSUE THREAD

**Issue by AAraKKe** [python-telegram-bot/python-telegram-bot#4057]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Any bot that written in a maintainable manner should have a battery of unit tests, at least. I have tried to find if this library provides any solution for unit tests, but I could not find anything, and in the wiki, I see a repo that can be used to write tests that are unmaintained.

It would be great if the library it self provided a module for testing that would be maintained alongside the library and that can be used by users of this package to create unit tests of their bot, mainly mocking calls to the bot through polling.

### Describe the solution you'd like

I think a good solution would be an integrated testing framework that can be consumed to submit requests to the bot itself as if they were messages sent by telegram and that would register the bot responses. It could also expose a pytest fixture for easy consumption in tests.

As a first approach we could include a minimal version of this solution and keep growing it from it. Is this something you are considering or something you would be open to integrating into this package? I could help with that if necessary. I have a bot with lots of users written in Ruby. We are moving now to Python in an effort to rewrite it and start from scratch, and having the ability to do unit tests is something we would really like.

### Describe alternatives you've considered

I have not tried any alternative so far. We were considering doing our own solution but thought that it might be better if a testing solution were available in the library itself and maybe this is something you would open to.

What do you think?

**Comment by Poolitzer** [comment]
Hi. We don't consider unit testing to be part of our library, and we don't have resources to develop them. We have [ptbtest](https://github.com/python-telegram-bot/ptbtest) as a repository in our ownership which was written for an old version of PTB.

In January of 2022 we asked the community if someone wants to maintain it, but nobody contacted us. https://t.me/pythontelegrambotchannel/111 and https://t.me/pythontelegrambotchannel/115

If you would like to start doing this, we are happy to answer questions and if you have something ready, to give it a shout out, link to it in the appropriate places, etc. I would also be fine to have it in our ownership and add you (and anyone else who wants to code it) to our team, but the others do get a vote for that as well ofc.

But again, we don't consider it part of our library goals, and we can't help develop it, we have enough work with PTB as it is. Sorry.

**Comment by Bibo-Joshi** [comment]
Thanks for reaching out. This topic has been discussed several times. The last that I removed is #1828. The answer hasn't changed since then, i.e. support for testing utilities is considered out of scope for PTB. Still, I want to highlight some points:

* We have made an effort to find a new maintainer for ptbcontrib (see https://t.me/pythontelegrambotchannel/111), unfortunately without result. If you are interested in becoming the new maintainer, I'm happy to take that trough with you
* Apart from PT test, smaller contributions to the PTB ecosystem are also welcome via the ptbcontrib repository 
* PTB provides an API that IMO allows for comparatively easy integration with unit tests without the need for any changes within PTB. Firstly, through the public Application.update_queue and Application.process_update, you can easily enqueue and manually process updates for checking that they are handled as expected. Secondly, since the networking backend is built to be customizable via BaseRequest, one can implement a MockRequest class to mock thr communication with Telegram.

I'm aware that these points are not what you're aiming for, but they are what I can offer that this time. Thanks for your understanding.

**Comment by AAraKKe** [comment]
Thanks for coming back so quick. The reason why I am saying I think this would be a nice addition to the library is that it would live within the same library, making sure each update to the library is also shipped with any necessary changes to the testing framework to ensure any production-ready bot can update without losing testing capabilities.

Since this is a framework and not just a utility library, it seems incomplete without the ability to easily test the app built with this framework. That being said, I was not aware of the process_queue, and it might be good to at least add this information to the wiki where [testing is mentioned](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Writing-Tests). Something as simple as guidance about how you would propose to write tests explaining some of these details.

That being said, I understand if, due to a lack of manpower, you cannot provide this solution as part of the framework. If I want to take on this, what would be your suggestion to fit the project's current state better? Would you like someone to take on the ptbtest package, or would it be a better approach to start something from scratch? Depending on how outdated it is (it seems to be pretty outdated), you might prefer to have something different.

I am ok with any approach you prefer. I feel that what I was planning to do would be general enough that anyone would be able to benefit from it, and because of this, it might make more sense to do it as part of PTB instead of just for our project.

Let me know what you guys think! 

PS: I am unsure at the moment about how much time I can dedicate to this since I have other commitments (work at AWS and need to come back to my YT channel in 2024 😅), but I will do my best to keep in touch with you as soon as this starts moving.

**Comment by Bibo-Joshi** [comment]
> it might be good to at least add this information to the wiki where [testing is mentioned](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Writing-Tests).

That's a good point 👍 I've edited the page. You're ofc welcome to extend the page with any insights that you have.

> If I want to take on this, what would be your suggestion to fit the project's current state better? Would you like someone to take on the ptbtest package, or would it be a better approach to start something from scratch?

I would leave this decision up to you/anyone interested in starting such a project. The `ptbtest` package has already some history in the PTB ecosystem, a PyPi package & documentation set up on RTD. This can be viewed as an advantage or disantvantage. For handing over the maintainer-ship for ptbtest, the status is as described in https://github.com/python-telegram-bot/ptbtest?tab=readme-ov-file#maintainer-wanted. If a new package is created instead, we're ofc open to give it some spotlight & support as indicated by Poolitzer.
