### ISSUE TITLE
[QUESTION]Is there any way to join channel or group automatically?

### ISSUE THREAD

**Issue by jnxyatmjx** [python-telegram-bot/python-telegram-bot#4059]
### Issue I am facing

any method api can join channel or group automatically?

### Traceback to the issue

```python
none
```

### Related part of your code

```python
none
```

### Operating System

ubuntu 20 none linux

### Version of Python, python-telegram-bot & dependencies

```shell
none
```

**Comment by Poolitzer** [comment]
@jnxyatmjx No, users need to add your bot to chats
