### ISSUE TITLE
ChosenInlineResultHandler not working

### ISSUE THREAD

**Issue by Skargonas** [python-telegram-bot/python-telegram-bot#406]
### Steps to reproduce
1. Run the code below (you can see it's based on [the tutorial](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-Your-first-Bot)):

2. Send an inline message via the bot.

```python
import logging

from telegram import InlineQueryResultArticle, InputTextMessageContent
from telegram.ext import Updater
from telegram.ext import InlineQueryHandler, ChosenInlineResultHandler

from secret import token

logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.DEBUG)

def inline_caps(bot, update):
    logging.debug('HI')
    query = update.inline_query.query
    if not query:
        return
    results = list()
    results.append(
        InlineQueryResultArticle(
            id=query.upper(),
            title='Caps',
            input_message_content=InputTextMessageContent(query.upper())
            )
        )
    bot.answerInlineQuery(update.inline_query.id, results)

def say_hello(bot, update):
    logging.debug('HELLO')
    logging.debug(update.to_dict())

updater = Updater(token=token)
dispatcher = updater.dispatcher

updater.start_polling()

inline_caps_handler = InlineQueryHandler(inline_caps)
result_handler = ChosenInlineResultHandler(say_hello)

dispatcher.add_handler(inline_caps_handler)
dispatcher.add_handler(result_handler)

updater.idle()
updater.stop()

```

### Expected behaviour
The function `say_hello` is called and related text appears in the logs.

### Actual behaviour
It doesn't happen.

### Configuration
**Operating System:** 
Ubuntu 16.04

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 5.0.0
urllib3 1.17
certifi 2016.08.31
future 0.15.2
Python 3.5.2 (default, Jul  5 2016, 12:43:10)  [GCC 5.4.0 20160609]

**Comment by bomjacob** [comment]
Make sure that telegram knows that you'd like inline feedback by sending `/setinlinefeedback` to `@botfather` and choosing `Enabled`.
After you've done that, the code you've pasted above should work :)

**Comment by Skargonas** [comment]
Oh, I'm sorry!
Closing issue.
