### ISSUE TITLE
Move handler-related files to a new subdirectory

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#4060]
The [`telegram/ext`](https://github.com/python-telegram-bot/python-telegram-bot/tree/master/telegram/ext) directory is getting a bit crowded. It would be good if all `_*handler.py` files as well as `filters.py` (which is part of the handlers setup) would be moved to a directory `telegram/ext/_handlers`. The imports and `telegram/ext/__init__.py` would have to be adapted in such a way that the public API doesn't change, i.e. `from telegram.ext import BaseHandler, CommandHandler, filters` etc is still the expected way of importing.

**Comment by ManikMKR11** [comment]
Thanks Boss, I am interested here, but I don't understand about this all Thanks ♥️♥️♥️

you means you are thinking to delete the telegram.ext and make new module for work with filters and so on

**Comment by Bibo-Joshi** [comment]
No, deleting `telegram.ext` is not what is meant at all. I explicitly clarified:

> the public API doesn't change, i.e. from telegram.ext import BaseHandler, CommandHandler, filters etc is still the expected way of importing.

**Comment by lucasmolinari** [comment]
Hello :) That's a great oportunity to me to learn about python packages and help you. Can I work on it?
