### ISSUE TITLE
Deprecate `filters.CHAT`

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#4062]
`filters.CHAT` doesn't really have a purpose as `Message.chat` is not optional. I would assume that `filters.CHAT` was added in #2759 as constant version of `filters.Chat` and that this is superfluous was just missed in that rather large rework.

We should deprecate that filter. Since issuing warnings on filter access is non-trivial, this would be a documentation-only deprecation but should still get its own commit for more visibility in the changelog.

Reference: https://t.me/pythontelegrambottalk/248839

**Comment by sheriifMahadi** [comment]
I'd like to work on this.

**Comment by ManikMKR11** [comment]
as i think it not need to remove filters.CHAT as maybe some of users make some code with this handle so it will just cause problems to us in future
i don't use it before i am don't understand it is just sometimes easy and sometimes complicated

**Comment by clot27** [comment]
@sheriifMahadi sure! assigned to you.

**Comment by ManikMKR11** [comment]
> @sheriifMahadi sure! assigned to you.

what your assign means?
what to do me?

**Comment by ManikMKR11** [comment]
owo Thanks, can You Guys Forgive me, i want to get some help in ur PTB Learning, i swear i will not try to make any problem in the group i will fully learn by docs as much as possible pls allow me in group
