### ISSUE TITLE
[QUESTION] Persist bot information in the SqLite database

### ISSUE THREAD

**Issue by aleksanderFox** [python-telegram-bot/python-telegram-bot#4068]
### Issue I am facing

Hello!
In my project I would like to implement the storage of persistent bot information in the SqLite database.
I did not find a class in the library that implements such functionality.
Therefore, I want to ask the community how much demand will such a class SqlitePersistence(BasePersistence) have?
I want to start contributing :)

### Operating System

Any

### Version of Python, python-telegram-bot & dependencies

```shell
Last
```

**Comment by Bibo-Joshi** [comment]
@aleksanderFox Hi. <a href="https://docs.python-telegram-bot.org/telegram.ext.dictpersistence.html#telegram.ext.DictPersistence">telegram.ext.DictPersistence</a> and <a href="https://github.com/python-telegram-bot/ptbcontrib/tree/main/ptbcontrib/postgres_persistence">ptbcontrib/postgres_persistence</a> may be starting points.

**Comment by aleksanderFox** [comment]
@Bibo-Joshi Hi. I know about telegram.ext.DictPersistence and telegram.ext.PicklePersistence.
I want to know is class SqlitePersistence will be needed?

**Comment by Bibo-Joshi** [comment]
TBH I personally don't see additional persistence classes as part of the built-in functionality of `python-telegram-bot` in the forseable future.
