### ISSUE TITLE
on raspberry pi3 i receive urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError(HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out.

### ISSUE THREAD

**Issue by lopanta** [python-telegram-bot/python-telegram-bot#407]
### Steps to reproduce
1.

2.

3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by bomjacob** [comment]
Please try to describe your issue. What are you trying to do? How are you doing it (show your code!)? If you can, also please post your log file (that is, the full output you get in your console when you run the bot with logging enabled).

**Comment by lopanta** [comment]
python-telegram-bot 5.0.0
urllib3 1.16
certifi 2016.08.08
future 0.15.2
Python 2.7.9 (default, Mar  8 2015, 00:52:26)  [GCC 4.9.2]

**Comment by lopanta** [comment]
First: excuse me for late reply.Now I have a log for you: it is only warning, but I think that you can have a suggestion.The wanings appen not with regularity, the log is on the file
 

    Il Martedì 13 Settembre 2016 18:49, Jacob Bom <notifications@github.com> ha scritto:
 

 Please try to describe your issue. What are you trying to do? How are you doing it (show your code!)? If you can, also please post your log file (that is, the full output you get in your console when you run the bot with logging enabled).—
