### ISSUE TITLE
[FEATURE] Add send scheduled message

### ISSUE THREAD

**Issue by rafaelribeiroo** [python-telegram-bot/python-telegram-bot#4076]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Hi, is it possible to add the schedule_date flag to the SendMessage method?
As it appears from [here](https://core.telegram.org/api/scheduled-messages#:~:text=To%20schedule%20a%20message%2C%20simply,sent%20at%20the%20specified%20time.) , it looks that the api provides this feature.

### Describe the solution you'd like

simply provide a future unixtime in the schedule_date flag of [messages.sendMessage](https://core.telegram.org/method/messages.sendMessage) or [messages.sendMedia](https://core.telegram.org/method/messages.sendMedia)

**Comment by Poolitzer** [comment]
@rafaelribeiroo Hi, you are mixing up the MTProto API and the bot API, telegrams bot api documentation is at https://core.telegram.org/bots/api. So no we can not.
