### ISSUE TITLE
[FEATURE] Bind to file descriptor of unix socket

### ISSUE THREAD

**Issue by septatrix** [python-telegram-bot/python-telegram-bot#4078]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

#3986 already added support to bind PTB to a unix socket though for security purposes it is common to pass the socket via a file descriptor to the service instead of it opening it manually.

### Describe the solution you'd like

It would be great if `run_webhook` would be expanded to take a `socket_fd` parameter or if its `unix=` paramter would support `file` values in addition to `Path`/`str`.

### Additional context

The reason to supply the socket as a file descriptor instead of having the service create it on its own is that it allows restricting the capabilities of the service and permissions of the socket further for improved security. Furthermore it allows for socket activation, i.e. a service manager can start listening on the socket and only once the first requests is received does PTB have to be started which saves server resources.

**Comment by septatrix** [comment]
> Hi, we pass the Path/str to https://www.tornadoweb.org/en/stable/netutil.html#tornado.netutil.bind_unix_socket. This function doesn't take a file descriptor. I don't see a tornado way to pass it either, and couldn't find one in my (arguably very quick) search.

The passed file descriptor would replace calling `bind_unix_socket`. Instead one would call [`socket.fromfd`](https://docs.python.org/3/library/socket.html#socket.fromfd) and pass the obtained socket to `self._http_server.add_socket`

**Comment by Poolitzer** [comment]
Aha, funny that I didn't see this as an example somewhere. Maybe too basic of a problem.

I wont have time to work on this for the next month, if someone else wants to in the meantime.
