### ISSUE TITLE
Remove deprecated code

### ISSUE THREAD

**Issue by rahiel** [python-telegram-bot/python-telegram-bot#408]
Through all the versions we've acquired a lot of deprecated code, left intact for backwards compatibility. Here an overview so we won't leave them in forever (between parentheses the first release with the deprecation warning):

Group 1 (#564)
- [x] Non-PEP8 [dispatcher methods](https://github.com/python-telegram-bot/python-telegram-bot/blob/5285f63e4a39c171728710e2dd15601e46de9c39/telegram/ext/dispatcher.py#L370) (v4)
- [x] Non-PEP8 method names in all `telegram.ext.*handler.py` files (v4)
- [x] Check examples for deprecated code usage
---
Group 2 (at around 7.0)
- [x] Botan import from [utils](https://github.com/python-telegram-bot/python-telegram-bot/blob/5285f63e4a39c171728710e2dd15601e46de9c39/telegram/utils/botan.py) (v5)
- [x] [telegram.Emoji](https://github.com/python-telegram-bot/python-telegram-bot/blob/5285f63e4a39c171728710e2dd15601e46de9c39/telegram/emoji.py) (v5.1)
- [x] [`ReplyKeyboardHide`](https://github.com/python-telegram-bot/python-telegram-bot/blob/botapi2.3/telegram/replykeyboardremove.py#L64) (v5.3)
- [x] [`edit_message` in `setGameScore`](https://github.com/python-telegram-bot/python-telegram-bot/blob/botapi2.3/telegram/bot.py#L1490) (v5.3)
- [x] Remove usage of deprecated code in tests.

**Comment by jh0ker** [comment]
Perhaps we could convert this (and potentally other long-running issues like this) into a "Project" so they don't clutter up our Issues page?

**Comment by KamranMackey** [comment]
@jh0ker That would be a good idea. By the way, there's no need to put Project in quotes. We know what you mean :smile:

**Comment by bomjacob** [comment]
It seems you cannot add links to a note in a project, which means that using an issue might still be the best approach (unless we wanna make a issue for each of the code pieces)...
I made a [deprecation project](https://github.com/python-telegram-bot/python-telegram-bot/projects/4) to test things out anyway...

**Comment by Neurrone** [comment]
Should I open a PR that removes all this code at once?

**Comment by rahiel** [comment]
@Neurrone I've split up the tasks in two groups, with the intention that they will be covered in two PRs. This is because we want to keep the backwards-compatibility for a fair period of time. PRs are welcome, feel free to ask questions on any problems you might encounter and add yourself to `AUTHORS.rst` if you like.
