### ISSUE TITLE
[FEATURE] Add Update.effective_sender

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#4085]
We have `Update.effective_user` for the sender of the message. This attribute however misses out on the anonymous sender info provided in `Message.sender_chat`, `MessageReactionUpdated.action_chat` and `Poll.voter_chat`.

I would propose adding a new shortcut to the `Update` class, `effective_sender`. It either returns the sender chats above or effective_user, if they are not set.

**Comment by nemo-1999** [comment]
Hi, I would like to work on this

**Comment by Poolitzer** [comment]
Alright, have fun!

**Comment by Bibo-Joshi** [comment]
@Poolitzer Please keep in mind that this is dependent on the ongoing API 7.0 pr

**Comment by nemo-1999** [comment]
I can wait. Until then I can take a look at the code base and understand the req better

**Comment by harshil21** [comment]
> I can wait. Until then I can take a look at the code base and understand the req better

@nemo-1999 you may start working on this now since it's already merged to master
