### ISSUE TITLE
[FEATURE] Call `out.seek(0)` in `File.download_to_memory`

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#4098]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

After calling `await file.download_to_memory(out)`, you have to call `out.seek(0)` in order to be able to read the content from the `out` object. This is a minor inconvenience and can be confusing for people not familiar with IO-objects.

### Describe the solution you'd like

Call `out.seek(0)`  after 

https://github.com/python-telegram-bot/python-telegram-bot/blob/a8f1164b0cb9bb1e26920a03ae5c88b167bd3041/telegram/_files/file.py#L269

and document this in the docstring.
This would be backward compatible, since calling `out.seek(0)` twice doesn't harm. 

### Additional context

 See e.g. https://t.me/pythontelegrambotgroup/722969.

**Comment by Poolitzer** [comment]
@Bibo-Joshi If some code depends on extending the byte stream though...

**Comment by Bibo-Joshi** [comment]
Fair point. I'll resort to adding a note in the docs, then

**Comment by Poolitzer** [comment]
@Bibo-Joshi Well I am not sure we can&#x27;t provide this functionality. I would argue most users will want seek(0), if someone actually wants the end they can just call seek(0, 2). And I really doubt anyone needs it.

But we should follow our rules of how to make those changes, so I guess at least raise a warning we changed this interface
