### ISSUE TITLE
send_media_group has a error   telegram.error.BadRequest: Failed to send message #1 with the error message "wrong file identifier/http url specified"

### ISSUE THREAD

**Issue by ximo163** [python-telegram-bot/python-telegram-bot#4102]
### Issue I am facing

I have a document_list, which contains files of type InputMediaDocument. I am sure that my file_id is correct and can be successfully sent through context.bot.send_document. However, it cannot be sent successfully when placed in send_media_group.

### Traceback to the issue

```python
await context.bot.send_media_group(chat_id=user_id, media=document_list, caption=document_caption)                            
  File ".../site-packages/telegram/ext/_extbot.py", line 2585, in send_media_group
    return await super().send_media_group(                                                                                                                                         
  File ".../site-packages/telegram/_bot.py", line 525, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102                                                                                                                
  File ".../site-packages/telegram/_bot.py", line 2048, in send_media_group
    result = await self._post(                                                                                                                                                     
  File ".../site-packages/telegram/_bot.py", line 613, in _post
    return await self._do_post(
  File ".../site-packages/telegram/ext/_extbot.py", line 340, in _do_post
    return await super()._do_post(
  File ".../site-packages/telegram/_bot.py", line 641, in _do_post
    return await request.post(
  File ".../site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File ".../site-packages/telegram/request/_baserequest.py", line 379, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Failed to send message #1 with the error message "wrong file identifier/http url specified"

```

### Related part of your code

```python
document_list = [
    InputMediaDocument(media='CgACAgUAAxkBAAICfGXBFT6DT6wazrl4f_5_ifJ89TQXAALyDAACIYRQVnqzHEDl6pKJNAQ'),
    InputMediaDocument(media='CgACAgUAAxkBAAICfGXBFT6DT6wazrl4f_6_ifJ89TQXAALyDAACIYRQVnqzHEDl6pKJNAQ'),
    InputMediaDocument(media='CgACAgUAAxkBAAICfGXBFT6DT6wazrl4f_7_ifJ89TQXAALyDAACIYRQVnqzHEDl6pKJNAQ'),
]
await context.bot.send_media_group(chat_id=user_id, media=document_list, caption=document_caption)                            

```

### Operating System

macos

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot
Version: 20.7
```

**Comment by Poolitzer** [comment]
Hi, this is not an error in our library, rather in the bot api. Please report the bug there.

**Comment by ximo163** [comment]
> Hi, this is not an error in our library, rather in the bot api. Please report the bug there.
> 
> Probably not applicable, I still want to point you towards [tdlib/telegram-bot-api#301](https://github.com/tdlib/telegram-bot-api/issues/301) which was a similar issue

Okay, thank you. It has been two years and it seems like there is no hope for a solution.

**Comment by ximo163** [comment]
But I saw other bots being able to access send_media_group, and I don't know how they did it.

**Comment by Poolitzer** [comment]
@ximo163 The issue is about animations. If you are sure your file_id is a document, your call should work

**Comment by ximo163** [comment]
> @ximo163 The issue is about animations. If you are sure your file_id is a document, your call should work

I am sure that my file_di are all of the document type, but the above error is reported.

**Comment by Poolitzer** [comment]
@ximo163 then report this in the bot api repository :)

**Comment by ximo163** [comment]
I found the reason. The reason is that python-telegram-bot handles animations in a vague way. For the animation type, the obtained message object has two attributes: document and animation. Their file_id is the same. This file_id can be sent using send_animation and send_document, but it is not supported by send_media_group. The error handling of python-telegram-bot is unclear, without clear indication like pyrogram's error message "ValueError: Expected DOCUMENT, got ANIMATION file id instead". Instead, python-telegram-bot's error message is "telegram.error.BadRequest: Failed to send message #1 with the error message 'wrong file identifier/http url specified'". It's not clear.

**Comment by Poolitzer** [comment]
This is all set by the bot api, not us. Please ask them to make a better error

**Comment by ximo163** [comment]
Ok, I understand.
