### ISSUE TITLE
[QUESTION] Send message failed when running multiple applications

### ISSUE THREAD

**Issue by leviethung2103** [python-telegram-bot/python-telegram-bot#4106]
### Issue I am facing

Hello, 

I am currently facing a issue with threading safe problem.

I've built 3 applications.  Each application used schedule library to send the messages out every 15 minutes. 

I've noticed that at the same time, only one application can send the message. The remaining applications can not send the massage.

Thererfore, I think there is a huge problem when developing multiple applications and send the messages concurrency.

Please suggest for me some solutions. 

Thank you

here is an example of first application
<img width="780" alt="CleanShot 2024-02-08 at 09 51 53@2x" src="https://github.com/python-telegram-bot/python-telegram-bot/assets/16741872/45d0de3d-f9c9-4a7f-ad53-21a3c222cf2c">

### Operating System

Linux

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.7
Bot API 6.9
Python 3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0]
```

**Comment by Bibo-Joshi** [comment]
Hi. What exactly do you mean by "application", `telegram.ext.Application` or something else? What does threading have to do with your question - I don't see threading being used in your code snippet. In any case, please note that PTB is not designed to be thread safe. How does it show that the other applicants can not send messages - do you get an exception? Can you provide an  [mwe](../wiki/MWE)?

**Comment by leviethung2103** [comment]
Hi. Thank you for answer my question. I've found that problems with PM2 - Process Manager App. It's actually not a problem with telegram bot. 

Have a nice day.
