### ISSUE TITLE
[FEATURE] Improve Backward Compatibility for pickling

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#4111]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

When TG deprecates attributes, we usually convert them to properties in our classes and issue a warning on access. For this, we rename `Class.attribute` to `Class.._attribute`. This leads to [problems](https://t.me/pythontelegrambotgroup/723964) on un-pickling data that was pickled with previous versions. While this is okay acccording to our [stability policy](https://docs.python-telegram-bot.org/en/v20.8/stability_policy.html#what-doesn-t-this-policy-cover), it would still be nice to handle this better for the users

### Describe the solution you'd like

In `TelegramObjejct.__setstate__`, the current logic is

https://github.com/python-telegram-bot/python-telegram-bot/blob/1cf63c26c59c3db2c938bffe26898216283b60af/telegram/_telegramobject.py#L311-L322

I would like to change this to

1. first try set_attr
2. check if the attribute name is a property
3. if yes, try setting _attributename (unless the name already starts with underscore)
4. if that fails or the attribute is not a property, put the attribute into `api_kwargs` - unless the attribute has a leading underscore. This last part is for when we finally completely remove the property - pickling with the property in place and unpickling without the property in the new version will then simply remove the attribute.

Moreover, in `_apply_api_kwargs`

https://github.com/python-telegram-bot/python-telegram-bot/blob/1cf63c26c59c3db2c938bffe26898216283b60af/telegram/_telegramobject.py#L492-L494

we can first check if tha attribute is a property

### Describe alternatives you've considered

Do nothing as we didn't promise that this works.

### Additional context

https://t.me/pythontelegrambotgroup/723964

**Comment by Trifase** [comment]
As a 'victim' of this unfortunate upgrading consequence, I would like to add that - while 'doing nothing' is of course a valid course of action, it would be nice to *at least* having the un-pickling continue, skipping the deprecated attributes - even with a loss of data - instead of totally crashing and being de-facto locked out of the pickle file.

**Comment by Bibo-Joshi** [comment]
@harshil21 For reference: it&#x27;s also possible to directly check if something is a property: https://stackoverflow.com/a/17735709
Try-except may still be viewed as more elegant, I guess. I&#x27;ll leave that up to you:)
