### ISSUE TITLE
getting errors creating a bot for telgram using the ansible semaphore api 

### ISSUE THREAD

**Issue by RustinCassiem** [python-telegram-bot/python-telegram-bot#4115]
### Issue I am facing

I created this and Im not sure if my variable are correct or not but I get new errors after fix the prevous ones 
```python
from telegram.ext import *
import requests

from queue import Queue

# Telegram Bot Token
TOKEN = "YOUR_TOKEN"

# Ansible Semaphore API Base URL
API_BASE_URL = "https://url/api/v1"

# Function to handle start command
async def start(update, context):
    update.message.reply_text("Welcome to Ansible Bot! Send /login to authenticate.")

# Function to handle login command
def login(update, context):
    update.message.reply_text("Please enter your username:")
    context.user_data['login_state'] = 'username'

# Function to handle username input
def handle_username(update, context):
    context.user_data['username'] = update.message.text
    update.message.reply_text("Please enter your password:")
    context.user_data['login_state'] = 'password'

# Function to handle password input
def handle_password(update, context):
    username = context.user_data['username']
    password = update.message.text
    # Make a POST request to login endpoint
    response = requests.post(API_BASE_URL + "/auth/login", json={"username": username, "password": password})
    if response.status_code == 200:
        # Assuming your API returns a token upon successful login
        token = response.json()["token"]
        context.user_data["token"] = token
        update.message.reply_text("Login successful! You can now run playbooks.")
    else:
        update.message.reply_text("Login failed. Please try again.")

# Function to handle playbook execution
def run_playbook(update, context):
    # Check if user is authenticated
    if 'token' not in context.user_data:
        update.message.reply_text("Please login first using /login command.")
        return

    # Assuming you have an endpoint to trigger playbook execution
    # Example: API_BASE_URL + "/run_playbook"
    run_playbook_url = "/project/1/tasks/8"
    # Extract playbook command from user message
    playbook_command = update.message.text
    # Make a POST request to run playbook endpoint
    response = requests.post(run_playbook_url, headers={"Authorization": "Bearer {}".format(context.user_data['token'])}, json={"playbook_command": playbook_command})
    if response.status_code == 200:
        update.message.reply_text("Playbook execution initiated.")
    else:
        update.message.reply_text("Failed to execute playbook. Please try again.")

# Function to handle unknown commands
def unknown(update, context):
    update.message.reply_text("Sorry, I don't understand that command.")

# Create an instance of the Updater class
updater = Updater(TOKEN, update_queue=Queue())

# Get the dispatcher to register handlers
dispatcher = updater.dispatcher

# Register command handlers
dispatcher.add_handler(CommandHandler("start", start))
dispatcher.add_handler(CommandHandler("login", login))
dispatcher.add_handler(MessageHandler(filters.text & filters.command, handle_username))
dispatcher.add_handler(MessageHandler(filters.text & ~filters.command, handle_password))
dispatcher.add_handler(CommandHandler("run_playbook", run_playbook))
dispatcher.add_handler(MessageHandler(filters.command, unknown))

# Start the bot
updater.start_polling()
updater.idle()
```

### Traceback to the issue

```python
error1 
Traceback (most recent call last):
  File "ansible_telegram_bot.py", line 68, in <module>
    dispatcher = updater.dispatcher
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'Updater' object has no attribute 'dispatcher'

error 2 
Traceback (most recent call last):
  File "ansible_telegram_bot.py", line 63, in <module>
    updater = Updater(TOKEN)
              ^^^^^^^^^^^^^^
TypeError: Updater.__init__() missing 1 required positional argument: 'update_queue'
error 3
```

### Operating System

Linux and windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.8
Bot API 7.0
Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
```

**Comment by Bibo-Joshi** [comment]
@RustinCassiem Hey. You seem to be using the new version (&gt;=20.0) of <code>python-telegram-bot</code> but your code is written for an older and deprecated version (&lt;=13.15).
Please update your code to the new v20 by reading the release notes and the transition guide linked below.
You can also install a version of PTB that is compatible with your code base, but please note that the library has undergone significant changes in v20 and the older version is not supported anymore. It may contain bugs that will not be fixed by the PTB team and it also doesn&#x27;t support new functions added by newer Bot API releases.

**Comment by RustinCassiem** [comment]
So I update the code to >=20 but Im getting  AttributeError: module 'telegram.ext.filters' has no attribute 'text'

`Traceback (most recent call last):
  File "ansible_telegram_bot.py", line 48, in <module>
    app.add_handler(MessageHandler(filters.text & filters.regex(r"^[a-zA-Z0-9_]+$"), handle_username))
AttributeError: module 'telegram.ext.filters' has no attribute 'text'`

`from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, ContextTypes, ConversationHandler
import requests
import telegram.ext.filters as filters

# Create a dictionary to store user credentials
user_credentials = {}

# Function to handle the /start command and prompt the user for their username
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    update.message.reply_text("Please enter your username:")
    context.user_data["next_step"] = "password"

# Function to handle the username entered by the user and prompt for their password
async def handle_username(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    user_credentials["username"] = update.message.text
    update.message.reply_text("Please enter your password:")
    context.user_data["next_step"] = "authenticate"

# Function to handle the password entered by the user and authenticate with Ansible Semaphore API
async def handle_password(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    user_credentials["password"] = update.message.text

    # Authenticate with Ansible Semaphore API using the provided credentials
    auth_payload = {
        "username": user_credentials["username"],
        "password": user_credentials["password"]
    }
    auth_response = requests.post("https://ansible./api/v2/auth/login/", json=auth_payload)

    if auth_response.status_code == 200:
        auth_token = auth_response.json()["token"]

        # Run the script using the obtained authentication token
        # Replace the below URL with the actual endpoint for running a script in Ansible Semaphore
        script_response = requests.post("https://ansible./api/v2/project/1/job_template/2/launch/", headers={"Authorization": f"Token {auth_token}"})

        if script_response.status_code == 200:
            update.message.reply_text("Script execution initiated successfully.")
        else:
            update.message.reply_text("Failed to run the script. Please try again.")
    else:
        update.message.reply_text("Authentication with Ansible Semaphore API failed. Please try again.")

# Update the ApplicationBuilder with the new command and message handlers
app = ApplicationBuilder().token("6").build()
app.add_handler(CommandHandler("start", start))
app.add_handler(MessageHandler(filters.text & filters.regex(r"^[a-zA-Z0-9_]+$"), handle_username))
app.add_handler(MessageHandler(filters.text & ~filters.command, handle_password))
app.run_polling()
`

**Comment by Poolitzer** [comment]
Hi yes, this is because you did not read the transition guide or choose not to apply its content. If you do this you would not face that error.
