### ISSUE TITLE
[BUG] Unsupported urllib3

### ISSUE THREAD

**Issue by chemelli74** [python-telegram-bot/python-telegram-bot#4117]
### Steps to Reproduce

1. Enable Telegram integration in Home Assistant
2. Check the log
3.

### Expected behaviour

Fully support for Home Assistant and no warning logged

### Actual behaviour

2024-02-13 20:01:50.973 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.12/site-packages/telegram/utils/request.py:49: UserWarning: python-telegram-bot is using upstream urllib3. This is allowed but not supported by python-telegram-bot maintainers.

### Operating System

Alpine Linux v3.19

### Version of Python, python-telegram-bot & dependencies

```shell
homeassistant-prod:/etc# python -m telegram
/usr/local/lib/python3.12/site-packages/telegram/utils/request.py:49: UserWarning: python-telegram-bot is using upstream urllib3. This is allowed but not supported by python-telegram-bot maintainers.
  warnings.warn(
python-telegram-bot 13.1
certifi 2024.02.02
Python 3.12.1 (main, Jan  4 2024, 09:41:05) [GCC 13.2.1 20231014]
```

**Comment by Poolitzer** [comment]
Thats not a bug, just a warning; but it is from an old version of our library we no longer support.

**Comment by Bibo-Joshi** [comment]
Also duplicate of #4065 :)
