### ISSUE TITLE
[FEATURE] Add or remove a photo to a message

### ISSUE THREAD

**Issue by javaisntlanguage** [python-telegram-bot/python-telegram-bot#4123]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

I want edit message instead of sending new message. I can't delete/add photo to message, if it has/hasn't it

### Describe the solution you'd like

add possibility to add or delete photo to message

**Comment by Bibo-Joshi** [comment]
you can't add a photo to a text message and you can't remove a photo from a photo message. That's simply not supported by the Bot API.
