### ISSUE TITLE
[QUESTION] How to charge recurring fees such as subscription ？

### ISSUE THREAD

**Issue by JunhaoWang** [python-telegram-bot/python-telegram-bot#4137]
### Issue I am facing

Current send_invoice api can handle single time purchase, but is there a way user can pay for a subscription?

### Operating System

NA

### Version of Python, python-telegram-bot & dependencies

```shell
NA
```

**Comment by Poolitzer** [comment]
@JunhaoWang No, the API doesn&#x27;t support that
