### ISSUE TITLE
[QUESTION] Embedded image using binary data, without links

### ISSUE THREAD

**Issue by AkiraRy** [python-telegram-bot/python-telegram-bot#4138]
### Issue I am facing

I have function called `render` which renders japanese kanji as Image using Pillow library and returns binary data of that image.
After that I use `bot.send_photo(chat_id=update.effective_chat.id, photo=img)` but the text will be below the rendered image.

(usage of just `bot.send_photo()`  )
![image](https://github.com/python-telegram-bot/python-telegram-bot/assets/106382882/785baf39-3605-478b-b19c-83b0e66ca253)

I want it to look like this:
![image](https://github.com/python-telegram-bot/python-telegram-bot/assets/106382882/c504b198-1303-4589-84a6-d26d881e84c6)

I'm aware that i can send an embedded image like so, where `img` is URL . 
 **But I want to send binary data without saving it to the disk.**

```shell
await bot.send_message(
            chat_id=effective_chat.id,
            text=f'sometext\n<a href="{img}">&#8205;</a>',
            parse_mode=telegram.constants.ParseMode.HTML
        )
```
Also `<img src="">` tag doesn't work here If i wanted to replace `<a>` tag with tit 

I have read both PTB documentation and official documentation on this matter but couldn't find a solution.
[telegram.Bot.send_photo](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.send_photo)
core telegram [sendPhoto](https://core.telegram.org/bots/api#sendphoto)

Any help would be greatly appreciated!

### Operating System

Windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.3
Bot API 6.7
Python 3.9.16 (main, May 17 2023, 17:49:16) [MSC v.1916 64 bit (AMD64)]
```

**Comment by Poolitzer** [comment]
Hi thats not a thing. You need to upload it somewhere and link to it to get this result

**Comment by AkiraRy** [comment]
I see, but is it even possible to implement in PTB?

**Comment by Poolitzer** [comment]
Sending a link to a photo? Sure. Uploading the photo? That is not a job for PTB.

**Comment by AkiraRy** [comment]
There is difference, when you have several thouthands of different words, as well as fonts it is not efficient to upload every combination to web service

**Comment by AkiraRy** [comment]
Well I will just have text under photo then
