### ISSUE TITLE
Dont end the conversation on Timeout

### ISSUE THREAD

**Issue by vogdb** [python-telegram-bot/python-telegram-bot#4153]
### Issue I am facing

Conversation ends if timeout occurs but I would like to switch to another Conversation state instead. I'm developing a quiz game where you need to answer the question in 60 seconds, If user timeouts then I show the next question. Currently it can't be done as timeout callback ends the conversation with user no matter what.

### Related part of your code

```python
https://pastebin.com/kkvWGZzn
```

### Operating System

Ubuntu 20

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.8. python-telegram-bot 21
```

**Comment by Bibo-Joshi** [comment]
@vogdb Hi. I&#x27;m pretty sure that this is already being tracked in #2770.

**Comment by vogdb** [comment]
Thank you @Bibo-Joshi ! I'm closing this issue. I couldn't find any temporary solution to my problem in the mentioned issue. Can you advice on something? It's critical for me to implement it.

**Comment by Bibo-Joshi** [comment]
There is no workaround atm other than patching CH yourself , sorry

**Comment by vogdb** [comment]
thank you for such swift feedback!
