### ISSUE TITLE
[BUG] telegram.ext.Application.bot.set_my_commands does accept capital letter

### ISSUE THREAD

**Issue by JonahTzuChi** [python-telegram-bot/python-telegram-bot#4154]
### Steps to Reproduce

1. Define `post_init` method to specify the commands and the corresponding description. Use capital letter in the command.
```
async def post_init(application: Application):
    await application.bot.set_my_commands(
        [
            BotCommand("/addPhoto", "Set bot to accept photo"),
        ]
``` 
2. Build the bot with snippet below
```
application = (
        ApplicationBuilder()
        .token(config.worker)
        .concurrent_updates(True)
        .rate_limiter(AIORateLimiter(max_retries=5))
        .post_init(post_init)
        .build()
    )
```
3. Add handler to bot
```
application.add_handler(
        CommandHandler("addPhoto", tu.set_addPhoto_mode_handle, filters=user_filter)
    )
```
4. Start polling
```
application.run_polling()
```

### Expected behaviour

Successfully build the bot with defined commands.

### Actual behaviour

Get error `telegram.error.BadRequest: Bot_command_invalid` while building the bot.

### Operating System

Docker python:3.10-slim

### Version of Python, python-telegram-bot & dependencies

```shell
# python:3.10-slim
python-telegram-bot[rate-limiter]==21.0.1
PyYAML==6.0
pymongo==4.3.3
python-dotenv==0.21.0
pydub==0.25.1
charade==1.0.3
requests==2.31.0
numpy==1.24.4
Pillow==9.0.1
```

### Relevant log output

```python
worker_1      | Traceback (most recent call last):
worker_1      |   File "/code/bot/bot.py", line 144, in <module>
worker_1      |     run_bot()
worker_1      |   File "/code/bot/bot.py", line 140, in run_bot
worker_1      |     application.run_polling()
worker_1      |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_application.py", line 836, in run_polling
worker_1      |     return self.__run(
worker_1      |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_application.py", line 1036, in __run
worker_1      |     raise exc
worker_1      |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_application.py", line 1027, in __run
worker_1      |     loop.run_until_complete(self.post_init(self))
worker_1      |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
worker_1      |     return future.result()
worker_1      |   File "/code/bot/bot.py", line 20, in post_init
worker_1      |     await application.bot.set_my_commands(
worker_1      |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 3384, in set_my_commands
worker_1      |     return await super().set_my_commands(
worker_1      |   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 541, in decorator
worker_1      |     result = await func(self, *args, **kwargs)
worker_1      |   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 7305, in set_my_commands
worker_1      |     return await self._post(
worker_1      |   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 629, in _post
worker_1      |     return await self._do_post(
worker_1      |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 367, in _do_post
worker_1      |     return await self.rate_limiter.process_request(
worker_1      |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_aioratelimiter.py", line 245, in process_request
worker_1      |     return await self._run_request(
worker_1      |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_aioratelimiter.py", line 203, in _run_request
worker_1      |     return await callback(*args, **kwargs)
worker_1      |   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 657, in _do_post
worker_1      |     return await request.post(
worker_1      |   File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 200, in post
worker_1      |     result = await self._request_wrapper(
worker_1      |   File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 379, in _request_wrapper
worker_1      |     raise BadRequest(message)
worker_1      | telegram.error.BadRequest: Bot_command_invalid
```

### Additional Context

- __Build without `post_init`__: I was able to build the bot without it and calling /addPhoto does return the desired response

- __Build with `post_init`, command as `add_photo`__: I was able to build the bot with `add_photo`  and calling /add_photo does return the desired response.

**Comment by Poolitzer** [comment]
Hi, that is a limitation of the bot api (see https://core.telegram.org/bots/api#botcommand). I do not see the need to manually double check this on our end, are you requesting that? It would only change the error message a bit...

**Comment by JonahTzuChi** [comment]
> Hi, that is a limitation of the bot api (see https://core.telegram.org/bots/api#botcommand). I do not see the need to manually double check this on our end, are you requesting that? It would only change the error message a bit...

I was expecting BotCommand to accept uppercase letter like the CommandaHandler, but based on the link you share the BotCommand only accept lowercase. 

Anyway, thanks for referencing this [page]( https://core.telegram.org/bots/api#botcommand). I only reading from https://docs.python-telegram-bot.org/en/v21.0.1/telegram.bot.html#telegram.Bot.set_my_commands. 

I can settle with lowercase, but I think it's necessary to standardize the behavior of BotCommand and CommandHandler in terms of the string format they accept.

**Comment by Poolitzer** [comment]
Well our docs have a link in the second paragraph to the restrictions of a bot command.

CommandHandler mentions that inputting commands into it is case insensitive, I think that is nicer than raising an error.

**Comment by Bibo-Joshi** [comment]
I want to add that we made a concious decision not to check Bot API parameters for limitation violations within the PTB code, as documented in #2901 and #30024.
