### ISSUE TITLE
[BUG] AttributeError: 'File' object has no attribute 'download_to_drive'

### ISSUE THREAD

**Issue by Sp4g0** [python-telegram-bot/python-telegram-bot#4159]
### Steps to Reproduce

voice_id = message.voice.file_id
new_file = bot.get_file(voice_id)
new_file.download_to_drive()

### Expected behaviour

download voice message

### Actual behaviour

can't download voice message

### Operating System

windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 21.0.1
Bot API 7.1
Python 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
```

### Additional Context

method download was deprecated from version 20

**Comment by GivenFLY** [comment]
Just tested using the same version and same environment using this snippet, everything works

```python
from telegram import Update
from telegram.ext import Application, MessageHandler, filters


async def download_voice(update, context) -> None:
    file_id = update.message.voice.file_id
    new_file = await context.bot.get_file(file_id)
    await new_file.download_to_drive()


def main() -> None:
    application = Application.builder().token("TOKEN").build()

    application.add_handler(MessageHandler(filters.VOICE, download_voice))

    application.run_polling(allowed_updates=Update.ALL_TYPES)


if __name__ == "__main__":
    main()
```

**Comment by Sp4g0** [comment]
i'll try tnx but documentation is not too clear https://github.com/python-telegram-bot/python-telegram-bot/wiki/Working-with-Files-and-Media

**Comment by Sp4g0** [comment]
@Poolitzer I would like to have more examples, I have read all the documentation for get_file and download_to_drive.  I also saw the code of the File class but it is not specified that the update is needed as in the example they provided in the previous comment.  Thanks for the support.

**Comment by Poolitzer** [comment]
> I would like to have more example

But you already linked to the wiki page, which already has the exact example helpfully written out above.
