### ISSUE TITLE
How to use per_message=True?

### ISSUE THREAD

**Issue by remokon** [python-telegram-bot/python-telegram-bot#4164]
### Issue I am facing

Imagine there is some user input based on a specific search command, called within `ConversationHandler` with standard per_chat and per_user as True. Let's say this user was to type `/search x`, which yields a finite number of results featuring a reply markup that allows the user to cycle through these results. If the same user were to initiate a new search, `/search y`, and wanted to go back to the first search to still go through the results, they'd find that it is actually cycling through y-based results, not the x-based it once was on that message.
Therefore, one would naturally incline towards per_message=True. However, having to use only `CallbackQueryHandler` objects, it is hard to understand how to trigger the conversation (like in `CommandHandler`'s command argument).

Would it be possible to showcase an example?

### Operating System

Ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 21.0.1
Bot API 7.1
Python 3.12.1 (main, Feb  4 2024, 19:38:15) [GCC 11.4.0]
```

**Comment by Poolitzer** [comment]
You could just trigger the conv by the first button press of the generated menu?
