### ISSUE TITLE
[Feature] API 7.2

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#4179]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Next bot api update \o/

> [!IMPORTANT]  
> * Comment here or in the dev group what you want to work on so we can assign you
> * Please copy the relevant part of the checklist from #4179 to your PR and make sure to cover everything :)
> * Please base your branch on the [`api-7.2`](https://github.com/python-telegram-bot/python-telegram-bot/tree/api-7.2) branch
> * If this is your first contribution, please be sure to read the [contribution guide](https://docs.python-telegram-bot.org/en/v20.7/contributing.html) and feel free to reach out with any questions via https://t.me/pythontelegrambotchannel/105

### Describe the solution you'd like

Integration with Business Accounts [Taken by @harshil21]
-  [x]  Added the class [BusinessConnection](https://core.telegram.org/bots/api#businessconnection) and updates about the connection or disconnection of the bot to a business account, represented by the field business_connection in the class [Update](https://core.telegram.org/bots/api#update).
- [x] Added updates about new messages in a business account connected to the bot, represented by the field business_message in the class [Update](https://core.telegram.org/bots/api#update).
- [x] Added updates about message edits in a business account connected to the bot, represented by the field edited_business_message in the class [Update](https://core.telegram.org/bots/api#update).
- [x] Added updates about message deletion in a business account connected to the bot, represented by the class [BusinessMessagesDeleted](https://core.telegram.org/bots/api#businessmessagesdeleted) and the field deleted_business_messages in the class [Update](https://core.telegram.org/bots/api#update).
- [x] Added the method [getBusinessConnection](https://core.telegram.org/bots/api#getbusinessconnection).

Working on Behalf of Business Accounts [Taken by @harshil21]
- [x] Added the parameter business_connection_id to the methods [sendMessage](https://core.telegram.org/bots/api#sendmessage), [sendPhoto](https://core.telegram.org/bots/api#sendphoto), [sendVideo](https://core.telegram.org/bots/api#sendvideo), [sendAnimation](https://core.telegram.org/bots/api#sendanimation), [sendAudio](https://core.telegram.org/bots/api#sendaudio), [sendDocument](https://core.telegram.org/bots/api#senddocument), [sendSticker](https://core.telegram.org/bots/api#sendsticker), [sendVideoNote](https://core.telegram.org/bots/api#sendvideonote), [sendVoice](https://core.telegram.org/bots/api#sendvoice), [sendLocation](https://core.telegram.org/bots/api#sendlocation), [sendVenue](https://core.telegram.org/bots/api#sendvenue), [sendContact](https://core.telegram.org/bots/api#sendcontact), [sendPoll](https://core.telegram.org/bots/api#sendpoll), [sendDice](https://core.telegram.org/bots/api#senddice), [sendGame](https://core.telegram.org/bots/api#sendgame), and [sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup).
- [x] Added the parameter business_connection_id to the method [sendChatAction](https://core.telegram.org/bots/api#sendchataction).
- [x] Added the field business_connection_id to the class [Message](https://core.telegram.org/bots/api#message).
- [x] Added the field sender_business_bot to the class [Message](https://core.telegram.org/bots/api#message).

Information about Business Accounts [Taken by @aelkheir - #4183]

- [x] Added the class [BusinessIntro](https://core.telegram.org/bots/api#businessintro) and the field business_intro to the class [Chat](https://core.telegram.org/bots/api#chat).
- [x] Added the class [BusinessLocation](https://core.telegram.org/bots/api#businesslocation) and the field business_location to the class [Chat](https://core.telegram.org/bots/api#chat).
- [x] Added the classes [BusinessOpeningHours](https://core.telegram.org/bots/api#businessopeninghours) and [BusinessOpeningHoursInterval](https://core.telegram.org/bots/api#businessopeninghoursinterval) and the field business_opening_hours to the class [Chat](https://core.telegram.org/bots/api#chat).

Mixed-Format Sticker Packs [Taken by @harshil21]

- [x] Removed the fields is_animated and is_video from the class [StickerSet](https://core.telegram.org/bots/api#stickerset).
- [x] Added the field format to the class [InputSticker](https://core.telegram.org/bots/api#inputsticker).
- [x] Removed the parameter sticker_format from the method [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset).
- [x] Added the parameter format to the method [setStickerSetThumbnail](https://core.telegram.org/bots/api#setstickersetthumbnail).
- [x] Increased the maximum number of stickers in any regular and mask sticker set to 120.
- [x] Allowed to upload WEBM stickers using [SendSticker](https://core.telegram.org/bots/api#sendsticker).

Request Chat Improvements [Taken by @clot27]

- [x] Added the fields request_name, request_username, and request_photo to the class [KeyboardButtonRequestUsers](https://core.telegram.org/bots/api#keyboardbuttonrequestusers).
- [x] Added the fields request_title, request_username, and request_photo to the class [KeyboardButtonRequestChat](https://core.telegram.org/bots/api#keyboardbuttonrequestchat).
- [x] Added the class SharedUser and replaced the field user_ids in the class [UsersShared](https://core.telegram.org/bots/api#usersshared) with the field users.
- [x] Added the fields title, username, and photo to the class [ChatShared](https://core.telegram.org/bots/api#chatshared).

Other Changes

- [x] Added the field is_from_offline to the class [Message](https://core.telegram.org/bots/api#message). [Taken by @mahdyar - #4189]
- [x] Added the field can_connect_to_business to the class [User](https://core.telegram.org/bots/api#user) [Taken by @harshil21].
- [x] Added the field personal_chat to the class [Chat](https://core.telegram.org/bots/api#chat) [Taken by @harshil21].
- [x] Added the method [replaceStickerInSet](https://core.telegram.org/bots/api#replacestickerinset) [Taken by @harshil21],
- [x] Added the class [Birthdate](https://core.telegram.org/bots/api#birthdate) and the field birthdate to the class [Chat](https://core.telegram.org/bots/api#chat) [Taken by @harshil21].
- ~Added the field BiometricManager to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps).~

### Describe alternatives you've considered

If you want to contribute, you can start from the [Contribution Guide](https://docs.python-telegram-bot.org/en/v20.7/contributing.html).

### Additional context

Please comment below before start working on any part of the update so as to keep things in track and avoid double work.

**Comment by harshil21** [comment]
I'll take the "working on behalf of business accounts" section

**Comment by aelkheir** [comment]
I wanted to create some ptb quality classes so badly 🥹, soo

Information about Business Accounts

- [ ]  Added the class BusinessIntro and the field business_intro to the class Chat.
- [ ]  Added the class BusinessLocation and the field business_location to the class Chat.
- [ ]  Added the classes BusinessOpeningHours and BusinessOpeningHoursInterval and the field business_opening_hours to the class Chat.

**Comment by clot27** [comment]
I'll take the "Request Chat Improvements" part

**Comment by ManikMKR11** [comment]
i really want to work here and contribute ♥️♥️♥️
if any easy topic is here which will suitable for easy to start with,
any suggestion pls me, i will tey to check, i am still not goood in OOP here, i need to look pls suggest me something which topic to choose,
like👇👇👇

maybe i can remove the is_animated or is_video parameters to remove from the Sticker Set Class

**Comment by RanaUniverse** [comment]
i really want to work here and contribute ♥️♥️♥️
if any easy topic is here which will suitable for easy to start with as i want to start freshly,
any suggestion pls me, i will try to check, i am still not good in OOP here, i need to look pls suggest me something which topic to choose,
like👇👇👇

maybe i can remove the is_animated or is_video parameters to remove from the Sticker Set Class

**Comment by harshil21** [comment]
> if any easy topic is here which will suitable for easy to start with as i want to start freshly, any suggestion pls me

alright, you can try doing the "Added the field is_from_offline to the class [Message](https://core.telegram.org/bots/api#message)." part. You basically have to copy the field documentation from core.telegram.org/bots/api#message into our library. 

Remember to base your branch on api-7.2.

**Comment by RanaUniverse** [comment]
still it looks like i need a more learn python with background works with dunder and so on, 
i think if i will download the PTB zip and edit and send the edited zip to u then can be be done,

as the git commands which are said in the guide section is really going over my head, 
and i am not familiar with these.

**Comment by harshil21** [comment]
@RanaUniverse If that is the case, you can learn git and get more familiar with OOP and contribute in another issue at a later date.

**Comment by mahdyar** [comment]
I'll take the "Added the field is_from_offline to the class Message" section
