### ISSUE TITLE
[BUG] StickerSet require parameters that API no longer sends

### ISSUE THREAD

**Issue by kaine119** [python-telegram-bot/python-telegram-bot#4181]
### Steps to Reproduce

1. Call `bot.get_sticker_set(name)`

### Expected behaviour

`.get_sticker_set()` should return a `StickerSet` object

### Actual behaviour

`.get_sticker_set()` throws: `TypeError: StickerSet.__init__() missing 2 required positional arguments: 'is_animated' and 'is_video'`

### Operating System

Windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.8
Bot API 7.0
Python 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
```

### Relevant log output

```python
File "C:\Users\...\env\Lib\site-packages\telegram\ext\_extbot.py", line 1934, in get_sticker_set
    return await super().get_sticker_set(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\env\Lib\site-packages\telegram\_bot.py", line 542, in decorator
    result = await func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\env\Lib\site-packages\telegram\_bot.py", line 6092, in get_sticker_set
    return StickerSet.de_json(result, self)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\env\Lib\site-packages\telegram\_files\sticker.py", line 330, in de_json
    return super()._de_json(data=data, bot=bot, api_kwargs=api_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\env\Lib\site-packages\telegram\_telegramobject.py", line 403, in _de_json
    raise exc
  File "C:\Users\...\env\Lib\site-packages\telegram\_telegramobject.py", line 400, in _de_json
    obj = cls(**data, api_kwargs=api_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StickerSet.__init__() missing 2 required positional arguments: 'is_animated' and 'is_video'
```

### Additional Context

Telegram seems to be gearing up to allow mixed-media sticker packs. From [yesterday's update](https://core.telegram.org/bots/api#march-31-2024):

>## Mixed-Format Sticker Packs
>* Removed the fields is_animated and is_video from the class [StickerSet](https://core.telegram.org/bots/api#stickerset).
>* Added the field format to the class [InputSticker](https://core.telegram.org/bots/api#inputsticker).

Not sure if they've made any other announcements yet, but the `StickerSet` class may need to be reworked.

**Comment by harshil21** [comment]
Hi, thanks for the issue. This is known by the dev team, and we are working on the next update which will fix this. For now a workaround is to use `Bot.do_api_request("get_sticker_set", {"name": sticker_set_name})`. There will be a channel post on this soon.

**Comment by Worrah** [comment]
> Hi, thanks for the issue. This is known by the dev team, and we are working on the next update which will fix this. For now a workaround is to use `Bot.do_api_request("get_sticker_set", {"name": sticker_set_name})`. There will be a channel post on this soon.

im sorry, but what if i am using the python-telegram-bot 12.5 ? no chance to use it?

**Comment by harshil21** [comment]
> > Hi, thanks for the issue. This is known by the dev team, and we are working on the next update which will fix this. For now a workaround is to use `Bot.do_api_request("get_sticker_set", {"name": sticker_set_name})`. There will be a channel post on this soon.
> 
> im sorry, but what if i am using the python-telegram-bot 12.5 ? no chance to use it? 

No, that version is more than 5 years old.

**Comment by starry-shivam** [comment]
> im sorry, but what if i am using the python-telegram-bot 12.5 ? no chance to use it?

You can do something like this:

```python
resp = bot._request.post(
        f"{bot.base_url}/getStickerSet",
        {
            "name": packname,
        },
    )
```
Then, manually call `StickerSet.de_json()` on the returned data. It's a bit of a dirty hack, requiring access to a private property, I know, but it's better than nothing if you're for whatever reason stuck with v12/13.x

**Comment by Worrah** [comment]
> > im sorry, but what if i am using the python-telegram-bot 12.5 ? no chance to use it?
> 
> You can do something like this:
> 
> ```python
> resp = bot._request.post(
>         f"{bot.base_url}/getStickerSet",
>         {
>             "name": packname,
>         },
>     )
> ```
> 
> Then, manually call `StickerSet.de_json()` on the returned data, or just use the json data directly. It's a bit of a dirty hack, requiring access to a private property, I know, but it's better than nothing if you're for whatever reason stuck with v12/13.x

well, i already saved every sticker id one by one =_= but thank you anyway :D
