### ISSUE TITLE
[QUESTION] running other coroutines along with run_poll

### ISSUE THREAD

**Issue by DaFrenchFrog** [python-telegram-bot/python-telegram-bot#4197]
### Issue I am facing

Hi,

 I need to run other coroutines along with the run_poll method, but obviously if I run my task then I can't run the bot poll, and vice-versa...

So I guess I need to include the TG bot routine with the others but I get a "RuntimeError: This event loop is already running" error... I understand why but I don't know how to solve the issue.

### Traceback to the issue

```python
Traceback (most recent call last):
  File "/home/romaing/env/lib/python3.9/site-packages/telegram/ext/_application.py", line 1036, in __run
    raise exc
  File "/home/romaing/env/lib/python3.9/site-packages/telegram/ext/_application.py", line 1025, in __run
    loop.run_until_complete(self.initialize())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 618, in run_until_complete
    self._check_running()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 578, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

### Related part of your code

```python
def main():
    rpi_name = socket.gethostname()
    asyncio.run(async_sarter())


async def async_sarter():
    status_manager = StatusManager.StatusManager()
    talkie = Talkie(status_manager, device_id=DEVICE_ID)
    input_manager = Input.InputManager(talkie.on_button_press, talkie.on_button_release)
    telegramManager = TelegramBotManager()

    tasks = [
        asyncio.create_task(input_manager.listen()),
        asyncio.create_task(talkie.led_check()),
        asyncio.create_task(telegramManager.application.run_polling()),
    ]
    await asyncio.gather(*tasks)
```

### Operating System

Debian

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.9.2
python-telegram-bot 21.0.1
Bot API 7.1
Python 3.9.2 (default, Mar 12 2021, 04:06:34)  [GCC 10.2.1 20210110]
```

**Comment by Poolitzer** [comment]
You do either the steps of (our wiki)[https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#running-ptb-alongside-other-asyncio-frameworks] or you put your other code in a task in post_init from ApplicationBuilder.

**Comment by DaFrenchFrog** [comment]
Thx ! I didn't notice the wiki...

I did this and it seems to be working great !

`async def async_starter():
    status_manager = StatusManager.StatusManager()
    talkie = Talkie(status_manager, device_id=DEVICE_ID)
    input_manager = Input.InputManager(talkie.on_button_press, talkie.on_button_release)
    telegramManager = TelegramBotManager()
    await telegramManager.application.initialize()
    await telegramManager.application.start()
    await telegramManager.application.updater.start_polling()
    # update_manager = AppUpdater()
    # task_btn_listener = asyncio.create_task(inputManager.listen())
    # task_led_manager = asyncio.create_task(talkie.led_check())
    # task_app_version_manager = asyncio.create_task(update_manager.version_check())
    tasks = [
        asyncio.create_task(input_manager.listen()),
        asyncio.create_task(talkie.led_check()),
        # asyncio.create_task(telegramManager.application.updater.start_polling()),
        # asyncio.create_task(update_manager.version_check()),
    ]
    await asyncio.gather(*tasks)

    await telegramManager.application.updater.stop()
    await telegramManager.application.stop()
    await telegramManager.application.shutdown()`
