### ISSUE TITLE
[BUG] Getting text_markdown_v2 from message does not always work correctly when the message contains blockquote entities

### ISSUE THREAD

**Issue by TarasY5** [python-telegram-bot/python-telegram-bot#4219]
### Steps to Reproduce

I modified the echobot example a bit to reproduce this bug.
Send to bot message with quote and some text after it.
Then reply to message that bot send to you, using command /copy_markdown_v2.

```python
import logging

from telegram import Update
from telegram.constants import ParseMode
from telegram.ext import Application, CommandHandler, ContextTypes, MessageHandler, filters

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO
)

logging.getLogger("httpx").setLevel(logging.WARNING)
logger = logging.getLogger(__name__)
EXEMPLE_MESSAGE_TEXT = ">Quote text\n\nSome other text\nAnd more text"


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Send a message when the command /start is issued."""
    user = update.effective_user
    await update.message.reply_html(
        rf"Hi {user.mention_html()}!"
    )


async def echo(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Echo the user message."""
    await update.message.reply_text(update.message.text_markdown_v2, parse_mode=ParseMode.MARKDOWN_V2)


async def copy_message_markdown(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if update.message.reply_to_message is None:
        await update.message.reply_text("Reply with this command to message with quote")
    text = update.message.reply_to_message.text_markdown_v2
    await update.message.reply_text(text, parse_mode=ParseMode.MARKDOWN_V2)


async def copy_message_html(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if update.message.reply_to_message is None:
        await update.message.reply_text("Reply with this command to message with quote")
    text = update.message.reply_to_message.text_html
    await update.message.reply_text(text, parse_mode=ParseMode.HTML)


def main() -> None:
    application = Application.builder().token("TOKEN").build()

    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("copy_markdown_v2", copy_message_markdown))
    application.add_handler(CommandHandler("copy_html", copy_message_html))
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, echo))
    application.run_polling()


if __name__ == "__main__":
    main()

```

### Expected behaviour

When bot sends back update.message.reply_to_message.**text_markdown_v2** it should be identical with original message.

It works as expected with update.message.reply_to_message.**text_html**

### Actual behaviour

When I reply with /copy_markdown_v2 to bot's message it messes up the blockquote formatting by concatenating it with the next line.
/copy_markdown_v2 only takes text_markdown_v2 from original message and does not change anything, so messages should be identical.

/copy_html does the same thing but with text_html and works correctly.

![Exemple](https://github.com/python-telegram-bot/python-telegram-bot/assets/147804835/2380a572-f69d-40fb-b222-cd462d6eede1)

Sometimes it also does not work right when echoing user's messages:
![936236834](https://github.com/python-telegram-bot/python-telegram-bot/assets/147804835/aa072072-f691-4d32-aa5b-174512ebef33)

I added print(update.message.reply_to_message.entities) to see the difference between these two messages that was sent by me in last picture:
First `(MessageEntity(length=5, offset=0, type=<MessageEntityType.BLOCKQUOTE>),)`
Second `(MessageEntity(length=6, offset=0, type=<MessageEntityType.BLOCKQUOTE>),)`

### Operating System

Ubuntu 23.10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 21.1.1
Bot API 7.2
Python 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0]
```

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for reaching out. We are aware of this behavior, but this is accepted and documented in the docs of [text_markdown_v2](https://docs.python-telegram-bot.org/en/v21.1.1/telegram.message.html#telegram.Message.text_markdown_v2). If you are interested in more background story, please have a look at the discussion in #4308.
As alternative, Telegram recommends that you work directly with `Message.entities.`
I expect that my answer will be unsatisfactory for you - as it is for me - but this is the current status...

**Comment by TarasY5** [comment]
> Hi. Thanks for reaching out. We are aware of this behavior, but this is accepted and documented in the docs of [text_markdown_v2](https://docs.python-telegram-bot.org/en/v21.1.1/telegram.message.html#telegram.Message.text_markdown_v2).

Thanks for the quick reply and sorry I don't know how I read the documentation and didn't see that warning.

**Comment by TarasY5** [comment]
> If you are interested in more background story, please have a look at the discussion in #4038.

Hi again, I took some time and looked through the discussion and the code responsible for `text_markdown_v2` and found the following:
```python
insert = ">" + "\n>".join(escaped_text.splitlines())
```
`/n` at the end of `escaped_text` will be ignored by `splitlines()` that is what causes behavior which I described in the issue.
When I added `insert += "\n" if escaped_text.endswith("\n") else ""` my issue was solved.


But there is another, and it is more about Telegram Desktop only:
If the blockquote is immediately followed by text without `\n`, the text will be attached to the blockquote, and if blockquote is immediately after text the `telegram.error.BadRequest: Can't parse entities: character '>' is reserved and must be escaped with the preceding '\'` is raised.
Telegram Desktop allows writing blockquote like this
![image](https://github.com/python-telegram-bot/python-telegram-bot/assets/147804835/d7de34e0-2ba9-4369-b555-aa4c5553481a)
And after sending, blockquote is shown on separate line, but there is no `\n` at all.
![image](https://github.com/python-telegram-bot/python-telegram-bot/assets/147804835/bda6c3ec-bd66-43d9-a687-3e17cb854d74)


Since we know where quote actualy starts and ends, I think, it can be fixed, by adding check if there is `\n` in the beginning and ending of blockquote, and adding it if needed.

I changed localy this line:
https://github.com/python-telegram-bot/python-telegram-bot/blob/ee88973fee47fa6a2113af9a749e9726d7b76d20/telegram/_message.py#L4562
to this:
```python
# Check if there's no \n before blockquote and blockquote is not at the beginning of message
if message_text[entity.offset - 1] != "\n" and entity.offset != 0:
    insert = "\n>" + "\n>".join(escaped_text.splitlines())
else:
    insert = ">" + "\n>".join(escaped_text.splitlines())
# Check if blockquote is not the last thing in message
if entity.length + entity.offset != len(message_text):
    # Check if there's an \n after blockquote
    if message_text[entity.length + entity.offset] != "\n":
        insert += "\n"
```
And everything works as expected.

![gif](https://github.com/python-telegram-bot/python-telegram-bot/assets/147804835/09192916-3fcd-4653-858b-63fccddb8eca)

The thing is that we add `\n` which were not there before, but it should be there according to Telegram's recommendations as in that, mentioned earlier, [warning](https://docs.python-telegram-bot.org/en/v21.1.1/telegram.message.html#telegram.Message.text_markdown_v2):
>Telegram recommends that entities of type [BLOCKQUOTE](https://docs.python-telegram-bot.org/en/v21.1.1/telegram.messageentity.html#telegram.MessageEntity.BLOCKQUOTE) and [PRE](https://docs.python-telegram-bot.org/en/v21.1.1/telegram.messageentity.html#telegram.MessageEntity.PRE) should start and end on a new line

Hope this will help resolve the issue.

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for the additional investigation. TBH I can't really form a opinion atm if this would affect any other special cases/introduce different problems. At least one point that I see is that simply checking for `endswith("\n")`  is not enough, since the text could actually end on an escaped `\\n`.
Frankly, since TG officially discouraged us from providing these proporties, I'm not very motivated to try and cover every edge case … This is also why we included the note in the docs.

**Comment by TarasY5** [comment]
No problem.
Then I'll use HTML, it is much more convenient and predictable.
Thank you for your time.
