### ISSUE TITLE
[QUESTION] Get User "Typing" behavior

### ISSUE THREAD

**Issue by ttrungtin** [python-telegram-bot/python-telegram-bot#4234]
### Issue I am facing

I am having a problem that I need to send a list of messages which user send to the bot after they done typing for 5 seconds. I am wondering is there any solution that to catch the "Typing" behavior from the User?

### Operating System

Ubuntu 23.10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 21.1.1
Bot API 7.2
Python 3.9.19 (main, Mar 21 2024, 17:11:28)  [GCC 11.2.0]
```

**Comment by Poolitzer** [comment]
@ttrungtin Hi, no. You can only catch the resulting message when someone finished typing.
