### ISSUE TITLE
[FEATURE] Make has_args in CommandHandler accept str / pattern in addition to None, bool and int

### ISSUE THREAD

**Issue by uniquetrij** [python-telegram-bot/python-telegram-bot#4258]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

While `CommandHandler` can be currently filtered based on `int` `has_args` matching number of arguments, this can be further enhanced to check the value of the arguments as well.

### Describe the solution you'd like

If `has_args`  can also accept `str` or `Pattern[str]`, then `CommandHandler` can filter argument values. 

Example Commands:
`/start type_one payload_for_type_one`
`/start type_two payload_for_type_two`

`CommandHandler('start', fn_type_one, has_args='^type_one')`
`CommandHandler('start', fn_type_two, has_args='^type_two')`

### Describe alternatives you've considered

Although this may be achieved using `MessageHandler` with filter combination `filters.COMMAND & filters.Regex()` , but it doesn't feel elegant. Also, the arguments won't be available in `context.args`, and would require separate parsing. 

An example implementation of the requested feature may be as follows.

```

class CommandHandler(BaseHandler[Update, CCT]):
    ...
    def __init__(
        self,
        ...,
        has_args: Optional[Union[bool, int, str, Pattern[str]]] = None, #  <- add str and Pattern[str]
    ):
            ...
            self.has_args: Optional[Union[bool, int, str, Pattern[str]]] = has_args # <- add str and Pattern[str]
            ...


    def _check_correct_args(self, args: List[str]) -> Optional[bool]:
        ...
        return bool(
           ...
            or ((isinstance(self.has_args, str) or (isinstance(self.has_args, Pattern[str]))) and re.match(self.has_args, ' '.join(args))) #  <- add this line       
        )

```

### Additional context

If the above implementation looks satisfactory, I'll make a PR. Please let me know.

**Comment by bqback** [comment]
> Although this may be achieved using MessageHandler with filter combination filters.COMMAND & filters.Regex()

CommandHandler already accepts filters.

**Comment by uniquetrij** [comment]
Thanks for the clarification

**Comment by Bibo-Joshi** [comment]
For completeness, let me also point to the discussion in #2219 and #3798
