### ISSUE TITLE
[FEATURE] Add version deprecated information to PTB raised warnings

### ISSUE THREAD

**Issue by harshil21** [python-telegram-bot/python-telegram-bot#4261]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

We can slightly increase the information provided in warnings by adding which version the feature was deprecated in.

### Describe the solution you'd like

[Python's `warn()` ](https://docs.python.org/3.13/library/warnings.html#warnings.warn)accepts instances of `UserWarning`, so we can customize the message without repeating the phrase "Deprecated in NEXT.VERSION" everywhere.

Steps:

1. Add an argument `version` and `message` to `PTBDeprecationWarning`.
2. Override `__str__` to add the phrase `"Depreacted in {self.version}: {self.message}"`

Our call will now look like: 
```python
PTBDeprecationWarning("NEXT.VERSION", "msg")
```
### Describe alternatives you've considered

Simply add the version information in the warning message, but then we'll have to keep repeating ourselves.

### Additional context

We can also do the same for `PTBUserWarning` and `PTBRuntimeWarning`.

**Comment by Poolitzer** [comment]
@harshil21 We would need several version classes, no? We can deprecate in different (minor) versions before they vanish

**Comment by harshil21** [comment]
> We would need several version classes, no?

edited comment to better reflect what I meant
