### ISSUE TITLE
InlineKeyboardButtons keep the loading circle turning on Android...

### ISSUE THREAD

**Issue by hmdz105** [python-telegram-bot/python-telegram-bot#428]
### Steps to reproduce
1.
Generate an InlineKeyboardButton and send it as an InlineKeyboardMarkup in editMessage()
2.
The user clicks on this key on his Android phone, causing a callback handler to be called on the bot's side.
3.
Eventually the bot generates a new page including new inlineLeyboardButtons (**with exactly the same text but a different callback query data**) and send it to the user in the next editMessage(). However, the new inlineKeyboardMarkup button still keeps that loading turning circles! 

### Expected behaviour
The loading circle should disappear after a new inlineKeyboardButton is sent to the user via editMessage() 
### Actual behaviour
The new inlineKeyboardButtons (with text similar to previous ones) keep their turning loading circle. This happens only on Android Telegram clients and not on iOS/Windows clients.

### Configuration
Android 4.4

**Version of Python, python-telegram-bot & dependencies:**
python 2.7

``$ python -m telegram``
python-telegram-bot 5.1.0
urllib3 1.18
certifi 2016.09.26
future 0.15.2
Python 2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)]

**Comment by bomjacob** [comment]
This seems to be a bug with Android clients. It only happens if the buttons have the same `data` attribute. To get around it you can send a `answer_callback_query()`, which should remove the loading circle.

**Comment by hmdz105** [comment]
Thanks! The Issue is now resolved on Android clients.
