### ISSUE TITLE
[FEATURE] Add `edit_photo` in `telegram._message.Message` 

### ISSUE THREAD

**Issue by uniquetrij** [python-telegram-bot/python-telegram-bot#4293]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

An `edit_photo` shortcut would be convenient instead of having to use `edit_media(media=InputMediaPhoto(...))` every time.

### Describe the solution you'd like

```python
update.effective_message.edit_photo(
  photo=...,
  ...
)
```

### Describe alternatives you've considered

```python
update.effective_message.edit_media(
  media=InputMediaPhoto(
    photo=...,
    ...
  )
)
```

### Additional context

Let me know if there is an alternate / better way to achieve this.

**Comment by Poolitzer** [comment]
But that would mean one shortcut for all five types, thats a lot tbh. And same for CallbackQuery... Kind of a lot just to not write a class name in my opinion

**Comment by Bibo-Joshi** [comment]
I vote -1 on this for the same reason as pool: too little benefit for too much code.
