### ISSUE TITLE
Strange delay on iOS (iPhone/iPad) clients displaying new messages after a call to editMessage()

### ISSUE THREAD

**Issue by hmdz105** [python-telegram-bot/python-telegram-bot#430]
### Steps to reproduce
1.
Create a callback function to handle inlineKeyboardButton's callbacks. This function will edit a message 
2.
Create a Message Handler (A) with Filters.command to handle all links in form of /* from Telegram clients. This function will send new messages to users via Bot.sendMessage() 
3.
After a call to the callback handler, edit a message (using editMessage() ). The modified message contains /* commands.
4. 
Click on one of commands. The message handler (A) handles the incoming command, and sends a new message to the user ( using Bot.sendMessage() )
5.
The new message appears (almost) immediately on Windows/Android Telegram clients. However, on iOS clients there is almost 3-4 seconds delay for the new message to appear on the client side. (This was tested on the same Telegram account using both Windows/iOS clients simultaneously.)
6.
Calling the same command again (the /* command) will work normally on all clients (The created message appears immediately on all clients). However, clicking on an inlineKeyboardButton and causing an editMessage() will cause the same bug for the next command on iOS devices.

### Expected behaviour
Like Windows/Android clients, the new message should appear (almost) immediately after being sent by the bot.

### Actual behaviour
There is a longer than normal (3-4) seconds delay for iOS clients to show the new message (created via Bot.sendMessage() ) 

Windows/Android clients, however, show the new message immediately!

### Configuration
**Operating System:**
iOS 9.5/8.2 
Telegram 3.12

**Version of Python, python-telegram-bot & dependencies:**
Python 2.7 

``$ python -m telegram``
python-telegram-bot 5.1.0
urllib3 1.18
certifi 2016.09.26
future 0.15.2
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]

**Comment by jh0ker** [comment]
This is not our responsibility, but rather a bug in the iOS client. Try contacting Bot Support on Telegram about it.
