### ISSUE TITLE
[DOCS] switch_inline_query_current_chat documentation discrepancy

### ISSUE THREAD

**Issue by robelasefa** [python-telegram-bot/python-telegram-bot#4301]
### Steps to Reproduce

N/A (This is a documentation issue, not a code issue)

### Expected behaviour

The library documentation should accurately reflect the behavior described in the official Telegram Bot API documentation. The switch_inline_query_current_chat parameter should be documented as inserting the bot's username and inline query into the current chat's input field

### Actual behaviour

The documentation for InlineKeyboardButton.switch_inline_query_current_chat currently describes behavior that differs from the official Telegram Bot API documentation. 

The library documentation currently states that the parameter prompts the user to select a chat of a specific type and then inserts the bot's username and inline query.

### Operating System

Windows

### Version of Python, python-telegram-bot & dependencies

```shell
Not applicable, this is a documentation issue.
```

**Comment by Bibo-Joshi** [comment]
Hey, thanks for reaching out. Would you like to send a PR to improve the docs?

**Comment by robelasefa** [comment]
Hi there! Thanks for the offer! I'm really happy to help improve the documentation, but unfortunately I'm currently away from my computer and unable to send a pull request at the moment. 

I've already drafted the changes I'd like to make, but since I'm not able to commit them right now, I think it would be best if either you or another someone could make the updates directly and send a PR.

**Comment by Bibo-Joshi** [comment]
Will be closed by #4303
