### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Aditya99111** [python-telegram-bot/python-telegram-bot#4308]
### Issue I am facing

when i go to set the message on interval it throws this error

### Traceback to the issue

```python
File "/Users/home/Desktop/Aditya/projects/mine/telegram/bot.py", line 29, in start
    context.job_queue.run_repeating(send_recurring_message, interval=20, first=0, context=chat_id, name=str(chat_id),conversation_timeout=10)
AttributeError: 'NoneType' object has no attribute 'run_repeating'
```

### Related part of your code

```python
context.job_queue.run_repeating(send_recurring_message, interval=20, first=0, context=chat_id, name=str(chat_id),conversation_timeout=10)
```

### Operating System

macos

### Version of Python, python-telegram-bot & dependencies

```shell
all latest
```

**Comment by Bibo-Joshi** [comment]
Hi. Please carefully read the highlighted boxes in the docs of [`JobQueue`](https://docs.python-telegram-bot.org/en/v21.3/telegram.ext.jobqueue.html) ;)
