### ISSUE TITLE
Filtering and discarding messages in a RegexHandler

### ISSUE THREAD

**Issue by FutureSharks** [python-telegram-bot/python-telegram-bot#432]
Hi,
I would like to only allow a few specific people to send commands to my bot. I was going to just filter messages and commands based on the chat_id. Is there a way I can have a RegexHandler filter out some commands or messages based on chat_id and discard them?

Something like this:
```
def filter_chat_id(bot, update):
        if update.message.chat_id not in allowed_chat_ids:
        # Stop here and skip all other handlers

updater = Updater(token)
dp = updater.dispatcher
dp.add_handler(RegexHandler('.*', filter_chat_id), group=1)
dp.add_handler(CommandHandler("help", help))
dp.add_handler(CommandHandler("status", status))
```

Or is there a better way to achieve this? I know I could just add a conditional inside every single handler that compares the chat_id but I think this is a bit messy and hoping there is a cleaner way.

Thanks!

**Comment by jh0ker** [comment]
Hey. It won't work exactly like that, but you're on the right track ;)

Handlers have a `check_update` method and a `handle_update` method. What you need is a handler that returns `True` from `check_update` for those messages you want to filter out, and `False` for those messages you want to be checked by other handlers.

I haven't tried this, but maybe you can use a `MessageHandler` and some custom filter function:

```python
def filter_chat_id(message):
    return message.chat_id not in allowed_chat_ids

dp.add_handler(MessageHandler([filter_chat_id], lambda bot, update: pass))
```

**Comment by FutureSharks** [comment]
I couldn't quite work it out so I did it the hacky way but no worries, thanks for the quick response jh0ker!
