### ISSUE TITLE
ContextTypes.DEFUALT_TYPE is missing [BUG]

### ISSUE THREAD

**Issue by 0xAhmed-wq** [python-telegram-bot/python-telegram-bot#4327]
### Steps to Reproduce

Use ContextTypes.DEFAULT_TYPE

### Expected behaviour

Run without error

### Actual behaviour

AttributeError: type object 'ContextTypes' has no attribute 'DEFAULT_TYPE'

### Operating System

Debian

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.15
Bot API 6.3
certifi2022.09.24
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
```

**Comment by Bibo-Joshi** [comment]
Hi. Please note that `ContextTypes.DEFAULT_TYPE` exists only in ptb version >=20.0. Please also not ethat we no longer support v13.x or older. I recommend switching to the newers versions - have a look at our [transition guide](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-20.0) :)
