### ISSUE TITLE
[FEATURE] New `TO.de_json_subclasses` method for parent classes

### ISSUE THREAD

**Issue by harshil21** [python-telegram-bot/python-telegram-bot#4346]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

We can save some code duplication by extracting the `de_json` logic of classes like `PaidMedia` or `ChatMember`. Ideally this should go into `TelegramObject` so we can easily call it.

### Describe the solution you'd like

https://github.com/python-telegram-bot/python-telegram-bot/pull/4334#discussion_r1665902751

### Describe alternatives you've considered

keep doing what we do right now

**Comment by Bibo-Joshi** [comment]
closing as won't do as discussed in #4358
