### ISSUE TITLE
[Discussion] What is an attachment

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/python-telegram-bot#4350]
We have the following string describing our attachment shortcut:
_If this message is neither a plain text message nor a status update_

and the following message attributes are set to it:

        * :class:`telegram.Audio`
        * :class:`telegram.Dice`
        * :class:`telegram.Contact`
        * :class:`telegram.Document`
        * :class:`telegram.Animation`
        * :class:`telegram.Game`
        * :class:`telegram.Invoice`
        * :class:`telegram.Location`
        * :class:`telegram.PassportData`
        * List[:class:`telegram.PhotoSize`]
        * :class:`telegram.Poll`
        * :class:`telegram.Sticker`
        * :class:`telegram.Story`
        * :class:`telegram.SuccessfulPayment`
        * :class:`telegram.Venue`
        * :class:`telegram.Video`
        * :class:`telegram.VideoNote`
        * :class:`telegram.Voice`

Now status update is not really defined in Telegram context. From my feeling for how I would use this method, I would describe it as "user generated message which is not a plain text message". This would however mean to remove SuccessfulPayment from this list.

On the other hand, if we stick to a definition which includes SuccessfulPayment, imo all service messages which link to an object should be included.

**Comment by harshil21** [comment]
I agree, `SuccessfulPayment` does not belong there.

**Comment by Bibo-Joshi** [comment]
the "user generated" in pools description makes sense to me. I guess narrowing down to "downloadable" (i.e. everything with a `file_id`) would be too harsh as e.g. locations & venues don't have that?

**Comment by Poolitzer** [comment]
Yes no download there and for me they fit/should stay there

**Comment by Bibo-Joshi** [comment]
All right, sounds like a consensus. Pool, will you PR for the deprecation? Maybe also add the woring "user generated" or even "actively sent by the user" to the docstring?
