### ISSUE TITLE
[BUG]Send audio in inline mode prompts Audio_content_type_invalid

### ISSUE THREAD

**Issue by Rovniced** [python-telegram-bot/python-telegram-bot#4352]
### Steps to Reproduce

`await bot.send_audio(chat_id=chat_id, audio=f,filename="music.flac")`

After using send_audio to get the fileid, if the suffix of the filename is flac (mp3 test is normal, other formats are not tested), sending it in inline mode will report an error telegram.error.BadRequest: Audio_content_type_invalid.

```
results = [InlineQueryResultCachedAudio(
    id=str(uuid4()),
    audio_file_id=music_data.file_id,
    caption=caption,
    reply_markup=keyboard,
    parse_mode="MarkdownV2"
)]
```

Confirm it is a format extension problem, set the filename to music.flac and the problem occurs (the audio file is in flac format), set it to music.mp3 and it sends fine (the audio file is in flac format).

Tried to observe the body of the request, where the Content-Type is audio/x-flac, another library sends the Content-Type as application/octet-stream, inline mode sends no error, maybe it's the Content-Type that's causing the problem?

### Expected behaviour

Sending audio messages in inline mode using fileid

### Actual behaviour

telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\Code\music_bot\.venv\lib\site-packages\telegram\ext\_application.py", line 1325, in process_update
    await coroutine
  File "C:\Users\Administrator\Documents\Code\music_bot\.venv\lib\site-packages\telegram\ext\_handlers\basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
  File "C:\Users\Administrator\Documents\Code\music_bot\src\bot\__init__.py", line 17, in wrapper
    return await func(update, context, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Code\music_bot\src\bot\inline.py", line 118, in inline_query
    await update.inline_query.answer(results)
  File "C:\Users\Administrator\Documents\Code\music_bot\.venv\lib\site-packages\telegram\_inline\inlinequery.py", line 186, in answer
    return await self.get_bot().answer_inline_query(
  File "C:\Users\Administrator\Documents\Code\music_bot\.venv\lib\site-packages\telegram\ext\_extbot.py", line 963, in answer_inline_query
    return await super().answer_inline_query(
  File "C:\Users\Administrator\Documents\Code\music_bot\.venv\lib\site-packages\telegram\_bot.py", line 3564, in answer_inline_query
    return await self._post(
  File "C:\Users\Administrator\Documents\Code\music_bot\.venv\lib\site-packages\telegram\_bot.py", line 618, in _post
    return await self._do_post(
  File "C:\Users\Administrator\Documents\Code\music_bot\.venv\lib\site-packages\telegram\ext\_extbot.py", line 353, in _do_post
    return await super()._do_post(
  File "C:\Users\Administrator\Documents\Code\music_bot\.venv\lib\site-packages\telegram\_bot.py", line 647, in _do_post
    result = await request.post(
  File "C:\Users\Administrator\Documents\Code\music_bot\.venv\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\Administrator\Documents\Code\music_bot\.venv\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Audio_content_type_invalid

### Operating System

Windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 21.3
Bot API 7.4
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
```

**Comment by Poolitzer** [comment]
Hi, this is not a bug of this library, rather of the bot API.

However the send_audio docs clearly state that the "audio must be in the .MP3 or .M4A format". If you send a flac file instead, you should not be surprised it doesn't work :)

Since sending a flac does indeed result in a proper audio file you could raise an issue about this in https://github.com/tdlib/telegram-bot-api. Either flac shouldn't result in audios and rather documents or inputcachedaudio should accept it, at least imo.

**Comment by Rovniced** [comment]
But trying to manually send a flac file to get the fileid and then replying inline works fine, including using the https://github.com/go-telegram-bot-api/telegram-bot-api library to send and reply.

**Comment by Poolitzer** [comment]
@Rovniced What do you mean with &quot;replying inline&quot; and &quot;getting manually&quot;.

**Comment by Rovniced** [comment]
I manually create an http request to tg api to send a file

```
curl --location --request POST 'http://IP:8081/botTOKEN/sendAudio' \
--header 'User-Agent: python-telegram-bot v21.3 (https://python-telegram-bot.org)' \
--header 'Accept: */*' \\
--header 'Host: IP:8081' \\
--header 'Connection: keep-alive' \\
--form 'chat_id=""' \\
--form 'performer="name"' \\
--form 'title="title"' \\
--form 'audio=@"30612793.flac"'
```

After that get the fileid and add it to my own program's database, then test it in inline

```
        results = [InlineQueryResultCachedAudio(
            id=str(uuid4()),
            audio_file_id=music_data.file_id,
            caption=caption,
            reply_markup=keyboard,
            parse_mode="MarkdownV2"
        )]
        await update.inline_query.answer(results)
```

is working properly.

**Comment by Poolitzer** [comment]
@Rovniced What is the response from the curl request? Especially the mime_type

**Comment by Rovniced** [comment]
(Removed bot name and group info.)
{
	"ok": true,
	"result": {
		"message_id": 1075,
		"from": {
			"id": ,
			"is_bot": true,
			"first_name": "Test_bot",
			"username": ""
		},
		"chat": {
			"id": 0,
			"title": "",
			"type": "group",
			"all_members_are_administrators": true
		},
		"date": 1720261107,
		"audio": {
			"duration": 0,
			"file_name": "file",
			"mime_type": "audio/mpeg",
			"title": "G.E.M",
			"performer": "G.E.M",
			"file_id": "CQACAgUAAxkDAAIEM2aJGfMPbW2Pnvub4erF089DJeSLAAJtEAAC2LdIVM-2X77XJi9cNQQ",
			"file_unique_id": "AgADbRAAAti3SFQ",
			"file_size": 22730095
		}
	}
}

**Comment by Poolitzer** [comment]
yes PTB generated audio/x-flac as mime_type on my end. According to https://stackoverflow.com/a/78086048 it should be audio/flac now, but from my understanding the discussion is not final https://datatracker.ietf.org/doc/draft-ietf-cellar-flac/14/

But in the end it is definitely not audio/mpeg, which curl for some reason claims there (or you maybe need to submit it in somewhere in the request im not that deep into uploading files). So since telegram comes for whatever reason to the conclusion your manually uploaded file is a mpeg one it gives it that mime type, and then you can use it in your inline result.

But PTB correctly communicates the file type to telegram so it correctly reports audio/x-flac. And then you get the error, which you need to report to the bot API as I laid out before.

**Comment by Rovniced** [comment]
Okay, thanks for the answer.
