### ISSUE TITLE
Can we transfer data from the bot to the WebApp? 

### ISSUE THREAD

**Issue by gokhanaltun** [python-telegram-bot/python-telegram-bot#4354]
We can transfer data from the WebApp to the bot. Can we transfer data from the bot to the WebApp? Either when the WebApp is launched or in any other way?

python telegram bot version 21.3

**Comment by Poolitzer** [comment]
@gokhanaltun Depends on how it is launched, e.g. check our example for with a reply keyboard: <a href="https://docs.python-telegram-bot.org/examples.html#examples-webappbot">webappbot.py</a>

**Comment by gokhanaltun** [comment]
> @gokhanaltun Depends on how it is launched, e.g. check our example for with a reply keyboard: [webappbot.py](https://docs.python-telegram-bot.org/examples.html#examples-webappbot)

I understand how to send data from the WebApp to the bot. What I'm curious about is whether I can send data from the bot to the WebApp, and if so, how can I do it?

**Comment by Poolitzer** [comment]
@gokhanaltun The easiest way is to use url query strings :)

**Comment by gokhanaltun** [comment]
> @gokhanaltun The easiest way is to use url query strings :)

I think this is the only solution for now, thank you :)
