### ISSUE TITLE
[QUESTION] Possible to see User id of people who used my invitation links ?

### ISSUE THREAD

**Issue by xerno0om** [python-telegram-bot/python-telegram-bot#4379]
### Issue I am facing

I created an invitation link on my Telegram channel, and I wanted to know if it is possible to make a script that tells me the user IDs of the people who used my invitation links to join my channel

### Operating System

Windows 11

### Version of Python, python-telegram-bot & dependencies

```shell
Last Python
```

**Comment by Bibo-Joshi** [comment]
@xerno0om Hi. I guess it should be possible to that that via <a href="https://docs.python-telegram-bot.org/telegram.chatmemberupdated.html#telegram.ChatMemberUpdated.invite_link">telegram.ChatMemberUpdated.invite_link</a> <a href="https://core.telegram.org/bots/api#chatmemberupdated">ᵀᴱᴸᴱᴳᴿᴬᴹ</a>. Please also have a look at <a href="https://docs.python-telegram-bot.org/telegram.ext.chatmemberhandler.html#telegram.ext.ChatMemberHandler">telegram.ext.ChatMemberHandler</a> and <a href="https://docs.python-telegram-bot.org/examples.html#examples-chatmemberbot">chatmemberbot.py</a>
