### ISSUE TITLE
Message.reply_x methods are not present in pythonhosted docs

### ISSUE THREAD

**Issue by bluehood** [python-telegram-bot/python-telegram-bot#438]
As per title, there is no mention of `reply_text` and the other similar methods of the `Message` class in the official documentation. It is particularly confusing since the methods are now used in the examples.

**Comment by jh0ker** [comment]
@bluehood Correct, we have some kind of build problems. Please use python-telegram-bot.readthedocs.io instead for now

**Comment by bluehood** [comment]
@jh0ker all right, thanks! I have no idea how serious the build problems are. If they will take a while to fix, it might be useful to change the README to also point at the up-to-date docs.
