### ISSUE TITLE
[BUG] Send video with file_id gives an error

### ISSUE THREAD

**Issue by KMoszczyc** [python-telegram-bot/python-telegram-bot#4381]
### Steps to Reproduce

1.  Get file_id from the message.video.id using telethon
```
 async with self.client:
                async for msg in self.client.iter_messages(CHAT_ID, offset_date=offset_timestamp, reverse=True):
                       if core_utils.is_video(msg):
                               print(msg.video.id)
           with self.client:
                      chat_history = self.client.loop.run_until_complete(helper())
                      return chat_history
 ```
2. Send video via bot command:
```
file_id='some_id' # msg.video.id
    async def videos_by_reactions(self, update: Update, context: ContextTypes.DEFAULT_TYPE):
        await context.bot.send_video(chat_id=update.effective_chat.id, caption='ee', video=file_id)
```
3. Use the command
4. Get error in the logs

### Expected behaviour

Video gets send from the telegram servers using the file_id

### Actual behaviour

```
2024-07-15 17:11:01,810 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "F:\Anaconda\envs\python-3.12\Lib\site-packages\telegram\ext\_application.py", line 1277, in process_update
    await coroutine
  File "F:\Anaconda\envs\python-3.12\Lib\site-packages\telegram\ext\_handlers\basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\TelegramBot\src\stats\chat_commands.py", line 164, in videos_by_reactions
    await context.bot.send_video(chat_id=update.effective_chat.id, caption='ee', video='8353835788705158591')
  File "F:\Anaconda\envs\python-3.12\Lib\site-packages\telegram\ext\_extbot.py", line 3100, in send_video
    return await super().send_video(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\python-3.12\Lib\site-packages\telegram\_bot.py", line 1949, in send_video
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\python-3.12\Lib\site-packages\telegram\ext\_extbot.py", line 587, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\python-3.12\Lib\site-packages\telegram\_bot.py", line 731, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\python-3.12\Lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\python-3.12\Lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\python-3.12\Lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\python-3.12\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\python-3.12\Lib\site-packages\telegram\request\_baserequest.py", line 379, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Wrong remote file identifier specified: wrong padding in the string
```

### Operating System

W11

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.12
python-telegram-bot 21.1.1
```

### Additional Context

I guess that this is simply a wrong file_id, but I'm not sure where I can get the correct one.
Thanks for any help!

**Comment by Poolitzer** [comment]
Hi, the file id is account specific, you can't use one from a user account in a bot account. You can't even use one from a different bot.

**Comment by KMoszczyc** [comment]
Okay! Well that makes sense. So as I see it in your docs, that I can only get the file_ids of videos send only by the bot in that case? No way of getting the file_ids of videos sent my users, other than with incompatible client api.

![image](https://github.com/user-attachments/assets/f2557fb0-b55e-4c71-a089-18a841349963)

I just wanted a shortcut to not download videos if I didnt have to but I guess there is no other way. Right?

**Comment by Bibo-Joshi** [comment]
@KMoszczyc You can read the file ID from messages sent by the user, sure. See <a href="https://docs.python-telegram-bot.org/telegram.update.html#telegram.Update.message">telegram.Update.message</a> <a href="https://core.telegram.org/bots/api#update">ᵀᴱᴸᴱᴳᴿᴬᴹ</a>, <a href="https://docs.python-telegram-bot.org/telegram.message.html#telegram.Message.video">telegram.Message.video</a> <a href="https://core.telegram.org/bots/api#message">ᵀᴱᴸᴱᴳᴿᴬᴹ</a>, <a href="https://docs.python-telegram-bot.org/telegram.video.html#telegram.Video.file_id">telegram.Video.file_id</a> <a href="https://core.telegram.org/bots/api#video">ᵀᴱᴸᴱᴳᴿᴬᴹ</a>, <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Working-with-Files-and-Media">Working with Files and Media</a>

**Comment by KMoszczyc** [comment]
Okay.. but it works only on the new messages and new videos, there is no way of getting the old ones, right?

**Comment by Bibo-Joshi** [comment]
@KMoszczyc That&#x27;s correct. Best you can do is forward them to your bot again

**Comment by KMoszczyc** [comment]
Like... send the stored past messages with the bot to the chat and get the file_ids? Id probably like to delete those after the upload... with 300k messages and a few k of vids xd

**Comment by Bibo-Joshi** [comment]
I can't quite follow... The points are:

* Bots can not request information on past messages. They can access them only as they come in. Storing some data about the message is ofc an option 
* A bot can use a file_id only if the file_id was retrieved from an update that the bot itself received. If you have a video that you'd like to know the bots file_id for, you'll have to send that video to the bot and extract the file_id
* Afaik file_ids remain valid even after the message contain the document/video/photo has been deleted. Not sure if TG guarantees that, though
