### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by alex123321-wq** [python-telegram-bot/python-telegram-bot#4428]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

Access to full user info in `User` class

### Describe the solution you'd like

There are existing properties, such as `is_premium`, `full_name`, `can_join_groups`, bla. They all come from API call called `user` - https://core.telegram.org/constructor/user
Why not have access to all fields that request provides? For example - I need `status` and `emoji_status`, it's not implemented but is avaliable in API. Instead of implementing every single property there could be raw access to all `User` fields.

### Describe alternatives you've considered

[Telethon library](https://docs.telethon.dev/en/stable/examples/users.html) has `GetFullUserRequest` method, it returns tons of info about the user and I can choose what I need.

**Comment by Poolitzer** [comment]
@alex123321-wq Hi, we implement the bot API (https://telegram.org/bots/api), not the MTProto API.
