### ISSUE TITLE
[FEATURE] API 7.10

### ISSUE THREAD

**Issue by aelkheir** [python-telegram-bot/python-telegram-bot#4459]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

API 7.10

> [!IMPORTANT] 
> - Comment here or in the dev group what you want to work on so we can assign you
> - Please copy the relevant part of the checklist from #4459 to your PR and make sure to cover everything :)
> - If this is your first contribution, please be sure to read the [contribution guide](https://docs.python-telegram-bot.org/en/v20.7/contributing.html) and feel free to reach out with any questions via https://t.me/pythontelegrambotchannel/105

### Describe the solution you'd like

- [x] Added updates about purchased paid media, represented by the class [PaidMediaPurchased](https://core.telegram.org/bots/api#paidmediapurchased) and the field purchased_paid_media in the class [Update](https://core.telegram.org/bots/api#update). (Taken by @harshil21)
- [ ] Added the ability to specify a payload in [sendPaidMedia](https://core.telegram.org/bots/api#sendpaidmedia) that is received back by the bot in [TransactionPartnerUser](https://core.telegram.org/bots/api#transactionpartneruser) and purchased_paid_media updates. (Taken by @aelkheir)
- [ ] Added the field prize_star_count to the classes [GiveawayCreated](https://core.telegram.org/bots/api#giveawaycreated), [Giveaway](https://core.telegram.org/bots/api#giveaway), [GiveawayWinners](https://core.telegram.org/bots/api#giveawaywinners) and [ChatBoostSourceGiveaway](https://core.telegram.org/bots/api#chatboostsourcegiveaway).  (Taken by @aelkheir)
- [ ] Added the field is_star_giveaway to the class [GiveawayCompleted](https://core.telegram.org/bots/api#giveawaycompleted).  (Taken by @aelkheir)

### Describe alternatives you've considered

If you want to contribute, you can start from the [Contribution Guide](https://docs.python-telegram-bot.org/en/v20.7/contributing.html).

### Additional context

Please comment below before start working on any part of the update so as to keep things in track and avoid double work.

**Comment by harshil21** [comment]
Taking point 1.
