### ISSUE TITLE
Couldn't download pdf readbook

### ISSUE THREAD

**Issue by mengyyy** [python-telegram-bot/python-telegram-bot#447]
I want to download pdf book,but in this [http://readthedocs.org](http://readthedocs.org/projects/python-telegram-bot/downloads/) I found the pdf has just 7 pages.Is this something wrong?

**Comment by jh0ker** [comment]
Yeah, that is not right. I just digged into the sphinx sources and fixed the latexpdf build here. I'll attach the PDF I compiled so you can use it right away. It might not be perfect, but it looks okay to me.
[PythonTelegramBot.pdf](https://github.com/python-telegram-bot/python-telegram-bot/files/563382/PythonTelegramBot.pdf)

**Comment by jh0ker** [comment]
I built a new PDF with some improvements
[PythonTelegramBot.pdf](https://github.com/python-telegram-bot/python-telegram-bot/files/563430/PythonTelegramBot.pdf)

**Comment by jh0ker** [comment]
https://media.readthedocs.org/pdf/python-telegram-bot/latest/python-telegram-bot.pdf has been updated as well.
I'll close this issue now. Thank you for getting me off my lazy ass and finally fix the sphinx mess.
