### ISSUE TITLE
[PROBLEM & IMPROVEMENT] Persistent data update

### ISSUE THREAD

**Issue by HK-Mattew** [python-telegram-bot/python-telegram-bot#4472]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

**Hello,**

I had a problem when running a bot with persistent data using BasePersistence(..., update_interval=0). My intention when using update_interval=0 is that the persistent data is updated as quickly as possible after processing a handler (callback).

However, the problem I faced was that by setting update_interval=0 the loop: https://github.com/python-telegram-bot/python-telegram-bot/blob/0b352b043e9270b799d96df566da30fe76265e76/telegram/ext/_application.py#L1638 It keeps working all the time (even without having data to update, this seems inefficient).

Since the loop kept working all the time without delay, in my case the CPU consumption of the bot process exceeded 100%. (Just with the bot started, without using any command).

Making it clear that, normal use of my bot without using update_interval=0, consumption is something like 0.3% of CPU.

### Describe the solution you'd like

One solution I thought of would be to refactor how persistent data is updated. I don't know if this is the best option or not, this is just an idea.

My idea is to implement a logic to update persistent data after a handler callback. At: https://github.com/python-telegram-bot/python-telegram-bot/blob/0b352b043e9270b799d96df566da30fe76265e76/telegram/ext/_handlers/basehandler.py#L157

If persistence.update_interval is equal to 0, update the data. If not, add a logic to update it later.

In my opinion, this would work better and would also avoid the loop: https://github.com/python-telegram-bot/python-telegram-bot/blob/0b352b043e9270b799d96df566da30fe76265e76/telegram/ext/_application.py#L1638 working unnecessarily.

**Comment by Bibo-Joshi** [comment]
Hi. Can you explain what exactly your use case is for having the persistence updated right after each update? Please also consider that each handler might schedule asyncio tasks that alter data long after the callback has already exited. Finally, please also have look at the discussion in #3554

**Comment by HK-Mattew** [comment]
> Can you explain what exactly your use case is for having the persistence updated right after each update?

Synchronize context.user_data data between multiple processes for the same bot. In this case, a bot running in webhook mode.

But I've just come to the conclusion that ptb's data persistence is not designed for my use case. ptb's data persistence is designed to work with a single-process bot. (And it works fine in that case.)

Because of this, I'm currently considering moving away from using context.user_data and the ConversationHandler.

**Comment by Bibo-Joshi** [comment]
Mh, that does sound like use cas 2 ii) of #3554, which we decided not to support.
While we do try to cover as many scenarios as possible with PTBs standard tools, some are out of scope - at least for now.
Sorry that you can't find a fitting solution for your setup.
