### ISSUE TITLE
[QUESTION] Send Paid Media for photo error: Can't parse inputpaidmedia: media not found

### ISSUE THREAD

**Issue by ethanlolomg** [python-telegram-bot/python-telegram-bot#4480]
### Issue I am facing

Hi,

Currently, I am trying to implement paid media content in my telegram bot but I run into an error that says: `telegram.error.BadRequest: Can't parse inputpaidmedia: media not found` I have followed the documentation in this [doc](https://docs.python-telegram-bot.org/en/stable/telegram.inputpaidmedia.html#telegram.InputPaidMedia) for structuring input paid media object

Here is a snippet of my implementation:

```
with open(image_path, "rb") as image_file:
        image = InputFile(image_file)

        await context.bot.send_paid_media(
            chat_id=chat.id,
            star_count=star_price,
            media=[InputPaidMedia(media=image, type=InputPaidMediaType.PHOTO)]
        )
```

Would love to get some suggestion for how I can resolve this issue with send paid media.

### Operating System

mac os

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot==21.5
```

**Comment by Bibo-Joshi** [comment]
Hi. What's missing here is that you need to pass `attach=True` to `InputFile`. That way I it works fine for me in this mwe:

<details>

```python
import asyncio
import logging

from telegram import Bot, InputFile, InputPaidMedia, InputPaidMediaPhoto
from telegram.constants import InputPaidMediaType

# Enable logging
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.DEBUG
)

async def main():
    async with Bot("TOKEN") as bot:
        await send_message(bot)


async def send_message(bot: Bot):
    with open("tests/data/telegram.jpg", "rb") as image_file:
        image = InputFile(image_file, attach=True)

        await bot.send_paid_media(
            chat_id=123456,
            star_count=42,
            # media=[InputPaidMediaPhoto(media=image_file)],
            media=[InputPaidMedia(media=image, type=InputPaidMediaType.PHOTO)],
        )


if __name__ == "__main__":
    asyncio.run(main())

```

</details>

However, recommend to simply pass `image_file` as `media` argument - that way, PTB takes care of converting to an `InputFile` object for you. Moreover, you can directly use the `InputPaidMediaPhoto` class instead of specifying the `type`.
