### ISSUE TITLE
[QUESTION] BOT reply itself

### ISSUE THREAD

**Issue by gmenezes-sistemas** [python-telegram-bot/python-telegram-bot#4490]
Is there any way to make the bot able to respond to itself from other integrations, from telegram endpoint? https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage?

**Comment by Bibo-Joshi** [comment]
@gmenezes-sistemas Hey. In order for someone to be able to help you, you must ask a <b>good technical question</b>. Please read <a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Ask-Right">this short article</a> and try again ;)
