### ISSUE TITLE
[QUESTION] How to handle message unpinning?

### ISSUE THREAD

**Issue by Vilin97** [python-telegram-bot/python-telegram-bot#4497]
### Issue I am facing

Hi.
It looks like message unpinning is not exposed in the API at all, is this correct? My bot remembers pinned messages, but I want it to forget the pinned message when it gets unpinned. I found no way of doing it, since message unpinning does not send any status update (unlike message pinning).

### Operating System

Windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 21.5
Bot API 7.9
Python 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)]
```

**Comment by Poolitzer** [comment]
That's correct

**Comment by Vilin97** [comment]
Is there any workaround?

**Comment by Poolitzer** [comment]
None that I know of
