### ISSUE TITLE
contacts.importContacts

### ISSUE THREAD

**Issue by johnjosh1927** [python-telegram-bot/python-telegram-bot#450]
hello, this is not a bug or something, I just could not figure out how to use this api function 
https://core.telegram.org/method/contacts.importContacts

Is there a way to do it? 

I really looked for it and searched both in your website and here in the github repo.

Thanks!

**Comment by jh0ker** [comment]
Hey,
That is a function of the Telegram API, which is **not** the same as the Telegram **Bot** API. This library only connects to the Bot API. 
If you want to use the regular Telegram API, you can use telegram-cli, which acts like a regular user account.
