### ISSUE TITLE
[QUESTION]  ~~ strikethrough ~~  problem using python script

### ISSUE THREAD

**Issue by JoyCatDev** [python-telegram-bot/python-telegram-bot#4516]
### Steps to Reproduce

hello guys, how do you make this work using  python script for bot

     ⬇️⬇️⬇️⬇️⬇️
~~strikethrough~~

I need some assistance with an issue I'm facing. In the chat, everything works normally, and the strikethrough formatting functions as expected when I edit the message directly. However, when I send the message using my Python script, the strikethrough formatting doesn't work.

Could you please help me figure out why this might be happening? Thank you!

i think  The Bot API  dont support that type of  formatting for messages. ⁉️

as it showing like this in final result  ~~ strikethrough ~~

### Expected behaviour

it should be showing like this   :   ~~strikethrough~~

### Actual behaviour

it show  ~~ strikethrough ~~

### Operating System

Python

### Version of Python, python-telegram-bot & dependencies

latest version for both

**Comment by Poolitzer** [comment]
@JoyCatDev Wiki of <i>python-telegram-bot</i> - Category <i>Code Snippets</i>
<a href="https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#message-formatting-bold-italic-code-">Message Formatting (bold, italic, code, ...)</a>

**Comment by LaxmanChoudhary** [comment]
@JoyCatDev did you tried this **parse_mode** ??

> [@JoyCatDev](https://github.com/JoyCatDev) Wiki of python-telegram-bot - Category Code Snippets [Message Formatting (bold, italic, code, ...)](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#message-formatting-bold-italic-code-)
