### ISSUE TITLE
[QUESTION] Is it possible to send msg in channel by "channel sender" not by bot?

### ISSUE THREAD

**Issue by Louis24** [python-telegram-bot/python-telegram-bot#4522]
### Issue I am facing

![Image](https://github.com/user-attachments/assets/c308a8e7-bba9-499b-9ba3-770391cefadf)
![Image](https://github.com/user-attachments/assets/f46137ca-15fa-4f53-bfe0-874583663307)
The first picture is what I posted manually as a channel owner. The second picture is what I did with code, using a robot to post in the channel.

### Operating System

Win11

### Version of Python, python-telegram-bot & dependencies

python:3.12
Name: python-telegram-bot
Version: 21.4

**Comment by Poolitzer** [comment]
No bots can't do that.
