### ISSUE TITLE
[Bug] issuing CH's "unknown state" warning from a callback created w/ `functools.partial` turns into an exception

### ISSUE THREAD

**Issue by aelkheir** [python-telegram-bot/python-telegram-bot#4527]
### Steps to Reproduce

1. #### MWE
 ```python
from functools import partial

from telegram import Update
from telegram.ext import Application, CommandHandler, ConversationHandler


async def callback(update, context, a):
    return "Unknown state"


partial_callback = partial(callback, a="A")

conv = ConversationHandler(
    entry_points=[CommandHandler("start", partial_callback)],
    fallbacks=[],
    states={},
)

app = (
    Application.builder()
    .token("TOKEN")
    .build()
)
app.add_handler(conv)
app.run_polling(allowed_updates=Update.ALL_TYPES)
```
1. send "/start".
2. exception gets raised.

### Expected behaviour

Issue the warning without crashing.

### Actual behaviour

An exception gets raised.

### Operating System

Windows 11

### Version of Python, python-telegram-bot & dependencies

python-telegram-bot 21.1.1 (v1.0.0-71-g2ad055a)
Bot API 7.2
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]

An older version, but latest:main handles the warning the same.

### Relevant log output
```bash
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "venv\Lib\site-packages\telegram\ext\_application.py", line 1277, in process_update
    await coroutine
  File "venv\Lib\site-packages\telegram\ext\_handlers\conversationhandler.py", line 904, in handle_update
    self._update_state(new_state, conversation_key, handler)
  File "venv\Lib\site-packages\telegram\ext\_handlers\conversationhandler.py", line 929, in _update_state
    f"{repr(handler.callback.__name__) if handler is not None else 'BaseHandler'} "
            ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'functools.partial' object has no attribute '__name__'. Did you mean: '__ne__'?
```

### Additional Context

apparently [partial objects](https://docs.python.org/3/library/functools.html#partial-objects) don't have `__name__`.
>[partial](https://docs.python.org/3/library/functools.html#functools.partial) objects are like [function objects](https://docs.python.org/3/reference/datamodel.html#user-defined-funcs) in that they are callable, weak referenceable, and can have attributes. There are some important differences. For instance, the [__name__](https://docs.python.org/3/reference/datamodel.html#function.__name__) and [function.__doc__](https://docs.python.org/3/reference/datamodel.html#function.__doc__) attributes are not created automatically. Also, [partial](https://docs.python.org/3/library/functools.html#functools.partial) objects defined in classes behave like static methods and do not transform into bound methods during instance attribute look-up.

relevant line:
https://github.com/python-telegram-bot/python-telegram-bot/blob/06854633ab00d81fa5592adc17d92896fbda662c/telegram/ext/_handlers/conversationhandler.py#L929

probably not common enough to add specific handling for it (?), adding the missing state also avoids the issue in the first place.
feel free to close, in case no action is needed :)

**Comment by Poolitzer** [comment]
Yes I do feel its not a common issue (I can't really guess your use case out of the MWE), it hasn't come up yet. And as you figured out it's easy to just set that attribute and fix the error. And it's way better in debug to see which callback handled what.

**Comment by aelkheir** [comment]
> And it's way better in debug to see which callback handled what.

Aha, the more reason to set it manually anyway.
Thanks for the prompt response!
