### ISSUE TITLE
Get users first name and use on message.reply_text()

### ISSUE THREAD

**Issue by d3lv11n** [python-telegram-bot/python-telegram-bot#453]
Hi, first i am brazilian, so english errors will hapen.

Now the problem itself is that i am new with python and creating bots with it.

My issue is:

Im using one of the exemples that are on the archive (conversationbot.py) and doing some alterations just for learning purpose.

Than there is this code here: 

```
def gender(bot, update):
    user = update.message.from_user
    logger.info("%s eh: %s" % (user.first_name, update.message.text))
    update.message.reply_text("Something that the bot says %s "
                              "more things that it says.")
```

update.message.reply_text("Something that the bot says %s <<---- **Here i whant to put the users first name**

I thought to use something like "% user.first_name" after the end of the "", but it didnt worked for me.

I think that it is not that difficult, but i can't figure out how to do it.

**Comment by jh0ker** [comment]
Hey
I already replied to your question in the group. The example code on our website (https://python-telegram-bot.org/) does this.
