### ISSUE TITLE
[QUESTION] My code works fine, but I would like to know how can I update to stop receiving DeprecationWarning: There is no current event loop

### ISSUE THREAD

**Issue by rafaelribeiroo** [python-telegram-bot/python-telegram-bot#4533]
### Issue I am facing

Hello guys,

So, last month I started receiving this error` DeprecationWarning: There is no current event loop` when I'm running a script to monitor new listings, does anyone know how can I ignore it by updating the code?

```python
bot = Bot(config('TOKEN'))

async def send_telegram(filename, title, price, url):
    # InputMediaPhoto(open(f'./tmp/{file}', 'rb')) for file in filenames
    await bot.send_photo(
        chat_id='-1001746032698',
        photo=open(f'./tmp/{filename}.jpg', 'rb'),
        parse_mode='HTML',
        caption=f'🆕 <a href="{url}">{title.title()}</a> 🆕 \n\n💸💸💸 {price} 💸💸💸',
        write_timeout=50,
        read_timeout=45
    )

base_url = config('BASE_URL')

def setup_driver():
    chrome_options = Options()
    chrome_options.add_argument('--start-maximized')
    # chrome_options.add_argument("--headless")

    driver = webdriver.Chrome(options=chrome_options)
    # driver = webdriver.Chrome(
    #     options=chrome_options,
    #     service=Service(ChromeDriverManager().install())
    # )
    driver.minimize_window()

    return driver


def scrap_enjoei(driver, base_url):

    print(f'{color}[ ENJOEI ]{end} Scraping {hyperlink_it(base_url, f"Page {page_nro+1: <2}")}')

    driver.get(base_url)
    try:
        WebDriverWait(driver, 45).until(
            EC.presence_of_element_located((By.CLASS_NAME, 'c-product-card'))
        )
    except TimeoutException:
        driver.refresh()
        driver.save_screenshot('./tmp/file.png')

    soup = beauty(driver.page_source, "html.parser")
    return soup


def parse_enjoei(soup):

    for item in soup.select('div.c-product-feed__list__wrapper > div.c-product-card'):

        title = item.select('h2', class_='c-product-card__title o-text')[0].get_text().strip().replace("'", "''")
        price = item.select('span.c-product-card__price > span')[0].text.strip()

        base = 'https://www.enjoei.com.br'
        join = base + item.select('a[href^="/p/"]')[0]['href']
        url = search(r'(https).*\?', join)[0].replace('?', '')

        if any(item in title.lower() for item in blacklist):
            continue

        cursor.execute(
            f"SELECT title FROM ad WHERE title = '{title}' AND url = '{url}'"
        )
        data = cursor.fetchone()

        if data:
            pass
        else:
            cursor.execute(
                f"INSERT INTO ad (title, price, url) "
                f"VALUES ('{title}', '{price}', '{url}')"
            )
            connection.commit()

            loop = get_event_loop()
            loop.run_until_complete(
                send_telegram(filename, title, price, URL)
            )

driver = setup_driver()
while True:
    soup = scrap_enjoei(driver, base_url)
```

### Operating System

Linux Mint 21.3

### Version of Python, python-telegram-bot & dependencies

python 3.12.0
anyio==4.0.0
attrs==23.1.0
Automat==22.10.0
beautifulsoup4==4.12.2
bs4==0.0.1
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.2
constantly==23.10.4
cryptography==41.0.5
cssselect==1.2.0
filelock==3.13.1
h11==0.14.0
httpcore==1.0.2
httpx==0.25.1
hyperlink==21.0.0
idna==3.4
incremental==22.10.0
itemadapter==0.8.0
itemloaders==1.1.0
jmespath==1.0.1
lxml==4.9.3
outcome==1.3.0.post0
packaging==23.2
parsel==1.8.1
Protego==0.3.0
psycopg2-binary==2.9.9
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
PyDispatcher==2.0.7
pyOpenSSL==23.3.0
PySocks==1.7.1
python-decouple==3.8
python-dotenv==1.0.0
python-telegram-bot==20.6
queuelib==1.6.2
requests==2.31.0
requests-file==1.5.1
Scrapy==2.11.0
selenium==4.23.1
service-identity==23.1.0
setuptools==73.0.1
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.5
tldextract==5.1.0
trio==0.23.1
trio-websocket==0.11.1
Twisted==22.10.0
typing_extensions==4.12.2
urllib3==2.0.7
w3lib==2.1.2
webdriver-manager==4.0.1
websocket-client==1.8.0
wsproto==1.2.0
zope.interface==6.1

**Comment by Bibo-Joshi** [comment]
Hi. please show the full console output of the warning. There should be a python file and a line number mentioned.

**Comment by rafaelribeiroo** [comment]
Oh sure @Bibo-Joshi , I've extracted only "useful" lines of the code, so the line number won´t be correct, but he's warning about the line below.

![Image](https://github.com/user-attachments/assets/c2d684b2-3c4b-4481-b718-f2c8797a9bad)

loop = get_event_loop()
loop.run_until_complete(
    send_telegram(filename, title, price, URL)
)
remove(f'tmp/{filename}.jpg')

**Comment by rafaelribeiroo** [comment]
If I create a new script only to show this error occurring would help you analyze @Bibo-Joshi ?

**Comment by Bibo-Joshi** [comment]
Ah, I see. This doesn't look like an issue with PTB, though. Please have a look at the Python documentation at https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop

**Comment by Bibo-Joshi** [comment]
I recommend that you explicitly set an event loop for your thread if there no loop available yet in the thread. But this is a general asyncio question and not specific to PTB:)
