### ISSUE TITLE
Issue with MessageHandlers Not Triggering filters.Document.ALL

### ISSUE THREAD

**Issue by hcfk** [python-telegram-bot/python-telegram-bot#4538]
### Issue I am facing

I'm trying to download documents sent by users to my bot and have set up the relevant MessageHandlers. However, I'm encountering an issue where the handler for **filters.Document.ALL** doesn't seem to trigger—it always defaults to **filters.ALL**.

Other handlers, such as **filters.Voice()** and **filters.TEXT & ~filters.COMMAND** (for web links), work as expected and fire correctly. While I can work around this by using filters.ALL to handle document downloads, I’d like to know how to resolve this so that filters.Document.ALL triggers as intended.

Below is the request trace for reference.

### Traceback to the issue

telegram.ext.ExtBot - DEBUG - Call to Bot API endpoint `getUpdates` finished with return value `[{'update_id': 523289959, 'message': {'message_id': 233, 'from': {'id': 1522357784, 'is_bot': False, 'first_name': 'Fatih', 'username': '**************', 'language_code': 'en'}, 'chat': {'id': 1522357784, 'first_name': 'Fatih', 'username': '**************', 'type': 'private'}, 'date': 1730067067, 'video': {'duration': 3, 'width': 256, 'height': 480, 'file_name': 'IMG_8669.MP4', 'mime_type': 'video/mp4', 'thumbnail': {'file_id': 'AAMCBAADGQEAA91nHqtkZT6bBmFif773RAQoYd_kCgACNh0AAkbc8FCXXXSBJl9vYwEAB20AAzYE', 'file_unique_id': 'AQADNh0AAkbc8FBy', 'file_size': 14887, 'width': 171, 'height': 320}, 'thumb': {'file_id': 'AAMCBAADGQEAA91nHqtkZT6bBmFif773RAQoYd_kCgACNh0AAkbc8FCXXXSBJl9vYwEAB20AAzYE', 'file_unique_id': 'AQADNh0AAkbc8FBy', 'file_size': 14887, 'width': 171, 'height': 320}, 'file_id': 'BAACAgQAAxkBAAPdZx6rZGU-mwZhYn--90QEKGHf5AoAAjYdAAJG3PBQl110gSZfb2M2BA', 'file_unique_id': 'AgADNh0AAkbc8FA', 'file_size': 233426}}}]`

### Related part of your code

def main():
    application = Application.builder().token(TELEGRAM_BOT_TOKEN).build()

    # Command and message handlers  
    application.add_handler(CommandHandler("start", start))
    application.add_handler(MessageHandler(filters.Document.ALL, handle_document))
    application.add_handler(MessageHandler(filters._Voice(), handle_voice_message))
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_web_link)) 
    application.add_handler(MessageHandler(filters.ALL, do_nothing))  # Handle unsupported message types

    # Start the bot
    logger.info("Starting bot application...")
    application.run_polling()

### Operating System

windows 11

### Version of Python, python-telegram-bot & dependencies

python 3.12
python-telegram-bot==21.6

**Comment by Bibo-Joshi** [comment]
Hi. In the update payload you included in your description, the update doesn't have a "document", it only contains a "video". filters.Document.ALL doesn't catch that. Maybe you're looking for [filters.ATTACHMENT](https://docs.python-telegram-bot.org/en/v21.6/telegram.ext.filters.html#telegram.ext.filters.ATTACHMENT)? Note that this would include voice messages.

As a side note: filters._Voice is a protected attribute and should not be used directly. Please use `filters.VOICE` instead.
