### ISSUE TITLE
How to know a message is deleted from Telegram APP?

### ISSUE THREAD

**Issue by jnxyatmjx** [python-telegram-bot/python-telegram-bot#4569]
### Issue I am facing

For a bot is there any way to konw a message is deleted?

### Traceback to the issue

```python

```

### Related part of your code

```python

```

### Operating System

Distributor ID: Ubuntu Description:    Ubuntu 22.04.5 LTS Release:        22.04 Codename:       jammy

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 21.7
Bot API 7.11
Python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
```

**Comment by Poolitzer** [comment]
No you don't get an update for it. Probably forward/copy fails if you want to check for a specific message.

**Comment by jnxyatmjx** [comment]
> No you don't get an update for it. Probably forward/copy fails if you want to check for a specific message.

Thanks, got it.

**Comment by jnxyatmjx** [comment]
by the way, use below code. how can i use parameter ***application*** send message in executor **groupsender**
```python
async with application:
        await application.initialize()
        await application.start()
        await application.updater.start_polling(allowed_updates=Update.ALL_TYPES)
        await asyncio.get_running_loop().run_in_executor(None,groupsender,task_queue_,application)
        await application.stop()
```

**Comment by jnxyatmjx** [comment]
> groupsender

or how to send messages in other  thread, if above code can't do it

**Comment by Poolitzer** [comment]
Please don't use an old issue to get support for a different problem, open a discussion or ask in the telegram group. In there though please state why you want this, this looks to me like a [XY problem](https://xyproblem.info/)
