### ISSUE TITLE
Unifiy `datetime` import

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#4577]
The imports of the `datetime` module are all over the place. We currently have at least the following styles in our lib:

* `import datetime`
* `import datetime as dtm`
* `from datetime import datetime, timedelta`

Let's unify that to `import datetime as dtm`. I prefer this option since

1. Since there is `datetime.datetime`, a standalone `datetime` can be confusing. Using the toplevel module is preferable IMO.
2. `dtm` is shorter that `datetime`, plus it make `dtm.datetime` unambiguous`

**Comment by cuevasrja** [comment]
Hi, my class group and I want to work in this Issue.

Group:
@Jeam-zx
@Migueldsc12
@AnyaMarcanito
@henryg311
@cuevasrja

**Comment by Bibo-Joshi** [comment]
Assigned to you. As noted in the group, please get started with this one. #4580 and #4575 require a bit more understanding of PTBs code base, so I'd like to first see how this one works out :)
