### ISSUE TITLE
`CommandHandler` not recognized when text is copy-pasted

### ISSUE THREAD

**Issue by jgsch** [python-telegram-bot/python-telegram-bot#4579]
### Steps to Reproduce

1. 

```python
from telegram.ext import Application, CommandHandler, MessageHandler, filters


async def start_callback(update, context):
    user_says = " ".join(context.args)
    await update.message.reply_text("You said: " + user_says)


async def debug_handler(update, context) -> None:
    print(f"Received debug text: {repr(update.message.text)}")


app = Application.builder().token("<YOUR_TOKEN>").build()
app.add_handler(CommandHandler("start", start_callback))
app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, debug_handler))
app.run_polling(allowed_updates=["message"])

```

2.

Send a message to your bot: `/start test`. You should receive the response: `You said: test`.

3.

Copy and paste the same message, then press Enter. You should not receive a response from the bot, but in the terminal log, you should see: `Received debug text: /start test`.

### Expected behaviour

There should be no difference between typed text and copy-pasted text.

### Actual behaviour

When the message is copied and pasted, the `CommandHandler` is not triggered.

### Operating System

Fedora Linux 40 (Workstation Edition)

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 21.7
Bot API 7.11
Python 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0]
```

### Relevant log output

```python

```

**Comment by Poolitzer** [comment]
@jgsch Can you provide a screenshot from the conversation? I assume your client doesn&#x27;t send the copy pasted message as an actual command

**Comment by jgsch** [comment]
@Poolitzer good point !

![Image](https://github.com/user-attachments/assets/12d04d21-8894-4b25-b5f9-990a0f100c73)

The second message is copy-pasted. When the command is underlined, it triggers the debug text. This behavior occurs in the desktop web app and is also observed on my smartphone.

**Comment by Poolitzer** [comment]
@jgsch If you want your situation to be covered you should use a <a href="https://docs.python-telegram-bot.org/telegram.ext.prefixhandler.html#telegram.ext.PrefixHandler">telegram.ext.PrefixHandler</a>
