### ISSUE TITLE
Extend Support for Convenience Types in Bot Methods

### ISSUE THREAD

**Issue by Bibo-Joshi** [python-telegram-bot/python-telegram-bot#4580]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

In `test_official` we currently allow convenience input types only for `send_*` methods:

https://github.com/python-telegram-bot/python-telegram-bot/blob/151123745e9e8d53c54fd6715008b3e8c85bdc82/tests/test_official/arg_type_checker.py#L174-L178

https://github.com/python-telegram-bot/python-telegram-bot/blob/151123745e9e8d53c54fd6715008b3e8c85bdc82/tests/test_official/exceptions.py#L39-L48

Removing the `obj.__name__.startswith("send")` reveals that there are a few more parameters that could use convenience types.

### Describe the solution you'd like

* Set up the "additional types" excetpions in test_official such that they can either be defined globally or per method, remove the `obj.__name__` check
* add support for convenience types where possible

**Comment by cuevasrja** [comment]
Hi, my class group and I want to work in this Issue.

Group:
@Jeam-zx
@Migueldsc12
@AnyaMarcanito
@henryg311
@cuevasrja
