### ISSUE TITLE
Ask if document internationalization tasks are required

### ISSUE THREAD

**Issue by Muzych** [python-telegram-bot/python-telegram-bot#4581]
### Issue I am facing

As a Chinese language user, I would like to inquire whether the PTB community's documentation requires internationalization translation, and I am willing to contribute a Pull Request for the Chinese translation of the PTB documentation.

### Traceback to the issue

```python

```

### Related part of your code

```python

```

### Operating System

Windows

### Version of Python, python-telegram-bot & dependencies

```shell
nothing here.
```

**Comment by Poolitzer** [comment]
Hi, thanks for the offer, but we are constantly working on the English documentation alone, so we don't have the resources to branch out to a different language.
