### ISSUE TITLE
What exactly should be written in the main file of the bot so that the bot listens to updates from the telegram server via "The integrated webhook server"??

### ISSUE THREAD

**Issue by surgutandrey** [python-telegram-bot/python-telegram-bot#4588]
### Issue I am facing

What exactly should be written in the main file of the bot so that the bot listens to updates from the telegram server via "The integrated webhook server"??

https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks#the-integrated-webhook-server

Everything else works! Diagnostics show that the bot is not listening to updates:

My code is:
application.run_webhook(
            listen='0.0.0.0',
            port=8443,
            secret_token=config.webhook_secret_token,
            key=config.webhook_key,
            cert=config.webhook_cert,
            webhook_url=https://{SERVER_IP}:{PORT}/{TOKEN}
        )

### Traceback to the issue

```python

```

### Related part of your code

```python

```

### Operating System

Linux Ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
Python 3.11
```

**Comment by surgutandrey** [comment]
The port is open to the server, ping from the globe goes to the port.

**Comment by Bibo-Joshi** [comment]
https://t.me/pythontelegrambotgroup/766700

**Comment by Bibo-Joshi** [comment]
Closing in favor of https://t.me/pythontelegrambotgroup/766938
