### ISSUE TITLE
User.to_dict() returns absent fields with empty strings '' values

### ISSUE THREAD

**Issue by lisitsky** [python-telegram-bot/python-telegram-bot#460]
### Steps to reproduce
1. Register any bot in Telegram. Here I will use one with smudged sensitive information.
Get its own information using `getMe` telegram api call.
For example (output pretty-printed):
```
$ http https://api.telegram.org/bot17XXXXX3:AXXcXnXXXXXXXXQgcXXXXc/getMe
HTTP/1.1 200 OK
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
Connection: keep-alive
Content-Length: 89
Content-Type: application/json
Date: Sun, 06 Nov 2016 22:00:54 GMT
Server: nginx/1.10.1
Strict-Transport-Security: max-age=31536000; includeSubdomains

{
    "ok": true,
    "result": {
        "first_name": "test",
        "id": 17XXXXX3,
        "username": "test_bot"
    }
}
```

2. Try to get the same information using Python Telegram Bot.
Version 3.4.0 (prior to 4.0.0):
```
$ bpython
bpython version 0.16 on top of Python 3.5.1 /Users/el/.pyenv/versions/3.5.1/bin/python3.5
>>> import telegram
>>> bot=telegram.Bot('bot17XXXXX3:AXXcXnXXXXXXXXQgcXXXXc')
>>> user=bot.getMe()
>>> user.to_dict()
{'first_name': 'test', 'id': 17XXXXX3, 'username': 'test_bot'}
```

Version after 4+ (for example 5.2.0):
```
$ bpython
bpython version 0.16 on top of Python 3.5.1 /Users/el/.pyenv/versions/3.5.1/bin/python3.5
>>> import telegram
>>> bot=telegram.Bot('bot17XXXXX3:AXXcXnXXXXXXXXQgcXXXXc')
>>> user=bot.getMe()
>>> user.to_dict()
{'first_name': 'test', 'last_name': '', 'type': '', 'id': 17XXXXX3, 'username': 'test_bot'}```
```

3. 

### Expected behaviour
Should return only fields got with Telegram API (id, first_name, username), do not add empty optional fields (last_name, type).

### Actual behaviour
Returned dict is populated with absent optional fields (last_name, type) with empty string values.

### Configuration
**Operating System:**
MaxOS 10.12.1 
Also tested on Linux boxes in different CI platforms (like Travis-CI, Codeship)

**Version of Python, python-telegram-bot & dependencies:**
Reproduced on 3.4.5, 3.5.1, 3.5.2, 3.6b4+

```
$ python -m telegram
/Users/el/.pyenv/versions/3.5.1/bin/python: No module named telegram.__main__; 'telegram' is a package and cannot be directly executed
```
### Logs
Insert logs here (if necessary)

Issue was found after upgrading python-telegram-bot from 3.2 to 5.2.0 used as an intermediate dependency in my project.

### Reason
One of the reasons to emerge the issue can be a [changes](https://github.com/python-telegram-bot/python-telegram-bot/compare/v3.2...v5.2.0?diff=split&name=v5.2.0#diff-4a13231a9fa379318457405e5df4712bL63) between versions. While dumping user data to dict, old version ignored empty field checking them (``if field: ...``) thus 0, false and some other values could be lost. New version checks them (``if field is not None: ...``) in this case we ignore only real empty (``None``) fields, but method ``User.__init__`` [uses empty string as default values](https://github.com/python-telegram-bot/python-telegram-bot/compare/v3.2...v5.2.0?diff=split&name=v5.2.0#diff-c9df4cc0aa3986f1f87042b987ec5bd4R47) for absent parameters. So User object gets ``''`` as values.

## Possible impact
Can break some other products dependant on returned values of ``getMe`` method.

## Proposition
Change signature of ``User`` constructor to use ``None`` as default value for absent optional parameters.

If you wish I can make a PR with tests.

**Comment by jh0ker** [comment]
I would like to hear @leandrotoledo 's opinion on this, but I would generally agree with you. When I joined the project, string fields would be populated with empty strings everywhere, and I simply carried on the tradition ^^
I guess in some cases it could make things easier, but I would generally agree that using `None` makes more sense. If we decide to change this, we have to do it in the 6.0 release.

**Comment by lisitsky** [comment]
I quite agree with you, let's get know how Leandro sees further project development. These changes can seriously modify module behaviour and break other application based on this behaviour. If we decide to do, how do you think: is it better to make all changes at once? So users will have to adopt them only one time upgrading to next major version? On the other side, big changes can crash many things.

I've made a grep to see what classes have constructors with empty strings:
If I haven't missed anything -  11 classes are our possible clients :)

```
11:40 $ pcregrep -Mrni --buffer-size=300M --match-limit=100000000000 --recursion-limit=100000000000  "def __init__\([^)']+'[^)]*\):" telegram/*
telegram/audio.py:46:    def __init__(self,
                 file_id,
                 duration,
                 performer='',
                 title='',
                 mime_type='',
                 file_size=0,
                 **kwargs):
telegram/chat.py:53:    def __init__(self,
                 id,
                 type,
                 title='',
                 username='',
                 first_name='',
                 last_name='',
                 all_members_are_admins=False,
                 bot=None,
                 **kwargs):
telegram/contact.py:42:    def __init__(self, phone_number, first_name, last_name='', user_id=0, **kwargs):
telegram/document.py:44:    def __init__(self, file_id, thumb=None, file_name='', mime_type='', file_size=0, **kwargs):
telegram/file.py:43:    def __init__(self, file_id, bot, file_size=0, file_path='', **kwargs):
telegram/game.py:47:    def __init__(self,
                 title,
                 description,
                 photo,
                 text='',
                 text_entities=None,
                 animation=None,
                 **kwargs):
telegram/message.py:111:    def __init__(self,
                 message_id,
                 from_user,
                 date,
                 chat,
                 forward_from=None,
                 forward_from_chat=None,
                 forward_date=None,
                 reply_to_message=None,
                 edit_date=None,
                 text='',
                 entities=None,
                 audio=None,
                 document=None,
                 photo=None,
                 sticker=None,
                 video=None,
                 voice=None,
                 caption='',
                 contact=None,
                 location=None,
                 venue=None,
                 new_chat_member=None,
                 left_chat_member=None,
                 new_chat_title='',
                 new_chat_photo=None,
                 delete_chat_photo=False,
                 group_chat_created=False,
                 supergroup_chat_created=False,
                 migrate_to_chat_id=0,
                 migrate_from_chat_id=0,
                 channel_chat_created=False,
                 pinned_message=None,
                 bot=None,
                 **kwargs):
telegram/sticker.py:47:    def __init__(self, file_id, width, height, thumb=None, emoji='', file_size=0, **kwargs):
telegram/user.py:47:    def __init__(self, id, first_name, type='', last_name='', username='', bot=None, **kwargs):
telegram/video.py:49:    def __init__(self,
                 file_id,
                 width,
                 height,
                 duration,
                 thumb=None,
                 mime_type='',
                 file_size=0,
                 **kwargs):
telegram/voice.py:43:    def __init__(self, file_id, duration, mime_type='', file_size=0, **kwargs):
```
