### ISSUE TITLE
RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by nxmnn** [python-telegram-bot/python-telegram-bot#4602]
### Issue I am facing

hello everyone! 

I'm encountering a rare error when using python-telegram-bot version 20.x (tested with 20.0, 20.1, 20.2, and 20.3) in asynchronous mode. Following the official documentation's recommended approach to run long polling, I receive a RuntimeError: This event loop is already running immediately upon starting the bot.

Key Details:

Server environment: Ubuntu 20.04 LTS.
Tried multiple Python versions: 3.8 (system default), Python 3.10, and Python 3.11 (installed via deadsnakes PPA).
Tried multiple python-telegram-bot versions in the 20.x series (20.0 through 20.3).
The issue reproduces with the minimal example code from the official documentation:
python
Копировать код
import asyncio
from telegram.ext import ApplicationBuilder, CommandHandler
from telegram import Update
from telegram.ext import ContextTypes

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("Hello!")

async def main():
    application = ApplicationBuilder().token("YOUR_TOKEN").build()
    application.add_handler(CommandHandler("start", start))
    await application.run_polling()  # also tried await application.run_polling(close_loop=False)

if __name__ == "__main__":
    asyncio.run(main())
Upon running the script, I get:
vbnet
Копировать код
RuntimeError: This event loop is already running
...
RuntimeWarning: coroutine 'Application.initialize' was never awaited
RuntimeWarning: coroutine 'Application.shutdown' was never awaited
A simple async test (test_async.py without python-telegram-bot) works fine, indicating that the basic asyncio setup is okay.
No other Python processes, IPython, or Jupyter sessions are running on the server.
Using older synchronous versions (e.g., python-telegram-bot==13.14) on the same server works without issues.
Restarting the server, using fresh virtual environments, upgrading packages, and trying different Python and library versions have not resolved the problem.
Tried both asyncio.run(main()) and manually managing the event loop, as well as close_loop=False, with no success.
Expected Behavior: The code from the documentation should run without errors, allowing the bot to receive updates via long polling asynchronously.

Actual Behavior: Immediately after starting, I get RuntimeError: This event loop is already running, preventing the bot from operating correctly.

Questions:

Are there known conflicts or conditions that cause this error?
Do I need additional event loop configurations for certain environments?
Could there be an issue in how run_polling() manages the event loop?
Any guidance or suggestions would be greatly appreciated.

### Traceback to the issue

```python

```

### Related part of your code

```python

```

### Operating System

windows

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot version 20.x
Python versions: 3.8 (system default), Python 3.10, and Python 3.11
```

**Comment by Poolitzer** [comment]
@nxmnn Our official documentation does not use asyncio.run please refere to any of our examples, e.g. <a href="https://docs.python-telegram-bot.org/examples.html#examples-echobot">echobot.py</a>
