### ISSUE TITLE
General question for Docker

### ISSUE THREAD

**Issue by superbabii** [python-telegram-bot/python-telegram-bot#4609]
### Issue I am facing

How to run this project using Docker

### Traceback to the issue

```python

```

### Related part of your code

```python

```

### Operating System

Ubuntu

### Version of Python, python-telegram-bot & dependencies

```shell
python 3
```

**Comment by Bibo-Joshi** [comment]
Hi. Please explain what exactly you need help with. See also [this wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Ask-Right). I'll close this thread for now. If you reply with a more meaningful question, we can consider reopening.

**Comment by superbabii** [comment]
sorry, good repo, I already solved myself
