### ISSUE TITLE
I use filters.ALL, and then the interceptor can't receive the message. How should I deal with it?

### ISSUE THREAD

**Issue by yaaynn** [python-telegram-bot/python-telegram-bot#4612]
### Issue I am facing

Hi, everyone!

I use filters.ALL, and then the interceptor can't receive the message. How should I deal with it?

Thank!

### Traceback to the issue

```python

```

### Related part of your code

```python

```

### Operating System

windows

### Version of Python, python-telegram-bot & dependencies

```shell
3.10.14
```

**Comment by Poolitzer** [comment]
@yaaynn Register the interceptor before the all handler

**Comment by yaaynn** [comment]
> [@yaaynn](https://github.com/yaaynn) Register the interceptor before the all handler

The point: Is there a way to keep this chain going down, instead of being terminated by a Handler? Hopefully, this connection can continue.

All filters are not auxiliary, but necessary processes. In this chain, they must be executed. Here I need to check if the user and group information is in my database and initialize some basic data for it.

English is not my native language, I apologize for the grammar and description errors.

Thank you!

**Comment by yaaynn** [comment]
> > [@yaaynn](https://github.com/yaaynn) Register the interceptor before the all handler
> 
> The point: Is there a way to keep this chain going down, instead of being terminated by a Handler? Hopefully, this connection can continue.
> 
> All filters are not auxiliary, but necessary processes. In this chain, they must be executed. Here I need to check if the user and group information is in my database and initialize some basic data for it.
> 
> English is not my native language, I apologize for the grammar and description errors.
> 
> Thank you!

@Poolitzer

**Comment by Poolitzer** [comment]
@yaaynn Each handler triggers at most once per group, if you want them to be independent from another you should add them to different groups

**Comment by yaaynn** [comment]
> [@yaaynn](https://github.com/yaaynn) Each handler triggers at most once per group, if you want them to be independent from another you should add them to different groups

@Poolitzer Thank you very much, the problem is solved. Awesome!
