### ISSUE TITLE
TypeError: 'MessageHandler' object is not iterable when using fallbacks

### ISSUE THREAD

**Issue by superciccio14** [python-telegram-bot/python-telegram-bot#463]
I'm trying to use `ConversationHandler()` to manage conversations. My sample it's very simple

```
def cancel(bot, update):
    update.message.reply_text('Bye!')
    return ConversationHandler.END

conv_handler = ConversationHandler(
    entry_points=[CommandHandler('foo',foo)],
    states={
        A_STATE_RETURNED_BY_FOO: MessageHandler(Filters.text, bar)
    },
    fallbacks=[CommandHandler('cancel', cancel)]
)

dispatcher.add_handler(conv_handler)
```

### Expected behaviour
when I `/cancel` the conversation I expect a normal conversation ending.

### Actual behaviour
when I try to `/cancel` the conversation I get an error, see log. (The same happens using your examples of conversation bots)

### Configuration
Ubuntu server 16.04 LTS

**Version of Python, python-telegram-bot & dependencies:**

python-telegram-bot 5.2.0
urllib3 1.19
certifi 2016.09.26
future 0.16.0
Python 2.7.12 (default, Jul  1 2016, 15:12:24)  [GCC 5.4.0 20160609]

### Logs
2016-11-14 18:27:27,986 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File ".../python2.7/site-packages/telegram/ext/dispatcher.py", line 269, in process_update
    if handler.check_update(update):
  File ".../python2.7/site-packages/telegram/ext/conversationhandler.py", line 166, in check_update
    for candidate in (handlers or []):
TypeError: 'MessageHandler' object is not iterable

**Comment by jh0ker** [comment]
`A_STATE_RETURNED_BY_FOO: MessageHandler(Filters.text, bar)`
should be 
`A_STATE_RETURNED_BY_FOO: [MessageHandler(Filters.text, bar)]`
