### ISSUE TITLE
Command import from JSON file functionality

### ISSUE THREAD

**Issue by Srogozins** [python-telegram-bot/python-telegram-bot#464]
I've made a module that lets you define some simple stupid commands for a bot in JSON file and import them:
It allows for following mappings:
- command -> reply string
- command -> random reply string from a list
It also allows to call the command inline.

The demo repository is https://github.com/Srogozins/stupid_bot. Commands are defined in commands.json and command_importer.py is the module responsible for import. It is also running in Telegram right now as @stupidbotbot.

This allows to quickly create simple stupid novelty bots and/or avoid having to mess up your code with many short callbacks that differ only in which specific string variable they use. I've gotten confirmation that some people(one person) are interested in this feature. 

**My question is following:** is this kind of functionality in demand upstream? Should I bother with preparing a pull request? Otherwise I'll probably make it available in some other way.

**Comment by rahiel** [comment]
Hey @Srogozins this looks cool, but at this time this functionality would be just outside our scope.

I suggest to provide this in a separate package, then we can recommend it on our [Related Projects](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Related-Projects) page.
