### ISSUE TITLE
Usage of update.message without checking for None in case of edits.

### ISSUE THREAD

**Issue by Lumiukko** [python-telegram-bot/python-telegram-bot#469]
There are several places where the bot accesses `update.message` without checking whether it is `None`. If a message is edited, the `message` will be `None`, and instead there is a field called `edited_message`. This causes the bot to throw an Exception and stop working.

This is used for example in the `echobot.py` example, as well as in the Tutorial that re-uses the echo example, here: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-Your-first-Bot

I would like to note that this is probably only an issue for beginners. However, the examples should be accessible enough to be used as a learning basis and be a minimal working example.

### Steps to reproduce
1. Try out the echobot.py example
2. Send a message to the bot.
3. Edit the previously sent message.

### Expected behaviour
The bot should either echo the edited message, or edit his previously echoed message. Echo the edited message seems more intuitive for this example bot.

### Actual behaviour
The bot throws an KeyError exception.

**Comment by bomjacob** [comment]
Hmm... The echobot2 example does not pass edited=True to the command and/or messagehandlers.. this means that it should just silently ignore the error....
Could you show the full log of that KeyError exception please?

**Comment by Lumiukko** [comment]
> Could you show the full log of that KeyError exception please?

Nope, because it doesn't exist. I read about someone complain about this error and checked for the echobot example and assumed this was the cause, because it would be if allow_edit is True (I didn't know that the `allow_edited=False` is a default setting in the handlers). So apparently the mistake was either that the user accidentally set it to True, or the error was somewhere else.

In any case, this issue can be closed :)
