### ISSUE TITLE
Is there any way to serve multiple robots by same process?

### ISSUE THREAD

**Issue by alex4321** [python-telegram-bot/python-telegram-bot#474]
In my case - I'll have multiple robots with different "scripts".
But, at least, some robot common components need big count of memory and have long instantiation procedures (up to few minutes), so I want to serve all bots in same process (seems like sharing between process willn't be easy. also, building some like "microservice" will work, but maybe there any other way?).

So - is there any way to serve it in same process, or it can't be maked without moving "backend" to other process?

**Comment by alex4321** [comment]
Sorry, seems like I fiound answer by myself.
I just started multiple updaters:

```
updaters=[Updater(token) for token in config['TOKENS']]
...
for updater in updaters:
  updater.start_polling()
```

Ans it works. But are it's right way, or can cause any problems?

**Comment by naveenvhegde** [comment]
It works though. These days, many use REDIS to share data between multiple processes. You can give it a try,
