### ISSUE TITLE
Getting Username

### ISSUE THREAD

**Issue by Alirezaies** [python-telegram-bot/python-telegram-bot#476]
Hello,
Thanks For Your Good Work On This Repository.
Honestly I'm New To Telegram Bots And I Have A Question:

I Know That `update.message.chat_id` Returns The User's Chat ID, But I Need To Know How To Get User's Username Or First Name And/Or Last Name.

I've Found [This](https://core.telegram.org/bots/api#getchatmember) On Telegram's Documentation But I Don't Know How To Use It ( I Tried `bot.getChatMember(update.message.chat_id)` But No Result)

Sorry For Newbie Question.
Thanks

**Comment by jh0ker** [comment]
@Alirezaies You can use update.message.from_user which is a User object. 
Example: update.message.from_user.first_name

**Comment by Alirezaies** [comment]
Ok I Used `bot.sendMessage(chat_id, update.message.from_user)` Which Didn't Return Me Anything, 
But I've Found Another Solution, Which Is `bot.getChat(update.message.chat_id)` Which Returns A Dictionary With All Available Information.

**Comment by jh0ker** [comment]
@Alirezaies bot.sendMessage(chat_id, update.message.from_user) is faulty, because sendMessage expects a string, not a User object.

**Comment by Alirezaies** [comment]
ok I used `bot.sendMessage(update.message.chat_id, str(update.message.from_user.username))` And It Worked For Me.
Thanks

**Comment by Nadya24** [comment]
how I get User ID, update.message.from_user.id Is it the chat ID?

**Comment by m4mallu** [comment]
How to get bot's username ?

**Comment by puroh** [comment]
> How to get bot's username ?
```python
def funtion_example(update, context):
    print(update.message.from_user['username'])
```

**Comment by Bibo-Joshi** [comment]
> > How to get bot's username ?
> 
> ```python
> def funtion_example(update, context):
>     print(update.message.from_user['username'])
> ```

No, that gives the username of the sender. The bot's username is given by `bot.name`, as documented [here](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.name). In callbacks, the bot is available as `context.bot`.
