### ISSUE TITLE
Group Does Not Exist

### ISSUE THREAD

**Issue by Alirezaies** [python-telegram-bot/python-telegram-bot#477]
In The README File There Is A [Telegram Group](https://telegram.me/pythontelegrambotgroup) Mentioned, But This Group Does Not Exist On Telegram.

**Comment by amamaenko** [comment]
It does exist indeed. Did you try to navigate the link?

**Comment by rahiel** [comment]
Either follow the link or search for `pythontelegrambotgroup` on Telegram.

**Comment by Alirezaies** [comment]
Have A Look At [This Screenshot](http://webgo.ir/tg.png).
I Directly Clicked On The Link In README

**Comment by jh0ker** [comment]
@Alirezaies Is it possible that public supergroups are disabled in your country?

**Comment by Alirezaies** [comment]
No,
I Joined The Channel Via iPhone Client, But I Don't Know What Is Wrong With The Desktop.
