### ISSUE TITLE
How to delete a sent photo

### ISSUE THREAD

**Issue by MrUke** [python-telegram-bot/python-telegram-bot#480]
Hi,
I need to make my bot delete a photo that has been sent (by the bot itself) previously. Is there a API/function to do it?

Thank you in advance.
Luca

**Comment by MrUke** [comment]
In other words, I need a way to edit a photo replacing them. I thought that the easiest way to do it may be deleting the photo and sending the another one.

**Comment by jh0ker** [comment]
The API doesn't allow you to delete messages or edit photos :/

**Comment by jzs14** [comment]
Are there any plans for this? Or is this something that's likely to never be possible?

**Comment by jh0ker** [comment]
@jzs14 It's not our decision, you will have to ask the Telegram (Bot) Support.

**Comment by StreakyCobra** [comment]
Hi,

> The API doesn't allow you to delete messages or edit photos :/

It seems to be possible now: https://core.telegram.org/method/messages.deleteMessages

Note sure about what I am saying though :smiley:

**Comment by jh0ker** [comment]
@StreakyCobra That is the Telegram API, not the Bot API

**Comment by StreakyCobra** [comment]
@jh0ker Oh, I saw "API" I thought it was the same! My bad, sorry for the noise.

**Comment by jh0ker** [comment]
@StreakyCobra No problem
