### ISSUE TITLE
RegexHandler(r'^ب$', modikar)  //Problem with Persian Chars

### ISSUE THREAD

**Issue by zeynaliAli** [python-telegram-bot/python-telegram-bot#488]
### Steps to reproduce
1.

2.

3.

### Expected behaviour
I used `RegexHandler('^ب$', modikar)` method (with Persian Chars) I expected that it works same as English but it wont.

### Actual behaviour
When I use This method with English chars everything is okay but with Persian Chars it don't work 
and Don't log anything tho.

### Configuration
**Operating System:** Ubuntu 16.04.1 

**Version of Python, python-telegram-bot & dependencies:** Python 2.7.12, 5.3.0 , no dependency

``$ python -m telegram``  ::
``
python-telegram-bot 5.3.0
urllib3 1.19.1
certifi 2016.09.26
future 0.16.0
Python 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
``

### Logs
no Log produced 
but a code snippet below ::
```
conv_handler = ConversationHandler(
        entry_points=[CommandHandler('start', start)],

        states={
            IN_THE_FIRST_KEYBOARD: [RegexHandler('^ب$', modikar),
                                    RegexHandler('^B$', rahavard)]
        },

        fallbacks=[CommandHandler('cancel', cancel)]
    )
```
And please update the telegram group link in read me it's broken

**Comment by tsnoam** [comment]
Hi @zeynaliAli ,

The new issue template is there for a reason. We need more information, please add everything as was requested:
### Steps to reproduce
1.

2.

3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating System:**


**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by zeynaliAli** [comment]
@tsnoam Hi 
Sorry issue edited ; but I can't Understand  ``Steps to reproduce`` what actually want.

**Comment by tsnoam** [comment]
@zeynaliAli 
example steps to reproduce: 
```
1. send keyboard
2. error - exception raised              -> add log of exception 
  - or - 
2. client receives keyboard but it shows wrong text.      -> add screenshot
```

in any case, it seems that you're using python2.7 which is inferior in everything related to unicode (so it just makes your life more difficult).
what I do see in the code you sent in the problem description is that you missed the '`u`' prefix to unicode strings.
try this instead (mind the '`u`'):
`RegexHandler(u'^ب$', modikar),`

**Comment by zeynaliAli** [comment]
@tsnoam Thank you , I just learned python last night ,too much things to understand :)

**Comment by tsnoam** [comment]
you're welcome.

**Comment by denisergashbaev** [comment]
Have you tried to debug? It may be that you are just working with different
encodings. I had the same with russian once, which was fixed by ensuring my
python code converts everything to unicode
