### ISSUE TITLE
[Question] How to get user's Id

### ISSUE THREAD

**Issue by devianpctek** [python-telegram-bot/python-telegram-bot#491]
Hello, just as the title says, I want to know how to retrieve the user's id, this in order so the bot only replies to that specific user/s, I'm playing with some home automation stuff, and found a code using node.js that does exactly that, but I want to do it in python, I put the code in js so you get the idea

`function echo(message) {
  
  bot.sendMessage({
	  chat_id: message.chat.id,
	  text: 'User ID ' + message.from.id + ' says "' + message.text + '"',
  });
}`

I'm interested in the "message.from.id" part, this because as I say, I just want only certain users to interact with the bot.

Thanks in advance

**Comment by eteamin** [comment]
use `message.from_user.id`

**Comment by devianpctek** [comment]
Thanx a lot
