### ISSUE TITLE
cannot import name ReplyKeyboardRemove

### ISSUE THREAD

**Issue by mabedis** [python-telegram-bot/python-telegram-bot#493]
### Steps to reproduce
1. from telegram import (ReplyKeyboardMarkup, ReplyKeyboardRemove)

### Actual behaviour
ImportError: cannot import name ReplyKeyboardRemove

### Configuration
**Operating System:**
LinuxMint
#1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19)

**Version of Python, python-telegram-bot & dependencies:**
``$ python -m telegram``
python-telegram-bot 5.2.0
urllib3 1.19.1
certifi 2016.09.26
future 0.16.0
Python 2.7.9 (default, Jun 29 2016, 13:08:31)  [GCC 4.9.2]

### Logs

**Comment by tsnoam** [comment]
@mabedis ReplyKeyboardRemove was introduced in version 5.3.
You should upgrade...
