### ISSUE TITLE
MySQLdb Problem

### ISSUE THREAD

**Issue by Alirezaies** [python-telegram-bot/python-telegram-bot#498]
Hello.
I'm having issue using `MySQLdb.connect()` into any function that receives `bot, update` as input parameters.
example

    def something(bot, update):

         print "going for sql"

         db = MySQLdb.connect("host", "user", "password", "db_name")

         cursor = db.curser()

         curser.execute("QUERY;")

         db.commit()

         db.close()

         print "sql finished"

the program prints `going for sql` but freezes.
I tried to write a function for sql in call that inside the bots function but same problem
I need to use database with the bot.
thank you

**Comment by tsnoam** [comment]
Hi @Alirezaies 
Your code example shows that your code hangs with the DB code. This has nothing to do with python-telegram-bot.
Also, next time when you open an issue, please fill the information as requested in the new issue form. It helps us to help you.
