### ISSUE TITLE
ConversationHandler asynchronously

### ISSUE THREAD

**Issue by estsantre** [python-telegram-bot/python-telegram-bot#501]
Hello, I'm using run_async to improve response time, and it works great with a message or command handler, but I can't use it with ConversationHandler, then if a user sent a message that starts a conversation the bot can't response asynchronously to all users.

So how can I use run_async with ConversationHandler? Or how can I manage asynchronously conversations?

Thanks!

I'm using python 3.5

**Comment by tsnoam** [comment]
Please open a new case and fill all information requested in the issue template.
