### ISSUE TITLE
ImportError: No module named telegram.ext

### ISSUE THREAD

**Issue by leanminmachine** [python-telegram-bot/python-telegram-bot#503]
### Expected behaviour
File should run 

### Actual behaviour
ImportError: No module named telegram.ext on first line of code

### Configuration
**Operating System:**
Mac OS 10.12.1

**Version of Python, python-telegram-bot & dependencies:**
pip 9.0.1 from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (python 2.7)

``$ python -m telegram``
/Applications/MAMP/Library/bin/python: No module named telegram
^Suspecting this is the issue.. 

### Logs
Insert logs here (if necessary)

**Comment by jh0ker** [comment]
@leanminmachine Did you install the library via pip?

**Comment by leanminmachine** [comment]
@jh0ker yeap i did:

```
Requirement already up-to-date: python-telegram-bot in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requirement already up-to-date: future>=0.15.2 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from python-telegram-bot)
Requirement already up-to-date: urllib3>=1.10 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from python-telegram-bot)
Requirement already up-to-date: certifi in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from python-telegram-bot)

python -m telegram
/Applications/MAMP/Library/bin/python: No module named telegram
```

**Comment by jh0ker** [comment]
@leanminmachine It looks to me like you have two (or more) different python versions installed. To make sure you install the module for the right version, try this:
python -m pip install python-telegram-bot

**Comment by tsnoam** [comment]
Closing due to no response.

**Comment by brotherpark** [comment]
Because your python file name is 'telegram'. It cause the conflict

**Comment by izjenie** [comment]
Removed telegram.pyc if you already rename your telegram.py

**Comment by ZishanAdThandar** [comment]
**solution is here::** 
`pip install python-telegram-bot`

**Comment by quangvuptit** [comment]
Thank you brotherpark! I get this error for some days and I don't know how to fix it. Suddently I see your comment about fixing it. Thanks too much.
