### ISSUE TITLE
Problem with deploy on heroku

### ISSUE THREAD

**Issue by Forkfant** [python-telegram-bot/python-telegram-bot#505]
I have simple telegram bot, and i want deploy it on Heroku.
I use this code for webhook:

    TOKEN = "*MY_TOKEN*"
    PORT = int(os.environ.get('PORT', '5000'))

    # add handlers
    updater.start_webhook(listen="127.0.0.1",
                        port=PORT,
                        url_path=TOKEN)
    updater.bot.setWebhook("https://herokuappname.herokuapp.com/" + TOKEN)
    updater.idle()`

But in heroku console I see : 2017-01-17T19:19:42.988546+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=POST

My Procfile:
`worker: python main.py`
How fix it?

**Comment by jh0ker** [comment]
@Forkfant Your code looks like you forgot the line
updater = Updater(TOKEN)
Also, I think you should use '0.0.0.0' instead of '127.0.0.1'

**Comment by Forkfant** [comment]
Yes, I copied the code is bad, really it looks like this:

    TOKEN = "*my_token*"
    PORT = int(os.environ.get('PORT', '5000'))
    updater = Updater(TOKEN)

    updater.start_webhook(listen="0.0.0.0",
                        port=PORT,
                        url_path=TOKEN)
    updater.bot.setWebhook("https://myappname.herokuapp.com/" + TOKEN)
    updater.idle()


Changing the IP did not help. I still get in the console "No web processes running".

**Comment by Eldinnie** [comment]
in your procfile:
change `worker: <script.py>`
into `web: <script.py>`
heroku only starts a webnserver when your procfile declares a web dyno.

good luck

**Comment by Forkfant** [comment]
@Eldinnie thank you very much, it has solved the problem.
