### ISSUE TITLE
[Feature Request] distributed/storage-backed JobQueue

### ISSUE THREAD

**Issue by amyodov** [python-telegram-bot/python-telegram-bot#506]
### Steps to reproduce

At the moment, according to the documents, the JobQueue is memory-backed and runs on a thread. This makes it complex and unsafe to scale the system. 

### Expected behaviour
If the system had supported the storage of a queue data in some external backend (likely pluggable), like in Redis/RQ/RabbitMQ – so that that worker who executes the Job is not necessary the same one as who schedules the Job – it would made things much easier.

This would likely also require storing the chat_data/user_data in the same or separate storage backend as well.

**Comment by jh0ker** [comment]
This is currently not part of our plans. It might come some day, but don't hold your breath ;) If you want to contribute something along these lines yourself, we'd appreciate it of course.

**Comment by Eldinnie** [comment]
It seems to me this issue has been answered. Closing
