### ISSUE TITLE
Updater.idle() not working correct in Thread

### ISSUE THREAD

**Issue by MTRNord** [python-telegram-bot/python-telegram-bot#509]
### Steps to reproduce
1. Make normal TG handling
2. Put that function in a thread and start the thread (from lib threading)

### Expected behaviour
Should work without error

### Actual behaviour
Gives Error "ValueError: signal only works in main thread"

### Configuration
**Operating System:** Windows 10 x64 with Aconda3 Python 3.5

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 5.3.0
urllib3 1.20
certifi 2017.01.23
future 0.16.0
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]

**Comment by jh0ker** [comment]
@MTRNord The updater and dispatcher already run in separate threads. If you insist on wrapping the adding of handlers and such in another thread, you must not use updater.idle

**Comment by MTRNord** [comment]
ah ok thanks :)
