### ISSUE TITLE
Telegram bot does not work for all people

### ISSUE THREAD

**Issue by MarcSky** [python-telegram-bot/python-telegram-bot#511]
Hello! Recently began to receive emails from my bot users, not all of it works, that is, not everyone responds to requests. Strange, but I have everything working fine on your phone. What could be the problem? Maybe I did not handle the server. Who faced a similar problem?

**Comment by rahiel** [comment]
This issue is too vaguely described. Answer the questions of [the issue template](https://github.com/python-telegram-bot/python-telegram-bot/issues/new) if you have more information.
