### ISSUE TITLE
ImportError: No module named connection

### ISSUE THREAD

**Issue by errazudin** [python-telegram-bot/python-telegram-bot#519]
### Steps to reproduce
1. Install :
$ pip install python-telegram-bot --upgrade

2. Execute import telegram from python console :
```
>>> import telegram
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/telegram/__init__.py", line 45, in <module>
    from .file import File
  File "/usr/local/lib/python2.7/dist-packages/telegram/file.py", line 24, in <module>
    from telegram.utils.request import download as _download
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 28, in <module>
    from urllib3.connection import HTTPConnection
ImportError: No module named connection
```

### Expected behaviour
Should be able to continue without ImportError message

### Actual behaviour
ImportError: No module named connection

### Configuration
**Operating System:**
Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-48-generic x86_64)

**Version of Python, python-telegram-bot & dependencies:**
Python 2.7.6
python-telegram-bot 5.3.0
urllib3 1.20
certifi 2017.01.23
future 0.16.0

``$ python -m telegram``
/usr/bin/python: No module named connection; 'telegram' is a package and cannot be directly executed

### Logs
Insert logs here (if necessary)

**Comment by errazudin** [comment]
UPDATES
- upgraded to Ubuntu 14.04.5 LTS
- the same error message still appear

**Comment by tsnoam** [comment]
@errazudin Can you try installing python-telegram-bot inside a virtualenv?

**Comment by errazudin** [comment]
@tsnoam thanks for responding
i've run through with a fresh 14.04.5 and it works. Maybe i've messed things up with earlier vm :(
