### ISSUE TITLE
How to set a proxy for this module?

### ISSUE THREAD

**Issue by dev-techmoe** [python-telegram-bot/python-telegram-bot#525]
I live in China, it's too hard to connent to Telegram's API Server because of some reason that as we all know. Can you have some ways to set a proxy for this module? Thanks.

**Comment by jh0ker** [comment]
When you create the `Updater` object, you can pass the following parameters:

`request_kwargs={'proxy_url': '', 'urllib3_proxy_kwargs': {}}`

**Comment by tsnoam** [comment]
@jh0ker You can also use the common https_proxy environment variable.

**Comment by mengyyy** [comment]
as a a example i have a shadowsocksr socks5 127.0.0.1:1080
according 
[urllib3 document](http://urllib3.readthedocs.io/en/latest/advanced-usage.html?highlight=socks)
request_kwargs={'proxy_url': ''socks5://127.0.0.1:1080/''}
more about function [urllib3.contrib.socks.SOCKSProxyManager()](http://urllib3.readthedocs.io/en/latest/reference/urllib3.contrib.html?highlight=SOCKSProxyManager)

**Comment by mengyyy** [comment]
DO NOT USE THE VERSION REALEASED ON **_12 Dec 2016_**   (DO NOT SUPPORT PROXY)
YOU SHOULD INSTALL THIS MODULE BY **_THE LETEST SOURCE CODE_**

**Comment by xmoiduts** [comment]
@mengyyy Thanks, it is of great help. I have tried for several days for the `request_kwargs` argument, only in error information.
The version installed using `pip` doesn't support proxy.

**Comment by HouCoder** [comment]
Code sample:
```py
updater = Updater(token='YOUR_TOKEN', request_kwargs={
    'proxy_url': 'socks5://127.0.0.1:1080/'
})
```

**Comment by mengyyy** [comment]
if you use telegram.Bot to connect your bot
your can use this to config proxy

**import telegram  
[pp = telegram.utils.request.Request(proxy_url='socks5://127.0.0.1:1080')](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/utils/request.py)  
bot = telegram.Bot(token=my_token, request=pp)**  

according [https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/utils/request.py](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/utils/request.py)

you can use https proxy or socks proxy

**Comment by artohidi** [comment]
thank u

**Comment by kmahyyg** [comment]
@mengyyy  @artohidi   The config of ```mengyyy``` noticed me that ``` PySocks requirement is missing. ``` .

I'll open a PR to fix it.

**Comment by tsnoam** [comment]
@kmahyyg 
the dependency is listed in the extras.

**Comment by partyspy** [comment]
@mengyyy 's answer is good. Another way is setting the env variables like
`export https_proxy=socks5://127.0.0.1:1080`
And this telegram module will recognize it

**Comment by carlgonz** [comment]
@partyspy answer worked for me in a RPi running Raspian Jessie. I also installed PySocks with pip.

**Comment by foger** [comment]
My working code for HTTPS SOCKS5 Proxy using authorization (tested in Python2.7):

```
from __future__ import print_function
import telegram


proxy_kwargs = {
    'username': config['proxy_user'],
    'password': config['proxy_password']
}

proxy_url = 'socks5://{0}:{1}'.format(config['proxy_ip'], config['proxy_port'])
proxy_conn = telegram.utils.request.Request(proxy_url=proxy_url, urllib3_proxy_kwargs=proxy_kwargs)

bot = telegram.Bot(token=config['my_token'], request=proxy_conn)
```
**If your SOCKS5 Proxy requires authorization you need to specify urllib3_proxy_kwargs with username and password**
If i using username and pass in proxy_url, e.g. socks5://username:password@ip:port - I get authorization error.
If everything is much easier - let me know how :)))
