### ISSUE TITLE
callback_data and json.dumps results in Bad Request: BUTTON_DATA_INVALID

### ISSUE THREAD

**Issue by Tzaoh** [python-telegram-bot/python-telegram-bot#528]
I am trying to create some buttons inside the conversations, each with its own data but, it seems there is an error when sending the data
```python
btns = [InlineKeyboardButton(
    summoner.name,
    callback_data=json.dumps({'data': {'id': summoner.id, 'name': summoner.name}, 'action': ""})
) for _, summoner in summoners.items()]
```
'Bad Request: BUTTON_DATA_INVALID'

It does not happen if I create the structure like:
```python
btns = [InlineKeyboardButton(
    summoner.name,
    callback_data=json.dumps({'data': {'id': summoner.id, 'name': summoner.name}})
) for _, summoner in summoners.items()]
```

python-telegram-bot 5.3.0
urllib3 1.19.1
certifi 2016.09.26
future 0.16.0
Python 3.5.2

**Comment by bomjacob** [comment]
Is it possible that the data gets longer than 64 bytes in the first version? That's unfortunately the cap that telegram imposes on the callback_data parameter. If you want to have more data associated with the button you'll have to use a database (or a simple dict if you don't need persistency) where you associate for example a UUID with the data. Then you just pass the UUID as the callback_data and look it up when you get a response from the user.

**Comment by Tzaoh** [comment]
You are probably right, that must be the problem. I will check it.
One more question, I couldnt locate any example or snippet of a button who could change the input field of the user, I think is it possible right?
Do you know any example of how the code should be? thanks man

**Comment by jh0ker** [comment]
That would be the `switch_inline_query_current_chat` parameter
