### ISSUE TITLE
AWS Lambda

### ISSUE THREAD

**Issue by revolter** [python-telegram-bot/python-telegram-bot#534]
How can I use this inside a AWS Lambda function?

As far as I can tell, it works as a server, but I need it to run only once.

**Comment by jh0ker** [comment]
You might be able to use `telegram.Bot` (and related classes like `ReplyKeyboardMarkup` etc) to make API requests, but you can probably not use the framework in `telegram.ext`.

**Comment by revolter** [comment]
What is `telegram.ext`?

**Comment by jh0ker** [comment]
It's a multi-threaded bot framework that is part of our library, in addition to the "basic" API implementation.

**Comment by jh0ker** [comment]
Since AWS Lambda is stateless, you can only use it in a limited fashion, if at all. 

If you want to try it, I'd go on about it like this:
- Directly create a `telegram.ext.Dispatcher` instance on every request, ignore `telegram.ext.Updater` completely
- Register your handlers like normal
- Set a webhook to your Lambda function with `bot.setWebhook()` (do this only once, from your PC)
- Use `telegram.Update.de_json(json.loads(request_body.decode()))` to decode every update
- Use the `process_update` method of your `Dispatcher` object to process the decoded update

**Comment by revolter** [comment]
Thanks a bunch for the detailed instructions! I'll close this for now until (if) I have more question.

**Comment by erpheus** [comment]
For anyone wandering around here again here is an excerpt from my lambda function's code:

```
import json
from telegram.ext import Dispatcher
from telegram import Update, Bot
from bot.handlers import set_up


bot = Bot(token=os.getenv('TELEGRAM_TOKEN'))
dispatcher = Dispatcher(bot, None, use_context=True)
set_up(dispatcher)


def lambda_handler(event, context):
    try:
        dispatcher.process_update(
            Update.de_json(json.loads(event["body"]), bot)
        )

    except Exception as e:
        print(e)
        return {"statusCode": 500}

    return {"statusCode": 200}
```

The `set_up` function basically calls `dispatcher.add_handler` as usual with this library.

**Comment by dtphat** [comment]
@ergoz thanks for your solutions 👍

**Comment by dfpoon** [comment]
I am new to this wonderful package. It may sound a nobody question, is 'bot.handlers.set_up' belongs to the python-telegram-bot package? I cannot find it in the documentation. 

> from bot.handlers import set_up

If not, what extra package do I need to install?

**Comment by Bibo-Joshi** [comment]
> The set_up function basically calls dispatcher.add_handler as usual with this library.

The OP propbably has a self-written module `bot`, which implements a specific telegram bot based on PTB, where `bot.handlers` is some sort of collection of Handlers and `bot.handlers.set_up(disptacher)`  runs `dispatcher.add_handler(handler)` for all `handler` objects in `bot.handlers`

**Comment by dfpoon** [comment]
I'm a bit confused. That means the 'bot.handlers.set_up' is a custom
function which is not documented in the official doc, right?

If so, could any guru please rewrite those lines with the out-of-the-box
functions to make a clear template for AWS lambda use cases?

Deploying chat bots to the AWS lambda is cost effective and popular. Please
offer the help. Thx.

在 2020年3月11日週三 15:34，Bibo-Joshi <notifications@github.com> 寫道：

**Comment by Bibo-Joshi** [comment]
> I'm a bit confused. That means the 'bot.handlers.set_up' is a custom function which is not documented in the official doc, right?

yes

> If so, could any guru please rewrite those lines with the out-of-the-box functions to make a clear template for AWS lambda use cases?

```python

handlers = [handler1, handler2, …] # Or some other iterable

...

# "set_up(disptacher) runs dispatcher.add_handler(handler) for all
#  handler objects in bot.handlers" magically becomes:
def setup_handler(dispatcher):
    for handler in handlers:
        dispatcher.add_handler(handler)
```

This is not only for a AWS lambda use case btw but a rather common approach ;)
