### ISSUE TITLE
Cannot remove handler

### ISSUE THREAD

**Issue by ngoctuan001** [python-telegram-bot/python-telegram-bot#541]
Hi everyone ,
Basically , i want to create a easy bot to ask our name and return "Hello 'name' "
So i create 2 function hello and reply.
i create a commandhandler /hello for the hello function to ask the question
and a messagehandler for the reply function to detect the name

**however, i just want the reply function to execute only once , which mean that after it print out "Hello 'name' " , any message from the user will not call the reply function anymore. Anybody have any idea to do this ? Im thinking of adding the remove messagehandler at the end of the reply function but it wont work**

Here is my code:

```
dp= updater.dispatcher

def reply(bot,update):
    text = (update.message.text)
    textupper = text.upper()
    if "I AM" in textupper:
        text = text[5:]
    elif "MY NAME IS" in textupper:
        text = text[10:]
    update.message.reply_text("Hello {}".format(text))


def hello(bot, update):
    update.message.reply_text("What's your name ?")
    dp.add_handler(MessageHandler(Filters.text, reply))
    
dp.add_handler(CommandHandler("hello",hello)) 
```

Telegram:
![image](https://cloud.githubusercontent.com/assets/26194619/23720340/70983bc8-0479-11e7-9de2-0c2ca619a3bf.png)

**Comment by Eldinnie** [comment]
First of all, this is not an issue, and better suited in the discussion group at: https://t.me/pythontelegrambotgroup

and look at:
http://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.dispatcher.html#telegram.ext.dispatcher.Dispatcher.remove_handler

**Comment by jh0ker** [comment]
Besides, it would be better to use a `ConversationHandler` for this purpose, check out https://github.com/python-telegram-bot/python-telegram-bot/tree/master/examples#conversationbotpy
