### ISSUE TITLE
About send  file size 

### ISSUE THREAD

**Issue by mengyyy** [python-telegram-bot/python-telegram-bot#543]
According [telegram bot API about send file](https://core.telegram.org/bots/api#sending-files)
the large file size is 50MB (50\*1024\*1024 bytes)
### Steps to reproduce
1. i have write a test function
```
def send_test_one(size, test_file_name='./test.bin'):
    with open(test_file_name, 'wb') as f:
        f.write(b'1' * size)
    try:
        bot.sendDocument(chat_id=chat_id, document=open(test_file_name, 'rb'))
    except:
        print('failed size {}'.format(size))
    else:
        print('success size {}'.format(size))
```
2. I found the file name length effect the size
`send_test_one(50*1024*1024-297, './test.bin')`
success size 52428503
`send_test_one(50*1024*1024-296, './test.bin')`
failed size 52428504
`send_test_one(50*1024*1024-397, './test1234567890.bin')`
success size 52428493
`send_test_one(50*1024*1024-396, './.test1234567890.bin')`
failed size 52428494

### Configuration
**Operating System: Debian7**

**Version of Python, python-telegram-bot & dependencies:**

``
python-telegram-bot 5.3.0
urllib3 1.20
certifi 2017.01.23
future 0.16.0
Python 3.5.3 (default, Mar  6 2017, 08:52:46)  [GCC 4.9.2]
 ``

**Comment by jh0ker** [comment]
I'm not sure what this is about. Is this a question? Are you asking us to add this to https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/constants.py ?

**Comment by mengyyy** [comment]
just little confuse about sending file size.

**Comment by TwistedPriv** [comment]
If i want to load a file with an  external url ?
