### ISSUE TITLE
python-telegram

### ISSUE THREAD

**Issue by CMGameplay** [python-telegram-bot/python-telegram-bot#544]
### Steps to reproduce
1.

2.

3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by Eldinnie** [comment]
eeeehm. I guess this can be closed @jh0ker

**Comment by jh0ker** [comment]
indeed
