### ISSUE TITLE
Callback fails when bot removed from chat

### ISSUE THREAD

**Issue by Badiboy** [python-telegram-bot/python-telegram-bot#546]
Bot posts the message with inline keyboard to channel.
>     message = "Start!"
>     chatid = 0
>     keys = [[
>         InlineKeyboardButton(
>             "Русский",
>             callback_data='start_ru'),
>         InlineKeyboardButton(
>             "English",
>             callback_data='start_en')
>         ]]
>     keyboard = InlineKeyboardMarkup(keys)
>     bot.sendMessage(
>         chatid,
>         text = message,
>         reply_markup = keyboard)
>     ....
>     updater.dispatcher.add_handler(CallbackQueryHandler(clBot.buttonCallBack))

After bot was removed from the channel when, pressing the inline button drops the bot down with error "OSError: [Errno 22] Invalid argument".
Exception in thread updater:

> Traceback (most recent call last):
>   File "C:\Python3\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\Python3\lib\threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Python3\lib\site-packages\telegram\ext\updater.py", line 115, in _thread_wrapper
>     target(*args, **kwargs)
>   File "C:\Python3\lib\site-packages\telegram\ext\updater.py", line 233, in _start_polling
>     self.last_update_id, timeout=timeout, network_delay=network_delay)
>   File "C:\Python3\lib\site-packages\telegram\bot.py", line 125, in decorator
>     result = func(self, *args, **kwargs)
>   File "C:\Python3\lib\site-packages\telegram\bot.py", line 1248, in getUpdates
>     return [Update.de_json(u, self) for u in result]
>   File "C:\Python3\lib\site-packages\telegram\bot.py", line 1248, in <listcomp>
>     return [Update.de_json(u, self) for u in result]
>   File "C:\Python3\lib\site-packages\telegram\update.py", line 94, in de_json
>     data['callback_query'] = CallbackQuery.de_json(data.get('callback_query'), bot)
>   File "C:\Python3\lib\site-packages\telegram\callbackquery.py", line 64, in de_json
>     data['message'] = Message.de_json(data.get('message'), bot)
>   File "C:\Python3\lib\site-packages\telegram\message.py", line 204, in de_json
>     data['date'] = datetime.fromtimestamp(data['date'])
> OSError: [Errno 22] Invalid argument

### Steps to reproduce
1. Add bot to channel as admin
2. Force bot post the message with inline keyboard
3. Remove bot from channel
4. Press the inline key

### Expected behaviour
Catchable error in CallbackQueryHandler.

### Actual behaviour
Bot crashes and do not react any more with any handlers.

### Configuration
Windows 10
> python-telegram-bot 5.3.0
> urllib3 1.20
> certifi 2017.01.23
> future 0.16.0
> Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]

**Update**.
It happens not in all channels. In most channels/groups bot returns ordinal error "Unauthorized". Will look for details to reproduce...

**Comment by jh0ker** [comment]
Can you try again with latest master? It should be fixed now

**Comment by Badiboy** [comment]
@jh0ker Sorry, for the long answer and thank you for your effort. I tried again but I cannot reproduce this issue any more (I tried **before** update). Alway report correct "Unauthorized"...

**Comment by jh0ker** [comment]
Excellent!
