### ISSUE TITLE
Any way to send a Photo (not share the link)

### ISSUE THREAD

**Issue by msanchezt** [python-telegram-bot/python-telegram-bot#551]
I wanted to send JPG photos through the Telegram Bot. I have reviewed the documentation and the only option I can find is to share a photo by using the URL:

    To post an image file via URL:
    >>> bot.sendPhoto(chat_id=chat_id, photo='https://telegram.org/img/t_logo.png')

My problem is that in my setup, once the photo is taken is uploaded to Amazon S3, so I don't really have any URL of the photo to share.

Any chance I can actually send the photo itself? Instead of having to share the photo URL?

Thanks!

**Comment by jh0ker** [comment]
@msanchezt https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#post-an-image-file-from-disk

**Comment by msanchezt** [comment]
Wow, that was quick! I didn't see that.

Thanks!

**Comment by NotANormalNerd** [comment]
Is there a way to pre-upload a photo, get a file_id and use that in consecutive messages, so we don't have to upload the photo everytime we send a photo to multiple receivers?

**Comment by tsnoam** [comment]
@NotANormalNerd please do not resurrect ancient closed issues.
For usage question you are welcome to join our users group: https://telegram.me/pythontelegrambotgroup
