### ISSUE TITLE
getting time zone data

### ISSUE THREAD

**Issue by 0xck** [python-telegram-bot/python-telegram-bot#554]
Hello.
Is it possible to get current user's time zone data using bot?
If answer is not will you plan to make this feature in future?
Thank you.

**Comment by jh0ker** [comment]
@0xck Jacob B:
This is not possible without asking the user and saving that data. And unfortunately we cannot implement this in the future as this is just a wrapper of telegram's official API, so unless they implement it, we cannot.

**Comment by 0xck** [comment]
A bit sad, but thank you and good luck :)
