### ISSUE TITLE
add reasons description when an Unauthorized exceptions occurs

### ISSUE THREAD

**Issue by 91DarioDev** [python-telegram-bot/python-telegram-bot#558]
Add possibility to know the description of an Unauthorized exceptions.

Botogram (https://botogram.pietroalbini.org/) has the feature and it returns a description of the error well documented here: https://botogram.pietroalbini.org/docs/dev/unavailable-chats/

thanks

**Comment by jh0ker** [comment]
@91DarioDev For reference: https://github.com/pietroalbini/botogram/blob/master/botogram/api.py#L112-L153

**Comment by Eldinnie** [comment]
It seems to me it's enough to pass the error-message so you can handle it in your own code. Working on this

**Comment by 91DarioDev** [comment]
I agree
