### ISSUE TITLE
Possibility to stop to run any other code for that update

### ISSUE THREAD

**Issue by 91DarioDev** [python-telegram-bot/python-telegram-bot#559]
Add the possibilty to stop to run any other code for the processed udpate.

for example we have many handlers in different groups. If the first one (just an example, it could be the second, third ... one too) returns a certain value i would like to be able to stop to execute any other code in the current and in the following groups of handlers.

At the moment a workaroud is to set update.message = None

botogram (https://botogram.pietroalbini.org/) provides this feature using "return True"

**Comment by Eldinnie** [comment]
With the latests release and the introduction of `DispatcherHandlerStop` I think this issue can be closed.
