### ISSUE TITLE
python-telegram-bot callable WSGI

### ISSUE THREAD

**Issue by awkinc** [python-telegram-bot/python-telegram-bot#565]
Hello,
I'm using Phusion Passenger as web application server. To run my web app it needs a callable WSGI (https://www.phusionpassenger.com/library/walkthroughs/start/python.html)

Does python-telegram-bot HTTP Server have any callable WSGI? How can I run it behind Phusion Passenger?

**Comment by jh0ker** [comment]
We are currently using `SimpleHTTPServer` and the likes, which probably doesn't support WSGI. If you want to do this yourself, please read https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks#custom-solution
