### ISSUE TITLE
Command Handler - don't split() the args, shlex.split() them

### ISSUE THREAD

**Issue by pleasantone** [python-telegram-bot/python-telegram-bot#568]
### Steps to reproduce
1. Create a command, allow it to be dispatched with pass_args

2. Feed the command something like this:
```
/mycommand search/history="30 days ago to now"/csv
```
(if there are smart quotes here, ignore them, it's just a Mac bug, I mean ascii quotes)

3. Examine the command logging (basically a pformat of the passed args):

```
2017-04-18 00:20:55 INFO root: args=['search/history="30',
 'days',
 'ago',
 'to',
 'now"/csv']
```

### Desired behaviour

It would be lovely (read: enhancement request) if, instead of just blindly splitting up arguments when we pass them along as args, if, instead, we were to use python's shlex splitter instead.

I really want args[0] to be `search/history=30 days ago to now/csv`

### Actual behaviour

We parse on whitespace, simply using the standard split rules.

### Configuration
**Operating System:**
Debian Stretch
python-telegram-bot 5.3.0
urllib3 1.20
certifi 2017.01.23
future 0.16.0
Python 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]

**Comment by pleasantone** [comment]
handleupdate in CommandHandler can be changed to `shlex.split(message.text)[1:]`

**Comment by Eldinnie** [comment]
I think if you want this you can do this yourself in the handler pretty easily, while for most people standard whitespace splitting is good enough. Special cases for your wishes should be handled in your code, not in the library imo.

**Comment by pleasantone** [comment]
I've done it in my code. It's a question of principle of least astonishment. What's the intuitive  (vs. good enough) behavior, since the whole point is arg parsing for a command?

**Comment by jh0ker** [comment]
@pleasantone I tend to agree with you

**Comment by tsnoam** [comment]
shlex.split() is problematic with non ASCII strings when using py2.7
I removed the "easyfix" label and I'm with @Eldinnie here - if some1 is using py3 and have this special need he can do it easily by himself.
So I suggest closing this one as WONTFIX

**Comment by pleasantone** [comment]
Can the string be converted or is the shlex.split function broken? This is, fundamentally, a parsing bug in this API. Asking other people to code around it, while possible, does not fix the bug.

**Comment by Eldinnie** [comment]
After discussing it, and keeping in mind the trouble with python2 we're closing this issue.
