### ISSUE TITLE
How do I acknowledge that message has been received

### ISSUE THREAD

**Issue by avinassh** [python-telegram-bot/python-telegram-bot#572]
I run the bot in AWS Lambda and I use Webhooks. I learnt that if you don't acknowledge that message has received, then Telegram keeps sending it back. 

So is it possible to acknowledge that message been received using Telegram Bot API?

**Comment by jh0ker** [comment]
@avinassh If your webhook returns the HTTP 200 status code, the update should be acknowledged

**Comment by avinassh** [comment]
Oh great, so I need to respond with 200 from Webhook. 

Thank you!
