### ISSUE TITLE
Validation function

### ISSUE THREAD

**Issue by Carlovan** [python-telegram-bot/python-telegram-bot#584]
It would be useful to have a `validation` parameter similar to `pattern` in the handlers, but which accepts a function and uses it to validate the message.
Otherwise it could be the same parameter `pattern` that checks if its value it's a function (used as validation function) or a string (used like it's now).

**Comment by Eldinnie** [comment]
I think what you're looking for are `filters`
see http://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.filters.html

**Comment by Carlovan** [comment]
Actually I'd like to use it also with other handlers (say `CommandHandler` or `CallbackQueryHandler`).
For example if I save the data inside the callback query data using JSON format it would be useful to decode it and check its values insted of using a regex pattern.

**Comment by bomjacob** [comment]
I've been thinking that maybe we should get rid of the `pattern` argument and the RegexHandler entirely. I think it might be better if they all took a single `filter` arguement instead and we then had a `Regex` or `Pattern` filter that accepts a pattern (a bit like the current MesageEntity filter).
This would require an overhaul that makes Filters with non-Message types, and also changing the signature for a lot of classes, so we should proceed with caution.
This is just my thoughts of cause, would love to hear your input (@jh0ker, yours too :))

**Comment by Eldinnie** [comment]
Callbackqueryhandler already has a pattern argument, and the commandhandler
has the filter argument.

Op vr 28 apr. 2017 om 23:16 schreef Jacob Bom <notifications@github.com>:

**Comment by bomjacob** [comment]
I am well aware, I'm suggesting unifying such that all handles only have a filter argument and none of them have pattern arguments, since that could be done with a filter, and to implement what @Carlovan wants, a filter like functionality is needed for callbackqueryhandler

**Comment by jh0ker** [comment]
@bomjacob Yeah I had been considering this as well

**Comment by Eldinnie** [comment]
@bomjacob I get what you mean. I think it would be hard to implement without breaking backwards compatibility, but it would be nice...

**Comment by Poolitzer** [comment]
guys, I dont think this issue should be open. What he wants is a Filter, and that works for almost all Handlers. We rather need (in order to "close" this issue/the initial idea of op) a filter parameter for all handlers, which we can put in a new issue, right? @python-telegram-bot/maintainers
