### ISSUE TITLE
Problem parsing image

### ISSUE THREAD

**Issue by pattyland** [python-telegram-bot/python-telegram-bot#589]
Hi there,

I have problems parsing a jpg image. I already postet this issue at https://github.com/home-assistant/home-assistant/issues/7413 but I'm not sure wether this a problem of python-telegram-bot parsing the image wrong or hass creating a corrupt image!

Greets, Sören

**Comment by rahiel** [comment]
Could you share an example jpg image that fails to send?

**Comment by pattyland** [comment]
Sure! Should have done this in the first place. I zipped it to be sure that GitHub doesn't tamper with it: [camera.fang.jpg.zip](https://github.com/python-telegram-bot/python-telegram-bot/files/981909/camera.fang.jpg.zip)

**Comment by rahiel** [comment]
I can send the image just fine with `telegram.Bot.send_photo`, so I think the issue is with home-assistant.

**Comment by pattyland** [comment]
@rahiel Could test this again while serving the image from any webserver? It's working fine when I send the image using the file option from Telegram, but not the URL

**Comment by rahiel** [comment]
@pattyland posting your images here: 
![camera fang](https://cloud.githubusercontent.com/assets/6839756/26528267/0df8c88e-43a8-11e7-9e7a-d3820533e437.jpg)

This image hosted by github has the same sha256 hash as the image from your zip, so they're completely the same. I tested with
``` python
bot.send_photo(chat_id=chat_id, photo="https://cloud.githubusercontent.com/assets/6839756/26528267/0df8c88e-43a8-11e7-9e7a-d3820533e437.jpg")
```
and it works.

**Comment by pattyland** [comment]
Thank you again for your help! I'm still searching the cause for this problem :/

**Comment by tsnoam** [comment]
@pattyland 
Please note that when sending a photo using URL you are bound to the behaviour of Telegram servers in regards to identifying that the file type is what it should be. So for example, make sure that the URL contains '.jpg' in the end (if it's a jpeg, obviously).

**Comment by pattyland** [comment]
@tsnoam Thanks for the tip! So the GitHub CDN URL should work, but it's not:
```bash
May 28 11:29:21 jarvis hass[19081]: INFO:homeassistant.core:Bus:Handling <Event call_service[L]: service_data=url=https://cloud.githubusercontent.com/assets/6839756/26528267/0df8c88e-43a8-11e7-9e7a-d3820533e437.jpg, domain=telegram_bot, service=send_photo, service_call_id=1977728880-22>
May 28 11:29:21 jarvis hass[19081]: ERROR:homeassistant.core:Error doing job: Task exception was never retrieved
May 28 11:29:21 jarvis hass[19081]: Traceback (most recent call last):
May 28 11:29:21 jarvis hass[19081]: File "/home/homeassistant/.homeassistant/deps/telegram/inputfile.py", line 83, in __init__
May 28 11:29:21 jarvis hass[19081]: self.mimetype = self.is_image(self.input_file_content)
May 28 11:29:21 jarvis hass[19081]: File "/home/homeassistant/.homeassistant/deps/telegram/inputfile.py", line 164, in is_image
May 28 11:29:21 jarvis hass[19081]: raise TelegramError('Could not parse file content')
May 28 11:29:21 jarvis hass[19081]: telegram.error.TelegramError: Could not parse file content
```
I would suggest it's something more basic from python, something with mimetype detection? I guess something is wrong with this image...

**Comment by tsnoam** [comment]
Hi, i see that you haven't attached all info requested when you initially opened this issue. Specifically please add the output of `python -m telegram`

**Comment by pattyland** [comment]
@tsnoam I added the info!

According to @azogue the problem lays in the mimetype detection of telegram-bot... Did you already fixed [this problem](https://github.com/home-assistant/home-assistant/issues/7413#issuecomment-304523620)? As far as I can see my installed version is already a bit outdated...

**Comment by tsnoam** [comment]
@pattyland 
I suggest you join our telegram group, you can get great support from our community.
https://telegram.me/pythontelegrambotgroup

**Comment by tsnoam** [comment]
Since this is a closed case which looks unrelated to the library, I'm closing this topic for further comments.
