### ISSUE TITLE
Putting jobs with datetime.timedelta delay

### ISSUE THREAD

**Issue by thisfieldmustbefilled** [python-telegram-bot/python-telegram-bot#590]
Hi there!
This ticket is both enhancement request and tiny fix.
The bug is a small typo in jobqueue.py module.
This code on 88 line:
```
        elif isinstance(next_t, datetime.timedelta):
            next_t = next_t.total_second()
```
does not work when dealing with JobQueue.put(Job, datetime.timedelta) as there is a typo in method name. It should be 
` next_t = next_t.total_second`**s**`()`

And talking of JobQueue module in general. There is pretty much a standard in recurring events representation called "rrule", which is represented in Python by dateutil.rrule module, and I think dealing with it will be much better for creating delaying and repeating jobs then dealing with deltas, plain seconds or days representations. What I actually do now is a double-job converting rrules next occurrence to delta and only then passing it to queue each execution time. Moreover, rrules allow to create more complex execution calendars than just repeating by same interval or day. Unfortunately, my skills do not allow me to contribute the code over this idea at the time. I will really appreciate contributors to bring this to life.
Thanks.

**Comment by thisfieldmustbefilled** [comment]
Oh I'm really sorry, just checked current master branch and this was fixed already. But I have 5.3.1 which is latest obtained from PyPI and there the bug is present.
So let it be just a feature request.

**Comment by bartkamphorst** [comment]
👍

**Comment by bomjacob** [comment]
I think rrules would be a great way to schedule jobs in many cases.. I however am hesitant about adding another dependency to the library ([`dateutil`](https://dateutil.readthedocs.io/en/stable/)) for this single purpose... Is there any way we can make it optional?

**Comment by thisfieldmustbefilled** [comment]
@bomjacob it can be derived to separate branch as a variant, but it seems to be even bigger over-engineering. Unfortunately it seems to be nothing for this in standard library. Actually, the only dependency is just a single submodule from dateutil, but it is bundled over and I think can not be extracted due to licensing.

**Comment by tsnoam** [comment]
@thisfieldmustbefilled 
`JobQueue.put()` is a deprecated method.
You can now use `JobQueue.run_once()` or `JobQueue.run_repeating()` both supporting `datetime.timedelta`.
