### ISSUE TITLE
Run tests on Windows

### ISSUE THREAD

**Issue by rahiel** [python-telegram-bot/python-telegram-bot#591]
- [x] Enable/setup [AppVeyor Continuous Integration](https://www.appveyor.com/).
- [x] Add AppVeyor badge to Readme

There's a problem if multiple tests are run concurrently, because they'll fail if they try to use the same webhook/getupdates thing at the same time. So concurrent number of builds should be 1 (or low), and a delay should be used so the Appveyor tests run after Travis is done.

**Comment by Eldinnie** [comment]
Usefull info:
https://packaging.python.org/appveyor/
