### ISSUE TITLE
editMessageText  and editMessageReplyMarkup with reply_markup is not working

### ISSUE THREAD

**Issue by Gurumurthy1905** [python-telegram-bot/python-telegram-bot#593]
### Steps to reproduce
1. Try to send a editMessageText with reply_markp=inline keyboard for callback_query 
2. In the code it seems like reply_markup is not handled in editMessageText / editMessageReplyMarkup

### Expected behaviour
editMessageText  and editMessageReplyMarkup with reply_markup should work

### Actual behaviour
failed to send editmessageText / editMessageReplyMarkup with reply_markup=inlinekeyboard.

### Configuration
Ubuntu

**Version of Python, python-telegram-bot & dependencies:**
python : 2.7.10

### Logs
Insert logs here (if necessary)

**Comment by bomjacob** [comment]
Are you getting any errors or warnings or anything in the log? (remember to set up logging!)

>In the code it seems like reply_markup is not handled in editMessageText / editMessageReplyMarkup

Do you mean your code? If so please show it. Do you mean your code? Cause that doesn't seem to be the case based on our testing...

**Comment by Gurumurthy1905** [comment]
ooops! i m sorry the issue was my code was trying to set unchanged message. hence it was failing to modify the  message (reply_markup).

Now its working fine 
Thank you.

**Comment by qadirsuh** [comment]
@Gurumurthy1905 how did you solve this issue. I am getting this too. what do you mean by _my code was trying to set unchanged message._
I am trying to change my text message and the inline_keyboard buttons upon click of certain message.

**Comment by Gurumurthy1905** [comment]
keyboard = [[InlineKeyboardButton('UnAck', callback_data='1')]]
			reply_markup = InlineKeyboardMarkup(keyboard)
		bot.editMessageReplyMarkup(chat_id=query.message.chat_id, message_id = query.message.message_id, reply_markup=reply_markup)

**Comment by qadirsuh** [comment]
@Gurumurthy1905 thank you for this. I resolved my issue already. 

Do you know any date and time picker widget for telegram bot written in any language preferably in nodeJS.
https://www.google.com/search?q=date+and+time+pickers&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiV4o_e8LjYAhUGKyYKHfBrCCIQ_AUICigB&biw=1920&bih=886#imgrc=_

**Comment by Gurumurthy1905** [comment]
you can check this once: https://github.com/unmonoqueteclea/calendar-telegram

**Comment by qadirsuh** [comment]
already checked. but this shows only calendar. I want to pick date and time. :)
thanks by the way

**Comment by Eldinnie** [comment]
@Gurumurthy1905 and @qadirsuh I'm locking this issue. It's an old one and you're not even talking about the issue anymore.
