### ISSUE TITLE
install from source code found error

### ISSUE THREAD

**Issue by mengyyy** [python-telegram-bot/python-telegram-bot#609]
### Steps to reproduce
1.git clone https://github.com/python-telegram-bot/python-telegram-bot

2.cd python-telegram-bot

3.python3 setup.py install

### Expected behaviour
Successful install

### Actual behaviour
error: package directory 'telegram/vendor/urllib3/urllib3' does not exist

### Configuration
Debian GNU/Linux 8.7 (jessie)

**Version of Python, python-telegram-bot & dependencies:**
python 3.4.2

### Logs
running install
running bdist_egg
running egg_info
creating python_telegram_bot.egg-info
writing python_telegram_bot.egg-info/PKG-INFO
writing requirements to python_telegram_bot.egg-info/requires.txt
writing top-level names to python_telegram_bot.egg-info/top_level.txt
writing dependency_links to python_telegram_bot.egg-info/dependency_links.txt
writing manifest file 'python_telegram_bot.egg-info/SOURCES.txt'
error: package directory 'telegram/vendor/urllib3/urllib3' does not exist

**Comment by bomjacob** [comment]
You need to do a deep clone of the repository

**Comment by Eldinnie** [comment]
To be more specific. your step 1 should be:
`git clone https://github.com/python-telegram-bot/python-telegram-bot --recursive`

this is because we use a submodule for urllib3 that you need to clone too.
in case of your already cloned repo you can run 
`git submodule --init --recursive` inside the working directory

**Comment by tsnoam** [comment]
Reopening. Apparently we need to fix the README

**Comment by Sherlock-Holo** [comment]
if I down the [source code](https://github.com/python-telegram-bot/python-telegram-bot/archive/v6.0.1.tar.gz), urllib3 will not include in the codes

how could i download urllib3 without git submodule

**Comment by Eldinnie** [comment]
@Sherlock-Holo to be simple, you shouldn't the best way to install is using pypi or the method described in the README.

**Comment by Sherlock-Holo** [comment]
@Eldinnie got it
