### ISSUE TITLE
Use requests library if available

### ISSUE THREAD

**Issue by leandrotoledo** [python-telegram-bot/python-telegram-bot#61]
On telegram/utils/request.py implement the option to use requests library if available, if not, fallbacks to urllib.

**Comment by joncasdam** [comment]
+1 for requests, but why not set requests as requirement instead of an option?

**Comment by leandrotoledo** [comment]
@joncasdam, GAE doesn't support requests. In the last survey we noticed we still have people using GAE for their bots.

**Comment by franciscod** [comment]
Is maintaining support for multiple network libraries worth the gains of using requests when available?

**Comment by leandrotoledo** [comment]
@franciscod it does not. Right now i don't really see the goods of having requests, please feel free to reopen if you think I'm wrong, so we can evaluate a migration to this library and give up on GAE.
