### ISSUE TITLE
problem with html chars in message.text using update.message.text_html

### ISSUE THREAD

**Issue by 91DarioDev** [python-telegram-bot/python-telegram-bot#611]
just assume we want to develop an echo bot:

```
def echo(bot, update):
  update.message.reply_text(text=update.message.text_html, parse_mode='HTML')
```

in case the user sent a formatted bold text where the text is: "`<i> hello`" (anything bold)

the text the bot will send is "`<b><i> hello</b>`" and it can't be sent.

it would be perfect to have a way to fix this

**Comment by Eldinnie** [comment]
To clarify this issue.
the text_html and text_markdown atm do not sanitize the message.text.
@jh0ker already thought of a solution.
