### ISSUE TITLE
echobot2.py CommandHandler not working anymore

### ISSUE THREAD

**Issue by dermatty** [python-telegram-bot/python-telegram-bot#615]
When running your example echobot2.py the CommandHandlers

dp.add_handler(CommandHandler("start", start))
dp.add_handler(CommandHandler("help", help))

are without effect. The message sent to the bot is always just echoed, a "Hi!" or "Help!" is never returned.

### Steps to reproduce
1. running echobot2.py, send "start" to bot, it just replies "start", not "Hi!" as intendend 

### Expected behaviour
The CommandHandler should call start function and reply "Hi!"

### Actual behaviour
just echoing, the functions hooked via the command handlers are never called. 

### Configuration
**Operating System:**
Ubuntu 16.04.02

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 5.3.1
urllib3 1.20
certifi 2017.04.17
future 0.16.0
Python 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]

**Comment by Eldinnie** [comment]
In the echobot example the `MessageHandler` is added after the `CommandHandler`s.
Are you sure that you did that in the same way? I can not reproduce this issue if I take the echobot2.py and fill in my token it works as intended.

Just to be sure. A `CommandHandler` only react on a **bot command**. So in this example it would be `/start` or `/help`
