### ISSUE TITLE
Docs: Wrong member name 'user name'

### ISSUE THREAD

**Issue by Endogen** [python-telegram-bot/python-telegram-bot#616]
The [documentation](http://python-telegram-bot.readthedocs.io/en/latest/telegram.user.html?highlight=user) (latest) tells me that if i want to know the username i have to use `user name` which is not correct. The correct value is `username`.

Also: isn't this kind of inconsistent? Why not use `user_name`?

Or am i getting something wrong here?

**Comment by jh0ker** [comment]
@Endogen it just looks like that because of the highlighting. Go to the same page without the highlight (http://python-telegram-bot.readthedocs.io/en/latest/telegram.user.html) and you will see it is just username

**Comment by Endogen** [comment]
-_- thanks for pointing that out!
