### ISSUE TITLE
May 18 changes

### ISSUE THREAD

**Issue by bomjacob** [python-telegram-bot/python-telegram-bot#617]
### Payment:
- [x] New updates: shipping_query and pre_checkout_query
- [x] New message content fields: invoice and successful_payment
- [x] New bot methods: sendInvoice, answerShippingQuery, and answerPreCheckoutQuery
- [x] New button type: pay (new boolean argument for InlineKeyBoardButton)

### Weird rounded video messages
- [x] New bot method: sendVideoNote
- [x] New Message field: video_note
- [x] New ChatActions: record_video_note or upload_video_note
- [x] VideoNote class

### i18n
- [x] New User field: language_code
Note that the documentation uses "may" wording here... we should do some research as to when.

### Admin power???
- [x] Remove warning from delete_message

### Minor stuff
- [x] Rename new_chat_member to new_chat_member**s**
- [x] New fields gif_duration (InlineQueryResultGif) and mpeg4_duration (InlineQueryResultMpeg4Gif)

**Comment by Eldinnie** [comment]
In Minor stuff `new_chat_members` is an array of `User` and not a single one

**Comment by bomjacob** [comment]
@Eldinnie suggested we coordinate the work here so:
I'm doing the piliminary work on payments rn... not sure I'm up for writing tests this time around though...
