### ISSUE TITLE
Split internal code for better maintainability

### ISSUE THREAD

**Issue by bomjacob** [python-telegram-bot/python-telegram-bot#619]
Currently all our `telegram.*` classes are all jumbled up in a single folder, and it's starting to get a bit unwieldy. I propose we split it into a few folders - much like the telegram documentation also does (Inline, Games, Payments).
We can still have everything exported in the `telegram` module (and we _really_ should), so it should be fully backwards compatible provided you've done something like `from telegram import User` or simply `import telegram`, - in fact the only time it wouldn't work is if they've hardcoded the module such as `from  telegram.user import User`, but I've never actually seen anyone do that, so I think we're fine.

**Comment by ratijas** [comment]
actually, looking at PyCharm's automatic imports, here's typical header for a module declaring handlers:

```
from telegram.bot import Bot
from telegram.callbackquery import CallbackQuery
from telegram.ext.callbackqueryhandler import CallbackQueryHandler
from telegram.ext.commandhandler import CommandHandler
from telegram.ext.conversationhandler import ConversationHandler
from telegram.ext.filters import Filters
from telegram.ext.messagehandler import MessageHandler
from telegram.inlinekeyboardbutton import InlineKeyboardButton
from telegram.inlinekeyboardmarkup import InlineKeyboardMarkup
from telegram.message import Message
from telegram.update import Update
from telegram.user import User
```

PS i am not that crazy to manage imports with my bare hands

**Comment by bomjacob** [comment]
I'm not entirely sure I understand what you mean... like at all... What you describe in your comment would never be our intent. That would export the `ext` submodule as part of the main `telegram` which has never been the plan.
Like have a look at [`__init__.py` of the telegram module](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/__init__.py) and the [`__init__.py` of the telegram.ext module](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/__init__.py). They both export exactly however much is needed, so that our users never ever has to know how we store the classes in our internal files. Are you saying you'd __like__ our users to have to write stuff like you're writing in your comment? If so that seems mighty un-userfriendly.
If you're saying that you think we should convert the internal imports of the `__init__.py` modules from relative imports (starting with a `.`) to absolute (starting with `telegram.`) then perhaps you're right.

PS: Wait what? How is that crazy? You've never touched your imports manually..? If the code you show above is how your editor (in this case PyCharm) does imports in your code, then I __strongly__ urge you to have a thorough look through its settings, cause that is definitely __not__ how it should handle imports from our library.
