### ISSUE TITLE
update.message.from?!?!?!

### ISSUE THREAD

**Issue by w0lfic** [python-telegram-bot/python-telegram-bot#620]
okay let me explain by an example:
msg  = {'update_id': 513463644, 'message': {'message_id': 30, 'date': 1495208452, 'chat': {'id': -218696614, 'type': 'group', 'title': 'test', 'username': '', 'first_name': '', 'last_name': '', 'all_members_are_admins': False}, 'text': 'h', 'entities': [], 'photo': [], 'caption': '', 'new_chat_title': '', 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'migrate_to_chat_id': 0, 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'from': {'id': 280735794, 'first_name': '\u202eH-', 'type': '', 'last_name': '', 'username': '*****'}}}

i will get an update in a group like this its bunch of dicts so i should be able to see username for msg['message']['from']['username'] and i can... only when iam doing it manually

when i try update.message['from'] or update['message']['from'] i will get None value can someone explain this to me iam new at this stuff :)

thanks

**Comment by jh0ker** [comment]
`update.message.from_user` will do the trick

**Comment by jh0ker** [comment]
The reason is that `from` is a reserved keyword in Python, so we renamed the attribute in our library.
