### ISSUE TITLE
Not receiving any group messages via MessageHandler

### ISSUE THREAD

**Issue by AlexandreChollet** [python-telegram-bot/python-telegram-bot#626]
Hi, I don't understand this, or is it a normal behaviour ?

### Steps to reproduce
1. Instantiate Update
2. Instantiate dispatcher with Updater
3. Add new MessageHandler and associate function with the Handler
4. The function never logs any message from a group chat

### Expected behaviour
Receive any message by the Telegram Group with the bot in it

### Actual behaviour
Only receiving messages by private channels

### Configuration
Windows 7 64bits

**Version of Python, python-telegram-bot & dependencies:**
Python : 2.7.10
latest dependency versions

**Comment by jh0ker** [comment]
@AlexandreChollet https://core.telegram.org/bots/faq#what-messages-will-my-bot-get

**Comment by AlexandreChollet** [comment]
Oh my god, so sorry, my friend had created the group and the bot was blocked.
Closing the issue.
