### ISSUE TITLE
AttributeError: module 'requests.packages.urllib3.contrib' has no attribute 'appengine'

### ISSUE THREAD

**Issue by Sherlock-Holo** [python-telegram-bot/python-telegram-bot#632]
### Steps to reproduce
1.
run my bot
2.

3.

### Expected behaviour
run it normally

### Actual behaviour
 File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 93, in __init__
    if urllib3.contrib.appengine.is_appengine_sandbox():
AttributeError: module 'requests.packages.urllib3.contrib' has no attribute 'appengine'

### Configuration
**Operating System: Arch Linux

**Version of Python, python-telegram-bot & dependencies: 6.1b

``$ python -m telegram``

### Logs
> Traceback (most recent call last):
  File "./bot.py", line 22, in <module>
    bot = Updater(token=bot_token['token'])
  File "/usr/lib/python3.6/site-packages/telegram/ext/updater.py", line 103, in __init__
    self._request = Request(**request_kwargs)
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 93, in __init__
    if urllib3.contrib.appengine.is_appengine_sandbox():
AttributeError: module 'requests.packages.urllib3.contrib' has no attribute 'appengine'

on my server, python-telegram-bot version is 6.0.1 and it works well

**Comment by Sherlock-Holo** [comment]
i think urllib3 1.21.1 cause this problem because on my server the version of urllib3 is 1.20

**Comment by Sherlock-Holo** [comment]
on my pc is python 3.6.1, server's is python 3.5.3

**Comment by gregsonar** [comment]
Try to update requests module.
`pip3 install requests --upgrade`
This helped me after upgrading to PTB 6.0.1

**Comment by Sherlock-Holo** [comment]
i download from [pypi](https://files.pythonhosted.org/packages/b3/86/0ce63db69006343f3b5f1cc90cf6fee2fc0d1ddf21949bd591daefedeff7/python-telegram-bot-6.0.1.tar.gz)
and i `just python setup.py build`, `python setup.py install --root="$pkgdir" --optimize=1`

this is my [AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-telegram-bot), i think it should be no mistakes

**Comment by Sherlock-Holo** [comment]
@gregsonar if i modify telegram/utils/request.py, add `import request`at the beginning or `import requests` in my file, my bot can run well

**Comment by tsnoam** [comment]
Version 6.0.3 will not show this problem.
If you prefer to install from sources, please follow the instructions on README.rst on the proper way to get the sources.

**Comment by Sherlock-Holo** [comment]
thx, I will update on AUR issue (sorry for my angry words on AUR issue🙈

Noam Meltzer <notifications@github.com>于2017年6月2日周五 02:10写道：

**Comment by tsnoam** [comment]
All forgiven. Just post the apology there as well ;-)
