### ISSUE TITLE
Message.from is not mandatory due to channels

### ISSUE THREAD

**Issue by bomjacob** [python-telegram-bot/python-telegram-bot#637]
Currently it's a required attribute in the Message constructor. We should fix that.

CC: @tsnoam

**Comment by pingiun** [comment]
If `from_user` in the Message constructor is made optional by providing a default of `None`, won't this break people who use the `from_user` argument without keyword?

**Comment by pingiun** [comment]
Can confirm that some tests fail if from_user becomes a positional argument, how can we make it optional but remain compatibility?
