### ISSUE TITLE
ImportError: No module named ptb_urllib3.urllib3

### ISSUE THREAD

**Issue by hajix** [python-telegram-bot/python-telegram-bot#640]
Hi

I installed python-telegram-bot using pip: `sudo pip install python-telegram-bot`

when I import telegram in ipython, I get the following import error:

telegram/utils/request.py:37: UserWarning: python-telegram-bot wasn't properly installed. Please refer to README.rst on how to properly install.
  warnings.warn("python-telegram-bot wasn't properly installed. Please refer to README.rst on "

ImportError                               Traceback (most recent call last)
<ipython-input-1-c0c4e3ab5730> in <module>()
----> 1 import telegram

/home/aj/repo/python-telegram-bot/telegram/__init__.py in <module>()
     87 from .videonote import VideoNote
     88 from .update import Update
---> 89 from .bot import Bot
     90 from .constants import (MAX_MESSAGE_LENGTH, MAX_CAPTION_LENGTH, SUPPORTED_WEBHOOK_PORTS,
     91                         MAX_FILESIZE_DOWNLOAD, MAX_FILESIZE_UPLOAD,

/home/aj/repo/python-telegram-bot/telegram/bot.py in <module>()
     27                       ReplyMarkup, TelegramObject, WebhookInfo, GameHighScore)
     28 from telegram.error import InvalidToken, TelegramError
---> 29 from telegram.utils.request import Request
     30 
     31 logging.getLogger(__name__).addHandler(logging.NullHandler())

/home/aj/repo/python-telegram-bot/telegram/utils/request.py in <module>()
     30 import certifi
     31 try:
---> 32     import telegram.vendor.ptb_urllib3.urllib3 as urllib3
     33     import telegram.vendor.ptb_urllib3.urllib3.contrib.appengine as appengine
     34     from telegram.vendor.ptb_urllib3.urllib3.connection import HTTPConnection

ImportError: No module named ptb_urllib3.urllib3

**Comment by tsnoam** [comment]
Hi, the ptb_urllib3 change is currently only on the master branch and wasn't yet released to pip.
Are you sure that you're using the package from pip and not one you've built yourself or by accident working from a git clone without --recursive (see the README ok how to properly clone)

**Comment by hajix** [comment]
I try to install it using pip: `sudo pip install python-telegram-bot`

Secondly, I clone the git repo and try to install python-telegram-bot from git, but I get the same import error

any help is appreciated...

**Comment by patrnk** [comment]
Where do you clone python-telegram-bot to? The problem might be that `import telegram` statement refers to the python-telegram-bot you've cloned, not piped. See [how import works](https://simpleit.rocks/understanding-how-python-packages-modules-and-imports-work/#module-search-path). The possible remedy is to delete the cloned repository and just use pip.

**Comment by hajix** [comment]
the issue has been solved by: `sudo pip uninstall python-telegram-bot; sudo pip install python-telegram-bo`

thank for helps...
