### ISSUE TITLE
forward_from_message_id & forward_from_chat missing

### ISSUE THREAD

**Issue by pussinboot** [python-telegram-bot/python-telegram-bot#646]
hi,

trying to do something with forwarded messages, the `forward_from` and `forward_date` fields of the `update` object i create are populated but i am missing `forward_from_message_id` and `forward_from_chat`, which I understand are optional fields but they should be included when dealing with a forwarded message?

i've looked at the json object used to create the `update` originally and the corresponding original data are missing from there too so this could be an issue with telegram's own api..

i'm running latest version of everything python 3.6.1 on linux.

**Comment by bomjacob** [comment]
Since this isn't a problem with how our library passes the json, I'm closing this issue.
Note that a likely reason for not having `forward_from_message_id` and `forward_from_chat` is that it might be a inline message, which have none of those.

**Comment by apepenkov** [comment]
I am having the same issue
```
print(update.message.forward_signature)
    print(update.message.forward_from)
    print(update.message.forward_from_chat)
    print(update.message.forward_from_message_id)
    print(update.message.forward_date)
```
returns
```
None
{'id': 908511106, 'first_name': 'TESTPOST', 'is_bot': True, 'username': 'TEPOABOT'}
None
None
2019-08-28 22:42:59
````

for example forward from channel, and forward from group:
```
None
{'id': 234480941, 'first_name': '<[GNU/std::twit]>', 'is_bot': False, 'last_name': '💩', 'username': 'tWiTfAcE'}
None
None
2019-08-29 23:58:08
```
