### ISSUE TITLE
how to set conversation no-operation timeout

### ISSUE THREAD

**Issue by Sherlock-Holo** [python-telegram-bot/python-telegram-bot#648]
### Steps to reproduce
1. use telegram.ext.conversationhandler

2. set run_async_timeout = 90

### Expected behaviour
Tell us what should happen
after 90s, the conversation should be stopped
### Actual behaviour
Tell us what happens instead
after 90s, i still in the conversation and can use command set in conversation states list
### Configuration
**Operating System:**
arch linux arm, PRi 3

**Version of Python, python-telegram-bot & dependencies:**

python 3.6.1 python-telegram-bot 6.0.3

### Logs
Insert logs here (if necessary)

i want to know how to set no-operation timeout but after reading documents, i don't find or i just find `run_async_timeout`

**Comment by jh0ker** [comment]
@Sherlock-Holo There is no such feature.

**Comment by Sherlock-Holo** [comment]
telegram doesn't have API about it？

Jannes Höke <notifications@github.com>于2017年6月6日周二 22:03写道：

**Comment by jh0ker** [comment]
@Sherlock-Holo The conversation handler is not part of the Telegram Bot API. It's a library feature.

**Comment by Sherlock-Holo** [comment]
got it, is there any plan to support no-operation timeout？

Jannes Höke <notifications@github.com>于2017年6月7日周三 00:55写道：

**Comment by Sherlock-Holo** [comment]
i read the tg API documents, message have 'date' field, can we add time check, i mean we can get current time and compare it with message time, if it is longer than timeout which user sets, we can return  a state means timeout and let user define action how to deal it

**Comment by jh0ker** [comment]
@Sherlock-Holo I agree, and we could use the job queue to implement this. That's why I tagged it as enhancement :)

**Comment by Sherlock-Holo** [comment]
oh, I am very happy to hear that😋👍

Jannes Höke <notifications@github.com>于2017年6月7日周三 14:47写道：
