### ISSUE TITLE
import requests gives error 

### ISSUE THREAD

**Issue by Samuel1123** [python-telegram-bot/python-telegram-bot#651]
I've installed using the following commands

```
pip install python-telegram-bot==6.1b0
pip install requests --upgrade
pip install urllib3 --upgrade
```

When I run the follwing 2 line code
```
from telegram.ext import Updater
import requests

```

I get 

```
2017-06-08T14:39:18.555808+00:00 app[process.1]:   File "test_app.py", line 6, in <module>
2017-06-08T14:39:18.555847+00:00 app[process.1]:     import requests
2017-06-08T14:39:18.555871+00:00 app[process.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/requests/__init__.py", line 53, in <module>
2017-06-08T14:39:18.555916+00:00 app[process.1]:     major, minor, patch = urllib3_version
2017-06-08T14:39:18.556018+00:00 app[process.1]: ValueError: need more than 1 value to unpack
```

This issue [4076](https://github.com/requests/requests/issues/4076) on requests suggests that something weird is happening with `telegram.ext`

Is anyone else facing the same issue?

python 2.7.13

**Comment by stejesh** [comment]
Same issue here

**Comment by tsnoam** [comment]
@Samuel1123 Can you please attache your test app?

**Comment by tsnoam** [comment]
@Samuel1123 sorry. I see that you attached it at the top.

**Comment by stejesh** [comment]
@tsnoam as @nateprewitt suggests  [here](https://github.com/requests/requests/issues/4076) this link -> [](https://github.com/python-telegram-bot/python-telegram-bot/blob/ff897ce9ef1e50acd56148de5aaa8226c7de9b03/.gitmodules) seems to be the culprit

**Comment by Eldinnie** [comment]
there's two things that might be able to fix this if you're willing to try.
`pip install python-telegram-bot==6.1b2` (in which we internally renamed the vendored urllib3 ptb_urllib3 to avoid these kind of conflicts)
and/or reverse the imports so `requests` is imported before any of the `telegram` modules.

**Comment by tsnoam** [comment]
@Samuel1123 @stejesh 
Thanks for reporting the bug with our beta version. (same problem is with 6.1b2)
We should release 6.1 soon, and this problem will be fixed there.
For the meantime, you can work with the master branch of our git. (make sure to check the README on how to properly clone).
