### ISSUE TITLE
Payment method not working

### ISSUE THREAD

**Issue by Doomsk** [python-telegram-bot/python-telegram-bot#665]
I've installed the python-telegram-bot library last Wednesday via pip and tried to run the payment.py example. No success. I've got the error:

_from telegram import LabeledPrice, ShippingOption
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/shippingoption.py", line 21, in <module>
    from telegram import TelegramObject, LabeledPrice
ImportError: cannot import name 'LabeledPrice'_

Then I upgraded the library earlier today. No success. Is there an issue to the actual git version and the pip repository? I need to run the application on Heroku, so even if I, let's say, unzip the git version local it won't work anyways for my purposes.

**Comment by Eldinnie** [comment]
The payement stuff is still in our bèta release. To try and use it use
`pip install python-telegram-bot==6.1b2`

**Comment by jeffffc** [comment]
`v6.1b2` only supports payment without shipping options
while `master` now already support full payment methods

**Comment by Doomsk** [comment]
@Eldinnie worked! thank you very much! <br>

@jeffffc wow, I'll test later on for shipping
