### ISSUE TITLE
RegexHandler with Wildcards left and right

### ISSUE THREAD

**Issue by Rostgnom** [python-telegram-bot/python-telegram-bot#669]
[As indicated in the documentation](https://docs.python.org/3.6/howto/regex.html) of the `re`-module, matching strings with wildcards should be performed using the `re.search()` method, as opposed to the "hardcoded" `re.match()` we use in the library.

**Example:**
User has a string "abc" that should be matched using `RegexHandler`, but _anywhere_ in the message text. The user might be tempted to declare it as follows:
`RegexHandler(r'.*abc.*', ...)`

Matching wildcards left or right has implications on performance and should be avoided.

**Possible Solution:**

Make the matching function configurable via argument to `RegexHandler`, e.g. `RegexHandler(r'.*abc.*', ..., use_search=True, use_match=False)`, resulting in `re.search()` being used instead of `re.match()`

**Comment by bomjacob** [comment]
Okay, so I know I'm the one who originally suggested this... But after running a few tests with both complicated and simple regex... it seems like using `re.match()` with `.*` (or even `[\s\S]`) is actually faster than `re.search()`... So I suggest we close this issue :)
