### ISSUE TITLE
[Feature] Add global timeout argument for all network methods

### ISSUE THREAD

**Issue by evgfilim1** [python-telegram-bot/python-telegram-bot#676]
I think it will be useful to add one timeout argument for all network methods

For example, I have slow internet connection and I know that timeout for me should be 20 sec. I put `timeout=20` keyword argument in all send_* calls. But I have big code, so it will take me some minutes to do it. But when I have global timeout argument, I can change one line of code and everything will work as I wanted

**Version of Python, python-telegram-bot & dependencies:**

python-telegram-bot 6.1.0, Python 3.6.1

**Comment by tsnoam** [comment]
@evgfilim1 
I believe that creating a `Request` object and passing it to the `Bot` (or `Updater`) when initializing it should meet you needs. 
What do you think?

**Comment by evgfilim1** [comment]
@tsnoam I think this will help, but it should be documented.
