### ISSUE TITLE
What's job.context?

### ISSUE THREAD

**Issue by giacomocerquone** [python-telegram-bot/python-telegram-bot#700]
Hi everyone. I was stuck at version 3 of this library and now updating I found the whole new job queuing system, great work I'd say but I've a doubt.
I used to store in a db all the chat_id that requested that job in order to send them a message back every "5 minutes" for example.
Now, this is what job.context automatically does? And if yes, which way should I choose and why?

Thank you very much, Giacomo.

**Comment by jh0ker** [comment]
`Job.context` is simply a storage for any data that is related to that job. How you use it is your decision. Keep in mind that jobs are kept in memory and are not persistent (e.g. the context is lost when the bot restarts)

**Comment by giacomocerquone** [comment]
Ok you're right, not being persistent (of course) means that I can't do anything without a DB.
But so I have another question, why isn't it an optional parameter? Right now I'm using pylint and if I don't insert this param (https://github.com/python-telegram-bot/python-telegram-bot/blob/6479e1557873803ad75e939bcf3e3b57522e09ad/examples/timerbot.py#L36) inside my handler the bot returns an error, if I put it I get a warning because it's unused.

**Comment by jh0ker** [comment]
@giacomocerquone I'm sorry, the handler callback does indeed require the argument list of bot, job I'm afraid
