### ISSUE TITLE
how to ignore other bots

### ISSUE THREAD

**Issue by Sherlock-Holo** [python-telegram-bot/python-telegram-bot#706]
6.1.0

I want my bot ignore other bots, because sometimes other bots will activate my bot, it will make us unhappy. So I want to know how to ignore others bots?

**Comment by 91DarioDev** [comment]
As far as I know telegram does not allow bots to see other bots messages

**Comment by matiniamirhossein** [comment]
As mentioned here:
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions

Bots talking to each other could potentially get stuck in unwelcome loops. To avoid this, we decided that bots will not be able to see messages from other bots regardless of mode.

**Comment by Sherlock-Holo** [comment]
oh sorry I forgot this

Amirhossein Matini <notifications@github.com>于2017年7月3日周一 23:49写道：
