### ISSUE TITLE
No parameter "entities" for bot.send_message()

### ISSUE THREAD

**Issue by mathefreak1** [python-telegram-bot/python-telegram-bot#707]
Hello, 

I wanted to include some text mentions to my messages using MessageEntity. But the method bot.send_message doesn't support the parameter "entities", like it should (https://core.telegram.org/bots/api#message). Can you please add this parameter to make MessageEntities possible in python?

Thanks a lot,
Jannik

**Comment by tsnoam** [comment]
@mathefreak1 
Please recheck the documentation. `sendMessage` does not have a parameter called `entitites`.
