### ISSUE TITLE
maximum length of a query

### ISSUE THREAD

**Issue by mostafaasadi** [python-telegram-bot/python-telegram-bot#708]
Hi 
I have a bot that paste long text in beepaste , it can found on [https://github.com/mostafaasadi/bpastebot/](https://github.com/mostafaasadi/bpastebot/)
I tried to add a abilitty to be as inline bot , you can test it on http://t.me/bpaste_bot
Is there any limitation on length of query ? I found out there is maximum 7 line limit , is it true ? 
is there any way to bypass or resolve it ? my bot need to give long long text.
best regards

### Configuration
**Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-77-generic x86_64)**
**python-telegram-bot 6.0.3
urllib3 1.21.1
certifi 2017.04.17
future 0.16.0
Python 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]**

**Comment by thodnev** [comment]
@mostafaasadi The limits are caused by Telegram itself, so there are at least 3 ways to bypass them: 1) divide text into parts and send numerous messages
2) send the "first" part and provide external link to read more
3) use ordinary messages instead of inline ones

For me it seems that 2nd approach is optimal in your case

**Comment by matiniamirhossein** [comment]
@mostafaasadi 
Sample of first option by @thodnev 
`def split_into_messages(message):
    msgs = [message[i:i + 4096] for i in range(0, len(message), 4096)]
    return msgs
msgs = split_into_messages(message)
for text in msgs:
     update.message.reply_text(text=text)`

**Comment by mostafaasadi** [comment]
@matiniamirhossein 
thank you 
I decide to warn users in inline mode for more than 256 character and send it directly 
https://github.com/mostafaasadi/bpastebot/commit/f07a5cc83ea8c5dae6d1fdc9f0a4a332a56146a5
