### ISSUE TITLE
Allow multiple strings for CommandHandler via tuple

### ISSUE THREAD

**Issue by Rostgnom** [python-telegram-bot/python-telegram-bot#710]
I like to use multiple aliases for my bot commands.
For example all of ('favorites', 'favorite', 'fav', 'f') point to my `favorites_handler`.

Could we add tuples (probably rather than lists) as the first argument of `CommandHandler`, making all of its values point to the right handler? This would save 4 `dispatcher.add_handler(blabla)` lines regarding my example.

Is there already a better way?

**Comment by bomjacob** [comment]
`dispatcher.add_handler(CommandHandler(('favorites', 'favorite', 'fav', 'f'), favorites_handler)` should work as-is... Is that not the case?

**Comment by matiniamirhossein** [comment]
Or use RegexHandler

**Comment by Rostgnom** [comment]
@bomjacob You're right. Somehow that didn't work the first time oO
