### ISSUE TITLE
My questions

### ISSUE THREAD

**Issue by MyZik** [python-telegram-bot/python-telegram-bot#712]
Hi everyone!
This is my first experience with Python. And I have some questions.
Previously, I was developing Telegram Bot with PHP (https://github.com/php-telegram-bot/core)

1. Has your library admin functions? For example: send message to all users, send message to user by ID, list all bot users
2. Can I use "branched conversations". For example: I have a 3 buttons "Fruits", "Vegetables", "Other" and if I pick "Other", bot shows me other buttons, etc..

Thanks in advance!

**Comment by Eldinnie** [comment]
This is not an issue with the module. If you need help with regarding programming bots with this library I recommend joining our community chat on [telegram](https://t.me/pythontelegrambotgroup)
