### ISSUE TITLE
[Best Practice] How to create a workflow based on InlineKeyboardMarkup?

### ISSUE THREAD

**Issue by Endogen** [python-telegram-bot/python-telegram-bot#719]
I have a workflow where the user enters a command and then is being asked some questions. The user can answer the questions by pressing one of the preconfigured buttons (like "YES" or "NO" - ReplyKeyboardMarkup).

My issue is, that for some questions the user has to enter a numerical value that i can't put on a button since i don't know the value before hand. I can of course send the question and wait for a reply but how to know that the answer is part of that previously started workflow? With buttons this was easy since i have a callback function for every question and by pressing one of the answers i enter that specific callback function but since i can't have a button for that numerical value, how to know at which point the workflow is at that time?

**Comment by 91DarioDev** [comment]
you can save user status in a database or using chat_data or user_data.
you could also create a keyboard inline like [-10, -5, 1, +1, +5, +10] modified the text of the message and an 'enter' button.
also take a look at conversation handler of the library, it probabily would be the best option for you

**Comment by Endogen** [comment]
Thanks! I will look into `ConversationHandler` a bit more. I already use it but i don't think that i really understood the full potential yet. For other people that want to get a grip: [Link](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/conversationbot.py)
