### ISSUE TITLE
get contact number without key press

### ISSUE THREAD

**Issue by rezaduty** [python-telegram-bot/python-telegram-bot#721]
Hello Thanks for read 

how to get contact phone number without user click KeyboardButton
for example use this code

```contact_keyboard = telegram.KeyboardButton(text="get con", request_contact=True)
location_keyboard = telegram.KeyboardButton(text="get loc", request_location=True)
reply_keyboard = [['a'],
                  [location_keyboard, contact_keyboard],
                  ['x'],
                  ['y']]
markup = ReplyKeyboardMarkup(reply_keyboard, one_time_keyboard=True)
update.message.reply_text(
        "dvssvd"
        reply_markup=markup)
```
OR 

controll message from telegram for request number

```The bot will know your phone number. This can be useful for integration with other services.```

but change this message with my text and ok or cancel button listener

```
ok():
   ....
cancel():
   ....
```
very special thanks

**Comment by bomjacob** [comment]
This is not possible and is not something we can make possible either due to telegram api limitations, sorry.
