### ISSUE TITLE
[Question] Why does the error handler use logger.warning()?

### ISSUE THREAD

**Issue by Endogen** [python-telegram-bot/python-telegram-bot#722]
In [this](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/timerbot.py) example i see that the method that is added to `dp.add_error_handler()` uses `logger.warning()`. Why not use `logger.error()` ?

**Comment by bomjacob** [comment]
No particular reason, other than the fact that an `ERROR` often signifies that the program can't continue (or at least shouldn't. This is not the case with bots however, even if an error accurs you want it to continue running. Note that this is just convention and there's nothing special about `logger.error()` that means it can't/shouldn't be used here, so if that's what you prefer in your code go ahead.
Hope that cleared it up enough for you.
In the future you can ask question and get quicker (and often better) replies in our [telegram support group](https://t.me/pythontelegrambotgroup).

**Comment by Endogen** [comment]
Thanks for the fast reply. Got it
