### ISSUE TITLE
Send PIL photo in Python

### ISSUE THREAD

**Issue by dr0pn3t** [python-telegram-bot/python-telegram-bot#739]
I am trying to send a photo that I made using PIL (pillow) python library.

`bio = BytesIO()`
`bio.name = 'image.png'`
`b.get_crossword_img(bio, True)  # return img.save(filename, 'PNG')`
`bio.seek(0)`
`pic = bio.getvalue()`
`bot.send_photo(cid, pic)`

I have already tried lots of different variants, including `open(bio, 'rb')` instead of getvalue(), StringIO instead of BytesIO, etc... but no of them works. My webhook (Google App Engine) return `ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request`.

I use Python 2.7 and last version of telebot. Also, I should say that other methods are working well, and know I use `resp1 = multipart.post_multipart(BASE_URL + 'sendPhoto', [('chat_id', str(cid))], [('photo', 'image.png', pic)])` to send photos (it works well but it is not convenient and I can't use 'reply_keyboard' with this)

Please, help me with my issue.

**Comment by thodnev** [comment]
Accodring to [’send_photo’ docs](http://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html?highlight=send_photo#telegram.bot.Bot.send_photo) just providing a opened file is not enough. You should use multipart anyway. This is not an issue, but an expected behavior and architectural choice

**Comment by JosXa** [comment]
@dr0pn3t Hi @dr0pn3t,

First of all, this is not the repository for the library you're working with. You should post to the pyTelegramBot page (or their telegram group) instead.

With python-telegram-bot you could just open via the filename without any bytesIO.
