### ISSUE TITLE
The 'latest' version of the readthedocs is empty.

### ISSUE THREAD

**Issue by SitiSchu** [python-telegram-bot/python-telegram-bot#740]
### Steps to reproduce
1. Go to http://python-telegram-bot.readthedocs.io/

2. Click on any of the links  (for example [telegram.ext.updater module](http://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.updater.html)) 

3. See the empty text

### Expected behaviour
There should be a description describing the  function etc.

If I the version is set to 'stable' it works:
 [telegram.ext.updater module](http://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.updater.html)

### Actual behaviour
There is no description at all

Tried with Chrome and Edge

**Comment by bomjacob** [comment]
Should be fixed within the hour. see #728

**Comment by Eldinnie** [comment]
They've just been updated.
