### ISSUE TITLE
No documentation for jobqueue run_repeating etc

### ISSUE THREAD

**Issue by Alwinius** [python-telegram-bot/python-telegram-bot#743]
### Steps to reproduce
1. use job.put as described in the wiki

### Expected behaviour
Documentation for new functions

### Actual behaviour
`/usr/lib/python3.4/site-packages/telegram/ext/jobqueue.py:84: UserWarning: 'JobQueue.put' is being deprecated, use 'JobQueue.run_once', 'JobQueue.run_daily' or 'JobQueue.run_repeating' instead                                                                                                                                                                warnings.warn("'JobQueue.put' is being deprecated, use 'JobQueue.run_once', "`

I tried to update my code to .run_repeating, but there's no documentation at all on how to use these functions. I tried some easy changes (like changing put to run_repeating), but that's not working.

**Comment by Eldinnie** [comment]
Yesterday we put our new docs online. under [JobQueue.put()](http://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.jobqueue.html#telegram.ext.JobQueue.put) you'll find not only the warning it's being deprecated, but also direct links to the suggested methods on the same page. Being:
[run_once](http://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.jobqueue.html#telegram.ext.JobQueue.run_once), [run_daily](http://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.jobqueue.html#telegram.ext.JobQueue.run_daily) or [run_repeating](http://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.jobqueue.html#telegram.ext.JobQueue.run_repeating)

I'm closing the issue, If you have any more questions regarding the working of the methods I suggest you ask the question in our [telegram group](https://t.me/pythontelegrambotgroup).
