### ISSUE TITLE
add effective_attachment to telegram.Message

### ISSUE THREAD

**Issue by Eldinnie** [python-telegram-bot/python-telegram-bot#746]
I suggest adding a property to `telegram.Message` called `effective_attachment`.
It should return the attachment in the Message if any or None.
So for a message with a video it returns the `telegram.Video` object etc.

**Comment by bomjacob** [comment]
Could we name it something else, the word "attachment" isn't used anywhere else in the lib.
Was thinking "effective_media" at first, but I wouldn't really say that e.g. a "Location" a type of media though :/ (do we store it in the media submodule btw?)

**Comment by ihoru** [comment]
I agree on suggested `attachment`. Explanation: Content or file (location, contact, photo, video) was attached to the message. As @bomjacob noticed, it's not always a media or a file.
