### ISSUE TITLE
@message decorator in Bot

### ISSUE THREAD

**Issue by Eldinnie** [python-telegram-bot/python-telegram-bot#752]
In bot.py we have some methods decorated with @message which in turn calles self._message_wrapper.

Is this still needed? Or could we do with just one decorator?

**Comment by bomjacob** [comment]
The code in `Bot._message_wrapper` should be moved to the `@message` decorator.

**Comment by Eldinnie** [comment]
@bomjacob it's not that easy. In that cas @message should be located within the Bot class because _message_wrapper needs a reference to self

**Comment by bomjacob** [comment]
It doesn't need to be no, the decorator gets attributes as if they were passed to the decorated method, therefore the first arguement that the decorator (or the wrapper inside it to be more precise) will indeed be the bots `self` AFAIK
