### ISSUE TITLE
What Can I Use For Listening & Auth

### ISSUE THREAD

**Issue by BTaskaya** [python-telegram-bot/python-telegram-bot#753]
I want just auth with my account and listen all chats if a group / people chat updated it write it in the console basicly its a logger. Is there a any example for it?

**Comment by jh0ker** [comment]
@BTaskaya If you want to auth with your own account, that is not possible using the Bot API. You have to use the actual Telegram API for that. There are projects that do this, for example Telethon (Python) or MadelineProto (PHP). There is also a telegram-cli by vysheng but I don't think that project is still being supported.
