### ISSUE TITLE
Nose is deprecated, move to pytest

### ISSUE THREAD

**Issue by bomjacob** [python-telegram-bot/python-telegram-bot#756]
The Nose project that we're currently using for tests have been "deprecated" for years now. 

> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.
[https://nose.readthedocs.io/en/latest/#note-to-users](https://nose.readthedocs.io/en/latest/#note-to-users)

After debating in dev group, it's been decided to switch to [pytest](https://docs.pytest.org/en/latest/)

# Progress
_(not necessarily in order of importance or chronology)_
- [x] Add pytest to requirements
- [x] Teach travis to use it
- [x] Remove nose and plugins from requirements
- [x] Port travis folding stuff
- [x] Port trivial tests
- [x] Port more advanced tests
- [x] Port test_bot
- [x] Port test_official
- [ ] Refractor test_updater (split into handler tests)
- [ ] Figure out if we're missing any testcases and write them if possible
- [ ] Update contributing guide

# Missing/lacking tests noticed so far
_(documenting here so we hopefully don't forget, just check the of or remove if they turn out be just be elsewhere in the test suite_

- [ ] No send_contact tests
- [ ] Many tests' de_json (and family) tests are only testing a subset of arguments (for example Chat which only checks id, title, type, and all_members_are_administrators)
  - [ ] test_chat
- [x] CallbackQuery
- [x] No tests where fallback of ConversationHandler is used

**Comment by Eldinnie** [comment]
@bomjacob I think this should be a project, not an issue

**Comment by bomjacob** [comment]
I tired making it a project first, but realised that projects on github are honestly quite bad and annoying to use (need to create a lot of issues or a lot of notes, both have their ups an downs)

**Comment by Eldinnie** [comment]
since pytest is merged, closing this
