### ISSUE TITLE
[FeatureRequest] Split too long messages

### ISSUE THREAD

**Issue by sprnza** [python-telegram-bot/python-telegram-bot#768]
Hi there!
Thanks for the project! It's really awesome how it's easy to set up a bot with it!
The only thing I'm missing migrating from php implementation of a bot is a feature that splits outgoing messages automaticaly if it exceeds `MAX_MESSAGE_LENGTH`.

What I currently do is grepping a file line by line and if there is a pattern found I add the line to a variable that's being sent. And sometimes it's exceeds `MAX_MESSAGE_LENGTH` obviously.

Do you have any advice how to send message once variable reaches `MAX_MESSAGE_LENGTH` and then to proceed executing my process of composing text?

**Comment by bomjacob** [comment]
Thank you for the suggestion, we're currently working on a solution (that also takes into account the maximum number of message entity and that takes care to not split in the middle of an entity).

**Comment by sprnza** [comment]
Yay! Cool! Thanks!

**Comment by JosXa** [comment]
```
    def send_message(bot, chat_id, text: str, **kwargs):
        text = text.encode('utf-8').decode('utf-8')
        if len(text) <= constants.MAX_MESSAGE_LENGTH:
            return self.bot.send_message(chat_id, text, **kwargs)

        parts = []
        while len(text) > 0:
            if len(text) > constants.MAX_MESSAGE_LENGTH:
                part = text[:constants.MAX_MESSAGE_LENGTH]
                first_lnbr = part.rfind('\n')
                if first_lnbr != -1:
                    parts.append(part[:first_lnbr])
                    text = text[first_lnbr:]
                else:
                    parts.append(part)
                    text = text[constants.MAX_MESSAGE_LENGTH:]
            else:
                parts.append(text)
                break

        msg = None
        for part in parts:
            msg = bot.send_message(chat_id, part, **self._set_defaults(kwargs))
            time.sleep(1)
        return msg  # return only the last message
```

This is a snippet I used in one of my projects. Perhaps it's of help to anyone

**Comment by JosXa** [comment]
@bomjacob What's the status on this?

**Comment by codewhizz** [comment]
> ```
>     def send_message(bot, chat_id, text: str, **kwargs):
>         if len(text) <= constants.MAX_MESSAGE_LENGTH:
>             return self.bot.send_message(chat_id, text, **kwargs)
> 
>         parts = []
>         while len(text) > 0:
>             if len(text) > constants.MAX_MESSAGE_LENGTH:
>                 part = text[:constants.MAX_MESSAGE_LENGTH]
>                 first_lnbr = part.rfind('\n')
>                 if first_lnbr != -1:
>                     parts.append(part[:first_lnbr])
>                     text = text[first_lnbr:]
>                 else:
>                     parts.append(part)
>                     text = text[constants.MAX_MESSAGE_LENGTH:]
>             else:
>                 parts.append(text)
>                 break
> 
>         msg = None
>         for part in parts:
>             msg = bot.send_message(chat_id, part, **kwargs)
>             time.sleep(1)
>         return msg  # return only the last message
> ```
> This is a snippet I used in one of my projects. Perhaps it's of help to anyone

*while loop* goes into forever looping because `part.rfind('\n') == 0` as '\n' is not removed from text
**Fix:**
Line 12: `text = text[(first_lnbr+1):]`

**Comment by loozhengyuan** [comment]
@jsmnbom Just wanted to check if there's any solution being implemented, else would love to take a stab at this?

**Comment by Bibo-Joshi** [comment]
Closing for the reasons mentioned in #1557

**Comment by RakibFiha** [comment]
Probably its better to send as attachment when the message is too long ?

**Comment by Poolitzer** [comment]
@RakibFiha I personally recommend using telegra.ph for the really long stuff.

**Comment by JosXa** [comment]
> @RakibFiha I personally recommend using telegra.ph for the really long stuff.

That can be automated. Maybe something for contrib ;)
