### ISSUE TITLE
Unable to use promoteChatMember

### ISSUE THREAD

**Issue by PaulSonOfLars** [python-telegram-bot/python-telegram-bot#769]
### Steps to reproduce
1. call bot.promoteChatMember(), from a bot that is admin

### Expected behaviour

The member it is called on should be changed accordingly

### Actual behaviour

Member isnt made admin, or demoted, or restricted in any way - a BadRequest telegram error is raised.

### Configuration
ubuntu 17.04

**Version of Python, python-telegram-bot & dependencies:**
python3.5
sqlalchemy: '1.1.12'

python-telegram-bot 7.0.1
certifi 2017.07.27.1
future 0.16.0
Python 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]

### Logs
```
2017-08-03 22:09:02,217 - telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update.
{'_id_attrs': (<telegram.user.User object at 0x7f91b1777e10>, 'administrator'),
 'can_add_web_page_previews': None,
 'can_be_edited': False,
 'can_change_info': True,
 'can_delete_messages': True,
 'can_edit_messages': None,
 'can_invite_users': True,
 'can_pin_messages': True,
 'can_post_messages': None,
 'can_promote_members': True,
 'can_restrict_members': True,
 'can_send_media_messages': None,
 'can_send_messages': None,
 'can_send_other_messages': None,
 'status': 'administrator',
 'until_date': None,
 'user': <telegram.user.User object at 0x7f91b1777e10>}
BadRequest caught
Chat_admin_required
```
(Added the bot's member dict to show his permissions)

Am I missing something? Bot is as admin as possible on telegram, and I'm pretty convinced the chat_id and user_id are correct (they're from chat.id and user.id, respectively.)

Thanks in advance!

**Comment by bomjacob** [comment]
"Chat_admin_required" means that the bot isn't a chat admin. So there must be a setting you're missing somewhere.

**Comment by Eldinnie** [comment]
@bomjacob I've helped this person in the chat before. We tried anything I could think of, and his printed chat member for the bot shows it should have permissions, maybe it's a problem on tg's side. We should try to reproduce

**Comment by PaulSonOfLars** [comment]
I doubt it's a telegram issue, since running  the following command does indeed promote him, and returns `{"ok":true,"result":true}`

```
curl -i -X GET https://api.telegram.org/bot<KEY>/promoteChatMember\?chat_id\=<CHATID>\&user_id\=<USERID>\&can_change_indo\=True\&can_post_message\=True\&can_deit_message\=True\&can_delete_message\=True\&can_invite_users\=True\&can_restrict_members\=True\&can_pin_messages\=True\&can_promote_members\=True
```
Once I've promoted over curl, I can demote the user using promoteChatMember by setting everything to False (as expected), but I still won't be able to promote them back again after - only option is to use curl again.

**Comment by PaulSonOfLars** [comment]
I guess the errors came from the "None" values for posting and editing in my original log. Closing.

**Comment by kmahyyg** [comment]
I met this issue too, and I use postman for testing this. I ensure all params correct. But still got the error that `RIGHT_FORBIDDEN`

**Comment by daya0576** [comment]
> I met this issue too, and I use postman for testing this. I ensure all params correct. But still got the error that `RIGHT_FORBIDDEN`

got the same issue.
