### ISSUE TITLE
API updates: 8th Oct, 2015

### ISSUE THREAD

**Issue by leandrotoledo** [python-telegram-bot/python-telegram-bot#77]
October 8, 2015
- Added initial channel support for bots (no Telegram clients support this at the moment, please wait for updates):
- The Chat field in the Message is now of the new type Chat.
- You can now pass a channel username (in the format @channelusername) in the place of chat_id in all methods (and instead of from_chat_id in forwardMessage). For this to work, the bot must be an administrator in the channel (and that‘s exactly what Telegram clients don’t support yet — adding bots as administrators coming soon).

https://core.telegram.org/bots/api-changelog

**Comment by leandrotoledo** [comment]
> The Chat field in the Message is now of the new type Chat.

We need to move from ``GroupChat`` and ``User`` to a new ``Chat`` class. https://core.telegram.org/bots/api#chat

> You can now pass a channel username (in the format @channelusername) in the place of chat_id in all methods (and instead of from_chat_id in forwardMessage).

TBC as well.

**Comment by jh0ker** [comment]
#127
