### ISSUE TITLE
Bad Request: failed to get HTTP URL content

### ISSUE THREAD

**Issue by Trabel** [python-telegram-bot/python-telegram-bot#770]
### Steps to reproduce
1. Send correct audio with correct and working url 

2. It gives error 400: Bad Request: failed to get HTTP URL content

### Expected behaviour
I am trying to send audio with url to mp3, and telegram should upload it, becouse the size and type of audio is correct. Example link: http://data3.api.xn--41a.ws/vkp/cs9-5v4.userapi.com/p15/8f89f22d07c1ea.mp3

### Actual behaviour
It gives just error 400: Bad Request: failed to get HTTP URL content and stop uploading file.

### Configuration
**Operating System:**
Windows 10

**Version of Python, python-telegram-bot & dependencies:**
3.6
``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by bomjacob** [comment]
Please execute `python -m telegram` in your terminal and put the result under the "Version of Python, python-telegram-bot & dependencies:"-section, until you do we can't help you :)
Oh and if you could provide the code you're using to send that might help too :)

**Comment by Trabel** [comment]
The fact is that I am using pyTelegramBotAPI library, not yours, and I haven't tried your library to send it yet, but I have tried 3 different libraries and all of them gave me the same error, and to be honest I think library is not the reason  of this, but Telegram limitations. But I have found just limitations by file size and file type, and everything is correct for this. And I am looking for answers for weeks in the web but can't find anything, and support of telegram doesn't answer me, so I understand that it can be not correct place to send thing question, but now I am trying anything I can to resolve the problem, may be you know about limitations of telegram for uploading files by the url?

**Comment by bomjacob** [comment]
Please take this question to our user group at https://t.me/pythontelegrambotgroup

**Comment by Eldinnie** [comment]
@Trabel Usually this means tg has cached the same bad url on their servers. Try to send the file via a link shortener e.g. goo.gl and see if that works

**Comment by Trabel** [comment]
It doesn't work with short url too(
