### ISSUE TITLE
nested loop for inlinekeyboardbottom

### ISSUE THREAD

**Issue by mrmashoufi** [python-telegram-bot/python-telegram-bot#772]
Hi I'm using this API to develop a bot
Right now i want to create a nested loop to send a dictionary of questions and get answers and save the answers and then calculate the result and send the final result

but when i want to create a nested loop to send a message and ask user to answer it through inline keyboard bottom , I can't call next function to send it

this is my code on gist

please help me ;)
https://gist.github.com/mrmashoufi/5e26a6a0eb1ad3fa24e001d0451247fd

**Comment by bomjacob** [comment]
Sorry but we are unable to provide help with bot coding through github. Please join our usergroup at https://t.me/pythontelegrambotgroup and ask there :)
