### ISSUE TITLE
Remove de_json from object that never use them

### ISSUE THREAD

**Issue by Eldinnie** [python-telegram-bot/python-telegram-bot#778]
We have a lot of objects in the library that will only ever be sent, never received. But they still do have a de_json method. I propose to remove all de_json methods from objects that are never sent by tg. Below you'll find a list of the objects involved

- [x] Bot
- [x] ForceReply
- [x] InlineKeyboardButton
- [x] InlineKeyboardMarkup
- [x] InlineQueryResult*
- [x] InlineQueryResultCached*
- [x] InputMessageContent
- [x] Input*MessageContent
- [x] KeyboardButton
- [x] LabeledPrice
- [x] ReplyKeyboardMarkup
- [x] ReplyKeyboardRemove
- [x] ShippingOption

**Comment by bomjacob** [comment]
The only case where this would be bad is if someone is serializing telegram objects as json and then deserializing them afterwards, but I don't believe that should be a usecase we should support since
1) We don't use it in the library internally anywhere
2) Pickle exists

**Comment by Eldinnie** [comment]
@bomjacob it's even worse, de_json doesn't accept json, it works on dicts which is for another issue maybe
