### ISSUE TITLE
ProxyError occurred

### ISSUE THREAD

**Issue by Konsotra** [python-telegram-bot/python-telegram-bot#779]
### Steps to reproduce
1.Installed PyCharm, imported telebot

2.Started with:

import telebot
import const
bot = telebot.TeleBot(const.token)
@bot.message_handler(content_types=['text'])
def handle_text(message):
    if message.text == 'a':
        bot.send_message(message.chat.id, 'Try again!')
bot.polling(none_stop=True, interval=0)

3. Many errors happened 

### Expected behaviour
Bot should sent 'Try again!' on message 'a'.

### Actual behaviour
Several blocks of errors related to proxy.
Somehow one time bot has answered my, even though every single try we errors,

When I am deleting
bot.polling(none_stop=True, interval=0)
there're no errors.

### Configuration
PyCharm, Windows 10, corporate laptop and Internet. The try with personal Internet connection was not succeed.

Python 3.6.1, python-telegram-bot I've downloaded the last week.

### Logs
(util.py:64 PollingThread) ERROR - TeleBot: "ProxyError occurred, args=(MaxRetryError("HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot(token_number)/getUpdates?offset=1&timeout=20 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required ( Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  )',)))",),)
Traceback (most recent call last):
File "C:\Users\nikitivs\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\nikitivs\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 810, in _prepare_proxy
    conn.connect()
  File "C:\Users\nikitivs\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 294, in connect
    self._tunnel()
  File "C:\Users\nikitivs\AppData\Local\Continuum\Anaconda3\lib\http\client.py", line 919, in _tunnel
    message.strip()))
 OSError: Tunnel connection failed: 407 Proxy Authentication Required ( Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  )

**Comment by jh0ker** [comment]
This is the github page for the library `python-telegram-bot` not TeleBot.
