### ISSUE TITLE
How to send message without conversation/chat flow?

### ISSUE THREAD

**Issue by awitherow** [python-telegram-bot/python-telegram-bot#780]
My goal: I want to activate a bot and send a `message` to a `group`. 

Is it possible to to do something like

```python
# bot
bot = telegram.Bot(token)

def send_message(group_id, text):
    bot.send_message(chat_id, text)
```

```python
# logic
from bot import send_message
def do_logic():
    ...
    ....
    ...
    send_message(chat_id=xxx, text="xxx")
```

I cannot find any simple examples like this in the documentation, only complex conversational scenarios.

**Comment by jh0ker** [comment]
@awitherow Yes, that is possible.

**Comment by awitherow** [comment]
Awesome! That is nice @jh0ker . Would it be good to have something like this as an example doc?

**Comment by jh0ker** [comment]
I think it's already appearent that you can do this from the wiki, eg https://github.com/python-telegram-bot/python-telegram-bot/wiki/Introduction-to-the-API and https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets 
Also I'm not really sure why you would need to wrap the `bot` object in it's own module.

**Comment by Serpens66** [comment]
I currently struggle with the same question.
I used the echobot2.py example and have the updater and dispatcher.
This way the telegram bot can only reply, but not send messages on its own. So now I struggle to get the "bot" object to be able to use send_message, without an context or update object.

So what to do now? How do I merge my echobot2 code with a bot?

**Comment by jh0ker** [comment]
@Serpens66 You can use `updater.bot` attribute to make API calls with the same bot object that your updater/dispatcher uses, see [the documentation](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.updater.html#telegram.ext.Updater.bot)
if you have more questions, please ask in our [Telegram group](https://t.me/pythontelegrambotgroup) or open a new issue.
