### ISSUE TITLE
ASCII encoding error when sending ZIP files

### ISSUE THREAD

**Issue by kade-robertson** [python-telegram-bot/python-telegram-bot#782]
### Steps to reproduce
1. Attempt to send a ZIP file with `bot.send_document(chat_id=chat_id, document=open(filename, 'rb'))`

### Expected behaviour
The file should be uploaded to the appropriate chat.

### Actual behaviour
An exception is thrown, seemingly when creating the form data for uploading.

### Configuration
**Operating System:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

**Version of Python, python-telegram-bot & dependencies:**

```
python-telegram-bot 7.0.1
certifi 2017.07.27.1
future 0.16.0
Python 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
```

### Logs
```
Traceback (most recent call last):
  File "/home/kade/telegrambot/lib/command_rom.py", line 37, in _rom
    bot.send_document(chat_id=update.message.chat_id, document=open(filep, 'rb'))
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 57, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 69, in decorator
    return self._message_wrapper(url, data, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 175, in _message_wrapper
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 248, in post
    'POST', url, body=data.to_form(), headers=data.headers, **urlopen_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/files/inputfile.py", line 133, in to_form
    return self._parse(form)
  File "/usr/local/lib/python2.7/dist-packages/telegram/files/inputfile.py", line 147, in _parse
    return '\r\n'.join(form)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbc in position 11: ordinal not in range(128)
```

**Note that I have tried the other solutions from previous issues, however my file name is presumably not the problem as it isn't unicode. This doesn't work with _any_ zip file I try.**

**Comment by bomjacob** [comment]
Thank you for reporting this, we'll be looking into the issue.
(In the meantime maybe you can try it on py3, It should work on there)

**Comment by jh0ker** [comment]
Are you using any method for unicode compatibility, like those offered by the `__future__` module or Django?

**Comment by kade-robertson** [comment]
I'm not doing anything in particular, no. Is there something from the `__future__` module I *should* be using?

**Comment by jh0ker** [comment]
No, I'm asking because it has been a source of similar problems in the past.

**Comment by jh0ker** [comment]
IIRC what used to help in those cases was to modify the call like this:
`bot.send_document(chat_id, document=open(str(filename), 'rb'))`
Could you check if that makes a difference?

**Comment by kade-robertson** [comment]
Just tried, doesn't seem to make a difference.

I tested switching to Python 3, seemed to fix the uploading problem. However some of the files take longer than the 5-second SSL timeout I seem to be seeing in the logs, how can I increase this? The `read_latency` parameter for the `Updater` doesn't seem to affect this timeout.

**Comment by kade-robertson** [comment]
Well I think I solved the issue on Python2. I changed how I was forming the file path and that seems to have worked. However, the timeout issue is still occuring here:
```
Traceback (most recent call last):
  File "/home/kade/telegrambot/lib/command_rom.py", line 37, in _rom
    bot.send_document(chat_id=update.message.chat_id, document=open(str(filep), 'rb'))
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 57, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 69, in decorator
    return self._message_wrapper(url, data, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 175, in _message_wrapper
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 248, in post
    'POST', url, body=data.to_form(), headers=data.headers, **urlopen_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 176, in _request_wrapper
    raise TimedOut()
TimedOut: Timed out
```

**Comment by bomjacob** [comment]
Could it be that the file you're uploading is big?
You could try increasing the timeout by doing `bot.send_document(chat_id=update.message.chat_id, document=open(str(filep), 'rb'), timeout=20)`

**Comment by kade-robertson** [comment]
Ah, I didn't see `timeout` as an option there, I only saw it as part of `Updater.start_polling()`. I'll test that.
