### ISSUE TITLE
Remove deprecated MessageHandler.allow_edited

### ISSUE THREAD

**Issue by tsnoam** [python-telegram-bot/python-telegram-bot#794]

**Comment by Eldinnie** [comment]
As mentioned before (and now mentioning here lest we forget).
1) this should also inlcude removing it from RegexHandler
2) I think (not able to look at code now) that both those handlers atm never handle updates with `edited_channel_post`. I guess we/I should fix that

**Comment by tsnoam** [comment]
This will be handled during the Handlers refactoring.
