### ISSUE TITLE
Pass a variable between states of a conversation.

### ISSUE THREAD

**Issue by sprnza** [python-telegram-bot/python-telegram-bot#803]
Hi there!
Is there a way to pass a variable to the next step of a conversation. I gather data from users and add it to a mysql db. So currently I need to query the database on every step. But I'm thinking of querying it once at the last step. Sorry for maybe lame question.

**Comment by Eldinnie** [comment]
Hi,
This is not an issue with the bot's code, but a usage question. For those please ask again in our [telegram group](https://t.me/pythontelegrambotgroup).
