### ISSUE TITLE
de_json() error "__init__() takes at least 2 arguments (10 given)"

### ISSUE THREAD

**Issue by tinamorale** [python-telegram-bot/python-telegram-bot#804]
### Steps to reproduce
    def webhook():
        # retrieve the message in JSON and then transform it to Telegram object
        text = request.get_json(force=True)
        update = telegram.update.Update.de_json(text, bot)

        chat_id = update.message.chat.id
        text = update.message.text.encode('utf-8')

        manager.bot.sendMessage(chat_id=chat_id, text=text)

        logger.info("Update received! " + update.message.text)
        update_queue.put(update)
        return "OK"

### Expected behaviour
Return an object without an error

### Actual behaviour
I get an error `"__init__() takes at least 2 arguments (10 given)"`

<img width="999" alt="screen shot 2017-08-21 at 15 43 40" src="https://user-images.githubusercontent.com/26300276/29519540-7ed178b4-8686-11e7-921f-f74932fb0515.png">

### Configuration

**Version of Python, python-telegram-bot & dependencies:**
``$ python -m telegram``

    python-telegram-bot 7.0.1
    certifi 2017.07.27.1
    future 0.16.0
    Python 2.7.10 (default, Feb  7 2017, 00:08:15)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

**Comment by Eldinnie** [comment]
Can you show a `print ` for the `text` argument?
I'm suspecting it's a `telegram.Message` object instead of a `telegram.Update`

**Comment by Eldinnie** [comment]
The json you post is not an incomming telegram update. I don;t know where it cmoes from, or how you;re webhook() method is called, but I guess you should look for the root of your problem there.

**Comment by Eldinnie** [comment]
@tinamorale is this issue resolved yet? If not, please respond. I will close the issue in two days if you don't.

**Comment by tinamorale** [comment]
@Eldinnie Thanks. The problem was with my Nginx configurations.
