### ISSUE TITLE
Passing dispatcher to MessageHandler

### ISSUE THREAD

**Issue by matiniamirhossein** [python-telegram-bot/python-telegram-bot#805]
Hello
Is there anyway to pass the dispatcher to message handler?

**Comment by jh0ker** [comment]
@matiniamirhossein use a closure or lambda for that

**Comment by matiniamirhossein** [comment]
@jh0ker Thanks you.
`dp = updater.dispatcher
dp.add_handler(MessageHandler(Filters.all, lambda bot, update: update_handler(bot, update, dp)))`
