### ISSUE TITLE
Bot does not response after running for some time or deleting conversation

### ISSUE THREAD

**Issue by aminalaee** [python-telegram-bot/python-telegram-bot#811]
### Steps to reproduce
1.
    I've used the sample conversationbot2.py from [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/conversationbot2.py) 
2.
    I tried my first bot and relized this issue, then checked with the repo's sample and there it is again.
3.
    When I talk for the first time to bot it's working fine, when I delete conversation and start chatting again /start does nothing. I don't know anything about python-telegram-bot but one thing I noticed is the first time it's logging selecting conversation (132, 12313) with state None  and it works fine but after that selecting conversation (109384554, 109384554) with state 0 and it doesn't reply. After restarting the service it's working again. You can test the bot online.

### Expected behaviour
It should show KeayboardMarkup again.

### Actual behaviour
It does nothing.

### Configuration
**Operating System:**
Ubuntu 16.04

**Version of Python, python-telegram-bot & dependencies:**

python-telegram-bot 7.0.1
certifi 2017.07.27.1
future 0.16.0
Python 3.4.3 (default, Nov 17 2016, 01:08:31)  [GCC 4.8.4]

### Logs
Insert logs here (if necessary)

https://pastebin.com/raw/nxPjNEVx

**Comment by Eldinnie** [comment]
What do you mean with `deleting the conversation`?

**Comment by aminalaee** [comment]
@Eldinnie I mean after starting the chat with the bot, I hold on it and select "Delete and stop" option. You can try it it's online by the name NiknamGalleyBot.

**Comment by Eldinnie** [comment]
I'm sorry but you need to explain further what this deleting does. I just ran the conversationbot2.py example and everything works as expected. Even after letting it idle mid-conversation for 2 hours and picking it up again, the bot does exactly what it needs to do.

**Comment by jeffffc** [comment]
I think you meant it is stuck in a state that you cannot `/start` again? You have to mark `allow_reentry=True` in the handler so as to make the entry points listen to your commands even within a state.

**Comment by aminalaee** [comment]
Thank you guys. What @jeffffc suggested was exactly what I was looking for.
@Eldinnie @jeffffc
