### ISSUE TITLE
Is inlineQuery's answers paging working?

### ISSUE THREAD

**Issue by tenuki** [python-telegram-bot/python-telegram-bot#812]
### Steps to reproduce
1. have this code: 

          LEN = 50
          try:
                    base = int(query.offset)
          except:
                    base = 0
          total = len(full_results)
          results = full_results[base:base+LEN]
          more = total>base+LEN
          logger.warning("%s %s results size: %d base: %d more: %r"%( query.id, query.query, len(full_results), base, more))

          if more:
                    update.inline_query.answer(results, cache_time=CACHE_TIME,  next_offset=str(base+LEN))
          else:
                    update.inline_query.answer(results, cache_time=CACHE_TIME)

2.  full_results has about 190 answers.

3. server queries for first 50s but never for more...

### Expected behaviour

I think, if haven't misunderstood, server should query for more answers after finding next_offset value in answer.

### Actual behaviour

Server doesn't.  

### Configuration
Debian stable.

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 7.0.1
certifi 2017.07.27.1
future 0.16.0
Python 2.7.13 (default, Jan 19 2017, 14:48:08)  [GCC 6.3.0 20170118]

I mean.. maybe it's a problem on the server or in how I'm using the API..  I'm sorry if it's my problem but don't know where to look at! Thanks!

**Comment by Eldinnie** [comment]
As far as I know, the server only requests the next answers as the user scrolls down to the end of the list. Is this what you meant?

**Comment by tenuki** [comment]
@Eldinnie yes.. I'm actually scrolling the list to the end.. but no further request is made to get answers from next_offset on..

**Comment by tenuki** [comment]
My bad. It is working! What doesn't supports longer answer list is the telegram web client.. :-(

**Comment by Eldinnie** [comment]
Ok thanks for reporting back on this.
