### ISSUE TITLE
chat history 

### ISSUE THREAD

**Issue by shayan3985** [python-telegram-bot/python-telegram-bot#813]
is there anyway to fetch all existed message in a chat ?
i searched a lot but logically it must be in `telegram.Chat`

**Comment by Eldinnie** [comment]
Hi,

Since this is a usage question, and not an issue with the bot I would like to point you to our [telegram group](https://t.me/pythontelegrambotgroup), to ask the question again. So we can keep the issues section for problems with the libraries behavior and code.

**Comment by shayan3985** [comment]
i 'm not expert but that telegram group you've mentioned is no longer existed
please provide me with another id :)

**Comment by tsnoam** [comment]
@shayan3985 It is not possible to access public supergroups or something from Iran and some other countries. Only telegram support knows why.
For usage instructions please refer to the documentation.
