### ISSUE TITLE
Reply doesn't quote the original message

### ISSUE THREAD

**Issue by flyingrub** [python-telegram-bot/python-telegram-bot#814]
### Steps to reproduce
1. use reply_* api

### Expected behaviour
The original message should be quoted.

### Actual behaviour
The response is sent as is without being considered as a reply by telegram.

**Comment by Eldinnie** [comment]
@flyingrub HI,

Do you mean this is not working when using the quote argument? Or not at all?

**Comment by flyingrub** [comment]
I didn't know there was a quote argument and expected the reply to quote by
default. Why isn't it the case ?

**Comment by Eldinnie** [comment]
I suggest you read the documentation. It explains what it defaults to in different chat types.
http://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html?#telegram.Message.reply_text
