### ISSUE TITLE
webhookInfo error message

### ISSUE THREAD

**Issue by leavesster** [python-telegram-bot/python-telegram-bot#821]
### Steps to reproduce
1. just run bot for a long time (10 hours+)

### Expected behaviour
bot reply my command and webhookInfo should return no error message

### Actual behaviour
bot does not reply my command and webhookInfo shows some error message

```
{"ok":true,"result":{"url":"https://ip:443/token","has_custom_certificate":true,"pending_update_count":2,"last_error_date":1505000009,"last_error_message":"Write timeout expired","max_connections":40}}
```
error message：
**"pending_update_count":2,"last_error_date":1505000009,"last_error_message":"Write timeout expired"**

### Configuration
**Operating System:**
Linux version 4.4.0-87-generic (buildd@lcy01-31) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) 
a vps on vultr New Jersey ($2.5/month)

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
python-telegram-bot 7.0.1
certifi 2017.07.27.1
future 0.16.0
Python 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]
### Others
I search the `last_error_message Write timeout expired` on Google. It seems no correspond information.
I actually don't know where this error happen. It said Write timeout, but I search these world and couldn't find these words. 
Maybe it reported by other dependencies, or this is Telegram error?
But it seems no one encountered it.

**Comment by leavesster** [comment]
Version of Python, python-telegram-bot & dependencies:

python-telegram-bot 8.0
certifi 2017.07.27.1
future 0.16.0
Python 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]

this also happened

**Comment by Eldinnie** [comment]
Hi,

As far as I can find any information it's mainly directed towards custom self-signing ssl certificates. Telegram just accepts, but never checks them. Can you try again without ssl or with a new/working certificate?

**Comment by leavesster** [comment]
Thank you~
I generate the SSL certificate from [python-telegram-bot wiki-Webhooks](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks).
`openssl req -newkey rsa:2048 -sha256 -nodes -keyout private.key -x509 -days 3650 -out cert.pem`
It's quite strange that it works fine at first , only error after run a long time.
Maybe I should back to use polling ...

**Comment by Eldinnie** [comment]
@leavesster the error seems to indicate telegram servers are unable to deliver the messages to your webserver. This could be due to ssl certificate or have another root. If it works at the start but stops working later on. SSL is probably not the problem.

**Comment by leavesster** [comment]
Yeah. It work fine at first 4~6 hours, maybe less, but actually work for a long time. That confuses me.
I just test it, I restart the bot server 1 hours ago (a temporarily workaround to this problem ——restart bot every 4 hours by crontab ). It still work now. 

Maybe the webserver occurs error ？

**Comment by leavesster** [comment]
I return to use polling. It has been working on for 4 days  and no error occurs.
I think polling is enough for my situation.
Thank you~

**Comment by vasinkd** [comment]
I have 100% the same situation! Bot is working fine for about 5 or 6 hours but after a while stops responding to my commands. Only restart helps. 

getWebhookInfo returned:
```{'ok': True, 'result': {'url': my_webhook_addr, 'has_custom_certificate': True, 'pending_update_count': 14, 'last_error_date': 1534568434, 'last_error_message': 'Write timeout expired', 'max_connections': 40}}```

Ubuntu 16.04., ptb 10.1.0, hosting: DigitalOcean.

Also I noticed that on my second server which I use for testing where is no problem like that (maybe because it has different settings or maybe because it has less running processes). I keep digging.
