### ISSUE TITLE
return the type of a message

### ISSUE THREAD

**Issue by 91DarioDev** [python-telegram-bot/python-telegram-bot#824]
add a feature to return the type of a message in `update.effective_message.type`

for example:
`print(update.effective_message.type`)
and it could print: 'text', 'photo', 'video', 'document' ...

**Comment by JosXa** [comment]
I think this would be a nice utility to have as opposed to all the conditional statements you'd need to write in order to get the type of a message.

**Comment by Eldinnie** [comment]
As I remarked in the group I will also respond here:

I'm not really seeing the added benefit yet. Instead of testing
`if update.effective_message.photo:`
You go to:
`if update.effective_message.effective_type == 'photo':`
How is that an improvement?

**Comment by JosXa** [comment]
@Eldinnie That's not what @91DarioDev was proposing. `update.effective_message.type` would immediately return the type of message (attachment or 'text') as a **string**. So it could return _one of_ `('audio', 'game', 'document', 'photo', 'sticker', 'video', 'voice', 'video_note', 'contact', 'location', 'venue', 'invoice', 'successful_payment', 'text')`.

**Comment by Eldinnie** [comment]
@JosXa I understand that, but I'm asking what the added benefit for that is.

**Comment by Eldinnie** [comment]
To recap some stuff said in the chat. This could be beneficial for logging or DB purposes. Probably best place would be as a helper method in `telegram.utils.helpers`

**Comment by 91DarioDev** [comment]
yes my use case would be to log the type of any message in a group (along with other stuff) and you will be able to query what type of messages are sent more in a group for stats goal

**Comment by JosXa** [comment]
I've implemented an initial version in #826.

**Comment by JosXa** [comment]
Ready to merge.
