### ISSUE TITLE
Cannot change ConversationHandler state in CallbackQueryHandler

### ISSUE THREAD

**Issue by Kazauwa** [python-telegram-bot/python-telegram-bot#825]
### Steps to reproduce
1. Initialize ConversationHandler

2. Add handler which sends user a message with InlineKeyboard

3. Add CallbackQueryHandler which changes state using `return STATE_NAME`

### Expected behaviour
ConversationHandler state is changed

### Actual behaviour
It does not changes. Bot remains in previous state as if there wasn't `return STATE_NAME` at all.

### Configuration
**Operating System:**
Linux Mint 17.3 Rosa

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 6.1.0
urllib3 1.21.1
certifi 2017.04.17
future 0.16.0
Python 3.6.1 (default, Apr 29 2017, 14:51:44)  [GCC 4.8.4]

### Logs
I have noticed that when you enter a new state, logger prints this
```
DEBUG:telegram.ext.conversationhandler:selecting conversation (173131264,) with state WEATHER_BY_CITY
```
However, when trying to change state in CallbackQueryHandler, this line does not appear

**Comment by Eldinnie** [comment]
Hi,

Two points.
1. We only support or latest release version of the library. From your issue I see you;re working with ptb 6.1.0, our latest release is 8.0 please try again with the latest release.
2. If the problem remains would you mind adding a minimal working example to reproduce this problem? So we can see if the error is in the code, or actually with the library.

Thanks

**Comment by Kazauwa** [comment]
Silly me! In my code, I was calling CallbackQueryHandler outside of ConversationHandler, and trying to change state there. Been trying to find this bug for days. I am very sorry for inconvenience, this has nothing to do with wrapper. Minimal working example has proved me wrong
Thank you very much for very quick reponse

**Comment by Eldinnie** [comment]
No problem, glad to be of service :D
