### ISSUE TITLE
Support for CommandHandler in Channels

### ISSUE THREAD

**Issue by peterstory** [python-telegram-bot/python-telegram-bot#831]
Currently, `CommandHandler` only works in `Message`s. However, it would be very useful to support commands in channels as well. It should be easy to make this change: simply checking `Update.effective_message` instead of `Update.message`. 

https://github.com/python-telegram-bot/python-telegram-bot/blob/e0184455133677e54bf3db321256e1b3193208f8/telegram/ext/commandhandler.py#L132-L136

**Comment by Eldinnie** [comment]
Hi,
My personal opinion is that commands for bots are for private and/or group chats where people can actually interact with the bot. I think that if you want to make a bot do something in a channel it should either be done programmatically, or in pm with the bot.
If you really want this you could use `MessageHandler(Filters.command, callback)` right now, and I'll await the opinion of others to see if we should change this.

**Comment by peterstory** [comment]
Cool, thanks for that workaround! 

In my opinion, the strongest argument for supporting CommandHandler in channels is that *not* allowing commands in channels violates the [Principal of Least Astonishment](http://wiki.c2.com/?PrincipleOfLeastAstonishment). My implicit assumption was that the handler would work for channels, because so many other parts of the library work properly agnostic of private message/group message/channel.

**Comment by bomjacob** [comment]
I personally don't really see why we _shouldn't_ be supporting commands in channels? Like it should be up to the dev imo, and we might as well facilitate that. So +1 for this issue :)

**Comment by tsnoam** [comment]
I'm with @Eldinnie on this one. CommandHandler makes no sense in a Channel due to the lack of ability to interact. Channels are supposed to be used for one way notifications.
