### ISSUE TITLE
how to get chat_id and message_id for group

### ISSUE THREAD

**Issue by omidnw** [python-telegram-bot/python-telegram-bot#837]
Hi
How to get chat_id and message_id for group in use the delete_message

example code lua : 
local function cleanmsg (arg,data)
for k,v in pairs(data.messages_) do
tg.deleteMessages(v.chat_id_,{[0] = v.id_})
end
end
local function run(msg, matches)
    if matches[1] == 'del' and is_owner(msg) then
    if msg.chat_id_:match("^-100") then
       if is_owner(msg) then
          if tonumber(matches[2]) > 100 or tonumber(matches[2]) < 1 then
             pm = '_ 100> ok >1 _'
             tg.sendMessage(msg.chat_id_, data.msg.id_, 1, 'clear', 1, 'html')
             else
          tdcli_function ({
    ID = "GetChatHistory",
    chat_id_ = msg.chat_id_,
    from_message_id_ = 0,
    offset_ = 0,
    limit_ = tonumber(matches[2])
  }, cleanmsg, nil)
             tg.sendMessage(msg.chat_id_, msg.id_, 1, '<b>clear chat </b> ['..matches[2]..']', 1, 'html')
         end
end
end
end
end
return {
    patterns = {
        '^[!#/]([Dd][Ee][Ll]) (%d*)$'
    },
    run = run
}

/////
Top code for use delete all message from group

But in code for use project python telegram bot

Please Help Thank

And Sorry for Bad Grammar

I'm bad english

**Comment by JosXa** [comment]
To be blunt, why do you expect us Python guys to be able to help you with your Lua problem?

Here is your homebase: https://github.com/cosmonawt/lua-telegram-bot

**Comment by omidnw** [comment]
no use lua

The code was for example, so know what I want

I want the equivalent of this code for the same plugin

I said that very English is not good

sorry :D

**Comment by Eldinnie** [comment]
@JosXa What he asks is how to make this code in python-telegram-bot. However this is not an issue, but a usage question.
@omidnw I suggest you visit our [telegram group](https://t.me/pythontelegrambotgroup) to ask your question. There is bound to be someone able to help you. even likely in your own language.
