### ISSUE TITLE
sending bigger file than 50mb

### ISSUE THREAD

**Issue by raaaas** [python-telegram-bot/python-telegram-bot#841]
hello,

recently telegram allowed user to send up to 1gb file but still this program send only 50mb limit, how can i send bigger file ?

**Comment by Eldinnie** [comment]
According to this: https://core.telegram.org/bots/api#sending-files
bot's still have the same limitations as before. Can you point to a source that this is changed?
Anyway we're not limiting users with the library. The limit is given and regulated by telegram's server. We simply pass you the message.

**Comment by raaaas** [comment]
im useing a bot which send file in any size but my bot wont send it, 
 the bot is @utubebot and can download all size of youtube videos

**Comment by Eldinnie** [comment]
They might either be using a userbot or some other way to bypass telegram's limitations. I'm closing the issue.
