### ISSUE TITLE
bot not seeing other bots messages

### ISSUE THREAD

**Issue by rjuni0r** [python-telegram-bot/python-telegram-bot#842]
i´m using python telegram 8 and my bot is not seeing other bots messages.
is there any Filter that i have to use to see other bot messages? i am just using Filter.text

it´s ok with people messages that aren't bot

    updater = Updater(bot_token)
    dp = updater.dispatcher

    dp.add_handler(MessageHandler(Filters.text,check_messages))

.

**Comment by JosXa** [comment]
@rjuni0r Bots cannot communicate with other bots, but there are the following exceptions:
- Channel messages can be read by each other
- Userbots are capable of everything a tg user is

If the channel approach makes sense for you, try Filters.channel_post in conjunction with update.channel_post.message.
