### ISSUE TITLE
"Wrong persistent file_id specified: wrong string length" when send PhotoSize to user

### ISSUE THREAD

**Issue by vartagg** [python-telegram-bot/python-telegram-bot#847]
### Steps to reproduce
1. Handle Photo sending by user to your bot and save all of `PhotoSize` data anywhere

2. Then send any of these photo-sizes by its `file_id`  like `update.effective_message.reply_photo(update.effective_user.id, saved_photo_size_file_id)` from your bot to user

### Expected behaviour
Photo should be sent from bot to user

### Actual behaviour
Error from Telegram API: "Wrong persistent file_id specified: wrong string length"

### Configuration
**Operating System:**
macOS Sierra

**Version of Python, python-telegram-bot & dependencies:**
```
python-telegram-bot 8.0
certifi 2017.07.27.1
future 0.16.0
Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13)  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

I found that Telegram bot API don't allow to resend thumbnails (PhotoSize): https://core.telegram.org/bots/api#sending-files 

> Sending by file_id
> 
> It is not possible to change the file type when resending by file_id. I.e. a video can't be sent as a photo, a photo can't be sent as a document, etc.
> **It is not possible to resend thumbnails**
> Resending a photo by file_id will send all of its sizes.
> file_id is unique for each individual bot and can't be transferred from one bot to another.

**But** `effective_attachment` of message sending by user has only list of `PhotoSize` and don't storing `file_id` of original Photo.

So how to extract `file_id` of original Photo for resend this in future?

**Comment by jh0ker** [comment]
@vartagg I think you are using the reply_photo method wrong, because why are you passing the user ID in there?

**Comment by Eldinnie** [comment]
It's like @jh0ker said. you're passing the users id as a file_id to the bot. telegram rejects it for obvious reasons

**Comment by vartagg** [comment]
@jh0ker @Eldinnie That's it, thank you! Sending image to user by `PhotoSize`'s `file_id` is working, probably telegram developers meant something else when say "It is not possible to resend thumbnails"
