### ISSUE TITLE
How to use two command for one function?

### ISSUE THREAD

**Issue by 631068264** [python-telegram-bot/python-telegram-bot#848]
For example
   /help /start for the same function

Only this way?
```
def help():
     .....

dispatcher.add_handler(handler=CommandHandler('start', help))
dispatcher.add_handler(handler=CommandHandler('help', help))

```

**Comment by Eldinnie** [comment]
This is not an issue but a usage question. You can ask your question again [here](https://t.me/pythontelegrambotgroup).
