### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by HouCoder** [python-telegram-bot/python-telegram-bot#849]
I want to make a bot that only certain people can use, I know their user IDs, is there a hook function to check and authorize user information before calling any command in python-telegram-bot? like `before_each` or something, thanks.

**Comment by 91DarioDev** [comment]
you could add a handler that check any update on a group higher than all the others one. you check if the user is allowed to use the bot, in case he is not allowed raise 

example code:
`dp.add_handler(MessageHandler(Filters.all, check_allowed), -1)`

```
def user_is_allowed(bot, update):
    if update.message.from_user.id not in allowed list:
        raise DispatcherHandlerStop
```
other groups of handlers should be greater than `-1`

**Comment by Eldinnie** [comment]
This is not an issue but a usage question. You're free to discuss in our [telegram group](https://t.me/pythontelegrambotgroup). I'm closing the issue
