### ISSUE TITLE
Send image on reply in conversation

### ISSUE THREAD

**Issue by ElizarovEugene** [python-telegram-bot/python-telegram-bot#850]
Hello. Need help, the wiki could not find an answer. It is necessary in the conversation, when replying to the user to send not only text, but also a picture. I use update.message.reply_text for this. How can I send a picture?

**Comment by Eldinnie** [comment]
This is not an issue but a usage question. You're free to discuss in our [telegram group](https://t.me/pythontelegrambotgroup). I'm closing the issue.
