### ISSUE TITLE
Delete or edit reply_text with InlineKeyboardMarkup when no answer provided

### ISSUE THREAD

**Issue by elenabdc** [python-telegram-bot/python-telegram-bot#851]
Hi everyone,

Is there any way to delete or edit a reply_text message with an InlineKeyboardMarkup if the user doesn't provide any kind of answer.

I have tried:
`bot.edit_message_text(chat_id=update.message.chat_id, message_id=update.callback_query.message.message_id, text="This is just a test")`

But I get the following error:

> AttributeError: 'NoneType' object has no attribute 'message'

Thank you :)

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup).
