### ISSUE TITLE
Group link

### ISSUE THREAD

**Issue by mohammadalian1383** [python-telegram-bot/python-telegram-bot#853]
The group link is incorrect

**Comment by Eldinnie** [comment]
What grouplink do you mean? This one? https://t.me/pythontelegrambotgroup ? if so, we've heard reports that users from Iraq aren't able to join. Could this be your case?

**Comment by mohammadalian1383** [comment]
I live in iran

**Comment by mohammadalian1383** [comment]
But says invalid address

**Comment by jeffffc** [comment]
Iranians cannot enter public groups (groups with usernames)

**Comment by mohammadalian1383** [comment]
so where i ask the questions

**Comment by jh0ker** [comment]
@mohammadalian1383 
We set up an IRC bridge, so you should be able to participate in discussions this way: http://webchat.freenode.net/?channels=##python-telegram-bot
