### ISSUE TITLE
Handle Errors

### ISSUE THREAD

**Issue by Lanseuo** [python-telegram-bot/python-telegram-bot#855]
I am trying to catch errors in my bot, so I can send them to sentry.io.

I added the following line of code:
`dispatcher.add_error_handler(error_callback)`

`def error_callback(bot, update, error):`
    `print("error")`
`    try:`
`        raise error`
`    except Exception as e:`
`       client.captureException()`

But if there is an error in an command function, it doesn't get handled:
`def details(bot, update):`
`    print(1/0)`

Where else do I have to put the try and except block and the code for reporting the error to sentry.io.

**Comment by Eldinnie** [comment]
Hey,

At the moment the only error's passed to the errorhandler are `TelegramError` (or subclasses). 
If you're expecting a different type of error in your handlers you should probably `try ... except` them within the handler.

**Comment by Lanseuo** [comment]
Thank you for your help! 
I created a decorator which catches all handler errors:

```python
def catch_error(f):
    @wraps(f)
    def wrap(bot, update):
        logger.info("User {user} sent {message}".format(user=update.message.from_user.username, message=update.message.text))
        try:
            return f(bot, update)
        except Exception as e:
            # Add info to error tracking
            client.user_context({
                "username": update.message.from_user.username,
                "message": update.message.text
            })

            client.captureException()
            logger.error(str(e))
            bot.send_message(chat_id=update.message.chat_id,
                             text="An error occured ...")

    return wrap
```

So I just added this line of code in front of every handler function:

```python
@catch_error
def start(bot, update):
    ....
```
