### ISSUE TITLE
I used Update.callback_query after which i used Update.message in same function its not working

### ISSUE THREAD

**Issue by Misaac77** [python-telegram-bot/python-telegram-bot#858]
### Steps to reproduce
1.update.callback_query.from_user i used and same function i used " update.message.text"
where i tried to get message from user as response its not working 

### Expected behaviour
update.message.text should replay user message

### Actual behaviour
'NoneType' object has no attribute 'text'

Tell us what happens instead

### Configuration
**Operating System:**
ubuntu 16.04

**Version of Python, python-telegram-bot & dependencies:**
3.6
``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by JosXa** [comment]
Easy fix: Use `update.effective_message.text` which will extract the correct message argument (it lies under `update.callback_query` aswell).
