### ISSUE TITLE
Result_id_duplicate confusion

### ISSUE THREAD

**Issue by derdav3** [python-telegram-bot/python-telegram-bot#860]
### Steps to reproduce
1. simple inline_bot

2. host on heroku

3. get errors

my bot parses a website and gives a snipped back. I don't understand why I get this error:

`2017-10-09 11:38:26,525 - __main__ - WARNING - Update "{'update_id': 456660684, 'inline_query': {'id': '86557556760404777', 'query': 'abd', 'offset': '', 'from': {'id': 20153251, 'first_name': 'censor', 'is_bot': False, 'last_name': 'censor', 'username': 'censor', 'language_code': 'en-CH'}}}" caused error "Result_id_duplicate"`

the method in question is:
```
def inline_handle(bot, update):
    query = update.inline_query.query
    if not query:
        return
    results = list()
    results.append(InlineQueryResultArticle(id=update.update_id,
                                            title="tagesmenu",
                                            input_message_content=InputTextMessageContent(
                                                tagesmenu)))
```

I have tried the same with `update.inline_query.id` instead of `update.update_id`, but with the same errors....

**Comment by Eldinnie** [comment]
@derdav3 InlineQueryResult*.id is supposed to be unique. Generally speaking str(uuid.uuid4()) is a safe way to generate ID's

**Comment by derdav3** [comment]
@Eldinnie this is confusing, since `update.update_id` should be unique....
how is uuid used? it throws an error...

**Comment by Eldinnie** [comment]
Let me try to clarify.
`Update.update_id` is indeed unique. It's used by telegram to identify an update.
When using `Bot.answer_inline_query` you need to return a list of `InlineQueryResult*` objects, all these `InlineQueryResult*` should have a unique ID. In the code you pasted above, all the results have the same ID (being `Update.update_id`). Telegram refuses this because they're not unique so it throws an error.

What would work is:
```python
from uuid import uuid4

def inline_handle(bot, update):
  query = update.inline_query.query
  if not query:
    return
  results = list()
  results.append(InlineQueryResultArticle(id=str(uuid4()),
                                                                  title="tagesmenu",
                                                                  input_message_content=InputTextMessageContent(
                                                                  tagesmenu)))
```

**Comment by derdav3** [comment]
@Eldinnie  thanks for the added code - now works flawlessly...
Now I'm trying to figure out how to make the thumbnail to the side a gif, instead of the stock thumb...

**Comment by Eldinnie** [comment]
`InlineQueryResultGif` 👍
