### ISSUE TITLE
InlineQueryResultGif breaks after 3 elements

### ISSUE THREAD

**Issue by derdav3** [python-telegram-bot/python-telegram-bot#862]
I have added 4 elements: 
```
results = list()
    results.append(InlineQueryResultGif(id=str(uuid.uuid4()),
                                           gif_url='https://media.giphy.com/media/IuZP6QzrnfQo8/giphy.gif',
                                           thumb_url='https://media.giphy.com/media/IuZP6QzrnfQo8/giphy.gif',
                                            title="tagesmenu",
                                            input_message_content=InputTextMessageContent(
                                                tagesmenu)))
    results.append(InlineQueryResultGif(id=str(uuid.uuid4()),
                                        gif_url='https://media.giphy.com/media/xUA7bdxar9tum5QQtW/giphy.gif',
                                        thumb_url='https://media.giphy.com/media/xUA7bdxar9tum5QQtW/giphy.gif',
                                            title="vegimenu",
                                            input_message_content=InputTextMessageContent(
                                                vegimenu)))
    results.append(InlineQueryResultGif(id=str(uuid.uuid4()),
                                            gif_url='https://media.giphy.com/media/3ohjUTGs2ttsuaQFvq/giphy.gif',
                                            thumb_url='https://media.giphy.com/media/3ohjUTGs2ttsuaQFvq/giphy.gif',
                                            title="exquisite",
                                            input_message_content=InputTextMessageContent(
                                                exquisite_menu )))
    results.append(InlineQueryResultGif(id=str(uuid.uuid4()),
                                            gif_url='https://media.giphy.com/media/wlEPdDuMQzSkE/giphy.gif',
                                            thumb_url='https://media.giphy.com/media/wlEPdDuMQzSkE/giphy.gif',
                                            title="everything",
                                            input_message_content=InputTextMessageContent(
                                                tagesmenu+vegimenu+exquisite_menu )))
```
the third item seems to get skipped. additionally telegram crashes when clicking in the empty space on the right of the last gif - see the attached screen shot - it crashes when clicking into the red marked square.  

  
<img width="513" alt="screen shot 2017-10-09 at 18 55 50" src="https://user-images.githubusercontent.com/6107913/31349479-ba82c516-ad23-11e7-9558-3d3c7c4ccad3.png">

  
ps: the last gif that gets rendered is actually the fourth item. but I've tried multiple gifs for the third item... all break

**Comment by jh0ker** [comment]
@derdav3 I don't see how this could be related to this library in any way.

**Comment by derdav3** [comment]
@jh0ker ..in any way? 
I'm using your library, specifically `InlineQueryResultGif`, that doesn't work as expected after a number of elements, with gifs, that clearly work... please clarify.

**Comment by jh0ker** [comment]
@derdav3 Sorry, sent too early. My point is that all we do is interact with the Telegram Bot API via HTTP - it should be impossible for us to crash a Telegram Client. Which strongly indicates that the root of the issue lies somewhere else.

Also, please fill out the issue template. It is there for a reason.

**Comment by jh0ker** [comment]
@derdav3 Oh and have you tried using different clients?

**Comment by derdav3** [comment]
@jh0ker on macOS 3 gifs get rendered, and it crashes. on ubuntu it works as expected.

**Comment by jh0ker** [comment]
@derdav3 I would say that makes it very unlikely that it is related to this library, and more likely to be an issue with the macOS client. 
Again, we only speak to the a HTTP REST API. If our request is accepted, it can be expected to work on all clients that are up-to-date. It is not our responsibility to account for any possible differences.
I invite you to join our Telegram Group at https://t.me/pythontelegrambotgroup to ask around - perhaps someone else has observed the same issue and knows a workaround.
