### ISSUE TITLE
setGameScore and getGameHighScores is not working 

### ISSUE THREAD

**Issue by Misaac77** [python-telegram-bot/python-telegram-bot#863]
### Steps to reproduce
1.setGameScore and getGameHighScores is not working
I passed user_id and score in that function

### Expected behaviour
set user score and throwback in user screen
### Actual behaviour
 A TelegramError was raised while processing the Update no t working

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup).
