### ISSUE TITLE
Commands and \n after aren't processed by CommandHandler

### ISSUE THREAD

**Issue by kisik21** [python-telegram-bot/python-telegram-bot#868]
### Steps to reproduce
1. Make a bot with a CommandHandler

2. Send a command with \n after it without space! Like this:
```
/feedback
some text
```

### Expected behaviour
Command should not be ignored...

### Actual behaviour
...but it is ignored instead

### Configuration
**Operating System:**
Gentoo

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kisik21/Projects/Nadeko/.virtualenv/lib64/python3.6/site-packages/telegram/__main__.py", line 3, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
```
Okay, I installed urllib3...
```
python-telegram-bot 6.1.0
urllib3 1.22
certifi 2017.04.17
future 0.16.0
Python 3.6.1 (default, Sep 25 2017, 22:51:25)  [GCC 5.4.0]
```
### Logs
Don't think this applies here.

The issue is probably the CommandHandler - I read the code, it thinks of \n as a part of command string. We need to strip these while detecting command names, I think...

**Comment by Eldinnie** [comment]
Hi,

Thanks for reporting this. We will take action soon.

**Comment by tsnoam** [comment]
@kisik21 re: urllib3
you are using an old version of ptb. you should upgrade to the latest which comes with a vendored version of urllib3.
best way is to upgrade using pip, but if you prefer to use sources, please make sure to follow the README in order to properly get the sources including the git submodules.

**Comment by kisik21** [comment]
@tsnoam re: re: urllib3

`pip install --upgrade python-telegram-bot` gave me the same 8.0 I was running.

**Comment by tsnoam** [comment]
@kisik21 that conflicts with the version you specified in the initial report. 
anyhow, it doesn't matter. fix for the actual issue is in the works.

**Comment by kisik21** [comment]
@tsnoam oh, yeah, I accidentally mistaken one venv for another.
