### ISSUE TITLE
commandhandler error after updated the library to the 8.1.0

### ISSUE THREAD

**Issue by 91DarioDev** [python-telegram-bot/python-telegram-bot#871]
after i updated the library to 8.1.0  i keep getting this error

```
 ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 269, in process_update
    for handler in (x for x in self.handlers[group] if x.check_update(update)):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 269, in <genexpr>
    for handler in (x for x in self.handlers[group] if x.check_update(update)):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/commandhandler.py", line 137, in check_update
    command = message.text[1:].split(None, 1)[0].split('@')
```

i did not change a single line of my code and in fact reverting to the previous version of the library i am fine

edit:

**steps to reproduce:**
- send a text message containing only one word.

it doesn't happen with commands or text containing more than one words or media

edit2:
set the log on DEBUG it also say
`IndexError: list index out of range` in addition to the previous Traceback

**Comment by 91DarioDev** [comment]
i guess the issue could depend on this https://github.com/python-telegram-bot/python-telegram-bot/commit/ec9b16ac7b55ca1f02291d157f06028321b52d79#diff-9cd44b48f0b3c83abd861dfd18b28090R137

**Comment by jh0ker** [comment]
@91DarioDev Do you mean one word or one character?

**Comment by SitiSchu** [comment]
I can verify that this happens when you only send one character to the bot.

**Comment by SitiSchu** [comment]
This can be tested with the echobot2.py example.

**Comment by 91DarioDev** [comment]
@jh0ker  yes only one char. it is more than 1 char it's fine. sorry
