### ISSUE TITLE
parse_entities returns an empty object with captions

### ISSUE THREAD

**Issue by 91DarioDev** [python-telegram-bot/python-telegram-bot#872]
```
entities = update.message.parse_entities([
				MessageEntity.URL, 
				MessageEntity.MENTION, 
				MessageEntity.TEXT_LINK, 
			        MessageEntity.TEXT_MENTION
				])
print(entities)
```

sending a text message containing a link (for example) print the entities with the code below, while sending a photo with a caption with the same link, the code below prints `{}`. The expected result was to print the entities like for message.text

**Comment by Eldinnie** [comment]
For caption entities you should use
`parse_caption_entities`

**Comment by 91DarioDev** [comment]
thank you i close
