### ISSUE TITLE
Add Filters.gif

### ISSUE THREAD

**Issue by JosXa** [python-telegram-bot/python-telegram-bot#875]
Since the question comes up a lot in our Telegram group, I'm adding it as an issue:
The `Filters` should include a `gif`-Filter checking if the update contains a document which has the mime type of gifs.

**Comment by tsnoam** [comment]
@JosXa Sounds useful. I'd say it should be somewhat more flexible - like instatinating fillers for known types and allowing users to instatinate their own custom fillers with a mimetype.

**Comment by JosXa** [comment]
@tsnoam I agree, there's a lot more that could be added. I'd still say that since gifs are an integral part of Telegram and baked into every client, they should get their own thing. Hmm is there a list of mime types that can be sent over Telegram and are ameliorated with rich views?

**Comment by JosXa** [comment]
Implemented with #1046: Filters.document.gif
