### ISSUE TITLE
Question: Can a bot get the user phone number as part of the POST body

### ISSUE THREAD

**Issue by balderman1** [python-telegram-bot/python-telegram-bot#876]
Is it possible to get the user phone number as part of the HTTP call to the Bot?

Thanks

**Comment by 91DarioDev** [comment]
bots api doesn't have any method to get a phone number but you can use the `request_contact` of `KeyboardButton` to ask it to the user
https://python-telegram-bot.readthedocs.io/en/stable/telegram.keyboardbutton.html#KeyboardButton.request_contact

**Comment by tsnoam** [comment]
@balderman1 if you're not already there you're invited to join our users group, which is the right place to ask usage questions.
https://t.me/pythontelegrambotgroup
