### ISSUE TITLE
Is python-telegram-bot suitable for async job?

### ISSUE THREAD

**Issue by stephentt-me** [python-telegram-bot/python-telegram-bot#877]
For example:
```python
def cmd_report(bot, update):
    bot.send_message(chat_id=update.message.chat_id, text="Hey, got it. Doing now!")
    result = getInfoFromSQLServer() # this line take 10s
    bot.send_message(chat_id=update.message.chat_id, text=result)

```

I got this problem. The `getInfoFromSQLServer()` block all incoming message. So, my question is: Is `python-telegram-bot` suitable for async job, or I should use Nodejs

**Comment by jeffffc** [comment]
There is a decorator for async functions.
Use `from telegram.ext.dispatcher import run_async`, then decorate the function with `@run_async`

And anyways, usage questions should not be done here. Feel free to ask it in our [Telegram group](http://t.me/pythontelegrambotgroup).
