### ISSUE TITLE
CallbackGame misses attribute?

### ISSUE THREAD

**Issue by JosXa** [python-telegram-bot/python-telegram-bot#879]
Judging from [this article](https://blog.ludei.com/how-to-create-a-game-bot-and-publish-your-html5-games-on-telegram/), although the Telegram documentation states that "CallbackGame value is just a placeholder, currently holds no information, when trying to set the callback game with this empty placeholder the button (as our logic expected) doesn’t do anything at all".

> After reading our Telegram API library source code, we discovered that a proper game callback does contain some values and after setting up a JSON with a unique field “game_short_name” the button works.

According to that, a `CallbackGame` must not be empty, but instead have something like `{'game_short_name': 'the game set up with botfather'}`. This is our current class: https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/games/callbackgame.py

I didn't manage to get a button to work that opens the game either. Edit: On second attempt, I added the parameter to our `CallbackGame` class, and yields the following error just the same as without it: `BadRequest: Button_type_invalid`.
This is the `to_dict()` of the whole keyboard markup: ```{'inline_keyboard': [[{'callback_game': {'game_short_name': 'speedreader'},
                       'text': 'Speed Read'}]]}```
I'm confused. Has anyone even written a HTML5 game bot with python-telegram-bot yet? I'd love to see a MWE

**Comment by JosXa** [comment]
Use sendGame instead.

**Comment by jeffffc** [comment]
I have a HTML5 game on my bot and i used both `sendGame` and `InlineQueryResultGame` and they work fine. never tried making my own keyboard with the callbackgame button tho

**Comment by pkappus** [comment]
I was able to get the custom button running. Based on [your linked article](https://blog.ludei.com/how-to-create-a-game-bot-and-publish-your-html5-games-on-telegram/) I added the game_short_name to the CallbackGame object and it worked fine for me.
`game = telegram.CallbackGame() 
    game.game_short_name="menu" #add game_short_menu value (despite the doc saying theres no need to add it)
    buttons = [[telegram.InlineKeyboardButton(text="Show Menu",callback_game=game)]] #Create the actual button
    keyboard_markup = telegram.InlineKeyboardMarkup(buttons)
    context.bot.send_game(chat_id=update.effective_chat.id,game_short_name="menu",reply_markup=keyboard_markup) #Send game with custom inline button`

**Comment by Bibo-Joshi** [comment]
Well, that's interesting. Thanks for your report @pkappus ! I'll contact @botsupport about it.
Maybe we can add `game_short_name` as an optional attribute to CallbackGame?

**Comment by Bibo-Joshi** [comment]
It seems, `callback_game` is only valid in keyboards attached to `send_game`. This would explain, why there is no need for Telegram to have the `game_short_name` in the button (b/c it's in the `send_message` arg already. @pkappus could test, if you can start a game without the `game_short_name` attribute in the button?

Haven't heard anything back from @botsupport, btw.
