### ISSUE TITLE
New Example of Inline keyboard bot with multiple callback query handlers.

### ISSUE THREAD

**Issue by sahilsharma811** [python-telegram-bot/python-telegram-bot#882]
### Steps to reproduce
1. Develop a Inline keyboard bot example that have multiple callback query handlers. 

2. Conversation Handler need to be added that can handle different callbacks from Inline keyboards.

### Expected behaviour
Replies from the user to the bot that supports inline keyboard must be handled by a dedicated callback query handler for that particular reply, so that a user reaches a dedicated query handler. This is needed to modularize the code and to reduce the complexity involved with a single callback query handler. For this a conversation handler is needed which has defined states for every response from the user, that call a function and return the control to the next corresponding state of the bot. This will enable the developers to use this example to develop conversation bots that supports inline keyboards.

### Actual behaviour
Inline keyboard example for now has no conversation handler and has only one callback query handler. So multiple callbacks are not supported in the current example 'inlinekeyboard.py' in 'examples' directory.

### Configuration
**Operating System: **
Linux 

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
Python 3.5.2 
python-telegram-bot==6.1.0

### Logs
Insert logs here (if necessary)
Not Necessary

**Comment by sahilsharma811** [comment]
I would like to work on this issue.

**Comment by tsnoam** [comment]
@sahilsharma811 We always welcome users' contribution is always welcome.

**Comment by tsnoam** [comment]
@tsnoam Just send a PR for a new example file when it's ready.
I don't see a reason to keep this issue open as it's not an actual issue with the library code, so I'm closing it.

**Comment by sahilsharma811** [comment]
@tsnoam Thanks for your comment. I'll send a PR soon.
