### ISSUE TITLE
Is https://t.me/pythontelegrambotgroup working?

### ISSUE THREAD

**Issue by lameei** [python-telegram-bot/python-telegram-bot#885]
Just tried to joing the channel but telegram says that the channel does not exists. Am I missing something ?

**Comment by 91DarioDev** [comment]
Persian users can’t join public groups. Maybe this is the reason?

**Comment by lameei** [comment]
I guess that is the problem.
 I just want to know what is the benefit of using this lib over the API or even the teleport lib.

**Comment by pepegc** [comment]
I am in Chile and also cannot access it.

**Comment by Eldinnie** [comment]
For some reason, some users can't join our telegramgroup. We've set up an IRC bridge for those users.
https://webchat.freenode.net/?channels=##python-telegram-bot

**Comment by SitiSchu** [comment]
Some Countries like Iran cant use public supergroups with usernames.

**Comment by lameei** [comment]
IRC is the answer for now. Thanks.
