### ISSUE TITLE
error during retrieve of update.channel_post.from_user.first_name

### ISSUE THREAD

**Issue by bigpea** [python-telegram-bot/python-telegram-bot#886]
Hi all,
I'd like to retrieve the name of the sender of the message in private chat and in a group chat.
So, I created this code:
    if update.message is not None:
        messaggio=str(update.message.text)
        chatId=str(update.message.chat_id)
        fromMessage=str(update.message.from_user.first_name)
    elif update.channel_post is not None:
        messaggio=str(update.channel_post.text)
        chatId=str(update.channel_post.chat_id)
        if update.channel_post.from_user is not None:
            fromMessage=str(update.channel_post.from_user.first_name)

The problem is that in case of group chat I don't receive the name of the sender:
   update.channel_post.from_user.first_name
because the object "update.channel_post.from_user" is null.

Exist a way to retrieve this information?

Thanks

### Expected behaviour
I'd like to have the the name of the sender in the channel group

### Actual behaviour
i receive a null object

### Configuration
Raspberry Pi3

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup).
