### ISSUE TITLE
Using existing webhook server for custom entry points

### ISSUE THREAD

**Issue by akiross** [python-telegram-bot/python-telegram-bot#894]
Hello, this is not a bug notification, but a documentation/enhancement request.

My objective is being able to use the same bot to process both telegram requests and also regular web requests. I thought that, when using webhooks, it could be possible to achieve such an objective as a web server is already running.

Basically, I would like to have custom entry points to command the bot via web interface, in addition to the regular mechanisms found in telegram. In this way, I could - for example - see bot statistics from a web page, or sending commands to the bot via URLs (deep linking works in telegram only for the start command).

I looked a bit into the code and I saw there is a webhook server and a webhook handler that are set-up. The server is available in the `update.httpd` variable, but I am not sure how to use it for my custom entry points.

Can you please give me pointers about that?
Thanks

**Comment by Eldinnie** [comment]
I suggest you use some web framework instead of the builtin `simplehttpserver`
I used [Cherrypy.org](Cherrypy.org) to mount three seperate entry-points (classes) on a http-server to run a bot, website and API-service from the same script.
