### ISSUE TITLE
LIST_OF_ADMINS for @restricted should be replaced by a callable

### ISSUE THREAD

**Issue by mndhkr** [python-telegram-bot/python-telegram-bot#898]
Since manually updating the hardcoded admins in LIST_OF_ADMINS is unfeasible,
I suggest to use a callable instead of a global variable to get the list of admins.

Thank you

**Comment by JosXa** [comment]
Hi @mndhkr, are you referring to [the snippet](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#restrict-access-to-a-handler-decorator)? As all snippets, it is only meant to be explanatory and of course you need to modify it to your needs. Also, the @restricted handler (although widely used) was introduced before we had `Filters.user(user_id)` in the `filters` section of Handlers, which should now probably be the preferred way of filtering admins. In my own projects, I still like to denote it with decorators, so I guess it has some value.

You make it sound like it is included in the library, where did you find it?
If you have a better code, feel free to update it in the wiki (it is free to edit for anyone).

**Comment by mndhkr** [comment]
Oh, yep, i misunderstood the snippet.
I thought it was included in the library.
Thank you for your hints and to point that out :))
