### ISSUE TITLE
Android telegram client scroll down after callback

### ISSUE THREAD

**Issue by sautchenkov** [python-telegram-bot/python-telegram-bot#900]
Hi! I have some problems with android telegram client. If I send a message with a link and callback button for this message, after press callback button client app force scroll down to the end of bot conversation.

This reproduce only in android client and only if a message has a link and callback button.

Maybe anyone one knows what I can do with this?

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code,

Closing.
