### ISSUE TITLE
Question - Wait for user input/message

### ISSUE THREAD

**Issue by AzriDelta** [python-telegram-bot/python-telegram-bot#901]
Hello.

How can I do a function in which I need to wait for a user input, before proceeding?

Here's my code:

def add(bot, update):
    bot.send_message(chat_id=update.message.chat_id, text="Send me a tracking number")
    #for user reply
    tracking_number = update.message.text #get user reply
    bot.send_message(chat_id=update.message.chat_id, text=tracking_number)

Thank you.

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup).
