### ISSUE TITLE
Reply message without passing bot and update parameter.

### ISSUE THREAD

**Issue by HouCoder** [python-telegram-bot/python-telegram-bot#902]
Hi, I'm working on a telegram bot project that uses WebSocket to communicate with backend, once backend replies, the `received_message` will be called with a message parameter, now I want to send the replied message back to the telegram user but I can't have the `bot` or `update` parameter in the `received_message` function, so how can I send the message back to the client  in `received_message` function?

Thanks.

**Comment by bomjacob** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup).

**Comment by HouCoder** [comment]
@bomjacob thanks for your concern, I searched dozens of documents, asked in the telegram channel(nobody replied) and I still don't know the correct way to deal with this issue.
