### ISSUE TITLE
RuntimeError: Dispatcher not initialized or multiple instances exist

### ISSUE THREAD

**Issue by paradox70** [python-telegram-bot/python-telegram-bot#903]
### Steps to reproduce
I don't know why this error is happening!
All of the code work fine until I used @run_async.
When I run my code in my personal system (ubuntu 12, get_update, apache2) the bot works fine but when I run the code on my VPS (ubuntu 16, get_update or webhook, nginx) the code compile but at runtime with @run_async got error. If I comment @run_async the bot also works fine on VPS.
How to avoid this error? 

### Configuration
**Operating System:** ubuntu 16.04
**webserver:** nginx (uwsgi mode)

**Version of Python, python-telegram-bot & dependencies:**
```python 3.5.2```
``python-telegram-bot (8.1.1)``

### Logs

    2017-11-06 04:18:22,598 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
      File "/usr/local/lib/python3.5/dist-packages/telegram/ext/callbackqueryhandler.py", line 143, in handle_update
        return self.callback(dispatcher.bot, update, **optional_args)
      File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 53, in async_func
        return Dispatcher.get_instance().run_async(func, *args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 149, in get_instance
        cls.__name__))
    RuntimeError: Dispatcher not initialized or multiple instances exist

**Comment by Eldinnie** [comment]
the error means exactly what it says. Please provide the minimal working example as requested in the template, so we can take a look.

**Comment by paradox70** [comment]
Ok, I make a mistake in my previous post, if I run the code by get_update method on my VPS, there is no error but when I use webhook method and run it by flask in uwsgi mode, I got this error.
I should mentioned I have several bots running by uwsgi in same host and port! and this make this error. So I deactivated other bots and kept one of them, now this error is gone but another problem exist, the functions decorated with @run_async didn't run at all!

I will upload a simple code in the next comment.

**Comment by paradox70** [comment]
Codes of flask application:

    from flask import Flask
    import json, logging
    from telegram import Update
    import exampleBot1
    import exampleBot2

    app = Flask(__name__)

    webhook_url='https://example.com/{}'.format(exampleBot1.TOKEN)
    dp_exampleBot1, bot_exampleBot1 = exampleBot1.main(webhook_url)

    webhook_url='https://example.com/{}'.format(exampleBot2.TOKEN)
    dp_exampleBot2, bot_exampleBot2 = exampleBot2.main(webhook_url)
    
    @app.route("/"+exampleBot1.TOKEN, methods=["POST","GET"])
    def get_exampleBot1():
        if request.json:
            update = Update.de_json(request.json, bot_exampleBot1)
            dp_exampleBot1.process_update(update)
        return ''

    @app.route("/"+exampleBot2.TOKEN, methods=["POST","GET"])
    def get_exampleBot2():
        if request.json:
            update = Update.de_json(request.json, bot_exampleBot2)
            dp_exampleBot2.process_update(update)
        return ''

    if __name__ == '__main__':
        app.run()

exampleBot1.py:

    from telegram import Bot
    from telegram.ext import Updater, CommandHandler, Dispatcher
    from telegram.ext.dispatcher import run_async
    import logging

    TOKEN = "×××××××××××"

    logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO)
    logger = logging.getLogger(__name__)

    @run_async
    def start(bot, update):
	text = update.message.text
        update.message.reply_text(text)

    def error(bot, update, error):
        logger.warn('Update "%s" caused error "%s"' % (update, error))

    def main(webhook_url=None):
        if webhook_url:
            bot = Bot(TOKEN)
            dp = Dispatcher(bot, None, workers=0)
        else:
            updater = Updater(TOKEN)
            bot = updater.bot
            dp = updater.dispatcher

        start_handler = CommandHandler('start', start)
        dp.add_handler(start_handler)
        dp.add_error_handler(error)

        # Start the Bot 
        if webhook_url:
            bot.set_webhook(url=webhook_url)
            return dp, bot
        else:
            bot.set_webhook()
            updater.start_polling()
            updater.idle()

    if __name__ == '__main__':
        main()

exampleBot2.py

    same as exampleBot1.py

uwsgi option (ini file):

    [uwsgi]
    chdir = /path/to/bot
    module = wsgi:app

    master = true
    processes = 1

    socket = botserver.sock
    chmod-socket = 660
    vacuum = true

    die-on-term = true

    py-autoreload = 1
    logto = /path/to/bot/log

    async = 10

**Comment by bomjacob** [comment]
`@run_async` as a decorator does not work with multiple dispatchers, if I recall correctly you can use it as `@dispatcher.run_async` substituting `dispatcher` for the variable containing your dispatcher.

**Comment by Eldinnie** [comment]
In addition to what @bomjacob wrote you start your dispatcher in `main` in `examplebot1 ` with `workers=0`.
As you can read on [Our docs](http://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.dispatcher.html#Dispatcher.workers) this is the number of threads available for `@run_async` decorated methods. Since you set this to 0 the callback will never run.
Set it to a number higher then 0 (or leave it at the default of 4) to solve this problem.

**Comment by paradox70** [comment]
@Eldinnie:  I set worker equal to 4 but noting change.
@bomjacob:  Can you show me a trick acording above codes to replace **dispature** in @dispature.run_async with my own dp?

**Comment by Eldinnie** [comment]
@paradox70 What @bomjacob meant is in the main script you should replace:
`dp_exampleBot1.process_update(update)`
with
`dp_examplebot1.run_async(examplebot1.start(bot_examplebot1, update))`
Although it might be easier to just run one bot in one script.

Anyway since this is not an issue with the code. And we pointed out your problems in the code I will close this issue.
Feel free to continue looking for help in our [telegram group](https://t.me/pythontelegrambotgroup) where users are mostly willing to help.

**Comment by paradox70** [comment]
Thanks for your help.
I try to join this group but telegram say: 

> User pythontelegrambotgroup not found

**Comment by jh0ker** [comment]
@paradox70 Probably your account or country is blocked from public supergroups, you can use our IRC bridge to participate: https://webchat.freenode.net/?channels=##python-telegram-bot

**Comment by paradox70** [comment]
Hi @jh0ker 
Absolutely users of my country are blocked to join public supergroup!
Is it possible to you add me to your supergroup? please give it a try.
My telegram username is **@Mehdi_Rahimi**.

At the end of this post, I choose an easier way and just run one bot in one script.
Thanks to all.
