### ISSUE TITLE
Is there any handler for addition of new user? Want to restrict permission for every new user added to the group.

### ISSUE THREAD

**Issue by syed-mehtab** [python-telegram-bot/python-telegram-bot#904]
### Steps to reproduce
1.

2.

3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup).
