### ISSUE TITLE
all files have error exec permission

### ISSUE THREAD

**Issue by Sherlock-Holo** [python-telegram-bot/python-telegram-bot#906]
### Steps to reproduce
1.
download [pypi](https://pypi.python.org/packages/b4/d4/66e153eb470179dd6346ae1f5a50c75b871c2263ab7b976427b2d9722689/python-telegram-bot-8.1.1.tar.gz#md5=09ad2c160fb13ffce1ed2c67d3d3501d) package
2.
use `bsdtar -xvf` to unzip
3.
found all files have exec permission
### Expected behaviour
Tell us what should happen
all files' permission should be 644 except dictories
### Actual behaviour
Tell us what happens instead
all files have exec permission
### Configuration
**Operating System:**
Arch Linux

**Comment by Eldinnie** [comment]
Hi @Sherlock-Holo 

Thanks for pointing this out. It appears pushing a release from a Windows-system was not such a good idea after all.
We will fix it in the next and further releases.

Greetings

**Comment by Sherlock-Holo** [comment]
you are welcome～

Eldinnie <notifications@github.com> 于 2017年11月8日周三 20:58写道：
