### ISSUE TITLE
Put on update queue doesn't trigger any handler

### ISSUE THREAD

**Issue by lucaspg96** [python-telegram-bot/python-telegram-bot#907]
### Steps to reproduce
1. Create an Updater object and call start_pooling(), storing the queue

2.Create an Update object with some message that will trigger a handler

3.Insert the update on the queue

### Expected behaviour
The handler must execute

### Actual behaviour
Nothing happens

### Configuration
**Operating System:**
Mac OS Sierra

**Version of Python, python-telegram-bot & dependencies:**
python 3.6
python-telegram-bot==8.1.1

**Comment by bomjacob** [comment]
I cant seem to reproduce this, can you provide some example code, please?

**Comment by lucaspg96** [comment]
Of course, sorry for the delay

`from telegram.ext import Updater, CommandHandler
from telegram import Message,Update
from os import environ

up = Updater(environ.get("BOT_ALFRED_TOKEN"))
dp = up.dispatcher

def start(bot,update):
    print("Start!")
    update.message.reply_text("Bot started")

dp.add_handler(CommandHandler("start",start))

q = up.start_polling()
q


msg = Message(0,0,0,0,text="/start")
update = Update(0,message=msg)

q.put(update)`

I was expecting that the handler trigger when I use the put method. That make sense?

**Comment by Eldinnie** [comment]
I expect (although you have no logging so it doesn;t show) this will actually raise an Exception.
change: `msg = Message(0,0,0,0,text="/start")` to `msg = Message(0,0,0,0,text="/start", bot=up.bot)`
for commandhandler to work properly the message has to have an originating bot.

**Comment by lucaspg96** [comment]
Thanks for the help. I understood the problem. I never have used the log, I always thought that the error were going to be appears by default. The problem is solved. Thanks!
