### ISSUE TITLE
error at "python3 setup.py install" when "Searching for certifi""unknown url type: https"

### ISSUE THREAD

**Issue by hominglee** [python-telegram-bot/python-telegram-bot#908]
centos 6.5
python3 setup.py install
error:

`
Searching for certifi
Reading https://pypi.python.org/simple/certifi/
Download error on https://pypi.python.org/simple/certifi/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'certifi' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or working download links found for certifi
error: Could not find suitable distribution for Requirement.parse('certifi')
`

unknown url type: https

I visited the url [https://pypi.python.org/simple/certifi/](url) and found their link was not url/X any more but changed to hash link like this:
../../packages/29/9b/25ef61e948321296f029f53c9f67cc2b54e224db509eb67ce17e0df6044a/certifi-2017.11.5-py2.py3-none-any.whl#md5=429fdf238d878f8090a80ccc3488049b

Would anyone check it and repair them? Thank you.

**Comment by Eldinnie** [comment]
@hominglee Hi, did you clone the repo like it's described here? https://github.com/python-telegram-bot/python-telegram-bot/blob/master/.github/CONTRIBUTING.rst

**Comment by Eldinnie** [comment]
closed due to lack of response
