### ISSUE TITLE
links are ignored in tg scheme with markdown format

### ISSUE THREAD

**Issue by RYNEQ** [python-telegram-bot/python-telegram-bot#909]
### Steps to reproduce
send message using MARKDOWN format. e.g.: 

```
bot.send_message(chat_id, u"[Doit](tg://bot_command?command=blc%(uid)s&bot=%(botname)s)"
                                 % {'uid':u.tgId, 'botname':_BOTNAME_},
                                  parse_mode=ParseMode.MARKDOWN)

```
### Expected behaviour
Receive link with text "Doit" which is linked to telegram bot command 

### Actual behaviour
Plain text without any link is received
Actually with http links received message is OK but links with "tg" scheme are ignored!
 
### Configuration
ubuntu 16.04

**Version of Python, python-telegram-bot & dependencies:**
```

python-telegram-bot 8.1.1
certifi 2017.07.27.1
future 0.16.0
Python 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
```

**Comment by Eldinnie** [comment]
That's because telegram does not consider them as links. It has nothing to do with this library
