### ISSUE TITLE
Can't run bot.py using threading or multiprocessing

### ISSUE THREAD

**Issue by elenabdc** [python-telegram-bot/python-telegram-bot#911]
I'm writing a Python3 script and I'm using python-telegram-bot as notification service. My code simple use OO to create a bot class, it has a method with an InlineKeyboardButton to answer a command received.

I'm trying to integrate it in the main script. It should run in a thread but when I try to start the thread I get a "RuntimeError: can't start new thread".

I'm running Debian 9, python-telegram-bot 8.0, certifi 2017.07.27.1, future 0.16.0 and Python 3.5.4 (default, Aug 12 2017, 14:08:14)  [GCC 7.1.0]. I have also tested it in Mac OS 10.12.6, python-telegram-bot 8.1.1, certifi 2017.04.17, future 0.16.0, Python 3.6.0 (default, Dec 24 2016, 08:01:42)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)].

Any idea on what is going on in my code? If needed, I can provide a simplified version of my code to test it.

Thank you.

**Comment by Eldinnie** [comment]
Hi,

Yes, please provide a minimal (not) working example of the problem so we can investigate the problem.

**Comment by jh0ker** [comment]
@Eldinnie I already helped @elenabdc find a solution in the group (hence the closed issue)

**Comment by Eldinnie** [comment]
I was not paying attention. Sorry :D
