### ISSUE TITLE
New API changes without changelog

### ISSUE THREAD

**Issue by Eldinnie** [python-telegram-bot/python-telegram-bot#918]
Some API method and objects have been added without a changelog.

What I found from `test_official`

New objects
- [x] [InputMedia](https://core.telegram.org/bots/api#inputmedia)
- [x] [InputMediaPhoto](https://core.telegram.org/bots/api#inputmediaphoto)
- [x] [InpputMediaVideo](https://core.telegram.org/bots/api#inputmediavideo)

New parameters to `Message`:
- [x] `media_group_id`

New arguments to `SendInvoice`:
- [x] `provider_data`

New method for `Bot`
- [x] [sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup)

**Comment by jcjc610** [comment]
An official change log after 3 days! 
https://core.telegram.org/bots/api-changelog#november-17-2017
