### ISSUE TITLE
telegram.ext.updater - 2017-11-22 18:00:15,979 - ERROR - Error while getting Updates: Timed out

### ISSUE THREAD

**Issue by soser1488** [python-telegram-bot/python-telegram-bot#921]
### Steps to reproduce
1.

2.

3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by Eldinnie** [comment]
Hi,

Unfortunately you missed all of the points in our issue template. Instead you just copied a single line from a traceback as a title.
Since we can;t do anything with that. I'm closing this.
