### ISSUE TITLE
ReplyKeyboardMarkup with set 

### ISSUE THREAD

**Issue by WTFisThat1** [python-telegram-bot/python-telegram-bot#922]
Hi!
I've got some set, that I want add to keyboard markup.
```
some_set = {'2', '3', '0.2', '1'}
markup = types.ReplyKeyboardMarkup(one_time_keyboard=True)
markup.add(some_set)
msg = bot.send_message(message.from_user.id, "test", reply_markup=markup)
```
So, I was trying to do that in stupid way: `new_set = some_set[1:-1]` So, its turned to:[screenshot](https://i.stack.imgur.com/5TjZI.png) How to do that?
Was searching it for hours, wrote to stack and etc. Can somebody help me?

**Comment by Eldinnie** [comment]
Hi,

There's quite a few things here that need some attention. First of all, you might want to read up on `[Set](https://docs.python.org/2/library/sets.html)`. Pay special attention to the title of that page.
Secondly I'm wondering if you're using python-telegram-bot at all? If so this is not an issue with the library's code, but a usage question. Which (as stated in our issue template) should be asked in our [telegram group](https://t.me/pythontelegrambotgroup).
