### ISSUE TITLE
converstaionbot in group

### ISSUE THREAD

**Issue by cbogithub** [python-telegram-bot/python-telegram-bot#923]
### Steps to reproduce
1. i run file converstaionbot.py in  example folder 

### Expected behaviour
if i chated with only bot this script working well but if add bot to the group and used it in this group and i got happend : seem it run until "bio" state and stop work. i think `BIO: [MessageHandler(Filters.text, bio)]` 
not worked here . anyone tell me what is problem?
### Configuration
**Operating System:**
i used ubuntu

**Version of Python, python-telegram-bot & dependencies:**
i used python 3.6 
``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by jh0ker** [comment]
Most likely your bot does not receive the message. Check https://core.telegram.org/bots/faq#what-messages-will-my-bot-get
