### ISSUE TITLE
Newbie troubles: Token and Authorization

### ISSUE THREAD

**Issue by stonemonk** [python-telegram-bot/python-telegram-bot#926]
I am having trouble getting started.  The documentation doesn't explain what the TOKEN is, and Telegram gives you 2 seperate peices: api_id and api_hash.  Looking at the source code I am pretty sure TOKEN = api_id:api_hash but when I launch I immediately get an telegram.error.Unauthorized Exception.  My code at present is very simple:

```
        token = "{}:{}".format(api_key, api_hash)
        self.client = Updater(token)
        self.client.dispatcher.add_error_handler(self.error_callback)
        self.client.dispatcher.add_handler(MessageHandler(Filters.text, self.process_message))
        self.client.start_polling()
        self.client.idle()
```

**Comment by jh0ker** [comment]
You are confusing the Telegram API with the Telegram **Bot** API. You can read up about the distinction [here](https://core.telegram.org/). Our library is a wrapper for the Telegram Bot API and not the Telegram API.

Read [this wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Introduction-to-the-API) to learn more.
