### ISSUE TITLE
Receiving bot messages

### ISSUE THREAD

**Issue by matiniamirhossein** [python-telegram-bot/python-telegram-bot#932]
Hello,
Following your wiki on https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions I have a question.

How to disable this feature that python-telegram-bot will not receive other bots messages? 
Can I overwrite it?

Use case: Bot is moderator of a super group will lot's of members. Bot enters the group and starts spamming. We need to filter telegram.me and t.me links on that bot.

And finally, Thank you for your awesome library.

**Comment by Eldinnie** [comment]
Hi,

What updates your bot receives is not limited by this library, but by [telegram's bot API.
](https://core.telegram.org/bots/faq#what-messages-will-my-bot-get).
Your problem can not be solved by using the bot API unfortunately.

**Comment by jh0ker** [comment]
@matiniamirhossein I'd like to add that this only applies to other "Bot API" bots. Many spambot accounts are actually custom clients that use the real Telegram API, so you should still be able to receive and filter those messages.

**Comment by matiniamirhossein** [comment]
@jh0ker Thank you for your response. Yes your are right. I'm encountering lot's of limitation with bot API.
 For example when kicking the user via bot A service message is triggered "Bot removed X", Bot can't delete that. Or fetching messages from history of group/mega/super group.
