### ISSUE TITLE
Pickle Bot State

### ISSUE THREAD

**Issue by JulesWayne** [python-telegram-bot/python-telegram-bot#935]
I hope this kind of question/request belongs here, apologies if not (and please point me to the right place to ask then). 
My Bots often have jobs running (e.g. scraper, or reminder, etc) and once I've done a few changes to my code I would like to commit them to the running bot. So far it didn't concern me much and I restarted the bot and had to start the jobs anew.
For my latest bot this is hardly possible, as it kind of works like a subscription bot where every user sets a job and is then notified at changes. Last "patch" I used a command that would let me message every user through the bot and tell them that they had to manually resubscribe due to the restart but that is **hardly** what I want to be doing everytime.

So, finally coming to my actual question: Is there a sane way to pickle the entire state of the bot or a similar solution to this problem? I'm sure many of you must've stumbled upon/solved that problem already.

Ways I figured one could probably be tackling it are:
- actually pickling everything, but for that I'd have to keep track of all the chat_datas etc
- **maybe** putting a lot of code into a different module and reloading it (not even sure if that works the way I think it might)

If there is a good way, one could think about implementing it as a function to this wrapper and/or give an example in the docs.

**Comment by jh0ker** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [Telegram group](https://t.me/pythontelegrambotgroup).
In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

**Comment by jh0ker** [comment]
Follow up: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#save-and-load-jobs-using-pickle
