### ISSUE TITLE
Message.reply_media_group

### ISSUE THREAD

**Issue by code1mountain** [python-telegram-bot/python-telegram-bot#936]
Hello, 

The Message class has helpers for `reply_text`, `reply_photo`, `reply_sticker` etc. Only `reply_media_group` is missing. Would be cool if you would add this little helper, so all type of sent messages are supported.

Best regards, 

Jannik (t.me/bergfreak)

**Comment by feuillemorte** [comment]
Please, review:

https://github.com/python-telegram-bot/python-telegram-bot/pull/994
