### ISSUE TITLE
documentation about webhooks are not clear.

### ISSUE THREAD

**Issue by amir3code** [python-telegram-bot/python-telegram-bot#940]
In webhooks page in the wiki in the part that involves nginx you said put the code:

updater.start_webhook(listen='127.0.0.1', port=5000, url_path='TOKEN1')
updater.bot.set_webhook(webhook_url='https://example.com/TOKEN1',
                        certificate=open('cert.pem', 'rb'))

and start.
I dont see any meaningful code here. Here I just started the webhook. Where is the request from telegram handled?
There is no property for callback.
What should I do?

I am using ubuntu vps and using nginx as a reverse proxy. I used to use uwsgi with nginx to redirect traffic from telegram servers to my code, but now want to use built in web server from python-telegram-bot instead of uwsgi.
But dont know how. (I can not join the group cause Im in a country under telegram sanctions. so please answer here)

**Comment by Eldinnie** [comment]
Hi,

First of all. Look at this [https://img.shields.io/badge/IRC-Channel-blue.svg](https://webchat.freenode.net/?channels=##python-telegram-bot). We set it up especially for people not able to join the channel.
Secondly. when using a webhook, you'd use the updater and handlers in the same way as everywhere. See the examples in our repo. The only think changed is that `updater.start_polling()` has to be replaced with the code you pasted yourself.

Good luck

**Comment by amir3code** [comment]
`updater.start_polling()` uses `getUpdates` method as mentioned in the webhooks page

    Our examples usually start the bot using Updater.start_polling. This method uses the getUpdates API method to receive new updates for your bot.

I dont want to use `UPDATES` method. I wanna use `webhooks`. In the heroku example specified:

```
import os

TOKEN = "TOKEN"
PORT = int(os.environ.get('PORT', '5000'))
updater = Updater(TOKEN)
# add handlers
updater.start_webhook(listen="0.0.0.0",
                      port=PORT,
                      url_path=TOKEN)
updater.bot.set_webhook("https://<appname>.herokuapp.com/" + TOKEN)
updater.idle()
```

I see its ok but it is only one aspect of the story. In programming we start a process which uses a socket and listens on it and sleeps. So the above code should sleep and do not do any work (which `updater.idle()` does) so this code just listens for request. But where does this `request` get handled?

Please describe in details so we can make the wiki of webhooks more understandable. thanks.

**Comment by amir3code** [comment]
@Eldinnie please answer my question.

**Comment by jh0ker** [comment]
@amir3code Look at https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/utils/webhookhandler.py and https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/updater.py#L325 if you want to understand more, but it's not something that belongs in the wiki since it's framework-internal and not exposed to the user
