### ISSUE TITLE
bot.setWebhook not setting allowed_updates

### ISSUE THREAD

**Issue by madl-ash** [python-telegram-bot/python-telegram-bot#941]
when i use `bot.setwebhook`,all parameters are sent as defined **but allowed_updates doesn't change**.
here is my code
### Steps to reproduce
```
hookurl = ....
certificate = open('....', 'rb')
timeout=None
max_connections=60
allowed_updates = ["message", "callback_query"]
setted = bot.setWebhook(hookurl, certificate=certificate, timeout=timeout,max_connections=max_connections, allowed_updates=allowed_updates)
webhook_info = bot.getWebhookInfo()
```
now if you check webhook_info,there is NO allowed_updates,meaning it is set to get all updates(according to the telegram docs)
`print(webhook_info.allowed_updates) ` this prints None
also,im using Django as web server

### My guess
i think the problem is with how allowed_updates is serialized,it is a array(list) and must be properly serialized before it is sent as a parameter

### Expected behaviour
allowed_updates should be set.
webhook_info.allowed_updates = ["message", "callback_query"]

### Actual behaviour
allowed_updates is not set for webhook
webhook_info.allowed_updates = None

### Configuration
**Operating System:**
Windows 10

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 9.0.0
certifi 2017.11.05
future 0.16.0
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

p.s : sorry for bad english

**Comment by jh0ker** [comment]
I did some basic testing which did not show the error

```python
>>> from telegram import Bot
>>> from os import environ
>>> bot = Bot(environ['TG_TOKEN'])
>>> hookurl = 'https://example.com/'
>>> allowed_updates = ["message", "callback_query"]
>>> print(bot.get_webhook_info())
{'url': '', 'has_custom_certificate': False, 'pending_update_count': 0}
>>> bot.set_webhook(hookurl, allowed_updates=allowed_updates)
True
>>> print(bot.get_webhook_info())
{'url': 'https://example.com/', 'has_custom_certificate': False, 'pending_update_count': 0, 'max_connections': 40, 'allowed_updates': ['message', 'callback_query']}
>>> bot.set_webhook(hookurl, allowed_updates=['message'])
True
>>> print(bot.get_webhook_info())
{'url': 'https://example.com/', 'has_custom_certificate': False, 'pending_update_count': 0, 'max_connections': 40, 'allowed_updates': ['message']}
```

@Eldinnie on the other hand said he could reproduce the bug... possibly a Telegram server bug, could be a good idea to try it again at a later date. Could also in some way be related to the other parameters you are passing.

**Comment by jh0ker** [comment]
I'm going to close this, if the issue persists please feel free to re-open it.
