### ISSUE TITLE
Add full name for user as a convenience method

### ISSUE THREAD

**Issue by graynk** [python-telegram-bot/python-telegram-bot#943]
I didn't find any issues about this, but it seems to me as a useful feature. Basically, I want to address my users by their full name, always. Right now I can only use User.name which return full name _only_ if no actual @username is provided. And so I have to use this snippet every time:
```
def get_name(user):
    name = user.first_name
    if user.last_name:
        name += ' ' + user.last_name
    return name
```
Why not add it as User.full_name?

**Comment by Eldinnie** [comment]
Hi,

I guess we never saw a need for it. You are welcome to make a PR for it.
See our [contributing guidelines](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/.github/CONTRIBUTING.rst) to get started.

**Comment by graynk** [comment]
Hi,

Just [made](https://github.com/python-telegram-bot/python-telegram-bot/pull/949) a PR
