### ISSUE TITLE
get_file_stream support

### ISSUE THREAD

**Issue by rexx0520** [python-telegram-bot/python-telegram-bot#944]
node-telegram-bot-api has added `getFileStream` method , which allows accessing the file stream without downloading it to a folder. It'll be useful.For example, changing a group photo from a photo uploaded by users.

**Comment by JosXa** [comment]
This is fairly easily done in python code. But I agree in that it is a very common question and it might make sense to abstract the functionality for our users as a convenience method...

**Comment by bomjacob** [comment]
You mean like downloading a file to a BytesIO object?
If so, this can already be done as so:
```
def document(bot, update):
    doc = update.effective_message.document
    file = bot.get_file(doc.file_id)
    with io.BytesIO() as content:
        file.download(out=content)
        do_something_with_content(content)
```
Though I agree that it could perhaps be simplified somewhat.
