### ISSUE TITLE
In test_jobqueue.py (maybe others), wait longer (but explicitly) for expected jobs to run

### ISSUE THREAD

**Issue by nmlorg** [python-telegram-bot/python-telegram-bot#957]
Hi, during my last review the [CI reported an error](https://travis-ci.org/python-telegram-bot/python-telegram-bot/jobs/322945105) in tests/test_jobqueue.py TestJobQueue test_error after scheduling a job to run after 20 ms and, after waiting 30 ms, seeing it hadn't run. One possibility is that the environment the tests are run in can't reliably resume execution in under 30 ms, and the two threads just ran out of order. If that's the case, would you guys be interested in changing some/all of those tests from:

```python
      def test_run_once(self, job_queue):
          job_queue.run_once(self.job_run_once, 0.01)
-         sleep(0.02)
          assert self.result == 1
```

to something like:

```python
      def test_run_once(self, job_queue):
          job_queue.run_once(self.job_run_once, 0.01)
+         assert self.job_ran.wait(10)
          assert self.result == 1
```

with:

```python
  class TestJobQueue(object):
      result = 0
      job_time = 0
+     job_ran = threading.Event()

      @pytest.fixture(autouse=True)
      def reset(self):
          self.result = 0
          self.job_time = 0
+         self.job_ran.clear()

      def job_run_once(self, bot, job):
          self.result += 1
+         self.job_ran.set()
```

which would cause the tests to wait explicitly until the job executes, but give up (and signal failure) after 10 seconds instead of just 10 ms?

**Comment by tsnoam** [comment]
@nmlorg 
That is a good idea. Would you like to send a PR for it?

**Comment by Ambro17** [comment]
The approach of having a threading.Event() does not work for tests that call the `job_run_once` more than one time. Because as per `Event.wait` behaviour all waits are started as soon as an event is `.set()`.
In those cases, as soon as the callback is executed the first time, it continues to try to validate the assertion (which fails because the callback was executed just 1 time, not `n` as expected)
Example:
```python
    def test_run_repeating(self, job_queue):
        job_queue.run_repeating(self.job_run_once, 0.02)
        # sleep(0.05)
        assert self.job_ran.wait(timeout=2)
        # As soon as job_run_once sets the flag, wait continues but job_run_once was called only once.
        assert self.result == 2
```

**Comment by jsmnbom** [comment]
@Ambro17 I haven't read too much into it but could a \[semiphore](https://docs.python.org/3/library/threading.html#threading.Semaphore) work?

**Comment by Ambro17** [comment]
I was looking into it an managed to write a preliminary version (which i don't like, but works)
```python
def job_run_many(self, bot, job):
    self.job_semaphore.release()
    self.result += 1

def test_run_repeating(self, job_queue):
    self.job_semaphore = threading.BoundedSemaphore(value=2)
    self.job_semaphore.acquire()
    self.job_semaphore.acquire()
    job_queue.run_repeating(self.job_run_many, 0.01)
    # Blocked until job_run_many releases the semaphore two times 
    self.job_semaphore.acquire()
    self.job_semaphore.acquire()
    assert self.result == 2
```
In my opinion, this adds too much complexity to the tests that should be simple to read. I will think of a better approach. Any suggestions? Maybe a non-blocking sleep function may help..

**Comment by Ambro17** [comment]
I think [freezegun](https://github.com/spulec/freezegun) would help the tests to be deterministic, no matter the execution environment.
@jsmnbom Do you think it is acceptable to include it on requirements_dev?

**Comment by jsmnbom** [comment]
I'm not sure why mocking the datetime module is something we need. Could you create a quick example, perhaps?

**Comment by Ambro17** [comment]
After thinking about threads, waits, semaphores, and seeing that some tests on job_queue check first if a job is not run, then sleep and check if it is run, i can honestly say that using freezegun seems the more reliable choice for me as semaphores will highly increase tests readibility.
This is a working _to-be-improved-if-approved_ example of my idea of refactor
```python
    def test_job_queue_nosleep_poc(self, bot):
        with freeze_time("2018-01-17") as frozen_time:
            # Setup
            job_queue = JobQueue(bot)
            job_queue.start()

            # Add scheduled job
            job_queue.run_once(self.job_run_once, 0.01)
            
            # Fake sleep function of 0.02 seconds.
            frozen_time.tick(delta=datetime.timedelta(seconds=0.01))
            
            # Force the jobqueue to run due jobs
            job_queue.tick()
            
            # Assert the job was run
            assert self.result == 1

            job_queue.stop()
```
modifying the tick timedelta you can check that if you tick with less seconds as the job interval, the job will not run and thus the test will fail (as it should).

Please advice if you think it's an acceptable trade-off to include a new dependency to avoid this non-deterministic behaviour on job_queue tests.
Thanks for your time

**Comment by Ambro17** [comment]
@jsmnbom any news on this? shall i open the pr with freezegun?

**Comment by jsmnbom** [comment]
Haven't gotten any feedback from the other devs yet, but since its only going to be a test time dependency that should be fine.
Most of the logic however should go in a pytest fixture as we currently do if possible (and if not possible, just a small helper func).

**Comment by emilydaitch** [comment]
did #1357 fix this? I've been poking around good-first-issue 's of a few projects for a while now and I happened to find this (I'm making a telegram bot). Should it be closed? The other pr is...

**Comment by Bibo-Joshi** [comment]
Closing as we switched to GitHub Actions. See comments on #1357
