### ISSUE TITLE
How to use messageQueue

### ISSUE THREAD

**Issue by Legend-of-Success** [python-telegram-bot/python-telegram-bot#958]
Hello :)

I am trying to find a method to avoid hitting telegram limits. By searching I reached to **messageQueue** module. But I don't know how can I use this module. Can anybody show me the usage in an example?

Thanks...

**Comment by evstratbg** [comment]
check [wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-flood-limits)

**Comment by prachik2** [comment]
I also have the same issue. please help if any finds
