### ISSUE TITLE
No possibility to add flags to RegexHandler

### ISSUE THREAD

**Issue by Endogen** [python-telegram-bot/python-telegram-bot#965]
### Steps to reproduce
1. Create a RegexHandler with pattern `^(UPDATE|RESTART|SHUTDOWN)$`
2. There is no way to "ignore case" in that pattern other then add also the lower-case words - which i don't want to do because in my case that blows up the code enormously

### Expected behaviour
I want to "ignore case" in that regex pattern. But there seems to be no useful way to achieve that. I would expect to be able to use flags with regex

### Actual behaviour
There is no way to achieve that. If the pattern consists of only one value (something like `^(UPDATE)$`) then i can use `(?i)^(UPDATE)$` to achieve what i want but that doesn't work with more then one value

### Configuration
**Operating System:**
macOS 10.13.2

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot = 9.0.0
python = 3.6.4

Python in general can use flags to indicate things like "ignore case" with:
```
p = re.compile('^(UPDATE|RESTART|SHUTDOWN)$', re.IGNORECASE)
```
But currently there seems to be no way to use flags with PTB

**Comment by Eldinnie** [comment]
Hi,

As you can see in our [documentation](https://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.regexhandler.html#telegram.ext.RegexHandler.pattern), you can either pass a `string` or a compiled `regex pattern` to RegexHandler.
This should solve you're issue

**Comment by Endogen** [comment]
Yep, indeed solved it. Cheers
