### ISSUE TITLE
JobQueue.jobs() is not thread safe

### ISSUE THREAD

**Issue by tsnoam** [python-telegram-bot/python-telegram-bot#968]
Direct usage of `PriorityQueue.queue` is not thread safe.
We should either remove support for `JobQueue.jobs()` (undesireable) or fix the issue.

Blocks #934

**Comment by Eldinnie** [comment]
For reference here aswell":
```
self.queue.mutex.acquire()
current_jobs =  tuple(job[1] for job in self.queue.queue if job)
self.queue.mutex.release()
return current_jobs```
