### ISSUE TITLE
Webhook broken pipe results in dispatcher stopping

### ISSUE THREAD

**Issue by yusufk** [python-telegram-bot/python-telegram-bot#969]
### Steps to reproduce
1.
` 
    updater = Updater(TOKEN)
    PORT = int(os.environ.get('PORT', '5000'))
    # add handlers
    updater.start_webhook(listen="0.0.0.0",
                          port=PORT,
                          url_path=TOKEN)
    updater.bot.set_webhook("https://home.co.za/" + TOKEN)
    dp = updater.dispatcher
    dp.add_error_handler(error)
    updater.idle()
`

### Expected behaviour
Bot should run continuously and be responsive.

### Actual behaviour
Bot becomes unresponsive after a random amount of time, usually a few hours.

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**
Linux Cappucino 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:50 UTC 2017 i686 athlon i686 GNU/Linux
python-telegram-bot 7.0.1
certifi 2017.07.27.1
future 0.16.0
Python 2.7.12 (default, Nov 20 2017, 18:23:56)  [GCC 5.4.0 20160609]

### Logs
https://pastebin.com/KbatbwHg

**Comment by tsnoam** [comment]
@yusufk 
We are unable to provide support for older versions of the library. Please upgrade to the latest version and if problem persist open a new issue.
