### ISSUE TITLE
Start bot without command start

### ISSUE THREAD

**Issue by MarcSky** [python-telegram-bot/python-telegram-bot#971]
Hey. Faced such a problem, when I make changes to the bot code, I need to restart it, but my users do not know about it. They click on the menu, but nothing happens, I have to tell them every time that I need to start the start command. Can I somehow avoid calling entry_points every time? How to make, so that users after rebooting the script continued to use the bot, as before? I try to set allow_reentry=True but its doesnt help me.
Thanx u.

**Comment by Eldinnie** [comment]
Hi,

At this moment the library does not persistence out of the box. It might be a comming feature, but for now it's up to the user to (re)store states.
