### ISSUE TITLE
Encapsulated HTML tags results in error

### ISSUE THREAD

**Issue by WilliamWCYoung** [python-telegram-bot/python-telegram-bot#972]
### Steps to reproduce
1. send_message with text that has an encapsulated message, e.g.  ```<b><a href="#">test</a></b>```

### Expected behaviour
It should send and show as a bold link

### Actual behaviour
Crashes with exception:
```
Traceback (most recent call last):
  File "send_message.py", line 33, in <module>
    reply_markup=reply_markup)
  File "/usr/lib/python3.6/site-packages/telegram/bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/telegram/bot.py", line 85, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 272, in post
    **urlopen_kwargs)
  File "/usr/lib/python3.6/site-packages/telegram/utils/request.py", line 210, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities in message text: expected end tag at byte offset 3
```

### Configuration
**Operating System:**
Linux 64-bit Manjaro

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 9.0.0
certifi 2017.07.27.1
future 0.16.0
Python 3.6.4 (default, Dec 23 2017, 19:07:07)  [GCC 7.2.1 20171128]

**Comment by tsnoam** [comment]
@WilliamWCYoung Can you please add to the report the exact parameters you've used with send_message()?

**Comment by WilliamWCYoung** [comment]
@tsnoam I've simplified it down, seems to throw with any tag:

```
bot.send_message(chat_id=...,
                 text="<b><i>foo</i></b>",
                 parse_mode=telegram.ParseMode.HTML)
```

**Comment by Eldinnie** [comment]
@WilliamWCYoung you can't use nested formatting.

**Comment by WilliamWCYoung** [comment]
@Eldinnie that's the conclusion I was reaching, I assume that's a restriction imposed by Telegram themselves? Closing.
