### ISSUE TITLE
File download freezes

### ISSUE THREAD

**Issue by nordorei** [python-telegram-bot/python-telegram-bot#973]
### Description
I'm trying to make a bot that downloads audio files that I send to it in telegram. My message handlers are good to go and work fine. There is just one issue when downloading audio from audio messages: It does not work at all.
I checked out the examples and code snippets and did exactly what they told (even copy/paste) but nothing happens anyway.

### Steps to reproduce
1. ``file_id = update.message.audio.file_id``

2. ``mp3_file = bot.get_file(file_id)``

3. ``mp3_file.download(custom_path='./audio/' + file_id + '.mp3')``

### Expected behaviour
Download the file into the given custom path

### Actual behaviour
Does nothing/freezes

### Configuration
**Operating System:**
macOS High Sierra 10.13.2

**Version of Python, python-telegram-bot & dependencies:**
* python-telegram-bot 9.0.0
* certifi 2017.11.05
* future 0.16.0
* Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:04:09)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

**Comment by evstratbg** [comment]
can you show your code and audio size

**Comment by Eldinnie** [comment]
Hi,

Can you please set your logging level to debug and paste the relevant logs?

**Comment by tsnoam** [comment]
@nordorei 
I'm closing the issue now. Once you have the logs ready feel free to reopen it and attach the logs.

**Comment by hpoleselo** [comment]
I used:

``` audio_file = context.bot.getFile(update.message.audio.file_id) ```

Referencing ```context``` before AND using camelCase function ```getFile```, i don't know if this is a version thing since this was too long ago but at least that works for me.
