### ISSUE TITLE
pip install from github

### ISSUE THREAD

**Issue by gavrilovks** [python-telegram-bot/python-telegram-bot#976]
### Steps to reproduce
pip install git+https://github.com/python-telegram-bot/python-telegram-bot.git

### Expected behaviour
install python-telegram-bot library directly from github

### Actual behaviour
error:
fatal: 'submodule' appears to be a git command, but we were not able to execute it. Maybe git-submodule is broken?
Command "git submodule update --init --recursive -q" failed with error code 128 in C:\Users\username\AppData\Local\Temp\pip-i0kwqt3f-build

### Configuration
**Operating System:**
Windows 10

**Version of Python, python-telegram-bot & dependencies:**
pip 9.0.1
Python 3.6.1

**Comment by tsnoam** [comment]
Unfortunately you can't install using `pip install git+...` mechanism.
See https://github.com/pypa/pip/issues/2705 for details.

**Comment by Eldinnie** [comment]
I've just tried this and it works fine for me...
