### ISSUE TITLE
getting channel post

### ISSUE THREAD

**Issue by adamvizly** [python-telegram-bot/python-telegram-bot#981]
### Steps to reproduce
1.if update.channel_post.photo:
            bot.get_file(file_id=update.channel_post.photo.file_id).download()

### Expected behaviour

I want when a specific channel post a photo my bot download that photo 
bot is a member of channel

### Actual behaviour

the if condition never become true even when channel post a photo

### Configuration
**Operating System:**
win10

**Version of Python, python-telegram-bot & dependencies:**
latest versions of all
``$ python -m telegram``

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup).
