### ISSUE TITLE
python-telegram-bot can not use in China as urllib3 is stupid

### ISSUE THREAD

**Issue by songluyi** [python-telegram-bot/python-telegram-bot#988]
## Get away from urllib3 please
All problems like

>  telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): 

is beacuse of urllib3 is stupid and can not access youtube.com twitter ..etc even you use global agent with shadowsocks to cross GFW.But when I use  **requests** or something else, It's OK.
So Is anybody  kind can change this f**k wheel like urllib3 to **requests** for human.

**Comment by tsnoam** [comment]
Hello,
Offensive language is not accepted here.
