### ISSUE TITLE
getChatMembersCount method missing in this wrapper

### ISSUE THREAD

**Issue by pnmartinez** [python-telegram-bot/python-telegram-bot#990]
Hi everyone,

I'm wondering if there's any way to use the [getChatMembersCount method](https://core.telegram.org/bots/api#getchatmemberscount) via python-telegram-bot.

Thanks in advance!

**Comment by Eldinnie** [comment]
As far as I'm aware this method does not exist in the [bot api](https://core.telegram.org/bots/api) Since this is a wrapper around that api it does not have that method.

**Comment by Eldinnie** [comment]
Hi @pnmartinez 

I'm sorry I was mistaken. I was thinking you were refering to a method in the tlscheme for clients.
You are right this method is in the bot api, and thus available in our bot with it's [method in Telegram.Bot](http://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.get_chat_members_count).
I'm sorry I mistook you're request and closed it prematurely, although by the issue template you're question was still not suitable for an issue but a usage question that belongs in our [telegram chat](https://t.me/pythontelegrambotgroup).

Assuming this answers you're question I;m keeping this closed, but no longer locked ;-)
