### ISSUE TITLE
smtp's module `send_messages` method does not acquire lock

### ISSUE THREAD

**Issue by sobolevn** [python-telegram-bot/python-telegram-bot#992]
### Steps to reproduce
1. Create a bot with `updater`
2. Run `updater.start_polling(); updater.idle()`
3. Try to send an email via `smtp` module https://docs.python.org/3/library/smtplib.html#module-smtplib

### Expected behaviour
An email should be sent.

### Actual behaviour
Application freezes on this line: `with self._lock:`. From here:

```python
    def send_messages(self, email_messages):
        """
        Sends one or more EmailMessage objects and returns the number of email
        messages sent.
        """
        if not email_messages:
            return
        with self._lock:
            new_conn_created = self.open()
            if not self.connection or new_conn_created is None:
                # We failed silently on open().
                # Trying to send would be pointless.
                return
            num_sent = 0
            for message in email_messages:
                sent = self._send(message)
                if sent:
                    num_sent += 1
            if new_conn_created:
                self.close()
        return num_sent
```

### Configuration
**Operating System:** macos

**Version of Python, python-telegram-bot & dependencies:**

python: 3.6.4
python-telegram-bot: 9.0.0

**Comment by Eldinnie** [comment]
Hi,

With the info you provided it's impossible to determine if there's actually something wrong with the library's code. Please provide a minimal (not) working example and the logs put out when setting the log-level to `DEBUG` so we can see if there's a problem occuring on our library.

**Comment by jh0ker** [comment]
@sobolevn Keep in mind that updater.idle is blocking

**Comment by sobolevn** [comment]
Yeap, sorry. That was not your fault indeed.
