### ISSUE TITLE
Custom reply keyboard (ReplyKeyboardMarkup) not shown in Telegram X for iOS

### ISSUE THREAD

**Issue by PkAIR** [python-telegram-bot/python-telegram-bot#993]
### Code snippet:

menu_keyboard = [['MenuItem1'],
                 ['MenuItem2']]
menu_markup = ReplyKeyboardMarkup(menu_keyboard, one_time_keyboard=True, resize_keyboard=True)

...

def display_start(bot, update):
    update.message.reply_text('Some text here', reply_markup=menu_markup)

### Expected behavior

Custom keyboard should be visible in Telegram X on iOS

### Actual behavior

Basic (alphanumeric keyboard) can be seen.

### Configuration

iOS 11.2.5, iOS 11.3

**Version of Python, python-telegram-bot & dependencies:**

Python 3.6.3, python-telegram-bot 9.0.0

Note: With ordinary telegram for both iOS (11.2.5 and 11.3) keyboard is shown flawlessly.

**Comment by matiniamirhossein** [comment]
I tested this once.

Code snippet:
```
import telegram
from telegram import ReplyKeyboardMarkup

bot = telegram.Bot('<token>')

menu_keyboard = [['MenuItem1'], ['MenuItem2']]
menu_markup = ReplyKeyboardMarkup(menu_keyboard, one_time_keyboard=True, resize_keyboard=True)

bot.send_message(chat_id=<chat_id>, text='Some text here', reply_markup=menu_markup)
```

The menu works pretty fine. (Tested with telegram X on iPhone 7 on iOS 11.2.5)

![photo_2018-02-11_00-33-37](https://user-images.githubusercontent.com/27870951/36066671-38d1ac06-0ec3-11e8-8fd9-d303b6e8eec9.jpg)


Also please note that if there is a problem with Telegram X and as you say it's shown **flawlessly** in the original app, then there is **no problem with this library**.

Have a good day.

**Comment by tsnoam** [comment]
As @matiniamirhossein had shown the problem is with the client application. Nothing we can do on ptb to help.
You can contact Telegram's bot support.
