### ISSUE TITLE
White spaces in message sent by send_message() function.

### ISSUE THREAD

**Issue by rfenzo** [python-telegram-bot/python-telegram-bot#997]
Hello, first of all, thank you for this package, its very usefull and time saving. 

I'm having some trouble trying to get the messages sent by the bot well formatted, here is a quick example.

### Steps to reproduce
1. prepare a multiple lines message, like: 
```
text = """
Hello
There
"""
```

2. Send text with `send_message()` function

### Expected behaviour
I should receive the text

```
Hello
There
```
on telegram

### Actual behaviour
I actually get:

```
Hello
         There
```

### Configuration
**Operating System:**
ubuntu 16.04

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
python-telegram-bot 9.0.0
certifi 2018.01.18
future 0.16.0
python 3.5.2

**Comment by jh0ker** [comment]
@rfenzo With multiline strings, python doesn't remove the trailing spaces in each line so you have to remove all trailing spaces inside the multiline string

**Comment by rfenzo** [comment]
Oh, I see now. Solved the problem doing string concatenation. Thank you!
