### ISSUE TITLE
cant send image to channel

### ISSUE THREAD

**Issue by alirezakhosraviyan** [python-telegram-bot/python-telegram-bot#998]
how to send photo to channel ?
i can send text message but cant send image. i got an error that cant parse chat_id with @ symbol!

bot.send_photo(photo=None, caption='testets', reply_markup=InlineKeyboardMarkup(keys),
                       chat_id='@test', )

**Comment by Eldinnie** [comment]
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup). Or (if you can't erach our group) our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot)
